import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory Limits

universe u v w

/-
Domain-style sampling for Definition 18.17.1:
- primary domain: global generation and global presentations of sheaves of modules;
- inspected owner declarations:
  `SheafOfModules.free`,
  `SheafOfModules.GeneratingSections`,
  `SheafOfModules.GeneratingSections.IsFiniteType`,
  `SheafOfModules.Presentation`;
- owner abstractions:
  `free` for free models,
  `GeneratingSections` for global generators,
  and `Presentation` for global presentations;
- primitive data: isomorphisms with free sheaves, generating families of global sections,
  epimorphisms from `free (ULift (Fin r))`, and presentations by free sheaves;
- derived API: the source-facing global rank-`r` and finite global generation predicates built
  from those owners.

Layer triage:
- `source-facing`: freeness, finite freeness, “generated by `r` global sections”, “finitely
  globally generated”, and “has finite global presentation”;
- `core/canonical`: `free`, `GeneratingSections`, and `Presentation`;
- `bridge/view`: the source-facing predicates `IsGeneratedBy` and `IsFiniteGloballyGenerated`
  relating the textbook wording to the owner data above.

The exact duplicate wrapper predicates around `GeneratingSections` and `Presentation` are therefore
removed below in favor of `Nonempty ℱ.GeneratingSections`, `Nonempty ℱ.Presentation`, and
`Nonempty {P : ℱ.Presentation // P.IsFinite}`. For the new source-facing content in parts (4) and
(5), the public layer is refined to the short chapter-style owners `IsGeneratedBy ℱ r` and
`IsFiniteGloballyGenerated ℱ`, rather than exposing subtype and `ULift` bookkeeping directly.
-/
namespace SheafOfModules

variable {C : Type u} [Category.{v} C] {J : GrothendieckTopology C}
variable {𝒪 : Sheaf J RingCat.{w}}
variable [HasWeakSheafify J AddCommGrpCat.{w}]
variable [J.WEqualsLocallyBijective AddCommGrpCat.{w}]
variable [J.HasSheafCompose (forget₂ RingCat.{w} AddCommGrpCat.{w})]
variable (ℱ : SheafOfModules.{w} 𝒪)

/-- Definition 18.17.1 (1): a sheaf of `\mathcal O`-modules is free if it is isomorphic to a
free sheaf `\bigoplus_{i \in I} \mathcal O`. -/
class IsFree (ℱ : SheafOfModules.{w} 𝒪) : Prop where
  exists_iso_free : ∃ I : Type w, Nonempty (ℱ ≅ free I)

/-- Definition 18.17.1 (2): a sheaf of `\mathcal O`-modules is finite free if it is isomorphic to
a finite coproduct of copies of `\mathcal O`. -/
class IsFiniteFree (ℱ : SheafOfModules.{w} 𝒪) : Prop where
  exists_iso_free :
    ∃ I : Type w, Finite I ∧ Nonempty (ℱ ≅ free I)

/- Definition 18.17.1 (3): a sheaf of `\mathcal O`-modules is generated by global sections iff it
admits a family of generating sections, i.e. iff `Nonempty ℱ.GeneratingSections`. -/
#check (Nonempty ℱ.GeneratingSections)

/- Companion recall: `ℱ.GeneratingSections` is the canonical owner for a chosen family of
generating global sections. -/
recall SheafOfModules.GeneratingSections

/-- Definition 18.17.1 (4): a sheaf of `\mathcal O`-modules is generated by `r` global sections
if it admits an epimorphism `\mathcal O^{\oplus r} \to \mathcal F`. -/
class IsGeneratedBy (ℱ : SheafOfModules.{w} 𝒪) (r : ℕ) : Prop where
  exists_epi :
    ∃ π : free (ULift.{w} (Fin r)) ⟶ ℱ, Epi π

/-- Helper for Definition 18.17.1: the tautological sections of a free sheaf recover the identity
morphism. -/
lemma free_tautological_sections_symm (I : Type w) :
    (free (R := 𝒪) I).freeHomEquiv.symm (freeSection (R := 𝒪)) =
      𝟙 (free (R := 𝒪) I) := by
  -- Compare morphisms after applying `freeHomEquiv`; on basis elements both sides give
  -- the tautological section.
  apply (free (R := 𝒪) I).freeHomEquiv.injective
  ext i
  simp

/-- Helper for Definition 18.17.1: the tautological sections on a free sheaf form a generating
family. -/
lemma free_tautological_sections_epi (I : Type w) :
    Epi ((free (R := 𝒪) I).freeHomEquiv.symm (freeSection (R := 𝒪))) := by
  -- After identifying the universal morphism with the identity, epimorphicity is immediate.
  rw [free_tautological_sections_symm (𝒪 := 𝒪) I]
  infer_instance

/-- Helper for Definition 18.17.1: a free sheaf is generated by its tautological basis sections. -/
lemma nonempty_generatingSections_free (I : Type w) :
    Nonempty (free I : SheafOfModules.{w} 𝒪).GeneratingSections := by
  -- The basis sections give the required generating family on `free I`.
  refine ⟨{ I := I, s := freeSection (R := 𝒪), epi := free_tautological_sections_epi (𝒪 := 𝒪) I }⟩

/-- Helper for Definition 18.17.1: an epimorphism out of a free sheaf produces generating global
sections on the target. -/
lemma nonempty_generatingSections_of_epi_free {I : Type w} {ℱ : SheafOfModules.{w} 𝒪}
    (π : free I ⟶ ℱ) [Epi π] :
    Nonempty ℱ.GeneratingSections := by
  -- Push the tautological generators of the free source forward along the epimorphism.
  obtain ⟨σ⟩ := nonempty_generatingSections_free (𝒪 := 𝒪) I
  exact ⟨σ.ofEpi π⟩

/-- Helper for Definition 18.17.1: reindexing a generating family by an equivalence with
`ULift (Fin r)` yields generation by `r` global sections. -/
lemma isGeneratedBy_of_generatingSections_equiv_ulift_fin
    {ℱ : SheafOfModules.{w} 𝒪} {σ : ℱ.GeneratingSections} {r : ℕ}
    (e : σ.I ≃ ULift.{w} (Fin r)) :
    IsGeneratedBy ℱ r := by
  -- Compose the chosen epimorphism `free σ.I ⟶ ℱ` with the reindexing isomorphism on free sheaves.
  let fIso : free (ULift.{w} (Fin r)) ≅ free σ.I :=
    (freeFunctor (R := 𝒪)).mapIso (Equiv.toIso e.symm)
  let _ : Epi fIso.hom := inferInstance
  let _ : Epi (fIso.hom ≫ σ.π) := epi_comp fIso.hom σ.π
  exact ⟨fIso.hom ≫ σ.π, inferInstance⟩

/-- Helper for Definition 18.17.1: every finite index type can be reindexed by `ULift (Fin r)` for
some `r`. -/
lemma equiv_ulift_fin_of_finite (I : Type w) [Finite I] :
    ∃ r : ℕ, Nonempty (I ≃ ULift.{w} (Fin r)) := by
  classical
  -- First identify `I` with a finite ordinal, then lift the ordinal into the target universe.
  obtain ⟨r, ⟨e⟩⟩ := Finite.exists_equiv_fin I
  exact ⟨r, ⟨e.trans Equiv.ulift.symm⟩⟩

/-- A generating family indexed by `r` elements is equivalently an epimorphism
`\mathcal O^{\oplus r} \to \mathcal F`. -/
theorem isGeneratedBy_iff_nonempty_generatingSections_equiv_fin
    (ℱ : SheafOfModules.{w} 𝒪) (r : ℕ) :
    IsGeneratedBy ℱ r ↔
      Nonempty {σ : ℱ.GeneratingSections // Nonempty (σ.I ≃ ULift.{w} (Fin r))} := by
  constructor
  · intro h
    -- An epimorphism from `free (ULift (Fin r))` gives generators indexed by that same type.
    rcases h.exists_epi with ⟨π, hπ⟩
    let _ : Epi π := hπ
    let σ : (free (ULift.{w} (Fin r)) : SheafOfModules.{w} 𝒪).GeneratingSections :=
      { I := ULift.{w} (Fin r)
        s := freeSection (R := 𝒪)
        epi := free_tautological_sections_epi (𝒪 := 𝒪) (ULift.{w} (Fin r)) }
    exact ⟨⟨σ.ofEpi π, ⟨Equiv.refl _⟩⟩⟩
  · rintro ⟨σ, ⟨e⟩⟩
    -- Reindex the chosen generating family along the prescribed equivalence.
    exact isGeneratedBy_of_generatingSections_equiv_ulift_fin (𝒪 := 𝒪) (σ := σ) e

/-- Definition 18.17.1 (5): a sheaf of `\mathcal O`-modules is finitely globally generated if it
is generated by `r` global sections for some `r`. -/
class IsFiniteGloballyGenerated (ℱ : SheafOfModules.{w} 𝒪) : Prop where
  exists_num : ∃ r : ℕ, IsGeneratedBy ℱ r

/-- A sheaf is finitely globally generated iff it admits a finite-type family of generating
sections. -/
theorem isFiniteGloballyGenerated_iff_nonempty_finiteGeneratingSections
    (ℱ : SheafOfModules.{w} 𝒪) :
    IsFiniteGloballyGenerated ℱ ↔
      Nonempty {σ : ℱ.GeneratingSections // σ.IsFiniteType} := by
  constructor
  · intro h
    -- A generating family indexed by `ULift (Fin r)` is finite, so the corresponding
    -- `GeneratingSections` witness is finite type.
    rcases h.exists_num with ⟨r, hr⟩
    rcases (isGeneratedBy_iff_nonempty_generatingSections_equiv_fin (𝒪 := 𝒪) ℱ r).mp hr with
      ⟨σ, ⟨e⟩⟩
    let _ : Finite σ.I := Finite.of_equiv (ULift.{w} (Fin r)) e.symm
    exact ⟨⟨σ, { finite := inferInstance }⟩⟩
  · rintro ⟨σ, hσ⟩
    let _ : σ.IsFiniteType := hσ
    -- Finite index types can be reindexed by some `ULift (Fin r)`.
    rcases equiv_ulift_fin_of_finite σ.I with ⟨r, ⟨e⟩⟩
    exact ⟨⟨r, isGeneratedBy_of_generatingSections_equiv_ulift_fin (𝒪 := 𝒪) (σ := σ) e⟩⟩

/- Definition 18.17.1 (6): a sheaf of `\mathcal O`-modules has a global presentation iff it
admits one, i.e. iff `Nonempty ℱ.Presentation`. -/
#check (Nonempty ℱ.Presentation)

/- Companion recall: `ℱ.Presentation` is the canonical owner for a chosen global presentation. -/
recall SheafOfModules.Presentation

/- Definition 18.17.1 (7): a sheaf of `\mathcal O`-modules has a global finite presentation iff
it admits a finite global presentation, i.e. iff
`Nonempty {P : ℱ.Presentation // P.IsFinite}`. -/
#check (Nonempty {P : ℱ.Presentation // P.IsFinite})

/-- A free sheaf of modules is free. -/
instance free_isFree (I : Type w) : IsFree (free I : SheafOfModules.{w} 𝒪) := by
  -- The free sheaf is isomorphic to itself.
  exact ⟨I, ⟨Iso.refl _⟩⟩

/-- A free sheaf on a finite index type is finite free. -/
instance free_isFiniteFree (I : Type w) [Finite I] :
    IsFiniteFree (free I : SheafOfModules.{w} 𝒪) := by
  -- The identity isomorphism gives a finite-free witness with the given finite index type.
  exact ⟨I, inferInstance, ⟨Iso.refl _⟩⟩

/-- A finite free sheaf is free. -/
instance isFiniteFree_to_isFree (ℱ : SheafOfModules.{w} 𝒪) [IsFiniteFree ℱ] :
    IsFree ℱ := by
  -- Forget the finiteness part of the finite-free witness.
  obtain ⟨I, -, hI⟩ := IsFiniteFree.exists_iso_free (ℱ := ℱ)
  exact ⟨I, hI⟩

/-- A free sheaf is globally generated by its tautological basis sections. -/
instance free_generatingSections (I : Type w) :
    Nonempty (free I : SheafOfModules.{w} 𝒪).GeneratingSections :=
  nonempty_generatingSections_free (𝒪 := 𝒪) I

/-- The free sheaf `\mathcal O^{\oplus r}` is generated by `r` global sections. -/
instance free_fin_isGeneratedBy (r : ℕ) :
    IsGeneratedBy (free (ULift.{w} (Fin r)) : SheafOfModules.{w} 𝒪) r := by
  -- The identity map is already an epimorphism from `\mathcal O^{\oplus r}` onto itself.
  refine ⟨𝟙 _, inferInstance⟩

/-- Being generated by `r` global sections implies being generated by global sections. -/
theorem generatingSections_of_isGeneratedBy
    (ℱ : SheafOfModules.{w} 𝒪) (r : ℕ) (_ : IsGeneratedBy ℱ r) :
    Nonempty ℱ.GeneratingSections := by
  rename_i h
  -- Any epimorphism from a free sheaf pushes forward the tautological generators.
  rcases h.exists_epi with ⟨π, hπ⟩
  let _ : Epi π := hπ
  exact nonempty_generatingSections_of_epi_free (𝒪 := 𝒪) π

/-- Being generated by `r` global sections implies finite global generation. -/
theorem isFiniteGloballyGenerated_of_isGeneratedBy
    (ℱ : SheafOfModules.{w} 𝒪) (r : ℕ) (_ : IsGeneratedBy ℱ r) :
    IsFiniteGloballyGenerated ℱ := by
  rename_i h
  -- Keep the given rank as the finite global generation witness.
  exact ⟨⟨r, h⟩⟩

/-- A finitely globally generated sheaf is generated by global sections. -/
instance isFiniteGloballyGenerated_to_generatingSections
    (ℱ : SheafOfModules.{w} 𝒪) [IsFiniteGloballyGenerated ℱ] :
    Nonempty ℱ.GeneratingSections := by
  -- Extract a finite rank witness and forget the finiteness afterwards.
  obtain ⟨r, hr⟩ := IsFiniteGloballyGenerated.exists_num (ℱ := ℱ)
  exact generatingSections_of_isGeneratedBy (𝒪 := 𝒪) ℱ r hr

/-- Helper for Definition 18.17.1: the free sheaf on the empty type yields an initial object of
`SheafOfModules`. -/
theorem sheafOfModules_hasInitial_of_free_empty :
    HasInitial (SheafOfModules.{w} 𝒪) := by
  let X : SheafOfModules.{w} 𝒪 := free (ULift.{w, 0} PEmpty)
  -- Morphisms out of `free (ULift PEmpty)` are unique because the indexing type is empty.
  let _ : ∀ M : SheafOfModules.{w} 𝒪, Nonempty (X ⟶ M) := fun M ↦
    ⟨M.freeHomEquiv.symm (fun i : ULift.{w, 0} PEmpty ↦ PEmpty.elim i.down)⟩
  let _ : ∀ M : SheafOfModules.{w} 𝒪, Subsingleton (X ⟶ M) := fun M ↦
    ⟨fun f g ↦ M.freeHomEquiv.injective (by
      funext i
      exact PEmpty.elim i.down)⟩
  exact hasInitial_of_unique X

/-- Helper for Definition 18.17.1: the initial object above is a zero object since
`SheafOfModules` has zero morphisms. -/
theorem sheafOfModules_hasZeroObject_of_free_empty :
    HasZeroObject (SheafOfModules.{w} 𝒪) := by
  let _ : HasInitial (SheafOfModules.{w} 𝒪) :=
    sheafOfModules_hasInitial_of_free_empty (𝒪 := 𝒪)
  exact hasZeroObject_of_hasInitial_object

/-- Helper for Definition 18.17.1: the chosen initial object is generated by one trivial global
section. -/
lemma nonempty_generatingSections_initial_equiv_punit :
    Nonempty
      {σ : (⊥_ (SheafOfModules.{w} 𝒪)).GeneratingSections //
        Nonempty (σ.I ≃ ULift.{w, 0} Unit)} := by
  let π : (free (ULift.{w, 0} Unit) : SheafOfModules.{w} 𝒪) ⟶
      ⊥_ (SheafOfModules.{w} 𝒪) := 0
  let _ : Epi π := inferInstance
  let σ : (free (ULift.{w, 0} Unit) : SheafOfModules.{w} 𝒪).GeneratingSections :=
    { I := ULift.{w, 0} Unit
      s := freeSection (R := 𝒪)
      epi := free_tautological_sections_epi (𝒪 := 𝒪) (ULift.{w, 0} Unit) }
  -- Push the tautological generator forward to the initial object.
  have hσ : Nonempty ((σ.ofEpi π).I ≃ ULift.{w, 0} Unit) := by
    change Nonempty (σ.I ≃ ULift.{w, 0} Unit)
    exact ⟨Equiv.refl _⟩
  exact ⟨⟨σ.ofEpi π, hσ⟩⟩

/-- Helper for Definition 18.17.1: the kernel of the identity on a free sheaf is generated by one
trivial global section. -/
lemma nonempty_generatingSections_kernel_id_equiv_punit (I : Type w) :
    Nonempty
      {σ : (kernel (𝟙 (free I : SheafOfModules.{w} 𝒪))).GeneratingSections //
        Nonempty (σ.I ≃ ULift.{w, 0} Unit)} := by
  let _ : HasInitial (SheafOfModules.{w} 𝒪) :=
    sheafOfModules_hasInitial_of_free_empty (𝒪 := 𝒪)
  let _ : HasZeroObject (SheafOfModules.{w} 𝒪) :=
    sheafOfModules_hasZeroObject_of_free_empty (𝒪 := 𝒪)
  rcases nonempty_generatingSections_initial_equiv_punit (𝒪 := 𝒪) with ⟨⟨σ, hσ⟩⟩
  let e : (⊥_ (SheafOfModules.{w} 𝒪)) ≅
      kernel (𝟙 (free I : SheafOfModules.{w} 𝒪)) :=
    (HasZeroObject.zeroIsoInitial).symm.trans
      (kernel.ofMono (𝟙 (free I : SheafOfModules.{w} 𝒪))).symm
  -- Transport the generating family along the identification of the identity kernel with the
  -- zero object.
  exact ⟨⟨(SheafOfModules.GeneratingSections.equivOfIso e) σ, hσ⟩⟩

/-- A free sheaf has a global presentation. -/
instance free_presentation (I : Type w) :
    Nonempty (free I : SheafOfModules.{w} 𝒪).Presentation := by
  rcases nonempty_generatingSections_kernel_id_equiv_punit (𝒪 := 𝒪) I with ⟨⟨ρ, -⟩⟩
  let σ : (free I : SheafOfModules.{w} 𝒪).GeneratingSections :=
    { I := I
      s := freeSection (R := 𝒪)
      epi := free_tautological_sections_epi (𝒪 := 𝒪) I }
  let e : kernel σ.π ≅ kernel (𝟙 (free I : SheafOfModules.{w} 𝒪)) :=
    kernel.congr σ.π (𝟙 (free I : SheafOfModules.{w} 𝒪))
      (free_tautological_sections_symm (𝒪 := 𝒪) I)
  let ρ' : (kernel σ.π).GeneratingSections :=
    (SheafOfModules.GeneratingSections.equivOfIso e).symm ρ
  -- The tautological generators together with generators of the identity kernel form a presentation.
  exact ⟨{ generators := σ, relations := ρ' }⟩

/-- A finite free sheaf has a finite global presentation. -/
instance free_finitePresentation (I : Type w) [Finite I] :
    Nonempty {P : (free I : SheafOfModules.{w} 𝒪).Presentation // P.IsFinite} := by
  rcases nonempty_generatingSections_kernel_id_equiv_punit (𝒪 := 𝒪) I with ⟨⟨ρ, ⟨eρ⟩⟩⟩
  let σ : (free I : SheafOfModules.{w} 𝒪).GeneratingSections :=
    { I := I
      s := freeSection (R := 𝒪)
      epi := free_tautological_sections_epi (𝒪 := 𝒪) I }
  let e : kernel σ.π ≅ kernel (𝟙 (free I : SheafOfModules.{w} 𝒪)) :=
    kernel.congr σ.π (𝟙 (free I : SheafOfModules.{w} 𝒪))
      (free_tautological_sections_symm (𝒪 := 𝒪) I)
  let ρ' : (kernel σ.π).GeneratingSections :=
    (SheafOfModules.GeneratingSections.equivOfIso e).symm ρ
  let P : (free I : SheafOfModules.{w} 𝒪).Presentation := { generators := σ, relations := ρ' }
  have hρfinite : Finite ρ.I := Finite.of_equiv (ULift.{w, 0} Unit) eρ.symm
  have hP : P.IsFinite := by
    refine { isFiniteType_generators := ?_, finite_relations := ?_ }
    · change σ.IsFiniteType
      exact { finite := inferInstance }
    · change Finite ρ'.I
      simpa [ρ'] using hρfinite
  -- The chosen presentation has finitely many generators and relations.
  exact ⟨⟨P, hP⟩⟩

/-- A finite global presentation is, in particular, a global presentation. -/
instance finitePresentation_to_presentation
    (ℱ : SheafOfModules.{w} 𝒪) [Nonempty {P : ℱ.Presentation // P.IsFinite}] :
    Nonempty ℱ.Presentation := by
  classical
  -- Forget the finiteness witness from the chosen finite presentation.
  rcases (inferInstance : Nonempty {P : ℱ.Presentation // P.IsFinite}) with ⟨P⟩
  exact ⟨P.1⟩

end SheafOfModules
