import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open Subgroup (closure normalClosure)

section

variable {X : Type u} {F : Type v} [Group F]

namespace FreeGroupBasis

variable (basis : FreeGroupBasis X F)

local notation "Gp[" Y "]" => closure (basis '' Y)

-- Layer triage:
-- `source-facing`: a free group `F` equipped with a chosen basis `basis : FreeGroupBasis X F`,
-- basis subsets `Y, Z : Set X`, relator sets `P, Q : Set F` lying in the generated subgroups
-- `Gp(Y)` and `Gp(Z)`, and the existence of an intermediate relator set `M` supported on
-- `Y ∩ Z`.
-- `core/canonical`: the owner namespace `FreeGroupBasis`, together with `Subgroup.closure` and
-- `Subgroup.normalClosure`.
-- `bridge/view`: the source subgroup notation `Gp(Y)` is rendered by the local notation `Gp[Y]`
-- backed by the canonical owner `closure (basis '' Y)`, while the normal closure remains the
-- owner expression `normalClosure P`.
-- Domain sampling:
-- 1. `FreeGroupBasis X F` is the canonical owner for a free group together with a specified
--    basis, and nearby basis-dependent Magnus theorems already live in `namespace FreeGroupBasis`.
-- 2. `Subgroup.closure` is the canonical owner for the subgroup generated by a subset.
-- 3. `Subgroup.normalClosure` is the canonical owner for the normal closure of a subset.
-- Primitive vs. derived:
-- the primitive data are the chosen basis, the two basis subsets, and the relator sets `P` and
-- `Q`; the generated subgroups and normal closures are derived canonically from those data, so no
-- extra wrapper around the three subset conditions is needed.

-- Proof sketch: reduce to the case where `Y ∪ Z` is the whole basis and `Q` is a singleton
-- cyclically reduced word. Fill that word by a simple van Kampen diagram over the relators `P`,
-- delete interior edges, and let `M` be the set of boundary labels of the resulting faces. Those
-- boundary labels lie in the subgroup generated by `Y ∩ Z`, remain in the normal closure of `P`,
-- and their normal closure contains the original set `Q`.
/-- Proposition 3-9-3: if `P` lies in the subgroup generated by the basis subset `Y`, `Q` lies in
the subgroup generated by `Z`, and `Q` is contained in the normal closure of `P`, then there is a
set `M` in the subgroup generated by `Y ∩ Z` which still lies in the normal closure of `P` and
whose normal closure contains `Q`. -/
theorem exists_intersection_relator_set_of_subset_normalClosure
    (Y Z : Set X) (P Q : Set F)
    (hP : P ⊆ Gp[Y])
    (hQ : Q ⊆ Gp[Z])
    (hQncl : Q ⊆ normalClosure P) :
    ∃ M : Set F,
      M ⊆ Gp[Y ∩ Z] ∧
        M ⊆ normalClosure P ∧
        Q ⊆ normalClosure M := sorry

end FreeGroupBasis

end
