import AchimKlenkeLean.Items.Chap05.Definition_5_1
import AchimKlenkeLean.Items.Chap05.Definition_5_12
import AchimKlenkeLean.Items.Chap05.Definition_5_22
import AchimKlenkeLean.Items.Chap05.Definition_5_25
import AchimKlenkeLean.Items.Chap05.Definition_5_33
import AchimKlenkeLean.Items.Chap05.Example_5_15
import AchimKlenkeLean.Items.Chap05.Example_5_21
import AchimKlenkeLean.Items.Chap05.Example_5_24
import AchimKlenkeLean.Items.Chap05.Example_5_9
import AchimKlenkeLean.Items.Chap05.Exercise_5_1_1
import AchimKlenkeLean.Items.Chap05.Exercise_5_1_2
import AchimKlenkeLean.Items.Chap05.Exercise_5_1_3
import AchimKlenkeLean.Items.Chap05.Exercise_5_1_4
import AchimKlenkeLean.Items.Chap05.Exercise_5_2_1
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_1
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_2
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_3
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_4
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_5
import AchimKlenkeLean.Items.Chap05.Exercise_5_3_6
import AchimKlenkeLean.Items.Chap05.Exercise_5_4_1
import AchimKlenkeLean.Items.Chap05.Exercise_5_5_1
import AchimKlenkeLean.Items.Chap05.Exercise_5_5_2
import AchimKlenkeLean.Items.Chap05.Lemma_5_18
import AchimKlenkeLean.Items.Chap05.Lemma_5_19
import AchimKlenkeLean.Items.Chap05.Lemma_5_20
import AchimKlenkeLean.Items.Chap05.Lemma_5_26
import AchimKlenkeLean.Items.Chap05.Remark_5_13
import AchimKlenkeLean.Items.Chap05.Remark_5_2
import AchimKlenkeLean.Items.Chap05.Remark_5_31
import AchimKlenkeLean.Items.Chap05.Theorem_5_10
import AchimKlenkeLean.Items.Chap05.Theorem_5_11
import AchimKlenkeLean.Items.Chap05.Theorem_5_14
import AchimKlenkeLean.Items.Chap05.Theorem_5_16
import AchimKlenkeLean.Items.Chap05.Theorem_5_17
import AchimKlenkeLean.Items.Chap05.Theorem_5_23
import AchimKlenkeLean.Items.Chap05.Theorem_5_27
import AchimKlenkeLean.Items.Chap05.Theorem_5_28
import AchimKlenkeLean.Items.Chap05.Theorem_5_29
import AchimKlenkeLean.Items.Chap05.Theorem_5_3
import AchimKlenkeLean.Items.Chap05.Theorem_5_30
import AchimKlenkeLean.Items.Chap05.Theorem_5_32
import AchimKlenkeLean.Items.Chap05.Theorem_5_34
import AchimKlenkeLean.Items.Chap05.Theorem_5_35
import AchimKlenkeLean.Items.Chap05.Theorem_5_36
import AchimKlenkeLean.Items.Chap05.Theorem_5_4
import AchimKlenkeLean.Items.Chap05.Theorem_5_5
import AchimKlenkeLean.Items.Chap05.Theorem_5_6
import AchimKlenkeLean.Items.Chap05.Theorem_5_7
import AchimKlenkeLean.Items.Chap05.Theorem_5_8
