import Mathlib
import stacks_project.Chap06.Extension_by_zero_by_the_initial_object
import stacks_project.Chap12.Aux_12_20_2_1

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory CategoryTheory.Limits TopCat TopologicalSpace

noncomputable section

universe u

section

variable {X : TopCat.{u}}
variable [HasWeakSheafify (Opens.grothendieckTopology X) AddCommGrpCat.{u}]

/-
Domain-style sampling for Lemma 20.20.3:
- primary domain: abelian sheaves on a topological space, their generation by finite sums of
  extension-by-zero constant sheaves, and finite filtrations by subobjects with controlled
  subquotients;
- sampled owner declarations:
  `constantSheaf`,
  `openSubsetSheafExtensionByInitialObject`,
  `CategoryTheory.subobjectSubquotient`,
  `ShortComplex.ShortExact`;
- best owner abstractions:
  `constantSheaf` and `openSubsetSheafExtensionByInitialObject` for the sheaves `j_!
  \underline{\mathbf Z}_U`,
  `ShortComplex.ShortExact` for the exact-sequence condition on a quotient,
  `subobjectSubquotient` for successive quotients of the filtration;
- source/core/bridge triage:
  `source-facing`: finite generation by finitely many quasi-compact local generators and the
  existence of a finite filtration with successive quotients of the specified form;
  `core/canonical`: the sheaf owners `constantSheaf`, `openSubsetSheafExtensionByInitialObject`,
  the exactness owner `ShortComplex.ShortExact`, and the abelian subquotient owner
  `subobjectSubquotient`;
  `bridge/view`: the chapter-local abbreviation `extensionByZeroConstantIntegerSheaf` identifying
  the source-text sheaf `j_! \underline{\mathbf Z}_U` with the canonical Chapter 6 owner.
- primitive data versus derived API: the opens `U`, `V`, the comparison maps, and the filtration
  stages are genuine source-level data here; the ambient coproduct object for finitely many
  generators is derived canonical data and should therefore use the finite coproduct owner
  directly rather than an arbitrary cofan witness. -/

/-- The constant abelian sheaf `\underline{\mathbf Z}` on `X`. The coefficient group is modeled by
`ULift ℤ` to match the ambient universe. -/
abbrev constantIntegerSheaf (X : TopCat.{u}) : X.Sheaf AddCommGrpCat.{u} :=
  ((constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
    (AddCommGrpCat.of (ULift.{u} ℤ)) : X.Sheaf AddCommGrpCat.{u})

/-- The lower-shriek image `j_{U!}\underline{\mathbf Z}` of the constant integer sheaf on the open
subspace `U`. -/
abbrev extensionByZeroConstantIntegerSheaf (U : Opens X) : X.Sheaf AddCommGrpCat.{u} :=
  ((j! U).obj
    (constantIntegerSheaf (extensionByZeroOpenSubsetSpace U)) :
    X.Sheaf AddCommGrpCat.{u})

/-- A sheaf is generated by finitely many sections over quasi-compact opens when it is an
epimorphic image of the canonical finite coproduct of sheaves `j_{U_i!}\underline{\mathbf Z}`
with each `U_i` quasi-compact. -/
def IsGeneratedByFinitelyManyQuasiCompactSections
    (F : Subobject (constantIntegerSheaf X)) : Prop :=
  ∃ (n : ℕ) (U : Fin n → Opens X),
    (∀ i, IsCompact (U i : Set X)) ∧
      ∃ π : (∐ fun i : Fin n ↦ extensionByZeroConstantIntegerSheaf (U i)) ⟶
          (F : X.Sheaf AddCommGrpCat.{u}),
        Epi π

/-- An abelian sheaf admits a short exact presentation by two extension-by-zero constant integer
sheaves on quasi-compact opens. -/
def HasExtensionByZeroIntegerShortExactPresentation
    (A : X.Sheaf AddCommGrpCat.{u}) : Prop :=
  ∃ (U V : Opens X),
    IsCompact (U : Set X) ∧
      IsCompact (V : Set X) ∧
        ∃ (f : extensionByZeroConstantIntegerSheaf V ⟶ extensionByZeroConstantIntegerSheaf U)
          (g : extensionByZeroConstantIntegerSheaf U ⟶ A) (zero : f ≫ g = 0),
          (ShortComplex.mk f g zero).ShortExact

/-- A finite increasing filtration of an abelian sheaf whose successive quotients admit short exact
presentations by extension-by-zero constant integer sheaves on quasi-compact opens. -/
structure FiniteExtensionByZeroIntegerFiltration (A : X.Sheaf AddCommGrpCat.{u}) where
  /-- The length of the finite filtration. -/
  length : ℕ
  /-- The filtration stages `0 = F₀ ⊆ \cdots ⊆ F_n = A`. -/
  stage : Fin (length + 1) → Subobject A
  /-- The filtration starts at the zero subsheaf. -/
  zero_eq : stage 0 = ⊥
  /-- The filtration ends at the whole sheaf. -/
  top_eq : stage (Fin.last length) = ⊤
  /-- Consecutive stages are nested. -/
  step_le : ∀ i : Fin length, stage i.castSucc ≤ stage i.succ
  /-- Each successive quotient admits the required short exact presentation. -/
  quotient_hasPresentation :
    ∀ i : Fin length,
      HasExtensionByZeroIntegerShortExactPresentation (subobjectSubquotient (step_le i))

-- Proof sketch: rewrite finite generation of the subsheaf as an epimorphism from a finite
-- coproduct of sheaves `j_{U_i!}\underline{\mathbf Z}` with quasi-compact `U_i`, refine the
-- generators by finite intersections so the local integer sections satisfy the gcd condition from
-- the Stacks Project proof, and then filter by the allowed integer values. Each successive quotient
-- is generated by one integer over a quasi-compact union, and its kernel is generated by the same
-- integer over a quasi-compact open, yielding the displayed short exact sequence.
/-- Lemma 20.20.3: if intersections of quasi-compact opens in `X` are quasi-compact and
`ℱ ⊆ \underline{\mathbf Z}` is generated by finitely many sections over quasi-compact opens, then
`ℱ` admits a finite filtration by abelian subsheaves whose successive quotients fit into short
exact sequences `0 ⟶ j'_! \underline{\mathbf Z}_V ⟶ j_! \underline{\mathbf Z}_U ⟶
\mathcal{F}_i / \mathcal{F}_{i-1} ⟶ 0` with `U` and `V` quasi-compact opens. -/
theorem exists_finite_extensionByZeroIntegerFiltration_of_finitely_generated_subsheaf
    (hqc_inter :
      ∀ U V : Opens X,
        IsCompact (U : Set X) →
          IsCompact (V : Set X) →
            IsCompact (U ⊓ V : Set X))
    (F : Subobject (constantIntegerSheaf X))
    (hF : IsGeneratedByFinitelyManyQuasiCompactSections F) :
    Nonempty (FiniteExtensionByZeroIntegerFiltration (F : X.Sheaf AddCommGrpCat.{u})) := sorry

end
