import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Example_9_41 (from Items/Chap09) -/
open MeasureTheory ProbabilityTheory

noncomputable section

/-- The three-point sample space underlying the martingale representation counterexample. -/
abbrev representationCounterexampleState := Fin 3

/-- The uniform probability measure on the three counterexample states. -/
abbrev representationCounterexampleMeasure : Measure representationCounterexampleState :=
  (PMF.uniformOfFintype representationCounterexampleState).toMeasure

/-- The two-step process `X` with `X₀ = 0` and terminal values `-1`, `0`, and `1`. -/
def representationCounterexampleX : Fin 2 → representationCounterexampleState → ℝ
  | 0, _ => 0
  | 1, ω =>
      if (ω : ℕ) = 0 then -1 else if (ω : ℕ) = 1 then 0 else 1

/-- The companion process `Y` with `Y₀ = 0` and `Y₁ = 2` exactly on the branch where `X₁ = 1`. -/
def representationCounterexampleY : Fin 2 → representationCounterexampleState → ℝ
  | 0, _ => 0
  | 1, ω => if representationCounterexampleX 1 ω = 1 then 2 else -1

-- Proof sketch: the state space is finite, so every coordinate map of `representationCounterexampleX`
-- is a finite-valued measurable function and therefore strongly measurable.
private theorem representationCounterexampleX_stronglyMeasurable :
    ∀ n, StronglyMeasurable (representationCounterexampleX n) :=
  fun _ ↦ StronglyMeasurable.of_discrete

local notation "ℱX" =>
  Filtration.natural representationCounterexampleX
    representationCounterexampleX_stronglyMeasurable

/-- The terminal value `representationCounterexampleY 1` is not a scalar multiple of
`representationCounterexampleX 1`. -/
theorem representationCounterexampleY_not_scalar_multiple :
    ¬ ∃ H₁ : ℝ, H₁ • representationCounterexampleX 1 = representationCounterexampleY 1 := by
  rintro ⟨H₁, hH₁⟩
  have hEval := congr_fun hH₁ 1
  simp [representationCounterexampleX, representationCounterexampleY] at hEval

-- Proof sketch: for the martingale part, `Y₀` is constant, `Y₁` is measurable with respect to
-- the `σ`-algebra generated by `X₁`, and under the uniform law on the three states one has
-- `E[Y₁] = (-1 - 1 + 2) / 3 = 0 = Y₀`. For the non-representability part, the equality
-- `H₁ • X₁ = Y₁` would force `0 = -1` on the state where `X₁ = 0`.
/-- Example 9.41: for the explicit two-step process `representationCounterexampleY` on the uniform
three-point space, `Y` is a martingale with respect to the natural filtration generated by
`representationCounterexampleX`, but `Y₁` is not a scalar multiple of `X₁`. -/
theorem explicit_sigma_martingale_not_scalar_multiple :
    Martingale representationCounterexampleY ℱX
      representationCounterexampleMeasure ∧
      ¬ ∃ H₁ : ℝ, H₁ • representationCounterexampleX 1 = representationCounterexampleY 1 := by
  refine ⟨?_, representationCounterexampleY_not_scalar_multiple⟩
  sorry

end
