import Mathlib
import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Construction_3_8_4 (from Chap03) -/
universe u

open Path.Homotopic.Quotient
open TopologicalSpace
open TopologicalSpace.OpenNhdsOf

variable {B : Type u} [TopologicalSpace B]

namespace TopologicalSpace.OpenNhdsOf

variable {x : B}

/-- A suitable neighborhood for the universal-cover construction is an open neighborhood that is
path connected and whose inclusion induces the trivial map on the based fundamental group. -/
def IsSuitableForUniversalCover (U : OpenNhdsOf x) : Prop :=
  IsPathConnected (U : Set B) ∧
    FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)) ⟨x, U.mem⟩ = 1

end TopologicalSpace.OpenNhdsOf

variable {b : B}

/-- Construction 3.8.4: for a point `q` of the universal-cover candidate over `b` and a suitable
path-connected open neighborhood `U` of its endpoint, the basic neighborhood `U[q]` is the set of
endpoint-fixed homotopy classes obtained by concatenating `q` with paths in `U` starting at the
endpoint of `q`. -/
def universalCoverCandidateBasicSet (q : universalCoverCandidate b)
    (U : OpenNhdsOf q.1) : Set (universalCoverCandidate b) :=
  { r | ∃ y : U, ∃ c : Path ⟨q.1, U.mem⟩ y,
      r = ⟨y.1, q.2.trans ((mk c).map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)))⟩ }

/- The source-facing notation for the universal-cover basic neighborhood determined by `q`. -/
namespace UniversalCover

scoped notation U "[" q "]" => universalCoverCandidateBasicSet q U

end UniversalCover

open scoped UniversalCover

/-- The family of basic sets used to topologize the universal-cover candidate. -/
def universalCoverCandidateBasicSets (b : B) : Set (Set (universalCoverCandidate b)) :=
  { s | ∃ q : universalCoverCandidate b,
      ∃ U : OpenNhdsOf q.1,
        U.IsSuitableForUniversalCover ∧
          s = U[q] }

/-- The universal-cover candidate is equipped with the topology generated by its standard basic
sets. -/
instance universalCoverCandidateTopologicalSpace (b : B) :
    TopologicalSpace (universalCoverCandidate b) :=
  TopologicalSpace.generateFrom (universalCoverCandidateBasicSets b)

/-- Helper for Construction 3.8.4: the induced map on based fundamental groups is functorial
under composition of continuous maps. -/
private theorem fundamental_group_map_comp_local
    {X Y Z : Type u} [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]
    (f : C(X, Y)) (g : C(Y, Z)) (x : X) :
    FundamentalGroup.map (g.comp f) x =
      (FundamentalGroup.map g (f x)).comp (FundamentalGroup.map f x) := by
  -- Reduce functoriality to the explicit action on path-homotopy classes.
  ext γ
  refine Quotient.inductionOn γ ?_
  intro r
  rfl

/-- Helper for Construction 3.8.4: every point has a suitable neighborhood for the universal-cover
construction. -/
private theorem exists_suitable_universal_cover_neighborhood
    [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] (x : B) :
    ∃ U : OpenNhdsOf x, U.IsSuitableForUniversalCover := by
  rcases SemilocallySimplyConnectedSpace.trivial_fundamentalGroup_map (B := B) x with
    ⟨U, hUtriv⟩
  let Vset : Set B := pathComponentIn (U : Set B) x
  have hVmem : x ∈ Vset := mem_pathComponentIn_self U.mem
  have hVopen : IsOpen Vset := U.isOpen.pathComponentIn x
  have hVpath : IsPathConnected Vset := isPathConnected_pathComponentIn U.mem
  let V : OpenNhdsOf x := ⟨⟨Vset, hVopen⟩, hVmem⟩
  have hVsubsetU : (V : Set B) ⊆ U := pathComponentIn_subset
  let iVU : C(V, U) :=
    ⟨fun v ↦ ⟨v.1, hVsubsetU v.2⟩, continuous_subtype_val.subtype_mk fun v ↦ hVsubsetU v.2⟩
  have hSubtypeComp :
      ((⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)).comp iVU) =
        (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) := by
    -- Both maps are the ambient inclusion of the smaller path component.
    ext v
    rfl
  have hVtriv :
      FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) ⟨x, V.mem⟩ =
        (FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)) ⟨x, U.mem⟩).comp
          (FundamentalGroup.map iVU ⟨x, V.mem⟩) := by
    -- The smaller inclusion factors through the original semilocally simply connected neighborhood.
    simpa [hSubtypeComp] using fundamental_group_map_comp_local iVU
      (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)) ⟨x, V.mem⟩
  refine ⟨V, ?_⟩
  constructor
  · -- By construction `V` is the path component of `x` inside `U`.
    exact hVpath
  · -- Triviality of the induced map descends along the inclusion `V ↪ U`.
    calc
      FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) ⟨x, V.mem⟩
          =
          (FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)) ⟨x, U.mem⟩).comp
            (FundamentalGroup.map iVU ⟨x, V.mem⟩) := hVtriv
      _ = 1 := by
        rw [hUtriv]
        simp

/-- Helper for Construction 3.8.4: a suitable neighborhood can be shrunk inside any prescribed
open neighborhood of the same point. -/
private theorem exists_suitable_universal_cover_neighborhood_subset
    [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] (x : B)
    (N : OpenNhdsOf x) :
    ∃ U : OpenNhdsOf x, (U : Set B) ⊆ N ∧ U.IsSuitableForUniversalCover := by
  rcases exists_suitable_universal_cover_neighborhood (B := B) x with ⟨U₀, hU₀⟩
  let Iset : Set B := (U₀ : Set B) ∩ (N : Set B)
  have hImem : x ∈ Iset := ⟨U₀.mem, N.mem⟩
  have hIopen : IsOpen Iset := U₀.isOpen.inter N.isOpen
  let Vset : Set B := pathComponentIn Iset x
  have hVmem : x ∈ Vset := mem_pathComponentIn_self hImem
  have hVopen : IsOpen Vset := hIopen.pathComponentIn x
  have hVpath : IsPathConnected Vset := isPathConnected_pathComponentIn hImem
  let V : OpenNhdsOf x := ⟨⟨Vset, hVopen⟩, hVmem⟩
  have hVsubsetI : (V : Set B) ⊆ Iset := pathComponentIn_subset
  have hVsubsetU₀ : (V : Set B) ⊆ U₀ := fun y hy ↦ (hVsubsetI hy).1
  let i : C(V, U₀) :=
    ⟨fun y ↦ ⟨y.1, hVsubsetU₀ y.2⟩,
      continuous_subtype_val.subtype_mk fun y ↦ hVsubsetU₀ y.2⟩
  have hcomp :
      ((⟨Subtype.val, continuous_subtype_val⟩ : C(U₀, B)).comp i) =
        (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) := by
    -- The inclusion `V ↪ B` factors through `U₀`.
    ext y
    rfl
  have hVtriv :
      FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) ⟨x, V.mem⟩ =
        (FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U₀, B)) ⟨x, U₀.mem⟩).comp
          (FundamentalGroup.map i ⟨x, V.mem⟩) := by
    -- The smaller path component still maps through the original suitable neighborhood.
    simpa [hcomp] using fundamental_group_map_comp_local i
      (⟨Subtype.val, continuous_subtype_val⟩ : C(U₀, B)) ⟨x, V.mem⟩
  refine ⟨V, fun y hy ↦ (hVsubsetI hy).2, ?_⟩
  constructor
  · -- This neighborhood is path connected by construction as a path component.
    exact hVpath
  · -- Trivial monodromy persists after shrinking inside `U₀`.
    calc
      FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(V, B)) ⟨x, V.mem⟩
          =
          (FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U₀, B)) ⟨x, U₀.mem⟩).comp
            (FundamentalGroup.map i ⟨x, V.mem⟩) := hVtriv
      _ = 1 := by
        rw [hU₀.2]
        simp

/-- Helper for Construction 3.8.4: any point of a basic neighborhood projects to the indexing
open set. -/
private theorem universal_cover_candidate_basic_set_endpoint_mem
    (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    {r : universalCoverCandidate b} (hr : r ∈ U[q]) :
    r.1 ∈ (U : Set B) := by
  rcases hr with ⟨y, c, rfl⟩
  -- The endpoint is exactly the witness `y : U` used in the definition of `U[q]`.
  exact y.2

/-- Helper for Construction 3.8.4: every point belongs to the basic set indexed by itself. -/
private theorem universal_cover_candidate_basic_set_self_mem
    (r : universalCoverCandidate b) (U : OpenNhdsOf r.1) :
    r ∈ U[r] := by
  let i : C(U, B) := (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B))
  refine ⟨⟨r.1, U.mem⟩, Path.refl _, ?_⟩
  cases r with
  | mk x γ =>
      -- Route correction: use the constant path directly, so the second component reduces by
      -- `trans_refl` instead of introducing any extra path-class comparison machinery.
      change (⟨x, γ⟩ : universalCoverCandidate b) =
        ⟨x, γ.trans ((mk (Path.refl ⟨x, U.mem⟩)).map i)⟩
      have hmap : ((mk (Path.refl ⟨x, U.mem⟩)).map i) = Path.Homotopic.Quotient.refl x := rfl
      rw [hmap]
      exact (congrArg
        (fun δ : Path.Homotopic.Quotient b x ↦ (⟨x, δ⟩ : universalCoverCandidate b))
        (Path.Homotopic.Quotient.trans_refl γ)).symm

set_option maxHeartbeats 400000 in
/-- Helper for Construction 3.8.4: a smaller basic sheet through a point of `U[q]` still lies in
`U[q]` whenever the smaller neighborhood is contained in `U`. -/
private theorem universal_cover_candidate_basic_set_subset_of_mem
    {q r : universalCoverCandidate b} (U : OpenNhdsOf q.1) (hr : r ∈ U[q])
    {W : OpenNhdsOf r.1} (hWU : (W : Set B) ⊆ U) :
    W[r] ⊆ U[q] := by
  rcases hr with ⟨u, c, rfl⟩
  intro t ht
  rcases ht with ⟨z, d, rfl⟩
  let i : C(W, U) :=
    ⟨fun y ↦ ⟨y.1, hWU y.2⟩, continuous_subtype_val.subtype_mk fun y ↦ hWU y.2⟩
  let iU : C(U, B) := (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B))
  let iW : C(W, B) := (⟨Subtype.val, continuous_subtype_val⟩ : C(W, B))
  let zU : U := ⟨z.1, hWU z.2⟩
  let dU : Path ⟨u.1, u.2⟩ zU := d.map i.continuous
  have hd :
      ((mk d).map iW) = ((mk dU).map iU) := by
    -- Mapping along `W ↪ B` is the same as first regarding the path in `U` and then including.
    dsimp [dU]
    rw [← mk_map, ← mk_map]
    congr
  have htrans :
      (((mk c).map iU).trans ((mk dU).map iU)) =
        ((mk (c.trans dU)).map iU) := by
    -- Concatenation commutes with mapping to the ambient space.
    rw [← mk_map, ← mk_map, ← mk_trans, ← mk_map]
    simp [Path.map_trans]
  refine ⟨zU, c.trans dU, ?_⟩
  apply Sigma.ext
  · rfl
  · -- Reassociate the two-step extension to express the final point as one element of `U[q]`.
    simpa [iU, iW, dU, zU] using
      (calc
        (q.2.trans ((mk c).map iU)).trans ((mk d).map iW) =
            (q.2.trans ((mk c).map iU)).trans ((mk dU).map iU) := by rw [hd]
        _ = q.2.trans ((((mk c).map iU).trans ((mk dU).map iU))) := by
            rw [Path.Homotopic.Quotient.trans_assoc]
        _ = q.2.trans ((mk (c.trans dU)).map iU) := by rw [htrans])

/-- Helper for Construction 3.8.4: intersections of two suitable basic neighborhoods refine to a
smaller suitable basic neighborhood through the common point. -/
private theorem universal_cover_candidate_basic_set_intersection_refines
    [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B]
    {q r s : universalCoverCandidate b}
    (U : OpenNhdsOf q.1) (V : OpenNhdsOf s.1)
    (hU : U.IsSuitableForUniversalCover) (hV : V.IsSuitableForUniversalCover)
    (hrU : r ∈ U[q]) (hrV : r ∈ V[s]) :
    ∃ W : OpenNhdsOf r.1, (W : Set B) ⊆ (U : Set B) ∩ (V : Set B) ∧
      W.IsSuitableForUniversalCover ∧
        W[r] ⊆ U[q] ∩ V[s] := by
  let I₀ : OpenNhdsOf r.1 :=
    ⟨⟨(U : Set B) ∩ (V : Set B), U.isOpen.inter V.isOpen⟩,
      ⟨universal_cover_candidate_basic_set_endpoint_mem (b := b) q U hrU,
        universal_cover_candidate_basic_set_endpoint_mem (b := b) s V hrV⟩⟩
  rcases exists_suitable_universal_cover_neighborhood_subset (B := B) r.1 I₀ with
    ⟨W, hWsubset, hW⟩
  refine ⟨W, hWsubset, hW, ?_⟩
  intro t ht
  constructor
  · -- Since `W ⊆ U`, any point of the smaller `W`-sheet remains in `U[q]`.
    exact
      universal_cover_candidate_basic_set_subset_of_mem (b := b) (q := q) (r := r) U hrU
        (fun x hx ↦ (hWsubset hx).1) ht
  · -- The same argument with `V` shows the refined sheet also stays in `V[s]`.
    exact
      universal_cover_candidate_basic_set_subset_of_mem (b := b) (q := s) (r := r) V hrV
        (fun x hx ↦ (hWsubset hx).2) ht

/-- The standard basic sets on the universal-cover candidate form a topological basis, under the
local hypotheses from May's universal-cover construction. -/
-- Proof sketch: local path connectedness and semilocal simple connectedness give arbitrarily small
-- suitable neighborhoods. These supply both the cover of `universalCoverCandidate b` and the
-- refinement of intersections by a third basic set through any common point.
theorem universalCoverCandidateBasicSets_isTopologicalBasis
    [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] (b : B) :
    TopologicalSpace.IsTopologicalBasis (universalCoverCandidateBasicSets b) := by
  refine TopologicalSpace.IsTopologicalBasis.mk ?_ ?_ rfl
  · intro s₁ hs₁ s₂ hs₂ r hr
    rcases hs₁ with ⟨q, U, hU, rfl⟩
    rcases hs₂ with ⟨s, V, hV, rfl⟩
    rcases universal_cover_candidate_basic_set_intersection_refines
        (b := b) (q := q) (r := r) (s := s) U V hU hV hr.1 hr.2 with
      ⟨W, -, hW, hsubset⟩
    -- The refined suitable neighborhood `W` supplies the third basis element through `r`.
    refine ⟨W[r], ?_, ?_, hsubset⟩
    · exact ⟨r, W, hW, rfl⟩
    · exact universal_cover_candidate_basic_set_self_mem (b := b) r W
  · ext r
    constructor
    · intro _
      simp
    · intro _
      rcases exists_suitable_universal_cover_neighborhood (B := B) r.1 with ⟨U, hU⟩
      have hrbasic : r ∈ U[r] := by
        -- A constant path at the endpoint puts `r` into its own basic sheet.
        exact universal_cover_candidate_basic_set_self_mem (b := b) r U
      refine Set.mem_sUnion.mpr ⟨U[r], ?_, hrbasic⟩
      exact ⟨r, U, hU, rfl⟩

/-! ### Lemma_3_8_5 (from Chap03) -/
universe u

open Path.Homotopic.Quotient
open TopologicalSpace
open TopologicalSpace.OpenNhdsOf
open scoped UniversalCover

variable {B : Type u} [TopologicalSpace B]

/-- The endpoint of a point in a universal-cover basic set lies in the chosen neighborhood. -/
-- Proof sketch: unpack membership in `universalCoverCandidateBasicSet`; the witness
-- `y : U` occurring in the definition has endpoint `y.1`, and the defining equality of the basic
-- set identifies this endpoint with the first component of `r`.
theorem universalCoverCandidateBasicSet_endpoint_mem
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    {r : universalCoverCandidate b} (hr : r ∈ U[q]) :
    r.1 ∈ (U : Set B) := sorry

/-- The class obtained by extending `q` with a path in `U` belongs to the associated basic set. -/
-- Proof sketch: use the defining witnesses `y := u` and `c` in the definition of
-- `universalCoverCandidateBasicSet`, with the displayed class as the required endpoint-fixed
-- homotopy class.
theorem universalCoverCandidateBasicSet_pathClass_mem
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    (u : U) (c : Path ⟨q.1, U.mem⟩ u) :
    (⟨u.1, q.2.trans ((mk c).map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)))⟩ :
      universalCoverCandidate b) ∈ U[q] :=
  sorry

/-- Any two paths in a neighborhood with trivial induced based fundamental-group map determine the
same point of the universal-cover candidate. -/
-- Proof sketch: if the inclusion `U ↪ B` induces the trivial map on the based fundamental group
-- at `q.1`, then the loop obtained by traversing `c₁` and then `c₂⁻¹` is null-homotopic in `B`.
-- Hence the two concatenated path classes represent the same point of the universal-cover
-- candidate.
theorem universalCoverCandidate_pathClass_eq_of_paths
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    (htriv : FundamentalGroup.map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B))
      ⟨q.1, U.mem⟩ = 1)
    (u : U) (c₁ c₂ : Path ⟨q.1, U.mem⟩ u) :
    (⟨u.1, q.2.trans ((mk c₁).map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)))⟩ :
      universalCoverCandidate b) =
      ⟨u.1, q.2.trans ((mk c₂).map (⟨Subtype.val, continuous_subtype_val⟩ : C(U, B)))⟩ := sorry

/-- The endpoint projection restricted to a universal-cover basic set. -/
def universalCoverCandidateBasicSet_projectionToNeighborhood
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1) :
    {r // r ∈ U[q]} → U
  | ⟨r, hr⟩ => ⟨r.1, universalCoverCandidateBasicSet_endpoint_mem b q U hr⟩

@[simp] theorem universalCoverCandidateBasicSet_projectionToNeighborhood_apply
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    (r : {r // r ∈ U[q]}) :
    (universalCoverCandidateBasicSet_projectionToNeighborhood b q U r : B) = r.1.1 := rfl

/-- Lemma 3.8.5: for a suitable basic set `U[f]`, the endpoint projection restricts to an open
embedding onto `U`; equivalently, the explicit restricted endpoint map is a homeomorphism onto
`U`. -/
-- Proof sketch: surjectivity follows from path connectedness of `U`, since every `u : U` is
-- joined to the endpoint of `q` by a path producing a point of the basic set above `u`.
-- Injectivity comes from `universalCoverCandidate_pathClass_eq_of_paths`, using that the
-- inclusion `U ↪ B` kills based loops. Openness and continuity are checked on the basis
-- `universalCoverCandidateBasicSets b`, so the restricted endpoint map is a homeomorphism onto
-- `U`.
theorem universalCoverCandidateBasicSet_projectionToNeighborhood_homeomorphic
    (b : B) (q : universalCoverCandidate b) (U : OpenNhdsOf q.1)
    (hU : U.IsSuitableForUniversalCover) :
    IsHomeomorph (universalCoverCandidateBasicSet_projectionToNeighborhood b q U) := sorry

/-! ### Lemma_3_8_6 (from Chap03) -/
universe u

variable {B : Type u} [TopologicalSpace B]

section

variable [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B]

/- The owner fact behind Lemma 3.8.6 (2): the path-class space is locally path connected. -/
-- Proof sketch: the standard basic neighborhoods from Construction 3.8.3 are indexed by suitable
-- open neighborhoods in `B`. By Lemma 3.8.5, each such basic neighborhood is identified with its
-- indexing neighborhood, which is path connected by definition, so these basic sets form a
-- path-connected neighborhood basis on the total space.
instance instLocPathConnectedSpace_universalCoverCandidate (b : B) :
    LocPathConnectedSpace (universalCoverCandidate b) := by
  sorry

/- The owner fact behind Lemma 3.8.6 (3): the path-class space is simply connected. -/
-- Proof sketch: a loop in the total space based at the class of the constant path projects to a
-- loop in `B`. The endpoint-fixed path-class construction identifies the endpoint of the lifted
-- loop with the resulting path class in `B`, so a loop can close only when that class is trivial.
-- This makes every based loop null-homotopic, hence the total space is simply connected.
instance instSimplyConnectedSpace_universalCoverCandidate (b : B) :
    SimplyConnectedSpace (universalCoverCandidate b) := by
  sorry

end

/-- Lemma 3.8.6 (1): the path-class space constructed over the basepoint `b` is connected. -/
theorem universalCoverCandidate_connectedSpace
    (b : B) [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] :
    ConnectedSpace (universalCoverCandidate b) :=
  inferInstance

/-- Lemma 3.8.6 (2): the path-class space constructed over the basepoint `b` is locally path
connected. -/
theorem universalCoverCandidate_locPathConnectedSpace
    (b : B) [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] :
    LocPathConnectedSpace (universalCoverCandidate b) :=
  inferInstance

/-- Lemma 3.8.6 (3): the path-class space constructed over the basepoint `b` is simply connected.
-/
theorem universalCoverCandidate_simplyConnectedSpace
    (b : B) [LocPathConnectedSpace B] [SemilocallySimplyConnectedSpace B] :
    SimplyConnectedSpace (universalCoverCandidate b) :=
  inferInstance

/-! ### Definition_3_8_7 (from Chap03) -/
universe u v

variable (G : Type u) (X : Type v) [Group G] [TopologicalSpace X] [MulAction G X]

/- The source-facing orbit-space notation `X/H`, implemented as `X /[H]`, is the canonical orbit
quotient `MulAction.orbitRel.Quotient H X`. Equality of orbit classes is expressed by the
canonical theorem `MulAction.orbitRel.Quotient.mem_orbit`. -/
notation:70 X " /[" H "]" => MulAction.orbitRel.Quotient H X

/- Definition 3.8.7: for a group action from Definition 3.4.1, a `G`-space is the canonical
continuity condition `ContinuousConstSMul G X`; for a discrete topological group this says each
translate `x ↦ g • x` is continuous. -/
#check (ContinuousConstSMul G X)

/- In the orbit space `X /[G]`, the class of `x` lies in the orbit represented by `q` exactly when
`Quotient.mk'' x = q`. -/
#check (MulAction.orbitRel.Quotient.mem_orbit :
  ∀ {a : X} {q : X /[G]}, a ∈ q.orbit ↔ Quotient.mk'' a = q)

/-! ### Lemma_3_8_8 (from Chap03) -/
universe u v

open CategoryTheory
open QuotientGroup
open Topology

variable (G : Type u) [Group G]

variable {G}
variable {X : Type v} [MulAction G X]

/-- A coset `γK` acts on the orbit space `X/K` by the canonical formula `x ↦ K (γ⁻¹ • x)`. -/
noncomputable def orbitSpacePointMap {K : O(G)} (x : X) : G ⧸ K → X /[K] :=
  Quotient.lift (fun γ : G ↦ Quotient.mk'' (γ⁻¹ • x)) fun a b hab ↦ by
    apply Quotient.sound
    change MulAction.orbitRel (K : Subgroup G) X (a⁻¹ • x) (b⁻¹ • x)
    rw [MulAction.orbitRel_apply]
    have hk : a⁻¹ * b ∈ (K : Subgroup G) := (QuotientGroup.leftRel_apply).mp hab
    refine ⟨⟨a⁻¹ * b, hk⟩, ?_⟩
    simp [smul_smul, mul_assoc]

/-- Evaluating `orbitSpacePointMap` on a represented coset gives the expected formula. -/
@[simp] theorem orbitSpacePointMap_apply_mk {K : O(G)} (x : X) (γ : G) :
    orbitSpacePointMap x (γ : G ⧸ K) = Quotient.mk'' (γ⁻¹ • x) :=
  rfl

/-- The pointwise orbit-space formula attached to an orbit-category morphism uses the canonical
fixed coset `α(1H)` from `Subgroup.orbitCategoryHomEvalOne`. -/
noncomputable def orbitSpaceMapFn {H K : O(G)} (α : H ⟶ K) : X → X /[K] :=
  fun x ↦ orbitSpacePointMap x (Subgroup.orbitCategoryHomEvalOne H K α)

/-- The pointwise orbit-space formula is constant on `H`-orbits. -/
-- Proof sketch: if `y = h • x`, the coset `α(1H)` is `H`-fixed in `G ⧸ K`, so the corresponding
-- conjugate of `h` lies in `K`; this exactly identifies the two classes in `X/K`.
theorem orbitSpaceMapFn_eq_of_orbitRel {H K : O(G)} (α : H ⟶ K) {x y : X}
    (hxy : MulAction.orbitRel (H : Subgroup G) X x y) :
    orbitSpaceMapFn α x = orbitSpaceMapFn α y := by
  -- Choose a representative of the fixed coset controlling `α`.
  obtain ⟨γ, hγ⟩ := Quotient.exists_rep
    ((Subgroup.orbitCategoryHomEvalOne H K α :
      MulAction.fixedPoints (H : Subgroup G) (G ⧸ K)) : G ⧸ K)
  -- Translate the fixed-point condition into the needed subconjugacy inclusion.
  have hsub := subgroup_map_conj_inv_le_of_quotient_mulActionHom_apply_one α γ (by
    simpa [Subgroup.orbitCategoryHomEvalOne] using hγ.symm)
  -- After rewriting the distinguished coset as `γK`, equality in `X /[K]` is orbit relation.
  rw [orbitSpaceMapFn, orbitSpaceMapFn, ← hγ, orbitSpacePointMap_apply_mk,
    orbitSpacePointMap_apply_mk]
  apply Quotient.sound
  rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff] at hxy
  obtain ⟨h, rfl⟩ := hxy
  rw [Subgroup.pointwise_smul_def] at hsub
  refine ⟨⟨γ⁻¹ * (h : G) * γ, hsub ⟨h, h.2, by simp [mul_assoc]⟩⟩, ?_⟩
  -- The witness `γ⁻¹ h γ ∈ K` transports the `H`-orbit relation to a `K`-orbit relation.
  change ((γ⁻¹ * (h : G) * γ : G)) • (γ⁻¹ • y) = γ⁻¹ • ((h : G) • y)
  simp [smul_smul, mul_assoc]

section Topological

variable [TopologicalSpace X]

/-- Restricting a `G`-space action along a subgroup again gives a continuous action. -/
instance subgroup_continuousConstSMul (H : Subgroup G) [ContinuousConstSMul G X] :
    ContinuousConstSMul H X where
  continuous_const_smul h := by
    -- Restrict the ambient continuous translate `x ↦ h • x` along the subgroup inclusion.
    simpa using (continuous_const_smul (h : G) : Continuous fun x : X => (h : G) • x)

/-- The pointwise orbit-space formula is continuous. -/
-- Proof sketch: for a fixed coset `γK`, the map `x ↦ K (γ⁻¹ • x)` is the quotient projection
-- composed with the continuous translate `x ↦ γ⁻¹ • x`.
theorem orbitSpaceMapFn_continuous [ContinuousConstSMul G X] {H K : O(G)} (α : H ⟶ K) :
    Continuous (orbitSpaceMapFn α : X → X /[K]) := by
  -- Pick a representative for the distinguished fixed coset of `α`.
  obtain ⟨γ, hγ⟩ := Quotient.exists_rep
    ((Subgroup.orbitCategoryHomEvalOne H K α :
      MulAction.fixedPoints (H : Subgroup G) (G ⧸ K)) : G ⧸ K)
  -- Rewrite the map as the quotient projection after the continuous translate by `γ⁻¹`.
  rw [show (orbitSpaceMapFn α : X → X /[K]) = fun x ↦ orbitSpacePointMap x (γ : G ⧸ K) by
    funext x
    rw [orbitSpaceMapFn, ← hγ]]
  simpa using (continuous_quotient_mk'.comp (continuous_const_smul (γ⁻¹ : G)))

/-- The continuous map on orbit spaces induced by a morphism in the orbit category. -/
noncomputable def orbitSpaceMap (G : Type u) [Group G] (X : Type v)
    [TopologicalSpace X] [MulAction G X] [ContinuousConstSMul G X] {H K : O(G)}
    (α : H ⟶ K) :
    C(X /[H], X /[K]) :=
  ⟨Quotient.lift (orbitSpaceMapFn α) fun _ _ hxy ↦ orbitSpaceMapFn_eq_of_orbitRel α hxy,
    continuous_quot_lift
      (fun _ _ hxy ↦ orbitSpaceMapFn_eq_of_orbitRel α hxy)
      (orbitSpaceMapFn_continuous α)⟩

/-- Applying the induced orbit-space map to an orbit class uses the canonical fixed coset
`α(1H)`. -/
theorem orbitSpaceMap_apply_mk [ContinuousConstSMul G X] {H K : O(G)}
    (α : H ⟶ K) (x : X) :
    orbitSpaceMap G X α (Quotient.mk'' x) =
      orbitSpacePointMap x (Subgroup.orbitCategoryHomEvalOne H K α) :=
  rfl

/-- If `α : G/H ⟶ G/K` sends `1H` to `γK`, then the induced map on orbit spaces sends `Hx` to
`K (γ⁻¹ • x)`. -/
-- Proof sketch: replace the canonical fixed coset `Subgroup.orbitCategoryHomEvalOne H K α` by the
-- represented coset `γK` and evaluate `orbitSpacePointMap` at that class.
theorem orbitSpaceMap_apply_mk_of_apply_one [ContinuousConstSMul G X]
    {H K : O(G)} (α : H ⟶ K) {γ : G}
    (hα : α.toFun ((1 : G) : G ⧸ H) = (γ : G ⧸ K)) (x : X) :
    orbitSpaceMap G X α (Quotient.mk'' x) = Quotient.mk'' (γ⁻¹ • x) := by
  -- Rewrite the canonical fixed coset `α(1H)` as the represented coset `γK`.
  change orbitSpacePointMap x (α.toFun ((1 : G) : G ⧸ H)) = Quotient.mk'' (γ⁻¹ • x)
  rw [hα, orbitSpacePointMap_apply_mk]

/-- The orbit-space map is the identity on `X/H` for the identity morphism of `H`. -/
-- Proof sketch: the identity morphism sends `1H` to `1H`, so the induced pointwise formula is the
-- identity on orbit classes.
theorem orbitSpaceMap_id (G : Type u) [Group G] (X : Type v)
    [TopologicalSpace X] [MulAction G X] [ContinuousConstSMul G X] (H : O(G)) :
    orbitSpaceMap G X (𝟙 H) = ContinuousMap.id (X /[H]) := by
  -- Compare the two continuous maps on orbit representatives.
  ext q
  refine Quotient.inductionOn' q ?_
  intro x
  -- The identity morphism is determined by the base coset `1H`.
  rw [orbitSpaceMap_apply_mk_of_apply_one (α := 𝟙 H) (x := x) rfl]
  simp

/-- Composition of orbit-space maps matches composition in the orbit category. -/
-- Proof sketch: the canonical fixed coset of `β ∘ α` is the product of the fixed cosets of `α`
-- and `β`, so the pointwise formulas agree on representatives.
theorem orbitSpaceMap_comp (G : Type u) [Group G] (X : Type v)
    [TopologicalSpace X] [MulAction G X] [ContinuousConstSMul G X] {H K L : O(G)}
    (α : H ⟶ K) (β : K ⟶ L) :
    (orbitSpaceMap G X (α ≫ β) : C(X /[H], X /[L])) =
      (orbitSpaceMap G X β : C(X /[K], X /[L])).comp
        (orbitSpaceMap G X α : C(X /[H], X /[K])) := by
  -- Choose representatives for the canonical fixed cosets of `α` and `β`.
  obtain ⟨γ, hα⟩ := Quotient.exists_rep
    ((Subgroup.orbitCategoryHomEvalOne H K α :
      MulAction.fixedPoints (H : Subgroup G) (G ⧸ K)) : G ⧸ K)
  obtain ⟨δ, hβ⟩ := Quotient.exists_rep
    ((Subgroup.orbitCategoryHomEvalOne K L β :
      MulAction.fixedPoints (K : Subgroup G) (G ⧸ L)) : G ⧸ L)
  have hα_apply : α.toFun ((1 : G) : G ⧸ H) = (γ : G ⧸ K) := by
    -- Unwrap the chosen representative of the fixed coset attached to `α`.
    simpa [Subgroup.orbitCategoryHomEvalOne] using hα.symm
  have hβ_apply : β.toFun ((1 : G) : G ⧸ K) = (δ : G ⧸ L) := by
    -- Unwrap the chosen representative of the fixed coset attached to `β`.
    simpa [Subgroup.orbitCategoryHomEvalOne] using hβ.symm
  have hcomp : (α ≫ β).toFun ((1 : G) : G ⧸ H) = ((γ * δ : G) : G ⧸ L) := by
    -- The composite sends `1H` to `β (γK) = (γδ)L`.
    change β.toFun (Subgroup.orbitCategoryHomEvalOne H K α) = ((γ * δ : G) : G ⧸ L)
    rw [← hα]
    exact quotient_mulActionHom_apply_coe_eq_coe_mul_of_apply_one β δ γ hβ_apply
  -- Check the two maps on quotient representatives, then simplify the inverse product formula.
  ext q
  refine Quotient.inductionOn' q ?_
  intro x
  rw [orbitSpaceMap_apply_mk_of_apply_one (α := α ≫ β) (x := x) hcomp]
  rw [ContinuousMap.comp_apply]
  rw [orbitSpaceMap_apply_mk_of_apply_one (α := α) (x := x) hα_apply]
  rw [orbitSpaceMap_apply_mk_of_apply_one (α := β) (x := γ⁻¹ • x) hβ_apply]
  change Quotient.mk'' (((γ * δ)⁻¹ : G) • x) = Quotient.mk'' (δ⁻¹ • (γ⁻¹ • x) : X)
  simp [smul_smul]

/-- Lemma 3.8.8: for a `G`-space `X`, passage to orbit spaces defines a functor
`X/(-) : O(G) ⥤ TopCat`, sending `G/H` to `X/H` and an orbit map determined by `γ` to the map
`Hx ↦ K (γ⁻¹ • x)`. -/
noncomputable def orbitSpaceFunctor (G : Type u) [Group G] (X : Type v)
    [TopologicalSpace X] [MulAction G X] [ContinuousConstSMul G X] :
    O(G) ⥤ TopCat where
  obj H := TopCat.of (X /[H])
  map {_ _} α := TopCat.ofHom (orbitSpaceMap G X α)
  map_id H := by
    simpa using congrArg TopCat.ofHom (orbitSpaceMap_id G X H)
  map_comp α β := by
    simpa using congrArg TopCat.ofHom (orbitSpaceMap_comp G X α β)

end Topological

/-! ### Proposition_3_8_9 (from Chap03) -/
open CategoryTheory
open CategoryTheory.Groupoid.CategoryTheory
open FundamentalGroupoid
open scoped FundamentalGroup
open scoped Pointwise

universe u

variable {E B : Type u} [TopologicalSpace E] [TopologicalSpace B]

/-- The automorphism group of a covering space acts on its total space by evaluation. -/
instance coveringSpaceAutMulAction (p : C(E, B)) :
    MulAction (Aut (Over.mk (TopCat.ofHom p))) E where
  smul α x := α.hom.left.hom x
  -- The identity automorphism evaluates to the identity self-map of `E`.
  one_smul x := by
    rfl
  -- Multiplication in `Aut` is composition, so evaluation is associative.
  mul_smul α β x := by
    rfl

/-- Every covering-space automorphism lies over the identity on the base, so evaluating it does
not change the image under the covering map. -/
-- Proof sketch: the defining commutative triangle of a morphism in the over-category says exactly
-- that `p ∘ α = p`.
private theorem coveringSpaceAut_smul_proj
    (p : C(E, B)) (α : Aut (Over.mk (TopCat.ofHom p))) (x : E) :
    p (α • x) = p x := by
  -- Evaluate the commutative triangle `p ∘ α = p` at the chosen point `x`.
  have hcomm := congrArg (fun f => TopCat.Hom.hom f x) (Over.w α.hom)
  simpa [ContinuousMap.comp_apply] using hcomm

/-- The covering map is constant on orbits of the covering-space automorphism action. -/
-- Proof sketch: two points in the same orbit differ by applying some covering automorphism, and
-- the previous lemma shows that `p` is invariant under that action.
private theorem coveringSpaceAut_proj_eq_of_orbitRel (p : C(E, B)) {x y : E}
    (hxy : MulAction.orbitRel (Aut (Over.mk (TopCat.ofHom p))) E x y) :
    p x = p y := by
  rcases hxy with ⟨α, hα⟩
  -- Orbit-related points differ by a deck transformation, and deck transformations preserve `p`.
  simpa [hα] using coveringSpaceAut_smul_proj p α y

/-- The canonical orbit projection `E / Aut(E) → B` induced by the covering map. -/
def coveringSpaceAutOrbitProjection (p : C(E, B)) :
    C(E /[Aut (Over.mk (TopCat.ofHom p))], B) :=
  ⟨fun x ↦ Quotient.liftOn' x p (fun _ _ hxy ↦ coveringSpaceAut_proj_eq_of_orbitRel p hxy),
    continuous_quot_lift
      (fun _ _ hxy ↦ coveringSpaceAut_proj_eq_of_orbitRel p hxy)
      p.continuous⟩

/-- The deck-transformation group acts on the fiber over `p e` by restricting evaluation to that
fiber. -/
@[reducible] noncomputable def coveringSpaceAutFiberMulAction
    (p : C(E, B)) (e : E) :
    MulAction (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e}) :=
  { smul := fun α x ↦
      ⟨α.hom.left.hom x.1, by
        have hproj : p (α.hom.left.hom x.1) = p x.1 := by
          simpa using coveringSpaceAut_smul_proj p α x.1
        simpa using hproj.trans x.2⟩
    -- The restricted action inherits the identity law from evaluation on `E`.
    one_smul := by
      intro x
      apply Subtype.ext
      rfl
    -- The restricted action inherits associativity from evaluation on `E`.
    mul_smul := by
      intro α β x
      apply Subtype.ext
      rfl }

variable {p : C(E, B)}

/-- Helper for Proposition 3.8.9: the subgroup attached to a categorical fiber point, obtained by
transporting the image of the corresponding vertex-group map to the chosen base vertex. -/
private def fiberPointSubgroup
    {E' B' : Type u} [Groupoid E'] [Groupoid B'] {q : E' ⥤ B'} {b : B'}
    (x : q.Fiber b) : Subgroup (b ⟶ b) :=
  x.2 ▸ (CategoryTheory.Functor.mapVertexGroup q x.1).range

/-- Helper for Proposition 3.8.9: for any fiber point of a covering functor, the transported
vertex-group image subgroup is exactly the stabilizer of that point under fiber translation. -/
private theorem mapVertexGroup_range_eq_stabilizer
    {E' B' : Type u} [Groupoid E'] [Groupoid B'] {q : E' ⥤ B'}
    (hq : Functor.IsCovering q) {b : B'} (x : q.Fiber b) :
    by
      letI : MulAction (b ⟶ b) (q.Fiber b) := Functor.IsCovering.fiberTranslationMulAction hq b
      exact fiberPointSubgroup x = MulAction.stabilizer (b ⟶ b) x := by
  -- Reduce to the distinguished basepoint of the fiber, where Lemma 3.4.11 computes the
  -- stabilizer explicitly.
  rcases x with ⟨x, rfl⟩
  simpa [fiberPointSubgroup, Functor.IsCovering.fiberTranslationMulAction] using
    (Functor.IsCovering.fiberTranslation_basepoint_stabilizer_eq_mapVertexGroup_range hq x).symm

/-- Helper for Proposition 3.8.9: an equivariant bijection preserves stabilizers. -/
private theorem stabilizer_eq_of_equivariant_bijective
    {G S : Type u} [Group G] [MulAction G S] (σ : S → S) (hσ : Function.Bijective σ)
    (hσ_eqv : ∀ (g : G) (x : S), σ (g • x) = g • σ x) (s : S) :
    MulAction.stabilizer G (σ s) = MulAction.stabilizer G s := by
  ext g
  constructor
  · intro hg
    -- Injectivity lets us pull the fixed-point condition back through `σ`.
    change g • s = s
    apply hσ.1
    calc
      σ (g • s) = g • σ s := hσ_eqv g s
      _ = σ s := hg
  · intro hg
    -- Equivariance pushes a fixed-point condition forward through `σ`.
    change g • σ s = σ s
    rw [← hσ_eqv g s, hg]

/-- Helper for Proposition 3.8.9: transporting the induced categorical fiber map of a deck
transformation across `fundamentalGroupoidMapFiberEquiv` recovers the ordinary deck action on the
fiber over `p e`. -/
private theorem coveringSpaceAut_fundamentalGroupoidFiberEquiv_smul
    (hp : IsPathConnectedCoveringMap p) (e : E) (α : Aut (Over.mk (TopCat.ofHom p)))
    (x : hp.fundamentalGroupoidMap.Fiber (mk (p e))) :
    letI := coveringSpaceAutFiberMulAction p e
    hp.fundamentalGroupoidMapFiberEquiv (p e)
        (Functor.IsCovering.mapOfCoveringsToFiberFun
          (mk (p e))
          (hp.toFundamentalGroupoidCoveringHom hp α.hom)
          x) =
      α • hp.fundamentalGroupoidMapFiberEquiv (p e) x := by
  -- Both constructions evaluate the same deck transformation on the underlying point of the
  -- chosen fiber.
  apply Subtype.ext
  rfl

/-- Helper for Proposition 3.8.9: moving the chosen fiber point by a deck transformation preserves
the transported categorical subgroup in the base vertex group. -/
private theorem coveringSpaceAut_fundamentalGroup_map_range_eq
    (hp : IsPathConnectedCoveringMap p) (e : E) (x : p ⁻¹' {p e})
    (α : Aut (Over.mk (TopCat.ofHom p)))
    (hα :
      by
        letI := coveringSpaceAutFiberMulAction p e
        exact α • (⟨e, rfl⟩ : p ⁻¹' {p e}) = x) :
    fiberPointSubgroup ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm x) =
      fiberPointSubgroup ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm ⟨e, rfl⟩) := by
  -- Route correction: keep the subgroup comparison inside the categorical fiber over `mk (p e)`,
  -- where deck transformations act by an equivariant bijection.
  letI := Functor.IsCovering.fiberTranslationMulAction hp.fundamentalGroupoidMap_isCovering
    (mk (p e))
  letI := coveringSpaceAutFiberMulAction p e
  let ξ₀ : hp.fundamentalGroupoidMap.Fiber (mk (p e)) :=
    (hp.fundamentalGroupoidMapFiberEquiv (p e)).symm ⟨e, rfl⟩
  let σ : hp.fundamentalGroupoidMap.Fiber (mk (p e)) →
      hp.fundamentalGroupoidMap.Fiber (mk (p e)) :=
    Functor.IsCovering.mapOfCoveringsToFiberFun (mk (p e))
      (hp.toFundamentalGroupoidCoveringHom hp α.hom)
  have hσ : Function.Bijective σ := by
    refine ⟨?_, ?_⟩
    · intro y z hyz
      have hαyz :
          α • hp.fundamentalGroupoidMapFiberEquiv (p e) y =
            α • hp.fundamentalGroupoidMapFiberEquiv (p e) z := by
        calc
          α • hp.fundamentalGroupoidMapFiberEquiv (p e) y =
              hp.fundamentalGroupoidMapFiberEquiv (p e) (σ y) := by
                symm
                simpa [σ] using coveringSpaceAut_fundamentalGroupoidFiberEquiv_smul hp e α y
          _ = hp.fundamentalGroupoidMapFiberEquiv (p e) (σ z) := by
                rw [hyz]
          _ = α • hp.fundamentalGroupoidMapFiberEquiv (p e) z := by
                simpa [σ] using coveringSpaceAut_fundamentalGroupoidFiberEquiv_smul hp e α z
      have hyz' :
          hp.fundamentalGroupoidMapFiberEquiv (p e) y =
            hp.fundamentalGroupoidMapFiberEquiv (p e) z := by
        have hcancel := congrArg (fun t => α⁻¹ • t) hαyz
        simpa [mul_smul] using hcancel
      exact (hp.fundamentalGroupoidMapFiberEquiv (p e)).injective hyz'
    · intro y
      refine ⟨(hp.fundamentalGroupoidMapFiberEquiv (p e)).symm
        (α⁻¹ • hp.fundamentalGroupoidMapFiberEquiv (p e) y), ?_⟩
      apply (hp.fundamentalGroupoidMapFiberEquiv (p e)).injective
      calc
        hp.fundamentalGroupoidMapFiberEquiv (p e)
            (σ ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm
              (α⁻¹ • hp.fundamentalGroupoidMapFiberEquiv (p e) y))) =
              α • (α⁻¹ • hp.fundamentalGroupoidMapFiberEquiv (p e) y) := by
                simpa [σ] using coveringSpaceAut_fundamentalGroupoidFiberEquiv_smul hp e α
                  ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm
                    (α⁻¹ • hp.fundamentalGroupoidMapFiberEquiv (p e) y))
        _ = hp.fundamentalGroupoidMapFiberEquiv (p e) y := by
              simp
  have hσ_eqv :
      ∀ (g : mk (p e) ⟶ mk (p e)) (y : hp.fundamentalGroupoidMap.Fiber (mk (p e))),
        σ (g • y) = g • σ y := by
    intro g y
    simpa [σ] using
      (Functor.IsCovering.mapOfCoveringsToFiberFun_comm hp.fundamentalGroupoidMap_isCovering
        hp.fundamentalGroupoidMap_isCovering (mk (p e))
        (hp.toFundamentalGroupoidCoveringHom hp α.hom) g y)
  have hmap : σ ξ₀ = (hp.fundamentalGroupoidMapFiberEquiv (p e)).symm x := by
    apply (hp.fundamentalGroupoidMapFiberEquiv (p e)).injective
    simpa [σ, ξ₀] using
      (coveringSpaceAut_fundamentalGroupoidFiberEquiv_smul hp e α ξ₀).trans hα
  calc
    fiberPointSubgroup ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm x) =
        MulAction.stabilizer (mk (p e) ⟶ mk (p e))
          ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm x) := by
          simpa using mapVertexGroup_range_eq_stabilizer hp.fundamentalGroupoidMap_isCovering
            ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm x)
    _ = MulAction.stabilizer (mk (p e) ⟶ mk (p e)) (σ ξ₀) := by
          rw [hmap]
    _ = MulAction.stabilizer (mk (p e) ⟶ mk (p e)) ξ₀ :=
          stabilizer_eq_of_equivariant_bijective σ hσ hσ_eqv ξ₀
    _ = fiberPointSubgroup ξ₀ := by
          rw [mapVertexGroup_range_eq_stabilizer hp.fundamentalGroupoidMap_isCovering ξ₀]

/-- Helper for Proposition 3.8.9: at the distinguished categorical fiber point over `p e`, the
transported subgroup is the image of the induced vertex-group map. -/
private theorem fiberPointSubgroup_basepoint_eq_mapVertexGroup_range
    (hp : IsPathConnectedCoveringMap p) (e : E) :
    fiberPointSubgroup ((hp.fundamentalGroupoidMapFiberEquiv (p e)).symm ⟨e, rfl⟩) =
      (CategoryTheory.Functor.mapVertexGroup hp.fundamentalGroupoidMap (mk e)).range := by
  -- At the literal basepoint, the transported subgroup is definitionally the induced image.
  rfl

/-- Proposition 3.8.9: if the restricted deck-transformation action on the fiber over `p e` is
pretransitive, then the image subgroup `p_*(π₁(E,e))` is normal in `π₁(B, b)`. -/
-- Proof sketch: pretransitivity identifies the stabilizers of different points in the chosen
-- fiber, forcing the subgroup `p_*(π₁(E,e))` to be normal.
theorem coveringSpaceAut_transitiveOnFiber_normal_fundamentalGroup_map_range
    (hp : IsPathConnectedCoveringMap p) (e : E)
    (htrans :
      letI := coveringSpaceAutFiberMulAction p e
      MulAction.IsPretransitive (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e})) :
    ((FundamentalGroup.map p e).range).Normal := by
  let ξ₀ : hp.fundamentalGroupoidMap.Fiber (mk (p e)) :=
    (hp.fundamentalGroupoidMapFiberEquiv (p e)).symm ⟨e, rfl⟩
  have hnormal : (fiberPointSubgroup ξ₀).Normal := by
    constructor
    intro n hn g
    rcases Functor.IsCovering.exists_fiberPoint_mapVertexGroup_range_eq_conjugate
        hp.fundamentalGroupoidMap_isCovering ξ₀ g with ⟨ξ, hξ⟩
    let x : p ⁻¹' {p e} := hp.fundamentalGroupoidMapFiberEquiv (p e) ξ
    letI := coveringSpaceAutFiberMulAction p e
    -- Pretransitivity moves the distinguished fiber point to the new categorical point.
    obtain ⟨α, hα⟩ := MulAction.exists_smul_eq (Aut (Over.mk (TopCat.ofHom p)))
      (⟨e, rfl⟩ : p ⁻¹' {p e}) x
    have hsub : fiberPointSubgroup ξ = fiberPointSubgroup ξ₀ := by
      -- The earlier deck-invariance lemma collapses the subgroup at `ξ` back to the base subgroup.
      simpa [x, ξ₀] using coveringSpaceAut_fundamentalGroup_map_range_eq hp e x α hα
    have hconj : MulAut.conj g • fiberPointSubgroup ξ₀ = fiberPointSubgroup ξ₀ := by
      -- Proposition 3.3.6 gives the conjugate subgroup, and pretransitivity identifies it with `ξ₀`.
      calc
        MulAut.conj g • fiberPointSubgroup ξ₀ = fiberPointSubgroup ξ := by
          symm
          exact hξ
        _ = fiberPointSubgroup ξ₀ := hsub
    have hmem : MulAut.conj g • n ∈ MulAut.conj g • fiberPointSubgroup ξ₀ :=
      Subgroup.smul_mem_pointwise_smul n (MulAut.conj g) (fiberPointSubgroup ξ₀) hn
    have hmem' : g ≫ n ≫ inv g ∈ MulAut.conj g • fiberPointSubgroup ξ₀ := by
      simpa [MulAut.conj_apply] using hmem
    -- Transport the conjugated element back to the original subgroup at the basepoint.
    simpa using (hconj ▸ hmem')
  have hnormal' : (CategoryTheory.Functor.mapVertexGroup hp.fundamentalGroupoidMap (mk e)).range.Normal := by
    simpa [ξ₀, fiberPointSubgroup_basepoint_eq_mapVertexGroup_range] using hnormal
  have hnormal'' : (((FundamentalGroupoid.map p).mapEnd (mk e)).range).Normal := by
    let q : C(E, B) := ⟨p, hp.isCoveringMap.continuous⟩
    have hq : q = p := by
      ext x
      rfl
    have hnormalqv : (CategoryTheory.Functor.mapVertexGroup (FundamentalGroupoid.map q) (mk e)).range.Normal := by
      simpa [q, IsPathConnectedCoveringMap.fundamentalGroupoidMap] using hnormal'
    have hnormalq : (((FundamentalGroupoid.map q).mapEnd (mk e)).range).Normal := by
      constructor
      intro n hn g
      rcases (Subgroup.Normal.conj_mem' hnormalqv n hn g) with ⟨x, hx⟩
      refine ⟨x, ?_⟩
      change Path.Homotopic.Quotient.map x q = g⁻¹ ≫ n ≫ g
      simpa [CategoryTheory.Functor.mapVertexGroup] using hx
    simpa [hq] using hnormalq
  -- Rewrite the distinguished categorical subgroup as the ordinary fundamental-group image.
  simpa [FundamentalGroup.map] using hnormal''

/-- Helper for Proposition 3.8.9: applying a deck transformation to the endpoint of a lifted path
matches lifting the same base path from the translated starting point. -/
private theorem coveringSpaceAut_liftPath_endpoint_comm
    (hp : IsPathConnectedCoveringMap p) (α : Aut (Over.mk (TopCat.ofHom p)))
    {b₀ b₁ : B} (γ : Path b₀ b₁) (x : p ⁻¹' {b₀}) :
    α.hom.left.hom (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm) 1) =
      hp.isCoveringMap.liftPath γ (α • x.1)
        (by
          rw [coveringSpaceAut_smul_proj p α x.1]
          exact γ.source.trans x.2.symm) 1 := by
  -- Route correction: compare the two actual lifts of `γ`, rather than pushing through another
  -- categorical fiber-transport layer.
  let hxα : γ 0 = p (α • x.1) := by
    rw [coveringSpaceAut_smul_proj p α x.1]
    exact γ.source.trans x.2.symm
  have hLiftEq :
      α.hom.left.hom.comp (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm)) =
        hp.isCoveringMap.liftPath γ (α • x.1) hxα := by
    -- Both lifts project to `γ` and start at the translated point, so uniqueness identifies them.
    apply (hp.isCoveringMap.eq_liftPath_iff' hxα).2
    constructor
    · ext t
      have hproj :
          p (α.hom.left.hom (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm) t)) =
            p (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm) t) := by
        simpa using coveringSpaceAut_smul_proj p α
          (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm) t)
      simpa [ContinuousMap.comp_apply] using
        hproj.trans
          (congr_fun (hp.isCoveringMap.liftPath_lifts γ x.1 (γ.source.trans x.2.symm)) t)
    · calc
        (α.hom.left.hom.comp (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm))) 0 =
            α.hom.left.hom ((hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm)) 0) := by
              rfl
        _ = α.hom.left.hom x.1 := by
              rw [hp.isCoveringMap.liftPath_zero]
        _ = α • x.1 := by
              rfl
  -- Evaluate the identified lifts at the endpoint.
  simpa using congrArg (fun f => f 1) hLiftEq

/-- Helper for Proposition 3.8.9: deck transformations commute with fiber translation along a base
path class. -/
private theorem coveringSpaceAut_fiberTranslationMap_comm
    (hp : IsPathConnectedCoveringMap p) (α : Aut (Over.mk (TopCat.ofHom p)))
    {b₀ b₁ : B} (f : mk b₀ ⟶ mk b₁) (x : p ⁻¹' {b₀}) :
    hp.fiberTranslationMap f
      ⟨α • x.1, by
        simpa [x.2] using (coveringSpaceAut_smul_proj p α x.1).trans x.2⟩ =
      ⟨α • (hp.fiberTranslationMap f x).1, by
        simpa using (coveringSpaceAut_smul_proj p α (hp.fiberTranslationMap f x).1).trans
          (hp.fiberTranslationMap f x).2⟩ := by
  -- Reduce the groupoid arrow to a represented path so that Example 3.3.9 applies on endpoints.
  obtain ⟨γ, rfl⟩ := Path.Homotopic.Quotient.mk_surjective f
  let xα : p ⁻¹' {b₀} :=
    ⟨α • x.1, by
      simpa [x.2] using (coveringSpaceAut_smul_proj p α x.1).trans x.2⟩
  have hleft := IsPathConnectedCoveringMap.fiberTranslationMap_fromPath_eq_liftPath_endpoint
    hp γ xα
  have hright := IsPathConnectedCoveringMap.fiberTranslationMap_fromPath_eq_liftPath_endpoint
    hp γ x
  apply Subtype.ext
  -- Rewrite both fiber translations to lifted-path endpoints and then compare those endpoints.
  simpa using
    calc
      ↑(hp.fiberTranslationMap (fromPath (Path.Homotopic.Quotient.mk γ)) xα) =
          hp.isCoveringMap.liftPath γ xα.1 (γ.source.trans xα.2.symm) 1 := by
            simpa using congrArg Subtype.val hleft
      _ = α.hom.left.hom (hp.isCoveringMap.liftPath γ x.1 (γ.source.trans x.2.symm) 1) := by
            simpa [xα] using (coveringSpaceAut_liftPath_endpoint_comm hp α γ x).symm
      _ = α.hom.left.hom (hp.fiberTranslationMap (fromPath (Path.Homotopic.Quotient.mk γ)) x).1 := by
            simpa using congrArg (fun z => α.hom.left.hom z) (congrArg Subtype.val hright).symm

/-- Helper for Proposition 3.8.9: fiber translation along a groupoid morphism and then back along
its inverse returns the original point of the fiber. -/
private theorem fiberTranslationMap_apply_inv
    (hp : IsPathConnectedCoveringMap p) {b₀ b₁ : B} (f : mk b₀ ⟶ mk b₁)
    (x : p ⁻¹' {b₁}) :
    hp.fiberTranslationMap f (hp.fiberTranslationMap (CategoryTheory.Groupoid.inv f) x) = x := by
  -- Transport the categorical inverse-translation identity to the ordinary fiber.
  apply (hp.fundamentalGroupoidMapFiberEquiv b₁).symm.injective
  calc
    (hp.fundamentalGroupoidMapFiberEquiv b₁).symm
        (hp.fiberTranslationMap f (hp.fiberTranslationMap (CategoryTheory.Groupoid.inv f) x))
        = Functor.IsCovering.fiberTranslationMap hp.fundamentalGroupoidMap_isCovering f
            (Functor.IsCovering.fiberTranslationMap hp.fundamentalGroupoidMap_isCovering
              (CategoryTheory.Groupoid.inv f)
              ((hp.fundamentalGroupoidMapFiberEquiv b₁).symm x)) := by
                simp [IsPathConnectedCoveringMap.fiberTranslationMap, Function.comp]
    _ = Functor.IsCovering.fiberTranslationMap hp.fundamentalGroupoidMap_isCovering
          (CategoryTheory.Groupoid.inv f ≫ f)
          ((hp.fundamentalGroupoidMapFiberEquiv b₁).symm x) := by
            -- Compose the two categorical transport maps before comparing with the identity.
            symm
            exact congrFun
              (Functor.IsCovering.fiberTranslationMap_comp hp.fundamentalGroupoidMap_isCovering
                (CategoryTheory.Groupoid.inv f) f)
              ((hp.fundamentalGroupoidMapFiberEquiv b₁).symm x)
    _ = Functor.IsCovering.fiberTranslationMap hp.fundamentalGroupoidMap_isCovering
          (𝟙 (mk b₁))
          ((hp.fundamentalGroupoidMapFiberEquiv b₁).symm x) := by
            simp
    _ = (hp.fundamentalGroupoidMapFiberEquiv b₁).symm x := by
          exact congrFun
            (Functor.IsCovering.fiberTranslationMap_id hp.fundamentalGroupoidMap_isCovering
              (mk b₁))
            ((hp.fundamentalGroupoidMapFiberEquiv b₁).symm x)

/-- Helper for Proposition 3.8.9: under the chosen-fiber transitivity hypothesis, two points of
`E` lie in the same deck-transformation orbit exactly when they have the same image in `B`. -/
private theorem coveringSpaceAut_orbitRel_iff_proj_eq
    [PathConnectedSpace B]
    (hp : IsPathConnectedCoveringMap p) (e : E)
    (htrans :
      letI := coveringSpaceAutFiberMulAction p e
      MulAction.IsPretransitive (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e}))
    {x y : E} :
    MulAction.orbitRel (Aut (Over.mk (TopCat.ofHom p))) E x y ↔ p x = p y := by
  constructor
  · exact coveringSpaceAut_proj_eq_of_orbitRel p
  · intro hxy
    let γ : Path (p e) (p x) := PathConnectedSpace.somePath (p e) (p x)
    let f : mk (p e) ⟶ mk (p x) := fromPath ⟦γ⟧
    let x' : p ⁻¹' {p x} := ⟨x, rfl⟩
    let y' : p ⁻¹' {p x} := ⟨y, hxy.symm⟩
    let x₀ : p ⁻¹' {p e} := hp.fiberTranslationMap (CategoryTheory.Groupoid.inv f) x'
    let y₀ : p ⁻¹' {p e} := hp.fiberTranslationMap (CategoryTheory.Groupoid.inv f) y'
    letI := coveringSpaceAutFiberMulAction p e
    -- Pull both points back to the chosen fiber and use pretransitivity there.
    obtain ⟨α, hα⟩ := MulAction.exists_smul_eq (Aut (Over.mk (TopCat.ofHom p))) y₀ x₀
    have hα' : ⟨α • y₀.1, by
          simpa [y₀.2] using (coveringSpaceAut_smul_proj p α y₀.1).trans y₀.2⟩ = x₀ := by
      simpa using hα
    have hpush := coveringSpaceAut_fiberTranslationMap_comm hp α f y₀
    rw [hα'] at hpush
    have hpush : hp.fiberTranslationMap f x₀ =
        ⟨α • (hp.fiberTranslationMap f y₀).1, by
          simpa using (coveringSpaceAut_smul_proj p α (hp.fiberTranslationMap f y₀).1).trans
            (hp.fiberTranslationMap f y₀).2⟩ := by
      -- Push the chosen-fiber deck transformation forward along `f`.
      exact hpush
    have hxback : hp.fiberTranslationMap f x₀ = x' := by
      simpa [x₀] using fiberTranslationMap_apply_inv hp f x'
    have hyback : hp.fiberTranslationMap f y₀ = y' := by
      simpa [y₀] using fiberTranslationMap_apply_inv hp f y'
    have hxval : (hp.fiberTranslationMap f x₀).1 = x := by
      simpa [x'] using congrArg Subtype.val hxback
    have hyval : (hp.fiberTranslationMap f y₀).1 = y := by
      simpa [y'] using congrArg Subtype.val hyback
    have hpushval : α • (hp.fiberTranslationMap f y₀).1 = (hp.fiberTranslationMap f x₀).1 := by
      simpa using (congrArg Subtype.val hpush).symm
    -- Translating back recovers the original points, so `x` and `y` lie in the same orbit.
    refine ⟨α, ?_⟩
    calc
      α • y = α • (hp.fiberTranslationMap f y₀).1 := by
        rw [hyval]
      _ = (hp.fiberTranslationMap f x₀).1 := hpushval
      _ = x := hxval

/-- If the base is path connected and the restricted deck-transformation action on one fiber is
pretransitive, then the canonical map from `E / Aut(E)` to `B` is a homeomorphism. -/
-- Proof sketch: path connectedness transports fiberwise pretransitivity from the chosen fiber to
-- every fiber by lifting base paths and using uniqueness of path lifting for deck
-- transformations. The descended orbit map is then bijective, and on evenly covered
-- neighborhoods it is identified with the original covering map modulo permutation of sheets.
theorem coveringSpaceAut_transitiveOnFiber_quotientMap_isHomeomorph
    [PathConnectedSpace B]
    (hp : IsPathConnectedCoveringMap p) (e : E)
    (htrans :
      letI := coveringSpaceAutFiberMulAction p e
      MulAction.IsPretransitive (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e})) :
    IsHomeomorph (coveringSpaceAutOrbitProjection p) := by
  refine ⟨(coveringSpaceAutOrbitProjection p).continuous, ?_, ?_⟩
  · intro U hU
    have hpre : IsOpen
        ((Quotient.mk'' : E → E /[Aut (Over.mk (TopCat.ofHom p))]) ⁻¹' U) := by
      simpa using
        (isOpen_coinduced
          (f := (Quotient.mk'' : E → E /[Aut (Over.mk (TopCat.ofHom p))]))).mp hU
    have himage : (coveringSpaceAutOrbitProjection p) '' U =
        p '' ((Quotient.mk'' : E → E /[Aut (Over.mk (TopCat.ofHom p))]) ⁻¹' U) := by
      -- The descended orbit map has the same image as `p` on representatives of `U`.
      ext b
      constructor
      · rintro ⟨q, hq, hqeq⟩
        obtain ⟨x, rfl⟩ := Quotient.mk''_surjective q
        exact ⟨x, hq, hqeq⟩
      · rintro ⟨x, hx, rfl⟩
        exact ⟨Quotient.mk'' x, hx, rfl⟩
    rw [himage]
    -- The original covering map is open, so the descended orbit map is open as well.
    exact hp.isCoveringMap.isOpenMap _ hpre
  · constructor
    · intro q₁ q₂ hq
      refine Quotient.inductionOn₂' q₁ q₂ (fun x y hxy => ?_) hq
      -- Equal images mean the representatives have the same basepoint, hence are orbit-related.
      exact Quotient.eq''.2
        ((coveringSpaceAut_orbitRel_iff_proj_eq hp e htrans).2
          (by simpa [coveringSpaceAutOrbitProjection] using hxy))
    · intro b
      -- Surjectivity is inherited directly from the covering map.
      obtain ⟨x, rfl⟩ := hp.surjective b
      exact ⟨Quotient.mk'' x, rfl⟩

/-- In a locally path-connected base, fiberwise pretransitivity of deck transformations upgrades
the normality clause of Proposition 3.8.9 to the canonical regular-covering owner. -/
theorem coveringSpaceAut_transitiveOnFiber_isRegularCoveringMap
    (hp : IsPathConnectedCoveringMap p) (e : E)
    (htrans :
      letI := coveringSpaceAutFiberMulAction p e
      MulAction.IsPretransitive (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e})) :
    IsRegularCoveringMap p e := by
  refine
    { toIsPathConnectedCoveringMap := hp
      normal_fundamentalGroup_map_range := ?_ }
  exact coveringSpaceAut_transitiveOnFiber_normal_fundamentalGroup_map_range hp e htrans

/-- Proposition 3.8.9: over a locally path-connected, path-connected base, fiberwise
pretransitivity of deck transformations implies regularity at the chosen fiber point and
identifies the orbit quotient `E / Aut(E)` with `B`. -/
theorem coveringSpaceAut_transitiveOnFiber_regular_and_quotientMap_isHomeomorph
    [LocPathConnectedSpace B] [PathConnectedSpace B]
    (hp : IsPathConnectedCoveringMap p) (e : E)
    (htrans :
      letI := coveringSpaceAutFiberMulAction p e
      MulAction.IsPretransitive (Aut (Over.mk (TopCat.ofHom p))) (p ⁻¹' {p e})) :
    IsRegularCoveringMap p e ∧
      IsHomeomorph (coveringSpaceAutOrbitProjection p) := by
  exact
    ⟨coveringSpaceAut_transitiveOnFiber_isRegularCoveringMap hp e htrans,
      coveringSpaceAut_transitiveOnFiber_quotientMap_isHomeomorph hp e htrans⟩
