import Mathlib.Analysis.SpecialFunctions.Elliptic.Weierstrass
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs

noncomputable section

/- Semantic recall:
- `lean_leansearch`: `PeriodPair.lattice`, `PeriodPair.lattice_eq_span_range_basis`,
  `Matrix.GeneralLinearGroup`.
- Verified locally: `PeriodPair`, `PeriodPair.ω₁`, `PeriodPair.ω₂`, `PeriodPair.lattice`, and the
  `GL(2, ℤ)` action on `Fin 2 → ℂ` via `Matrix.mulVec` after entrywise casting `ℤ → ℂ`.
- Owner choice: state the exercise directly for the canonical `PeriodPair.lattice` owner, with the
  unimodular basis-change matrix acting on the column vector `![ω₁, ω₂]`. The orientation-preserving
  `SL(2, ℤ)` formulation belongs to normalized period pairs, not to bare `PeriodPair`.
-/

/-- Exercise 1.4: two lattices in `ℂ` generated by period pairs are equal if and only if their
ordered generators differ by a unimodular change-of-basis matrix. -/
theorem periodPair_lattice_eq_iff_exists_gl2z (L L' : PeriodPair) :
    L.lattice = L'.lattice ↔
      ∃ A : GL (Fin 2) ℤ,
        ![L'.ω₁, L'.ω₂] =
          Matrix.mulVec ((A : Matrix (Fin 2) (Fin 2) ℤ).map (Int.castRingHom ℂ))
            ![L.ω₁, L.ω₂] :=
  sorry
