import Mathlib
import Mathlib.Tactic.Recall
import stacks_project.Chap09.Example_9_7_4_Degree_of_a_rational_function_field

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open scoped RatFunc

section

variable (k : Type u) (F : Type v) [Field k] [Field F] [Algebra k F] [FiniteDimensional k F]

/- A finite extension of fields is essentially of finite type via the canonical
`Algebra.EssFiniteType` instance induced by finite-dimensionality. -/
#synth Algebra.EssFiniteType k F

end

section

open IntermediateField

variable {k : Type u} [Field k]

/-- Helper for Lemma 9.7.5: the top intermediate field of `k⟮X⟯ / k` is generated by the
singleton `{X}`. -/
lemma ratFunc_top_fg : (⊤ : IntermediateField k k⟮X⟯).FG := by
  -- The rational function field is generated by adjoining the single element `X`.
  simpa [Finset.coe_singleton, RatFunc.adjoin_X] using
    (IntermediateField.fg_adjoin_finset (F := k) ({(RatFunc.X : k⟮X⟯)} : Finset k⟮X⟯))

/-- Lemma 9.7.5: the rational function field `k⟮X⟯ = k(X)` is a finitely generated field
extension of `k`, generated by the single element `X`. -/
-- Proof sketch: use `IntermediateField.fg_top_iff` together with `RatFunc.adjoin_X` to show
-- that `k⟮X⟯` is generated as an intermediate field by the singleton `{X}`.
theorem ratFunc_essFiniteType : Algebra.EssFiniteType k k⟮X⟯ := by
  -- Translate essential finite type into finite generation of the top intermediate field.
  rw [← IntermediateField.fg_top_iff]
  -- The helper records the source proof's single-generator argument.
  exact ratFunc_top_fg

/- The converse fails for the rational function field: `k⟮X⟯` is essentially of finite type over
`k`, but by Example 9.7.4 it is not finite-dimensional over `k`. -/
recall ratFunc_not_finiteDimensional

end
