import Mathlib.RingTheory.MvPolynomial.Basic
import StacksProject_2024.Chap10.Lemma_10_17_2
import StacksProject_2024.Chap29.Definition_29_7_1

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

open CategoryTheory
open MvPolynomial
open scoped AlgebraicGeometry PrimeSpectrum

namespace AlgebraicGeometry

-- Semantic recall: `lean_leansearch` returned the topological owner `Dense`; local Chapter 29
-- inspection confirmed that the scheme-theoretic side is the project owner
-- `AlgebraicGeometry.schemeTheoreticClosure` from `Definition_29_7_1`.
-- The Stacks example tag is `01RC`, matching the source URL `/tag/01RC`.

universe u

variable (k : Type u) [Field k]

/-- Variables for the Example 29.7.2 affine algebra: one variable `x` and countably many variables
`z_n` indexed by `n : ℕ`, corresponding to the source's `z_{n+1}`. -/
def example29_7_2Var : Type := Unit ⊕ ℕ

/-- The polynomial variable `x` used in Example 29.7.2. -/
def example29_7_2x : MvPolynomial example29_7_2Var k :=
  X (Sum.inl ())

/-- The polynomial variable `z_n` used in Example 29.7.2, with `n : ℕ` representing the source's
`z_{n+1}`. -/
def example29_7_2z (n : ℕ) : MvPolynomial example29_7_2Var k :=
  X (Sum.inr n)

/-- The relation ideal generated by the monomials `x^(n+1) z_n`. This is the source algebra
`k[x, z_1, z_2, \ldots]/(x^n z_n)` after reindexing the `z`-variables by `ℕ`. -/
def example29_7_2RelationIdeal : Ideal (MvPolynomial example29_7_2Var k) :=
  Ideal.span (Set.range fun n : ℕ ↦ example29_7_2x k ^ (n + 1) * example29_7_2z k n)

/-- The affine coordinate ring used in Example 29.7.2. -/
abbrev example29_7_2Ring :=
  MvPolynomial example29_7_2Var k ⧸ example29_7_2RelationIdeal k

/-- The class of `x` in the quotient ring of Example 29.7.2. -/
def example29_7_2xbar : example29_7_2Ring k :=
  Ideal.Quotient.mk _ (example29_7_2x k)

/-- The class of `z_n` in the quotient ring of Example 29.7.2. -/
def example29_7_2zbar (n : ℕ) : example29_7_2Ring k :=
  Ideal.Quotient.mk _ (example29_7_2z k n)

/-- The ideal `I = (z_1, z_2, \ldots)` of Example 29.7.2, expressed with `ℕ`-indexing. -/
def example29_7_2Ideal : Ideal (example29_7_2Ring k) :=
  Ideal.span (Set.range fun n : ℕ ↦ example29_7_2zbar k n)

/-- The affine scheme `X = Spec(A)` of Example 29.7.2. -/
abbrev example29_7_2Scheme :=
  Spec (CommRingCat.of (example29_7_2Ring k))

/-- The open subscheme `U = X \setminus V(I)` of Example 29.7.2. -/
def example29_7_2Open : (example29_7_2Scheme k).Opens :=
  ⟨(V(example29_7_2Ideal k))ᶜ,
    (PrimeSpectrum.isClosed_zeroLocus _).isOpen_compl⟩

/-- The underlying open subset of the source open subscheme `U = X \setminus V(I)`. -/
abbrev example29_7_2OpenSet : Set (example29_7_2Scheme k) :=
  example29_7_2Open k

/-- The canonical source expression `U = X \setminus V(I)`. -/
@[simp]
theorem example29_7_2_open_eq_compl_V :
    example29_7_2OpenSet k = (V(example29_7_2Ideal k))ᶜ := rfl

/-- The canonical union expression for the source open `U = X \setminus V(I)`, rewritten as the
union of the principal opens `D(z_n)`. -/
theorem example29_7_2_open_eq_iSup_D :
    example29_7_2Open k = ⨆ n : ℕ, D(example29_7_2zbar k n) := by
  classical
  apply TopologicalSpace.Opens.ext
  ext x
  simpa [example29_7_2Open, example29_7_2Ideal, PrimeSpectrum.zeroLocus_span] using
    congrArg (fun s : Set (PrimeSpectrum (example29_7_2Ring k)) ↦ x ∈ s)
      (iUnion_D_eq_compl_zeroLocus_range (example29_7_2zbar k)).symm

/-- Example 29.7.2 (1): for the affine scheme
`X = Spec(k[x, z_1, z_2, \ldots]/(x^n z_n))` and the open subscheme
`U = X \setminus V((z_1, z_2, \ldots))`, the scheme theoretic closure of `U` is all of `X`. -/
@[stacks 01RC]
theorem example29_7_2_schemeTheoreticClosure_eq_self :
    schemeTheoreticClosure (example29_7_2Open k) = example29_7_2Scheme k := sorry

/-- Example 29.7.2 (2): in the same affine scheme, the open subscheme
`U = X \setminus V((z_1, z_2, \ldots))` is not dense for the underlying topological space of
`X`. -/
@[stacks 01RC]
theorem example29_7_2_not_dense :
    ¬ Dense (example29_7_2OpenSet k) := sorry

end AlgebraicGeometry
