import StacksProject_2024.stacks_project.Chap29.RelativeProjProjectiveBundleHypothesis

-- Declarations for this item will be appended below by the statement pipeline.

open AlgebraicGeometry
open scoped AlgebraicGeometry

noncomputable section

universe u

namespace AlgebraicGeometry.Scheme.Hom

/- Semantic source/core/bridge check:
- source item: Stacks, Example `07ZS`, whose content is that a relative `Proj` morphism obtained
  from a graded algebra generated in degree `1` by a finite type module is projective, hence
  proper;
- source-facing layer kept here: a chosen relative `Proj` presentation `P : RelativeProjPresentation p`
  together with the source-faithful degree-one generation / finite-type-module hypothesis owner
  `RelativeProjGeneratedByDegreeOneFiniteModuleProjectiveBundleHypothesis P`;
- canonical chapter owner reused here: `AlgebraicGeometry.Projective`.

This file is therefore a bridge/view file: it reuses the shared degree-one projective-bundle
hypothesis owner and exposes the Chapter 29 projective conclusion. The downstream properness
consequence already has the canonical owner `LocallyProjective.isProper` in
`Lemma_29_43_5.lean`, so it is not repeated here as a duplicate local theorem. -/

section

variable {S X : Scheme.{u}} {p : X ⟶ S}

/-- Example 29.43.2: a relative `Proj` morphism presented by a graded algebra generated by a
finite type degree-one piece is projective. -/
@[stacks 07ZS]
theorem relativeProj_projective
    (P : RelativeProjPresentation p)
    (h : RelativeProjGeneratedByDegreeOneFiniteModuleProjectiveBundleHypothesis P) :
    Projective p := by
  rcases h.presentation with ⟨P', π, hdeg1, hπ, i, hi⟩
  exact ⟨⟨P', π, P.degreePiece 1, hdeg1, inferInstance, hπ, i, hi⟩⟩

/-- The degree-one generation / finite-type-module hypothesis of Example 29.43.2 makes the
relative `Proj` morphism projective. -/
theorem RelativeProjGeneratedByDegreeOneFiniteModuleProjectiveBundleHypothesis.projective
    {P : RelativeProjPresentation p}
    (h : RelativeProjGeneratedByDegreeOneFiniteModuleProjectiveBundleHypothesis P) :
    Projective p :=
  relativeProj_projective _ h

end

end AlgebraicGeometry.Scheme.Hom
