import LinearRepresentations_Serre_1977.Chap18.Exercise_18_18_3_2.RegularValueCongruenceSourceFaithful

#check regularValueCongruenceSourceFaithfulStatement
#check Representation.regularValueCongruenceSourceFaithfulStatement
#check regularValueCongruenceSourceFaithfulStatement_of_canonicalProductInput
