import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.EmptyKoszulBasics
import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.SingletonTensorTerms
import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.SingletonDifferential
import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.HeadTailExactness
import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.FinConsExteriorSplit
import stacks_proof.stacks_project.Chap10.Remark_10_69_7_Other_types_of_regular_sequences.TensorWindowTransport
