import ProbabilityTheory_Klenke_2020.Chap12.Definition_12_6
import ProbabilityTheory_Klenke_2020.Chap12.Remark_12_2
import ProbabilityTheory_Klenke_2020.Chap12.Remark_12_7
import ProbabilityTheory_Klenke_2020.Chap02.Definition_2_34
import ProbabilityTheory_Klenke_2020.Chap07.Definition_7_2
import ProbabilityTheory_Klenke_2020.Chap12.Theorem_12_14

-- Declarations for this item will be appended below by the statement pipeline.

open Filter MeasureTheory ProbabilityTheory
open scoped BigOperators ProbabilityTheory

universe u v

variable {Ω : Type u} [MeasurableSpace Ω]
variable {E : Type v} [MeasurableSpace E]
variable {μ : Measure Ω} [IsFiniteMeasure μ]

section

variable {k : ℕ} {X : ℕ → Ω → E} {φ : (Fin k → E) → ℝ}

local notation "Xseq" => Function.swap X
local notation "ψ" => (fun x : ℕ → E ↦ φ (fun i ↦ x i))
local notation "Y" => ψ ∘ Xseq
local notation "G" => μ[Y | exchangeableSigmaAlgebra Xseq]

/-- Helper for Theorem 12.17: the `l`th tail stage of `X` is the sigma-algebra generated by the
coordinates from `l` onward. -/
private abbrev tailStage (l : ℕ) : MeasurableSpace Ω :=
  ⨆ i ∈ Set.Ici l, MeasurableSpace.comap (X i) inferInstance

/-- Helper for Theorem 12.17: the test functional `ψ` on sequence space is measurable whenever
the original `k`-coordinate map `φ` is measurable. -/
private theorem measurable_psi (hφ_meas : Measurable φ) :
    Measurable ψ := by
  -- Proof comment: the coordinate projection `x ↦ fun i ↦ x i` is measurable into `E^k`, so
  -- composing it with `φ` yields the required measurability.
  refine hφ_meas.comp ?_
  refine measurable_pi_lambda _ fun i ↦ ?_
  simpa using (measurable_pi_apply (i : ℕ) : Measurable fun x : ℕ → E ↦ x i)

/-- Helper for Theorem 12.17: `permutePrefix n ρ` is measurable on sequence space. -/
private theorem measurable_permutePrefix (n : ℕ) (ρ : Equiv.Perm (Fin n)) :
    Measurable (permutePrefix n ρ : (ℕ → E) → ℕ → E) := by
  -- Proof comment: each output coordinate is evaluation at the corresponding extended
  -- permutation index.
  refine measurable_pi_lambda _ fun i ↦ ?_
  simpa [permutePrefix, Function.comp] using
    (measurable_pi_apply ((ρ.extendDomain Fin.equivSubtype) i) :
      Measurable fun x : ℕ → E ↦ x ((ρ.extendDomain Fin.equivSubtype) i))

/-- Helper for Theorem 12.17: on the first `n` coordinates, `permutePrefix n ρ` acts by `ρ`. -/
private theorem permutePrefix_apply_fin {n : ℕ} (ρ : Equiv.Perm (Fin n)) (x : ℕ → E) (i : Fin n) :
    permutePrefix n ρ x i = x (ρ i) := by
  -- Proof comment: on the embedded copy of `Fin n`, the extended permutation is exactly `ρ`.
  simp [permutePrefix, Equiv.Perm.extendDomain_apply_subtype]

/-- Helper for Theorem 12.17: exchangeability makes the sample-sequence map a.e.-measurable. -/
private theorem aemeasurableProcessSwap_of_isExchangeable (hX : IsExchangeable X μ) :
    AEMeasurable Xseq μ := by
  -- Proof comment: each coordinate has the law of `X 0`, hence every coordinate map is
  -- a.e.-measurable and the product map is a.e.-measurable.
  refine aemeasurable_pi_lambda _ fun i ↦ ?_
  simpa [Function.swap] using (hX.identDistrib 0 i).aemeasurable_snd

/-- Helper for Theorem 12.17: exchangeability is invariant under permuting the first `n`
coordinates of the sample-sequence map. -/
private theorem identDistrib_process_permutePrefix_of_isExchangeable
    (hX : IsExchangeable X μ) (n : ℕ) (ρ : Equiv.Perm (Fin n)) :
    IdentDistrib Xseq (permutePrefix n ρ ∘ Xseq) μ μ := by
  let σ : ℕ ≃ ℕ := ρ.extendDomain Fin.equivSubtype
  have hXseq_ae := aemeasurableProcessSwap_of_isExchangeable (X := X) (μ := μ) hX
  have hperm_Xseq_ae :
      AEMeasurable (permutePrefix n ρ ∘ Xseq) μ := by
    -- Proof comment: compose the measurable finite-prefix permutation with the a.e.-measurable
    -- sample-sequence map.
    exact (measurable_permutePrefix (E := E) n ρ).comp_aemeasurable hXseq_ae
  rw [ProbabilityTheory.identDistrib_iff_forall_finset_identDistrib hXseq_ae hperm_Xseq_ae]
  intro s
  let e := s.orderIsoOfFin rfl
  let u : Fin s.card ↪ ℕ := (s.orderEmbOfFin rfl).toEmbedding
  let v : Fin s.card ↪ ℕ := ⟨fun i ↦ σ (u i), σ.injective.comp u.injective⟩
  have htuple :
      IdentDistrib
        (fun ω ↦ fun i : Fin s.card ↦ X (u i) ω)
        (fun ω ↦ fun i : Fin s.card ↦ X (v i) ω) μ μ :=
    (isExchangeable_iff_identDistrib_of_pairwise_distinct X μ).mp hX _ u v
  let es : (Fin s.card → E) ≃ᵐ (s → E) := MeasurableEquiv.piCongrLeft (fun _ : s ↦ E) e
  have hrestrict := htuple.comp es.measurable
  have hleft :
      es ∘ (fun ω ↦ fun i : Fin s.card ↦ X (u i) ω) =
        fun ω ↦ s.restrict (Xseq ω) := by
    -- Proof comment: identify the left finite-dimensional marginal with restriction of `Xseq`.
    funext ω
    ext j
    let xu : (i : Fin s.card) → (fun _ : s ↦ E) (e i) := fun i ↦ X (u i) ω
    have h := Equiv.piCongrLeft_apply_apply (fun _ : s ↦ E) e xu (e.symm j)
    have hindex : u (e.symm j) = (j : ℕ) := by
      change (s.orderEmbOfFin rfl) ((s.orderIsoOfFin rfl).symm j) = (j : ℕ)
      rw [← Finset.coe_orderIsoOfFin_apply]
      simp
    simpa [xu, es, MeasurableEquiv.piCongrLeft, e, Function.swap, Finset.restrict, hindex]
      using h
  have hright :
      es ∘ (fun ω ↦ fun i : Fin s.card ↦ X (v i) ω) =
        fun ω ↦ s.restrict (permutePrefix n ρ (Xseq ω)) := by
    -- Proof comment: after extending `ρ` to `ℕ`, the right marginal is the restricted permuted
    -- sample sequence.
    funext ω
    ext j
    let xv : (i : Fin s.card) → (fun _ : s ↦ E) (e i) := fun i ↦ X (v i) ω
    have h := Equiv.piCongrLeft_apply_apply (fun _ : s ↦ E) e xv (e.symm j)
    have hindex : v (e.symm j) = σ j := by
      change σ ((s.orderEmbOfFin rfl) ((s.orderIsoOfFin rfl).symm j)) = σ j
      rw [← Finset.coe_orderIsoOfFin_apply]
      simp
    simpa [xv, es, MeasurableEquiv.piCongrLeft, e, Function.swap, Finset.restrict,
      permutePrefix, Function.comp, σ, hindex] using h
  simpa [hleft, hright] using hrestrict

/-- Helper for Theorem 12.17: the permutation average is measurable with respect to the
finite exchangeable `σ`-algebra. -/
private theorem exchangeableAverage_measurable_nExchangeableSigmaAlgebra
    (hφ_meas : Measurable φ) (n : ℕ) :
    Measurable[nExchangeableSigmaAlgebra Xseq n] (exchangeableAverage n ψ ∘ Xseq) := by
  have hψ_meas : Measurable ψ := measurable_psi (φ := φ) hφ_meas
  -- Proof comment: first place the average itself in the sequence-space symmetric
  -- `σ`-algebra, then pull it back along `Xseq`.
  have havg_meas :
      Measurable (exchangeableAverage n ψ : (ℕ → E) → ℝ) := by
    have hsum :
        Measurable (fun x : ℕ → E ↦
          (∑ ρ : Equiv.Perm (Fin n), ψ (permutePrefix n ρ x) : ℝ)) := by
      simpa using
        (Finset.measurable_sum (Finset.univ : Finset (Equiv.Perm (Fin n)))
          fun ρ hρ ↦ hψ_meas.comp (measurable_permutePrefix (E := E) n ρ))
    simpa [exchangeableAverage] using hsum.div_const (Nat.factorial n : ℝ)
  have havg_exchangeable :
      Measurable[nSymmetricSequenceSigmaAlgebra n] (exchangeableAverage n ψ) := by
    let f : {f : (ℕ → E) → ℝ // Measurable f ∧ IsNSymmetricSequenceMap n f} :=
      ⟨exchangeableAverage n ψ, havg_meas, exchangeableAverage_isNSymmetric n ψ⟩
    rw [measurable_iff_comap_le]
    exact le_iSup_of_le f le_rfl
  exact havg_exchangeable.comp (comap_measurable Xseq)

/-- Helper for Theorem 12.17: on events from the finite exchangeable `σ`-algebra, the original
test functional and any finite prefix permutation have the same set integral. -/
private theorem setIntegral_eq_on_nExchangeable_event_of_isExchangeable
    (hX : IsExchangeable X μ) (hXseq_meas : Measurable Xseq) (hφ_meas : Measurable φ)
    (n : ℕ) (ρ : Equiv.Perm (Fin n))
    {A : Set Ω} (hA : MeasurableSet[nExchangeableSigmaAlgebra Xseq n] A) :
    ∫ ω in A, ψ (Xseq ω) ∂μ =
      ∫ ω in A, ψ (permutePrefix n ρ (Xseq ω)) ∂μ := by
  rcases (measurableSet_nExchangeableSigmaAlgebra_iff n Xseq A).1 hA with
    ⟨B, hB_meas, hB_symm, hA_eq⟩
  have hA_meas : MeasurableSet A := (nExchangeableSigmaAlgebra_le hXseq_meas n) _ hA
  let χ : (ℕ → E) → ℝ := B.indicator ψ
  have hχ_meas : Measurable χ := (measurable_psi (φ := φ) hφ_meas).indicator hB_meas
  have hχ_int :
      ∫ ω, χ (Xseq ω) ∂μ =
        ∫ ω, χ (permutePrefix n ρ (Xseq ω)) ∂μ := by
    -- Proof comment: compare the whole-space integrals through equality in law of the two
    -- sequence-valued maps.
    exact
      (identDistrib_process_permutePrefix_of_isExchangeable (X := X) (μ := μ) hX n ρ).comp
        hχ_meas |>.integral_eq
  have hleft :
      (fun ω ↦ χ (Xseq ω)) = A.indicator (fun ω ↦ ψ (Xseq ω)) := by
    -- Proof comment: the indicator on sequence space becomes the event indicator on `Ω`.
    funext ω
    by_cases hω : Xseq ω ∈ B
    · simp [χ, hA_eq, hω]
    · simp [χ, hA_eq, hω]
  have hright :
      (fun ω ↦ χ (permutePrefix n ρ (Xseq ω))) =
        A.indicator (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) := by
    -- Proof comment: `B` is invariant under all `n`-prefix permutations, so membership can be
    -- checked on the unpermuted sequence.
    funext ω
    have hmem : permutePrefix n ρ (Xseq ω) ∈ B ↔ Xseq ω ∈ B := by
      exact Set.ext_iff.mp (hB_symm ρ) (Xseq ω)
    by_cases hω : Xseq ω ∈ B
    · have hperm : permutePrefix n ρ (Xseq ω) ∈ B := hmem.mpr hω
      simp [χ, hA_eq, hω, hperm]
    · have hperm : permutePrefix n ρ (Xseq ω) ∉ B := fun h ↦ hω (hmem.mp h)
      simp [χ, hA_eq, hω, hperm]
  calc
    ∫ ω in A, ψ (Xseq ω) ∂μ = ∫ ω, χ (Xseq ω) ∂μ := by
      rw [hleft, MeasureTheory.integral_indicator hA_meas]
    _ = ∫ ω, χ (permutePrefix n ρ (Xseq ω)) ∂μ := hχ_int
    _ = ∫ ω in A, ψ (permutePrefix n ρ (Xseq ω)) ∂μ := by
      rw [hright, MeasureTheory.integral_indicator hA_meas]

/-- Helper for Theorem 12.17: the finite exchangeable conditional expectation equals the
permutation average under the finite-measure hypotheses used in Theorem 12.17. -/
private theorem condExp_eq_exchangeableAverage_of_isExchangeable_finite
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) (n : ℕ) :
    μ[Y | nExchangeableSigmaAlgebra Xseq n] =ᵐ[μ]
      exchangeableAverage n ψ ∘ Xseq := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: measurability into the countable product is coordinatewise.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  have hm :
      nExchangeableSigmaAlgebra Xseq n ≤ (inferInstance : MeasurableSpace Ω) :=
    nExchangeableSigmaAlgebra_le hXseq_meas n
  let g : Equiv.Perm (Fin n) → Ω → ℝ := fun ρ ω ↦ ψ (permutePrefix n ρ (Xseq ω))
  have hg_int : ∀ ρ : Equiv.Perm (Fin n), Integrable (g ρ) μ := by
    intro ρ
    -- Proof comment: every permutation summand has the same law as `Y`.
    exact
      (identDistrib_process_permutePrefix_of_isExchangeable (X := X) (μ := μ) hX n ρ).comp
        (measurable_psi (φ := φ) hφ_meas) |>.integrable_snd hφ_int
  have hsum_int : Integrable (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) μ := by
    simpa [g] using
      (MeasureTheory.integrable_finset_sum (μ := μ)
        (Finset.univ : Finset (Equiv.Perm (Fin n))) fun ρ hρ ↦ hg_int ρ)
  have havg_int : Integrable (exchangeableAverage n ψ ∘ Xseq) μ := by
    simpa [exchangeableAverage, Function.comp, g] using
      hsum_int.div_const (Nat.factorial n : ℝ)
  have havg_meas :
      AEStronglyMeasurable[nExchangeableSigmaAlgebra Xseq n] (exchangeableAverage n ψ ∘ Xseq) μ :=
    Measurable.aestronglyMeasurable
      (exchangeableAverage_measurable_nExchangeableSigmaAlgebra
        (X := X) (φ := φ) hφ_meas n)
  have hfactorial_ne_zero : (Nat.factorial n : ℝ) ≠ 0 := by
    exact_mod_cast Nat.factorial_ne_zero n
  refine
    (MeasureTheory.ae_eq_condExp_of_forall_setIntegral_eq hm hφ_int
      (fun s hs hs_fin ↦ havg_int.integrableOn)
      (fun s hs hs_fin ↦ by
        have hsum_eq :
            ∫ ω in s, (∑ ρ : Equiv.Perm (Fin n), g ρ ω : ℝ) ∂μ =
              ∑ ρ : Equiv.Perm (Fin n), ∫ ω in s, g ρ ω ∂μ := by
          simpa [g] using
            (MeasureTheory.integral_finset_sum (μ := μ.restrict s)
              (Finset.univ : Finset (Equiv.Perm (Fin n)))
              fun ρ hρ ↦ (hg_int ρ).integrableOn)
        have hperm_sum :
            (∑ ρ : Equiv.Perm (Fin n), ∫ ω in s, g ρ ω ∂μ) =
              ∑ ρ : Equiv.Perm (Fin n), ∫ ω in s, ψ (Xseq ω) ∂μ := by
          refine Finset.sum_congr rfl ?_
          intro ρ hρ
          exact
            (setIntegral_eq_on_nExchangeable_event_of_isExchangeable
              (X := X) (μ := μ) (φ := φ) hX hXseq_meas hφ_meas n ρ hs).symm
        calc
          ∫ ω in s, exchangeableAverage n ψ (Xseq ω) ∂μ =
              ∫ ω in s, ((∑ ρ : Equiv.Perm (Fin n), g ρ ω : ℝ) / Nat.factorial n) ∂μ := by
                simp [exchangeableAverage, g]
          _ = (∫ ω in s, (∑ ρ : Equiv.Perm (Fin n), g ρ ω : ℝ) ∂μ) / Nat.factorial n := by
                simpa [MeasureTheory.integral, g] using
                  (MeasureTheory.integral_div (μ := μ.restrict s) (Nat.factorial n : ℝ)
                    (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω))
          _ = (∑ ρ : Equiv.Perm (Fin n), ∫ ω in s, g ρ ω ∂μ) / Nat.factorial n := by
                rw [hsum_eq]
          _ = (∑ ρ : Equiv.Perm (Fin n), ∫ ω in s, ψ (Xseq ω) ∂μ) / Nat.factorial n := by
                rw [hperm_sum]
          _ = ∫ ω in s, ψ (Xseq ω) ∂μ := by
                simp [hfactorial_ne_zero, Fintype.card_perm])
      havg_meas).symm

/-- Helper for Theorem 12.17: extending a permutation of the first `m` coordinates to the first
`n` coordinates leaves the resulting prefix action unchanged on sequence space. -/
private theorem permutePrefix_viaFintypeEmbedding {m n : ℕ} (hmn : m ≤ n)
    (ρ : Equiv.Perm (Fin m)) (x : ℕ → E) :
    permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x = permutePrefix m ρ x := by
  funext i
  by_cases hin : i < n
  · by_cases him : i < m
    · let im : Fin m := ⟨i, him⟩
      let in' : Fin n := ⟨i, hin⟩
      have hin_eq : Fin.castLEEmb hmn im = in' := by
        ext
        rfl
      -- Proof comment: on the common prefix, the embedded permutation acts exactly like `ρ`.
      have hleft :
          permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x i =
            x ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in') := by
        simpa [in'] using
          (permutePrefix_apply_fin (ρ := ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x in')
      have hmid :
          x ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in') = x (Fin.castLEEmb hmn (ρ im)) := by
        rw [← hin_eq]
        simpa using
          congrArg (fun j : Fin n ↦ x j)
            (Equiv.Perm.viaFintypeEmbedding_apply_image
              (e := ρ) (f := Fin.castLEEmb hmn) im)
      have hright :
          permutePrefix m ρ x i = x (ρ im) := by
        simpa [im] using (permutePrefix_apply_fin (ρ := ρ) x im)
      calc
        permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x i =
            x ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in') := hleft
        _ = x (Fin.castLEEmb hmn (ρ im)) := hmid
        _ = x (ρ im) := by
              rfl
        _ = permutePrefix m ρ x i := hright.symm
    · let in' : Fin n := ⟨i, hin⟩
      have hnotRange : in' ∉ Set.range (Fin.castLEEmb hmn) := by
        intro hmem
        rcases hmem with ⟨j, hj⟩
        have hji : (j : ℕ) = i := by
          simpa [in'] using congrArg Fin.val hj
        exact him (by simpa [hji] using j.2)
      have hfix :
          (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in' = in' :=
        Equiv.Perm.viaFintypeEmbedding_apply_notMem_range
          (e := ρ) (f := Fin.castLEEmb hmn) hnotRange
      have hleft :
          permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x i =
            x ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in') := by
        simpa [in'] using
          (permutePrefix_apply_fin (ρ := ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x in')
      have hright : permutePrefix m ρ x i = x i := by
        have hfixm :
            (ρ.extendDomain Fin.equivSubtype) i = i :=
          Equiv.Perm.extendDomain_apply_not_subtype (e := ρ) (f := Fin.equivSubtype) (b := i)
            (h := Nat.not_lt_of_ge (le_of_not_gt him))
        simpa [permutePrefix] using congrArg x hfixm
      -- Proof comment: outside the shorter prefix, the extension fixes the index.
      calc
        permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x i =
            x ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) in') := hleft
        _ = x i := by
              rw [hfix]
        _ = permutePrefix m ρ x i := hright.symm
  · have hmn' : m ≤ i := le_trans hmn (le_of_not_gt hin)
    have hleft :
        permutePrefix n (ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) x i = x i := by
      have hfixn :
          ((ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)).extendDomain Fin.equivSubtype) i = i :=
        Equiv.Perm.extendDomain_apply_not_subtype
          (e := ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)) (f := Fin.equivSubtype) (b := i)
          (h := Nat.not_lt_of_ge (le_of_not_gt hin))
      simpa [permutePrefix] using congrArg x hfixn
    have hright : permutePrefix m ρ x i = x i := by
      have hfixm :
          (ρ.extendDomain Fin.equivSubtype) i = i :=
        Equiv.Perm.extendDomain_apply_not_subtype (e := ρ) (f := Fin.equivSubtype) (b := i)
          (h := Nat.not_lt_of_ge hmn')
      simpa [permutePrefix] using congrArg x hfixm
    rw [hleft, hright]

/-- Helper for Theorem 12.17: finite exchangeable stages form a decreasing family. -/
private theorem nSymmetricSequenceSigmaAlgebra_antitone :
    Antitone (fun n : ℕ ↦ nSymmetricSequenceSigmaAlgebra (E := E) n) := by
  intro m n hmn s hs
  rw [measurableSet_nSymmetricSequenceSigmaAlgebra_iff] at hs ⊢
  rcases hs with ⟨hs_meas, hs_symm⟩
  refine ⟨hs_meas, ?_⟩
  intro ρ
  let ρ' : Equiv.Perm (Fin n) := ρ.viaFintypeEmbedding (Fin.castLEEmb hmn)
  have hpre :
      permutePrefix m ρ ⁻¹' s = permutePrefix n ρ' ⁻¹' s := by
    -- Proof comment: compare the short and long prefix actions through the canonical extension.
    ext x
    simp [ρ', permutePrefix_viaFintypeEmbedding (E := E) (hmn := hmn) (ρ := ρ) (x := x)]
  simpa [hpre] using hs_symm ρ'

/-- Helper for Theorem 12.17: the pulled-back finite exchangeable `σ`-algebras are antitone. -/
private theorem nExchangeableSigmaAlgebra_antitone :
    Antitone (fun n : ℕ ↦ nExchangeableSigmaAlgebra Xseq n) := by
  intro m n hmn
  -- Proof comment: pull back the sequence-space antitone statement along the sample-sequence map.
  exact MeasurableSpace.comap_mono (nSymmetricSequenceSigmaAlgebra_antitone (E := E) hmn)

/-- Helper for Theorem 12.17: the exchangeable `σ`-algebra is the intersection of the finite
exchangeable stages. -/
theorem exchangeableSigmaAlgebra_eq_iInf_nExchangeableSigmaAlgebra :
    (exchangeableSigmaAlgebra Xseq : MeasurableSpace Ω) = ⨅ n, nExchangeableSigmaAlgebra Xseq n := by
  refine le_antisymm
    (exchangeableSigmaAlgebra_le_iInf_nExchangeableSigmaAlgebra Xseq) ?_
  intro s hs
  classical
  rw [exchangeableSigmaAlgebra,
    exchangeableSequenceSigmaAlgebra_eq_iInf_nSymmetricSequenceSigmaAlgebra,
    MeasurableSpace.measurableSet_comap]
  rw [MeasurableSpace.measurableSet_iInf] at hs
  have hs_stage :
      ∀ n, ∃ t : Set (ℕ → E), MeasurableSet[nSymmetricSequenceSigmaAlgebra n] t ∧ Xseq ⁻¹' t = s := by
    intro n
    exact MeasurableSpace.measurableSet_comap.mp (hs n)
  choose B hB_meas hB_pre using hs_stage
  let C : ℕ → Set (ℕ → E) := fun n ↦ ⋂ j : ℕ, B (n + j)
  let A : Set (ℕ → E) := ⋃ n : ℕ, C n
  have hC_mono : Monotone C := by
    intro a b hab x hx
    change x ∈ ⋂ j : ℕ, B (a + j) at hx
    change x ∈ ⋂ j : ℕ, B (b + j)
    simp only [Set.mem_iInter] at hx ⊢
    intro j
    rcases Nat.exists_eq_add_of_le hab with ⟨d, rfl⟩
    simpa [Nat.add_assoc] using hx (d + j)
  refine ⟨A, ?_, ?_⟩
  · -- Proof comment: rewrite measurability in the exchangeable sequence algebra as membership in
    -- every finite symmetric stage, then use the increasing tail union `⋃ r, C (m + r)`.
    rw [MeasurableSpace.measurableSet_iInf]
    intro m
    have hA_eq : A = ⋃ r : ℕ, C (m + r) := by
      ext x
      simp only [A, Set.mem_iUnion]
      constructor
      · intro hx
        rcases hx with ⟨n, hn⟩
        exact ⟨n, hC_mono (Nat.le_add_left n m) hn⟩
      · intro hx
        rcases hx with ⟨r, hr⟩
        exact ⟨m + r, hr⟩
    rw [hA_eq]
    refine MeasurableSet.iUnion fun r ↦ ?_
    refine MeasurableSet.iInter fun j ↦ ?_
    simpa [Nat.add_assoc] using
      ((nSymmetricSequenceSigmaAlgebra_antitone (E := E) (Nat.le_add_right m (r + j)))
        _ (hB_meas (m + (r + j))))
  · -- Proof comment: every stage witness `B n` pulls back to the same event `s`, so the
    -- countable intersections and union still pull back to `s`.
    ext ω
    simp only [A, C, Set.mem_preimage, Set.mem_iUnion, Set.mem_iInter]
    constructor
    · rintro ⟨n, hn⟩
      have hBn : Xseq ω ∈ B n ↔ ω ∈ s := by
        simpa [Set.mem_preimage] using congrArg (fun t : Set Ω ↦ ω ∈ t) (hB_pre n)
      exact hBn.mp (by simpa using hn 0)
    · intro hω
      refine ⟨0, ?_⟩
      intro j
      have hBj : Xseq ω ∈ B j ↔ ω ∈ s := by
        simpa [Set.mem_preimage] using congrArg (fun t : Set Ω ↦ ω ∈ t) (hB_pre j)
      simpa using hBj.mpr hω

/-- Helper for Theorem 12.17: a permutation of the first `n` coordinates fixes every coordinate
from index `n` onward. -/
private theorem permutePrefix_apply_of_le (n i : ℕ) (ρ : Equiv.Perm (Fin n)) (x : ℕ → E)
    (hi : n ≤ i) :
    permutePrefix n ρ x i = x i := by
  -- Proof comment: indices outside the permuted prefix are fixed by the extended permutation.
  have hfix :
      (ρ.extendDomain Fin.equivSubtype) i = i :=
    Equiv.Perm.extendDomain_apply_not_subtype (e := ρ) (f := Fin.equivSubtype) (b := i)
      (h := Nat.not_lt_of_ge hi)
  simpa [permutePrefix] using congrArg x hfix

/-- Helper for Theorem 12.17: each tail stage of `X` lies inside the matching finite
exchangeable stage of the sample-sequence map. -/
private theorem tailStage_le_nExchangeableSigmaAlgebra (n : ℕ) :
    tailStage (X := X) n ≤ nExchangeableSigmaAlgebra Xseq n := by
  refine iSup_le fun i ↦ iSup_le fun hi ↦ ?_
  have hi' : n ≤ i := hi
  have hEval : Measurable[nSymmetricSequenceSigmaAlgebra n] (Function.eval i : (ℕ → E) → E) := by
    rw [measurable_iff_comap_le]
    intro s hs
    rcases (MeasurableSpace.measurableSet_comap.mp hs) with ⟨t, ht, rfl⟩
    rw [measurableSet_nSymmetricSequenceSigmaAlgebra_iff]
    refine ⟨measurableSet_preimage (measurable_pi_apply i) ht, ?_⟩
    intro ρ
    ext x
    simp [permutePrefix_apply_of_le (E := E) n i ρ x hi']
  calc
    MeasurableSpace.comap (X i) inferInstance =
        (MeasurableSpace.comap (Function.eval i) inferInstance).comap Xseq := by
          rw [MeasurableSpace.comap_comp]
          rfl
    _ ≤ (nSymmetricSequenceSigmaAlgebra n).comap Xseq :=
      MeasurableSpace.comap_mono hEval.comap_le
    _ = nExchangeableSigmaAlgebra Xseq n := rfl

/-- Helper for Theorem 12.17: the tail stages form a decreasing family. -/
private theorem tailStage_antitone :
    Antitone (tailStage (X := X)) := by
  intro l m hlm
  -- Proof comment: later tail stages generate fewer coordinates, so they define smaller
  -- sigma-algebras.
  refine iSup_le fun i ↦ iSup_le fun hi ↦ ?_
  exact le_iSup_of_le i <| le_iSup_of_le (show i ∈ Set.Ici l from le_trans hlm hi) le_rfl

/-- Helper for Theorem 12.17: the tail sigma-algebra is the intersection of the tail stages. -/
private theorem tailRandomVariableMeasurableSpace_eq_iInf_tailStage :
    tailRandomVariableMeasurableSpace X = ⨅ l : ℕ, tailStage (X := X) l := by
  -- Proof comment: this is the canonical Chapter 2 presentation of the tail sigma-algebra.
  rw [tailRandomVariableMeasurableSpace, tailMeasurableSpace_nat_eq_iInf_iSup_Ici]

/-- Helper for Theorem 12.17: the tail `σ`-algebra of `X` is contained in the exchangeable
`σ`-algebra of the sample-sequence map. -/
private theorem tailRandomVariableMeasurableSpace_le_exchangeableSigmaAlgebra :
    tailRandomVariableMeasurableSpace X ≤ exchangeableSigmaAlgebra Xseq := by
  rw [tailRandomVariableMeasurableSpace_eq_iInf_tailStage (X := X),
    exchangeableSigmaAlgebra_eq_iInf_nExchangeableSigmaAlgebra]
  -- Proof comment: each tail stage ignores the first `n` coordinates, so it lies in the
  -- corresponding finite exchangeable stage.
  exact iInf_mono fun n ↦ tailStage_le_nExchangeableSigmaAlgebra (X := X) (E := E) n

/-- Helper for Theorem 12.17: conditioning the `n`th permutation average on the matching tail
stage agrees with conditioning `Y` on that tail stage. -/
private theorem condExp_exchangeableAverage_tailStage_ae_eq_condExp_tailStage
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) (n : ℕ) :
    μ[exchangeableAverage n ψ ∘ Xseq | tailStage (X := X) n] =ᵐ[μ]
      μ[Y | tailStage (X := X) n] := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: measurability of the sample-sequence map is coordinatewise measurability.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  have htail_le :
      tailStage (X := X) n ≤ nExchangeableSigmaAlgebra Xseq n :=
    tailStage_le_nExchangeableSigmaAlgebra (X := X) (E := E) n
  -- Proof comment: first rewrite the average as the finite exchangeable conditional expectation,
  -- then collapse the iterated conditional expectation by the tower property.
  calc
    μ[exchangeableAverage n ψ ∘ Xseq | tailStage (X := X) n] =ᵐ[μ]
        μ[μ[Y | nExchangeableSigmaAlgebra Xseq n] | tailStage (X := X) n] := by
          exact condExp_congr_ae
            (condExp_eq_exchangeableAverage_of_isExchangeable_finite
              (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int n).symm
    _ =ᵐ[μ] μ[Y | tailStage (X := X) n] := by
          exact condExp_condExp_of_le htail_le (nExchangeableSigmaAlgebra_le hXseq_meas n)

/-- Helper for Theorem 12.17: conditioning the exchangeable conditional expectation on the tail
sigma-algebra is the same as conditioning `Y` on the tail sigma-algebra. -/
private theorem condExp_exchangeableCondExp_tail_ae_eq_condExp_tail
    (hX_meas : ∀ n, Measurable (X n)) :
    μ[G | tailRandomVariableMeasurableSpace X] =ᵐ[μ]
      μ[Y | tailRandomVariableMeasurableSpace X] := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: as above, the sample-sequence map is measurable coordinatewise.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  -- Proof comment: the tail sigma-algebra sits below the exchangeable sigma-algebra, so a second
  -- conditioning step collapses by the tower property.
  exact condExp_condExp_of_le
    (tailRandomVariableMeasurableSpace_le_exchangeableSigmaAlgebra (X := X) (E := E))
    (exchangeableSigmaAlgebra_le hXseq_meas)

/-- Helper for Theorem 12.17: truncate the permutation average by keeping only permutations whose
first `k` images lie in the tail block `Ici l`. -/
private noncomputable def tailApprox (l n : ℕ) : (ℕ → E) → ℝ :=
  fun x ↦
    if hkn : k ≤ n then
      (∑ ρ : Equiv.Perm (Fin n),
        if ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
          ψ (permutePrefix n ρ x)
        else 0) / Nat.factorial n
    else 0

/-- Helper for Theorem 12.17: a good permutation summand in `tailApprox` only depends on tail
coordinates. -/
private theorem measurable_tailApproxSummand
    (hφ_meas : Measurable φ) {l n : ℕ} (hkn : k ≤ n) (ρ : Equiv.Perm (Fin n))
    (hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ)) :
    Measurable[tailStage (X := X) l] (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) := by
  have hcoord :
      ∀ i : Fin k, Measurable[tailStage (X := X) l] (fun ω ↦ X (ρ (Fin.castLE hkn i)) ω) := by
    intro i
    -- Proof comment: every coordinate read by the good permutation lies in the tail stage by
    -- assumption, so its coordinate map is measurable for that stage.
    refine Measurable.of_comap_le ?_
    simpa using
      (le_iSup_of_le (ρ (Fin.castLE hkn i) : ℕ)
        (le_iSup_of_le (hgood i) le_rfl) :
          MeasurableSpace.comap (X (ρ (Fin.castLE hkn i))) inferInstance ≤
            tailStage (X := X) l)
  have htuple :
      Measurable[tailStage (X := X) l]
        (fun ω ↦ fun i : Fin k ↦ X (ρ (Fin.castLE hkn i)) ω) := by
    let mTail : MeasurableSpace Ω := tailStage (X := X) l
    letI : MeasurableSpace Ω := mTail
    have hcoord' : ∀ i : Fin k, Measurable (fun ω ↦ X (ρ (Fin.castLE hkn i)) ω) := by
      intro i
      simpa [mTail] using hcoord i
    have htuple' :
        Measurable (fun ω ↦ fun i : Fin k ↦ X (ρ (Fin.castLE hkn i)) ω) :=
      measurable_pi_lambda _ hcoord'
    simpa [mTail] using htuple'
  have hcore :
      Measurable[tailStage (X := X) l]
        (fun ω ↦ φ (fun i : Fin k ↦ X (ρ (Fin.castLE hkn i)) ω)) :=
    hφ_meas.comp htuple
  -- Proof comment: rewrite the summand into the explicit `k`-tuple of tail coordinates.
  have hEq :
      (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) =
        fun ω ↦ φ (fun i : Fin k ↦ X (ρ (Fin.castLE hkn i)) ω) := by
    funext ω
    change φ (fun i : Fin k ↦ permutePrefix n ρ (Xseq ω) i) =
      φ (fun i : Fin k ↦ X (ρ (Fin.castLE hkn i)) ω)
    refine congrArg φ ?_
    funext i
    simpa using
      (permutePrefix_apply_fin (ρ := ρ) (x := Xseq ω) (i := Fin.castLE hkn i))
  simpa [hEq] using hcore

/-- Helper for Theorem 12.17: the tail truncation is measurable for the fixed tail stage. -/
private theorem tailApprox_measurable
    (hφ_meas : Measurable φ) (l n : ℕ) :
    Measurable[tailStage (X := X) l] (tailApprox (k := k) (φ := φ) l n ∘ Xseq) := by
  classical
  by_cases hkn : k ≤ n
  · have hsum :
        Measurable[tailStage (X := X) l]
          (fun ω ↦
            ∑ ρ : Equiv.Perm (Fin n),
              if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
                ψ (permutePrefix n ρ (Xseq ω))
              else 0) := by
      refine Finset.measurable_sum (Finset.univ : Finset (Equiv.Perm (Fin n))) ?_
      intro ρ hρ
      by_cases hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ)
      · simpa [hgood] using
          measurable_tailApproxSummand (X := X) (φ := φ) hφ_meas hkn ρ hgood
      · simp [hgood]
    -- Proof comment: divide the measurable finite sum by the constant normalizing factor.
    have hEq :
        tailApprox (k := k) (φ := φ) l n ∘ Xseq =
          fun ω ↦
            (∑ ρ : Equiv.Perm (Fin n),
              if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
                ψ (permutePrefix n ρ (Xseq ω))
              else 0) / Nat.factorial n := by
      funext ω
      simp [tailApprox, hkn]
    simpa [hEq] using hsum.div_const (Nat.factorial n : ℝ)
  · have hzero : tailApprox (k := k) (φ := φ) l n ∘ Xseq = fun _ : Ω ↦ (0 : ℝ) := by
        funext ω
        simp [tailApprox, hkn]
    simpa [hzero] using
      (measurable_const : Measurable[tailStage (X := X) l] (fun _ : Ω ↦ (0 : ℝ)))

/-- Helper for Theorem 12.17: fixing the value of one coordinate of a finite permutation leaves
`(n - 1)!` possibilities for the remaining coordinates. -/
private theorem card_perm_apply_eq {n : ℕ} (i j : Fin n) :
    Fintype.card {ρ : Equiv.Perm (Fin n) // ρ i = j} = Nat.factorial (n - 1) := by
  classical
  let c : ℕ := Fintype.card {ρ : Equiv.Perm (Fin n) // ρ i = i}
  have hconst : ∀ j : Fin n, Fintype.card {ρ : Equiv.Perm (Fin n) // ρ i = j} = c := by
    intro j
    refine Fintype.card_congr
      { toFun := fun ρ ↦ ⟨Equiv.swap i j * ρ.1, by
          change Equiv.swap i j (ρ.1 i) = i
          simpa [ρ.2]⟩
        invFun := fun ρ ↦ ⟨Equiv.swap i j * ρ.1, by
          change Equiv.swap i j (ρ.1 i) = j
          simpa [ρ.2]⟩
        left_inv := by
          intro ρ
          ext a
          simp
        right_inv := by
          intro ρ
          ext a
          simp }
  have hcard :
      Nat.factorial n = n * c := by
    have hMapsTo :
        ((Finset.univ : Finset (Equiv.Perm (Fin n))) :
          Set (Equiv.Perm (Fin n))).MapsTo
          (fun ρ : Equiv.Perm (Fin n) ↦ ρ i) (Finset.univ : Finset (Fin n)) :=
      fun _ _ ↦ Finset.mem_univ _
    calc
      Nat.factorial n =
          ∑ j : Fin n,
            (Finset.filter (fun ρ : Equiv.Perm (Fin n) ↦ ρ i = j)
              (Finset.univ : Finset (Equiv.Perm (Fin n)))).card := by
            simpa [Fintype.card_perm] using Finset.card_eq_sum_card_fiberwise hMapsTo
      _ = ∑ j : Fin n, Fintype.card {ρ : Equiv.Perm (Fin n) // ρ i = j} := by
            refine Finset.sum_congr rfl ?_
            intro j hj
            simpa using
              (Fintype.card_subtype (fun ρ : Equiv.Perm (Fin n) ↦ ρ i = j)).symm
      _ = ∑ _j : Fin n, c := by
            refine Finset.sum_congr rfl ?_
            intro j hj
            exact hconst j
      _ = n * c := by simp [c]
  have hfiber : c = Nat.factorial (n - 1) := by
    have hn_pos : 0 < n := lt_of_lt_of_le (Nat.zero_lt_succ i.1) (Nat.succ_le_of_lt i.2)
    apply Nat.mul_left_cancel hn_pos
    calc
      n * c = Nat.factorial n := hcard.symm
      _ = n * Nat.factorial (n - 1) := by
            exact (Nat.mul_factorial_pred (Nat.ne_of_gt hn_pos)).symm
  exact (hconst j).trans hfiber

/-- Helper for Theorem 12.17: the permutations hitting the first `l` coordinates among the first
`k` slots are at most `k * l * (n - 1)!` in number. -/
private theorem card_badPermutations_le (l n : ℕ) (hkn : k ≤ n) (hln : l ≤ n) :
    Fintype.card
        {ρ : Equiv.Perm (Fin n) //
          ∃ i : Fin k, ∃ j : Fin l,
            ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j} ≤
      k * l * Nat.factorial (n - 1) := by
  classical
  let badEmbedding :
      {ρ : Equiv.Perm (Fin n) //
        ∃ i : Fin k, ∃ j : Fin l,
          ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j} ↪
        Sigma fun i : Fin k ↦
          Sigma fun j : Fin l ↦
            {ρ : Equiv.Perm (Fin n) //
              ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j} :=
    { toFun := fun ρ ↦
        let hi : ∃ i : Fin k, ∃ j : Fin l,
            ρ.1 (Fin.castLE hkn i) = Fin.castLEEmb hln j := ρ.2
        let i : Fin k := Classical.choose hi
        let hj : ∃ j : Fin l, ρ.1 (Fin.castLE hkn i) = Fin.castLEEmb hln j :=
          Classical.choose_spec hi
        let j : Fin l := Classical.choose hj
        ⟨i, j, ⟨ρ.1, Classical.choose_spec hj⟩⟩
      inj' := by
        intro ρ τ h
        exact Subtype.ext <| by
          simpa using congrArg (fun z ↦ z.2.2.1) h }
  calc
    Fintype.card
        {ρ : Equiv.Perm (Fin n) //
          ∃ i : Fin k, ∃ j : Fin l,
            ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j} ≤
        Fintype.card
          (Sigma fun i : Fin k ↦
            Sigma fun j : Fin l ↦
              {ρ : Equiv.Perm (Fin n) //
                ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j}) :=
      Fintype.card_le_of_embedding badEmbedding
    _ = ∑ i : Fin k, ∑ j : Fin l,
          Fintype.card
            {ρ : Equiv.Perm (Fin n) //
              ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j} := by
          rw [Fintype.card_sigma]
          refine Finset.sum_congr rfl ?_
          intro i hi
          exact Fintype.card_sigma
    _ = ∑ i : Fin k, ∑ _j : Fin l, Nat.factorial (n - 1) := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          refine Finset.sum_congr rfl ?_
          intro j hj
          simpa using
            (card_perm_apply_eq (i := Fin.castLE hkn i) (j := Fin.castLEEmb hln j))
    _ = k * l * Nat.factorial (n - 1) := by
          simp [mul_assoc, mul_left_comm, mul_comm]

/-- Helper for Theorem 12.17: permuting the first `n` coordinates preserves the `L¹` norm of the
corresponding summand. -/
private theorem lpNorm_permutePrefix_eq
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (n : ℕ) (ρ : Equiv.Perm (Fin n)) :
    lpNorm (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) 1 μ = lpNorm Y 1 μ := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: measurability of the process map is coordinatewise measurability.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  have hleft_meas :
      Measurable (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) :=
    (measurable_psi (φ := φ) hφ_meas).comp
      ((measurable_permutePrefix (E := E) n ρ).comp hXseq_meas)
  have hright_meas : Measurable Y :=
    (measurable_psi (φ := φ) hφ_meas).comp hXseq_meas
  -- Proof comment: identical distribution of the permuted and unpermuted samples preserves the
  -- integral of the absolute value, hence the `L¹` norm.
  rw [MeasureTheory.lpNorm_one_eq_integral_norm hleft_meas.aestronglyMeasurable,
    MeasureTheory.lpNorm_one_eq_integral_norm hright_meas.aestronglyMeasurable]
  change ∫ ω, ‖ψ (permutePrefix n ρ (Xseq ω))‖ ∂μ = ∫ ω, ‖ψ (Xseq ω)‖ ∂μ
  exact
    (identDistrib_process_permutePrefix_of_isExchangeable
      (X := X) (μ := μ) hX n ρ).comp ((measurable_psi (φ := φ) hφ_meas).norm) |>.integral_eq.symm

/-- Helper for Theorem 12.17: each tail truncation belongs to `L¹`. -/
private theorem tailApprox_memLp_one
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) (l n : ℕ) :
    MemLp (tailApprox (k := k) (φ := φ) l n ∘ Xseq) 1 μ := by
  classical
  by_cases hkn : k ≤ n
  · let g : Equiv.Perm (Fin n) → Ω → ℝ := fun ρ ω ↦
      if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
        ψ (permutePrefix n ρ (Xseq ω))
      else 0
    have hg_int : ∀ ρ : Equiv.Perm (Fin n), Integrable (g ρ) μ := by
      intro ρ
      by_cases hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ)
      · -- Proof comment: a good permutation summand is a permuted copy of `Y`, so it is
        -- integrable by exchangeability.
        simpa [g, hgood] using
          (identDistrib_process_permutePrefix_of_isExchangeable
            (X := X) (μ := μ) hX n ρ).comp (measurable_psi (φ := φ) hφ_meas) |>.integrable_snd
            hφ_int
      · simp [g, hgood]
    have hsum_int :
        Integrable (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) μ := by
      simpa [g] using
        (MeasureTheory.integrable_finset_sum (μ := μ)
          (Finset.univ : Finset (Equiv.Perm (Fin n))) fun ρ hρ ↦ hg_int ρ)
    have hEq :
        tailApprox (k := k) (φ := φ) l n ∘ Xseq =
          fun ω ↦ (∑ ρ : Equiv.Perm (Fin n), g ρ ω) / Nat.factorial n := by
      funext ω
      simp [tailApprox, g, hkn]
    -- Proof comment: divide the integrable finite sum by the constant normalization factor.
    exact memLp_one_iff_integrable.mpr <| hEq ▸ hsum_int.div_const (Nat.factorial n : ℝ)
  · have hzero : tailApprox (k := k) (φ := φ) l n ∘ Xseq = fun _ : Ω ↦ (0 : ℝ) := by
      funext ω
      simp [tailApprox, hkn]
    simpa [hzero] using
      (memLp_one_iff_integrable.mpr (integrable_zero : Integrable (fun _ : Ω ↦ (0 : ℝ)) μ))

/-- Helper for Theorem 12.17: the tail truncations approximate the exchangeable averages in
`L¹` for each fixed tail stage. -/
private theorem tendsto_eLpNorm_tailApprox_sub_exchangeableAverage
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) (l : ℕ) :
    Tendsto
      (fun n ↦
        eLpNorm
          (tailApprox (k := k) (φ := φ) l n ∘ Xseq - exchangeableAverage n ψ ∘ Xseq) 1 μ)
      atTop
      (nhds 0) := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: measurability of the sequence-valued sample map is coordinatewise.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  have hs_meas :
      ∀ n : ℕ, ∀ ρ : Equiv.Perm (Fin n),
        Measurable (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) := by
    intro n ρ
    exact (measurable_psi (φ := φ) hφ_meas).comp
      ((measurable_permutePrefix (E := E) n ρ).comp hXseq_meas)
  have hs_int :
      ∀ n : ℕ, ∀ ρ : Equiv.Perm (Fin n),
        Integrable (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) μ := by
    intro n ρ
    -- Proof comment: every permutation summand has the same law as `Y`, hence the same `L¹`
    -- integrability.
    exact
      (identDistrib_process_permutePrefix_of_isExchangeable
        (X := X) (μ := μ) hX n ρ).comp (measurable_psi (φ := φ) hφ_meas) |>.integrable_snd hφ_int
  have heLpNorm_eq_of_lpNorm :
      ∀ {f : Ω → ℝ}, Integrable f μ → Measurable f →
        eLpNorm f 1 μ = ENNReal.ofReal (lpNorm f 1 μ) := by
    intro f hf_int hf_meas
    rw [MeasureTheory.eLpNorm_one_eq_lintegral_enorm,
      MeasureTheory.lpNorm_one_eq_integral_norm hf_meas.aestronglyMeasurable]
    exact (MeasureTheory.ofReal_integral_norm_eq_lintegral_enorm hf_int).symm
  have hbound :
      ∀ᶠ n in atTop,
        eLpNorm
            (tailApprox (k := k) (φ := φ) l n ∘ Xseq - exchangeableAverage n ψ ∘ Xseq) 1 μ ≤
          ENNReal.ofReal (((k * l : ℝ) * lpNorm Y 1 μ) / n) := by
    refine Filter.eventually_atTop.2 ?_
    refine ⟨max (max k l) 1, ?_⟩
    intro n hn
    have hmax : max k l ≤ n := le_trans (le_max_left _ _) hn
    have hkn : k ≤ n := le_trans (le_max_left _ _) hmax
    have hln : l ≤ n := le_trans (le_max_right _ _) hmax
    have hn_pos : 0 < n := lt_of_lt_of_le (by simp) (le_trans (le_max_right _ _) hn)
    have hn_cast_ne : (n : ℝ) ≠ 0 := by
      exact_mod_cast (Nat.ne_of_gt hn_pos)
    let bad : Equiv.Perm (Fin n) → Prop := fun ρ ↦
      ∃ i : Fin k, ∃ j : Fin l, ρ (Fin.castLE hkn i) = Fin.castLEEmb hln j
    let g : Equiv.Perm (Fin n) → Ω → ℝ := fun ρ ω ↦
      if bad ρ then -ψ (permutePrefix n ρ (Xseq ω)) else 0
    have hbad_iff :
        ∀ ρ : Equiv.Perm (Fin n),
          (¬ ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ)) ↔ bad ρ := by
      intro ρ
      constructor
      · intro hρ
        push Not at hρ
        rcases hρ with ⟨i, hi⟩
        refine ⟨i, ⟨⟨ρ (Fin.castLE hkn i), hi⟩, ?_⟩⟩
        ext
        rfl
      · rintro ⟨i, j, hρ⟩ hgood
        have : l ≤ ((Fin.castLEEmb hln j : Fin n) : ℕ) := by
          simpa [hρ] using hgood i
        exact (not_le_of_gt j.2) this
    have hg_aesm : ∀ ρ : Equiv.Perm (Fin n), AEStronglyMeasurable (g ρ) μ := by
      intro ρ
      by_cases hbad : bad ρ
      · simpa [g, hbad] using ((hs_meas n ρ).aestronglyMeasurable.neg)
      · simpa [g, hbad] using
          (aestronglyMeasurable_const : AEStronglyMeasurable (fun _ : Ω ↦ (0 : ℝ)) μ)
    have hsum_aesm :
        AEStronglyMeasurable (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) μ := by
      simpa using
        ((Finset.univ : Finset (Equiv.Perm (Fin n))).aestronglyMeasurable_fun_sum
          fun ρ hρ ↦ hg_aesm ρ)
    have hterm :
        ∀ ρ : Equiv.Perm (Fin n), ∀ ω : Ω,
          (if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
              ψ (permutePrefix n ρ (Xseq ω))
            else 0) - ψ (permutePrefix n ρ (Xseq ω)) =
            g ρ ω := by
      intro ρ ω
      by_cases hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ)
      · have hnot_bad : ¬ bad ρ := by
          intro hbad
          exact (hbad_iff ρ).2 hbad hgood
        simp [g, hgood, hnot_bad]
      · have hbad : bad ρ := (hbad_iff ρ).1 hgood
        simp [g, hgood, hbad]
    have hEq :
        tailApprox (k := k) (φ := φ) l n ∘ Xseq - exchangeableAverage n ψ ∘ Xseq =
          (1 / Nat.factorial n : ℝ) • fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω := by
      funext ω
      -- Proof comment: after subtracting the full average, only the bad permutations survive.
      calc
        tailApprox (k := k) (φ := φ) l n (Xseq ω) - exchangeableAverage n ψ (Xseq ω) =
            (((∑ ρ : Equiv.Perm (Fin n),
                if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
                  ψ (permutePrefix n ρ (Xseq ω))
                else 0) -
              ∑ ρ : Equiv.Perm (Fin n), ψ (permutePrefix n ρ (Xseq ω))) /
              Nat.factorial n) := by
              simp [tailApprox, exchangeableAverage, hkn, sub_div]
        _ =
            ((∑ ρ : Equiv.Perm (Fin n),
                ((if hgood : ∀ i : Fin k, l ≤ (ρ (Fin.castLE hkn i) : ℕ) then
                    ψ (permutePrefix n ρ (Xseq ω))
                  else 0) -
                  ψ (permutePrefix n ρ (Xseq ω)))) /
              Nat.factorial n) := by
              congr 1
              rw [← Finset.sum_sub_distrib]
        _ = ((∑ ρ : Equiv.Perm (Fin n), g ρ ω) / Nat.factorial n) := by
              congr 1
              exact Finset.sum_congr rfl fun ρ hρ ↦ hterm ρ ω
        _ = (1 / Nat.factorial n : ℝ) * (∑ ρ : Equiv.Perm (Fin n), g ρ ω) := by
              ring
        _ = ((1 / Nat.factorial n : ℝ) • fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) ω := by
              rfl
    have hperm_eLpNorm :
        ∀ ρ : Equiv.Perm (Fin n),
          eLpNorm (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) 1 μ =
            ENNReal.ofReal (lpNorm Y 1 μ) := by
      intro ρ
      rw [heLpNorm_eq_of_lpNorm (hs_int n ρ) (hs_meas n ρ),
        lpNorm_permutePrefix_eq (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas n ρ]
    have hterm_norm :
        ∀ ρ : Equiv.Perm (Fin n),
          eLpNorm (g ρ) 1 μ = if bad ρ then ENNReal.ofReal (lpNorm Y 1 μ) else 0 := by
      intro ρ
      by_cases hbad : bad ρ
      · have hneg :
            eLpNorm (fun ω ↦ -ψ (permutePrefix n ρ (Xseq ω))) 1 μ =
              ENNReal.ofReal (lpNorm Y 1 μ) := by
          calc
            eLpNorm (fun ω ↦ -ψ (permutePrefix n ρ (Xseq ω))) 1 μ =
                eLpNorm (-(fun ω ↦ ψ (permutePrefix n ρ (Xseq ω)))) 1 μ := by
                  rfl
            _ = eLpNorm (fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))) 1 μ := by
                  let s : Ω → ℝ := fun ω ↦ ψ (permutePrefix n ρ (Xseq ω))
                  have hneg' : eLpNorm (-s) 1 μ = eLpNorm s 1 μ := by
                    rw [MeasureTheory.eLpNorm_neg]
                  simpa [s] using hneg'
            _ = ENNReal.ofReal (lpNorm Y 1 μ) := hperm_eLpNorm ρ
        simpa [g, hbad] using hneg
      · simpa [g, hbad]
    have hsum_norm :
        ∑ ρ : Equiv.Perm (Fin n), eLpNorm (g ρ) 1 μ =
          ((Finset.univ.filter bad).card : ENNReal) * ENNReal.ofReal (lpNorm Y 1 μ) := by
      calc
        ∑ ρ : Equiv.Perm (Fin n), eLpNorm (g ρ) 1 μ =
            ∑ ρ : Equiv.Perm (Fin n),
              if bad ρ then ENNReal.ofReal (lpNorm Y 1 μ) else 0 := by
                refine Finset.sum_congr rfl ?_
                intro ρ hρ
                exact hterm_norm ρ
        _ = ((Finset.univ : Finset (Equiv.Perm (Fin n))).filter bad).sum
              (fun _ ↦ ENNReal.ofReal (lpNorm Y 1 μ)) := by
                simpa using
                  (Finset.sum_filter
                    (s := (Finset.univ : Finset (Equiv.Perm (Fin n))))
                    (p := bad)
                    (f := fun _ ↦ ENNReal.ofReal (lpNorm Y 1 μ))).symm
        _ = ((Finset.univ.filter bad).card : ENNReal) * ENNReal.ofReal (lpNorm Y 1 μ) := by
              simp
    have hcard_le :
        (Finset.univ.filter bad).card ≤ k * l * Nat.factorial (n - 1) := by
      simpa [Fintype.card_subtype, bad] using
        card_badPermutations_le (k := k) (l := l) (n := n) hkn hln
    have hsum_norm_le :
        ∑ ρ : Equiv.Perm (Fin n), eLpNorm (g ρ) 1 μ ≤
          ENNReal.ofReal (lpNorm Y 1 μ) * (k * l * Nat.factorial (n - 1) : ENNReal) := by
      rw [hsum_norm, mul_comm]
      simpa [mul_comm] using
        mul_le_mul_left
          (show ((Finset.univ.filter bad).card : ENNReal) ≤
              (k * l * Nat.factorial (n - 1) : ENNReal) by
            exact_mod_cast hcard_le)
          (ENNReal.ofReal (lpNorm Y 1 μ))
    have htriangle :
        eLpNorm (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) 1 μ ≤
          ∑ ρ : Equiv.Perm (Fin n), eLpNorm (g ρ) 1 μ := by
      have hsum_le :
          eLpNorm ((Finset.univ : Finset (Equiv.Perm (Fin n))).sum g) 1 μ ≤
            (Finset.univ : Finset (Equiv.Perm (Fin n))).sum (fun ρ ↦ eLpNorm (g ρ) 1 μ) := by
        refine MeasureTheory.eLpNorm_sum_le ?_ ?_
        · intro ρ hρ
          exact hg_aesm ρ
        · norm_num
      have hsum_eq :
          ((Finset.univ : Finset (Equiv.Perm (Fin n))).sum g) =
            fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω := by
        funext ω
        simp [Finset.sum_apply]
      simpa [hsum_eq] using hsum_le
    have hscalar_arith :
        ‖(1 / Nat.factorial n : ℝ)‖ₑ *
            (ENNReal.ofReal (lpNorm Y 1 μ) *
              (k * l * Nat.factorial (n - 1) : ENNReal)) =
          ENNReal.ofReal (((k * l : ℝ) * lpNorm Y 1 μ) / n) := by
      have hfact :
          (Nat.factorial n : ℝ) = n * Nat.factorial (n - 1) := by
        exact_mod_cast (Nat.mul_factorial_pred (Nat.ne_of_gt hn_pos)).symm
      have hlp_nonneg : 0 ≤ lpNorm Y 1 μ := by
        exact MeasureTheory.lpNorm_nonneg
      have hnat :
          (k * l * Nat.factorial (n - 1) : ENNReal) =
            ENNReal.ofReal (k * l * Nat.factorial (n - 1) : ℝ) := by
        simpa using (ENNReal.ofReal_natCast (k * l * Nat.factorial (n - 1))).symm
      rw [one_div, enorm_inv (by positivity), Real.enorm_natCast, ← ENNReal.div_eq_inv_mul]
      rw [hnat, ← ENNReal.ofReal_mul hlp_nonneg, ← ENNReal.ofReal_natCast,
        ← ENNReal.ofReal_div_of_pos (show (0 : ℝ) < Nat.factorial n by positivity)]
      congr 1
      rw [hfact]
      field_simp [hn_cast_ne]
    calc
      eLpNorm
          (tailApprox (k := k) (φ := φ) l n ∘ Xseq - exchangeableAverage n ψ ∘ Xseq) 1 μ =
          ‖(1 / Nat.factorial n : ℝ)‖ₑ *
            eLpNorm (fun ω ↦ ∑ ρ : Equiv.Perm (Fin n), g ρ ω) 1 μ := by
              rw [hEq, MeasureTheory.eLpNorm_const_smul]
      _ ≤ ‖(1 / Nat.factorial n : ℝ)‖ₑ *
            (∑ ρ : Equiv.Perm (Fin n), eLpNorm (g ρ) 1 μ) := by
              simpa [mul_comm] using mul_le_mul_left htriangle ‖(1 / Nat.factorial n : ℝ)‖ₑ
      _ ≤ ‖(1 / Nat.factorial n : ℝ)‖ₑ *
            (ENNReal.ofReal (lpNorm Y 1 μ) *
              (k * l * Nat.factorial (n - 1) : ENNReal)) := by
              simpa [mul_assoc, mul_left_comm, mul_comm] using
                mul_le_mul_left hsum_norm_le ‖(1 / Nat.factorial n : ℝ)‖ₑ
      _ = ENNReal.ofReal (((k * l : ℝ) * lpNorm Y 1 μ) / n) := hscalar_arith
  have hmajorant :
      Tendsto (fun n : ℕ ↦ ENNReal.ofReal (((k * l : ℝ) * lpNorm Y 1 μ) / n)) atTop (nhds 0) := by
    simpa using
      (ENNReal.tendsto_ofReal
        (tendsto_const_div_atTop_nhds_zero_nat ((k * l : ℝ) * lpNorm Y 1 μ)))
  -- Proof comment: squeeze the truncation error between `0` and the explicit `O(1 / n)` bound.
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds hmajorant
    (Filter.Eventually.of_forall fun _ ↦ zero_le _)
    hbound

/-- Helper for Theorem 12.17: the permutation averages converge almost surely and in `L¹` to the
conditional expectation onto the infimum of the finite exchangeable stages. -/
private theorem exchangeableAverage_tendsto_iInfCondexp
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) :
    (∀ᵐ ω ∂μ,
      Tendsto (fun n ↦ exchangeableAverage n ψ (Xseq ω)) atTop
        (nhds (μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n] ω))) ∧
      TendstoInLp 1 μ (fun n ↦ exchangeableAverage n ψ ∘ Xseq)
        (μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n]) := by
  have hXseq_meas : Measurable Xseq := by
    -- Proof comment: measurability of the process map is coordinatewise measurability.
    rw [measurable_pi_iff]
    intro i
    simpa [Function.swap] using hX_meas i
  let m : ℕ → MeasurableSpace Ω := fun n ↦ nExchangeableSigmaAlgebra Xseq n
  have hm_le : ∀ n, m n ≤ (inferInstance : MeasurableSpace Ω) := by
    intro n
    exact nExchangeableSigmaAlgebra_le hXseq_meas n
  have hm_anti : Antitone m := nExchangeableSigmaAlgebra_antitone (X := X) (E := E)
  have hstage :
      ∀ᵐ ω ∂μ, ∀ n, μ[Y | m n] ω = exchangeableAverage n ψ (Xseq ω) := by
    rw [ae_all_iff]
    intro n
    simpa [m] using
      condExp_eq_exchangeableAverage_of_isExchangeable_finite
        (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int n
  have hae :
      ∀ᵐ ω ∂μ,
        Tendsto (fun n ↦ exchangeableAverage n ψ (Xseq ω)) atTop
          (nhds (μ[Y | ⨅ n, m n] ω)) := by
    have hcond :
        ∀ᵐ ω ∂μ, Tendsto (fun n ↦ μ[Y | m n] ω) atTop (nhds (μ[Y | ⨅ n, m n] ω)) :=
      tendsto_ae_condExp_iInf_of_antitone (μ := μ) (m := m) hm_le hm_anti hφ_int
    filter_upwards [hstage, hcond] with ω hstageω hcondω
    have hfun :
        (fun n ↦ exchangeableAverage n ψ (Xseq ω)) = fun n ↦ μ[Y | m n] ω := by
      funext n
      exact (hstageω n).symm
    simpa [hfun] using hcondω
  have hmem_stage : ∀ n, MemLp (μ[Y | m n]) 1 μ := by
    intro n
    exact memLp_one_iff_integrable.mpr (MeasureTheory.integrable_condExp (f := Y))
  have hmem_limit : MemLp (μ[Y | ⨅ n, m n]) 1 μ := by
    exact memLp_one_iff_integrable.mpr (MeasureTheory.integrable_condExp (f := Y))
  have hnorm_cond :
      Tendsto (fun n ↦ eLpNorm (μ[Y | m n] - μ[Y | ⨅ n, m n]) 1 μ) atTop (nhds 0) :=
    tendsto_eLpNorm_condExp_iInf_of_antitone (μ := μ) (m := m) hm_le hm_anti hφ_int
  have hnorm :
      Tendsto
        (fun n ↦ eLpNorm (exchangeableAverage n ψ ∘ Xseq - μ[Y | ⨅ n, m n]) 1 μ)
        atTop (nhds 0) := by
    have hEq :
        (fun n ↦ eLpNorm (exchangeableAverage n ψ ∘ Xseq - μ[Y | ⨅ n, m n]) 1 μ) =
          fun n ↦ eLpNorm (μ[Y | m n] - μ[Y | ⨅ n, m n]) 1 μ := by
      funext n
      refine eLpNorm_congr_ae ?_
      exact
        ((condExp_eq_exchangeableAverage_of_isExchangeable_finite
          (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int n).symm).sub
          Filter.EventuallyEq.rfl
    simpa [hEq] using hnorm_cond
  have hmem_avg : ∀ n, MemLp (exchangeableAverage n ψ ∘ Xseq) 1 μ := by
    intro n
    exact
      (memLp_congr_ae
        (condExp_eq_exchangeableAverage_of_isExchangeable_finite
          (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int n)).1
        (hmem_stage n)
  exact ⟨hae, (tendstoInLp_iff_tendsto_eLpNorm).2 ⟨hmem_avg, hmem_limit, hnorm⟩⟩

/-- Helper for Theorem 12.17: the limiting conditional expectation over the finite exchangeable
stages is the exchangeable conditional expectation. -/
private theorem exchangeableCondExp_iInfStages_eq :
    μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n] =ᵐ[μ]
      μ[Y | exchangeableSigmaAlgebra Xseq] := by
  -- Proof comment: once the exchangeable `σ`-algebra is identified with the intersection of the
  -- finite stages, the two conditional expectations are definitionally the same.
  rw [exchangeableSigmaAlgebra_eq_iInf_nExchangeableSigmaAlgebra]

/-- Helper for Theorem 12.17: every fixed tail stage should already fix the exchangeable
conditional expectation. -/
private theorem condExp_exchangeableCondExp_tailStage_ae_eq_self
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) (l : ℕ) :
    μ[G | tailStage (X := X) l] =ᵐ[μ] G := by
  let A : ℕ → Ω → ℝ := fun n ↦ exchangeableAverage n ψ ∘ Xseq
  let T : ℕ → Ω → ℝ := fun n ↦ tailApprox (k := k) (φ := φ) l n ∘ Xseq
  have hF_le : tailStage (X := X) l ≤ (inferInstance : MeasurableSpace Ω) := by
    -- Proof comment: each generator of the fixed tail stage comes from a measurable coordinate.
    refine iSup_le fun i ↦ iSup_le fun hi ↦ ?_
    exact (hX_meas i).comap_le
  have hA_mem : ∀ n, MemLp (A n) 1 μ := by
    intro n
    exact
      (memLp_congr_ae
        (condExp_eq_exchangeableAverage_of_isExchangeable_finite
          (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int n)).1
        (memLp_one_iff_integrable.mpr (MeasureTheory.integrable_condExp (f := Y)))
  have hT_mem : ∀ n, MemLp (T n) 1 μ := by
    intro n
    simpa [T] using
      tailApprox_memLp_one (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int l n
  have hT_cond : ∀ n, μ[T n | tailStage (X := X) l] =ᵐ[μ] T n := by
    intro n
    have hT_int : Integrable (T n) μ := memLp_one_iff_integrable.mp (hT_mem n)
    -- Proof comment: the truncation uses only tail coordinates, so conditioning on that stage
    -- does nothing.
    simpa [T] using
      (Filter.EventuallyEq.of_eq <|
        condExp_of_stronglyMeasurable hF_le
          ((tailApprox_measurable (X := X) (φ := φ) hφ_meas l n).stronglyMeasurable)
          hT_int)
  have hApprox :
      Tendsto (fun n ↦ eLpNorm (T n - A n) 1 μ) atTop (nhds 0) := by
    simpa [T, A] using
      tendsto_eLpNorm_tailApprox_sub_exchangeableAverage
        (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int l
  have hResidual_bound :
      ∀ n,
        eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ ≤
          eLpNorm (A n - T n) 1 μ + eLpNorm (A n - T n) 1 μ := by
    intro n
    have hA_int : Integrable (A n) μ := memLp_one_iff_integrable.mp (hA_mem n)
    have hT_int : Integrable (T n) μ := memLp_one_iff_integrable.mp (hT_mem n)
    have hDiff :
        A n - μ[A n | tailStage (X := X) l] =ᵐ[μ]
          (A n - T n) - μ[A n - T n | tailStage (X := X) l] := by
      have hcond_sub :
          μ[A n - T n | tailStage (X := X) l] =ᵐ[μ]
            μ[A n | tailStage (X := X) l] - μ[T n | tailStage (X := X) l] :=
        condExp_sub hA_int hT_int _
      filter_upwards [hT_cond n, hcond_sub] with ω hTω hsubω
      change A n ω - μ[A n | tailStage (X := X) l] ω =
        (A n ω - T n ω) - μ[A n - T n | tailStage (X := X) l] ω
      simp [Pi.sub_apply, hsubω, hTω]
    have hDiff_aesm :
        AEStronglyMeasurable (A n - T n) μ :=
      (hA_mem n).aestronglyMeasurable.sub (hT_mem n).aestronglyMeasurable
    have hcond_aesm :
        AEStronglyMeasurable (μ[A n - T n | tailStage (X := X) l]) μ :=
      (MeasureTheory.integrable_condExp (f := A n - T n)).aestronglyMeasurable
    have hcond_bound :
        eLpNorm (μ[A n - T n | tailStage (X := X) l]) 1 μ ≤ eLpNorm (A n - T n) 1 μ := by
      exact
        MeasureTheory.eLpNorm_one_condExp_le_eLpNorm
          (μ := μ) (m := tailStage (X := X) l) (f := A n - T n)
    calc
      eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ =
          eLpNorm ((A n - T n) - μ[A n - T n | tailStage (X := X) l]) 1 μ := by
            exact eLpNorm_congr_ae hDiff
      _ ≤ eLpNorm (A n - T n) 1 μ +
            eLpNorm (μ[A n - T n | tailStage (X := X) l]) 1 μ := by
            exact MeasureTheory.eLpNorm_sub_le hDiff_aesm hcond_aesm (by norm_num)
      _ ≤ eLpNorm (A n - T n) 1 μ + eLpNorm (A n - T n) 1 μ := by
            gcongr
  have hResidual :
      Tendsto (fun n ↦ eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ) atTop (nhds 0) := by
    have hApprox' : Tendsto (fun n ↦ eLpNorm (A n - T n) 1 μ) atTop (nhds 0) := by
      have hEq :
          (fun n ↦ eLpNorm (A n - T n) 1 μ) = fun n ↦ eLpNorm (T n - A n) 1 μ := by
        funext n
        rw [MeasureTheory.eLpNorm_sub_comm]
      rw [hEq]
      exact hApprox
    have hmajorant :
        Tendsto
          (fun n ↦ eLpNorm (A n - T n) 1 μ + eLpNorm (A n - T n) 1 μ)
          atTop (nhds 0) := by
      simpa using hApprox'.add hApprox'
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds hmajorant
      (fun _ ↦ zero_le _)
      (fun n ↦ hResidual_bound n)
  have hlimit :=
    exchangeableAverage_tendsto_iInfCondexp
      (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int
  rcases hlimit with ⟨_, hLpInf⟩
  rcases (tendstoInLp_iff_tendsto_eLpNorm).1 hLpInf with ⟨_hmemA, hmemInf, hnormInf⟩
  have hG_mem : MemLp G 1 μ := by
    change MemLp (μ[Y | exchangeableSigmaAlgebra Xseq]) 1 μ
    exact
      (memLp_congr_ae
        (exchangeableCondExp_iInfStages_eq (X := X) (μ := μ) (φ := φ))).1 hmemInf
  have hAG :
      Tendsto (fun n ↦ eLpNorm (A n - G) 1 μ) atTop (nhds 0) := by
    have hEq :
        (fun n ↦ eLpNorm (A n - G) 1 μ) =
          fun n ↦ eLpNorm (A n - μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n]) 1 μ := by
      funext n
      refine eLpNorm_congr_ae ?_
      exact Filter.EventuallyEq.sub Filter.EventuallyEq.rfl
        (exchangeableCondExp_iInfStages_eq (X := X) (μ := μ) (φ := φ)).symm
    exact hEq ▸ hnormInf
  have hCondAG :
      Tendsto
        (fun n ↦
          eLpNorm
            (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]) 1 μ)
        atTop (nhds 0) := by
    exact
      MeasureTheory.tendsto_eLpNorm_condExp_sub_of_tendsto_eLpNorm
        (ℱ := tailStage (X := X) l) hF_le hG_mem hA_mem hAG
  have hConst_bound :
      ∀ n,
        eLpNorm (G - μ[G | tailStage (X := X) l]) 1 μ ≤
          eLpNorm (G - A n) 1 μ +
            (eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ +
              eLpNorm
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]) 1 μ) := by
    intro n
    have hDecomp :
        ∀ᵐ ω ∂μ,
          (G - μ[G | tailStage (X := X) l]) ω =
            ((G - A n) +
              ((A n - μ[A n | tailStage (X := X) l]) +
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]))) ω := by
      filter_upwards [] with ω
      change G ω - μ[G | tailStage (X := X) l] ω =
        (G ω - A n ω) +
          ((A n ω - μ[A n | tailStage (X := X) l] ω) +
            (μ[A n | tailStage (X := X) l] ω - μ[G | tailStage (X := X) l] ω))
      ring_nf
    have hLeft_aesm :
        AEStronglyMeasurable (G - A n) μ :=
      hG_mem.aestronglyMeasurable.sub (hA_mem n).aestronglyMeasurable
    have hMid_aesm :
        AEStronglyMeasurable (A n - μ[A n | tailStage (X := X) l]) μ :=
      (hA_mem n).aestronglyMeasurable.sub
        (MeasureTheory.integrable_condExp (f := A n)).aestronglyMeasurable
    have hRight_aesm :
        AEStronglyMeasurable
          (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]) μ :=
      (MeasureTheory.integrable_condExp (f := A n)).aestronglyMeasurable.sub
        (MeasureTheory.integrable_condExp (f := G)).aestronglyMeasurable
    calc
      eLpNorm (G - μ[G | tailStage (X := X) l]) 1 μ =
          eLpNorm
            ((G - A n) +
              ((A n - μ[A n | tailStage (X := X) l]) +
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]))) 1 μ := by
            exact eLpNorm_congr_ae hDecomp
      _ ≤ eLpNorm (G - A n) 1 μ +
            eLpNorm
              ((A n - μ[A n | tailStage (X := X) l]) +
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l])) 1 μ := by
            exact MeasureTheory.eLpNorm_add_le hLeft_aesm (hMid_aesm.add hRight_aesm) (by simp)
      _ ≤ eLpNorm (G - A n) 1 μ +
            (eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ +
              eLpNorm
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]) 1 μ) := by
            gcongr
            exact MeasureTheory.eLpNorm_add_le hMid_aesm hRight_aesm (by simp)
  have hmajorant :
      Tendsto
        (fun n ↦
          eLpNorm (G - A n) 1 μ +
            (eLpNorm (A n - μ[A n | tailStage (X := X) l]) 1 μ +
              eLpNorm
                (μ[A n | tailStage (X := X) l] - μ[G | tailStage (X := X) l]) 1 μ))
        atTop (nhds 0) := by
    have hGA : Tendsto (fun n ↦ eLpNorm (G - A n) 1 μ) atTop (nhds 0) := by
      have hEq :
          (fun n ↦ eLpNorm (G - A n) 1 μ) = fun n ↦ eLpNorm (A n - G) 1 μ := by
        funext n
        rw [MeasureTheory.eLpNorm_sub_comm]
      rw [hEq]
      exact hAG
    simpa [add_assoc] using hGA.add (hResidual.add hCondAG)
  have hconst :
      Tendsto (fun _ : ℕ ↦ eLpNorm (G - μ[G | tailStage (X := X) l]) 1 μ) atTop (nhds 0) := by
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le tendsto_const_nhds hmajorant
      (fun _ ↦ zero_le _)
      (fun n ↦ hConst_bound n)
  have hzero :
      eLpNorm (G - μ[G | tailStage (X := X) l]) 1 μ = 0 := by
    exact tendsto_nhds_unique tendsto_const_nhds hconst
  have hsub_zero :
      G - μ[G | tailStage (X := X) l] =ᵐ[μ] 0 := by
    have hG_int : Integrable G μ := memLp_one_iff_integrable.mp hG_mem
    exact
      (eLpNorm_eq_zero_iff
        (hG_int.sub
          (MeasureTheory.integrable_condExp (f := G))).aestronglyMeasurable
        one_ne_zero).1 hzero
  filter_upwards [hsub_zero] with ω hω
  exact (sub_eq_zero.mp hω).symm

/-- Helper for Theorem 12.17: once every fixed tail stage fixes `G`, the tail infimum fixes `G`
as well. -/
private theorem condExp_exchangeableCondExp_tail_ae_eq_self
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) :
    μ[G | tailRandomVariableMeasurableSpace X] =ᵐ[μ] G := by
  let m : ℕ → MeasurableSpace Ω := fun l ↦ tailStage (X := X) l
  have hm_le : ∀ l, m l ≤ (inferInstance : MeasurableSpace Ω) := by
    intro l
    -- Proof comment: each generator in the `l`th tail stage comes from a measurable coordinate.
    refine iSup_le fun i ↦ iSup_le fun hi ↦ ?_
    exact (hX_meas i).comap_le
  have hm_anti : Antitone m := tailStage_antitone (X := X)
  have hG_int : Integrable G μ := MeasureTheory.integrable_condExp (f := Y)
  have hlimit :
      Tendsto
        (fun l ↦ eLpNorm (μ[G | m l] - μ[G | ⨅ n : ℕ, m n]) 1 μ)
        atTop (nhds 0) :=
    tendsto_eLpNorm_condExp_iInf_of_antitone (μ := μ) (m := m) hm_le hm_anti hG_int
  have hconst :
      Tendsto (fun _ : ℕ ↦ eLpNorm (G - μ[G | ⨅ n : ℕ, m n]) 1 μ) atTop (nhds 0) := by
    have hEq :
        (fun l ↦ eLpNorm (μ[G | m l] - μ[G | ⨅ n : ℕ, m n]) 1 μ) =
          fun _ : ℕ ↦ eLpNorm (G - μ[G | ⨅ n : ℕ, m n]) 1 μ := by
      funext l
      -- Proof comment: the assumed stagewise fixed-point turns the convergence sequence into a
      -- constant one.
      refine eLpNorm_congr_ae ?_
      exact (condExp_exchangeableCondExp_tailStage_ae_eq_self
        (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int l).sub
        Filter.EventuallyEq.rfl
    exact hEq ▸ hlimit
  have hzero :
      eLpNorm (G - μ[G | ⨅ n : ℕ, m n]) 1 μ = 0 := by
    have hconst_self :
        Tendsto
          (fun _ : ℕ ↦ eLpNorm (G - μ[G | ⨅ n : ℕ, m n]) 1 μ)
          atTop
          (nhds (eLpNorm (G - μ[G | ⨅ n : ℕ, m n]) 1 μ)) :=
      tendsto_const_nhds
    exact tendsto_nhds_unique hconst_self hconst
  have hsub_zero :
      G - μ[G | ⨅ n : ℕ, m n] =ᵐ[μ] 0 := by
    -- Proof comment: vanishing `L¹` norm forces the residual to vanish almost everywhere.
    exact
      (eLpNorm_eq_zero_iff
        ((hG_int.sub (MeasureTheory.integrable_condExp (f := G))).aestronglyMeasurable)
        one_ne_zero).1 hzero
  calc
    μ[G | tailRandomVariableMeasurableSpace X] =ᵐ[μ] μ[G | ⨅ l, m l] := by
      simpa [m, tailRandomVariableMeasurableSpace_eq_iInf_tailStage (X := X)]
    _ =ᵐ[μ] G := by
      filter_upwards [hsub_zero] with ω hω
      exact (sub_eq_zero.mp hω).symm

-- Proof sketch: apply Theorem 12.10 to identify each permutation average with the conditional
-- expectation onto the finite exchangeable `σ`-algebra, then use Theorem 12.14 together with the
-- chapter owner notion `TendstoInLp` to obtain almost-sure and `L¹` convergence to the
-- expectation onto the limiting exchangeable `σ`-algebra. The limit is tail-measurable because
-- changing finitely many coordinates has asymptotically negligible effect on the permutation
-- average, so the two conditional expectations agree almost everywhere.
/-- Theorem 12.17: for an exchangeable `E`-valued sequence of random variables `X`, the
permutation averages attached to a measurable integrable `k`-variable test function `φ` converge
almost surely and in `L¹` to a common limit, and that limit is both the conditional expectation
onto the exchangeable `σ`-algebra and the conditional expectation onto the tail `σ`-algebra. -/
theorem exchangeableAverage_limit_of_isExchangeable (hX : IsExchangeable X μ)
    (hX_meas : ∀ n, Measurable (X n)) (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) :
    G =ᵐ[μ] μ[Y | tailRandomVariableMeasurableSpace X] ∧
      (∀ᵐ ω ∂μ,
        Tendsto (fun n ↦ exchangeableAverage n ψ (Xseq ω)) atTop
          (nhds (G ω))) ∧
      TendstoInLp 1 μ (fun n ↦ exchangeableAverage n ψ ∘ Xseq) G := by
  -- Route correction: the finite-stage bridge and the antitone convergence to
  -- `μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n]` are now in place.
  have hlimit :=
    exchangeableAverage_tendsto_iInfCondexp
      (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int
  rcases hlimit with ⟨haeInf, hLpInf⟩
  have haeG :
      ∀ᵐ ω ∂μ,
        Tendsto (fun n ↦ exchangeableAverage n ψ (Xseq ω)) atTop (nhds (G ω)) := by
    -- Proof comment: rewrite the almost-sure limit by the stage-intersection identity.
    filter_upwards [haeInf, exchangeableCondExp_iInfStages_eq (X := X) (μ := μ) (φ := φ)] with
      ω hω hωeq
    change Tendsto (fun n ↦ exchangeableAverage n ψ (Xseq ω)) atTop
      (nhds (μ[Y | exchangeableSigmaAlgebra Xseq] ω))
    exact hωeq ▸ hω
  have hLpG : TendstoInLp 1 μ (fun n ↦ exchangeableAverage n ψ ∘ Xseq) G := by
    change TendstoInLp 1 μ (fun n ↦ exchangeableAverage n ψ ∘ Xseq)
      (μ[Y | exchangeableSigmaAlgebra Xseq])
    rcases (tendstoInLp_iff_tendsto_eLpNorm).1 hLpInf with ⟨hmem_avg, hmem_inf, hnorm_inf⟩
    have hmem_G : MemLp G 1 μ := by
      change MemLp (μ[Y | exchangeableSigmaAlgebra Xseq]) 1 μ
      exact (memLp_congr_ae
        (exchangeableCondExp_iInfStages_eq (X := X) (μ := μ) (φ := φ))).1 hmem_inf
    have hnorm_G :
        Tendsto
          (fun n ↦
            eLpNorm
              (exchangeableAverage n ψ ∘ Xseq -
                μ[Y | exchangeableSigmaAlgebra Xseq]) 1 μ)
          atTop (nhds 0) := by
      have hEq :
          (fun n ↦
            eLpNorm
              (exchangeableAverage n ψ ∘ Xseq -
                μ[Y | exchangeableSigmaAlgebra Xseq]) 1 μ) =
            fun n ↦
              eLpNorm
                (exchangeableAverage n ψ ∘ Xseq -
                  μ[Y | ⨅ n, nExchangeableSigmaAlgebra Xseq n]) 1 μ := by
        funext n
        refine eLpNorm_congr_ae ?_
        exact Filter.EventuallyEq.sub Filter.EventuallyEq.rfl
          (exchangeableCondExp_iInfStages_eq (X := X) (μ := μ) (φ := φ)).symm
      exact hEq ▸ hnorm_inf
    exact (tendstoInLp_iff_tendsto_eLpNorm).2 ⟨hmem_avg, hmem_G, hnorm_G⟩
  refine ⟨?_, haeG, hLpG⟩
  have htail_tower :
      μ[G | tailRandomVariableMeasurableSpace X] =ᵐ[μ]
        μ[Y | tailRandomVariableMeasurableSpace X] :=
    condExp_exchangeableCondExp_tail_ae_eq_condExp_tail
      (X := X) (μ := μ) (φ := φ) hX_meas
  have hG_tail :
      μ[G | tailRandomVariableMeasurableSpace X] =ᵐ[μ] G :=
    condExp_exchangeableCondExp_tail_ae_eq_self
      (X := X) (μ := μ) (φ := φ) hX hX_meas hφ_meas hφ_int
  -- Proof comment: once tail conditioning fixes `G`, the previous tower identity rewrites the
  -- tail conditional expectation of `Y` to `G`.
  calc
    G =ᵐ[μ] μ[G | tailRandomVariableMeasurableSpace X] := hG_tail.symm
    _ =ᵐ[μ] μ[Y | tailRandomVariableMeasurableSpace X] := htail_tower

-- Proof sketch: pass from the owner `TendstoInLp` statement to its `eLpNorm` bridge via
-- `TendstoInLp.tendsto_eLpNorm`, then rewrite the standard `p = 1` identity with the integral of
-- the absolute value.
/-- Bridge companion to Theorem 12.17: the canonical `L¹` convergence statement can be rewritten
as convergence of the integral of the absolute difference. -/
theorem exchangeableAverage_tendsto_integral_abs_sub_condexp_exchangeable
    (hX : IsExchangeable X μ) (hX_meas : ∀ n, Measurable (X n))
    (hφ_meas : Measurable φ) (hφ_int : Integrable Y μ) :
    Tendsto
      (fun n ↦ ∫ ω, |exchangeableAverage n ψ (Xseq ω) - G ω| ∂μ)
      atTop (nhds 0) := by
  let fSeq : ℕ → Ω → ℝ := fun n ↦ exchangeableAverage n ψ ∘ Xseq
  have hLp : TendstoInLp 1 μ fSeq G :=
    (exchangeableAverage_limit_of_isExchangeable hX hX_meas hφ_meas hφ_int).2.2
  have hIntSub : ∀ n, Integrable (fSeq n - G) μ := by
    intro n
    exact memLp_one_iff_integrable.mp ((hLp.memLpSeq n).sub hLp.memLp)
  have hnorm :
      Tendsto (fun n ↦ (eLpNorm (fSeq n - G) 1 μ).toReal) atTop (nhds 0) := by
    -- Proof comment: move the `TendstoInLp` conclusion to the scalar `eLpNorm` and then pass from
    -- `ℝ≥0∞` to `ℝ` via `ENNReal.toReal` at the limit point `0`.
    simpa using (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp hLp.tendsto_eLpNorm
  have hrewrite :
      (fun n ↦ (eLpNorm (fSeq n - G) 1 μ).toReal) =
        fun n ↦ ∫ ω, |exchangeableAverage n ψ (Xseq ω) - G ω| ∂μ := by
    funext n
    -- Proof comment: for `p = 1`, the `eLpNorm` is the integral of the norm, and on `ℝ` the norm
    -- is the absolute value.
    calc
      (eLpNorm (fSeq n - G) 1 μ).toReal =
          (ENNReal.ofReal (∫ ω, ‖(fSeq n - G) ω‖ ∂μ)).toReal := by
            rw [eLpNorm_one_eq_lintegral_enorm,
              ← ofReal_integral_norm_eq_lintegral_enorm (hIntSub n)]
      _ = ∫ ω, ‖(fSeq n - G) ω‖ ∂μ := by
            have hnonneg : 0 ≤ ∫ ω, ‖(fSeq n - G) ω‖ ∂μ := by
              exact integral_nonneg fun ω ↦ norm_nonneg _
            rw [ENNReal.toReal_ofReal hnonneg]
      _ = ∫ ω, |exchangeableAverage n ψ (Xseq ω) - G ω| ∂μ := by
            refine integral_congr_ae ?_
            filter_upwards with ω
            simp [fSeq, Real.norm_eq_abs]
  convert hnorm using 1
  exact hrewrite.symm

end
