import Mathlib.Tactic.Recall
import ConvexAnalysis_Rockafellar_1970.Chap06.Definition_6_30_4
import ConvexAnalysis_Rockafellar_1970.Chap07.Defn_34_2

noncomputable section

universe u v u' v'

open scoped Rockafellar

namespace Bifunction

/- Definition 34.6 reuses Chapter 34's canonical representative owners from `Defn_34_2`. -/
recall lowerPairing
recall upperAdjointPairing
recall omegaAdjoint
recall mem_omegaAdjoint_iff

section

variable {U : Type u} {UStar : Type u'} {X : Type v} {XStar : Type v'}
variable {L : Type*}
variable [InfSet L] [Sub L]

/-!
Source/core/bridge triage:

- `source-facing`: Definition 34.6 also names the concave-side class `Ω(G)` generated by a
  closed concave bifunction `G`.
- `core/canonical`: the convex-side class `Ω(F)` is already owned by `Bifunction.omega` from
  `Defn_34_2`, together with its owner theorem `mem_omega_iff`.
- `bridge/view`: the source class is represented by the slice-wise Chapter 6
  concave-conjugate upper representative `(u, x⋆) ↦ (G x⋆)∗ u`.
  This file owns that bridge map and then applies the mixed-dual class owner
  `Bifunction.omegaAdjoint` to it.

Primitive data vs derived API:
- primitive bridge datum owned here: `upperConcavePairing G`;
- primitive concave-side owner reused here: `Function.IsClosedConcave (Function.uncurry G)`;
- no new primitive class owner is introduced: the source-facing class notation `ΩConc(G)` is a
  direct notation view of `omegaAdjoint` on `upperConcavePairing G`;
- derived API: the induced membership restatement `mem_omegaConcave_iff`.

Layer target: `bridge/view`. The numbered item contributes the concave-side specialization of the
existing mixed-dual owner `omegaAdjoint`; this file therefore exposes that specialization as a
stable owner declaration, keeping the same canonical chapter vocabulary.
-/

/- Domain-style sampling for this refine pass:
- `Function.IsClosedConcave` from `Definition33_0_27`, the canonical closed-concave owner for one
  function on a paired space;
- `Bifunction.lowerPairing` and `Bifunction.upperPairing` from `Defn_34_2`, the canonical Chapter
  34 representatives;
- `Bifunction.omega` from `Defn_34_2`, the canonical owner for a Chapter 34 representative class;
- `Bifunction.concaveAdjoint` from `Definition_6_30_15`, the generic paired-space owner
  showing that Chapter 34 concave-side constructions should stay on `G : XStar → UStar → L`
  rather than collapsing to a self-dual specialization.

Primary mathematical domain: Chapter 34 bifunction representative classes on paired spaces.

Owner abstraction decision:
- `source-facing`: `upperConcavePairing G` and `ΩConc(G)` for a bifunction
  `G : XStar → UStar → L`;
- `core/canonical`: `Function.IsClosedConcave` for the graph function and
  `Bifunction.omegaAdjoint` for the representative class;
- `bridge/view`: this file only supplies the Chapter 34 concave-side view of those owners.

Primitive data vs derived API refinement:
- primitive data: a paired-space bifunction `G : XStar → UStar → L`;
- primitive ambient owners: the product pairing
  `HasPairing (XStar × UStar) (X × U) L`, the reversed `XStar`-pairing, and the mixed pairing
  `(U × XStar, UStar × X)` needed by the Chapter 34 `omegaAdjoint` owner;
- derived API: the `Function.uncurry` closed-concave bridge and the membership restatement for
  `ΩConc(G)`.
-/

/-!
The bridge representative `(u, x⋆) ↦ (G x⋆)∗ u` appears repeatedly in Chapter 34.
It is the order-dual, swapped-variable view of the existing Chapter 34 lower representative, so
this file keeps only the source-facing bridge name rather than a second primitive slice-conjugate
implementation.
-/
/-- Definition 34.6's canonical upper representative attached to a concave bifunction `G`. This
is the general-dual owner behind the old self-dual formula `(u, x⋆) ↦ (G x⋆)∗ u`. -/
def upperConcavePairing [HasPairing U UStar L] (G : XStar → UStar → L) :
    U → XStar → L :=
  let _ : HasPairing UStar U (OrderDual L) := HasPairing.swap
  Function.swap ((lowerPairing U G : XStar → U → OrderDual L))

@[simp] theorem upperConcavePairing_apply
    [HasPairing U UStar L]
    (G : XStar → UStar → L) (u : U) (xStar : XStar) :
    upperConcavePairing G u xStar = (G xStar)∗ u :=
  rfl

section

variable [SupSet L] [Preorder L]
variable [Neg L] [Neg UStar]
variable [HasPairing U UStar L]

/-- Definition 34.6 (concave-side class): for a concave bifunction `G`, the chapter class `Ω(G)`
is the Chapter 34 mixed-dual owner `omegaAdjoint` applied to the canonical upper representative
`upperConcavePairing G`. The source-facing surface is notation-only; no extra owner alias is
introduced under it. -/
scoped[Rockafellar] notation "ΩConc" "(" G ")" =>
  ΩAdj[_](Bifunction.upperConcavePairing G)

/-- Membership in Definition 34.6's concave-side class is exactly the chapter sandwich relation
for the canonical upper representative `upperConcavePairing G` at the mixed-dual layer. -/
theorem mem_omegaConcave_iff
    [HasPairing XStar X L] [HasPairing (U × XStar) (UStar × X) L]
    (G : XStar → UStar → L) (K : U → X → L) :
    K ∈ ΩConc(G) ↔
      lowerPairing X (upperConcavePairing G) ≤ K ∧
        K ≤ upperAdjointPairing X UStar (upperConcavePairing G) := by
  simpa using
    (mem_omegaAdjoint_iff (X := XStar) (XStar := X) (UStar := UStar)
      (F := upperConcavePairing G) (K := K))

end

end

end Bifunction
