import Mathlib.CategoryTheory.IsConnected
import Mathlib.CategoryTheory.Limits.Constructions.Over.Connected
import Mathlib.CategoryTheory.Limits.Preserves.Opposites
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Definition_4_16_1 (from Chap04) -/
universe v u

namespace CategoryTheory

variable {J : Type u} [Category.{v} J]

/- Domain-style sampling for Definition 4.16.1:
- primary domain: connected categories and zigzag connectivity in `CategoryTheory`;
- sampled owner-level declarations:
  `IsConnected`,
  `Zigzag`,
  `isPreconnected_zigzag`,
  `zigzag_isConnected`;
- best owner abstraction: the canonical owner is the class `IsConnected J`;
- primitive data: the owner class `IsConnected J`;
- derived API: `isPreconnected_zigzag`, `zigzag_isConnected`, and the source-facing zigzag
  characterization below.

Source/core/bridge triage:
- `source-facing`: the textbook zigzag characterization of connectedness;
- `core/canonical`: `IsConnected`;
- `bridge/view`: the equivalence theorem below, which restates the source wording in terms of the
  canonical owner. -/

/- Canonical recall: a category is connected when the equivalence relation generated by the
existence of a morphism between two objects has exactly one equivalence class; this is the
canonical mathlib notion `CategoryTheory.IsConnected`. -/
recall IsConnected

/-- Definition 4.16.1: a category is connected exactly when it is nonempty and any two objects are
related by the zigzag relation generated by the existence of morphisms in either direction. -/
theorem isConnected_iff_nonempty_and_zigzag :
    IsConnected J ↔ Nonempty J ∧ ∀ j₁ j₂ : J, Zigzag j₁ j₂ := by
  constructor
  · intro hJ
    letI : IsConnected J := hJ
    exact ⟨inferInstance, isPreconnected_zigzag⟩
  · rintro ⟨hJ, hzigzag⟩
    letI : Nonempty J := hJ
    exact zigzag_isConnected hzigzag

end CategoryTheory

/-! ### Lemma_4_16_2 (from Chap04) -/
universe v₁ v₂ u₁ u₂

namespace CategoryTheory

open Limits

variable {J : Type u₁} [Category.{v₁} J] [IsConnected J]
variable {C : Type u₂} [Category.{v₂} C]
variable {X : C} (M : J ⥤ Over X)

/- Domain-style sampling for Lemma 4.16.2:
- primary domain: connected limits in slice categories, with the slice projection `Over.forget X`
  as the ambient owner functor;
- sampled owner API:
  `Over.createsLimitsOfShapeForgetOfIsConnected`,
  `Over.preservesLimitsOfShape_forget_of_isConnected`,
  `PreservesLimitsOfShape.preservesLimit`;
- best owner abstraction: the connected-limit preservation instance on `Over.forget X`;
- primitive data: the connected diagram shape `J`, the slice projection `Over.forget X`, and the
  owner instance `PreservesLimitsOfShape J (Over.forget X)`;
- derived API: for each fixed diagram `M : J ⥤ Over X`, the specialized instance
  `PreservesLimit M (Over.forget X)`.

The statement in this file lives at the `bridge/view` layer: it specializes the ambient owner
instance to one diagram, so it should reuse `PreservesLimitsOfShape.preservesLimit` rather than
introducing a local wrapper or restating the universal property.
-/

/- Source/core/bridge triage for Lemma 4.16.2:
- `source-facing`: the specialized preservation statement for a fixed connected diagram
  `M : J ⥤ Over X`.
- `core/canonical`: the owner instance
  `Over.preservesLimitsOfShape_forget_of_isConnected`.
- `bridge/view`: the derived instance `PreservesLimit M (Over.forget X)`, obtained from
  `PreservesLimitsOfShape.preservesLimit`.
-/

/- Lemma 4.16.2: if `M : J ⥤ Over X` is a diagram indexed by a connected category and `M` has a
limit in `Over X`, then after forgetting to `C` the underlying diagram has the same limit. This is
the canonical connected-limit preservation instance on `Over.forget X`, specialized to `M`. -/
#check (inferInstance : PreservesLimit M (Over.forget X))

end CategoryTheory

/-! ### Lemma_4_16_3 (from Chap04) -/
universe v₁ v₂ u₁ u₂

namespace CategoryTheory

open Limits

variable {J : Type u₁} [Category.{v₁} J]
variable {C : Type u₂} [Category.{v₂} C]
variable {X : C}

/- Companion recall: for a connected indexing category `J`, the forgetful functor
`Over.forget (op X)` preserves `Jᵒᵖ`-shaped limits. -/
recall Over.preservesLimitsOfShape_forget_of_isConnected

/-- Lemma 4.16.3: for a connected diagram `M : J ⥤ Under X`, the forgetful functor
`Under.forget X` preserves the colimit of `M`. Equivalently, whenever `M` has a colimit in
`Under X`, the underlying diagram in `C` has the same colimit. -/
-- Proof sketch: dualize the connected-limit statement for `Over.forget (op X)` using
-- `Over.opEquivOpUnder X` and the opposites API, then specialize the resulting
-- `PreservesColimitsOfShape` instance to the diagram `M`.
theorem under_forget_preserves_colimit_of_isConnected (M : J ⥤ Under X) [IsConnected J] :
    PreservesColimit M (Under.forget X) := by
  -- Move the opposite diagram across the over-under equivalence so the connected-limit
  -- statement for `Over.forget (op X)` applies to the transported diagram.
  have h_limit_via_over :
      PreservesLimit M.op
        (((Over.opEquivOpUnder X).symm.functor) ⋙ Over.forget (Opposite.op X)) := by
    infer_instance
  -- Identify the transported forgetful functor with the opposite of `Under.forget X`.
  have h_comparison :
      ((Over.opEquivOpUnder X).symm.functor ⋙ Over.forget (Opposite.op X)) ≅
        (Under.forget X).op := by
    refine NatIso.ofComponents (fun Y ↦ Iso.refl _) ?_
    intro Y Z f
    cases f
    simp [Over.opEquivOpUnder]
  -- Transport the preservation result across that comparison isomorphism.
  have h_limit_op : PreservesLimit M.op (Under.forget X).op := by
    letI : PreservesLimit M.op
        (((Over.opEquivOpUnder X).symm.functor) ⋙ Over.forget (Opposite.op X)) :=
      h_limit_via_over
    exact preservesLimit_of_natIso M.op h_comparison
  -- Convert the opposite-side limit preservation statement back to the desired colimit claim.
  letI : PreservesLimit M.op (Under.forget X).op := h_limit_op
  simpa using (preservesColimit_of_op M (Under.forget X))

end CategoryTheory
