import Mathlib
import Serre.Chap01.Theorem_1_1_4_2
import Serre.Chap03.Definition_3_3_3_1
import Serre.Chap03.Exercise_3_3_3_6
import Serre.Chap07.Proposition_7_7_1_3
import Serre.Chap07.Proposition_7_7_2_1
import Serre.Chap07.Remark_7_7_1_4
import Serre.Chap08.Definition_8_8_3_2
import Serre.Chap08.Exercise_8_8_3_9
import Serre.Chap10.Definition_10_10_1_3
import Serre.Chap10.MonomialCharacter
import Serre.Chap10.Theorem_10_10_2_1
import Serre.Chap11.Theorem_11_11_2_1.TensorCharacterBridge

noncomputable section

namespace Representation

open CategoryTheory Rep
open scoped Representation SubgroupInduction
open scoped BigOperators Pointwise

section

variable {G : Type} [Group G] [Finite G]

/-- A finite group has a fintype structure in this local support file. -/
local instance theorem_10_10_5_2_brauer_infra_fintype_of_finite : Fintype G := Fintype.ofFinite G

/-- A subgroup of a finite group has a fintype structure in this local support file. -/
local instance theorem_10_10_5_2_brauer_infra_subgroup_fintype_of_finite (H : Subgroup G) :
    Fintype H := Fintype.ofFinite H

/-- A monomial character belongs to Serre's integral character ring `R(G)`. -/
theorem IsMonomialCharacter.mem_characterRing {χ : G → ℂ}
    (hχ : IsMonomialCharacter χ) :
    χ ∈ R(G) := by
  rcases hχ with ⟨H, α, rfl⟩
  simpa [MonoidHom.toCharacterRing_apply] using
    Subgroup.inducedClassFunction_mem_characterRing H (MonoidHom.toCharacterRing α)

/-- The `ℤ`-submodule of Serre's character ring `R(G)` generated by the monomial characters of
`G`. This is the ambient `R(G)`-view of the source-facing owner `IsMonomialCharacter`. -/
def monomialCharacterSpan (G : Type) [Group G] [Finite G] : Submodule ℤ (R(G)) :=
  Submodule.span ℤ {χ : R(G) | IsMonomialCharacter (χ : G → ℂ)}

-- Proof sketch: the corresponding element of `R(G)` is one of the generators of
-- `monomialCharacterSpan G` by definition, so apply `Submodule.subset_span`.
/-- Every monomial character of `G` belongs to the monomial-character span inside `R(G)`. -/
theorem mem_monomialCharacterSpan_of_isMonomialCharacter {χ : G → ℂ}
    (hχ : IsMonomialCharacter χ) :
    (⟨χ, hχ.mem_characterRing⟩ : R(G)) ∈ monomialCharacterSpan G := by
  exact Submodule.subset_span hχ

/-- The induced character of a degree-`1` subgroup character belongs to the monomial-character
span inside `R(G)`. -/
theorem induced_character_mem_monomialCharacterSpan (H : Subgroup G)
    (α : H →* ℂˣ) :
    Representation.Subgroup.characterRingInduction H
      (MonoidHom.toCharacterRing α) ∈ monomialCharacterSpan G := by
  simpa [Representation.Subgroup.characterRingInduction_apply, MonoidHom.toCharacterRing_apply] using
    mem_monomialCharacterSpan_of_isMonomialCharacter (isMonomialCharacter_of_induced H α)

/-- Helper for Theorem 10-10.5-2: the character of a finite-dimensional complex representation,
bundled as an element of Serre's character ring `R(G)`. -/
abbrev fdRepCharacterRing (V : FDRep ℂ G) : R(G) :=
  ⟨V.character, by simpa using Representation.rep_character_mem_characterRing (Rep.of V.ρ)⟩

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: the trivial one-dimensional representation gives the unit of
`R(G)`. -/
theorem fdRepCharacterRing_trivial_eq_one :
    fdRepCharacterRing (FDRep.of (Representation.trivial ℂ G ℂ)) = (1 : R(G)) := by
  -- The trivial character is the constant function `1`, so its bundled ring element is the unit.
  apply Subtype.ext
  ext g
  have htriv : (Representation.trivial ℂ G ℂ).character = (1 : G → ℂ) := by
    -- The trivial action is the identity on a one-dimensional space.
    ext x
    simp [Representation.character, Representation.trivial]
  change (Representation.trivial ℂ G ℂ).character g = 1
  simpa using congrFun htriv g

/-- Helper for Theorem 10-10.5-2: tensor products multiply finite-dimensional characters inside
`R(G)`. -/
theorem fdRepCharacterRing_tensor_eq_mul (V W : FDRep ℂ G) :
    fdRepCharacterRing (CategoryTheory.MonoidalCategoryStruct.tensorObj V W) =
      fdRepCharacterRing V * fdRepCharacterRing W := by
  -- `FDRep.char_tensor` is the character-level multiplicativity statement; bundle it into `R(G)`.
  apply Subtype.ext
  ext g
  change (CategoryTheory.MonoidalCategoryStruct.tensorObj V W).character g =
    (V.character * W.character) g
  exact congrFun (FDRep.char_tensor V W) g

/-- Helper for Theorem 10-10.5-2: a degree-`1` character on `K ≤ H` transports to the image
subgroup `K.map H.subtype ≤ G`. -/
def Subgroup.mappedLinearCharacter
    (H : Subgroup G) (K : Subgroup H) (α : K →* ℂˣ) :
    K.map H.subtype →* ℂˣ :=
  α.comp (K.equivMapOfInjective H.subtype H.subtype_injective).symm.toMonoidHom

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: restricting the mapped subgroup `K.map H.subtype` back to `H`
recovers the original subgroup `K`. -/
theorem subgroup_chain_inner_subgroup_eq
    (H : Subgroup G) (K : Subgroup H) :
    ((K.map H.subtype).subgroupOf H : Subgroup H) = K := by
  -- The image subgroup consists exactly of those elements of `H` coming from `K`.
  ext k
  change k.1 ∈ K.map H.subtype ↔ k ∈ K
  constructor
  · intro hk
    rcases hk with ⟨x, hx, hxk⟩
    have : x = k := by
      apply Subtype.ext
      simpa using hxk
    simpa [this] using hx
  · intro hk
    exact ⟨k, hk, rfl⟩

/-- Helper for Theorem 10-10.5-2: the mapped subgroup `K.map H.subtype` is contained in `H`. -/
theorem subgroup_chain_map_le
    (H : Subgroup G) (K : Subgroup H) :
    K.map H.subtype ≤ H := by
  -- Every element of the mapped subgroup is literally the image of an element of `K ≤ H`.
  intro x hx
  rcases hx with ⟨y, -, rfl⟩
  exact y.property

/-- Helper for Theorem 10-10.5-2: transporting the mapped linear character back along
`((K.map H.subtype).subgroupOf H) ≃ K` recovers the original induced character on `H`. -/
theorem Subgroup.transport_mappedLinearCharacter_eq_original
    (H : Subgroup G) (K : Subgroup H) (α : K →* ℂˣ) :
    ((((K.map H.subtype).subgroupOf H).classFunctionInduction
      (fun x : (K.map H.subtype).subgroupOf H ↦
        ((Subgroup.mappedLinearCharacter H K α).toRepresentation.character)
          ((Subgroup.subgroupOfEquivOfLe (subgroup_chain_map_le H K)) x)) : H → ℂ) =
      Ind[K](α.toRepresentation.character)) := by
  -- Expand the induced-function formula so the subgroup identification is only used in card and
  -- membership positions, where `simp` can normalize it safely.
  ext h
  simp [Subgroup.classFunctionInduction_apply, Subgroup.inducedClassFunction,
    subgroup_chain_inner_subgroup_eq H K]
  congr with x
  by_cases hk : x⁻¹ * h * x ∈ K
  · have hsg : x⁻¹ * h * x ∈ (K.map H.subtype).subgroupOf H := by
      simpa [subgroup_chain_inner_subgroup_eq H K] using hk
    have htransport :
        (K.equivMapOfInjective H.subtype H.subtype_injective).symm
            ((Subgroup.subgroupOfEquivOfLe (subgroup_chain_map_le H K))
              ⟨x⁻¹ * h * x, hsg⟩) =
          ⟨x⁻¹ * h * x, hk⟩ := by
      apply (K.equivMapOfInjective H.subtype H.subtype_injective).injective
      apply Subtype.ext
      simp
    simp [hk, hsg, htransport, Subgroup.mappedLinearCharacter]
  · have hsg : ¬ x⁻¹ * h * x ∈ (K.map H.subtype).subgroupOf H := by
      simpa [subgroup_chain_inner_subgroup_eq H K] using hk
    simp [hk, hsg]

/-- Helper for Theorem 10-10.5-2: if `L ≤ H ≤ G`, inducing first from `L` to `H` and then from
`H` to `G` agrees with direct induction from `L` to `G`. -/
theorem Subgroup.inducedClassFunction_subgroupOf_induction_in_stages
    (H L : Subgroup G) (hL : L ≤ H) (f : L → ℂ) :
    Subgroup.inducedClassFunction H
      (Subgroup.inducedClassFunction (L.subgroupOf H)
        (fun x : L.subgroupOf H ↦ f ((Subgroup.subgroupOfEquivOfLe hL) x))) =
      Subgroup.inducedClassFunction L f := by
  classical
  let _ : DecidablePred fun z : G ↦ z ∈ H := Classical.decPred _
  let _ : DecidablePred fun z : G ↦ z ∈ L := Classical.decPred _
  let _ : DecidablePred fun z : H ↦ z ∈ L.subgroupOf H := Classical.decPred _
  ext g
  have hcard : Nat.card (L.subgroupOf H) = Nat.card L := by
    exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe hL).toEquiv
  let φ : G → ℂ := fun s ↦
    if hs : s⁻¹ * g * s ∈ L then
      f ⟨s⁻¹ * g * s, hs⟩
    else
      0
  have hinner :
      ∀ x : G,
        (if hsg : x⁻¹ * g * x ∈ H then
          (↑(Nat.card ↥L) : ℂ)⁻¹ *
            ∑ y : H,
              if hsg_1 : y⁻¹ * ⟨x⁻¹ * g * x, hsg⟩ * y ∈ L.subgroupOf H then
                f ((Subgroup.subgroupOfEquivOfLe hL)
                  ⟨y⁻¹ * ⟨x⁻¹ * g * x, hsg⟩ * y, hsg_1⟩)
              else
                0
        else
          0) =
        (↑(Nat.card ↥L) : ℂ)⁻¹ * ∑ y : H, φ (x * y) := by
    intro x
    by_cases hx : x⁻¹ * g * x ∈ H
    · -- Once the conjugate of `g` by `x` lies in `H`, both inner sums are indexed by the same
      -- elements of `H`, and the subgroup equivalence only changes the subtype wrapper.
      rw [dif_pos hx]
      congr 1
      apply Finset.sum_congr rfl
      intro y hy
      have hmul :
          (((y : H) : G)⁻¹) * (x⁻¹ * g * x) * ((y : H) : G) =
            (x * y : G)⁻¹ * g * (x * y : G) := by
        group
      dsimp [φ]
      by_cases hxy : (x * y : G)⁻¹ * g * (x * y : G) ∈ L
      · have hsub : ((y : H)⁻¹ * ⟨x⁻¹ * g * x, hx⟩ * y) ∈ L.subgroupOf H := by
          change (((y : H) : G)⁻¹ * (x⁻¹ * g * x) * (y : H)) ∈ L
          simpa [hmul] using hxy
        rw [dif_pos hsub, dif_pos hxy]
        congr 1
        apply Subtype.ext
        simp [Subgroup.subgroupOfEquivOfLe, hmul]
      · have hsub : ¬ ((y : H)⁻¹ * ⟨x⁻¹ * g * x, hx⟩ * y) ∈ L.subgroupOf H := by
          change ¬ ((((y : H) : G)⁻¹ * (x⁻¹ * g * x) * (y : H)) ∈ L)
          simpa [hmul] using hxy
        rw [dif_neg hsub, dif_neg hxy]
    · -- If the conjugate misses `H`, then it certainly misses `L ≤ H`, so the whole inner sum
      -- vanishes on both sides.
      have hall : ∀ y : H, φ (x * y) = 0 := by
        intro y
        dsimp [φ]
        by_cases hxy : (x * y : G)⁻¹ * g * (x * y : G) ∈ L
        · exfalso
          apply hx
          have hxyH : (x * y : G)⁻¹ * g * (x * y : G) ∈ H := hL hxy
          simpa [mul_assoc] using
            H.mul_mem (H.mul_mem y.2 hxyH) (H.inv_mem y.2)
        · rw [dif_neg hxy]
      rw [dif_neg hx]
      simp [hall]
  -- Expand both induction operators and collapse the double sum by the bijection
  -- `(x, y) ↦ (x * y, y)` on `G × H`.
  calc
    Subgroup.inducedClassFunction H
        (Subgroup.inducedClassFunction (L.subgroupOf H)
          (fun x : L.subgroupOf H ↦ f ((Subgroup.subgroupOfEquivOfLe hL) x))) g =
      ((↑(Nat.card ↥H) : ℂ)⁻¹) * ∑ x : G,
        ((↑(Nat.card ↥L) : ℂ)⁻¹) * ∑ y : H, φ (x * y) := by
      change ((↑(Nat.card ↥H) : ℂ)⁻¹) *
          ∑ s : G,
            (if hsg : s⁻¹ * g * s ∈ H then
              Subgroup.inducedClassFunction (L.subgroupOf H)
                (fun x : L.subgroupOf H ↦ f ((Subgroup.subgroupOfEquivOfLe hL) x))
                ⟨s⁻¹ * g * s, hsg⟩
            else
              0) = _
      congr 1
      apply Finset.sum_congr rfl
      intro x hx
      rw [Subgroup.inducedClassFunction, hcard]
      exact hinner x
    _ = ((↑(Nat.card ↥H) : ℂ)⁻¹) *
        (((↑(Nat.card ↥L) : ℂ)⁻¹) * ∑ x : G, ∑ y : H, φ (x * y)) := by
      simp [Finset.mul_sum]
    _ = ((↑(Nat.card ↥H) : ℂ)⁻¹) *
        (((↑(Nat.card ↥L) : ℂ)⁻¹) * ∑ p : G × H, φ p.1) := by
      congr 2
      calc
        ∑ x : G, ∑ y : H, φ (x * y) = ∑ p : G × H, φ (p.1 * p.2) := by
          rw [Fintype.sum_prod_type]
        _ = ∑ p : G × H, φ p.1 := by
          let e : G × H ≃ G × H :=
            { toFun := fun p ↦ (p.1 * p.2, p.2)
              invFun := fun p ↦ (p.1 * p.2⁻¹, p.2)
              left_inv := by
                intro p
                ext <;> simp [mul_assoc]
              right_inv := by
                intro p
                ext <;> simp [mul_assoc] }
          exact Fintype.sum_equiv e
            (fun p : G × H ↦ φ (p.1 * p.2))
            (fun p : G × H ↦ φ p.1)
            (fun p ↦ rfl)
    _ = ((↑(Nat.card ↥H) : ℂ)⁻¹) *
        (((↑(Nat.card ↥L) : ℂ)⁻¹) * ((↑(Nat.card ↥H) : ℂ) * ∑ z : G, φ z)) := by
      congr 2
      calc
        ∑ p : G × H, φ p.1 = ∑ z : G, ∑ y : H, φ z := by
          rw [Fintype.sum_prod_type]
        _ = ∑ z : G, (↑(Nat.card ↥H) : ℂ) * φ z := by
          simp
        _ = (↑(Nat.card ↥H) : ℂ) * ∑ z : G, φ z := by
          rw [Finset.mul_sum]
    _ = (↑(Nat.card ↥L) : ℂ)⁻¹ * ∑ z : G, φ z := by
      have hH0 : (↑(Nat.card ↥H) : ℂ) ≠ 0 := by
        exact Nat.cast_ne_zero.mpr Nat.card_pos.ne'
      field_simp [hH0, mul_assoc]
    _ = Ind[L](f) g := by
      simp [Subgroup.inducedClassFunction, φ]

/-- Helper for Theorem 10-10.5-2: inducing from `K ≤ H ≤ G` in two steps agrees with direct
induction from the image subgroup `K.map H.subtype ≤ G`. -/
theorem Subgroup.inducedClassFunction_subgroup_chain
    (H : Subgroup G) (K : Subgroup H) (f : K.map H.subtype → ℂ) :
    Subgroup.inducedClassFunction H
      (Subgroup.inducedClassFunction ((K.map H.subtype).subgroupOf H)
        (fun x : (K.map H.subtype).subgroupOf H ↦
          f ((Subgroup.subgroupOfEquivOfLe (subgroup_chain_map_le H K)) x))) =
      Subgroup.inducedClassFunction (K.map H.subtype) f := by
  -- This is the generic subgroup-of induction-in-stages identity specialized to the mapped chain
  -- `K.map H.subtype ≤ H`.
  simpa using
    (Subgroup.inducedClassFunction_subgroupOf_induction_in_stages
      H (K.map H.subtype) (subgroup_chain_map_le H K) f)

/-- Helper for Theorem 10-10.5-2: inducing a linear character from `K ≤ H ≤ G` agrees with the
one-step induction from the image subgroup `K.map H.subtype ≤ G`. -/
theorem Subgroup.characterRingInduction_induced_linearCharacter_subgroup_chain
    (H : Subgroup G) (K : Subgroup H) (α : K →* ℂˣ) :
    Representation.Subgroup.characterRingInduction H
      (Representation.Subgroup.characterRingInduction K (MonoidHom.toCharacterRing α)) =
      Representation.Subgroup.characterRingInduction (K.map H.subtype)
        (MonoidHom.toCharacterRing (Subgroup.mappedLinearCharacter H K α)) := by
  -- Route correction: normalize the inner induced character on `H`, then apply the direct
  -- subgroup-chain induction-in-stages identity at the class-function level.
  apply Subtype.ext
  ext g
  calc
    ((Representation.Subgroup.characterRingInduction H
        (Representation.Subgroup.characterRingInduction K
          (MonoidHom.toCharacterRing α)) : R(G)) : G → ℂ) g =
      Ind[H](Ind[K](α.toRepresentation.character)) g := by
        simp [Representation.Subgroup.characterRingInduction_apply]
    _ =
      Ind[H](Subgroup.inducedClassFunction ((K.map H.subtype).subgroupOf H)
          (fun x : (K.map H.subtype).subgroupOf H ↦
            ((Subgroup.mappedLinearCharacter H K α).toRepresentation.character)
              ((Subgroup.subgroupOfEquivOfLe (subgroup_chain_map_le H K)) x))) g := by
        exact congrArg (fun φ : H → ℂ ↦ Ind[H](φ) g)
          (Subgroup.transport_mappedLinearCharacter_eq_original H K α).symm
    _ = Subgroup.inducedClassFunction (K.map H.subtype)
        ((Subgroup.mappedLinearCharacter H K α).toRepresentation.character) g := by
        simpa using congrFun
          (Subgroup.inducedClassFunction_subgroup_chain H K
            ((Subgroup.mappedLinearCharacter H K α).toRepresentation.character))
          g
    _ =
      (((Representation.Subgroup.characterRingInduction (K.map H.subtype)
        (MonoidHom.toCharacterRing (Subgroup.mappedLinearCharacter H K α)) : R(G)) :
          G → ℂ) g) := by
        simp [Representation.Subgroup.characterRingInduction_apply]

/-- Helper for Theorem 10-10.5-2: induction from a subgroup sends the monomial-character span
into the ambient monomial-character span. -/
theorem Subgroup.characterRingInduction_map_monomialCharacterSpan (H : Subgroup G) :
    Submodule.map (Representation.Subgroup.characterRingInduction H) (monomialCharacterSpan H) ≤
      monomialCharacterSpan G := by
  -- Route correction: reduce the image of the span to monomial generators, then rewrite each
  -- subgroup-chain induction to a one-step induction from `K.map H.subtype`.
  rw [monomialCharacterSpan, Submodule.map_span_le]
  intro χ hχ
  rcases hχ with ⟨K, α, hχ⟩
  -- Repackage the generator as the canonical character-ring induction from `K ≤ H`.
  have hχeq :
      χ = Representation.Subgroup.characterRingInduction K (MonoidHom.toCharacterRing α) := by
    apply Subtype.ext
    simpa [Representation.Subgroup.characterRingInduction_apply,
      MonoidHom.toCharacterRing_apply] using hχ.symm
  -- Induction in stages moves the generator to an honest monomial character on `G`.
  have hmon :
      Representation.Subgroup.characterRingInduction (K.map H.subtype)
          (MonoidHom.toCharacterRing (Subgroup.mappedLinearCharacter H K α)) ∈
        monomialCharacterSpan G :=
    induced_character_mem_monomialCharacterSpan
      (K.map H.subtype) (Subgroup.mappedLinearCharacter H K α)
  have hrewrite :
      Representation.Subgroup.characterRingInduction H χ =
        Representation.Subgroup.characterRingInduction (K.map H.subtype)
          (MonoidHom.toCharacterRing (Subgroup.mappedLinearCharacter H K α)) := by
    calc
      Representation.Subgroup.characterRingInduction H χ =
          Representation.Subgroup.characterRingInduction H
            (Representation.Subgroup.characterRingInduction K (MonoidHom.toCharacterRing α)) := by
        rw [hχeq]
      _ = Representation.Subgroup.characterRingInduction (K.map H.subtype)
            (MonoidHom.toCharacterRing (Subgroup.mappedLinearCharacter H K α)) :=
        Subgroup.characterRingInduction_induced_linearCharacter_subgroup_chain H K α
  rw [hrewrite]
  exact hmon

/-- Helper for Theorem 10-10.5-2: the honest finite-dimensional characters span Serre's integral
character ring `R(G)`. -/
theorem rep_character_span_eq_top :
    Submodule.span ℤ {χ : R(G) | ∃ V : FDRep ℂ G, fdRepCharacterRing V = χ} = ⊤ := by
  let S : Set (R(G)) := {χ : R(G) | ∃ V : FDRep ℂ G, fdRepCharacterRing V = χ}
  have hmul_span :
      ∀ {χ ψ : R(G)},
        χ ∈ Submodule.span ℤ S →
        ψ ∈ Submodule.span ℤ S →
        χ * ψ ∈ Submodule.span ℤ S := by
    intro χ ψ hχ hψ
    have hχ_mul : ∀ ψ : R(G), ψ ∈ Submodule.span ℤ S → χ * ψ ∈ Submodule.span ℤ S := by
      induction hχ using Submodule.span_induction with
      | mem η hη =>
          rcases hη with ⟨V, rfl⟩
          intro ψ hψ
          induction hψ using Submodule.span_induction with
          | mem ξ hξ =>
              rcases hξ with ⟨W, rfl⟩
              refine Submodule.subset_span ?_
              refine ⟨CategoryTheory.MonoidalCategoryStruct.tensorObj V W, ?_⟩
              exact fdRepCharacterRing_tensor_eq_mul V W
          | zero =>
              rw [mul_zero]
              exact Submodule.zero_mem (Submodule.span ℤ S)
          | add ξ ζ _ _ hξ hζ =>
              simpa [mul_add] using
                Submodule.add_mem (Submodule.span ℤ S) hξ hζ
          | smul n ξ _ hξ =>
              simpa [zsmul_eq_mul, mul_assoc, mul_left_comm, mul_comm] using
                Submodule.smul_mem (Submodule.span ℤ S) n hξ
      | zero =>
          intro ψ hψ
          rw [zero_mul]
          exact Submodule.zero_mem (Submodule.span ℤ S)
      | add χ₁ χ₂ _ _ hχ₁ hχ₂ =>
          intro ψ hψ
          simpa [add_mul] using
            Submodule.add_mem (Submodule.span ℤ S) (hχ₁ ψ hψ) (hχ₂ ψ hψ)
      | smul n χ' _ hχ' =>
          intro ψ hψ
          simpa [zsmul_eq_mul, mul_left_comm, mul_assoc] using
            Submodule.smul_mem (Submodule.span ℤ S) n (hχ' ψ hψ)
    exact hχ_mul ψ hψ
  -- The representation ring is generated by irreducible characters, and honest characters are
  -- stable under the ring operations via the trivial representation and tensor products.
  refine top_unique ?_
  intro χ _
  have hspan_of_mem :
      ∀ (f : G → ℂ) (hf : f ∈ R(G)),
        (⟨f, hf⟩ : R(G)) ∈ Submodule.span ℤ S := by
    intro f hf
    refine
      Algebra.adjoin_induction
        (p := fun f hf ↦ (⟨f, hf⟩ : R(G)) ∈ Submodule.span ℤ S)
        ?_ ?_ ?_ ?_ hf
    · intro ψ hψ
      rcases hψ with ⟨ρ, hρfd, _hρirr, rfl⟩
      letI : FiniteDimensional ℂ ρ := hρfd
      change fdRepCharacterRing (FDRep.of ρ.ρ) ∈ Submodule.span ℤ S
      exact Submodule.subset_span ⟨FDRep.of ρ.ρ, rfl⟩
    · intro n
      change (algebraMap ℤ (R(G)) n) ∈ Submodule.span ℤ S
      rw [show algebraMap ℤ (R(G)) n =
          n • fdRepCharacterRing (FDRep.of (Representation.trivial ℂ G ℂ)) by
        rw [fdRepCharacterRing_trivial_eq_one]
        simp]
      exact Submodule.smul_mem (Submodule.span ℤ S) n <|
        Submodule.subset_span ⟨FDRep.of (Representation.trivial ℂ G ℂ), rfl⟩
    · intro f g hf hg hfspan hgspan
      change (⟨f, hf⟩ : R(G)) + ⟨g, hg⟩ ∈ Submodule.span ℤ S
      exact Submodule.add_mem (Submodule.span ℤ S) hfspan hgspan
    · intro f g hf hg hfspan hgspan
      change (⟨f, hf⟩ : R(G)) * ⟨g, hg⟩ ∈ Submodule.span ℤ S
      exact hmul_span hfspan hgspan
  exact hspan_of_mem (χ : G → ℂ) χ.2

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: the cyclicity of a quotient `A / B` pulls back along a
surjective homomorphism to the corresponding quotient of inverse-image subgroups. -/
theorem isCyclic_comap_quotient_of_surjective
    {Q : Type} [Group Q] (q : G →* Q) (hq : Function.Surjective q)
    {A B : Subgroup Q} [B.Normal]
    [IsCyclic (A ⧸ B.subgroupOf A)] :
    IsCyclic ((Subgroup.comap q A) ⧸ (Subgroup.comap q B).subgroupOf (Subgroup.comap q A)) := by
  -- Realize the pulled-back quotient as the quotient by the kernel of the restricted map to `A`.
  let qA : Subgroup.comap q A →* A :=
    { toFun := fun x ↦ ⟨q x, x.property⟩
      map_one' := by
        ext
        simp
      map_mul' := by
        intro x y
        ext
        simp }
  let φ : Subgroup.comap q A →* A ⧸ B.subgroupOf A :=
    (QuotientGroup.mk' (B.subgroupOf A)).comp qA
  have hφ_surj : Function.Surjective φ := by
    -- Surjectivity comes from surjectivity of `q` and of the quotient map `A → A / B`.
    intro x
    rcases QuotientGroup.mk'_surjective (B.subgroupOf A) x with ⟨a, rfl⟩
    rcases hq a with ⟨y, hy⟩
    refine ⟨⟨y, by simp [hy, a.property]⟩, ?_⟩
    simp [φ, qA, hy]
  have hker : (Subgroup.comap q B).subgroupOf (Subgroup.comap q A) = φ.ker := by
    -- The kernel consists exactly of those elements whose `q`-image lands in `B`.
    ext x
    simp [φ, qA]
    rfl
  let e :
      ((Subgroup.comap q A) ⧸ (Subgroup.comap q B).subgroupOf (Subgroup.comap q A)) ≃*
        (A ⧸ B.subgroupOf A) :=
    QuotientGroup.liftEquiv
      ((Subgroup.comap q B).subgroupOf (Subgroup.comap q A)) hφ_surj hker
  exact (e.isCyclic).2 inferInstance

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: any subgroup contained in the center is normal. -/
theorem normal_of_le_center {H : Subgroup G}
    (hH : H ≤ Subgroup.center G) :
    H.Normal := by
  -- Conjugation fixes every central element, so it preserves every subgroup of the center.
  constructor
  intro x hx g
  have hxC : x ∈ Subgroup.center G := hH hx
  rw [Subgroup.mem_center_iff] at hxC
  simpa [hxC g, mul_assoc] using hx

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: the cyclic subgroup generated by a central element is again
central. -/
theorem zpowers_le_center_of_mem_center {z : G}
    (hz : z ∈ Subgroup.center G) :
    Subgroup.zpowers z ≤ Subgroup.center G := by
  -- Every power of a central element is central because commutation is stable under integer powers.
  intro x hx
  rcases Subgroup.mem_zpowers_iff.mp hx with ⟨n, rfl⟩
  rw [Subgroup.mem_center_iff]
  intro g
  have hcomm : Commute g z := (commute_iff_eq _ _).2 (Subgroup.mem_center_iff.mp hz g)
  exact (hcomm.zpow_right n).eq

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: in a `p`-elementary decomposition, the cyclic factor is a
normal subgroup of the ambient group. -/
theorem IsPElementaryDecomposition.cyclic_factor_normal
    {p : ℕ} {C P : Subgroup G} (hCP : IsPElementaryDecomposition p C P) :
    C.Normal := by
  -- Show that both complementary factors lie in the normalizer of `C`; their supremum is all of
  -- `G`, so the normalizer is the whole group.
  rw [← Subgroup.normalizer_eq_top_iff, eq_top_iff]
  have hPnorm : P ≤ Subgroup.normalizer (C : Set G) := by
    intro p hp
    rw [Subgroup.mem_normalizer_iff_conj_image_eq]
    ext x
    constructor
    · rintro ⟨c, hc, rfl⟩
      have hcomm : Commute (c : G) p := hCP.commute ⟨c, hc⟩ ⟨p, hp⟩
      have hconj : p * c * p⁻¹ = c := by
        calc
          p * c * p⁻¹ = c * p * p⁻¹ := by rw [hcomm.eq, mul_assoc]
          _ = c := by simp
      simpa [MulAut.conj_apply, hconj] using hc
    · intro hx
      refine ⟨x, hx, ?_⟩
      have hcomm : Commute x p := hCP.commute ⟨x, hx⟩ ⟨p, hp⟩
      have hconj : p * x * p⁻¹ = x := by
        calc
          p * x * p⁻¹ = x * p * p⁻¹ := by rw [hcomm.eq, mul_assoc]
          _ = x := by simp
      simp [MulAut.conj_apply, hconj]
  have hsup :
      C ⊔ P ≤ Subgroup.normalizer (C : Set G) :=
    sup_le Subgroup.le_normalizer hPnorm
  simpa [hCP.isComplement.sup_eq_top] using hsup

omit [Finite G] in
/-- Helper for Theorem 10-10.5-2: supersolvability lifts across a normal cyclic kernel. -/
theorem isSupersolvable_of_normal_cyclic_subgroup_quotient
    (N : Subgroup G) [N.Normal] (hN : IsCyclic N)
    [IsSupersolvable (G ⧸ N)] :
    IsSupersolvable G := by
  let hsup : IsSupersolvable (G ⧸ N) := inferInstance
  letI : IsCyclic N := hN
  rcases hsup.supersolvable with ⟨n, f, hmono, hnormal, hcyclic, h0, hn⟩
  let q : G →* G ⧸ N := QuotientGroup.mk' N
  let g : ℕ → Subgroup G := fun i ↦
    match i with
    | 0 => ⊥
    | j + 1 => Subgroup.comap q (f j)
  -- Insert the cyclic kernel as the first nontrivial term, then pull back the supersolvable
  -- series from the quotient.
  refine ⟨?_⟩
  refine ⟨n + 1, g, ?_⟩
  refine ⟨?_, ⟨?_, ⟨?_, ?_, ?_⟩⟩⟩
  · refine monotone_nat_of_le_succ ?_
    intro i
    cases i with
    | zero =>
        simp [g, q, h0]
    | succ i =>
        exact Subgroup.comap_mono (hmono (Nat.le_succ i))
  · intro i hi
    cases i with
    | zero =>
        change (⊥ : Subgroup G).Normal
        infer_instance
    | succ i =>
        simpa [g] using (hnormal i (Nat.succ_lt_succ_iff.mp hi)).comap q
  · intro i hi
    cases i with
    | zero =>
        -- The first quotient is just the kernel `N` itself.
        change IsCyclic
          ((Subgroup.comap q (f 0)) ⧸
            ((⊥ : Subgroup G).subgroupOf (Subgroup.comap q (f 0))))
        let e0 : Subgroup.comap q (f 0) ≃* N :=
          { toFun := fun x ↦
              ⟨x, by
                simpa [q, h0, QuotientGroup.ker_mk' N] using x.property⟩
            invFun := fun x ↦
              ⟨x, by
                have hx : q x = 1 := by
                  exact (QuotientGroup.eq_one_iff _).2 x.property
                show q x ∈ f 0
                rw [h0, hx]
                simp⟩
            left_inv := by
              intro x
              ext
              rfl
            right_inv := by
              intro x
              ext
              rfl
            map_mul' := by
              intro x y
              rfl }
        have hker_cyclic : IsCyclic (Subgroup.comap q (f 0)) := by
          exact (e0.isCyclic).2 inferInstance
        letI : IsCyclic (Subgroup.comap q (f 0)) := hker_cyclic
        simpa using
          (isCyclic_of_surjective
            (QuotientGroup.mk' ((⊥ : Subgroup G).subgroupOf (Subgroup.comap q (f 0))))
            (QuotientGroup.mk'_surjective
              ((⊥ : Subgroup G).subgroupOf (Subgroup.comap q (f 0)))))
    | succ i =>
        -- Later quotients are the pullbacks of the cyclic quotients in the quotient series.
        have hi' : i < n := Nat.succ_lt_succ_iff.mp hi
        letI : (f i).Normal := hnormal i hi'
        letI : IsCyclic (f (i + 1) ⧸ (f i).subgroupOf (f (i + 1))) := hcyclic i hi'
        simpa [g, q] using
          (isCyclic_comap_quotient_of_surjective q (QuotientGroup.mk'_surjective N)
            (A := f (i + 1)) (B := f i) :
            IsCyclic
              ((Subgroup.comap q (f (i + 1))) ⧸
                (Subgroup.comap q (f i)).subgroupOf (Subgroup.comap q (f (i + 1)))))
  · simp [g]
  · simp [g, q, hn]

/-- Helper for Theorem 10-10.5-2: every finite `p`-group is supersolvable. -/
theorem isSupersolvable_of_isPGroup
    {p : ℕ} [Fact p.Prime] (hG : IsPGroup p G) :
    IsSupersolvable G := by
  cases nonempty_fintype G
  classical
  revert ‹Group G›
  apply @Fintype.induction_subsingleton_or_nontrivial _ G _
  · intro G _ _ _ _
    -- A subsingleton group is cyclic, hence supersolvable.
    letI : Subsingleton G := inferInstance
    letI : IsCyclic G := isCyclic_of_subsingleton
    infer_instance
  · intro G _ _ ih _ hG
    -- Choose a nontrivial central element and quotient by its cyclic subgroup.
    have hcenter_nontrivial : Nontrivial (Subgroup.center G) := IsPGroup.center_nontrivial hG
    letI : Nontrivial (Subgroup.center G) := hcenter_nontrivial
    obtain ⟨z, hz_ne⟩ := exists_ne (1 : Subgroup.center G)
    let Z : Subgroup G := Subgroup.zpowers (z : G)
    have hz_center : (z : G) ∈ Subgroup.center G := z.property
    have hZ_le_center : Z ≤ Subgroup.center G := zpowers_le_center_of_mem_center hz_center
    letI : Z.Normal := normal_of_le_center hZ_le_center
    have hZ_ne_bot : Z ≠ ⊥ := by
      intro hZ
      apply hz_ne
      apply Subtype.ext
      have hz_mem : (z : G) ∈ Z := Subgroup.mem_zpowers (z : G)
      have hz_one : (z : G) = 1 := by
        simpa [Z, hZ] using hz_mem
      exact hz_one
    have hq_card : Fintype.card (G ⧸ Z) < Fintype.card G := by
      -- The quotient is strictly smaller because the cyclic kernel is nontrivial.
      simp only [← Nat.card_eq_fintype_card]
      rw [Subgroup.card_eq_card_quotient_mul_card_subgroup Z]
      apply lt_mul_of_one_lt_right
      · exact Nat.card_pos
      · exact (Subgroup.one_lt_card_iff_ne_bot Z).mpr hZ_ne_bot
    letI : IsSupersolvable (G ⧸ Z) := ih (G ⧸ Z) hq_card (hG.to_quotient Z)
    have hZ_cyclic : IsCyclic Z := inferInstance
    exact isSupersolvable_of_normal_cyclic_subgroup_quotient Z hZ_cyclic

/-- Helper for Theorem 10-10.5-2: a `p`-elementary finite group is supersolvable. -/
theorem isSupersolvable_of_isPElementary
    {p : ℕ} (hG : IsPElementary p G) :
    IsSupersolvable G := by
  rcases hG with ⟨C, P, hCP⟩
  letI : Fact p.Prime := ⟨hCP.prime⟩
  letI : C.Normal := IsPElementaryDecomposition.cyclic_factor_normal hCP
  have hquot_p : IsPGroup p (G ⧸ C) := by
    let e : G ⧸ C ≃* P := hCP.isComplement.symm.QuotientMulEquiv
    exact hCP.isPGroup.of_surjective e.symm.toMonoidHom e.symm.surjective
  letI : IsSupersolvable (G ⧸ C) := isSupersolvable_of_isPGroup hquot_p
  -- The quotient by the cyclic factor is the `p`-group factor, so the cyclic-kernel lifting
  -- lemma closes the ambient group.
  exact isSupersolvable_of_normal_cyclic_subgroup_quotient C hCP.cyclic

/-- Helper for Theorem 10-10.5-2: an elementary finite group is supersolvable. -/
theorem isSupersolvable_of_isElementary (hG : IsElementary G) : IsSupersolvable G := by
  -- Route correction: instead of forcing a nilpotent-to-supersolvable theorem from elsewhere,
  -- we prove the exact source bridge here by handling finite `p`-groups and then the
  -- `p`-elementary decomposition.
  rcases hG with ⟨p, hp⟩
  exact isSupersolvable_of_isPElementary hp

end

end Representation
