import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Definition_10_21 (from Chap10) -/
noncomputable section

/- Definition 10.21 is `source-facing`: the primitive data are the smoothness constant `L_f` and
the positive strong-convexity modulus `σ`. The chapter owner for their ratio is the condition
number itself; notation and elementary positivity facts are derived API. When `L_f` is itself
positive, Chapter 6 already provides the canonical bridge `Lf.toNNReal : NNReal`, so downstream
files should reuse `κ(Lf.toNNReal, σ)` rather than rebuilding that bridge through
`Real.toNNReal (Lf : ℝ)`. -/

/-- Definition 10.21: the condition number attached to the smoothness constant `L_f` and the
positive strong-convexity modulus `σ` is the ratio `L_f / σ`. -/
def condition_number (Lf : NNReal) (σ : PosReal) : ℝ :=
  (Lf : ℝ) / (σ : ℝ)

notation "κ(" Lf ", " σ ")" => condition_number Lf σ

-- Proof sketch: this is just the defining formula of `condition_number`.
/-- Expanding `condition_number` yields the ratio `L_f / σ`. -/
@[simp] theorem condition_number_eq (Lf : NNReal) (σ : PosReal) :
    κ(Lf, σ) = (Lf : ℝ) / (σ : ℝ) :=
  rfl

-- Proof sketch: unfold `condition_number`; the numerator `(Lf : ℝ)` is nonnegative because
-- `Lf : NNReal`, and division by the positive modulus `σ` preserves nonnegativity.
/-- The condition number is nonnegative. -/
theorem condition_number_nonneg (Lf : NNReal) (σ : PosReal) :
    0 ≤ κ(Lf, σ) := by
  exact div_nonneg Lf.2 (le_of_lt σ.2)

end

/-! ### Theorem_10_21 (from Chap10) -/
noncomputable section

universe u

section

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [ProperSpace E]
variable {f g : E → EReal} {XStar : Set E} {FOpt : ℝ} {Lf : NNReal}
variable [hproblem : IsConvexCompositeSmoothMinimizationProblem f g XStar FOpt Lf]
variable {α : ℝ} {x : ℕ → E} {L : ℕ → PosReal} {xStar : E}

local notation "F" => composite_model_objective f g

/- Theorem 10.21 is `source-facing` in the convex proximal-gradient API.

Domain sampling in the existing chapter identifies:
- `IsConvexCompositeSmoothMinimizationProblem` as the owner of Assumption 10.1 plus convexity of
  `f`;
- `is_proximal_gradient_trajectory` as the owner of the iterate sequence `x^k`;
- `proximal_gradient_sublinear_rate_stepsize_rule` from Remark 10.19 as the source-facing owner
  of the admissible constant/B2 stepsize regimes together with the auxiliary constant `α`;
- `hproblem.SublinearRateStepsizeRule` as the canonical owner-level bridge/view surface that
  imports those regularity hypotheses from Assumption 10.77.

The admissible stepsize regime used here is therefore the single shared source-facing owner from
Remark 10.19 rather than a repeated local disjunction. The objective-gap estimate is derived API
over that owner stack and should not introduce a second wrapper carrying unrelated optimizer
data. -/

-- Proof sketch: apply the fundamental prox-gradient inequality from Theorem 10.16 with
-- `x = xStar`, `y = x^n`, and `L = L_n`, then use the convexity of `f` to make the
-- linearization error nonnegative. Sum the resulting inequalities from `n = 0` to `k - 1`,
-- use Remark 10.19 to bound every `L_n` by `α L_f`, and finally use the monotonicity from
-- Remark 10.20 to pass from the averaged bound to the pointwise estimate at the positive index
-- `k`.
/-- Theorem 10.21: under Assumption 10.1, if `f` is convex and `x^k` is generated by the
proximal gradient method with either the constant stepsize rule `L_k = L_f` or backtracking
procedure B2, then every positive
iterate satisfies the sublinear objective-gap estimate
`F(x^k) - F_opt ≤ α L_f ‖x^0 - x*‖² / (2 k)`. -/
theorem proximal_gradient_convex_objective_gap_le
    (htraj : is_proximal_gradient_trajectory f g x L)
    (hrule : hproblem.SublinearRateStepsizeRule x L htraj α)
    (hxStar : xStar ∈ XStar)
    (k : ℕ) (hk : 1 ≤ k) :
    F (x k) - (FOpt : EReal) ≤
      (((α * (Lf : ℝ) * ‖x 0 - xStar‖ ^ (2 : ℕ) / (2 * (k : ℝ)) : ℝ) : EReal)) := sorry

end

end
