import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.SourcePrecomposition
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.StrictProjection
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.IsoCommaModel
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.FractionSourceCharts
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.FixedFractionCandidate
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.SectionCompositeLifts
import stacks_proof.stacks_project.Chap08.Lemma_8_12_6.SourceReplacementFrontier
