import Integer.Chapters.Chap04.section_4_1.ch4_sec4_1_theorem_4_1

open scoped BigOperators Matrix Pointwise

-- Semantic recall note: the statement policy requested `lean_leansearch`, but no deferred Lean
-- search tool was available in this environment. The declarations below therefore use only
-- self-contained Mathlib surfaces for convex hulls, generated cones, and the canonical
-- matrix-inequality owner `polyhedron_le_set`.

section Theorem439

/-- The union of the listed finite families over those indices for which the input polyhedron is
nonempty. -/
def balas_nonempty_family
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (F : Fin k → Finset (Fin n → ℝ)) : Set (Fin n → ℝ) :=
  {x : Fin n → ℝ | ∃ i : Fin k, polyhedron_le_set (A i) (b i) ≠ ∅ ∧ x ∈ (F i : Set (Fin n → ℝ))}

/-- Membership in `balas_nonempty_family m A b F` means belonging to one listed family `F i`
whose polyhedron `Pᵢ` is nonempty. -/
theorem mem_balas_nonempty_family_iff
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (F : Fin k → Finset (Fin n → ℝ))
    (x : Fin n → ℝ) :
    x ∈ balas_nonempty_family m A b F ↔
      ∃ i : Fin k, polyhedron_le_set (A i) (b i) ≠ ∅ ∧ x ∈ (F i : Set (Fin n → ℝ)) := by
  rfl

/-- The union of all listed Balas rays. -/
def balas_ray_family
    {n k : ℕ}
    (R : Fin k → Finset (Fin n → ℝ)) : Set (Fin n → ℝ) :=
  {x : Fin n → ℝ | ∃ i : Fin k, x ∈ (R i : Set (Fin n → ℝ))}

/-- The Balas polyhedron built from the vertex families attached to the nonempty input polyhedra
and the ray families attached to their recession cones. -/
def balas_union_polyhedron
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V R : Fin k → Finset (Fin n → ℝ)) : Set (Fin n → ℝ) :=
  convexHull ℝ (balas_nonempty_family m A b V) +
    (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ))

/-- Membership in the Balas union polyhedron is membership in the convex hull of the vertices
coming from the nonempty input polyhedra, plus the cone generated by all rays. -/
theorem mem_balas_union_polyhedron_iff
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V R : Fin k → Finset (Fin n → ℝ))
    (x : Fin n → ℝ) :
    x ∈ balas_union_polyhedron m A b V R ↔
      x ∈ convexHull ℝ (balas_nonempty_family m A b V) +
        (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
  -- This theorem only unfolds the definition of the Balas union polyhedron.
  rfl

/-- The lifted polyhedron in Balas' formulation, with variables `(x, xParts, δ)`. -/
def balas_lifted_polyhedron
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ) :
    Set ((Fin n → ℝ) × (Fin k → Fin n → ℝ) × (Fin k → ℝ)) :=
  {y |
    (∀ i : Fin k, A i *ᵥ y.2.1 i ≤ y.2.2 i • b i) ∧
      (∑ i : Fin k, y.2.1 i = y.1) ∧
      (∑ i : Fin k, y.2.2 i = 1) ∧
      (∀ i : Fin k, 0 ≤ y.2.2 i)}

/-- Membership in the Balas lifted polyhedron is exactly the system
`Aᵢ xⁱ ≤ δᵢ bⁱ`, `∑ xⁱ = x`, `∑ δᵢ = 1`, and `δᵢ ≥ 0`. -/
theorem mem_balas_lifted_polyhedron_iff
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (x : Fin n → ℝ)
    (xParts : Fin k → Fin n → ℝ)
    (δ : Fin k → ℝ) :
    (x, xParts, δ) ∈ balas_lifted_polyhedron m A b ↔
      (∀ i : Fin k, A i *ᵥ xParts i ≤ δ i • b i) ∧
        (∑ i : Fin k, xParts i = x) ∧
        (∑ i : Fin k, δ i = 1) ∧
        (∀ i : Fin k, 0 ≤ δ i) := by
  -- This is exactly the defining conjunction for the lifted system.
  rfl

/-- The projection of the Balas lifted polyhedron onto the `x`-coordinates. -/
def balas_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ) : Set (Fin n → ℝ) :=
  Prod.fst '' balas_lifted_polyhedron m A b

/-- Membership in the `x`-projection of the Balas lifted polyhedron is existence of compatible
auxiliary variables `(xParts, δ)`. -/
theorem mem_balas_x_projection_iff
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (x : Fin n → ℝ) :
    x ∈ balas_x_projection m A b ↔
      ∃ xParts : Fin k → Fin n → ℝ, ∃ δ : Fin k → ℝ,
        (x, xParts, δ) ∈ balas_lifted_polyhedron m A b := by
  constructor
  · rintro ⟨y, hy, rfl⟩
    -- Unpack the image witness into the auxiliary Balas variables.
    exact ⟨y.2.1, y.2.2, hy⟩
  · rintro ⟨xParts, δ, hLifted⟩
    -- Repackage the auxiliary variables as a witness for the image under `Prod.fst`.
    exact ⟨(x, xParts, δ), hLifted, rfl⟩

/-- Helper for Theorem 4.39: scaling a positive Balas block by `δᵢ⁻¹` recovers a point of the
original polyhedron `Aᵢ x ≤ bⁱ`. -/
lemma scaled_part_mem_input_polyhedron_of_positive_delta
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    {x : Fin n → ℝ}
    {xParts : Fin k → Fin n → ℝ}
    {δ : Fin k → ℝ}
    {i : Fin k}
    (hLifted : (x, xParts, δ) ∈ balas_lifted_polyhedron m A b)
    (hδ : 0 < δ i) :
    (δ i)⁻¹ • xParts i ∈ polyhedron_le_set (A i) (b i) := by
  rcases (mem_balas_lifted_polyhedron_iff m A b x xParts δ).1 hLifted with
    ⟨hineq, -, -, -⟩
  -- Scale the `i`-th inequality by dividing through by the positive scalar `δᵢ`.
  change A i *ᵥ ((δ i)⁻¹ • xParts i) ≤ b i
  intro j
  have hij : (A i *ᵥ xParts i) j ≤ δ i * b i j := by
    simpa [Pi.smul_apply, smul_eq_mul] using hineq i j
  have hdiv : (A i *ᵥ xParts i) j / δ i ≤ b i j := by
    refine (div_le_iff₀ hδ).2 ?_
    simpa [mul_comm, mul_left_comm, mul_assoc] using hij
  simpa [Matrix.mulVec_smul, Pi.smul_apply, smul_eq_mul, div_eq_mul_inv,
    mul_comm, mul_left_comm, mul_assoc] using hdiv

/-- Helper for Theorem 4.39: every listed vertex of a nonempty input polyhedron already belongs to
the Balas `x`-projection by activating only its own block. -/
lemma balas_vertex_mem_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V R : Fin k → Finset (Fin n → ℝ))
    (hV :
      ∀ i : Fin k,
        polyhedron_le_set (A i) (b i) ≠ ∅ →
          polyhedron_le_set (A i) (b i) =
            convexHull ℝ (V i : Set (Fin n → ℝ)) +
              (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)))
    {i : Fin k}
    {v : Fin n → ℝ}
    (hPi : polyhedron_le_set (A i) (b i) ≠ ∅)
    (hv : v ∈ (V i : Set (Fin n → ℝ))) :
    v ∈ balas_x_projection m A b := by
  have hv_mem_input : v ∈ polyhedron_le_set (A i) (b i) := by
    rw [hV i hPi]
    -- The chosen vertex is in the convex hull, and the cone contributes the zero ray.
    refine ⟨v, (subset_convexHull ℝ (V i : Set (Fin n → ℝ))) hv, 0, ?_, by simp⟩
    show (0 : Fin n → ℝ) ∈ (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ))
    exact Submodule.zero_mem _
  rw [mem_balas_x_projection_iff]
  let xParts : Fin k → Fin n → ℝ := fun j ↦ if j = i then v else 0
  let δ : Fin k → ℝ := fun j ↦ if j = i then 1 else 0
  refine ⟨xParts, δ, ?_⟩
  rw [mem_balas_lifted_polyhedron_iff m A b v xParts δ]
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro j
    by_cases hji : j = i
    · subst hji
      simpa [xParts, δ] using hv_mem_input
    · simp [xParts, δ, hji]
  · -- Only the active block contributes to the sum of the partial vectors.
    ext t
    rw [Fintype.sum_eq_single i]
    · simp [xParts]
    · intro j hji
      simp [xParts, hji]
  · -- Only the active block contributes to the sum of the Balas multipliers.
    rw [Fintype.sum_eq_single i]
    · simp [δ]
    · intro j hji
      simp [δ, hji]
  · intro j
    by_cases hji : j = i
    · simp [δ, hji]
    · simp [δ, hji]

/-- Helper for Theorem 4.39: the convex hull of one admissible vertex family sits inside the global
Balas vertex hull whenever that input polyhedron is nonempty. -/
lemma convexHull_subset_balas_vertex_hull
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V : Fin k → Finset (Fin n → ℝ))
    {i : Fin k}
    (hPi : polyhedron_le_set (A i) (b i) ≠ ∅) :
    convexHull ℝ (V i : Set (Fin n → ℝ)) ⊆
      convexHull ℝ (balas_nonempty_family m A b V) := by
  -- Embed the `i`-th vertex family into the global admissible-vertex family.
  -- Then close the inclusion under convex hull.
  refine convexHull_min ?_ (convex_convexHull ℝ _)
  intro x hx
  exact (subset_convexHull ℝ (balas_nonempty_family m A b V)) ⟨i, hPi, hx⟩

/-- Helper for Theorem 4.39: the cone generated by the `i`-th local ray family is contained in
the cone generated by the global Balas ray family. -/
lemma local_ray_hull_subset_global_ray_hull
    {n k : ℕ}
    (R : Fin k → Finset (Fin n → ℝ))
    (i : Fin k) :
    (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)) ⊆
      (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
  -- Embed each local generator `r ∈ R i` into the global Balas ray family before taking the hull.
  exact
    (Submodule.span_mono <| by
      intro x hx
      exact ⟨i, hx⟩ :
      PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) ≤
        PointedCone.hull ℝ (balas_ray_family R))

/-- Helper for Theorem 4.39: the Balas `x`-projection is convex because convex combinations of
lifted witnesses remain lifted witnesses. -/
lemma convex_balas_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ) :
    Convex ℝ (balas_x_projection m A b) := by
  intro x hx y hy a c ha hc hac
  rw [mem_balas_x_projection_iff] at hx hy ⊢
  rcases hx with ⟨xParts, δ, hLiftedX⟩
  rcases hy with ⟨yParts, ε, hLiftedY⟩
  rcases (mem_balas_lifted_polyhedron_iff m A b x xParts δ).1 hLiftedX with
    ⟨hineqX, hsumX, hsumδ, hδnonneg⟩
  rcases (mem_balas_lifted_polyhedron_iff m A b y yParts ε).1 hLiftedY with
    ⟨hineqY, hsumY, hsumε, hεnonneg⟩
  let zParts : Fin k → Fin n → ℝ := fun i ↦ a • xParts i + c • yParts i
  let ζ : Fin k → ℝ := fun i ↦ a * δ i + c * ε i
  refine ⟨zParts, ζ, ?_⟩
  rw [mem_balas_lifted_polyhedron_iff m A b (a • x + c • y) zParts ζ]
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro i j
    -- Each row inequality is preserved by taking the same convex combination of the two witnesses.
    have hxij : (A i *ᵥ xParts i) j ≤ δ i * b i j := by
      simpa [Pi.smul_apply, smul_eq_mul] using hineqX i j
    have hyij : (A i *ᵥ yParts i) j ≤ ε i * b i j := by
      simpa [Pi.smul_apply, smul_eq_mul] using hineqY i j
    have hax : a * (A i *ᵥ xParts i) j ≤ a * (δ i * b i j) := by
      exact mul_le_mul_of_nonneg_left hxij ha
    have hcy : c * (A i *ᵥ yParts i) j ≤ c * (ε i * b i j) := by
      exact mul_le_mul_of_nonneg_left hyij hc
    have hsum := add_le_add hax hcy
    simpa [zParts, ζ, Matrix.mulVec_add, Matrix.mulVec_smul, Pi.smul_apply, smul_eq_mul,
      left_distrib, right_distrib, mul_add, add_mul, mul_assoc] using hsum
  · -- The convexly combined block vectors still sum to the projected point.
    calc
      ∑ i : Fin k, zParts i = ∑ i : Fin k, (a • xParts i + c • yParts i) := by
        rfl
      _ = a • ∑ i : Fin k, xParts i + c • ∑ i : Fin k, yParts i := by
        rw [Finset.sum_add_distrib, Finset.smul_sum, Finset.smul_sum]
      _ = a • x + c • y := by
        rw [hsumX, hsumY]
  · -- The combined multipliers still form a convex combination.
    calc
      ∑ i : Fin k, ζ i = ∑ i : Fin k, (a * δ i + c * ε i) := by
        rfl
      _ = a * ∑ i : Fin k, δ i + c * ∑ i : Fin k, ε i := by
        rw [Finset.sum_add_distrib, Finset.mul_sum, Finset.mul_sum]
      _ = 1 := by
        simpa [hsumδ, hsumε] using hac
  · -- Nonnegativity is preserved coordinatewise.
    intro i
    exact add_nonneg (mul_nonneg ha (hδnonneg i)) (mul_nonneg hc (hεnonneg i))

/-- Helper for Theorem 4.39: adding a homogeneous feasible direction to one block witness keeps
the projected point feasible in the Balas system. -/
lemma add_homogeneous_block_mem_balas_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    {x r : Fin n → ℝ}
    {i : Fin k}
    (hx : x ∈ balas_x_projection m A b)
    (hr : r ∈ polyhedron_le_set (A i) 0) :
    x + r ∈ balas_x_projection m A b := by
  rw [mem_balas_x_projection_iff] at hx ⊢
  rcases hx with ⟨xParts, δ, hLifted⟩
  rcases (mem_balas_lifted_polyhedron_iff m A b x xParts δ).1 hLifted with
    ⟨hineq, hsumX, hsumδ, hδnonneg⟩
  let xParts' : Fin k → Fin n → ℝ := fun j ↦ if j = i then xParts i + r else xParts j
  refine ⟨xParts', δ, ?_⟩
  rw [mem_balas_lifted_polyhedron_iff m A b (x + r) xParts' δ]
  refine ⟨?_, ?_, hsumδ, hδnonneg⟩
  · intro j t
    by_cases hji : j = i
    · subst j
      -- Only the active block changes, and the homogeneous part contributes on the right by `0`.
      have hxjt : (A i *ᵥ xParts i) t ≤ δ i * b i t := by
        simpa [Pi.smul_apply, smul_eq_mul] using hineq i t
      have hrt : (A i *ᵥ r) t ≤ 0 := hr t
      have hsum : (A i *ᵥ xParts i) t + (A i *ᵥ r) t ≤ δ i * b i t + 0 := by
        exact add_le_add hxjt hrt
      simpa [xParts', Matrix.mulVec_add, Pi.smul_apply, smul_eq_mul] using hsum
    · simpa [xParts', hji] using hineq j t
  · -- Updating a single block adds exactly `r` to the projected sum.
    ext t
    -- The erased part of the sum is unchanged because only the `i`-th block was updated.
    have hsumParts' :
        (∑ j : Fin k, xParts' j) t =
          (xParts' i) t + Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts' j) t) := by
      simpa using
        (Finset.add_sum_erase (s := Finset.univ) (a := i)
          (f := fun j : Fin k ↦ xParts' j t) (by simp)).symm
    have hsumParts :
        (∑ j : Fin k, xParts j) t =
          xParts i t + Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts j) t) := by
      simpa using
        (Finset.add_sum_erase (s := Finset.univ) (a := i)
          (f := fun j : Fin k ↦ xParts j t) (by simp)).symm
    have hsumErase :
        Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts' j) t) =
          Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts j) t) := by
      refine Finset.sum_congr rfl ?_
      intro j hj
      have hji : j ≠ i := (Finset.mem_erase.1 hj).1
      simp [xParts', hji]
    calc
      (∑ j : Fin k, xParts' j) t
          = (xParts' i) t + Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts' j) t) := hsumParts'
      _ = (xParts i t + r t) + Finset.sum (Finset.univ.erase i) (fun j : Fin k ↦ (xParts j) t) := by
        rw [hsumErase]
        simp [xParts']
      _ = (∑ j : Fin k, xParts j) t + r t := by
        rw [hsumParts]
        abel
      _ = x t + r t := by
        simpa using congrArg (fun f : Fin n → ℝ ↦ f t) hsumX
      _ = (x + r) t := by
        simp

/-- Helper for Theorem 4.39: the Balas `x`-projection is stable under adding any vector from the
global cone generated by the listed ray families. -/
lemma add_global_ray_hull_mem_balas_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (R : Fin k → Finset (Fin n → ℝ))
    (hR :
      ∀ i : Fin k,
        polyhedron_le_set (A i) 0 =
          (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)))
    {x r : Fin n → ℝ}
    (hx : x ∈ balas_x_projection m A b)
    (hr : r ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ))) :
    x + r ∈ balas_x_projection m A b := by
  rw [SetLike.mem_coe, PointedCone.mem_hull_set] at hr
  rcases hr with ⟨c, hc_support, hc_nonneg, rfl⟩
  classical
  -- Iterate the one-block homogeneous move over the finite conic combination of global rays.
  have hsum :
      x + Finset.sum c.support (fun y ↦ c y • y) ∈ balas_x_projection m A b := by
    have haux :
        ∀ s : Finset (Fin n → ℝ), s ⊆ c.support →
          x + Finset.sum s (fun y ↦ c y • y) ∈ balas_x_projection m A b := by
      intro s
      refine Finset.induction_on s ?_ ?_
      · intro hs_subset
        simpa using hx
      · intro y s hy_notin hs hs_subset
        have hy_support : y ∈ c.support := hs_subset (by simp)
        have hs_subset' : s ⊆ c.support := by
          intro z hz
          exact hs_subset (by simp [hz, hy_notin])
        rcases hc_support hy_support with ⟨i, hyR⟩
        have hyLocal : y ∈ (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)) := by
          exact PointedCone.subset_hull hyR
        have hyScaled :
            c y • y ∈ (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)) := by
          simpa using
            (Submodule.smul_mem (PointedCone.hull ℝ (R i : Set (Fin n → ℝ))) ⟨c y, hc_nonneg y⟩
              hyLocal)
        have hyPoly : c y • y ∈ polyhedron_le_set (A i) 0 := by
          rw [hR i]
          exact hyScaled
        have hsProj : x + Finset.sum s (fun z ↦ c z • z) ∈ balas_x_projection m A b := hs hs_subset'
        have hstep :=
          add_homogeneous_block_mem_balas_x_projection m A b hsProj hyPoly
        simpa [Finset.sum_insert, hy_notin, add_assoc, add_left_comm, add_comm] using hstep
    exact haux c.support (by intro z hz; exact hz)
  simpa [Finsupp.sum] using hsum

/-- Helper for Theorem 4.39: a positive Balas multiplier allows one to decompose the
corresponding block into a scaled global vertex-hull point plus a global ray-hull point. -/
lemma positive_delta_block_decomposition
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V R : Fin k → Finset (Fin n → ℝ))
    (hV :
      ∀ i : Fin k,
        polyhedron_le_set (A i) (b i) ≠ ∅ →
          polyhedron_le_set (A i) (b i) =
            convexHull ℝ (V i : Set (Fin n → ℝ)) +
              (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)))
    {x : Fin n → ℝ}
    {xParts : Fin k → Fin n → ℝ}
    {δ : Fin k → ℝ}
    {i : Fin k}
    (hLifted : (x, xParts, δ) ∈ balas_lifted_polyhedron m A b)
    (hδ : 0 < δ i) :
    ∃ v r,
      v ∈ convexHull ℝ (balas_nonempty_family m A b V) ∧
      r ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) ∧
      xParts i = δ i • v + r := by
  have hz :
      (δ i)⁻¹ • xParts i ∈ polyhedron_le_set (A i) (b i) :=
    scaled_part_mem_input_polyhedron_of_positive_delta m A b hLifted hδ
  have hPi : polyhedron_le_set (A i) (b i) ≠ ∅ := by
    exact Set.nonempty_iff_ne_empty.1 ⟨(δ i)⁻¹ • xParts i, hz⟩
  rw [hV i hPi] at hz
  rcases hz with ⟨v, hv, r, hr, hzEq⟩
  have hvGlobal : v ∈ convexHull ℝ (balas_nonempty_family m A b V) := by
    exact convexHull_subset_balas_vertex_hull m A b V hPi hv
  have hrGlobal :
      r ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
    exact local_ray_hull_subset_global_ray_hull R i hr
  have hδnonneg : 0 ≤ δ i := le_of_lt hδ
  have hδrGlobal :
      δ i • r ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
    simpa using
      (Submodule.smul_mem (PointedCone.hull ℝ (balas_ray_family R)) ⟨δ i, hδnonneg⟩ hrGlobal)
  refine ⟨v, δ i • r, hvGlobal, hδrGlobal, ?_⟩
  -- Rescale the local decomposition of `xParts i / δ i` back to the original block.
  calc
    xParts i = δ i • ((δ i)⁻¹ • xParts i) := by
      symm
      simpa [smul_smul, hδ.ne', mul_inv_cancel₀, one_smul]
    _ = δ i • (v + r) := by
      rw [← hzEq]
    _ = δ i • v + δ i • r := by
      rw [smul_add]

/-- Helper for Theorem 4.39: a convex combination of global Balas vertex-hull points stays in the
global Balas vertex hull. -/
lemma weighted_sum_mem_balas_vertex_hull
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V : Fin k → Finset (Fin n → ℝ))
    (s : Finset (Fin k))
    (δ : Fin k → ℝ)
    (v : Fin k → Fin n → ℝ)
    (hδ_nonneg : ∀ i ∈ s, 0 ≤ δ i)
    (hδ_sum : Finset.sum s δ = 1)
    (hv : ∀ i ∈ s, v i ∈ convexHull ℝ (balas_nonempty_family m A b V)) :
    Finset.sum s (fun i ↦ δ i • v i) ∈ convexHull ℝ (balas_nonempty_family m A b V) := by
  -- This is the canonical convex-combination packaging step for the positive-δ blocks.
  exact (convex_convexHull ℝ (balas_nonempty_family m A b V)).sum_mem hδ_nonneg hδ_sum hv

/-- Theorem 4.39 (Balas [24,26]). Let `Pᵢ = {x | Aᵢ x ≤ bⁱ}` be `k` polyhedra, let
`Cᵢ = {x | Aᵢ x ≤ 0}`, assume each `Cᵢ` is the cone generated by the finite family `R i`, and
assume each nonempty `Pᵢ` admits the representation `conv(V i) + cone(R i)`. Then the Balas
polyhedron built from the union of the vertex families of the nonempty `Pᵢ` and the union of all
ray families is exactly the `x`-projection of the lifted polyhedron
`Aᵢ xⁱ ≤ δᵢ bⁱ`, `∑ xⁱ = x`, `∑ δᵢ = 1`, `δᵢ ≥ 0`. -/
theorem balas_union_polyhedron_eq_x_projection
    {n k : ℕ}
    (m : Fin k → ℕ)
    (A : ∀ i : Fin k, Matrix (Fin (m i)) (Fin n) ℝ)
    (b : ∀ i : Fin k, Fin (m i) → ℝ)
    (V R : Fin k → Finset (Fin n → ℝ))
    (hR :
      ∀ i : Fin k,
        polyhedron_le_set (A i) 0 =
          (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ)))
    (hV :
      ∀ i : Fin k,
        polyhedron_le_set (A i) (b i) ≠ ∅ →
          polyhedron_le_set (A i) (b i) =
            convexHull ℝ (V i : Set (Fin n → ℝ)) +
              (PointedCone.hull ℝ (R i : Set (Fin n → ℝ)) : Set (Fin n → ℝ))) :
    balas_union_polyhedron m A b V R = balas_x_projection m A b := by
  ext x
  constructor
  · intro hx
    rw [mem_balas_union_polyhedron_iff] at hx
    rcases hx with ⟨v, hv, r, hr, rfl⟩
    -- First place the global vertex part in the projection using convexity and the single-block lift.
    have hfamily :
        balas_nonempty_family m A b V ⊆ balas_x_projection m A b := by
      intro y hy
      rcases hy with ⟨i, hPi, hyV⟩
      exact balas_vertex_mem_x_projection m A b V R hV hPi hyV
    have hvertexHull :
        convexHull ℝ (balas_nonempty_family m A b V) ⊆ balas_x_projection m A b := by
      refine convexHull_min hfamily (convex_balas_x_projection m A b)
    have hvProj : v ∈ balas_x_projection m A b := hvertexHull hv
    -- Then add the global recession part by decomposing it into homogeneous block moves.
    exact add_global_ray_hull_mem_balas_x_projection m A b R hR hvProj hr
  · intro hx
    rw [mem_balas_x_projection_iff] at hx
    rw [mem_balas_union_polyhedron_iff]
    rcases hx with ⟨xParts, δ, hLifted⟩
    rcases (mem_balas_lifted_polyhedron_iff m A b x xParts δ).1 hLifted with
      ⟨hineq, hsumX, hsumδ, hδnonneg⟩
    classical
    let s : Finset (Fin k) := Finset.univ.filter fun i ↦ 0 < δ i
    let t : Finset (Fin k) := Finset.univ.filter fun i ↦ ¬ 0 < δ i
    -- Route correction: split the witness by the source-proof partition `δ i > 0` versus `δ i = 0`.
    have hzero_not_pos :
        Finset.sum t δ = 0 := by
      refine Finset.sum_eq_zero ?_
      intro i hi
      have hnotpos : ¬ 0 < δ i := by
        simpa [t] using (Finset.mem_filter.1 hi).2
      exact le_antisymm (le_of_not_gt hnotpos) (hδnonneg i)
    have hsδ : Finset.sum s δ = 1 := by
      have hpartition :
          Finset.sum s δ + Finset.sum t δ = ∑ i : Fin k, δ i := by
        simpa [s, t] using
          (Finset.sum_filter_add_sum_filter_not (s := Finset.univ)
            (p := fun i : Fin k ↦ 0 < δ i) δ)
      calc
        Finset.sum s δ = Finset.sum s δ + Finset.sum t δ := by
          rw [hzero_not_pos, add_zero]
        _ = ∑ i : Fin k, δ i := hpartition
        _ = 1 := hsumδ
    have hposBlock :
        ∀ i, i ∈ s →
          ∃ v r,
            v ∈ convexHull ℝ (balas_nonempty_family m A b V) ∧
            r ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) ∧
            xParts i = δ i • v + r := by
      intro i hi
      exact
        positive_delta_block_decomposition m A b V R hV hLifted
          ((Finset.mem_filter.1 hi).2)
    choose vPos rPos hvPos hrPos hxPos using hposBlock
    let vChoice : Fin k → Fin n → ℝ :=
      fun i ↦ if hi : i ∈ s then vPos i hi else 0
    let rChoice : Fin k → Fin n → ℝ :=
      fun i ↦ if hi : i ∈ s then rPos i hi else 0
    have hvChoice :
        ∀ i ∈ s, vChoice i ∈ convexHull ℝ (balas_nonempty_family m A b V) := by
      intro i hi
      simp [vChoice, hi, hvPos i hi]
    have hrChoice :
        ∀ i ∈ s, rChoice i ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
      intro i hi
      simp [rChoice, hi, hrPos i hi]
    have hxChoice :
        ∀ i ∈ s, xParts i = δ i • vChoice i + rChoice i := by
      intro i hi
      simp [vChoice, rChoice, hi, hxPos i hi]
    have hvertex :
        Finset.sum s (fun i ↦ δ i • vChoice i) ∈ convexHull ℝ (balas_nonempty_family m A b V) := by
      apply weighted_sum_mem_balas_vertex_hull m A b V s δ vChoice
      · intro i hi
        exact hδnonneg i
      · exact hsδ
      · intro i hi
        exact hvChoice i hi
    have hrayPos :
        Finset.sum s rChoice ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
      exact Submodule.sum_mem _ fun i hi ↦ hrChoice i hi
    have hzeroBlock :
        ∀ i, i ∉ s →
          xParts i ∈ (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
      intro i hi
      have hnotpos : ¬ 0 < δ i := by
        simpa [s] using hi
      have hδi0 : δ i = 0 := le_antisymm (not_lt.mp hnotpos) (hδnonneg i)
      have hxZero : xParts i ∈ polyhedron_le_set (A i) 0 := by
        simpa [hδi0] using hineq i
      rw [hR i] at hxZero
      exact local_ray_hull_subset_global_ray_hull R i hxZero
    have hrayZero :
        Finset.sum t xParts ∈
          (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
      refine Submodule.sum_mem _ ?_
      intro i hi
      have hi_not_mem_s : i ∉ s := by
        intro his
        have hnotpos : ¬ 0 < δ i := by
          simpa [t] using (Finset.mem_filter.1 hi).2
        exact hnotpos ((Finset.mem_filter.1 his).2)
      exact hzeroBlock i hi_not_mem_s
    have hray :
        (Finset.sum s rChoice + Finset.sum t xParts) ∈
          (PointedCone.hull ℝ (balas_ray_family R) : Set (Fin n → ℝ)) := by
      exact Submodule.add_mem _ hrayPos hrayZero
    refine ⟨Finset.sum s (fun i ↦ δ i • vChoice i), hvertex,
      (Finset.sum s rChoice + Finset.sum t xParts), hray, ?_⟩
    -- Reassemble the split witness into the Balas vertex part plus the Balas ray part.
    calc
      Finset.sum s (fun i ↦ δ i • vChoice i) +
          (Finset.sum s rChoice + Finset.sum t xParts)
          = Finset.sum s (fun i ↦ δ i • vChoice i + rChoice i) +
              Finset.sum t xParts := by
              rw [Finset.sum_add_distrib]
              abel
      _ = Finset.sum s xParts + Finset.sum t xParts := by
              refine congrArg (fun z ↦ z + Finset.sum t xParts) ?_
              exact Finset.sum_congr rfl fun i hi ↦ (hxChoice i hi).symm
      _ = ∑ i : Fin k, xParts i := by
            simpa [s, t, add_comm, add_left_comm, add_assoc] using
              (Finset.sum_filter_add_sum_filter_not (s := Finset.univ)
                (p := fun i : Fin k ↦ 0 < δ i) xParts)
      _ = x := by
            exact hsumX

end Theorem439
