import Mathlib
import Integer.Chapters.Chap03.section_3_3.ch3_sec3_3_proposition_3_9
import Integer.Chapters.Chap03.section_3_5.ch3_sec3_5_definition_3_5_extra_1

-- Declarations for this item will be appended below by the statement pipeline.

-- Domain-style sampling for this refine pass:
-- * primary domain: convex geometry of feasible integer points and their convex hull in `ℝ²`
-- * source-facing owner: `convexHull ℝ exercise_4_30_real_feasible_set`
-- * core/canonical owner: the Chapter 3 polyhedron owner `is_polyhedron`
-- * canonical bridge/view: mathlib's `LinearEquiv.finTwoArrow ℝ ℝ`
-- * primitive data: the feasible integer points and the objective functional
-- * derived API: positivity, convexity, and the non-polyhedrality statement transported along the
--   canonical `Fin 2 ↔ ℝ²` linear equivalence

open LinearEquiv
open scoped BigOperators

/-- A point `(x₁, x₂) ∈ ℤ²` is feasible for Exercise 4.30 when `1 ≤ x₂ ≤ √2 x₁`. -/
def exercise_4_30_feasible (x : ℤ × ℤ) : Prop :=
  1 ≤ x.2 ∧ (x.2 : ℝ) ≤ Real.sqrt 2 * (x.1 : ℝ)

/-- The objective value `√2 x₁ - x₂` of the integer program in Exercise 4.30. -/
noncomputable def exercise_4_30_real_objective : (ℝ × ℝ) →ₗ[ℝ] ℝ where
  toFun p := Real.sqrt 2 * p.1 - p.2
  map_add' p q := by
    dsimp
    ring
  map_smul' a p := by
    dsimp
    ring

/-- The objective value `√2 x₁ - x₂` of the integer program in Exercise 4.30. -/
noncomputable def exercise_4_30_objective (x : ℤ × ℤ) : ℝ :=
  exercise_4_30_real_objective ((x.1 : ℝ), (x.2 : ℝ))

@[simp] lemma exercise_4_30_real_objective_apply (p : ℝ × ℝ) :
    exercise_4_30_real_objective p = Real.sqrt 2 * p.1 - p.2 :=
  rfl

@[simp] lemma exercise_4_30_objective_apply (x : ℤ × ℤ) :
    exercise_4_30_objective x = Real.sqrt 2 * (x.1 : ℝ) - (x.2 : ℝ) :=
  rfl

/-- The canonical embedding of an integer point of `ℤ²` into `ℝ²`. -/
def exercise_4_30_real_point (x : ℤ × ℤ) : ℝ × ℝ :=
  ((x.1 : ℝ), (x.2 : ℝ))

/-- The subset of `ℝ²` consisting of the feasible integer points from Exercise 4.30. -/
def exercise_4_30_real_feasible_set : Set (ℝ × ℝ) :=
  exercise_4_30_real_point '' {x : ℤ × ℤ | exercise_4_30_feasible x}

/-- Helper for Exercise 4.30: the Pell-type integer points generated by multiplication by
`3 + 2√2`. -/
def exercise_4_30_pell_point : ℕ → ℤ × ℤ
  | 0 => (1, 1)
  | n + 1 =>
      let p := exercise_4_30_pell_point n
      (3 * p.1 + 2 * p.2, 4 * p.1 + 3 * p.2)

/-- Helper for Exercise 4.30: the geometric ratio in the Pell recurrence is positive. -/
lemma exercise_4_30_ratio_pos : 0 < 3 - 2 * Real.sqrt 2 := by
  -- The elementary bound `√2 < 3 / 2` makes the ratio strictly positive.
  nlinarith [Real.sqrt_two_lt_three_halves]

/-- Helper for Exercise 4.30: the Pell recurrence ratio is strictly less than `1`. -/
lemma exercise_4_30_ratio_lt_one : 3 - 2 * Real.sqrt 2 < 1 := by
  -- The lower bound `1 < √2` is enough to place the ratio below `1`.
  nlinarith [Real.one_lt_sqrt_two]

/-- Helper for Exercise 4.30: a feasible integer point has positive first coordinate. -/
lemma exercise_4_30_first_coordinate_pos {x : ℤ × ℤ} (hx : exercise_4_30_feasible x) : 0 < x.1 := by
  -- The upper feasibility inequality would contradict `x₂ ≥ 1` if `x₁ ≤ 0`.
  have hx2_ge_one : (1 : ℝ) ≤ (x.2 : ℝ) := by exact_mod_cast hx.1
  have hsqrt_pos : 0 < Real.sqrt 2 := lt_trans zero_lt_one Real.one_lt_sqrt_two
  have hx1_real_pos : 0 < (x.1 : ℝ) := by
    by_contra hx1_real_pos
    have hx1_real_nonpos : (x.1 : ℝ) ≤ 0 := le_of_not_gt hx1_real_pos
    have hmul_nonpos : Real.sqrt 2 * (x.1 : ℝ) ≤ 0 :=
      mul_nonpos_of_nonneg_of_nonpos hsqrt_pos.le hx1_real_nonpos
    linarith [hx2_ge_one, hx.2, hmul_nonpos]
  exact_mod_cast hx1_real_pos

/-- Helper for Exercise 4.30: every feasible integer point has strictly positive objective gap
`√2 x₁ - x₂`. -/
lemma exercise_4_30_feasible_objective_pos {x : ℤ × ℤ} (hx : exercise_4_30_feasible x) :
    0 < exercise_4_30_objective x := by
  -- Feasibility already gives nonnegativity of the gap.
  have hnonneg : 0 ≤ exercise_4_30_objective x := by
    simpa [sub_nonneg] using hx.2
  by_cases hzero : exercise_4_30_objective x = 0
  · -- Equality would express `√2` as an integer quotient, contradicting irrationality.
    have hx1_ne_zero : x.1 ≠ 0 := by
      have hx1_pos : 0 < x.1 := exercise_4_30_first_coordinate_pos hx
      linarith
    have hmul : Real.sqrt 2 * (x.1 : ℝ) = (x.2 : ℝ) := by
      have hzero' : Real.sqrt 2 * (x.1 : ℝ) - (x.2 : ℝ) = 0 := by
        simpa using hzero
      exact sub_eq_zero.mp hzero'
    have hrat : Real.sqrt 2 = (x.2 : ℝ) / (x.1 : ℝ) := by
      exact (eq_div_iff (by exact_mod_cast hx1_ne_zero)).2 (by simpa using hmul)
    exact (irrational_sqrt_two.ne_rational x.2 x.1 hrat).elim
  · exact lt_of_le_of_ne hnonneg (Ne.symm hzero)

/-- Helper for Exercise 4.30: one Pell step multiplies the objective gap by
`3 - 2√2`. -/
lemma exercise_4_30_objective_pell_point_succ (n : ℕ) :
    exercise_4_30_objective (exercise_4_30_pell_point (n + 1)) =
      (3 - 2 * Real.sqrt 2) * exercise_4_30_objective (exercise_4_30_pell_point n) := by
  -- Expanding the recurrence shows that the gap evolves geometrically.
  simp [exercise_4_30_pell_point, exercise_4_30_objective, exercise_4_30_real_objective]
  ring_nf
  have hs : (Real.sqrt 2) ^ 2 = 2 := by
    nlinarith [Real.sq_sqrt (show (0 : ℝ) ≤ 2 by positivity)]
  rw [hs]
  ring

/-- Helper for Exercise 4.30: every Pell point is feasible for the integer program. -/
lemma exercise_4_30_pell_point_feasible (n : ℕ) :
    exercise_4_30_feasible (exercise_4_30_pell_point n) := by
  induction n with
  | zero =>
      -- The initial Pell point is the obvious feasible point `(1, 1)`.
      constructor
      · simp [exercise_4_30_pell_point]
      · simp [exercise_4_30_pell_point]
  | succ n ih =>
      -- The recurrence preserves the upper inequality by preserving the objective gap.
      constructor
      · have hx1_pos : 0 < (exercise_4_30_pell_point n).1 := exercise_4_30_first_coordinate_pos ih
        rcases ih with ⟨hx2_ge_one, _⟩
        simp [exercise_4_30_pell_point]
        linarith
      · have hprev_nonneg : 0 ≤ exercise_4_30_objective (exercise_4_30_pell_point n) :=
          le_of_lt (exercise_4_30_feasible_objective_pos ih)
        have hnext_nonneg : 0 ≤ exercise_4_30_objective (exercise_4_30_pell_point (n + 1)) := by
          rw [exercise_4_30_objective_pell_point_succ]
          nlinarith [hprev_nonneg, exercise_4_30_ratio_pos]
        simpa [sub_nonneg] using hnext_nonneg

/-- Helper for Exercise 4.30: the Pell points have geometric objective values. -/
lemma exercise_4_30_pell_point_objective_eq (n : ℕ) :
    exercise_4_30_objective (exercise_4_30_pell_point n) =
      (Real.sqrt 2 - 1) * (3 - 2 * Real.sqrt 2) ^ n := by
  induction n with
  | zero =>
      -- The initial objective value is `√2 - 1`.
      simp [exercise_4_30_objective, exercise_4_30_pell_point, exercise_4_30_real_objective]
  | succ n ih =>
      -- Iterating the recurrence produces the claimed geometric formula.
      rw [exercise_4_30_objective_pell_point_succ, ih]
      ring

/-- Helper for Exercise 4.30: the geometric ratio powers tend to `0`. -/
lemma exercise_4_30_ratio_pow_tendsto_zero :
    Filter.Tendsto (fun k : ℕ ↦ (3 - 2 * Real.sqrt 2) ^ k) Filter.atTop (nhds 0) := by
  exact tendsto_pow_atTop_nhds_zero_of_lt_one (le_of_lt exercise_4_30_ratio_pos)
    exercise_4_30_ratio_lt_one

/-- Helper for Exercise 4.30: the Pell objective values tend to `0`. -/
lemma exercise_4_30_pell_point_objective_tendsto_zero :
    Filter.Tendsto
      (fun k : ℕ ↦ exercise_4_30_objective (exercise_4_30_pell_point k))
      Filter.atTop
      (nhds 0) := by
  convert exercise_4_30_ratio_pow_tendsto_zero.const_mul (Real.sqrt 2 - 1) using 1
  · ext k
    exact exercise_4_30_pell_point_objective_eq k
  · simp

/-- Helper for Exercise 4.30: the strict halfspace cut out by the objective is convex. -/
lemma exercise_4_30_convex_strict_objective_halfspace :
    Convex ℝ {p : ℝ × ℝ | 0 < exercise_4_30_real_objective p} := by
  intro x hx y hy a b ha hb hab
  -- A convex combination preserves strict positivity because the objective is linear.
  dsimp [exercise_4_30_real_objective] at hx hy ⊢
  by_cases ha_zero : a = 0
  · have hb_one : b = 1 := by linarith
    simpa [ha_zero, hb_one] using hy
  · have ha_pos : 0 < a := lt_of_le_of_ne ha (Ne.symm ha_zero)
    have hx' : 0 < a * (Real.sqrt 2 * x.1 - x.2) := mul_pos ha_pos hx
    have hy' : 0 ≤ b * (Real.sqrt 2 * y.1 - y.2) := mul_nonneg hb hy.le
    have hsum : 0 < a * (Real.sqrt 2 * x.1 - x.2) + b * (Real.sqrt 2 * y.1 - y.2) :=
      add_pos_of_pos_of_nonneg hx' hy'
    nlinarith

/-- Helper for Exercise 4.30: the convex hull of the feasible integer points stays in the strict
objective halfspace. -/
lemma exercise_4_30_convexHull_subset_strict_objective_halfspace :
    convexHull ℝ exercise_4_30_real_feasible_set ⊆
      {p : ℝ × ℝ | 0 < exercise_4_30_real_objective p} := by
  -- Every feasible integer point lies in the strict halfspace, and convexity preserves this.
  refine convexHull_min ?_ exercise_4_30_convex_strict_objective_halfspace
  rintro p ⟨x, hx, rfl⟩
  simpa [exercise_4_30_real_point, exercise_4_30_objective] using
    exercise_4_30_feasible_objective_pos hx

/-- Exercise 4.30 (1). The integer program
`min {√2 x₁ - x₂ | (x₁, x₂) ∈ ℤ², 1 ≤ x₂ ≤ √2 x₁}` has no optimal solution. -/
theorem exercise_4_30_has_no_optimal_solution :
    ¬ ∃ x : ℤ × ℤ,
      exercise_4_30_feasible x ∧
        ∀ y : ℤ × ℤ,
          exercise_4_30_feasible y → exercise_4_30_objective x ≤ exercise_4_30_objective y := by
  rintro ⟨x, hx, hopt⟩
  have hx_obj_pos : 0 < exercise_4_30_objective x := exercise_4_30_feasible_objective_pos hx
  have hseq_lt :
      ∀ᶠ k : ℕ in Filter.atTop,
        exercise_4_30_objective (exercise_4_30_pell_point k) < exercise_4_30_objective x := by
    -- Convergence to `0` eventually puts the sequence below the supposed optimal value.
    exact exercise_4_30_pell_point_objective_tendsto_zero (Iio_mem_nhds hx_obj_pos)
  rcases Filter.Eventually.exists hseq_lt with ⟨k, hk⟩
  exact not_lt_of_ge (hopt (exercise_4_30_pell_point k) (exercise_4_30_pell_point_feasible k)) hk

/-- Exercise 4.30 (2). There exists a sequence of feasible integer points whose objective values
converge to `0`. -/
theorem exercise_4_30_exists_feasible_sequence_tending_to_zero :
    ∃ x : ℕ → ℤ × ℤ,
      (∀ k : ℕ, exercise_4_30_feasible (x k)) ∧
        Filter.Tendsto (fun k : ℕ ↦ exercise_4_30_objective (x k)) Filter.atTop (nhds 0) := by
  exact ⟨exercise_4_30_pell_point, exercise_4_30_pell_point_feasible,
    exercise_4_30_pell_point_objective_tendsto_zero⟩

/-- Helper for Exercise 4.30: transport the real objective to the canonical `Fin 2 → ℝ` owner via
`LinearEquiv.finTwoArrow`. -/
noncomputable def exercise_4_30_fin_objective : (Fin 2 → ℝ) →ₗ[ℝ] ℝ :=
  exercise_4_30_real_objective.comp (finTwoArrow ℝ ℝ).toLinearMap

/-- Helper for Exercise 4.30: the transported objective is evaluated by converting back to
`ℝ × ℝ`. -/
@[simp] lemma exercise_4_30_fin_objective_apply (z : Fin 2 → ℝ) :
    exercise_4_30_fin_objective z = exercise_4_30_real_objective ((finTwoArrow ℝ ℝ) z) :=
  rfl

/-- Helper for Exercise 4.30: the `Fin 2` image of the convex hull still lies in the strict
objective halfspace. -/
lemma exercise_4_30_fin_image_subset_strict_objective_halfspace :
    ((finTwoArrow ℝ ℝ).symm '' convexHull ℝ exercise_4_30_real_feasible_set) ⊆
      {z : Fin 2 → ℝ | 0 < exercise_4_30_fin_objective z} := by
  rintro z ⟨p, hp, rfl⟩
  -- Transport the already-proved strict positivity along the linear equivalence.
  simpa [exercise_4_30_fin_objective] using
    exercise_4_30_convexHull_subset_strict_objective_halfspace hp

/-- Helper for Exercise 4.30: the negated transported objective is the LP cost vector
`[-√2, 1]`. -/
noncomputable def exercise_4_30_neg_cost : Fin 2 → ℝ :=
  ![-Real.sqrt 2, 1]

/-- Helper for Exercise 4.30: dotting with the cost vector `[-√2, 1]` is exactly the negated
transported objective. -/
lemma exercise_4_30_neg_cost_dot_eq_neg_fin_objective (z : Fin 2 → ℝ) :
    exercise_4_30_neg_cost ⬝ᵥ z = -exercise_4_30_fin_objective z := by
  -- Expand the two coordinates and compare with the definition of the transported objective.
  rw [Matrix.vec2_dotProduct]
  rw [exercise_4_30_fin_objective_apply]
  simp [exercise_4_30_neg_cost, exercise_4_30_real_objective]
  ring

/-- Helper for Exercise 4.30: transporting an integer point to `Fin 2 → ℝ` does not change the
objective value. -/
lemma exercise_4_30_fin_objective_transport_real_point (x : ℤ × ℤ) :
    exercise_4_30_fin_objective ((finTwoArrow ℝ ℝ).symm (exercise_4_30_real_point x)) =
      exercise_4_30_objective x := by
  -- Evaluating after transporting to `Fin 2 → ℝ` is definitionally the same as evaluating in `ℝ²`.
  simp [exercise_4_30_fin_objective, exercise_4_30_objective, exercise_4_30_real_point]

/-- Helper for Exercise 4.30: every Pell point belongs to the transported convex hull of the
feasible integer points. -/
lemma exercise_4_30_pell_point_mem_transported_convexHull (n : ℕ) :
    (finTwoArrow ℝ ℝ).symm (exercise_4_30_real_point (exercise_4_30_pell_point n)) ∈
      ((finTwoArrow ℝ ℝ).symm '' convexHull ℝ exercise_4_30_real_feasible_set) := by
  -- A feasible Pell point lies in the original feasible set, hence in its convex hull and image.
  refine ⟨exercise_4_30_real_point (exercise_4_30_pell_point n), ?_, ?_⟩
  · refine subset_convexHull ℝ exercise_4_30_real_feasible_set ?_
    exact Set.mem_image_of_mem exercise_4_30_real_point
      (exercise_4_30_pell_point_feasible n)
  · simp

/-- Exercise 4.30 (3). Under the canonical linear equivalence between `Fin 2 → ℝ` and `ℝ²`, the
convex hull of the feasible integer points `{x ∈ ℤ² | 1 ≤ x₂ ≤ √2 x₁}` is not a polyhedron on the
Chapter 3 owner surface. -/
theorem exercise_4_30_convexHull_real_feasible_set_not_polyhedron :
    ¬ is_polyhedron ((finTwoArrow ℝ ℝ).symm '' convexHull ℝ exercise_4_30_real_feasible_set) := by
  -- Route correction: use the LP-duality contradiction route already aligned with the Chapter 3
  -- polyhedron owner, rather than reintroducing the earlier cone-decomposition detour.
  let P : Set (Fin 2 → ℝ) :=
    (finTwoArrow ℝ ℝ).symm '' convexHull ℝ exercise_4_30_real_feasible_set
  intro hP_polyhedron
  have hP_pos : P ⊆ {z : Fin 2 → ℝ | 0 < exercise_4_30_fin_objective z} := by
    -- Transport strict positivity from `ℝ²` to the `Fin 2` owner surface.
    simpa [P] using exercise_4_30_fin_image_subset_strict_objective_halfspace
  rcases (is_polyhedron_iff.mp hP_polyhedron) with ⟨m, A, b, hP_eq⟩
  have hP_eq' : P = polyhedron_le_set A b := by
    -- Repackage the owner equality using the local abbreviation `P`.
    simpa [P] using hP_eq
  have hP_nonempty : P.Nonempty := by
    -- The initial Pell point gives a concrete point of the transported convex hull.
    refine ⟨(finTwoArrow ℝ ℝ).symm
      (exercise_4_30_real_point (exercise_4_30_pell_point 0)), ?_⟩
    simpa [P] using exercise_4_30_pell_point_mem_transported_convexHull 0
  have hprimal_nonempty : Set.Nonempty (primal_feasible_region A b) := by
    rcases hP_nonempty with ⟨z, hz⟩
    refine ⟨z, ?_⟩
    have hz_poly : z ∈ polyhedron_le_set A b := by
      simpa [hP_eq'] using hz
    simpa [mem_primal_feasible_region_iff, polyhedron_le_set] using hz_poly
  have hobjective_bddAbove :
      BddAbove (primal_objective_values A b exercise_4_30_neg_cost) := by
    refine ⟨0, ?_⟩
    rintro y ⟨z, hz, rfl⟩
    have hzP : z ∈ P := by
      have hz_poly : z ∈ polyhedron_le_set A b := by
        simpa [primal_feasible_region, polyhedron_le_set] using hz
      simpa [hP_eq'] using hz_poly
    have hz_obj_pos : 0 < exercise_4_30_fin_objective z := hP_pos hzP
    change exercise_4_30_neg_cost ⬝ᵥ z ≤ 0
    rw [exercise_4_30_neg_cost_dot_eq_neg_fin_objective]
    linarith
  have hdual_nonempty : Set.Nonempty (dual_feasible_region A exercise_4_30_neg_cost) := by
    -- Since the negated objective is bounded above on the polyhedron, Proposition 3.9 forces a
    -- dual feasible point.
    by_contra hdual_empty
    have hunbounded :
        ¬ BddAbove (primal_objective_values A b exercise_4_30_neg_cost) := by
      rw [primal_objective_unbounded_iff_dual_feasible_region_empty A b
        exercise_4_30_neg_cost hprimal_nonempty]
      exact Set.not_nonempty_iff_eq_empty.mp hdual_empty
    exact hunbounded hobjective_bddAbove
  rcases linear_programming_duality_primal_optimum_exists A b exercise_4_30_neg_cost
      hprimal_nonempty hdual_nonempty with ⟨xStar, hxStar, hStar_opt⟩
  have hxStarP : xStar ∈ P := by
    -- Translate primal feasibility back to membership in the transported convex hull.
    rw [hP_eq']
    simpa [mem_primal_feasible_region_iff, polyhedron_le_set] using hxStar
  have hxStar_obj_pos : 0 < exercise_4_30_fin_objective xStar := hP_pos hxStarP
  have hseq_lt :
      ∀ᶠ k : ℕ in Filter.atTop,
        exercise_4_30_objective (exercise_4_30_pell_point k) <
          exercise_4_30_fin_objective xStar := by
    -- The Pell objectives converge to `0`, so eventually they fall below the candidate minimum.
    exact exercise_4_30_pell_point_objective_tendsto_zero (Iio_mem_nhds hxStar_obj_pos)
  rcases Filter.Eventually.exists hseq_lt with ⟨k, hk⟩
  have hk_memP :
      (finTwoArrow ℝ ℝ).symm (exercise_4_30_real_point (exercise_4_30_pell_point k)) ∈ P := by
    -- Reuse the transported convex-hull membership already recorded for Pell points.
    simpa [P] using exercise_4_30_pell_point_mem_transported_convexHull k
  have hk_feasible : (finTwoArrow ℝ ℝ).symm
      (exercise_4_30_real_point (exercise_4_30_pell_point k)) ∈ primal_feasible_region A b := by
    have hk_poly :
        (finTwoArrow ℝ ℝ).symm (exercise_4_30_real_point (exercise_4_30_pell_point k)) ∈
          polyhedron_le_set A b := by
      simpa [hP_eq'] using hk_memP
    simpa [mem_primal_feasible_region_iff, polyhedron_le_set] using hk_poly
  have hk_opt :
      exercise_4_30_neg_cost ⬝ᵥ
          ((finTwoArrow ℝ ℝ).symm (exercise_4_30_real_point (exercise_4_30_pell_point k))) ≤
        exercise_4_30_neg_cost ⬝ᵥ xStar := by
    -- Optimality of `xStar` for the negated objective dominates every feasible Pell point.
    exact hStar_opt.2 ⟨_, hk_feasible, rfl⟩
  have hk_lower :
      exercise_4_30_fin_objective xStar ≤
        exercise_4_30_objective (exercise_4_30_pell_point k) := by
    -- Rewriting the maximizing inequality for `-f` produces the minimizing inequality for `f`.
    rw [exercise_4_30_neg_cost_dot_eq_neg_fin_objective,
      exercise_4_30_neg_cost_dot_eq_neg_fin_objective] at hk_opt
    simpa [exercise_4_30_fin_objective_transport_real_point] using neg_le_neg hk_opt
  exact not_lt_of_ge hk_lower hk
