import Mathlib
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Corollary_7_12
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Corollary_7_19
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Corollary_7_6
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Definition_7_1
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Definition_7_14
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Definition_7_8
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Example_7_15
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_1
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_10
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_2
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_4
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_5
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_7
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_8
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Exercise_7_9
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_11
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_13
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_16
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_2
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_3
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Proposition_7_5
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Remark_7_17_1
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Remark_7_17_2
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Theorem_7_18
import ConvexAnalysisMonotoneOperators_BauschkeCombettes_2017.Chap07.Theorem_7_4

/-!
# Chapter 07 — Convex Analysis and Monotone Operator Theory (Bauschke & Combettes, 2017)

Aggregation module for all formalized items in Chapter 7.
-/
