import StacksProject_2024.stacks_project.Chap20.Lemma_20_20_3

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory CategoryTheory.Limits TopologicalSpace TopCat

noncomputable section

universe u

namespace CategoryTheory
namespace Sheaf

variable {X : TopCat.{u}}
local notation "JX" => Opens.grothendieckTopology X

/- Domain-style sampling for Lemma 20.20.4:
- primary domain: higher cohomology of abelian sheaves on quasi-compact spectral-style spaces,
  reduced to extension-by-zero constant integer sheaves on quasi-compact opens;
- sampled owner declarations:
  `CompactOpens`,
  `j!ℤ[U.toOpens]`,
  `Sheaf.H'`;
- best owner abstraction: the local acyclicity hypothesis ranges over quasi-compact opens, so its
  primitive input should be the canonical owner `CompactOpens X` rather than an open together with
  a separate compactness proof. The cohomology objects themselves should stay on the canonical
  owner `Sheaf.H'`, and the source sheaves should stay on the Chapter 20 lower-shriek notation,
  specialized to compact opens as `j!ℤ[U.toOpens]`;
- primitive data: a quasi-compact open `U : CompactOpens X`, an abelian sheaf `F`, and a degree
  bound `d < p`;
- derived API: the degree-`p` cohomology objects on `⊤` and their vanishing assertions.

Source/core/bridge triage:
- `source-facing`: the vanishing-transfer statement from the source text;
- `core/canonical`: `CompactOpens X` and `Sheaf.H'`;
- `bridge/view`: the compact-open specialization of the Chapter 20 notation `j!ℤ[U]`, written in
  Lean as `j!ℤ[U.toOpens]`. -/

-- Proof sketch: write any abelian sheaf `F` as the filtered colimit of its subsheaves generated by
-- finitely many local sections over compact opens and use Lemma `20.19.1` to pass cohomology
-- through that filtered colimit. Then induct on the number of generators, reducing to quotients of
-- sheaves `j!ℤ[U]`. For the kernel of such a quotient,
-- use the finite filtration supplied by Lemma `20.20.3`; the long exact cohomology sequence and
-- induction on the
-- filtration length propagate the assumed vanishing from the extension-by-zero constant integer
-- sheaves to every abelian sheaf.
/-- The compact-open acyclicity hypothesis used in Lemma 20.20.4: every extension-by-zero constant
integer sheaf `j!ℤ[U.toOpens]` has vanishing global cohomology in degrees strictly larger than
`d`. -/
class HasAcyclicExtensionByZeroConstantIntegerSheaves
    (Y : TopCat.{u})
    [PrespectralSpace Y] [QuasiSeparatedSpace Y]
    [HasSheafify (Opens.grothendieckTopology Y) AddCommGrpCat.{u}]
    [HasExt.{u} (Y.Sheaf AddCommGrpCat.{u})]
    (d : outParam ℕ) : Prop where
  isZero (U : CompactOpens Y) (p : ℕ) (hp : d < p) :
    IsZero ((j!ℤ[U.toOpens]).H' p (⊤ : Opens Y))

/-- Typeclass form of the compact-open acyclicity hypothesis: for `p > d`, the extension-by-zero
constant integer sheaf `j!ℤ[U.toOpens]` has vanishing global cohomology in degree `p`. -/
instance instIsZeroExtensionByZeroConstantIntegerSheafOfHasAcyclicExtensionByZeroConstantIntegerSheaves
    [PrespectralSpace X] [QuasiSeparatedSpace X]
    [HasSheafify JX AddCommGrpCat.{u}]
    [HasExt.{u} (X.Sheaf AddCommGrpCat.{u})]
    {d : ℕ} [hacyclic : HasAcyclicExtensionByZeroConstantIntegerSheaves X d]
    (U : CompactOpens X) (p : ℕ) [Fact (d < p)] :
    IsZero ((j!ℤ[U.toOpens]).H' p (⊤ : Opens X)) :=
  hacyclic.isZero U p Fact.out

/-- Typeclass form of Lemma 20.20.4: under the acyclicity hypothesis for the compact-open
extension-by-zero constant integer sheaves, every cohomology object `H^p(X, 𝓕)` with `p > d`
vanishes. -/
instance instIsZeroHigherCohomologyOfAcyclicExtensionByZeroConstantIntegerSheaf
    [PrespectralSpace X] [QuasiSeparatedSpace X]
    [HasSheafify JX AddCommGrpCat.{u}]
    [HasExt.{u} (X.Sheaf AddCommGrpCat.{u})]
    {d : ℕ} [hacyclic : HasAcyclicExtensionByZeroConstantIntegerSheaves X d]
    (F : X.Sheaf AddCommGrpCat.{u}) (p : ℕ) [Fact (d < p)] :
    IsZero (F.H' p (⊤ : Opens X)) := by
  sorry

/-- Lemma 20.20.4: if `X` is prespectral and quasi-separated, and if `H^p(X, j!ℤ[U]) = 0` for
every compact open `U` and every `p > d`, then `H^p(X, 𝓕) = 0` for every abelian sheaf `𝓕` and
every `p > d`. -/
@[stacks 02UX]
theorem isZero_higherCohomology_of_acyclic_extensionByZeroConstantIntegerSheaf
    [PrespectralSpace X] [QuasiSeparatedSpace X]
    [HasSheafify JX AddCommGrpCat.{u}]
    [HasExt.{u} (X.Sheaf AddCommGrpCat.{u})]
    (d : ℕ)
    (hacyclic : ∀ (U : CompactOpens X) (p : ℕ), d < p →
      IsZero ((j!ℤ[U.toOpens]).H' p (⊤ : Opens X)))
    (F : X.Sheaf AddCommGrpCat.{u}) {p : ℕ} (hp : d < p) :
    IsZero (F.H' p (⊤ : Opens X)) := by
  letI : HasAcyclicExtensionByZeroConstantIntegerSheaves X d :=
    ⟨fun U p hp ↦ hacyclic U p hp⟩
  letI : Fact (d < p) := ⟨hp⟩
  exact instIsZeroHigherCohomologyOfAcyclicExtensionByZeroConstantIntegerSheaf F p

end Sheaf
end CategoryTheory
