import StacksProject_2024.stacks_project.Chap06.Definition_6_26_1
import StacksProject_2024.stacks_project.Chap12.Definition_12_31_2
import StacksProject_2024.stacks_project.Chap20.Global_sections_module_owners_core
import StacksProject_2024.stacks_project.Chap20.Sections_on_open

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open CategoryTheory.Limits
open CategoryTheory.SequentialInverseSystem
open Opposite
open TopologicalSpace
open AlgebraicGeometry

noncomputable section

universe u

namespace AlgebraicGeometry.RingedSpace

/-
Domain-style sampling for Lemma 20.36.1:
- primary domain: sequential inverse systems of `𝒪_X`-modules equipped with
  multiplication by a global section of the structure sheaf;
- sampled owner declarations:
  * `globalSectionsRing X`;
  * the canonical restriction map `X.presheaf.map (Opens.leTop U).op`;
  * `RingedSpace.Modules X`;
- best owner abstraction:
  * `source-facing`: the three conditions of Lemma 20.36.1 and their equivalence theorems;
  * `core/canonical`: the global-sections ring `globalSectionsRing X`, the ambient category
    `RingedSpace.Modules X`, and the canonical restriction maps on the structure sheaf;
  * `bridge/view`: the source-facing name `globalSectionMul` for that canonical scalar
    endomorphism, reused by the kernel/quotient towers below;
- primitive data: a global section `f : globalSectionsRing X`, a module or sequential inverse
  system of modules, and the short-exact/kernel/cokernel conditions;
- derived API: the multiplication endomorphism `globalSectionMul f ℱ`, its powers, and the
  canonical kernel/quotient towers generated by those powers. -/

variable {X : RingedSpace.{u}}

private abbrev globalSectionsToOpenMap
    (X : RingedSpace.{u}) (U : Opens X.carrier) :
    globalSectionsRing X ⟶ sectionsRingOnOpen X U :=
  X.presheaf.map (Opens.leTop U).op

local notation "ΓX" => globalSectionsRing X
local notation "ModX" => RingedSpace.Modules X

/-- Multiplication by a global section as an endomorphism of the module of sections over an open
subset. -/
private abbrev globalSectionMulApp
    (f : ΓX) (ℱ : ModX) (U : (Opens X.carrier)ᵒᵖ) :
    ℱ.val.obj U ⟶ ℱ.val.obj U :=
  let r : X.presheaf.obj U := (globalSectionsToOpenMap X U.unop).hom f
  ModuleCat.ofHom (LinearMap.lsmul (X.presheaf.obj U) (ℱ.val.obj U) r)

/-- Multiplication by a global section is natural with respect to restriction maps. -/
private theorem globalSectionMul_naturality
    (f : ΓX) (ℱ : ModX) {U V : (Opens X.carrier)ᵒᵖ}
    (i : U ⟶ V) :
    ℱ.val.map i ≫
      (ModuleCat.restrictScalars ((X.presheaf.map i).hom)).map
        (globalSectionMulApp f ℱ V) =
    globalSectionMulApp f ℱ U ≫ ℱ.val.map i := by
  -- Restriction maps are semilinear, so they commute with scalar multiplication after
  -- transporting the scalar along the restriction map on the structure sheaf.
  ext s
  change
    (ModuleCat.Hom.hom
        ((ModuleCat.restrictScalars ((X.presheaf.map i).hom)).map
          (globalSectionMulApp f ℱ V))
        ((ℱ.val.map i).hom s) : ℱ.val.obj V) =
      (ℱ.val.map i).hom (ModuleCat.Hom.hom (globalSectionMulApp f ℱ U) s)
  have hres :
      (X.presheaf.map i).hom ((globalSectionsToOpenMap X U.unop).hom f) =
        (globalSectionsToOpenMap X V.unop).hom f := by
    have hcomp : (Opens.leTop U.unop).op ≫ i = (Opens.leTop V.unop).op := by
      exact Subsingleton.elim _ _
    dsimp [globalSectionsToOpenMap]
    change ((X.presheaf.map (Opens.leTop U.unop).op ≫ X.presheaf.map i).hom f) =
      (X.presheaf.map (Opens.leTop V.unop).op).hom f
    rw [← X.presheaf.map_comp]
    rw [hcomp]
  rw [show
      (ModuleCat.Hom.hom
          ((ModuleCat.restrictScalars ((X.presheaf.map i).hom)).map
            (globalSectionMulApp f ℱ V))
          ((ℱ.val.map i).hom s) :
        ℱ.val.obj V) =
        ((globalSectionsToOpenMap X V.unop).hom f) •
          (show ℱ.val.obj V from (ℱ.val.map i).hom s) by
      rfl]
  rw [show
      (ModuleCat.Hom.hom (globalSectionMulApp f ℱ U) s : ℱ.val.obj U) =
        ((globalSectionsToOpenMap X U.unop).hom f) • s by
      rfl]
  rw [show
      (ℱ.val.map i).hom (((globalSectionsToOpenMap X U.unop).hom f) • s) =
        (X.presheaf.map i).hom ((globalSectionsToOpenMap X U.unop).hom f) •
          (show ℱ.val.obj V from (ℱ.val.map i).hom s) by
      simpa using (ℱ.val.map i).hom.map_smulₛₗ ((globalSectionsToOpenMap X U.unop).hom f) s]
  rw [hres]

/-- Multiplication by a global section of the structure sheaf on an `𝒪_X`-module. -/
abbrev globalSectionMul
    (f : ΓX) (ℱ : ModX) :
    ℱ ⟶ ℱ where
  val.app U := globalSectionMulApp f ℱ U
  val.naturality i := globalSectionMul_naturality f ℱ i

/-- Multiplication by the `n`th power of a global section of the structure sheaf. -/
abbrev globalSectionMulPow
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    ℱ ⟶ ℱ :=
  globalSectionMul (f ^ n) ℱ

/-- The stage `ℱ[f^(n + 1)]` of the global-section power kernel tower. -/
abbrev globalSectionPowerKernelStage
    (f : ΓX) (ℱ : ModX) (n : ℕ) : ModX :=
  kernel (globalSectionMulPow f ℱ (n + 1))

/-- Multiplying first by a global section `f` and then by `f^n` is multiplication by
`f^(n + 1)`. -/
theorem globalSectionMul_comp_pow
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    globalSectionMul f ℱ ≫ globalSectionMulPow f ℱ n =
      globalSectionMulPow f ℱ (n + 1) := by
  ext U s
  change
    ((globalSectionsToOpenMap X U.unop).hom (f ^ n)) •
        (((globalSectionsToOpenMap X U.unop).hom f) • s) =
      ((globalSectionsToOpenMap X U.unop).hom (f ^ (n + 1))) • s
  rw [smul_smul, map_pow, map_pow]
  simp [pow_succ, mul_comm]

/-- Multiplication by the unit global section is the identity endomorphism. -/
@[simp]
theorem globalSectionMul_one
    (ℱ : ModX) :
    globalSectionMul (1 : ΓX) ℱ = 𝟙 ℱ := by
  ext U s
  change ((globalSectionsToOpenMap X U.unop).hom (1 : ΓX)) • s = s
  rw [map_one]
  simp

-- Proof sketch: a section killed by `f^(n + 2)` is sent by multiplication by `f` to a section
-- killed by `f^(n + 1)`.
/-- Multiplication by `f` sends `ℱ[f^(n + 2)]` into `ℱ[f^(n + 1)]`. -/
private theorem globalSectionPowerKernelTransition_condition
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    kernel.ι (globalSectionMulPow f ℱ (n + 2)) ≫
      globalSectionMul f ℱ ≫
        globalSectionMulPow f ℱ (n + 1) = 0 := by
  -- Rewrite the composite as the defining kernel map for `f^(n + 2)`.
  calc
    kernel.ι (globalSectionMulPow f ℱ (n + 2)) ≫
        globalSectionMul f ℱ ≫
          globalSectionMulPow f ℱ (n + 1)
        =
      kernel.ι (globalSectionMulPow f ℱ (n + 2)) ≫
        globalSectionMulPow f ℱ (n + 2) := by
          simpa [Category.assoc] using
            congrArg
              (fun k ↦
                kernel.ι (globalSectionMulPow f ℱ (n + 2)) ≫ k)
              (globalSectionMul_comp_pow f ℱ (n + 1))
    _ = 0 := kernel.condition (globalSectionMulPow f ℱ (n + 2))

/-- The transition morphism
`ℱ[f^(n + 2)] ⟶ ℱ[f^(n + 1)]` in the global-section power kernel tower. -/
abbrev globalSectionPowerKernelTransition
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    globalSectionPowerKernelStage f ℱ (n + 1) ⟶
      globalSectionPowerKernelStage f ℱ n :=
  kernel.lift (globalSectionMulPow f ℱ (n + 1))
    (kernel.ι (globalSectionMulPow f ℱ (n + 2)) ≫ globalSectionMul f ℱ)
    (globalSectionPowerKernelTransition_condition f ℱ n)

/-- The sequential inverse system `(ℱ[f^(n + 1)])ₙ`, with transition maps induced by
multiplication by `f`. -/
abbrev globalSectionPowerKernelTower
    (f : ΓX) (ℱ : ModX) : SequentialInverseSystem ModX :=
  Functor.ofOpSequence (globalSectionPowerKernelTransition f ℱ)

/-- The quotient stage `ℱ / f^(n + 1)ℱ` attached to a global section `f`. -/
abbrev globalSectionPowerQuotientStage
    (f : ΓX) (ℱ : ModX) (n : ℕ) : ModX :=
  cokernel (globalSectionMulPow f ℱ (n + 1))

-- Proof sketch: multiplication by `f^(n + 2)` factors through multiplication by `f^(n + 1)`,
-- so the quotient map for `f^(n + 1)` annihilates the image of `f^(n + 2)`.
/-- The canonical quotient map defines the successor transition on the global-section power
quotient tower. -/
private theorem globalSectionPowerQuotientTransition_condition
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    globalSectionMulPow f ℱ (n + 2) ≫
      cokernel.π (globalSectionMulPow f ℱ (n + 1)) = 0 := by
  -- Factor `f^(n + 2)` through `f^(n + 1)` and apply the cokernel relation.
  calc
    globalSectionMulPow f ℱ (n + 2) ≫
        cokernel.π (globalSectionMulPow f ℱ (n + 1))
        =
      globalSectionMul f ℱ ≫ globalSectionMulPow f ℱ (n + 1) ≫
        cokernel.π (globalSectionMulPow f ℱ (n + 1)) := by
          simpa [Category.assoc] using
            congrArg
              (fun k ↦
                k ≫ cokernel.π (globalSectionMulPow f ℱ (n + 1)))
              (globalSectionMul_comp_pow f ℱ (n + 1)).symm
    _ = globalSectionMul f ℱ ≫ 0 := by
          simp [cokernel.condition]
    _ = 0 := by simp

/-- The transition morphism
`ℱ / f^(n + 2)ℱ ⟶ ℱ / f^(n + 1)ℱ`. -/
abbrev globalSectionPowerQuotientTransition
    (f : ΓX) (ℱ : ModX) (n : ℕ) :
    globalSectionPowerQuotientStage f ℱ (n + 1) ⟶
      globalSectionPowerQuotientStage f ℱ n :=
  cokernel.desc (globalSectionMulPow f ℱ (n + 2))
    (cokernel.π (globalSectionMulPow f ℱ (n + 1)))
    (globalSectionPowerQuotientTransition_condition f ℱ n)

/-- The sequential inverse system `(ℱ / f^(n + 1)ℱ)ₙ`. -/
abbrev globalSectionPowerQuotientTower
    (f : ΓX) (ℱ : ModX) : SequentialInverseSystem ModX :=
  Functor.ofOpSequence (globalSectionPowerQuotientTransition f ℱ)

/-- An `𝒪_X`-module is `f`-divisible if multiplication by `f` is an epimorphism. -/
abbrev IsDivisibleByGlobalSection
    (f : ΓX) (ℱ : ModX) : Prop :=
  Epi (globalSectionMul f ℱ)

/-- An `𝒪_X`-module is `f`-torsion free if multiplication by `f` is a monomorphism. -/
abbrev IsTorsionFreeByGlobalSection
    (f : ΓX) (ℱ : ModX) : Prop :=
  Mono (globalSectionMul f ℱ)

/-- Condition (1) from Lemma 20.36.1: for every `n ≥ 1`, multiplication by `f` on
`ℱ_{n + 1}` factors through `ℱ_{n + 1} ⟶ ℱ_n` and gives a short
exact sequence `0 ⟶ ℱ_n ⟶ ℱ_{n + 1} ⟶ ℱ_1 ⟶ 0`. -/
def stepShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) : Prop :=
  ∀ n ≥ 1,
    let π := transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n))
    let σ := stepMap ℱ n
    ∃ (ι : ℱ.obj (op n) ⟶ ℱ.obj (op (n + 1))) (hιπ : ι ≫ π = 0),
      (ShortComplex.mk ι π hιπ).ShortExact ∧
        σ ≫ ι = globalSectionMul f (ℱ.obj (op (n + 1)))

/-- Condition (2) from Lemma 20.36.1: for every `n ≥ 1`, multiplication by `f^n` on
`ℱ_{n + 1}` factors through `ℱ_{n + 1} ⟶ ℱ_1` and gives a short
exact sequence `0 ⟶ ℱ_1 ⟶ ℱ_{n + 1} ⟶ ℱ_n ⟶ 0`. -/
def powerShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) : Prop :=
  ∀ n ≥ 1,
    let π := stepMap ℱ n
    let σ := transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n))
    ∃ (ι : ℱ.obj (op 1) ⟶ ℱ.obj (op (n + 1))) (hιπ : ι ≫ π = 0),
      (ShortComplex.mk ι π hιπ).ShortExact ∧
        σ ≫ ι =
          globalSectionMulPow f (ℱ.obj (op (n + 1))) n

/-- Condition (3) from Lemma 20.36.1: the inverse system is obtained from the kernels
`𝒢[f^n]` of powers of multiplication by `f` on an `f`-divisible module `𝒢`.
Because the source tower is indexed by `n ≥ 1`, we compare `ℱ_n` with the shifted tower
`(𝒢[f^(n + 1)])ₙ = (𝒢[f^n])_{n ≥ 1}`. -/
def divisibleKernelTowerCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) : Prop :=
  ∃ 𝒢 : ModX,
    IsDivisibleByGlobalSection f 𝒢 ∧
      Nonempty (shift ℱ 1 ≅ globalSectionPowerKernelTower f 𝒢)

/-- Helper for Lemma 20.36.1: morphisms of `𝒪_X`-modules commute with multiplication by
powers of a global section. -/
theorem globalSectionMulPow_natural
    (f : ΓX) {𝒜 ℬ : ModX} (φ : 𝒜 ⟶ ℬ) (n : ℕ) :
    globalSectionMulPow f 𝒜 n ≫ φ =
      φ ≫ globalSectionMulPow f ℬ n := by
  -- Compare both morphisms sectionwise; `φ` is linear over every restriction ring.
  ext U s
  simpa [globalSectionMulPow, globalSectionMul] using
    (φ.val.app U).hom.map_smul ((globalSectionsToOpenMap X U.unop).hom (f ^ n)) s

/-- If multiplication by `f` is mono, then multiplication by every power `f^n` is mono as well. -/
instance globalSectionMulPow_mono
    (f : ΓX) (𝒢 : ModX) [Mono (globalSectionMul f 𝒢)] (n : ℕ) :
    Mono (globalSectionMulPow f 𝒢 n) := by
  induction n with
  | zero =>
      -- The zeroth power acts as the identity.
      rw [globalSectionMulPow, pow_zero]
      rw [globalSectionMul_one]
      infer_instance
  | succ n ih =>
      -- Rewrite `f^(n + 1)` as the composite `f` followed by `f^n`.
      rw [← globalSectionMul_comp_pow]
      letI : Mono (globalSectionMulPow f 𝒢 n) := ih
      infer_instance

/-- If multiplication by `f` is epi, then multiplication by every power `f^n` is epi as well. -/
instance globalSectionMulPow_epi
    (f : ΓX) (𝒢 : ModX) [Epi (globalSectionMul f 𝒢)] (n : ℕ) :
    Epi (globalSectionMulPow f 𝒢 n) := by
  induction n with
  | zero =>
      -- The zeroth power acts as the identity.
      rw [globalSectionMulPow, pow_zero]
      rw [globalSectionMul_one]
      infer_instance
  | succ n ih =>
      -- Rewrite `f^(n + 1)` as the composite `f` followed by `f^n`.
      rw [← globalSectionMul_comp_pow]
      letI : Epi (globalSectionMulPow f 𝒢 n) := ih
      infer_instance

/-- Helper for Lemma 20.36.1: the canonical inclusion `𝒢[f] ⟶ 𝒢[f^(n + 2)]`. -/
abbrev globalSectionPowerKernelInclusion
    (f : ΓX) (𝒢 : ModX) (n : ℕ) :
    globalSectionPowerKernelStage f 𝒢 0 ⟶
      globalSectionPowerKernelStage f 𝒢 (n + 1) :=
  kernel.lift (globalSectionMulPow f 𝒢 (n + 2))
    (kernel.ι (globalSectionMulPow f 𝒢 1))
    (by
      -- A section killed by `f` is automatically killed by every higher power of `f`.
      have hker :
          kernel.ι (globalSectionMulPow f 𝒢 1) ≫ globalSectionMul f 𝒢 = 0 := by
        have hpow1 : globalSectionMulPow f 𝒢 1 = globalSectionMul f 𝒢 := by
          ext U s
          change ((globalSectionsToOpenMap X U.unop).hom (f ^ 1)) • s =
            ((globalSectionsToOpenMap X U.unop).hom f) • s
          rw [pow_one]
        rw [← hpow1]
        exact kernel.condition (globalSectionMulPow f 𝒢 1)
      calc
        kernel.ι (globalSectionMulPow f 𝒢 1) ≫
            globalSectionMulPow f 𝒢 (n + 2)
            =
          kernel.ι (globalSectionMulPow f 𝒢 1) ≫
            globalSectionMul f 𝒢 ≫
              globalSectionMulPow f 𝒢 (n + 1) := by
                simpa [Category.assoc] using
                  congrArg
                    (fun k ↦ kernel.ι (globalSectionMulPow f 𝒢 1) ≫ k)
                    (globalSectionMul_comp_pow f 𝒢 (n + 1)).symm
        _ =
          (kernel.ι (globalSectionMulPow f 𝒢 1) ≫ globalSectionMul f 𝒢) ≫
            globalSectionMulPow f 𝒢 (n + 1) := by
              simp [Category.assoc]
        _ = 0 := by simp [hker]
)

/-- Helper for Lemma 20.36.1: the canonical inclusion `𝒢[f] ⟶ 𝒢[f^(n + 2)]` is the obvious
subobject inclusion into `𝒢`. -/
theorem globalSectionPowerKernelInclusion_comp_ι
    (f : ΓX) (𝒢 : ModX) (n : ℕ) :
    globalSectionPowerKernelInclusion f 𝒢 n ≫
      kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) =
        kernel.ι (globalSectionMulPow f 𝒢 1) := by
  -- The inclusion was defined by the universal property of the larger kernel.
  simp [globalSectionPowerKernelInclusion]

/-- Helper for Lemma 20.36.1: transition maps in a sequential inverse system compose through any
intermediate stage. -/
private theorem sequentialInverseSystem_transitionMap_comp
    {C : Type*} [Category C] (F : SequentialInverseSystem C)
    {i j k : ℕ} (hij : i ≤ j) (hjk : j ≤ k) :
    transitionMap F (Nat.le_trans hij hjk) =
      transitionMap F hjk ≫ transitionMap F hij := by
  -- The unique arrow `k ⟶ i` in `ℕᵒᵖ` factors through the intermediate stage `j`.
  have hh :
      (homOfLE (Nat.le_trans hij hjk)).op = (homOfLE hjk).op ≫ (homOfLE hij).op := by
    subsingleton
  simpa [SequentialInverseSystem.transitionMap, Functor.map_comp] using congrArg F.map hh

/-- Helper for Lemma 20.36.1: the long transition from `𝒢[f^(n + 1)]` to `𝒢[f]` is
multiplication by `f^n` after forgetting to `𝒢`. -/
theorem globalSectionPowerKernelLongTransition_comp_ι
    (f : ΓX) (𝒢 : ModX) (n : ℕ) :
    transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le n) ≫
      kernel.ι (globalSectionMulPow f 𝒢 1) =
        kernel.ι (globalSectionMulPow f 𝒢 (n + 1)) ≫
          globalSectionMulPow f 𝒢 n := by
  induction n with
  | zero =>
      -- Proof comment: the zero-stage transition is the identity, so both sides are the kernel
      -- inclusion of `𝒢[f]`.
      change kernel.ι (globalSectionMulPow f 𝒢 1) =
        kernel.ι (globalSectionMulPow f 𝒢 1) ≫ globalSectionMul (f ^ 0) 𝒢
      rw [pow_zero, globalSectionMul_one]
      simp
  | succ n ih =>
      -- Proof comment: factor the long transition through the immediate predecessor stage and
      -- then rewrite the successor transition by its kernel-lift formula.
      calc
        transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (n + 1)) ≫
            kernel.ι (globalSectionMulPow f 𝒢 1)
            =
          transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.le_succ n) ≫
            (transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le n) ≫
              kernel.ι (globalSectionMulPow f 𝒢 1)) := by
                rw [sequentialInverseSystem_transitionMap_comp
                  (F := globalSectionPowerKernelTower f 𝒢)
                  (Nat.zero_le n) (Nat.le_succ n)]
                simp [Category.assoc]
        _ =
          transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.le_succ n) ≫
            (kernel.ι (globalSectionMulPow f 𝒢 (n + 1)) ≫
              globalSectionMulPow f 𝒢 n) := by
                simpa using
                  congrArg
                    (fun t ↦
                      transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.le_succ n) ≫ t)
                    ih
        _ =
          (transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.le_succ n) ≫
              kernel.ι (globalSectionMulPow f 𝒢 (n + 1))) ≫
            globalSectionMulPow f 𝒢 n := by
                simp [Category.assoc]
        _ =
          (kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫ globalSectionMul f 𝒢) ≫
            globalSectionMulPow f 𝒢 n := by
                simp [globalSectionPowerKernelTower, SequentialInverseSystem.transitionMap,
                  globalSectionPowerKernelTransition, Category.assoc,
                  Functor.ofOpSequence_map_homOfLE_succ]
        _ = kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫
            globalSectionMulPow f 𝒢 (n + 1) := by
              simpa [Category.assoc] using
                congrArg
                  (fun k ↦ kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫ k)
                    (globalSectionMul_comp_pow f 𝒢 n)

/-- Helper for Lemma 20.36.1: the canonical inclusion `𝒢[f] ⟶ 𝒢[f^(n + 2)]` is killed by the
successor transition `𝒢[f^(n + 2)] ⟶ 𝒢[f^(n + 1)]`. -/
theorem globalSectionPowerKernelInclusion_transition_zero
    (f : ΓX) (𝒢 : ModX) (n : ℕ) :
    globalSectionPowerKernelInclusion f 𝒢 n ≫
      globalSectionPowerKernelTransition f 𝒢 n = 0 := by
  -- Compare after forgetting to `𝒢`; the composite becomes multiplication by `f` on `𝒢[f]`.
  have hker :
      kernel.ι (globalSectionMulPow f 𝒢 1) ≫ globalSectionMul f 𝒢 = 0 := by
    have hpow1 : globalSectionMulPow f 𝒢 1 = globalSectionMul f 𝒢 := by
      ext U s
      change ((globalSectionsToOpenMap X U.unop).hom (f ^ 1)) • s =
        ((globalSectionsToOpenMap X U.unop).hom f) • s
      rw [pow_one]
    rw [← hpow1]
    exact kernel.condition (globalSectionMulPow f 𝒢 1)
  refine (cancel_mono (kernel.ι (globalSectionMulPow f 𝒢 (n + 1)))).1 ?_
  calc
    globalSectionPowerKernelInclusion f 𝒢 n ≫
        globalSectionPowerKernelTransition f 𝒢 n ≫
          kernel.ι (globalSectionMulPow f 𝒢 (n + 1))
        =
      globalSectionPowerKernelInclusion f 𝒢 n ≫
        kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫
          globalSectionMul f 𝒢 := by
            simp [globalSectionPowerKernelTransition]
    _ = kernel.ι (globalSectionMulPow f 𝒢 1) ≫ globalSectionMul f 𝒢 := by
          simpa [Category.assoc] using
            congrArg (fun t ↦ t ≫ globalSectionMul f 𝒢)
              (globalSectionPowerKernelInclusion_comp_ι f 𝒢 n)
    _ = 0 := hker
    _ = 0 ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 1)) := by simp

/-- Helper for Lemma 20.36.1: if `𝒢` is `f`-divisible, then the successor transition
`𝒢[f^(n + 2)] ⟶ 𝒢[f^(n + 1)]` is an epimorphism. -/
theorem globalSectionPowerKernelTransition_epi
    (f : ΓX) (𝒢 : ModX) [Epi (globalSectionMul f 𝒢)] (n : ℕ) :
    Epi (globalSectionPowerKernelTransition f 𝒢 n) := by
  let Ssucc : ShortComplex ModX :=
    ShortComplex.mk
      (kernel.ι (globalSectionMulPow f 𝒢 (n + 2)))
      (globalSectionMulPow f 𝒢 (n + 2))
      (kernel.condition _)
  let Sprev : ShortComplex ModX :=
    ShortComplex.mk
      (kernel.ι (globalSectionMulPow f 𝒢 (n + 1)))
      (globalSectionMulPow f 𝒢 (n + 1))
      (kernel.condition _)
  let φ : Ssucc ⟶ Sprev :=
    ShortComplex.Hom.mk
      (globalSectionPowerKernelTransition f 𝒢 n)
      (globalSectionMul f 𝒢)
      (𝟙 𝒢)
      (by
        -- Proof comment: the left square is the defining property of the successor kernel lift.
        simp [Ssucc, Sprev, globalSectionPowerKernelTransition])
      (by
        -- Proof comment: the right square is the factorization `f^(n+2) = f ≫ f^(n+1)`.
        simpa [Ssucc, Sprev] using globalSectionMul_comp_pow f 𝒢 (n + 1))
  have hExact : Ssucc.Exact := by
    -- Proof comment: the canonical kernel row is exact by the universal property of the kernel.
    exact ShortComplex.exact_of_f_is_kernel Ssucc (kernelIsKernel _)
  have hMono : Mono Sprev.f := by
    simpa [Sprev] using (inferInstance : Mono (kernel.ι (globalSectionMulPow f 𝒢 (n + 1))))
  have hEpiMiddle : Epi φ.τ₂ := by
    simpa [φ]
  have hMonoRight : Mono φ.τ₃ := by
    infer_instance
  simpa [φ] using
    ShortComplex.epi_of_mono_of_epi_of_mono φ hExact hMono hEpiMiddle hMonoRight

/-- Helper for Lemma 20.36.1: the canonical kernel tower of an `f`-divisible module satisfies the
zero-indexed power rows used to transport condition `(3)` to condition `(2)`. -/
theorem globalSectionPowerKernelTower_powerRow
    (f : ΓX) (𝒢 : ModX) [Epi (globalSectionMul f 𝒢)] (n : ℕ) :
    let π := globalSectionPowerKernelTransition f 𝒢 n
    let σ := transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (n + 1))
    ∃ (ι : globalSectionPowerKernelStage f 𝒢 0 ⟶
            globalSectionPowerKernelStage f 𝒢 (n + 1)) (hιπ : ι ≫ π = 0),
      (ShortComplex.mk ι π hιπ).ShortExact ∧
        σ ≫ ι =
          globalSectionMulPow f (globalSectionPowerKernelStage f 𝒢 (n + 1)) (n + 1) := by
  dsimp
  refine ⟨globalSectionPowerKernelInclusion f 𝒢 n,
    globalSectionPowerKernelInclusion_transition_zero f 𝒢 n, ?_, ?_⟩
  · -- Proof comment: assemble short exactness from the kernel universal property and the epi step.
    have hKernel :
        IsLimit (KernelFork.ofι (globalSectionPowerKernelInclusion f 𝒢 n)
          (globalSectionPowerKernelInclusion_transition_zero f 𝒢 n)) := by
      refine KernelFork.IsLimit.ofι'
        (globalSectionPowerKernelInclusion f 𝒢 n)
        (globalSectionPowerKernelInclusion_transition_zero f 𝒢 n) ?_
      intro W t ht
      -- Proof comment: after forgetting to `𝒢`, the vanishing against the successor transition
      -- says that the ambient composite is killed by multiplication by `f`.
      have hstep :
          globalSectionPowerKernelTransition f 𝒢 n ≫
              kernel.ι (globalSectionMulPow f 𝒢 (n + 1))
            =
          kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫ globalSectionMul f 𝒢 := by
        simp [globalSectionPowerKernelTransition]
      have ht_mul_zero :
          t ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫ globalSectionMul f 𝒢 = 0 := by
        calc
          t ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫ globalSectionMul f 𝒢
              =
            t ≫ globalSectionPowerKernelTransition f 𝒢 n ≫
              kernel.ι (globalSectionMulPow f 𝒢 (n + 1)) := by
                rw [← hstep]
          _ = 0 := by
                simpa [Category.assoc] using
                  congrArg
                    (fun k ↦ k ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 1)))
                    ht
      have hpow1 :
          globalSectionMulPow f 𝒢 1 = globalSectionMul f 𝒢 := by
        ext U s
        change ((globalSectionsToOpenMap X U.unop).hom (f ^ 1)) • s =
          ((globalSectionsToOpenMap X U.unop).hom f) • s
        rw [pow_one]
      let s : W ⟶ globalSectionPowerKernelStage f 𝒢 0 :=
        kernel.lift (globalSectionMulPow f 𝒢 1)
          (t ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 2)))
          (by
            rw [hpow1]
            simpa [Category.assoc] using ht_mul_zero)
      refine ⟨s, ?_⟩
      -- Proof comment: both lifts agree after embedding into the ambient module `𝒢`.
      refine (cancel_mono (kernel.ι (globalSectionMulPow f 𝒢 (n + 2)))).1 ?_
      calc
        s ≫ globalSectionPowerKernelInclusion f 𝒢 n ≫
            kernel.ι (globalSectionMulPow f 𝒢 (n + 2))
            =
          s ≫ kernel.ι (globalSectionMulPow f 𝒢 1) := by
              rw [globalSectionPowerKernelInclusion_comp_ι]
        _ = t ≫ kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) := by
              simp [s]
    refine ShortComplex.ShortExact.mk' ?_ ?_ ?_
    · exact ShortComplex.exact_of_f_is_kernel _ hKernel
    · infer_instance
    · exact globalSectionPowerKernelTransition_epi f 𝒢 n
  · -- Proof comment: compare both endomorphisms after forgetting to the ambient module `𝒢`.
    refine (cancel_mono (kernel.ι (globalSectionMulPow f 𝒢 (n + 2)))).1 ?_
    calc
      transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (n + 1)) ≫
          globalSectionPowerKernelInclusion f 𝒢 n ≫
            kernel.ι (globalSectionMulPow f 𝒢 (n + 2))
          =
        transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (n + 1)) ≫
          kernel.ι (globalSectionMulPow f 𝒢 1) := by
            simpa [Category.assoc] using
              congrArg
                (fun t ↦ transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (n + 1)) ≫ t)
                (globalSectionPowerKernelInclusion_comp_ι f 𝒢 n)
      _ = kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) ≫
          globalSectionMulPow f 𝒢 (n + 1) := by
            simpa using globalSectionPowerKernelLongTransition_comp_ι f 𝒢 (n + 1)
      _ = globalSectionMulPow f (globalSectionPowerKernelStage f 𝒢 (n + 1)) (n + 1) ≫
          kernel.ι (globalSectionMulPow f 𝒢 (n + 2)) := by
            simpa using
              (globalSectionMulPow_natural f
                (kernel.ι (globalSectionMulPow f 𝒢 (n + 2))) (n + 1)).symm

/-- Helper for Lemma 20.36.1: a shift isomorphism to the canonical kernel tower transports the
fixed-stage power row back to the source inverse system. -/
theorem powerRow_of_shiftIso_globalSectionPowerKernelTower
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) (𝒢 : ModX)
    [Epi (globalSectionMul f 𝒢)]
    (e : shift ℱ 1 ≅ globalSectionPowerKernelTower f 𝒢)
    (n : ℕ) (hn : 1 ≤ n) :
    let π := stepMap ℱ n
    let σ := transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n))
    ∃ (ι : ℱ.obj (op 1) ⟶ ℱ.obj (op (n + 1))) (hιπ : ι ≫ π = 0),
      (ShortComplex.mk ι π hιπ).ShortExact ∧
        σ ≫ ι =
          globalSectionMulPow f (ℱ.obj (op (n + 1))) n := by
  -- Route correction: the right proof route is still the fixed-stage transport of
  -- `globalSectionPowerKernelTower_powerRow f 𝒢 (n - 1)`.
  let m := n - 1
  have hm : m + 1 = n := by
    -- Proof comment: the positivity hypothesis rewrites the source index `n` as `m + 1`.
    dsimp [m]
    exact Nat.succ_pred_eq_of_pos hn
  obtain ⟨ι0, hι0π0, hshort0, hσ0ι0⟩ := globalSectionPowerKernelTower_powerRow f 𝒢 m
  let e0 := e.app (op 0)
  let em := e.app (op m)
  let em1 := e.app (op (m + 1))
  let ι : (shift ℱ 1).obj (op 0) ⟶ (shift ℱ 1).obj (op (m + 1)) :=
    e0.hom ≫ ι0 ≫ em1.inv
  have hstep :
      globalSectionPowerKernelTransition f 𝒢 m ≫ em.inv =
        em1.inv ≫ stepMap (shift ℱ 1) m := by
    -- Proof comment: naturality of `e.inv` identifies the successor map in the shifted source
    -- with the canonical kernel-tower transition.
    simpa [em, em1, SequentialInverseSystem.stepMap, SequentialInverseSystem.transitionMap,
      Functor.ofOpSequence_map_homOfLE_succ] using
      e.inv.naturality ((homOfLE (Nat.le_succ m)).op)
  have hιπ :
      ι ≫ stepMap (shift ℱ 1) m = 0 := by
    -- Proof comment: after rewriting the shifted successor map via `hstep`, the transported
    -- inclusion factors through the canonical zero relation `ι0 ≫ π0 = 0`.
    dsimp [ι]
    calc
      e0.hom ≫ ι0 ≫ em1.inv ≫ stepMap (shift ℱ 1) m
          = e0.hom ≫ ι0 ≫ (globalSectionPowerKernelTransition f 𝒢 m ≫ em.inv) := by
              rw [hstep]
              simp [Category.assoc]
      _ = e0.hom ≫ (ι0 ≫ globalSectionPowerKernelTransition f 𝒢 m) ≫ em.inv := by
              simp [Category.assoc]
      _ = 0 := by
              simp [hι0π0, Category.assoc]
  let S : ShortComplex ModX :=
    ShortComplex.mk ι (stepMap (shift ℱ 1) m) hιπ
  let T : ShortComplex ModX :=
    ShortComplex.mk ι0 (globalSectionPowerKernelTransition f 𝒢 m) hι0π0
  let eRow : T ≅ S :=
    ShortComplex.isoMk e0.symm em1.symm em.symm
      (by
        -- Proof comment: the transported inclusion is defined by conjugating `ι0`.
        dsimp [S, T, ι]
        simp [Category.assoc])
      (by
        -- Proof comment: the right square is exactly the successor-map transport `hstep`.
        simpa [S, T] using hstep)
  have hshortS : S.ShortExact := by
    -- Proof comment: short exactness survives transport across the row isomorphism `eRow`.
    exact ShortComplex.shortExact_of_iso eRow hshort0
  have hpowNat :
      globalSectionMulPow f ((shift ℱ 1).obj (op (m + 1))) (m + 1) ≫ em1.hom =
        em1.hom ≫ globalSectionMulPow f (globalSectionPowerKernelStage f 𝒢 (m + 1)) (m + 1) := by
    -- Proof comment: multiplication by powers of `f` commutes with the component isomorphism.
    exact globalSectionMulPow_natural f em1.hom (m + 1)
  have hshiftEq :
      transitionMap (shift ℱ 1) (Nat.zero_le (m + 1)) ≫ ι =
        globalSectionMulPow f ((shift ℱ 1).obj (op (m + 1))) (m + 1) := by
    -- Proof comment: transport the end equation of the canonical power row along the two
    -- comparison isomorphisms and then rewrite the power endomorphism by naturality.
    dsimp [ι]
    calc
      transitionMap (shift ℱ 1) (Nat.zero_le (m + 1)) ≫ e0.hom ≫ ι0 ≫ em1.inv
          =
        em1.hom ≫ transitionMap (globalSectionPowerKernelTower f 𝒢) (Nat.zero_le (m + 1)) ≫
          ι0 ≫ em1.inv := by
            simpa [e0, em1, SequentialInverseSystem.transitionMap,
              Functor.ofOpSequence_map_homOfLE_succ, Category.assoc] using
              congrArg (fun k ↦ k ≫ ι0 ≫ em1.inv)
                (e.hom.naturality ((homOfLE (Nat.zero_le (m + 1))).op))
      _ = em1.hom ≫ globalSectionMulPow f (globalSectionPowerKernelStage f 𝒢 (m + 1)) (m + 1) ≫
          em1.inv := by
            rw [hσ0ι0]
            simp [Category.assoc]
      _ = globalSectionMulPow f ((shift ℱ 1).obj (op (m + 1))) (m + 1) := by
            rw [← Category.assoc, hpowNat]
            simp [Category.assoc]
  refine ⟨?_, ?_, ?_, ?_⟩
  · -- Proof comment: rewrite the shifted-stage inclusion back to the source indexing convention.
    simpa [SequentialInverseSystem.shift_obj, hm, Nat.add_comm] using ι
  · -- Proof comment: the zero relation on the shifted row becomes the desired source relation.
    simpa [SequentialInverseSystem.shift_obj, SequentialInverseSystem.stepMap,
      SequentialInverseSystem.shift_transitionMap, SequentialInverseSystem.transitionMap, hm,
      Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using hιπ
  · -- Proof comment: the transported shifted row is the required short exact source row.
    simpa [S, ι, SequentialInverseSystem.shift_obj, SequentialInverseSystem.stepMap,
      SequentialInverseSystem.shift_transitionMap, SequentialInverseSystem.transitionMap, hm,
      Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using hshortS
  · -- Proof comment: the shifted end equation is exactly the source `f^n` equality after `hm`.
    simpa [SequentialInverseSystem.shift_obj, SequentialInverseSystem.transitionMap, hm,
      Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using hshiftEq

/-- Helper for Lemma 20.36.1: condition `(3)` implies condition `(2)` by transporting the
canonical power rows of the kernel tower across the given shift isomorphism. -/
theorem powerShortExactCondition_of_divisibleKernelTowerCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) :
    divisibleKernelTowerCondition f ℱ →
      powerShortExactCondition f ℱ := by
  -- Proof comment: unpack the divisible witness and apply the fixed-stage transport helper at
  -- every index `n ≥ 1`.
  intro hdiv n hn
  rcases hdiv with ⟨𝒢, hdiv𝒢, ⟨e⟩⟩
  letI : Epi (globalSectionMul f 𝒢) := hdiv𝒢
  exact powerRow_of_shiftIso_globalSectionPowerKernelTower f ℱ 𝒢 e n hn

/-- Helper for Lemma 20.36.1: under condition `(2)`, the first stage `ℱ₁` is annihilated by
multiplication by `f`. -/
theorem globalSectionMul_stageOne_eq_zero_of_powerShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX)
    (hpower : powerShortExactCondition f ℱ) :
    globalSectionMul f (ℱ.obj (op 1)) = 0 := by
  let π : ℱ.obj (op 2) ⟶ ℱ.obj (op 1) := stepMap ℱ 1
  let σ : ℱ.obj (op 2) ⟶ ℱ.obj (op 1) :=
    transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le 1))
  have hrow :
      ∃ (ι : ℱ.obj (op 1) ⟶ ℱ.obj (op 2)) (hιπ : ι ≫ π = 0),
        (ShortComplex.mk ι π hιπ).ShortExact ∧
          σ ≫ ι = globalSectionMulPow f (ℱ.obj (op 2)) 1 := by
    -- Proof comment: the `n = 1` power row is exactly the first source short exact sequence.
    simpa [π, σ] using hpower 1 (by omega)
  rcases hrow with ⟨ι, hιπ, hshort, hσι⟩
  letI : Mono ι := hshort.mono_f
  have hpow1_left :
      globalSectionMulPow f (ℱ.obj (op 1)) 1 =
        globalSectionMul f (ℱ.obj (op 1)) := by
    simpa [globalSectionMulPow] using
      (show globalSectionMul (f ^ 1) (ℱ.obj (op 1)) =
          globalSectionMul f (ℱ.obj (op 1)) by
        rw [pow_one])
  have hpow1_right :
      globalSectionMulPow f (ℱ.obj (op 2)) 1 =
        globalSectionMul f (ℱ.obj (op 2)) := by
    simpa [globalSectionMulPow] using
      (show globalSectionMul (f ^ 1) (ℱ.obj (op 2)) =
          globalSectionMul f (ℱ.obj (op 2)) by
        rw [pow_one])
  have hnat :
      globalSectionMul f (ℱ.obj (op 1)) ≫ ι =
        ι ≫ globalSectionMul f (ℱ.obj (op 2)) := by
    -- Proof comment: move multiplication by `f` across the stage-one inclusion by naturality.
    rw [← hpow1_left, ← hpow1_right]
    exact globalSectionMulPow_natural f ι 1
  have hright_zero : ι ≫ globalSectionMul f (ℱ.obj (op 2)) = 0 := by
    -- Proof comment: in the first power row, the long transition is the same as the step map, so
    -- the source inclusion kills multiplication by `f` on the middle term.
    calc
      ι ≫ globalSectionMul f (ℱ.obj (op 2))
          = ι ≫ (π ≫ ι) := by
              simpa [π, σ, hpow1_right, Category.assoc] using
                congrArg (fun t ↦ ι ≫ t) hσι.symm
      _ = (ι ≫ π) ≫ ι := by simp [Category.assoc]
      _ = 0 := by simp [hιπ]
  refine (cancel_mono ι).1 ?_
  calc
    globalSectionMul f (ℱ.obj (op 1)) ≫ ι
        = ι ≫ globalSectionMul f (ℱ.obj (op 2)) := hnat
    _ = 0 := hright_zero
    _ = 0 ≫ ι := by simp

/-- Helper for Lemma 20.36.1: under condition `(2)`, every transition
`ℱ_{n + 1} ⟶ ℱ₁` is an epimorphism. -/
theorem transitionToStageOne_epi_of_powerShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX)
    (hpower : powerShortExactCondition f ℱ) :
    ∀ n : ℕ, 1 ≤ n →
      Epi (transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n)))
  | 0, hn => False.elim (Nat.not_succ_le_zero 0 hn)
  | 1, _ =>
      by
        let π : ℱ.obj (op 2) ⟶ ℱ.obj (op 1) := stepMap ℱ 1
        let σ : ℱ.obj (op 2) ⟶ ℱ.obj (op 1) :=
          transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le 1))
        have hrow :
            ∃ (ι : ℱ.obj (op 1) ⟶ ℱ.obj (op 2)) (hιπ : ι ≫ π = 0),
              (ShortComplex.mk ι π hιπ).ShortExact ∧
                σ ≫ ι = globalSectionMulPow f (ℱ.obj (op 2)) 1 := by
          -- Proof comment: the first long transition is the first step map itself.
          simpa [π, σ] using hpower 1 (by omega)
        rcases hrow with ⟨_, _, hshort, _⟩
        simpa [σ, π] using hshort.epi_g
  | n + 2, _ =>
      by
        let π : ℱ.obj (op (n + 3)) ⟶ ℱ.obj (op (n + 2)) := stepMap ℱ (n + 2)
        let σ : ℱ.obj (op (n + 2)) ⟶ ℱ.obj (op 1) :=
          transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le (n + 1)))
        have hrow :
            ∃ (ι : ℱ.obj (op 1) ⟶ ℱ.obj (op (n + 3))) (hιπ : ι ≫ π = 0),
              (ShortComplex.mk ι π hιπ).ShortExact ∧
                transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le (n + 2))) ≫ ι =
                  globalSectionMulPow f (ℱ.obj (op (n + 3))) (n + 2) := by
          -- Proof comment: the `(n + 2)`nd power row provides the step epimorphism.
          simpa [π] using hpower (n + 2) (by omega)
        rcases hrow with ⟨_, _, hshort, _⟩
        letI : Epi π := hshort.epi_g
        letI :
            Epi (transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le (n + 1)))) :=
          transitionToStageOne_epi_of_powerShortExactCondition f ℱ hpower (n + 1) (by omega)
        have hcomp :
            transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le (n + 2))) = π ≫ σ := by
          -- Proof comment: the long transition from stage `n + 3` to stage `1` factors through
          -- the immediate predecessor stage `n + 2`.
          simpa [π, σ, SequentialInverseSystem.stepMap] using
            (sequentialInverseSystem_transitionMap_comp
              (F := ℱ)
              (Nat.succ_le_succ (Nat.zero_le (n + 1)))
              (Nat.le_succ (n + 2)))
        rw [hcomp]
        infer_instance

/-- Helper for Lemma 20.36.1: condition `(2)` canonically produces the candidate map
`ℱₙ ⟶ ℱ_{n + 1}` for the reverse direction `(2) → (1)`. -/
theorem stepMapFactor_of_powerShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX)
    (hpower : powerShortExactCondition f ℱ)
    (n : ℕ) (hn : 1 ≤ n) :
    let π := stepMap ℱ n
    let σ := transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n))
    ∃ ι : ℱ.obj (op n) ⟶ ℱ.obj (op (n + 1)),
      π ≫ ι = globalSectionMul f (ℱ.obj (op (n + 1))) ∧
        ι ≫ π = globalSectionMul f (ℱ.obj (op n)) ∧
        ι ≫ σ = 0 := by
  let π : ℱ.obj (op (n + 1)) ⟶ ℱ.obj (op n) := stepMap ℱ n
  let σ : ℱ.obj (op (n + 1)) ⟶ ℱ.obj (op 1) :=
    transitionMap ℱ (Nat.succ_le_succ (Nat.zero_le n))
  have hrow :
      ∃ (ι₁ : ℱ.obj (op 1) ⟶ ℱ.obj (op (n + 1))) (hι₁π : ι₁ ≫ π = 0),
        (ShortComplex.mk ι₁ π hι₁π).ShortExact ∧
          σ ≫ ι₁ = globalSectionMulPow f (ℱ.obj (op (n + 1))) n := by
    -- Proof comment: unpack the given `n`th power row in the source indexing.
    simpa [π, σ] using hpower n hn
  rcases hrow with ⟨ι₁, hι₁π, hshort, hσι₁⟩
  letI : Epi π := hshort.epi_g
  have hstageOneZero :
      globalSectionMul f (ℱ.obj (op 1)) = 0 :=
    globalSectionMul_stageOne_eq_zero_of_powerShortExactCondition f ℱ hpower
  have hι₁mul_zero :
      ι₁ ≫ globalSectionMul f (ℱ.obj (op (n + 1))) = 0 := by
    -- Proof comment: the left object in the power row is `ℱ₁`, which is already annihilated
    -- by `f`, so the row inclusion kills multiplication by `f` on the middle term.
    have hnat :
        globalSectionMul f (ℱ.obj (op 1)) ≫ ι₁ =
          ι₁ ≫ globalSectionMul f (ℱ.obj (op (n + 1))) := by
      have hpow1_left :
          globalSectionMulPow f (ℱ.obj (op 1)) 1 =
            globalSectionMul f (ℱ.obj (op 1)) := by
        simpa [globalSectionMulPow] using
          (show globalSectionMul (f ^ 1) (ℱ.obj (op 1)) =
              globalSectionMul f (ℱ.obj (op 1)) by
            rw [pow_one])
      have hpow1_right :
          globalSectionMulPow f (ℱ.obj (op (n + 1))) 1 =
            globalSectionMul f (ℱ.obj (op (n + 1))) := by
        simpa [globalSectionMulPow] using
          (show globalSectionMul (f ^ 1) (ℱ.obj (op (n + 1))) =
              globalSectionMul f (ℱ.obj (op (n + 1))) by
            rw [pow_one])
      rw [← hpow1_left, ← hpow1_right]
      exact globalSectionMulPow_natural f ι₁ 1
    calc
      ι₁ ≫ globalSectionMul f (ℱ.obj (op (n + 1)))
          = globalSectionMul f (ℱ.obj (op 1)) ≫ ι₁ := hnat.symm
      _ = 0 := by simp [hstageOneZero]
  let ι : ℱ.obj (op n) ⟶ ℱ.obj (op (n + 1)) :=
    hshort.gIsCokernel.desc
      (CokernelCofork.ofπ (globalSectionMul f (ℱ.obj (op (n + 1)))) hι₁mul_zero)
  have hπι :
      π ≫ ι = globalSectionMul f (ℱ.obj (op (n + 1))) := by
    -- Proof comment: `ι` is the unique factor of multiplication by `f` through the power-row
    -- cokernel `π`.
    simpa [ι, π] using
      hshort.gIsCokernel.fac
        (CokernelCofork.ofπ (globalSectionMul f (ℱ.obj (op (n + 1)))) hι₁mul_zero)
        WalkingParallelPair.one
  have hιπ :
      ι ≫ π = globalSectionMul f (ℱ.obj (op n)) := by
    -- Proof comment: after postcomposing with the epi map `π`, both sides agree by naturality of
    -- multiplication by `f`.
    apply (cancel_epi π).1
    calc
      π ≫ ι ≫ π
          = globalSectionMul f (ℱ.obj (op (n + 1))) ≫ π := by
              simpa [Category.assoc] using congrArg (fun t ↦ t ≫ π) hπι
      _ = π ≫ globalSectionMul f (ℱ.obj (op n)) := by
            have hpow1_left :
                globalSectionMulPow f (ℱ.obj (op (n + 1))) 1 =
                  globalSectionMul f (ℱ.obj (op (n + 1))) := by
              simpa [globalSectionMulPow] using
                (show globalSectionMul (f ^ 1) (ℱ.obj (op (n + 1))) =
                    globalSectionMul f (ℱ.obj (op (n + 1))) by
                  rw [pow_one])
            have hpow1_right :
                globalSectionMulPow f (ℱ.obj (op n)) 1 =
                  globalSectionMul f (ℱ.obj (op n)) := by
              simpa [globalSectionMulPow] using
                (show globalSectionMul (f ^ 1) (ℱ.obj (op n)) =
                    globalSectionMul f (ℱ.obj (op n)) by
                  rw [pow_one])
            rw [← hpow1_left, ← hpow1_right]
            exact globalSectionMulPow_natural f π 1
  have hισ :
      ι ≫ σ = 0 := by
    -- Proof comment: the long transition to `ℱ₁` kills multiplication by `f`, because the
    -- target stage `ℱ₁` is already annihilated by `f`.
    apply (cancel_epi π).1
    calc
      π ≫ ι ≫ σ
          = globalSectionMul f (ℱ.obj (op (n + 1))) ≫ σ := by
              simpa [Category.assoc] using congrArg (fun t ↦ t ≫ σ) hπι
      _ = σ ≫ globalSectionMul f (ℱ.obj (op 1)) := by
            have hpow1_left :
                globalSectionMulPow f (ℱ.obj (op (n + 1))) 1 =
                  globalSectionMul f (ℱ.obj (op (n + 1))) := by
              simpa [globalSectionMulPow] using
                (show globalSectionMul (f ^ 1) (ℱ.obj (op (n + 1))) =
                    globalSectionMul f (ℱ.obj (op (n + 1))) by
                  rw [pow_one])
            have hpow1_right :
                globalSectionMulPow f (ℱ.obj (op 1)) 1 =
                  globalSectionMul f (ℱ.obj (op 1)) := by
              simpa [globalSectionMulPow] using
                (show globalSectionMul (f ^ 1) (ℱ.obj (op 1)) =
                    globalSectionMul f (ℱ.obj (op 1)) by
                  rw [pow_one])
            rw [← hpow1_left, ← hpow1_right]
            exact globalSectionMulPow_natural f σ 1
      _ = 0 := by simp [hstageOneZero]
      _ = π ≫ 0 := by simp
  refine ⟨ι, hπι, hιπ, hισ⟩

-- Proof sketch: for `3 → 2`, use the inclusions `𝒢[f] ⊆ 𝒢[f^(n + 1)]`
-- inside an `f`-divisible module and identify the quotient with `𝒢[f^n]`; for the reverse
-- direction, first recover condition `(1)` from the power rows and then apply the source-faithful
-- colimit construction `(1) → (3)`.
/-- Lemma 20.36.1 (2): the inverse system comes from the kernels `𝒢[f^n]` of an
`f`-divisible module if and only if the powers `f^n` factor through
`ℱ_{n + 1} ⟶ ℱ_1` to yield short exact sequences
`0 ⟶ ℱ_1 ⟶ ℱ_{n + 1} ⟶ ℱ_n ⟶ 0`. -/
@[stacks 0H39]
theorem divisibleKernelTowerCondition_iff_powerShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) :
    divisibleKernelTowerCondition f ℱ ↔
      powerShortExactCondition f ℱ := by
  constructor
  · -- The canonical kernel tower of an `f`-divisible module already satisfies condition `(2)`.
    exact powerShortExactCondition_of_divisibleKernelTowerCondition f ℱ
  · -- Route correction: do not retry a direct `(2) → (3)` colimit from power rows.
    -- Proof comment: the reverse direction should now pass through the stagewise factorization
    -- helper `stepMapFactor_of_powerShortExactCondition`; the remaining blocker is upgrading that
    -- factorization to a short exact row and then feeding the established colimit route `(1) → (3)`.
    -- TODO: prove `(2) → (1)` by identifying the exact kernel/cokernel interface of the
    -- candidate returned by `stepMapFactor_of_powerShortExactCondition`, and then compose with
    -- the source-faithful colimit construction `(1) → (3)`.
    intro hpower
    sorry

-- Proof sketch: in one direction, compose the factorization through `ℱ_{n + 1} ⟶
-- ℱ_1` with the standard exact sequence from condition (2) to recover the factorization
-- through `ℱ_{n + 1} ⟶ ℱ_n`; in the other direction, iterate the stepwise
-- factorization from condition (1) to identify the factorization of `f^n`.
/-- Lemma 20.36.1 (3): the power-factorization short exact sequences from condition (2) are
equivalent to the stepwise factorization short exact sequences from condition (1). -/
@[stacks 0H39]
theorem powerShortExactCondition_iff_stepShortExactCondition
    (f : ΓX) (ℱ : SequentialInverseSystem ModX) :
    powerShortExactCondition f ℱ ↔
      stepShortExactCondition f ℱ := by
  -- Proof comment: the remaining missing piece is not the factorization itself; it is the exact
  -- identification showing that the canonical reverse-row map from
  -- `stepMapFactor_of_powerShortExactCondition` is mono and has cokernel `ℱ₁`.
  -- TODO: package the factorization from `stepMapFactor_of_powerShortExactCondition` into a
  -- source-facing short exact row, then use the established `(1) → (3) → (2)` route for the
  -- other direction.
  sorry

end AlgebraicGeometry.RingedSpace
