import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open MeasureTheory Set Filter intervalIntegral
open scoped Pointwise Topology

/-- Exercise 13.1.7: for a locally integrable function on `ℝ^d`, the averages over the dilates
`x + r C` of an open bounded convex set `C` containing `0` converge almost everywhere to the value
`f x` as `r ↓ 0`. -/
-- Proof sketch: this is the source-facing specialization of the owner theorem
-- `VitaliFamily.ae_tendsto_average` to the Vitali family generated by the translated dilates
-- `{x} + r • C`, as suggested by Exercise 13.1.6.
theorem ae_tendsto_average_over_convex_dilates {d : ℕ}
    {f : (Fin d → ℝ) → ℝ} (hf : LocallyIntegrable f volume)
    {C : Set (Fin d → ℝ)} (hC_open : IsOpen C) (hC_convex : Convex ℝ C)
    (hC_bounded : Bornology.IsBounded C) (hC_zero : (0 : Fin d → ℝ) ∈ C) :
    ∀ᵐ x ∂volume,
      Tendsto
        (fun r : ℝ ↦ ⨍ y in ({x} + r • C), f y ∂volume)
        (𝓝[>] (0 : ℝ)) (𝓝 (f x)) := sorry

/-- The one-dimensional primitive `x ↦ ∫ t in 0..x, f t` has derivative `f x` almost everywhere
for locally integrable `f`. -/
-- Proof sketch: apply `LocallyIntegrable.ae_hasDerivAt_integral` to `hf` with
-- base point `c = 0`, then pass from `HasDerivAt` to `deriv`.
theorem ae_deriv_intervalIntegral_from_zero_eq {f : ℝ → ℝ} (hf : LocallyIntegrable f volume) :
    ∀ᵐ x ∂volume, deriv (fun x ↦ ∫ t in (0 : ℝ)..x, f t) x = f x := by
  filter_upwards [LocallyIntegrable.ae_hasDerivAt_integral hf] with x hx
  simpa using (hx 0).deriv
