import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open scoped Pointwise
open scoped Monoid.Coprod
open Monoid.Coprod

set_option autoImplicit false

section

variable {G : Type u} {Ω : Type v} [Group G] [MulAction G Ω]

/-!
Primary domain: group actions, subgroup generation, and the ping-pong free-product alternative.

Layer triage:
- `source-facing`: two subgroups `G₁` and `G₂` of a group `G` acting on `Ω`, together with two
  disjoint nonempty subsets `Ω₁` and `Ω₂` satisfying the alternating ping-pong containment
  hypotheses from the textbook.
- `core/canonical`: `Subgroup G` is the owner abstraction for the subgroup factors and their join
  `G₁ ⊔ G₂`, the pointwise action `g • Ωᵢ` is the owner API for the set-containment hypotheses,
  `Monoid.Coprod` with notation `G₁ ∗ G₂` is mathlib's owner for the free product of the two
  subgroup types, and `DihedralGroup n` is mathlib's owner for the finite and infinite dihedral
  groups.
- `bridge/view`: the canonical map from the free product `G₁ ∗ G₂` to the generated subgroup is
  the coproduct lift of the two subgroup inclusions `G₁ ≤ G₁ ⊔ G₂` and `G₂ ≤ G₁ ⊔ G₂`.

Domain sampling:
1. `[MulAction G Ω]` is the intrinsic owner of the action used in the ping-pong hypotheses, so
   this proposition should live over `Subgroup G` rather than the special model
   `Subgroup (Equiv.Perm Ω)`.
2. `Subgroup` and the lattice operation `⊔` are the canonical owners for the subgroup generated by
   two given subgroups.
3. The pointwise action `g • Ωᵢ` on subsets is the canonical owner for the ping-pong
   set-containment hypotheses.
4. `Monoid.Coprod` with notation `G₁ ∗ G₂` is mathlib's owner for the free product of two groups.
5. `DihedralGroup n` is the canonical family containing both finite and infinite dihedral groups.
6. Proposition `3_12_5` in this chapter already uses the same intrinsic action-theoretic owner
   level for two-set ping-pong statements.

Primitive vs. derived:
- primitive public data: the two subgroup factors, the action on `Ω`, and the ping-pong subsets
  with their disjointness, nonemptiness, and alternating image-containment hypotheses;
- derived API: the resulting free-product equivalence `G₁ ∗ G₂ ≃* ↥(G₁ ⊔ G₂)` and the conclusion
  that the generated subgroup is either the free product of the two factors or falls into the
  exceptional order-`2` dihedral case.
-/

variable (G₁ G₂ : Subgroup G)

variable
    (Ω₁ Ω₂ : Set Ω)
    (hdisjoint : Disjoint Ω₁ Ω₂)
    (hΩ₁ : Ω₁.Nonempty)
    (hΩ₂ : Ω₂.Nonempty)
    (h₁ : ∀ g : G₁, g ≠ 1 → (g : G) • Ω₁ ⊆ Ω₂)
    (h₂ : ∀ g : G₂, g ≠ 1 → (g : G) • Ω₂ ⊆ Ω₁)

include hdisjoint hΩ₁ hΩ₂ h₁ h₂

/-- The canonical comparison map from the free product of `G₁` and `G₂` to the subgroup they
generate. -/
private def freeProductToSup : G₁ ∗ G₂ →* ↥(G₁ ⊔ G₂) :=
  lift (Subgroup.inclusion le_sup_left) (Subgroup.inclusion le_sup_right)

/-- If the two-subgroup ping-pong hypotheses hold and the exceptional order-`2`/order-`2` case is
excluded, then the canonical map from `G₁ ∗ G₂` to `G₁ ⊔ G₂` is bijective. -/
private theorem freeProductToSup_bijective_of_two_subgroup_pingPong
    (hnot_dihedral : ¬ (Nat.card G₁ = 2 ∧ Nat.card G₂ = 2)) :
    Function.Bijective (freeProductToSup G₁ G₂) := sorry

/-- The canonical free-product equivalence induced by the two-subgroup ping-pong hypotheses away
from the exceptional order-`2`/order-`2` branch. -/
noncomputable def freeProductSupEquivOfTwoSubgroupPingPong
    (hnot_dihedral : ¬ (Nat.card G₁ = 2 ∧ Nat.card G₂ = 2)) :
    G₁ ∗ G₂ ≃* ↥(G₁ ⊔ G₂) :=
  MulEquiv.ofBijective
    (freeProductToSup G₁ G₂)
    (freeProductToSup_bijective_of_two_subgroup_pingPong
      G₁ G₂ Ω₁ Ω₂ hdisjoint hΩ₁ hΩ₂ h₁ h₂ hnot_dihedral)

@[simp] theorem freeProductSupEquivOfTwoSubgroupPingPong_inl
    (hnot_dihedral : ¬ (Nat.card G₁ = 2 ∧ Nat.card G₂ = 2)) (g : G₁) :
    freeProductSupEquivOfTwoSubgroupPingPong
        G₁ G₂ Ω₁ Ω₂ hdisjoint hΩ₁ hΩ₂ h₁ h₂ hnot_dihedral
        (inl g) =
      Subgroup.inclusion le_sup_left g := by
  simp [freeProductSupEquivOfTwoSubgroupPingPong, freeProductToSup,
    MulEquiv.ofBijective_apply]

@[simp] theorem freeProductSupEquivOfTwoSubgroupPingPong_inr
    (hnot_dihedral : ¬ (Nat.card G₁ = 2 ∧ Nat.card G₂ = 2)) (g : G₂) :
    freeProductSupEquivOfTwoSubgroupPingPong
        G₁ G₂ Ω₁ Ω₂ hdisjoint hΩ₁ hΩ₂ h₁ h₂ hnot_dihedral
        (inr g) =
      Subgroup.inclusion le_sup_right g := by
  simp [freeProductSupEquivOfTwoSubgroupPingPong, freeProductToSup,
    MulEquiv.ofBijective_apply]

-- Proof sketch: this is the two-subgroup ping-pong argument. If one factor has more than two
-- elements, the containment hypotheses sharpen to strict disjointness of the relevant translates,
-- and a reduced alternating word moves `Ω₁` strictly inside itself, so the generated subgroup is
-- canonically identified with the free product `G₁ ∗ G₂`. The only remaining case is when both
-- factors have order `2`, where
-- every additional relation is of the form `(ab)^n = 1`; this identifies the generated subgroup
-- with a finite dihedral group, and the relation-free case gives the infinite dihedral group.
/-- Proposition 3-12-3: if two subgroup factors acting on `Ω` satisfy the alternating ping-pong
hypotheses on disjoint nonempty subsets `Ω₁` and `Ω₂`, then the subgroup they generate is either
their free product, or both factors have order `2` and the generated subgroup is dihedral. -/
theorem freeProduct_or_dihedral_of_two_subgroup_pingPong
    :
    Nonempty (G₁ ∗ G₂ ≃* ↥(G₁ ⊔ G₂)) ∨
      Nat.card G₁ = 2 ∧ Nat.card G₂ = 2 ∧
        ∃ n : ℕ, Nonempty (DihedralGroup n ≃* ↥(G₁ ⊔ G₂)) := by
  by_cases hnot_dihedral : ¬ (Nat.card G₁ = 2 ∧ Nat.card G₂ = 2)
  · exact .inl
      ⟨freeProductSupEquivOfTwoSubgroupPingPong
        G₁ G₂ Ω₁ Ω₂ hdisjoint hΩ₁ hΩ₂ h₁ h₂ hnot_dihedral⟩
  · sorry

end
