import Mathlib
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import CombinatorialGroupTheory_Magnus_2004.CombinatorialGroupTheory.Items.Chap01.Definition_1_1_1

-- Declarations for this item will be appended below by the statement pipeline.

open scoped MatrixGroups

section

-- Layer triage:
-- `source-facing`: the two explicit integral matrices
-- `A = !![1, 2; 0, 1]` and `B = !![1, 0; 2, 1]`.
-- `core/canonical`: the subgroup owner `Subgroup (SL(2, ℤ))` together with the subset-style
-- basis predicate `IsFreeGroupBasis` on the corresponding generating subset of the closure.
-- `bridge/view`: the explicit matrices are packaged as elements of `SL(2, ℤ)` via their
-- determinant-one certificates, but the main statement remains about the concrete matrices named
-- in the source.
-- Domain sampling:
-- 1. `SL(2, ℤ)` from `Matrix.SpecialLinearGroup` is the clean matrix-group owner for these
--    determinant-one matrices.
-- 2. `Subgroup.closure` is the canonical owner for the subgroup generated by a set of group
--    elements.
-- 3. `IsFreeGroupBasis` is the chapter's canonical source-facing owner for “these displayed
--    elements form a free basis of the subgroup they generate,” while `FreeGroupBasis` is derived
--    from it only when an indexed basis is needed.
-- Primitive vs. derived:
-- the primitive data are the two explicit matrices `A` and `B`; the subgroup they generate is the
-- derived canonical object `Subgroup.closure ({A, B} : Set (SL(2, ℤ)))`, and the proposition
-- asserts that these two generators themselves form a free basis of that subgroup.

/-- The determinant of the upper-unitriangular matrix `!![1, 2; 0, 1]` is `1`. -/
-- Proof sketch: evaluate the determinant of this explicit `2 × 2` matrix using
-- `Matrix.det_fin_two`.
theorem sanovMatrixA_det :
    Matrix.det (!![1, 2; 0, 1] : Matrix (Fin 2) (Fin 2) ℤ) = 1 := sorry

/-- The matrix `A = !![1, 2; 0, 1]` as an element of `SL(2, ℤ)`. -/
def sanovMatrixA : SL(2, ℤ) :=
  ⟨!![1, 2; 0, 1], sanovMatrixA_det⟩

/-- The determinant of the lower-unitriangular matrix `!![1, 0; 2, 1]` is `1`. -/
-- Proof sketch: evaluate the determinant of this explicit `2 × 2` matrix using
-- `Matrix.det_fin_two`.
theorem sanovMatrixB_det :
    Matrix.det (!![1, 0; 2, 1] : Matrix (Fin 2) (Fin 2) ℤ) = 1 := sorry

/-- The matrix `B = !![1, 0; 2, 1]` as an element of `SL(2, ℤ)`. -/
def sanovMatrixB : SL(2, ℤ) :=
  ⟨!![1, 0; 2, 1], sanovMatrixB_det⟩

local notation "A" => sanovMatrixA
local notation "B" => sanovMatrixB
local notation "S" => ({A, B} : Set (SL(2, ℤ)))

/-- Proposition 3-12-4: the matrices `A = !![1, 2; 0, 1]` and `B = !![1, 0; 2, 1]` form a free
basis of the subgroup of `SL(2, ℤ)` that they generate. -/
-- Proof sketch: view these matrices as acting by linear fractional transformations and apply the
-- ping-pong argument with the unit disc and its exterior, equivalently the free-product
-- decomposition generated by `A` and the involution exchanging `0` and `∞`. This shows that every
-- nonempty reduced alternating word in `A` and `B` is nontrivial, so the subgroup they generate
-- is free on the displayed generating subset.
theorem sanov_matrices_form_free_basis :
    IsFreeGroupBasis {g : Subgroup.closure S | (g : SL(2, ℤ)) ∈ S} := sorry

end
