import Mathlib
import StacksProject_2024.Chap07.Lemma_7_12_5
import StacksProject_2024.Chap07.Lemma_7_17_3
import StacksProject_2024.Chap07.Lemma_7_17_7
import StacksProject_2024.Chap07.Lemma_7_17_8

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory CategoryTheory.Limits Opposite
open CategoryTheory.Sheaf
open CategoryTheory.SemiRepresentableFamily.Over
open scoped CategoryTheory.GrothendieckTopology.SheafifiedRepresentable

noncomputable section

universe u v w

namespace CategoryTheory.GrothendieckTopology

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)
variable [HasWeakSheafify J (Type (max u v))]

local instance finiteSheafifiedRepresentableHasCoproduct {ι : Type (max u v)} [Finite ι]
    (Y : ι → C) : HasCoproduct (fun i : ι ↦ h[Y i]^#[J]) := by
  let _ : Fintype ι := Fintype.ofFinite ι
  let _ : HasColimitsOfShape (Discrete ι) (Sheaf J (Type (max u v))) :=
    Sheaf.instHasColimitsOfShape
  infer_instance

/- Source/core/bridge triage for 7.17.9:
- source-facing owners: `HasSurjectiveBasisQuasiCompactProducts`,
  `HasFiniteRefinementBasisQuasiCompactProducts`,
  `HasQuasiCompactProductsOfQuasiCompactRepresentables`
- core/canonical owners reused from earlier in the chapter: `SemiRepresentableFamily`,
  `SemiRepresentableFamily.Over`, refinement morphisms `𝒱 ⟶ 𝒰`,
  `sheafifiedRepresentable`/`sheafifiedRepresentableMap`, the coproduct owner
  `∐ fun i ↦ h[U i]^#[J]` from Lemma 7.12.5, `IsQuasiCompactTestSet`,
  the terminal-sheaf owner `(⊤_ (Sheaf J (Type (max u v)))).IsQuasiCompactObject`,
  and `J.HasEnoughObjectsWithProperty`
- primitive data used here: a semi-representable family `𝒰` and finiteness of `𝒰.index`
- derived API used here: coproduct objects and their universal morphisms `Limits.Sigma.desc`,
  together with `prod.lift`
-/

/-- The set of actual finite coproducts `∐ h_{U_j}^#` with every `U_j` lying in `B`. -/
def FiniteSheafifiedRepresentableCoproductsFrom (B : Set C) :
    Set (Sheaf J (Type (max u v))) :=
  { ℱ | ∃ 𝒰 : SemiRepresentableFamily.{max u v, v, u} C, ∃ _ : Finite 𝒰.index,
      (∀ i : 𝒰.index, 𝒰.obj i ∈ B) ∧
        ℱ = ∐ fun i : 𝒰.index ↦ h[𝒰.obj i]^#[J] }

/-- A basis `B` of objects detects locally surjective maps to the terminal sheaf by finite
coproducts of sheafified representables, and pairwise products of those representables are
quasi-compact. -/
class HasSurjectiveBasisQuasiCompactProducts (B : Set C) : Prop where
  surjective_to_terminal {ℱ : Sheaf J (Type (max u v))}
      (hℱ : IsLocallySurjective (terminal.from ℱ)) :
      ∃ 𝒰 : SemiRepresentableFamily.{max u v, v, u} C, ∃ _ : Finite 𝒰.index,
        (∀ i : 𝒰.index, 𝒰.obj i ∈ B) ∧
          ∃ κ : (∐ fun i : 𝒰.index ↦ h[𝒰.obj i]^#[J]) ⟶ ℱ,
            IsLocallySurjective (κ ≫ terminal.from ℱ)
  product_quasiCompact {U U' : C} (hU : U ∈ B) (hU' : U' ∈ B) :
      (h[U]^#[J] ⨯ h[U']^#[J]).IsQuasiCompactObject

/-- A basis `B` has a finite representable cover of the terminal sheaf, finite cover refinements
inside `B`, and finite representable covers of products built from actual arrows in the site. -/
class HasFiniteRefinementBasisQuasiCompactProducts (B : Set C) : Prop where
  terminal_surjection :
    ∃ 𝒰 : SemiRepresentableFamily.{max u v, v, u} C, ∃ _ : Finite 𝒰.index,
      (∀ i : 𝒰.index, 𝒰.obj i ∈ B) ∧
        IsLocallySurjective
          (terminal.from (∐ fun i : 𝒰.index ↦ h[𝒰.obj i]^#[J]))
  cover_refinement {U : C} (hU : U ∈ B)
      (𝒰 : SemiRepresentableFamily.Over.{v, u, w} U) (h𝒰 : 𝒰.toSieve ∈ J U) :
      ∃ (𝒱 : SemiRepresentableFamily.Over.{v, u, w} U) (_ : Finite 𝒱.index) (_ : 𝒱 ⟶ 𝒰),
        𝒱.toSieve ∈ J U ∧
          ∀ j : 𝒱.index, (𝒱.obj j).left ∈ B
  product_surjection {U U' : C} (hU : U ∈ B) (hU' : U' ∈ B) :
      ∃ 𝒱 : SemiRepresentableFamily.{max u v, v, u} C, ∃ _ : Finite 𝒱.index,
        ∃ f : ∀ i : 𝒱.index, 𝒱.obj i ⟶ U, ∃ g : ∀ i : 𝒱.index, 𝒱.obj i ⟶ U',
          (∀ i : 𝒱.index, 𝒱.obj i ∈ B) ∧
            IsLocallySurjective
              (prod.lift
                (Limits.Sigma.desc
                  (fun i : 𝒱.index ↦ J.sheafifiedRepresentableMap (f i)))
                (Limits.Sigma.desc
                  (fun i : 𝒱.index ↦ J.sheafifiedRepresentableMap (g i))))

/-- Products of sheafified representables attached to quasi-compact objects are quasi-compact in
the sheaf topos. -/
class HasQuasiCompactProductsOfQuasiCompactRepresentables : Prop where
  product_quasiCompact {U U' : C}
      (hU : J.QuasiCompactObject U)
      (hU' : J.QuasiCompactObject U') :
      (h[U]^#[J] ⨯ h[U']^#[J]).IsQuasiCompactObject

/-- The site is generated by quasi-compact objects, the terminal sheaf is quasi-compact, and
products of sheafified representables of quasi-compact objects are quasi-compact. -/
class HasQuasiCompactGeneratorTestSetHypotheses : Prop where
  topos_quasiCompact :
    (⊤_ (Sheaf J (Type (max u v)))).IsQuasiCompactObject
  enough_quasiCompactObjects :
    J.HasEnoughObjectsWithProperty (J.QuasiCompactObject)
  quasiCompactRepresentableProducts :
    HasQuasiCompactProductsOfQuasiCompactRepresentables J

-- Proof sketch: use the finite coproducts supplied by the basis to test locally surjective maps
-- to the terminal sheaf; quasi-compactness of pairwise products of basis representables yields the
-- product quasi-compactness clause for the resulting finite coproduct test set.
/-- Finite coproducts of sheafified representables from a surjective basis form a test set for
Lemma 7.17.8 (4). -/
theorem isQuasiCompactTestSet_of_surjective_basis
    (B : Set C)
    [HasSurjectiveBasisQuasiCompactProducts J B] :
    IsQuasiCompactTestSet J (FiniteSheafifiedRepresentableCoproductsFrom J B) := sorry

-- Proof sketch: the finite cover of the terminal sheaf gives the first clause of
-- `IsQuasiCompactTestSet`; refinements by finite `B`-covers produce finite coproducts that test
-- arbitrary surjections to `*`, and the product-cover hypothesis supplies the quasi-compactness
-- information needed for their pairwise products.
/-- Finite coproducts of sheafified representables from a finite-refinement basis form a test set
for Lemma 7.17.8 (4). -/
theorem isQuasiCompactTestSet_of_finite_refinement_basis
    (B : Set C)
    [HasFiniteRefinementBasisQuasiCompactProducts J B] :
    IsQuasiCompactTestSet J (FiniteSheafifiedRepresentableCoproductsFrom J B) := sorry

-- Proof sketch: quasi-compactness of the terminal sheaf handles the first stage of the testing
-- argument; coverings by quasi-compact objects yield finite representable coproducts that refine
-- any locally surjective map to `*`, and quasi-compactness of products of quasi-compact
-- representables gives the second clause of `IsQuasiCompactTestSet`.
/-- Finite coproducts of sheafified representables attached to quasi-compact objects form a test
set for Lemma 7.17.8 (4) on a quasi-compact site generated by quasi-compact objects. -/
theorem isQuasiCompactTestSet_of_quasiCompact_generators
    (hTopos : (⊤_ (Sheaf J (Type (max u v)))).IsQuasiCompactObject)
    (hEnough : J.HasEnoughObjectsWithProperty (J.QuasiCompactObject))
    [HasQuasiCompactProductsOfQuasiCompactRepresentables J] :
    IsQuasiCompactTestSet J
      (FiniteSheafifiedRepresentableCoproductsFrom J
        { U | J.QuasiCompactObject U }) :=
  sorry

-- Proof sketch: perform the explicit three-way case split from Remark 7.17.9 and apply the
-- corresponding existence theorem, using the finite coproduct family supplied in each case.
/-- Remark 7.17.9: any of the three standard hypotheses yields a test set satisfying the
assumptions of Lemma 7.17.8 (4). -/
theorem exists_quasiCompactTestSet_of_surjective_basis_or_finite_refinement_basis_or_quasiCompact_generators
    (h :
      (∃ B : Set C, HasSurjectiveBasisQuasiCompactProducts J B) ∨
        (∃ B : Set C, HasFiniteRefinementBasisQuasiCompactProducts J B) ∨
          HasQuasiCompactGeneratorTestSetHypotheses J) :
    ∃ S : Set (Sheaf J (Type (max u v))), IsQuasiCompactTestSet J S := sorry

end CategoryTheory.GrothendieckTopology
