import Mathlib
import LecturesConvexOptimization_Nesterov_2018.Chap07.Algorithm_7_12
import LecturesConvexOptimization_Nesterov_2018.Chap07.Lemma_7_12
import LecturesConvexOptimization_Nesterov_2018.Chap07.Definition_7_56
import LecturesConvexOptimization_Nesterov_2018.Chap07.Definition_7_57

-- Declarations for this item will be appended below by the statement pipeline.

open scoped BigOperators

noncomputable section

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-
Proposition 7.29 lies in the barrier-subgradient / weighted-average domain.

Mandatory domain-style sampling:
- `DualBarrierSubgradientMethod` in `Algorithm_7_12`, the source-facing owner of the iterates and
  stepsizes;
- `barrierSubgradientWeightSum` in `Theorem_7_15` and
  `barrierSubgradientAverageDualityGap_le_maximalGap` in `Lemma_7_12`, the chapter owners for
  `S_k` and the nearby averaged-gap estimate;
- `Finset.centerMass` and `ConcaveOn.le_map_centerMass`, the canonical finite weighted-average
  owner and Jensen inequality for concave functions;
- `maximalValueOn` and `barrierSubgradientMaximalGap`, the faithful `EReal` owners for the primal
  optimum `f_*` and the maximal gap `ℓ_k⋆`.

Best owner abstraction:
- source-facing: the weighted primal-value average generated by a `DualBarrierSubgradientMethod`;
- core/canonical: `Finset.centerMass` for that normalized average, together with
  `barrierSubgradientWeightSum`, `maximalValueOn`, and `barrierSubgradientMaximalGap`;
- bridge/view: the textbook quotient formula
  `(∑ λ_i f(x_i)) / (∑ λ_i)`, which is just the scalar expansion of `Finset.centerMass`.

Primitive data:
- the method owner `method : DualBarrierSubgradientMethod P f`;
- the index `k`.

Derived API:
- the scalar weighted average `centerMass` of the sampled values `f(method i)`;
- the normalization factor `barrierSubgradientWeightSum`;
- the explicit-rate specialization obtained by combining the main estimate with an assumed maximal
  gap bound.

The previous version duplicated both the denominator `S_k` and the normalized weighted average as
raw quotient expressions. This refinement keeps the proposition source-facing, but moves its public
surface to the existing weighted-average and gap owners already established earlier in the chapter.
-/

-- Proof sketch: for each feasible `y ∈ P`, concavity gives
-- `f y ≤ f(x_i) + ⟪g_i, y - x_i⟫` for every `i`. Multiply by the positive step sizes,
-- sum from `i = 0` to `k`, and then take the supremum over `y ∈ P` to identify the gap term
-- `barrierSubgradientMaximalGap ... k`.
/-- Proposition 7.29: for a concave objective on the feasible set of the barrier subgradient
method, the weighted average of the values `f(x_i)` over the first `k + 1` iterates, written
canonically as a `Finset.centerMass`, is within `ℓ_k⋆ / S_k` of the maximal value
`f_* = maximalValueOn P f`, where `ℓ_k⋆` is `barrierSubgradientMaximalGap ... k` and
`S_k = barrierSubgradientWeightSum ... k`. -/
theorem barrierSubgradientMethod_primal_efficiency_estimate
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) :
    maximalValueOn P f -
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) ≤
      method.maximalGap k /
        barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k :=
  sorry

-- Proof sketch: combine `barrierSubgradientMethod_primal_efficiency_estimate` with the explicit
-- bound assumed for `barrierSubgradientMaximalGap ... k / S_k`, where that bound is the one
-- obtained in the text from the parameter choice `(7.3.19)`.
/-- When the maximal-gap estimate produced by the parameter choice `(7.3.19)` holds, the weighted
average of the sampled values `f(x_i)` satisfies the corresponding explicit rate. -/
theorem barrierSubgradientMethod_primal_efficiency_estimate_explicit_rate
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) {M ν : ℝ}
    (hgap :
      ∀ k : ℕ,
        method.maximalGap k /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k ≤
          ((2 * M *
              (Real.sqrt (ν / ((k : ℝ) + 1)) + ν / ((k : ℝ) + 1)) *
                (1 + Real.log (2 + (3 / 2 : ℝ) * Real.sqrt (ν * ((k : ℝ) + 1)))) : ℝ)))
    (k : ℕ) :
    maximalValueOn P f -
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) ≤
      ((2 * M *
          (Real.sqrt (ν / ((k : ℝ) + 1)) + ν / ((k : ℝ) + 1)) *
            (1 + Real.log (2 + (3 / 2 : ℝ) * Real.sqrt (ν * ((k : ℝ) + 1)))) : ℝ)) :=
  sorry
