import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Definition_17_1 (from Items/Chap17) -/
open MeasureTheory
open scoped ProbabilityTheory

universe u v w

namespace ProbabilityTheory

variable {ι : Type u} [Preorder ι]
variable {Ω : Type v} [mΩ : MeasurableSpace Ω]
variable {E : Type w} [mE : MeasurableSpace E]

/-- Definition 17.1: a process has the Markov property with respect to a filtration `ℱ` if, for
it is adapted to `ℱ`, and for every measurable set `A` and all times `s ≤ t`, the conditional
probability of the future event `{X_t ∈ A}` given `ℱ s` agrees almost surely with the conditional
probability given the present state `X s`. -/
def HasMarkovProperty (ℱ : Filtration ι mΩ) (μ : Measure Ω) [IsProbabilityMeasure μ]
    (X : ι → Ω → E) : Prop :=
  Adapted ℱ X ∧
    ∀ ⦃A : Set E⦄, MeasurableSet A → ∀ ⦃s t : ι⦄, s ≤ t →
      μ⟦X t ⁻¹' A | ℱ s⟧ =ᵐ[μ]
        μ⟦X t ⁻¹' A | MeasurableSpace.comap (X s) mE⟧

theorem HasMarkovProperty.adapted {ℱ : Filtration ι mΩ} {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X : ι → Ω → E} (h : HasMarkovProperty ℱ μ X) :
    Adapted ℱ X :=
  h.1

theorem HasMarkovProperty.measurable {ℱ : Filtration ι mΩ} {μ : Measure Ω}
    [IsProbabilityMeasure μ] {X : ι → Ω → E} (h : HasMarkovProperty ℱ μ X) (t : ι) :
    Measurable (X t) :=
  h.adapted.measurable

-- Proof sketch: unfold `HasMarkovProperty`; this is the defining adaptedness plus conditional-
-- probability identity written as an explicit `↔`, which is the useful elimination form for later
-- rewriting.
/-- Having the Markov property is equivalent to adaptedness together with the conditional-
probability identity for all measurable state events and all times `s ≤ t`. -/
theorem hasMarkovProperty_iff (ℱ : Filtration ι mΩ) (μ : Measure Ω) [IsProbabilityMeasure μ]
    (X : ι → Ω → E) :
    HasMarkovProperty ℱ μ X ↔
      Adapted ℱ X ∧
        ∀ ⦃A : Set E⦄, MeasurableSet A → ∀ ⦃s t : ι⦄, s ≤ t →
          μ⟦X t ⁻¹' A | ℱ s⟧ =ᵐ[μ]
            μ⟦X t ⁻¹' A | MeasurableSpace.comap (X s) mE⟧ :=
  Iff.rfl

end ProbabilityTheory

/-! ### Exercise_17_1_1 (from Items/Chap17) -/
open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory

noncomputable section

universe u v w

variable {Ω : Type u} [MeasurableSpace Ω]
variable {T : Type v} [LinearOrder T]
variable {E : Type w} [MeasurableSpace E]

namespace ProbabilityTheory

/-- The future `σ`-algebra of a process from time `t` onward, generated by the coordinates
`X r` with `t ≤ r`. -/
abbrev processFuture (X : T → Ω → E) (t : T) : MeasurableSpace Ω :=
  ⨆ r ≥ t, MeasurableSpace.comap (X r) ‹MeasurableSpace E›

-- Proof sketch: for the forward implication, use the natural-history Markov property on future
-- cylinder events and extend from the generating future coordinates to the full future
-- `σ`-algebra. For the reverse implication, test the conditional-independence statement on the
-- future events `{ω | X u ω ∈ A}` with `t ≤ u`.
/-- Exercise 17.1.1: on a linearly ordered time set, a process has the natural Markov property
exactly when, for every time `t`, the history `σ`-algebra up to `t` and the future `σ`-algebra
from `t` onward are conditionally independent given the present state `X t`. This is stated in
the chapter's source-facing conditional-independence API. -/
theorem hasNaturalMarkovProperty_iff_pastFutureConditionallyIndependentGivenPresent
    (μ : Measure Ω) [IsProbabilityMeasure μ] (X : T → Ω → E) :
    HasNaturalMarkovProperty μ X ↔
      ∀ t : T,
        IsConditionallyIndependent
          (MeasurableSpace.comap (X t) ‹MeasurableSpace E›)
          (fun b : Bool ↦ if b then processFuture X t else generatedFiltrationSpace X t) μ := sorry

/-- Under `StandardBorelSpace Ω`, the source-facing past/future conditional-independence
criterion on a linearly ordered time set is equivalent to the owner-level statement `CondIndep`
for the history and future `σ`-algebras. -/
theorem pastFutureConditionallyIndependentGivenPresent_iff_condIndep
    [StandardBorelSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ] (X : T → Ω → E) :
    (∀ t : T,
      IsConditionallyIndependent
        (MeasurableSpace.comap (X t) ‹MeasurableSpace E›)
        (fun b : Bool ↦ if b then processFuture X t else generatedFiltrationSpace X t) μ) ↔
      ∀ t : T,
        ∃ hXt : MeasurableSpace.comap (X t) ‹MeasurableSpace E› ≤ ‹MeasurableSpace Ω›,
          CondIndep (MeasurableSpace.comap (X t) ‹MeasurableSpace E›)
            (generatedFiltrationSpace X t) (processFuture X t) hXt μ := sorry

end ProbabilityTheory
