import Serre.RepresentationTheory.ExternalTensor
import Serre.RepresentationTheory.FrobeniusCharacterPairing
import Serre.RepresentationTheory.GroupFunctionPairing
import Serre.RepresentationTheory.RealizableOver
import Serre.RepresentationTheory.SymmetricExterior
