import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open scoped Gradient

noncomputable section

/-
Primary domain: abstract first-order iterative methods on a real Hilbert space, together with the
span restriction used in lower-complexity arguments.

Relevant owner-style declarations sampled before refining:
* `ConvexC1SeminormSmooth.contDiff` in `Theorem_2_5`, the chapter's canonical recovery of the
  `C¹` regularity carried by a smooth convex objective owner;
* `IsStrongConvexSmoothObjective.contDiff` in `Definition_2_17`, the analogous `C¹` recovery in
  the strongly convex smooth regime;
* `gradient_eq_zero_of_not_differentiableAt` in mathlib, showing that quantifying a gradient-based
  condition over arbitrary `f : E → ℝ` would otherwise import the implementation-specific
  zero-totalization of `∇`;
* `AffineSubspace.mk'` and `AffineSubspace.mem_mk'` in mathlib, the canonical owner of an affine
  translate `x₀ + V`.

Layer triage:
* source-facing: the predicate `SatisfiesSpanCondition` on a first-order iterate family
  `(E → ℝ) → E → ℕ → E`;
* core/canonical: the iterate family itself, together with the canonical `ContDiff ℝ 1`
  smooth-objective hypothesis and `AffineSubspace.mk' x₀ V` for the affine search space;
* bridge/view: the vector-form companion theorem `satisfiesSpanCondition_iff`.

Primitive data:
* the iterate family `x_k(f, x₀)`.

Derived API:
* the affine search space `gradientSpanSearchSpace method f x₀ k`;
* the zeroth-iterate law `x₀ = x₀` on `C¹` objectives;
* the span-condition predicate on the iterate family, sampled only on `C¹` objectives;
* the companion vector-form restatement obtained from `AffineSubspace.mem_mk'`.
-/

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- The affine search space generated from the initial point `x₀` and the earlier gradients of an
iterate family `method` applied to a `C¹` objective `f`. -/
def gradientSpanSearchSpace
    (method : (E → ℝ) → E → ℕ → E) (f : E → ℝ) (x0 : E) (k : ℕ) :
    AffineSubspace ℝ E :=
  AffineSubspace.mk' x0
    (Submodule.span ℝ (Set.range fun i : Fin k ↦ ∇ f (method f x0 i)))

/-- Definition 2.9: a first-order iterate family `method` satisfies the span condition when, for
every `C¹` objective `f`, it starts from the prescribed initial point and every iterate `x_k` with
`k ≥ 1` lies in the affine translate by `x₀` of the linear span of the earlier gradients
`∇ f(x₀), …, ∇ f(x_{k-1})`. -/
def SatisfiesSpanCondition (method : (E → ℝ) → E → ℕ → E) : Prop :=
  ∀ (f : E → ℝ) (_ : ContDiff ℝ 1 f) (x0 : E) (k : ℕ),
    method f x0 k ∈ gradientSpanSearchSpace method f x0 k

namespace SatisfiesSpanCondition

variable {method : (E → ℝ) → E → ℕ → E}

/-- A span-condition method family starts from the prescribed initial point on every `C¹`
objective. -/
@[simp] theorem zero_eq
    (hmethod : SatisfiesSpanCondition method) (f : E → ℝ) (hf : ContDiff ℝ 1 f) (x0 : E) :
    method f x0 0 = x0 := by
  have hzero : method f x0 0 - x0 = 0 := by
    simpa [gradientSpanSearchSpace, AffineSubspace.mem_mk'] using hmethod f hf x0 0
  exact sub_eq_zero.mp hzero

/-- A span-condition method family keeps every iterate in the affine span generated by the earlier
gradients. -/
theorem sub_mem_span
    (hmethod : SatisfiesSpanCondition method) (f : E → ℝ) (hf : ContDiff ℝ 1 f) (x0 : E)
    (k : ℕ) :
    method f x0 k - x0 ∈
      Submodule.span ℝ (Set.range fun i : Fin k ↦ ∇ f (method f x0 i)) := by
  simpa [gradientSpanSearchSpace, AffineSubspace.mem_mk'] using hmethod f hf x0 k

end SatisfiesSpanCondition

/-- A method satisfies the span condition exactly when, for every `C¹` objective, each positive
iterate differs from `x₀` by a vector in the linear span of the earlier gradients, while the
zeroth iterate is exactly `x₀`. -/
theorem satisfiesSpanCondition_iff (method : (E → ℝ) → E → ℕ → E) :
    SatisfiesSpanCondition method ↔
      ∀ (f : E → ℝ) (_ : ContDiff ℝ 1 f) (x0 : E) (k : ℕ),
        method f x0 k - x0 ∈
          Submodule.span ℝ (Set.range fun i : Fin k ↦ ∇ f (method f x0 i)) := by
  simp [SatisfiesSpanCondition, gradientSpanSearchSpace, AffineSubspace.mem_mk']
