import OptimizationTheoryAndMethods_SunYuan_2006.Compat
import OptimizationTheoryAndMethods_SunYuan_2006.SunYuanOptimizationTheoryMethods.Chapter05.Algorithm_5_7_2
import OptimizationTheoryAndMethods_SunYuan_2006.SunYuanOptimizationTheoryMethods.Chapter01.Definition_1_5_extra_2
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Convex.Extrema
import Mathlib.Analysis.Convex.Strong

noncomputable section

open Filter

section

variable {n : ℕ}

local notation "Point" => EuclideanSpace ℝ (Fin n)

-- Domain sampling for this refine pass:
-- * project owner `LBFGSMethod` from `Algorithm_5_7_2.lean`
-- * project owner `LBFGSMethod.terminatedAt` from `Algorithm_5_7_2.lean`
-- * project owner `rLinearConvergenceTo` from Chapter 1
-- * mathlib owner `StrongConvexOn`
-- The L-BFGS method data are canonical upstream; this file only owns the geometric
-- error-bound conclusion through the canonical Chapter 1 `R`-linear convergence owner.

/-- Chapter05 Theorem 5.7.7: let `f : ℝ^n → ℝ` be twice continuously differentiable, with
uniform strong convexity modulus `m > 0`. Assume `A` is the sequence generated by
Chapter05 Algorithm 5.7.2; `A` converges to the unique global minimizer `xStar` of `f`;
`xStar` is characterized by `IsMinOn f Set.univ xStar`, and uniqueness is the canonical
consequence of strong convexity already exposed in Chapter 5. Then the convergence rate is
at least `R`-linear, expressed by the canonical Chapter 1 owner
`rLinearConvergenceTo A xStar`. -/
theorem lbfgs_atLeastRLinear_of_tendsto_uniqueGlobalMinimizer_of_strongConvex
    (f : Point → ℝ) (A : LBFGSMethod n f) (m : ℝ) (xStar : Point)
    (hC2 : ContDiff ℝ 2 f)
    (hm : 0 < m)
    (hStrong : StrongConvexOn Set.univ m f)
    (hMin : IsMinOn f Set.univ xStar)
    (hTendsto : Tendsto A atTop (nhds xStar)) :
    rLinearConvergenceTo A xStar := sorry

end
