import Mathlib
import LinearRepresentations_Serre_1977.Serre.Chap14.Lemma_14_14_4_1
import LinearRepresentations_Serre_1977.Serre.Chap15.Definition_15_15_1_1

noncomputable section

universe u

open CategoryTheory
open scoped MonoidAlgebra MonoidalCategory Representation TensorProduct

namespace Representation

section FiniteRepTensorRing

variable (k : Type u) (G : Type u) [Field k] [Monoid G]

/- Domain-style sampling for this item:
* primary domain: tensor-product actions on Serre's Grothendieck groups `R₀[k](G)` and `P₀[k](G)`.
* core/canonical owners already fixed upstream:
  `finiteRepGrothendieckGroup` / `R₀[k](G)`,
  `FiniteProjectiveGroupAlgebraModule`,
  `FiniteProjectiveGroupAlgebraModule.toRep`,
  `FiniteProjectiveGroupAlgebraModule.toFiniteRep`,
  and `cartanHom`.
* core/canonical content refined in this section: the tensor-product ring structure on `R₀[k](G)`.
* source-facing finite-group content deferred to the later section: the tensor action on projective
  classes, the `R₀[k](G)`-module structure on `P₀[k](G)`, and the `R₀[k](G)`-linearity of
  `cartanHom`.
* primitive data here: the short-exact-sequence relations defining `R₀[k](G)` and the tensor
  product `Representation.tprod` on `FDRep k G`.
* derived API here: the quotient tensor lifts, the commutative ring structure on `R₀[k](G)`, and
  `finiteRepGrothendieckClass_mul`.
-/

-- Proof sketch: tensor a short exact sequence in the second variable with the fixed
-- finite-dimensional representation `V`; exactness over `k` gives the defining relation in
-- `R_k(G)`.
/-- Tensoring a short exact sequence of finite-dimensional representations with a fixed
finite-dimensional representation preserves the defining relation in `R_k(G)`. -/
theorem tensorFiniteRepClass_middle_eq_left_add_right
    (V : FDRep k G) (S : ShortComplex (FDRep k G)) (hS : S.ShortExact) :
    [V ⊗ S.X₂]₀ = [V ⊗ S.X₁]₀ + [V ⊗ S.X₃]₀ := by
  -- First forget to `Rep k G`, then to `ModuleCat k`, where tensoring by a fixed vector space is
  -- exact because every `k`-module is flat.
  have hTensor : (S.map (MonoidalCategory.tensorLeft V)).ShortExact := by
    let F : FDRep k G ⥤ Rep k G := forget₂ (FDRep k G) (Rep k G)
    apply
      (CategoryTheory.ShortExact.shortExact_map_iff
        (S := S.map (MonoidalCategory.tensorLeft V)) (F := F)).1
    have hRep : ((S.map (MonoidalCategory.tensorLeft V)).map F).ShortExact := by
      have hRepBase : (S.map F).ShortExact := by
        simpa using hS.map_of_exact F
      let Vk : ModuleCat k := ModuleCat.of k (F.obj V).V
      have hMod :
          (((S.map F).map (MonoidalCategory.tensorLeft (F.obj V))).map
            (forget₂ (Rep k G) (ModuleCat k))).ShortExact := by
        have hForget : (((S.map F)).map (forget₂ (Rep k G) (ModuleCat k))).ShortExact := by
          simpa using hRepBase.map_of_exact (forget₂ (Rep k G) (ModuleCat k))
        have hFlat : Module.Flat k Vk := by
          infer_instance
        let _ : CategoryTheory.Limits.PreservesFiniteLimits (MonoidalCategory.tensorLeft Vk) :=
          (Module.Flat.iff_preservesFiniteLimits_tensorLeft (R := k) Vk).mp hFlat
        have := hForget.map_of_exact (MonoidalCategory.tensorLeft Vk)
        simpa [Vk] using this
      apply
        (CategoryTheory.ShortExact.shortExact_map_iff
          (S := (S.map F).map (MonoidalCategory.tensorLeft (F.obj V)))
          (F := forget₂ (Rep k G) (ModuleCat k))).1
      simpa using hMod
    simpa using hRep
  -- Apply the Chapter 14 Grothendieck relation to the tensorized short exact sequence.
  simpa using
    finiteRepGrothendieckClass_middle_eq_left_add_right (L := k) (G := G)
      (S.map (MonoidalCategory.tensorLeft V)) hTensor

/-- Tensoring by a fixed finite-dimensional representation defines an additive map on the free
abelian group generated by finite-dimensional representations. -/
private abbrev finiteRepTensorLift (V : FDRep k G) :
    FreeAbelianGroup (FDRep k G) →+ R₀[k](G) :=
  FreeAbelianGroup.lift fun W ↦ [V ⊗ W]₀

-- Proof sketch: the tensorized short exact sequence relation from the previous theorem shows that
-- every generator of `finiteRepGrothendieckRelations k G` lies in the kernel.
/-- The tensor-product lift on finite-dimensional classes factors through `R_k(G)`. -/
private theorem finiteRepGrothendieckRelations_le_finiteRepTensorLift_ker
    (V : FDRep k G) :
    finiteRepGrothendieckRelations k G ≤ (finiteRepTensorLift k G V).ker := by
  -- It suffices to check the defining short-exact-sequence generators of the Grothendieck
  -- relations.
  change
    AddSubgroup.closure
      (Set.range fun S : { S : ShortComplex (FDRep k G) // S.ShortExact } ↦
        FreeAbelianGroup.of S.1.X₂ - FreeAbelianGroup.of S.1.X₁ - FreeAbelianGroup.of S.1.X₃) ≤
      (finiteRepTensorLift k G V).ker
  refine (AddSubgroup.closure_le (K := (finiteRepTensorLift k G V).ker)).2 ?_
  rintro _ ⟨⟨S, hS⟩, rfl⟩
  change [V ⊗ S.X₂]₀ - [V ⊗ S.X₁]₀ - [V ⊗ S.X₃]₀ = 0
  rw [sub_eq_zero]
  have hrel := tensorFiniteRepClass_middle_eq_left_add_right (k := k) (G := G) V S hS
  calc
    [V ⊗ S.X₂]₀ - [V ⊗ S.X₁]₀ =
        ([V ⊗ S.X₁]₀ + [V ⊗ S.X₃]₀) - [V ⊗ S.X₁]₀ := by rw [hrel]
    _ = [V ⊗ S.X₃]₀ := by abel

/-- Tensoring by a fixed class of `R_k(G)` induces an additive endomorphism of `R_k(G)`. -/
private def finiteRepTensorEnd (V : FDRep k G) :
    R₀[k](G) →+ R₀[k](G) :=
  QuotientAddGroup.lift
    (finiteRepGrothendieckRelations k G)
    (finiteRepTensorLift k G V)
    (finiteRepGrothendieckRelations_le_finiteRepTensorLift_ker k G V)

-- Proof sketch: tensor the short exact sequence in the first variable with the fixed
-- finite-dimensional representation `V`; the resulting tensorized sequence gives the required
-- relation in `R_k(G)`.
/-- Tensoring a short exact sequence of finite-dimensional representations in the first variable
also preserves the defining relation in `R_k(G)`. -/
theorem finiteRep_tensorFiniteRepClass_middle_eq_left_add_right
    (S : ShortComplex (FDRep k G)) (hS : S.ShortExact) (V : FDRep k G) :
    [S.X₂ ⊗ V]₀ = [S.X₁ ⊗ V]₀ + [S.X₃ ⊗ V]₀ := by
  -- Commute the fixed tensor factor to the left via the braiding, then reuse the previous exact
  -- tensor relation.
  have hX₂ : Nonempty (S.X₂ ⊗ V ≅ V ⊗ S.X₂) := by
    exact ⟨β_ S.X₂ V⟩
  have hX₁ : Nonempty (S.X₁ ⊗ V ≅ V ⊗ S.X₁) := by
    exact ⟨β_ S.X₁ V⟩
  have hX₃ : Nonempty (S.X₃ ⊗ V ≅ V ⊗ S.X₃) := by
    exact ⟨β_ S.X₃ V⟩
  rw [finiteRepGrothendieckClass_eq_of_nonempty_iso (L := k) (G := G) hX₂,
    finiteRepGrothendieckClass_eq_of_nonempty_iso (L := k) (G := G) hX₁,
    finiteRepGrothendieckClass_eq_of_nonempty_iso (L := k) (G := G) hX₃]
  simpa [add_comm] using
    tensorFiniteRepClass_middle_eq_left_add_right (k := k) (G := G) V S hS

/-- The tensor action of finite-dimensional representations on `R_k(G)` lifted to the free abelian
group on generators of `R_k(G)`. -/
private abbrev finiteRepActionLift :
    FreeAbelianGroup (FDRep k G) →+ AddMonoid.End (R₀[k](G)) :=
  FreeAbelianGroup.lift fun V ↦ finiteRepTensorEnd k G V

-- Proof sketch: the previous tensorized relation in the first variable shows that every defining
-- relation of `R_k(G)` acts trivially on the quotient.
/-- The tensor action on `R_k(G)` factors through the Grothendieck quotient `R_k(G)`. -/
private theorem finiteRepGrothendieckRelations_le_finiteRepActionLift_ker :
    finiteRepGrothendieckRelations k G ≤ (finiteRepActionLift k G).ker := by
  -- Evaluate a defining short-exact-sequence generator pointwise on `R₀[k](G)` and reduce to the
  -- already-proved tensor relation in the first variable.
  change
    AddSubgroup.closure
      (Set.range fun S : { S : ShortComplex (FDRep k G) // S.ShortExact } ↦
        FreeAbelianGroup.of S.1.X₂ - FreeAbelianGroup.of S.1.X₁ - FreeAbelianGroup.of S.1.X₃) ≤
      (finiteRepActionLift k G).ker
  refine (AddSubgroup.closure_le (K := (finiteRepActionLift k G).ker)).2 ?_
  rintro _ ⟨⟨S, hS⟩, rfl⟩
  apply AddMonoidHom.ext
  intro y
  refine QuotientAddGroup.induction_on y ?_
  intro a
  refine FreeAbelianGroup.induction_on a ?_ ?_ ?_ ?_
  · simp
  · intro W
    -- On a generator class, the pointwise action is the tensor-product class relation.
    change [S.X₂ ⊗ W]₀ - [S.X₁ ⊗ W]₀ - [S.X₃ ⊗ W]₀ = 0
    rw [sub_eq_zero]
    have hrel :=
      finiteRep_tensorFiniteRepClass_middle_eq_left_add_right (k := k) (G := G) S hS W
    calc
      [S.X₂ ⊗ W]₀ - [S.X₁ ⊗ W]₀ =
          ([S.X₁ ⊗ W]₀ + [S.X₃ ⊗ W]₀) - [S.X₁ ⊗ W]₀ := by rw [hrel]
      _ = [S.X₃ ⊗ W]₀ := by abel
  · intro a ha
    -- Negation is respected because the lifted action is additive.
    simpa using congrArg Neg.neg ha
  · intro a₁ a₂ ha₁ ha₂
    -- Addition is respected because the lifted action is additive.
    simpa using congrArg₂ HAdd.hAdd ha₁ ha₂

/-- Tensoring with classes in `R_k(G)` defines the tensor-product self-action on `R_k(G)`. -/
private def finiteRepActionHom :
    R₀[k](G) →+ AddMonoid.End (R₀[k](G)) :=
  QuotientAddGroup.lift
    (finiteRepGrothendieckRelations k G)
    (finiteRepActionLift k G)
    (finiteRepGrothendieckRelations_le_finiteRepActionLift_ker k G)

private instance finiteRepGrothendieckGroup_mul : Mul (R₀[k](G)) where
  mul x y := finiteRepActionHom k G x y

private instance finiteRepGrothendieckGroup_one : One (R₀[k](G)) where
  one := [𝟙_ (FDRep k G)]₀

/-- Helper for Exercise 15-15.1-2: multiplication by a fixed class sends `0` to `0`. -/
theorem finiteRepGrothendieck_mul_zero (x : R₀[k](G)) :
    x * (0 : R₀[k](G)) = 0 := by
  change finiteRepActionHom k G x 0 = 0
  exact (finiteRepActionHom k G x).map_zero

/-- Helper for Exercise 15-15.1-2: the zero class acts trivially on `R₀[k](G)`. -/
theorem finiteRepGrothendieck_zero_mul (x : R₀[k](G)) :
    (0 : R₀[k](G)) * x = 0 := by
  change finiteRepActionHom k G 0 x = 0
  exact congrArg (fun f : AddMonoid.End (R₀[k](G)) ↦ f x)
    ((finiteRepActionHom k G).map_zero)

/-- Helper for Exercise 15-15.1-2: multiplication on `R₀[k](G)` is additive in its second
argument. -/
theorem finiteRepGrothendieck_mul_add
    (x y z : R₀[k](G)) :
    x * (y + z) = x * y + x * z := by
  change finiteRepActionHom k G x (y + z) =
    finiteRepActionHom k G x y + finiteRepActionHom k G x z
  exact (finiteRepActionHom k G x).map_add y z

/-- Helper for Exercise 15-15.1-2: multiplication on `R₀[k](G)` is additive in its first
argument. -/
theorem finiteRepGrothendieck_add_mul
    (x y z : R₀[k](G)) :
    (x + y) * z = x * z + y * z := by
  change finiteRepActionHom k G (x + y) z =
    finiteRepActionHom k G x z + finiteRepActionHom k G y z
  exact congrArg (fun f : AddMonoid.End (R₀[k](G)) ↦ f z)
    ((finiteRepActionHom k G).map_add x y)

/-- Helper for Exercise 15-15.1-2: multiplication on `R₀[k](G)` sends negatives in the second
argument to negatives. -/
theorem finiteRepGrothendieck_mul_neg
    (x y : R₀[k](G)) :
    x * (-y) = -(x * y) := by
  change finiteRepActionHom k G x (-y) = -finiteRepActionHom k G x y
  exact (finiteRepActionHom k G x).map_neg y

/-- Helper for Exercise 15-15.1-2: multiplication on `R₀[k](G)` sends negatives in the first
argument to negatives. -/
theorem finiteRepGrothendieck_neg_mul
    (x y : R₀[k](G)) :
    (-x) * y = -(x * y) := by
  change finiteRepActionHom k G (-x) y = -finiteRepActionHom k G x y
  exact congrArg (fun f : AddMonoid.End (R₀[k](G)) ↦ f y)
    ((finiteRepActionHom k G).map_neg x)

-- Proof sketch: descend to generator classes and compare the two tensorings by the monoidal
-- associator.
/-- Helper for Exercise 15-15.1-2: tensor-product multiplication on `R₀[k](G)` is associative. -/
private theorem finiteRepGrothendieck_mul_assoc (x y z : R₀[k](G)) :
    x * y * z = x * (y * z) := by
  refine QuotientAddGroup.induction_on x ?_
  intro a
  refine QuotientAddGroup.induction_on y ?_
  intro b
  refine QuotientAddGroup.induction_on z ?_
  intro c
  refine FreeAbelianGroup.induction_on a ?_ ?_ ?_ ?_
  · change ((0 : R₀[k](G)) * (b : R₀[k](G))) * (c : R₀[k](G)) =
        (0 : R₀[k](G)) * ((b : R₀[k](G)) * (c : R₀[k](G)))
    rw [finiteRepGrothendieck_zero_mul, finiteRepGrothendieck_zero_mul,
      finiteRepGrothendieck_zero_mul]
  · intro V
    refine FreeAbelianGroup.induction_on b ?_ ?_ ?_ ?_
    · simp [finiteRepGrothendieck_mul_zero, finiteRepGrothendieck_zero_mul]
    · intro W
      refine FreeAbelianGroup.induction_on c ?_ ?_ ?_ ?_
      · simp [finiteRepGrothendieck_mul_zero]
      · intro U
        change [((V ⊗ W) ⊗ U)]₀ = [V ⊗ (W ⊗ U)]₀
        exact finiteRepGrothendieckClass_eq_of_nonempty_iso
          (L := k) (G := G) ⟨α_ V W U⟩
      · intro c hc
        simp [finiteRepGrothendieck_mul_neg, hc]
      · intro c₁ c₂ hc₁ hc₂
        simp [finiteRepGrothendieck_mul_add, hc₁, hc₂]
    · intro b hb
      simp [finiteRepGrothendieck_mul_neg, finiteRepGrothendieck_neg_mul, hb]
    · intro b₁ b₂ hb₁ hb₂
      simp [finiteRepGrothendieck_mul_add, finiteRepGrothendieck_add_mul, hb₁, hb₂]
  · intro a ha
    simp [finiteRepGrothendieck_neg_mul, ha]
  · intro a₁ a₂ ha₁ ha₂
    simp [finiteRepGrothendieck_add_mul, ha₁, ha₂]

-- Proof sketch: descend to generator classes and compare the two tensor orders by the braiding.
/-- Helper for Exercise 15-15.1-2: tensor-product multiplication on `R₀[k](G)` is commutative. -/
private theorem finiteRepGrothendieck_mul_comm (x y : R₀[k](G)) :
    x * y = y * x := by
  refine QuotientAddGroup.induction_on x ?_
  intro a
  refine QuotientAddGroup.induction_on y ?_
  intro b
  refine FreeAbelianGroup.induction_on a ?_ ?_ ?_ ?_
  · simp [finiteRepGrothendieck_zero_mul, finiteRepGrothendieck_mul_zero]
  · intro V
    refine FreeAbelianGroup.induction_on b ?_ ?_ ?_ ?_
    · simp [finiteRepGrothendieck_mul_zero, finiteRepGrothendieck_zero_mul]
    · intro W
      change [V ⊗ W]₀ = [W ⊗ V]₀
      exact finiteRepGrothendieckClass_eq_of_nonempty_iso
        (L := k) (G := G) ⟨β_ V W⟩
    · intro b hb
      simp [finiteRepGrothendieck_mul_neg, finiteRepGrothendieck_neg_mul, hb]
    · intro b₁ b₂ hb₁ hb₂
      simp [finiteRepGrothendieck_mul_add, finiteRepGrothendieck_add_mul, hb₁, hb₂]
  · intro a ha
    simp [finiteRepGrothendieck_mul_neg, finiteRepGrothendieck_neg_mul, ha]
  · intro a₁ a₂ ha₁ ha₂
    simp [finiteRepGrothendieck_mul_add, finiteRepGrothendieck_add_mul, ha₁, ha₂]

-- Proof sketch: descend to generator classes and compare `𝟙 ⊗ V` with `V` by the left unitor.
/-- Helper for Exercise 15-15.1-2: the tensor-unit class is a left unit for multiplication. -/
private theorem finiteRepGrothendieck_one_mul (x : R₀[k](G)) :
    1 * x = x := by
  refine QuotientAddGroup.induction_on x ?_
  intro a
  refine FreeAbelianGroup.induction_on a ?_ ?_ ?_ ?_
  · simp [finiteRepGrothendieck_mul_zero]
  · intro V
    change [((𝟙_ (FDRep k G)) ⊗ V)]₀ = [V]₀
    exact finiteRepGrothendieckClass_eq_of_nonempty_iso
      (L := k) (G := G) ⟨λ_ V⟩
  · intro a ha
    simp [finiteRepGrothendieck_mul_neg, ha]
  · intro a₁ a₂ ha₁ ha₂
    simp [finiteRepGrothendieck_mul_add, ha₁, ha₂]

/-- Helper for Exercise 15-15.1-2: the tensor-unit class is a right unit for multiplication. -/
private theorem finiteRepGrothendieck_mul_one (x : R₀[k](G)) :
    x * 1 = x := by
  rw [finiteRepGrothendieck_mul_comm, finiteRepGrothendieck_one_mul]

/-- Tensor-product multiplication makes `R_k(G)` into Serre's representation ring.

The additive part reuses the canonical quotient `AddCommGroup` structure on `R₀[k](G)`
field-by-field, so this instance does not introduce a second, non-definitionally-equal additive
structure (and hence no `ℤ`-module diamond) on the Grothendieck group. -/
instance finiteRepGrothendieckGroup_commRing :
    CommRing (R₀[k](G)) :=
  { (inferInstance : AddCommGroup (R₀[k](G))),
    finiteRepGrothendieckGroup_mul k G,
    finiteRepGrothendieckGroup_one k G with
    left_distrib := finiteRepGrothendieck_mul_add k G
    right_distrib := finiteRepGrothendieck_add_mul k G
    zero_mul := finiteRepGrothendieck_zero_mul k G
    mul_zero := finiteRepGrothendieck_mul_zero k G
    mul_assoc := finiteRepGrothendieck_mul_assoc k G
    one_mul := finiteRepGrothendieck_one_mul k G
    mul_one := finiteRepGrothendieck_mul_one k G
    mul_comm := finiteRepGrothendieck_mul_comm k G }

/-- Multiplication of Grothendieck classes is represented by the tensor product. -/
theorem finiteRepGrothendieckClass_mul (V W : FDRep k G) :
    [V]₀ * [W]₀ = [V ⊗ W]₀ := by
  -- On generator classes, multiplication is exactly the quotient lift defined above.
  rfl

end FiniteRepTensorRing

end Representation
