import Mathlib
import CombinatorialGroupTheory_Magnus_2004.Chap01.Definition_1_1_1
import CombinatorialGroupTheory_Magnus_2004.Chap01.Proposition_1_3_7

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open FreeGroup
open QuotientGroup

/-!
Primary domain: Schreier transversals and Schreier generators for subgroups of free groups.

Layer triage:
- `source-facing`: a subgroup `H ≤ FreeGroup X`, a chosen right transversal `T`, and the textbook
  minimality condition saying that the chosen representative in each right coset has least
  reduced-word length.
- `core/canonical`: `Subgroup.RightTransversal`, `rightRel H`, `IsComplement.toRightFun`, and the
  existing chapter owners `HasInitialSegments`, `schreierGeneratorSet`, and
  `schreierGeneratorSet_isFreeGroupBasis`.
- `bridge/view`: the textbook representative `\bar w` is the canonical selector `T.2.toRightFun w`,
  while “minimal Schreier transversal” is the owner predicate `T.IsMinimalSchreier` layered on top
  of the right-transversal data.

Domain sampling:
1. `Subgroup.RightTransversal` in mathlib is the owner abstraction for chosen right-coset
   representatives.
2. `QuotientGroup.rightRel` is the canonical same-right-coset relation.
3. `IsComplement.toRightFun` and `IsComplement.mul_inv_toRightFun_mem` are the owner APIs for the
   canonical representative map and the associated subgroup element `g * \bar g⁻¹`.
4. `HasInitialSegments`, `schreierGeneratorSet`, and
   `schreierGeneratorSet_isFreeGroupBasis` in Propositions `1-3-22` and `1-3-7` are the existing
   chapter owners for the Schreier prefix condition and the free-basis conclusion attached to a
   transversal.

Primitive vs. derived:
- primitive public data: only `H`, `T`, and the source-facing minimality predicate;
- derived API: the Schreier initial-segment condition, the canonical subgroup identity
  `Subgroup.closure (schreierGeneratorSet ...) = H`, the induced free-basis statement, and the
  `N`-reduced conclusion.
-/

section

variable {X : Type u} [DecidableEq X]
variable {H : Subgroup (FreeGroup X)}

namespace Subgroup.RightTransversal

/-- A minimal Schreier transversal is a right transversal whose chosen representative in each
right coset has minimal reduced-word length within that coset. -/
def IsMinimalSchreier (T : H.RightTransversal) : Prop :=
  ∀ ⦃t w : FreeGroup X⦄, t ∈ (T : Set (FreeGroup X)) → rightRel H t w → norm t ≤ norm w

/-- A minimal Schreier transversal is closed under taking initial segments of reduced words. -/
-- Layer triage:
-- `source-facing`: the textbook Schreier-prefix property for a minimal transversal.
-- `core/canonical`: `HasInitialSegments` is the chapter owner predicate for closure under
-- initial segments, while `rightRel H` is the owner same-coset relation from mathlib.
-- `bridge/view`: this theorem converts the owner minimality predicate `T.IsMinimalSchreier` to
-- the chapter Schreier-transversal predicate `HasInitialSegments (T : Set (FreeGroup X))`.
-- Proof sketch: if `t ∈ T`, every initial segment of the reduced word for `t` lies in the same
-- right coset as a shorter representative. Minimality forces that shorter representative itself to
-- be the initial segment, so the initial segment remains in `T`.
theorem hasInitialSegments {T : H.RightTransversal} (hT : T.IsMinimalSchreier) :
    HasInitialSegments (T : Set (FreeGroup X)) := sorry

end Subgroup.RightTransversal

end

section

variable {X : Type u}
variable {H : Subgroup (FreeGroup X)}

namespace Subgroup.RightTransversal

/-- The nontrivial Schreier generators attached to a right transversal generate the subgroup whose
cosets the transversal represents. -/
-- Layer triage:
-- `source-facing`: the textbook subgroup `Gp({γ(tx) ≠ 1})`.
-- `core/canonical`: `Subgroup.closure`, `H.RightTransversal`, and mathlib's owner theorem
-- `Subgroup.closure_mul_image_eq_top`.
-- `bridge/view`: `schreierGeneratorSet (T : Set (FreeGroup X)) T.2.toRightFun` is the chapter's
-- source-facing presentation of the owner-side Schreier generating family.
-- Proof sketch: `Set.range FreeGroup.of` generates the ambient free group, so the owner theorem
-- `Subgroup.closure_mul_image_eq_top` applied to the transversal `T` shows that the subgroup of
-- `H` generated by the canonical elements `w * \bar w⁻¹` is all of `H`. Removing the trivial
-- generator `1` does not change the closure, yielding the displayed equality in the ambient free
-- group.
theorem closure_schreierGeneratorSet_eq {T : H.RightTransversal} :
    Subgroup.closure (schreierGeneratorSet (T : Set (FreeGroup X)) T.2.toRightFun) = H := sorry

end Subgroup.RightTransversal

end

section

variable {X : Type u} [DecidableEq X]
variable {H : Subgroup (FreeGroup X)}

-- Layer triage:
-- `source-facing`: the subgroup `H` together with the textbook Schreier generators `γ(tx)`.
-- `core/canonical`: Proposition `1-3-7` already owns the free-basis statement for the subgroup
-- generated by a Schreier transversal with initial segments.
-- `bridge/view`: this theorem specializes that owner basis theorem to the ambient subgroup `H`
-- by using the owner minimality predicate `T.IsMinimalSchreier` to obtain `HasInitialSegments`
-- and the owner-level subgroup identity `T.closure_schreierGeneratorSet_eq`.
-- Proof sketch: minimality gives the initial-segment property, so Proposition `1-3-7` supplies a
-- free basis of the subgroup generated by the Schreier generators. The canonical bridge
-- `T.closure_schreierGeneratorSet_eq` then identifies that generated subgroup with `H`.
namespace Subgroup.RightTransversal

/-- The nontrivial Schreier generators coming from a minimal Schreier transversal form a free basis
of the subgroup `H`. -/
theorem schreierGeneratorSet_isFreeGroupBasis {T : H.RightTransversal} (hT : T.IsMinimalSchreier) :
    IsFreeGroupBasis
      { y : H | (y : FreeGroup X) ∈ schreierGeneratorSet (T : Set (FreeGroup X)) T.2.toRightFun } :=
  sorry

/-- Proposition 1-3-20: for a subgroup `H` of the free group on `X`, if `T` is a minimal
Schreier transversal for `H`, then the nontrivial Schreier generators `γ(tx)` form an
`N`-reduced set. Together with the companion basis theorem above, this is the textbook statement
that they form an `N`-reduced basis of `H`. -/
-- Layer triage:
-- `source-facing`: the textbook `N`-reducedness condition for the Schreier generators of a
-- minimal Schreier transversal.
-- `core/canonical`: `FreeGroup.IsNReduced` is the owner predicate for Nielsen reducedness.
-- `bridge/view`: the generators are still the chapter owner set
-- `schreierGeneratorSet (T : Set (FreeGroup X)) T.2.toRightFun` attached to the right
-- transversal `T`.
-- Proof sketch: apply Nielsen's cancellation criteria to products of the generators
-- `γ(tx) = t * of x * \overline{tx}⁻¹`. Minimality controls how much cancellation can occur in
-- adjacent products, forcing the middle letter to survive in triple products and yielding the
-- inequalities `(N1)` and `(N2)`.
theorem schreierGeneratorSet_isNReduced {T : H.RightTransversal} (hT : T.IsMinimalSchreier) :
    FreeGroup.IsNReduced (schreierGeneratorSet (T : Set (FreeGroup X)) T.2.toRightFun) := sorry

end Subgroup.RightTransversal

end
