import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open scoped BigOperators
open MvPolynomial

universe u v

/- Domain-style sampling for `Definition_16_2_3`:
- primary domain: finite presentations of commutative algebras, Jacobian matrices/minors, and the
  Chapter 16 source-facing predicates of elementary and strict standardness;
- sampled owner API:
  `Algebra.Presentation`,
  `Algebra.Presentation.relation_mem_ker`,
  `Algebra.Presentation.quotientEquiv_mk`,
  `Algebra.Presentation.quotientEquiv_symm`,
  `Algebra.IsStandardSmooth.out`;
- best owner abstraction: the source-facing owners in this file should live on
  `Algebra.Presentation`; the primitive presentation-level lift data should use the canonical
  quotient owner `P.quotientEquiv` and relation-to-kernel API already bundled there, while the
  global predicates on `a : A` remain source-facing existential wrappers over a finite
  presentation and should not be collapsed into the later standard-smooth owner
  `Algebra.IsStandardSmooth`;
- primitive vs. derived:
  the primitive data are a finite presentation `P`, the first-`c` relation ideal, and the
  Jacobian matrix of the first `c` relations against all variables, together with the intrinsic
  tail condition on lifts of `a` to `P.Ring`;
  `leadingJacobianDet` and the column minors are derived from that matrix, while the deleted
  exact-unfolding `_iff` wrappers were only redundant derived API.

Source/core/bridge triage:
- `source-facing`: `IsElementaryStandardElement`, `IsStrictlyStandardElement`,
  `IsElementaryStandard`, and `IsStrictlyStandard`;
- `core/canonical`: the ambient presentation owner `Algebra.Presentation` and its Jacobian matrix;
- `bridge/view`: the determinant/minor expressions and the existential passage from a specific
  presentation witness to the global predicates on `a`.
-/

namespace Algebra.Presentation

variable {R : Type u} {A : Type v} [CommRing R] [CommRing A] [Algebra R A]
variable {n m c : ℕ}

/-- The index of the relation `f_{c + j}` among the `m` relations of a finite presentation. -/
def tailRelationIndex (hc : c ≤ m) : Fin (m - c) → Fin m :=
  Fin.cast (Nat.add_sub_of_le hc) ∘ Fin.natAdd c

/-- The ideal generated by the first `c` relations of a finite presentation. -/
noncomputable def leadingRelationIdeal
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (hc : c ≤ m) : Ideal P.Ring :=
  Ideal.span (Set.range fun i : Fin c ↦ P.relation (Fin.castLE hc i))

/-- The tail ideal-membership condition from Definition 16.2.3, stated intrinsically in the
presentation ring by requiring some lift of `a` to satisfy the displayed congruences. -/
def tailRelationCondition
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (a : A) (hcₘ : c ≤ m) : Prop :=
  ∃ a₀ : P.Ring,
    algebraMap P.Ring A a₀ = a ∧
      ∀ j : Fin (m - c),
        a₀ * P.relation (tailRelationIndex hcₘ j) ∈
          P.leadingRelationIdeal hcₘ + P.ker ^ 2

/-- The intrinsic tail condition is equivalent to checking the same congruences on the arbitrary
chosen section `P.σ a`; the difference between any two lifts lies in `P.ker`, so multiplying by a
tail relation changes the condition only by an element of `P.ker ^ 2`. -/
theorem tailRelationCondition_iff_sigma
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (a : A) (hcₘ : c ≤ m) :
    P.tailRelationCondition a hcₘ ↔
      ∀ j : Fin (m - c),
        P.σ a * P.relation (tailRelationIndex hcₘ j) ∈
          P.leadingRelationIdeal hcₘ + P.ker ^ 2 := by
  constructor
  · rintro ⟨a₀, ha₀, htail⟩ j
    let r : P.Ring := P.relation (tailRelationIndex hcₘ j)
    have hk : P.σ a - a₀ ∈ P.ker := by
      apply (Ideal.Quotient.eq).mp
      apply P.quotientEquiv.injective
      rw [P.quotientEquiv_mk, P.quotientEquiv_mk]
      simpa [ha₀, P.algebraMap_apply] using P.aeval_val_σ a
    have hr : r ∈ P.ker := by
      dsimp [r]
      exact P.relation_mem_ker _
    have hsq : (P.σ a - a₀) * r ∈ P.ker ^ 2 := by
      simpa [pow_two] using Ideal.mul_mem_mul hk hr
    have hdecomp : P.σ a * r = a₀ * r + (P.σ a - a₀) * r := by
      ring
    rw [hdecomp]
    exact Ideal.add_mem _ (htail j) (Ideal.mem_sup_right hsq)
  · intro h
    exact ⟨P.σ a, by simp [P.algebraMap_apply], h⟩

/-- The `c × n` Jacobian matrix built from the first `c` relations of a finite presentation. -/
noncomputable def jacobianMatrix
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (hcₘ : c ≤ m) : Matrix (Fin c) (Fin n) P.Ring :=
  fun j i ↦ pderiv i (P.relation (Fin.castLE hcₘ j))

/-- The `c × c` leading Jacobian determinant built from the first `c` relations and first `c`
variables of a finite presentation. -/
noncomputable def leadingJacobianDet
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (hcₙ : c ≤ n) (hcₘ : c ≤ m) : P.Ring :=
  Matrix.det ((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (Fin.castLE hcₙ))

/-- The Jacobian minor indexed by a `c`-element subset of the variables. -/
noncomputable def jacobianColumnMinor
    (P : Algebra.Presentation R A (Fin n) (Fin m))
    (hcₘ : c ≤ m) (I : Set.powersetCard (Fin n) c) : P.Ring :=
  Matrix.det ((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (I.1.orderEmbOfFin I.2))

/-- The presentation-specific witness that `a` is elementary standard for the chosen finite
presentation. The second displayed condition is phrased intrinsically via
`P.tailRelationCondition a hcₘ`, equivalently by
`P.tailRelationCondition_iff_sigma a hcₘ`. -/
def IsElementaryStandardElement
    (P : Algebra.Presentation R A (Fin n) (Fin m)) (a : A) : Prop :=
  ∃ (c : ℕ) (hcₙ : c ≤ n) (hcₘ : c ≤ m) (a' : A),
    a = a' * algebraMap P.Ring A (P.leadingJacobianDet hcₙ hcₘ) ∧
      P.tailRelationCondition a hcₘ

/-- The presentation-specific witness that `a` is strictly standard for the chosen finite
presentation. The strict Jacobian expansion is indexed by the `c`-element subsets of the
variables, and the shared tail condition is the intrinsic predicate
`P.tailRelationCondition a hcₘ`. -/
def IsStrictlyStandardElement
    (P : Algebra.Presentation R A (Fin n) (Fin m)) (a : A) : Prop :=
  ∃ (c : ℕ) (hcₘ : c ≤ m) (aI : Set.powersetCard (Fin n) c → A),
    a = ∑ I : Set.powersetCard (Fin n) c,
        aI I * algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I) ∧
      P.tailRelationCondition a hcₘ

end Algebra.Presentation

namespace Algebra

section

variable {R : Type u} [CommRing R] {A : Type v} [CommRing A] [Algebra R A]
variable (R)

open Presentation

/-- Definition 16.2.3 (1): an element `a : A` is elementary standard over `R` if some finite
presentation `A = R[x₁, ..., xₙ] / (f₁, ..., fₘ)` and some `0 ≤ c ≤ min (n, m)` witness the
leading Jacobian determinant identity and the tail ideal-membership condition from the text. -/
def IsElementaryStandard (a : A) : Prop :=
  ∃ (n m : ℕ) (P : Presentation R A (Fin n) (Fin m)),
    P.IsElementaryStandardElement a

/-- Definition 16.2.3 (2): an element `a : A` is strictly standard over `R` if some finite
presentation `A = R[x₁, ..., xₙ] / (f₁, ..., fₘ)` and some `0 ≤ c ≤ min (n, m)` write `a` as an
`A`-linear combination of the `c × c` Jacobian minors and satisfy the same tail ideal-membership
condition. -/
def IsStrictlyStandard (a : A) : Prop :=
  ∃ (n m : ℕ) (P : Presentation R A (Fin n) (Fin m)),
    P.IsStrictlyStandardElement a

end

end Algebra
