import Mathlib
import StacksProject_2024.stacks_project.Chap10.Lemma_10_15_5
import StacksProject_2024.stacks_project.Chap16.Definition_16_2_1
import StacksProject_2024.stacks_project.Chap16.Definition_16_2_3
import StacksProject_2024.stacks_project.Chap16.«16_7_1_1»
import StacksProject_2024.stacks_project.Chap16.Lemma_16_3_6
import StacksProject_2024.stacks_project.Chap16.Lemma_16_2_5_Elkik

-- Declarations for this item will be appended below by the statement pipeline.

universe u v w

namespace Algebra

open Algebra.Presentation
open scoped SingularIdealNotation

section

variable {R : Type u} {A : Type v} {Λ : Type w}
variable [CommRing R] [CommRing A] [CommRing Λ]
variable [Algebra R A] [Algebra R Λ]

variable (π : R)

local notation "I4" => Ideal.span ({π ^ 4} : Set R)
local notation "R4" => R ⧸ I4
local notation "I4A" => Ideal.map (algebraMap R A) I4
local notation "I4Λ" => Ideal.map (algebraMap R Λ) I4
local notation "A4" => A ⧸ I4A
local notation "Λ4" => Λ ⧸ I4Λ
local notation "AnnR[" x "]" => Ideal.torsionOf R R x
local notation "AnnΛ[" x "]" => Ideal.torsionOf Λ Λ x

/-
Domain-style sampling for Lemma 16.7.1:
- primary domain: commutative algebra of finite-presentation `R`-algebras, quotient algebra maps,
  strict-standard elements, and the singular ideal `H[B⁄R]`;
- sampled owner declarations:
  `Ideal.torsionOf`,
  `Module.annihilator`,
  `Algebra.IsStrictlyStandard`,
  `Algebra.singularIdeal`,
  `Ideal.quotientMapₐ`,
  `Ideal.Quotient.algebraQuotientOfLEComap`;
- best owner abstraction: the source-facing theorem stays an existence statement, with
  the quotient-element annihilators expressed through `Ideal.torsionOf`, the outer quotient-module
  annihilator expressed through `Module.annihilator`, and the mod-`π⁴` comparison map used
  through the named bridge `piPowFourQuotientMap π f`, built from the canonical quotient-map owner
  `Ideal.quotientMapₐ`;
- primitive data: `f : A →ₐ[R] Λ`, the strict-standardness witness for `π`, the annihilator
  equality in `Λ`, and a compatible `R4`-algebra section `A4 →ₐ[R4] R4`;
- derived API: the compatibility equation between the section and the canonical quotient map to
  `Λ4`.

Source/core/bridge triage:
- `source-facing`: the factorization theorem below, with the source ideal written directly as
  `Ann_R(Ann_R(π²) / Ann_R(π))`;
- `core/canonical`: `Ideal.torsionOf`, `Module.annihilator`, `IsStrictlyStandard`, `H[B⁄R]`, and
  `Ideal.quotientMapₐ`;
- `bridge/view`: `piPowFourQuotientMap π f` and the section-compatibility equation.
-/

/-- The ideal generated by `π⁴` maps into the corresponding quotient ideal along any `R`-algebra
map. -/
private theorem map_piPowFour_le_comap_map_piPowFour
    {S : Type*} {T : Type*} [CommRing S] [CommRing T] [Algebra R S] [Algebra R T]
    (f : S →ₐ[R] T) :
    Ideal.map (algebraMap R S) I4 ≤
      Ideal.comap f (Ideal.map (algebraMap R T) I4) := by
  simpa [Ideal.map_map] using
    (show Ideal.map (algebraMap R S) I4 ≤
        Ideal.comap (f : S →+* T) (Ideal.map (f : S →+* T) (Ideal.map (algebraMap R S) I4)) from
      Ideal.le_comap_map)

/-- The reduction modulo `π⁴` induced by an `R`-algebra map. -/
def piPowFourQuotientMap
    (f : A →ₐ[R] Λ) :
    A4 →ₐ[R4] Λ4 :=
  { toRingHom := (Ideal.quotientMapₐ I4Λ f (map_piPowFour_le_comap_map_piPowFour π f)).toRingHom
    commutes' := by
      intro r
      refine Quotient.inductionOn' r fun r ↦ ?_
      change Ideal.Quotient.mk I4Λ (f (algebraMap R A r)) =
        Ideal.Quotient.mk I4Λ (algebraMap R Λ r)
      rw [f.commutes] }

/-- Helper for Lemma 16.7.1: a strict-standard witness already packages a finite presentation of
the ambient algebra. -/
private theorem finitePresentation_of_isStrictlyStandard {a : A}
    (h : IsStrictlyStandard R a) :
    FinitePresentation R A := by
  -- A strict-standard witness is given by a finite presentation indexed by finite sets.
  rcases h with ⟨n, m, P, _hP⟩
  exact P.finitePresentation_of_isFinite

/-- Helper for Lemma 16.7.1: every strictly standard element of a finitely presented algebra lies
in the singular ideal. -/
private theorem mem_singularIdeal_of_isStrictlyStandard [FinitePresentation R A] {a : A}
    (ha : IsStrictlyStandard R a) :
    a ∈ H[A⁄R] := by
  -- Elkik identifies the singular ideal with the radical generated by strictly standard elements.
  rw [singularIdeal_eq_radical_span_strictlyStandard]
  exact Ideal.le_radical (Ideal.subset_span ha)

/-- Helper for Lemma 16.7.1: the quotient module `Ann_R(π²) / Ann_R(π)` appearing in the
statement. -/
private abbrev quotient_annihilator_module (π : R) :=
  AnnR[π ^ 2] ⧸ Submodule.comap (AnnR[π ^ 2]).subtype AnnR[π]

/-- Helper for Lemma 16.7.1: the quotient `Ann_R(π²) / Ann_R(π)` is annihilated by `π`. -/
private theorem pi_mem_annihilator_quotient_annR :
    π ∈ Module.annihilator R (quotient_annihilator_module (R := R) π) := by
  rw [Module.mem_annihilator]
  intro x
  obtain ⟨x, rfl⟩ :=
    (Submodule.Quotient.mk_surjective
      (p := Submodule.comap (AnnR[π ^ 2]).subtype AnnR[π])) x
  -- Passing to the quotient, it is enough to show `π • x` already lands in `Ann_R(π)`.
  rw [← Submodule.Quotient.mk_smul]
  rw [Submodule.Quotient.mk_eq_zero]
  rw [Submodule.mem_comap]
  -- The defining property of `x ∈ Ann_R(π²)` rewrites exactly to the desired annihilation.
  rw [Ideal.mem_torsionOf_iff]
  have hx : (x : R) • (π ^ 2) = 0 := by
    have hxmem : (x : R) ∈ AnnR[π ^ 2] := x.2
    rw [Ideal.mem_torsionOf_iff] at hxmem
    exact hxmem
  simpa [pow_two, smul_smul, mul_assoc, mul_left_comm, mul_comm] using hx

/-- Helper for Lemma 16.7.1: over a Noetherian base ring, the quotient module
`Ann_R(π²) / Ann_R(π)` is finite. -/
private theorem quotient_annihilator_module_finite [IsNoetherianRing R] :
    Module.Finite R (quotient_annihilator_module (R := R) π) := by
  -- The quotient of a submodule of the finite module `R` is again finite.
  infer_instance

/-- Helper for Lemma 16.7.1: after a flat base change, inverting any element of
`Ann_R(Ann_R(π²) / Ann_R(π))` forces the base-changed quotient module to vanish. This isolates
the algebraic part of the over-`π` localization argument before the quotient-comparison geometry is
reintroduced. -/
private theorem baseChange_quotient_annihilator_subsingleton_of_annihilator_unit
    [IsNoetherianRing R]
    {S : Type*} [CommRing S] [Algebra R S] [Module.Flat R S]
    {r : R}
    (hr : r ∈ Module.annihilator R (quotient_annihilator_module (R := R) π))
    (hrunit : IsUnit (algebraMap R S r)) :
    Subsingleton (S ⊗[R] quotient_annihilator_module (R := R) π) := by
  let M := S ⊗[R] quotient_annihilator_module (R := R) π
  have hrmap :
      algebraMap R S r ∈ Module.annihilator S M := by
    -- Flat base change identifies the annihilator of the quotient module with the extended ideal.
    have hmem :
        algebraMap R S r ∈
          Ideal.map (algebraMap R S) (Module.annihilator R (quotient_annihilator_module (R := R) π)) :=
      Ideal.mem_map_of_mem (algebraMap R S) hr
    rw [Module.map_annihilator_eq_annihilator_baseChange_of_flat
      (R := R) (S := S) (M := quotient_annihilator_module (R := R) π)] at hmem
    simpa [M] using hmem
  have htop : Module.annihilator S M = ⊤ := by
    -- A unit inside an ideal forces that ideal to be the whole ring.
    exact (Module.annihilator S M).eq_top_of_isUnit_mem hrmap hrunit
  have hone : (1 : S) ∈ Module.annihilator S M := by
    simpa [htop]
  rw [Module.mem_annihilator] at hone
  -- Once `1` lies in the annihilator, every element of the base-changed quotient module is zero.
  refine ⟨fun x y ↦ ?_⟩
  have hx : x = 0 := by
    simpa using hone x
  have hy : y = 0 := by
    simpa using hone y
  exact hx.trans hy.symm

/-- Helper for Lemma 16.7.1: a compatible section modulo `π⁴` chooses a base-ring lift of any
element of `A`, and the original map differs from that lift by a `π⁴`-multiple in `Λ`. -/
private theorem exists_baseLift_of_compatible_piPowFour_section
    (f : A →ₐ[R] Λ)
    {ρ : A4 →ₐ[R4] R4}
    (hρcompat : (Algebra.ofId R4 Λ4).comp ρ = piPowFourQuotientMap π f)
    (a : A) :
    ∃ r : R, ρ (Ideal.Quotient.mk I4A a) = Ideal.Quotient.mk I4 r ∧
      ∃ l : Λ, f a = algebraMap R Λ r + algebraMap R Λ (π ^ 4) * l := by
  obtain ⟨r, hr⟩ := Ideal.Quotient.mk_surjective (I := I4) (ρ (Ideal.Quotient.mk I4A a))
  refine ⟨r, hr.symm, ?_⟩
  have hquot :
      Ideal.Quotient.mk I4Λ (f a) = Ideal.Quotient.mk I4Λ (algebraMap R Λ r) := by
    -- The section compatibility identifies the two reductions modulo `π⁴`.
    have hcompat := DFunLike.congr_fun hρcompat (Ideal.Quotient.mk I4A a)
    calc
      Ideal.Quotient.mk I4Λ (f a) =
          (Algebra.ofId R4 Λ4) (ρ (Ideal.Quotient.mk I4A a)) := by
            simpa [AlgHom.comp_apply, piPowFourQuotientMap] using hcompat.symm
      _ = (Algebra.ofId R4 Λ4) (Ideal.Quotient.mk I4 r) := by rw [hr.symm]
      _ = Ideal.Quotient.mk I4Λ (algebraMap R Λ r) := by rfl
  have hmem : f a - algebraMap R Λ r ∈ I4Λ := by
    -- Rewriting the quotient equality as membership isolates the `π⁴`-error term.
    exact (Ideal.Quotient.eq (I := I4Λ) (x := f a) (y := algebraMap R Λ r)).mp hquot
  have hmem_span : f a - algebraMap R Λ r ∈ Ideal.span ({algebraMap R Λ (π ^ 4)} : Set Λ) := by
    simpa [Ideal.map_span, Set.image_singleton] using hmem
  rcases Ideal.mem_span_singleton.mp hmem_span with ⟨l, hl⟩
  refine ⟨l, ?_⟩
  calc
    f a = algebraMap R Λ r + (f a - algebraMap R Λ r) := by ring
    _ = algebraMap R Λ r + algebraMap R Λ (π ^ 4) * l := by rw [hl]

/-- Helper for Lemma 16.7.1: under `Ann_Λ(π) = Ann_Λ(π²)`, every `π`-multiple annihilated by
`π³` already vanishes. -/
private theorem eq_zero_of_pi_multiple_of_piCube_eq_zero
    (hAnnΛ : AnnΛ[algebraMap R Λ π] = AnnΛ[algebraMap R Λ (π ^ 2)])
    {t : Λ}
    (ht : t ∈ Ideal.span ({algebraMap R Λ π} : Set Λ))
    (hπ3t : algebraMap R Λ (π ^ 3) * t = 0) :
    t = 0 := by
  let p : Λ := algebraMap R Λ π
  have hAnn : AnnΛ[p] = AnnΛ[p ^ 2] := by
    simpa [p, map_pow] using hAnnΛ
  rcases Ideal.mem_span_singleton.mp ht with ⟨l, rfl⟩
  have hstep : ∀ {x : Λ}, p ^ 2 * x = 0 → p * x = 0 := by
    intro x hx
    have hxmem : x ∈ AnnΛ[p ^ 2] := by
      rw [Ideal.mem_torsionOf_iff]
      calc
        x * p ^ 2 = p ^ 2 * x := by rw [mul_comm]
        _ = 0 := hx
    have hxmem' : x ∈ AnnΛ[p] := by
      simpa [hAnn] using hxmem
    rw [Ideal.mem_torsionOf_iff] at hxmem'
    calc
      p * x = x * p := by rw [mul_comm]
      _ = 0 := hxmem'
  have hpi3t' : p ^ 3 * (p * l) = 0 := by
    simpa [p, map_pow] using hπ3t
  have hpi4 : p ^ 2 * (p ^ 2 * l) = 0 := by
    -- Writing `t = π * l`, the `π³`-vanishing hypothesis becomes a `π⁴`-relation on `l`.
    calc
      p ^ 2 * (p ^ 2 * l) = p ^ 3 * (p * l) := by
        ring_nf
      _ = 0 := hpi3t'
  have hpi3 : p ^ 3 * l = 0 := by
    -- Apply the annihilator equality to `p² * l`.
    have hx : p * (p ^ 2 * l) = 0 := hstep hpi4
    calc
      p ^ 3 * l = p * (p ^ 2 * l) := by
        ring_nf
      _ = 0 := hx
  have hpi2 : p ^ 2 * l = 0 := by
    -- Apply the same step once more to `p * l`.
    have hx : p ^ 2 * (p * l) = 0 := by
      calc
        p ^ 2 * (p * l) = p ^ 3 * l := by
          ring_nf
        _ = 0 := hpi3
    have hy : p * (p * l) = 0 := hstep hx
    calc
      p ^ 2 * l = p * (p * l) := by
        ring_nf
      _ = 0 := hy
  -- A final application gives the required vanishing of `p * l`.
  simpa [p] using hstep hpi2

/-- Helper for Lemma 16.7.1: normalize the strict-standard presentation using the section modulo
`π⁴`, so the presentation generators come from explicit base-ring lifts and the source tail clause
is written with the literal lift of `π` in the presentation ring. -/
private theorem exists_normalized_presentation_section_data
    (f : A →ₐ[R] Λ)
    (hπ : IsStrictlyStandard R (algebraMap R A π))
    {ρ : A4 →ₐ[R4] R4}
    (hρcompat : (Algebra.ofId R4 Λ4).comp ρ = piPowFourQuotientMap π f) :
    ∃ (n m c : ℕ) (P : Presentation R A (Fin n) (Fin m)) (hcₘ : c ≤ m)
      (aI : Set.powersetCard (Fin n) c → A) (r : Fin n → R) (l : Fin n → Λ),
      algebraMap R A π =
        ∑ I : Set.powersetCard (Fin n) c,
          aI I * algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I) ∧
      (∀ j : Fin (m - c),
        algebraMap R P.Ring π * P.relation (tailRelationIndex hcₘ j) ∈
          P.leadingRelationIdeal hcₘ + P.ker ^ 2) ∧
      (∀ i : Fin n,
        ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)) ∧
      (∀ i : Fin n,
        f (P.val i) = algebraMap R Λ (r i) + algebraMap R Λ (π ^ 4) * l i) := by
  classical
  rcases hπ with ⟨n, m, P, hP⟩
  rcases hP with ⟨c, hcₘ, aI, hjac, hTail⟩
  let r : Fin n → R := fun i ↦
    Classical.choose <|
      exists_baseLift_of_compatible_piPowFour_section
        (R := R) (A := A) (Λ := Λ) (π := π) f hρcompat (P.val i)
  let l : Fin n → Λ := fun i ↦
    Classical.choose <|
      (Classical.choose_spec <|
        exists_baseLift_of_compatible_piPowFour_section
          (R := R) (A := A) (Λ := Λ) (π := π) f hρcompat (P.val i)).2
  refine ⟨n, m, c, P, hcₘ, aI, r, l, hjac, ?_, ?_, ?_⟩
  · -- Rewrite the intrinsic tail clause in the source proof's base-ring form.
    exact (P.tailRelationCondition_iff_baseRing π hcₘ).1 hTail
  · intro i
    -- Each presentation generator admits a chosen base-ring lift modulo `π⁴`.
    exact (Classical.choose_spec <|
      exists_baseLift_of_compatible_piPowFour_section
        (R := R) (A := A) (Λ := Λ) (π := π) f hρcompat (P.val i)).1
  · intro i
    -- The original map differs from that lift by an explicit `π⁴`-multiple in `Λ`.
    exact (Classical.choose_spec <|
      (Classical.choose_spec <|
        exists_baseLift_of_compatible_piPowFour_section
          (R := R) (A := A) (Λ := Λ) (π := π) f hρcompat (P.val i)).2)

/-- Helper for Lemma 16.7.1: evaluating any presentation polynomial through the compatible
section amounts to evaluating it at the chosen base-ring lifts of the presentation generators. -/
private theorem section_evaluates_presentation_polynomial_at_generator_lifts
    {n m : ℕ} (P : Presentation R A (Fin n) (Fin m))
    {ρ : A4 →ₐ[R4] R4} {r : Fin n → R}
    (hρval : ∀ i : Fin n,
      ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)) :
    ∀ p : P.Ring,
      ρ (Ideal.Quotient.mk I4A (algebraMap P.Ring A p)) =
        Ideal.Quotient.mk I4 (MvPolynomial.aeval r p) := by
  intro p
  induction p using MvPolynomial.induction_on with
  | C a =>
      -- Constants are preserved because `ρ` is an `R / π⁴R`-algebra map.
      simpa [P.algebraMap_apply, MvPolynomial.aeval_def] using
        (ρ.commutes (Ideal.Quotient.mk I4 a))
  | add p q hp hq =>
      -- The section and quotient maps are ring homomorphisms, so addition is handled termwise.
      simpa [P.algebraMap_apply, map_add] using congrArg₂ (fun x y ↦ x + y) hp hq
  | mul_X p i hp =>
      -- Multiplication by `X i` evaluates at the chosen lift `r i` of `P.val i`.
      simpa [P.algebraMap_apply, MvPolynomial.aeval_def, hρval, map_mul] using
        congrArg (fun x ↦ x * Ideal.Quotient.mk I4 (r i)) hp

/-- Helper for Lemma 16.7.1: after replacing the presentation generators by their chosen
base-ring lifts modulo `π⁴`, each defining relation evaluates into the ideal `(π⁴) ⊂ R`. -/
private theorem relation_values_of_generator_lifts_mem_piPowFour
    {n m : ℕ} (P : Presentation R A (Fin n) (Fin m))
    {ρ : A4 →ₐ[R4] R4} {r : Fin n → R}
    (hρval : ∀ i : Fin n,
      ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)) :
    ∀ j : Fin m, MvPolynomial.aeval r (P.relation j) ∈ I4 := by
  intro j
  have hrel_zero : algebraMap P.Ring A (P.relation j) = 0 := by
    -- The defining relations vanish in `A` because they lie in the presentation kernel.
    simpa [P.algebraMap_apply, RingHom.mem_ker] using P.relation_mem_ker j
  have hquot_zero :
      Ideal.Quotient.mk I4 (MvPolynomial.aeval r (P.relation j)) = 0 := by
    -- Applying the section to the zero relation identifies the evaluated polynomial with zero
    -- in `R / (π⁴)`.
    calc
      Ideal.Quotient.mk I4 (MvPolynomial.aeval r (P.relation j)) =
          ρ (Ideal.Quotient.mk I4A (algebraMap P.Ring A (P.relation j))) := by
            symm
            simpa using
              section_evaluates_presentation_polynomial_at_generator_lifts
                (R := R) (A := A) (π := π) (P := P) (ρ := ρ) (r := r) hρval
                (P.relation j)
      _ = 0 := by simp [hrel_zero]
  exact (Ideal.Quotient.eq_zero_iff_mem (I := I4)).mp hquot_zero

/-- Helper for Lemma 16.7.1: quotienting by the linear relations `X i = β i` computes any
polynomial by direct evaluation at `β`. This is the stable transport bridge for the later
auxiliary quotient construction. -/
private theorem linearRelationQuotientEquiv_mk_eq_aeval
    {S : Type*} [CommRing S] [Algebra R S] {n : ℕ}
    (β : Fin n → S) (p : MvPolynomial (Fin n) S) :
    linearRelationQuotientEquiv β (Ideal.Quotient.mk (linearRelationIdeal β) p) =
      MvPolynomial.aeval β p := by
  -- Induct on the polynomial so the quotient computation reduces to the generator case.
  induction p using MvPolynomial.induction_on with
  | C a =>
      -- Constants are preserved because the quotient equivalence is an `S`-algebra map.
      simpa using (linearRelationQuotientEquiv β).commutes a
  | add p q hp hq =>
      -- Both sides respect addition termwise.
      simpa [map_add] using congrArg₂ (fun x y ↦ x + y) hp hq
  | mul_X p i hp =>
      -- The generator computation is exactly `linearRelationQuotientEquiv_mk_X`.
      calc
        linearRelationQuotientEquiv β (Ideal.Quotient.mk (linearRelationIdeal β) (p * X i)) =
            linearRelationQuotientEquiv β (Ideal.Quotient.mk (linearRelationIdeal β) p) *
              linearRelationQuotientEquiv β (Ideal.Quotient.mk (linearRelationIdeal β) (X i)) := by
                simp [map_mul]
        _ = MvPolynomial.aeval β p * β i := by
              rw [hp, linearRelationQuotientEquiv_mk_X]
        _ = MvPolynomial.aeval β (p * X i) := by
              simp [MvPolynomial.aeval_def, map_mul]

/-- Helper for Lemma 16.7.1: any substitution on the presentation generators that matches the
composed map `A → Λ` kills every defining relation. This is the reusable input needed for the
later map `B → Λ` out of the auxiliary quotient. -/
private theorem relation_aeval_eq_zero_of_generator_image
    {n m : ℕ} (P : Presentation R A (Fin n) (Fin m))
    (f : A →ₐ[R] Λ) (φ : Fin n → Λ)
    (hφ : ∀ i : Fin n, f (P.val i) = φ i) :
    ∀ j : Fin m, MvPolynomial.aeval φ (P.relation j) = 0 := by
  have h_eval :
      ∀ p : P.Ring, f (algebraMap P.Ring A p) = MvPolynomial.aeval φ p := by
    intro p
    induction p using MvPolynomial.induction_on with
    | C a =>
        -- Constants commute with every `R`-algebra map.
        simpa [P.algebraMap_apply, MvPolynomial.aeval_def] using f.commutes a
    | add p q hp hq =>
        -- The presentation map and `aeval` are ring homomorphisms.
        simpa [P.algebraMap_apply, map_add] using congrArg₂ (fun x y ↦ x + y) hp hq
    | mul_X p i hp =>
        -- Multiplication by a generator uses the prescribed image `φ i`.
        calc
          f (algebraMap P.Ring A (p * X i)) =
              f (algebraMap P.Ring A p) * f (P.val i) := by
                simp [P.algebraMap_apply, map_mul]
          _ = MvPolynomial.aeval φ p * φ i := by rw [hp, hφ i]
          _ = MvPolynomial.aeval φ (p * X i) := by
                simp [MvPolynomial.aeval_def, map_mul]
  intro j
  have hrel_zero : algebraMap P.Ring A (P.relation j) = 0 := by
    -- The defining relations lie in the presentation kernel.
    simpa [P.algebraMap_apply, RingHom.mem_ker] using P.relation_mem_ker j
  -- Evaluate the relation through the composed map and rewrite with the presentation kernel fact.
  calc
    MvPolynomial.aeval φ (P.relation j) = f (algebraMap P.Ring A (P.relation j)) := by
      symm
      exact h_eval (P.relation j)
    _ = 0 := by simp [hrel_zero]

/-- Helper for Lemma 16.7.1: evaluating any presentation polynomial after applying an
`R`-algebra map to the presentation generators agrees with first evaluating in `A` and then
applying the algebra map. -/
private theorem presentation_aeval_eq_of_generator_image
    {S : Type*} [CommRing S] [Algebra R S] {n m : ℕ}
    (P : Presentation R A (Fin n) (Fin m))
    (g : A →ₐ[R] S) :
    ∀ p : P.Ring,
      MvPolynomial.aeval (fun i ↦ g (P.val i)) p =
        g (MvPolynomial.aeval P.val p) := by
  intro p
  induction p using MvPolynomial.induction_on with
  | C a =>
      -- Constants commute with every `R`-algebra map.
      simpa [MvPolynomial.aeval_def] using (g.commutes a)
  | add p q hp hq =>
      -- Addition is preserved termwise by polynomial evaluation and by `g`.
      simpa [map_add] using congrArg₂ (fun x y ↦ x + y) hp hq
  | mul_X p i hp =>
      -- Multiplication by a variable evaluates at the chosen image of `P.val i`.
      calc
        MvPolynomial.aeval (fun i ↦ g (P.val i)) (p * X i) =
            MvPolynomial.aeval (fun i ↦ g (P.val i)) p * g (P.val i) := by
              simp [MvPolynomial.aeval_def, map_mul]
        _ = g (MvPolynomial.aeval P.val p) * g (P.val i) := by rw [hp]
        _ = g (MvPolynomial.aeval P.val (p * X i)) := by
              simp [MvPolynomial.aeval_def, map_mul]

/-- Helper for Lemma 16.7.1: each evaluated Jacobian column minor is the corresponding maximal
minor of the constant Jacobian matrix obtained by evaluating the first `c` relations at the chosen
base-ring lifts. -/
private theorem evaluated_jacobianColumnMinor_eq_constantJacobian_minor
    {n m c : ℕ} (P : Presentation R A (Fin n) (Fin m))
    (hcₘ : c ≤ m) (r : Fin n → R) (I : Set.powersetCard (Fin n) c) :
    let J0 : Matrix (Fin c) (Fin n) R :=
      fun j i ↦ MvPolynomial.aeval r ((P.jacobianMatrix hcₘ) j i)
    MvPolynomial.aeval r (P.jacobianColumnMinor hcₘ I) =
      ((J0.transpose).submatrix ((I.1.orderEmbOfFin I.2).toEmbedding)
        (Function.Embedding.refl (Fin c))).det := by
  classical
  let J0 : Matrix (Fin c) (Fin n) R :=
    fun j i ↦ MvPolynomial.aeval r ((P.jacobianMatrix hcₘ) j i)
  have hsub :
      RingHom.mapMatrix (MvPolynomial.aeval r).toRingHom
          ((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (I.1.orderEmbOfFin I.2)) =
        (((J0.transpose).submatrix ((I.1.orderEmbOfFin I.2).toEmbedding)
          (Function.Embedding.refl (Fin c))).transpose) := by
    -- The mapped Jacobian submatrix is the transpose of the corresponding submatrix of the
    -- constant matrix `J0.transpose`.
    ext i j
    rfl
  -- Route correction: make the determinant transport explicit before the quotient-lifting step.
  unfold jacobianColumnMinor
  calc
    MvPolynomial.aeval r
        (((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (I.1.orderEmbOfFin I.2)).det) =
        (RingHom.mapMatrix (MvPolynomial.aeval r).toRingHom
          ((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (I.1.orderEmbOfFin I.2))).det := by
          simpa using
            (RingHom.map_det (MvPolynomial.aeval r).toRingHom
              ((P.jacobianMatrix hcₘ).submatrix (fun i ↦ i) (I.1.orderEmbOfFin I.2)))
    _ = ((((J0.transpose).submatrix ((I.1.orderEmbOfFin I.2).toEmbedding)
          (Function.Embedding.refl (Fin c))).transpose)).det := by
          rw [hsub]
    _ = (((J0.transpose).submatrix ((I.1.orderEmbOfFin I.2).toEmbedding)
          (Function.Embedding.refl (Fin c)))).det := by
          rw [Matrix.det_transpose]

/-- Helper for Lemma 16.7.1: applying the compatible section to the strict-standard Jacobian
expansion produces a concrete equality in `R / (π⁴)` whose coefficients are honest lifts in `R`.
This isolates the source step “apply the section to the strict-standard identity and lift the
resulting coefficients from the quotient ring”. -/
private theorem section_applied_to_jacobian_minor_expansion_mod_piPowFour
    {n m c : ℕ} (P : Presentation R A (Fin n) (Fin m)) (hcₘ : c ≤ m)
    (aI : Set.powersetCard (Fin n) c → A)
    (hjac : algebraMap R A π =
      ∑ I : Set.powersetCard (Fin n) c,
        aI I * algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I))
    {ρ : A4 →ₐ[R4] R4} {r : Fin n → R}
    (hρval : ∀ i : Fin n,
      ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)) :
    ∃ rI : Set.powersetCard (Fin n) c → R,
      Ideal.Quotient.mk I4 π =
        ∑ I : Set.powersetCard (Fin n) c,
          Ideal.Quotient.mk I4 (rI I) *
            Ideal.Quotient.mk I4 (MvPolynomial.aeval r (P.jacobianColumnMinor hcₘ I)) := by
  classical
  let rI : Set.powersetCard (Fin n) c → R := fun I ↦
    Classical.choose (Ideal.Quotient.mk_surjective (ρ (Ideal.Quotient.mk I4A (aI I))))
  have hrI :
      ∀ I : Set.powersetCard (Fin n) c,
        ρ (Ideal.Quotient.mk I4A (aI I)) = Ideal.Quotient.mk I4 (rI I) := by
    intro I
    simpa [rI] using
      (Classical.choose_spec (Ideal.Quotient.mk_surjective (ρ (Ideal.Quotient.mk I4A (aI I))))).symm
  have hquotA :
      Ideal.Quotient.mk I4A (algebraMap R A π) =
        ∑ I : Set.powersetCard (Fin n) c,
          Ideal.Quotient.mk I4A (aI I) *
            Ideal.Quotient.mk I4A (algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I)) := by
    -- Reduce the strict-standard equality modulo `π⁴` before applying the section.
    simpa [map_sum, map_mul] using congrArg (Ideal.Quotient.mk I4A) hjac
  have hρquot := congrArg ρ hquotA
  refine ⟨rI, ?_⟩
  -- The section sends each coefficient to its chosen lift and each Jacobian minor to the
  -- evaluation at the chosen generator lifts `r`.
  calc
    Ideal.Quotient.mk I4 π = ρ (Ideal.Quotient.mk I4A (algebraMap R A π)) := by
      symm
      simpa using (ρ.commutes (Ideal.Quotient.mk I4 π))
    _ =
        ∑ I : Set.powersetCard (Fin n) c,
          ρ (Ideal.Quotient.mk I4A (aI I) *
            Ideal.Quotient.mk I4A (algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I))) := by
          simpa [map_sum] using hρquot
    _ =
        ∑ I : Set.powersetCard (Fin n) c,
          ρ (Ideal.Quotient.mk I4A (aI I)) *
            ρ (Ideal.Quotient.mk I4A (algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I))) := by
          simp [map_mul]
    _ =
        ∑ I : Set.powersetCard (Fin n) c,
          Ideal.Quotient.mk I4 (rI I) *
            Ideal.Quotient.mk I4 (MvPolynomial.aeval r (P.jacobianColumnMinor hcₘ I)) := by
          refine Finset.sum_congr rfl ?_
          intro I hI
          rw [hrI I]
          rw [section_evaluates_presentation_polynomial_at_generator_lifts
            (R := R) (A := A) (π := π) (P := P) (ρ := ρ) (r := r) hρval
            (P.jacobianColumnMinor hcₘ I)]

/-- Helper for Lemma 16.7.1: evaluating the strict-standard Jacobian-minor identity at the chosen
section data yields a constant Jacobian matrix with a left inverse up to a scalar `u * π`, where
`u` is congruent to `1` modulo `π³`. -/
private theorem exists_constant_jacobian_left_inverse_at_section
    {n m c : ℕ} (P : Presentation R A (Fin n) (Fin m)) (hcₘ : c ≤ m)
    (aI : Set.powersetCard (Fin n) c → A)
    (hjac : algebraMap R A π =
      ∑ I : Set.powersetCard (Fin n) c,
        aI I * algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I))
    {ρ : A4 →ₐ[R4] R4} {r : Fin n → R}
    (hρval : ∀ i : Fin n,
      ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)) :
    ∃ (u t : R) (S : Matrix (Fin c) (Fin n) R),
      let J0 : Matrix (Fin c) (Fin n) R :=
        fun j i ↦ MvPolynomial.aeval r ((P.jacobianMatrix hcₘ) j i)
      u = 1 + π ^ 3 * t ∧ S * J0.transpose = (u * π) • (1 : Matrix (Fin c) (Fin c) R) := by
  classical
  obtain ⟨rI, hmod⟩ :=
    section_applied_to_jacobian_minor_expansion_mod_piPowFour
      (R := R) (A := A) (π := π) (P := P) (hcₘ := hcₘ) (aI := aI) hjac hρval
  let J0 : Matrix (Fin c) (Fin n) R :=
    fun j i ↦ MvPolynomial.aeval r ((P.jacobianMatrix hcₘ) j i)
  let σ : R :=
    ∑ I : Set.powersetCard (Fin n) c,
      rI I * MvPolynomial.aeval r (P.jacobianColumnMinor hcₘ I)
  have hmod' : Ideal.Quotient.mk I4 π = Ideal.Quotient.mk I4 σ := by
    -- Collapse the quotient-level sum into a single quotient equality in `R`.
    simpa [σ, map_sum, map_mul] using hmod
  have hdiff : π - σ ∈ I4 := by
    -- Rephrasing the quotient equality isolates the `(π⁴)`-error term in `R`.
    exact (Ideal.Quotient.eq (I := I4) (x := π) (y := σ)).mp hmod'
  obtain ⟨t', ht'⟩ := Ideal.mem_span_singleton.mp
    (show π - σ ∈ Ideal.span ({π ^ 4} : Set R) from hdiff)
  let u : R := 1 + π ^ 3 * (-t')
  have huσ : u * π = σ := by
    -- The quotient error term is exactly `π * (π³ * t')`, so absorbing it into `u` gives an
    -- honest equality in `R`.
    have hσ : σ = π - π ^ 4 * t' := by
      calc
        σ = π - (π - σ) := by ring
        _ = π - π ^ 4 * t' := by rw [ht']
    calc
      u * π = (1 + π ^ 3 * (-t')) * π := by rfl
      _ = π - π ^ 4 * t' := by ring
      _ = σ := hσ.symm
  have hσ_mem : σ ∈ I_(c)(J0.transpose) := by
    -- Each evaluated Jacobian minor becomes a literal maximal minor of the constant matrix `J0`.
    refine (I_(c)(J0.transpose)).sum_mem ?_
    intro I hI
    have hminor :
        MvPolynomial.aeval r (P.jacobianColumnMinor hcₘ I) ∈ I_(c)(J0.transpose) := by
      rw [evaluated_jacobianColumnMinor_eq_constantJacobian_minor
        (R := R) (A := A) (P := P) (hcₘ := hcₘ) (r := r) (I := I)]
      exact
        Matrix.det_submatrix_mem_minorIdeal c (J0.transpose)
          ((I.1.orderEmbOfFin I.2).toEmbedding)
          (Function.Embedding.refl (Fin c))
    exact Ideal.mul_mem_left _ _ hminor
  have hu_mem : u * π ∈ I_(c)(J0.transpose) := by
    -- The exact equality `u * π = σ` transports the minor-ideal membership to the scalar used in
    -- the source proof.
    rw [huσ]
    exact hσ_mem
  obtain ⟨S, hS⟩ := exists_mul_eq_smul_one_of_mem_minorIdeal (J0.transpose) hu_mem
  refine ⟨u, -t', S, ?_⟩
  -- This is exactly the matrix left-inverse statement needed later for the auxiliary relations.
  dsimp [J0, u]
  exact ⟨rfl, hS⟩

/-- Helper for Lemma 16.7.1: a strictly standard element gives a smooth basic-open neighborhood at
every prime that does not contain it. -/
private theorem smoothAtPrime_of_isStrictlyStandard_away
    [FinitePresentation R A]
    (hπ : IsStrictlyStandard R (algebraMap R A π))
    (q : PrimeSpectrum A)
    (hq : algebraMap R A π ∉ q.asIdeal) :
    SmoothAtPrime R A q := by
  -- `SmoothAtPrime` is witnessed by one smooth localization away from an element outside `q`.
  refine ⟨algebraMap R A π, hq, ?_⟩
  -- Strict standardness gives the required smoothness after inverting `π`.
  exact
    (isStrictlyStandard_implies_stablyFreeKaehlerAway
      (R := R) (A := A) (a := algebraMap R A π) hπ).1

/-- Helper for Lemma 16.7.1: once a finitely presented `R`-algebra is smooth at every prime
avoiding the image of an ideal from `R`, that image ideal is contained in the singular ideal. -/
private theorem ideal_map_le_singularIdeal_of_forall_smoothAtPrime
    {B : Type*} [CommRing B] [Algebra R B] [FinitePresentation R B]
    (I : Ideal R)
    (hSmooth : ∀ q : PrimeSpectrum B,
      ¬ Ideal.map (algebraMap R B) I ≤ q.asIdeal → SmoothAtPrime R B q) :
    Ideal.map (algebraMap R B) I ≤ H[B⁄R] := by
  have hsubset :
      PrimeSpectrum.zeroLocus (H[B⁄R] : Set B) ⊆
        PrimeSpectrum.zeroLocus (Ideal.map (algebraMap R B) I : Set B) := by
    intro q hq
    -- A prime in the zero locus of the singular ideal is nonsmooth, so the primewise smoothness
    -- hypothesis forces the mapped ideal to be contained in that prime.
    rw [PrimeSpectrum.mem_zeroLocus]
    have hqNotIsSmooth : ¬ IsSmoothAt R q.asIdeal := by
      simpa [zeroLocus_singularIdeal_eq_compl_smoothLocus, smoothLocus] using hq
    have hqNotSmoothAtPrime : ¬ SmoothAtPrime R B q := by
      intro hqSmooth
      exact hqNotIsSmooth ((smoothAtPrime_iff_isSmoothAt (R := R) (S := B) q).1 hqSmooth)
    have hmapLe : Ideal.map (algebraMap R B) I ≤ q.asIdeal := by
      by_contra hmap
      exact hqNotSmoothAtPrime (hSmooth q hmap)
    simpa using hmapLe
  have hmapLeVan :
      Ideal.map (algebraMap R B) I ≤
        PrimeSpectrum.vanishingIdeal (PrimeSpectrum.zeroLocus (H[B⁄R] : Set B)) :=
    (PrimeSpectrum.subset_zeroLocus_iff_le_vanishingIdeal _ _).1 hsubset
  -- Convert the zero-locus containment back into the desired ideal containment using that the
  -- singular ideal is radical.
  calc
    Ideal.map (algebraMap R B) I ≤
        PrimeSpectrum.vanishingIdeal (PrimeSpectrum.zeroLocus (H[B⁄R] : Set B)) := hmapLeVan
    _ = (H[B⁄R]).radical := by rw [PrimeSpectrum.vanishingIdeal_zeroLocus_eq_radical]
    _ = H[B⁄R] := by rw [(singularIdeal_isRadical (R := R) (A := B)).radical]

/-- Helper for Lemma 16.7.1: once a finitely presented factorization `A → B → Λ` is smooth at
every prime avoiding the mapped quotient-annihilator ideal, the desired singular-ideal
containment follows formally from the primewise criterion above. -/
private theorem exists_factorization_with_quotient_annihilator_map_le_singularIdeal_of_forall_smoothAtPrime
    (f : A →ₐ[R] Λ) :
    (∃ (B : Type (max u v w)) (_ : CommRing B) (_ : Algebra R B) (_ : FinitePresentation R B)
        (fA : A →ₐ[R] B) (g : B →ₐ[R] Λ),
        g.comp fA = f ∧
          (∀ q : PrimeSpectrum B,
            ¬ Ideal.map (algebraMap R B)
                (Module.annihilator R (quotient_annihilator_module (R := R) π)) ≤ q.asIdeal →
              SmoothAtPrime R B q)) →
      ∃ (B : Type (max u v w)) (_ : CommRing B) (_ : Algebra R B) (_ : FinitePresentation R B)
        (fA : A →ₐ[R] B) (g : B →ₐ[R] Λ),
        g.comp fA = f ∧
          Ideal.map (algebraMap R B)
              (Module.annihilator R (quotient_annihilator_module (R := R) π)) ≤
            H[B⁄R] := by
  rintro ⟨B, hB, hAlgB, hfpB, fA, g, hcomp, hSmooth⟩
  letI : CommRing B := hB
  letI : Algebra R B := hAlgB
  letI : FinitePresentation R B := hfpB
  refine ⟨B, hB, hAlgB, hfpB, fA, g, hcomp, ?_⟩
  -- Proof comment: after the factorization is fixed, the target containment is exactly the
  -- primewise smoothness-to-singular-ideal lemma applied to the quotient-annihilator ideal.
  exact
    ideal_map_le_singularIdeal_of_forall_smoothAtPrime
      (R := R) (B := B)
      (Module.annihilator R (quotient_annihilator_module (R := R) π))
      hSmooth

/-- Helper for Lemma 16.7.1: once an ideal dies after localizing away from `g`, the away
localization of the source algebra identifies with the away localization of the quotient by that
ideal. This packages the quotient-localization transport needed in the over-`π` branch without
reintroducing prime-local-ring coercion noise. -/
private noncomputable theorem localizationAwayQuotientAlgEquivOfMapEqBot
    {B : Type*} [CommRing B] [Algebra R B] (I : Ideal B) (g : B)
    (hbot : Ideal.map (algebraMap B (Localization.Away g)) I = ⊥) :
    Localization.Away g ≃ₐ[R] Localization.Away (Ideal.Quotient.mk I g) := by
  classical
  let eQuot := Classical.choice <|
    Ideal.quotient_localizationAway_algEquiv (R := B) (I := I) (g := g)
  let eBot :
      Localization.Away g ≃ₐ[B]
        ((Localization.Away g) ⧸ Ideal.map (algebraMap B (Localization.Away g)) I) := by
    -- Once the extended ideal is zero, quotienting by it is the identity quotient.
    exact hbot ▸ (AlgEquiv.quotientBot B (Localization.Away g)).symm
  let eBotR :
      Localization.Away g ≃ₐ[R]
        ((Localization.Away g) ⧸ Ideal.map (algebraMap B (Localization.Away g)) I) :=
    AlgEquiv.restrictScalars R eBot
  let eQuotR :
      ((Localization.Away g) ⧸ Ideal.map (algebraMap B (Localization.Away g)) I) ≃ₐ[R]
        Localization.Away (Ideal.Quotient.mk I g) :=
    AlgEquiv.restrictScalars R eQuot
  -- Compose the quotient-by-zero collapse with the canonical quotient/localization comparison.
  exact eBotR.trans eQuotR

/-- Helper for Lemma 16.7.1: the quotient-annihilator ideal always contains `π`, so its image in
any `R`-algebra contains the image of `π`. This is the basic away-from-`π` inclusion used in the
primewise smoothness split. -/
private theorem algebraMap_pi_mem_mappedQuotientAnnihilatorIdeal
    {B : Type*} [CommRing B] [Algebra R B] :
    algebraMap R B π ∈
      Ideal.map (algebraMap R B)
        (Module.annihilator R (quotient_annihilator_module (R := R) π)) := by
  -- Map the already verified annihilation relation `π ∈ Ann_R(Ann_R(π²) / Ann_R(π))` into `B`.
  exact Ideal.mem_map_of_mem (algebraMap R B)
    (pi_mem_annihilator_quotient_annR (R := R) (π := π))

/-- Helper for Lemma 16.7.1: if the mapped quotient-annihilator ideal is not contained in a prime
of an `R`-algebra, then some annihilator element has image outside that prime. This is the
source-side witness `r ∈ 𝔞 \\ q` needed in the over-`π` localization branch. -/
private theorem exists_annihilatorWitness_not_mem_of_mappedIdeal_not_le
    {B : Type*} [CommRing B] [Algebra R B]
    (q : PrimeSpectrum B)
    (hq :
      ¬ Ideal.map (algebraMap R B)
          (Module.annihilator R (quotient_annihilator_module (R := R) π)) ≤ q.asIdeal) :
    ∃ r ∈ Module.annihilator R (quotient_annihilator_module (R := R) π),
      algebraMap R B r ∉ q.asIdeal := by
  have hq' :
      ¬ Module.annihilator R (quotient_annihilator_module (R := R) π) ≤
        Ideal.comap (algebraMap R B) q.asIdeal := by
    -- Pull the prime back along `R → B`; otherwise the mapped ideal would land inside `q`.
    intro hle
    exact hq ((Ideal.map_le_iff_le_comap).2 hle)
  rcases SetLike.not_le_iff_exists.mp hq' with ⟨r, hr, hrq⟩
  -- Unfold the comap statement back to the desired claim about the image of `r` in `B`.
  exact ⟨r, hr, by simpa using hrq⟩

/-- Helper for Lemma 16.7.1: package the normalized presentation, the chosen section lifts, and
the constant Jacobian left-inverse data extracted from the strict-standard witness. -/
private structure NormalizedPresentationJacobianData
    (f : A →ₐ[R] Λ) (ρ : A4 →ₐ[R4] R4) where
  n : ℕ
  m : ℕ
  c : ℕ
  P : Presentation R A (Fin n) (Fin m)
  hcₘ : c ≤ m
  aI : Set.powersetCard (Fin n) c → A
  r : Fin n → R
  l : Fin n → Λ
  hjac :
    algebraMap R A π =
      ∑ I : Set.powersetCard (Fin n) c,
        aI I * algebraMap P.Ring A (P.jacobianColumnMinor hcₘ I)
  htail :
    ∀ j : Fin (m - c),
      algebraMap R P.Ring π * P.relation (tailRelationIndex hcₘ j) ∈
        P.leadingRelationIdeal hcₘ + P.ker ^ 2
  hr :
    ∀ i : Fin n,
      ρ (Ideal.Quotient.mk I4A (P.val i)) = Ideal.Quotient.mk I4 (r i)
  hl :
    ∀ i : Fin n,
      f (P.val i) = algebraMap R Λ (r i) + algebraMap R Λ (π ^ 4) * l i
  hrelation_mod_piPowFour :
    ∀ j : Fin m, MvPolynomial.aeval r (P.relation j) ∈ I4
  u t : R
  S : Matrix (Fin c) (Fin n) R
  hu : u = 1 + π ^ 3 * t
  hS :
    let J0 : Matrix (Fin c) (Fin n) R :=
      fun j i ↦ MvPolynomial.aeval r ((P.jacobianMatrix hcₘ) j i)
    S * J0.transpose = (u * π) • (1 : Matrix (Fin c) (Fin c) R)

/-- Helper for Lemma 16.7.1: the current verified frontier can be packaged into one reusable
object carrying the normalized presentation and the Jacobian matrix data needed for the auxiliary
quotient construction. -/
private theorem existsNormalizedPresentationJacobianData
    (f : A →ₐ[R] Λ)
    (hπ : IsStrictlyStandard R (algebraMap R A π))
    {ρ : A4 →ₐ[R4] R4}
    (hρcompat : (Algebra.ofId R4 Λ4).comp ρ = piPowFourQuotientMap π f) :
    Nonempty (NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) := by
  -- First freeze the source-side normalized presentation and the chosen lifts coming from the
  -- compatible section modulo `π⁴`.
  obtain ⟨n, m, c, P, hcₘ, aI, r, l, hjac, htail, hr, hl⟩ :=
    exists_normalized_presentation_section_data
      (R := R) (A := A) (Λ := Λ) (π := π) f hπ hρcompat
  have hrelation_mod_piPowFour :
      ∀ j : Fin m, MvPolynomial.aeval r (P.relation j) ∈ I4 :=
    relation_values_of_generator_lifts_mem_piPowFour
      (R := R) (A := A) (π := π) (P := P) hr
  -- Then evaluate the strict-standard Jacobian identity at those lifts to obtain the constant
  -- left-inverse matrix used later in the source construction of the auxiliary quotient.
  obtain ⟨u, t, S, hu, hS⟩ :=
    exists_constant_jacobian_left_inverse_at_section
      (R := R) (A := A) (π := π) (P := P) (hcₘ := hcₘ) (aI := aI) hjac hr
  exact ⟨{
    n := n
    m := m
    c := c
    P := P
    hcₘ := hcₘ
    aI := aI
    r := r
    l := l
    hjac := hjac
    htail := htail
    hr := hr
    hl := hl
    hrelation_mod_piPowFour := hrelation_mod_piPowFour
    u := u
    t := t
    S := S
    hu := hu
    hS := hS
  }⟩

/-- Helper for Lemma 16.7.1: the packaged matrix identity can be read entrywise as the source
equations
`∑ᵢ s_{j i} r_{k i} = (u * π) * δ_{jk}` for the evaluated constant Jacobian matrix. This is the
stable bridge from the frozen matrix identity to the later auxiliary relations. -/
private theorem normalizedPresentationJacobianData_matrix_entry
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    ∀ j k : Fin data.c,
      ∑ i : Fin data.n,
        data.S j i *
          MvPolynomial.aeval data.r ((data.P.jacobianMatrix data.hcₘ) k i) =
        if j = k then data.u * π else 0 := by
  intro j k
  let J0 : Matrix (Fin data.c) (Fin data.n) R :=
    fun j i ↦ MvPolynomial.aeval data.r ((data.P.jacobianMatrix data.hcₘ) j i)
  -- Proof comment: evaluate the verified matrix identity on the `(j, k)` entry.
  have hentry :=
    congrArg (fun M : Matrix (Fin data.c) (Fin data.c) R => M j k) data.hS
  -- Proof comment: after expanding matrix multiplication and the scalar matrix, this is exactly
  -- the source's Kronecker-delta equation.
  simpa [J0, Matrix.mul_apply, Matrix.one_apply] using hentry

/-- Helper for Lemma 16.7.1: each normalized presentation relation evaluates at the chosen base
ring lifts to an explicit `π⁴`-multiple. This is the exact divisibility input needed when turning
the source-side substituted relations into auxiliary quotient equations. -/
private theorem normalizedPresentationJacobianData_relation_value_eq_piPowFour_mul
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) (j : Fin data.m) :
    ∃ t : R, MvPolynomial.aeval data.r (data.P.relation j) = π ^ 4 * t := by
  -- Proof comment: the packaged congruence modulo `π⁴` is already recorded as membership in the
  -- principal ideal `(π⁴)`.
  rcases Ideal.mem_span_singleton.mp (data.hrelation_mod_piPowFour j) with ⟨t, ht⟩
  exact ⟨t, ht⟩

/-- Helper for Lemma 16.7.1: the auxiliary polynomial ring uses variables for the original
presentation generators, the correction variables `v`, and the error variables `w`. -/
private abbrev auxiliaryVariable
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :=
  Fin data.n ⊕ (Fin data.c ⊕ Fin data.n)

/-- Helper for Lemma 16.7.1: the `x`-variables inside the auxiliary polynomial ring. -/
private abbrev auxiliaryXVar
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    Fin data.n → auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data :=
  Sum.inl

/-- Helper for Lemma 16.7.1: the `v`-variables inside the auxiliary polynomial ring. -/
private abbrev auxiliaryVVar
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    Fin data.c → auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data :=
  fun j ↦ Sum.inr (Sum.inl j)

/-- Helper for Lemma 16.7.1: the `w`-variables inside the auxiliary polynomial ring. -/
private abbrev auxiliaryWVar
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    Fin data.n → auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data :=
  fun i ↦ Sum.inr (Sum.inr i)

/-- Helper for Lemma 16.7.1: this is the source-side target assignment sending the original
presentation generators to their images in `Λ`, the `v`-variables to `0`, and the `w`-variables
to `π * l_i`. -/
private noncomputable def auxiliaryTargetAssignment
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data → Λ
  | Sum.inl i => f (data.P.val i)
  | Sum.inr (Sum.inl _) => 0
  | Sum.inr (Sum.inr i) => algebraMap R Λ π * data.l i

/-- Helper for Lemma 16.7.1: these are the linear auxiliary relations
`x_i - r_i - π² * Σ_j s_{j i} v_j - π³ w_i`. -/
private noncomputable def auxiliaryLinearRelation
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) (i : Fin data.n) :
    MvPolynomial (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R :=
  MvPolynomial.X (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data i) -
    MvPolynomial.C (data.r i) -
    MvPolynomial.C (π ^ 2) *
      ∑ j : Fin data.c,
        MvPolynomial.C (data.S j i) *
          MvPolynomial.X (auxiliaryVVar (R := R) (A := A) (Λ := Λ) (π := π) f data j) -
    MvPolynomial.C (π ^ 3) *
      MvPolynomial.X (auxiliaryWVar (R := R) (A := A) (Λ := Λ) (π := π) f data i)

/-- Helper for Lemma 16.7.1: the original presentation relations embedded into the auxiliary
polynomial ring by using only the `x`-variables. -/
private noncomputable def auxiliaryPresentationRelation
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) (j : Fin data.m) :
    MvPolynomial (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R :=
  MvPolynomial.rename
    (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data)
    (data.P.relation j)

/-- Helper for Lemma 16.7.1: the source target assignment kills each linear auxiliary relation.
This packages the easy part of the later quotient map `B → Λ`. -/
private theorem auxiliaryLinearRelation_aeval_eq_zero
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    ∀ i : Fin data.n,
      MvPolynomial.aeval
          (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
          (auxiliaryLinearRelation (R := R) (A := A) (Λ := Λ) (π := π) f data i) = 0 := by
  intro i
  -- Proof comment: the `v`-variables vanish under the target assignment, so only the displayed
  -- relation `f(P.val i) = r_i + π⁴ l_i` from the normalized presentation survives.
  calc
    MvPolynomial.aeval
        (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
        (auxiliaryLinearRelation (R := R) (A := A) (Λ := Λ) (π := π) f data i) =
        f (data.P.val i) - algebraMap R Λ (data.r i) -
          algebraMap R Λ (π ^ 3) * (algebraMap R Λ π * data.l i) := by
            simp [auxiliaryLinearRelation, auxiliaryTargetAssignment, map_sub, map_sum, map_mul]
  _ = algebraMap R Λ (π ^ 4) * data.l i -
        algebraMap R Λ (π ^ 3) * (algebraMap R Λ π * data.l i) := by
          rw [data.hl i]
          ring
  _ = 0 := by
        rw [map_pow]
        ring

/-- Helper for Lemma 16.7.1: the source target assignment also kills the original presentation
relations after embedding them into the auxiliary polynomial ring. -/
private theorem auxiliaryPresentationRelation_aeval_eq_zero
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    ∀ j : Fin data.m,
      MvPolynomial.aeval
          (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
          (auxiliaryPresentationRelation (R := R) (A := A) (Λ := Λ) (π := π) f data j) = 0 := by
  intro j
  -- Proof comment: `rename` along the `x`-variables reduces the auxiliary statement to the
  -- original presentation relation, which already vanishes under `f`.
  calc
    MvPolynomial.aeval
        (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
        (auxiliaryPresentationRelation (R := R) (A := A) (Λ := Λ) (π := π) f data j) =
        MvPolynomial.aeval
          (fun i : Fin data.n ↦ f (data.P.val i))
          (data.P.relation j) := by
            simp [auxiliaryPresentationRelation, auxiliaryTargetAssignment, MvPolynomial.aeval_rename]
  _ = 0 := by
        simpa using
          relation_aeval_eq_zero_of_generator_image
            (R := R) (A := A) (Λ := Λ) data.P f
            (fun i ↦ f (data.P.val i)) (fun i ↦ rfl) j

/-- Helper for Lemma 16.7.1: quotienting the auxiliary polynomial ring by the linear relations
and the original presentation relations already produces a finitely presented algebra `B₀`
through which `f : A → Λ` factors. This freezes the algebraic setup before the later singular-ideal
refinement. -/
private theorem exists_preliminaryAuxiliaryFactorization
    (f : A →ₐ[R] Λ) {ρ : A4 →ₐ[R4] R4}
    (data : NormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f ρ) :
    ∃ (B0 : Type (max u v w)) (_ : CommRing B0) (_ : Algebra R B0) (_ : FinitePresentation R B0)
      (fA0 : A →ₐ[R] B0) (g0 : B0 →ₐ[R] Λ),
      g0.comp fA0 = f := by
  let rel :
      Fin data.n ⊕ Fin data.m →
        MvPolynomial
          (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R :=
    fun i ↦ Sum.elim
      (auxiliaryLinearRelation (R := R) (A := A) (Λ := Λ) (π := π) f data)
      (auxiliaryPresentationRelation (R := R) (A := A) (Λ := Λ) (π := π) f data)
      i
  let J :
      Ideal
        (MvPolynomial
          (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R) :=
    Ideal.span (Set.range rel)
  let B0 :
      Type (max u v w) :=
    MvPolynomial
        (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R ⧸
      J
  letI : CommRing B0 := inferInstance
  letI : Algebra R B0 := inferInstance
  have hJfg : J.FG := by
    -- The setup ideal is generated by finitely many explicit auxiliary relations.
    simpa [J] using (Submodule.fg_span (Set.finite_range rel) : J.FG)
  letI : FinitePresentation R B0 := Algebra.FinitePresentation.quotient hJfg
  let mkB0 :
      MvPolynomial
          (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R →ₐ[R]
        B0 :=
    Ideal.Quotient.mkₐ R J
  let xImage : Fin data.n → B0 := fun i ↦
    mkB0 (MvPolynomial.X (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data i))
  let ψ0 : data.P.Ring →ₐ[R] B0 := MvPolynomial.aeval xImage
  have hψ0_rename :
      ∀ p : data.P.Ring,
        ψ0 p =
          mkB0
            (MvPolynomial.rename
              (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p) := by
    intro p
    -- Evaluating at the quotient classes of the `x`-variables is the same as renaming into the
    -- auxiliary polynomial ring and then taking the quotient class.
    simp [ψ0, xImage, mkB0, MvPolynomial.aeval_rename]
  have hψ0_relation :
      ∀ j : Fin data.m, ψ0 (data.P.relation j) = 0 := by
    intro j
    -- Each presentation relation was included among the generators of the setup ideal `J`.
    rw [hψ0_rename]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨Sum.inr j, rfl⟩)
  have hker :
      data.P.ker ≤ RingHom.ker ψ0 := by
    -- The defining relations generate the kernel of the presentation map, so `ψ0` descends to `A`.
    rw [← data.P.span_range_relation_eq_ker]
    refine Ideal.span_le.2 ?_
    rintro _ ⟨j, rfl⟩
    simpa [RingHom.mem_ker] using hψ0_relation j
  let fAq : data.P.Quotient →ₐ[R] B0 :=
    Ideal.Quotient.liftₐ (R₁ := R) (I := data.P.ker) ψ0
      (fun z hz ↦ by simpa [RingHom.mem_ker] using hker hz)
  let fA0 : A →ₐ[R] B0 :=
    fAq.comp ((data.P.quotientEquiv.restrictScalars R).symm.toAlgHom)
  have hAuxLinearZero :
      ∀ i : Fin data.n,
        MvPolynomial.aeval
            (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
            (auxiliaryLinearRelation (R := R) (A := A) (Λ := Λ) (π := π) f data i) = 0 :=
    auxiliaryLinearRelation_aeval_eq_zero
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  have hAuxRelationZero :
      ∀ j : Fin data.m,
        MvPolynomial.aeval
            (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
            (auxiliaryPresentationRelation (R := R) (A := A) (Λ := Λ) (π := π) f data j) = 0 :=
    auxiliaryPresentationRelation_aeval_eq_zero
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  let ψΛ :
      MvPolynomial
          (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R →ₐ[R]
        Λ :=
    MvPolynomial.aeval
      (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
  have hJle :
      J ≤ RingHom.ker ψΛ := by
    -- The target assignment kills every generator of the setup ideal, so it descends to `B₀`.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨i, rfl⟩
    rcases i with i | j
    · simpa [rel, RingHom.mem_ker] using hAuxLinearZero i
    · simpa [rel, RingHom.mem_ker] using hAuxRelationZero j
  let g0 : B0 →ₐ[R] Λ :=
    Ideal.Quotient.liftₐ (R₁ := R) (I := J) ψΛ
      (fun z hz ↦ by simpa [RingHom.mem_ker] using hJle hz)
  have hfaq_comp :
      fAq.comp (Ideal.Quotient.mkₐ R data.P.ker) = ψ0 := by
    -- This is the defining computation rule for the quotient lift to `A`.
    simpa [fAq] using
      (Ideal.Quotient.liftₐ_comp (R₁ := R) (I := data.P.ker) ψ0
        (fun z hz ↦ by simpa [RingHom.mem_ker] using hker hz))
  have hg0_comp :
      g0.comp mkB0 = ψΛ := by
    -- This is the defining computation rule for the quotient lift to `Λ`.
    simpa [g0, mkB0] using
      (Ideal.Quotient.liftₐ_comp (R₁ := R) (I := J) ψΛ
        (fun z hz ↦ by simpa [RingHom.mem_ker] using hJle hz))
  refine ⟨B0, inferInstance, inferInstance, inferInstance, fA0, g0, ?_⟩
  ext x
  obtain ⟨q, rfl⟩ := (data.P.quotientEquiv.restrictScalars R).surjective x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective q
  have hfaq_apply :
      fAq (Ideal.Quotient.mk data.P.ker p) = ψ0 p := by
    -- Evaluating the quotient-lift identity at `p` turns the descended map back into `ψ0`.
    have h := congrArg (fun F : data.P.Ring →ₐ[R] B0 => F p) hfaq_comp
    simpa using h
  have hg0_apply :
      g0
          (mkB0
            (MvPolynomial.rename
              (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p)) =
        ψΛ
          (MvPolynomial.rename
            (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p) := by
    -- Evaluating the quotient-lift identity at the renamed polynomial turns `g0` back into `ψΛ`.
    have h := congrArg
      (fun F :
          MvPolynomial
              (auxiliaryVariable (R := R) (A := A) (Λ := Λ) (π := π) f data) R →ₐ[R]
            Λ ↦
        F
          (MvPolynomial.rename
            (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p))
      hg0_comp
    simpa using h
  -- The factorization equality reduces to evaluating the same presentation polynomial in `Λ`
  -- along the chosen images of the original generators.
  calc
    g0 (fA0 (data.P.quotientEquiv (Ideal.Quotient.mk data.P.ker p))) =
        g0 (fAq (Ideal.Quotient.mk data.P.ker p)) := by
          simp [fA0]
    _ = g0 (ψ0 p) := by rw [hfaq_apply]
    _ =
        g0
          (mkB0
            (MvPolynomial.rename
              (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p)) := by
          rw [hψ0_rename]
    _ =
        ψΛ
          (MvPolynomial.rename
            (auxiliaryXVar (R := R) (A := A) (Λ := Λ) (π := π) f data) p) := by
          exact hg0_apply
    _ = MvPolynomial.aeval (fun i : Fin data.n ↦ f (data.P.val i)) p := by
          simp [ψΛ, auxiliaryTargetAssignment, MvPolynomial.aeval_rename]
    _ = f (MvPolynomial.aeval data.P.val p) := by
          exact presentation_aeval_eq_of_generator_image
            (R := R) (A := A) (S := Λ) data.P f p
    _ = f (data.P.quotientEquiv (Ideal.Quotient.mk data.P.ker p)) := by
          simp [data.P.quotientEquiv_mk, data.P.algebraMap_apply]

/-- Helper for Lemma 16.7.1: freeze the current verified frontier into one package before the
final `B₀ ↠ B' ↠ B` refinement. The package contains the normalized presentation data, the
away-from-`π` smoothness route on `A`, the constant-Jacobian identities, the explicit `π⁴`
divisibility data, the auxiliary vanishing identities in `Λ`, and the preliminary factorization
`A → B₀ → Λ`. -/
private theorem exists_preliminaryAuxiliaryFactorization_with_frozen_frontier
    (f : A →ₐ[R] Λ)
    (hπ : IsStrictlyStandard R (algebraMap R A π))
    {ρ : A4 →ₐ[R4] R4}
    (hρcompat : (Algebra.ofId R4 Λ4).comp ρ = piPowFourQuotientMap π f) :
    ∃ (data : NormalizedPresentationJacobianData
        (R := R) (A := A) (Λ := Λ) (π := π) f ρ)
      (B0 : Type (max u v w)) (_ : CommRing B0) (_ : Algebra R B0) (_ : FinitePresentation R B0)
      (fA0 : A →ₐ[R] B0) (g0 : B0 →ₐ[R] Λ),
      (∀ q : PrimeSpectrum A,
        algebraMap R A π ∉ q.asIdeal → SmoothAtPrime R A q) ∧
      (∀ j k : Fin data.c,
        ∑ i : Fin data.n,
          data.S j i *
            MvPolynomial.aeval data.r ((data.P.jacobianMatrix data.hcₘ) k i) =
          if j = k then data.u * π else 0) ∧
      (∀ j : Fin data.m,
        ∃ t : R, MvPolynomial.aeval data.r (data.P.relation j) = π ^ 4 * t) ∧
      (∀ i : Fin data.n,
        MvPolynomial.aeval
            (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
            (auxiliaryLinearRelation (R := R) (A := A) (Λ := Λ) (π := π) f data i) = 0) ∧
      (∀ j : Fin data.m,
        MvPolynomial.aeval
            (auxiliaryTargetAssignment (R := R) (A := A) (Λ := Λ) (π := π) f data)
            (auxiliaryPresentationRelation (R := R) (A := A) (Λ := Λ) (π := π) f data j) = 0) ∧
      g0.comp fA0 = f := by
  letI : FinitePresentation R A := finitePresentation_of_isStrictlyStandard (R := R) hπ
  -- First freeze the normalized source-side presentation and the Jacobian data extracted from it.
  obtain ⟨data⟩ :=
    existsNormalizedPresentationJacobianData
      (R := R) (A := A) (Λ := Λ) (π := π) f hπ hρcompat
  -- Then record the source-side smoothness and the explicit auxiliary identities in the shapes
  -- needed by the later quotient refinement.
  obtain ⟨B0, hB0, hAlgB0, hfpB0, fA0, g0, hg0A⟩ :=
    exists_preliminaryAuxiliaryFactorization
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  refine ⟨data, B0, hB0, hAlgB0, hfpB0, fA0, g0, ?_⟩
  constructor
  · exact smoothAtPrime_of_isStrictlyStandard_away (R := R) (A := A) (π := π) hπ
  constructor
  · exact normalizedPresentationJacobianData_matrix_entry
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  constructor
  · exact normalizedPresentationJacobianData_relation_value_eq_piPowFour_mul
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  constructor
  · exact auxiliaryLinearRelation_aeval_eq_zero
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  constructor
  · exact auxiliaryPresentationRelation_aeval_eq_zero
      (R := R) (A := A) (Λ := Λ) (π := π) f data
  · exact hg0A

-- Proof sketch: the proof follows the Stacks construction of the auxiliary finitely presented
-- algebra `B` obtained by adjoining variables to a finite presentation of `A` coming from the
-- strict-standard witness for `π` and using the section modulo `π⁴` to normalize the presentation.
-- The annihilator hypothesis on `Λ` kills the extra relations after mapping to `Λ`, while the
-- strict standardness of `π` and Elkik's Jacobian criterion imply that the image of `𝔞` in `B` is
-- contained in the singular ideal `H_{B/R}`.
/-- Lemma 16.7.1: let `R` be Noetherian, let `Λ` be an `R`-algebra, let `π ∈ R`, and let
`A → Λ` be an `R`-algebra map. Assume the image of `π` is strictly standard in `A` over `R`
(hence witnessed by a finite presentation of `A`), assume `Ann_Λ(π) = Ann_Λ(π²)`, and assume there
is a section `A / π⁴A → R / π⁴R` compatible with the map to `Λ / π⁴Λ`. Then there is a
factorization `A → B → Λ` through a finitely presented `R`-algebra `B` such that the image of
`𝔞 = Ann_R(Ann_R(π²) / Ann_R(π))` in `B` is contained in the singular ideal `H_{B/R}`. -/
theorem exists_factorization_with_quotient_annihilator_map_le_singularIdeal
    [IsNoetherianRing R]
    (f : A →ₐ[R] Λ)
    (hπ : IsStrictlyStandard R (algebraMap R A π))
    (hAnnΛ : AnnΛ[algebraMap R Λ π] = AnnΛ[algebraMap R Λ (π ^ 2)])
    (hρ : ∃ ρ : A4 →ₐ[R4] R4,
      (Algebra.ofId R4 Λ4).comp ρ = piPowFourQuotientMap π f) :
    ∃ (B : Type (max u v w)) (_ : CommRing B) (_ : Algebra R B) (_ : FinitePresentation R B)
      (fA : A →ₐ[R] B) (g : B →ₐ[R] Λ),
      g.comp fA = f ∧
          Ideal.map (algebraMap R B)
            (Module.annihilator R (quotient_annihilator_module (R := R) π)) ≤
          H[B⁄R] :=
  by
    rcases hρ with ⟨ρ, hρcompat⟩
    obtain ⟨data, B0, _, _, _, fA0, g0, hSmoothAwayPi, hMatrixEntry,
      hRelationPiPowFour, hAuxLinearZero, hAuxRelationZero, hg0A⟩ :=
      exists_preliminaryAuxiliaryFactorization_with_frozen_frontier
        (R := R) (A := A) (Λ := Λ) (π := π) f hπ hρcompat
    -- Route correction: the source-side normalization, the constant Jacobian equations, and the
    -- explicit `π⁴` divisibility of the substituted relations are now frozen in `data`,
    -- `hMatrixEntry`, `hRelationPiPowFour`, and the explicit vanishing facts
    -- `hAuxLinearZero`/`hAuxRelationZero` for the eventual quotient map to `Λ`. The remaining
    -- blocker is no longer raw algebraic setup: the preliminary factorization `A → B₀ → Λ` has
    -- now been formalized. What remains is specifically the source-faithful refinement
    -- `B₀ ↠ B' ↠ B` and the over-`π` localization comparison needed for the primewise smoothness
    -- argument controlling the singular ideal.
    refine
      exists_factorization_with_quotient_annihilator_map_le_singularIdeal_of_forall_smoothAtPrime
        (R := R) (A := A) (Λ := Λ) (π := π) f ?_
    -- TODO: refine `B₀` by adjoining the divided leading relations to obtain `B'`, then quotient
    -- by the transported tail ideal to obtain the final auxiliary algebra `B`.
    -- The quotient-localization bridge is now available as
    -- `localizationAwayQuotientAlgEquivOfMapEqBot`, so the remaining blocker is specifically the
    -- construction of explicit `B'`, the explicit tail ideal in `B'`, and the proof that this tail
    -- ideal vanishes after localizing away from the over-`π` witness `δ * r` via
    -- `baseChange_quotient_annihilator_subsingleton_of_annihilator_unit`.
    let _ := B0
    let _ := fA0
    let _ := g0
    let _ := hg0A
    sorry

end

end Algebra
