import Mathlib
import ConvexAnalysis_Rockafellar_1970.Chap02.Theorem_8_1
import ConvexAnalysis_Rockafellar_1970.Chap04.Proposition_17_0_8
import ConvexAnalysis_Rockafellar_1970.Chap04.Definition_17_0_9

-- Declarations for this item will be appended below by the statement pipeline.

open Set
open scoped Pointwise Rockafellar

section

universe u v

/-!
Source/core/bridge triage:

- `source-facing`: Proposition 17.0.10 identifies the mixed convex hull generated by `points` and
  directions with the height-`1` section of the cone generated by the lifted set.
- `core/canonical`: the owner abstractions are `mconv[R](points | directions)`, the Chapter 1
  height-one owners `U[R | S]` and `unitLift R`, the lifted generating set
  `liftingSet R points directions`, and its generated cone owner
  `cone[R] (liftingSet R points directions)`.
- `bridge/view`: the intrinsic owner-level equality is the unit-section identity in `E`; the
  product-space slice equality with `unitHeightSet` is a derived bridge.

Domain-style sampling used here:
- `mixedConvexHull`;
- `mixedConvexHull_min`;
- `mem_unitSection_pointedConeHull_lift_iff`;
- `Set.mem_recessionCone_iff`;
- `PointedCone.ofConeComb`, `PointedCone.hull`, and `cone[R]`.

Primitive data vs derived API:
- primitive source data: the point set `points`, a direction-carrier set `directions`, and the
  lifted generating set `liftingSet R points directions`;
- derived bridge API: the unit-section membership equivalence, the resulting owner equality
  `mconv = U[R | cone[R] (liftingSet R ...)]`, and the product-space slice equality for
  `unitLift`.

Layer target: `bridge/view`.
-/

variable {R : Type v} [Semifield R] [PartialOrder R] [IsOrderedRing R] [PosMulReflectLT R]
variable {E : Type u} [AddCommMonoid E] [Module R E]

omit [PosMulReflectLT R] in
private theorem convex_unitSection_liftingSetCone
    (points directions : Set E) :
    Convex R (U[R | cone[R] (liftingSet R points directions)] : Set E) := by
  intro x hx y hy a b ha hb hab
  rw [mem_unitSection_iff] at hx hy ⊢
  have hxy :
      a • ((1 : R), x) + b • ((1 : R), y) ∈
        cone[R] (liftingSet R points directions) :=
    (cone[R] (liftingSet R points directions)).convex hx hy ha hb hab
  simpa [Prod.smul_mk, hab, add_assoc, add_left_comm, add_comm] using hxy

omit [PosMulReflectLT R] in
private theorem directions_subset_recession_unitSection_liftingSetCone
    (points directions : Set E) :
    directions ⊆ 0⁺[R] (U[R | cone[R] (liftingSet R points directions)] : Set E) := by
  intro y hy
  rw [Set.mem_recessionCone_iff]
  intro x hx a ha
  rw [mem_unitSection_iff] at hx ⊢
  have hyLift :
      ((0 : R), y) ∈
        cone[R] (liftingSet R points directions) :=
    PointedCone.subset_hull <| by
      rw [mem_liftingSet_iff]
      exact Or.inr ⟨rfl, hy⟩
  have hsum :
      ((1 : R), x) + a • ((0 : R), y) ∈
        cone[R] (liftingSet R points directions) :=
    (cone[R] (liftingSet R points directions)).add_mem hx <|
      (cone[R] (liftingSet R points directions)).smul_mem ha hyLift
  simpa [Prod.smul_mk, add_assoc, add_left_comm, add_comm] using hsum

omit [PosMulReflectLT R] in
private theorem mixedConvexHull_subset_unitSection_liftingSetCone
    (points directions : Set E) :
    mconv[R](points | directions) ⊆
      (U[R | cone[R] (liftingSet R points directions)] : Set E) := by
  refine mixedConvexHull_min R
    (convex_unitSection_liftingSetCone points directions) ?_
    (directions_subset_recession_unitSection_liftingSetCone points directions)
  intro x hx
  rw [mem_unitSection_iff]
  exact PointedCone.subset_hull <| by
    rw [mem_liftingSet_iff]
    exact Or.inl ⟨rfl, hx⟩

private theorem mem_liftingSetCone_one_mem_of_subset_recession
    (points directions : Set E) {C : Set E} (hC_convex : Convex R C)
    (hpoints : points ⊆ C) (hdirections : directions ⊆ 0⁺[R]C) {x : E}
    (hx : ((1 : R), x) ∈ cone[R] (liftingSet R points directions)) :
    x ∈ C := by
  let liftedPointCone : PointedCone R (R × E) := cone[R] (unitLift R C)
  let zeroLiftRecessionCone : PointedCone R (R × E) :=
    PointedCone.ofConeComb (L₀[R | 0⁺[R] C])
      ⟨(0, 0), ⟨0, zero_mem_recessionCone C, rfl⟩⟩
      fun p hp q hq a ha b hb ↦ by
        rcases hp with ⟨y, hy, rfl⟩
        rcases hq with ⟨z, hz, rfl⟩
        have hsum :
            a • y + b • z ∈ 0⁺[R] C := by
          rw [Set.mem_recessionCone_iff]
          intro x hx c hc
          have hxy : x + (c * a) • y ∈ C :=
            (Set.mem_recessionCone_iff.mp hy) x hx (c * a) (mul_nonneg hc ha)
          have hxyz : x + (c * a) • y + (c * b) • z ∈ C :=
            (Set.mem_recessionCone_iff.mp hz) (x + (c * a) • y) hxy (c * b) (mul_nonneg hc hb)
          simpa [smul_add, smul_smul, mul_assoc, add_assoc] using hxyz
        refine ⟨a • y + b • z, hsum, ?_⟩
        simp [Prod.smul_mk]
  have hlift :
      liftingSet R points directions ⊆
        ((liftedPointCone ⊔ zeroLiftRecessionCone : PointedCone R (R × E)) : Set (R × E)) := by
    intro p hp
    rcases p with ⟨a, x⟩
    rw [mem_liftingSet_iff] at hp
    rcases hp with ⟨ha, hx⟩ | ⟨ha, hx⟩
    · have hxC : x ∈ C := hpoints hx
      change a = (1 : R) at ha
      have hmem : ((1 : R), x) ∈ (liftedPointCone : Set (R × E)) :=
        PointedCone.subset_hull ⟨x, hxC, rfl⟩
      simpa [ha] using
        (show ((1 : R), x) ∈
            ((liftedPointCone ⊔ zeroLiftRecessionCone : PointedCone R (R × E)) : Set (R × E))
          from
            (show liftedPointCone ≤ liftedPointCone ⊔ zeroLiftRecessionCone from le_sup_left) hmem)
    · have hmem : ((0 : R), x) ∈ (zeroLiftRecessionCone : Set (R × E)) :=
        ⟨x, hdirections hx, rfl⟩
      change a = (0 : R) at ha
      simpa [ha] using
        (show ((0 : R), x) ∈
            ((liftedPointCone ⊔ zeroLiftRecessionCone : PointedCone R (R × E)) : Set (R × E))
          from
            (show zeroLiftRecessionCone ≤ liftedPointCone ⊔ zeroLiftRecessionCone from
              le_sup_right) hmem)
  have hHull_le :
      (cone[R] (liftingSet R points directions) : PointedCone R (R × E)) ≤
        liftedPointCone ⊔ zeroLiftRecessionCone :=
    Submodule.span_le.mpr hlift
  have hpair :
      ((1 : R), x) ∈
        ((liftedPointCone ⊔ zeroLiftRecessionCone : PointedCone R (R × E)) : Set (R × E)) := by
    exact hHull_le hx
  change ((1 : R), x) ∈ (liftedPointCone ⊔ zeroLiftRecessionCone : PointedCone R (R × E)) at hpair
  rw [Submodule.mem_sup] at hpair
  rcases hpair with ⟨p, hp, q, hq, hpq⟩
  rcases hq with ⟨y, hy, rfl⟩
  rcases p with ⟨a, z⟩
  have hp_fst : a = (1 : R) := by
    simpa using congrArg Prod.fst hpq
  have hpLift : ((1 : R), z) ∈ (liftedPointCone : Set (R × E)) := by
    simpa [hp_fst] using hp
  have hp_section : z ∈ U[R | liftedPointCone] := by
    simpa [mem_unitSection_iff] using hpLift
  have hpC : z ∈ C :=
    (mem_unitSection_pointedConeHull_lift_iff C hC_convex z).1 hp_section
  have hsum : z + y ∈ C := by
    simpa using (Set.mem_recessionCone_iff.mp hy) z hpC 1 zero_le_one
  have hsnd : z + y = x := by
    simpa using congrArg Prod.snd hpq
  simpa [hsnd] using hsum

/-- Membership in the height-`1` section of the cone generated by the lifted set is equivalent to
membership in the mixed convex hull over the same direction carrier. -/
theorem mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull
    (points directions : Set E) (x : E) :
    x ∈ U[R | cone[R] (liftingSet R points directions)] ↔
      x ∈ mconv[R](points | directions) := by
  constructor
  · exact fun hx ↦
      mem_liftingSetCone_one_mem_of_subset_recession points directions
        (convex_mixedConvexHull R points directions)
        (subset_mixedConvexHull R points directions)
        (directions_subset_recessionCone_mixedConvexHull R points directions)
        (by simpa [mem_unitSection_iff] using hx)
  · exact fun hx ↦ mixedConvexHull_subset_unitSection_liftingSetCone points directions hx

/-- Proposition 17.0.10, owner-level form: the mixed convex hull generated by `points` and
`directions` is exactly the height-`1` section of the cone generated by `liftingSet`. -/
theorem mixedConvexHull_eq_unitSection_liftingSetCone
    (points directions : Set E) :
    mconv[R](points | directions) =
      U[R | cone[R] (liftingSet R points directions)] := by
  ext x
  exact (mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull points directions x).symm

/-- Product-space bridge form of Proposition 17.0.10: under the canonical owner `unitLift R`,
the mixed convex hull identifies with the intersection of the lifted cone and the intrinsic
height-`1` slice `unitHeightSet`. -/
theorem unitLift_mixedConvexHull_eq_unitHeightSet_inter_liftingSetCone
    (points directions : Set E) :
    L[R | mconv[R](points | directions)] =
      unitHeightSet (R := R) ∩ cone[R] (liftingSet R points directions) := by
  ext p
  rcases p with ⟨a, x⟩
  constructor
  · rintro ⟨y, hy, hxy⟩
    cases hxy
    constructor
    · simp [unitHeightSet]
    · simpa using
        (mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull points directions x).2 hy
  · rintro ⟨ha, hp⟩
    have ha : a = (1 : R) := by
      simpa [unitHeightSet] using ha
    have hx_section :
        x ∈ U[R | cone[R] (liftingSet R points directions)] := by
      simpa [mem_unitSection_iff, ha] using hp
    have hx : x ∈ mconv[R](points | directions) :=
      (mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull points directions x).1 hx_section
    exact ⟨x, hx, by ext <;> simp [ha]⟩

section

variable [IsStrictOrderedRing R]

/-- Source-facing ray bridge form of Proposition 17.0.10:
membership in the height-`1` section of the lifted cone over `ray directions` is equivalent to
membership in the mixed convex hull generated by `points` and `ray directions`. -/
theorem mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull_ray
    (points : Set E) (directions : Set (Module.Ray R E)) (x : E) :
    x ∈ U[R | cone[R] (liftingSet R points (ray directions))] ↔
      x ∈ mconv[R](points | ray directions) := by
  simpa using
    (mem_unitSection_liftingSetCone_iff_mem_mixedConvexHull
      (R := R) (points := points) (directions := ray directions) x)

/-- Source-facing ray bridge equality form of Proposition 17.0.10. -/
theorem mixedConvexHull_eq_unitSection_liftingSetCone_ray
    (points : Set E) (directions : Set (Module.Ray R E)) :
    mconv[R](points | ray directions) =
      U[R | cone[R] (liftingSet R points (ray directions))] := by
  simpa using
    (mixedConvexHull_eq_unitSection_liftingSetCone
      (R := R) (points := points) (directions := ray directions))

/-- Source-facing ray bridge product-space form of Proposition 17.0.10. -/
theorem unitLift_mixedConvexHull_eq_unitHeightSet_inter_liftingSetCone_ray
    (points : Set E) (directions : Set (Module.Ray R E)) :
    L[R | mconv[R](points | ray directions)] =
      unitHeightSet (R := R) ∩ cone[R] (liftingSet R points (ray directions)) := by
  simpa using
    (unitLift_mixedConvexHull_eq_unitHeightSet_inter_liftingSetCone
      (R := R) (points := points) (directions := ray directions))

end

end
