import Mathlib
import CombinatorialGroupTheory_Magnus_2004.Chap01.Definition_1_1_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

/-- The distinguished generators `a` and `b` of the two-generator presentation in
Proposition `2-5-30`. -/
inductive LargePowerFreeSubgroupGenerator
  | a
  | b
  deriving DecidableEq

section

open LargePowerFreeSubgroupGenerator

variable (s : FreeGroup LargePowerFreeSubgroupGenerator) {m : ℕ}

local notation "G" => PresentedGroup (Set.singleton (s ^ m))
local notation "gen" => (PresentedGroup.of : LargePowerFreeSubgroupGenerator → G)

-- Layer triage:
-- `source-facing`: the two-generator one-relator group `G = (a, b; s ^ m)` with `1 < m`, together
-- with the hypothesis that the relator root `s` is not conjugate to any power of `a` or of `b`,
-- and the conclusion that the pair `a, b ^ n` is eventually a basis for the subgroup it
-- generates.
-- `core/canonical`: `PresentedGroup (Set.singleton (s ^ m))`
-- for the one-relator quotient, `IsConj` for conjugacy in the ambient free group, and
-- `IsFreeGroupBasis` for the textbook basis claim inside the generated subgroup.
-- `bridge/view`: the textbook generators `a` and `b` are represented by the constructors of
-- `LargePowerFreeSubgroupGenerator`, and their images in the one-relator quotient are the
-- canonical elements `gen .a` and `gen .b`.
-- Domain sampling:
-- 1. `PresentedGroup` is the canonical owner for one-relator groups in this chapter.
-- 2. Because this proposition works directly in that canonical quotient, the owner-side generator
--    map is `PresentedGroup.of` itself rather than the later bridge API
--    `GroupPresentation.generatorImage` for an arbitrary chosen presentation equivalence.
-- 3. `IsConj` is mathlib's owner relation for conjugacy in a group.
-- 4. `IsFreeGroupBasis` is the project's source-faithful basis predicate for a subset of a group.
-- Primitive vs. derived:
-- the primitive public data are the relator root `s`, the exponent `m`, and the non-conjugacy
-- hypotheses excluding powers of `a` and of `b`; the subgroup generated by the images of `a` and
-- `b ^ n` is derived canonically from those elements.

/-- Proposition 2-5-30: let `G = (a, b; s ^ m)` with `1 < m`, where `s` is not conjugate in the
free group on `{a, b}` to any power of `a` or of `b`. Then for all sufficiently large `n`, the
pair consisting of the image of `a` and the image of `b ^ n` is a free basis of the subgroup of
`G` that it generates. -/
-- Proof sketch: this is Magnus's large-power freeness theorem for one-relator groups with
-- torsion. The hypotheses exclude the exceptional cases where the relator is supported on a
-- conjugate of one generator, so high powers of the second generator avoid the defining relation.
-- For all sufficiently large `n`, the subgroup generated by the images of `a` and `b ^ n`
-- therefore embeds in the one-relator quotient as a free subgroup on those two generators, which
-- is exactly the `IsFreeGroupBasis` conclusion below.
theorem exists_threshold_a_and_bpow_isFreeGroupBasis
    (s : FreeGroup LargePowerFreeSubgroupGenerator) {m : ℕ} (hm : 1 < m)
    (hsa : ∀ k : ℤ, ¬ IsConj s (FreeGroup.of a ^ k))
    (hsb : ∀ k : ℤ, ¬ IsConj s (FreeGroup.of b ^ k)) :
    ∃ N : ℕ,
      ∀ n : ℕ, N ≤ n →
        let Y : Set G := {gen a, gen b ^ n}
        IsFreeGroupBasis {g : Subgroup.closure Y | (g : G) ∈ Y} := sorry

end
