import Mathlib

-- Declarations for this item are recorded in this dedicated item file.

universe u

set_option autoImplicit false

section

variable (C : Type u) [Group C] [Countable C]

/-!
Primary domain: embedding countable groups into finitely generated simple groups.

Layer triage:
- `source-facing`: a countable group `C`, an embedding of `C` into a simple overgroup, and the
  assertion that the overgroup is generated by six elements.
- `core/canonical`: `Countable` for countability, `IsSimpleGroup` for simplicity, `Group.FG` and
  `Group.rank` for finite generation and generator bounds, and an injective homomorphism `C →* S`
  for the embedding.
- `bridge/view`: the textbook phrase “six-generator simple group” is expressed canonically as the
  bound `Group.rank S ≤ 6`.

Domain sampling:
1. `IsSimpleGroup` is mathlib's owner predicate for simplicity of a group.
2. `Group.FG` and `Group.rank` are the canonical owner APIs for “generated by finitely many
   elements” and “generated by at most `n` elements”.
3. An embedding of groups is canonically a homomorphism together with `Function.Injective`.
4. Theorem `4-3-5` in this section already uses the source-facing existential-overgroup owner
   pattern with canonical predicates, an explicit embedding homomorphism in the existential
   telescope, and theorem-level properties grouped in the final conjunction, rather than a nested
   packaging layer.

Primitive vs. derived:
- primitive public data: the source group `C`, an ambient overgroup `S`, and an embedding
  homomorphism `f : C →* S`;
- derived public properties: simplicity of `S`, injectivity of `f`, and the six-generator bound
  recorded as `Group.rank S ≤ 6`;
- auxiliary instance data: the explicit witness `Group.FG S`, kept only because `Group.rank S`
  is defined through the canonical finite-generation owner.
-/

/-- Theorem 4-3-6: every countable group embeds in a simple group generated by at most six
elements. -/
-- Proof sketch: first embed `C` in a countable simple group using the preceding theorem. Then
-- adjoin two generators for a two-generator overgroup with chosen infinite-order elements and add
-- three further stable letters as in Rabin's construction. The resulting amalgamated product is
-- simple after quotienting by a maximal normal subgroup avoiding the original simple subgroup, and
-- the presentation shows that the ambient simple group has rank at most `6`.
theorem countable_group_embeds_in_six_generator_simple_group :
    ∃ (S : Type u) (_ : Group S) (_ : Group.FG S) (f : C →* S),
      IsSimpleGroup S ∧ Function.Injective f ∧ Group.rank S ≤ 6 := sorry

end
