import Mathlib
import ProbabilityTheory_Klenke_2020.AchimKlenkeLean.Items.Chap05.Theorem_5_28
import ProbabilityTheory_Klenke_2020.AchimKlenkeLean.Items.Chap09.Definition_9_10

-- Declarations for this item will be appended below by the statement pipeline.

open MeasureTheory ProbabilityTheory
open scoped BigOperators

universe u

variable {Ω : Type u} [MeasurableSpace Ω]

noncomputable section

/-- The process obtained by counting how many of the first `n` increments are nonnegative. -/
def nonnegativeCountProcess (Y : ℕ → Ω → ℝ) : ℕ → Ω → ℝ :=
  fun n ω ↦ ∑ i ∈ Finset.range n, if 0 ≤ Y i ω then 1 else 0

-- Proof sketch: unfold `nonnegativeCountProcess`; it is exactly the finite sum of the indicators
-- of the half-line `[0, ∞)` evaluated on the first `n` increments.
/-- The nonnegative-count process evaluates as the finite sum of the indicators of the events
`{Y_i ≥ 0}` over the first `n` coordinates. -/
theorem nonnegativeCountProcess_apply (Y : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) :
    nonnegativeCountProcess Y n ω = ∑ i ∈ Finset.range n, if 0 ≤ Y i ω then 1 else 0 := sorry

-- Proof sketch: each increment `Y i` is measurable, and finite sums of measurable real-valued
-- functions are measurable.
/-- If the increments are measurable, then every partial sum is measurable. -/
theorem partialSum_measurable (Y : ℕ → Ω → ℝ) (hY : ∀ n, Measurable (Y n)) :
    ∀ n, Measurable (partialSum Y n) := sorry

-- Proof sketch: each summand `if 0 ≤ Y i ω then 1 else 0` is a measurable real-valued function of
-- `Y i`, and finite sums preserve measurability.
/-- If the increments are measurable, then every nonnegative-count partial sum is measurable. -/
theorem nonnegativeCountProcess_measurable (Y : ℕ → Ω → ℝ) (hY : ∀ n, Measurable (Y n)) :
    ∀ n, Measurable (nonnegativeCountProcess Y n) := sorry

-- Proof sketch: each summand `Y j` with `j ≤ n` is measurable with respect to its own pullback
-- `σ`-algebra `MeasurableSpace.comap (Y j) (borel ℝ)`, hence also with respect to the supremum
-- over `j ≤ n`; finite sums preserve measurability.
/-- If the increments are measurable, then the partial-sum process is adapted to their generated
filtration. -/
theorem partialSum_measurable_prefix_sigma (Y : ℕ → Ω → ℝ) (hY : ∀ n, Measurable (Y n)) :
    Adapted (generatedFiltration Y hY) (partialSum Y) := sorry

-- Proof sketch: for each `n`, the prefix vector `(Y 0, ..., Y n)` determines the shifted partial
-- sums `(partialSum Y 1, ..., partialSum Y (n + 1))` by finite summation, so the left-hand side is
-- contained in the right-hand side; conversely, `Y 0 = partialSum Y 1` and each later increment is
-- the difference of two successive shifted partial sums, so the right-hand side is contained in the
-- left-hand side.
/-- Example 9.13: for a real-valued increment process `Y 0, Y 1, ...`, the prefix `σ`-algebra
generated by the shifted partial sums `n ↦ partialSum Y (n + 1)` coincides with the generated
filtration of the increments. This is the canonical `0`-based Lean formulation of the textbook
example `X_n = Y_1 + ⋯ + Y_n`. -/
theorem partialSum_prefix_sigma_eq_increment_prefix_sigma
    (Y : ℕ → Ω → ℝ) (hY : ∀ n, Measurable (Y n)) :
    generatedFiltration (fun n ↦ partialSum Y (n + 1))
        (fun n ↦ partialSum_measurable Y hY (n + 1)) =
      generatedFiltration Y hY := sorry

-- Proof sketch: each summand `if 0 ≤ Y i ω then 1 else 0` is a measurable function of `Y i`,
-- hence measurable with respect to the prefix `σ`-algebra generated by `Y 0, ..., Y n`; finite
-- sums preserve measurability.
/-- If the increments are measurable, then the nonnegative-count process is adapted to their
generated filtration. -/
theorem nonnegativeCountProcess_measurable_prefix_sigma
    (Y : ℕ → Ω → ℝ) (hY : ∀ n, Measurable (Y n)) :
    Adapted (generatedFiltration Y hY) (nonnegativeCountProcess Y) := sorry

-- Proof sketch: take the concrete increment process `Y n x = x` on `Ω = ℝ`. Then the prefix
-- `σ`-algebra generated by `Y` at time `1` is the full Borel `σ`-algebra, while the count process
-- at time `1` is just the sign indicator `x ↦ if 0 ≤ x then 1 else 0`, whose generated
-- `σ`-algebra only distinguishes the two half-lines and is therefore strictly smaller.
/-- A concrete counterexample showing that the generated filtration of the nonnegative-count
process can be strictly smaller than the one generated by the original increments. -/
theorem nonnegativeCountProcess_prefix_sigma_strict_at_one_for_identity :
    generatedFiltration (nonnegativeCountProcess (fun (_ : ℕ) (x : ℝ) ↦ x))
        (nonnegativeCountProcess_measurable (fun (_ : ℕ) (x : ℝ) ↦ x) fun _ ↦ measurable_id) 1 <
      generatedFiltration (fun (_ : ℕ) (x : ℝ) ↦ x) (fun _ ↦ measurable_id) 1 := sorry
