import stacks_proof.stacks_project.Chap10.Lemma_10_128_3.Index
open scoped TensorProduct
#check DirectedLocalEssFinitePresentationModuleApproximation.raw_stage_multiplication
#check DirectedLocalEssFinitePresentationModuleApproximation.raw_stage_multiplication_restrictScalars_eq
#check DirectedLocalEssFinitePresentationModuleApproximation.transitionBaseChange
#check DirectedLocalEssFinitePresentationModuleApproximation.stageBaseChangeMap
#check DirectedLocalEssFinitePresentationModuleApproximation.targetMap
#check DirectedLocalEssFinitePresentationModuleApproximation.stageMap
