import Mathlib.Algebra.Module.SpanRank
import Mathlib.RingTheory.Ideal.Oka
import Mathlib.Tactic.StacksAttribute

-- Declarations for this item will be appended below by the statement pipeline.

universe u

section

variable {R : Type u} [CommRing R]

namespace Ideal

open Set

/-- Example 10.28.6: for an infinite cardinal `κ`, the family of ideals of `R` generated by at
most `κ` elements is an Oka family. Canonically, this is the predicate `I.spanRank ≤ κ` on
`Ideal R`. -/
@[stacks 05KD]
-- Proof sketch: follow the proof of `Ideal.isOka_fg`.  The key point is that
-- `(I ⊔ Ideal.span {a}).spanRank ≤ I.spanRank + 1`, so an infinite cardinal bound `κ` absorbs the
-- extra singleton generator.  Combining generators for `I.colon (Ideal.span {a})` and
-- `I ⊔ Ideal.span {a}` then yields a generating family for `I` of cardinality at most `κ`.
  theorem isOka_spanRank_le (κ : Cardinal) (hκ : Cardinal.aleph0 ≤ κ) :
    IsOka (fun I : Ideal R ↦ I.spanRank ≤ κ) where
  top := by
    calc
      (⊤ : Ideal R).spanRank = (span ({1} : Set R)).spanRank := by rw [span_singleton_one]
      _ ≤ Cardinal.mk ↑({1} : Set R) := Submodule.spanRank_span_le_card ({1} : Set R)
      _ ≤ κ := by simpa using Cardinal.one_le_aleph0.trans hκ
  oka {I} {a} hsup hcolon := by
    classical
    let A : Ideal R := span ({a} : Set R)
    let J : Ideal R := I ⊔ A
    let K : Ideal R := I.colon A
    rw [Submodule.FG.spanRank_le_iff_exists_span_set_card_le J] at hsup
    obtain ⟨s, hs_card, hs_span⟩ := hsup
    rw [Submodule.FG.spanRank_le_iff_exists_span_set_card_le K] at hcolon
    obtain ⟨t, ht_card, ht_span⟩ := hcolon
    have hs_decomp (x : s) : ∃ r : R, ∃ p ∈ I, r * a + p = (x : R) := by
      have hx' : (x : R) ∈ J := by
        rw [← hs_span]
        exact subset_span x.2
      have hx : (x : R) ∈ A ⊔ I := by simpa [A, J, sup_comm] using hx'
      exact mem_span_singleton_sup.1 <| by simpa [A] using hx
    choose r p hp hEq using hs_decomp
    let pImage : Set R := range p
    let aMulImage : Set R := (fun y : R ↦ y * a) '' t
    have hpImage_spanRank : (span pImage).spanRank ≤ κ := by
      calc
        (span pImage).spanRank ≤ Cardinal.mk ↑pImage := Submodule.spanRank_span_le_card pImage
        _ ≤ Cardinal.mk ↑s := Cardinal.mk_range_le
        _ ≤ κ := hs_card
    have haMulImage_spanRank : (span aMulImage).spanRank ≤ κ := by
      calc
        (span aMulImage).spanRank ≤ Cardinal.mk ↑aMulImage :=
          Submodule.spanRank_span_le_card aMulImage
        _ ≤ Cardinal.mk ↑t := Cardinal.mk_image_le
        _ ≤ κ := ht_card
    have hpImage_le : span pImage ≤ I := by
      refine span_le.2 ?_
      rintro x ⟨y, rfl⟩
      exact hp y
    have haMulImage_le : span aMulImage ≤ I := by
      refine span_le.2 ?_
      rintro x ⟨y, hy, rfl⟩
      have hy_colon : y ∈ K := by
        rw [← ht_span]
        exact subset_span hy
      exact mem_colon_span_singleton.1 <| by simpa [K, A] using hy_colon
    have hI_eq : I = span pImage ⊔ span aMulImage := by
      refine le_antisymm ?_ (sup_le hpImage_le haMulImage_le)
      intro x hx
      have hx_span : x ∈ span s := by
        have hx' : x ∈ J := mem_sup_left hx
        rw [← hs_span, submodule_span_eq] at hx'
        exact hx'
      obtain ⟨n, c, g, hg⟩ := Submodule.mem_span_set'.1 hx_span
      let pSum : R := ∑ i, c i * p (g i)
      let b : R := ∑ i, c i * r (g i)
      have hpSum_mem : pSum ∈ span pImage := by
        dsimp [pSum, pImage]
        refine Submodule.sum_mem _ fun i _ ↦ ?_
        exact (span pImage).mul_mem_left (c i) (subset_span ⟨g i, rfl⟩)
      have h_formula : x = pSum + b * a := by
        calc
          x = ∑ i, c i * (g i : R) := hg.symm
          _ = ∑ i, (c i * p (g i) + (c i * r (g i)) * a) := by
            refine Finset.sum_congr rfl fun i _ ↦ ?_
            calc
              c i * (g i : R) = c i * (r (g i) * a + p (g i)) := by rw [← hEq (g i)]
              _ = c i * p (g i) + (c i * r (g i)) * a := by ring
          _ = pSum + b * a := by
            simp [pSum, b, Finset.sum_add_distrib, Finset.sum_mul]
      have hpSum_mem_I : pSum ∈ I := by
        dsimp [pSum]
        refine Submodule.sum_mem _ fun i _ ↦ ?_
        exact I.mul_mem_left (c i) (hp (g i))
      have hb_mul_mem : b * a ∈ I := by
        have hx_sub : x - pSum ∈ I := I.sub_mem hx hpSum_mem_I
        have hb_mul_eq : b * a = x - pSum := by
          rw [h_formula, add_sub_cancel_left]
        exact hb_mul_eq ▸ hx_sub
      have hb_colon : b ∈ K := by
        exact mem_colon_span_singleton.2 <| by simpa [A] using hb_mul_mem
      have hb_span : b ∈ span t := by
        have hb_span' : b ∈ Submodule.span R t := by
          rw [ht_span]
          exact hb_colon
        simpa [submodule_span_eq] using hb_span'
      have hbv_mem : b * a ∈ span aMulImage := by
        exact (Submodule.image_span_subset_span (LinearMap.mulRight R a) t) ⟨b, hb_span, rfl⟩
      exact Submodule.mem_sup.2 ⟨pSum, hpSum_mem, b * a, hbv_mem, h_formula.symm⟩
    calc
      I.spanRank = (span pImage ⊔ span aMulImage).spanRank := by rw [hI_eq]
      _ ≤ (span pImage).spanRank + (span aMulImage).spanRank :=
        Submodule.spanRank_sup_le_sum_spanRank
      _ ≤ κ + κ := add_le_add hpImage_spanRank haMulImage_spanRank
      _ = κ := by rw [Cardinal.add_eq_max hκ, max_eq_left le_rfl]

end Ideal

end
