import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

universe u v

section

variable {R : Type u} [CommRing R]
variable (I : Ideal R)
variable (M : Type v) [AddCommGroup M] [Module R M]

/- Lemma 10.96.3 (1): for a finitely generated ideal `I`, the `I`-adic completion `AdicCompletion I M`
is `I`-adically complete. -/
recall AdicCompletion.isAdicComplete

/- Lemma 10.96.3 (2): for every positive integer `n`, the kernel of the canonical map
`AdicCompletion I M → M ⧸ (I ^ n • ⊤)` is exactly `I ^ n` times the completed module. -/
recall AdicCompletion.pow_smul_top_eq_ker_eval

/- Companion bridge: the canonical map `AdicCompletion.ofPowSMul` from the completion of `I ^ n M`
into the completion of `M` has image equal to the kernel of the evaluation map. -/
recall AdicCompletion.restrictScalars_range_ofPowSMul_eq_ker_eval

end

section

variable {R : Type u} [CommRing R]
variable (I : Ideal R)

/-- Helper for Lemma 10.96.3: after restricting scalars to `R`, the kernel of the algebra-valued
evaluation map agrees with the kernel of the underlying linear evaluation map. -/
lemma ker_evalₐ_restrictScalars_eq_ker_eval (n : ℕ) :
    (((RingHom.ker (AdicCompletion.evalₐ I n) : Ideal (AdicCompletion I R)) :
        Submodule (AdicCompletion I R) (AdicCompletion I R)).restrictScalars R) =
      (AdicCompletion.eval I R n).ker := by
  have hle₁ : (I ^ n : Ideal R) ≤ I ^ n • (⊤ : Submodule R R) := by
    simpa [Ideal.smul_eq_mul] using le_of_eq (Ideal.mul_top (I ^ n)).symm
  have hle₂ : I ^ n • (⊤ : Submodule R R) ≤ (I ^ n : Ideal R) := by
    simpa [Ideal.smul_eq_mul] using le_of_eq (Ideal.mul_top (I ^ n))
  -- Compare kernel membership by transporting vanishing across the canonical quotient factors.
  ext x
  rw [Submodule.restrictScalars_mem, RingHom.mem_ker, LinearMap.mem_ker]
  constructor
  · intro hx
    simpa [hx] using (AdicCompletion.factor_evalₐ_eq_eval (I := I) (n := n) x hle₁).symm
  · intro hx
    simpa [hx] using (AdicCompletion.factor_eval_eq_evalₐ (I := I) (n := n) x hle₂).symm

-- Proof sketch: compare the ring-theoretic map `AdicCompletion.evalₐ I n` with the module map
-- `AdicCompletion.eval I R n`, then translate the kernel description from the module theorem into
-- an equality of ideals in `AdicCompletion I R`.
/-- For every `n : ℕ`, the ideal generated by `I ^ n` in the completed ring is the kernel of the
canonical map `AdicCompletion I R → R ⧸ I ^ n`. -/
theorem completionIdeal_pow_eq_ker_evalₐ (hI : I.FG) (n : ℕ) :
    Ideal.map (algebraMap R (AdicCompletion I R)) (I ^ n) =
      RingHom.ker (AdicCompletion.evalₐ I n) := by
  -- Restrict scalars so the goal matches the module-side kernel statement from the completion API.
  apply Submodule.restrictScalars_injective R (AdicCompletion I R) (AdicCompletion I R)
  -- The left-hand ideal map becomes `I ^ n • ⊤`, which is exactly the source-proof image term.
  calc
    (((Ideal.map (algebraMap R (AdicCompletion I R)) (I ^ n) : Ideal (AdicCompletion I R)) :
        Submodule (AdicCompletion I R) (AdicCompletion I R)).restrictScalars R) =
        I ^ n • (⊤ : Submodule R (AdicCompletion I R)) := by
          simpa [Ideal.smul_top_eq_map]
    _ = (AdicCompletion.eval I R n).ker := by
      -- Finite generation gives the kernel description on the completed module.
      simpa using (AdicCompletion.pow_smul_top_eq_ker_eval (I := I) (M := R) (n := n) hI)
    _ =
        (((RingHom.ker (AdicCompletion.evalₐ I n) : Ideal (AdicCompletion I R)) :
          Submodule (AdicCompletion I R) (AdicCompletion I R)).restrictScalars R) := by
      -- The algebra-valued and linear evaluation maps have the same kernel after restricting scalars.
      symm
      exact ker_evalₐ_restrictScalars_eq_ker_eval (I := I) n

end
