import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

section

variable {R : Type u} [CommRing R] [Nontrivial R]
variable {M : Type v} [AddCommGroup M] [Module R M]

/-- Lemma 10.15.7: if an `R`-module `M` is generated by fewer than `n` elements, encoded
canonically as `(⊤ : Submodule R M).spanRank < n`, then every `R`-linear map
`R^{\oplus n} → M` has nonzero kernel. This is the source-facing bridge from the
generation hypothesis to the owner `rank`/`spanRank` comparison API. -/
@[stacks 05WI]
theorem linearMap_ker_ne_bot_of_spanRank_lt
    {n : ℕ} (hgen : (⊤ : Submodule R M).spanRank < n) (f : (Fin n → R) →ₗ[R] M) :
    LinearMap.ker f ≠ ⊥ := by
  intro hker
  have hrank : n ≤ Module.rank R M :=
    Module.le_rank_iff_exists_linearMap.2 ⟨f, LinearMap.ker_eq_bot.mp hker⟩
  exact (not_lt_of_ge (hrank.trans Submodule.rank_le_spanRank) hgen).elim

end
