import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

universe u v w z

open IsScalarTower (toAlgHom)
open KaehlerDifferential

variable (R : Type u) (R' : Type v) {S : Type w} {S' : Type z}
  [CommRing R] [CommRing R'] [CommRing S] [CommRing S']
  [Algebra R S] [Algebra R R'] [Algebra R S'] [Algebra R' S'] [Algebra S S']
  [IsScalarTower R S S'] [IsScalarTower R R' S']

/-- Helper for Lemma 10.131.6: the presentation map on free `Finsupp` modules induced by
`S → S'`. -/
private noncomputable abbrev presentationMap : (S →₀ S) →ₗ[S] (S' →₀ S') :=
  (Finsupp.mapRange.linearMap (Algebra.linearMap S S')).comp
    (Finsupp.lmapDomain S S (algebraMap S S'))

/-- Helper for Lemma 10.131.6: the `S`-span of free generators indexed by the pullback
subalgebra of `range (R' → S')`. -/
private noncomputable abbrev pullbackGeneratorSpan : Submodule S (S →₀ S) :=
  Submodule.span S
    (Set.range fun a : Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦
      Finsupp.single a.1 (1 : S))

/-- Helper for Lemma 10.131.6: the `S`-span of free generators indexed by the image of
`R' → S'`. -/
private noncomputable abbrev rangeGeneratorSpan : Submodule S (S' →₀ S') :=
  Submodule.span S
    (Set.range fun r' : R' ↦ Finsupp.single (algebraMap R' S' r') (1 : S'))

/-- Helper for Lemma 10.131.6: the target `S`-submodule generated by differentials of elements
whose image in `S'` comes from `R'`. -/
private noncomputable abbrev pullbackDifferentialSpan : Submodule S Ω[S⁄R] :=
  Submodule.span S
    (Set.range fun a :
      Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1)

local notation "presentationMap0" => (presentationMap (S := S) (S' := S'))
local notation "pullbackGeneratorSpan0" =>
  (pullbackGeneratorSpan R R' (S := S) (S' := S'))
local notation "rangeGeneratorSpan0" =>
  (rangeGeneratorSpan R' (S := S) (S' := S'))
local notation "pullbackDifferentialSpan0" =>
  (pullbackDifferentialSpan R R' (S := S) (S' := S'))

-- Proof sketch: the presentation map sends `single a 1` to `single (φ a) 1`. The pullback
-- condition says precisely that `φ a` lies in the image of `R' → S'`, and surjectivity of `φ`
-- supplies a lift for every codomain generator.
/-- Helper for Lemma 10.131.6: mapping the pullback presentation generators across `S → S'`
produces exactly the generators coming from `R' → S'`. -/
private theorem pullback_generator_span_map_eq_range_generator_span
    (hφ : Function.Surjective (algebraMap S S')) :
    ((pullbackGeneratorSpan0 : Submodule S (S →₀ S)).map presentationMap0) =
      (rangeGeneratorSpan0 : Submodule S (S' →₀ S')) := by
  refine le_antisymm ?_ ?_
  · -- Every pullback generator maps to a codomain generator indexed by some `r' : R'`.
    unfold rangeGeneratorSpan pullbackGeneratorSpan
    rw [Submodule.map_span]
    refine Submodule.span_le.2 ?_
    rintro _ ⟨_, ⟨a, rfl⟩, rfl⟩
    rcases (Subalgebra.mem_comap _ _ _).1 a.2 with ⟨r', hr'⟩
    unfold presentationMap
    rw [LinearMap.comp_apply, Finsupp.lmapDomain_apply, Finsupp.mapDomain_single,
      Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_single, Algebra.linearMap_apply, map_one]
    exact Submodule.subset_span ⟨r', by
      simpa using congrArg (fun x : S' ↦ Finsupp.single x (1 : S')) hr'⟩
  · -- Surjectivity of `S → S'` lets us lift each codomain generator back to the pullback side.
    unfold rangeGeneratorSpan
    refine Submodule.span_le.2 ?_
    rintro _ ⟨r', rfl⟩
    obtain ⟨a, ha⟩ := hφ (algebraMap R' S' r')
    have ha_pullback : a ∈ Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range := by
      rw [Subalgebra.mem_comap, AlgHom.mem_range]
      exact ⟨r', ha.symm⟩
    refine Submodule.mem_map.2 ?_
    refine ⟨Finsupp.single a (1 : S), ?_, ?_⟩
    · exact Submodule.subset_span ⟨⟨a, ha_pullback⟩, rfl⟩
    · unfold presentationMap
      rw [LinearMap.comp_apply, Finsupp.lmapDomain_apply, Finsupp.mapDomain_single,
        Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_single, Algebra.linearMap_apply, map_one,
        ha]

-- Proof sketch: `linearCombination` sends the basis vector `single a 1` to the universal
-- differential `d a`, so mapping the pullback generator span simply replaces free generators by
-- their differentials.
/-- Helper for Lemma 10.131.6: applying `linearCombination` to the pullback presentation span
turns the generators `single a 1` into the differentials `d a`. -/
private theorem pullback_generator_span_linearCombination_eq_d_span :
    ((pullbackGeneratorSpan0 : Submodule S (S →₀ S)).map
        (Finsupp.linearCombination S (D R S))) =
      Submodule.span S
        (Set.range fun a :
          Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1) := by
  unfold pullbackGeneratorSpan
  rw [Submodule.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨y, ⟨a, rfl⟩, rfl⟩
    exact ⟨a, by simp [Finsupp.linearCombination_single]⟩
  · rintro ⟨a, rfl⟩
    refine ⟨Finsupp.single a.1 (1 : S), ⟨a, rfl⟩, ?_⟩
    simp [Finsupp.linearCombination_single]

/-- Helper for Lemma 10.131.6: if `a` maps to `0` in `S'`, then `d a` already lies in the
pullback differential span. -/
private theorem d_mem_pullback_differential_span_of_map_eq_zero
    {a : S} (ha : algebraMap S S' a = 0) :
    D R S a ∈
      Submodule.span S
        (Set.range fun a :
          Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1) := by
  -- The zero element of `S'` lies in the image of `R' → S'`, so `a` indexes one of the generators.
  have ha_pullback : a ∈ Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range := by
    rw [Subalgebra.mem_comap, AlgHom.mem_range]
    exact ⟨0, by simpa [ha]⟩
  exact Submodule.subset_span ⟨⟨a, ha_pullback⟩, rfl⟩

/-- Helper for Lemma 10.131.6: if `c` maps to `0` in `S'`, then every scalar multiple
`c • d a` lies in the pullback differential span. -/
private theorem smul_d_mem_pullback_differential_span_of_map_eq_zero
    {c a : S} (hc : algebraMap S S' c = 0) :
    c • D R S a ∈
      Submodule.span S
        (Set.range fun a :
          Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1) := by
  let dSpan : Submodule S Ω[S⁄R] :=
    Submodule.span S
      (Set.range fun a :
        Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1)
  -- Leibniz rewrites `c • d a` in terms of differentials of elements mapping to zero.
  have hc_mem : D R S c ∈ dSpan := by
    change D R S c ∈
      Submodule.span S
        (Set.range fun a :
          Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1)
    exact d_mem_pullback_differential_span_of_map_eq_zero
      (R := R) (R' := R') (S := S) (S' := S') hc
  have hmul_mem : D R S (c * a) ∈ dSpan := by
    change D R S (c * a) ∈
      Submodule.span S
        (Set.range fun a :
          Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1)
    apply d_mem_pullback_differential_span_of_map_eq_zero
      (R := R) (R' := R') (S := S) (S' := S')
    simp [hc]
  have hrewrite : c • D R S a = D R S (c * a) - a • D R S c := by
    exact eq_sub_iff_add_eq.mpr (by simpa [add_comm] using ((D R S).leibniz c a).symm)
  change c • D R S a ∈ dSpan
  rw [hrewrite]
  exact Submodule.sub_mem dSpan hmul_mem (Submodule.smul_mem dSpan a hc_mem)

/-- Helper for Lemma 10.131.6: after subtracting a source `kerTotal` relation, any presentation
term mapping into the target `kerTotal` can be normalized into the `R'`-generator span. -/
private theorem presentationMap_mem_rangeGeneratorSpan_after_sub_kerTotal
    (hφ : Function.Surjective (algebraMap S S')) {x : S →₀ S}
    (hx : presentationMap0 x ∈
      ((KaehlerDifferential.kerTotal R' S').restrictScalars S)) :
    ∃ y : S →₀ S,
      y ∈ KaehlerDifferential.kerTotal R S ∧
      presentationMap0 (x - y) ∈ (rangeGeneratorSpan0 : Submodule S (S' →₀ S')) := by
  -- The owner presentation theorem splits target `kerTotal` into the image of source relations
  -- plus the free generators indexed by the image of `R' → S'`.
  have hx' :
      presentationMap0 x ∈
        (KaehlerDifferential.kerTotal R S).map
            presentationMap0 ⊔
          (rangeGeneratorSpan0 : Submodule S (S' →₀ S')) := by
    rw [KaehlerDifferential.kerTotal_map (R := R) (S := R') (A := S) (B := S') hφ]
    exact hx
  -- Splitting the membership in the supremum produces the correction term coming from
  -- `kerTotal R S` and the residual `R'`-generator contribution.
  obtain ⟨u, hu, v, hv, huv⟩ := Submodule.mem_sup.mp hx'
  rcases Submodule.mem_map.mp hu with ⟨y, hy, rfl⟩
  refine ⟨y, hy, ?_⟩
  have hsub :
      presentationMap0 (x - y) = v := by
    rw [LinearMap.map_sub]
    exact (sub_eq_iff_eq_add').2 huv.symm
  simpa [hsub] using hv
/-- Helper for Lemma 10.131.6: if a presentation term maps to zero, then after summing the
coefficients on each fiber of `S → S'`, every fiber sum already lies in `ker(S → S')`. -/
private theorem presentationMap_eq_zero_coefficients_map_eq_zero
    {x : S →₀ S}
    (hx : presentationMap0 x = 0) :
    ∀ a' : S',
      algebraMap S S'
        ((Finsupp.lmapDomain S S (algebraMap S S')) x a') = 0 := by
  let z : S' →₀ S := (Finsupp.lmapDomain S S (algebraMap S S')) x
  have hzKer :
      z ∈ LinearMap.ker
        (Finsupp.mapRange.linearMap (Algebra.linearMap S S') : (S' →₀ S) →ₗ[S] (S' →₀ S')) := by
    -- Rewriting the presentation map isolates the coefficient map on the fiber-summed term `z`.
    rw [LinearMap.mem_ker]
    simpa [presentationMap, z, LinearMap.comp_apply] using hx
  have hzCoeff :
      z ∈ Finsupp.submodule (fun _ : S' => LinearMap.ker (Algebra.linearMap S S')) := by
    rwa [Finsupp.ker_mapRange] at hzKer
  intro a'
  -- Membership in the product kernel submodule is exactly the pointwise coefficient condition.
  have hzPoint :=
    (Finsupp.mem_submodule_iff (fun _ : S' => LinearMap.ker (Algebra.linearMap S S')) z).1 hzCoeff a'
  simpa [LinearMap.mem_ker, z] using hzPoint

/-- Helper for Lemma 10.131.6: lifting a fiber-summed presentation term along any section
produces a linear combination of differentials whose coefficients already lie in `ker(S → S')`,
hence it belongs to the pullback differential span. -/
private theorem section_lift_linearCombination_mem_pullbackDifferentialSpan
    (σ : S' → S) {z : S' →₀ S}
    (hz : ∀ a' : S', algebraMap S S' (z a') = 0) :
    Finsupp.linearCombination S (D R S) ((Finsupp.lmapDomain S S σ) z) ∈
      (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
  classical
  -- After rewriting along `mapDomain`, each fiber contributes one scalar multiple of `d (σ a')`.
  rw [Finsupp.lmapDomain_apply, Finsupp.linearCombination_mapDomain, Finsupp.linearCombination_apply]
  refine Submodule.sum_mem _ ?_
  intro a' ha'
  exact smul_d_mem_pullback_differential_span_of_map_eq_zero
    (R := R) (R' := R') (S := S) (S' := S') (c := z a') (a := σ a') (hz a')

/-- Helper for Lemma 10.131.6: the differential of a singleton fiber-difference is the scalar
multiple of the differential of the underlying source-ring difference. -/
private theorem linearCombination_single_sub_section_single
    (a b c : S) :
    Finsupp.linearCombination S (D R S) (Finsupp.single a c - Finsupp.single b c) =
      c • D R S (a - b) := by
  -- The two singleton generators subtract to the differential of the difference `a - b`.
  calc
    Finsupp.linearCombination S (D R S) (Finsupp.single a c - Finsupp.single b c)
        = c • D R S a - c • D R S b := by
            simp [Finsupp.linearCombination_single]
    _ = c • (D R S a - D R S b) := by rw [smul_sub]
    _ = c • D R S (a - b) := by rw [(D R S).map_sub]

/-- Helper for Lemma 10.131.6: replacing each source generator by the chosen representative of
its image fiber changes the differential by elements coming from `ker(S → S')`, so the residual
fiber-difference term already lies in the pullback differential span. -/
private theorem fiber_difference_linearCombination_mem_pullbackDifferentialSpan
    (σ : S' → S) (hσ : Function.RightInverse σ (algebraMap S S')) :
    ∀ x : S →₀ S,
      Finsupp.linearCombination S (D R S)
          (x - (Finsupp.lmapDomain S S σ)
            ((Finsupp.lmapDomain S S (algebraMap S S')) x)) ∈
        (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
  intro x
  induction x using Finsupp.induction_linear with
  | zero =>
      -- The normalized residual of the zero presentation term is zero.
      simpa using (Submodule.zero_mem (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]))
  | add x y hx hy =>
      -- Both `lmapDomain` maps are linear, so the residual decomposition is additive.
      have hsplit :
          x + y -
              (Finsupp.lmapDomain S S σ)
                ((Finsupp.lmapDomain S S (algebraMap S S')) (x + y)) =
            (x - (Finsupp.lmapDomain S S σ)
                ((Finsupp.lmapDomain S S (algebraMap S S')) x)) +
              (y - (Finsupp.lmapDomain S S σ)
                ((Finsupp.lmapDomain S S (algebraMap S S')) y)) := by
        ext a
        rw [Finsupp.lmapDomain_apply, Finsupp.lmapDomain_apply, Finsupp.lmapDomain_apply,
          Finsupp.lmapDomain_apply, Finsupp.lmapDomain_apply, Finsupp.lmapDomain_apply,
          Finsupp.mapDomain_add, Finsupp.mapDomain_add]
        abel_nf
      rw [hsplit, LinearMap.map_add]
      exact Submodule.add_mem _ hx hy
  | single a c =>
      -- On a singleton, the normalization subtracts the chosen representative of the same fiber.
      have hsingle :
          Finsupp.single a c -
              (Finsupp.lmapDomain S S σ)
                ((Finsupp.lmapDomain S S (algebraMap S S')) (Finsupp.single a c)) =
            Finsupp.single a c - Finsupp.single (σ (algebraMap S S' a)) c := by
        simp [Finsupp.lmapDomain_apply, Finsupp.mapDomain_single]
      have hzero : algebraMap S S' (a - σ (algebraMap S S' a)) = 0 := by
        -- The section representative has the same image in `S'`, so the difference maps to zero.
        simp [map_sub, hσ (algebraMap S S' a)]
      rw [hsingle, linearCombination_single_sub_section_single]
      exact Submodule.smul_mem _
        c
        (d_mem_pullback_differential_span_of_map_eq_zero
          (R := R) (R' := R') (S := S) (S' := S') hzero)

/-- Helper for Lemma 10.131.6: once the presentation representative lands in the
`R'`-generator span, it suffices to lift those generators back to the pullback side and reduce to
the case `presentationMap x = 0`. -/
private theorem linearCombination_mem_pullbackDifferentialSpan_of_presentationMap_eq_zero
    (hφ : Function.Surjective (algebraMap S S')) {x : S →₀ S}
    (hx : presentationMap0 x = 0) :
    Finsupp.linearCombination S (D R S) x ∈
      (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
  classical
  let φ : S → S' := algebraMap S S'
  let σ : S' → S := Function.surjInv hφ
  have hσ : Function.RightInverse σ φ := Function.rightInverse_surjInv hφ
  let z : S' →₀ S := (Finsupp.lmapDomain S S φ) x
  let lift : S →₀ S := (Finsupp.lmapDomain S S σ) z
  -- Route correction: normalize the presentation term by choosing one representative in each fiber.
  have hz : ∀ a' : S', algebraMap S S' (z a') = 0 := by
    simpa [z, φ] using
      (presentationMap_eq_zero_coefficients_map_eq_zero
        (S := S) (S' := S') hx)
  have hlift :
      Finsupp.linearCombination S (D R S) lift ∈
        (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
    -- The lifted fiber sums have coefficients in `ker(S → S')`, so their differentials are allowed.
    simpa [lift, z] using
      (section_lift_linearCombination_mem_pullbackDifferentialSpan
        (R := R) (R' := R') (S := S) (S' := S') (σ := σ) (z := z) hz)
  have hresidual :
      Finsupp.linearCombination S (D R S) (x - lift) ∈
        (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
    -- Subtracting the chosen fiber representatives leaves only differences mapping to zero.
    simpa [lift, z, φ] using
      (fiber_difference_linearCombination_mem_pullbackDifferentialSpan
        (R := R) (R' := R') (S := S) (S' := S') (σ := σ) hσ x)
  have hsplit :
      Finsupp.linearCombination S (D R S) x =
        Finsupp.linearCombination S (D R S) (x - lift) +
          Finsupp.linearCombination S (D R S) lift := by
    -- The source proof writes `x` as the residual fiber-difference plus the lifted fiber sums.
    rw [← LinearMap.map_add, sub_add_cancel]
  rw [hsplit]
  exact Submodule.add_mem _ hresidual hlift

/-- Helper for Lemma 10.131.6: a presentation representative whose image lies in the
`R'`-generator span already maps into the pullback differential span. -/
private theorem linearCombination_mem_pullbackDifferentialSpan_of_presentationMap_mem_rangeGeneratorSpan
    (hφ : Function.Surjective (algebraMap S S')) {x : S →₀ S}
    (hx : presentationMap0 x ∈ (rangeGeneratorSpan0 : Submodule S (S' →₀ S'))) :
    Finsupp.linearCombination S (D R S) x ∈
      (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
  -- Surjectivity lifts the `R'`-generator presentation term to the pullback generator span.
  have hxLift :
      presentationMap0 x ∈ ((pullbackGeneratorSpan0 : Submodule S (S →₀ S)).map presentationMap0) := by
    rw [pullback_generator_span_map_eq_range_generator_span
      (R := R) (R' := R') (S := S) (S' := S') hφ]
    exact hx
  rcases Submodule.mem_map.mp hxLift with ⟨w, hw, hwx⟩
  -- Subtracting this lift reduces to the kernel case `presentationMap (x - w) = 0`.
  have hzero :
      presentationMap0 (x - w) = 0 := by
    rw [LinearMap.map_sub, hwx, sub_self]
  have hkernel :
      Finsupp.linearCombination S (D R S) (x - w) ∈
        (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
    exact linearCombination_mem_pullbackDifferentialSpan_of_presentationMap_eq_zero
      (R := R) (R' := R') (S := S) (S' := S') hφ hzero
  -- The lifted pullback generators already map to the span generated by the allowed
  -- differentials.
  have hwSpan :
      Finsupp.linearCombination S (D R S) w ∈
        (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
    have hwMap :
      Finsupp.linearCombination S (D R S) w ∈
          ((pullbackGeneratorSpan0 : Submodule S (S →₀ S)).map
            (Finsupp.linearCombination S (D R S))) :=
      Submodule.mem_map.2 ⟨w, hw, rfl⟩
    have hmap :
        ((pullbackGeneratorSpan0 : Submodule S (S →₀ S)).map
            (Finsupp.linearCombination S (D R S))) =
          pullbackDifferentialSpan0 := by
      simpa [pullbackDifferentialSpan] using
        pullback_generator_span_linearCombination_eq_d_span
          (R := R) (R' := R') (S := S) (S' := S')
    rw [hmap] at hwMap
    exact hwMap
  -- Linearity reconstructs the original differential from the kernel part and the lifted
  -- pullback-generator part.
  have hsplit :
      Finsupp.linearCombination S (D R S) x =
        Finsupp.linearCombination S (D R S) (x - w) +
          Finsupp.linearCombination S (D R S) w := by
    rw [← LinearMap.map_add, sub_add_cancel]
  rw [hsplit]
  exact Submodule.add_mem _ hkernel hwSpan

/-- Helper for Lemma 10.131.6: the source-proof kernel inclusion factors through the quotient by
the pullback differential span. -/
private theorem ker_map_le_pullback_differential_span_via_universal_property
    (hφ : Function.Surjective (algebraMap S S')) :
    LinearMap.ker (map R R' S S') ≤
      (pullbackDifferentialSpan0 : Submodule S Ω[S⁄R]) := by
  intro η hη
  -- Route correction: return to the source's first proof and work with a presentation
  -- representative coming from `KaehlerDifferential.ker_map`.
  rw [KaehlerDifferential.ker_map (R := R) (S := R') (A := S) (B := S')] at hη
  rcases Submodule.mem_map.mp hη with ⟨x, hx, rfl⟩
  have hxKerTotal :
      presentationMap0 x ∈
        ((KaehlerDifferential.kerTotal R' S').restrictScalars S) := by
    simpa [Submodule.mem_comap] using hx
  -- Subtract the source `kerTotal` part so only the `R'`-generator span remains.
  rcases presentationMap_mem_rangeGeneratorSpan_after_sub_kerTotal
      (R := R) (R' := R') (S := S) (S' := S') hφ hxKerTotal with ⟨y, hy, hxy⟩
  have hyZero :
      Finsupp.linearCombination S (D R S) y = 0 := by
    have hyKer : y ∈ LinearMap.ker (Finsupp.linearCombination S (D R S)) := by
      simpa [KaehlerDifferential.kerTotal_eq (R := R) (S := S)] using hy
    simpa [LinearMap.mem_ker] using hyKer
  have hxySpan :
      Finsupp.linearCombination S (D R S) (x - y) ∈
        pullbackDifferentialSpan0 := by
    exact linearCombination_mem_pullbackDifferentialSpan_of_presentationMap_mem_rangeGeneratorSpan
      (R := R) (R' := R') (S := S) (S' := S') hφ hxy
  -- The `kerTotal` correction vanishes under `linearCombination`, so the normalized element is
  -- exactly the original differential class.
  have hxyEq :
      Finsupp.linearCombination S (D R S) (x - y) =
        Finsupp.linearCombination S (D R S) x := by
    rw [LinearMap.map_sub, hyZero, sub_zero]
  simpa [hxyEq] using hxySpan

-- Proof sketch: the surjectivity clause is the owner theorem
-- `KaehlerDifferential.map_surjective_of_surjective`. For the kernel, specialize the owner kernel
-- description `KaehlerDifferential.ker_map` to this square and rewrite it through the source-facing
-- pullback subalgebra `Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range`.
/-- Lemma 10.131.6: if `S → S'` is surjective in a commutative square
`R → S`, `R → R'`, `R' → S'`, `S → S'`, then the induced map
`Ω[S⁄R] → Ω[S'⁄R']` is surjective, and its kernel is the `S`-submodule generated by the
differentials `d a` of elements whose image in `S'` lies in the image of `R' → S'`. In
particular, this generating set contains every `d i` with `i` in the kernel of `S → S'`. -/
@[stacks 00RR]
theorem kaehlerDifferential_map_surjective_and_ker_eq_span_d_mem_range
    (hφ : Function.Surjective (algebraMap S S')) :
    Function.Surjective (map R R' S S') ∧
      LinearMap.ker (map R R' S S') =
        Submodule.span S
          (Set.range fun a :
            Subalgebra.comap (toAlgHom R S S') (toAlgHom R R' S').range ↦ D R S a.1) := by
  constructor
  · -- The surjectivity statement is exactly the owner theorem for Kähler differentials.
    exact KaehlerDifferential.map_surjective_of_surjective R R' S S' hφ
  · -- Route correction: use the source proof's first presentation argument, not the abandoned
    -- quotient-transport route from earlier attempts.
    refine le_antisymm ?_ ?_
    · simpa [pullbackDifferentialSpan] using
        ker_map_le_pullback_differential_span_via_universal_property
          (R := R) (R' := R') (S := S) (S' := S') hφ
    · -- Generators coming from the pullback image map to zero because they are already differentials
      -- of elements in the image of `R' → S'`.
      change pullbackDifferentialSpan0 ≤ LinearMap.ker (map R R' S S')
      refine Submodule.span_le.2 ?_
      rintro _ ⟨a, rfl⟩
      change map R R' S S' (D R S a.1) = 0
      rw [KaehlerDifferential.map_D]
      rcases (Subalgebra.mem_comap _ _ _).1 a.2 with ⟨r', hr'⟩
      have hr'' : algebraMap S S' a.1 = algebraMap R' S' r' := by
        simpa using hr'.symm
      rw [hr'']
      simpa using (KaehlerDifferential.D R' S').map_algebraMap r'
