import Mathlib
import Mathlib.Tactic.Recall
import Mathlib.Algebra.Module.LocalizedModule.Submodule
import stacks_proof.stacks_project.Chap10.Lemma_10_67_2
import stacks_proof.stacks_project.Chap10.Lemma_10_63_16
import stacks_proof.stacks_project.Chap10.Lemma_10_40_6

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open scoped TensorProduct

section

variable (R : Type u) [CommRing R]
variable (M : Type v) [AddCommGroup M] [Module R M]

/- Layering for this item.
Sampled declarations in this localization/quotient domain:
* `embeddedPrimeFreeSubmodule` from `Lemma_10_67_2` is the source-facing submodule.
* `localizedQuotientEquiv` is the owner equivalence for localizing quotients.
* `Submodule.quotEquivOfEq` is the canonical rewrite once the localized submodule is identified.
* `Lemma_10_9_13` already recalls the same owner pattern for localized quotients in this chapter.
Target triage:
* source-facing: the quotient identification
  `LocalizedModule.Away f (M ⧸ embeddedPrimeFreeSubmodule R M) ≃ₗ[Localization.Away f]
    (LocalizedModule.Away f M ⧸
      embeddedPrimeFreeSubmodule (Localization.Away f) (LocalizedModule.Away f M))`.
* core/canonical owner: `localizedQuotientEquiv`.
* bridge/view: the supporting equality
  `(embeddedPrimeFreeSubmodule R M).localized (.powers f) =
    embeddedPrimeFreeSubmodule (Localization.Away f) (LocalizedModule.Away f M)`
  rewrites the owner equivalence into the source-facing quotient statement.
-/

/- Core/canonical owner recall: localization of quotients is controlled by
`localizedQuotientEquiv`. -/
recall localizedQuotientEquiv

variable (f : R)

local notation "Rloc" => Localization.Away f
local notation "Mloc" => LocalizedModule.Away f M

/-- Helper for Lemma 10.67.3: localizing a cyclic submodule away from `f` gives the cyclic
submodule generated by the localized image of the generator. -/
private theorem away_span_singleton_eq (m : M) :
    (R ∙ m).localized (.powers f) = (Rloc) ∙ LocalizedModule.mkLinearMap (.powers f) M m := by
  -- Identify the localized span with the span of the image of its single generator.
  simpa [Submodule.localized, Set.image_singleton] using
    (Submodule.localized'_span (Localization.Away f) (.powers f)
      (LocalizedModule.mkLinearMap (.powers f) M) ({m} : Set M))

/-- Helper for Lemma 10.67.3: the support of a cyclic submodule generated by `m` commutes with
away localization along `Spec(R_f) → Spec(R)`. -/
private theorem cyclic_support_away_preimage_comap (m : M) :
    Module.support Rloc ((Rloc) ∙ LocalizedModule.mkLinearMap (.powers f) M m) =
      PrimeSpectrum.comap (algebraMap R Rloc) ⁻¹' Module.support R (R ∙ m) := by
  -- Rewrite the localized cyclic submodule as the localized module of `R ∙ m`.
  calc
    Module.support Rloc ((Rloc) ∙ LocalizedModule.mkLinearMap (.powers f) M m) =
        Module.support Rloc ↥((R ∙ m).localized (.powers f)) := by
          rw [away_span_singleton_eq (R := R) (M := M) (f := f) m]
    _ = Module.support Rloc (LocalizedModule.Away f ↥(R ∙ m)) := by
          -- `Submodule.localizedEquiv` removes the ambient-submodule presentation.
          simpa using
            (LinearEquiv.support_eq (R := Rloc)
              (Submodule.localizedEquiv (.powers f) (R ∙ m)))
    _ = Module.support Rloc (Rloc ⊗[R] ↥(R ∙ m)) := by
          -- Rewrite the localized module as the tensor-product base change used by Lemma 10.40.6.
          simpa using
            (LinearEquiv.support_eq (R := Rloc)
              (LocalizedModule.equivTensorProduct (.powers f) ↥(R ∙ m)))
    _ = PrimeSpectrum.comap (algebraMap R Rloc) ⁻¹' Module.support R (R ∙ m) := by
          -- The cyclic module is finite, so the standard support/base-change theorem applies.
          simpa using
            (Module.Lemma_10_40_6 (R := R) (R' := Rloc) (M := ↥(R ∙ m)))

/-- Helper for Lemma 10.67.3: if an associated prime of `M` avoids the powers of `f`, then its
extension to `R_f` is associated to `M_f`. -/
private theorem associatedPrimesOfModule_away_map_of_disjoint {p : Ideal R}
    (hp : p ∈ associatedPrimesOfModule R M)
    (hp_disj : Disjoint ((.powers f : Submonoid R) : Set R) (p : Set R)) :
    Ideal.map (algebraMap R Rloc) p ∈ associatedPrimesOfModule Rloc Mloc := by
  -- First view `p` as an associated prime of `M_f` over the original ring `R`.
  have hp_range : p ∈ Set.range (Ideal.comap (algebraMap R Rloc)) := by
    refine ⟨Ideal.map (algebraMap R Rloc) p, ?_⟩
    exact IsLocalization.comap_map_of_isPrime_disjoint (.powers f) Rloc hp.1 hp_disj
  have hp_localized_over_R : p ∈ associatedPrimesOfModule R Mloc :=
    associatedPrimesOfModule_inter_localization_range_subset
      (R := R) (S := .powers f) (M := M) ⟨hp, hp_range⟩
  -- Then use injectivity of `Spec(R_f) → Spec(R)` to identify the unique prime above `p`.
  rw [← associatedPrimesOfModule_localizedModule_eq_image_comap
    (R := R) (S := .powers f) (M := M)] at hp_localized_over_R
  rcases hp_localized_over_R with ⟨J, hJ, hJcomap⟩
  let qJ : PrimeSpectrum Rloc := ⟨J, hJ.1⟩
  let qp : PrimeSpectrum Rloc := ⟨Ideal.map (algebraMap R Rloc) p,
    IsLocalization.isPrime_of_isPrime_disjoint (.powers f) Rloc p hp.1 hp_disj⟩
  have hq_comap :
      PrimeSpectrum.comap (algebraMap R Rloc) qJ =
        PrimeSpectrum.comap (algebraMap R Rloc) qp := by
    ext1
    exact hJcomap.trans
      (IsLocalization.comap_map_of_isPrime_disjoint (.powers f) Rloc hp.1 hp_disj).symm
  have hq_eq : qJ = qp :=
    (PrimeSpectrum.localization_comap_injective (S := Rloc) (.powers f)) hq_comap
  have hJ_eq : J = Ideal.map (algebraMap R Rloc) p := by
    simpa [qJ, qp] using congrArg PrimeSpectrum.asIdeal hq_eq
  simpa [hJ_eq] using hJ

/-- Helper for Lemma 10.67.3: an embedded associated prime of `M` that survives away from `f`
remains embedded after localizing away from `f`. -/
private theorem embeddedAssociatedPrimes_away_map_of_disjoint {p : Ideal R}
    (hp : p ∈ embeddedAssociatedPrimes R M)
    (hp_disj : Disjoint ((.powers f : Submonoid R) : Set R) (p : Set R)) :
    Ideal.map (algebraMap R Rloc) p ∈ embeddedAssociatedPrimes Rloc Mloc := by
  rw [mem_embeddedAssociatedPrimes_iff] at hp ⊢
  refine ⟨associatedPrimesOfModule_away_map_of_disjoint
    (R := R) (M := M) (f := f) hp.1 hp_disj, ?_⟩
  -- Minimality descends because every smaller associated prime of `p` also avoids `f`.
  intro hmin
  apply hp.2
  refine ⟨hp.1, ?_⟩
  intro p' hp' hp'le
  have hp'_disj : Disjoint ((.powers f : Submonoid R) : Set R) (p' : Set R) := by
    rw [Set.disjoint_left] at hp_disj ⊢
    intro x hxS hxp'
    exact hp_disj hxS (hp'le hxp')
  have hp'_map_assoc :
      Ideal.map (algebraMap R Rloc) p' ∈ associatedPrimesOfModule Rloc Mloc :=
    associatedPrimesOfModule_away_map_of_disjoint
      (R := R) (M := M) (f := f) hp' hp'_disj
  have hp_map_le :
      Ideal.map (algebraMap R Rloc) p ≤ Ideal.map (algebraMap R Rloc) p' :=
    hmin.2 hp'_map_assoc (Ideal.map_mono hp'le)
  simpa [IsLocalization.comap_map_of_isPrime_disjoint (.powers f) Rloc hp'.1 hp'_disj] using
    (Ideal.map_le_iff_le_comap.mp hp_map_le)

/-- Helper for Lemma 10.67.3: the embedded-prime locus of `M` pulls back into the embedded-prime
locus of `M_f`. -/
private theorem embedded_locus_away_preimage_comap_subset :
    PrimeSpectrum.comap (algebraMap R Rloc) ⁻¹'
      (⋃ p ∈ embeddedAssociatedPrimes R M, PrimeSpectrum.zeroLocus p) ⊆
        ⋃ p ∈ embeddedAssociatedPrimes Rloc Mloc, PrimeSpectrum.zeroLocus p := by
  intro q hq
  change PrimeSpectrum.comap (algebraMap R Rloc) q ∈
    ⋃ p ∈ embeddedAssociatedPrimes R M, PrimeSpectrum.zeroLocus p at hq
  rcases Set.mem_iUnion.mp hq with ⟨p, hp⟩
  rcases Set.mem_iUnion.mp hp with ⟨hp_emb, hp_zero⟩
  have hp_le : p ≤ Ideal.comap (algebraMap R Rloc) q.asIdeal :=
    (PrimeSpectrum.mem_zeroLocus _ _).mp hp_zero
  have hq_disj :
      Disjoint ((.powers f : Submonoid R) : Set R)
        (Ideal.comap (algebraMap R Rloc) q.asIdeal : Set R) := by
    exact (IsLocalization.disjoint_comap_iff (.powers f) Rloc q.asIdeal).2 q.2.ne_top
  have hp_disj : Disjoint ((.powers f : Submonoid R) : Set R) (p : Set R) := by
    rw [Set.disjoint_left] at hq_disj ⊢
    intro x hxS hxp
    exact hq_disj hxS (hp_le hxp)
  refine Set.mem_iUnion.2 ⟨Ideal.map (algebraMap R Rloc) p, Set.mem_iUnion.2 ⟨?_, ?_⟩⟩
  · exact embeddedAssociatedPrimes_away_map_of_disjoint
      (R := R) (M := M) (f := f) hp_emb hp_disj
  · exact (PrimeSpectrum.mem_zeroLocus q _).2 <| by
      exact Ideal.map_le_iff_le_comap.mpr hp_le

/-- Helper for Lemma 10.67.3: the localized canonical submodule is contained in the canonical
submodule of the localized module. -/
private theorem embeddedPrimeFreeSubmodule_localized_le :
    (embeddedPrimeFreeSubmodule R M).localized (.powers f) ≤
      embeddedPrimeFreeSubmodule Rloc Mloc := by
  -- It is enough to check the generators of the localized span.
  rw [Submodule.localized, Submodule.localized'_eq_span]
  refine Submodule.span_le.2 ?_
  rintro _ ⟨m, hm, rfl⟩
  -- The cyclic support localizes by preimage, and the embedded locus only grows after
  -- localization along `R → R_f`.
  exact (mem_embeddedPrimeFreeSubmodule_iff
    (R := Rloc) (M := Mloc) (LocalizedModule.mkLinearMap (.powers f) M m)).2 <|
      (cyclic_support_away_preimage_comap (R := R) (M := M) (f := f) m).symm ▸
        (Set.preimage_mono ((mem_embeddedPrimeFreeSubmodule_iff
          (R := R) (M := M) m).mp hm)).trans
          (embedded_locus_away_preimage_comap_subset (R := R) (M := M) (f := f))

/-- Helper for Lemma 10.67.3: an embedded associated prime of an away localization descends to an
embedded associated prime before localizing. -/
private theorem embeddedAssociatedPrimes_away_comap_of_mem
    [IsNoetherianRing R] {N : Type v} [AddCommGroup N] [Module R N] [Module.Finite R N]
    {q : Ideal Rloc} (hq : q ∈ embeddedAssociatedPrimes Rloc (LocalizedModule.Away f N)) :
    Ideal.comap (algebraMap R Rloc) q ∈ embeddedAssociatedPrimes R N := by
  -- First contract the associated prime from the localized module back to `R`.
  rw [mem_embeddedAssociatedPrimes_iff] at hq ⊢
  let p : Ideal R := Ideal.comap (algebraMap R Rloc) q
  have hp_assoc_localized :
      p ∈ associatedPrimesOfModule R (LocalizedModule.Away f N) := by
    rw [← associatedPrimesOfModule_localizedModule_eq_image_comap
      (R := R) (S := .powers f) (M := N)]
    exact ⟨q, hq.1, rfl⟩
  have hp_assoc :
      p ∈ associatedPrimesOfModule R N := by
    rw [← associatedPrimesOfModule_inter_localization_range_eq
      (R := R) (S := .powers f) (M := N)] at hp_assoc_localized
    exact hp_assoc_localized.1
  refine ⟨hp_assoc, ?_⟩
  -- Route correction: instead of rebuilding the localized quotient contradiction here, reflect
  -- minimality along the injective map `Spec(R_f) → Spec(R)`.
  intro hp_min
  apply hq.2
  refine ⟨hq.1, ?_⟩
  intro q' hq' hq'le
  let p' : Ideal R := Ideal.comap (algebraMap R Rloc) q'
  have hp'_assoc_localized :
      p' ∈ associatedPrimesOfModule R (LocalizedModule.Away f N) := by
    rw [← associatedPrimesOfModule_localizedModule_eq_image_comap
      (R := R) (S := .powers f) (M := N)]
    exact ⟨q', hq', rfl⟩
  have hp'_assoc :
      p' ∈ associatedPrimesOfModule R N := by
    rw [← associatedPrimesOfModule_inter_localization_range_eq
      (R := R) (S := .powers f) (M := N)] at hp'_assoc_localized
    exact hp'_assoc_localized.1
  have hp_le : p ≤ p' :=
    hp_min.2 hp'_assoc (Ideal.comap_mono hq'le)
  let qPoint : PrimeSpectrum Rloc := ⟨q, hq.1.1⟩
  let qPoint' : PrimeSpectrum Rloc := ⟨q', hq'.1⟩
  have hcomap_eq :
      PrimeSpectrum.comap (algebraMap R Rloc) qPoint =
        PrimeSpectrum.comap (algebraMap R Rloc) qPoint' := by
    ext1
    exact le_antisymm hp_le (Ideal.comap_mono hq'le)
  have hq_eq : qPoint = qPoint' :=
    (PrimeSpectrum.localization_comap_injective (S := Rloc) (.powers f)) hcomap_eq
  simpa [qPoint, qPoint'] using (congrArg PrimeSpectrum.asIdeal hq_eq).le

/-- Helper for Lemma 10.67.3: localizing the quotient by the canonical submodule introduces no
embedded associated primes. -/
private theorem localized_embeddedPrimeFree_quotient_has_no_embedded
    [IsNoetherianRing R] [Module.Finite R M] :
    embeddedAssociatedPrimes Rloc
      (LocalizedModule.Away f (M ⧸ embeddedPrimeFreeSubmodule R M)) = ∅ := by
  -- Descend any hypothetical localized embedded prime to the quotient before localization.
  ext q
  constructor
  · intro hq
    have hp :
        Ideal.comap (algebraMap R Rloc) q ∈
          embeddedAssociatedPrimes R (M ⧸ embeddedPrimeFreeSubmodule R M) :=
      embeddedAssociatedPrimes_away_comap_of_mem (R := R) (f := f)
        (N := M ⧸ embeddedPrimeFreeSubmodule R M) hq
    simpa [embeddedAssociatedPrimes_quotient_embeddedPrimeFreeSubmodule (R := R) (M := M)] using hp
  · intro hq
    exact hq.elim

/-- Helper for Lemma 10.67.3: the localized quotient by the canonical submodule has the same
support as the localized ambient module. -/
private theorem localized_embeddedPrimeFree_quotient_support_eq
    [IsNoetherianRing R] [Module.Finite R M] :
    Module.support Rloc
        (LocalizedModule.Away f (M ⧸ embeddedPrimeFreeSubmodule R M)) =
      Module.support Rloc Mloc := by
  -- Rewrite both localized modules as the tensor-product base change from Lemma 10.40.6.
  calc
    Module.support Rloc
        (LocalizedModule.Away f (M ⧸ embeddedPrimeFreeSubmodule R M)) =
        Module.support Rloc
          (Rloc ⊗[R] (M ⧸ embeddedPrimeFreeSubmodule R M)) := by
            simpa using
              (LinearEquiv.support_eq (R := Rloc)
                (LocalizedModule.equivTensorProduct (.powers f)
                  (M ⧸ embeddedPrimeFreeSubmodule R M)))
    _ = PrimeSpectrum.comap (algebraMap R Rloc) ⁻¹'
          Module.support R (M ⧸ embeddedPrimeFreeSubmodule R M) := by
            simpa using
              (Module.Lemma_10_40_6
                (R := R) (R' := Rloc) (M := M ⧸ embeddedPrimeFreeSubmodule R M))
    _ = PrimeSpectrum.comap (algebraMap R Rloc) ⁻¹' Module.support R M := by
          rw [support_quotient_embeddedPrimeFreeSubmodule (R := R) (M := M)]
    _ = Module.support Rloc (Rloc ⊗[R] M) := by
          simpa using
            (Module.Lemma_10_40_6 (R := R) (R' := Rloc) (M := M)).symm
    _ = Module.support Rloc Mloc := by
          simpa using
            (LinearEquiv.support_eq (R := Rloc)
              (LocalizedModule.equivTensorProduct (.powers f) M)).symm

/-- Helper for Lemma 10.67.3: the cyclic support of the image of an element under a linear map is
contained in the cyclic support of the original element. -/
private theorem support_cyclic_image_subset
    {P : Type*} [AddCommGroup P] [Module Rloc P]
    (g : Mloc →ₗ[Rloc] P) (x : Mloc) :
    Module.support Rloc (Rloc ∙ g x) ⊆ Module.support Rloc (Rloc ∙ x) := by
  -- Restrict `g` to the cyclic submodule generated by `x` and use support monotonicity for the
  -- induced surjection onto its range.
  let gSpan : (Rloc ∙ x) →ₗ[Rloc] P := g.domRestrict (Rloc ∙ x)
  let gRange : (Rloc ∙ x) →ₗ[Rloc] LinearMap.range gSpan := gSpan.rangeRestrict
  have hg_surj : Function.Surjective gRange := LinearMap.surjective_rangeRestrict gSpan
  have hsupp :
      Module.support Rloc (LinearMap.range gSpan) ⊆ Module.support Rloc (Rloc ∙ x) :=
    Module.support_subset_of_surjective gRange hg_surj
  have hrange : LinearMap.range gSpan = (Rloc ∙ g x) := by
    calc
      LinearMap.range gSpan = (Rloc ∙ x).map g := by
        simp [gSpan]
      _ = (Rloc ∙ g x) := by
        simpa [Set.image_singleton] using (Submodule.map_span g ({x} : Set Mloc))
  calc
    Module.support Rloc (Rloc ∙ g x) = Module.support Rloc ↥(LinearMap.range gSpan) := by
      rw [hrange]
    _ ⊆ Module.support Rloc (Rloc ∙ x) := hsupp

/-- Helper for Lemma 10.67.3: a canonical localized element maps to zero in the localized quotient
by the canonical submodule from Lemma 10.67.2. -/
private theorem localized_quotient_map_eq_zero_of_mem_embeddedPrimeFreeSubmodule
    [IsNoetherianRing R] [Module.Finite R M] {x : Mloc}
    (hx : x ∈ embeddedPrimeFreeSubmodule Rloc Mloc) :
    LocalizedModule.map (.powers f) (embeddedPrimeFreeSubmodule R M).mkQ x = 0 := by
  let K : Submodule R M := embeddedPrimeFreeSubmodule R M
  let Q : Type v := M ⧸ K
  let π : Mloc →ₗ[Rloc] LocalizedModule.Away f Q := LocalizedModule.map (.powers f) K.mkQ
  let y : LocalizedModule.Away f Q := π x
  -- If the image were nonzero, a minimal associated prime of its cyclic span would become an
  -- embedded associated prime of the localized quotient, contradicting the previous helper.
  by_contra hy
  have hy_ne : y ≠ 0 := hy
  let Ny : Submodule Rloc (LocalizedModule.Away f Q) := Rloc ∙ y
  have hNy_ne_bot : Ny ≠ ⊥ := by
    simpa [Ny, Submodule.span_singleton_eq_bot] using hy_ne
  letI : Nontrivial ↥Ny := Submodule.nontrivial_iff_ne_bot.mpr hNy_ne_bot
  obtain ⟨p, hp_assocNy⟩ := associatedPrimes.nonempty Rloc ↥Ny
  have hp_assocQ :
      p ∈ associatedPrimes Rloc (LocalizedModule.Away f Q) :=
    associatedPrimes.subset_of_injective Ny.subtype_injective hp_assocNy
  let pPoint : PrimeSpectrum Rloc := ⟨p, (AssociatedPrimes.mem_iff.mp hp_assocNy).isPrime⟩
  have hp_supportNy : pPoint ∈ Module.support Rloc ↥Ny := by
    exact Module.associatedPrimes_subset_support (by simpa [pPoint] using hp_assocNy)
  have hp_supportY : pPoint ∈ Module.support Rloc (Rloc ∙ π x) := by
    simpa [Ny, y, π] using hp_supportNy
  have hp_supportMx : pPoint ∈ Module.support Rloc (Rloc ∙ x) :=
    (support_cyclic_image_subset (R := R) (M := M) (f := f)
      (P := LocalizedModule.Away f Q) π x) hp_supportY
  have hx_support_subset :
      Module.support Rloc (Rloc ∙ x) ⊆
        ⋃ q ∈ embeddedAssociatedPrimes Rloc Mloc, PrimeSpectrum.zeroLocus q :=
    (mem_embeddedPrimeFreeSubmodule_iff (R := Rloc) (M := Mloc) x).mp hx
  have hp_embedded_locus :
      pPoint ∈ ⋃ q ∈ embeddedAssociatedPrimes Rloc Mloc, PrimeSpectrum.zeroLocus q :=
    hx_support_subset hp_supportMx
  rcases Set.mem_iUnion.1 hp_embedded_locus with ⟨q, hq⟩
  rcases Set.mem_iUnion.1 hq with ⟨hq_emb, hp_zero⟩
  let qPoint : PrimeSpectrum Rloc := ⟨q, hq_emb.1.1⟩
  have hq_le_p : q ≤ p := (PrimeSpectrum.mem_zeroLocus pPoint q).mp hp_zero
  have hp_embeddedQ :
      p ∈ embeddedAssociatedPrimes Rloc (LocalizedModule.Away f Q) := by
    rw [mem_embeddedAssociatedPrimes_iff_mem_associatedPrimes]
    refine ⟨hp_assocQ, ?_⟩
    intro hp_min
    have hsupport_eq :
        Module.support Rloc (LocalizedModule.Away f Q) = Module.support Rloc Mloc := by
      simpa [K, Q] using
        localized_embeddedPrimeFree_quotient_support_eq (R := R) (M := M) (f := f)
    have hp_min_supportQ :
        Minimal (· ∈ Module.support Rloc (LocalizedModule.Away f Q)) pPoint :=
      (minimal_support_iff_minimal_associatedPrimes
        (R := Rloc) (M := LocalizedModule.Away f Q) pPoint).2 hp_min
    have hp_min_supportM :
        Minimal (· ∈ Module.support Rloc Mloc) pPoint := by
      simpa [hsupport_eq] using hp_min_supportQ
    have hq_emb_assoc :
        q ∈ associatedPrimes Rloc Mloc ∧
          ¬ Minimal (· ∈ associatedPrimes Rloc Mloc) q := by
      exact
        (mem_embeddedAssociatedPrimes_iff_mem_associatedPrimes
          (R := Rloc) (M := Mloc) q).mp hq_emb
    have hq_supportM : qPoint ∈ Module.support Rloc Mloc := by
      exact Module.associatedPrimes_subset_support (by simpa [qPoint] using hq_emb_assoc.1)
    have hp_le_q : p ≤ q := hp_min_supportM.2 hq_supportM hq_le_p
    have hp_eq_q : p = q := le_antisymm hp_le_q hq_le_p
    have hp_min_assocM :
        Minimal (· ∈ associatedPrimes Rloc Mloc) p :=
      (minimal_support_iff_minimal_associatedPrimes (R := Rloc) (M := Mloc) pPoint).mp
        hp_min_supportM
    exact hq_emb_assoc.2 (by simpa [hp_eq_q] using hp_min_assocM)
  have hno_embedded :
      embeddedAssociatedPrimes Rloc (LocalizedModule.Away f Q) = ∅ :=
    localized_embeddedPrimeFree_quotient_has_no_embedded (R := R) (M := M) (f := f)
  simpa [Q, hno_embedded] using hp_embeddedQ

/-- Supporting bridge: the canonical submodule from Lemma 10.67.2 is compatible with away
localization. -/
theorem embeddedPrimeFreeSubmodule_localized_eq
    [IsNoetherianRing R] [Module.Finite R M] :
    (embeddedPrimeFreeSubmodule R M).localized (.powers f) =
      embeddedPrimeFreeSubmodule Rloc Mloc := by
  -- Route correction: the forward inclusion only needs the one-sided localization theorem for
  -- textbook associated primes, so we record that verified prefix explicitly.
  have hle :
      (embeddedPrimeFreeSubmodule R M).localized (.powers f) ≤
        embeddedPrimeFreeSubmodule Rloc Mloc :=
    embeddedPrimeFreeSubmodule_localized_le (R := R) (M := M) (f := f)
  apply le_antisymm hle
  intro x hx
  let K : Submodule R M := embeddedPrimeFreeSubmodule R M
  let Q : Type v := M ⧸ K
  let π : Mloc →ₗ[Rloc] LocalizedModule.Away f Q := LocalizedModule.map (.powers f) K.mkQ
  -- The reverse inclusion is a kernel computation once the localized quotient image is known to
  -- vanish on the canonical localized submodule.
  have hx_zero : π x = 0 :=
    localized_quotient_map_eq_zero_of_mem_embeddedPrimeFreeSubmodule
      (R := R) (M := M) (f := f) hx
  have hx_ker : x ∈ LinearMap.ker π := by
    simpa [π, LinearMap.mem_ker] using hx_zero
  have hker :
      K.localized (.powers f) = LinearMap.ker π := by
    simpa [K, Q, π] using
      (LinearMap.localized'_ker_eq_ker_localizedMap (S := Localization (.powers f))
        (p := .powers f)
        (f := LocalizedModule.mkLinearMap (.powers f) M)
        (f' := LocalizedModule.mkLinearMap (.powers f) Q) K.mkQ)
  rw [← hker] at hx_ker
  simpa [K] using hx_ker

/-- Lemma 10.67.3: after inverting `f`, the quotient by the canonical submodule from
Lemma 10.67.2 agrees with the canonical quotient of the localized module. -/
@[stacks 02M7]
noncomputable def away_embeddedPrimeFreeQuotientEquiv
    [IsNoetherianRing R] [Module.Finite R M] :
    LocalizedModule.Away f (M ⧸ embeddedPrimeFreeSubmodule R M) ≃ₗ[Localization.Away f]
      Mloc ⧸ embeddedPrimeFreeSubmodule Rloc Mloc :=
  (localizedQuotientEquiv (.powers f) (embeddedPrimeFreeSubmodule R M)).symm ≪≫ₗ
    Submodule.quotEquivOfEq _ _ (embeddedPrimeFreeSubmodule_localized_eq R M f)

-- Proof sketch: unfold `away_embeddedPrimeFreeQuotientEquiv`; the statement is exactly its
-- defining composition of the canonical localized quotient equivalence with the quotient rewrite
-- coming from `embeddedPrimeFreeSubmodule_localized_eq`.
/-- The equivalence in Lemma 10.67.3 is defined by composing the canonical localization-of-quotient
equivalence with the quotient rewrite induced by
`embeddedPrimeFreeSubmodule_localized_eq`. -/
theorem away_embeddedPrimeFreeQuotientEquiv_def
    [IsNoetherianRing R] [Module.Finite R M] :
    away_embeddedPrimeFreeQuotientEquiv R M f =
      (localizedQuotientEquiv (.powers f) (embeddedPrimeFreeSubmodule R M)).symm ≪≫ₗ
        Submodule.quotEquivOfEq _ _ (embeddedPrimeFreeSubmodule_localized_eq R M f) :=
  rfl

end
