import Mathlib
import StacksProject_2024.Chap10.Definition_10_70_1
import StacksProject_2024.Chap10.Lemma_10_70_2

-- Declarations for this item will be appended below by the statement pipeline.

universe u

noncomputable section

open MvPolynomial
open scoped AffineBlowupChart nonZeroDivisors

/-
Domain-style sampling pass for Lemma 10.70.6.

Primary domain: commutative algebra of affine blowup charts and polynomial presentations.

Sampled owner declarations:
* `affineBlowupChart` and its notation `R[I / a]` from `Definition_10_70_1.lean`;
* `affineBlowupChartBasicFraction` from `Definition_10_70_1.lean`;
* `tensorToAffineBlowupAlgebra` and
  `affineBlowupChart_baseChange_surjective_and_ker_eq_primaryComponent` from
  `Lemma_10_70_3.lean`;
* `MvPolynomial.aeval` and `Ideal.Quotient.liftₐ` from mathlib's polynomial-quotient API.

Owner abstraction: the canonical quotient-to-chart map
`affineBlowupTuplePresentationMap f :
    let I : Ideal R := Ideal.span (Set.range f)
    let a : I := tupleSpanFirst f
    affineBlowupTuplePresentationQuotient f →ₐ[R] R[I / a]`.

Primitive data are the tuple-generated ideal, its distinguished first generator, the relations
`a₁ X i - aᵢ₊₁`, and the quotient presentation. The map to the affine blowup chart and the kernel
descriptions are derived API.

Source/core/bridge triage:
* source-facing: the canonical quotient presentation map and its `a₁`-power torsion kernel;
* core/canonical: the same kernel as a primary component;
* bridge/view: the polynomial evaluation map before passing to the quotient.
-/

section

variable {R : Type u} [CommRing R]
variable {r : ℕ} (f : Fin (r + 1) → R)

/-- Helper for Chap10 Lemma 10 70 6: every tuple entry belongs to the ideal spanned by the
tuple. -/
private theorem tupleMemSpanRange (j : Fin (r + 1)) :
    f j ∈ Ideal.span (Set.range f) := by
  -- Each tuple entry is one of the spanning generators.
  exact Ideal.subset_span ⟨j, rfl⟩

/-- The first tuple entry viewed as an element of the ideal `Ideal.span (Set.range f)`. -/
def tupleSpanFirst : Ideal.span (Set.range f) :=
  ⟨f 0, tupleMemSpanRange f 0⟩

/-- The relation `a₁ xᵢ - aᵢ₊₁` in the polynomial presentation over `R`. -/
def affineBlowupTuplePresentationRelation (i : Fin r) :
    MvPolynomial (Fin r) R :=
  C (f 0) * X i - C (f i.succ)

/-- The ideal generated by the relations `a₁ xᵢ - aᵢ₊₁` for `i = 1, …, r`. -/
def affineBlowupTuplePresentationRelationIdeal :
    Ideal (MvPolynomial (Fin r) R) :=
  Ideal.span (Set.range fun i : Fin r ↦ affineBlowupTuplePresentationRelation f i)

/-- The quotient presentation
`R[x₂, …, xᵣ₊₁] / (a₁ x₂ - a₂, …, a₁ xᵣ₊₁ - aᵣ₊₁)`. -/
abbrev affineBlowupTuplePresentationQuotient :=
  MvPolynomial (Fin r) R ⧸ affineBlowupTuplePresentationRelationIdeal f

private instance instModuleAffineBlowupTuplePresentationQuotient :
    Module (affineBlowupTuplePresentationQuotient f)
      (affineBlowupTuplePresentationQuotient f) :=
  Semiring.toModule

section

local notation "I" => Ideal.span (Set.range f)
local notation "a" => tupleSpanFirst f
local notation "Q" => affineBlowupTuplePresentationQuotient f
local notation "Chart" => R[I / a]

/-- The canonical generator `xᵢ ↦ aᵢ₊₁ / a₁` in the tuple presentation of the affine blowup
chart. -/
private def affineBlowupTuplePresentationGenerator (i : Fin r) : Chart :=
  affineBlowupChartBasicFraction I a
    ⟨f i.succ, tupleMemSpanRange f i.succ⟩

/-- The polynomial map sending each presentation variable to the corresponding fraction
`aᵢ₊₁ / a₁` in the affine blowup chart. -/
private def affineBlowupTuplePresentationToBlowup :
    MvPolynomial (Fin r) R →ₐ[R] Chart :=
  MvPolynomial.aeval (affineBlowupTuplePresentationGenerator f)

/-- Helper for Chap10 Lemma 10 70 6: the first tuple entry is a valid denominator in the ordinary
away-localization at `f 0`. -/
private theorem tupleFirst_mem_powers : f 0 ∈ Submonoid.powers (f 0) := by
  -- The first power of `f 0` is the chosen denominator.
  exact ⟨1, by simp⟩

/-- Helper for Chap10 Lemma 10 70 6: ordinary localization evaluation sending each presentation
variable to `f i.succ / f 0`. -/
private def tupleLocalizationEval :
    MvPolynomial (Fin r) R →ₐ[R] Localization.Away (f 0) :=
  MvPolynomial.aeval fun i ↦ Localization.mk (f i.succ) ⟨f 0, tupleFirst_mem_powers f⟩

/-- Helper for Chap10 Lemma 10 70 6: the canonical chart comparison
`R[J/b] → R_b` is injective. -/
private theorem affineBlowupChartToLocalizationAway_injective_for_tuple
    (J : Ideal R) (b : J) :
    Function.Injective (affineBlowupChartToLocalizationAway J b) := by
  let A := R[J / b]
  let bA : A := algebraMap R A b.1
  have hM : Submonoid.powers bA ≤ nonZeroDivisors A := by
    intro x hx
    rcases hx with ⟨n, rfl⟩
    rw [mem_nonZeroDivisors_iff_right]
    intro y hy
    -- Lemma 10.70.2 makes the chart parameter regular, so every power is regular.
    exact (IsRegular.pow n (affineBlowupChart_isRegular J b)).right
      (by simpa [A, bA] using hy)
  letI : IsLocalization.Away bA (Localization.Away b.1) := by
    -- The public localization instance is stated for the image of `b` in the chart.
    simpa [A, bA] using affineBlowupChart_isLocalizationAway J b
  exact IsLocalization.injective (Localization.Away b.1) hM

/-- Helper for Chap10 Lemma 10 70 6: the chart comparison sends a basic fraction `x / b`
to the ordinary localization fraction `x / b`. -/
private theorem affineBlowupChartToLocalizationAway_basicFraction_for_tuple
    (J : Ideal R) (b x : J) :
    affineBlowupChartToLocalizationAway J b (affineBlowupChartBasicFraction J b x) =
      Localization.mk x.1 ⟨b.1, by exact ⟨1, by simp⟩⟩ := by
  let g : reesAlgebra J →+* Localization.Away b.1 :=
    (Polynomial.eval₂RingHom (algebraMap R (Localization.Away b.1)) 1).comp
      (reesAlgebra J).toSubring.subtype
  have hfrac (r : R) :
      algebraMap R (Localization.Away b.1) r *
          Localization.mk 1 ⟨b.1, by exact ⟨1, by simp⟩⟩ =
        Localization.mk r ⟨b.1, by exact ⟨1, by simp⟩⟩ := by
    -- Multiplying by the standard inverse `1 / b` gives the ordinary fraction `r / b`.
    rw [← Algebra.smul_def, Localization.mk_eq_mk'_apply, IsLocalization.smul_mk'_one]
    exact (Localization.mk_eq_mk'_apply r ⟨b.1, by exact ⟨1, by simp⟩⟩).symm
  -- Evaluate the homogeneous-localization fraction through the away-localization lift.
  rw [affineBlowupChartToLocalizationAway, RingHom.comp_apply,
    HomogeneousLocalization.algebraMap_apply]
  simp [affineBlowupChartBasicFraction]
  have h :=
    Localization.awayLift_mk g (reesAlgebraDegreeOne J b) (reesAlgebraDegreeOne J x)
      (Localization.mk 1 ⟨b.1, by exact ⟨1, by simp⟩⟩)
      (by
        rw [show g (reesAlgebraDegreeOne J b) =
            algebraMap R (Localization.Away b.1) b.1 by
          simp [g, reesAlgebraDegreeOne]]
        rw [hfrac]
        exact Localization.mk_self ⟨b.1, by exact ⟨1, by simp⟩⟩)
      1
  simpa [g, reesAlgebraDegreeOne, pow_one, hfrac] using h

/-- Helper for Chap10 Lemma 10 70 6: in the affine blowup chart, `(x / b) * b = x`. -/
private theorem affineBlowupChartBasicFraction_mul_parameter_for_tuple
    (J : Ideal R) (b x : J) :
    affineBlowupChartBasicFraction J b x * algebraMap R R[J / b] b.1 =
      algebraMap R R[J / b] x.1 := by
  apply affineBlowupChartToLocalizationAway_injective_for_tuple J b
  -- After applying the injective comparison map, this is ordinary localization cancellation.
  rw [map_mul, affineBlowupChartToLocalizationAway_basicFraction_for_tuple,
    affineBlowupChartToLocalizationAway_algebraMap,
    affineBlowupChartToLocalizationAway_algebraMap, Localization.mk_eq_mk'_apply,
    ← IsLocalization.mk'_one (M := Submonoid.powers b.1) (S := Localization.Away b.1) b.1,
    ← IsLocalization.mk'_mul (M := Submonoid.powers b.1) (S := Localization.Away b.1)]
  simpa using
    (IsLocalization.mk'_mul_cancel_right (M := Submonoid.powers b.1)
      (S := Localization.Away b.1) x.1 ⟨b.1, ⟨1, by simp⟩⟩)

/-- Helper for Chap10 Lemma 10 70 6: chart evaluation followed by the comparison to `R_{f 0}`
is the ordinary tuple localization evaluation. -/
private theorem affineBlowupTuplePresentationToAway_eq_tupleLocalizationEval
    (p : MvPolynomial (Fin r) R) :
    affineBlowupChartToLocalizationAway I a (affineBlowupTuplePresentationToBlowup f p) =
      tupleLocalizationEval f p := by
  -- Induct on the polynomial so the bridge only uses the scalar and variable computations.
  induction p using MvPolynomial.induction_on with
  | C r =>
      have hC :
          affineBlowupTuplePresentationToBlowup f (C r) =
            algebraMap R Chart r := by
        -- Constants evaluate to the corresponding scalar in the chart.
        simp [affineBlowupTuplePresentationToBlowup]
      rw [hC]
      simpa [tupleLocalizationEval, tupleSpanFirst] using
        affineBlowupChartToLocalizationAway_algebraMap I a r
  | add p q hp hq =>
      simpa [map_add] using congrArg₂ (fun x y ↦ x + y) hp hq
  | mul_X p i hp =>
      have hbasic :=
        affineBlowupChartToLocalizationAway_basicFraction_for_tuple I a
          ⟨f i.succ, Ideal.subset_span ⟨i.succ, rfl⟩⟩
      have hvar :
          affineBlowupChartToLocalizationAway I a
              (affineBlowupTuplePresentationGenerator f i) =
            Localization.mk (f i.succ) ⟨f 0, tupleFirst_mem_powers f⟩ := by
        -- Variables compare by the basic-fraction computation.
        simpa [affineBlowupTuplePresentationGenerator, tupleSpanFirst] using hbasic
      simpa [map_mul, affineBlowupTuplePresentationToBlowup, tupleLocalizationEval] using
        congrArg₂ (fun x y ↦ x * y) hp hvar

/-- Helper for Chap10 Lemma 10 70 6: in the ordinary localization, multiplying
`f i.succ / f 0` by `f 0` recovers `f i.succ`. -/
private theorem tupleLocalizationEval_variable_relation (i : Fin r) :
    algebraMap R (Localization.Away (f 0)) (f 0) * tupleLocalizationEval f (X i) =
      algebraMap R (Localization.Away (f 0)) (f i.succ) := by
  -- This is the ordinary cancellation identity for the chosen denominator `f 0`.
  simp only [tupleLocalizationEval, aeval_X]
  rw [Localization.mk_eq_mk'_apply,
    ← IsLocalization.mk'_one (M := Submonoid.powers (f 0))
      (S := Localization.Away (f 0)) (f 0),
    ← IsLocalization.mk'_mul (M := Submonoid.powers (f 0))
      (S := Localization.Away (f 0))]
  simpa [mul_comm] using
    (IsLocalization.mk'_mul_cancel_right (M := Submonoid.powers (f 0))
      (S := Localization.Away (f 0)) (f i.succ) ⟨f 0, tupleFirst_mem_powers f⟩)

/-- Each defining relation `a₁ xᵢ - aᵢ₊₁` maps to zero in the affine blowup chart. -/
private theorem affineBlowupTuplePresentationRelation_map_eq_zero (i : Fin r) :
    affineBlowupTuplePresentationToBlowup f (affineBlowupTuplePresentationRelation f i) = 0 := by
  -- Evaluation sends the relation to `a₁ * (aᵢ₊₁ / a₁) - aᵢ₊₁`.
  simp only [affineBlowupTuplePresentationToBlowup,
    affineBlowupTuplePresentationRelation, map_sub, map_mul, aeval_C, aeval_X]
  rw [mul_comm]
  rw [affineBlowupTuplePresentationGenerator]
  have hbasic :
      affineBlowupChartBasicFraction I a
          ⟨f i.succ, Ideal.subset_span ⟨i.succ, rfl⟩⟩ *
        algebraMap R Chart (f 0) =
          algebraMap R Chart (f i.succ) := by
    -- The generic basic-fraction identity specializes to the tuple generator.
    simpa [tupleSpanFirst] using
      affineBlowupChartBasicFraction_mul_parameter_for_tuple I a
        ⟨f i.succ, Ideal.subset_span ⟨i.succ, rfl⟩⟩
  rw [hbasic]
  simp

/-- Every element of the relation ideal maps to zero in the affine blowup chart. -/
private theorem affineBlowupTuplePresentationRelationIdeal_map_eq_zero (φ : MvPolynomial (Fin r) R)
    (hφ : φ ∈ affineBlowupTuplePresentationRelationIdeal f) :
    affineBlowupTuplePresentationToBlowup f φ = 0 := by
  have hker : affineBlowupTuplePresentationRelationIdeal f ≤
      RingHom.ker
        ((affineBlowupTuplePresentationToBlowup f).toRingHom : MvPolynomial (Fin r) R →+*
          Chart) := by
    -- The span of the displayed relations lies in the kernel because each generator vanishes.
    rw [affineBlowupTuplePresentationRelationIdeal]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨i, rfl⟩
    exact affineBlowupTuplePresentationRelation_map_eq_zero f i
  exact RingHom.mem_ker.mp (hker hφ)

-- Proof sketch: Example 10.70.5 gives the polynomial presentation before base change, and
-- Lemma 10.70.3 identifies the kernel after base change with the `a₁`-power torsion ideal.
/-- Lemma 10.70.6 (Stacks tag `0G8S`): the canonical quotient presentation map
`R[x₂, …, xᵣ₊₁] / (a₁ x₂ - a₂, …, a₁ xᵣ₊₁ - aᵣ₊₁) → R[I/a₁]`. -/
@[stacks 0G8S]
def affineBlowupTuplePresentationMap : Q →ₐ[R] Chart :=
  Ideal.Quotient.liftₐ (affineBlowupTuplePresentationRelationIdeal f)
    (affineBlowupTuplePresentationToBlowup f)
    (affineBlowupTuplePresentationRelationIdeal_map_eq_zero f)

/-- Helper for Chap10 Lemma 10 70 6: the quotient presentation map sends each polynomial
variable to the corresponding basic chart fraction. -/
private theorem affineBlowupTuplePresentationMap_apply_variable (i : Fin r) :
    affineBlowupTuplePresentationMap f
        (Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (X i)) =
      affineBlowupTuplePresentationGenerator f i := by
  -- The quotient map is induced by the polynomial evaluation defining the presentation.
  simp [affineBlowupTuplePresentationMap, affineBlowupTuplePresentationToBlowup]

/-- Helper for Chap10 Lemma 10 70 6: every displayed chart generator lies in the range of the
tuple presentation map. -/
private theorem affineBlowupTuplePresentationGenerator_mem_range (i : Fin r) :
    affineBlowupTuplePresentationGenerator f i ∈
      (AlgHom.range (affineBlowupTuplePresentationMap f) : Subalgebra R Chart) := by
  -- Lift the polynomial variable class and use the variable computation.
  refine ⟨Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (X i), ?_⟩
  exact affineBlowupTuplePresentationMap_apply_variable f i

/-- Helper for Chap10 Lemma 10 70 6: generation of the affine chart by the displayed fractions
implies surjectivity of the tuple presentation map. -/
private theorem affineBlowupTuplePresentationMap_surjective_of_adjoin_generators
    (hgen : Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f)) =
      (⊤ : Subalgebra R Chart)) :
    Function.Surjective (affineBlowupTuplePresentationMap f) := by
  -- The range subalgebra contains the generators, so the assumed generated subalgebra is all of
  -- the chart and the map is surjective.
  refine (AlgHom.range_eq_top (affineBlowupTuplePresentationMap f)).mp ?_
  apply top_unique
  rw [← hgen, Algebra.adjoin_le_iff]
  rintro _ ⟨i, rfl⟩
  exact affineBlowupTuplePresentationGenerator_mem_range f i

/-- Helper for Chap10 Lemma 10 70 6: in the presentation quotient, the defining relation gives
`a₁ xᵢ = aᵢ₊₁`. -/
private theorem affineBlowupTuplePresentationQuotient_variable_relation (i : Fin r) :
    (algebraMap R Q (f 0)) *
        Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (X i) =
      algebraMap R Q (f i.succ) := by
  have hmem :
      affineBlowupTuplePresentationRelation f i ∈
        affineBlowupTuplePresentationRelationIdeal f := by
    -- Each displayed relation is one of the generators of the relation ideal.
    exact Ideal.subset_span ⟨i, rfl⟩
  have hzero :
      Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f)
          (affineBlowupTuplePresentationRelation f i) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr hmem
  have hsub :
      (algebraMap R Q (f 0)) *
          Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (X i) -
        algebraMap R Q (f i.succ) = 0 := by
    -- Rewrite the quotient image of `a₁ Xᵢ - aᵢ₊₁` into the desired subtraction.
    simpa [affineBlowupTuplePresentationRelation] using hzero
  exact sub_eq_zero.mp hsub

/-- Helper for Chap10 Lemma 10 70 6: the degree-one Rees generator attached to a tuple entry. -/
private noncomputable def tupleReesGenerator (j : Fin (r + 1)) : reesAlgebra I :=
  reesAlgebraDegreeOne I ⟨f j, tupleMemSpanRange f j⟩

/-- Helper for Chap10 Lemma 10 70 6: a tuple Rees generator has degree one. -/
private theorem tupleReesGenerator_mem_grade (j : Fin (r + 1)) :
    tupleReesGenerator f j ∈ reesAlgebraGrade I 1 := by
  -- This is the standard degree-one membership theorem for Rees generators.
  exact reesAlgebraDegreeOne_mem I ⟨f j, tupleMemSpanRange f j⟩

/-- Helper for Chap10 Lemma 10 70 6: a degree-one monomial with coefficient in the tuple ideal
belongs to the tuple Rees algebra. -/
private theorem tupleDegreeOneMonomial_mem
    (x : R) (hx : x ∈ I) :
    Polynomial.monomial 1 x ∈ reesAlgebra I := by
  -- The Rees membership condition in degree one is exactly membership in `I`.
  exact (reesAlgebra.monomial_mem).2 (by simpa [pow_one] using hx)

/-- Helper for Chap10 Lemma 10 70 6: a base-ring element gives a degree-zero Rees element. -/
private theorem tupleChartGradeZero_mem (x : R) :
    algebraMap R (reesAlgebra I) x ∈ reesAlgebraGrade I 0 := by
  -- The degree-zero piece is the range of constant Rees monomials.
  change algebraMap R (reesAlgebra I) x ∈ LinearMap.range _
  exact ⟨⟨x, by simp⟩, rfl⟩

/-- Helper for Chap10 Lemma 10 70 6: the degree-zero Rees element associated to a scalar. -/
private noncomputable def tupleChartGradeZero (x : R) : reesAlgebraGrade I 0 :=
  ⟨algebraMap R (reesAlgebra I) x, tupleChartGradeZero_mem f x⟩

/-- Helper for Chap10 Lemma 10 70 6: every degree-one Rees element of the tuple ideal lies in
the subalgebra generated by the tuple degree-one generators. -/
private theorem tupleReesDegreeOne_mem_adjoin
    (x : R) (hx : x ∈ I) (hmem : Polynomial.monomial 1 x ∈ reesAlgebra I) :
    (⟨Polynomial.monomial 1 x, hmem⟩ : reesAlgebra I) ∈
      Algebra.adjoin (reesAlgebraGrade I 0)
        (Set.range (tupleReesGenerator f) : Set (reesAlgebra I)) := by
  let A : Subalgebra (reesAlgebraGrade I 0) (reesAlgebra I) :=
    Algebra.adjoin (reesAlgebraGrade I 0)
      (Set.range (tupleReesGenerator f) : Set (reesAlgebra I))
  change (⟨Polynomial.monomial 1 x, hmem⟩ : reesAlgebra I) ∈ A
  -- Induct through the span expression for the tuple-generated ideal.
  refine Submodule.span_induction
    (p := fun y hy ↦ ∀ hmem : Polynomial.monomial 1 y ∈ reesAlgebra I,
      (⟨Polynomial.monomial 1 y, hmem⟩ : reesAlgebra I) ∈ A)
    ?_ ?_ ?_ ?_ hx hmem
  · intro y hy hmem
    rcases hy with ⟨j, rfl⟩
    change tupleReesGenerator f j ∈ A
    exact Algebra.subset_adjoin ⟨j, rfl⟩
  · intro hmem
    have hzero : (⟨Polynomial.monomial 1 0, hmem⟩ : reesAlgebra I) = 0 := by
      apply Subtype.ext
      simp
    rw [hzero]
    exact zero_mem A
  · intro x y hx hy hxmem hymem hmem
    have hx' := hxmem (tupleDegreeOneMonomial_mem f x hx)
    have hy' := hymem (tupleDegreeOneMonomial_mem f y hy)
    have hxy :
        (⟨Polynomial.monomial 1 (x + y), hmem⟩ : reesAlgebra I) =
          (⟨Polynomial.monomial 1 x, tupleDegreeOneMonomial_mem f x hx⟩ :
              reesAlgebra I) +
          (⟨Polynomial.monomial 1 y, tupleDegreeOneMonomial_mem f y hy⟩ :
              reesAlgebra I) := by
      apply Subtype.ext
      simp
    rw [hxy]
    exact add_mem hx' hy'
  · intro c x hx hxmem hmem
    have hx' := hxmem (tupleDegreeOneMonomial_mem f x hx)
    have hcoeff :
        algebraMap (reesAlgebraGrade I 0) (reesAlgebra I) (tupleChartGradeZero f c) ∈ A := by
      exact Subalgebra.algebraMap_mem A (tupleChartGradeZero f c)
    have hcx :
        (⟨Polynomial.monomial 1 (c • x), hmem⟩ : reesAlgebra I) =
          algebraMap (reesAlgebraGrade I 0) (reesAlgebra I) (tupleChartGradeZero f c) *
          (⟨Polynomial.monomial 1 x, tupleDegreeOneMonomial_mem f x hx⟩ :
              reesAlgebra I) := by
      apply Subtype.ext
      simp [tupleChartGradeZero, smul_eq_mul]
    rw [hcx]
    exact mul_mem hcoeff hx'

/-- Helper for Chap10 Lemma 10 70 6: membership in the degree-one adjoin gives membership in the
tuple Rees algebra. -/
private theorem tupleAdjoin_mem_rees {p : Polynomial R}
    (hp : p ∈ Algebra.adjoin R
      (Submodule.map (Polynomial.monomial 1 : R →ₗ[R] Polynomial R) I :
        Set (Polynomial R))) :
    p ∈ reesAlgebra I := by
  -- Mathlib identifies the Rees algebra with the algebra generated by degree-one ideal monomials.
  rw [← adjoin_monomial_eq_reesAlgebra]
  exact hp

/-- Helper for Chap10 Lemma 10 70 6: the tuple degree-one generators generate the Rees algebra
over the degree-zero piece. -/
private theorem affineBlowupTupleReesGenerators_adjoin_eq_top :
    Algebra.adjoin (reesAlgebraGrade I 0)
        (Set.range (tupleReesGenerator f) : Set (reesAlgebra I)) = ⊤ := by
  let A : Subalgebra (reesAlgebraGrade I 0) (reesAlgebra I) :=
    Algebra.adjoin (reesAlgebraGrade I 0)
      (Set.range (tupleReesGenerator f) : Set (reesAlgebra I))
  rw [← top_le_iff]
  intro y _hy
  change y ∈ A
  have hyadjoin : (y : Polynomial R) ∈
      Algebra.adjoin R
        (Submodule.map (Polynomial.monomial 1 : R →ₗ[R] Polynomial R) I :
          Set (Polynomial R)) := by
    rw [adjoin_monomial_eq_reesAlgebra]
    exact y.2
  -- Induct through the algebra generated by degree-one monomials of the tuple ideal.
  refine Algebra.adjoin_induction
    (p := fun p _hp ↦ ∀ hmem : p ∈ reesAlgebra I,
      (⟨p, hmem⟩ : reesAlgebra I) ∈ A)
    ?_ ?_ ?_ ?_ hyadjoin y.2
  · intro p hp hmem
    rcases hp with ⟨x, hx, rfl⟩
    exact tupleReesDegreeOne_mem_adjoin f x hx hmem
  · intro x hmem
    have hconst :
        (⟨algebraMap R (Polynomial R) x, hmem⟩ : reesAlgebra I) =
          algebraMap (reesAlgebraGrade I 0) (reesAlgebra I) (tupleChartGradeZero f x) := by
      rfl
    rw [hconst]
    exact Subalgebra.algebraMap_mem A (tupleChartGradeZero f x)
  · intro p q hp hq hpmem hqmem hmem
    have hp_rees : p ∈ reesAlgebra I := tupleAdjoin_mem_rees f hp
    have hq_rees : q ∈ reesAlgebra I := tupleAdjoin_mem_rees f hq
    have hp' := hpmem hp_rees
    have hq' := hqmem hq_rees
    have hadd :
        (⟨p + q, hmem⟩ : reesAlgebra I) =
          (⟨p, hp_rees⟩ : reesAlgebra I) + (⟨q, hq_rees⟩ : reesAlgebra I) := by
      rfl
    rw [hadd]
    exact add_mem hp' hq'
  · intro p q hp hq hpmem hqmem hmem
    have hp_rees : p ∈ reesAlgebra I := tupleAdjoin_mem_rees f hp
    have hq_rees : q ∈ reesAlgebra I := tupleAdjoin_mem_rees f hq
    have hp' := hpmem hp_rees
    have hq' := hqmem hq_rees
    have hmul :
        (⟨p * q, hmem⟩ : reesAlgebra I) =
          (⟨p, hp_rees⟩ : reesAlgebra I) * (⟨q, hq_rees⟩ : reesAlgebra I) := by
      rfl
    rw [hmul]
    exact mul_mem hp' hq'

/-- Helper for Chap10 Lemma 10 70 6: the chart algebra map from `R` is the degree-zero
homogeneous-localization map. -/
private theorem affineBlowupTupleChart_algebraMap_eq_fromZero (x : R) :
    algebraMap R Chart x =
      HomogeneousLocalization.fromZeroRingHom (reesAlgebraGrade I)
        (Submonoid.powers (reesAlgebraDegreeOne I a)) (tupleChartGradeZero f x) := by
  -- This is the chart's `R`-algebra structure from the affine blowup definition.
  rfl

/-- Helper for Chap10 Lemma 10 70 6: every degree-zero homogeneous scalar belongs to any
`R`-subalgebra of the tuple chart. -/
private theorem affineBlowupTupleChart_gradeZero_algebraMap_mem_adjoin
    (A : Subalgebra R Chart) (r0 : reesAlgebraGrade I 0) :
    algebraMap (reesAlgebraGrade I 0) Chart r0 ∈ A := by
  rcases r0.2 with ⟨x, hx⟩
  have hval : r0 = tupleChartGradeZero f x.1 := by
    apply Subtype.ext
    rw [← hx]
    rfl
  have hmap : algebraMap (reesAlgebraGrade I 0) Chart r0 = algebraMap R Chart x.1 := by
    rw [affineBlowupTupleChart_algebraMap_eq_fromZero]
    change HomogeneousLocalization.fromZeroRingHom (reesAlgebraGrade I)
        (Submonoid.powers (reesAlgebraDegreeOne I a)) r0 =
      HomogeneousLocalization.fromZeroRingHom (reesAlgebraGrade I)
        (Submonoid.powers (reesAlgebraDegreeOne I a)) (tupleChartGradeZero f x.1)
    rw [hval]
  rw [hmap]
  exact Subalgebra.algebraMap_mem A x.1

/-- Helper for Chap10 Lemma 10 70 6: a tuple Rees generator has the degree required for a chart
fraction. -/
private theorem tupleReesGenerator_mem_chartGrade (j : Fin (r + 1)) :
    tupleReesGenerator f j ∈ reesAlgebraGrade I (1 • 1) := by
  -- The denominator has degree one, so the one-step numerator degree is also `1 • 1`.
  simpa using tupleReesGenerator_mem_grade f j

/-- Helper for Chap10 Lemma 10 70 6: the homogeneous chart fraction attached to one tuple
coordinate. -/
private noncomputable def affineBlowupTupleChartCoordinateFraction (j : Fin (r + 1)) : Chart :=
  HomogeneousLocalization.Away.mk (reesAlgebraGrade I) (reesAlgebraDegreeOne_mem I a) 1
    (tupleReesGenerator f j) (tupleReesGenerator_mem_chartGrade f j)

/-- Helper for Chap10 Lemma 10 70 6: the denominator coordinate fraction is `1`. -/
private theorem affineBlowupTupleChartCoordinateFraction_zero :
    affineBlowupTupleChartCoordinateFraction f 0 = (1 : Chart) := by
  -- Compare in the ambient homogeneous localization, where `a^(1) / a^(1) = 1`.
  apply (HomogeneousLocalization.ext_iff_val _ _).2
  rw [affineBlowupTupleChartCoordinateFraction, HomogeneousLocalization.Away.val_mk,
    HomogeneousLocalization.val_one]
  simpa [tupleReesGenerator, tupleSpanFirst] using
    (Localization.mk_self (M := reesAlgebra I)
      (⟨tupleReesGenerator f 0,
        ⟨1, pow_one (tupleReesGenerator f 0)⟩⟩ :
        Submonoid.powers (tupleReesGenerator f 0)))

/-- Helper for Chap10 Lemma 10 70 6: every tuple index is either the denominator index or a
successor tail index. -/
private theorem affineBlowupTupleChartIndex_cases (j : Fin (r + 1)) :
    j = 0 ∨ ∃ i : Fin r, j = i.succ := by
  by_cases hj : j = 0
  · exact Or.inl hj
  · rcases Fin.exists_succ_eq_of_ne_zero hj with ⟨i, hi⟩
    exact Or.inr ⟨i, hi.symm⟩

/-- Helper for Chap10 Lemma 10 70 6: successor coordinate fractions are the displayed chart
generators. -/
private theorem affineBlowupTupleChartCoordinateFraction_succ (i : Fin r) :
    affineBlowupTupleChartCoordinateFraction f i.succ =
      affineBlowupTuplePresentationGenerator f i := by
  -- Both sides are the same basic homogeneous fraction `aᵢ₊₁^(1) / a₁^(1)`.
  rfl

/-- Helper for Chap10 Lemma 10 70 6: every tuple coordinate fraction belongs to the algebra
generated by the displayed tail fractions. -/
private theorem affineBlowupTupleChartCoordinateFraction_mem_adjoin (j : Fin (r + 1)) :
    affineBlowupTupleChartCoordinateFraction f j ∈
      Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f) : Set Chart) := by
  let A : Subalgebra R Chart :=
    Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f) : Set Chart)
  -- Split off the denominator coordinate; all other coordinates are displayed generators.
  rcases affineBlowupTupleChartIndex_cases j with hzero | hidx
  · subst j
    rw [affineBlowupTupleChartCoordinateFraction_zero]
    exact one_mem A
  · rcases hidx with ⟨i, hi⟩
    subst j
    rw [affineBlowupTupleChartCoordinateFraction_succ]
    exact Algebra.subset_adjoin ⟨i, rfl⟩

/-- Helper for Chap10 Lemma 10 70 6: the localization value of a finite product is the product
of the localization values. -/
private theorem affineBlowupTupleChart_val_finset_prod
    {ι : Type*} (s : Finset ι) (g : ι → Chart) :
    HomogeneousLocalization.val (∏ i ∈ s, g i) =
      ∏ i ∈ s, HomogeneousLocalization.val (g i) := by
  classical
  -- The value map is multiplicative, so the statement follows by finite-product induction.
  induction s using Finset.induction_on with
  | empty =>
      simp [HomogeneousLocalization.val_one]
  | insert i s his ih =>
      simp [his, ih, HomogeneousLocalization.val_mul]

/-- Helper for Chap10 Lemma 10 70 6: a full homogeneous product fraction is the product of the
corresponding tuple coordinate fractions. -/
private theorem affineBlowupTupleChartProductFraction_eq
    (n : ℕ) (e : Fin (r + 1) → ℕ) (he : ∑ j, e j • (1 : ℕ) = n • 1) :
    HomogeneousLocalization.Away.mk (reesAlgebraGrade I) (reesAlgebraDegreeOne_mem I a) n
      (∏ j, tupleReesGenerator f j ^ e j)
      (he ▸ SetLike.prod_pow_mem_graded (reesAlgebraGrade I)
        (fun _ : Fin (r + 1) => (1 : ℕ)) (tupleReesGenerator f) e
        (fun j _ => tupleReesGenerator_mem_grade f j)) =
    ∏ j, (affineBlowupTupleChartCoordinateFraction f j) ^ e j := by
  -- Compare the two sides in the ambient localization and collect numerators and denominators.
  apply (HomogeneousLocalization.ext_iff_val _ _).2
  rw [HomogeneousLocalization.Away.val_mk]
  rw [affineBlowupTupleChart_val_finset_prod]
  simp only [HomogeneousLocalization.val_pow, affineBlowupTupleChartCoordinateFraction,
    HomogeneousLocalization.Away.val_mk]
  simp_rw [Localization.mk_pow]
  rw [Localization.mk_prod]
  congr 1
  have hn : ∑ j, e j = n := by
    simpa using he
  ext
  simp [hn, Finset.prod_pow_eq_pow_sum]

/-- Helper for Chap10 Lemma 10 70 6: every full product generator of the homogeneous chart lies
in the algebra generated by the displayed tail fractions. -/
private theorem affineBlowupTupleChartProductFraction_mem_adjoin
    (n : ℕ) (e : Fin (r + 1) → ℕ) (he : ∑ j, e j • (1 : ℕ) = n • 1) :
    HomogeneousLocalization.Away.mk (reesAlgebraGrade I) (reesAlgebraDegreeOne_mem I a) n
      (∏ j, tupleReesGenerator f j ^ e j)
      (he ▸ SetLike.prod_pow_mem_graded (reesAlgebraGrade I)
        (fun _ : Fin (r + 1) => (1 : ℕ)) (tupleReesGenerator f) e
        (fun j _ => tupleReesGenerator_mem_grade f j)) ∈
      Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f) : Set Chart) := by
  -- Rewrite to a product of coordinate fractions, each already known to lie in the generator
  -- algebra.
  rw [affineBlowupTupleChartProductFraction_eq (R := R) f n e he]
  exact prod_mem fun j _ =>
    pow_mem (affineBlowupTupleChartCoordinateFraction_mem_adjoin f j) (e j)

/-- Helper for Chap10 Lemma 10 70 6: the tuple affine blowup chart is generated over `R` by the
displayed fractions `aᵢ₊₁ / a₁`. -/
private theorem affineBlowupTupleChart_generators_adjoin_eq_top :
    Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f)) =
      (⊤ : Subalgebra R Chart) := by
  have hfull := HomogeneousLocalization.Away.adjoin_mk_prod_pow_eq_top
    (𝒜 := reesAlgebraGrade I)
    (f := reesAlgebraDegreeOne I a)
    (d := (1 : ℕ))
    (reesAlgebraDegreeOne_mem I a)
    (Fin (r + 1)) (tupleReesGenerator f)
    (affineBlowupTupleReesGenerators_adjoin_eq_top f)
    (fun _ : Fin (r + 1) => (1 : ℕ))
    (tupleReesGenerator_mem_grade f)
  let A : Subalgebra R Chart :=
    Algebra.adjoin R (Set.range (affineBlowupTuplePresentationGenerator f) : Set Chart)
  apply top_unique
  intro z _hz
  have hzfull : z ∈ (⊤ : Subalgebra (reesAlgebraGrade I 0) Chart) := by
    trivial
  rw [← hfull] at hzfull
  -- The full homogeneous-localization generators lie in `A`, and degree-zero scalars are ordinary
  -- `R`-scalars, so the full generated algebra is contained in `A`.
  change z ∈ A
  refine Algebra.adjoin_induction
    (p := fun z _hz ↦ z ∈ A)
    ?_ ?_ ?_ ?_ hzfull
  · rintro _ ⟨n, e, he, _hle, rfl⟩
    exact affineBlowupTupleChartProductFraction_mem_adjoin f n e he
  · intro r0
    exact affineBlowupTupleChart_gradeZero_algebraMap_mem_adjoin f A r0
  · intro x y _hx _hy hxA hyA
    exact A.add_mem hxA hyA
  · intro x y _hx _hy hxA hyA
    exact A.mul_mem hxA hyA

/-- Helper for Chap10 Lemma 10 70 6: after multiplying by a power of `a₁`, a polynomial class
and its ordinary localization evaluation both come from the same element of `R`. -/
private theorem tupleLocalizationEval_clearDenominators
    (p : MvPolynomial (Fin r) R) :
    ∃ N : ℕ, ∃ y : R,
      (algebraMap R Q (f 0)) ^ N *
          Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) p =
        algebraMap R Q y ∧
      (algebraMap R (Localization.Away (f 0)) (f 0)) ^ N * tupleLocalizationEval f p =
        algebraMap R (Localization.Away (f 0)) y := by
  -- Induct over polynomials, carrying one common cleared numerator in the quotient and in
  -- ordinary localization.
  induction p using MvPolynomial.induction_on with
  | C x =>
      refine ⟨0, x, ?_, ?_⟩
      · rw [pow_zero, one_mul]
        change
          (Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f))
              (algebraMap R (MvPolynomial (Fin r) R) x) =
            algebraMap R Q x
        rfl
      · simp [tupleLocalizationEval]
  | add p q hp hq =>
      rcases hp with ⟨Np, yp, hpQ, hpL⟩
      rcases hq with ⟨Nq, yq, hqQ, hqL⟩
      refine ⟨Np + Nq, f 0 ^ Nq * yp + f 0 ^ Np * yq, ?_, ?_⟩
      · -- Equalize denominators by multiplying the two induction hypotheses by complementary
        -- powers of `a₁`.
        calc
          (algebraMap R Q (f 0)) ^ (Np + Nq) *
              Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (p + q)
              =
            (algebraMap R Q (f 0)) ^ Nq *
                ((algebraMap R Q (f 0)) ^ Np *
                  Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) p) +
              (algebraMap R Q (f 0)) ^ Np *
                ((algebraMap R Q (f 0)) ^ Nq *
                  Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) q) := by
                simp only [map_add]
                ring
          _ =
            (algebraMap R Q (f 0)) ^ Nq * algebraMap R Q yp +
              (algebraMap R Q (f 0)) ^ Np * algebraMap R Q yq := by
                rw [hpQ, hqQ]
          _ = algebraMap R Q (f 0 ^ Nq * yp + f 0 ^ Np * yq) := by
                simp [map_add, map_mul, map_pow]
      · -- The same denominator equalization works after ordinary localization evaluation.
        calc
          (algebraMap R (Localization.Away (f 0)) (f 0)) ^ (Np + Nq) *
              tupleLocalizationEval f (p + q)
              =
            (algebraMap R (Localization.Away (f 0)) (f 0)) ^ Nq *
                ((algebraMap R (Localization.Away (f 0)) (f 0)) ^ Np *
                  tupleLocalizationEval f p) +
              (algebraMap R (Localization.Away (f 0)) (f 0)) ^ Np *
                ((algebraMap R (Localization.Away (f 0)) (f 0)) ^ Nq *
                  tupleLocalizationEval f q) := by
                simp only [map_add]
                ring
          _ =
            (algebraMap R (Localization.Away (f 0)) (f 0)) ^ Nq *
                algebraMap R (Localization.Away (f 0)) yp +
              (algebraMap R (Localization.Away (f 0)) (f 0)) ^ Np *
                algebraMap R (Localization.Away (f 0)) yq := by
                rw [hpL, hqL]
          _ =
            algebraMap R (Localization.Away (f 0)) (f 0 ^ Nq * yp + f 0 ^ Np * yq) := by
                simp [map_add, map_mul, map_pow]
  | mul_X p i hp =>
      rcases hp with ⟨N, y, hpQ, hpL⟩
      refine ⟨N + 1, y * f i.succ, ?_, ?_⟩
      · -- The defining quotient relation replaces `a₁ Xᵢ` by `aᵢ₊₁`.
        have hvar := affineBlowupTuplePresentationQuotient_variable_relation f i
        calc
          (algebraMap R Q (f 0)) ^ (N + 1) *
              Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (p * X i)
              =
            ((algebraMap R Q (f 0)) ^ N *
                Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) p) *
              ((algebraMap R Q (f 0)) *
                Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) (X i)) := by
                simp only [map_mul]
                ring
          _ = algebraMap R Q y * algebraMap R Q (f i.succ) := by
                rw [hpQ, hvar]
          _ = algebraMap R Q (y * f i.succ) := by
                simp [map_mul]
      · -- The ordinary localization relation has the same shape.
        have hvar := tupleLocalizationEval_variable_relation f i
        calc
          (algebraMap R (Localization.Away (f 0)) (f 0)) ^ (N + 1) *
              tupleLocalizationEval f (p * X i)
              =
            ((algebraMap R (Localization.Away (f 0)) (f 0)) ^ N *
                tupleLocalizationEval f p) *
              ((algebraMap R (Localization.Away (f 0)) (f 0)) *
                tupleLocalizationEval f (X i)) := by
                simp only [map_mul]
                ring
          _ =
            algebraMap R (Localization.Away (f 0)) y *
              algebraMap R (Localization.Away (f 0)) (f i.succ) := by
                rw [hpL, hvar]
          _ = algebraMap R (Localization.Away (f 0)) (y * f i.succ) := by
                simp [map_mul]

end

/-- Membership in the kernel of the tuple-presentation map is exactly `a₁`-power torsion in the
source quotient. -/
theorem mem_ker_affineBlowupTuplePresentationMap_iff_exists_pow_mul_eq_zero
    (x : affineBlowupTuplePresentationQuotient f) :
    x ∈ RingHom.ker (affineBlowupTuplePresentationMap f).toRingHom ↔
      ∃ n : ℕ, (algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0)) ^ n * x = 0 :=
  by
    constructor
    · intro hx
      -- Choose a polynomial representative, compare its chart image with ordinary localization,
      -- then clear denominators and pull ordinary-localization vanishing back to the quotient.
      obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
      have hchart :
          affineBlowupTuplePresentationToBlowup f p = 0 := by
        simpa [RingHom.mem_ker, affineBlowupTuplePresentationMap] using hx
      have hloc_zero : tupleLocalizationEval f p = 0 := by
        have hcomp := congrArg
          (affineBlowupChartToLocalizationAway (Ideal.span (Set.range f)) (tupleSpanFirst f))
          hchart
        simpa [affineBlowupTuplePresentationToAway_eq_tupleLocalizationEval f p] using hcomp
      rcases tupleLocalizationEval_clearDenominators f p with ⟨N, y, hQ, hL⟩
      have hy_loc : algebraMap R (Localization.Away (f 0)) y = 0 := by
        have hy_loc' : 0 = algebraMap R (Localization.Away (f 0)) y := by
          simpa [hloc_zero] using hL
        exact hy_loc'.symm
      have hy_loc_mk :
          IsLocalization.mk' (Localization.Away (f 0)) y
              (1 : Submonoid.powers (f 0)) = 0 := by
        simpa [IsLocalization.mk'_one] using hy_loc
      rw [IsLocalization.mk'_eq_zero_iff] at hy_loc_mk
      rcases hy_loc_mk with ⟨s, hs⟩
      rcases s.2 with ⟨k, hk⟩
      have hy_zero : f 0 ^ k * y = 0 := by
        simpa [hk] using hs
      refine ⟨N + k, ?_⟩
      calc
        (algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0)) ^ (N + k) *
            Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) p
            =
          (algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0)) ^ k *
            ((algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0)) ^ N *
              Ideal.Quotient.mk (affineBlowupTuplePresentationRelationIdeal f) p) := by
              ring
        _ =
          (algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0)) ^ k *
            algebraMap R (affineBlowupTuplePresentationQuotient f) y := by
              rw [hQ]
        _ = algebraMap R (affineBlowupTuplePresentationQuotient f) (f 0 ^ k * y) := by
              simp [map_mul, map_pow]
        _ = 0 := by
              rw [hy_zero, map_zero]
    · rintro ⟨n, hn⟩
      rw [RingHom.mem_ker]
      -- Mapping the annihilating equality to the chart makes a regular power of `a₁` kill the
      -- image, hence the image itself is zero.
      have hmap := congrArg (affineBlowupTuplePresentationMap f) hn
      have hmul :
          (algebraMap R
              (affineBlowupChart (Ideal.span (Set.range f)) (tupleSpanFirst f)) (f 0)) ^ n *
              affineBlowupTuplePresentationMap f x = 0 := by
        simpa [map_mul, map_pow] using hmap
      have hmul' :
          (algebraMap R
              (affineBlowupChart (Ideal.span (Set.range f)) (tupleSpanFirst f))
              (tupleSpanFirst f).1) ^ n * affineBlowupTuplePresentationMap f x =
            (algebraMap R
              (affineBlowupChart (Ideal.span (Set.range f)) (tupleSpanFirst f))
              (tupleSpanFirst f).1) ^ n * 0 := by
        rw [mul_zero]
        simpa [tupleSpanFirst] using hmul
      exact (IsRegular.pow n
        (affineBlowupChart_isRegular (Ideal.span (Set.range f)) (tupleSpanFirst f))).left hmul'

/-- Chap10 Lemma 10 70 6: the canonical quotient presentation map is surjective, and its kernel
consists exactly of the elements annihilated by some power of the image of `a₁`. -/
@[stacks 0G8S]
theorem affineBlowupTuplePresentationMap_surjective_and_ker_eq_a_power_torsion :
    let Q := affineBlowupTuplePresentationQuotient f
    let φ := affineBlowupTuplePresentationMap f
    let aQ : Q := algebraMap R Q (f 0)
    Function.Surjective φ ∧
      ∀ x : Q, x ∈ RingHom.ker φ.toRingHom ↔ ∃ n : ℕ, aQ ^ n * x = 0 := by
  refine ⟨?_, ?_⟩
  · -- The homogeneous-localization generation theorem gives the displayed fraction generators;
    -- the quotient map hits those generators, so it is surjective.
    exact affineBlowupTuplePresentationMap_surjective_of_adjoin_generators f
      (affineBlowupTupleChart_generators_adjoin_eq_top f)
  · intro x
    exact mem_ker_affineBlowupTuplePresentationMap_iff_exists_pow_mul_eq_zero f x

/-- Canonical reformulation of Lemma 10.70.6: the kernel of the quotient presentation map is the
primary component of the principal ideal generated by the image of `a₁`. -/
theorem affineBlowupTuplePresentationMap_surjective_and_ker_eq_primaryComponent :
    let Q := affineBlowupTuplePresentationQuotient f
    let φ := affineBlowupTuplePresentationMap f
    let aQ : Q := algebraMap R Q (f 0)
    Function.Surjective φ ∧
      RingHom.ker φ.toRingHom = (Ideal.span ({aQ} : Set Q)).primaryComponent Q := by
  let Q := affineBlowupTuplePresentationQuotient f
  let φ := affineBlowupTuplePresentationMap f
  let aQ : Q := algebraMap R Q (f 0)
  change Function.Surjective φ ∧
    RingHom.ker φ.toRingHom = (Ideal.span ({aQ} : Set Q)).primaryComponent Q
  refine ⟨(affineBlowupTuplePresentationMap_surjective_and_ker_eq_a_power_torsion f).1, ?_⟩
  ext x
  rw [Ideal.primaryComponent_mem]
  constructor
  · intro hx
    rcases
      (affineBlowupTuplePresentationMap_surjective_and_ker_eq_a_power_torsion f).2 x |>.mp hx with
        ⟨n, hn⟩
    have hn' : aQ ^ n * x = 0 := by
      simpa [aQ] using hn
    refine ⟨n, ?_⟩
    rw [Submodule.mem_torsionBySet_iff]
    intro y
    rcases y with ⟨y, hy⟩
    rw [Ideal.span_singleton_pow] at hy
    change y ∈ Ideal.span ({aQ ^ n} : Set Q) at hy
    rw [Ideal.mem_span_singleton'] at hy
    rcases hy with ⟨c, rfl⟩
    simp [smul_eq_mul, mul_assoc, hn']
  · rintro ⟨n, hx⟩
    refine
      (affineBlowupTuplePresentationMap_surjective_and_ker_eq_a_power_torsion f).2 x |>.mpr ⟨n, ?_⟩
    rw [Submodule.mem_torsionBySet_iff] at hx
    simpa [smul_eq_mul, Ideal.span_singleton_pow] using
      hx ⟨aQ ^ n, by
        rw [Ideal.span_singleton_pow]
        exact Ideal.subset_span (by simp)⟩

end
