import StacksProject_2024.Chap10.Lemma_10_64_3.Index

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

section

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S] [Module.Flat R S]

open scoped TensorProduct

namespace Ideal

variable (𝔭 : Ideal R) [𝔭.IsPrime]
variable [(𝔭.map (algebraMap R S)).IsPrime]

local notation "𝔭S" => 𝔭.map (algebraMap R S)
local notation "Rₚ" => Localization.AtPrime 𝔭
local notation "Sₚ" => Localization (Algebra.algebraMapSubmonoid S (Ideal.primeCompl 𝔭))
local notation "S𝔮" => Localization.AtPrime 𝔭S

attribute [local instance] semilocal_map_prime_isPrime
attribute [local instance] semilocalToLocalAlgebra

/-
Domain triage: this file stays in commutative algebra of prime ideals, flatness, and localization.
The owner abstraction is the source-facing `Ideal.symbolicPower` from `Definition_10_64_1`; this
lemma is a derived base-change statement for that owner, not a new wrapper notion.

Relevant upstream owner-side declarations inspected before refinement:
* `Ideal.symbolicPower` and `Ideal.symbolicPower_eq_ker_quotient_map_pow`
* `RingHom.Flat.generalizingMap_comap` / `Ideal.exists_ideal_le_liesOver_of_le`
* `IsLocalization.AtPrime.map_eq_maximalIdeal` and `IsLocalization.AtPrime.comap_maximalIdeal`
-/

-- Proof sketch: rewrite both symbolic powers through the owner declaration
-- `Ideal.symbolicPower`; flatness identifies the extension of the kernel
-- `R → R_𝔭 / 𝔭^n R_𝔭` with the kernel of the base-changed map
-- `S → S_𝔮 / 𝔭^n S_𝔮`, and the primeness of `𝔭S` lets one compare this with the defining kernel
-- of the symbolic power of `𝔭S`.
/-- Helper for Chap10 Lemma 10 64 3: the tensor-side denominator `J₀Sₚ • ⊤` appearing in the localized
power-layer comparison. -/
noncomputable def semilocal_power_ideal_baseChange_sourceDenominator (m : ℕ) :
    Submodule Sₚ (Sₚ ⊗[Rₚ] ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ)) :=
  let M := Sₚ ⊗[Rₚ] ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ)
  letI : Module Sₚ M := inferInstance
  letI : IsScalarTower Sₚ Sₚ M := IsScalarTower.left Sₚ (α := M)
  let J₀Sₚ : Ideal Sₚ := map (algebraMap Rₚ Sₚ) (map (algebraMap R Rₚ) 𝔭)
  J₀Sₚ • (⊤ : Submodule Sₚ M)

/-- Helper for Chap10 Lemma 10 64 3: the semilocal power-ideal denominator `JSₚ • ⊤` after transporting
across the tensor-unit equivalence. -/
noncomputable def semilocal_power_ideal_baseChange_targetDenominator (m : ℕ) :
    Submodule Sₚ (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)) :=
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  J • (⊤ : Submodule Sₚ (J ^ m : Ideal Sₚ))

omit [Module.Flat R S] [(𝔭.map (algebraMap R S)).IsPrime] in
/-- Helper for Chap10 Lemma 10 64 3: the target denominator is the usual next-power submodule
`J^(m + 1) ≤ J^m`. -/
lemma semilocal_power_ideal_baseChange_targetDenominator_eq_submoduleOf
    (m : ℕ) :
    (((map (algebraMap S Sₚ) 𝔭S) ^ (m + 1) : Ideal Sₚ).submoduleOf
      (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ))) =
      semilocal_power_ideal_baseChange_targetDenominator
        (R := R) (S := S) (𝔭 := 𝔭) m := by
  -- Normalize the filtration quotient denominator from a next-power inclusion to `J • ⊤`.
  simp [semilocal_power_ideal_baseChange_targetDenominator,
    pow_succ_submoduleOf_eq_ideal_smul_top]

/-- Helper for Chap10 Lemma 10 64 3: the raw base-change equivalence carries the tensor-side denominator
`J₀Sₚ • ⊤` to the literal denominator `JSₚ • ⊤` on the semilocal power ideal. -/
lemma semilocal_power_ideal_baseChange_smul_top
    (m : ℕ) :
    Submodule.map
        (semilocal_power_ideal_baseChange_linearEquiv
          (R := R) (S := S) (𝔭 := 𝔭) m).toLinearMap
        (semilocal_power_ideal_baseChange_sourceDenominator
        (R := R) (S := S) (𝔭 := 𝔭) m) =
      semilocal_power_ideal_baseChange_targetDenominator
        (R := R) (S := S) (𝔭 := 𝔭) m := by
  -- The quotient denominator is generated by the localized prime, so the linear equivalence
  -- sends it to the corresponding `J • ⊤` denominator after identifying the image ideal.
  simp [semilocal_power_ideal_baseChange_sourceDenominator,
    semilocal_power_ideal_baseChange_targetDenominator, Submodule.map_smul'',
    Submodule.map_top, LinearEquiv.range,
    localized_prime_map_eq_semilocalized_prime]

/-- Helper for Chap10 Lemma 10 64 3: the graded layer `J^m / J^(m + 1)` is the flat base change of the
corresponding layer for the localized base prime. -/
noncomputable def semilocal_power_layer_baseChange_equiv
    (m : ℕ) :
    ((((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)) ⧸
        (((map (algebraMap S Sₚ) 𝔭S) ^ (m + 1) : Ideal Sₚ).submoduleOf
          (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)))) ≃ₗ[Sₚ]
      Sₚ ⊗[Rₚ]
        (((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ) ⧸
          ((map (algebraMap R Rₚ) 𝔭) •
            (⊤ : Submodule Rₚ ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ)))) :=
  (Submodule.quotEquivOfEq
      (((map (algebraMap S Sₚ) 𝔭S) ^ (m + 1) : Ideal Sₚ).submoduleOf
        (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)))
      (semilocal_power_ideal_baseChange_targetDenominator
        (R := R) (S := S) (𝔭 := 𝔭) m)
      (semilocal_power_ideal_baseChange_targetDenominator_eq_submoduleOf
        (R := R) (S := S) (𝔭 := 𝔭) m)).trans
    ((Submodule.Quotient.equiv
        (semilocal_power_ideal_baseChange_sourceDenominator
          (R := R) (S := S) (𝔭 := 𝔭) m)
        (semilocal_power_ideal_baseChange_targetDenominator
          (R := R) (S := S) (𝔭 := 𝔭) m)
        (semilocal_power_ideal_baseChange_linearEquiv
          (R := R) (S := S) (𝔭 := 𝔭) m)
        (semilocal_power_ideal_baseChange_smul_top
          (R := R) (S := S) (𝔭 := 𝔭) m)).symm.trans
      (TensorProduct.tensorQuotMapSMulEquivTensorQuot
        (R := Rₚ) (S := Sₚ)
        (M := ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ))
        (map (algebraMap R Rₚ) 𝔭)))

/-- Helper for Chap10 Lemma 10 64 3: the localized power layer quotient is already annihilated by the
localized prime ideal, so it is naturally a module over the residue field `Rₚ / J₀`. -/
lemma pow_layer_ideal_smul_top_eq_bot
    (m : ℕ) :
    let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
    let V :=
      (((J₀ ^ m : Ideal Rₚ) ⧸
        (J₀ • (⊤ : Submodule Rₚ (J₀ ^ m : Ideal Rₚ)))))
    J₀ • (⊤ : Submodule Rₚ V) = ⊥ := by
  let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
  let V :=
    (((J₀ ^ m : Ideal Rₚ) ⧸
      (J₀ • (⊤ : Submodule Rₚ (J₀ ^ m : Ideal Rₚ)))))
  -- Proof comment: every scalar from `J₀` maps to zero in `Rₚ / J₀`, so it acts trivially on the
  -- quotient layer, which collapses the whole `J₀ • ⊤` submodule.
  rw [← Submodule.le_annihilator_iff, Submodule.annihilator_top]
  intro r hr
  exact Module.mem_annihilator.mpr fun x ↦ by
    rw [← algebraMap_smul (A := Rₚ ⧸ J₀) r x]
    simp [J₀, Ideal.Quotient.eq_zero_iff_mem.mpr hr]

/-- Helper for Chap10 Lemma 10 64 3: the semilocal residue tensor ring
`Sₚ ⊗[Rₚ] (Rₚ / J₀)` is a domain. -/
lemma semilocal_residueTensor_isDomain :
    let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
    let κ := Rₚ ⧸ J₀
    let B := Sₚ ⊗[Rₚ] κ
    letI : Algebra Sₚ B :=
      Algebra.TensorProduct.leftAlgebra (R := Rₚ) (S := Sₚ) (A := Sₚ) (B := κ)
    letI : Algebra κ B :=
      Algebra.TensorProduct.rightAlgebra (R := Rₚ) (A := Sₚ) (B := κ)
    letI : Module κ B := Algebra.toModule
    IsDomain B := by
  dsimp only
  let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
  let κ := Rₚ ⧸ J₀
  let A := Sₚ ⧸ map (algebraMap S Sₚ) 𝔭S
  let B := Sₚ ⊗[Rₚ] κ
  letI : Algebra κ A :=
    semilocal_prime_quotient_residue_algebra (R := R) (S := S) (𝔭 := 𝔭)
  letI : Module κ A := Algebra.toModule
  letI : IsDomain A := inferInstance
  letI : Nontrivial A := inferInstance
  -- Proof comment: identify the tensor ring with the prime quotient, then transport the
  -- domain structure across this algebra equivalence.
  have hJ : map (algebraMap S Sₚ) 𝔭S = J₀.map (algebraMap Rₚ Sₚ) := by
    simpa [J₀] using
      (localized_prime_map_eq_semilocalized_prime (R := R) (S := S) (𝔭 := 𝔭)).symm
  let eAlgJ : A ≃ₐ[Sₚ] (Sₚ ⧸ J₀.map (algebraMap Rₚ Sₚ)) :=
    Ideal.quotientEquivAlgOfEq Sₚ hJ
  letI : Algebra Sₚ B :=
    Algebra.TensorProduct.leftAlgebra (R := Rₚ) (S := Sₚ) (A := Sₚ) (B := κ)
  let eAlg0 : (Sₚ ⧸ J₀.map (algebraMap Rₚ Sₚ)) ≃ₐ[Sₚ] B :=
    Algebra.TensorProduct.quotIdealMapEquivTensorQuot Sₚ J₀
  let eAlg : A ≃ₐ[Sₚ] B := eAlgJ.trans eAlg0
  letI : Nontrivial B := eAlg.symm.toEquiv.nontrivial
  exact eAlg.symm.toRingEquiv.toMulEquiv.isDomain A

/-- Helper for Chap10 Lemma 10 64 3: a semilocal denominator has nonzero image in
`Sₚ ⊗[Rₚ] (Rₚ / J₀)`. -/
lemma semilocal_residueTensor_includeLeft_ne_zero
    (c : Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S)) :
    (Algebra.TensorProduct.includeLeft (R := Rₚ) (S := Sₚ) (A := Sₚ)
      (B := Rₚ ⧸ map (algebraMap R Rₚ) 𝔭)) (c : Sₚ) ≠ 0 := by
  let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  let κ := Rₚ ⧸ J₀
  let A := Sₚ ⧸ J
  let B := Sₚ ⊗[Rₚ] κ
  letI : Algebra Sₚ B :=
    Algebra.TensorProduct.leftAlgebra (R := Rₚ) (S := Sₚ) (A := Sₚ) (B := κ)
  -- Proof comment: compare the tensor-side class with the quotient class, whose nonvanishing is
  -- exactly the definition of `primeCompl`.
  have hJ : J = J₀.map (algebraMap Rₚ Sₚ) := by
    simpa [J₀, J] using
      (localized_prime_map_eq_semilocalized_prime (R := R) (S := S) (𝔭 := 𝔭)).symm
  let eAlgJ : A ≃ₐ[Sₚ] (Sₚ ⧸ J₀.map (algebraMap Rₚ Sₚ)) :=
    Ideal.quotientEquivAlgOfEq Sₚ hJ
  let eAlg0 : (Sₚ ⧸ J₀.map (algebraMap Rₚ Sₚ)) ≃ₐ[Sₚ] B :=
    Algebra.TensorProduct.quotIdealMapEquivTensorQuot Sₚ J₀
  let eAlg : A ≃ₐ[Sₚ] B := eAlgJ.trans eAlg0
  intro hc
  have hcA : Ideal.Quotient.mk J (c : Sₚ) ≠ 0 := by
    simpa [J] using semilocal_denominator_class_ne_zero (R := R) (S := S) (𝔭 := 𝔭) c
  have hcomm : eAlg (Ideal.Quotient.mk J (c : Sₚ)) =
      (Algebra.TensorProduct.includeLeft (R := Rₚ) (S := Sₚ) (A := Sₚ) (B := κ))
        (c : Sₚ) := by
    simp [eAlg, eAlgJ, eAlg0, A, B, κ, Ideal.quotientEquivAlgOfEq_mk]
  exact hcA (eAlg.toEquiv.injective (by simpa [J₀, κ, hcomm] using hc))

/-- Helper for Chap10 Lemma 10 64 3: a basis of a `κ`-vector space identifies
`B ⊗[A] V` with finitely supported coordinates in `B ⊗[A] κ` after restricting scalars to
`A`. -/
noncomputable def tensorBasisFinsuppRightEquiv
    {A : Type*} {B : Type*} {κ : Type*} {V : Type*} {ι : Type*}
    [CommRing A] [CommRing B] [Field κ] [Algebra A B] [Algebra A κ]
    [AddCommGroup V] [Module A V] [Module κ V] [IsScalarTower A κ V]
    [DecidableEq ι] (b : Module.Basis ι κ V) :
    B ⊗[A] V ≃ₗ[B] ι →₀ B ⊗[A] κ :=
  let e₁ : V ≃ₗ[A] ι →₀ κ := b.repr.restrictScalars A
  let e₂ : B ⊗[A] V ≃ₗ[B] B ⊗[A] (ι →₀ κ) :=
    TensorProduct.AlgebraTensorModule.congr (LinearEquiv.refl B B) e₁
  let e₃ : B ⊗[A] (ι →₀ κ) ≃ₗ[B] ι →₀ B ⊗[A] κ :=
    TensorProduct.finsuppRight A B B κ ι
  e₂.trans e₃

/-- Helper for Chap10 Lemma 10 64 3: if the image of a scalar in a domain algebra is nonzero, then
that scalar acts regularly on finitely supported families after restriction of scalars. -/
lemma isSMulRegular_finsupp_restrictScalars_of_ne_zero
    {A : Type*} {B : Type*} {ι : Type*}
    [CommRing A] [CommRing B] [Algebra A B] [IsDomain B]
    {a : A} (ha : algebraMap A B a ≠ 0) :
    IsSMulRegular (ι →₀ B) a := by
  -- First prove regularity coordinatewise over `B`, then reinterpret it along `A → B`.
  have hB : IsSMulRegular (ι →₀ B) (algebraMap A B a) :=
    isSMulRegular_finsupp_of_ne_zero (A := B) (ι := ι) ha
  exact (isSMulRegular_algebraMap_iff (A := B) (M := ι →₀ B) (r := a)).mp hB

/-- Helper for Chap10 Lemma 10 64 3: denominators act regularly on the tensor-side localized
power layer after choosing coordinates over the residue field. -/
lemma semilocal_tensor_layer_isSMulRegular_via_basis
    (m : ℕ) (c : Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S)) :
    IsSMulRegular
      (Sₚ ⊗[Rₚ]
        (((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ) ⧸
          ((map (algebraMap R Rₚ) 𝔭) •
            (⊤ : Submodule Rₚ ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ)))))
      (c : Sₚ) := by
  classical
  let J₀ : Ideal Rₚ := map (algebraMap R Rₚ) 𝔭
  let κ := Rₚ ⧸ J₀
  let V := ((J₀ ^ m : Ideal Rₚ) ⧸ J₀ • (⊤ : Submodule Rₚ (J₀ ^ m : Ideal Rₚ)))
  let B := Sₚ ⊗[Rₚ] κ
  letI : J₀.IsMaximal := IsLocalization.AtPrime.isMaximal_map 𝔭 Rₚ
  letI : Field κ := Ideal.Quotient.field J₀
  letI : Algebra Sₚ B :=
    Algebra.TensorProduct.leftAlgebra (R := Rₚ) (S := Sₚ) (A := Sₚ) (B := κ)
  let hTors : Module.IsTorsionBySet Rₚ V J₀ :=
    Module.isTorsionBySet_quotient_ideal_smul (J₀ ^ m : Ideal Rₚ) J₀
  letI : SMul κ V := hTors.module.toDistribMulAction.toMulAction.toSMul
  letI : Module κ V := hTors.module
  letI : IsScalarTower Rₚ κ V := hTors.isScalarTower
  have hdomain : IsDomain B := by
    -- The residue tensor ring is the semilocal prime quotient, hence a domain.
    simpa [J₀, κ, B] using
      semilocal_residueTensor_isDomain (R := R) (S := S) (𝔭 := 𝔭)
  letI : IsDomain B := hdomain
  have hcB : algebraMap Sₚ B (c : Sₚ) ≠ 0 := by
    -- The denominator remains nonzero in the residue tensor ring.
    simpa [J₀, κ, B, Algebra.TensorProduct.includeLeft] using
      semilocal_residueTensor_includeLeft_ne_zero (R := R) (S := S) (𝔭 := 𝔭) c
  let ι := Module.Basis.ofVectorSpaceIndex κ V
  let b : Module.Basis ι κ V := Module.Basis.ofVectorSpace κ V
  let e : Sₚ ⊗[Rₚ] V ≃ₗ[Sₚ] ι →₀ B :=
    tensorBasisFinsuppRightEquiv (A := Rₚ) (B := Sₚ) (κ := κ) (V := V) b
  have hregular_finsupp : IsSMulRegular (ι →₀ B) (c : Sₚ) :=
    isSMulRegular_finsupp_restrictScalars_of_ne_zero (A := Sₚ) (B := B) (ι := ι) hcB
  -- Transport coordinatewise regularity back through the tensor basis normal form.
  exact (e.isSMulRegular_congr (c : Sₚ)).mpr hregular_finsupp

/-- Chap10 Lemma 10 64 3: each graded piece `J^m / J^(m + 1)` is a tensor module over the
semilocal prime quotient, so denominators outside `J` act regularly on it. -/
lemma semilocal_denominator_layer_isSMulRegular_via_tensor_layer
    (m : ℕ) (c : Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S)) :
    IsSMulRegular
      ((((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)) ⧸
          (((map (algebraMap S Sₚ) 𝔭S) ^ (m + 1) : Ideal Sₚ).submoduleOf
            (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ))))
      (c : Sₚ) := by
  -- Route correction: avoid the previous cancel-base-change transport and use the basis/finsupp
  -- tensor normal form on the already constructed base-change layer.
  have htensor :
      IsSMulRegular
        (Sₚ ⊗[Rₚ]
          (((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ) ⧸
            ((map (algebraMap R Rₚ) 𝔭) •
              (⊤ : Submodule Rₚ ((map (algebraMap R Rₚ) 𝔭) ^ m : Ideal Rₚ)))))
        (c : Sₚ) :=
    semilocal_tensor_layer_isSMulRegular_via_basis
      (R := R) (S := S) (𝔭 := 𝔭) m c
  -- The target layer is linearly equivalent to that tensor-side layer.
  exact ((semilocal_power_layer_baseChange_equiv
    (R := R) (S := S) (𝔭 := 𝔭) m).isSMulRegular_congr (c : Sₚ)).mpr htensor

/-- Helper for Chap10 Lemma 10 64 3: regularity on `Sₚ / J^m` and on the next graded layer propagates to
regularity on `Sₚ / J^(m + 1)`. -/
lemma semilocal_denominator_isSMulRegular_pow_quotient_succ
    (m : ℕ) (c : Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S))
    (hprev :
      IsSMulRegular (Sₚ ⧸ (map (algebraMap S Sₚ) 𝔭S) ^ m) (c : Sₚ))
    (hlayer :
      IsSMulRegular
        ((((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ)) ⧸
          (((map (algebraMap S Sₚ) 𝔭S) ^ (m + 1) : Ideal Sₚ).submoduleOf
            (((map (algebraMap S Sₚ) 𝔭S) ^ m : Ideal Sₚ))))
        (c : Sₚ)) :
    IsSMulRegular (Sₚ ⧸ (map (algebraMap S Sₚ) 𝔭S) ^ (m + 1)) (c : Sₚ) := by
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  -- Route correction: use the quotient membership criterion directly instead of repackaging the
  -- layer sequence as a separate short exact object.
  rw [isSMulRegular_quotient_iff_mem_of_smul_mem]
  intro x hx
  have hx_mem_pow :
      x ∈ J ^ m := by
    -- First descend one step in the filtration using regularity on the previous quotient.
    have hsmul_mem_pow : (c : Sₚ) • x ∈ (J ^ m : Ideal Sₚ) := by
      exact (Ideal.pow_le_pow_right (Nat.le_succ m)) hx
    exact (isSMulRegular_quotient_iff_mem_of_smul_mem (J ^ m) (c : Sₚ)).mp
      hprev x <| by
        simpa [smul_eq_mul, J] using hsmul_mem_pow
  let x' : (J ^ m : Ideal Sₚ) := ⟨x, hx_mem_pow⟩
  have hsmul_mem_layer :
      (c : Sₚ) • x' ∈ ((J ^ (m + 1)).submoduleOf (J ^ m)) := by
    -- The hypothesis already says the scalar multiple lands in the next power.
    change ((c : Sₚ) * x) ∈ J ^ (m + 1)
    simpa [smul_eq_mul, J] using hx
  have hx_mem_layer :
      x' ∈ ((J ^ (m + 1)).submoduleOf (J ^ m)) := by
    -- Then kill the class of `x` in the layer quotient.
    exact (isSMulRegular_quotient_iff_mem_of_smul_mem
      ((J ^ (m + 1)).submoduleOf (J ^ m)) (c : Sₚ)).mp
        hlayer x' hsmul_mem_layer
  -- Membership in the `submoduleOf` is exactly membership in the ambient next power.
  simpa [Submodule.submoduleOf, J] using hx_mem_layer

/-- Helper for Chap10 Lemma 10 64 3: every denominator outside the semilocalized prime acts regularly on
the positive semilocal power quotients `Sₚ / J^n`, where `J = map (algebraMap S Sₚ) 𝔭S`. -/
lemma semilocal_denominator_isSMulRegular_pow_quotient
    {n : ℕ} (hn : 0 < n) :
    ∀ c : Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S),
      IsSMulRegular (Sₚ ⧸ (map (algebraMap S Sₚ) 𝔭S) ^ n) (c : Sₚ) := by
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  intro c
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  have hpow :
      ∀ k : ℕ, ∀ d : Ideal.primeCompl J, IsSMulRegular (Sₚ ⧸ J ^ (k + 1)) (d : Sₚ) := by
    intro k
    induction k with
    | zero =>
        intro d
        -- The base case is the prime quotient, where every denominator class is already regular.
        exact ((Submodule.quotEquivOfEq (J ^ (0 + 1)) J (by simp [pow_one])).isSMulRegular_congr
          (d : Sₚ)).mpr <|
          semilocal_denominator_isSMulRegular_prime_quotient
            (R := R) (S := S) (𝔭 := 𝔭) d
    | succ k ih =>
        intro d
        -- Once the previous quotient and the next graded layer are regular, the quotient
        -- criterion upgrades regularity to the next power quotient.
        exact semilocal_denominator_isSMulRegular_pow_quotient_succ
          (R := R) (S := S) (𝔭 := 𝔭) (m := k + 1) d (ih d)
          (semilocal_denominator_layer_isSMulRegular_via_tensor_layer
            (R := R) (S := S) (𝔭 := 𝔭) (m := k + 1) d)
  exact hpow m c

/-- Helper for Chap10 Lemma 10 64 3: every denominator inverted in the iterated localization is already a
nonzerodivisor on the positive semilocal power quotient `Sₚ / J^n`. -/
lemma semilocal_denominator_nonZeroDivisors_pow_quotient
    {n : ℕ} (hn : 0 < n) :
    Algebra.algebraMapSubmonoid
        (Sₚ ⧸ (map (algebraMap S Sₚ) 𝔭S) ^ n)
        (Ideal.primeCompl (map (algebraMap S Sₚ) 𝔭S)) ≤
      nonZeroDivisors (Sₚ ⧸ (map (algebraMap S Sₚ) 𝔭S) ^ n) := by
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  intro y hy
  rcases (show ∃ c : Ideal.primeCompl J, algebraMap Sₚ (Sₚ ⧸ J ^ n) c = y by
      simpa [Algebra.algebraMapSubmonoid, Submonoid.mem_map, J] using hy) with ⟨c, rfl⟩
  -- Read quotient regularity as left-cancellation for multiplication by the quotient class of `c`.
  refine mem_nonZeroDivisors_iff_left.mpr ?_
  intro x hx
  have hx' : (c : Sₚ) • x = 0 := by
    rw [Algebra.smul_def]
    exact hx
  exact (semilocal_denominator_isSMulRegular_pow_quotient
    (R := R) (S := S) (𝔭 := 𝔭) hn c).right_eq_zero_of_smul hx'

/-- Helper for Chap10 Lemma 10 64 3: once denominators are regular on the semilocal power quotient, the
public comparison `Sₚ / J^n → S𝔮 / maximalIdeal(S𝔮)^n` is injective. -/
lemma semilocalPowQuotientToLocalPowQuotient_injective
    {n : ℕ} (hn : 0 < n) :
    Function.Injective
      (semilocalPowQuotientToLocalPowQuotient (R := R) (S := S) (𝔭 := 𝔭) n) := by
  let J : Ideal Sₚ := map (algebraMap S Sₚ) 𝔭S
  -- Route correction: the public quotient map now factors through the quotient of the explicit
  -- iterated-localization equivalence, so only the injectivity of the canonical localization
  -- quotient map remains.
  rw [← semilocalLocalizationAtMapPrimePowQuotient_factorization
    (R := R) (S := S) (𝔭 := 𝔭) n]
  refine (semilocalLocalizationAtMapPrimePowQuotientAlgEquiv
    (R := R) (S := S) (𝔭 := 𝔭) n).injective.comp ?_
  rw [semilocalPowQuotientToIteratedLocalPowQuotient_factorization_via_localization
    (R := R) (S := S) (𝔭 := 𝔭) n]
  refine (semilocalPowQuotientLocalizationAlgEquiv
    (R := R) (S := S) (𝔭 := 𝔭) n).injective.comp ?_
  -- Route correction: the remaining input is exactly the source-proof regularity statement saying
  -- denominators outside `J` are nonzerodivisors on `Sₚ / J^n`.
  exact IsLocalization.injective
    (M := Algebra.algebraMapSubmonoid
      (Sₚ ⧸ J ^ n)
      (Ideal.primeCompl J))
    (S := Localization
      (Algebra.algebraMapSubmonoid
        (Sₚ ⧸ J ^ n)
        (Ideal.primeCompl J)))
    (semilocal_denominator_nonZeroDivisors_pow_quotient
      (R := R) (S := S) (𝔭 := 𝔭) hn)

/-- Helper for Chap10 Lemma 10 64 3: once the semilocal-to-local quotient comparison is injective, the
reverse inclusion reduces to the two kernel descriptions already isolated above. -/
lemma symbolicPower_map_le_map_symbolicPower_of_semilocal_comparison_injective
    (n : ℕ)
    (hinj :
      Function.Injective
        (semilocalPowQuotientToLocalPowQuotient (R := R) (S := S) (𝔭 := 𝔭) n)) :
    symbolicPower 𝔭S n ≤ map (algebraMap R S) (𝔭.symbolicPower n) := by
  -- Rewrite the target symbolic power as the local quotient kernel.
  rw [symbolicPower_map_eq_ker_local_pow_quotient (𝔭 := 𝔭) n]
  -- Then descend that kernel across the injective semilocal-to-local comparison.
  rw [ker_local_pow_quotient_eq_ker_semilocal_pow_quotient_of_injective
    (𝔭 := 𝔭) n hinj]
  -- The remaining semilocal kernel is the flat base change of the defining kernel of `𝔭^(n)`.
  rw [← map_symbolicPower_eq_ker_semilocal_pow_quotient (𝔭 := 𝔭) n]

/-- Helper for Chap10 Lemma 10 64 3: the first symbolic power of a prime ideal is the prime ideal
itself. -/
lemma symbolicPower_one_eq_self : symbolicPower 𝔭 1 = 𝔭 := by
  -- Contracting the localized prime back to the original ring recovers the prime.
  simpa [Ideal.symbolicPower, pow_one] using
    (IsLocalization.comap_map_of_isPrime_disjoint (Ideal.primeCompl 𝔭) Rₚ
      (show 𝔭.IsPrime from inferInstance) <| by
        rw [Set.disjoint_left]
        intro x hxcompl hxmem
        exact hxcompl hxmem)

omit [Module.Flat R S] [𝔭.IsPrime] in
/-- Helper for Chap10 Lemma 10 64 3: the first symbolic power of the extended prime `𝔭S` is `𝔭S`
itself. -/
lemma symbolicPower_map_one_eq_self : symbolicPower 𝔭S 1 = 𝔭S := by
  -- The same contraction argument applies after passing to the prime `𝔭S` of `S`.
  simpa [Ideal.symbolicPower, pow_one] using
    (IsLocalization.comap_map_of_isPrime_disjoint (Ideal.primeCompl 𝔭S) S𝔮
      (show (𝔭.map (algebraMap R S)).IsPrime from inferInstance) <| by
        rw [Set.disjoint_left]
        intro x hxcompl hxmem
        exact hxcompl hxmem)

omit [Module.Flat R S] [𝔭.IsPrime] in
/-- Helper for Chap10 Lemma 10 64 3: after localizing at `𝔭S`, the symbolic power of `𝔭S` becomes the
ordinary power of the maximal ideal. -/
lemma symbolicPower_map_localized_eq_pow_maximalIdeal (n : ℕ) :
    map (algebraMap S S𝔮) (symbolicPower 𝔭S n) = IsLocalRing.maximalIdeal S𝔮 ^ n := by
  -- This is the defining contraction formula for symbolic powers, pushed to the local ring.
  simpa [Ideal.symbolicPower, Localization.AtPrime.map_eq_maximalIdeal] using
    (IsLocalization.map_comap (Ideal.primeCompl 𝔭S) S𝔮
      ((map (algebraMap S S𝔮) 𝔭S) ^ n))

/-- Helper for Chap10 Lemma 10 64 3: after localizing at `𝔭S`, the extension of `𝔭^(n)` becomes the
same `n`th power of the maximal ideal. -/
lemma map_symbolicPower_localized_eq_pow_maximalIdeal (n : ℕ) :
    map (algebraMap S S𝔮) (map (algebraMap R S) (𝔭.symbolicPower n)) =
      IsLocalRing.maximalIdeal S𝔮 ^ n := by
  let h𝔮 : Ideal.LiesOver 𝔭S 𝔭 := map_prime_lies_over_of_flat (𝔭 := 𝔭)
  let f : Rₚ →+* S𝔮 := Localization.localRingHom 𝔭 𝔭S (algebraMap R S) h𝔮.over
  have hcomp : f.comp (algebraMap R Rₚ) = algebraMap R S𝔮 := by
    ext x
    exact Localization.localRingHom_to_map 𝔭 𝔭S (algebraMap R S) h𝔮.over x
  have hsource : map (algebraMap R Rₚ) (𝔭.symbolicPower n) = IsLocalRing.maximalIdeal Rₚ ^ n := by
    -- Localizing the defining contraction of `𝔭^(n)` recovers the ordinary power in `R_𝔭`.
    simpa [Ideal.symbolicPower, Localization.AtPrime.map_eq_maximalIdeal] using
      (IsLocalization.map_comap (Ideal.primeCompl 𝔭) Rₚ
        ((map (algebraMap R Rₚ) 𝔭) ^ n))
  have hmax : map f (IsLocalRing.maximalIdeal Rₚ) = IsLocalRing.maximalIdeal S𝔮 := by
    -- The local-ring map sends the maximal ideal of `R_𝔭` to the maximal ideal of `S_𝔮`.
    calc
      map f (IsLocalRing.maximalIdeal Rₚ)
          = map (algebraMap R S𝔮) 𝔭 := by
              rw [← Localization.AtPrime.map_eq_maximalIdeal (I := 𝔭), Ideal.map_map, hcomp]
      _ = map (algebraMap S S𝔮) 𝔭S := by
            rw [IsScalarTower.algebraMap_eq R S S𝔮, Ideal.map_map]
      _ = IsLocalRing.maximalIdeal S𝔮 := by
            simpa using (Localization.AtPrime.map_eq_maximalIdeal (I := 𝔭S))
  calc
    map (algebraMap S S𝔮) (map (algebraMap R S) (𝔭.symbolicPower n))
        = map (algebraMap R S𝔮) (𝔭.symbolicPower n) := by
            rw [IsScalarTower.algebraMap_eq R S S𝔮, Ideal.map_map]
    _ = map f (map (algebraMap R Rₚ) (𝔭.symbolicPower n)) := by
          rw [← hcomp, Ideal.map_map]
    _ = map f (IsLocalRing.maximalIdeal Rₚ ^ n) := by rw [hsource]
    _ = (map f (IsLocalRing.maximalIdeal Rₚ)) ^ n := by rw [Ideal.map_pow]
    _ = IsLocalRing.maximalIdeal S𝔮 ^ n := by rw [hmax]

/-- Helper for Chap10 Lemma 10 64 3: in a local ring, the symbolic powers of the maximal ideal agree
with its ordinary powers. -/
lemma symbolicPower_maximalIdeal_eq_pow_of_local
    (A : Type*) [CommRing A] [IsLocalRing A] (n : ℕ) :
    symbolicPower (IsLocalRing.maximalIdeal A) n = IsLocalRing.maximalIdeal A ^ n := by
  let m : Ideal A := IsLocalRing.maximalIdeal A
  letI : m.IsPrime := by
    simpa [m] using (show (IsLocalRing.maximalIdeal A).IsPrime from inferInstance)
  let e : Localization.AtPrime m ≃ₐ[A] A := by
    have h_units : m.primeCompl ≤ IsUnit.submonoid A := by
      intro x hx
      -- Outside the maximal ideal, a local-ring element is a unit.
      simpa [m, Ideal.mem_primeCompl_iff, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff,
        Classical.not_not] using hx
    letI : IsLocalization m.primeCompl A := IsLocalization.self h_units
    exact IsLocalization.algEquiv m.primeCompl (Localization.AtPrime m) A
  have hsymm : e.symm.toRingHom = algebraMap A (Localization.AtPrime m) := by
    ext x
    simpa [m] using (AlgEquiv.commutes e.symm x)
  have hcomp : e.toRingHom.comp e.symm.toRingHom = RingHom.id A := by
    -- The algebra equivalence is inverse to its symmetry on the nose.
    ext x
    exact e.apply_symm_apply x
  have hmap_pow : map e.symm.toRingHom (m ^ n) = comap e.toRingHom (m ^ n) := by
    simpa using (Ideal.map_comap_of_equiv (I := m ^ n) e.symm.toRingEquiv)
  -- Transport the defining symbolic-power ideal through the self-localization equivalence.
  calc
    symbolicPower m n
        = comap (algebraMap A (Localization.AtPrime m))
            (map (algebraMap A (Localization.AtPrime m)) (m ^ n)) := by
              simp [Ideal.symbolicPower, Ideal.map_pow]
    _ = comap e.symm.toRingHom (map e.symm.toRingHom (m ^ n)) := by
          rw [hsymm]
    _ = comap e.symm.toRingHom (comap e.toRingHom (m ^ n)) := by
          rw [hmap_pow]
    _ = comap (e.toRingHom.comp e.symm.toRingHom) (m ^ n) := by
          rw [Ideal.comap_comap]
    _ = m ^ n := by
          rw [hcomp]
          rfl

omit [Module.Flat R S] [(𝔭.map (algebraMap R S)).IsPrime] in
/-- Helper for Chap10 Lemma 10 64 3: the `n`th ordinary power of the extended prime is contained in the
extension of the `n`th symbolic power. -/
lemma map_prime_pow_le_map_symbolicPower (n : ℕ) :
    𝔭S ^ n ≤ map (algebraMap R S) (𝔭.symbolicPower n) := by
  -- First compare the ordinary power with the symbolic power in `R`, then extend to `S`.
  calc
    𝔭S ^ n = map (algebraMap R S) (𝔭 ^ n) := by
      rw [Ideal.map_pow]
    _ ≤ map (algebraMap R S) (𝔭.symbolicPower n) := by
      exact Ideal.map_mono <| by
        -- The symbolic power is the contraction of `(𝔭Rₚ)^n`, so it contains `𝔭^n`.
        simpa [Ideal.symbolicPower, Ideal.map_pow] using
          (Ideal.le_comap_map : 𝔭 ^ n ≤ comap (algebraMap R Rₚ) (map (algebraMap R Rₚ) (𝔭 ^ n)))

/-- Helper for Chap10 Lemma 10 64 3: for positive `n`, the extended symbolic power `𝔭^(n)S` is
contained in the symbolic power of the extended prime `𝔭S`. -/
lemma map_symbolicPower_le_symbolicPower_map {n : ℕ} (hn : 0 < n) :
    map (algebraMap R S) (𝔭.symbolicPower n) ≤ symbolicPower 𝔭S n := by
  have hloc :
      map (algebraMap S S𝔮) (map (algebraMap R S) (𝔭.symbolicPower n)) =
        map (algebraMap S S𝔮) (symbolicPower 𝔭S n) := by
    -- Both ideals become the same maximal-ideal power after localizing at `𝔭S`.
    rw [map_symbolicPower_localized_eq_pow_maximalIdeal (𝔭 := 𝔭),
      symbolicPower_map_localized_eq_pow_maximalIdeal (𝔭 := 𝔭)]
  have hdisj : Disjoint ((Ideal.primeCompl 𝔭S) : Set S) (symbolicPower 𝔭S n) := by
    -- A positive symbolic power is contained in its prime radical, so it misses `𝔭S.primeCompl`.
    rw [Set.disjoint_left]
    intro x hxcompl hxmem
    have hxrad : x ∈ radical (symbolicPower 𝔭S n) := Ideal.le_radical hxmem
    have hxprime : x ∈ 𝔭S := by
      simpa [Ideal.radical_symbolicPower (𝔭 := 𝔭S) hn] using hxrad
    exact hxcompl hxprime
  have hcomap :
      comap (algebraMap S S𝔮) (map (algebraMap S S𝔮) (symbolicPower 𝔭S n)) =
        symbolicPower 𝔭S n := by
    -- The right-hand symbolic power is `𝔭S`-primary, so localization away from `𝔭S` does not
    -- change its contraction back to `S`.
    simpa using
      (IsLocalization.comap_map_of_isPrimary_disjoint (Ideal.primeCompl 𝔭S) S𝔮
        (Ideal.symbolicPower_isPrimary (𝔭 := 𝔭S) hn) hdisj)
  rw [← hcomap]
  exact (Ideal.map_le_iff_le_comap).mp (le_of_eq hloc)

/-- Consequence for Chap10 Lemma 10 64 3: for a flat ring map `R → S`, if the extension `𝔭S` of a prime ideal `𝔭 ⊂ R`
is prime in `S`, then extending the `n`th symbolic power of `𝔭` to `S` gives the `n`th symbolic
power of `𝔭S`. -/
@[stacks 0BC0]
theorem map_symbolicPower_eq_symbolicPower_map (n : ℕ)
    : map (algebraMap R S) (𝔭.symbolicPower n) = symbolicPower 𝔭S n := by
  by_cases hn : n = 0
  · -- At level `0`, both symbolic powers are the unit ideal by definition.
    subst hn
    calc
      map (algebraMap R S) (𝔭.symbolicPower 0) = map (algebraMap R S) ⊤ := by
        simp [Ideal.symbolicPower]
      _ = ⊤ := by simpa using (Ideal.map_top (f := algebraMap R S))
      _ = symbolicPower 𝔭S 0 := by
        simp [Ideal.symbolicPower]
  · by_cases h1 : n = 1
    · -- At level `1`, symbolic powers are just the prime ideals themselves.
      subst h1
      rw [symbolicPower_one_eq_self (𝔭 := 𝔭),
        symbolicPower_map_one_eq_self (R := R) (S := S) (𝔭 := 𝔭)]
    · have hn' : 0 < n := Nat.pos_of_ne_zero hn
      apply le_antisymm
      · -- The easy direction already descends from localization because the right-hand side is
        -- primary away from `𝔭S`.
        exact map_symbolicPower_le_symbolicPower_map (𝔭 := 𝔭) hn'
      · -- Route correction: the remaining direction is the source-proof injectivity step for
        -- `S / 𝔭^(n)S → S_𝔮 / 𝔭^n S_𝔮`, now factored through the explicit semilocal comparison
        -- `Sₚ ⧸ J^n → S𝔮 ⧸ maximalIdeal(S𝔮)^n`.
        have hinj :
            Function.Injective
              (semilocalPowQuotientToLocalPowQuotient (R := R) (S := S) (𝔭 := 𝔭) n) := by
          -- The localization packaging is now explicit; the only remaining source-faithful input
          -- is regularity of denominators on the semilocal power quotient.
          exact semilocalPowQuotientToLocalPowQuotient_injective
            (R := R) (S := S) (𝔭 := 𝔭) hn'
        exact symbolicPower_map_le_map_symbolicPower_of_semilocal_comparison_injective
          (𝔭 := 𝔭) n hinj

end Ideal

end
