import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open scoped TensorProduct

universe u v

section

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]

/- Domain-style sampling for Lemma 10.151.4:
- primary domain: unramified commutative algebra through the tensor-product multiplication map and
  localization away from an idempotent;
- sampled owner declarations:
  `KaehlerDifferential.ideal`,
  `Ideal.cotangent_subsingleton_iff`,
  `Ideal.isIdempotentElem_iff_of_fg`,
  `IsLocalization.Away`;
- best owner abstraction: the cotangent ideal
  `KaehlerDifferential.ideal R S = ker(TensorProduct.lmul' R)`, whose cotangent quotient controls
  formal unramifiedness and whose finitely generated idempotent form yields the desired
  localization;
- primitive data: the unramified `R`-algebra `S` and the tensor-product multiplication algebra
  structure on `S`;
- derived API: the idempotent generator of `ker(TensorProduct.lmul' R)` and the resulting
  localization statement.

Source/core/bridge triage:
- `source-facing`: the textbook existence of an idempotent cutting out the diagonal for an
  unramified map;
- `core/canonical`: `KaehlerDifferential.ideal R S` together with
  `Ideal.cotangent_subsingleton_iff` and `Ideal.isIdempotentElem_iff_of_fg`;
- `bridge/view`: identifying the cotangent ideal with the kernel of `TensorProduct.lmul' R` and
  translating the resulting idempotent-generator statement into `IsLocalization.Away`. -/

-- Proof sketch: let `J = ker(S ⊗[R] S → S)` for the tensor-product multiplication map. Since
-- `R → S` is unramified, it is formally unramified and finite type, so Lemma `10.131.13` gives
-- `J / J^2 = 0`, hence `J = J^2`, and finite type shows `J` is finitely generated by the
-- elements `xᵢ ⊗ 1 - 1 ⊗ xᵢ`. Apply Lemma `10.21.5` to write `J = (1 - e)` for an idempotent
-- `e`, then identify the quotient by `J` with `S` and the quotient by `(1 - e)` with the
-- localization away from `e`.
/-- Lemma 10.151.4: if `R → S` is unramified, then after identifying `S` as an
`S ⊗[R] S`-algebra via the tensor-product multiplication map, there exists an idempotent
`e ∈ S ⊗[R] S` such that `S` is the localization of `S ⊗[R] S` away from `e`. -/
@[stacks 02FL]
theorem exists_idempotent_tensorProduct_self_isLocalization_of_unramified
    [Algebra.Unramified R S] :
    ∃ e : S ⊗[R] S, IsIdempotentElem e ∧
      letI : Algebra (S ⊗[R] S) S := (Algebra.TensorProduct.lmul' R).toRingHom.toAlgebra
      IsLocalization.Away e S := by
  letI : Algebra (S ⊗[R] S) S := (Algebra.TensorProduct.lmul' R).toRingHom.toAlgebra
  let I : Ideal (S ⊗[R] S) := KaehlerDifferential.ideal R S
  have hI : IsIdempotentElem I := by
    rw [← Ideal.cotangent_subsingleton_iff]
    change Subsingleton (KaehlerDifferential R S)
    exact (Algebra.formallyUnramified_iff R S).mp inferInstance
  have hfg : I.FG := by
    simpa [I] using KaehlerDifferential.ideal_fg R S
  obtain ⟨u, hu, hker⟩ := (Ideal.isIdempotentElem_iff_of_fg I hfg).mp hI
  refine ⟨1 - u, hu.one_sub, ?_⟩
  refine IsLocalization.away_of_isIdempotentElem hu.one_sub ?_ fun s ↦ ⟨1 ⊗ₜ[R] s, by
    change (Algebra.TensorProduct.lmul' R) (1 ⊗ₜ[R] s) = s
    simp⟩
  change RingHom.ker (Algebra.TensorProduct.lmul' R).toRingHom = Ideal.span {1 - (1 - u)}
  simpa [I, sub_sub_cancel] using hker

end
