import Mathlib
import stacks_proof.stacks_project.Chap10.Definition_10_160_1
import stacks_proof.stacks_project.Chap10.Definition_10_160_4
import stacks_proof.stacks_project.Chap10.Definition_10_160_5
import stacks_proof.stacks_project.Chap10.Lemma_10_160_6
import stacks_proof.stacks_project.Chap10.Lemma_10_160_7

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open IsLocalRing

section

variable (R : Type u) [CommRing R] [IsCompleteLocalRing R]

/- Domain-style sampling:
* primary domain: Cohen structure and finite-variable formal power series presentations of complete
  local rings.
* source/core/bridge triage:
  - `source-facing`: the textbook quotient presentation of `R` by a finite-variable power series
    ring over either a field or a Cohen ring;
  - `core/canonical`: `MvPowerSeries σ A` with `[Finite σ]`, together with the chapter owners
    `IsCoefficientRing` and `IsCohenRing`;
  - `bridge/view`: the quotient presentation obtained from a surjective power-series map via
    `RingHom.quotientKerEquivOfSurjective`.
* sampled owner declarations:
  `IsCoefficientRing`,
  `IsCohenRing`,
  `isNoetherianRing_mvPowerSeries_of_finite`,
  `RingHom.quotientKerEquivOfSurjective`.
* best owner abstraction: the finite-index power series ring `MvPowerSeries σ A` is the canonical
  owner for “formal power series in finitely many variables”; the quotient model is derived API
  from a surjective map out of that owner.
* primitive data: a finite index type `σ`, a coefficient field or Cohen ring, and a surjective
  ring homomorphism `MvPowerSeries σ _ →+* R`.
* derived API: the ideal-kernel quotient presentation.
-/

-- Proof sketch: choose a coefficient ring `Λ₀ ⊆ R`. If the residue field has characteristic zero,
-- `Λ₀` is a field and the chosen generators of `maximalIdeal R` define a surjective map
-- `MvPowerSeries σ Λ₀ →+* R` for a finite index type `σ`; passing to the kernel identifies `R`
-- with the corresponding
-- quotient. In positive residue characteristic, pick a Cohen ring mapping into `R` via the
-- coefficient-ring construction and argue in the same way.
/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a coefficient ring is a field
when the ambient residue characteristic is zero. -/
private theorem coefficientRing_isField_of_residueChar_zero
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ]
    (hchar : ringChar (ResidueField R) = 0) : IsField Λ := by
  -- The coefficient-ring maximal ideal is generated by the residue characteristic, which is `0`
  -- in the equal-characteristic branch.
  have hmax : maximalIdeal Λ = ⊥ := by
    rw [hΛ.maximalIdeal_eq_span_residueChar, hchar]
    simp
  -- A local ring with zero maximal ideal is a field.
  exact IsLocalRing.isField_iff_maximalIdeal_eq.mpr hmax

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a finite generating family for
`maximalIdeal R` can be used as a finite variable set. -/
private theorem finiteMaximalIdealGeneratingFamily
    (hfg : (maximalIdeal R).FG) :
    ∃ (σ : Type u) (_ : Finite σ) (x : σ → R),
      (∀ i, x i ∈ maximalIdeal R) ∧ Ideal.span (Set.range x) = maximalIdeal R := by
  -- Unpack finite generation as a finite set whose span is the maximal ideal.
  rcases hfg with ⟨s, hs⟩
  refine ⟨s, inferInstance, (fun i : s ↦ (i : R)), ?_, ?_⟩
  · intro i
    -- Each chosen generator lies in the span, hence in the maximal ideal after rewriting by `hs`.
    have hmem : (i : R) ∈ Ideal.span (↑s : Set R) := Ideal.subset_span i.2
    simpa [hs] using hmem
  · -- The range of the subtype projection is exactly the original finite set.
    have hrange : Set.range (fun i : s ↦ (i : R)) = (↑s : Set R) := by
      ext y
      constructor
      · rintro ⟨i, rfl⟩
        exact i.2
      · intro hy
        exact ⟨⟨y, hy⟩, rfl⟩
    simpa [hrange, hs]

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: in positive residue
characteristic there is a Cohen ring with residue field `ResidueField R`. -/
private theorem existsCohenRingResidueFieldSource
    (hchar : ringChar (ResidueField R) ≠ 0) :
    ∃ (Λ : Type u) (_ : CommRing Λ) (_ : IsCohenRing Λ),
      Nonempty (ResidueField Λ ≃+* ResidueField R) := by
  -- The residue-field characteristic supplies the prime used by the Cohen-ring existence theorem.
  let p := ringChar (ResidueField R)
  have hpPrime : Nat.Prime p := CharP.char_prime_of_ne_zero (ResidueField R) hchar
  letI : Fact p.Prime := ⟨hpPrime⟩
  letI : CharP (ResidueField R) p := ringChar.of_eq rfl
  exact existsCohenRingWithResidueFieldRingEquiv p (ResidueField R)

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: every power of the residue
characteristic lies in the corresponding power of the maximal ideal. -/
private theorem residueCharPow_mem_maximalIdealPow
    {S : Type u} [CommRing S] [IsLocalRing S] (n : ℕ) :
    ((ringChar (ResidueField S) : S) ^ n) ∈ (maximalIdeal S) ^ n := by
  -- First detect the residue characteristic as zero in the residue field, hence as an element of
  -- the maximal ideal of the local ring.
  have hpzero : IsLocalRing.residue S (ringChar (ResidueField S) : S) = 0 := by
    change ((ringChar (ResidueField S) : ℕ) : ResidueField S) = 0
    exact (ringChar.spec (ResidueField S) (ringChar (ResidueField S))).2 dvd_rfl
  have hpmem : (ringChar (ResidueField S) : S) ∈ maximalIdeal S := by
    change Ideal.Quotient.mk (maximalIdeal S) (ringChar (ResidueField S) : S) = 0 at hpzero
    exact Ideal.Quotient.eq_zero_iff_mem.mp hpzero
  -- Powers preserve membership in matching ideal powers.
  exact Ideal.pow_mem_pow hpmem n

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the residue-field map of a
coefficient-ring inclusion can be upgraded to a ring equivalence. -/
private theorem coefficientRingResidueFieldEquiv
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ] :
    Nonempty (ResidueField Λ ≃+* ResidueField R) := by
  -- The coefficient-ring hypothesis already stores bijectivity of the residue-field map.
  exact ⟨RingEquiv.ofBijective (ResidueField.map (Λ.subtype : Λ →+* R))
    hΛ.residueField_bijective⟩

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: powers of the maximal ideal in a
coefficient ring are generated by powers of the ambient residue characteristic. -/
private theorem coefficientRing_maximalIdeal_pow_eq_span_residueChar_pow
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ] (n : ℕ) :
    (maximalIdeal Λ) ^ n =
      Ideal.span ({((ringChar (ResidueField R) : Λ) ^ n)} : Set Λ) := by
  -- Rewrite the maximal ideal to its principal generator and use the singleton-span power formula.
  rw [hΛ.maximalIdeal_eq_span_residueChar, Ideal.span_singleton_pow]

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the transition ideal
`K^n / K^(n+1)` has square zero for positive `n`. -/
private theorem quotient_pow_transition_square_zero
    {A : Type*} [CommRing A] (K : Ideal A) {n : ℕ} (hn : 0 < n) :
    (Ideal.map (Ideal.Quotient.mk (K ^ (n + 1))) (K ^ n)) ^ 2 = ⊥ := by
  -- The square is the image of `K^(2n)`, which is killed modulo `K^(n+1)`.
  rw [pow_two, ← Ideal.map_mul, ← pow_add]
  have hle : n + 1 ≤ n + n := by
    omega
  exact eq_bot_mono
    (Ideal.map_mono (Ideal.pow_le_pow_right hle))
    (Ideal.map_quotient_self _)

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the kernel of a positive
successive power-quotient transition is nilpotent. -/
private theorem factorPow_kernel_isNilpotent
    {A : Type*} [CommRing A] (K : Ideal A) {n : ℕ} (hn : 0 < n) :
    IsNilpotent (RingHom.ker (Ideal.Quotient.factorPow K (Nat.le_succ n))) := by
  -- Identify the kernel with the square-zero transition ideal.
  refine ⟨2, ?_⟩
  rw [show
      RingHom.ker (Ideal.Quotient.factorPow K (Nat.le_succ n)) =
        Ideal.map (Ideal.Quotient.mk (K ^ (n + 1))) (K ^ n) by
    simpa [Ideal.Quotient.factorPow] using
      (Ideal.Quotient.factor_ker (I := K ^ (n + 1)) (J := K ^ n)
        (Ideal.pow_le_pow_right (Nat.le_succ n)))]
  exact quotient_pow_transition_square_zero K hn

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the residue characteristic of a
coefficient ring agrees with that of the ambient complete local ring. -/
private theorem coefficientRing_residueField_ringChar_eq
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ] :
    ringChar (ResidueField Λ) = ringChar (ResidueField R) := by
  -- The coefficient-ring inclusion induces an injective residue-field map, so it transports the
  -- characteristic of the ambient residue field back to the coefficient residue field.
  rw [ringChar.eq_iff]
  exact (ResidueField.map (Λ.subtype : Λ →+* R)).charP hΛ.residueField_bijective.1 _

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a prescribed residue-field
equivalence aligns the Cohen source characteristic with the ambient coefficient-ring one. -/
private theorem cohenCoefficient_residueChar_eq
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) :
    ringChar (ResidueField C) = ringChar (ResidueField R) := by
  -- First transport across the chosen residue-field equivalence, then across the coefficient
  -- inclusion into the ambient complete local ring.
  calc
    ringChar (ResidueField C) = ringChar (ResidueField Λ₀) := by
      rw [ringChar.eq_iff]
      exact e.toRingHom.charP e.injective _
    _ = ringChar (ResidueField R) :=
      coefficientRing_residueField_ringChar_eq (R := R) (Λ := Λ₀)

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the ambient residue
characteristic power vanishes in the matching coefficient-ring quotient. -/
private theorem coefficientRing_residueChar_pow_quotient_eq_zero
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ] (n : ℕ) :
    (((ringChar (ResidueField R)) ^ n : ℕ) : Λ ⧸ (maximalIdeal Λ) ^ n) = 0 := by
  -- The coefficient-ring maximal ideal is generated by the ambient residue characteristic; its
  -- `n`-th power therefore kills the corresponding `n`-th quotient.
  rw [Nat.cast_pow]
  change Ideal.Quotient.mk ((maximalIdeal Λ) ^ n)
      (((ringChar (ResidueField R) : Λ) ^ n)) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  rw [coefficientRing_maximalIdeal_pow_eq_span_residueChar_pow (R := R) (Λ := Λ) n]
  exact Ideal.subset_span (by simp)

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the first positive quotient map
is exactly the prescribed residue-field equivalence, viewed as a map to `Λ₀ / m`. -/
private theorem cohenLiftResidueQuotientMap
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) :
    ∃ g : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (1 : ℕ),
      g = ((Ideal.quotEquivOfEq
        (by simp [pow_one] : maximalIdeal Λ₀ = (maximalIdeal Λ₀) ^ (1 : ℕ))).toRingHom).comp
          (e.toRingHom.comp (IsLocalRing.residue C)) := by
  -- The base stage is just the residue map of `C`, followed by the chosen equivalence and the
  -- definitional identification of `m` with `m^1`.
  refine ⟨_, rfl⟩

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: compatibility with a residue-field
equivalence makes a ring map local and gives a bijective induced residue-field map. -/
private theorem exists_isLocalHom_and_residueFieldMap_bijective_of_residue_compat
    {C : Type u} [CommRing C] [IsLocalRing C]
    {S : Type u} [CommRing S] [IsLocalRing S]
    (ψ : C →+* S) (e : ResidueField C ≃+* ResidueField S)
    (hψ : (IsLocalRing.residue S).comp ψ = e.toRingHom.comp (IsLocalRing.residue C)) :
    ∃ (_ : IsLocalHom ψ), Function.Bijective (ResidueField.map ψ) := by
  -- The residue compatibility detects units: if `ψ a` is a unit, then its residue is nonzero,
  -- hence the residue of `a` is nonzero and `a` is not in the maximal ideal.
  have hlocal : IsLocalHom ψ := by
    refine ⟨?_⟩
    intro a ha
    rw [← IsLocalRing.notMem_maximalIdeal]
    intro ham
    have hresC : IsLocalRing.residue C a = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr ham
    have hresS : IsLocalRing.residue S (ψ a) = 0 := by
      calc
        IsLocalRing.residue S (ψ a) = ((IsLocalRing.residue S).comp ψ) a := rfl
        _ = (e.toRingHom.comp (IsLocalRing.residue C)) a := by rw [hψ]
        _ = 0 := by simp [hresC]
    have hresS_ne_zero : IsLocalRing.residue S (ψ a) ≠ 0 :=
      isUnit_iff_ne_zero.mp (IsUnit.map (IsLocalRing.residue S) ha)
    exact hresS_ne_zero hresS
  refine ⟨hlocal, ?_⟩
  letI : IsLocalHom ψ := hlocal
  -- With locality installed, the induced residue-field map agrees with the chosen equivalence on
  -- representatives, and therefore is bijective.
  have hmap : ResidueField.map ψ = e.toRingHom := by
    ext y
    rcases IsLocalRing.residue_surjective y with ⟨a, rfl⟩
    rw [IsLocalRing.ResidueField.map_residue]
    exact RingHom.congr_fun hψ a
  rw [hmap]
  exact e.bijective

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: any stage map to a coefficient
quotient kills the next source residue-characteristic power. -/
private theorem cohenLift_kills_residueChar_pow
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) (n : ℕ)
    (g : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1)) :
    Ideal.span ({((ringChar (ResidueField C) : C) ^ (n + 2))} : Set C) ≤ RingHom.ker g := by
  -- The residue-characteristic equality changes the Cohen source power into the ambient
  -- coefficient-ring power, which is already deep enough in the coefficient-ring filtration.
  rw [Ideal.span_le]
  intro x hx
  rw [Set.mem_singleton_iff] at hx
  rw [hx]
  change g ((ringChar (ResidueField C) : C) ^ (n + 2)) = 0
  rw [map_pow, map_natCast]
  have hchar := cohenCoefficient_residueChar_eq (R := R) (C := C) (Λ₀ := Λ₀) e
  have hmemGen :
      ((ringChar (ResidueField R) : Λ₀) ^ (n + 1)) ∈ (maximalIdeal Λ₀) ^ (n + 1) := by
    rw [coefficientRing_maximalIdeal_pow_eq_span_residueChar_pow
      (R := R) (Λ := Λ₀) (n := n + 1)]
    exact Ideal.subset_span (by simp)
  have hmem : ((ringChar (ResidueField R) : Λ₀) ^ (n + 2)) ∈
      (maximalIdeal Λ₀) ^ (n + 1) := by
    have hmul : ((ringChar (ResidueField R) : Λ₀) ^ (n + 1)) *
        (ringChar (ResidueField R) : Λ₀) ∈ (maximalIdeal Λ₀) ^ (n + 1) :=
      Ideal.mul_mem_right _ _ hmemGen
    simpa [show n + 2 = n + 1 + 1 by omega, pow_succ] using hmul
  change Ideal.Quotient.mk ((maximalIdeal Λ₀) ^ (n + 1))
      (((ringChar (ResidueField C) : ℕ) : Λ₀) ^ (n + 2)) = 0
  rw [hchar]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr hmem

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: stage maps factor through the
Cohen source quotient by the next residue-characteristic power. -/
private theorem cohenLift_factor_through_source_quotient
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) (n : ℕ)
    (g : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1)) :
    ∃ qg : C ⧸ Ideal.span ({((ringChar (ResidueField C) : C) ^ (n + 2))} : Set C) →+*
        Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1),
      qg.comp (Ideal.Quotient.mk _) = g := by
  -- The source power-killing lemma supplies exactly the kernel containment required by the
  -- quotient universal property.
  refine ⟨Ideal.Quotient.lift _ g ?_, ?_⟩
  · exact cohenLift_kills_residueChar_pow (R := R) (C := C) (Λ₀ := Λ₀) e n g
  · ext x
    rfl

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a ring homomorphism between
`ZMod N`-algebras automatically respects the `ZMod N`-algebra maps. -/
private theorem zmodAlgebraMap_commutes_of_ringHom
    {N : ℕ} {A B : Type u} [CommRing A] [CommRing B]
    [Algebra (ZMod N) A] [Algebra (ZMod N) B] (f : A →+* B) :
    ∀ z : ZMod N, f ((algebraMap (ZMod N) A) z) = (algebraMap (ZMod N) B) z := by
  -- Ring maps out of `ZMod N` are unique, so the two scalar maps into `B` coincide.
  intro z
  have h : f.comp (algebraMap (ZMod N) A) = algebraMap (ZMod N) B := by
    exact RingHom.ext_zmod _ _
  exact RingHom.congr_fun h z

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: higher residue-characteristic
powers vanish in shallower coefficient-ring quotients. -/
private theorem coefficientQuotient_residueChar_pow_eq_zero_of_le
    {Λ : Subring R} [hΛ : IsCoefficientRing R Λ] {a b : ℕ} (hab : a ≤ b) :
    (((ringChar (ResidueField R)) ^ b : ℕ) : Λ ⧸ (maximalIdeal Λ)^a) = 0 := by
  -- The coefficient-ring maximal ideal is generated by the residue characteristic, so `p^b`
  -- lies in the principal ideal generated by `p^a` whenever `a ≤ b`.
  rw [Nat.cast_pow]
  change Ideal.Quotient.mk ((maximalIdeal Λ)^a)
      (((ringChar (ResidueField R) : Λ) ^ b)) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  rw [coefficientRing_maximalIdeal_pow_eq_span_residueChar_pow (R := R) (Λ := Λ) a]
  rw [Ideal.mem_span_singleton]
  refine ⟨(ringChar (ResidueField R) : Λ) ^ (b - a), ?_⟩
  rw [← pow_add]
  congr
  omega

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a Cohen stage map lifts across
one positive coefficient-ring power quotient. -/
private theorem cohenLiftQuotientStep
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) (n : ℕ)
    (g : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1)) :
    ∃ gnext : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 2),
      (Ideal.Quotient.factorPow (maximalIdeal Λ₀) (Nat.le_succ (n + 1))).comp gnext = g := by
  -- Route correction: exact target `CharP` instances are stronger than needed. It suffices to
  -- install `ZMod`-algebra structures from the vanishing of the source power in the two target
  -- quotients and then use formal smoothness of the Cohen source quotient.
  let N : ℕ := ringChar (ResidueField C) ^ (n + 2)
  let I : Ideal C :=
    Ideal.span ({((ringChar (ResidueField C) : C) ^ (n + 2))} : Set C)
  let K : Ideal Λ₀ := maximalIdeal Λ₀
  rcases cohenLift_factor_through_source_quotient (R := R) (C := C) (Λ₀ := Λ₀) e n g with
    ⟨qg, hqg⟩
  have hchar := cohenCoefficient_residueChar_eq (R := R) (C := C) (Λ₀ := Λ₀) e
  have hzeroPrev : ((N : ℕ) : Λ₀ ⧸ K ^ (n + 1)) = 0 := by
    dsimp [N, K]
    rw [hchar]
    exact coefficientQuotient_residueChar_pow_eq_zero_of_le (R := R) (Λ := Λ₀)
      (by omega : n + 1 ≤ n + 2)
  have hzeroNext : ((N : ℕ) : Λ₀ ⧸ K ^ (n + 2)) = 0 := by
    dsimp [N, K]
    rw [hchar]
    exact coefficientQuotient_residueChar_pow_eq_zero_of_le (R := R) (Λ := Λ₀)
      (by omega : n + 2 ≤ n + 2)
  letI : Algebra (ZMod N) (Λ₀ ⧸ K ^ (n + 1)) :=
    RingHom.toAlgebra (ZMod.castHom (ringChar.dvd hzeroPrev) (Λ₀ ⧸ K ^ (n + 1)))
  letI : Algebra (ZMod N) (Λ₀ ⧸ K ^ (n + 2)) :=
    RingHom.toAlgebra (ZMod.castHom (ringChar.dvd hzeroNext) (Λ₀ ⧸ K ^ (n + 2)))
  have hpos : 0 < n + 2 := by omega
  letI : Algebra (ZMod N) (C ⧸ I) := by
    dsimp [N, I]
    exact quotientResidueCharPowAlgebra (Λ := C) ⟨n + 2, hpos⟩
  letI : Algebra.FormallySmooth (ZMod N) (C ⧸ I) := by
    dsimp [N, I]
    exact cohenRing_zmodPow_quotient_formallySmooth (Λ := C) ⟨n + 2, hpos⟩
  let qgAlg : C ⧸ I →ₐ[ZMod N] Λ₀ ⧸ K ^ (n + 1) :=
    { qg with commutes' := zmodAlgebraMap_commutes_of_ringHom qg }
  let factor : Λ₀ ⧸ K ^ (n + 2) →+* Λ₀ ⧸ K ^ (n + 1) :=
    Ideal.Quotient.factorPow K (Nat.le_succ (n + 1))
  let factorAlg : Λ₀ ⧸ K ^ (n + 2) →ₐ[ZMod N] Λ₀ ⧸ K ^ (n + 1) :=
    { factor with commutes' := zmodAlgebraMap_commutes_of_ringHom factor }
  have hsurj : Function.Surjective factorAlg := by
    dsimp [factorAlg, factor]
    exact Ideal.Quotient.factor_surjective
      (Ideal.pow_le_pow_right (Nat.le_succ (n + 1)))
  have hnil : IsNilpotent (RingHom.ker factorAlg.toRingHom) := by
    dsimp [factorAlg, factor]
    exact factorPow_kernel_isNilpotent (K := K) (n := n + 1) (hn := Nat.succ_pos n)
  let lift : C ⧸ I →ₐ[ZMod N] Λ₀ ⧸ K ^ (n + 2) :=
    Algebra.FormallySmooth.liftOfSurjective qgAlg factorAlg hsurj hnil
  -- Composing the formal-smoothness lift with the source quotient map gives the next stage, and
  -- the defining lift identity recovers the previous stage.
  refine ⟨lift.toRingHom.comp (Ideal.Quotient.mk I), ?_⟩
  ext x
  calc
    ((Ideal.Quotient.factorPow (maximalIdeal Λ₀) (Nat.le_succ (n + 1))).comp
        (lift.toRingHom.comp (Ideal.Quotient.mk I))) x =
        (factorAlg.comp lift) ((Ideal.Quotient.mk I) x) := by
      rfl
    _ = qgAlg ((Ideal.Quotient.mk I) x) := by
      rw [Algebra.FormallySmooth.comp_liftOfSurjective]
    _ = g x := by
      exact RingHom.congr_fun hqg x

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the positive coefficient-ring
power quotients carry a compatible tower of Cohen lifts. -/
private theorem cohenPositiveQuotientTowerLift
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) :
    ∃ g : (n : ℕ) → C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1),
      g 0 = ((Ideal.quotEquivOfEq
        (by simp [pow_one] : maximalIdeal Λ₀ = (maximalIdeal Λ₀) ^ (1 : ℕ))).toRingHom).comp
          (e.toRingHom.comp (IsLocalRing.residue C)) ∧
      ∀ n, (Ideal.Quotient.factorPow (maximalIdeal Λ₀) (Nat.le_succ (n + 1))).comp
        (g (n + 1)) = g n := by
  classical
  -- Start from the residue-field stage and choose each successor lift recursively.
  let base : C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (1 : ℕ) :=
    Classical.choose (cohenLiftResidueQuotientMap (R := R) (C := C) (Λ₀ := Λ₀) e)
  have hbase : base = ((Ideal.quotEquivOfEq
        (by simp [pow_one] : maximalIdeal Λ₀ = (maximalIdeal Λ₀) ^ (1 : ℕ))).toRingHom).comp
          (e.toRingHom.comp (IsLocalRing.residue C)) :=
    Classical.choose_spec (cohenLiftResidueQuotientMap (R := R) (C := C) (Λ₀ := Λ₀) e)
  let g : (n : ℕ) → C →+* Λ₀ ⧸ (maximalIdeal Λ₀) ^ (n + 1) :=
    fun n => Nat.rec base
      (fun m gm => Classical.choose (cohenLiftQuotientStep (R := R) e m gm)) n
  refine ⟨g, ?_, ?_⟩
  · dsimp [g]
    exact hbase
  · intro n
    dsimp [g]
    exact Classical.choose_spec
      (cohenLiftQuotientStep (R := R) e n
        (Nat.rec base
          (fun m gm => Classical.choose (cohenLiftQuotientStep (R := R) e m gm)) n))

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: compatibility after quotienting
by `maximalIdeal S ^ 1` is the same as residue-field compatibility. -/
private theorem residue_comp_of_firstPowerQuotient_comp
    {C S : Type u} [CommRing C] [IsLocalRing C] [CommRing S] [IsLocalRing S]
    (ψ : C →+* S) (e : ResidueField C ≃+* ResidueField S)
    (hψ : (Ideal.Quotient.mk ((maximalIdeal S) ^ (1 : ℕ))).comp ψ =
      ((Ideal.quotEquivOfEq
        (by simp [pow_one] : maximalIdeal S = (maximalIdeal S) ^ (1 : ℕ))).toRingHom).comp
          (e.toRingHom.comp (IsLocalRing.residue C))) :
    (IsLocalRing.residue S).comp ψ = e.toRingHom.comp (IsLocalRing.residue C) := by
  -- Apply the quotient equivalence `S/m ≃ S/m^1`; after this, the assumed first-stage identity
  -- is exactly the desired equality.
  let E : S ⧸ maximalIdeal S ≃+* S ⧸ (maximalIdeal S) ^ (1 : ℕ) :=
    Ideal.quotEquivOfEq
      (by simp [pow_one] : maximalIdeal S = (maximalIdeal S) ^ (1 : ℕ))
  ext x
  apply E.injective
  calc
    E (((IsLocalRing.residue S).comp ψ) x) =
        ((Ideal.Quotient.mk ((maximalIdeal S) ^ (1 : ℕ))).comp ψ) x := by
      rfl
    _ = (((Ideal.quotEquivOfEq
        (by simp [pow_one] : maximalIdeal S = (maximalIdeal S) ^ (1 : ℕ))).toRingHom).comp
          (e.toRingHom.comp (IsLocalRing.residue C))) x := by
      exact RingHom.congr_fun hψ x
    _ = E ((e.toRingHom.comp (IsLocalRing.residue C)) x) := by
      rfl

/-- Chap10 Theorem 10 160 8 Cohen structure theorem: the Cohen-lift step constructs a local
Cohen-ring map into the chosen coefficient subring. -/
private theorem cohenRingLiftToCoefficientRing
    {C : Type u} [CommRing C] [IsCohenRing C]
    {Λ₀ : Subring R} [hΛ₀ : IsCoefficientRing R Λ₀]
    (e : ResidueField C ≃+* ResidueField Λ₀) :
    ∃ (ψ : C →+* Λ₀) (_ : IsLocalHom ψ), Function.Bijective (ResidueField.map ψ) := by
  -- Route correction: the previous route tried to lift the Cohen ring directly into `R`.
  -- The coefficient subring is the complete local target with controlled quotient powers; the
  -- resolved prefix above now supplies the base quotient map, characteristic alignment, source
  -- quotient factorization, and final residue-field/locality criterion. The remaining step is the
  -- compatible finite-thickening lift from level `n + 1` to `n + 2` and the strict-positive adic
  -- limit in `Λ₀`.
  -- TODO: use `cohenLift_factor_through_source_quotient` with
  -- `cohenRing_zmodPow_quotient_formallySmooth` to lift each stage across
  -- `Ideal.Quotient.factorPow (maximalIdeal Λ₀) (Nat.le_succ _)`, then assemble the compatible
  -- family with `IsAdicComplete.StrictMono.liftRingHom`.
  rcases cohenPositiveQuotientTowerLift (R := R) (C := C) (Λ₀ := Λ₀) e with
    ⟨g, hg0, hgcompat⟩
  have ha : StrictMono (fun n : ℕ ↦ n + 1) := by
    exact strictMono_nat_of_lt_succ (fun n ↦ by omega)
  let ψ : C →+* Λ₀ :=
    IsAdicComplete.StrictMono.liftRingHom (maximalIdeal Λ₀) ha g (by
      intro m
      exact hgcompat m)
  have hfirst :
      (Ideal.Quotient.mk ((maximalIdeal Λ₀) ^ (1 : ℕ))).comp ψ =
        ((Ideal.quotEquivOfEq
          (by simp [pow_one] : maximalIdeal Λ₀ = (maximalIdeal Λ₀) ^ (1 : ℕ))).toRingHom).comp
            (e.toRingHom.comp (IsLocalRing.residue C)) := by
    -- The adic limit map has the prescribed reduction at level zero of the positive tower.
    calc
      (Ideal.Quotient.mk ((maximalIdeal Λ₀) ^ (1 : ℕ))).comp ψ = g 0 := by
        simpa [ψ] using
          (IsAdicComplete.StrictMono.mk_comp_liftRingHom (maximalIdeal Λ₀) ha g
            (by
              intro m
              exact hgcompat m) (n := 0))
      _ = ((Ideal.quotEquivOfEq
          (by simp [pow_one] : maximalIdeal Λ₀ = (maximalIdeal Λ₀) ^ (1 : ℕ))).toRingHom).comp
            (e.toRingHom.comp (IsLocalRing.residue C)) := hg0
  have hres :
      (IsLocalRing.residue Λ₀).comp ψ = e.toRingHom.comp (IsLocalRing.residue C) :=
    residue_comp_of_firstPowerQuotient_comp ψ e hfirst
  rcases exists_isLocalHom_and_residueFieldMap_bijective_of_residue_compat ψ e hres with
    ⟨hψlocal, hψres⟩
  exact ⟨ψ, hψlocal, hψres⟩

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: choose a coefficient source
mapping locally to `R` and inducing an isomorphism on residue fields. -/
private theorem existsCoefficientSourceMap
    (hcoeff : ∃ Λ₀ : Subring R, IsCoefficientRing R Λ₀) :
    (∃ (k : Type u) (_ : Field k) (ι : k →+* R) (_ : IsLocalHom ι),
      Function.Bijective (ResidueField.map ι)) ∨
      ∃ (Λ : Type u) (_ : CommRing Λ) (_ : IsCohenRing Λ) (ι : Λ →+* R)
        (_ : IsLocalHom ι), Function.Bijective (ResidueField.map ι) := by
  rcases hcoeff with ⟨Λ₀, hΛ₀⟩
  by_cases hchar : ringChar (ResidueField R) = 0
  · -- In equal characteristic the chosen coefficient ring itself supplies the field source.
    left
    letI : IsCoefficientRing R Λ₀ := hΛ₀
    letI : Field Λ₀ := (coefficientRing_isField_of_residueChar_zero (R := R) hchar).toField
    exact ⟨Λ₀, inferInstance, (Λ₀.subtype : Λ₀ →+* R), inferInstance,
      hΛ₀.residueField_bijective⟩
  · -- In positive characteristic, first choose the abstract Cohen ring with the right residue
    -- field, then lift it into the chosen coefficient subring before composing with `R`.
    right
    rcases existsCohenRingResidueFieldSource (R := R) hchar with ⟨Λ, hComm, hCohen, ⟨e⟩⟩
    letI : CommRing Λ := hComm
    letI : IsCohenRing Λ := hCohen
    letI : IsCoefficientRing R Λ₀ := hΛ₀
    rcases coefficientRingResidueFieldEquiv (R := R) (Λ := Λ₀) with ⟨eΛ₀⟩
    let eToCoeff : ResidueField Λ ≃+* ResidueField Λ₀ := e.trans eΛ₀.symm
    have hlift :
        ∃ (ι : Λ →+* R) (_ : IsLocalHom ι),
          Function.Bijective (ResidueField.map ι) := by
      rcases cohenRingLiftToCoefficientRing (R := R) (C := Λ) (Λ₀ := Λ₀) eToCoeff with
        ⟨ψ, hψlocal, hψres⟩
      -- Compose the coefficient-subring lift with the canonical inclusion into the ambient ring.
      let ι : Λ →+* R := (Λ₀.subtype : Λ₀ →+* R).comp ψ
      have hιlocal : IsLocalHom ι := by
        letI : IsLocalHom ψ := hψlocal
        exact inferInstance
      have hιres : Function.Bijective (ResidueField.map ι) := by
        letI : IsLocalHom ψ := hψlocal
        -- The residue-field map of the composite is the composite of the two residue-field maps.
        simpa [ι, IsLocalRing.ResidueField.map_comp] using
          hΛ₀.residueField_bijective.comp hψres
      exact ⟨ι, hιlocal, hιres⟩
    rcases hlift with ⟨ι, hlocal, hres⟩
    exact ⟨Λ, inferInstance, inferInstance, ι, hlocal, hres⟩

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: polynomial evaluation sends
the variables ideal to the ideal spanned by the chosen target elements. -/
private theorem mvPolynomialIdealOfVars_eval₂Hom_map_eq_span
    {A S σ : Type u} [CommSemiring A] [CommSemiring S]
    (ι : A →+* S) (x : σ → S) :
    Ideal.map (MvPolynomial.eval₂Hom ι x) (MvPolynomial.idealOfVars σ A) =
      Ideal.span (Set.range x) := by
  -- The variables ideal is the span of all `X i`, and evaluation sends `X i` to `x i`.
  rw [MvPolynomial.idealOfVars, Ideal.map_span]
  congr
  ext y
  simp

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: polynomial evaluation sends
the variables ideal onto `maximalIdeal R` when the chosen elements generate it. -/
private theorem mvPolynomialIdealOfVars_eval₂Hom_map_eq_maximalIdeal
    {A σ : Type u} [CommSemiring A] (ι : A →+* R) (x : σ → R)
    (hxspan : Ideal.span (Set.range x) = maximalIdeal R) :
    Ideal.map (MvPolynomial.eval₂Hom ι x) (MvPolynomial.idealOfVars σ A) =
      maximalIdeal R := by
  -- Reduce the maximal-ideal statement to the generic span computation.
  rw [mvPolynomialIdealOfVars_eval₂Hom_map_eq_span, hxspan]

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: polynomial evaluation is
surjective after reducing modulo the maximal ideal if the coefficient map is residue-surjective. -/
private theorem mvPolynomialEval_mod_maximal_surjective
    {A σ : Type u} [CommRing A] [IsLocalRing A]
    (ι : A →+* R) [IsLocalHom ι]
    (hres : Function.Bijective (ResidueField.map ι)) (x : σ → R) :
    Function.Surjective
      ((Ideal.Quotient.mk (maximalIdeal R)).comp (MvPolynomial.eval₂Hom ι x)) := by
  -- Lift the desired residue class to a coefficient, then use the constant polynomial.
  intro y
  rcases hres.2 y with ⟨z, hz⟩
  rcases IsLocalRing.residue_surjective z with ⟨a, rfl⟩
  refine ⟨MvPolynomial.C a, ?_⟩
  simpa [IsLocalRing.ResidueField.map_residue] using hz

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the same residue-level
surjectivity holds modulo the image of the variables ideal once that image is `maximalIdeal R`. -/
private theorem mvPolynomialEval_mod_imageIdeal_surjective
    {A σ : Type u} [CommRing A] [IsLocalRing A]
    (ι : A →+* R) [IsLocalHom ι]
    (hres : Function.Bijective (ResidueField.map ι)) (x : σ → R)
    (hmap :
      Ideal.map (MvPolynomial.eval₂Hom ι x) (MvPolynomial.idealOfVars σ A) =
        maximalIdeal R) :
    Function.Surjective
      ((Ideal.Quotient.mk
        (Ideal.map (MvPolynomial.eval₂Hom ι x) (MvPolynomial.idealOfVars σ A))).comp
          (MvPolynomial.eval₂Hom ι x)) := by
  -- Rewrite the image ideal to the maximal ideal and invoke the residue-field calculation.
  rw [hmap]
  exact mvPolynomialEval_mod_maximal_surjective (R := R) ι hres x

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: powers of an ideal map into
powers of its image ideal. -/
private theorem ideal_pow_le_comap_pow_of_map_eq
    {P S : Type u} [CommRing P] [CommRing S] {J : Ideal P} {I : Ideal S}
    (g : P →+* S) (hmap : Ideal.map g J = I) (n : ℕ) :
    J ^ n ≤ (I ^ n).comap g := by
  -- Rewrite the target power as the image of the source power and use the map/comap adjunction.
  exact Ideal.map_le_iff_le_comap.mp (by rw [Ideal.map_pow, hmap])

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the quotient maps from an adic
completion induced by a ring map with prescribed ideal image are compatible in the inverse
system. -/
private theorem adicCompletionQuotientMaps_compatible
    {P S : Type u} [CommRing P] [CommRing S] {J : Ideal P} {I : Ideal S}
    (g : P →+* S) (hmap : Ideal.map g J = I) :
    let f : (n : ℕ) → AdicCompletion J P →+* S ⧸ I ^ n := fun n =>
      (Ideal.quotientMap (I ^ n) g (ideal_pow_le_comap_pow_of_map_eq g hmap n)).comp
        (AdicCompletion.evalₐ J n).toRingHom
    ∀ {m n : ℕ} (hle : m ≤ n), (Ideal.Quotient.factorPow I hle).comp (f n) = f m := by
  dsimp only
  intro m n hle
  ext y
  -- Reduce the compatibility to the Cauchy-sequence representative of the completion element.
  apply AdicCompletion.induction_on J P y
  intro a
  change (Ideal.Quotient.mk (I ^ m)) (g (↑(a n) : P)) =
    (Ideal.Quotient.mk (I ^ m)) (g (↑(a m) : P))
  rw [Ideal.Quotient.eq]
  -- The Cauchy condition says the two representatives agree modulo `J ^ m`; mapping this
  -- congruence across `g` gives agreement modulo `I ^ m`.
  have hcong : (↑(a n) : P) ≡ (↑(a m) : P)
      [SMOD (J ^ m • ⊤ : Submodule P P)] := (a.property hle).symm
  have hmemJ : ((↑(a n) : P) - (↑(a m) : P)) ∈ J ^ m := by
    simpa using (SModEq.sub_mem.mp hcong)
  have hmem : g ((↑(a n) : P) - (↑(a m) : P)) ∈ Ideal.map g (J ^ m) :=
    Ideal.mem_map_of_mem g hmemJ
  have hmap_pow : Ideal.map g (J ^ m) = I ^ m := by
    rw [Ideal.map_pow, hmap]
  simpa [map_sub, hmap_pow] using hmem

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: the lifted map from the source
adic completion agrees with the original ring map on polynomial elements. -/
private theorem adicCompletionLiftRingHom_comp_algebraMap
    {P S : Type u} [CommRing P] [CommRing S] {J : Ideal P} {I : Ideal S}
    (g : P →+* S) (hmap : Ideal.map g J = I) [IsAdicComplete I S] :
    let f : (n : ℕ) → AdicCompletion J P →+* S ⧸ I ^ n := fun n =>
      (Ideal.quotientMap (I ^ n) g (ideal_pow_le_comap_pow_of_map_eq g hmap n)).comp
        (AdicCompletion.evalₐ J n).toRingHom
    (IsAdicComplete.liftRingHom I f (adicCompletionQuotientMaps_compatible g hmap)).comp
      (algebraMap P (AdicCompletion J P)) = g := by
  dsimp only
  let f : (n : ℕ) → AdicCompletion J P →+* S ⧸ I ^ n := fun n =>
    (Ideal.quotientMap (I ^ n) g (ideal_pow_le_comap_pow_of_map_eq g hmap n)).comp
      (AdicCompletion.evalₐ J n).toRingHom
  have hf : ∀ {m n : ℕ} (hle : m ≤ n), (Ideal.Quotient.factorPow I hle).comp (f n) = f m :=
    adicCompletionQuotientMaps_compatible g hmap
  let G : AdicCompletion J P →+* S := IsAdicComplete.liftRingHom I f hf
  -- Since `S` is Hausdorff for the `I`-adic topology, equality of maps into `S` is checked on
  -- all quotient reductions.
  apply DFunLike.coe_injective
  apply IsHausdorff.funext' I
  intro n x
  calc
    Ideal.Quotient.mk (I ^ n) (G ((algebraMap P (AdicCompletion J P)) x)) =
        f n ((algebraMap P (AdicCompletion J P)) x) := by
      exact
        RingHom.congr_fun (IsAdicComplete.mk_comp_liftRingHom I f hf n)
          ((algebraMap P (AdicCompletion J P)) x)
    _ = Ideal.Quotient.mk (I ^ n) (g x) := by
      simp [f, Ideal.quotientMap_mk]

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a ring map that is surjective
modulo the image ideal induces a surjective map from the adic completion of the source. -/
private theorem adicCompletionMapRingHom_surjective_of_quotient_surjective
    {P S : Type u} [CommRing P] [CommRing S] {J : Ideal P} {I : Ideal S}
    [IsAdicComplete I S] (g : P →+* S) (hmap : Ideal.map g J = I)
    (hJfg : J.FG) (hmod : Function.Surjective ((Ideal.Quotient.mk I).comp g)) :
    ∃ G : AdicCompletion J P →+* S,
      Function.Surjective G ∧ G.comp (algebraMap P (AdicCompletion J P)) = g := by
  let f : (n : ℕ) → AdicCompletion J P →+* S ⧸ I ^ n := fun n =>
    (Ideal.quotientMap (I ^ n) g (ideal_pow_le_comap_pow_of_map_eq g hmap n)).comp
      (AdicCompletion.evalₐ J n).toRingHom
  have hf : ∀ {m n : ℕ} (hle : m ≤ n), (Ideal.Quotient.factorPow I hle).comp (f n) = f m :=
    adicCompletionQuotientMaps_compatible g hmap
  let G : AdicCompletion J P →+* S := IsAdicComplete.liftRingHom I f hf
  have hGcomp : G.comp (algebraMap P (AdicCompletion J P)) = g := by
    simpa [G, f, hf] using adicCompletionLiftRingHom_comp_algebraMap (I := I) g hmap
  refine ⟨G, ?_, hGcomp⟩
  let K : Ideal (AdicCompletion J P) := Ideal.map (algebraMap P (AdicCompletion J P)) J
  have hpre : IsPrecomplete K (AdicCompletion J P) := by
    change IsPrecomplete (Ideal.map (algebraMap P (AdicCompletion J P)) J)
      (AdicCompletion J P)
    have hcomp : IsAdicComplete J (AdicCompletion J P) := AdicCompletion.isAdicComplete hJfg
    letI : IsAdicComplete J (AdicCompletion J P) := hcomp
    exact (IsPrecomplete.map_algebraMap_iff (I := J) (M := AdicCompletion J P)).2 inferInstance
  have hGmap : Ideal.map G K = I := by
    calc
      Ideal.map G K = Ideal.map (G.comp (algebraMap P (AdicCompletion J P))) J := by
        rw [Ideal.map_map]
      _ = Ideal.map g J := by rw [hGcomp]
      _ = I := hmap
  have hhaus : IsHausdorff (Ideal.map G K) S := by
    rw [hGmap]
    infer_instance
  -- The standard separated/precomplete surjectivity criterion now reduces surjectivity of `G`
  -- to the already-known surjectivity modulo the image ideal.
  apply @surjective_of_mk_map_comp_surjective
    (AdicCompletion J P) inferInstance K S inferInstance G hpre hhaus
  intro y
  let e : S ⧸ Ideal.map G K ≃+* S ⧸ I := Ideal.quotEquivOfEq hGmap
  rcases hmod (e y) with ⟨x, hx⟩
  refine ⟨(algebraMap P (AdicCompletion J P)) x, ?_⟩
  apply e.injective
  change (Ideal.Quotient.mk I) (G ((algebraMap P (AdicCompletion J P)) x)) = e y
  have hxG : G ((algebraMap P (AdicCompletion J P)) x) = g x :=
    RingHom.congr_fun hGcomp x
  rw [hxG]
  exact hx

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: a local coefficient source whose
residue-field map is bijective and whose chosen elements generate `maximalIdeal R` gives a
surjective finite-variable formal power series map to `R`. -/
private theorem mvPowerSeriesSurjective_of_residue_bijective_of_generates_maximalIdeal
    {A σ : Type u} [CommRing A] [IsLocalRing A] [Finite σ]
    (ι : A →+* R) [IsLocalHom ι]
    (hres : Function.Bijective (ResidueField.map ι))
    (x : σ → R) (_hxmem : ∀ i, x i ∈ maximalIdeal R)
    (hxspan : Ideal.span (Set.range x) = maximalIdeal R) :
    ∃ φ : MvPowerSeries σ A →+* R, Function.Surjective φ := by
  -- The polynomial evaluation has the right first-order image and is surjective on the residue
  -- quotient; the remaining step is to lift this through the power-series completion.
  let g : MvPolynomial σ A →+* R := MvPolynomial.eval₂Hom ι x
  let J : Ideal (MvPolynomial σ A) := MvPolynomial.idealOfVars σ A
  have hmapJ : Ideal.map g J = maximalIdeal R := by
    exact mvPolynomialIdealOfVars_eval₂Hom_map_eq_maximalIdeal (R := R) ι x hxspan
  have hmod :
      Function.Surjective ((Ideal.Quotient.mk (Ideal.map g J)).comp g) := by
    exact mvPolynomialEval_mod_imageIdeal_surjective (R := R) ι hres x hmapJ
  have hmodMax :
      Function.Surjective ((Ideal.Quotient.mk (maximalIdeal R)).comp g) := by
    -- Transport the modulo-image surjectivity across the equality `Ideal.map g J = maximalIdeal R`.
    intro y
    let e : R ⧸ Ideal.map g J ≃+* R ⧸ maximalIdeal R := Ideal.quotEquivOfEq hmapJ
    rcases hmod (e.symm y) with ⟨z, hz⟩
    refine ⟨z, ?_⟩
    change e (((Ideal.Quotient.mk (Ideal.map g J)).comp g) z) = y
    rw [hz]
    exact e.apply_symm_apply y
  have hJfg : J.FG := by
    exact MvPolynomial.idealOfVars_fg σ A
  -- Complete the polynomial evaluation map and transport it across the canonical equivalence
  -- between power series and the variables-adic completion of the polynomial ring.
  rcases adicCompletionMapRingHom_surjective_of_quotient_surjective
      (I := maximalIdeal R) g hmapJ hJfg hmodMax with
    ⟨G, hGsurj, _hGcomp⟩
  let φ : MvPowerSeries σ A →+* R :=
    G.comp (MvPowerSeries.toAdicCompletionAlgEquiv σ A).toRingHom
  exact ⟨φ, hGsurj.comp (MvPowerSeries.toAdicCompletionAlgEquiv σ A).surjective⟩

/-- Helper for Chap10 Theorem 10 160 8 Cohen structure theorem: under the coefficient-ring and
finite-generation hypotheses, `R` has a surjective map from a finite-index formal power series
ring over either a field or a Cohen ring. The quotient-by-kernel presentation is derived from this
owner theorem via `RingHom.quotientKerEquivOfSurjective`. -/
theorem exists_surjective_mvPowerSeries_of_exists_coefficientRing_of_maximalIdeal_fg
    (hcoeff : ∃ Λ₀ : Subring R, IsCoefficientRing R Λ₀) (hfg : (maximalIdeal R).FG) :
    ∃ (σ : Type u) (_ : Finite σ),
      (∃ (k : Type u) (_ : Field k) (φ : MvPowerSeries σ k →+* R), Function.Surjective φ) ∨
        ∃ (Λ : Type u) (_ : CommRing Λ) (_ : IsCohenRing Λ)
          (φ : MvPowerSeries σ Λ →+* R), Function.Surjective φ := by
  -- First fix finite generators for the maximal ideal; these are the formal variables.
  rcases finiteMaximalIdealGeneratingFamily (R := R) hfg with ⟨σ, hσ, x, hxmem, hxspan⟩
  refine ⟨σ, hσ, ?_⟩
  -- Then choose either a coefficient field or a Cohen coefficient source and apply the shared
  -- power-series surjectivity engine.
  rcases existsCoefficientSourceMap (R := R) hcoeff with hfield | hcohen
  · rcases hfield with ⟨k, hField, ι, hlocal, hres⟩
    left
    letI : Field k := hField
    letI : IsLocalHom ι := hlocal
    rcases
      mvPowerSeriesSurjective_of_residue_bijective_of_generates_maximalIdeal
        (R := R) (σ := σ) ι hres x hxmem hxspan with
      ⟨φ, hφ⟩
    exact ⟨k, inferInstance, φ, hφ⟩
  · rcases hcohen with ⟨Λ, hComm, hCohen, ι, hlocal, hres⟩
    right
    letI : CommRing Λ := hComm
    letI : IsCohenRing Λ := hCohen
    letI : IsLocalHom ι := hlocal
    rcases
      mvPowerSeriesSurjective_of_residue_bijective_of_generates_maximalIdeal
        (R := R) (σ := σ) ι hres x hxmem hxspan with
      ⟨φ, hφ⟩
    exact ⟨Λ, inferInstance, inferInstance, φ, hφ⟩

-- Proof sketch: apply the primitive surjective-presentation theorem above and identify the target
-- with the quotient by the kernel of the chosen surjective map using
-- `RingHom.quotientKerEquivOfSurjective`.
/-- Consequence of Chap10 Theorem 10 160 8 Cohen structure theorem (Theorem 10.160.8): if a
complete local ring `R` has a coefficient ring and its maximal ideal is finitely generated, then
`R` is isomorphic to a quotient of a finite-variable formal power series ring over either a field
or a Cohen ring. -/
@[stacks 032A]
theorem exists_mvPowerSeries_quotient_of_exists_coefficientRing_of_maximalIdeal_fg
    (hcoeff : ∃ Λ₀ : Subring R, IsCoefficientRing R Λ₀) (hfg : (maximalIdeal R).FG) :
    ∃ (σ : Type u) (_ : Finite σ),
      (∃ (k : Type u) (_ : Field k) (I : Ideal (MvPowerSeries σ k)),
        Nonempty ((MvPowerSeries σ k ⧸ I) ≃+* R)) ∨
        ∃ (Λ : Type u) (_ : CommRing Λ) (_ : IsCohenRing Λ)
          (I : Ideal (MvPowerSeries σ Λ)),
          Nonempty ((MvPowerSeries σ Λ ⧸ I) ≃+* R) := by
  rcases exists_surjective_mvPowerSeries_of_exists_coefficientRing_of_maximalIdeal_fg R hcoeff hfg with
    ⟨σ, hσ, hσR⟩
  refine ⟨σ, hσ, ?_⟩
  rcases hσR with hfield | hcohen
  · rcases hfield with ⟨k, _, φ, hφ⟩
    left
    refine ⟨k, inferInstance, RingHom.ker φ, ?_⟩
    exact ⟨RingHom.quotientKerEquivOfSurjective hφ⟩
  · rcases hcohen with ⟨Λ, _, _, φ, hφ⟩
    right
    refine ⟨Λ, inferInstance, inferInstance, RingHom.ker φ, ?_⟩
    exact ⟨RingHom.quotientKerEquivOfSurjective hφ⟩

end
