import StacksProject_2024.Chap10.Theorem_10_34_1_Hilbert_Nullstellensatz
import StacksProject_2024.Chap10.Lemma_10_35_5
import StacksProject_2024.Chap10.Lemma_10_35_9
import StacksProject_2024.Chap10.Lemma_10_35_10
import Mathlib.RingTheory.Extension.Generators
import Mathlib.Tactic.StacksAttribute

-- Declarations for this item will be appended below by the statement pipeline.

open Cardinal

universe u w

section

variable {k : Type u} {S : Type w}
variable [Field k] [CommRing S] [Algebra k S]

/- Domain triage:
* primary domain: residue-field algebraicity and Jacobson properties for small `k`-algebras;
* source-facing layer: the Stacks hypotheses stay in terms of a generating set `s` with
  `Algebra.adjoin k s = ⊤` and `#s < #k`;
* core/canonical owners: `Algebra.IsAlgebraic k m.ResidueField` and `IsJacobsonRing S`;
* bridge/view: this item upgrades the small-generation hypothesis to those owner predicates;
* primitive data vs. derived API: the only primitive source data are `s`, `hs`, and `hcard`,
  while residue-field algebraicity and the Jacobson condition remain theorem-level conclusions.
-/

/-- Helper for Theorem 10.35.11: the polynomial evaluation map on the chosen generators is
surjective once those generators adjoin the whole algebra. -/
lemma aeval_subtype_surjective_of_adjoin_eq_top
    (s : Set S) (hs : Algebra.adjoin k s = ⊤) :
    Function.Surjective (MvPolynomial.aeval ((↑) : s → S) : MvPolynomial s k →ₐ[k] S) := by
  -- Identify the evaluation map range with the subalgebra generated by `s`.
  rw [← AlgHom.range_eq_top]
  simpa [Algebra.adjoin_eq_range] using hs

/-- Helper for Theorem 10.35.11: for infinitely many generators, the residue field of a maximal
ideal has `k`-dimension strictly smaller than `#k`. -/
lemma lift_rank_residueField_lt_cardinal_of_infinite_generators
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    (hcard : lift.{max u w} (#s) < lift.{max u w} (#k))
    (m : Ideal S) [m.IsMaximal] (hsinf : Set.Infinite s) :
    lift.{max u w} (Module.rank k m.ResidueField) < lift.{max u w} (#k) := by
  let ψ : MvPolynomial s k →ₐ[k] m.ResidueField :=
    (IsScalarTower.toAlgHom k S m.ResidueField).comp
      (MvPolynomial.aeval ((↑) : s → S))
  have hψ : Function.Surjective ψ := by
    -- Choose a polynomial preimage of the numerator in `S`, then descend to the residue field.
    intro y
    obtain ⟨x, rfl⟩ := Ideal.algebraMap_residueField_surjective m y
    obtain ⟨p, hp⟩ := aeval_subtype_surjective_of_adjoin_eq_top (k := k) s hs x
    refine ⟨p, ?_⟩
    simpa [ψ, hp] using congrArg (algebraMap S m.ResidueField) hp
  have hψlin : Function.Surjective ψ.toLinearMap := by
    simpa using hψ
  have hrank_le :
      lift.{max u w} (Module.rank k m.ResidueField) ≤
        lift.{w} (Module.rank k (MvPolynomial s k)) := by
    exact LinearMap.lift_rank_le_of_surjective (f := ψ.toLinearMap) hψlin
  have hpoly_rank :
      lift.{w} (Module.rank k (MvPolynomial s k)) ≤ lift.{max u w} (#s) := by
    letI : Infinite s := hsinf.to_subtype
    haveI : Nonempty s := Infinite.nonempty s
    -- Infinite-variable monomials have the same cardinality as the variable set itself.
    rw [MvPolynomial.rank_eq_lift, lift_lift, Cardinal.mk_finsupp_nat]
    exact le_of_eq <| by simpa using congrArg (lift.{max u w}) (max_eq_left (aleph0_le_mk s))
  -- Chain the surjective rank bound with the monomial-cardinality calculation.
  exact lt_of_le_of_lt (hrank_le.trans hpoly_rank) hcard

/-- Helper for Theorem 10.35.11: surjective algebra maps carry a generating set onto a generating
set of the target algebra. -/
lemma adjoin_image_eq_top_of_surjective
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    {T : Type w} [CommRing T] [Algebra k T]
    (φ : S →ₐ[k] T) (hφ : Function.Surjective φ) :
    Algebra.adjoin k (φ '' s) = ⊤ := by
  -- Map the generating equality across `φ` and use surjectivity to identify the image with `⊤`.
  simpa [AlgHom.map_adjoin, (AlgHom.range_eq_top φ).2 hφ] using
    congrArg (Subalgebra.map φ) hs

/-- Helper for Theorem 10.35.11: the canonical quotient-plus-localization presentation already
surjects onto the localized quotient ring, so no hand-built `Option`-indexed evaluation map is
needed. -/
lemma quotient_localization_comp_generators_aeval_surjective
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    (q : PrimeSpectrum S) (f : S) :
    let A : Type w := S ⧸ q.asIdeal
    let L : Type w := Localization.Away (Ideal.Quotient.mk q.asIdeal f)
    let sA : Set A := (Ideal.Quotient.mkₐ k q.asIdeal) '' s
    let hsA : Algebra.adjoin k sA = ⊤ :=
      adjoin_image_eq_top_of_surjective (k := k) (S := S) s hs
        (Ideal.Quotient.mkₐ k q.asIdeal) (Ideal.Quotient.mkₐ_surjective k q.asIdeal)
    let P : Algebra.Generators k A sA := Algebra.Generators.ofSet hsA
    let Q : Algebra.Generators A L Unit :=
      Algebra.Generators.localizationAway L (Ideal.Quotient.mk q.asIdeal f)
    Function.Surjective
      (MvPolynomial.aeval ((Q.comp P).val) : MvPolynomial (Unit ⊕ sA) k →ₐ[k] L) := by
  intro A L sA hsA P Q
  -- The composed generators come with a built-in section, hence the evaluation map is surjective.
  simpa using (Q.comp P).aeval_val_surjective

omit [Field k] [CommRing S] [Algebra k S] in
/-- Helper for Theorem 10.35.11: adjoining one localization generator to a set whose cardinality is
bounded by `#s` still keeps the resulting generator family smaller than `#k`. -/
lemma lift_cardinal_range_sum_generators_lt_cardinal
    {A : Type w} {T : Type w} (s : Set S) (φ : Unit ⊕ A → T)
    (hAcard : lift.{max u w} (#A) ≤ lift.{max u w} (#s))
    (hcard : lift.{max u w} (#s) < lift.{max u w} (#k))
    (hsinf : Set.Infinite s) :
    lift.{max u w} #(↑(Set.range φ)) < lift.{max u w} (#k) := by
  letI : Infinite s := hsinf.to_subtype
  have hrange0 : #(↑(Set.range φ)) ≤ #(Unit ⊕ A) := by
    refine Cardinal.mk_le_of_surjective (f := fun x : Unit ⊕ A => ⟨φ x, ⟨x, rfl⟩⟩) ?_
    intro y
    rcases y.2 with ⟨x, hx⟩
    refine ⟨x, Subtype.ext ?_⟩
    simpa using hx
  have hrange :
      lift.{max u w} #(↑(Set.range φ)) ≤ lift.{max u w} (#(Unit ⊕ A)) := by
    exact Cardinal.lift_le.mpr hrange0
  have hsAleph :
      ℵ₀ ≤ lift.{max u w} (#s) := by
    exact Cardinal.aleph0_le_lift.2 (aleph0_le_mk s)
  have hsum :
      lift.{max u w} (#(Unit ⊕ A)) ≤ lift.{max u w} (#s) := by
    rw [Cardinal.mk_sum, Cardinal.lift_add, Cardinal.lift_lift, Cardinal.lift_lift,
      Cardinal.mk_eq_one, Cardinal.lift_one]
    calc
      1 + lift.{max u w} (#A) ≤ 1 + lift.{max u w} (#s) := by
        simpa [add_comm] using add_le_add_left hAcard 1
      _ = lift.{max u w} (#s) := by
        rw [Cardinal.add_eq_right hsAleph (one_le_aleph0.trans hsAleph)]
  -- Chain the range bound through the `1 + #A = #s` cardinal estimate.
  exact lt_of_le_of_lt (hrange.trans hsum) hcard

/-- Helper for Theorem 10.35.11: the field `(S / q)_f` is generated over `k` by fewer than `#k`
elements when `s` is infinite and already generates `S`. -/
lemma exists_small_generating_set_localizationAway_quotient
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    (hcard : lift.{max u w} (#s) < lift.{max u w} (#k))
    (q : PrimeSpectrum S) (f : S) (_hf : f ∉ q.asIdeal) (hsinf : Set.Infinite s) :
    ∃ t : Set (Localization.Away (Ideal.Quotient.mk q.asIdeal f)),
      Algebra.adjoin k t = ⊤ ∧
        lift.{max u w} (#t) < lift.{max u w} (#k) := by
  let A : Type w := S ⧸ q.asIdeal
  let L : Type w := Localization.Away (Ideal.Quotient.mk q.asIdeal f)
  let sA : Set A := (Ideal.Quotient.mkₐ k q.asIdeal) '' s
  have hsA : Algebra.adjoin k sA = ⊤ := by
    -- Pass the original generating set through the quotient map to generate `S / q`.
    exact
      adjoin_image_eq_top_of_surjective (k := k) (S := S) s hs
        (Ideal.Quotient.mkₐ k q.asIdeal) (Ideal.Quotient.mkₐ_surjective k q.asIdeal)
  let P : Algebra.Generators k A sA := Algebra.Generators.ofSet hsA
  let Q : Algebra.Generators A L Unit :=
    Algebra.Generators.localizationAway L (Ideal.Quotient.mk q.asIdeal f)
  let PQ : Algebra.Generators k L (Unit ⊕ sA) := Q.comp P
  refine ⟨Set.range PQ.val, ?_, ?_⟩
  · -- Route correction: use the canonical composed presentation instead of a manual `Option` map.
    rw [Algebra.adjoin_range_eq_range_aeval]
    exact (AlgHom.range_eq_top _).2 <|
      quotient_localization_comp_generators_aeval_surjective
      (k := k) (S := S) s hs q f
  · let ιsA : s → A := fun x ↦ Ideal.Quotient.mkₐ k q.asIdeal x.1
    have hsAcard :
        lift.{max u w} (#sA) ≤ lift.{max u w} (#s) := by
      -- The quotient-image generating set is indexed by the image of the original subtype `s`.
      simpa [sA, Set.image_eq_range, ιsA] using
        (Cardinal.mk_range_le_lift (f := ιsA))
    -- The extra localization inverse contributes only one additional generator.
    simpa [PQ] using
      lift_cardinal_range_sum_generators_lt_cardinal
        (k := k) (S := S) (A := sA) (T := L) s PQ.val hsAcard hcard hsinf

/-- Helper for Theorem 10.35.11: if the field `(S / q)_f` is algebraic over `k`, then so is the
residue field `κ(q)`. -/
lemma isAlgebraic_residueField_of_field_localizationAway_quotient
    (q : PrimeSpectrum S) (f : S) (hf : f ∉ q.asIdeal)
    {L : Type w} [Field L] [Algebra k L] [Algebra (S ⧸ q.asIdeal) L]
    [IsScalarTower k (S ⧸ q.asIdeal) L] [IsLocalization.Away (Ideal.Quotient.mk q.asIdeal f) L]
    [Algebra.IsAlgebraic k L] :
    Algebra.IsAlgebraic k q.asIdeal.ResidueField := by
  let A : Type w := S ⧸ q.asIdeal
  let y : A := Ideal.Quotient.mk q.asIdeal f
  let hy_ne_zero : y ≠ 0 := by
    intro hy
    exact hf <| Ideal.Quotient.eq_zero_iff_mem.mp <| by simpa [y] using hy
  have hnonzero :
      Submonoid.powers y ≤ nonZeroDivisors A := by
    intro z hz
    rcases hz with ⟨n, rfl⟩
    exact mem_nonZeroDivisors_iff_ne_zero.mpr (pow_ne_zero n hy_ne_zero)
  have hA_alg : Algebra.IsAlgebraic k A :=
    Algebra.IsAlgebraic.of_injective
      (IsScalarTower.toAlgHom k A L)
      (IsLocalization.injective L hnonzero)
  let _ : Algebra.IsAlgebraic k A := hA_alg
  exact Algebra.IsAlgebraic.trans k A q.asIdeal.ResidueField

/-- Helper for Theorem 10.35.11: the residue field at the zero ideal of a field is just the field
itself, so algebraicity of that residue field transports back to the field. -/
lemma isAlgebraic_of_bot_residueField
    {L : Type w} [Field L] [Algebra k L]
    [Algebra.IsAlgebraic k ((⊥ : Ideal L).ResidueField)] :
    Algebra.IsAlgebraic k L := by
  let eQuot :
      (L ⧸ (⊥ : Ideal L)) ≃ₐ[L] ((⊥ : Ideal L).ResidueField) :=
    AlgEquiv.ofBijective
      (IsScalarTower.toAlgHom L (L ⧸ (⊥ : Ideal L)) ((⊥ : Ideal L).ResidueField))
      (Ideal.bijective_algebraMap_quotient_residueField (⊥ : Ideal L))
  let e :
      ((⊥ : Ideal L).ResidueField) ≃ₐ[k] L :=
    (eQuot.symm.trans (AlgEquiv.quotientBot L L)).restrictScalars k
  -- Replace the bottom residue field with `L` itself via the canonical quotient equivalence.
  exact e.isAlgebraic

/-- Helper for Theorem 10.35.11: over a field base, a prime ideal with algebraic residue field is
already maximal. -/
lemma isMaximal_of_isAlgebraic_residueField_over_field
    (q : Ideal S) [q.IsPrime] [Algebra.IsAlgebraic k q.ResidueField] :
    q.IsMaximal := by
  let _ : Algebra.IsAlgebraic k (S ⧸ q) :=
    Algebra.IsAlgebraic.of_injective
      (IsScalarTower.toAlgHom k (S ⧸ q) q.ResidueField)
      q.injective_algebraMap_quotient_residueField
  -- The quotient by `q` is an integral algebra over the field `k`, hence a field.
  exact Ideal.Quotient.maximal_of_isField q
    (isField_of_isIntegral_of_isField' (Field.toIsField k))

-- Proof sketch: replace `S` by the polynomial ring on the generating family and pass to the
-- quotient by the corresponding maximal ideal. The polynomial ring has `k`-dimension bounded by
-- the cardinality of the generating set, so Lemma `10.35.10` rules out a transcendental element in
-- the residue field, forcing `κ(m) / k` to be algebraic.
/-- Theorem 10.35.11 (1): if a `k`-algebra `S` is generated by fewer than `#k` elements, then for
every maximal ideal `m` of `S` the residue field extension `m.ResidueField / k` is algebraic. -/
@[stacks 00FU]
theorem isAlgebraic_residueField_of_maximal_of_adjoin_eq_top_of_cardinalMk_lt
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    (hcard : lift.{max u w} (#s) < lift.{max u w} (#k))
    (m : Ideal S) [m.IsMaximal] :
    Algebra.IsAlgebraic k m.ResidueField := by
  by_cases hsfin : Set.Finite s
  · -- In the finite case, apply Hilbert Nullstellensatz through finite type.
    have hfgTop : (⊤ : Subalgebra k S).FG := by
      refine ⟨hsfin.toFinset, ?_⟩
      simpa using hs
    letI : Algebra.FiniteType k S := ⟨hfgTop⟩
    have hfinite : Module.Finite k m.ResidueField :=
      finite_residueField_of_isMaximal_of_finiteType k m
    infer_instance
  · have hsinf : Set.Infinite s := by
      rw [Set.Infinite]
      exact hsfin
    -- Route correction: the infinite branch follows the source proof via a rank contradiction,
    -- not by trying to build algebraicity directly.
    have hrank :
        lift.{max u w} (Module.rank k m.ResidueField) < lift.{max u w} (#k) :=
      lift_rank_residueField_lt_cardinal_of_infinite_generators
        (k := k) (S := S) s hs hcard m hsinf
    by_contra halg
    have htrans_alg : Algebra.Transcendental k m.ResidueField := by
      simpa [Algebra.transcendental_iff_not_isAlgebraic] using halg
    obtain ⟨T, hT⟩ := Algebra.transcendental_def.mp htrans_alg
    let μT : Module.End k m.ResidueField := Algebra.lmul k m.ResidueField T
    obtain ⟨P, hPmonic, hPnotunit⟩ :=
      exists_monic_polynomial_aeval_not_isUnit_of_rank_lt_cardinal (T := μT) hrank
    have hTinj :
        Function.Injective (Polynomial.aeval T : Polynomial k →ₐ[k] m.ResidueField) :=
      (transcendental_iff_injective (R := k) (x := T)).mp hT
    have hPT_ne_zero : Polynomial.aeval T P ≠ 0 := by
      intro hPT_zero
      have hP_zero : P = 0 := hTinj <| by simpa using hPT_zero
      exact Polynomial.not_monic_zero (hP_zero ▸ hPmonic)
    have hPunit : IsUnit (Polynomial.aeval T P) :=
      isUnit_iff_ne_zero.mpr hPT_ne_zero
    have hμT_unit : IsUnit (Polynomial.aeval μT P) := by
      -- Evaluating at left multiplication by `T` is left multiplication by `P(T)`.
      rw [Polynomial.aeval_algHom_apply]
      exact (Algebra.lmul_isUnit_iff (R := k) (A := m.ResidueField)).2 hPunit
    exact hPnotunit hμT_unit

-- Proof sketch: if `S` were not Jacobson, Lemma `10.35.5` gives a nonmaximal prime `q` such that
-- a localization of `S ⧸ q` is a field. That localization is still generated by fewer than `#k`
-- elements, so the first part makes it algebraic over `k`; then Lemma `10.35.9` forces `q` to be
-- maximal, a contradiction.
/-- Theorem 10.35.11 (2): if a `k`-algebra `S` is generated by fewer than `#k` elements, then `S`
is a Jacobson ring. -/
@[stacks 00FU]
theorem isJacobsonRing_of_adjoin_eq_top_of_cardinalMk_lt
    (s : Set S) (hs : Algebra.adjoin k s = ⊤)
    (hcard : lift.{max u w} (#s) < lift.{max u w} (#k))
    : IsJacobsonRing S := by
  by_cases hsfin : Set.Finite s
  · -- In the finite case, Jacobsonness is the finite-type Nullstellensatz.
    have hfgTop : (⊤ : Subalgebra k S).FG := by
      refine ⟨hsfin.toFinset, ?_⟩
      simpa using hs
    letI : Algebra.FiniteType k S := ⟨hfgTop⟩
    exact isJacobsonRing_of_finiteType (A := k) (B := S)
  · have hsinf : Set.Infinite s := by
      rw [Set.Infinite]
      exact hsfin
    by_contra hJacobson
    obtain ⟨q, f, hq_nonmax, hq_basicOpen⟩ :=
      exists_nonmaximal_prime_basicOpen_inter_zeroLocus_eq_singleton_of_not_isJacobsonRing
        (R := S) hJacobson
    have hf : f ∉ q.asIdeal := by
      -- The source obstruction keeps `q` inside the displayed basic open, so `f ∉ q`.
      have hq_mem :
          q ∈ PrimeSpectrum.zeroLocus (q.asIdeal : Set S) ∩
            (PrimeSpectrum.basicOpen f : Set (PrimeSpectrum S)) := by
        rw [hq_basicOpen]
        simp
      exact (PrimeSpectrum.mem_basicOpen f q).mp hq_mem.2
    have hLfield : IsField (Localization.Away (Ideal.Quotient.mk q.asIdeal f)) := by
      -- The Jacobson obstruction localizes to a field by Lemma `10.35.5`.
      exact
        isField_localizationAway_quotient_of_zeroLocus_inter_basicOpen_eq_singleton
          (R := S) q f hq_basicOpen
    letI : Field (Localization.Away (Ideal.Quotient.mk q.asIdeal f)) := hLfield.toField
    obtain ⟨t, ht, htcard⟩ :
        ∃ t : Set (Localization.Away (Ideal.Quotient.mk q.asIdeal f)),
          Algebra.adjoin k t = ⊤ ∧
          lift.{max u w} (#t) < lift.{max u w} (#k) := by
      -- Route correction: follow the source `#s + 1` localization presentation exactly.
      exact
        exists_small_generating_set_localizationAway_quotient
          (k := k) (S := S) s hs hcard q f hf hsinf
    have hL_residue_alg :
        Algebra.IsAlgebraic k
          ((⊥ : Ideal (Localization.Away (Ideal.Quotient.mk q.asIdeal f))).ResidueField) :=
      letI :
          (⊥ : Ideal (Localization.Away (Ideal.Quotient.mk q.asIdeal f))).IsMaximal :=
        Ideal.bot_isMaximal
      isAlgebraic_residueField_of_maximal_of_adjoin_eq_top_of_cardinalMk_lt
        (k := k) (S := Localization.Away (Ideal.Quotient.mk q.asIdeal f)) t ht htcard
        (⊥ : Ideal (Localization.Away (Ideal.Quotient.mk q.asIdeal f)))
    let _ :
        Algebra.IsAlgebraic k
          ((⊥ : Ideal (Localization.Away (Ideal.Quotient.mk q.asIdeal f))).ResidueField) :=
      hL_residue_alg
    let _ : Algebra.IsAlgebraic k (Localization.Away (Ideal.Quotient.mk q.asIdeal f)) :=
      isAlgebraic_of_bot_residueField
        (k := k) (L := Localization.Away (Ideal.Quotient.mk q.asIdeal f))
    have hq_alg : Algebra.IsAlgebraic k q.asIdeal.ResidueField :=
      isAlgebraic_residueField_of_field_localizationAway_quotient
        (k := k) (S := S) q f hf
        (L := Localization.Away (Ideal.Quotient.mk q.asIdeal f))
    have hq_max : q.asIdeal.IsMaximal :=
      isMaximal_of_isAlgebraic_residueField_over_field (k := k) (S := S) q.asIdeal
    exact hq_nonmax hq_max

end
