import Mathlib
import Mathlib.Tactic.Recall
import StacksProject_2024.Chap10.Definition_10_60_10

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

open RingTheory Sequence IsLocalRing
open scoped nonZeroDivisors Pointwise

section

variable {R : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]

/- Domain triage:
* primary domain: regular sequences and regular local rings in commutative algebra;
* sampled owner declarations:
  `RingTheory.Sequence.IsRegular`,
  `ringKrullDim_add_length_eq_ringKrullDim_of_isRegular`,
  `ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`,
  `IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`;
* core/canonical owner: `IsRegularLocalRing R` together with the regular-sequence owner
  `Sequence.IsRegular R rs`;
* bridge/view: the quotient rings `R ⧸ Ideal.ofList rs` and `R ⧸ Ideal.span {x}`.

Primitive data here are only the ring `R`, the regular sequence `rs`, and the owner predicates
`IsRegular R rs` and `IsRegularLocalRing`. The singleton quotient dimension-drop statement is
already provided canonically by mathlib, so this file should reuse that owner theorem rather than
keep an unused parallel local wrapper.
-/

/- Companion recall: the singleton nonzerodivisor quotient step is already the canonical mathlib
theorem `ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`. -/
recall ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors

/-- Helper for Lemma 10.106.7: a regular sequence in a local ring lies in the maximal ideal. -/
private theorem regularSequence_ofList_le_maximalIdeal
    {A : Type u} [CommRing A] [IsLocalRing A]
    {M : Type v} [AddCommGroup M] [Module A M] {ts : List A} (hreg : IsRegular M ts) :
    Ideal.ofList ts ≤ maximalIdeal A := by
  -- An element outside the maximal ideal is a unit, which would force the unit ideal and
  -- contradict the nontriviality clause in the definition of a regular sequence.
  refine Ideal.span_le.mpr ?_
  intro x hx
  by_contra hx_not_mem
  have hx_unit : IsUnit x := by
    by_contra hx_not_unit
    exact hx_not_mem (by
      simpa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] using hx_not_unit)
  have hx_mem : x ∈ Ideal.ofList ts := by
    exact Ideal.subset_span hx
  have htop : Ideal.ofList ts = ⊤ :=
    Ideal.eq_top_of_isUnit_mem (Ideal.ofList ts) hx_mem hx_unit
  have hsmul : Ideal.ofList ts • (⊤ : Submodule A M) = ⊤ := by
    simpa [htop]
  exact hreg.top_ne_smul hsmul.symm

/-- Helper for Lemma 10.106.7: adjoining one more maximal-ideal element appends the corresponding
principal ideal to the parameter ideal. -/
private theorem parameterIdeal_snoc_eq_sup
    {A : Type u} [CommRing A] [IsLocalRing A] {d : ℕ}
    (z : Fin d → maximalIdeal A) (x : maximalIdeal A) :
    parameterIdeal (Fin.snoc z x) = Ideal.span ({(x : A)} : Set A) ⊔ parameterIdeal z := by
  -- `Fin.snoc` adds exactly one new generator to the range defining the parameter ideal.
  let w : Fin (d + 1) → maximalIdeal A := Fin.snoc z x
  have hfun :
      (fun i : Fin (d + 1) ↦ ((w i : maximalIdeal A) : A)) =
        Fin.snoc (fun i : Fin d ↦ ((z i : maximalIdeal A) : A)) (x : A) := by
    funext i
    cases i using Fin.lastCases <;> simp [w]
  simpa [w] using
    (show parameterIdeal w = Ideal.span ({(x : A)} : Set A) ⊔ parameterIdeal z by
      rw [parameterIdeal_eq_span, hfun, Fin.range_snoc, Ideal.span_insert, parameterIdeal_eq_span])

/-- Helper for Lemma 10.106.7: the head principal ideal is contained in the ideal generated by the
whole sequence. -/
private theorem full_tail_quotient_ringEquiv_head_le
    {A : Type u} [CommRing A] {r : A} {rs : List A} :
    Ideal.span ({r} : Set A) ≤ Ideal.ofList (r :: rs) := by
  -- The head generator is one of the generators of the full list ideal.
  simpa [Ideal.ofList_cons] using
    (le_sup_left : Ideal.span ({r} : Set A) ≤ Ideal.span ({r} : Set A) ⊔ Ideal.ofList rs)

/-- Helper for Lemma 10.106.7: after quotienting by the head element, the remaining list ideal is
the image of the full ideal. -/
private theorem full_tail_quotient_ringEquiv_map_eq
    {A : Type u} [CommRing A] {r : A} {rs : List A} :
    Ideal.ofList (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))) =
      (Ideal.ofList (r :: rs)).map (Ideal.Quotient.mk (Ideal.span ({r} : Set A))) := by
  -- Modding out by `r` kills the head generator and leaves only the mapped tail.
  rw [Ideal.map_ofList, List.map_cons, Ideal.ofList_cons]
  simp

/-- Helper for Lemma 10.106.7: quotienting first by the head and then by the mapped tail is the
same as quotienting once by the whole list. -/
noncomputable def full_tail_quotient_ringEquiv
    {A : Type u} [CommRing A] {r : A} {rs : List A} :
    ((A ⧸ Ideal.span ({r} : Set A)) ⧸
      Ideal.ofList (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A))))) ≃+*
      A ⧸ Ideal.ofList (r :: rs) :=
  (Ideal.quotEquivOfEq (full_tail_quotient_ringEquiv_map_eq (A := A) (r := r) (rs := rs))).trans
    (DoubleQuot.quotQuotEquivQuotOfLE
      (full_tail_quotient_ringEquiv_head_le (A := A) (r := r) (rs := rs)))

/-- Helper for Lemma 10.106.7: reducing the ring modulo `r` identifies the owner quotient module
`QuotSMulTop r A` with the quotient ring for regularity of the tail sequence. -/
private theorem isRegular_quotSMulTop_iff_quotient_span_singleton
    {A : Type u} [CommRing A] {r : A} {rs : List A} :
    IsRegular (QuotSMulTop r A) rs ↔
      IsRegular (A ⧸ Ideal.span ({r} : Set A))
        (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))) := by
  have hspan : Ideal.span ({r} : Set A) = r • (⊤ : Ideal A) := by
    -- The quotient ring `A ⧸ (r)` is the same quotient object as `A / rA`.
    simp [smul_eq_mul, ← Submodule.ideal_span_singleton_smul]
  let e : QuotSMulTop r A ≃+ A ⧸ Ideal.span ({r} : Set A) :=
    (Ideal.quotientEquivAlgOfEq A hspan).symm.toRingEquiv.toAddEquiv
  -- Transport regularity across the canonical additive equivalence while mapping the scalars by
  -- the quotient map `A → A ⧸ (r)`.
  refine e.isRegular_congr <| List.forall₂_map_right_iff.mpr ?_
  rw [List.forall₂_same]
  intro a ha x
  change e (a • x) = Ideal.Quotient.mk (Ideal.span ({r} : Set A)) a • e x
  rcases Quotient.exists_rep x with ⟨y, rfl⟩
  -- On representatives, the transported scalar action is exactly multiplication by the image of
  -- `a` in the quotient ring.
  rw [Algebra.smul_def, Ideal.Quotient.algebraMap_eq]
  simp [e, smul_eq_mul]

/-- Helper for Lemma 10.106.7: the tail regularity on `QuotSMulTop r A` becomes regularity of the
mapped tail on the quotient ring `A ⧸ Ideal.span {r}`. -/
private theorem quotientTail_isRegular_on_quotientRing
    {A : Type u} [CommRing A] {r : A} {rs : List A}
    (hreg : IsRegular (QuotSMulTop r A) rs) :
    IsRegular (A ⧸ Ideal.span ({r} : Set A))
      (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))) := by
  -- The `_iff` transport lemma packages the canonical quotient identification needed for the
  -- induction step.
  exact (isRegular_quotSMulTop_iff_quotient_span_singleton (A := A) (r := r) (rs := rs)).1 hreg

/-- Helper for Lemma 10.106.7: a single maximal-ideal nonzerodivisor can be adjoined to lifted
parameters from the quotient to recover a regular system of parameters upstairs. -/
private theorem isRegularLocalRing_of_quotient_span_singleton_of_mem_nonZeroDivisors
    {A : Type u} [CommRing A] [IsLocalRing A] [IsNoetherianRing A] {x : A}
    (hx : x ∈ maximalIdeal A) (hxd : x ∈ nonZeroDivisors A)
    (hquot : IsRegularLocalRing (A ⧸ Ideal.span ({x} : Set A))) :
    IsRegularLocalRing A := by
  let I : Ideal A := Ideal.span ({x} : Set A)
  letI : IsRegularLocalRing (A ⧸ I) := by
    simpa [I] using hquot
  let d : ℕ := (maximalIdeal (A ⧸ I)).spanFinrank
  have hdimQ : ringKrullDim (A ⧸ I) = d := by
    simpa [d] using ((isRegularLocalRing_iff (R := A ⧸ I)).1 hquot).symm
  have hx_nonunit : ¬ IsUnit x := by
    rwa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] at hx
  have hI_ne_top : I ≠ ⊤ := by
    intro hI
    exact hx_nonunit (by simpa [I] using (Ideal.span_singleton_eq_top.mp hI))
  have hdimA : ringKrullDim A = d + 1 := by
    -- The dimension-drop theorem measures exactly how much the nonzerodivisor contributes.
    rw [← ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors
      (R := A) hxd hx, hdimQ]
  obtain ⟨y, hy⟩ :=
    (isRegularLocalRing_iff_exists_regularSystemOfParameters (R := A ⧸ I) (d := d) hdimQ).1 hquot
  have hy_parameter : parameterIdeal y = maximalIdeal (A ⧸ I) := by
    -- In the quotient, a regular system of parameters is exactly a generating family of `𝔪`.
    exact (isRegularSystemOfParameters_iff_of_ringKrullDim_eq (R := A ⧸ I) hdimQ y).1 hy
  have hmaxmap : Ideal.map (Ideal.Quotient.mk I) (maximalIdeal A) = maximalIdeal (A ⧸ I) := by
    -- The quotient map identifies the image of the maximal ideal with the quotient maximal ideal.
    exact IsLocalRing.map_maximalIdeal_of_surjective (Ideal.Quotient.mk I)
      Ideal.Quotient.mk_surjective
  choose z hz_mem hz_eq using fun i : Fin d ↦ by
    have hyi :
        ((y i : maximalIdeal (A ⧸ I)) : A ⧸ I) ∈ Ideal.map (Ideal.Quotient.mk I) (maximalIdeal A) := by
      simpa [hmaxmap] using (y i).property
    exact (Ideal.mem_map_iff_of_surjective (Ideal.Quotient.mk I)
      Ideal.Quotient.mk_surjective).1 hyi
  let zLift : Fin d → maximalIdeal A := fun i ↦ ⟨z i, hz_mem i⟩
  have hz_image :
      (Ideal.Quotient.mk I) '' Set.range (fun i : Fin d ↦ ((zLift i : maximalIdeal A) : A)) =
        Set.range (fun i : Fin d ↦ ((y i : maximalIdeal (A ⧸ I)) : A ⧸ I)) := by
    -- The chosen lifts project back to the original quotient parameters coordinatewise.
    ext q
    constructor
    · rintro ⟨a, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, by simpa [zLift] using (hz_eq i).symm⟩
    · rintro ⟨i, rfl⟩
      exact ⟨((zLift i : maximalIdeal A) : A), ⟨i, rfl⟩, by simpa [zLift] using hz_eq i⟩
  have hz_parameter_map : Ideal.map (Ideal.Quotient.mk I) (parameterIdeal zLift) = parameterIdeal y := by
    -- Mapping the lifted parameter family recovers exactly the quotient parameter family.
    rw [parameterIdeal_eq_span, parameterIdeal_eq_span, Ideal.map_span, hz_image]
  have hz_parameter_sup : parameterIdeal zLift ⊔ I = maximalIdeal A := by
    -- Taking the preimage of the quotient maximal ideal adds back only the kernel `(x)`.
    calc
      parameterIdeal zLift ⊔ I =
          Ideal.comap (Ideal.Quotient.mk I) (Ideal.map (Ideal.Quotient.mk I) (parameterIdeal zLift)) := by
            rw [Ideal.comap_map_of_surjective (Ideal.Quotient.mk I)
              Ideal.Quotient.mk_surjective, ← RingHom.ker_eq_comap_bot, Ideal.mk_ker]
      _ = Ideal.comap (Ideal.Quotient.mk I) (maximalIdeal (A ⧸ I)) := by
        rw [hz_parameter_map, hy_parameter]
      _ = maximalIdeal A := by
        rw [← hmaxmap, Ideal.comap_map_of_surjective (Ideal.Quotient.mk I)
          Ideal.Quotient.mk_surjective, ← RingHom.ker_eq_comap_bot, Ideal.mk_ker,
          sup_eq_left.mpr (le_maximalIdeal hI_ne_top)]
  let w : Fin (d + 1) → maximalIdeal A := Fin.snoc zLift ⟨x, hx⟩
  have hw_parameter : parameterIdeal w = maximalIdeal A := by
    -- Adjoining `x` to the lifted quotient parameters now generates the whole maximal ideal.
    calc
      parameterIdeal w = Ideal.span ({x} : Set A) ⊔ parameterIdeal zLift := by
        simpa [w] using parameterIdeal_snoc_eq_sup (z := zLift) ⟨x, hx⟩
      _ = maximalIdeal A := by
        simpa [I, sup_comm] using hz_parameter_sup
  have hw_regular : IsRegularSystemOfParameters w := by
    -- The dimension count from the singleton quotient theorem upgrades the generating family to a
    -- full regular system of parameters upstairs.
    exact (isRegularSystemOfParameters_iff_of_ringKrullDim_eq (R := A) hdimA w).2 hw_parameter
  -- A regular system of parameters of the correct length is exactly the regular-local condition.
  exact (isRegularLocalRing_iff_exists_regularSystemOfParameters (R := A) (d := d + 1) hdimA).2
    ⟨w, hw_regular⟩

/-- Helper for Lemma 10.106.7: regular-locality lifts along a regular sequence by induction on the
length of the sequence. -/
private theorem isRegularLocalRing_of_quotient_of_isRegular_length
    (n : ℕ) :
    ∀ {A : Type u} [CommRing A] [IsLocalRing A] [IsNoetherianRing A]
      {ts : List A}, ts.length = n → IsRegular A ts →
      IsRegularLocalRing (A ⧸ Ideal.ofList ts) → IsRegularLocalRing A := by
  induction n with
  | zero =>
      intro A _ _ _ ts hlen _ hquot
      cases ts with
      | nil =>
          -- For the empty sequence, the quotient is definitionally the ring itself.
          letI : IsRegularLocalRing (A ⧸ Ideal.ofList ([] : List A)) := hquot
          letI : IsRegularLocalRing (A ⧸ (⊥ : Ideal A)) := by
            exact IsRegularLocalRing.of_ringEquiv
              (Ideal.quotEquivOfEq (Ideal.ofList_nil (R := A)))
          simpa [Ideal.ofList_nil] using
            (IsRegularLocalRing.of_ringEquiv (RingEquiv.quotientBot A))
      | cons r rs =>
          cases hlen
  | succ n ih =>
      intro A _ _ _ ts hlen hreg hquot
      cases ts with
      | nil =>
          cases hlen
      | cons r rs =>
          have hlen_tail : rs.length = n := by
            simpa using Nat.succ.inj hlen
          -- Route correction: use the unmapped-tail form `isRegular_cons_iff` so the tail lives on
          -- `QuotSMulTop r A` before transporting it to the quotient ring.
          rcases (isRegular_cons_iff (M := A) r rs).1 hreg with ⟨hr_regular, hrs_regular⟩
          have hr_mem : r ∈ maximalIdeal A := by
            -- The head of a regular sequence cannot be a unit in a local ring.
            have hle : Ideal.ofList (r :: rs) ≤ maximalIdeal A :=
              regularSequence_ofList_le_maximalIdeal
                (A := A) (M := A) (ts := r :: rs) hreg
            exact hle (Ideal.subset_span (by simp))
          have hspan_ne_top : Ideal.span ({r} : Set A) ≠ ⊤ := by
            intro htop
            have hr_nonunit : ¬ IsUnit r := by
              rwa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff] at hr_mem
            exact hr_nonunit (Ideal.span_singleton_eq_top.mp htop)
          letI : Nontrivial (A ⧸ Ideal.span ({r} : Set A)) :=
            Ideal.Quotient.nontrivial_iff.mpr hspan_ne_top
          letI : IsLocalRing (A ⧸ Ideal.span ({r} : Set A)) :=
            IsLocalRing.of_surjective' (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))
              Ideal.Quotient.mk_surjective
          have hrs_regular' :
              IsRegular (A ⧸ Ideal.span ({r} : Set A))
                (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))) := by
            -- Transport the tail regularity from the owner quotient module to the quotient ring.
            exact quotientTail_isRegular_on_quotientRing hrs_regular
          have hquot_tail :
              IsRegularLocalRing
                (((A ⧸ Ideal.span ({r} : Set A)) ⧸
                  Ideal.ofList (rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A)))))) := by
            -- The tail induction hypothesis expects the iterated quotient presentation.
            letI : IsRegularLocalRing (A ⧸ Ideal.ofList (r :: rs)) := hquot
            exact IsRegularLocalRing.of_ringEquiv
              (full_tail_quotient_ringEquiv (A := A) (r := r) (rs := rs)).symm
          have hquot_head : IsRegularLocalRing (A ⧸ Ideal.span ({r} : Set A)) := by
            -- The mapped tail has length `n`, so the induction hypothesis applies in the quotient.
            exact ih (A := A ⧸ Ideal.span ({r} : Set A))
              (ts := rs.map (Ideal.Quotient.mk (Ideal.span ({r} : Set A))))
              (by simpa using hlen_tail) hrs_regular' hquot_tail
          have hr_nonZero : r ∈ nonZeroDivisors A := by
            -- For the ring module itself, regularity of multiplication by `r` means that `r` is a
            -- nonzerodivisor in the ordinary ring-theoretic sense.
            have hr_isRegular : IsRegular r := by
              exact (Commute.isRegular_iff (a := r)
                (fun s ↦ by simpa [Commute] using (mul_comm r s))).2 hr_regular.isLeftRegular
            exact isRegular_iff_mem_nonZeroDivisors.mp hr_isRegular
          exact isRegularLocalRing_of_quotient_span_singleton_of_mem_nonZeroDivisors
            hr_mem hr_nonZero hquot_head

-- Proof sketch: induct on the regular sequence `rs`. The empty sequence is tautological. For
-- `x :: rs`, the regularity hypothesis gives that `x` is a nonzerodivisor and that the tail is a
-- regular sequence on `R ⧸ Ideal.span ({x} : Set R)`. Apply the induction hypothesis to the tail,
-- then use the canonical singleton dimension-drop theorem
-- `ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`; combine the
-- resulting dimension identities with `IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`.
/-- Lemma 10.106.7: if `rs` is a regular sequence in a Noetherian local ring `R` and
`R ⧸ Ideal.ofList rs` is a regular local ring, then `R` is a regular local ring. -/
theorem isRegularLocalRing_of_quotient_of_isRegular {rs : List R} (hreg : IsRegular R rs)
    (hquot : IsRegularLocalRing (R ⧸ Ideal.ofList rs)) :
    IsRegularLocalRing R := by
  -- We follow the source proof: first handle one nonzerodivisor, then iterate that step along the
  -- regular sequence by induction on its length.
  exact isRegularLocalRing_of_quotient_of_isRegular_length
    (A := R) (ts := rs) rs.length rfl hreg hquot

end
