import Mathlib
import StacksProject_2024.Chap10.Definition_10_69_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

namespace RingTheory.Sequence

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M]

namespace IsQuasiRegular

/-- Lemma 10.69.5: if `rs` is an `M`-quasi-regular sequence, then after quotienting `R` by the
ideal generated by the first `i` terms and quotienting `M` by the corresponding submodule, the
remaining tail sequence is quasi-regular on the quotient module. -/
theorem tail_quotient {rs : List R} (hqr : IsQuasiRegular M rs) (i : ℕ) :
    IsQuasiRegular (M ⧸ (Ideal.ofList (rs.take i) • (⊤ : Submodule R M)))
      ((rs.drop i).map (Ideal.Quotient.mk (Ideal.ofList (rs.take i)))) := by
  -- This is the quotient-by-prefix stability statement for quasi-regular sequences.
  admit

end IsQuasiRegular

end RingTheory.Sequence
