import Mathlib.RingTheory.Ideal.Pure
import Mathlib.Tactic.TFAE
import StacksProject_2024.Chap05.Lemma_5_12_12
import StacksProject_2024.Chap10.Lemma_10_21_3

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open PrimeSpectrum

section

variable {R : Type u} [CommRing R]

namespace Ideal

/-- An ideal is generated by idempotents if it is spanned by its idempotent elements. -/
def IsGeneratedByIdempotents (I : Ideal R) : Prop :=
  Ideal.span {e : R | IsIdempotentElem e ∧ e ∈ I} = I

/-- The span of idempotents is generated by idempotents. -/
private theorem isGeneratedByIdempotents_span {S : Set R} (hS : ∀ e ∈ S, IsIdempotentElem e) :
    (Ideal.span S : Ideal R).IsGeneratedByIdempotents := by
  rw [IsGeneratedByIdempotents]
  refine le_antisymm ?_ ?_
  · exact Ideal.span_le.2 fun e he ↦ he.2
  · exact Ideal.span_mono fun e he ↦ ⟨hS e he, Ideal.subset_span he⟩

/-- Helper for Lemma 10.22.1: an ideal generated by idempotents is an idempotent ideal. -/
private theorem isIdempotentElem_of_isGeneratedByIdempotents {I : Ideal R}
    (hI : I.IsGeneratedByIdempotents) : IsIdempotentElem I := by
  rw [Ideal.IsGeneratedByIdempotents] at hI
  rw [IsIdempotentElem]
  refine le_antisymm (Ideal.mul_le_inf.trans inf_le_left) ?_
  -- Every idempotent generator already lies in `I * I`.
  rw [← hI]
  refine Ideal.span_le.2 fun e he ↦ ?_
  rw [← he.1.eq]
  exact Ideal.mul_mem_mul (Ideal.subset_span he) (Ideal.subset_span he)

-- Proof sketch: use the Stacks criterion behind this lemma to show that such an ideal satisfies the
-- finite-generation test for purity, reducing generators one idempotent at a time.
/-- An ideal generated by idempotents is pure. -/
theorem IsGeneratedByIdempotents.pure {I : Ideal R} (hI : I.IsGeneratedByIdempotents) :
    I.Pure := by
  rw [Ideal.IsGeneratedByIdempotents] at hI
  refine Ideal.Pure.of_inf_eq_mul I ?_
  intro J hJ
  refine le_antisymm ?_ Ideal.mul_le_inf
  intro x hx
  -- Reduce `x ∈ I` to a finite span of idempotent generators inside `I`.
  have hxspan : x ∈ Ideal.span {e : R | IsIdempotentElem e ∧ e ∈ I} := by
    simpa [hI] using hx.1
  obtain ⟨s, hs, hxs⟩ := Submodule.mem_span_finite_of_mem_span hxspan
  let K : Ideal R := Ideal.span (s : Set R)
  have hKle : K ≤ I := by
    -- The finite auxiliary ideal still lies inside `I`.
    refine Ideal.span_le.2 fun e he ↦ (hs he).2
  have hKidempotents : ∀ e ∈ (s : Set R), IsIdempotentElem e := by
    intro e he
    exact (hs he).1
  have hKgenerated : K.IsGeneratedByIdempotents := by
    -- The finite auxiliary ideal is itself generated by idempotents.
    simpa [K] using isGeneratedByIdempotents_span hKidempotents
  have hKfg : K.FG := by
    -- Finite spans are finitely generated.
    simpa [K] using (Submodule.fg_span (s := (s : Set R)) s.finite_toSet)
  have hKidem : IsIdempotentElem K :=
    isIdempotentElem_of_isGeneratedByIdempotents hKgenerated
  let _ : K.Pure := Ideal.Pure.of_isIdempotentElem hKfg hKidem
  have hxKJ : x ∈ K * J := by
    -- Purity turns membership in `K ∩ J` into membership in `K * J`.
    rw [← Ideal.inf_eq_mul_of_pure K J]
    exact ⟨hxs, hx.2⟩
  exact (Ideal.mul_mono_left hKle) hxKJ

end Ideal

variable (T : Set (PrimeSpectrum R))

/- Domain-style sampling:
- primary domain: commutative algebra and prime-spectrum topology for closed unions of connected
  components, clopen subsets, and pure ideals;
- same-domain owner declarations inspected:
  `isClosed_of_isIntersectionOfClopens`,
  `isIntersectionOfClopens_of_isClosed_of_union_connectedComponents`,
  `Ideal.Pure`,
  `Ideal.zeroLocus_inj_of_pure`;
- best owner abstraction:
  `source-facing`: `Ideal.IsGeneratedByIdempotents` for the new ideal-side clause in this file;
  `core/canonical`: the chapter-5 clopen/connected-component theorems and the mathlib owner
    `Ideal.Pure`;
  `bridge/view`: the existential `⋂₀` presentation of `T` and the uniqueness statement obtained
    from `Ideal.zeroLocus_inj_of_pure`.

Primitive data are only the ring `R`, the subset `T : Set (PrimeSpectrum R)`, and the ideal
`I : Ideal R`. The clopen-intersection clause and the pure-ideal uniqueness step are derived from
the existing owners above, so the only owner this file needs to keep locally is the source-facing
predicate `Ideal.IsGeneratedByIdempotents`. -/

/-- Helper for Lemma 10.22.1: an intersection of clopen subsets of `Spec(R)` is the zero locus of
an ideal generated by idempotents. -/
private theorem exists_ideal_isGeneratedByIdempotents_of_sInter_clopens
    {T : Set (PrimeSpectrum R)}
    (hT : ∃ S : Set (Set (PrimeSpectrum R)), (∀ Z ∈ S, IsClopen Z) ∧ T = ⋂₀ S) :
    ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I := by
  classical
  rcases hT with ⟨S, hSclopen, rfl⟩
  let E : Set R := {e : R | ∃ Z ∈ S, IsIdempotentElem e ∧ Z = zeroLocus ({e} : Set R)}
  refine ⟨Ideal.span E, ?_, ?_⟩
  · -- By construction, the chosen generators are idempotent.
    refine Ideal.isGeneratedByIdempotents_span ?_
    intro e he
    rcases he with ⟨Z, hZ, heidem, _⟩
    exact heidem
  · -- A prime belongs to the intersection exactly when it contains every chosen idempotent.
    ext p
    constructor
    · intro hp
      rw [PrimeSpectrum.mem_zeroLocus]
      refine Ideal.span_le.2 fun e he ↦ ?_
      rcases he with ⟨Z, hZ, _, hZeq⟩
      rw [Set.mem_sInter] at hp
      have hpZ : p ∈ Z := hp Z hZ
      rwa [hZeq, PrimeSpectrum.mem_zeroLocus, Set.singleton_subset_iff] at hpZ
    · intro hp
      rw [Set.mem_sInter]
      intro Z hZ
      rcases PrimeSpectrum.isClopen_iff_zeroLocus.mp (hSclopen Z hZ) with ⟨e, he, hZeq⟩
      rw [hZeq, PrimeSpectrum.mem_zeroLocus, Set.singleton_subset_iff]
      rw [PrimeSpectrum.mem_zeroLocus] at hp
      exact hp (Ideal.subset_span ⟨Z, hZ, he, hZeq⟩)

/-- Helper for Lemma 10.22.1: the zero locus of an idempotent-generated ideal is an intersection
of clopen subsets of `Spec(R)`. -/
private theorem sInter_clopens_of_zeroLocus_isGeneratedByIdempotents
    {I : Ideal R} (hI : I.IsGeneratedByIdempotents) :
    ∃ S : Set (Set (PrimeSpectrum R)), (∀ Z ∈ S, IsClopen Z) ∧ zeroLocus I = ⋂₀ S := by
  classical
  rw [Ideal.IsGeneratedByIdempotents] at hI
  let S : Set (Set (PrimeSpectrum R)) :=
    {Z : Set (PrimeSpectrum R) | ∃ e : R, IsIdempotentElem e ∧ e ∈ I ∧ Z = zeroLocus ({e} : Set R)}
  refine ⟨S, ?_, ?_⟩
  · intro Z hZ
    rcases hZ with ⟨e, he, _, rfl⟩
    exact (PrimeSpectrum.isClopen_iff_zeroLocus).2 ⟨e, he, rfl⟩
  · -- The defining idempotents of `I` cut out exactly `V(I)`.
    ext p
    constructor
    · intro hp
      rw [PrimeSpectrum.mem_zeroLocus] at hp
      rw [Set.mem_sInter]
      intro Z hZ
      rcases hZ with ⟨e, he, heI, rfl⟩
      rw [PrimeSpectrum.mem_zeroLocus, Set.singleton_subset_iff]
      exact hp heI
    · intro hp
      rw [PrimeSpectrum.mem_zeroLocus]
      rw [← hI]
      refine Ideal.span_le.2 fun e he ↦ ?_
      rw [Set.mem_sInter] at hp
      have hpZ : p ∈ zeroLocus ({e} : Set R) :=
        hp (zeroLocus ({e} : Set R)) ⟨e, he.1, he.2, rfl⟩
      rwa [PrimeSpectrum.mem_zeroLocus, Set.singleton_subset_iff] at hpZ

-- Proof sketch: `(1) ↔ (2)` is the spectral-space topology statement that closed unions of
-- connected components are exactly intersections of clopens by
-- `isClosed_of_isIntersectionOfClopens`,
-- `connectedComponent_subset_of_isIntersectionOfClopens`, and
-- `isIntersectionOfClopens_of_isClosed_of_union_connectedComponents`. For `(2) → (3)`, write
-- each clopen as `D(e)` using Lemma 10.21.3 and rewrite the intersection as the zero locus of the
-- ideal generated by the complementary idempotents. For `(3) → (2)`, express `V(I)` as the
-- intersection of the clopens `V(e) = D(1 - e)` coming from idempotent generators of `I`.
/-- Lemma 10.22.1 (1): for a subset `T ⊆ Spec(R)`, the following are equivalent: `T` is closed and a
union of connected components of `Spec(R)`; `T` is an intersection of open and closed subsets of
`Spec(R)`; and `T = V(I)` for an ideal `I` of `R` generated by idempotents. -/
theorem primeSpectrum_tfae_closed_union_components_sInter_clopens_zeroLocus_generatedByIdempotents :
    List.TFAE
      [ IsClosed T ∧ ∀ x ∈ T, connectedComponent x ⊆ T
      , ∃ S : Set (Set (PrimeSpectrum R)), (∀ Z ∈ S, IsClopen Z) ∧ T = ⋂₀ S
      , ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I ] := by
  -- The source proof factors through clopen intersections.
  tfae_have 1 ↔ 2 := by
    constructor
    · intro hT
      -- Closed component-saturated subsets are intersections of clopens.
      exact isIntersectionOfClopens_of_isClosed_of_union_connectedComponents hT.1 hT.2
    · intro hT
      -- Intersections of clopens are closed and component-saturated.
      refine ⟨isClosed_of_isIntersectionOfClopens hT, ?_⟩
      intro x hx
      exact connectedComponent_subset_of_isIntersectionOfClopens hT x hx
  tfae_have 2 → 3 := by
    intro hT
    -- Choose an idempotent equation for each clopen factor and span the corresponding generators.
    exact exists_ideal_isGeneratedByIdempotents_of_sInter_clopens hT
  tfae_have 3 → 2 := by
    rintro ⟨I, hI, hzero⟩
    -- A zero locus of an idempotent-generated ideal is the intersection of the clopen singleton
    -- zero loci of its idempotent generators.
    obtain ⟨S, hS, hSzero⟩ := sInter_clopens_of_zeroLocus_isGeneratedByIdempotents hI
    exact ⟨S, hS, hzero.trans hSzero⟩
  tfae_finish

/-- If `T ⊆ Spec(R)` is closed and a union of connected components, then `T = V(I)` for an ideal
generated by idempotents. -/
theorem exists_ideal_isGeneratedByIdempotents_zeroLocus_eq
    (hT : IsClosed T ∧ ∀ x ∈ T, connectedComponent x ⊆ T) :
    ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I :=
  ((primeSpectrum_tfae_closed_union_components_sInter_clopens_zeroLocus_generatedByIdempotents
    T).out 0 2).mp hT

-- Proof sketch: any ideal generated by idempotents is pure, so uniqueness follows from
-- `Ideal.zeroLocus_inj_of_pure` once two such ideals define the same closed subset of `Spec(R)`.
/-- Lemma 10.22.1 (2): if `T = V(I)` for an ideal `I` generated by idempotents, then `I` is unique. -/
theorem existsUnique_ideal_isGeneratedByIdempotents_zeroLocus_eq
    (hT : ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I) :
    ∃! I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I := by
  rcases hT with ⟨I, hI, hzero⟩
  refine ⟨I, ⟨hI, hzero⟩, fun J hJ ↦ ?_⟩
  let _ : I.Pure := hI.pure
  let _ : J.Pure := hJ.1.pure
  exact ((Ideal.zeroLocus_inj_of_pure).mp <| by
    simpa [hzero] using hJ.2).symm

end
