import Mathlib
import stacks_project.Chap10.Definition_10_63_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open MvPolynomial IsLocalRing

/-- The quotient ring `k[x₁, x₂, x₃, \ldots]/(x_i^2)` from the counterexample in
Stacks, Remark 10.63.12 (`05BX`). -/
abbrev infiniteSquareZeroPolynomialQuotient (k : Type u) [CommRing k] :=
  MvPolynomial ℕ k ⧸ Ideal.span (Set.range fun i : ℕ ↦ ((X i : MvPolynomial ℕ k) ^ 2))

section

variable (k : Type u) [Field k]

local notation "I∞" =>
  Ideal.span (Set.range fun i : ℕ ↦ ((X i : MvPolynomial ℕ k) ^ 2))
local notation "S∞" => infiniteSquareZeroPolynomialQuotient k

-- Keep the quotient ring's canonical self-module structure local so theorem statements elaborate
-- without exposing any extra public API.
noncomputable local instance : Module S∞ S∞ :=
  Semiring.toModule

/-- The augmentation `k[x₁, x₂, x₃, \ldots] / (x_i^2) → k` given by the constant coefficient. -/
noncomputable def infiniteSquareZeroPolynomialQuotientAugmentation : S∞ →+* k :=
  Ideal.Quotient.lift I∞ MvPolynomial.constantCoeff <| by
    intro p hp
    have hker : I∞ ≤ RingHom.ker (MvPolynomial.constantCoeff : MvPolynomial ℕ k →+* k) := by
      rw [Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      simp [RingHom.mem_ker]
    simpa [RingHom.mem_ker] using hker hp

/-- The augmentation `k[x₁, x₂, x₃, \ldots] / (x_i^2) → k` is surjective. -/
theorem infiniteSquareZeroPolynomialQuotientAugmentation_surjective :
    Function.Surjective (infiniteSquareZeroPolynomialQuotientAugmentation k) := by
  intro a
  refine ⟨Ideal.Quotient.mk I∞ (MvPolynomial.C a), ?_⟩
  simp [infiniteSquareZeroPolynomialQuotientAugmentation]

/-- Helper for Remark 10.63.12: the square-zero relation ideal is the monomial ideal generated by
the square monomials `X_i^2 = monomial (single i 2) 1`. -/
private theorem relation_ideal_eq_square_monomial_span :
    I∞ =
      Ideal.span ((fun s : ℕ →₀ ℕ ↦ MvPolynomial.monomial s (1 : k)) ''
        Set.range (fun i : ℕ ↦ Finsupp.single i 2)) := by
  change Ideal.span (Set.range fun i : ℕ ↦ (MvPolynomial.X i : MvPolynomial ℕ k) ^ 2) =
    Ideal.span ((fun s : ℕ →₀ ℕ ↦ MvPolynomial.monomial s (1 : k)) ''
      Set.range (fun i : ℕ ↦ Finsupp.single i 2))
  congr 1
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨Finsupp.single i 2, ⟨i, rfl⟩, by simp [MvPolynomial.X_pow_eq_monomial]⟩
  · rintro ⟨s, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, by simp [MvPolynomial.X_pow_eq_monomial]⟩

/-- Helper for Remark 10.63.12: every nonconstant monomial has square in the relation ideal. -/
private theorem monomial_sq_mem_relation_ideal_of_ne_zero
    {d : ℕ →₀ ℕ} (hd : d ≠ 0) (a : k) :
    (MvPolynomial.monomial d a : MvPolynomial ℕ k) ^ 2 ∈ I∞ := by
  classical
  rw [relation_ideal_eq_square_monomial_span (k := k)]
  rw [pow_two, MvPolynomial.monomial_mul, MvPolynomial.mem_ideal_span_monomial_image_iff_dvd]
  intro xi hxi
  by_cases ha : a = 0
  · simp [ha] at hxi
  · have haa : a * a ≠ 0 := mul_ne_zero ha ha
    have hxi_eq : xi = d + d := by
      simpa [MvPolynomial.support_monomial, haa] using hxi
    subst hxi_eq
    obtain ⟨i, hi⟩ := Finsupp.support_nonempty_iff.mpr hd
    have hi_pos : 1 ≤ d i := Nat.succ_le_of_lt (Nat.pos_of_ne_zero (Finsupp.mem_support_iff.mp hi))
    have hi_two : 2 ≤ (d + d) i := by
      simpa [Finsupp.add_apply] using add_le_add hi_pos hi_pos
    have hi_le : Finsupp.single i 2 ≤ d + d := by
      simpa [Finsupp.single_le_iff] using hi_two
    refine ⟨Finsupp.single i 2, ⟨i, rfl⟩, ?_⟩
    rw [MvPolynomial.monomial_dvd_monomial]
    exact ⟨Or.inr hi_le, one_dvd _⟩

/-- Helper for Remark 10.63.12: each nonconstant monomial class in the quotient is nilpotent,
indeed square-zero. -/
private theorem quotient_mk_monomial_isNilpotent_of_ne_zero
    {d : ℕ →₀ ℕ} (hd : d ≠ 0) (a : k) :
    IsNilpotent (Ideal.Quotient.mk I∞ (MvPolynomial.monomial d a) : S∞) := by
  refine ⟨2, ?_⟩
  -- The square vanishes because it lies in the defining monomial square ideal.
  simpa [map_pow] using
    (Ideal.Quotient.eq_zero_iff_mem).2
      (monomial_sq_mem_relation_ideal_of_ne_zero (k := k) hd a)

/-- Helper for Remark 10.63.12: augmentation-zero classes are nilpotent because they are finite
sums of nonconstant monomial classes. -/
private theorem quotient_mk_isNilpotent_of_constantCoeff_zero
    (p : MvPolynomial ℕ k) (hp : MvPolynomial.constantCoeff p = 0) :
    IsNilpotent (Ideal.Quotient.mk I∞ p : S∞) := by
  classical
  -- Expand the representative as a finite sum of support monomials and use nilpotence termwise.
  have hsum :
      (Ideal.Quotient.mk I∞ p : S∞) =
        ∑ d ∈ p.support, (Ideal.Quotient.mk I∞ (MvPolynomial.monomial d (p.coeff d)) : S∞) := by
    calc
      (Ideal.Quotient.mk I∞ p : S∞) =
          Ideal.Quotient.mk I∞ (∑ d ∈ p.support, MvPolynomial.monomial d (p.coeff d)) := by
            simpa using congrArg (Ideal.Quotient.mk I∞) (MvPolynomial.as_sum p)
      _ = ∑ d ∈ p.support, (Ideal.Quotient.mk I∞ (MvPolynomial.monomial d (p.coeff d)) : S∞) := by
            rw [map_sum]
  rw [hsum]
  apply isNilpotent_sum
  intro d hd
  have hd_ne_zero : d ≠ 0 := by
    intro hd0
    have hcoeff : p.coeff d ≠ 0 := MvPolynomial.mem_support_iff.mp hd
    exact hcoeff (by simpa [MvPolynomial.constantCoeff, hd0] using hp)
  exact quotient_mk_monomial_isNilpotent_of_ne_zero (k := k) hd_ne_zero (p.coeff d)

/-- Helper for Remark 10.63.12: a nonzero class has a support monomial not divisible by any
square monomial. -/
private theorem exists_squarefree_support_of_not_mem_relation_ideal
    {p : MvPolynomial ℕ k} (hp : p ∉ I∞) :
    ∃ d ∈ p.support, ∀ j : ℕ, ¬ Finsupp.single j 2 ≤ d := by
  classical
  by_contra h
  push Not at h
  apply hp
  rw [relation_ideal_eq_square_monomial_span (k := k)]
  rw [MvPolynomial.mem_ideal_span_monomial_image]
  intro d hd
  obtain ⟨j, hj⟩ := h d hd
  exact ⟨Finsupp.single j 2, ⟨j, rfl⟩, hj⟩

/-- Helper for Remark 10.63.12: every nonzero class is multiplied nontrivially by some fresh
square-zero variable class. -/
private theorem exists_square_zero_variable_mul_ne_zero_of_ne_zero
    {p : MvPolynomial ℕ k} (hp : (Ideal.Quotient.mk I∞ p : S∞) ≠ 0) :
    ∃ i : ℕ, (Ideal.Quotient.mk I∞ (MvPolynomial.X i) : S∞) ^ 2 = 0 ∧
      (Ideal.Quotient.mk I∞ (MvPolynomial.X i) : S∞) * Ideal.Quotient.mk I∞ p ≠ 0 := by
  classical
  have hp_not_mem : p ∉ I∞ := by
    simpa [Ideal.Quotient.eq_zero_iff_mem] using hp
  obtain ⟨d, hd, hd_squarefree⟩ :=
    exists_squarefree_support_of_not_mem_relation_ideal (k := k) hp_not_mem
  let i : ℕ := p.vars.sup id + 1
  have hi_not_mem_vars : i ∉ p.vars := by
    intro hi
    have hle : i ≤ p.vars.sup (fun n : ℕ => n) := by
      simpa using (Finset.le_sup (f := fun n : ℕ => n) hi)
    have hle' : p.vars.sup (fun n : ℕ => n) + 1 ≤ p.vars.sup (fun n : ℕ => n) := by
      simpa [i] using hle
    exact Nat.not_succ_le_self _ hle'
  have hdi_zero : d i = 0 := by
    by_contra hdi
    have hdi_mem : i ∈ d.support := Finsupp.mem_support_iff.mpr hdi
    have hi_mem_vars : i ∈ p.vars := (MvPolynomial.mem_vars i).2 ⟨d, hd, hdi_mem⟩
    exact hi_not_mem_vars hi_mem_vars
  have hXi_sq_zero : (Ideal.Quotient.mk I∞ (MvPolynomial.X i) : S∞) ^ 2 = 0 := by
    -- Each variable square is one of the defining relations.
    have hXi_sq_mem : (MvPolynomial.X i : MvPolynomial ℕ k) ^ 2 ∈ I∞ := by
      exact Ideal.subset_span ⟨i, rfl⟩
    simpa [map_pow] using
      (Ideal.Quotient.eq_zero_iff_mem).2 hXi_sq_mem
  let m : ℕ →₀ ℕ := Finsupp.single i 1 + d
  have hm_support : m ∈ (MvPolynomial.X i * p).support := by
    rw [MvPolynomial.mem_support_iff]
    simpa [m, MvPolynomial.coeff_X_mul] using (MvPolynomial.mem_support_iff.mp hd)
  have hm_no_square : ∀ j : ℕ, ¬ Finsupp.single j 2 ≤ m := by
    intro j hle
    by_cases hji : j = i
    · have hj_two : 2 ≤ m i := by
        simpa [m, hji, Finsupp.single_le_iff] using hle
      have : ¬ 2 ≤ m i := by
        simpa [m, Finsupp.add_apply, hdi_zero]
      exact this hj_two
    · have hj_two : 2 ≤ m j := by
        simpa [m, Finsupp.single_le_iff] using hle
      have hsingle_le : Finsupp.single j 2 ≤ d := by
        simpa [m, Finsupp.add_apply, hji, Finsupp.single_le_iff] using hj_two
      exact hd_squarefree j hsingle_le
  have hmul_not_mem : MvPolynomial.X i * p ∉ I∞ := by
    intro hmul_mem
    rw [relation_ideal_eq_square_monomial_span (k := k),
      MvPolynomial.mem_ideal_span_monomial_image] at hmul_mem
    rcases hmul_mem m hm_support with ⟨s, hs, hsle⟩
    rcases hs with ⟨j, rfl⟩
    exact hm_no_square j hsle
  refine ⟨i, hXi_sq_zero, ?_⟩
  intro hmul_zero
  apply hmul_not_mem
  exact (Ideal.Quotient.eq_zero_iff_mem).1 (by simpa [map_mul] using hmul_zero)

/-- An element of the infinite square-zero polynomial quotient is a unit exactly when its
augmentation is nonzero. -/
theorem infiniteSquareZeroPolynomialQuotient_isUnit_iff_augmentation_ne_zero (x : S∞) :
    IsUnit x ↔ infiniteSquareZeroPolynomialQuotientAugmentation k x ≠ 0 := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  constructor
  · intro hx
    -- Units remain units under the augmentation, and units in a field are exactly the nonzero
    -- elements.
    exact isUnit_iff_ne_zero.mp <|
      RingHom.isUnit_map (infiniteSquareZeroPolynomialQuotientAugmentation k) hx
  · intro hx
    have hconst : MvPolynomial.constantCoeff p ≠ 0 := by
      simpa [infiniteSquareZeroPolynomialQuotientAugmentation] using hx
    have hnil :
        IsNilpotent
          (Ideal.Quotient.mk I∞ (p - MvPolynomial.C (MvPolynomial.constantCoeff p)) : S∞) := by
      -- The augmentation-zero remainder is nilpotent by the monomial decomposition helper.
      apply quotient_mk_isNilpotent_of_constantCoeff_zero (k := k)
      simp [MvPolynomial.constantCoeff]
    have hconst_unit :
        IsUnit (Ideal.Quotient.mk I∞ (MvPolynomial.C (MvPolynomial.constantCoeff p)) : S∞) := by
      -- The constant term is a nonzero scalar from the base field, hence a unit.
      refine RingHom.isUnit_map (Ideal.Quotient.mk I∞) ?_
      exact RingHom.isUnit_map MvPolynomial.C (isUnit_iff_ne_zero.mpr hconst)
    -- Split into constant term plus nilpotent remainder.
    have hp_split :
        (Ideal.Quotient.mk I∞ p : S∞) =
          Ideal.Quotient.mk I∞ (MvPolynomial.C (MvPolynomial.constantCoeff p)) +
            Ideal.Quotient.mk I∞ (p - MvPolynomial.C (MvPolynomial.constantCoeff p)) := by
      calc
        (Ideal.Quotient.mk I∞ p : S∞) =
            Ideal.Quotient.mk I∞
              (MvPolynomial.C (MvPolynomial.constantCoeff p) +
                (p - MvPolynomial.C (MvPolynomial.constantCoeff p))) := by
                  congr 1
                  simp [sub_eq_add_neg, add_left_comm]
        _ =
            Ideal.Quotient.mk I∞ (MvPolynomial.C (MvPolynomial.constantCoeff p)) +
              Ideal.Quotient.mk I∞ (p - MvPolynomial.C (MvPolynomial.constantCoeff p)) := by
                  rw [map_add]
    rw [hp_split]
    exact hnil.isUnit_add_left_of_commute hconst_unit (Commute.all _ _)

instance : IsLocalRing S∞ := by
  letI : Nontrivial S∞ := (infiniteSquareZeroPolynomialQuotientAugmentation k).domain_nontrivial
  refine IsLocalRing.of_isUnit_or_isUnit_one_sub_self fun x ↦ ?_
  by_cases hx : infiniteSquareZeroPolynomialQuotientAugmentation k x = 0
  · right
    rw [infiniteSquareZeroPolynomialQuotient_isUnit_iff_augmentation_ne_zero]
    simp [map_sub, hx]
  · left
    exact (infiniteSquareZeroPolynomialQuotient_isUnit_iff_augmentation_ne_zero k x).2 hx

/-- The residue field of `k[x₁, x₂, x₃, \ldots] / (x_i^2)` is canonically `k`. -/
noncomputable def infiniteSquareZeroPolynomialQuotientResidueFieldEquiv :
    ResidueField S∞ ≃+* k := by
  let f := infiniteSquareZeroPolynomialQuotientAugmentation k
  letI : IsLocalHom f := IsLocalHom.of_surjective f
    (infiniteSquareZeroPolynomialQuotientAugmentation_surjective k)
  refine RingEquiv.ofBijective (IsLocalRing.ResidueField.lift f) ?_
  constructor
  · exact RingHom.injective _
  · intro a
    obtain ⟨x, rfl⟩ := infiniteSquareZeroPolynomialQuotientAugmentation_surjective k a
    refine ⟨residue S∞ x, ?_⟩
    change IsLocalRing.ResidueField.lift f (residue S∞ x) = f x
    simp [IsLocalRing.ResidueField.lift_residue_apply]

/-- In the Stacks counterexample ring `S = k[x₁, x₂, x₃, \ldots]/(x_i^2)`, the only
textbook-associated prime of `S` viewed as a `k`-module is `(0)`. -/
theorem infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_over_baseField_eq_singleton_bot :
    associatedPrimesOfModule k S∞ = {⊥} := by
  letI : Nontrivial S∞ := (infiniteSquareZeroPolynomialQuotientAugmentation k).domain_nontrivial
  -- Over a field, the only prime ideal is `(0)`, so nonemptiness already determines the set.
  rw [associatedPrimesOfModule_eq_associatedPrimes]
  refine Set.eq_singleton_iff_unique_mem.mpr ?_
  constructor
  · obtain ⟨p, hp⟩ := associatedPrimes.nonempty k S∞
    have hp_prime : p.IsPrime := (show IsAssociatedPrime p S∞ from hp).isPrime
    letI : p.IsPrime := hp_prime
    simpa [Ideal.eq_bot_of_prime p] using hp
  · intro p hp
    have hp_prime : p.IsPrime := (show IsAssociatedPrime p S∞ from hp).isPrime
    letI : p.IsPrime := hp_prime
    exact Ideal.eq_bot_of_prime p

/-- Noetherian-field companion to
`infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_over_baseField_eq_singleton_bot`
in mathlib's radical-based `associatedPrimes` API. -/
theorem infiniteSquareZeroPolynomialQuotient_associatedPrimes_over_baseField_eq_singleton_bot :
    associatedPrimes k S∞ = {⊥} := by
  rw [← associatedPrimesOfModule_eq_associatedPrimes k S∞]
  exact infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_over_baseField_eq_singleton_bot
    k

/-- In the Stacks counterexample ring `S = k[x₁, x₂, x₃, \ldots]/(x_i^2)`, the textbook-associated
primes of `S` as an `S`-module are empty. -/
theorem infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_self_eq_empty :
    associatedPrimesOfModule S∞ S∞ = ∅ := by
  ext q
  constructor
  · intro hq
    rw [mem_associatedPrimesOfModule_iff, Ideal.isAssociatedToModule_iff_exists_torsionOf] at hq
    rcases hq with ⟨hq_prime, x, rfl⟩
    by_cases hx : x = 0
    · -- The annihilator of `0` is the whole ring, which is never prime.
      exact hq_prime.ne_top ((Ideal.torsionOf_eq_top_iff S∞ x).2 hx)
    · obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
      obtain ⟨i, hXi_sq_zero, hXi_mul_ne_zero⟩ :=
        exists_square_zero_variable_mul_ne_zero_of_ne_zero (k := k) hx
      let y : S∞ := Ideal.Quotient.mk I∞ (MvPolynomial.X i)
      have hy_sq_mem : y ^ 2 ∈ Ideal.torsionOf S∞ S∞ (Ideal.Quotient.mk I∞ p) := by
        -- The chosen variable square annihilates every element because it is already zero.
        simpa [y, Ideal.mem_torsionOf_iff, smul_eq_mul, hXi_sq_zero]
      have hy_not_mem : y ∉ Ideal.torsionOf S∞ S∞ (Ideal.Quotient.mk I∞ p) := by
        -- But the fresh variable itself does not annihilate the chosen nonzero element.
        intro hy_mem
        exact hXi_mul_ne_zero (by simpa [y, Ideal.mem_torsionOf_iff, smul_eq_mul] using hy_mem)
      have hy_mul_mem : y * y ∈ Ideal.torsionOf S∞ S∞ (Ideal.Quotient.mk I∞ p) := by
        simpa [pow_two] using hy_sq_mem
      have hy_mem : y ∈ Ideal.torsionOf S∞ S∞ (Ideal.Quotient.mk I∞ p) := by
        rcases hq_prime.mem_or_mem hy_mul_mem with hy_mem | hy_mem
        · exact hy_mem
        · exact hy_mem
      exact hy_not_mem hy_mem
  · intro hq
    simp at hq

/-- Remark 10.63.12 (Stacks, tag `05BX`): for
`S = k[x₁, x₂, x₃, \ldots]/(x_i^2)` and `M = S`, the associated primes of `M` over the base field
`k` are nonempty, while the associated primes of `S` over itself are empty. -/
theorem infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_counterexample :
    (associatedPrimesOfModule k S∞).Nonempty ∧ associatedPrimesOfModule S∞ S∞ = ∅ := by
  refine ⟨?_, infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_self_eq_empty k⟩
  rw [infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_over_baseField_eq_singleton_bot k]
  exact Set.singleton_nonempty ⊥

/-- Noetherian-field companion to
`infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_counterexample` in mathlib's
`associatedPrimes` API. -/
theorem infiniteSquareZeroPolynomialQuotient_associatedPrimes_counterexample :
    (associatedPrimes k S∞).Nonempty ∧ associatedPrimesOfModule S∞ S∞ = ∅ := by
  rw [← associatedPrimesOfModule_eq_associatedPrimes k S∞]
  exact infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_counterexample k

/-- Remark 10.63.12 (Stacks, tag `05BX`): for the ring map
`k → k[x₁, x₂, x₃, \ldots]/(x_i^2)` with `M = S`, the image of `Ass_S(M)` in `Spec k` does not
contain `Ass_k(M)`. -/
theorem associatedPrimesOfModule_comap_not_superset_for_infiniteSquareZeroPolynomialQuotient :
    ¬ associatedPrimesOfModule k S∞ ⊆
      Ideal.comap (algebraMap k S∞) '' associatedPrimesOfModule S∞ S∞ := by
  rw [infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_over_baseField_eq_singleton_bot k,
    infiniteSquareZeroPolynomialQuotient_associatedPrimesOfModule_self_eq_empty k]
  simp

/-- Noetherian-field companion to
`associatedPrimesOfModule_comap_not_superset_for_infiniteSquareZeroPolynomialQuotient` in
mathlib's radical-based `associatedPrimes` API. -/
theorem associatedPrimes_comap_not_superset_for_infiniteSquareZeroPolynomialQuotient :
    ¬ associatedPrimes k S∞ ⊆
      Ideal.comap (algebraMap k S∞) '' associatedPrimesOfModule S∞ S∞ := by
  rw [← associatedPrimesOfModule_eq_associatedPrimes k S∞]
  exact associatedPrimesOfModule_comap_not_superset_for_infiniteSquareZeroPolynomialQuotient k

end
