import CombinatorialGroupTheory.Basic
import CombinatorialGroupTheory.Items.Chap02.Definition_2_1_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

section

variable {X : Type u} [Finite X] (r : FreeGroup X)

local notation "G" => PresentedGroup (Set.singleton r)

-- Layer triage:
-- `source-facing`: a one-relator group on a finite generator set `X`, with relator
-- `r : FreeGroup X`, whose quotient can be generated by fewer elements than `X` has.
-- `core/canonical`: the quotient owner `PresentedGroup (Set.singleton r)`, the invariant
-- `Group.rank`
-- measuring the minimum size of a generating set, the finite cardinal `Nat.card X` of the ambient
-- generator type, and `IsPrimitiveElement` for the primitive relator conclusion.
-- `bridge/view`: the source phrase “`|X| = nMinusOne + 1` and `G` is generated by `nMinusOne`
-- elements” is expressed by the owner-level inequality
-- `Group.rank (PresentedGroup (Set.singleton r)) < Nat.card X`. The public statement keeps the
-- source-facing `Nat.card X` form rather than replacing it by `Group.rank (FreeGroup X)`, while
-- the source conclusion “`r` is a member of some basis” is expressed by `IsPrimitiveElement r`.
-- Domain sampling:
-- 1. `PresentedGroup R` is mathlib's canonical owner abstraction for a group with generators and
--    relators; in this file the one-relator quotient is the owner-level object `G`.
-- 2. `PresentedGroup.instFG` from Definition `2-1-1` is the chapter owner bridge that supplies
--    the finite-generation instance required to form `Group.rank G`.
-- 3. `Group.rank` is the chapter's canonical owner invariant for “generated by at most `n`
--    elements”; compare Proposition `1-6-6`.
-- 4. `Nat.card X` is the chapter's intrinsic finite-cardinality owner for a generator type,
--    avoiding any public dependence on an ordered `Fin` indexing.
-- 5. `IsPrimitiveElement` from `CombinatorialGroupTheory.Basic` is the project owner for the
--    recurring
--    “belongs to some basis” conclusion.
-- Primitive vs. derived:
-- the primitive source data are only the finite generator type `X`, the ambient relator `r`, and
-- the owner-level rank comparison between the quotient and the ambient generator cardinality; the
-- primitive conclusion about `r` is derived, and any explicit basis witness is auxiliary data
-- behind the owner predicate.

/-- Proposition 2-5-10: let `G = (X; r)` be a one-relator group on a finite generator set `X`. If
`G` can be generated by fewer elements than `X` has, then the relator `r` is primitive in the
ambient free group on `X`. -/
-- Proof sketch: compare the `nMinusOne`-generated quotient `G` with the free group on `X`.
-- Magnus's Freiheitssatz/Nielsen-transform argument shows
-- that a one-relator quotient can lose one generator only when the defining relator is primitive,
-- so `r` is primitive.
theorem isPrimitiveElement_of_one_relator_group_generated_by_fewer_elements
    (hrank : Group.rank G < Nat.card X) :
    IsPrimitiveElement r := sorry

end
