import AchimKlenkeLean.Items.Chap02.Lemma_2_40
import AchimKlenkeLean.Items.Chap14.Lemma_14_27
import AchimKlenkeLean.Items.Chap15.Theorem_15_10
import AchimKlenkeLean.Items.Chap17.Theorem_17_41
import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open MeasureTheory ProbabilityTheory Filter
open scoped BigOperators ENNReal RealInnerProductSpace

noncomputable section

namespace ProbabilityTheory

-- Proof sketch: apply the lattice Fourier inversion formula from Theorem 15.10 to the `2n`-step
-- law generated by the canonical step law `symmetricSimpleRandomWalkStepPMF D`, identify its
-- characteristic function with the `2n`th power of the one-step symbol
-- `(D : ℝ)⁻¹ * ∑ i, cos (t_i)`, and then evaluate the singleton mass at `0`.
/-- Exercise 17.5.1 (1): for the simple symmetric random walk on `ℤ^D`, the `2n`-step return
probability at the origin is the normalized integral over `[-π, π)^D` of the `2n`th power of the
Fourier symbol `D⁻¹ (cos(t₁) + ⋯ + cos(t_D))`. -/
theorem simpleSymmetricRandomWalk_returnProbability_eq_cubeIntegral
    {D n : ℕ} [NeZero D] :
    ((((dirac_convolution_kernel ((symmetricSimpleRandomWalkStepPMF D).toMeasure)) ^ (2 * n))
        (0 : LatticePoint D)).real ({0} : Set (LatticePoint D))) =
      ((2 * Real.pi) ^ D)⁻¹ *
        ∫ t in latticeFrequencyCube D,
          (((D : ℝ)⁻¹ * ∑ i : Fin D, Real.cos (t i)) ^ (2 * n : ℕ)) ∂volume :=
  sorry

-- Proof sketch: split the frequency cube into a small neighborhood of the origin and its
-- complement, use the quadratic approximation `cos u = 1 - u^2 / 2 + o(u^2)` near `0`, dominate
-- the complement uniformly away from `1`, and rescale the local integral to the Gaussian limit.
/-- Exercise 17.5.1 (2): the even-time return probability of the simple symmetric random walk on
`ℤ^D` satisfies the local-limit asymptotic
`n^(D / 2) p^(2n)(0,0) → 2 * (4π / D)^(-D / 2)`. -/
theorem tendsto_scaled_simpleSymmetricRandomWalk_returnProbability
    {D : ℕ} [NeZero D] :
    Tendsto
      (fun n : ℕ ↦
        (n : ℝ) ^ ((D : ℝ) / 2) *
          ((((dirac_convolution_kernel ((symmetricSimpleRandomWalkStepPMF D).toMeasure)) ^
                (2 * n)) (0 : LatticePoint D)).real ({0} : Set (LatticePoint D))))
      atTop
      (nhds ((2 : ℝ) * (4 * Real.pi / D) ^ (-(D : ℝ) / 2))) := sorry

end ProbabilityTheory
