import Mathlib
import LinearRepresentations_Serre_1977.Serre.Chap06.Proposition_6_6_2_1
import LinearRepresentations_Serre_1977.Serre.Chap08.Corollary_8_8_3_8

noncomputable section

open scoped MonoidAlgebra

section Exercise131317AugmentationKernel

variable {p : ℕ}
variable {G : Type} [Group G] [Finite G]

local instance instFintypeExercise131317AugmentationKernel : Fintype G := Fintype.ofFinite G

/-- Helper for Exercise 13-13.1-17: over `ZMod p`, the augmentation kernel of a finite group
algebra is generated by the standard differences `[g] - 1`. -/
theorem monoidAlgebra_augmentationKernel_eq_span_sub_one :
    RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom =
      Ideal.span (Set.range fun g : G => (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
  let ε : (ZMod p)[G] →ₐ[ZMod p] ZMod p :=
    MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)
  let I : Ideal (ZMod p)[G] :=
    Ideal.span (Set.range fun g : G => (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)
  apply le_antisymm
  · intro x hx
    rw [RingHom.mem_ker] at hx
    have hx_alg : ε x = 0 := by
      simpa [ε] using hx
    have hsum_x : x = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := by
      calc
        x = Finsupp.sum x MonoidAlgebra.single := by
          simp
        _ = ∑ g : G, MonoidAlgebra.single g (x g) := by
          exact Finsupp.sum_fintype x MonoidAlgebra.single (by
            intro g
            simpa using (MonoidAlgebra.single_zero (R := ZMod p) (M := G) g))
        _ = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := by
          simp [MonoidAlgebra.of, Algebra.smul_def]
    have hsum_aug :
        algebraMap (ZMod p) ((ZMod p)[G]) (ε x) = ∑ g : G, x g • (1 : (ZMod p)[G]) := by
      have hcoeff : ε x = ∑ g : G, x g := by
        calc
          ε x = Finsupp.sum x (fun a b ↦ b) := by
            simp [ε, MonoidAlgebra.lift_apply]
          _ = ∑ g : G, x g := by
            exact Finsupp.sum_fintype x (fun _ a ↦ a) (by
              intro g
              simp)
      calc
        algebraMap (ZMod p) ((ZMod p)[G]) (ε x)
            = MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) (ε x) := rfl
        _ = ∑ g : G, MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) (x g) := by
            rw [hcoeff, map_sum]
        _ = ∑ g : G, x g • (1 : (ZMod p)[G]) := by
            simp [MonoidAlgebra.singleOneRingHom, Algebra.smul_def]
    have hrewrite : x = ∑ g : G, x g • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
      calc
        x = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := hsum_x
        _ = (∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G])) -
              algebraMap (ZMod p) ((ZMod p)[G]) (ε x) := by
                rw [hx_alg, map_zero, sub_zero]
        _ = (∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G])) -
              ∑ g : G, x g • (1 : (ZMod p)[G]) := by
                rw [hsum_aug]
        _ = ∑ g : G,
              (x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - x g • (1 : (ZMod p)[G])) := by
                rw [← Finset.sum_sub_distrib]
        _ = ∑ g : G, x g • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
              congr with g
              simp [smul_sub]
    rw [hrewrite]
    exact Ideal.sum_mem I fun g _ => by
      have hgmem :
          algebraMap (ZMod p) ((ZMod p)[G]) (x g) *
              ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ∈
            I :=
        I.mul_mem_left _ (Ideal.subset_span ⟨g, rfl⟩)
      simpa [Algebra.smul_def] using hgmem
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨g, rfl⟩
    change ε ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) = 0
    simp [ε]

/-- Helper for Exercise 13-13.1-17: modulo the square of the augmentation kernel, the standard
generator `[gh] - 1` is already the sum of `[g] - 1` and `[h] - 1`. -/
theorem monoidAlgebra_of_mul_sub_one_sub_add_mem_augmentationKernel_sq
    (g h : G) :
    let I : Ideal (ZMod p)[G] :=
      RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
    ((MonoidAlgebra.of (ZMod p) G (g * h) : (ZMod p)[G]) - 1 -
        (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) +
          ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1))) ∈ I ^ 2 := by
  set I : Ideal (ZMod p)[G] :=
    RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
  have hg :
      ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ∈ I := by
    -- Rewrite the augmentation kernel once to its canonical span by the differences `[g] - 1`.
    rw [show I =
        RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom by
        rfl, monoidAlgebra_augmentationKernel_eq_span_sub_one (p := p) (G := G)]
    exact Ideal.subset_span ⟨g, rfl⟩
  have hh :
      ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1) ∈ I := by
    -- The same span description puts `[h] - 1` in the augmentation kernel.
    rw [show I =
        RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom by
        rfl, monoidAlgebra_augmentationKernel_eq_span_sub_one (p := p) (G := G)]
    exact Ideal.subset_span ⟨h, rfl⟩
  have hmul' :
      (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) *
        ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1)) ∈ I * I :=
    Ideal.mul_mem_mul hg hh
  have hmul :
      (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) *
        ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1)) ∈ I ^ 2 := by
    -- Replace the square by the concrete product `I * I` before using the generator-level
    -- membership from the previous line.
    rw [show I ^ 2 = I ^ 1 * I by
      simpa using (Submodule.pow_succ (M := I) (n := 1))]
    rw [Submodule.pow_one]
    exact hmul'
  have hrewrite :
      ((MonoidAlgebra.of (ZMod p) G (g * h) : (ZMod p)[G]) - 1 -
          (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) +
            ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1))) =
        (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) *
          ((MonoidAlgebra.of (ZMod p) G h : (ZMod p)[G]) - 1)) := by
    -- Expand `[gh] = [g][h]` and collect terms; the remainder is exactly the product of the two
    -- augmentation generators.
    simp [sub_eq_add_neg, add_comm, add_left_comm, add_assoc, mul_add, add_mul]
  simpa [I] using (hrewrite ▸ hmul)

/-- Helper for Exercise 13-13.1-17: modulo the square of the augmentation kernel, `[g⁻¹] - 1`
is the additive inverse of `[g] - 1`. -/
theorem monoidAlgebra_of_inv_sub_one_add_mem_augmentationKernel_sq
    (g : G) :
    let I : Ideal (ZMod p)[G] :=
      RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
    ((MonoidAlgebra.of (ZMod p) G g⁻¹ : (ZMod p)[G]) - 1 +
        ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) ∈ I ^ 2 := by
  dsimp
  have hmul :=
    monoidAlgebra_of_mul_sub_one_sub_add_mem_augmentationKernel_sq
      (p := p) (G := G) g g⁻¹
  have hneg :
      -(((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) +
          ((MonoidAlgebra.of (ZMod p) G g⁻¹ : (ZMod p)[G]) - 1)) ∈
        (RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom) ^ 2 := by
    -- Rewrite the `gg⁻¹ = 1` case of the product linearization as a statement about the additive
    -- inverse of `[g] - 1 + [g⁻¹] - 1`.
    simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm, MonoidAlgebra.one_def] using hmul
  have hsum :
      (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) +
          ((MonoidAlgebra.of (ZMod p) G g⁻¹ : (ZMod p)[G]) - 1)) ∈
        (RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom) ^ 2 :=
    neg_mem_iff.mp hneg
  -- Commute the summands once so later commutator calculations can consume the statement directly.
  simpa [add_comm] using hsum

/-- Helper for Exercise 13-13.1-17: every augmentation-kernel element already lies in the
`ZMod p`-submodule spanned by the basis differences `[g] - 1`. -/
theorem monoidAlgebra_mem_submoduleSpan_sub_one_of_mem_augmentationKernel
    {x : (ZMod p)[G]}
    (hx : x ∈ RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom) :
    x ∈ Submodule.span (ZMod p)
      (Set.range fun g : G => (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
  let ε : (ZMod p)[G] →ₐ[ZMod p] ZMod p :=
    MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)
  have hx_alg : ε x = 0 := by
    simpa [ε] using hx
  have hsum_x : x = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := by
    calc
      x = Finsupp.sum x MonoidAlgebra.single := by
        simp
      _ = ∑ g : G, MonoidAlgebra.single g (x g) := by
        exact Finsupp.sum_fintype x MonoidAlgebra.single (by
          intro g
          simpa using (MonoidAlgebra.single_zero (R := ZMod p) (M := G) g))
      _ = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := by
        simp [MonoidAlgebra.of, Algebra.smul_def]
  have hsum_aug :
      algebraMap (ZMod p) ((ZMod p)[G]) (ε x) = ∑ g : G, x g • (1 : (ZMod p)[G]) := by
    have hcoeff : ε x = ∑ g : G, x g := by
      calc
        ε x = Finsupp.sum x (fun a b ↦ b) := by
          simp [ε, MonoidAlgebra.lift_apply]
        _ = ∑ g : G, x g := by
          exact Finsupp.sum_fintype x (fun _ a ↦ a) (by
            intro g
            simp)
    calc
      algebraMap (ZMod p) ((ZMod p)[G]) (ε x)
          = MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) (ε x) := rfl
      _ = ∑ g : G, MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) (x g) := by
          rw [hcoeff, map_sum]
      _ = ∑ g : G, x g • (1 : (ZMod p)[G]) := by
          simp [MonoidAlgebra.singleOneRingHom, Algebra.smul_def]
  have hrewrite : x = ∑ g : G, x g • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
    calc
      x = ∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) := hsum_x
      _ = (∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G])) -
            algebraMap (ZMod p) ((ZMod p)[G]) (ε x) := by
              rw [hx_alg, map_zero, sub_zero]
      _ = (∑ g : G, x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G])) -
            ∑ g : G, x g • (1 : (ZMod p)[G]) := by
              rw [hsum_aug]
      _ = ∑ g : G,
            (x g • (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - x g • (1 : (ZMod p)[G])) := by
              rw [← Finset.sum_sub_distrib]
      _ = ∑ g : G, x g • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) := by
            congr with g
            simp [smul_sub]
  rw [hrewrite]
  exact Submodule.sum_mem _ fun g _ =>
    Submodule.smul_mem _ _ (Submodule.subset_span ⟨g, rfl⟩)

/-- Helper for Exercise 13-13.1-17: modulo the square of the augmentation kernel, scalar
multiples of `[g] - 1` come from powers of `g`. -/
theorem monoidAlgebra_natCast_smul_sub_one_sub_pow_mem_augmentationKernel_sq
    (g : G) :
    ∀ n : ℕ,
      (((n : ZMod p) • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) -
          ((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1)) ∈
        (RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom) ^ 2 := by
  let I : Ideal (ZMod p)[G] :=
    RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
  intro n
  induction n with
  | zero =>
      -- The zeroth power is the identity, so both terms are zero.
      simpa [I, MonoidAlgebra.one_def]
  | succ n ih =>
      have hmul :
          ((MonoidAlgebra.of (ZMod p) G (g ^ n * g) : (ZMod p)[G]) - 1 -
              (((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1) +
                ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1))) ∈ I ^ 2 := by
        simpa [pow_succ] using
          monoidAlgebra_of_mul_sub_one_sub_add_mem_augmentationKernel_sq
            (p := p) (G := G) (g ^ n) g
      have hlinear :
          (((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1) +
              ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) -
            ((MonoidAlgebra.of (ZMod p) G (g ^ n * g) : (ZMod p)[G]) - 1)) ∈ I ^ 2 := by
        -- Reverse the standard product linearization once so it fits the induction step.
        let t : (ZMod p)[G] :=
          ((MonoidAlgebra.of (ZMod p) G (g ^ n * g) : (ZMod p)[G]) - 1) -
            (((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1) +
              ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1))
        have hneg : -t ∈ I ^ 2 := by
          exact neg_mem_iff.mpr hmul
        simpa [t, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using hneg
      have hsum :
          ((((n : ZMod p) • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) -
                ((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1)) +
              (((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1) +
                ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) -
                  ((MonoidAlgebra.of (ZMod p) G (g ^ n * g) : (ZMod p)[G]) - 1))) ∈
            I ^ 2 := by
        exact add_mem ih hlinear
      -- The middle basis term cancels, leaving the next scalar multiple and the next power.
      have hrewrite :
          (((n : ZMod p) • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) -
                ((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1)) +
              (((MonoidAlgebra.of (ZMod p) G (g ^ n) : (ZMod p)[G]) - 1) +
                ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) -
                  ((MonoidAlgebra.of (ZMod p) G (g ^ n * g) : (ZMod p)[G]) - 1)) =
            (((n + 1 : ℕ) : ZMod p) • ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) -
              ((MonoidAlgebra.of (ZMod p) G (g ^ (n + 1)) : (ZMod p)[G]) - 1) := by
        simp [pow_succ, Nat.cast_add, Nat.cast_one, add_smul, sub_eq_add_neg, add_assoc,
          add_left_comm, add_comm]
      exact hrewrite ▸ hsum

/-- Helper for Exercise 13-13.1-17: every augmentation-kernel element is congruent modulo `I²` to
a single basis difference `[g] - 1`. -/
theorem monoidAlgebra_exists_sub_one_sub_mem_augmentationKernel_sq
    [Fact p.Prime]
    (x : (ZMod p)[G])
    (hx : x ∈ RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom) :
    let I : Ideal (ZMod p)[G] :=
      RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
    ∃ g : G, x - ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ∈ I ^ 2 := by
  let I : Ideal (ZMod p)[G] :=
    RingHom.ker (MonoidAlgebra.lift (ZMod p) (ZMod p) G (1 : G →* ZMod p)).toRingHom
  let S : Set ((ZMod p)[G]) :=
    Set.range fun g : G => (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1
  let e : G → (ZMod p)[G] := fun g => (MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1
  have hxspan : x ∈ Submodule.span (ZMod p) S := by
    exact monoidAlgebra_mem_submoduleSpan_sub_one_of_mem_augmentationKernel
      (p := p) (G := G) hx
  clear hx
  refine Submodule.span_induction
      (p := fun z _ => ∃ g : G, z - e g ∈ I ^ 2)
      ?_ ?_ ?_ ?_ hxspan
  · rintro _ ⟨g, rfl⟩
    -- A basis generator is congruent to itself modulo `I²`.
    refine ⟨g, by simpa [e, I] using (Ideal.zero_mem (I ^ 2))⟩
  · -- The zero class is represented by the identity element.
    refine ⟨1, ?_⟩
    simp [e, I, MonoidAlgebra.one_def]
  · intro y z hy hz hyRep hzRep
    rcases hyRep with ⟨g, hg⟩
    rcases hzRep with ⟨h, hh⟩
    refine ⟨g * h, ?_⟩
    have hmul :
        (e (g * h) - (e g + e h)) ∈ I ^ 2 := by
      simpa [e, I] using
        monoidAlgebra_of_mul_sub_one_sub_add_mem_augmentationKernel_sq
          (p := p) (G := G) g h
    have hlinear : (e g + e h - e (g * h)) ∈ I ^ 2 := by
      -- Reverse the product linearization once so the representative errors add directly.
      let t : (ZMod p)[G] := e (g * h) - (e g + e h)
      have hneg : -t ∈ I ^ 2 := by
        exact neg_mem_iff.mpr hmul
      simpa [t, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using hneg
    have hsum : (y - e g) + (z - e h) + (e g + e h - e (g * h)) ∈ I ^ 2 := by
      exact add_mem (add_mem hg hh) hlinear
    -- The two established congruences and the product linearization collapse to the target sum.
    have hrewrite :
        (y - e g) + (z - e h) + (e g + e h - e (g * h)) =
          y + z - e (g * h) := by
      abel_nf
    exact hrewrite ▸ hsum
  · intro a y hy hyRep
    rcases hyRep with ⟨g, hg⟩
    refine ⟨g ^ a.val, ?_⟩
    have hscalar : a • (y - e g) ∈ I ^ 2 := by
      -- Rewrite the base-field scalar as left multiplication in the group algebra.
      rw [Algebra.smul_def]
      exact (I ^ 2).mul_mem_left _ hg
    have hpowNat : ((a.val : ZMod p) • e g) - e (g ^ a.val) ∈ I ^ 2 := by
      -- Replace the scalar `a` by `a.val`, then use the repeated-product congruence.
      simpa [e, I] using
        monoidAlgebra_natCast_smul_sub_one_sub_pow_mem_augmentationKernel_sq
          (p := p) (G := G) g a.val
    have hpow : a • e g - e (g ^ a.val) ∈ I ^ 2 := by
      convert hpowNat using 1
      · rw [ZMod.natCast_zmod_val a]
    have hsum : a • (y - e g) + (a • e g - e (g ^ a.val)) ∈ I ^ 2 := by
      exact add_mem hscalar hpow
    -- Distribute the scalar once and then cancel the intermediate representative.
    have hrewrite :
        a • (y - e g) + (a • e g - e (g ^ a.val)) =
          a • y - e (g ^ a.val) := by
      simp [smul_sub, sub_eq_add_neg, add_assoc, add_left_comm, add_comm]
    exact hrewrite ▸ hsum

/-- Helper for Exercise 13-13.1-17: a nilpotent two-sided ideal is contained in the Jacobson
radical. -/
theorem ideal_le_ring_jacobson_of_isNilpotent {R : Type*} [Ring R]
    (I : Ideal R) (hI : IsNilpotent I) :
    I ≤ Ring.jacobson R := by
  rw [← Ideal.jacobson_bot]
  intro x hx
  rw [Ideal.mem_jacobson_iff]
  intro y
  have hyx_nilpotent : IsNilpotent (y * x) := by
    rcases hI with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have hyx_mem : y * x ∈ I := I.mul_mem_left y hx
    have hyx_pow_mem : (y * x) ^ n ∈ I ^ n := Ideal.pow_mem_pow hyx_mem n
    simpa [hn] using hyx_pow_mem
  rcases hyx_nilpotent.isUnit_add_one with ⟨u, hu⟩
  refine ⟨↑u⁻¹, ?_⟩
  change (↑u⁻¹ : R) * y * x + ↑u⁻¹ - 1 ∈ (⊥ : Ideal R)
  rw [Ideal.mem_bot]
  have hu' : (↑u⁻¹ : R) * (y * x + 1) = 1 := by
    simpa [hu] using congrArg (fun z : Rˣ => (z : R)) (Units.inv_mul u)
  have hmul : (↑u⁻¹ : R) * y * x = (↑u⁻¹ : R) * (y * x) := by
    rw [mul_assoc]
  calc
    (↑u⁻¹ : R) * y * x + ↑u⁻¹ - 1 = (↑u⁻¹ : R) * (y * x) + ↑u⁻¹ - 1 := by
      rw [hmul]
    _ = (↑u⁻¹ : R) * (y * x + 1) - 1 := by
      rw [mul_add, mul_one]
    _ = 1 - 1 := by
      rw [hu']
    _ = 0 := sub_self 1

/-- Helper for Exercise 13-13.1-17: if two elements of an ideal are congruent modulo `I²`, then
their `n`-th powers are congruent modulo `I^(n + 1)`. -/
theorem powSub_mem_pow_succ_of_sub_mem_sq
    {R : Type*} [Ring R] (I : Ideal R) {x y : R}
    (hx : x ∈ I) (hy : y ∈ I) (hxy : x - y ∈ I ^ 2) :
    ∀ n : ℕ, x ^ n - y ^ n ∈ I ^ (n + 1)
  | 0 => by
      -- The zeroth powers cancel, so the difference is the zero element of `I`.
      simpa using (show (0 : R) ∈ I ^ 1 from Ideal.zero_mem _)
  | n + 1 => by
      have ih : x ^ n - y ^ n ∈ I ^ (n + 1) :=
        powSub_mem_pow_succ_of_sub_mem_sq I hx hy hxy n
      have hfirstMul : (x ^ n - y ^ n) * x ∈ I ^ (n + 1) * I :=
        Ideal.mul_mem_mul ih hx
      have hfirst : (x ^ n - y ^ n) * x ∈ I ^ (n + 2) := by
        -- The inductive error gains one more factor of `I` after multiplying by `x`.
        rw [show I ^ (n + 2) = I ^ (n + 1) * I by
          simpa [Nat.add_assoc] using (Submodule.pow_succ (M := I) (n := n + 1))]
        exact hfirstMul
      have hyPow : y ^ n ∈ I ^ n := Ideal.pow_mem_pow hy n
      have hsecondMul : y ^ n * (x - y) ∈ I ^ n * I ^ 2 :=
        Ideal.mul_mem_mul hyPow hxy
      have hsecond : y ^ n * (x - y) ∈ I ^ (n + 2) := by
        -- The `I²`-congruence contributes the extra two ideal factors in the telescoping term.
        rw [show I ^ (n + 2) = I ^ n * I ^ 2 by
          simpa using (Submodule.pow_add (M := I) (m := n) (n := 2) (by decide))]
        exact hsecondMul
      have hEq :
          x ^ (n + 1) - y ^ (n + 1) = (x ^ n - y ^ n) * x + y ^ n * (x - y) := by
        -- This is the standard noncommutative telescoping identity for consecutive powers.
        simp [pow_succ, sub_eq_add_neg, add_mul, mul_add, add_assoc, add_left_comm]
      rw [hEq]
      exact add_mem hfirst hsecond

/-- Helper for Exercise 13-13.1-17: the previous telescoping lemma specialized to a `p`-th-power
comparison. -/
theorem augmentationKernel_pth_power_congr_of_sub_mem_sq
    {R : Type*} [Ring R] (I : Ideal R) {x y : R}
    (hx : x ∈ I) (hy : y ∈ I) (hxy : x - y ∈ I ^ 2) (p : ℕ) :
    x ^ p - y ^ p ∈ I ^ (p + 1) := by
  -- The `p`-th-power estimate is just the `n = p` instance of the generic telescoping lemma.
  exact powSub_mem_pow_succ_of_sub_mem_sq I hx hy hxy p

/-- Helper for Exercise 13-13.1-17: in characteristic `p`, the basis element `[g] - 1` has
`p`-th power `[g^p] - 1`. -/
private theorem monoidAlgebra_sub_one_pow_p [Fact p.Prime] (g : G) :
    ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ^ p =
      MonoidAlgebra.of (ZMod p) G (g ^ p) - 1 := by
  let x : (ZMod p)[G] := MonoidAlgebra.of (ZMod p) G g
  have hp : Nat.Prime p := Fact.out
  have hpow : (x + -(1 : (ZMod p)[G])) ^ p = x ^ p + (-(1 : (ZMod p)[G])) ^ p := by
    obtain ⟨r, hr⟩ := (Commute.one_right x).neg_right.exists_add_pow_prime_eq hp
    have hpzero : ((p : ℕ) : (ZMod p)[G]) = 0 := by
      have hpzero' : ((p : ℕ) : ZMod p) = 0 := by
        simpa using (CharP.cast_eq_zero (R := ZMod p) (p := p))
      calc
        ((p : ℕ) : (ZMod p)[G]) =
            MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) ((p : ℕ) : ZMod p) := rfl
        _ = MonoidAlgebra.singleOneRingHom (R := ZMod p) (M := G) 0 := by
            rw [hpzero']
        _ = 0 := by
            change MonoidAlgebra.single (1 : G) (0 : ZMod p) = 0
            exact Finsupp.single_zero _
    rw [hr, hpzero]
    simp
  have hxpow : x ^ p = MonoidAlgebra.of (ZMod p) G (g ^ p) := by
    simpa [x] using ((MonoidAlgebra.of (ZMod p) G).map_pow g p).symm
  -- Rewrite the Frobenius expansion in the group basis and then evaluate the scalar `(-1)^p`.
  calc
    ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ^ p
        = (x + -(1 : (ZMod p)[G])) ^ p := by
            simp [x, sub_eq_add_neg]
    _ = x ^ p + (-(1 : (ZMod p)[G])) ^ p := hpow
    _ = MonoidAlgebra.of (ZMod p) G (g ^ p) - 1 := by
          rw [hxpow]
          have hnegpow : (-(1 : (ZMod p)[G])) ^ p = -(1 : (ZMod p)[G]) := by
            have hnegcoeff : ((-1 : ZMod p) ^ p) = (-1 : ZMod p) := by
              by_cases hp2 : p = 2
              · subst hp2
                simp
              · have hpodd : Odd p := Nat.Prime.odd_of_ne_two hp hp2
                simpa using hpodd.neg_one_pow (α := ZMod p)
            have hsingle : (-(1 : (ZMod p)[G])) = MonoidAlgebra.single 1 (-1 : ZMod p) := by
              ext h
              by_cases hh : h = 1
              · subst hh
                simp [MonoidAlgebra.one_def]
              · simp [MonoidAlgebra.one_def, hh]
            rw [hsingle, MonoidAlgebra.single_pow]
            simpa [hnegcoeff]
          rw [hnegpow]
          simp [sub_eq_add_neg]

/-- Helper for Exercise 13-13.1-17: iterating Frobenius gives an explicit `p^n`-power formula for
the augmentation generators `[g] - 1`. -/
private theorem monoidAlgebra_sub_one_pow_prime_pow [Fact p.Prime] (g : G) (n : ℕ) :
    ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ^ (p ^ n) =
      MonoidAlgebra.of (ZMod p) G (g ^ (p ^ n)) - 1 := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      calc
        ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ^ (p ^ (n + 1))
            = (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ^ (p ^ n)) ^ p := by
                rw [pow_succ, pow_mul]
        _ = ((MonoidAlgebra.of (ZMod p) G (g ^ (p ^ n)) : (ZMod p)[G]) - 1) ^ p := by
              rw [ih]
        _ = MonoidAlgebra.of (ZMod p) G ((g ^ (p ^ n)) ^ p) - 1 :=
              monoidAlgebra_sub_one_pow_p (p := p) (g := g ^ (p ^ n))
        _ = MonoidAlgebra.of (ZMod p) G (g ^ (p ^ (n + 1))) - 1 := by
              rw [← pow_mul, pow_succ]

/-- Helper for Exercise 13-13.1-17: for a `k[G]`-module viewed through
`Representation.ofModule'`, the induced group-algebra operator is the original scalar action. -/
private theorem ofModule'_asAlgebraHom_apply_local
    {k : Type*} [Field k] {G' : Type*} [Group G'] {M : Type*}
    [AddCommGroup M] [Module k M] [Module k[G'] M] [IsScalarTower k k[G'] M]
    (r : k[G']) (m : M) :
    ((Representation.ofModule' (k := k) (G := G') M).asAlgebraHom r) m = r • m := by
  -- Expand the group-algebra element linearly and check the claim on monomials.
  refine MonoidAlgebra.induction_on
    (p := fun a : k[G'] =>
      ((Representation.ofModule' (k := k) (G := G') M).asAlgebraHom a) m = a • m) r ?_ ?_ ?_
  · intro g
    simp [Representation.ofModule', MonoidAlgebra.of]
  · intro a b ha hb
    simp [ha, hb, add_smul]
  · intro a b hb
    simp [hb]

/-- Helper for Exercise 13-13.1-17: the owner `k[G]`-module of `Representation.ofModule'` is
canonically the original module. -/
private theorem nonempty_ofModule'_asModuleLinearEquiv_local
    {k : Type*} [Field k] {G' : Type*} [Group G'] {M : Type*}
    [AddCommGroup M] [Module k M] [Module k[G'] M] [IsScalarTower k k[G'] M] :
    Nonempty ((Representation.ofModule' (k := k) (G := G') M).asModule ≃ₗ[k[G']] M) := by
  let toFun : (Representation.ofModule' (k := k) (G := G') M).asModule → M :=
    fun x => (Representation.ofModule' (k := k) (G := G') M).asModuleEquiv x
  let invFun : M → (Representation.ofModule' (k := k) (G := G') M).asModule :=
    fun x => (Representation.ofModule' (k := k) (G := G') M).asModuleEquiv.symm x
  have hleft : Function.LeftInverse invFun toFun := by
    intro x
    simp [toFun, invFun]
  have hright : Function.RightInverse invFun toFun := by
    intro x
    simp [toFun, invFun]
  have hadd : ∀ x y, toFun (x + y) = toFun x + toFun y := by
    intro x y
    rfl
  have hsmul : ∀ (r : k[G']) x, toFun (r • x) = r • toFun x := by
    intro r x
    -- Compare the transported owner action with the original module action on `M`.
    calc
      (Representation.ofModule' (k := k) (G := G') M).asModuleEquiv (r • x)
          = ((Representation.ofModule' (k := k) (G := G') M).asAlgebraHom r)
              ((Representation.ofModule' (k := k) (G := G') M).asModuleEquiv x) := by
              exact
                (Representation.asModuleEquiv_map_smul
                  (ρ := Representation.ofModule' (k := k) (G := G') M) r x)
      _ = r • (Representation.ofModule' (k := k) (G := G') M).asModuleEquiv x := by
            simp [ofModule'_asAlgebraHom_apply_local]
  refine ⟨
    { toFun := toFun
      invFun := invFun
      left_inv := hleft
      right_inv := hright
      map_add' := hadd
      map_smul' := hsmul }⟩

/-- Helper for Exercise 13-13.1-17: a simple `k[G]`-module, viewed through
`Representation.ofModule'`, is irreducible. -/
private theorem ofModule'_isIrreducible_of_isSimpleModule_local
    {k : Type*} [Field k] {G' : Type*} [Group G'] {M : Type*}
    [AddCommGroup M] [Module k M] [Module k[G'] M] [IsScalarTower k k[G'] M]
    (hM : IsSimpleModule k[G'] M) :
    (Representation.ofModule' (k := k) (G := G') M).IsIrreducible := by
  let ρ := Representation.ofModule' (k := k) (G := G') M
  letI : Module k[G'] ρ.asModule := ρ.instModuleMonoidAlgebraAsModule
  rcases
      nonempty_ofModule'_asModuleLinearEquiv_local (k := k) (G' := G') (M := M) with
    ⟨e⟩
  -- Transfer simplicity across the canonical owner-module equivalence.
  exact
    (Representation.irreducible_iff_isSimpleModule_asModule ρ).2
      (@IsSimpleModule.congr (k[G']) inferInstance ρ.asModule
        ρ.instAddCommGroupAsModule ρ.instModuleMonoidAlgebraAsModule
        M inferInstance inferInstance e hM)

/-- Helper for Exercise 13-13.1-17: in characteristic `p`, every augmentation generator
`[g] - 1` of a finite `p`-group group algebra lies in the Jacobson radical. -/
theorem p_group_generator_sub_one_mem_jacobson
    [Fact p.Prime]
    (hG : IsPGroup p G) (g : G) :
    ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) ∈ Ring.jacobson ((ZMod p)[G]) := by
  -- Route correction: use Serre's maximal-left-ideal quotient argument directly. For every
  -- maximal left ideal `I`, the quotient `k[G] ⧸ I` is a simple `k[G]`-module, hence an
  -- irreducible `G`-representation in characteristic `p`, so the `p`-group action is trivial.
  -- Evaluating `([g] - 1)` on the class of `1` therefore shows `([g] - 1) ∈ I`.
  rw [Ring.jacobson_eq_sInf_isMaximal, Ideal.mem_sInf]
  intro I hI
  simp only [Set.mem_setOf_eq] at hI
  have hsimple :
      IsSimpleModule ((ZMod p)[G]) (((ZMod p)[G]) ⧸ I) :=
    (isSimpleModule_iff_isCoatom).2 (Ideal.isMaximal_def.mp hI)
  let ρ := Representation.ofModule' (k := ZMod p) (G := G) (((ZMod p)[G]) ⧸ I)
  letI : ρ.IsIrreducible :=
    ofModule'_isIrreducible_of_isSimpleModule_local
      (k := ZMod p) (G' := G) (M := (((ZMod p)[G]) ⧸ I)) hsimple
  have htriv : ρ.IsTrivial :=
    isTrivial_of_isIrreducible_of_isPGroup_charP (ρ := ρ) hG
  let q : ((ZMod p)[G]) ⧸ I := Submodule.Quotient.mk (1 : (ZMod p)[G])
  have hkill :
      ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) • q = 0 := by
    -- Compare the quotient-module scalar action with the representation action, then use the
    -- triviality of the quotient representation.
    calc
      ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) • q
          = ((ρ.asAlgebraHom ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) q) := by
              symm
              simpa [ρ] using
                ofModule'_asAlgebraHom_apply_local
                  (k := ZMod p) (G' := G) (M := (((ZMod p)[G]) ⧸ I))
                  (((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) q
      _ = ρ g q - q := by
            have hsub :
                ρ.asAlgebraHom ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) = ρ g - 1 := by
              rw [map_sub, Representation.asAlgebraHom_of, map_one]
            calc
              (ρ.asAlgebraHom ((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1)) q
                  = ((ρ g - 1) q) := by
                      exact LinearMap.congr_fun hsub q
              _ = ρ g q - q := by
                    rfl
      _ = 0 := by
            simpa [q] using
              sub_eq_zero.mpr (Representation.isTrivial_apply (ρ := ρ) g q)
  have hmk :
      (Submodule.Quotient.mk
          ((((MonoidAlgebra.of (ZMod p) G g : (ZMod p)[G]) - 1) •
            (1 : (ZMod p)[G]))) : ((ZMod p)[G]) ⧸ I) = 0 := by
    rw [Submodule.Quotient.mk_smul]
    simpa [q] using hkill
  -- Reading the zero class of the quotient representative is exactly membership in `I`.
  simpa [Algebra.smul_def] using (Submodule.Quotient.mk_eq_zero (p := I)).1 hmk

end Exercise131317AugmentationKernel
