import Mathlib
import StacksProject_2024.Chap18.Lemma_18_3_1
import StacksProject_2024.Chap18.Lemma_18_3_2
import StacksProject_2024.Chap07.Proposition_7_39_3
import StacksProject_2024.Chap12.Lemma_12_7_2
import StacksProject_2024.Chap19.Lemma_19_9_1

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open CategoryTheory.Limits
open CategoryTheory.SemiRepresentableFamily.Over

universe u v

noncomputable section

namespace CategoryTheory

variable (A : Type u) [Category.{v} A] [Abelian A]

-- For the abelian exact structure, this agrees with
-- `Pretopology.toGrothendieck (singletonEpiPretopology A)` by
-- `ExactStructure.singletonAdmissibleEpiPretopology_toGrothendieck`.
local notation "J" => ExactStructure.topology (abelianExactStructure A)
local notation "F" => ExactStructure.sheafYoneda (abelianExactStructure A)

/- Domain-style sampling for Lemma 19.9.2:
- primary domain: Grothendieck topologies on abelian categories, stated source-facing via the
  singleton-epimorphism site and supported canonically by the exact-structure sheaf-Yoneda API;
- sampled owner declarations:
  `singletonEpiPretopology`,
  `Pretopology.toGrothendieck`,
  `ExactStructure.preadditiveYoneda_isSheaf`,
  `ExactStructure.sheafYoneda`;
- best owner abstraction: the Grothendieck topology
  `(abelianExactStructure A).topology`, canonically identified with
  `(singletonEpiPretopology A).toGrothendieck`;
- primitive data: the singleton covering pretopology generated by epimorphisms, already introduced
  in Lemma 19.9.1;
- derived API: the induced Grothendieck topology, representables as sheaves, the sheaf-valued
  Yoneda functor, its exact-functor packaging, and enough points.

Source/core/bridge triage:
- `source-facing`: `singletonEpiPretopology` and its generated topology;
- `core/canonical`: `(abelianExactStructure A).topology`,
  `ExactStructure.preadditiveYoneda_isSheaf`, `ExactStructure.sheafYoneda`, and `ExactFunctor.of`;
- `bridge/view`: `abelianExactStructure` from Lemma 19.9.1, together with the identification of
  its admissible epimorphisms with the ordinary epimorphisms.

Primitive-versus-derived check:
- primitive data should remain the singleton-epimorphism pretopology from Lemma 19.9.1;
- the exact-structure realization from Lemma 19.9.1 is auxiliary bridge data, not the public owner
  for this file;
- the sheaf statement is derived from the source-facing site via that bridge, while the sheaf-valued
  Yoneda functorial API is reused directly from `ExactStructure.sheafYoneda`.
-/

/-- Lemma 19.9.2: for every object `X`, the representable additive presheaf `U ↦ Hom(U, X)` is a
sheaf for the singleton-epimorphism topology on `A`. -/
theorem singletonEpiPretopology_preadditiveYoneda_isSheaf (X : A) :
    Presheaf.IsSheaf J (preadditiveYoneda.obj X) := by
  -- This is the exact-structure sheaf statement from Remark 19.9.6 specialized to the abelian
  -- exact structure from Lemma 19.9.1.
  simpa using ExactStructure.preadditiveYoneda_isSheaf (abelianExactStructure A) X

/-- Helper for Lemma 19.9.2: in the abelian exact structure, the sheaf-valued Yoneda functor sends
short exact sequences to short exact sequences of sheaves. -/
private theorem abelianExactStructure_sheafYoneda_maps_shortExact {S : ShortComplex A}
    (hS : S.ShortExact) :
    (S.map F).ShortExact := by
  -- The source short exact sequence is admissible for the canonical abelian exact structure, so
  -- Remark 19.9.6 applies directly.
  simpa [abelianExactStructure] using
    (ExactStructure.sheafYoneda_maps_admissible (E := abelianExactStructure A) hS)

/- Lemma 19.9.2 (1): the source-facing exactness statement is the mapped-short-exact theorem above;
this is the exact-structure formulation used throughout the local Chapter 19 API. -/

/- Lemma 19.9.2 (2): the functor `X ↦ h_X` is full on the singleton-epimorphism site. -/
#synth Functor.Full (ExactStructure.sheafYoneda (abelianExactStructure A))

/- Lemma 19.9.2 (3): the functor `X ↦ h_X` is faithful on the singleton-epimorphism site. -/
#synth Functor.Faithful (ExactStructure.sheafYoneda (abelianExactStructure A))

/-- Helper for Lemma 19.9.2: every covering sieve for the singleton-admissible-epimorphism
coverage contains the sieve generated by a singleton epimorphism. -/
private theorem abelianExactStructure_covering_sieve_has_singleton_epi {U : A} {S : Sieve U}
    (hS : S ∈ J U) :
    ∃ (Y : A) (f : Y ⟶ U), Epi f ∧ Sieve.generate (Presieve.singleton f) ≤ S := by
  change S ∈ (ExactStructure.singletonAdmissibleEpiCoverage (abelianExactStructure A)).toGrothendieck U
    at hS
  rw [Coverage.mem_toGrothendieck] at hS
  induction hS with
  | of X R hR =>
      -- A generating cover is already a singleton admissible epimorphism, hence a singleton epi.
      obtain ⟨Y, f, hf, rfl⟩ :=
        ExactStructure.mem_singletonAdmissibleEpiCoverage_iff (E := abelianExactStructure A)
          (X := X) (S := R) |>.1 hR
      refine ⟨Y, f, (abelianExactStructure_admissibleEpi_iff (A := A) f).1 hf, le_rfl⟩
  | top X =>
      -- The top sieve contains the identity singleton cover.
      refine ⟨X, 𝟙 X, inferInstance, le_top⟩
  | transitive X R S hR hRS ihR ihRS =>
      -- First choose a singleton epi cover inside the intermediate covering sieve `R`.
      obtain ⟨Y, f, hf, hRf⟩ := ihR
      have hfgen : Sieve.generate (Presieve.singleton f) f := by
        exact Sieve.le_generate (Presieve.singleton f) _ _ Presieve.singleton.mk
      have hfR : R f := hRf f hfgen
      -- Then refine locally over that singleton cover and compose the resulting epimorphisms.
      obtain ⟨Z, g, hg, hpull⟩ := ihRS hfR
      refine ⟨Z, g ≫ f, inferInstance, ?_⟩
      intro W k hk
      rw [Sieve.generateSingleton_eq] at hk
      rcases hk with ⟨l, rfl⟩
      have hggen : Sieve.generate (Presieve.singleton g) (l ≫ g) := by
        rw [Sieve.generateSingleton_eq]
        exact ⟨l, rfl⟩
      have hmem : S.pullback f (l ≫ g) := hpull (l ≫ g) hggen
      simpa [Sieve.pullback_apply, Category.assoc] using hmem

private theorem abelianExactStructure_topology_hasFiniteRefinementProperty (U : A) :
    GrothendieckTopology.HasFiniteRefinementProperty J U := by
  refine
    { finite_refinement := fun R hR ↦ ?_ }
  -- Route correction: work in the singleton-admissible-epimorphism coverage and extract one
  -- singleton epi whose generated sieve already refines the given covering sieve.
  obtain ⟨Y, f, hf, hle⟩ :=
    abelianExactStructure_covering_sieve_has_singleton_epi (A := A) (S := Sieve.generate R) hR
  let 𝒱 : SemiRepresentableFamily.Over.{v, u, max u v} U :=
    ofArrows (fun _ : PUnit ↦ Y) (fun _ ↦ f)
  have h𝒱toPresieve : 𝒱.toPresieve = Presieve.singleton f := by
    -- The explicit `PUnit`-indexed family is literally the singleton presieve of `f`.
    simpa [𝒱, toPresieve] using (Presieve.ofArrows_pUnit (f := f))
  have h𝒱eq : 𝒱.toSieve = Sieve.generate (Presieve.singleton f) := by
    -- Passing to sieves just applies `Sieve.generate` to the singleton-presieve identity above.
    simpa [toSieve] using congrArg Sieve.generate h𝒱toPresieve
  have h𝒱cover : 𝒱.toSieve ∈ J U := by
    -- A singleton epi is itself a covering family in the generated topology.
    have hfadmissible : (abelianExactStructure A).AdmissibleEpi f := by
      exact (abelianExactStructure_admissibleEpi_iff (A := A) f).2 hf
    have hfcover : Presieve.singleton f ∈
        ExactStructure.singletonAdmissibleEpiCoverage (abelianExactStructure A) U := by
      exact ⟨Y, f, hfadmissible, rfl⟩
    have hsingleton : Sieve.generate (Presieve.singleton f) ∈
      (ExactStructure.singletonAdmissibleEpiCoverage (abelianExactStructure A)).toGrothendieck U
        := by
      rw [Coverage.mem_toGrothendieck]
      exact Coverage.Saturate.of _ _ hfcover
    change 𝒱.toSieve ∈
      (ExactStructure.singletonAdmissibleEpiCoverage (abelianExactStructure A)).toGrothendieck U
    rw [h𝒱eq]
    exact hsingleton
  have h𝒱le : 𝒱.toSieve ≤ Sieve.generate R := by
    -- After identifying the singleton indexed family with the singleton presieve, the refinement
    -- inequality is the extracted singleton refinement.
    rw [h𝒱eq]
    exact hle
  have h𝒱finite : Finite 𝒱.index := by
    -- The chosen singleton refinement is indexed by `PUnit`.
    dsimp [𝒱]
    infer_instance
  exact ⟨𝒱, h𝒱finite, h𝒱cover, h𝒱le⟩

/-- Helper for Lemma 19.9.2: the singleton-epimorphism topology on an abelian category has enough
points because every cover has a finite singleton refinement. -/
private theorem abelianExactStructure_topology_hasEnoughPoints :
    ((abelianExactStructure A).topology : GrothendieckTopology A).HasEnoughPoints := by
  -- The finite-refinement theorem from Proposition 7.39.3 applies directly to `J`.
  exact hasEnoughPoints_of_finite_cover_refinement
    (fun U ↦ abelianExactStructure_topology_hasFiniteRefinementProperty (A := A) U)

/-- Lemma 19.9.2 (4): the singleton-epimorphism topology on an abelian category has enough
points. -/
theorem singletonEpiPretopology_toGrothendieck_hasEnoughPoints :
    (J : GrothendieckTopology A).HasEnoughPoints :=
  by
    -- This is exactly the internal enough-points statement for the abelian exact-structure
    -- topology.
    simpa using abelianExactStructure_topology_hasEnoughPoints A

end CategoryTheory
