import stacks_proof.stacks_project.Chap10.Lemma_10_20_2.FiniteQuotientGeneration
import stacks_proof.stacks_project.Chap10.Lemma_10_20_2.AwayProductMaps
import stacks_proof.stacks_project.Chap10.Lemma_10_20_2.SingleDenominator
