#!/usr/bin/env python3
"""Generate the single-book ReasBook website metadata.

The website intentionally publishes one literate module, the book aggregate.
The Beck formalization stores individual items directly under ``ChapNN``
directories, so the book home page links those source directories instead of
pretending that ``Chapters/sectionNN`` aggregate modules exist.

This generator only writes under ``ReasBookWeb``.  In particular, it never
rewrites the Lean sources, the book README, or the repository README.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


BOOK = "FirstOrderMethodsInOptimization_Beck_2017"
BOOK_TITLE = "First-Order Methods in Optimization (Beck, 2017)"
BOOK_MODULE = f"Books.{BOOK}.Book"
BOOK_SLUG = BOOK.lower()
BOOK_HOME_ROUTE = f"books/{BOOK_SLUG}/"
BOOK_MODULE_ROUTE = f"{BOOK_HOME_ROUTE}book/"
CHAPTER_RE = re.compile(r"^Chap(\d+)$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "repo_root",
        nargs="?",
        default=None,
        help="Repository root containing ReasBook/ and ReasBookWeb/.",
    )
    return parser.parse_args()


def write_text_if_changed(path: Path, content: str) -> bool:
    try:
        old = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        old = None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")
    return True


def lean_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def normalize_site_root(value: str) -> str:
    value = value.strip() or "/ReasBook/"
    if not value.startswith("/"):
        value = "/" + value
    if not value.endswith("/"):
        value += "/"
    return value


def github_coordinates() -> tuple[str, str, str]:
    slug = os.environ.get("REASBOOK_GITHUB_REPO", "optpku/ReasBook").strip("/")
    if "/" not in slug:
        slug = "optpku/ReasBook"
    owner, repo = slug.split("/", 1)
    branch = os.environ.get("REASBOOK_GITHUB_BRANCH", "main").strip() or "main"
    return owner, repo, branch


def chapter_directories(book_dir: Path) -> list[tuple[int, Path, int]]:
    chapters: list[tuple[int, Path, int]] = []
    if not book_dir.is_dir():
        return chapters
    for path in book_dir.iterdir():
        if not path.is_dir():
            continue
        match = CHAPTER_RE.fullmatch(path.name)
        if match is None:
            continue
        module_count = sum(1 for item in path.rglob("*.lean") if item.is_file())
        chapters.append((int(match.group(1)), path, module_count))
    chapters.sort(key=lambda item: item[0])
    return chapters


def emit_sections(site_root: str) -> str:
    sidebar = {
        "books": [
            {
                "slug": BOOK_SLUG,
                "title": BOOK_TITLE,
                "home": BOOK_HOME_ROUTE,
                "chapters": [],
            }
        ],
        "papers": [],
    }
    sidebar_json = json.dumps(sidebar, ensure_ascii=True, separators=(",", ":"))
    return "\n".join(
        [
            "-- This file is generated by scripts/gen_sections.py",
            "-- Do not edit manually.",
            "",
            "namespace ReasBookSite.Sections",
            "",
            "def sections : Array (Lean.Name × String) := #[",
            f"  (`{BOOK_MODULE}, {lean_string(BOOK_TITLE)}),",
            "]",
            "",
            "def routes : Array (String × Lean.Name) := #[",
            f"  ({lean_string(BOOK_MODULE_ROUTE)}, `{BOOK_MODULE}),",
            "]",
            "",
            f"def siteRoot : String := {lean_string(site_root)}",
            f"def siteBase : String := {lean_string(site_root)}",
            f"def docsRoot : String := {lean_string(site_root + 'docs/')}",
            f"def staticRoot : String := {lean_string(site_root + 'static/style.css')}",
            "",
            f"def sidebarDataJson : String := {lean_string(sidebar_json)}",
            "",
            "end ReasBookSite.Sections",
            "",
        ]
    )


def emit_route_table() -> str:
    work_page = f"ReasBookSite.WorkPages.Books.{BOOK}"
    literate_page = f"Book.{BOOK_MODULE}"
    return "\n".join(
        [
            "-- This file is generated by scripts/gen_sections.py",
            "-- Do not edit manually.",
            "",
            "import VersoBlog",
            "import ReasBookSite.Home",
            "import Book",
            f"import {work_page}",
            "",
            "open Verso Genre Blog Site Syntax",
            "",
            "namespace ReasBookSite.RouteTable",
            "",
            'scoped syntax "reasbook_site_dir" : dir_spec',
            "",
            "macro_rules",
            "  | `(dir_spec| reasbook_site_dir) =>",
            "    `(dir_spec| /",
            '      static "static" ← "./static_files"',
            f"      {lean_string(BOOK_HOME_ROUTE)} {work_page}",
            f"      {lean_string(BOOK_MODULE_ROUTE)} {literate_page}",
            "    )",
            "",
            "def reasbook_site : Site := site ReasBookSite.Home /",
            '  static "static" ← "./static_files"',
            f"  {lean_string(BOOK_HOME_ROUTE)} {work_page}",
            f"  {lean_string(BOOK_MODULE_ROUTE)} {literate_page}",
            "",
            "end ReasBookSite.RouteTable",
            "",
        ]
    )


def emit_work_page(book_dir: Path, site_root: str) -> str:
    owner, repo, branch = github_coordinates()
    repo_tree = f"https://github.com/{owner}/{repo}/tree/{branch}"
    source_root = f"{repo_tree}/ReasBook/Books/{BOOK}/"
    docs_link = f"{site_root}docs/Books/{BOOK}/Book.html"
    lines = [
        "import VersoBlog",
        "open Verso Genre Blog",
        "",
        f"#doc (Page) {lean_string(BOOK_TITLE)} =>",
        "",
        f"- [Documentation]({docs_link})",
        f"- [Lean source path]({source_root})",
        "",
        "Chapter source index:",
        "",
    ]
    chapters = chapter_directories(book_dir)
    if not chapters:
        lines.append("- No chapter directories were found.")
    else:
        for chapter, path, module_count in chapters:
            source_link = f"{source_root}{path.name}/"
            noun = "module" if module_count == 1 else "modules"
            lines.append(
                f"- [Chapter {chapter:02d}]({source_link}) ({module_count} Lean {noun})"
            )
    lines.append("")
    return "\n".join(lines)


def remove_stale_work_pages(work_pages_root: Path, keep: Path) -> None:
    if not work_pages_root.exists():
        return
    keep = keep.resolve()
    for page in sorted(work_pages_root.rglob("*.lean")):
        if page.resolve() == keep:
            continue
        page.unlink()
        print(f"Removed stale work page {page}")


def main() -> None:
    args = parse_args()
    repo_root = (
        Path(args.repo_root).resolve()
        if args.repo_root is not None
        else Path(__file__).resolve().parents[2]
    )
    source_root = repo_root / "ReasBook"
    web_root = repo_root / "ReasBookWeb"
    book_dir = source_root / "Books" / BOOK
    book_file = book_dir / "Book.lean"

    if not book_file.is_file():
        raise SystemExit(f"Book aggregate not found: {book_file}")

    site_root = normalize_site_root(os.environ.get("REASBOOK_SITE_ROOT", "/ReasBook/"))
    sections = web_root / "ReasBookSite" / "Sections.lean"
    routes = web_root / "ReasBookSite" / "RouteTable.lean"
    work_pages = web_root / "ReasBookSite" / "WorkPages"
    book_page = work_pages / "Books" / f"{BOOK}.lean"

    remove_stale_work_pages(work_pages, book_page)
    write_text_if_changed(sections, emit_sections(site_root))
    write_text_if_changed(routes, emit_route_table())
    write_text_if_changed(book_page, emit_work_page(book_dir, site_root))


if __name__ == "__main__":
    main()
