import Mathlib
import LinearRepresentations_Serre_1977.Chap18.Definition_18_18_1_1

/-!
Support for Theorem 18-18.2-1, Serre part `(a)`: the "mixed characteristic realization" layer.

This file provides the torsion bookkeeping needed to transport a Brauer-character relation over
an arbitrary coefficient field `K` (equipped with an injective multiplicative lift of the
prime-to-`p` roots of unity) down to a trace relation over the residue field `k` itself:

* the `p`-regular exponent `pRegularExponent p G` bounding all `p`-regular element orders;
* a generator of the corresponding torsion of `PrimeToPRoot p k` and the classification of all
  torsion elements as its powers;
* congruence and ring-homomorphism compatibility lemmas for `Representation.modularCharacter`
  showing that only the lift's values on the relevant torsion matter;
* a finite scaling lemma inside a valuation subring;
* the construction of a residue ring homomorphism from a valuation subring of the subfield
  generated by the lifted torsion back into `k`, sending the lifted generator to a primitive
  root of unity of the same order.
-/

noncomputable section

universe u v x

namespace Representation

section PRegularExponent

variable (p : ℕ) (G : Type u) [Group G] [Finite G]

open scoped Classical in
/-- The least common multiple of the orders of the `p`-regular elements of `G`.  Serre's prime-to-
`p` part of the exponent of `G`; every `p`-regular element order divides it and it is prime to
`p`. -/
def pRegularExponent : ℕ :=
  letI : Fintype G := Fintype.ofFinite G
  (Finset.univ.filter fun t : G ↦ IsPRegular p t).lcm orderOf

variable {p G}

theorem orderOf_dvd_pRegularExponent {t : G} (ht : IsPRegular p t) :
    orderOf t ∣ pRegularExponent p G := by
  classical
  letI : Fintype G := Fintype.ofFinite G
  -- The order of a `p`-regular element is one of the lcm factors.
  unfold pRegularExponent
  refine Finset.dvd_lcm ?_
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  exact ht

private theorem lcm_orderOf_ne_zero (s : Finset G) : Finset.lcm s orderOf ≠ 0 := by
  classical
  induction s using Finset.induction with
  | empty => simp
  | insert a s ha ih =>
      rw [Finset.lcm_insert]
      -- An lcm of nonzero numbers is nonzero.
      exact Nat.lcm_ne_zero (orderOf_pos a).ne' ih

theorem pRegularExponent_ne_zero : pRegularExponent p G ≠ 0 := by
  classical
  letI : Fintype G := Fintype.ofFinite G
  unfold pRegularExponent
  exact lcm_orderOf_ne_zero _

private theorem not_prime_dvd_lcm_orderOf (hp : p.Prime) (s : Finset G)
    (hmem : ∀ a ∈ s, ¬ p ∣ orderOf a) : ¬ p ∣ Finset.lcm s orderOf := by
  classical
  induction s using Finset.induction with
  | empty =>
      rw [Finset.lcm_empty]
      intro h
      rw [Nat.dvd_one] at h
      exact hp.ne_one h
  | insert a s ha ih =>
      rw [Finset.lcm_insert]
      intro hdvd
      -- A prime dividing an lcm of two numbers divides their product, hence one of them.
      have hmul : p ∣ orderOf a * Finset.lcm s orderOf :=
        hdvd.trans (lcm_dvd (dvd_mul_right _ _) (dvd_mul_left _ _))
      rcases (Nat.Prime.dvd_mul hp).1 hmul with h | h
      · exact hmem a (Finset.mem_insert_self a s) h
      · exact ih (fun b hb ↦ hmem b (Finset.mem_insert_of_mem hb)) h

theorem not_prime_dvd_pRegularExponent (hp : p.Prime) : ¬ p ∣ pRegularExponent p G := by
  classical
  letI : Fintype G := Fintype.ofFinite G
  unfold pRegularExponent
  refine not_prime_dvd_lcm_orderOf hp _ ?_
  intro a hamem
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hamem
  exact (Nat.Prime.coprime_iff_not_dvd hp).1 hamem

theorem coprime_pRegularExponent (hp : p.Prime) :
    Nat.Coprime p (pRegularExponent p G) :=
  (Nat.Prime.coprime_iff_not_dvd hp).2 (not_prime_dvd_pRegularExponent hp)

end PRegularExponent

section TorsionGenerator

variable {p : ℕ} [Fact p.Prime]
variable {k : Type u} [Field k] [IsAlgClosed k] [CharP k p]
variable {G : Type u} [Group G] [Finite G]

/-- Helper: `k` contains a primitive `m`-th root of unity for every `m` prime to `p`. -/
theorem exists_unit_orderOf_eq {m : ℕ} (hm : m ≠ 0) (hpm : ¬ p ∣ m) :
    ∃ u : kˣ, orderOf u = m := by
  haveI : NeZero ((m : k)) := ⟨by
    rw [Ne, CharP.cast_eq_zero_iff k p m]
    exact hpm⟩
  haveI : NeZero m := ⟨hm⟩
  obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot k m
  have hunit : IsUnit ζ := hζ.isUnit hm
  refine ⟨hunit.unit, ?_⟩
  have hζu : IsPrimitiveRoot hunit.unit m := hζ.isUnit_unit hm
  exact (hζu.eq_orderOf).symm

/-- Helper: torsion classification against a unit of maximal order — every `m`-torsion unit is a
power of a unit of order `m`. -/
theorem eq_pow_of_orderOf_eq_of_pow_eq_one {u x : kˣ} {m : ℕ} (hm : m ≠ 0)
    (hu : orderOf u = m) (hx : x ^ m = 1) :
    ∃ t : ℕ, x = u ^ t := by
  haveI : NeZero m := ⟨hm⟩
  have hprim : IsPrimitiveRoot u m := hu ▸ IsPrimitiveRoot.orderOf u
  obtain ⟨t, _ht, hxt⟩ :=
    hprim.eq_pow_of_mem_rootsOfUnity ((mem_rootsOfUnity m x).mpr hx)
  exact ⟨t, hxt.symm⟩

/-- The torsion generator for Theorem 18-18.2-1: an element of `PrimeToPRoot p k` of order
`pRegularExponent p G` whose powers exhaust the corresponding torsion. -/
theorem exists_torsion_generator (p : ℕ) [Fact p.Prime] (k : Type u) [Field k] [IsAlgClosed k]
    [CharP k p] (G : Type u) [Group G] [Finite G] :
    ∃ ζ : PrimeToPRoot p k,
      orderOf ζ = pRegularExponent p G ∧
        ∀ x : PrimeToPRoot p k, x ^ pRegularExponent p G = 1 → ∃ t : ℕ, x = ζ ^ t := by
  obtain ⟨u, hu⟩ :=
    exists_unit_orderOf_eq (k := k) (m := pRegularExponent p G)
      (pRegularExponent_ne_zero (p := p) (G := G))
      (not_prime_dvd_pRegularExponent (p := p) (G := G) Fact.out)
  have humem : u ∈ primeToPRoots p k := by
    change IsPRegular p u
    unfold IsPRegular
    rw [hu]
    exact coprime_pRegularExponent (G := G) Fact.out
  refine ⟨⟨u, humem⟩, ?_, ?_⟩
  · -- The subgroup inclusion preserves orders.
    have := orderOf_injective (primeToPRoots p k).subtype (primeToPRoots p k).subtype_injective
      ⟨u, humem⟩
    simpa [hu] using this
  · intro x hx
    have hxu : (x : kˣ) ^ pRegularExponent p G = 1 := by
      have := congrArg (Subgroup.subtype (primeToPRoots p k)) hx
      simpa using this
    obtain ⟨t, hxt⟩ :=
      eq_pow_of_orderOf_eq_of_pow_eq_one (u := u) (x := (x : kˣ))
        (pRegularExponent_ne_zero (p := p) (G := G)) hu hxu
    refine ⟨t, ?_⟩
    apply Subtype.ext
    simpa using hxt

/-- Every root packaged by `charpolyRoot_primeToPRoot` at a `p`-regular element of `G` is
`pRegularExponent p G`-torsion. -/
theorem charpolyRoot_primeToPRoot_pow_pRegularExponent
    {V : Type x} [AddCommGroup V] [Module k V] [Module.Finite k V]
    (ρ : Representation k G V) {s : G} (hs : IsPRegular p s) {μ : k}
    (hμ : μ ∈ (ρ s).charpoly.roots) :
    (charpolyRoot_primeToPRoot (p := p) (k := k) ρ hs hμ) ^ pRegularExponent p G = 1 := by
  -- The packaged root is an `orderOf s`-th root of unity and `orderOf s` divides the
  -- `p`-regular exponent.
  have hcoe :
      ((charpolyRoot_primeToPRoot (p := p) (k := k) ρ hs hμ : kˣ)) ^ orderOf s = 1 := by
    have hmem := (charpolyRoot_rootsOfUnity_orderOf ρ s hμ).property
    rw [mem_rootsOfUnity] at hmem
    exact hmem
  have hdvd : orderOf s ∣ pRegularExponent p G := orderOf_dvd_pRegularExponent hs
  have hcoe' :
      ((charpolyRoot_primeToPRoot (p := p) (k := k) ρ hs hμ : kˣ)) ^ pRegularExponent p G = 1 := by
    obtain ⟨c, hc⟩ := hdvd
    rw [hc, pow_mul, hcoe, one_pow]
  apply Subtype.ext
  simpa using hcoe'

end TorsionGenerator

section ModularCharacterTransport

variable {p : ℕ} [Fact p.Prime]
variable {k : Type u} [Field k] [IsAlgClosed k] [CharP k p]
variable {G : Type u} [Group G] [Finite G]
variable {V : Type x} [AddCommGroup V] [Module k V] [Module.Finite k V]

/-- The modular character only depends on the lift through its values on the
`pRegularExponent p G`-torsion of `PrimeToPRoot p k`. -/
theorem modularCharacter_congr_of_eqOn_torsion
    {A : Type v} [AddCommMonoid A]
    {lift₁ lift₂ : PrimeToPRoot p k → A}
    (h : ∀ x : PrimeToPRoot p k, x ^ pRegularExponent p G = 1 → lift₁ x = lift₂ x)
    (ρ : Representation k G V) (s : { g : G // IsPRegular p g }) :
    modularCharacter lift₁ ρ s = modularCharacter lift₂ ρ s := by
  unfold modularCharacter
  refine congrArg Multiset.sum ?_
  refine Multiset.map_congr rfl ?_
  intro μ _
  exact h _ (charpolyRoot_primeToPRoot_pow_pRegularExponent (p := p) ρ s.2 μ.2)

omit [Fact p.Prime] [CharP k p] [Finite G] in
/-- Ring homomorphisms commute with the modular character through the lift. -/
theorem ringHom_modularCharacter
    {A : Type v} [NonAssocSemiring A] {B : Type x} [NonAssocSemiring B]
    (σ : A →+* B) (lift : PrimeToPRoot p k → A)
    (ρ : Representation k G V) (s : { g : G // IsPRegular p g }) :
    σ (modularCharacter lift ρ s) = modularCharacter (fun x ↦ σ (lift x)) ρ s := by
  unfold modularCharacter
  rw [map_multiset_sum]
  rw [Multiset.map_map]
  rfl

omit [Fact p.Prime] [CharP k p] [Finite G] in
/-- When the lift factors through the field value of the root, the modular character is a plain
multiset sum over the characteristic polynomial roots. -/
theorem modularCharacter_eq_roots_sum
    {A : Type v} [AddCommMonoid A] (f : k → A) {lift : PrimeToPRoot p k → A}
    (hlift : ∀ x : PrimeToPRoot p k, lift x = f ((x : kˣ) : k))
    (ρ : Representation k G V) (s : { g : G // IsPRegular p g }) :
    modularCharacter lift ρ s = (((ρ s.1).charpoly.roots).map f).sum := by
  unfold modularCharacter
  refine congrArg Multiset.sum ?_
  have hmap :
      ((ρ s.1).charpoly.roots.attach.map fun μ ↦
          lift (charpolyRoot_primeToPRoot (p := p) (k := k) ρ s.2 μ.2)) =
        ((ρ s.1).charpoly.roots.attach.map fun μ ↦ f μ.1) := by
    refine Multiset.map_congr rfl ?_
    intro μ _
    rw [hlift]
    rw [charpolyRoot_primeToPRoot_coe]
  rw [hmap]
  -- Collapse the attached map to a plain map over the root multiset.
  have := Multiset.attach_map_val ((ρ s.1).charpoly.roots)
  calc
    ((ρ s.1).charpoly.roots.attach.map fun μ ↦ f μ.1) =
        (((ρ s.1).charpoly.roots.attach.map Subtype.val).map f) := by
          rw [Multiset.map_map]
          rfl
    _ = ((ρ s.1).charpoly.roots).map f := by rw [this]

end ModularCharacterTransport

section PowerInverse

variable {p : ℕ} [Fact p.Prime]
variable {G : Type u} [Group G] [Finite G]

/-- A `p`-regular element raised to its `pRegularExponent`-th power is trivial. -/
theorem pow_pRegularExponent_eq_one {t : G} (ht : IsPRegular p t) :
    t ^ pRegularExponent p G = 1 := by
  obtain ⟨c, hc⟩ := orderOf_dvd_pRegularExponent ht
  rw [hc, pow_mul, pow_orderOf_eq_one, one_pow]

/-- Powers prime to the `p`-regular exponent admit a uniform inverse exponent on the `p`-regular
locus. -/
theorem exists_pow_inverse {b : ℕ} (hco : Nat.Coprime b (pRegularExponent p G)) :
    ∃ b' : ℕ, 0 < b' ∧ ∀ t : G, IsPRegular p t → (t ^ b) ^ b' = t := by
  have hm0 : pRegularExponent p G ≠ 0 := pRegularExponent_ne_zero (p := p) (G := G)
  by_cases h1 : pRegularExponent p G = 1
  · -- Degenerate case: the only `p`-regular element is the identity.
    refine ⟨1, Nat.one_pos, ?_⟩
    intro t ht
    have htriv : t = 1 := by
      have := orderOf_dvd_pRegularExponent ht
      rw [h1, Nat.dvd_one] at this
      exact orderOf_eq_one_iff.mp this
    simp [htriv]
  · have hlt : 1 < pRegularExponent p G :=
      Nat.lt_of_le_of_ne (Nat.one_le_iff_ne_zero.mpr hm0) (Ne.symm h1)
    obtain ⟨b', _hb'lt, hb'⟩ := Nat.exists_mul_mod_eq_one_of_coprime hco hlt
    have hb'pos : 0 < b' := by
      rcases Nat.eq_zero_or_pos b' with h0 | hpos
      · rw [h0, Nat.mul_zero, Nat.zero_mod] at hb'
        exact absurd hb'.symm one_ne_zero
      · exact hpos
    refine ⟨b', hb'pos, ?_⟩
    intro t ht
    obtain ⟨q, hq⟩ : ∃ q, b * b' = pRegularExponent p G * q + 1 := by
      refine ⟨b * b' / pRegularExponent p G, ?_⟩
      conv_lhs => rw [← Nat.div_add_mod (b * b') (pRegularExponent p G)]
      rw [hb']
    calc
      (t ^ b) ^ b' = t ^ (b * b') := by rw [← pow_mul]
      _ = (t ^ pRegularExponent p G) ^ q * t := by
            rw [hq, pow_add, pow_mul, pow_one]
      _ = t := by rw [pow_pRegularExponent_eq_one ht, one_pow, one_mul]

end PowerInverse

section ValuationScaling

variable {L : Type v} [Field L]

/-- Inside a valuation subring, any finite family of field elements with a nonzero member can be
scaled by one of its nonzero members so that all ratios become integral. This is Serre's
denominator-normalization step, with the valuation replacing the discrete valuation of his
modular system. -/
theorem exists_valuation_scaling_index {ι : Type x} (B : ValuationSubring L)
    (c : ι → L) (s : Finset ι) (hwit : ∃ i ∈ s, c i ≠ 0) :
    ∃ j₀ ∈ s, c j₀ ≠ 0 ∧ ∀ j ∈ s, c j / c j₀ ∈ B := by
  classical
  induction s using Finset.induction with
  | empty =>
      obtain ⟨i, hi, _⟩ := hwit
      exact absurd hi (Finset.notMem_empty i)
  | insert a s ha ih =>
      by_cases htail : ∃ i ∈ s, c i ≠ 0
      · obtain ⟨j₀, hj₀s, hj₀ne, hall⟩ := ih htail
        -- Compare the new entry against the current pivot through the valuation.
        rcases B.mem_or_inv_mem (c a / c j₀) with hmem | hmemInv
        · refine ⟨j₀, Finset.mem_insert_of_mem hj₀s, hj₀ne, ?_⟩
          intro j hj
          rcases Finset.mem_insert.mp hj with rfl | hjs
          · exact hmem
          · exact hall j hjs
        · by_cases hca : c a = 0
          · refine ⟨j₀, Finset.mem_insert_of_mem hj₀s, hj₀ne, ?_⟩
            intro j hj
            rcases Finset.mem_insert.mp hj with rfl | hjs
            · rw [hca, zero_div]
              exact zero_mem _
            · exact hall j hjs
          · -- The new entry has smaller valuation: switch the pivot to it.
            refine ⟨a, Finset.mem_insert_self a s, hca, ?_⟩
            intro j hj
            rcases Finset.mem_insert.mp hj with rfl | hjs
            · rw [div_self hca]
              exact one_mem _
            · have hinv : c j₀ / c a ∈ B := by
                rwa [inv_div] at hmemInv
              have hfactor : c j / c a = c j / c j₀ * (c j₀ / c a) := by
                field_simp
              rw [hfactor]
              exact mul_mem (hall j hjs) hinv
      · -- All previous entries vanish, so the new entry carries the witness.
        have hall0 : ∀ i ∈ s, c i = 0 := by
          intro i his
          by_contra hne
          exact htail ⟨i, his, hne⟩
        have hca : c a ≠ 0 := by
          obtain ⟨i, hi, hci⟩ := hwit
          rcases Finset.mem_insert.mp hi with rfl | his
          · exact hci
          · exact absurd (hall0 i his) hci
        refine ⟨a, Finset.mem_insert_self a s, hca, ?_⟩
        intro j hj
        rcases Finset.mem_insert.mp hj with rfl | hjs
        · rw [div_self hca]
          exact one_mem _
        · rw [hall0 j hjs, zero_div]
          exact zero_mem _

end ValuationScaling

section CharDichotomy

variable {p : ℕ} [Fact p.Prime]
variable {k : Type u} [Field k] [IsAlgClosed k] [CharP k p]

/-- A field admitting an injective multiplicative lift of all prime-to-`p` roots of unity of an
algebraically closed field of characteristic `p` has characteristic `0` or `p`. -/
theorem ringChar_eq_zero_or_eq_of_injective_lift {K : Type v} [Field K]
    (lift : PrimeToPRoot p k →* Kˣ) (hlift : Function.Injective lift) :
    ringChar K = 0 ∨ ringChar K = p := by
  rcases CharP.char_is_prime_or_zero K (ringChar K) with hprime | hzero
  · by_cases hp : ringChar K = p
    · exact Or.inr hp
    · exfalso
      -- `k` has a `p`-regular unit of order `ringChar K`, whose lift would be a nontrivial
      -- `ringChar K`-torsion unit of `K`.
      have hnd : ¬ p ∣ ringChar K := by
        intro hdvd
        exact hp (((Nat.prime_dvd_prime_iff_eq Fact.out hprime).mp hdvd).symm)
      obtain ⟨u, hu⟩ :=
        exists_unit_orderOf_eq (p := p) (k := k) (m := ringChar K) hprime.ne_zero hnd
      have humem : u ∈ primeToPRoots p k := by
        change IsPRegular p u
        unfold IsPRegular
        rw [hu]
        exact (Nat.coprime_primes Fact.out hprime).mpr (fun h ↦ hp h.symm)
      have horder : orderOf (lift ⟨u, humem⟩) = ringChar K := by
        rw [orderOf_injective lift hlift]
        have := orderOf_injective (primeToPRoots p k).subtype
          (primeToPRoots p k).subtype_injective ⟨u, humem⟩
        simpa [hu] using this
      -- In characteristic `ringChar K`, the only `ringChar K`-torsion unit is `1`.
      have hpow : ((lift ⟨u, humem⟩ : Kˣ) : K) ^ ringChar K = 1 := by
        have := pow_orderOf_eq_one (lift ⟨u, humem⟩)
        rw [horder] at this
        exact_mod_cast congrArg (Units.coeHom K) this
      haveI : Fact (ringChar K).Prime := ⟨hprime⟩
      have hsub : (((lift ⟨u, humem⟩ : Kˣ) : K) - 1) ^ ringChar K = 0 := by
        rw [sub_pow_char, hpow, one_pow, sub_self]
      have hone : ((lift ⟨u, humem⟩ : Kˣ) : K) = 1 := by
        have := pow_eq_zero_iff hprime.ne_zero |>.mp hsub
        exact sub_eq_zero.mp this
      have : lift ⟨u, humem⟩ = 1 := Units.ext hone
      rw [this, orderOf_one] at horder
      exact hprime.one_lt.ne horder
  · exact Or.inl hzero

end CharDichotomy

section ResidueData

variable {p : ℕ} [Fact p.Prime]
variable {k : Type u} [Field k] [IsAlgClosed k] [CharP k p]

/-- The mixed-characteristic realization for Theorem 18-18.2-1, Serre part `(a)`: a valuation
subring of the coefficient subfield together with a residue homomorphism into `k` carrying the
lifted torsion generator to a primitive root of unity of `k` of the same order. -/
theorem exists_residue_data {L : Type v} [Field L]
    {m₀ : ℕ} (hm₀ : m₀ ≠ 0) (hpm₀ : ¬ p ∣ m₀)
    (η : Lˣ) (hη : orderOf η = m₀)
    (hchar : ringChar L = 0 ∨ ringChar L = p)
    (halg : ∀ x : L, ∃ q : Polynomial ℤ, Polynomial.aeval x q = 0 ∧
      q.map (Int.castRingHom (ZMod p)) ≠ 0) :
    ∃ (B : ValuationSubring L) (θ : B →+* k) (ξ : kˣ),
      Subring.closure {((η : Lˣ) : L)} ≤ B.toSubring ∧
      orderOf ξ = m₀ ∧
      ∀ (x : B) (t : ℕ), (x : L) = ((η : Lˣ) : L) ^ t → θ x = ((ξ : kˣ) : k) ^ t := by
  classical
  set ηL : L := ((η : Lˣ) : L) with hηL
  have hηLpow : ηL ^ m₀ = 1 := by
    have := pow_orderOf_eq_one η
    rw [hη] at this
    exact_mod_cast congrArg (Units.coeHom L) this
  set R : Subring L := Subring.closure {ηL} with hRdef
  have hηmem : ηL ∈ R := Subring.subset_closure rfl
  -- Every element of `R` is integral over `ℤ` (needed only in characteristic zero).
  have hint : ∀ x ∈ R, IsIntegral ℤ x := by
    intro x hx
    induction hx using Subring.closure_induction with
    | mem y hy =>
        rcases hy with rfl
        refine ⟨Polynomial.X ^ m₀ - Polynomial.C 1, ?_, ?_⟩
        · exact Polynomial.monic_X_pow_sub_C (1 : ℤ) hm₀
        · simp [Polynomial.eval₂_sub, hηLpow]
    | one => exact isIntegral_one
    | zero => exact isIntegral_zero
    | add y z _ _ hy hz => exact hy.add hz
    | neg y _ hy => exact hy.neg
    | mul y z _ _ hy hz => exact hy.mul hz
  -- `p` is not invertible in `R`.
  have hp_ne_top : Ideal.span {((p : ℕ) : R)} ≠ ⊤ := by
    intro htop
    rw [Ideal.span_singleton_eq_top] at htop
    obtain ⟨w, hw⟩ := htop.exists_right_inv
    have hwL : ((p : ℕ) : L) * ((w : R) : L) = 1 := by
      have := congrArg (R.subtype) hw
      simpa using this
    rcases hchar with h0 | hpchar
    · haveI : CharP L 0 := ringChar.eq_iff.mp h0
      haveI : CharZero L := CharP.charP_to_charZero L
      -- `w` is an integral element equal to `p⁻¹`, contradicting integral closedness of `ℤ`.
      have hpQ : ((p : ℕ) : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero
      have hwval : ((w : R) : L) = algebraMap ℚ L ((p : ℚ)⁻¹) := by
        have hL : ((w : R) : L) = ((p : ℕ) : L)⁻¹ :=
          eq_inv_of_mul_eq_one_left (by rw [mul_comm] at hwL; exact hwL)
        rw [hL, map_inv₀, map_natCast]
      have hwint : IsIntegral ℤ ((w : R) : L) := hint _ (SetLike.coe_mem w)
      rw [hwval] at hwint
      have hratint : IsIntegral ℤ ((p : ℚ)⁻¹) :=
        (isIntegral_algebraMap_iff (FaithfulSMul.algebraMap_injective ℚ L)).mp hwint
      obtain ⟨z, hz⟩ := IsIntegrallyClosed.isIntegral_iff.mp hratint
      have hmulQ : ((p : ℤ) : ℚ) * ((z : ℤ) : ℚ) = 1 := by
        have hz' : ((z : ℤ) : ℚ) = ((p : ℕ) : ℚ)⁻¹ := by
          rw [← hz]
          simp [algebraMap]
        rw [hz']
        push_cast
        rw [mul_inv_cancel₀ hpQ]
      have hzint : (p : ℤ) * z = 1 := by exact_mod_cast hmulQ
      have hpone : (p : ℤ) = 1 :=
        Int.eq_one_of_mul_eq_one_right (by positivity) hzint
      have : p = 1 := by exact_mod_cast hpone
      exact (Fact.out : p.Prime).one_lt.ne' this
    · haveI : CharP L p := ringChar.eq_iff.mp hpchar
      have : ((p : ℕ) : L) = 0 := CharP.cast_eq_zero L p
      rw [this, zero_mul] at hwL
      exact zero_ne_one hwL
  obtain ⟨𝔪, h𝔪max, h𝔪le⟩ := Ideal.exists_le_maximal _ hp_ne_top
  obtain ⟨B, hRB, hnon⟩ :=
    Ideal.image_subset_nonunits_valuationSubring (A := R) 𝔪 h𝔪max.ne_top
  have hηB : ηL ∈ B.toSubring := hRB hηmem
  set ηB : B := ⟨ηL, hηB⟩ with hηBdef
  have hηBpow : ηB ^ m₀ = 1 := by
    apply Subtype.ext
    push_cast
    exact hηLpow
  -- `p` is a nonunit of `B`, so the residue field has characteristic `p`.
  have hpnonL : ((p : ℕ) : L) ∈ B.nonunits := by
    have hp𝔪 : ((p : ℕ) : R) ∈ 𝔪 := h𝔪le (Ideal.subset_span rfl)
    have himg : R.subtype ((p : ℕ) : R) ∈ R.subtype '' (𝔪 : Set R) :=
      Set.mem_image_of_mem _ hp𝔪
    have := hnon himg
    simpa using this
  have hpBnotunit : ¬ IsUnit ((p : ℕ) : B) := by
    intro hunit
    obtain ⟨v, hv⟩ := hunit.exists_right_inv
    have hvL : ((p : ℕ) : L) * ((v : B) : L) = 1 := by
      exact_mod_cast congrArg (fun y : B ↦ (y : L)) hv
    rcases (ValuationSubring.mem_nonunits_iff_or B).mp hpnonL with h0 | hninv
    · rw [h0, zero_mul] at hvL
      exact zero_ne_one hvL
    · apply hninv
      have hinv : ((p : ℕ) : L)⁻¹ = ((v : B) : L) :=
        (eq_inv_of_mul_eq_one_left (by rw [mul_comm] at hvL; exact hvL)).symm
      rw [hinv]
      exact SetLike.coe_mem v
  have hpmax : ((p : ℕ) : B) ∈ IsLocalRing.maximalIdeal B :=
    IsLocalRing.mem_maximalIdeal _ |>.mpr hpBnotunit
  have hpκ : ((p : ℕ) : IsLocalRing.ResidueField B) = 0 := by
    have hres : IsLocalRing.residue B ((p : ℕ) : B) = 0 :=
      (IsLocalRing.residue_eq_zero_iff _).mpr hpmax
    rw [← map_natCast (IsLocalRing.residue B) p]
    exact hres
  haveI hκchar : CharP (IsLocalRing.ResidueField B) p := by
    have hdvd : ringChar (IsLocalRing.ResidueField B) ∣ p := ringChar.dvd hpκ
    rcases (Nat.Prime.eq_one_or_self_of_dvd Fact.out _ hdvd) with h1 | hp
    · exact absurd h1 (CharP.ringChar_ne_one)
    · exact ringChar.eq_iff.mp hp
  letI : Algebra (ZMod p) (IsLocalRing.ResidueField B) := ZMod.algebra _ p
  letI : Algebra (ZMod p) k := ZMod.algebra _ p
  -- The residue field is algebraic over its prime field.
  haveI halgκ : Algebra.IsAlgebraic (ZMod p) (IsLocalRing.ResidueField B) := by
    constructor
    intro y
    obtain ⟨x, rfl⟩ := IsLocalRing.residue_surjective (R := B) y
    obtain ⟨q, hq0, hqp⟩ := halg (x : L)
    have hxq : Polynomial.aeval x q = 0 := by
      have hcomm :
          (B.subtype.toIntAlgHom) (Polynomial.aeval x q) =
            Polynomial.aeval (B.subtype.toIntAlgHom x) q :=
        (Polynomial.aeval_algHom_apply (B.subtype.toIntAlgHom) x q).symm
      have hLzero : (B.subtype.toIntAlgHom) (Polynomial.aeval x q) = 0 := by
        rw [hcomm]
        exact hq0
      -- the subring inclusion is injective
      have hinj : Function.Injective (B.subtype) := Subtype.coe_injective
      apply hinj
      simpa using hLzero
    have hyq : Polynomial.aeval (IsLocalRing.residue B x) q = 0 := by
      have hcomm :
          Polynomial.aeval (IsLocalRing.residue B x) q =
            ((IsLocalRing.residue B).toIntAlgHom) (Polynomial.aeval x q) :=
        (Polynomial.aeval_algHom_apply ((IsLocalRing.residue B).toIntAlgHom) x q)
      rw [hcomm, hxq, map_zero]
    refine ⟨q.map (Int.castRingHom (ZMod p)), hqp, ?_⟩
    rw [Polynomial.aeval_def, Polynomial.eval₂_map]
    rw [show ((algebraMap (ZMod p) (IsLocalRing.ResidueField B)).comp
          (Int.castRingHom (ZMod p))) = algebraMap ℤ (IsLocalRing.ResidueField B) from
        Subsingleton.elim _ _]
    rw [← Polynomial.aeval_def]
    exact hyq
  -- Embed the residue field into `k`.
  let ε : IsLocalRing.ResidueField B →ₐ[ZMod p] k := IsAlgClosed.lift
  let θ : B →+* k := ε.toRingHom.comp (IsLocalRing.residue B)
  set ξk : k := θ ηB with hξkdef
  have hξkpow : ξk ^ m₀ = 1 := by
    rw [← map_pow, hηBpow, map_one]
  -- The factors `1 - ξk ^ d` for `0 < d < m₀` are nonzero, hence `ξk` has exact order `m₀`.
  obtain ⟨n, hn⟩ : ∃ n, m₀ = n + 1 := ⟨m₀ - 1, (Nat.succ_pred_eq_of_pos (Nat.pos_of_ne_zero hm₀)).symm⟩
  have hprimL : IsPrimitiveRoot ηL m₀ := by
    have : IsPrimitiveRoot η (orderOf η) := IsPrimitiveRoot.orderOf η
    rw [hη] at this
    exact IsPrimitiveRoot.coe_units_iff.mpr this
  have hprodL : (∏ d ∈ Finset.range n, ((1 : L) - ηL ^ (d + 1))) = ((n : L) + 1) := by
    have := IsPrimitiveRoot.prod_one_sub_pow_eq_order (n := n) (μ := ηL) (hn ▸ hprimL)
    exact_mod_cast this
  have hprodB : (∏ d ∈ Finset.range n, ((1 : B) - ηB ^ (d + 1))) = ((m₀ : ℕ) : B) := by
    apply Subtype.ext
    push_cast
    rw [hprodL, hn]
    push_cast
    ring
  have hm₀k : ((m₀ : ℕ) : k) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff k p]
    exact hpm₀
  have hθprod : (∏ d ∈ Finset.range n, ((1 : k) - ξk ^ (d + 1))) = ((m₀ : ℕ) : k) := by
    have := congrArg θ hprodB
    rw [map_prod] at this
    simpa [map_sub, map_pow, map_natCast] using this
  have hfac : ∀ d, 0 < d → d < m₀ → (1 : k) - ξk ^ d ≠ 0 := by
    intro d hd0 hdm h0
    apply hm₀k
    rw [← hθprod]
    refine Finset.prod_eq_zero (i := d - 1) ?_ ?_
    · rw [Finset.mem_range]
      omega
    · have : d - 1 + 1 = d := by omega
      rw [this]
      exact h0
  have hξkunit : IsUnit ξk := IsUnit.of_pow_eq_one hξkpow hm₀
  refine ⟨B, θ, hξkunit.unit, hRB, ?_, ?_⟩
  · -- exact order `m₀`
    rw [orderOf_eq_iff (Nat.pos_of_ne_zero hm₀)]
    constructor
    · apply Units.ext
      push_cast [hξkunit.unit_spec]
      exact hξkpow
    · intro m hmlt hm0 hcon
      have hval : ξk ^ m = 1 := by
        have := congrArg (fun u : kˣ ↦ (u : k)) hcon
        push_cast [hξkunit.unit_spec] at this
        exact this
      exact hfac m hm0 hmlt (by rw [hval, sub_self])
  · -- the power law for `θ`
    intro x t hxt
    have hxeq : x = ηB ^ t := by
      apply Subtype.ext
      push_cast
      exact hxt
    rw [hxeq, map_pow]
    rw [hξkunit.unit_spec]

end ResidueData

end Representation
