import Mathlib
import stacks_project.Chap15.Lemma_15_8_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open Matrix
open exteriorPower

namespace LinearMap

section

variable {R : Type u} [CommRing R] {m n : ℕ}

/-- The exterior rank of a linear map between finite free `R`-modules is the largest `r` such that
the induced map on `r`th exterior powers is nonzero. -/
noncomputable def exteriorRank (φ : (Fin m → R) →ₗ[R] (Fin n → R)) : ℕ :=
  letI : DecidablePred fun r ↦ exteriorPower.map r φ ≠ 0 := Classical.decPred _
  Nat.findGreatest (fun r ↦ exteriorPower.map r φ ≠ 0) (min m n)

/-- The exterior rank of a map `φ : R^m → R^n` is bounded by `min m n`. -/
-- Proof sketch: this is immediate from the definition by `Nat.findGreatest`, whose output is
-- always bounded by the search bound `min m n`.
theorem exteriorRank_le_min (φ : (Fin m → R) →ₗ[R] (Fin n → R)) :
    exteriorRank φ ≤ min m n := sorry

/-- Definition 10.102.5: the ideal `I(φ)` of a map `φ : R^m → R^n` is generated by the minors of
size equal to the exterior rank of `φ`. -/
noncomputable def rankMinorIdeal (φ : (Fin m → R) →ₗ[R] (Fin n → R)) : Ideal R :=
  minorIdeal (exteriorRank φ) <|
    LinearMap.toMatrix (Pi.basisFun R (Fin m)) (Pi.basisFun R (Fin n)) φ

notation:max "I(" φ ")" => LinearMap.rankMinorIdeal φ

/-- Every minor of the matrix of `φ` of size `LinearMap.exteriorRank φ` belongs to `I(φ)`. -/
-- Proof sketch: unfold `I(φ)` and use the defining generator-set inclusion
-- into `Ideal.span`.
theorem det_submatrix_mem_rankMinorIdeal (φ : (Fin m → R) →ₗ[R] (Fin n → R))
    (e₁ : Fin (exteriorRank φ) ↪ Fin n) (e₂ : Fin (exteriorRank φ) ↪ Fin m) :
    Matrix.det
        ((LinearMap.toMatrix (Pi.basisFun R (Fin m)) (Pi.basisFun R (Fin n)) φ).submatrix e₁ e₂) ∈
      I(φ) := by
  simpa [rankMinorIdeal] using
    det_submatrix_mem_minorIdeal (exteriorRank φ)
      (LinearMap.toMatrix (Pi.basisFun R (Fin m)) (Pi.basisFun R (Fin n)) φ) e₁ e₂

end

end LinearMap
