import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Lemma_10_129_1 (from Chap10) -/
universe u v

open RingTheory Sequence

section

variable {k : Type u} {S : Type v}
variable [Field k] [CommRing S] [Algebra k S] [Algebra.FiniteType k S]
variable [CohenMacaulayRing S] [TopologicalSpace.EquidimensionalSpace (PrimeSpectrum S)]

/-
Domain-style sampling:
* primary domain: regular sequences in Cohen-Macaulay affine rings of finite type over a field,
  organized through the chapter owners for local Cohen-Macaulayness, local dimension, and regular
  sequences;
* sampled owner declarations of the same kind:
  `CohenMacaulayRing`,
  `TopologicalSpace.EquidimensionalSpace`,
  `topologicalKrullDimAt_eq_iInf_ringKrullDim_localizationAtMaximal_over`,
  `isRegular_iff_ringKrullDim_quotient_add_length_eq`;
* best owner abstraction: the ambient owners are `CohenMacaulayRing S` and
  `EquidimensionalSpace (PrimeSpectrum S)`, while the local regular-sequence conclusion should be
  phrased directly with `IsRegular` on `Localization.AtPrime q.asIdeal`;
* primitive data: the finite list `fs` and the quotient-dimension bound;
* derived API: the exact dimension formula for `S ⧸ Ideal.ofList fs` and the regularity of the
  localized sequence at primes containing `Ideal.ofList fs`.

Source/core/bridge triage:
* `source-facing`: Lemma 10.129.1, giving the expected codimension of the quotient together with
  local regularity along `V(Ideal.ofList fs)`;
* `core/canonical`: `CohenMacaulayRing`, `EquidimensionalSpace`, `ringKrullDim`,
  `Localization.AtPrime`, and the chapter owner theorem
  `isRegular_iff_ringKrullDim_quotient_add_length_eq`;
* `bridge/view`: passing from the global equidimensional ring to the local rings
  `Localization.AtPrime q.asIdeal` via the local-dimension owner
  `topologicalKrullDimAt_eq_iInf_ringKrullDim_localizationAtMaximal_over`.

The dimension parameter `d` is not primitive data here: it is completely determined by the owner
`ringKrullDim S`. Keeping it as a separate public binder would only duplicate the canonical global
dimension owner. The quotient-dimension comparison should therefore be written in the chapter's
canonical additive form rather than by subtraction on `ringKrullDim`.
-/
-- Proof sketch: use the equidimensionality and Cohen-Macaulay hypotheses to identify the Krull
-- dimension of every maximal localization of `S` with `ringKrullDim S`. For a prime `q`
-- containing
-- `Ideal.ofList fs`, localize at a maximal ideal above `q` and apply Proposition `10.103.4` in
-- that Cohen-Macaulay local ring to the image of `fs`, using the assumed bound on the quotient
-- dimension in the canonical form
-- `ringKrullDim (S ⧸ Ideal.ofList fs) + fs.length = ringKrullDim S`. This gives both the expected
-- codimension formula and regularity of the localized sequence at every such `q`.
/-- Lemma 10.129.1: let `k` be a field, let `S` be a finite type `k`-algebra, and let `fs` be a
finite list of elements of `S`. Assume that `S` is Cohen-Macaulay and equidimensional of
dimension `ringKrullDim S`, and that the quotient by the ideal generated by `fs` has the expected
codimension lower bound, written canonically as
`ringKrullDim (S ⧸ Ideal.ofList fs) + fs.length ≤ ringKrullDim S`. Then in fact
`ringKrullDim (S ⧸ Ideal.ofList fs) + fs.length = ringKrullDim S`, and for every prime `q` of `S`
containing `Ideal.ofList fs`, the image of `fs` in the local ring `S_q` is a regular sequence. -/
theorem ringKrullDim_quotient_add_length_eq_and_isRegular_atPrime_of_cohenMacaulay_equidimensional
    {fs : List S}
    (hquot : ringKrullDim (S ⧸ Ideal.ofList fs) + fs.length ≤ ringKrullDim S) :
    ringKrullDim (S ⧸ Ideal.ofList fs) + fs.length = ringKrullDim S ∧
      ∀ q : PrimeSpectrum S, Ideal.ofList fs ≤ q.asIdeal →
        IsRegular (Localization.AtPrime q.asIdeal)
          (fs.map (algebraMap S (Localization.AtPrime q.asIdeal))) := sorry

end

/-! ### Lemma_10_129_2 (from Chap10) -/
noncomputable section

universe u v

open PrimeSpectrum
open RingTheory Sequence
open scoped PrimeSpectrum

section

variable {R : Type u} [CommRing R]
variable {S : Type v} [CommRing S] [Algebra R S]

/-
Domain-style sampling:
* primary domain: regular-sequence loci on the canonical fiber local rings over `Spec R`;
* sampled owner declarations of the same kind:
  `fiberLocalRingAt`,
  `toFiberLocalRingAt`,
  `PrimeSpectrum.IsRegularInFiberLocalRing`,
  `PrimeSpectrum.zeroLocus`,
  `RingTheory.Sequence.IsRegular`;
* best owner abstraction: the source-facing locus should live directly on the closed subspace
  `V(Ideal.ofList fs)`, because containment of `Ideal.ofList fs` is primitive data in the source
  statement; the pointwise regular-sequence owner on a prime `q` should be the bridge
  `q.IsRegularInFiberLocalRing R fs`, whose canonical content is regularity of the image of `fs`
  in the owner fiber local ring `fiberLocalRingAt R S q`;
* primitive data: the list `fs`, the point `q : V(Ideal.ofList fs)`, and regularity of the image
  of `fs` in the owner fiber local ring at `q.1`;
* derived API: the named regular-sequence locus on `V(Ideal.ofList fs)` and the openness theorem
  below.

Source/core/bridge triage:
* `source-facing`: the regular-sequence locus inside `V(Ideal.ofList fs)` and its openness;
* `core/canonical`: `fiberLocalRingAt`, `toFiberLocalRingAt`, and `Sequence.IsRegular`;
* `bridge/view`: `PrimeSpectrum.IsRegularInFiberLocalRing`, the subtype-valued locus, and its
  point-membership lemma.
-/

/-- The locus in `V(Ideal.ofList fs)` where the images of `fs` form a regular sequence in the
local fiber ring. -/
def fiberLocalRingRegularSequenceLocus (R : Type u) [CommRing R]
    (S : Type v) [CommRing S] [Algebra R S] (fs : List S) :
    Set (V((Ideal.ofList fs : Set S))) :=
  { q | q.1.IsRegularInFiberLocalRing R fs }

/-- A point of `V(Ideal.ofList fs)` lies in `fiberLocalRingRegularSequenceLocus` exactly when the
images of `fs` form a regular sequence in the corresponding local fiber ring. -/
theorem mem_fiberLocalRingRegularSequenceLocus_iff
    (fs : List S) (q : V((Ideal.ofList fs : Set S))) :
    q ∈ fiberLocalRingRegularSequenceLocus R S fs ↔
      q.1.IsRegularInFiberLocalRing R fs := by
  rfl

variable [Algebra.FiniteType R S]

-- Proof sketch: for `q` in the locus, pass to the quotient `S ⧸ Ideal.ofList fs`. The fiber over
-- `q ∩ R` stays Cohen--Macaulay and equidimensional, and `hConstDim` identifies its Krull
-- dimension with that of every other fiber. Regularity of `fs` in the local fiber ring gives the
-- expected dimension drop by `fs.length` for the quotient fiber. Lemma `10.125.6` then yields an
-- open neighborhood on which all quotient fibers have relative dimension bounded by this common
-- fiber dimension minus `fs.length`, and Lemma `10.129.1` upgrades that bound to regularity of the
-- localized sequence at every nearby point. Hence the locus is open inside `V(fs)`.
/-- Lemma 10.129.2: let `R → S` be a finite type ring map, and let `fs` be a finite list of
elements of `S`. Assume every fiber `κ(𝔭) ⊗[R] S` is Cohen--Macaulay and equidimensional, and
that these fibers all have the same Krull dimension. Then the primes `q` of `S` containing
`Ideal.ofList fs` for which the images of `fs` form a regular sequence in the local fiber ring at
`q` form an open subset of `V(Ideal.ofList fs)`. -/
theorem isOpen_fiberLocalRingRegularSequenceLocusWithinZeroLocus_of_fiberwise_cohenMacaulay_equidimensional
    (fs : List S)
    (hCM : ∀ p : PrimeSpectrum R, CohenMacaulayRing (p.asIdeal.Fiber S))
    (hEqdim : ∀ p : PrimeSpectrum R,
      TopologicalSpace.EquidimensionalSpace (PrimeSpectrum (p.asIdeal.Fiber S)))
    (hConstDim : ∀ p p' : PrimeSpectrum R,
      ringKrullDim (p.asIdeal.Fiber S) = ringKrullDim (p'.asIdeal.Fiber S)) :
    IsOpen (fiberLocalRingRegularSequenceLocus R S fs) := sorry

end

/-! ### Lemma_10_129_3 (from Chap10) -/
noncomputable section

universe u v w

open CategoryTheory ChainComplex HomologicalComplex
open scoped TensorProduct

section

variable {R : Type u} [CommRing R]
variable {S : Type v} [CommRing S] [Algebra R S]
variable {e : ℕ}

namespace FiniteFreeComplex

/- Domain triage:
* primary domain: exactness of bounded finite free complexes after passage to the fiber local ring;
* sampled owner declarations in this domain:
  `FiniteFreeComplex.ExactInPositiveDegrees`,
  `FiniteFreeComplex.toChainComplex`,
  `toFiberLocalRingAt`,
  `fiberLocalRingAt`, and
  `ModuleCat.extendScalars`;
* best owner abstraction: `FiniteFreeComplex.ExactInPositiveDegrees` is the chapter owner for
  fiberwise exactness in positive degrees; the scalar extension of `C` to
  `fiberLocalRingAt R S q` is the canonical `bridge/view` object connecting the source-facing
  fiberwise predicate to that owner abstraction;
* primitive versus derived API: the primitive data here are `C`, the owner fiber local ring, and
  the scalar-extended finite free complex `C.fiberComplexAt R q`; the pointwise predicate
  `C.ExactInPositiveDegreesAtFiber R q` is the source-facing owner on primes, and the exact locus
  is the derived set-valued API built from that pointwise predicate.
-/

/-- The finite free complex over the fiber local ring at `q` obtained from `C` by scalar
extension along `S → fiberLocalRingAt R S q`. -/
noncomputable def fiberComplexAt (C : FiniteFreeComplex S e) (R : Type u) [CommRing R]
    [Algebra R S] (q : PrimeSpectrum S) : FiniteFreeComplex (fiberLocalRingAt R S q) e where
  toChainComplex :=
    { X := fun i ↦ ModuleCat.of (fiberLocalRingAt R S q)
          ((fiberLocalRingAt R S q) ⊗[S] ↑(C.toChainComplex.X i))
      d := fun i j ↦ ModuleCat.ofHom
          (LinearMap.baseChange (fiberLocalRingAt R S q) (C.toChainComplex.d i j).hom)
      shape := fun i j hij ↦ by
        sorry
      d_comp_d' := fun i j k _ _ ↦ by
        sorry }
  isZero_toChainComplex_X i hi := by
    sorry
  rank := C.rank
  termIso i := by
    change ModuleCat.of (fiberLocalRingAt R S q)
        ((fiberLocalRingAt R S q) ⊗[S] ↑(C.toChainComplex.X i)) ≅
      ModuleCat.of (fiberLocalRingAt R S q) (Fin (C.rank i) → fiberLocalRingAt R S q)
    let hbase :
        ModuleCat.of (fiberLocalRingAt R S q)
            ((fiberLocalRingAt R S q) ⊗[S] ↑(C.toChainComplex.X i)) ≅
          ModuleCat.of (fiberLocalRingAt R S q)
            ((fiberLocalRingAt R S q) ⊗[S] (Fin (C.rank i) → S)) :=
      (LinearEquiv.baseChange S (fiberLocalRingAt R S q) (C.toChainComplex.X i)
        (Fin (C.rank i) → S) (C.termIso i).toLinearEquiv).toModuleIso
    let hpi :
        ModuleCat.of (fiberLocalRingAt R S q)
            ((fiberLocalRingAt R S q) ⊗[S] (Fin (C.rank i) → S)) ≅
          ModuleCat.of (fiberLocalRingAt R S q) (Fin (C.rank i) → fiberLocalRingAt R S q) := by
      simpa using
        (TensorProduct.piScalarRight S (fiberLocalRingAt R S q) (fiberLocalRingAt R S q)
          (Fin (C.rank i))).toModuleIso
    exact hbase ≪≫ hpi

/-- The fiber complex of `C` at `q` is exact in the positive degrees. -/
def ExactInPositiveDegreesAtFiber (C : FiniteFreeComplex S e) (R : Type u) [CommRing R]
    [Algebra R S] (q : PrimeSpectrum S) : Prop :=
  (C.fiberComplexAt R q).ExactInPositiveDegrees

/-- A prime `q` lies in the fiberwise exactness predicate exactly when the scalar-extended fiber
complex at `q` is exact in positive degrees. -/
theorem exactInPositiveDegreesAtFiber_iff (C : FiniteFreeComplex S e) (R : Type u) [CommRing R]
    [Algebra R S] (q : PrimeSpectrum S) :
    C.ExactInPositiveDegreesAtFiber R q ↔ (C.fiberComplexAt R q).ExactInPositiveDegrees := by
  rfl

/-- The primes `q : Spec(S)` where the localized fiber complex
`F_{•,q} ⊗[R] κ(q ∩ R)` attached to `C` is exact in positive degrees. -/
def fiberExactLocus (C : FiniteFreeComplex S e) (R : Type u) [CommRing R] [Algebra R S] :
    Set (PrimeSpectrum S) :=
  { q | C.ExactInPositiveDegreesAtFiber R q }

/-- A prime lies in `fiberExactLocus` exactly when the corresponding fiber complex is exact in
positive degrees. -/
theorem mem_fiberExactLocus_iff (C : FiniteFreeComplex S e) (R : Type u) [CommRing R]
    [Algebra R S] (q : PrimeSpectrum S) :
    q ∈ C.fiberExactLocus R ↔ C.ExactInPositiveDegreesAtFiber R q := by
  rfl

end FiniteFreeComplex

variable [IsNoetherianRing R] [Algebra.FiniteType R S] [Module.Flat R S]

-- Proof sketch: apply the Buchsbaum--Eisenbud exactness criterion on each local fiber ring to
-- translate exactness of the fiber complex into determinantal-ideal conditions. Flatness lets one
-- compare the localized complex with the residue-fiber complex, and Lemma `10.129.2` makes the
-- required regular-sequence conditions open under the assumption that all fibers are
-- Cohen--Macaulay of constant Krull dimension.
/-- Lemma 10.129.3: let `R → S` be a finite type flat ring map with `R` Noetherian, and let
`C : FiniteFreeComplex S e` encode a finite complex `0 → S^{n_e} → ⋯ → S^{n_0}`. If there is a
constant such that every fiber ring `κ(𝔭) ⊗[R] S` is Cohen--Macaulay of that Krull dimension,
then the set of primes `q : Spec(S)` for which the fiber complex
`F_{•,q} ⊗[R] κ(q ∩ R)` is exact is an open subset of `Spec(S)`. -/
theorem isOpen_setOf_exactInPositiveDegreesAtFiber (C : FiniteFreeComplex S e)
    (hCM : ∀ p : PrimeSpectrum R, CohenMacaulayRing (p.asIdeal.Fiber S))
    (hConstDim : ∀ p p' : PrimeSpectrum R,
      ringKrullDim (p.asIdeal.Fiber S) = ringKrullDim (p'.asIdeal.Fiber S)) :
    IsOpen { q : PrimeSpectrum S | C.ExactInPositiveDegreesAtFiber R q } := sorry

/-- The fiber exactness locus is open under the fiberwise Cohen--Macaulay and constant-dimension
hypotheses of Lemma `10.129.3`. -/
theorem isOpen_fiberExactLocus (C : FiniteFreeComplex S e)
    (hCM : ∀ p : PrimeSpectrum R, CohenMacaulayRing (p.asIdeal.Fiber S))
    (hConstDim : ∀ p p' : PrimeSpectrum R,
      ringKrullDim (p.asIdeal.Fiber S) = ringKrullDim (p'.asIdeal.Fiber S)) :
    IsOpen (C.fiberExactLocus R) := by
  simpa [FiniteFreeComplex.fiberExactLocus] using
    isOpen_setOf_exactInPositiveDegreesAtFiber C hCM hConstDim

end

/-! ### Theorem_10_129_4 (from Chap10) -/
universe u v w

namespace Module

section

variable (R : Type u) (S : Type v) (M : Type w)
variable [CommRing R] [CommRing S] [Algebra R S]
variable [AddCommGroup M] [Module S M] [Module R M] [IsScalarTower R S M]

/- Domain-style sampling:
- primary domain: flatness loci of finitely presented modules over a base ring on `Spec(S)`;
- sampled owner declarations in the surrounding chapter/project:
  `GenericFlatness.goodLocus`,
  `relativeDimensionAtLELocus`,
  `Ideal.IsFlatOverBaseLocus`,
  `Module.flatOverBaseLocus`;
- best owner abstraction here: the point-set owner
  `Module.flatOverBaseLocus R S M : Set (PrimeSpectrum S)`;
- primitive data: the base ring `R`, the target algebra `S`, and the `S`-module `M` viewed over
  `R`;
- derived API: the membership lemma and the openness theorem under finite-presentation
  hypotheses.

Source/core/bridge triage:
- `source-facing`: the Stacks-theorem openness statement for the flatness locus on `Spec(S)`;
- `core/canonical`: `Module.flatOverBaseLocus`;
- `bridge/view`: downstream closed-subset reformulations such as `Ideal.IsFlatOverBaseLocus`.
-/

/-- The locus in `Spec(S)` where the localized `S`-module `M_q` is flat over the base ring `R`. -/
def flatOverBaseLocus : Set (PrimeSpectrum S) :=
  { q | Module.Flat R (LocalizedModule.AtPrime q.asIdeal M) }

/-- Membership in `flatOverBaseLocus R S M` means that `M_q` is flat over `R`. -/
@[simp] theorem mem_flatOverBaseLocus (q : PrimeSpectrum S) :
    q ∈ flatOverBaseLocus R S M ↔
      Module.Flat R (LocalizedModule.AtPrime q.asIdeal M) :=
  Iff.rfl

variable [Algebra.FinitePresentation R S] [Module.FinitePresentation S M]

/-- Theorem 10.129.4: for a finitely presented ring map `R → S` and a finitely presented
`S`-module `M`, the set of primes `q` of `S` such that the localization `M_q` is flat over `R`
is an open subset of `Spec(S)`. -/
-- Proof sketch: for a prime `q` where `M_q` is flat over `R`, first descend the data to a finite
-- type `ℤ`-model using Lemma `10.127.18` and recover flatness at a stage via Lemma `10.128.3`.
-- Then reduce to the Noetherian case, resolve `M` by a bounded finite free complex, show the top
-- syzygy becomes free near `q`, and apply Lemma `10.129.3` together with the flatness criterion
-- from Lemma `10.99.5` to obtain a basic open neighborhood contained in the flat locus.
theorem isOpen_flatOverBaseLocus_of_finitePresentation :
    IsOpen (flatOverBaseLocus R S M) := sorry

end

end Module
