import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Lemma_10_43_8 (from Chap10) -/
open scoped TensorProduct
open Algebra
open Algebra.TensorProduct

universe u v

section

variable {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
variable [Algebra.IsSeparable k K]

/-
Layer note:
- `source-facing`: the existence of a localization presentation for the multiplication map
  `K ⊗[k] K → K`;
- `core/canonical`: separability is owned upstream by `Algebra.FormallyEtale` /
  `Algebra.FormallyUnramified`, organized around the tensor-product multiplication map `lmul'`;
- `bridge/view`: this lemma keeps the Stacks source conclusion that the diagonal map is a
  localization, with the submonoid as derived witness data rather than primitive structure.
-/
/-
Lemma 10.43.8 (Tag 0C2X): for a separable algebraic extension `K / k`, the tensor-product
multiplication map `K ⊗[k] K →ₐ[k] K` is a localization map at some multiplicative subset of
`K ⊗[k] K`.
-/
-- Proof sketch: the owner abstraction is the formally étale / formally unramified structure
-- attached to a separable field extension. In the finite separable case, choose a primitive
-- element, identify `K ⊗[k] K` with `K[X] / (P)` for the minimal polynomial `P`, factor
-- `P = (X - α) Q`, and localize away from the image of `Q`. For a general separable algebraic
-- extension, write `K` as the directed union of its finite separable subextensions and take the
-- union of the corresponding multiplicative subsets.
/-- Helper for Lemma 10.43.8: adjoining finitely many elements of a separable extension still
gives a separable intermediate extension. -/
lemma finite_adjoin_stage_isSeparable (t : Finset K) :
    Algebra.IsSeparable k (IntermediateField.adjoin k (t : Set K)) := by
  -- Every generator in the finite stage is already separable over `k`.
  rw [IntermediateField.isSeparable_adjoin_iff_isSeparable]
  intro x hx
  exact Algebra.IsSeparable.isSeparable k x

/-- Helper for Lemma 10.43.8: a finite adjoin stage is essentially of finite type over the base
field. -/
lemma finite_adjoin_stage_essFiniteType (t : Finset K) :
    Algebra.EssFiniteType k (IntermediateField.adjoin k (t : Set K)) := by
  -- The adjoin stage is generated by the finite set used to define it.
  rw [IntermediateField.essFiniteType_iff]
  exact ⟨t, rfl⟩

/-- Helper for Lemma 10.43.8: multiplication commutes with transporting tensors from an
intermediate field stage into the ambient extension. -/
lemma lmul_comp_adjoin_tensor_map (L : IntermediateField k K) :
    (TensorProduct.lmul' k : K ⊗[k] K →ₐ[k] K).comp
        (Algebra.TensorProduct.map (IsScalarTower.toAlgHom k L K) (IsScalarTower.toAlgHom k L K)) =
      (IsScalarTower.toAlgHom k L K).comp
        (TensorProduct.lmul' k : L ⊗[k] L →ₐ[k] L) := by
  -- Both composites send `x ⊗ y` to the product of the images of `x` and `y`.
  apply AlgHom.ext
  intro z
  refine TensorProduct.induction_on z ?_ ?_ ?_
  · simp
  · intro x y
    simp [TensorProduct.lmul'_apply_tmul]
  · intro x y hx hy
    simp [map_add, AlgHom.comp_apply, hx, hy]

/-- Helper for Lemma 10.43.8: transporting a stage tensor through a larger finite adjoin stage
does not change its image in the ambient tensor product. -/
lemma adjoin_tensor_map_comp_inclusion
    {E F : IntermediateField k K} (hEF : E ≤ F) (z : E ⊗[k] E) :
    Algebra.TensorProduct.map
        (IsScalarTower.toAlgHom k F K)
        (IsScalarTower.toAlgHom k F K)
        (Algebra.TensorProduct.map
          (IntermediateField.inclusion hEF)
          (IntermediateField.inclusion hEF)
          z) =
      Algebra.TensorProduct.map
        (IsScalarTower.toAlgHom k E K)
        (IsScalarTower.toAlgHom k E K)
        z := by
  -- Route correction: prove the transport identity pointwise, so later rewrites are direct.
  refine TensorProduct.induction_on z ?_ ?_ ?_
  · simp
  · intro x y
    simp [IntermediateField.coe_inclusion]
  · intro x y hx hy
    simp [map_add, hx, hy]

/-- Helper for Lemma 10.43.8: every tensor in `K ⊗[k] K` is already defined over a finite adjoin
stage of `K / k`. -/
lemma exists_finite_adjoin_stage_tensor (z : K ⊗[k] K) :
    ∃ t : Finset K,
      ∃ zt :
        IntermediateField.adjoin k (t : Set K) ⊗[k] IntermediateField.adjoin k (t : Set K),
        Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k (IntermediateField.adjoin k (t : Set K)) K)
            (IsScalarTower.toAlgHom k (IntermediateField.adjoin k (t : Set K)) K) zt = z := by
  -- Route correction: carry the tensor induction out stage-by-stage, making the additive
  -- transport through the union stage explicit.
  classical
  refine TensorProduct.induction_on z ?_ ?_ ?_
  · let t : Finset K := ∅
    let zt :
        IntermediateField.adjoin k (t : Set K) ⊗[k] IntermediateField.adjoin k (t : Set K) := 0
    refine ⟨t, zt, ?_⟩
    -- The zero tensor is already defined over the empty finite stage.
    simp [t, zt]
  · intro x y
    let t : Finset K := ({x, y} : Finset K)
    let L := IntermediateField.adjoin k (t : Set K)
    have hxt : x ∈ (t : Set K) := by
      simp [t]
    have hyt : y ∈ (t : Set K) := by
      simp [t]
    have hxL : x ∈ L := by
      exact IntermediateField.subset_adjoin k (t : Set K) hxt
    have hyL : y ∈ L := by
      exact IntermediateField.subset_adjoin k (t : Set K) hyt
    let xL : L := ⟨x, hxL⟩
    let yL : L := ⟨y, hyL⟩
    let zt : L ⊗[k] L := xL ⊗ₜ[k] yL
    refine ⟨t, zt, ?_⟩
    -- A pure tensor is defined over the stage generated by its two coordinates.
    simp [t, L, xL, yL, zt]
  · intro x y hx hy
    rcases hx with ⟨tx, ztx, htx⟩
    rcases hy with ⟨ty, zty, hty⟩
    let Lx := IntermediateField.adjoin k (tx : Set K)
    let Ly := IntermediateField.adjoin k (ty : Set K)
    let t : Finset K := tx ∪ ty
    let L := IntermediateField.adjoin k (t : Set K)
    have htx_subset : (tx : Set K) ⊆ (t : Set K) := by
      intro z hz
      simp [t, hz]
    have hty_subset : (ty : Set K) ⊆ (t : Set K) := by
      intro z hz
      simp [t, hz]
    have hLx : Lx ≤ L := by
      rw [IntermediateField.adjoin_le_iff]
      exact fun z hz ↦ IntermediateField.subset_adjoin k (t : Set K) (htx_subset hz)
    have hLy : Ly ≤ L := by
      rw [IntermediateField.adjoin_le_iff]
      exact fun z hz ↦ IntermediateField.subset_adjoin k (t : Set K) (hty_subset hz)
    let ztx' : L ⊗[k] L :=
      Algebra.TensorProduct.map
        (IntermediateField.inclusion hLx)
        (IntermediateField.inclusion hLx)
        ztx
    let zty' : L ⊗[k] L :=
      Algebra.TensorProduct.map
        (IntermediateField.inclusion hLy)
        (IntermediateField.inclusion hLy)
        zty
    refine ⟨t, ztx' + zty', ?_⟩
    -- Transport both finite-stage tensors into the union stage and then rewrite back to the
    -- ambient sum using the pointwise transport lemma.
    calc
      Algebra.TensorProduct.map
          (IsScalarTower.toAlgHom k L K)
          (IsScalarTower.toAlgHom k L K)
          (ztx' + zty') =
        Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k L K)
            (IsScalarTower.toAlgHom k L K)
            ztx' +
          Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k L K)
            (IsScalarTower.toAlgHom k L K)
            zty' := by
          simp [ztx', zty']
      _ =
        Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k Lx K)
            (IsScalarTower.toAlgHom k Lx K)
            ztx +
          Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k Ly K)
            (IsScalarTower.toAlgHom k Ly K)
            zty := by
          rw [adjoin_tensor_map_comp_inclusion (k := k) (K := K) hLx ztx,
            adjoin_tensor_map_comp_inclusion (k := k) (K := K) hLy zty]
      _ = x + y := by
          simpa [Lx, Ly] using congrArg₂ HAdd.hAdd htx hty

/-- Helper for Lemma 10.43.8: ambient multiplication on a transported stage tensor is the image
of the stage multiplication. -/
lemma lmul_adjoin_tensor_map_apply
    (L : IntermediateField k K) (z : L ⊗[k] L) :
    TensorProduct.lmul' k
        (Algebra.TensorProduct.map
          (IsScalarTower.toAlgHom k L K)
          (IsScalarTower.toAlgHom k L K)
          z) =
      IsScalarTower.toAlgHom k L K (TensorProduct.lmul' k z) := by
  -- Evaluate the algebra-hom transport identity on the chosen tensor.
  simpa using DFunLike.congr_fun (lmul_comp_adjoin_tensor_map (k := k) (K := K) L) z

/-- Helper for Lemma 10.43.8: for an essentially finite type formally unramified algebra, the
canonical tensor denominator annihilates the kernel of multiplication. -/
lemma tensor_elem_annihilates_of_lmul_eq_zero
    {L : Type*} [Field L] [Algebra k L]
    [Algebra.FormallyUnramified k L] [Algebra.EssFiniteType k L]
    (z : L ⊗[k] L) (hz : TensorProduct.lmul' k z = 0) :
    z * Algebra.FormallyUnramified.elem k L = 0 := by
  -- First rewrite the kernel of `lmul'` as the span of the standard tensor differences.
  have hzspan :
      z ∈ Submodule.span L (Set.range fun s : L => (1 : L) ⊗ₜ[k] s - s ⊗ₜ[k] (1 : L)) := by
    rw [KaehlerDifferential.submodule_span_range_eq_ideal]
    simpa [KaehlerDifferential.ideal, RingHom.mem_ker] using hz
  -- Then use span induction, with the generator case supplied by the canonical denominator API.
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hzspan
  · rintro _ ⟨s, rfl⟩
    exact Algebra.FormallyUnramified.one_tmul_sub_tmul_one_mul_elem (R := k) s
  · simp
  · intro x y hx hy hx' hy'
    simpa [add_mul, hx', hy'] using congrArg₂ HAdd.hAdd hx' hy'
  · intro a x hx hx'
    simpa [smul_eq_mul, mul_assoc, hx'] using congrArg (fun z ↦ a * z) hx'

/-- Helper for Lemma 10.43.8: the transported denominator from a finite adjoin stage maps to `1`
under the ambient multiplication map. -/
lemma finite_adjoin_stage_denominator_maps_to_one (t : Finset K) :
    let L := IntermediateField.adjoin k (t : Set K)
    let _ : Algebra.IsSeparable k L := finite_adjoin_stage_isSeparable (k := k) (K := K) t
    let _ : Algebra.EssFiniteType k L := finite_adjoin_stage_essFiniteType (k := k) (K := K) t
    let _ : Algebra.FormallyUnramified k L := Algebra.FormallyUnramified.of_isSeparable k L
    TensorProduct.lmul' k
      (Algebra.TensorProduct.map
        (IsScalarTower.toAlgHom k L K)
        (IsScalarTower.toAlgHom k L K)
        (Algebra.FormallyUnramified.elem k L)) = 1 := by
  -- Evaluate the multiplication transport on the canonical denominator, then use the finite-stage
  -- formally unramified identity.
  let L := IntermediateField.adjoin k (t : Set K)
  letI : Algebra.IsSeparable k L := finite_adjoin_stage_isSeparable (k := k) (K := K) t
  letI : Algebra.EssFiniteType k L := finite_adjoin_stage_essFiniteType (k := k) (K := K) t
  letI : Algebra.FormallyUnramified k L := Algebra.FormallyUnramified.of_isSeparable k L
  calc
    TensorProduct.lmul' k
        (Algebra.TensorProduct.map
          (IsScalarTower.toAlgHom k L K)
          (IsScalarTower.toAlgHom k L K)
          (Algebra.FormallyUnramified.elem k L)) =
      IsScalarTower.toAlgHom k L K
        (TensorProduct.lmul' k (Algebra.FormallyUnramified.elem k L)) := by
          simpa using
            lmul_adjoin_tensor_map_apply (k := k) (K := K) L
              (Algebra.FormallyUnramified.elem k L)
    _ = 1 := by
          simp [Algebra.FormallyUnramified.lmul_elem]

/-- Lemma 10.43.8 (Tag 0C2X): for a separable algebraic extension `K / k`, the tensor-product
multiplication map `K ⊗[k] K →ₐ[k] K` is a localization map at some multiplicative subset of
`K ⊗[k] K`. -/
@[stacks 0C2X]
theorem exists_submonoid_tensorProduct_self_isLocalization :
    ∃ S : Submonoid (K ⊗[k] K),
      S.IsLocalizationMap (lmul' k) := by
  -- Route correction: use the ambient submonoid of tensors mapping to `1`, and then show that
  -- finite-stage denominators give the cancellation witnesses demanded by localization.
  let carrier : Set (K ⊗[k] K) := { z | TensorProduct.lmul' k z = 1 }
  have h_one : (1 : K ⊗[k] K) ∈ carrier := by
    simp [carrier]
  have h_mul :
      ∀ {a b : K ⊗[k] K}, a ∈ carrier → b ∈ carrier → a * b ∈ carrier := by
    intro a b ha hb
    rw [show a * b ∈ carrier ↔ TensorProduct.lmul' k (a * b) = 1 by rfl]
    rw [map_mul, ha, hb, one_mul]
  let S : Submonoid (K ⊗[k] K) := {
    carrier := carrier
    one_mem' := h_one
    mul_mem' := fun ha hb ↦ h_mul ha hb
  }
  refine ⟨S, ?_⟩
  refine
    { map_units := ?_
      surj := ?_
      exists_of_eq := ?_ }
  · intro s
    -- Membership in `S` says exactly that the image is `1`, hence a unit.
    change IsUnit (TensorProduct.lmul' k (s : K ⊗[k] K))
    rw [s.2]
    exact isUnit_one
  · intro z
    -- Surjectivity is witnessed by the pure tensor `1 ⊗ z` and the unit denominator `1`.
    let s1 : S := ⟨1, h_one⟩
    let x : K ⊗[k] K := 1 ⊗ₜ[k] z
    refine ⟨⟨x, s1⟩, ?_⟩
    simp [x, s1]
  · intro x y hxy
    -- Reduce `x - y` to a finite stage, annihilate it there, and transport the relation back.
    have hsub : TensorProduct.lmul' k (x - y) = 0 := by
      simpa [map_sub, hxy] using sub_self (TensorProduct.lmul' k y)
    obtain ⟨t, zt, hzt⟩ :=
      exists_finite_adjoin_stage_tensor (k := k) (K := K) (x - y)
    let L := IntermediateField.adjoin k (t : Set K)
    have hstage_map :
        IsScalarTower.toAlgHom k L K (TensorProduct.lmul' k zt) = 0 := by
      have hsub_mapped :
          TensorProduct.lmul' k
            (Algebra.TensorProduct.map
              (IsScalarTower.toAlgHom k L K)
              (IsScalarTower.toAlgHom k L K)
              zt) = 0 := by
        rw [hzt]
        exact hsub
      calc
        IsScalarTower.toAlgHom k L K (TensorProduct.lmul' k zt) =
            TensorProduct.lmul' k
              (Algebra.TensorProduct.map
                (IsScalarTower.toAlgHom k L K)
                (IsScalarTower.toAlgHom k L K)
                zt) := by
              symm
              exact lmul_adjoin_tensor_map_apply (k := k) (K := K) L zt
        _ = 0 := by
              exact hsub_mapped
    have hstage_zero : TensorProduct.lmul' k zt = 0 := by
      exact (IsScalarTower.toAlgHom k L K).injective hstage_map
    letI : Algebra.IsSeparable k L := finite_adjoin_stage_isSeparable (k := k) (K := K) t
    letI : Algebra.EssFiniteType k L := finite_adjoin_stage_essFiniteType (k := k) (K := K) t
    letI : Algebra.FormallyUnramified k L := Algebra.FormallyUnramified.of_isSeparable k L
    have hann_stage :
        zt * Algebra.FormallyUnramified.elem k L = 0 := by
      exact tensor_elem_annihilates_of_lmul_eq_zero (k := k) zt hstage_zero
    let c : K ⊗[k] K :=
      Algebra.TensorProduct.map
        (IsScalarTower.toAlgHom k L K)
        (IsScalarTower.toAlgHom k L K)
        (Algebra.FormallyUnramified.elem k L)
    have hc_mem : c ∈ S := by
      change TensorProduct.lmul' k c = 1
      simpa [c, L] using finite_adjoin_stage_denominator_maps_to_one (k := k) (K := K) t
    have hann_ambient : (x - y) * c = 0 := by
      have hmap :=
        congrArg
          (Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k L K)
            (IsScalarTower.toAlgHom k L K))
          hann_stage
      have hmap' : Algebra.TensorProduct.map
            (IsScalarTower.toAlgHom k L K)
            (IsScalarTower.toAlgHom k L K)
            zt * c = 0 := by
        simpa [c, map_mul] using hmap
      rw [← hzt]
      exact hmap'
    have hcancel_right : x * c = y * c := by
      exact sub_eq_zero.mp (by simpa [sub_mul] using hann_ambient)
    have hcancel : (c : K ⊗[k] K) * x = c * y := by
      simpa [mul_comm] using hcancel_right
    let cS : S := ⟨c, hc_mem⟩
    exact ⟨cS, hcancel⟩

end

/-! ### Lemma_10_43_9 (from Chap10) -/
universe u w

namespace Algebra

section

open scoped TensorProduct
open Algebra.TensorProduct

variable {k k' : Type u} {A : Type w}
variable [Field k] [Field k'] [CommRing A]
variable [Algebra k k'] [Algebra k' A] [Algebra k A] [IsScalarTower k k' A]
variable [Algebra.IsSeparable k k']

/-- Helper for Lemma 10.43.9: first commute the outer `k'`-tensor so the eventual
`cancelBaseChange` sees the duplicated base field on the right. -/
noncomputable def tensor_base_change_assoc_equiv_comm
    {K B : Type*} [Field K] [CommRing B] [Algebra k K] [Algebra k' B] [Algebra k B]
    [IsScalarTower k k' B] :
    let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
    TensorProduct k' (TensorProduct k K k') B ≃ₐ[k'] TensorProduct k' B (TensorProduct k K k') :=
  -- Proof comment: this is the source proof's first tensor-order swap.
  let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
  Algebra.TensorProduct.comm k' (TensorProduct k K k') B

/-- Helper for Lemma 10.43.9: after the outer commutation, rewrite the right factor into the
Stacks order `k' ⊗[k] K`. -/
noncomputable def tensor_base_change_assoc_equiv_reorder
    {K B : Type*} [Field K] [CommRing B] [Algebra k K] [Algebra k' B] [Algebra k B]
    [IsScalarTower k k' B] :
    let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
    TensorProduct k' B (TensorProduct k K k') ≃ₐ[k'] TensorProduct k' B (TensorProduct k k' K) :=
  -- Proof comment: freeze the canonical right-factor `k'`-algebra and then apply the standard
  -- `commRight` comparison on that factor only.
  let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
  Algebra.TensorProduct.congr
    (AlgEquiv.refl : B ≃ₐ[k'] B)
    ((Algebra.TensorProduct.commRight k k' K).symm)

/-- Helper for Lemma 10.43.9: once the duplicated base field sits on the right, the standard
`cancelBaseChange` removes it. -/
noncomputable def tensor_base_change_assoc_equiv_cancel
    {K B : Type*} [Field K] [CommRing B] [Algebra k K] [Algebra k' B] [Algebra k B]
    [IsScalarTower k k' B] :
    TensorProduct k' B (TensorProduct k k' K) ≃ₐ[k'] TensorProduct k B K :=
  -- Proof comment: this is the canonical base-change cancellation used in the source proof.
  Algebra.TensorProduct.cancelBaseChange k k' k' B K

/-- Helper for Lemma 10.43.9: the source proof identifies the iterated tensor product
`(K ⊗[k] k') ⊗[k'] A` with the direct base change `K ⊗[k] A`. -/
noncomputable def tensor_base_change_assoc_equiv
    {K B : Type*} [Field K] [CommRing B] [Algebra k K] [Algebra k' B] [Algebra k B]
    [IsScalarTower k k' B] :
    let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
    TensorProduct k' (TensorProduct k K k') B ≃+* TensorProduct k K B :=
  -- Proof comment: follow the Stacks route verbatim: outer commutation, reorder the repeated
  -- base-change factor, cancel the duplicated `k'`, and then swap the remaining tensor factors.
  let _ : Algebra k' (TensorProduct k K k') := Algebra.TensorProduct.rightAlgebra
  (((tensor_base_change_assoc_equiv_comm (k := k) (k' := k') (K := K) (B := B)).trans
      (tensor_base_change_assoc_equiv_reorder (k := k) (k' := k') (K := K) (B := B))).trans
      (tensor_base_change_assoc_equiv_cancel (k := k) (k' := k') (K := K) (B := B))).toRingEquiv.trans
    (Algebra.TensorProduct.comm k B K).toRingEquiv

/-- Helper for Lemma 10.43.9: diagonal multiplication on `k' ⊗[k] k'` is compatible with the
left-factor `k'`-algebra structure. -/
lemma diagonal_lmul_left_commutes (x : k') :
    (TensorProduct.lmul' k : TensorProduct k k' k' →ₐ[k] k')
        (algebraMap k' (TensorProduct k k' k') x) =
      algebraMap k' k' x := by
  -- Proof comment: rewrite the scalar action through the left tensor inclusion and then apply the
  -- standard computation rule for tensor-product multiplication.
  change ((TensorProduct.lmul' k).comp Algebra.TensorProduct.includeLeft) x = x
  simpa using congr($(TensorProduct.lmul'_comp_includeLeft (R := k) (S := k')) x)

/-- Helper for Lemma 10.43.9: the diagonal multiplication map packaged as a `k'`-algebra map for
the left-factor `k'`-algebra structure on `k' ⊗[k] k'`. -/
noncomputable def diagonal_lmul_leftAlgHom :
    TensorProduct k k' k' →ₐ[k'] k' :=
  { __ := (TensorProduct.lmul' k : TensorProduct k k' k' →ₐ[k] k').toRingHom
    commutes' := diagonal_lmul_left_commutes (k := k) (k' := k') }

/-- Helper for Lemma 10.43.9: the packaged diagonal multiplication sends the pure tensor
`1 ⊗ₜ y` to `y`. -/
@[simp] lemma diagonal_lmul_left_apply_one_tmul (y : k') :
    diagonal_lmul_leftAlgHom (1 ⊗ₜ[k] y) = y := by
  -- Proof comment: unwrap the packaged diagonal map and apply the standard pure-tensor formula
  -- for tensor-product multiplication.
  change (TensorProduct.lmul' k : TensorProduct k k' k' →ₐ[k] k') (1 ⊗ₜ[k] y) = y
  simp [TensorProduct.lmul'_apply_tmul]

/-- Helper for Lemma 10.43.9: the localization witness of Lemma `10.43.8` is unchanged after
repackaging diagonal multiplication as the ambient `algebraMap`. -/
lemma diagonal_lmul_left_isLocalizationMap_toAlgebra
    (M : Submonoid (TensorProduct k k' k'))
    (hM : M.IsLocalizationMap (TensorProduct.lmul' k)) :
    letI : Algebra (TensorProduct k k' k') k' := diagonal_lmul_leftAlgHom.toAlgebra
    M.IsLocalizationMap (algebraMap (TensorProduct k k' k') k') := by
  letI : Algebra (TensorProduct k k' k') k' := diagonal_lmul_leftAlgHom.toAlgebra
  -- Proof comment: `toAlgebra` keeps the same underlying ring map, so the localization witness
  -- is literally the same after rewriting the target map as `algebraMap`.
  simpa [diagonal_lmul_leftAlgHom, RingHom.algebraMap_toAlgebra] using hM

/-- Helper for Lemma 10.43.9: the source ring from the right-tensored diagonal localization
identifies with the standard tensor product `K ⊗[k] k'`. -/
noncomputable def diagonal_tensor_source_algEquiv_to_baseChangeRight
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K] :
    let _ : Algebra k' (TensorProduct k k' k') := Algebra.TensorProduct.leftAlgebra
    TensorProduct k' (TensorProduct k k' k') K ≃ₐ[k'] TensorProduct k K k' :=
  -- Proof comment: the source proof uses exactly the outer `comm` followed by the standard
  -- `cancelBaseChange` with the left-factor `k'`-algebra on `k' ⊗[k] k'`.
  let _ : Algebra k' (TensorProduct k k' k') := Algebra.TensorProduct.leftAlgebra
  (Algebra.TensorProduct.comm k' (TensorProduct k k' k') K).trans
    (Algebra.TensorProduct.cancelBaseChange k k' k' K k')

/-- Helper for Lemma 10.43.9: tensoring a `k'`-algebra map on the right by `A` fixes the
canonical right tensor inclusion. -/
theorem tensor_right_map_includeRight_comp_local {Q : Type*} [CommRing Q]
    [Algebra k' Q] (φ : Q →ₐ[k'] A) :
    ((Algebra.TensorProduct.map φ (AlgHom.id k' A)).toRingHom).comp
        Algebra.TensorProduct.includeRight.toRingHom =
      Algebra.TensorProduct.includeRight.toRingHom := by
  ext x
  -- Proof comment: both composites send `x` to the pure tensor `1 ⊗ₜ x`.
  change Algebra.TensorProduct.map φ (AlgHom.id k' A) (1 ⊗ₜ[k'] x) = 1 ⊗ₜ[k'] x
  simp

/-- Helper for Lemma 10.43.9: after tensoring the diagonal multiplication on the right by `K`,
the target is collapsed to `K` through the left-unital tensor equivalence. -/
noncomputable def diagonal_tensor_source_to_lidAlgHom
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K] :
    TensorProduct k' (TensorProduct k k' k') K →ₐ[k'] K :=
  (TensorProduct.lid k' K).toAlgHom.comp
    (Algebra.TensorProduct.map diagonal_lmul_leftAlgHom (AlgHom.id k' K))

/-- Helper for Lemma 10.43.9: the standard map `K ⊗[k] k' → K` is a `k'`-algebra map for the
right-factor `k'`-algebra structure on the tensor product. -/
noncomputable def productMap_rightAlgHom
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K] :
    TensorProduct k K k' →ₐ[k'] K :=
  { __ := (Algebra.TensorProduct.productMap
      (AlgHom.id k K) (IsScalarTower.toAlgHom k k' K)).toRingHom
    commutes' := fun x ↦ by
      -- Proof comment: the right tensor inclusion is exactly the ambient `k'`-algebra map.
      simpa [RingHom.algebraMap_toAlgebra] using
        congr($(Algebra.TensorProduct.productMap_right
          (f := AlgHom.id k K) (g := IsScalarTower.toAlgHom k k' K)) x) }

/-- Helper for Lemma 10.43.9: under the source comparison equivalence, a pure tensor
`x ⊗ₜ y : K ⊗[k] k'` comes from the Stacks-style source tensor `(1 ⊗ₜ y) ⊗ₜ x`. -/
@[simp] lemma diagonal_tensor_source_algEquiv_to_baseChangeRight_symm_tmul
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K]
    (x : K) (y : k') :
    (diagonal_tensor_source_algEquiv_to_baseChangeRight
      (k := k) (k' := k') (K := K)).symm (x ⊗ₜ[k] y) =
      (1 ⊗ₜ[k] y) ⊗ₜ[k'] x := by
  -- Proof comment: unwind the comparison as the inverse of base-change cancellation followed by
  -- the inverse tensor commutor.
  simp [diagonal_tensor_source_algEquiv_to_baseChangeRight]

/-- Helper for Lemma 10.43.9: transporting the right-tensored diagonal multiplication from the
Stacks-style source identifies it with the standard map `K ⊗[k] k' → K`. -/
lemma transported_diagonal_tensor_map_eq_productMap
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K] :
    ((diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K)).toRingHom).comp
        ((diagonal_tensor_source_algEquiv_to_baseChangeRight
          (k := k) (k' := k') (K := K)).symm.toRingHom) =
      (productMap_rightAlgHom (k := k) (k' := k') (K := K)).toRingHom := by
  -- Proof comment: evaluate both maps on a pure tensor and simplify the transported diagonal map
  -- using the explicit inverse formula proved just above.
  refine RingHom.ext fun z ↦ ?_
  refine TensorProduct.induction_on z ?_ ?_ ?_
  · simp
  · intro x y
    -- Proof comment: on pure tensors, the source comparison sends `x ⊗ₜ y` to
    -- `(1 ⊗ₜ y) ⊗ₜ x`, after which the packaged diagonal multiplication and `TensorProduct.lid`
    -- reduce the left side to the standard product map formula.
    calc
      ((diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K)).toRingHom).comp
          ((diagonal_tensor_source_algEquiv_to_baseChangeRight
            (k := k) (k' := k') (K := K)).symm.toRingHom) (x ⊗ₜ[k] y) =
        diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K)
          ((1 ⊗ₜ[k] y) ⊗ₜ[k'] x) := by
            change diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K)
                (((diagonal_tensor_source_algEquiv_to_baseChangeRight
                  (k := k) (k' := k') (K := K)).symm) (x ⊗ₜ[k] y)) =
              diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K)
                ((1 ⊗ₜ[k] y) ⊗ₜ[k'] x)
            exact congrArg
              (diagonal_tensor_source_to_lidAlgHom (k := k) (k' := k') (K := K))
              (diagonal_tensor_source_algEquiv_to_baseChangeRight_symm_tmul
                (k := k) (k' := k') (K := K) x y)
      _ =
        (productMap_rightAlgHom (k := k) (k' := k') (K := K)).toRingHom (x ⊗ₜ[k] y) := by
          simp [diagonal_tensor_source_to_lidAlgHom, productMap_rightAlgHom,
      Algebra.TensorProduct.productMap_apply_tmul, TensorProduct.lid_tmul]
          rw [Algebra.smul_def, mul_comm]
  · intro z₁ z₂ hz₁ hz₂
    -- Proof comment: both sides are additive, so combine the induction hypotheses termwise.
    simpa [RingHom.comp_apply] using congrArg₂ HAdd.hAdd hz₁ hz₂

/-- Helper for Lemma 10.43.9: a localization witness for the diagonal map
`k' ⊗[k] k' → k'` transports to a localization witness for
`K ⊗[k] k' → K` along the source comparison and the right tensor by `K`. -/
lemma productMap_right_isLocalization_of_diagonal
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K]
    (M0 : Submonoid (TensorProduct k k' k'))
    (hM0 : M0.IsLocalizationMap (TensorProduct.lmul' k)) :
    let e := diagonal_tensor_source_algEquiv_to_baseChangeRight (k := k) (k' := k') (K := K)
    let M : Submonoid (TensorProduct k K k') :=
      (Algebra.algebraMapSubmonoid (TensorProduct k' (TensorProduct k k' k') K) M0).comap
        e.symm.toRingHom
    M.IsLocalizationMap ((productMap_rightAlgHom (k := k) (k' := k') (K := K)).toRingHom) := by
  -- Route correction: the remaining source-faithful blocker is exactly the two-step transport of
  -- Lemma `10.43.8`: tensor the diagonal localization on the right by `K`, then transport the
  -- target through `TensorProduct.lid` and the source through
  -- `diagonal_tensor_source_algEquiv_to_baseChangeRight`.
  -- TODO: first rewrite `hM0` as an `IsLocalization` witness for the packaged diagonal algebra map
  -- via `diagonal_lmul_left_isLocalizationMap_toAlgebra`, tensor that localization on the right by
  -- `K` using `isLocalization_tensor_right_of_isLocalization` and
  -- `tensor_right_map_includeRight_comp_local`, transport the target along `TensorProduct.lid`,
  -- and finally transport the source along
  -- `diagonal_tensor_source_algEquiv_to_baseChangeRight` using
  -- `transported_diagonal_tensor_map_eq_productMap`.
  sorry

/-- Helper for Lemma 10.43.9: the right-tensored diagonal localization from Lemma `10.43.8`
transports to a localization presentation of `K` over `K ⊗[k] k'`. -/
lemma exists_submonoid_tensorProduct_right_isLocalization
    {K : Type*} [Field K] [Algebra k' K] [Algebra k K] [IsScalarTower k k' K] :
    ∃ M : Submonoid (TensorProduct k K k'),
      M.IsLocalizationMap
        (Algebra.TensorProduct.productMap
          (AlgHom.id k K) (IsScalarTower.toAlgHom k k' K)).toRingHom := by
  obtain ⟨M0, hM0⟩ := exists_submonoid_tensorProduct_self_isLocalization (k := k) (K := k')
  let e := diagonal_tensor_source_algEquiv_to_baseChangeRight (k := k) (k' := k') (K := K)
  let M : Submonoid (TensorProduct k K k') :=
    (Algebra.algebraMapSubmonoid (TensorProduct k' (TensorProduct k k' k') K) M0).comap
      e.symm.toRingHom
  -- Proof comment: once the transported localization theorem is packaged for a fixed witness,
  -- the existential Stacks statement is obtained by instantiating it with Lemma `10.43.8`.
  refine ⟨M, ?_⟩
  simpa [M, e, productMap_rightAlgHom] using
    (productMap_right_isLocalization_of_diagonal
      (k := k) (k' := k') (K := K) M0 hM0)

/-- Helper for Lemma 10.43.9: after rewriting `K ⊗[k] A` as
`(K ⊗[k] k') ⊗[k'] A`, the diagonal-localization theorem of Lemma `10.43.8` should descend
reducedness from the `k`-base change to the `k'`-base change. -/
lemma isReduced_tensorProduct_over_extension_of_isReduced_baseChange
    {K : Type*} [Field K] [Algebra k K] [Algebra k' K] [IsScalarTower k k' K]
    (hKA : IsReduced (TensorProduct k K A)) :
    IsReduced (TensorProduct k' K A) := by
  -- Proof comment: the intended route is the source proof verbatim: use Lemma `10.43.8` to
  -- present `K` as a localization of `K ⊗[k] k'`, tensor that localization on the right by `A`,
  -- and transport the resulting reduced localization back to `K ⊗[k'] A`.
  -- TODO: rewrite `K ⊗[k] A` as `((K ⊗[k] k') ⊗[k'] A)`, tensor the localization witness from
  -- `exists_submonoid_tensorProduct_right_isLocalization` on the right by `A`, and conclude with
  -- `isReduced_localizationPreserves`.
  sorry

/- Domain triage:
- `source-facing`: invariance of geometric reducedness under a separable algebraic change of the
  ground field.
- `core/canonical`: the owner abstraction is `Algebra.IsGeometricallyReduced`.
- `bridge/view`: Definition `10.43.1` provides the owner-level reformulation in terms of reduced
  tensor products, and Lemma `10.43.6` supplies the separable-algebraic reducedness input used in
  the proof.

Primitive data are the field-extension hypotheses and the ambient `k'`-algebra `A`; geometric
reducedness itself stays in the owner class rather than being repackaged by a local wrapper.
-/
/-- Lemma 10.43.9 (Tag 0C2Y): for a separable algebraic field extension `k' / k`, a `k'`-algebra
`A` is geometrically reduced over `k` if and only if it is geometrically reduced over `k'`. -/
@[stacks 0C2Y]
theorem isGeometricallyReduced_iff_of_isSeparable :
    IsGeometricallyReduced k A ↔ IsGeometricallyReduced k' A := by
  constructor
  · intro h
    rw [isGeometricallyReduced_iff_forall_isReduced_tensorProduct] at h
    rw [isGeometricallyReduced_iff_forall_isReduced_tensorProduct]
    intro K _ _
    letI : Algebra k K := RingHom.toAlgebra ((algebraMap k' K).comp (algebraMap k k'))
    letI : IsScalarTower k k' K := IsScalarTower.of_algebraMap_eq' rfl
    -- Proof comment: first use the `k`-geometric hypothesis to control `K ⊗[k] A`.
    exact
      isReduced_tensorProduct_over_extension_of_isReduced_baseChange
        (k := k) (k' := k') (h K)
  · intro h
    rw [isGeometricallyReduced_iff_forall_isReduced_tensorProduct] at h
    rw [isGeometricallyReduced_iff_forall_isReduced_tensorProduct]
    intro K _ _
    letI : Algebra k' (TensorProduct k K k') :=
      (Algebra.TensorProduct.includeRight : k' →ₐ[k] TensorProduct k K k').toAlgebra
    have hKk' : IsReduced (TensorProduct k K k') := by
      let e : TensorProduct k k' K ≃ₐ[k] TensorProduct k K k' :=
        Algebra.TensorProduct.comm k k' K
      letI : IsReduced (TensorProduct k k' K) :=
        Lemma_10_43_6 (k := k) (K := k') (S := K)
      -- Proof comment: Lemma `10.43.6` gives reducedness in the opposite tensor order, so commute.
      exact isReduced_of_injective e.symm.toRingHom e.symm.injective
    letI : IsReduced (TensorProduct k K k') := hKk'
    have hiter : IsReduced (TensorProduct k' (TensorProduct k K k') A) := by
      have hgeom : IsGeometricallyReduced k' A := by
        exact isGeometricallyReduced_iff_forall_isReduced_tensorProduct.mpr h
      letI : IsGeometricallyReduced k' A := hgeom
      -- Proof comment: now apply Lemma `10.43.5` over the intermediate base field `k'`.
      exact
        isReduced_tensorProduct_of_geometricallyReduced
          (k := k') (R := TensorProduct k K k') (S := A)
    let e : TensorProduct k' (TensorProduct k K k') A ≃+* TensorProduct k K A :=
      tensor_base_change_assoc_equiv (k := k) (k' := k') (K := K) (B := A)
    -- Proof comment: finally transport reducedness across the canonical tensor comparison.
    exact isReduced_of_injective e.symm.toMonoidWithZeroHom e.symm.injective

end

end Algebra
