import Mathlib.RingTheory.Spectrum.Prime.RingHom
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.Tactic.StacksAttribute

-- Declarations for this item will be appended below by the statement pipeline.

open MvPolynomial PrimeSpectrum
open scoped BigOperators

universe u

section

variable {R : Type u} [CommRing R]
variable {n : ℕ} (d : Fin n → ℕ)

/-- Helper for Lemma 15.21.4: the zero locus of a finite infimum of ideals is the union of the
corresponding zero loci. -/
lemma zeroLocus_iInf_eq_iUnion_of_finite {ι : Type*} [Finite ι] (I : ι → Ideal R) :
    zeroLocus ((⨅ i, I i : Ideal R) : Set R) = ⋃ i, zeroLocus (I i : Set R) := by
  classical
  let _ : Fintype ι := Fintype.ofFinite ι
  let s : Finset ι := Finset.univ
  have hs :
      zeroLocus ((s.inf I : Ideal R) : Set R) = ⋃ i ∈ s, zeroLocus (I i : Set R) := by
    -- Reduce the finite union statement to repeated applications of `zeroLocus_inf`.
    induction s using Finset.induction_on with
    | empty =>
        simp
    | @insert a s ha ih =>
        rw [Finset.inf_insert, zeroLocus_inf, ih]
        simp
  simpa [s, Finset.inf_eq_iInf] using hs

/-- Helper for Lemma 15.21.4: after evaluating at `β`, the remainder is generated by the linear
relations `X i - C (β i)`. -/
lemma sub_C_eval_mem_span_X_sub_C (β : Fin n → R) (f : MvPolynomial (Fin n) R) :
    f - C (eval β f) ∈
      Ideal.span (Set.range fun i : Fin n => (X i - C (β i) : MvPolynomial (Fin n) R)) := by
  let I : Ideal (MvPolynomial (Fin n) R) :=
    Ideal.span (Set.range fun i : Fin n => (X i - C (β i) : MvPolynomial (Fin n) R))
  -- Induct on the polynomial structure and record that each step preserves the span ideal.
  change f - C (eval β f) ∈ I
  induction f using MvPolynomial.induction_on with
  | C r =>
      simp [I]
  | add p q hp hq =>
      -- The additive case splits the remainder into the sum of the two smaller remainders.
      simpa [I, sub_eq_add_neg, map_add, C_add, add_assoc, add_left_comm, add_comm] using
        I.add_mem hp hq
  | mul_X p i hp =>
      -- Factor the `mul_X` remainder into the chosen generator and the inductive remainder.
      have hgen : (X i - C (β i) : MvPolynomial (Fin n) R) ∈ I := by
        exact Ideal.subset_span ⟨i, rfl⟩
      have hleft : p * (X i - C (β i) : MvPolynomial (Fin n) R) ∈ I := by
        exact Ideal.mul_mem_left I _ hgen
      have hright : (p - C (eval β p)) * C (β i) ∈ I := by
        exact Ideal.mul_mem_right (C (β i)) I hp
      have hsplit :
          p * X i - C (eval β (p * X i)) =
            p * (X i - C (β i)) + (p - C (eval β p)) * C (β i) := by
        simp [sub_eq_add_neg, map_mul, mul_add, add_mul, add_assoc, add_left_comm]
      rw [hsplit]
      exact I.add_mem hleft hright

/-- Helper for Lemma 15.21.4: a prime over `J` containing the linear relations for `β` contracts
to a prime containing the evaluation image of `J`. -/
lemma eval_image_le_of_prime_over_with_linear_relations
    (J : Ideal (MvPolynomial (Fin n) R)) (β : Fin n → R) (p : PrimeSpectrum R)
    (Q : PrimeSpectrum (MvPolynomial (Fin n) R))
    (hJQ : J ≤ Q.asIdeal)
    (hcomap : Ideal.comap (C : R →+* MvPolynomial (Fin n) R) Q.asIdeal = p.asIdeal)
    (hlin : ∀ i : Fin n, (X i - C (β i) : MvPolynomial (Fin n) R) ∈ Q.asIdeal) :
    Ideal.map (eval β) J ≤ p.asIdeal := by
  -- Rewrite the target containment as a contraction statement to avoid unpacking `Ideal.map`.
  rw [Ideal.map_le_iff_le_comap]
  intro f hf
  have hfQ : f ∈ Q.asIdeal := hJQ hf
  have hremQ : f - C (eval β f) ∈ Q.asIdeal := by
    have hspan :
        Ideal.span (Set.range fun i : Fin n => (X i - C (β i) : MvPolynomial (Fin n) R)) ≤
          Q.asIdeal := by
      refine Ideal.span_le.2 ?_
      rintro _ ⟨i, rfl⟩
      exact hlin i
    exact hspan (sub_C_eval_mem_span_X_sub_C β f)
  have hconstQ : C (eval β f) ∈ Q.asIdeal := by
    have := Q.asIdeal.sub_mem hfQ hremQ
    simpa using this
  -- Contract the constant term back along `C`.
  rw [← hcomap]
  simpa [Ideal.mem_comap] using hconstQ

/-- Helper for Lemma 15.21.4: if the evaluation image of `J` is contained in `p`, then the kernel
of evaluation modulo `p` is a prime over `J` lying above `p`. -/
lemma prime_over_of_eval_image_le
    (J : Ideal (MvPolynomial (Fin n) R)) (β : Fin n → R) (p : PrimeSpectrum R)
    (hmap : Ideal.map (eval β) J ≤ p.asIdeal) :
    ∃ Q : PrimeSpectrum (MvPolynomial (Fin n) R),
      J ≤ Q.asIdeal ∧
        Ideal.comap (C : R →+* MvPolynomial (Fin n) R) Q.asIdeal = p.asIdeal := by
  let g : MvPolynomial (Fin n) R →+* R ⧸ p.asIdeal :=
    (Ideal.Quotient.mk p.asIdeal).comp (eval β)
  let Q : PrimeSpectrum (MvPolynomial (Fin n) R) := ⟨RingHom.ker g, RingHom.ker_isPrime g⟩
  refine ⟨Q, ?_, ?_⟩
  · -- The kernel contains `J` exactly because the evaluation image lands in `p`.
    rw [Ideal.map_le_iff_le_comap] at hmap
    intro f hf
    have hf' : eval β f ∈ p.asIdeal := by
      exact hmap hf
    change f ∈ RingHom.ker g
    rw [RingHom.mem_ker]
    exact Ideal.Quotient.eq_zero_iff_mem.2 hf'
  · -- On constants, `g` agrees with the quotient map `R → R ⧸ p`.
    change Ideal.comap (C : R →+* MvPolynomial (Fin n) R) (RingHom.ker g) = p.asIdeal
    rw [RingHom.comap_ker]
    have hgC : g.comp (C : R →+* MvPolynomial (Fin n) R) = Ideal.Quotient.mk p.asIdeal := by
      ext r
      simp [g]
    rw [hgC, Ideal.mk_ker]

/- Domain sampling for this item:
* primary domain: affine prime-spectrum images for quotients and finite products of commutative
  rings;
* sampled core owners: `PrimeSpectrum.range_comap_of_surjective`, `MvPolynomial.eval`,
  `Pi.ker_ringHom`, `PrimeSpectrum.iUnion_range_comap_comp_evalRingHom`, and `zeroLocus_inf`;
* layer: this lemma is a `source-facing` split-polynomial specialization of those owner
  constructions, not a new owner abstraction. -/
-- Proof sketch: form the product of the evaluation maps indexed by
-- `k : ∀ i : Fin n, Fin (d i)`. The split-polynomial hypothesis ensures that the quotient map to
-- this finite product is surjective, so `range_comap_of_surjective` identifies the spectrum image
-- with the zero locus of the kernel. Then compute that kernel with `Pi.ker_ringHom`, and rewrite
-- the finite-product spectrum image through `iUnion_range_comap_comp_evalRingHom` and
-- `zeroLocus_inf`.
/-- Lemma 15.21.4: if `J ⊆ R[T₁, …, Tₙ]` contains, for each variable `Tᵢ`, the split polynomial
`∏ⱼ (Tᵢ - αᵢⱼ)`, then for `S = R[T₁, …, Tₙ] / J` the image of `Spec(S) → Spec(R)` is the zero
locus `V(⋂ₖ Jₖ)`, where `Jₖ` is the image of `J` under evaluation at the tuple
`Tᵢ ↦ αᵢ,ₖᵢ`. -/
@[stacks 0532]
theorem range_comap_polynomial_quotient_eq_zeroLocus_iInf_evaluationImage
    (J : Ideal (MvPolynomial (Fin n) R)) (α : ∀ i : Fin n, Fin (d i) → R)
    (hJ : ∀ i : Fin n, ∏ j : Fin (d i), (X i - C (α i j)) ∈ J) :
    Set.range (comap (algebraMap R (MvPolynomial (Fin n) R ⧸ J))) =
      zeroLocus
        (⨅ k : ∀ i : Fin n, Fin (d i),
          Ideal.map (eval fun i ↦ α i (k i)) J) := by
  classical
  let A := MvPolynomial (Fin n) R
  let Jk : (∀ i : Fin n, Fin (d i)) → Ideal R :=
    fun k ↦ Ideal.map (eval fun i ↦ α i (k i)) J
  have hquot :
      Set.range (comap (algebraMap R (A ⧸ J))) =
        comap (C : R →+* A) '' zeroLocus (J : Set A) := by
    let q : A →+* A ⧸ J := Ideal.Quotient.mk J
    have hq : algebraMap R (A ⧸ J) = q.comp (C : R →+* A) := by
      ext r
      rfl
    have hrange :
        Set.range (comap q) = zeroLocus (J : Set A) := by
      simpa [q, Ideal.mk_ker] using
        (range_comap_of_surjective (R := A) (S := A ⧸ J) q Ideal.Quotient.mk_surjective)
    -- Rewrite the image of the composite map as the image of the quotient-spectrum image.
    rw [hq, PrimeSpectrum.comap_comp]
    change Set.range ((comap (C : R →+* A)).comp (comap q)) =
      comap (C : R →+* A) '' zeroLocus (J : Set A)
    rw [← hrange]
    ext p
    constructor
    · rintro ⟨Q, rfl⟩
      exact ⟨comap q Q, ⟨Q, rfl⟩, rfl⟩
    · rintro ⟨Q, ⟨Q', rfl⟩, rfl⟩
      exact ⟨Q', rfl⟩
  have hzero :
      zeroLocus ((⨅ k : ∀ i : Fin n, Fin (d i), Jk k : Ideal R) : Set R) =
        ⋃ k : ∀ i : Fin n, Fin (d i), zeroLocus (Jk k : Set R) := by
    simpa [Jk] using zeroLocus_iInf_eq_iUnion_of_finite (R := R) Jk
  have hzero' :
      zeroLocus (⨅ k : ∀ i : Fin n, Fin (d i), Ideal.map (eval fun i ↦ α i (k i)) J) =
        ⋃ k : ∀ i : Fin n, Fin (d i),
          zeroLocus (Ideal.map (eval fun i ↦ α i (k i)) J : Set R) := by
    simpa [Jk] using hzero
  rw [hquot]
  rw [hzero']
  ext p
  constructor
  · rintro ⟨Q, hQ, hpQ⟩
    have hJQ : J ≤ Q.asIdeal := (mem_zeroLocus Q (J : Set A)).1 hQ
    have hcomap : Ideal.comap (C : R →+* A) Q.asIdeal = p.asIdeal := by
      simpa [PrimeSpectrum.comap_asIdeal] using congrArg PrimeSpectrum.asIdeal hpQ
    have hchoose :
        ∀ i : Fin n, ∃ ki : Fin (d i), (X i - C (α i ki) : A) ∈ Q.asIdeal := by
      intro i
      have hprod :
          ∏ j ∈ (Finset.univ : Finset (Fin (d i))), (X i - C (α i j) : A) ∈ Q.asIdeal := by
        simpa using hJQ (hJ i)
      obtain ⟨ki, -, hki⟩ :=
        (Ideal.IsPrime.prod_mem_iff
          (s := (Finset.univ : Finset (Fin (d i))))
          (x := fun j : Fin (d i) => (X i - C (α i j) : A))
          (p := Q.asIdeal)).1 hprod
      exact ⟨ki, hki⟩
    choose k hk using hchoose
    -- The chosen tuple forces the whole evaluation image of `J` into the contracted prime.
    have hmap :
        Jk k ≤ p.asIdeal :=
      eval_image_le_of_prime_over_with_linear_relations J
        (fun i ↦ α i (k i)) p Q hJQ hcomap hk
    exact Set.mem_iUnion.mpr ⟨k, (mem_zeroLocus p (Jk k : Set R)).2 hmap⟩
  · rintro hp
    rcases Set.mem_iUnion.mp hp with ⟨k, hk⟩
    have hmap : Jk k ≤ p.asIdeal := (mem_zeroLocus p (Jk k : Set R)).1 hk
    obtain ⟨Q, hJQ, hcomap⟩ :=
      prime_over_of_eval_image_le J (fun i ↦ α i (k i)) p hmap
    have hQ : Q ∈ zeroLocus (J : Set A) := (mem_zeroLocus Q (J : Set A)).2 hJQ
    exact ⟨Q, hQ, PrimeSpectrum.ext hcomap⟩

end
