import Mathlib.Data.List.TFAE
import stacks_proof.stacks_project.Chap10.Lemma_10_21_5
import stacks_proof.stacks_project.Chap10.Lemma_10_25_1
import stacks_proof.stacks_project.Chap10.Lemma_10_26_5
import stacks_proof.stacks_project.Chap10.Lemma_10_39_18
import stacks_proof.stacks_project.Chap15.Definition_15_105_1
import stacks_proof.stacks_project.Chap15.Definition_15_105_3
import Mathlib.Tactic.StacksAttribute

-- Declarations for this item will be appended below by the statement pipeline.

universe u

section

open CategoryTheory PrimeSpectrum

variable (A : Type u) [CommRing A]

/- Domain-style sampling:
- primary domain: commutative algebra of weak dimension, absolute flatness, zero-dimensional
  reduced rings, and prime localizations;
- sampled owner declarations:
  `HasWeakDimensionLE`,
  `ModuleCat.hasTorDimensionLE_zero_iff_flat`,
  `IsAbsolutelyFlatRing`,
  `Ring.KrullDimLE.of_isLocalization`,
  `Ring.KrullDimLE.isField_of_isReduced`;
- best owner abstraction: the source-facing clause `(1)` should use the chapter owner
  `HasWeakDimensionLE A 0`, with the module-level zero-step bridge supplied canonically by
  `ModuleCat.hasTorDimensionLE_zero_iff_flat`; clause `(2)` should use the project owner
  `IsAbsolutelyFlatRing`, and clauses `(3)` and `(4)` should use the canonical mathlib owners
  `Ring.KrullDimLE 0` and `Localization.AtPrime`;
- primitive vs. derived:
  primitive data is just the ring `A` together with these owner predicates on `A` and its prime
  localizations;
  the only source-facing declaration needed here is the four-way `TFAE`, so no extra wrapper
  theorem is warranted.

Source/core/bridge triage:
- `source-facing`: the four-way equivalence matching the Stacks clause list;
- `core/canonical`: `HasWeakDimensionLE`, `IsAbsolutelyFlatRing`, `Ring.KrullDimLE 0`, and
  `Localization.AtPrime`;
- `bridge/view`: the `TFAE` theorem itself, which compares the source clauses directly without
  introducing any extra packaged interface.
-/

-- Proof sketch: `(1) ↔ (2)` follows by unpacking weak dimension `≤ 0` and using that tor
-- dimension `≤ 0` is flatness for every module. For `(2) → (3)`, absolute flatness makes every
-- finitely generated ideal pure, hence idempotent-generated, so basic opens are clopen; this
-- forces every prime ideal to be maximal, and nilpotents vanish. For `(3) → (4)`, transport
-- `Ring.KrullDimLE 0 A` to each `Localization.AtPrime p.asIdeal` via
-- `Ring.KrullDimLE.of_isLocalization`, then combine with reducedness and
-- `Ring.KrullDimLE.isField_of_isReduced`. For `(4) → (2)`, flatness is local at prime
-- localizations, and modules over fields are flat.
/-- Helper for Lemma 15.105.5: if the quotient by a principal ideal is flat, then the generator
admits a von Neumann regular factorization. -/
lemma exists_factor_of_flat_quotient_span_singleton
    (a : A) (hflat : Module.Flat A (A ⧸ Ideal.span ({a} : Set A))) :
    ∃ b : A, a = a ^ 2 * b := by
  let I : Ideal A := Ideal.span ({a} : Set A)
  have hfg : I.FG := by
    -- The principal ideal `(a)` is finitely generated by its defining singleton.
    simpa [I] using
      (Submodule.fg_span_singleton a : (Ideal.span ({a} : Set A)).FG)
  have hI_pure : I.Pure := by
    -- Purity is exactly flatness of the quotient by the ideal.
    change Module.Flat A (A ⧸ I)
    simpa [I] using hflat
  have hI_idempotent : IsIdempotentElem I := Ideal.isIdempotentElem_of_pure I
  obtain ⟨e, he, hIeq⟩ := (Ideal.isIdempotentElem_iff_of_fg I hfg).mp hI_idempotent
  have ha_span_e : a ∈ Ideal.span ({e} : Set A) := by
    -- Rewriting `(a) = (e)` moves `a` into the principal ideal generated by the idempotent.
    simpa [I, hIeq] using (show a ∈ I by exact Ideal.subset_span (by simp))
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp ha_span_e
  have he_span_a : e ∈ Ideal.span ({a} : Set A) := by
    -- The idempotent generator belongs to its own principal ideal, hence to `(a)`.
    simpa [I, hIeq] using Ideal.mem_span_singleton_self e
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp he_span_a
  have ha_mul_e : a = a * e := by
    -- Writing `a = c e` and using `e^2 = e` shows that multiplication by `e` fixes `a`.
    calc
      a = c * e := hc.symm
      _ = c * (e * e) := by rw [he.eq]
      _ = (c * e) * e := by rw [mul_assoc]
      _ = a * e := by rw [hc.symm]
  refine ⟨b, ?_⟩
  -- Since `e` itself lies in `(a)`, the fixed-point relation upgrades to `a = a^2 b`.
  calc
    a = a * e := ha_mul_e
    _ = a * (b * a) := by rw [hb]
    _ = a * a * b := by ac_rfl
    _ = a ^ 2 * b := by rw [pow_two]

/-- Helper for Lemma 15.105.5: a nilpotent element with a von Neumann regular factorization is
zero. -/
lemma eq_zero_of_isNilpotent_of_exists_square_factor
    (a : A) (ha : IsNilpotent a) (hfactor : ∃ b : A, a = a ^ 2 * b) :
    a = 0 := by
  by_cases hsub : Subsingleton A
  · -- In the zero ring every element is already zero.
    exact Subsingleton.elim _ _
  · letI : Nontrivial A := not_subsingleton_iff_nontrivial.mp hsub
    obtain ⟨b, hb⟩ := hfactor
    have hstep (n : ℕ) : a ^ (n + 1) = a ^ (n + 2) * b := by
      -- One copy of `a` can always be traded for the extra factor `a * b`.
      calc
        a ^ (n + 1) = a ^ n * a := by rw [pow_succ]
        _ = a ^ n * (a ^ 2 * b) := by
          exact congrArg (fun x ↦ a ^ n * x) hb
        _ = a ^ (n + 2) * b := by
          rw [pow_add, pow_two]
          ac_rfl
    have hvanish : ∀ n : ℕ, a ^ (n + 1) = 0 → a = 0 := by
      intro n
      induction n with
      | zero =>
          intro hn
          simpa using hn
      | succ n ihn =>
          intro hn
          have hprev : a ^ (n + 1) = 0 := by
            calc
              a ^ (n + 1) = a ^ (n + 2) * b := hstep n
              _ = 0 := by rw [hn, zero_mul]
          exact ihn hprev
    obtain ⟨n, hn⟩ := ha
    by_cases hn_zero : n = 0
    · exfalso
      rw [hn_zero, pow_zero] at hn
      exact one_ne_zero hn
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn_zero
      exact hvanish m (by simpa using hn)

/-- Helper for Lemma 15.105.5: in an absolutely flat ring, every basic open subset of `Spec(A)`
is closed. -/
lemma basicOpen_isClosed_of_isAbsolutelyFlatRing [IsAbsolutelyFlatRing A]
    (a : A) : IsClosed ((basicOpen a : Set (PrimeSpectrum A))) := by
  let I : Ideal A := Ideal.span ({a} : Set A)
  have hfg : I.FG := by
    -- The principal ideal `(a)` is finitely generated.
    simpa [I] using
      (Submodule.fg_span_singleton a : (Ideal.span ({a} : Set A)).FG)
  have hI_pure : I.Pure := by
    -- Over an absolutely flat ring, every quotient is flat, hence every ideal is pure.
    change Module.Flat A (A ⧸ I)
    infer_instance
  have hI_idempotent : IsIdempotentElem I := Ideal.isIdempotentElem_of_pure I
  obtain ⟨e, he, hIeq⟩ := (Ideal.isIdempotentElem_iff_of_fg I hfg).mp hI_idempotent
  have hzero :
      zeroLocus ({a} : Set A) = basicOpen (1 - e) := by
    -- The zero locus of `(a)` becomes a basic open cut out by the complementary idempotent.
    simpa [I] using
      zeroLocus_eq_basicOpen_one_sub_of_idempotent_generator (I := I) he hIeq
  have hbasic :
      (basicOpen a : Set (PrimeSpectrum A)) = (basicOpen (1 - e) : Set (PrimeSpectrum A))ᶜ := by
    -- Rewriting `D(a)` as the complement of `V(a)` turns the desired closedness into a basic-open
    -- complement.
    rw [basicOpen_eq_zeroLocus_compl, hzero]
  rw [hbasic]
  exact isOpen_basicOpen.isClosed_compl

/-- Helper for Lemma 15.105.5: an absolutely flat ring has Krull dimension at most `0`. -/
lemma krullDimLEZero_of_isAbsolutelyFlatRing [IsAbsolutelyFlatRing A] :
    Ring.KrullDimLE 0 A := by
  have hbasic :
      ∀ a : A, IsClosed ((basicOpen a : Set (PrimeSpectrum A))) := by
    -- The previous lemma supplies the topological clause needed for the profinite-spectrum TFAE.
    intro a
    exact basicOpen_isClosed_of_isAbsolutelyFlatRing (A := A) a
  have hclosed :
      ∀ p : PrimeSpectrum A, IsClosed ({p} : Set (PrimeSpectrum A)) :=
    ((primeSpectrum_profinite_tfae (R := A)).out 7 5).mp hbasic
  -- Closed points in `Spec(A)` are exactly maximal ideals, which is the dimension-zero criterion.
  refine Ring.KrullDimLE.mk₀ fun I hI ↦ ?_
  exact
    (PrimeSpectrum.isClosed_singleton_iff_isMaximal ⟨I, hI⟩).mp
      (hclosed ⟨I, hI⟩)

/-- Helper for Lemma 15.105.5: a reduced zero-dimensional ring has field localizations at all
prime ideals. -/
lemma isField_atPrime_of_isReduced_of_krullDimLEZero
    (hred : IsReduced A) (hdim : Ring.KrullDimLE 0 A)
    (p : PrimeSpectrum A) :
    IsField (Localization.AtPrime p.asIdeal) := by
  letI : IsReduced A := hred
  letI : Ring.KrullDimLE 0 A := hdim
  have hpmin : p.asIdeal ∈ minimalPrimes A := by
    -- In Krull dimension zero, every prime is minimal over `(0)`.
    simpa [minimalPrimes] using
      (Ring.KrullDimLE.mem_minimalPrimes_iff_le_of_isPrime
        (I := p.asIdeal) (J := (⊥ : Ideal A))).2 bot_le
  let pmin : minimalPrimes A := ⟨p.asIdeal, hpmin⟩
  simpa using isField_localizationAtPrime_of_minimalPrime pmin

/-- Lemma 15.105.5: for a commutative ring `A`, the following are equivalent: `A` has weak
dimension at most `0`; `A` is absolutely flat; `A` is reduced and every prime ideal is maximal,
formalized as `IsReduced A ∧ Ring.KrullDimLE 0 A`; and every canonical prime localization
`Localization.AtPrime p.asIdeal` is a field. -/
@[stacks 092F]
theorem weakDimensionLEZero_tfae :
    List.TFAE
      [ HasWeakDimensionLE A 0
      , IsAbsolutelyFlatRing A
      , IsReduced A ∧ Ring.KrullDimLE 0 A
      , ∀ p : PrimeSpectrum A, IsField (Localization.AtPrime p.asIdeal)
      ] := by
  -- The source-proof route is the cycle
  -- `weak dimension ≤ 0 → absolutely flat → reduced and zero-dimensional → local fields →
  -- absolutely flat`.
  tfae_have 1 → 2 := by
    intro hwd
    refine ⟨fun a ↦ ?_⟩
    -- Apply the weak-dimension owner to the principal quotient and convert tor-dimension `0` to
    -- flatness.
    have htor :
        ModuleHasTorDimensionLE (ModuleCat.of A (A ⧸ Ideal.span ({a} : Set A))) 0 :=
      hwd.hasTorDimensionLE (ModuleCat.of A (A ⧸ Ideal.span ({a} : Set A)))
    have hflat : Module.Flat A (A ⧸ Ideal.span ({a} : Set A)) :=
      (ModuleCat.hasTorDimensionLE_zero_iff_flat
        (R := A) (M := ModuleCat.of A (A ⧸ Ideal.span ({a} : Set A)))).mp htor
    exact exists_factor_of_flat_quotient_span_singleton (A := A) a hflat
  tfae_have 2 → 1 := by
    intro habs
    letI : IsAbsolutelyFlatRing A := habs
    refine ⟨fun M ↦ ?_⟩
    -- Over an absolutely flat ring every module is flat, hence has tor dimension at most `0`.
    exact (ModuleCat.hasTorDimensionLE_zero_iff_flat (R := A) (M := M)).mpr inferInstance
  tfae_have 2 → 3 := by
    intro habs
    letI : IsAbsolutelyFlatRing A := habs
    refine ⟨?_, krullDimLEZero_of_isAbsolutelyFlatRing (A := A)⟩
    -- Absolute-flat factorizations kill nilpotents, so the ring is reduced.
    refine ⟨fun a ha ↦ ?_⟩
    exact eq_zero_of_isNilpotent_of_exists_square_factor (A := A) a ha
      ((inferInstance : IsAbsolutelyFlatRing A).exists_factor a)
  tfae_have 3 → 4 := by
    intro hA
    -- Reducedness plus dimension zero turns every prime localization into the localization at a
    -- minimal prime.
    exact fun p ↦ isField_atPrime_of_isReduced_of_krullDimLEZero (A := A) hA.1 hA.2 p
  tfae_have 4 → 2 := by
    intro hfield
    refine ⟨fun a ↦ ?_⟩
    -- Flatness of the principal quotient is local on prime spectra, and every localized quotient
    -- is a module over a field.
    have hlocal :
        ∀ p : PrimeSpectrum A,
          Module.Flat (Localization.AtPrime p.asIdeal)
            (LocalizedModule.AtPrime p.asIdeal (A ⧸ Ideal.span ({a} : Set A))) := by
      intro p
      letI : Field (Localization.AtPrime p.asIdeal) := (hfield p).toField
      infer_instance
    have hflat : Module.Flat A (A ⧸ Ideal.span ({a} : Set A)) :=
      (flat_iff_flat_localizedModule_atPrime
        (R := A) (M := A ⧸ Ideal.span ({a} : Set A))).2 hlocal
    exact exists_factor_of_flat_quotient_span_singleton (A := A) a hflat
  tfae_finish

/-- An absolutely flat commutative ring has weak dimension at most `0`. -/
theorem hasWeakDimensionLEZero_of_isAbsolutelyFlatRing [IsAbsolutelyFlatRing A] :
    HasWeakDimensionLE A 0 := by
  have h : IsAbsolutelyFlatRing A ↔ HasWeakDimensionLE A 0 :=
    (weakDimensionLEZero_tfae A).out 1 0
  exact h.mp inferInstance

/-- A commutative ring of weak dimension at most `0` is absolutely flat. -/
theorem isAbsolutelyFlatRing_of_hasWeakDimensionLEZero [HasWeakDimensionLE A 0] :
    IsAbsolutelyFlatRing A := by
  have h : HasWeakDimensionLE A 0 ↔ IsAbsolutelyFlatRing A :=
    (weakDimensionLEZero_tfae A).out 0 1
  exact h.mp inferInstance

/-- An absolutely flat commutative ring is reduced. -/
theorem isReduced_of_isAbsolutelyFlatRing [IsAbsolutelyFlatRing A] :
    IsReduced A := by
  have h : IsAbsolutelyFlatRing A ↔ IsReduced A ∧ Ring.KrullDimLE 0 A :=
    (weakDimensionLEZero_tfae A).out 1 2
  exact (h.mp inferInstance).1

end
