import Mathlib
import StacksProject_2024.Chap10.Lemma_10_55_6
import StacksProject_2024.Chap13.Definition_13_37_1
import StacksProject_2024.Chap13.Remark_13_4_4
import StacksProject_2024.Chap13.Lemma_13_35_7
import StacksProject_2024.Chap13.Lemma_13_37_2
import StacksProject_2024.Chap13.Proposition_13_37_6
import StacksProject_2024.Chap15.Definition_15_75_1
import StacksProject_2024.Chap15.Lemma_15_75_4
import StacksProject_2024.Chap15.RingSingle

noncomputable section

open CategoryTheory
open CategoryTheory.Limits
open CategoryTheory.ObjectProperty
open CategoryTheory.Pretriangulated
open Opposite
open scoped CategoryTheory.ObjectProperty.GeneratedNotation

universe u v

attribute [local instance] HasDerivedCategory.standard

namespace CategoryTheory

section

variable {R : Type u} [Ring R]

local notation "DMod" => DerivedCategory (ModuleCat R)
local notation "H" => DerivedCategory.homologyFunctor (ModuleCat R)
local notation "PerfectObj" => (DerivedCategory.IsPerfect : ObjectProperty DMod)
local notation "single₀" => DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)

/- Domain-style sampling for Proposition 15.79.3:
- primary domain: perfect and compact objects in the derived category `D(R)`;
- sampled owner declarations:
  `DerivedCategory.IsPerfect`,
  `IsCompactObject`,
  `ObjectProperty.IsStableUnderRetracts`,
  `preadditiveCoyoneda_hocolim_comparison_is_iso`;
- best owner abstractions:
  the proposition is `source-facing`, but its two predicates are already canonically owned by
  `DerivedCategory.IsPerfect` and `IsCompactObject`;
  the file should therefore keep only the source-facing equivalence for a fixed object and avoid
  importing proof-route bridge files as if they were part of the owner surface;
- primitive vs. derived:
  the only primitive datum here is the object `K : D(R)`;
  closure of compact objects under retracts and the represented-Hom hocolim comparison map are
  derived bridge API from neighboring owner files, not primitive data of this proposition file;
- source/core/bridge triage:
  `source-facing`: the equivalence for a fixed object `K`;
  `core/canonical`: `K.IsPerfect` and `IsCompactObject K`;
  `bridge/view`: the generator description of perfect objects, compact-object retract stability,
    and the canonical represented-Hom hocolim comparison, all supplied upstream rather than
    re-owned here.
-/

-- Proof sketch: for `K.IsPerfect → IsCompactObject K`, unpack perfectness into a bounded
-- finite-projective representative and then use the Chapter 13 interval-stage theorem together
-- with compactness of the degree-zero finite-projective pieces. For the converse, first prove
-- that `R[0]` is a compact weak generator by identifying `Hom_D(R[0], X)` with `H^0(X)`;
-- compact generation then shows every compact object is generated by `R[0]`, and perfect objects
-- form the saturated triangulated property generated by that perfect ring object.
/-- Helper for Proposition 15.79.3: maps from `R[0]` into an object supported strictly below
degree `0` vanish because `R` is projective. -/
lemma ring_single_hom_eq_zero_of_isLE_negOne_local
    {Y : DMod} (hY : Y.IsLE (-1))
    (φ : (ringSingle : DMod) ⟶ Y) :
    φ = 0 := by
  -- Proof comment: replace the target by a strictly upper-bounded complex representative and use
  -- the derived-category vanishing theorem for maps from a projective single complex.
  rcases hY with ⟨L, eL, hL⟩
  apply (cancel_mono eL.hom).1
  simpa using
    (DerivedCategory.from_singleFunctor_obj_eq_zero_of_projective
      (P := ModuleCat.of R R) (L := L) (i := 0) (φ := φ ≫ eL.hom) (n := -1)
      (hn := by omega))

/-- Helper for Proposition 15.79.3: shifting `R[0]` by `k` identifies it with the degree-`-k`
single object on the free rank-one module. -/
noncomputable def shifted_ring_single_iso_single_local
    (k : ℤ) :
    ((ringSingle : DMod)⟦k⟧) ≅
      (DerivedCategory.singleFunctor (ModuleCat R) (-k)).obj (ModuleCat.of R R) :=
  ((DerivedCategory.singleFunctors (ModuleCat R)).shiftIso k (-k) 0 (by omega)).app
    (ModuleCat.of R R)

/-- Helper for Proposition 15.79.3: maps from `R[0]` into a first shift of an object supported
strictly below degree `0` vanish after transporting the source across the canonical shift
equivalence. -/
-- TODO: restore the transport from `Hom(R[0], Y⟦1⟧)` to `Hom(R[0][-1], Y)` cleanly once the
-- surrounding truncation bridge is rebuilt; this vanishing lemma is one input to the middle
-- truncation NatIso.
lemma ring_single_hom_shift_eq_zero_of_isLE_negOne_local
    {Y : DMod} (hY : Y.IsLE (-1))
    (φ : (ringSingle : DMod) ⟶ Y⟦(1 : ℤ)⟧) :
    φ = 0 := by
  sorry

/-- Helper for Proposition 15.79.3: an object concentrated in degree `n` is canonically the
single object on its degree-`n` homology. -/
noncomputable def singleFunctor_iso_of_isGE_of_isLE_local
    (X : DMod) (n : ℤ) [X.IsGE n] [X.IsLE n] :
    X ≅ (DerivedCategory.singleFunctor (ModuleCat R) n).obj ((H n).obj X) := by
  classical
  -- Proof comment: choose the standard single-degree model and rewrite its coefficient object
  -- back to the actual degree-`n` homology of `X`.
  let hX := DerivedCategory.exists_iso_singleFunctor_obj_of_isGE_of_isLE X n
  let Y := Classical.choose hX
  let e : X ≅ (DerivedCategory.singleFunctor (ModuleCat R) n).obj Y :=
    Classical.choice (Classical.choose_spec hX)
  let eH : (H n).obj X ≅ Y :=
    (H n).mapIso e ≪≫ (DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).app Y
  exact e ≪≫ (DerivedCategory.singleFunctor (ModuleCat R) n).mapIso eH.symm

/-- Helper for Proposition 15.79.3: after identifying a concentrated object with its single-degree
model, applying homology in that degree recovers the canonical single-functor comparison. -/
lemma singleFunctor_iso_of_isGE_of_isLE_local_homology
    (X : DMod) (n : ℤ) [X.IsGE n] [X.IsLE n] :
    (H n).map (singleFunctor_iso_of_isGE_of_isLE_local (R := R) X n).hom =
      ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).app
        ((H n).obj X)).inv := by
  classical
  let hX := DerivedCategory.exists_iso_singleFunctor_obj_of_isGE_of_isLE X n
  let Y := Classical.choose hX
  let e : X ≅ (DerivedCategory.singleFunctor (ModuleCat R) n).obj Y :=
    Classical.choice (Classical.choose_spec hX)
  let eH : (H n).obj X ≅ Y :=
    (H n).mapIso e ≪≫ (DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).app Y
  let α := DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n
  have hnat' :
      (H n).map ((DerivedCategory.singleFunctor (ModuleCat R) n).map eH.inv) ≫
          (α.app ((H n).obj X)).hom =
        (α.app Y).hom ≫ eH.inv := by
    -- Proof comment: naturality of the owner comparison converts the mapped single-functor arrow
    -- into the corresponding arrow on homology.
    refine (cancel_epi (α.app Y).inv).1 ?_
    simpa [Category.assoc] using
      (NatIso.naturality_1 α eH.inv).trans
        ((Iso.inv_hom_id_assoc (α.app Y) eH.inv).symm)
  have hcomp :
      (H n).map ((DerivedCategory.singleFunctor (ModuleCat R) n).map eH.inv) =
        (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv := by
    have hcomp' :
        (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv ≫
            (α.app ((H n).obj X)).hom =
          (α.app Y).hom ≫ eH.inv := by
      simpa [Category.assoc] using
        congrArg (fun t ↦ (α.app Y).hom ≫ eH.inv ≫ t)
          (Iso.inv_hom_id (α.app ((H n).obj X)))
    exact (cancel_mono (α.app ((H n).obj X)).hom).1 <| by
      simpa [Category.assoc] using hnat'.trans hcomp'.symm
  dsimp [singleFunctor_iso_of_isGE_of_isLE_local]
  have hmap :
      (H n).map e.hom ≫
          (H n).map ((DerivedCategory.singleFunctor (ModuleCat R) n).map eH.inv) =
        (H n).map e.hom ≫ (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv := by
    rw [hcomp]
    simp
  have hfinal :
      (H n).map e.hom ≫ (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv =
        ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).app
          ((H n).obj X)).inv := by
    -- Proof comment: the chosen concentrated model carries the same degree-`n` homology as `X`,
    -- so the auxiliary coefficient isomorphism cancels.
    simpa [eH, Category.assoc] using
      (Iso.hom_inv_id_assoc eH
        ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).app
          ((H n).obj X)).inv)
  have hmain :
      (H n).map (singleFunctor_iso_of_isGE_of_isLE_local (R := R) X n).hom =
        (H n).map e.hom ≫ (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv := by
    have hmain₁ :
        (H n).map (singleFunctor_iso_of_isGE_of_isLE_local (R := R) X n).hom =
          (H n).map e.hom ≫
              (H n).map
                ((DerivedCategory.singleFunctor (ModuleCat R) n).map
                  ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).inv.app
                    Y)) ≫
            (H n).map
              ((DerivedCategory.singleFunctor (ModuleCat R) n).map ((H n).map e.inv)) := by
      simpa [singleFunctor_iso_of_isGE_of_isLE_local, e, Y, Functor.map_comp]
    have hmain₂ :
        (H n).map e.hom ≫
              (H n).map
                ((DerivedCategory.singleFunctor (ModuleCat R) n).map
                  ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) n).inv.app
                    Y)) ≫
            (H n).map
              ((DerivedCategory.singleFunctor (ModuleCat R) n).map ((H n).map e.inv)) =
          (H n).map e.hom ≫ (α.app Y).hom ≫ eH.inv ≫ (α.app ((H n).obj X)).inv := by
      simpa [eH, Functor.map_comp, Category.assoc] using hmap
    exact hmain₁.trans hmain₂
  exact hmain.trans hfinal

/-- Helper for Proposition 15.79.3: the degree-zero truncation sandwich has the same zeroth
homology as the original derived object. -/
noncomputable def truncGE_truncLT_zero_homologyIso_local
    (X : DMod) :
    (H (0 : ℤ)).obj ((DerivedCategory.TStructure.t.truncGE 0).obj
      ((DerivedCategory.TStructure.t.truncLT 1).obj X)) ≅
        (H (0 : ℤ)).obj X := by
  let eπ :
      (H (0 : ℤ)).obj ((DerivedCategory.TStructure.t.truncLT 1).obj X) ≅
        (H (0 : ℤ)).obj ((DerivedCategory.TStructure.t.truncGE 0).obj
          ((DerivedCategory.TStructure.t.truncLT 1).obj X)) := by
    -- Proof comment: the lower truncation projection preserves the critical degree-zero
    -- homology group.
    exact @asIso _ _ _ _
      ((H (0 : ℤ)).map
        ((DerivedCategory.TStructure.t.truncGEπ 0).app
          ((DerivedCategory.TStructure.t.truncLT 1).obj X)))
      (isIso_homologyMap_truncGEπ (A := ModuleCat R)
        ((DerivedCategory.TStructure.t.truncLT 1).obj X) 0)
  let eι :
      (H (0 : ℤ)).obj ((DerivedCategory.TStructure.t.truncLT 1).obj X) ≅
        (H (0 : ℤ)).obj X := by
    -- Proof comment: the upper truncation inclusion is also an isomorphism on degree zero.
    exact @asIso _ _ _ _
      ((H (0 : ℤ)).map ((DerivedCategory.TStructure.t.truncLTι 1).app X))
      (isIso_homologyMap_truncLTι (A := ModuleCat R) X 0 1 rfl)
  exact eπ.symm ≪≫ eι

/-- Helper for Proposition 15.79.3: the degree-zero truncation sandwich is canonically the single
object on the zeroth homology module. -/
-- TODO: complete the source-faithful concentrated-object identification by packaging the
-- `τ_{<1}`/`τ_{≥0}` sandwich as a single-degree object and then rewriting its coefficient by
-- `H^0`. This is the first object-level bridge in the Hom-H0 comparison chain.
noncomputable def truncGE_truncLT_zero_termIso_local
    (X : DMod) :
    (DerivedCategory.TStructure.t.truncGE 0).obj
        ((DerivedCategory.TStructure.t.truncLT 1).obj X) ≅
      (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj ((H (0 : ℤ)).obj X) :=
  sorry

/-- Helper for Proposition 15.79.3: on degree-zero single objects, zeroth homology detects
morphisms. -/
lemma single_zero_map_ext_local
    {A B : ModuleCat R}
    {q₁ q₂ :
      (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A ⟶
        (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj B}
    (h : (H (0 : ℤ)).map q₁ = (H (0 : ℤ)).map q₂) :
    q₁ = q₂ := by
  let α := DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) (0 : ℤ)
  let u₁ : A ⟶ B := (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).preimage q₁
  let u₂ : A ⟶ B := (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).preimage q₂
  have h₁ := NatIso.naturality_1 α u₁
  have h₂ := NatIso.naturality_1 α u₂
  have h₁' :
      (α.app A).inv ≫ (H (0 : ℤ)).map q₁ ≫ (α.app B).hom = u₁ := by
    -- Proof comment: rewrite each single-degree morphism through the fully faithful preimage and
    -- then evaluate the owner homology comparison on that preimage.
    simpa [u₁, Functor.comp_map, Functor.map_comp,
      (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).map_preimage q₁,
      Category.assoc] using h₁
  have h₂' :
      (α.app A).inv ≫ (H (0 : ℤ)).map q₂ ≫ (α.app B).hom = u₂ := by
    simpa [u₂, Functor.comp_map, Functor.map_comp,
      (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).map_preimage q₂,
      Category.assoc] using h₂
  have hu : u₁ = u₂ := by
    exact h₁'.symm.trans <| (by rw [h]; exact h₂')
  simpa [u₁, u₂] using
    congrArg ((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).map) hu

/-- Helper for Proposition 15.79.3: the homology comparison for the degree-zero truncation
sandwich is natural in the target variable. -/
-- TODO: prove naturality after the concentrated-object bridge is rebuilt as a functor-level
-- comparison rather than by the current pointwise equality chain.
lemma truncGE_truncLT_zero_homologyIso_naturality_local
    {X Y : DMod} (f : X ⟶ Y) :
    (H (0 : ℤ)).map
        ((DerivedCategory.TStructure.t.truncGE 0).map
          ((DerivedCategory.TStructure.t.truncLT 1).map f)) ≫
        (truncGE_truncLT_zero_homologyIso_local (R := R) Y).hom =
      (truncGE_truncLT_zero_homologyIso_local (R := R) X).hom ≫
        (H (0 : ℤ)).map f := by
  sorry

/-- Helper for Proposition 15.79.3: applying zeroth homology to the concentrated truncation
comparison gives the canonical homology identification. -/
-- TODO: once the concentrated-object bridge is rebuilt, recover this equality as the image of
-- the functor-level NatIso instead of by the current explicit hom-calculation.
lemma truncGE_truncLT_zero_termIso_local_homology
    (X : DMod) :
    (H (0 : ℤ)).map (truncGE_truncLT_zero_termIso_local (R := R) X).hom =
      (truncGE_truncLT_zero_homologyIso_local (R := R) X).hom ≫
        ((DerivedCategory.singleFunctorCompHomologyFunctorIso (ModuleCat R) (0 : ℤ)).app
          ((H (0 : ℤ)).obj X)).inv := by
  sorry

/-- Helper for Proposition 15.79.3: the concentrated truncation comparison is natural in the
target variable. -/
-- TODO: deduce this naturality from the functor-level concentrated-object NatIso.
lemma truncGE_truncLT_zero_termIso_naturality_local
    {X Y : DMod} (f : X ⟶ Y) :
    ((DerivedCategory.TStructure.t.truncGE 0).map
        ((DerivedCategory.TStructure.t.truncLT 1).map f)) ≫
        (truncGE_truncLT_zero_termIso_local (R := R) Y).hom =
      (truncGE_truncLT_zero_termIso_local (R := R) X).hom ≫
        (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).map
          ((H (0 : ℤ)).map f) := by
  sorry

/-- Helper for Proposition 15.79.3: evaluation at `1` identifies a morphism out of the free
rank-one module with the chosen element of the target module. -/
lemma hom_from_ring_add_equiv_left_inv_local {N : ModuleCat R} (x : N) :
    (ModuleCat.homEquiv (ModuleCat.ofHom ((LinearMap.id : R →ₗ[R] R).smulRight x))) (1 : R) = x := by
  -- Proof comment: the inverse sends `x` to the linear map `r ↦ r • x`, and evaluating at `1`
  -- recovers `x`.
  change (((LinearMap.id : R →ₗ[R] R).smulRight x) (1 : R)) = x
  simp [LinearMap.smulRight_apply]

/-- Helper for Proposition 15.79.3: a morphism out of the free rank-one module is recovered from
the image of `1`. -/
lemma hom_from_ring_add_equiv_right_inv_local {N : ModuleCat R}
    (f : (ModuleCat.of R R) ⟶ N) :
    ModuleCat.ofHom (((LinearMap.id : R →ₗ[R] R).smulRight ((ModuleCat.homEquiv f) (1 : R)))) = f := by
  -- Proof comment: extensionality reduces the claim to `f (r • 1) = r • f 1`.
  apply ModuleCat.hom_injective
  exact LinearMap.ext fun r ↦ by
    simp [LinearMap.smulRight_apply]
    simpa using ((ModuleCat.homEquiv f).map_smul r (1 : R)).symm

/-- Helper for Proposition 15.79.3: evaluation at `1` preserves addition on morphisms out of the
free rank-one module. -/
lemma hom_from_ring_add_equiv_map_add_local {N : ModuleCat R}
    (f g : (ModuleCat.of R R) ⟶ N) :
    (ModuleCat.homEquiv (f + g)) (1 : R) =
      (ModuleCat.homEquiv f) (1 : R) + (ModuleCat.homEquiv g) (1 : R) :=
  rfl

/-- Helper for Proposition 15.79.3: morphisms out of the free rank-one module `R` are additively
equivalent to elements of the target module. -/
noncomputable def hom_from_ring_add_equiv_local (N : ModuleCat R) :
    ((ModuleCat.of R R) ⟶ N) ≃+ N :=
  { toFun := fun f ↦ (ModuleCat.homEquiv f) (1 : R)
    invFun := fun x ↦ ModuleCat.ofHom ((LinearMap.id : R →ₗ[R] R).smulRight x)
    left_inv := hom_from_ring_add_equiv_right_inv_local (R := R)
    right_inv := hom_from_ring_add_equiv_left_inv_local (R := R)
    map_add' := hom_from_ring_add_equiv_map_add_local (R := R) }

/-- Helper for Proposition 15.79.3: zeroth homology commutes with arbitrary discrete coproducts
of derived `R`-modules after forgetting to additive groups. -/
-- TODO: reinstall the exact-colimit universe parameters for `ModuleCat` and then deduce
-- coproduct preservation of `H^0` from exactness before forgetting to additive groups.
lemma homology_zero_preserves_discrete_coproducts_local
    {I : Type v} :
    PreservesColimitsOfShape (Discrete I)
      (H (0 : ℤ) ⋙ forget₂ (ModuleCat R) AddCommGrpCat) := by
  sorry

/-- Helper for Proposition 15.79.3: maps from a degree-zero single object are already detected on
the upper truncation `τ_{<1}` because the source itself lies in degrees `≤ 0`. -/
-- TODO: replace this pointwise bridge by the functor-level NatIso
-- `preadditiveCoyoneda.obj (op ringSingle) ≅ preadditiveCoyoneda.obj (op ringSingle) ⋙ τ_{<1}`.
noncomputable def single_zero_hom_equiv_truncLT_zero_local
    (A : ModuleCat R) (X : DMod) :
    (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶ X) ≃+
      (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
        (DerivedCategory.TStructure.t.truncLT 1).obj X) :=
  sorry

/-- Helper for Proposition 15.79.3: degree-zero single objects are fully faithful in the derived
category, so morphisms between them are exactly module morphisms. -/
noncomputable def single_zero_fullyFaithful_add_equiv_local
    (A B : ModuleCat R) :
    (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
      ((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj B)) ≃+
        (A ⟶ B) := by
  let F := DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)
  -- Proof comment: the Chapter 15 comparison now uses the owner theorem that `singleFunctor` is
  -- fully faithful, so we can move between derived morphisms and module maps without extra
  -- truncation work.
  exact
    { toFun := fun f ↦ F.preimage f
      invFun := fun f ↦ F.map f
      left_inv := by
        intro f
        simp [F]
      right_inv := by
        intro f
        simp [F]
      map_add' := by
        intro f g
        apply F.map_injective
        simp [F] }

/-- Helper for Proposition 15.79.3: once the target has been replaced by the concentrated
degree-zero truncation piece, maps out of `A[0]` identify with maps into `H^0(X)`. -/
noncomputable def single_zero_hom_equiv_homology_zero_truncation_local
    (A : ModuleCat R) (X : DMod) :
    (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
      (DerivedCategory.TStructure.t.truncGE 0).obj
        ((DerivedCategory.TStructure.t.truncLT 1).obj X)) ≃+
        (A ⟶ (H (0 : ℤ)).obj X) := by
  let eTarget := truncGE_truncLT_zero_termIso_local (R := R) X
  let ePost :
      (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
        (DerivedCategory.TStructure.t.truncGE 0).obj
          ((DerivedCategory.TStructure.t.truncLT 1).obj X)) ≃+
        (((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
          (DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj
            ((H (0 : ℤ)).obj X)) :=
    { toFun := fun f ↦ f ≫ eTarget.hom
      invFun := fun f ↦ f ≫ eTarget.inv
      left_inv := by
        intro f
        simp [eTarget, Category.assoc]
      right_inv := by
        intro f
        simp [eTarget, Category.assoc]
      map_add' := by
        intro f g
        simp [Category.assoc] }
  -- Proof comment: after replacing the target by the actual single-degree object
  -- `H^0(X)[0]`, full faithfulness of `singleFunctor` gives the desired additive equivalence.
  exact ePost.trans
    (single_zero_fullyFaithful_add_equiv_local (R := R) A ((H (0 : ℤ)).obj X))

/-- Helper for Proposition 15.79.3: after the target has been replaced by the concentrated
degree-zero truncation piece, maps out of `R[0]` are already identified with elements of
`H^0(X)`. -/
noncomputable def ring_single_hom_equiv_homology_zero_truncation_local
    (X : DMod) :
    ((ringSingle : DMod) ⟶ (DerivedCategory.TStructure.t.truncGE 0).obj
      ((DerivedCategory.TStructure.t.truncLT 1).obj X)) ≃+ (H (0 : ℤ)).obj X := by
  -- Proof comment: specialize the generic `A[0]` comparison to `A = R`, then evaluate at
  -- `1 : R` using the explicit additive equivalence for maps out of the free rank-one module.
  exact
    (single_zero_hom_equiv_homology_zero_truncation_local
      (R := R) (A := ModuleCat.of R R) X).trans
      (hom_from_ring_add_equiv_local (R := R) ((H (0 : ℤ)).obj X))

/-- Helper for Proposition 15.79.3: exactness of the degree-zero truncation triangle makes
postcomposition with `τ_{≥ 0}` an additive equivalence on maps out of `R[0]`. -/
-- TODO: replace this pointwise additive equivalence by the functor-level NatIso through the
-- special truncation triangle, using the already established vanishing lemmas for maps from
-- `R[0]` into `D^{≤ -1}` and its shift.
noncomputable def single_zero_hom_equiv_truncGE_truncLT_zero_local
    (X : DMod) :
    ((ringSingle : DMod) ⟶ (DerivedCategory.TStructure.t.truncLT 1).obj X) ≃+
      ((ringSingle : DMod) ⟶ (DerivedCategory.TStructure.t.truncGE 0).obj
        ((DerivedCategory.TStructure.t.truncLT 1).obj X)) :=
  sorry

/-- Helper for Proposition 15.79.3: composing the three truncation comparisons gives the
source-faithful additive identification `Hom(R[0], X) ≃ H^0(X)`. -/
noncomputable def ring_single_hom_equiv_homology_zero_local
    (X : DMod) :
    ((ringSingle : DMod) ⟶ X) ≃+ (H (0 : ℤ)).obj X := by
  -- Proof comment: first pass to `τ_{<1} X`, then through the exact degree-zero truncation
  -- bridge, and finally identify the concentrated target with `H^0(X)[0]`.
  exact
    (single_zero_hom_equiv_truncLT_zero_local
      (R := R) (A := ModuleCat.of R R) X).trans
      ((single_zero_hom_equiv_truncGE_truncLT_zero_local (R := R) X).trans
        (ring_single_hom_equiv_homology_zero_truncation_local (R := R) X))

/-- Helper for Proposition 15.79.3: the first truncation comparison `Hom(A[0], X) →
Hom(A[0], τ_{<1} X)` is natural in the target variable. -/
-- TODO: this should become automatic after replacing the pointwise `AddEquiv` by the
-- corresponding functor-level NatIso.
lemma single_zero_hom_equiv_truncLT_zero_naturality_local
    {A : ModuleCat R} {X Y : DMod} (f : X ⟶ Y)
    (g : ((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶ X) :
    single_zero_hom_equiv_truncLT_zero_local (R := R) A Y (g ≫ f) =
      single_zero_hom_equiv_truncLT_zero_local (R := R) A X g ≫
        (DerivedCategory.TStructure.t.truncLT 1).map f := by
  sorry

/-- Helper for Proposition 15.79.3: the exact degree-zero truncation bridge is natural in the
target variable. -/
-- TODO: this is the middle functor-level truncation NatIso from the source-faithful plan.
lemma single_zero_hom_equiv_truncGE_truncLT_zero_naturality_local
    {X Y : DMod} (f : X ⟶ Y)
    (g : (ringSingle : DMod) ⟶ (DerivedCategory.TStructure.t.truncLT 1).obj X) :
    single_zero_hom_equiv_truncGE_truncLT_zero_local (R := R) Y
        (g ≫ (DerivedCategory.TStructure.t.truncLT 1).map f) =
      single_zero_hom_equiv_truncGE_truncLT_zero_local (R := R) X g ≫
        (DerivedCategory.TStructure.t.truncGE 0).map
          ((DerivedCategory.TStructure.t.truncLT 1).map f) := by
  sorry

/-- Helper for Proposition 15.79.3: evaluation at `1` is natural for maps out of the free
rank-one module. -/
lemma hom_from_ring_add_equiv_naturality_local
    {M N : ModuleCat R} (k : M ⟶ N) (u : (ModuleCat.of R R) ⟶ M) :
    hom_from_ring_add_equiv_local (R := R) N (u ≫ k) =
      k (hom_from_ring_add_equiv_local (R := R) M u) := by
  -- Proof comment: both sides are the image of `1 : R` under the composite linear map.
  change (ModuleCat.homEquiv (u ≫ k)) (1 : R) = k ((ModuleCat.homEquiv u) (1 : R))
  rfl

/-- Helper for Proposition 15.79.3: after passing to the concentrated degree-zero truncation
piece, the identification with maps into `H^0` is natural in the target variable. -/
-- TODO: after the NatIso pivot, this becomes a one-line corollary of naturality of the
-- concentrated-object comparison.
lemma single_zero_hom_equiv_homology_zero_truncation_naturality_local
    (A : ModuleCat R) {X Y : DMod} (f : X ⟶ Y)
    (g : ((DerivedCategory.singleFunctor (ModuleCat R) (0 : ℤ)).obj A) ⟶
      (DerivedCategory.TStructure.t.truncGE 0).obj
        ((DerivedCategory.TStructure.t.truncLT 1).obj X)) :
    single_zero_hom_equiv_homology_zero_truncation_local (R := R) A Y
        (g ≫ (DerivedCategory.TStructure.t.truncGE 0).map
          ((DerivedCategory.TStructure.t.truncLT 1).map f)) =
      single_zero_hom_equiv_homology_zero_truncation_local (R := R) A X g ≫
        (H (0 : ℤ)).map f := by
  sorry

/-- Helper for Proposition 15.79.3: after the source-faithful truncation comparison has reduced
maps out of `R[0]` to the concentrated piece, the final identification with `H^0` is natural in
the target variable. -/
-- TODO: after the NatIso pivot, this follows by composing the concentrated-piece comparison with
-- the evaluation-at-`1` equivalence.
lemma ring_single_hom_equiv_homology_zero_truncation_naturality_local
    {X Y : DMod} (f : X ⟶ Y)
    (g : (ringSingle : DMod) ⟶ (DerivedCategory.TStructure.t.truncGE 0).obj
      ((DerivedCategory.TStructure.t.truncLT 1).obj X)) :
    ring_single_hom_equiv_homology_zero_truncation_local (R := R) Y
        (g ≫ (DerivedCategory.TStructure.t.truncGE 0).map
          ((DerivedCategory.TStructure.t.truncLT 1).map f)) =
      (H (0 : ℤ)).map f
        (ring_single_hom_equiv_homology_zero_truncation_local (R := R) X g) := by
  sorry

/-- Helper for Proposition 15.79.3: the full source-faithful comparison `Hom_D(R[0], X) ≃ H^0(X)`
is natural in the target variable. -/
-- TODO: once the three truncation bridges are packaged functorially, this becomes their direct
-- composite naturality statement.
lemma ring_single_hom_equiv_homology_zero_naturality_local
    {X Y : DMod} (f : X ⟶ Y) (φ : (ringSingle : DMod) ⟶ X) :
    ring_single_hom_equiv_homology_zero_local (R := R) Y (φ ≫ f) =
      (H (0 : ℤ)).map f
        (ring_single_hom_equiv_homology_zero_local (R := R) X φ) := by
  sorry

/-- Helper for Proposition 15.79.3: the represented Hom functor of `R[0]` is the degree-zero
homology functor after forgetting to additive groups. -/
-- TODO: rebuild this as the composite NatIso through `τ_{<1}`, `τ_{≥0}τ_{<1}`, and the
-- concentrated `H^0`-piece, so naturality is carried by `NatIso.ofComponents` instead of by the
-- pointwise equality chain above.
noncomputable def ring_single_coyoneda_iso_homology_zero_local :
    Unit :=
  ()

/-- Helper for Proposition 15.79.3: functions on `Fin (n + 1)` split into the first coordinate
and the remaining `Fin n` coordinates. -/
private noncomputable def finSuccArrowLinearEquiv_local (n : ℕ) :
    (Fin (n + 1) → R) ≃ₗ[R] (R × (Fin n → R)) where
  toEquiv := (Fin.consEquiv fun _ : Fin (n + 1) => R).symm
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Helper for Proposition 15.79.3: the degree-zero ring object `R[0]` is compact in `D(R)`. -/
-- TODO: deduce compactness from the rebuilt represented-Hom/H^0 NatIso together with
-- coproduct preservation of zeroth homology.
lemma ring_single_isCompactObject_local :
    IsCompactObject (ringSingle : DMod) := by
  sorry

/-- Helper for Proposition 15.79.3: if `P ≤ Q` and `Q` is shift-stable, then every bounded shift
interval of `P` also lies in `Q`. -/
private theorem shiftInterval_le_of_le_local
    {P Q : ObjectProperty DMod}
    [Q.IsClosedUnderIsomorphisms] [Q.IsStableUnderShift ℤ]
    (hPQ : P ≤ Q) (a b : ℤ) :
    P[a, b] ≤ Q := by
  intro X hX
  -- Proof comment: unwrap the interval witness, move the base property across `hPQ`, and then
  -- shift back using the stability of `Q`.
  rw [prop_shiftInterval_iff] at hX
  rcases hX with ⟨n, _, Y, hY, ⟨e⟩⟩
  rw [prop_shift_iff] at hY
  have hQshift : Q (Y⟦n⟧) := hPQ _ hY
  have hQYshiftNeg : Q ((Y⟦n⟧)⟦(-n : ℤ)⟧) := Q.le_shift (-n : ℤ) _ hQshift
  have hQY : Q Y := Q.prop_of_iso (shiftShiftNeg Y n) hQYshiftNeg
  exact Q.prop_of_iso e.symm hQY

/-- Helper for Proposition 15.79.3: if `P ≤ Q` and `Q` is saturated triangulated, then every
additive extension stage built from `P` also lies in `Q`. -/
private theorem additiveExtensionStage_le_of_le_local
    {P Q : ObjectProperty DMod}
    [Q.IsStableUnderRetracts] [Q.IsTriangulated]
    (hPQ : P ≤ Q) (n : ℕ+) :
    additiveExtensionStage P n ≤ Q := by
  -- Proof comment: additive-extension stages are built from additive closure, extensions, and
  -- retracts, so they stay inside any saturated triangulated property that already contains `P`.
  rw [additiveExtensionStage, retractClosure_le_iff]
  exact P.additiveClosure.extensionProductIter_le_of_isTriangulatedClosed₂
    (by
      refine colimitsClosure_le ?_
      exact hPQ)
    n.natPred

/-- Helper for Proposition 15.79.3: the degree-zero single object on the finite free module
`R^n` is compact. -/
-- TODO: once `R[0]` is recovered as compact by the functor-level Hom-H0 comparison, re-run the
-- biproduct induction on finite free modules inside the compact-object property.
private theorem finite_free_single_isCompactObject_local
    (n : ℕ) :
    IsCompactObject ((single₀).obj (ModuleCat.of R (Fin n → R))) := by
  sorry

/-- Helper for Proposition 15.79.3: the degree-zero single object on any finite projective
module is compact. -/
-- TODO: after the finite-free case is restored, recover finite projective compactness by
-- transporting the standard retract argument through `single₀`.
private theorem finiteProjective_single_isCompactObject_local
    (M : FiniteProjectiveModuleCat.{u} R) :
    IsCompactObject ((single₀).obj M.obj) := by
  sorry

/-- Helper for Proposition 15.79.3: the cochain single complex on a finite projective module is a
bounded finite-projective complex. -/
private theorem finiteProjectiveModule_single_isBoundedFiniteProjective_local
    (M : FiniteProjectiveModuleCat R) :
    CochainComplex.IsBoundedFiniteProjective
      ((CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj) := by
  -- Proof comment: the single complex is supported in degree `0`; outside that degree the terms
  -- are zero, hence still finite and projective.
  refine ⟨⟨0, 0, ?_, ?_⟩, ?_, ?_⟩
  · simpa using
      (inferInstance :
        ((CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj).IsStrictlyGE (0 : ℤ))
  · simpa using
      (inferInstance :
        ((CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj).IsStrictlyLE (0 : ℤ))
  · intro i
    by_cases hi : i = 0
    · subst hi
      letI : Module.Finite R M.obj := M.property.1
      simpa using
        (Module.Finite.equiv
          (HomologicalComplex.singleObjXSelf (ComplexShape.up ℤ) (0 : ℤ) M.obj).toLinearEquiv.symm)
    · let E : CochainComplex (ModuleCat R) ℤ :=
        (CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj
      let hzero := by
        simpa [E] using
          (HomologicalComplex.isZero_single_obj_X (ComplexShape.up ℤ) (0 : ℤ) M.obj i hi)
      letI : Subsingleton ↥(E.X i) := ModuleCat.subsingleton_of_isZero hzero
      let e : ModuleCat.of R PUnit ≅ E.X i :=
        (ModuleCat.isZero_of_subsingleton (ModuleCat.of R PUnit)).isoZero ≪≫ hzero.isoZero.symm
      exact Module.Finite.equiv e.toLinearEquiv
  · intro i
    by_cases hi : i = 0
    · subst hi
      letI : Module.Projective R M.obj := M.property.2
      simpa using
        (Module.Projective.of_equiv
          (HomologicalComplex.singleObjXSelf (ComplexShape.up ℤ) (0 : ℤ) M.obj).toLinearEquiv.symm)
    · let E : CochainComplex (ModuleCat R) ℤ :=
        (CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj
      let hzero := by
        simpa [E] using
          (HomologicalComplex.isZero_single_obj_X (ComplexShape.up ℤ) (0 : ℤ) M.obj i hi)
      letI : Subsingleton ↥(E.X i) := ModuleCat.subsingleton_of_isZero hzero
      letI : Module.Free R ↥(E.X i) := Module.Free.of_subsingleton (R := R) (N := ↥(E.X i))
      exact Module.Projective.of_free

/-- Helper for Proposition 15.79.3: the degree-zero ring object `R[0]` is perfect. -/
private theorem ring_single_isPerfect_local :
    DerivedCategory.IsPerfect (ringSingle : DMod) := by
  let M : FiniteProjectiveModuleCat R :=
    ⟨ModuleCat.of R R, ⟨inferInstance, inferInstance⟩⟩
  -- Proof comment: use the literal degree-zero single complex on the free rank-one module.
  refine ⟨(CochainComplex.singleFunctor (ModuleCat R) (0 : ℤ)).obj M.obj, ?_, ?_⟩
  · simpa [ringSingle] using (Iso.refl ((single₀).obj (ModuleCat.of R R)))
  · simpa using finiteProjectiveModule_single_isBoundedFiniteProjective_local (R := R) M

/-- Helper for Proposition 15.79.3: perfect objects form a triangulated object property in
`D(R)`. -/
-- TODO: the earlier owner theorem `Lemma_15_75_7` is currently only available under a
-- commutative-ring hypothesis, while Proposition 15.79.3 is stated for an arbitrary ring. A
-- ring-level two-out-of-three bridge for perfect objects is the remaining structural owner gap on
-- the perfect-object side.
private instance perfectObjectProperty_isTriangulated_local :
    ObjectProperty.IsTriangulated PerfectObj := by
  sorry

/-- Helper for Proposition 15.79.3: perfect objects are stable under retracts in `D(R)`. -/
private instance perfectObjectProperty_isStableUnderRetracts_local :
    ObjectProperty.IsStableUnderRetracts PerfectObj := by
  -- TODO: the earlier owner file `Lemma_15_75_5` currently fails to build in this workspace, so
  -- the retract-stability bridge cannot be imported here yet. Restore the canonical owner route
  -- once that file compiles, or strictify retracts locally as a fallback.
  sorry

/-- Helper for Proposition 15.79.3: every perfect object of `D(R)` is compact once `R[0]` is. -/
lemma perfect_implies_compact_local {K : DMod} (hK : K.IsPerfect) :
    IsCompactObject K := by
  let P : ObjectProperty DMod := IsCompactObject
  letI : P.IsTriangulated := inferInstance
  letI : P.IsStableUnderRetracts := inferInstance
  rcases hK with ⟨L, e, hL⟩
  letI : CochainComplex.IsBoundedFiniteProjective L := hL
  rcases hL.bounded with ⟨a, b, hGE, hLE⟩
  have hbase :
      (((finiteProjectiveModuleProperty R).map single₀ : ObjectProperty DMod) ≤ P) := by
    intro X hX
    -- Proof comment: unpack the image-property witness and reduce to the finite projective
    -- degree-zero compactness lemma.
    rcases hX with ⟨M, hM, ⟨eX⟩⟩
    let M' : FiniteProjectiveModuleCat R := ⟨M, hM⟩
    exact P.prop_of_iso eX <|
      finiteProjective_single_isCompactObject_local (R := R) M'
  have hinterval :
      ((((finiteProjectiveModuleProperty R).map single₀)[a, b] : ObjectProperty DMod) ≤ P) := by
    exact shiftInterval_le_of_le_local (R := R) hbase a b
  let n : ℕ+ := Nat.succPNat (Int.toNat (b - a))
  have hstage :
      additiveExtensionStage (((finiteProjectiveModuleProperty R).map single₀)[a, b]) n K := by
    -- Proof comment: the chosen bounded finite-projective representative puts `K` in the
    -- expected additive-extension stage of degree-zero finite projective terms.
    refine mem_additiveExtensionStage_of_exists_representative_mem
      (E := finiteProjectiveModuleProperty R) (K := K) (a := a) (b := b) ?_
    refine ⟨L, e.symm, hGE, hLE, ?_⟩
    intro i
    exact ⟨hL.finite i.1, hL.projective i.1⟩
  have hstageLe :
      additiveExtensionStage (((finiteProjectiveModuleProperty R).map single₀)[a, b]) n ≤ P := by
    exact additiveExtensionStage_le_of_le_local (R := R) hinterval n
  exact hstageLe _ hstage

/-- Helper for Proposition 15.79.3: if every cohomology object of a derived object vanishes, then
the derived object itself is zero. -/
private lemma isZero_of_homologyFunctor_obj_isZero_local
    (K : DMod) (hK : ∀ i : ℤ, IsZero ((H i).obj K)) :
    IsZero K := by
  have hLE : K.IsLE 0 := by
    rw [DerivedCategory.isLE_iff]
    intro i hi
    exact hK i
  have hGE : K.IsGE 1 := by
    rw [DerivedCategory.isGE_iff]
    intro i hi
    exact hK i
  letI : K.IsLE 0 := hLE
  letI : K.IsGE 1 := hGE
  -- Proof comment: simultaneous membership in `D^{≤ 0}` and `D^{≥ 1}` forces `K` into the empty
  -- overlap of the standard `t`-structure.
  exact DerivedCategory.TStructure.t.isZero K 0 1 (by omega)

/-- Helper for Proposition 15.79.3: right-orthogonality to all shifts of `R[0]` forces the zeroth
homology module to vanish. -/
private lemma homology_zero_isZero_of_ring_single_rightOrthogonal_local
    {X : DMod}
    (hX : ((singleton (ringSingle : DMod)).shiftClosure ℤ).rightOrthogonal X) :
    IsZero ((H (0 : ℤ)).obj X) := by
  have hsub :
      Subsingleton ((H (0 : ℤ)).obj X) := by
    refine ⟨fun x y ↦ ?_⟩
    have hring :
        ((singleton (ringSingle : DMod)).shiftClosure ℤ) (ringSingle : DMod) := by
      exact
        ⟨(ringSingle : DMod), 0, (shiftFunctorZero DMod ℤ).symm.app (ringSingle : DMod),
          by simp⟩
    have hx :
        (ring_single_hom_equiv_homology_zero_local (R := R) X).symm x = 0 := by
      exact hX _ hring
    have hy :
        (ring_single_hom_equiv_homology_zero_local (R := R) X).symm y = 0 := by
      exact hX _ hring
    have hx0 : x = 0 := by
      simpa using
        congrArg (ring_single_hom_equiv_homology_zero_local (R := R) X) hx
    have hy0 : y = 0 := by
      simpa using
        congrArg (ring_single_hom_equiv_homology_zero_local (R := R) X) hy
    calc
      x = 0 := hx0
      _ = y := hy0.symm
  exact ModuleCat.isZero_of_subsingleton ((H (0 : ℤ)).obj X)

/-- Helper for Proposition 15.79.3: right-orthogonality to all shifts of `R[0]` forces every
cohomology object to vanish. -/
private lemma homology_isZero_of_ring_single_rightOrthogonal_local
    {K : DMod}
    (hK : ((singleton (ringSingle : DMod)).shiftClosure ℤ).rightOrthogonal K)
    (i : ℤ) :
    IsZero ((H i).obj K) := by
  have hShift :
      ((singleton (ringSingle : DMod)).shiftClosure ℤ).rightOrthogonal (K⟦i⟧) :=
    ((singleton (ringSingle : DMod)).shiftClosure ℤ).rightOrthogonal.le_shift i K hK
  have hZeroShift :
      IsZero ((H (0 : ℤ)).obj (K⟦i⟧)) :=
    homology_zero_isZero_of_ring_single_rightOrthogonal_local (R := R) hShift
  let e :
      (H (0 : ℤ)).obj (K⟦i⟧) ≅ (H i).obj K :=
    ((H (0 : ℤ)).shiftIso i 0 i (by omega)).app K
  exact e.isZero_iff.1 hZeroShift

/-- Helper for Proposition 15.79.3: the degree-zero ring object `R[0]` is a weak generator of
`D(R)`. -/
private theorem ring_single_isWeakGenerator_local :
    IsWeakGenerator (ringSingle : DMod) := by
  rw [isWeakGenerator_iff_rightOrthogonal_shifts_eq_isZero]
  ext K
  constructor
  · intro hK
    -- Proof comment: the established comparison `Hom_D(R[0], X) ≃ H^0(X)` detects every
    -- cohomology object after shifting, so right-orthogonality to all shifts forces all
    -- cohomology to vanish.
    exact isZero_of_homologyFunctor_obj_isZero_local (R := R) K <|
      homology_isZero_of_ring_single_rightOrthogonal_local (R := R) hK
  · intro hK X f hX
    exact hK.eq_zero_of_tgt f

/-- Helper for Proposition 15.79.3: every compact object of `D(R)` lies in the thick subcategory
generated by `R[0]`. -/
-- TODO: once `R[0]` is re-established as a compact weak generator through the functor-level
-- Hom-H0 comparison, re-run Proposition `13.37.6` on compact objects to recover this generated
-- subcategory membership.
lemma compact_generated_by_ring_single_local {K : DMod} (hK : IsCompactObject K) :
    (⟨ringSingle⟩ : ObjectProperty DMod) K := by
  sorry

/-- Proposition 15.79.3: for an object `K` of `D(R)`, being perfect is equivalent to being a
compact object. -/
-- TODO: the perfect-to-compact branch is reduced to the compactness of `R[0]` and the finite
-- projective compactness induction, while the compact-to-perfect branch is reduced to the
-- generated-subcategory argument once `R[0]` is re-established as a compact weak generator.
theorem isPerfect_iff_isCompactObject (K : DMod) :
    K.IsPerfect ↔ IsCompactObject K := by
  sorry

end

end CategoryTheory
