import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.TrajectoryCore
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.SimplexWeights
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.ClusterConvergence
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.InteriorWeightedSum
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.TrajectoryWeights
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.PartialSumsDivergence
import FirstOrderMethodsinOptimization.Chap13.Lemma_13_19.CurvatureLowerBound
