import Mathlib.RingTheory.RegularLocalRing.Defs
import stacks_project.Chap10.Definition_10_59_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open IsLocalRing

section

variable {R : Type u} [CommRing R] [IsLocalRing R]

namespace IsLocalRing

/-- The ideal generated by a finite sequence in the maximal ideal of a local ring. -/
def parameterIdeal {d : ℕ} (x : Fin d → maximalIdeal R) : Ideal R :=
  Ideal.span (Set.range fun i ↦ (x i : R))

/-- Unfolding `parameterIdeal` as the ideal spanned by the underlying sequence in `R`. -/
@[simp] theorem parameterIdeal_eq_span {d : ℕ} (x : Fin d → maximalIdeal R) :
    parameterIdeal x = Ideal.span (Set.range fun i ↦ (x i : R)) :=
  rfl

/-- Definition 10.60.10 (1): a system of parameters is a length-`d` sequence in the maximal ideal
whose generated ideal is an ideal of definition. -/
def IsSystemOfParameters {d : ℕ} (x : Fin d → maximalIdeal R) : Prop :=
  ringKrullDim R = d ∧ (parameterIdeal x).IsIdealOfDefinition

/-- A sequence in the maximal ideal is a system of parameters exactly when its generated ideal is
an ideal of definition. -/
@[simp] theorem isSystemOfParameters_iff {d : ℕ} (x : Fin d → maximalIdeal R) :
    IsSystemOfParameters x ↔
      (ringKrullDim R = d ∧ (parameterIdeal x).IsIdealOfDefinition) :=
  Iff.rfl

/-- In a local ring whose Krull dimension is already identified with `d`, a length-`d` sequence in
the maximal ideal is a system of parameters exactly when its generated ideal is an ideal of
definition. -/
@[simp] theorem isSystemOfParameters_iff_of_ringKrullDim_eq {d : ℕ}
    (hdim : ringKrullDim R = d) (x : Fin d → maximalIdeal R) :
    IsSystemOfParameters x ↔ (parameterIdeal x).IsIdealOfDefinition := by
  rw [isSystemOfParameters_iff]
  simp [hdim]

/-- Definition 10.60.10 (2), bridge/view form: a regular system of parameters is a system of
parameters whose generated ideal is the maximal ideal itself. This keeps the chosen-family owner
abstraction `IsSystemOfParameters` primitive, while the ambient regularity owner abstraction is
`IsRegularLocalRing R`. -/
def IsRegularSystemOfParameters {d : ℕ} (x : Fin d → maximalIdeal R) : Prop :=
  IsSystemOfParameters x ∧ parameterIdeal x = maximalIdeal R

/-- A length-`c` sequence in the maximal ideal is part of a regular system of parameters of total
length `d` if it extends to a regular system of parameters after adjoining `d - c` further
elements. This is the source-facing existential owner for "part of a regular system" while
`IsRegularSystemOfParameters` remains the chosen-family bridge. -/
def IsPartOfRegularSystemOfParameters (d : ℕ) {c : ℕ} (x : Fin c → maximalIdeal R) : Prop :=
  ∃ y : Fin (d - c) → maximalIdeal R, IsRegularSystemOfParameters (Fin.append x y)

/-- Unfolding `IsRegularSystemOfParameters` into its dimension and maximal-ideal-generation
clauses. -/
@[simp] theorem isRegularSystemOfParameters_iff {d : ℕ} (x : Fin d → maximalIdeal R) :
    IsRegularSystemOfParameters x ↔
      (ringKrullDim R = d ∧ parameterIdeal x = maximalIdeal R) := by
  constructor
  · rintro ⟨hx, hmax⟩
    exact ⟨hx.1, hmax⟩
  · rintro ⟨hdim, hmax⟩
    exact ⟨
      (isSystemOfParameters_iff_of_ringKrullDim_eq hdim x).2 <|
        hmax ▸ Ideal.maximalIdeal_isIdealOfDefinition,
      hmax
    ⟩

/-- Unfolding `IsPartOfRegularSystemOfParameters` into the existence of a complementary tail. -/
@[simp] theorem isPartOfRegularSystemOfParameters_iff (d : ℕ) {c : ℕ}
    (x : Fin c → maximalIdeal R) :
    IsPartOfRegularSystemOfParameters d x ↔
      ∃ y : Fin (d - c) → maximalIdeal R, IsRegularSystemOfParameters (Fin.append x y) :=
  Iff.rfl

/-- With the dimension fixed in advance, a regular system of parameters is exactly a generating
family of the maximal ideal. -/
@[simp] theorem isRegularSystemOfParameters_iff_of_ringKrullDim_eq {d : ℕ}
    (hdim : ringKrullDim R = d) (x : Fin d → maximalIdeal R) :
    IsRegularSystemOfParameters x ↔ parameterIdeal x = maximalIdeal R := by
  rw [isRegularSystemOfParameters_iff]
  simp [hdim]

/-- A regular system of parameters is, in particular, a system of parameters. -/
theorem IsRegularSystemOfParameters.isSystemOfParameters {d : ℕ} {x : Fin d → maximalIdeal R}
    (hx : IsRegularSystemOfParameters x) :
    IsSystemOfParameters x :=
  hx.1

end IsLocalRing

/- Core/canonical owner for the ambient regularity clause: `IsRegularLocalRing R` says that the
maximal ideal can be generated by `dim R` elements. The local predicate
`IsRegularSystemOfParameters` is the source-facing chosen-family bridge built on
`IsSystemOfParameters`. -/
#check IsRegularLocalRing

variable [IsNoetherianRing R]

-- Proof sketch: use the canonical characterization `isRegularLocalRing_iff` of regular local
-- rings by the minimal number of generators of the maximal ideal. A regular system of parameters
-- gives a generating family of length `d = dim R`, while a minimal generating family of the
-- maximal ideal can be reindexed by `Fin d`.
/-- Definition 10.60.10 (2), bridge/view form: for a Noetherian local ring of dimension `d`, the
canonical owner `IsRegularLocalRing R` is equivalent to the existence of a regular system of
parameters indexed by `Fin d`. -/
theorem isRegularLocalRing_iff_exists_regularSystemOfParameters {d : ℕ}
    (hdim : ringKrullDim R = d) :
    IsRegularLocalRing R ↔
      ∃ x : Fin d → maximalIdeal R, IsRegularSystemOfParameters x := sorry

end
