import Mathlib
import stacks_project.Chap10.Definition_10_161_1

-- Declarations for this item will be appended below by the statement pipeline.

universe u

/-
Domain triage: this file is in commutative algebra of Japanese/Nagata-style finiteness and
Noetherianity for polynomial rings in infinitely many variables.

Source/core/bridge triage for the target declarations:
- source-facing: the two public example theorems for `MvPolynomial ℕ+ k` and `MvPolynomial ℕ+ ℤ`;
- core/canonical: `IsN2Ring` and `MvPolynomial.idealOfVars`;
- bridge/view: the private reduction from the countable-variable ring to the finite-variable family.

Owner abstractions sampled for this item:
- `IsN2Ring`, the source-facing `N-2` owner from `Definition_10_161_1`;
- `MvPolynomial.idealOfVars`, the canonical owner ideal generated by all variables;
- the finite-variable polynomial-ring owner theorem `isN2Ring_polynomial`, iterated through
  `MvPolynomial.finSuccEquiv` in the proof sketches below.

Primitive data here are only the coefficient ring and the countably many polynomial variables.
The `N-2` claim and the failure of Noetherianity are derived properties, so the public API should
stay as the two source-facing conjunction theorems while any reusable proof decomposition remains
private.
-/

-- Proof sketch: if `MvPolynomial σ R` were Noetherian, then the owner ideal
-- `MvPolynomial.idealOfVars σ R` would be finitely generated. Any finite generating family uses
-- only finitely many variables, so choosing a variable outside that finite support shows the
-- corresponding generator `X i` is not in the generated ideal, contradiction.
private theorem mvPolynomial_not_isNoetherianRing_of_infinite
    (σ : Type*) [Infinite σ] (R : Type u) [CommRing R] [Nontrivial R] :
    ¬ IsNoetherianRing (MvPolynomial σ R) := by
  sorry

-- Proof sketch: let `L / FractionRing (MvPolynomial ℕ+ R)` be a finite extension. Any finite set
-- of coefficients and structural constants arising from `L` and from generators of the relevant
-- integral closure involves only finitely many variables, so everything descends to some
-- finite-variable subring `MvPolynomial (Fin n) R`. Applying the supplied finite-variable `N-2`
-- hypothesis there and then extending scalars back to countably many variables gives the desired
-- finiteness.
private theorem countableVariableMvPolynomial_isN2Ring_of_finiteVariable
    {R : Type u} [CommRing R] [IsDomain R]
    (hfinite : ∀ n : ℕ, IsN2Ring (MvPolynomial (Fin n) R)) :
    IsN2Ring (MvPolynomial ℕ+ R) := by
  sorry

section

variable {R : Type u} [CommRing R] [IsDomain R] [IsNoetherianRing R] [IsN2Ring R]

local notation "R∞" => MvPolynomial ℕ+ R

-- Proof sketch: induct on the number of variables using the canonical equivalence between
-- `MvPolynomial (Fin (n + 1)) R` and `Polynomial (MvPolynomial (Fin n) R)`, and apply the owner
-- theorem `isN2Ring_polynomial` at each step.
private theorem finiteVariableMvPolynomial_isN2Ring (n : ℕ) :
    IsN2Ring (MvPolynomial (Fin n) R) := by
  sorry

private theorem countableVariableMvPolynomial_isN2Ring_and_not_isNoetherian :
    IsN2Ring R∞ ∧ ¬ IsNoetherianRing R∞ := by
  exact ⟨countableVariableMvPolynomial_isN2Ring_of_finiteVariable
      finiteVariableMvPolynomial_isN2Ring,
    mvPolynomial_not_isNoetherianRing_of_infinite ℕ+ R⟩

end

section

variable (k : Type u) [Field k]

local notation "Rinf" => MvPolynomial ℕ+ k

-- Proof sketch: write any finite extension of `FractionRing Rinf` over a finitely generated
-- subfield `L₀ / k(x₁, …, xₙ)`, use the finite-variable case for the integral closure over
-- `k[x₁, …, xₙ]`, and then adjoin the remaining transcendental variables. For non-Noetherianity,
-- use the generic infinite-variable lemma based on the owner ideal `MvPolynomial.idealOfVars`.
/-- Example 10.161.2: for a field `k`, the polynomial ring `k[x₁, x₂, x₃, \ldots]`, modeled as
`MvPolynomial ℕ+ k`, is `N-2` and is not Noetherian. -/
theorem countableVariablePolynomialRing_isN2Ring_and_not_isNoetherian :
    IsN2Ring Rinf ∧ ¬ IsNoetherianRing Rinf := by
  exact countableVariableMvPolynomial_isN2Ring_and_not_isNoetherian

end

section

local notation "Zinf" => MvPolynomial ℕ+ ℤ

-- Proof sketch: repeat the argument of the field case, using the finite-variable Nagata property
-- for `ℤ[x₁, …, xₙ]` in place of the field case. For non-Noetherianity, reuse the generic
-- infinite-variable lemma coming from `MvPolynomial.idealOfVars`.
/-- The same countable-variable polynomial-ring example over `ℤ` is `N-2` and not Noetherian. -/
theorem countableVariableIntegerPolynomialRing_isN2Ring_and_not_isNoetherian :
    IsN2Ring Zinf ∧ ¬ IsNoetherianRing Zinf := by
  haveI : IsN2Ring ℤ := by
    sorry
  exact countableVariableMvPolynomial_isN2Ring_and_not_isNoetherian

end
