import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open MvPolynomial

universe u

noncomputable section

section

variable (k : Type u) [Field k]

/- Domain triage:
* primary domain: commutative-algebra counterexamples built from quotient polynomial rings and
  their maximal-ideal residue fields;
* source-facing: the relations `f(x) x_f - 1`, the ideal they generate, the quotient ring, and the
  existence of a maximal ideal with residue field `k(x)`;
* core/canonical owners: `Ideal.span`, quotient-algebra instances, `MaximalSpectrum`,
  `IsFractionRing`, and `FractionRing.algEquiv`;
* bridge/view: the quotient inherits its `Polynomial k`-algebra structure from the ambient
  `MvPolynomial` ring, so there is no separate quotient-specific owner API here.
-/

local notation "NonzeroPoly" => {f : Polynomial k // f ≠ 0}
local notation "Vars" => Option NonzeroPoly
local notation "Rcount" => MvPolynomial Vars k
local notation "xVar" => (X (none : Vars) : Rcount)

/-- The defining relations `f(x) x_f - 1` in the countable-field counterexample to the
Jacobson-ring argument. -/
def countableFieldCounterexampleRelations : Set Rcount :=
  Set.range fun f : NonzeroPoly ↦
    ((Polynomial.aeval xVar f.1 : Rcount) * X (some f) - 1 : Rcount)

/-- The ideal generated by the relations `f(x) x_f - 1` in the polynomial ring
`k[x, {x_f}_{f ≠ 0}]`. -/
def countableFieldCounterexampleIdeal : Ideal Rcount :=
  Ideal.span (countableFieldCounterexampleRelations k)

/-- The quotient ring `k[x, {x_f}_{f ≠ 0}] / (f(x) x_f - 1)` from Example 10.35.13. -/
abbrev countableFieldCounterexampleRing : Type u :=
  Rcount ⧸ countableFieldCounterexampleIdeal k

local notation "Scount" => countableFieldCounterexampleRing k

private noncomputable instance : Algebra (Polynomial k) Rcount :=
  (Polynomial.aeval xVar).toRingHom.toAlgebra

/-- The defining relations are indexed by the nonzero polynomials of `k[x]`, so they form a
countable set when `k` is countable. -/
-- Proof sketch: `Polynomial k` is countable when `k` is countable, hence the subtype of nonzero
-- polynomials is countable; the image of a countable set under the indexing map is countable.
theorem countableFieldCounterexampleRelations_countable [Countable k] :
    (countableFieldCounterexampleRelations k).Countable := sorry

/-- The relation ideal in the countable-field example is proper. -/
-- Proof sketch: compose the inclusion `k[x] ↪ k(x)` with the map sending each variable `x_f` to
-- the inverse of `f(x)` in `RatFunc k`; every generator `f(x) x_f - 1` maps to zero, so the ideal
-- lies in the kernel of a homomorphism to the nontrivial ring `RatFunc k`.
private theorem countableFieldCounterexampleIdeal_ne_top :
    countableFieldCounterexampleIdeal k ≠ ⊤ := sorry

/-- Any maximal ideal of the quotient counterexample ring has residue field equal to a fraction
field of `k[x]`. -/
-- Proof sketch: in the quotient ring every relation `f(x) x_f = 1` already holds, so for any
-- maximal ideal of that quotient, every nonzero polynomial in the image of `x` remains invertible
-- in the residue field. Hence the induced map `k[x] → m.asIdeal.ResidueField` exhibits that
-- residue field as a fraction field of `k[x]`.
private noncomputable instance (m : MaximalSpectrum Scount) :
    IsFractionRing (Polynomial k) m.asIdeal.ResidueField := sorry

/-- For any maximal ideal of the quotient counterexample ring, the residue-field extension is not
algebraic over `k`. -/
-- Proof sketch: transport the transcendence of `RatFunc.X` over `k` across
-- the induced `k`-algebra equivalence `RatFunc k ≃ₐ[k] m.ResidueField`.
private theorem not_isAlgebraic_residueField_countableFieldCounterexampleQuotient
    (m : MaximalSpectrum Scount) :
    ¬ Algebra.IsAlgebraic k m.asIdeal.ResidueField := sorry

/-- Example 10.35.13: for a countable field `k`, the defining relations `f(x) x_f - 1` form a
countable set in `k[x, {x_f}_{f ∈ k[x] - {0}}]`, and the quotient ring by the ideal they generate
has a maximal ideal whose residue field is `k`-isomorphic to `k(x)`, hence not algebraic over
`k`. -/
-- Proof sketch: the relation ideal is proper, so the quotient ring is nontrivial and therefore
-- has a maximal ideal `m`. The private fraction-field instance above puts the owner object
-- `m.asIdeal.ResidueField` in the canonical `IsFractionRing (Polynomial k)` interface, so
-- `FractionRing.algEquiv` gives the required `k`-algebra isomorphism with `RatFunc k`; the final
-- conclusion follows from
-- `not_isAlgebraic_residueField_countableFieldCounterexampleQuotient`.
theorem exists_maximal_ideal_with_ratFunc_residueField_over_countable_field [Countable k] :
    (countableFieldCounterexampleRelations k).Countable ∧
      ∃ m : MaximalSpectrum Scount,
        ∃ e : RatFunc k ≃ₐ[k] m.asIdeal.ResidueField,
          ¬ Algebra.IsAlgebraic k m.asIdeal.ResidueField := sorry

end
