import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

universe u v

section

variable {R : Type u} [CommRing R]
variable (I : Ideal R)
variable (M : Type v) [AddCommGroup M] [Module R M]

/- Lemma 10.96.3 (1): for a finitely generated ideal `I`, the `I`-adic completion `AdicCompletion I M`
is `I`-adically complete. -/
recall AdicCompletion.isAdicComplete

/- Lemma 10.96.3 (2): for every positive integer `n`, the kernel of the canonical map
`AdicCompletion I M → M ⧸ (I ^ n • ⊤)` is exactly `I ^ n` times the completed module. -/
recall AdicCompletion.pow_smul_top_eq_ker_eval

/- Companion bridge: the canonical map `AdicCompletion.ofPowSMul` from the completion of `I ^ n M`
into the completion of `M` has image equal to the kernel of the evaluation map. -/
recall AdicCompletion.restrictScalars_range_ofPowSMul_eq_ker_eval

end

section

variable {R : Type u} [CommRing R]
variable (I : Ideal R)

-- Proof sketch: compare the ring-theoretic map `AdicCompletion.evalₐ I n` with the module map
-- `AdicCompletion.eval I R n`, then translate the kernel description from the module theorem into
-- an equality of ideals in `AdicCompletion I R`.
/-- For every `n : ℕ`, the ideal generated by `I ^ n` in the completed ring is the kernel of the
canonical map `AdicCompletion I R → R ⧸ I ^ n`. -/
theorem completionIdeal_pow_eq_ker_evalₐ (hI : I.FG) (n : ℕ) :
    Ideal.map (algebraMap R (AdicCompletion I R)) (I ^ n) =
      RingHom.ker (AdicCompletion.evalₐ I n) := sorry

end
