import Mathlib
import stacks_project.Chap04.Definition_4_6_4
import stacks_project.Chap07.Definition_7_8_1
import stacks_project.Chap07.Definition_7_8_2

-- Declarations for this item will be appended below by the statement pipeline.

universe w v u

namespace CategoryTheory

open Limits
open Equalizer.Presieve.Arrows

variable {C : Type u} [Category.{v} C]

namespace SemiRepresentableFamily
namespace Over

open CategoryTheory.Over (pullbackId)

variable {U : C}

/- Domain-style sampling for Definition 7.12.1:
- primary domain: effective epimorphic families in slice categories, expressed through the owner
  `SemiRepresentableFamily.Over U` and the canonical presieve generated by such a family;
- sampled owner declarations:
  `SemiRepresentableFamily.Over`,
  `SemiRepresentableFamily.Over.toPresieve`,
  `Presieve.EffectiveEpimorphic`,
  `(𝟭 C).relativelyRepresentable`;
- best owner abstraction:
  the source-facing owner remains `SemiRepresentableFamily.Over U`, while the canonical
  foundational notions are the generated-presieve owner `K.toPresieve.EffectiveEpimorphic` and
  the componentwise morphism property `(𝟭 C).relativelyRepresentable`;
- primitive-vs-derived split:
  primitive data: a fixed-target family `K : Over U`;
  derived API: effective-epimorphicity of the generated presieve, the induced
  `EffectiveEpiFamily` instance, pullback existence along each component, the Yoneda equalizer
  criterion, and the universal base-change stability predicate;
- source/core/bridge triage:
  `source-facing`: `IsEffectiveEpimorphism`, `IsUniversalEffectiveEpimorphism`;
  `core/canonical`: `K.toPresieve.EffectiveEpimorphic`, `(𝟭 C).relativelyRepresentable`;
  `bridge/view`: `baseChange`, which keeps only the pullbacks of the listed family members and so
  is more general than the ambient owner `Over.pullback f`, which would require
  `HasPullbacksAlong f`; under that stronger owner hypothesis, the companion bridge theorem
  `baseChange_eq_map_pullback` identifies it with `SemiRepresentableFamily.map
  (CategoryTheory.Over.pullback f)`. -/

/-- The componentwise slice pullback of a fixed-target family along a morphism `f : V ⟶ U`. -/
noncomputable abbrev baseChange (K : Over U) {V : C} (f : V ⟶ U)
    [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] : Over V :=
  ofArrows
    (fun i : K.index ↦ Limits.pullback (K.obj i).hom f)
    (fun i ↦ Limits.pullback.snd (K.obj i).hom f)

/-- The `i`th component of `baseChange K f` is the pullback object over the new target. -/
@[simp] theorem baseChange_obj_hom (K : Over U) {V : C} (f : V ⟶ U)
    [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] (i : K.index) :
    ((baseChange K f).obj i).hom = Limits.pullback.snd (K.obj i).hom f := rfl

private instance hasPullback_of_hasPullbacksAlong
    (K : Over U) {V : C} (f : V ⟶ U) [Limits.HasPullbacksAlong f] (i : K.index) :
    Limits.HasPullback (K.obj i).hom f :=
  (inferInstance : Limits.HasPullbacksAlong f) (K.obj i).hom

attribute [instance 100] hasPullback_of_hasPullbacksAlong

/-- Under the stronger owner hypothesis that pullback along `f` exists globally in the slice,
`baseChange K f` is exactly the componentwise application of the canonical slice pullback functor
to the family `K`. -/
@[simp] theorem baseChange_eq_map_pullback (K : Over U) {V : C} (f : V ⟶ U)
    [Limits.HasPullbacksAlong f] :
    baseChange K f = (SemiRepresentableFamily.map (CategoryTheory.Over.pullback f)).obj K := by
  let _ : ∀ i : K.index, Limits.HasPullback (K.obj i).hom f := fun i ↦
    (inferInstance : Limits.HasPullbacksAlong f) (K.obj i).hom
  rfl

/-- Definition 7.12.1 (1): a fixed-target family is an effective epimorphism when each component
arrow is representable and the presieve generated by the family is effective epimorphic. By
`Presieve.EffectiveEpimorphic.iff_forall_isSheafFor_yoneda` and
`Equalizer.Presieve.Arrows.sheaf_condition`, this is equivalent to the textbook equalizer
condition on representable presheaves. -/
class IsEffectiveEpimorphism (K : Over U) : Prop where
  /-- Every component arrow of the family is representable. -/
  representable (i : K.index) : (𝟭 C).relativelyRepresentable (K.obj i).hom
  /-- The canonical presieve generated by the family is effective epimorphic. -/
  effectiveEpimorphic : K.toPresieve.EffectiveEpimorphic

instance (K : Over U) [hK : IsEffectiveEpimorphism K] :
    EffectiveEpiFamily (fun i : K.index ↦ (K.obj i).left) (fun i ↦ (K.obj i).hom) :=
  (Sieve.effectiveEpimorphic_family
      (fun i : K.index ↦ (K.obj i).left)
      (fun i : K.index ↦ (K.obj i).hom)).mp
    hK.effectiveEpimorphic

private theorem toPresieveHasPairwisePullbacks (K : Over U)
    (hK : ∀ i : K.index, Limits.HasPullbacksAlong (K.obj i).hom) :
    K.toPresieve.HasPairwisePullbacks where
  has_pullbacks := by
    intro Y Z f hf g hg
    obtain ⟨i, hi, rfl⟩ :=
      Presieve.ofArrows_surj (fun i : K.index ↦ (K.obj i).hom) f hf
    obtain ⟨j, hj, rfl⟩ :=
      Presieve.ofArrows_surj (fun i : K.index ↦ (K.obj i).hom) g hg
    subst hi
    subst hj
    simpa using hK j (K.obj i).hom

instance (K : Over U) [hK : IsEffectiveEpimorphism K] (i : K.index) :
    Limits.HasPullbacksAlong (K.obj i).hom :=
  (relativelyRepresentable_iff_hasPullbacksAlong _).mp (hK.representable i)

private theorem hasPullback_of_representable {V W : C} (f : V ⟶ U) {g : W ⟶ U}
    (hg : (𝟭 C).relativelyRepresentable g) : Limits.HasPullback g f := by
  haveI : Limits.HasPullback f g := (relativelyRepresentable_iff_hasPullbacksAlong _).mp hg f
  exact Limits.hasPullback_symmetry f g

instance (K : Over U) [hK : IsEffectiveEpimorphism K] {V : C} (f : V ⟶ U) (i : K.index) :
    Limits.HasPullback (K.obj i).hom f :=
  hasPullback_of_representable f (hK.representable i)

instance (K : Over U) [hK : IsEffectiveEpimorphism K] :
    K.toPresieve.HasPairwisePullbacks :=
  toPresieveHasPairwisePullbacks K fun i ↦
    (inferInstance : Limits.HasPullbacksAlong (K.obj i).hom)

private instance ofArrowsHasPairwisePullbacks (K : Over U) [IsEffectiveEpimorphism K] :
    (Presieve.ofArrows (fun i : K.index ↦ (K.obj i).left)
      fun i ↦ (K.obj i).hom).HasPairwisePullbacks := by
  simpa [toPresieve] using (inferInstance : K.toPresieve.HasPairwisePullbacks)

/-- The textbook equalizer fork on `Hom_{\mathcal C}(-, X)` attached to an effective epimorphism
family `K`. -/
noncomputable abbrev yonedaEqualizerFork
    (K : Over U) [IsEffectiveEpimorphism K] (X : C) :
    Fork
      (firstMap (yoneda.obj X)
        (fun i : K.index ↦ (K.obj i).left)
        (fun i ↦ (K.obj i).hom))
      (secondMap (yoneda.obj X)
        (fun i : K.index ↦ (K.obj i).left)
        (fun i ↦ (K.obj i).hom)) :=
  Limits.Fork.ofι
    (forkMap (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom))
    (w (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom))

-- Proof sketch: apply `sheaf_condition` to the representable presheaf
-- `yoneda.obj X` and the presieve generated by the component arrows of `K`; the pairwise pullbacks
-- come from the representability of the component arrows.
private theorem isEffectiveEpimorphism_yoneda_equalizer_nonempty (K : Over U)
    [hK : IsEffectiveEpimorphism K] (X : C) :
    Nonempty (Limits.IsLimit (yonedaEqualizerFork K X)) := by
  have hSheaf : K.toPresieve.IsSheafFor (yoneda.obj X) :=
    Presieve.EffectiveEpimorphic.isSheafFor_of_isRepresentable
      hK.effectiveEpimorphic (yoneda.obj X)
  simpa [toPresieve] using
    (sheaf_condition
      (yoneda.obj X)
      (fun i : K.index ↦ (K.obj i).left)
      (fun i ↦ (K.obj i).hom)).mp hSheaf

/-- An effective epimorphism family satisfies the textbook equalizer diagram on
`Hom_{\mathcal C}(-, X)` for every object `X`. -/
noncomputable def IsEffectiveEpimorphism.yonedaEqualizerIsLimit (K : Over U)
    [IsEffectiveEpimorphism K] (X : C) :
    Limits.IsLimit (yonedaEqualizerFork K X) :=
  (isEffectiveEpimorphism_yoneda_equalizer_nonempty K X).some

private instance hasPullbacksAlong_id : Limits.HasPullbacksAlong (𝟙 U) := by
  intro W g
  exact (IsPullback.id_horiz g).hasPullback

private noncomputable abbrev baseChangeIdIso (K : Over U) : baseChange K (𝟙 U) ≅ K where
  hom :=
    { α := fun i ↦ i
      f := fun i ↦ pullbackId.hom.app (K.obj i) }
  inv :=
    { α := fun i ↦ i
      f := fun i ↦ pullbackId.inv.app (K.obj i) }
  hom_inv_id := by
    refine SemiRepresentableFamily.Hom.ext (by funext i; rfl) ?_
    intro i
    exact heq_of_eq (by simpa using Iso.hom_inv_id_app pullbackId (K.obj i))
  inv_hom_id := by
    refine SemiRepresentableFamily.Hom.ext (by funext i; rfl) ?_
    intro i
    exact heq_of_eq (by simpa using Iso.inv_hom_id_app pullbackId (K.obj i))

private theorem isIso_baseChangeIdIso_hom_left (K : Over U) (i : K.index) :
    IsIso (((baseChangeIdIso K).hom.f i).left) := by
  change IsIso ((pullbackId.hom.app (K.obj i)).left)
  haveI : IsIso (pullbackId.hom.app (K.obj i)) :=
    ((NatTrans.isIso_iff_isIso_app pullbackId.hom).mp inferInstance) (K.obj i)
  infer_instance

private theorem isEffectiveEpimorphism_of_baseChangeId (K : Over U)
    (hK : IsEffectiveEpimorphism (baseChange K (𝟙 U))) :
    IsEffectiveEpimorphism K where
  representable i := by
    letI : IsEffectiveEpimorphism (baseChange K (𝟙 U)) := hK
    let g := (baseChangeIdIso K).hom.f i
    haveI : IsIso g.left := by
      simpa [g] using isIso_baseChangeIdIso_hom_left K i
    exact
      (((𝟭 C).relativelyRepresentable).cancel_left_of_respectsIso g.left
        ((K.obj i).hom)).mp <| by
        rw [show g.left ≫ (K.obj i).hom = ((baseChange K (𝟙 U)).obj i).hom from Over.w g]
        exact hK.representable i
  effectiveEpimorphic := by
    letI : IsEffectiveEpimorphism (baseChange K (𝟙 U)) := hK
    let φ := (baseChangeIdIso K).hom
    let g : (i : K.index) → ((baseChange K (𝟙 U)).obj i).left ⟶ (K.obj i).left :=
      fun i ↦ (φ.f i).left
    have hcomp :
        (fun i ↦ g i ≫ (K.obj i).hom) = fun i ↦ ((baseChange K (𝟙 U)).obj i).hom :=
      funext fun i ↦ Over.w (φ.f i)
    have hEffective :
        EffectiveEpiFamily
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
          (fun i ↦ g i ≫ (K.obj i).hom) := by
      convert
        (Sieve.effectiveEpimorphic_family
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).left)
          (fun i : K.index ↦ ((baseChange K (𝟙 U)).obj i).hom)).mp hK.effectiveEpimorphic using 1
    have : EffectiveEpiFamily (fun i : K.index ↦ (K.obj i).left) (fun i ↦ (K.obj i).hom) :=
      @effectiveEpiFamily_of_effectiveEpi_epi_comp _ _ _ _ _ _
        (fun i ↦ (K.obj i).hom) g
        (fun i ↦ by
          change Epi ((φ.f i).left)
          haveI : IsIso ((φ.f i).left) := by
            simpa [φ] using isIso_baseChangeIdIso_hom_left K i
          infer_instance)
        hEffective
    simpa [toPresieve] using
      (Sieve.effectiveEpimorphic_family
        (fun i : K.index ↦ (K.obj i).left)
        (fun i : K.index ↦ (K.obj i).hom)).mpr this

/-- Definition 7.12.1 (2): a fixed-target family is a universal effective epimorphism when every
base change of the family is again an effective epimorphism. -/
class IsUniversalEffectiveEpimorphism (K : Over U) : Prop where
  /-- Pulling back the family along any morphism into the target yields another effective
  epimorphism family. -/
  effective_baseChange {V : C} (f : V ⟶ U)
      [∀ i : K.index, Limits.HasPullback (K.obj i).hom f] :
      IsEffectiveEpimorphism (baseChange K f)

theorem IsUniversalEffectiveEpimorphism.representable {K : Over U}
    (hK : IsUniversalEffectiveEpimorphism K) (i : K.index) :
    (𝟭 C).relativelyRepresentable (K.obj i).hom :=
  (isEffectiveEpimorphism_of_baseChangeId K (hK.effective_baseChange (𝟙 U))).representable i

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] {V : C} (f : V ⟶ U)
    (i : K.index) : Limits.HasPullback (K.obj i).hom f :=
  hasPullback_of_representable f (hK.representable i)

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] :
    IsEffectiveEpimorphism K :=
  isEffectiveEpimorphism_of_baseChangeId K (hK.effective_baseChange (𝟙 U))

instance (K : Over U) [hK : IsUniversalEffectiveEpimorphism K] {V : C} (f : V ⟶ U) :
    IsEffectiveEpimorphism (baseChange K f) :=
  hK.effective_baseChange f

end Over
end SemiRepresentableFamily

end CategoryTheory
