import Mathlib
import stacks_project.Chap07.Lemma_7_29_4

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open CategoryTheory.Limits
open Opposite
open Functor.IsDenseSubsite
open scoped CategoryTheory.GrothendieckTopology.SheafifiedRepresentable

noncomputable section

universe u v uI

namespace CategoryTheory

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)
variable [HasWeakSheafify J (Type (max u v))]
variable {I : Type uI} (ℱ : I → Sheaf J (Type (max u v)))

/- Domain-style sampling for Lemma 7.29.5:
- primary domain: replacement-site presentations of a sheaf topos through full subcategories of
  sheaves, equipped with the canonical surjective topology from Lemma `7.29.4`;
- sampled owner declarations:
  `ObjectProperty.FullSubcategory`,
  `ObjectProperty.IsClosedUnderSubobjects`,
  `ObjectProperty.sheafSubcategorySurjectiveTopology`,
  `ObjectProperty.sheafSubcategoryRepresentableFunctor`,
  `Presheaf.IsLocallySurjective`,
  `Functor.IsDenseSubsite`,
  `Functor.IsDenseSubsite.sheafEquiv`;
- best owner abstraction: the source-facing statement should expose the replacement site
  `(C', J')`, its dense-subsite comparison functor `v : C ⥤ C'`, and the canonical dense-subsite
  sheaf equivalence `sheafEquiv J J' v`; the internal `ObjectProperty` full-subcategory
  presentation from Lemma `7.29.4` is only the construction layer producing that site;
- primitive data: the replacement category `C'`, its topology `J'`, finite limits on `C'`, and the
  comparison functor `v`;
- derived API: subcanonicality of `J'`, the dense-subsite owner on `v`, the induced sheaf
  equivalence `sheafEquiv J J' v`, and the owner-level representability predicates on every
  subsheaf of a representable sheaf on the replacement site and on the transported family.

Source/core/bridge triage:
- `source-facing`: the replacement site with its canonical surjective topology, together with the
  special-cocontinuous comparison and the fact that the chosen family becomes representable there;
- `core/canonical`: `Functor.IsDenseSubsite`, `sheafEquiv`, and the site-level owners
  `GrothendieckTopology.Subcanonical` and `HasFiniteLimits`;
- `bridge/view`: the internal `ObjectProperty` full-subcategory construction from Lemma `7.29.4`,
  used only to build the replacement site realizing the theorem.
-/

-- Proof sketch: build the replacement site from the full subcategory of `Sh(J)` generated by the
-- sheafified representables and the chosen family, closed under fibre products and subobjects.
-- Lemma `7.29.4` equips that full subcategory with its canonical surjective topology, whose
-- covering families are exactly the family presentations whose induced coproduct map of
-- representable presheaves is locally surjective. We then state only the resulting replacement
-- site `(C', J')`, the dense-subsite functor `v : C ⥤ C'`, this covering characterization, and
-- the canonical representability consequences.
/-- Lemma 7.29.5: every set-indexed family of sheaves on `Sh(J)` admits a replacement site
`(C', J')` with finite limits and subcanonical topology, together with a dense-subsite comparison
functor `v : C ⥤ C'`, such that a family on `C'` is covering exactly when the induced coproduct
map of representable presheaves is locally surjective, every subsheaf of a representable sheaf on
the replacement site has representable underlying presheaf, and, under the canonical
dense-subsite equivalence `sheafEquiv J J' v`, each sheaf `ℱ i` has representable underlying
presheaf on the replacement site. The construction is realized internally by the full-subcategory
presentation of Lemma `7.29.4`, but that construction layer is not part of the public API here. -/
theorem exists_representable_family_site_presentation :
    ∃ (C' : Type (max u v)) (_ : Category C') (J' : GrothendieckTopology C')
      (_ : J'.Subcanonical) (_ : HasFiniteLimits C')
      (v : C ⥤ C') (_ : v.IsDenseSubsite J J')
      (hcover :
        ∀ ⦃X : C'⦄ (R : Presieve X),
        R ∈ J'.toPrecoverage X ↔
          ∃ (ι : Type (max u v)) (Y : ι → C') (π : ∀ i, Y i ⟶ X),
            R = Presieve.ofArrows Y π ∧
              Presheaf.IsLocallySurjective J'
                (Limits.Sigma.desc (fun i ↦ (J'.yoneda.map (π i)).hom)))
      (hsub :
        ∀ X : C', ∀ G : Subobject (J'.yoneda.obj X),
          ((G : Sheaf J' (Type (max u v))).obj).IsRepresentable),
      ∀ i : I,
        (((sheafEquiv J J' v (Type (max u v))).functor.obj (ℱ i)).obj).IsRepresentable := sorry

end CategoryTheory
