import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open scoped BigOperators
open Polynomial

noncomputable section

universe u

section

variable {A : Type u} [CommRing A]
variable {p : ℕ}

local notation "R₂" => MvPolynomial (Fin 2) A
local notation "X0" => (MvPolynomial.X (0 : Fin 2) : R₂)
local notation "X1" => (MvPolynomial.X (1 : Fin 2) : R₂)

/- Domain-style sampling:
* primary domain: source-facing quotient-polynomial identities attached to a primitive `p`th root
  of unity and its distinguished coefficient `1 - ζ`;
* sampled owner declarations:
  `IsPrimitiveRoot`,
  `Ideal.IsGabberHenselPolynomial`,
  `uniformizerRootPolynomial`,
  `RingHom.ShiftPowerPolynomialImageGenerating`;
* best owner abstraction: a source-facing predicate on the quotient polynomial `P` attached to
  `ζ`, with the distinguished coefficient kept as the canonical term `1 - ζ` rather than as a
  second primitive parameter;
* primitive data: coefficient witnesses `a i`, the displayed polynomial shape, and the quotient
  identity written with `1 - ζ`;
* derived API: coefficient/quotient projection lemmas, existence under `IsPrimitiveRoot ζ p`, and
  the additive identity derived from the quotient equation alone.

Layer triage:
* `source-facing`: the quotient polynomial attached to `ζ` and its source-form polynomial
  identities, since no chapter/project owner already packages this notion;
* `bridge/view`: the existence theorem specialized by `IsPrimitiveRoot ζ p`, and the additive
  identity derived from the quotient equation.
-/

/-- The quotient polynomial `P` from Lemma `15.116.13` attached to `ζ`, where the distinguished
coefficient is canonically `1 - ζ` and the intermediate coefficients lie in the principal ideal
generated by `1 - ζ`. -/
def IsOneSubZetaQuotientPolynomial (p : ℕ) (ζ : A) (P : A[X]) : Prop :=
  ∃ a : ℕ → A,
    (∀ i, 0 < i → i < p → a i ∈ Ideal.span ({1 - ζ} : Set A)) ∧
      P = X ^ p - X + ∑ i ∈ Finset.Icc 1 (p - 1), C (a i) * X ^ i ∧
      C ((1 - ζ) ^ p) * P = (C (1 : A) + C (1 - ζ) * X) ^ p - 1

namespace IsOneSubZetaQuotientPolynomial

theorem exists_coefficients {ζ : A} {P : A[X]} (hP : IsOneSubZetaQuotientPolynomial p ζ P) :
    ∃ a : ℕ → A,
      (∀ i, 0 < i → i < p → a i ∈ Ideal.span ({1 - ζ} : Set A)) ∧
        P = X ^ p - X + ∑ i ∈ Finset.Icc 1 (p - 1), C (a i) * X ^ i ∧
        C ((1 - ζ) ^ p) * P = (C (1 : A) + C (1 - ζ) * X) ^ p - 1 :=
  hP

theorem eq_polynomial {ζ : A} {P : A[X]} (hP : IsOneSubZetaQuotientPolynomial p ζ P) :
    ∃ a : ℕ → A, P = X ^ p - X + ∑ i ∈ Finset.Icc 1 (p - 1), C (a i) * X ^ i := by
  rcases hP.exists_coefficients with ⟨a, -, hshape, -⟩
  exact ⟨a, hshape⟩

theorem quotient_eq {ζ : A} {P : A[X]} (hP : IsOneSubZetaQuotientPolynomial p ζ P) :
    C ((1 - ζ) ^ p) * P = (C (1 : A) + C (1 - ζ) * X) ^ p - 1 := by
  rcases hP.exists_coefficients with ⟨_, _, _, hquot⟩
  exact hquot

end IsOneSubZetaQuotientPolynomial

-- Proof sketch: set `w = 1 - ζ`, expand `(1 + w X)^p` by the binomial theorem, use that `ζ` is a
-- primitive `p`th root of unity to show the numerator is divisible by `w^p`, and record the
-- remaining coefficients as elements of the ideal generated by `w`.
/-- Lemma 15.116.13 (1): if `A` contains a primitive `p`th root of unity `ζ`, then there is a
polynomial `P ∈ A[z]` representing `((1 + (1 - ζ) z)^p - 1) / (1 - ζ)^p`, and the intermediate
coefficients of `P` lie in the ideal `(1 - ζ)`. -/
theorem exists_oneSubZetaQuotientPolynomial
    [Fact p.Prime]
    {ζ : A}
    (hζ : IsPrimitiveRoot ζ p) :
    ∃ P : A[X], IsOneSubZetaQuotientPolynomial p ζ P := sorry

/-- Lemma 15.116.13 (2), core quotient form: any polynomial satisfying the quotient identity
`w^p P(z) = (1 + wz)^p - 1` also satisfies the two-variable additive formula. -/
theorem oneSubZetaQuotientPolynomial_add_formula
    {w : A}
    {P : A[X]}
    (hquot : C (w ^ p) * P = (C (1 : A) + C w * X) ^ p - 1) :
    (Polynomial.aeval (X0 + X1 + MvPolynomial.C w * X0 * X1) P : R₂) =
      Polynomial.aeval X0 P + Polynomial.aeval X1 P +
        MvPolynomial.C (w ^ p) * Polynomial.aeval X0 P * Polynomial.aeval X1 P := sorry

-- Proof sketch: use the quotient identity recorded in `hP`, written with the distinguished
-- element `w = 1 - ζ`, and compare the two ways of rewriting
-- `(1 + w (z₁ + z₂ + w z₁ z₂))^p - 1` in the two-variable polynomial ring `A[z₁, z₂]`.
/-- Lemma 15.116.13 (2): if `P` is the quotient polynomial from part `(1)`, then
`P(z₁ + z₂ + (1 - ζ) z₁ z₂) = P(z₁) + P(z₂) + (1 - ζ)^p P(z₁) P(z₂)` in `A[z₁, z₂]`. -/
theorem IsOneSubZetaQuotientPolynomial.add_formula
    {ζ : A}
    {P : A[X]}
    (hP : IsOneSubZetaQuotientPolynomial p ζ P) :
    (Polynomial.aeval (X0 + X1 + MvPolynomial.C (1 - ζ) * X0 * X1) P : R₂) =
      Polynomial.aeval X0 P + Polynomial.aeval X1 P +
        MvPolynomial.C ((1 - ζ) ^ p) * Polynomial.aeval X0 P * Polynomial.aeval X1 P := by
  exact oneSubZetaQuotientPolynomial_add_formula hP.quotient_eq

end
