import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Lemma_16_9_2 (from Chap16) -/
universe u v w

namespace Algebra

open scoped Algebra

section

variable {R : Type u} {A : Type v} {Λ : Type w}
variable [CommRing R] [CommRing A] [CommRing Λ]
variable [Algebra R A] [Algebra R Λ] [Algebra A Λ] [IsScalarTower R A Λ]
variable {r : ℕ} (π : Fin r → R)

/-
Domain-style sampling for Lemma 16.9.2:
- primary domain: commutative algebra of finitely presented resolution factorizations, singular
  ideals, and reduction modulo the ideal generated by the eighth powers of a finite family;
- sampled owner declarations:
  `Ideal.torsionOf`,
  `RingHom.singularIdealIn`,
  `ResolvableAtPrime`,
  `Algebra.IsStrictlyStandard`,
  `Ideal.Quotient.algebraQuotientOfLEComap`,
  `Ideal.isPrime_map_quotientMk_of_isPrime`;
- best owner abstraction: the source-facing owner is `ResolvableAtPrime`, while the successive
  quotient torsion hypotheses should be stated through the chapter's canonical owner
  `Ideal.torsionOf`; the reduction data should stay as the canonical quotient ideal/image-of-prime
  constructions instead of parallel wrapper APIs;
- primitive data: the finitely presented factorization `A → B → Λ`, the singular-ideal
  containment/noncontainment conditions, the successive quotient torsion equalities for the family
  `π`, and the quotient ideal generated by the family `π i ^ 8`;
- derived API: the reduced prime `q / I8 Λ`, the quotient algebra structures on
  `R / I8`, `A / I8 A`, `Λ / I8 Λ`, and the reduction step in the main theorem.

Source/core/bridge triage:
- `source-facing`: `ResolvableAtPrime` and the lifting theorem
  `resolvableAtPrime_of_resolvableAtPrime_mod_piPowEight_family`;
- `core/canonical`: `Ideal.torsionOf`, `RingHom.singularIdealIn`,
  `Ideal.Quotient.algebraQuotientOfLEComap`, `Ideal.isPrime_map_quotientMk_of_isPrime`, and
  `IsStrictlyStandard`;
- `bridge/view`: the quotient ideal `piPowEightReductionIdeal π` and the image prime
  `piPowEightReductionPrime π q`.
-/

/-- A global resolution of `R → A → Λ ⊃ q` is a finitely presented `R`-algebra factorization
`A → B → Λ` whose target singular ideal contains `𝔥_A` and is not contained in `q`. -/
def ResolvableAtPrime (R : Type u) (A : Type v) (Λ : Type w)
    [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [Algebra A Λ] [IsScalarTower R A Λ]
    (q : Ideal Λ) : Prop :=
  ∃ (B : Type (max u v w)) (_ : CommRing B) (_ : Algebra R B) (_ : FinitePresentation R B)
    (f : A →ₐ[R] B) (g : B →ₐ[R] Λ),
    g.comp f = IsScalarTower.toAlgHom R A Λ ∧
      h(A⁄R, Λ) ≤ g.singularIdealIn R ∧
      ¬ g.singularIdealIn R ≤ q

-- Proof sketch: this is just the definition of `ResolvableAtPrime`, unpacking the existence of
-- a finitely presented factorization `A → B → Λ` and the two singular-ideal conditions.
/-- Unfolding `ResolvableAtPrime q` gives a finitely presented factorization `A → B → Λ` whose
target singular ideal contains `𝔥_A` and is not contained in `q`. -/
theorem resolvableAtPrime_iff (q : Ideal Λ) :
    ResolvableAtPrime R A Λ q ↔
      ∃ (B : Type (max u v w)) (_ : CommRing B) (_ : Algebra R B) (_ : FinitePresentation R B)
        (f : A →ₐ[R] B) (g : B →ₐ[R] Λ),
        g.comp f = IsScalarTower.toAlgHom R A Λ ∧
          h(A⁄R, Λ) ≤ g.singularIdealIn R ∧
          ¬ g.singularIdealIn R ≤ q :=
  Iff.rfl

/-- The ideal generated by the eighth powers of the first `n` elements of the family `π`. -/
def piPowEightPrefixIdeal (n : ℕ) (hn : n ≤ r) : Ideal R :=
  Ideal.span (Set.range fun i : Fin n ↦ π (Fin.castLE hn i) ^ 8)

-- Proof sketch: this is the defining formula of `piPowEightPrefixIdeal`.
/-- Unfolding the prefix ideal generated by the eighth powers of the family `π`. -/
theorem piPowEightPrefixIdeal_def (n : ℕ) (hn : n ≤ r) :
    piPowEightPrefixIdeal π n hn =
      Ideal.span (Set.range fun i : Fin n ↦ π (Fin.castLE hn i) ^ 8) :=
  rfl

/-- The ideal generated by the eighth powers of all `r` elements of the family `π`. -/
abbrev piPowEightReductionIdeal : Ideal R :=
  piPowEightPrefixIdeal π r le_rfl

-- Proof sketch: this is the special case `n = r` of the definition of `piPowEightPrefixIdeal`.
/-- Unfolding the final eighth-power reduction ideal attached to the family `π`. -/
theorem piPowEightReductionIdeal_def :
    piPowEightReductionIdeal π = piPowEightPrefixIdeal π r le_rfl :=
  rfl

local notation "I8" => piPowEightReductionIdeal π
local notation "R8" => R ⧸ I8
local notation "A8" => A ⧸ Ideal.map (algebraMap R A) I8
local notation "L8" => Λ ⧸ Ideal.map (algebraMap R Λ) I8

-- Proof sketch: each generator `π i ^ 8` maps into `q` because `π i` does, and ideals generated
-- by elements mapping into `q` map into `q`.
/-- If every `π i` maps into `q`, then the ideal generated by the `π i^8` maps into `q`. -/
theorem map_piPowEightReductionIdeal_le
    (q : Ideal Λ) (hπq : ∀ i : Fin r, algebraMap R Λ (π i) ∈ q) :
    Ideal.map (algebraMap R Λ) I8 ≤ q := by
  rw [piPowEightReductionIdeal_def, piPowEightPrefixIdeal_def]
  refine Ideal.map_le_iff_le_comap.2 ?_
  refine Ideal.span_le.2 ?_
  rintro _ ⟨i, rfl⟩
  simpa [Ideal.mem_comap, map_pow] using q.pow_mem_of_mem (hπq i) 8 (by decide)

/-- The quotient `A / I8 A` inherits its canonical algebra structure over `R / I8`. -/
instance : Algebra R8 A8 :=
  Ideal.Quotient.algebraQuotientOfLEComap Ideal.le_comap_map

/-- The quotient `Λ / I8 Λ` inherits its canonical algebra structure over `A / I8 A`. -/
instance : Algebra A8 L8 :=
  Ideal.Quotient.algebraQuotientOfLEComap <| by
    simpa [Ideal.map_map, IsScalarTower.algebraMap_eq R A Λ] using
      (Ideal.le_comap_map :
        Ideal.map (algebraMap R A) I8 ≤
          Ideal.comap (algebraMap A Λ)
            (Ideal.map (algebraMap A Λ) (Ideal.map (algebraMap R A) I8)))

/-- The quotient algebra structures on `R / I8`, `A / I8 A`, and `Λ / I8 Λ` form a scalar tower.
-/
instance : IsScalarTower R8 A8 L8 := by
  refine IsScalarTower.of_algebraMap_eq fun x ↦ ?_
  refine Quotient.inductionOn' x fun x ↦ ?_
  change
    Ideal.Quotient.mk (Ideal.map (algebraMap R Λ) I8) (algebraMap R Λ x) =
      Ideal.Quotient.mk (Ideal.map (algebraMap R Λ) I8) ((algebraMap A Λ) (algebraMap R A x))
  rw [IsScalarTower.algebraMap_eq R A Λ]
  rfl

/-- The image of `q` in the quotient ring `Λ / I8 Λ`. -/
abbrev piPowEightReductionPrime (q : Ideal Λ) : Ideal L8 :=
  Ideal.map (Ideal.Quotient.mk (Ideal.map (algebraMap R Λ) I8)) q

-- Proof sketch: this is the defining formula of `piPowEightReductionPrime`.
/-- Unfolding the image of `q` in the quotient `Λ / I8 Λ`. -/
theorem piPowEightReductionPrime_def (q : Ideal Λ) :
    piPowEightReductionPrime π q =
      Ideal.map (Ideal.Quotient.mk (Ideal.map (algebraMap R Λ) I8)) q :=
  rfl

-- Proof sketch: the ideal generated by the `π i^8` maps into `q`, so the image of the prime ideal
-- `q` in the quotient `Λ / I8 Λ` is again prime.
/-- If every `π i` maps into the prime `q`, then the induced ideal `q / I8 Λ` is prime in
`Λ / I8 Λ`. -/
theorem piPowEightReductionPrime_isPrime
    (q : Ideal Λ) [q.IsPrime] (hπq : ∀ i : Fin r, algebraMap R Λ (π i) ∈ q) :
    (piPowEightReductionPrime π q).IsPrime :=
  Ideal.isPrime_map_quotientMk_of_isPrime (map_piPowEightReductionIdeal_le π q hπq)

-- Proof sketch: argue by induction on `r`. For `r = 1`, apply Lemma `16.7.3` to lift a
-- resolution modulo `π₁^8` to a resolution upstairs, using the successive quotient torsion-ideal
-- equalities and the strict standardness of `π₁`. For the induction step, first apply the
-- induction hypothesis to the quotient by `π₁^8`; Lemma `16.2.7` preserves strict standardness
-- after passing to that quotient, so the remaining family still satisfies the same hypotheses.
/-- Lemma 16.9.2: let `R → A → Λ ⊃ q` be in the situation of the local-tricks setup, so `R` is
Noetherian and `A` is finitely presented over `R`. Let `π : Fin r → R` encode the family
`π₁, …, π_r`, assume each `π i` maps into `q`, assume the successive quotient
torsion-ideal equalities from the text, expressed canonically via `Ideal.torsionOf`, hold after
modding out by the previously chosen eighth powers, and assume each `π i` maps to a strictly
standard element of `A` over `R`. If the quotient situation modulo `(π₁^8, …, π_r^8)` is
resolvable, then the original situation is resolvable. -/
theorem resolvableAtPrime_of_resolvableAtPrime_mod_piPowEight_family
    [IsNoetherianRing R] [FinitePresentation R A]
    (q : Ideal Λ) [q.IsPrime] {r : ℕ} (π : Fin r → R)
    (hπq : ∀ i : Fin r, algebraMap R Λ (π i) ∈ q)
    (hAnnR : ∀ i : Fin r,
      let I := piPowEightPrefixIdeal π i.1 (Nat.le_of_lt i.isLt)
      Ideal.torsionOf (R ⧸ I) (R ⧸ I) (Ideal.Quotient.mk I (π i)) =
        Ideal.torsionOf (R ⧸ I) (R ⧸ I) (Ideal.Quotient.mk I (π i ^ 2)))
    (hAnnΛ : ∀ i : Fin r,
      let I := piPowEightPrefixIdeal π i.1 (Nat.le_of_lt i.isLt)
      let J := Ideal.map (algebraMap R Λ) I
      Ideal.torsionOf (Λ ⧸ J) (Λ ⧸ J) (Ideal.Quotient.mk J (algebraMap R Λ (π i))) =
        Ideal.torsionOf (Λ ⧸ J) (Λ ⧸ J) (Ideal.Quotient.mk J (algebraMap R Λ (π i ^ 2))))
    (hStrict : ∀ i : Fin r, IsStrictlyStandard R (algebraMap R A (π i)))
    (hresolve :
      let r8 := R ⧸ piPowEightReductionIdeal π
      let a8 := A ⧸ Ideal.map (algebraMap R A) (piPowEightReductionIdeal π)
      let l8 := Λ ⧸ Ideal.map (algebraMap R Λ) (piPowEightReductionIdeal π)
      let q8 : Ideal l8 := piPowEightReductionPrime π q
      ResolvableAtPrime r8 a8 l8 q8) :
    ResolvableAtPrime R A Λ q := sorry

end

end Algebra

/-! ### Lemma_16_9_3 (from Chap16) -/
universe u v w

namespace Algebra

open IsLocalization
open scoped Algebra

section

variable {R : Type u} {A : Type v} {Λ : Type w}
variable [CommRing R] [CommRing A] [CommRing Λ]
variable [Algebra R A] [Algebra R Λ] [Algebra A Λ] [IsScalarTower R A Λ]

section Prime

variable (q : Ideal Λ) [q.IsPrime]

/- Domain-style sampling:
- primary domain: localized commutative algebra and finite-presentation resolution data;
- sampled owner declarations:
  `ResolvableAtPrime`,
  `resolvableAtPrime_iff`,
  `Localization.AtPrime`,
  `Localization (Algebra.algebraMapSubmonoid A p.primeCompl)`;
- best owner abstraction: the localized source condition in Lemma `16.9.3` is the existing owner
  `ResolvableAtPrime`, specialized to `R_𝔭 → A_𝔭 → Λ_𝔮 ⊃ 𝔮Λ_𝔮`;
- primitive vs. derived: the primitive data are the localized rings and the prime ideal
  `𝔮Λ_𝔮`; the former `HasLocalResolutionAtPrime` wrapper was only a derived repackaging and is
  deleted in favor of the owner predicate itself.

Source/core/bridge triage:
- `source-facing`: the localized resolution hypothesis in the Stacks statement;
- `core/canonical`: `ResolvableAtPrime` on the localized rings;
- `bridge/view`: the local notation identifying the localized base ring, algebra, and target
  prime ideal.
-/

local notation "Rₚ" => Localization.AtPrime (q.under R)
local notation "Sₚ" => Algebra.algebraMapSubmonoid A (Ideal.primeCompl (q.under R))
local notation "Aₚ" => Localization Sₚ
local notation "Λ_𝔮" => Localization.AtPrime q
local notation "𝔮Λ_𝔮" => Ideal.map (algebraMap Λ Λ_𝔮) q

private theorem localizedTargetSubmonoid_le (q : Ideal Λ) [q.IsPrime] :
    Algebra.algebraMapSubmonoid Λ (Ideal.primeCompl (q.under R)) ≤ q.primeCompl := by
  rintro _ ⟨r, hr, rfl⟩
  simpa [Ideal.primeCompl, Ideal.mem_comap] using hr

private theorem localizedSubmonoid_le (q : Ideal Λ) [q.IsPrime] :
    Algebra.algebraMapSubmonoid A (Ideal.primeCompl (q.under R)) ≤
      Submonoid.comap (algebraMap A Λ) q.primeCompl := by
  intro a ha
  exact localizedTargetSubmonoid_le q <|
    (Algebra.algebraMapSubmonoid_le_comap (Ideal.primeCompl (q.under R))
      (IsScalarTower.toAlgHom R A Λ)) ha

noncomputable instance : Algebra Aₚ Λ_𝔮 := by
  have hSubmonoid : Sₚ ≤ Submonoid.comap (algebraMap A Λ) q.primeCompl := localizedSubmonoid_le q
  exact
    RingHom.toAlgebra <| IsLocalization.map Λ_𝔮 (algebraMap A Λ) hSubmonoid

instance : IsScalarTower Rₚ Aₚ Λ_𝔮 := by
  refine IsScalarTower.of_algebraMap_eq ?_
  intro x
  obtain ⟨r, s, rfl⟩ := IsLocalization.exists_mk'_eq (Ideal.primeCompl (q.under R)) x
  have hSubmonoid : Sₚ ≤ Submonoid.comap (algebraMap A Λ) q.primeCompl := localizedSubmonoid_le q
  have hsA : algebraMap R A ↑s ∈ Sₚ := by
    exact ⟨↑s, s.2, rfl⟩
  have hsΛ : algebraMap R Λ ↑s ∈ q.primeCompl := by
    change ↑s ∉ q.under R
    exact s.2
  change algebraMap Rₚ Λ_𝔮 (IsLocalization.mk' Rₚ r s) =
    algebraMap Aₚ Λ_𝔮 (algebraMap Rₚ Aₚ (IsLocalization.mk' Rₚ r s))
  have hAp :
      algebraMap Rₚ Aₚ (IsLocalization.mk' Rₚ r s) =
        IsLocalization.mk' Aₚ (algebraMap R A r) ⟨algebraMap R A ↑s, hsA⟩ :=
    by simpa using IsLocalization.algebraMap_mk' A Rₚ Aₚ r s
  have hRq :
      algebraMap Rₚ Λ_𝔮 (IsLocalization.mk' Rₚ r s) =
        IsLocalization.mk' Λ_𝔮 (algebraMap R Λ r) ⟨algebraMap R Λ ↑s, hsΛ⟩ := by
    refine (Localization.localRingHom_mk' (q.under R) q (algebraMap R Λ) rfl r s).trans ?_
    congr 1
  rw [hAp, hRq]
  have hMap :
      algebraMap Aₚ Λ_𝔮 (IsLocalization.mk' Aₚ (algebraMap R A r) ⟨algebraMap R A ↑s, hsA⟩) =
        IsLocalization.mk' Λ_𝔮 (algebraMap R Λ r) ⟨algebraMap R Λ ↑s, hsΛ⟩ := by
    change
      IsLocalization.map Λ_𝔮 (algebraMap A Λ) hSubmonoid
          (IsLocalization.mk' Aₚ (algebraMap R A r) ⟨algebraMap R A ↑s, hsA⟩) =
        _
    simpa [IsScalarTower.algebraMap_eq R A Λ] using
      IsLocalization.map_mk' hSubmonoid
        (algebraMap R A r) ⟨algebraMap R A ↑s, hsA⟩
  simp [hMap]

end Prime

-- Proof sketch: start from the local resolution at `Λ_𝔮`, replace it by a standard smooth
-- factorization over `R_𝔭` using Lemmas `16.2.8`, `16.3.4`, and `16.3.6`, then clear
-- denominators in the resulting standard smooth presentation and homogenize the defining
-- equations. The resulting finitely presented global algebra still maps to `Λ`, and the chosen
-- Jacobian determinant stays away from `𝔮`, so the image of `H_{C/R}` is not contained in `𝔮`.
/-- Lemma 16.9.3: if `𝔮` is a minimal prime over `𝔥_A` and the localized map
`R_𝔭 → A_𝔭 → Λ_𝔮 ⊃ 𝔮 Λ_𝔮`, with `𝔭 = R ∩ 𝔮`, admits a resolution and `R` is Noetherian while `A`
is finitely presented over `R`, then `A → Λ` factors through a finitely presented `R`-algebra `C`
whose singular ideal image in `Λ` is not contained in `𝔮`. -/
theorem exists_factorization_with_singularIdeal_not_le_of_localResolutionAtMinimalPrime
    [IsNoetherianRing R] [FinitePresentation R A] (q : Ideal Λ)
    (hq : q ∈ (h(A⁄R, Λ)).minimalPrimes)
    (hresolve :
      let _ : q.IsPrime := Ideal.minimalPrimes_isPrime hq
      let Rₚ := Localization.AtPrime (q.under R)
      let Sₚ := Algebra.algebraMapSubmonoid A (Ideal.primeCompl (q.under R))
      let Aₚ := Localization Sₚ
      let Λ_𝔮 := Localization.AtPrime q
      let 𝔮Λ_𝔮 := Ideal.map (algebraMap Λ Λ_𝔮) q
      ResolvableAtPrime Rₚ Aₚ Λ_𝔮 𝔮Λ_𝔮) :
    ∃ (C : Type (max u v w)) (_ : CommRing C) (_ : Algebra R C) (_ : FinitePresentation R C)
      (f : A →ₐ[R] C) (g : C →ₐ[R] Λ),
      g.comp f = IsScalarTower.toAlgHom R A Λ ∧
        ¬ g.singularIdealIn R ≤ q := by
  letI : q.IsPrime := Ideal.minimalPrimes_isPrime hq
  sorry

end

end Algebra

/-! ### Lemma_16_9_4 (from Chap16) -/
universe u v w x

namespace Algebra

open PrimeSpectrum
open scoped Algebra

section

variable {R : Type u} {A : Type v} {Λ : Type w}
variable [CommRing R] [CommRing A] [CommRing Λ]
variable [Algebra R A] [Algebra R Λ] [Algebra A Λ] [IsScalarTower R A Λ]

/- Domain-style sampling:
- primary domain: localized commutative algebra for resolution data at a prime;
- sampled owner declarations:
  `ResolvableAtPrime`,
  `exists_factorization_with_singularIdeal_not_le_of_localResolutionAtMinimalPrime`,
  `Localization.AtPrime`,
  `Algebra.algebraMapSubmonoid`;
- best owner abstraction: the localized hypothesis is the canonical owner
  `ResolvableAtPrime` on the localized rings, exactly as in Lemma `16.9.3`;
- primitive data: the minimal prime itself, now taken canonically as `q : PrimeSpectrum Λ`,
  together with the localized rings `R_𝔭`, `A_𝔭`, `Λ_𝔮` and the prime ideal `𝔮Λ_𝔮`;
- derived API: the local-resolution hypothesis is stated directly via `ResolvableAtPrime` on those
  localized rings, with the prime structure supplied by `q` rather than repeated `let`-bound
  instance reconstruction.

Source/core/bridge triage:
- `source-facing`: Lemma `16.9.4`, which upgrades a local resolution at a minimal prime to a
  global one under the dimension-zero hypothesis;
- `core/canonical`: `ResolvableAtPrime`;
- `bridge/view`: the localized rings built from the prime-spectrum point `q`.
-/

section Prime

variable (q : PrimeSpectrum Λ)

local notation "𝔮" => q.asIdeal
local notation "Rₚ" => Localization.AtPrime (q.asIdeal.under R)
local notation "Sₚ" => Algebra.algebraMapSubmonoid A (Ideal.primeCompl (q.asIdeal.under R))
local notation "Aₚ" => Localization Sₚ
local notation "Λ_𝔮" => Localization.AtPrime q.asIdeal
local notation "𝔮Λ_𝔮" => Ideal.map (algebraMap Λ Λ_𝔮) q.asIdeal

-- Proof sketch: use Lemma `16.9.3` to replace the assumed local resolution at `q` by a finitely
-- presented factorization `A → C → Λ` with `𝔥_C` not contained in `q`. Because
-- `ringKrullDim (Localization.AtPrime q) = 0`, the local ring `Λ_q` is Artinian local, so some
-- power of `𝔥_A` is killed away from `q`. Adjoin variables and relations as in the textbook proof
-- to build a finitely presented `R`-algebra `B` over `A` whose target singular ideal contains
-- `𝔥_A` and still avoids `q`.
/-- Lemma 16.9.4: in Situation `16.9.1`, let `𝔭 = R ∩ 𝔮`. Assume `R` is Noetherian, `A` is
finitely presented over `R`, `𝔮` is minimal over `𝔥_A`, the localized map
`R_𝔭 → A_𝔭 → Λ_𝔮 ⊃ 𝔮 Λ_𝔮` can be resolved, and `ringKrullDim (Localization.AtPrime 𝔮) = 0`.
Then `R → A → Λ ⊃ 𝔮` can be resolved. -/
theorem resolvableAtPrime_of_localResolvableAtMinimalPrime_of_ringKrullDim_eq_zero
    [IsNoetherianRing R] [FinitePresentation R A]
    (hq : q.asIdeal ∈ (h(A⁄R, Λ)).minimalPrimes)
    (hlocal : ResolvableAtPrime Rₚ Aₚ Λ_𝔮 𝔮Λ_𝔮)
    (hdim : ringKrullDim (Localization.AtPrime q.asIdeal) = 0) :
    ResolvableAtPrime R A Λ q.asIdeal := by
  sorry

end Prime

end

end Algebra
