import StacksProject_2024.Chap10.Lemma_10_159_1.ResidueExtensionStage

universe u v w

open IsLocalRing
open CategoryTheory Limits
open scoped RatFunc

section

variable {R : Type u} [CommRing R] [IsLocalRing R]

/-- Helper for Lemma 10.159.1: the well-ordered element of `K` with ordinal rank `α`. -/
noncomputable def wellOrder_prefixElement
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal} (hα : α < Ordinal.type (@WellOrderingRel K)) : K :=
  Ordinal.enum WellOrderingRel (Ordinal.ToType.mk ⟨α, hα⟩)

/-- Helper for Lemma 10.159.1: the prefix set at ordinal `α` consists of all well-ordered
elements of `K` whose rank is `< α`. -/
noncomputable def wellOrder_prefixSet
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    (α : Ordinal) (hα : α ≤ Ordinal.type (@WellOrderingRel K)) : Set K :=
  Set.range fun β : {γ // γ < α} ↦
    wellOrder_prefixElement (R := R) (K := K) (hα := lt_of_lt_of_le β.2 hα)

/-- Helper for Lemma 10.159.1: the prefix field at ordinal `α` is generated by all well-ordered
elements of rank `< α`. This is the field-theoretic side of the source proof's transfinite
construction. -/
noncomputable def wellOrder_prefixField
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    (α : Ordinal) (hα : α ≤ Ordinal.type (@WellOrderingRel K)) :
    IntermediateField (ResidueField R) K :=
  IntermediateField.adjoin (ResidueField R) (wellOrder_prefixSet (R := R) (K := K) α hα)

/-- Helper for Lemma 10.159.1: the initial well-ordered prefix field is the bottom intermediate
field, because there are no elements of rank `< 0`. -/
theorem wellOrder_prefixField_zero
    (K : Type v) [Field K] [Algebra (ResidueField R) K] :
    wellOrder_prefixField (R := R) (K := K) 0
      (show (0 : Ordinal) ≤ Ordinal.type (@WellOrderingRel K) by simp) = ⊥ := by
  -- The prefix set at `0` is empty, so adjoining it gives the bottom intermediate field.
  have hset :
      wellOrder_prefixSet (R := R) (K := K) 0
        (show (0 : Ordinal) ≤ Ordinal.type (@WellOrderingRel K) by simp) = ∅ := by
    ext x
    constructor
    · intro hx
      rcases hx with ⟨β, _⟩
      exact (not_lt_of_ge (show (0 : Ordinal) ≤ β.1 by simp)) β.2
    · intro hx
      cases hx
  rw [wellOrder_prefixField, hset, IntermediateField.adjoin_empty]

/-- Helper for Lemma 10.159.1: passing from ordinal `α` to `α + 1` adds exactly the next
well-ordered element of `K` to the prefix set. -/
theorem wellOrder_prefixSet_succ
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal} (hα : α < Ordinal.type (@WellOrderingRel K)) :
    wellOrder_prefixSet (R := R) (K := K) (α + 1) (Order.succ_le_of_lt hα) =
      insert (wellOrder_prefixElement (R := R) (K := K) hα)
        (wellOrder_prefixSet (R := R) (K := K) α (le_of_lt hα)) := by
  -- A rank `< α + 1` is either exactly `α` or already `< α`.
  ext x
  constructor
  · intro hx
    rcases hx with ⟨⟨γ, hγ⟩, rfl⟩
    have hle : γ ≤ α := by
      simpa [Order.lt_succ_iff] using hγ
    rcases lt_or_eq_of_le hle with hlt | hEq
    · right
      refine ⟨⟨γ, hlt⟩, ?_⟩
      simp [wellOrder_prefixElement]
    · left
      cases hEq
      simp [wellOrder_prefixElement]
  · intro hx
    rcases hx with rfl | hx
    · refine ⟨⟨α, Order.lt_succ α⟩, ?_⟩
      simp [wellOrder_prefixElement]
    · rcases hx with ⟨⟨γ, hγ⟩, rfl⟩
      refine ⟨⟨γ, ?_⟩, ?_⟩
      · simpa [Order.lt_succ_iff] using hγ.le
      · simp [wellOrder_prefixElement]

/-- Helper for Lemma 10.159.1: the well-ordered prefix fields form an increasing chain. This is
the field-level compatibility needed before one packages the stage recursion above them. -/
theorem wellOrder_prefixField_mono
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α β : Ordinal}
    (hα : α ≤ Ordinal.type (@WellOrderingRel K))
    (hβ : β ≤ Ordinal.type (@WellOrderingRel K))
    (hαβ : α ≤ β) :
    wellOrder_prefixField (R := R) (K := K) α hα ≤
      wellOrder_prefixField (R := R) (K := K) β hβ := by
  -- Every generator appearing before stage `α` also appears before stage `β`.
  refine IntermediateField.adjoin.mono
    (F := ResidueField R)
    (S := wellOrder_prefixSet (R := R) (K := K) α hα)
    (T := wellOrder_prefixSet (R := R) (K := K) β hβ) ?_
  rintro x ⟨γ, rfl⟩
  exact ⟨⟨γ.1, lt_of_lt_of_le γ.2 hαβ⟩, rfl⟩

/-- Helper for Lemma 10.159.1: at a limit ordinal, the prefix field is the supremum of the
earlier prefix fields. This is the exact field-level limit rewrite used in the source proof's
direct-limit stage. -/
theorem wellOrder_prefixField_limit_eq_iSup_lt
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal}
    (hα : α ≤ Ordinal.type (@WellOrderingRel K))
    (hlimit : Order.IsSuccLimit α) :
    wellOrder_prefixField (R := R) (K := K) α hα =
      ⨆ β : Set.Iio α,
        wellOrder_prefixField (R := R) (K := K) β.1
          (le_trans (le_of_lt β.2) hα) := by
  -- At a limit stage, each generator already appears strictly earlier, and conversely every
  -- earlier stage sits inside the limit stage by monotonicity.
  apply le_antisymm
  · refine IntermediateField.adjoin_le_iff.mpr ?_
    rintro x ⟨γ, rfl⟩
    let β : Set.Iio α := ⟨γ.1 + 1, hlimit.succ_lt γ.2⟩
    have hxβ :
        wellOrder_prefixElement (R := R) (K := K)
            (hα := lt_of_lt_of_le γ.2 hα) ∈
          wellOrder_prefixField (R := R) (K := K) β.1
            (le_trans (le_of_lt β.2) hα) := by
      exact IntermediateField.subset_adjoin (ResidueField R)
        (wellOrder_prefixSet (R := R) (K := K) β.1 (le_trans (le_of_lt β.2) hα))
        ⟨⟨γ.1, by exact Order.lt_succ γ.1⟩, rfl⟩
    exact
      (le_iSup
        (fun β : Set.Iio α ↦
          wellOrder_prefixField (R := R) (K := K) β.1
            (le_trans (le_of_lt β.2) hα))
        β) hxβ
  · refine iSup_le fun β ↦ ?_
    exact wellOrder_prefixField_mono (R := R) (K := K)
      (le_trans (le_of_lt β.2) hα) hα β.2.le

/-- Helper for Lemma 10.159.1: the successor prefix field is obtained by adjoining the unique new
well-ordered element at rank `α` to the previous prefix field. This is the exact field-theoretic
rewrite used in the source proof's successor stage. -/
theorem wellOrder_prefixField_succ
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal} (hα : α < Ordinal.type (@WellOrderingRel K)) :
    wellOrder_prefixField (R := R) (K := K) (α + 1) (Order.succ_le_of_lt hα) =
      (IntermediateField.adjoin
        (wellOrder_prefixField (R := R) (K := K) α (le_of_lt hα))
        ({wellOrder_prefixElement (R := R) (K := K) hα} : Set K)).restrictScalars
          (ResidueField R) := by
  -- Rewrite the successor prefix set as one new element adjoined to the previous prefix field.
  rw [wellOrder_prefixField, wellOrder_prefixSet_succ (R := R) (K := K) (hα := hα)]
  calc
    IntermediateField.adjoin (ResidueField R)
        ({wellOrder_prefixElement (R := R) (K := K) hα} ∪
          wellOrder_prefixSet (R := R) (K := K) α (le_of_lt hα))
      =
        IntermediateField.adjoin (ResidueField R)
          (wellOrder_prefixSet (R := R) (K := K) α (le_of_lt hα) ∪
            ({wellOrder_prefixElement (R := R) (K := K) hα} : Set K)) := by
            rw [Set.union_comm]
    _ =
      (IntermediateField.adjoin
        (wellOrder_prefixField (R := R) (K := K) α (le_of_lt hα))
        ({wellOrder_prefixElement (R := R) (K := K) hα} : Set K)).restrictScalars
          (ResidueField R) := by
            simpa [wellOrder_prefixField] using
              (IntermediateField.adjoin_adjoin_left
                (F := ResidueField R)
                (S := wellOrder_prefixSet (R := R) (K := K) α (le_of_lt hα))
                (T := ({wellOrder_prefixElement (R := R) (K := K) hα} : Set K))).symm

/-- Helper for Lemma 10.159.1: the terminal well-ordered prefix field is all of `K`. This
discharges the source proof's claim that the transfinite recursion eventually reaches the whole
residue-field extension. -/
theorem wellOrder_prefixField_top
    (K : Type v) [Field K] [Algebra (ResidueField R) K] :
    wellOrder_prefixField (R := R) (K := K) (Ordinal.type (@WellOrderingRel K)) le_rfl = ⊤ := by
  -- Every element of `K` appears at its own well-order rank, so the full prefix field is all of
  -- `K`.
  apply eq_top_iff.mpr
  intro x hx
  have hxmem :
      x ∈ wellOrder_prefixSet (R := R) (K := K) (Ordinal.type (@WellOrderingRel K)) le_rfl := by
    refine ⟨⟨Ordinal.typein WellOrderingRel x, Ordinal.typein_lt_type WellOrderingRel x⟩, ?_⟩
    simpa [wellOrder_prefixElement] using (Ordinal.enum_typein WellOrderingRel x)
  exact IntermediateField.subset_adjoin (ResidueField R)
    (wellOrder_prefixSet (R := R) (K := K) (Ordinal.type (@WellOrderingRel K)) le_rfl) hxmem

/-- Helper for Lemma 10.159.1: the well-ordered prefix field does not depend on the chosen proof
that the stage ordinal lies below the ambient well-order type. This keeps the later recursive
packaging stable under proof irrelevance. -/
@[simp] theorem wellOrder_prefixField_proof_irrel
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal}
    (h₁ h₂ : α ≤ Ordinal.type (@WellOrderingRel K)) :
    wellOrder_prefixField (R := R) (K := K) α h₁ =
      wellOrder_prefixField (R := R) (K := K) α h₂ := by
  -- The ordinal bound witnesses live in a subsingleton, so the generated prefix field is the same.
  cases Subsingleton.elim h₁ h₂
  rfl

/-- Helper for Lemma 10.159.1: the bottom intermediate field sits inside every well-ordered
prefix field. This is the field-side inclusion attached to the canonical base-stage map. -/
theorem base_le_prefixField
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal} (hα : α ≤ Ordinal.type (@WellOrderingRel K)) :
    (⊥ : IntermediateField (ResidueField R) K) ≤
      wellOrder_prefixField (R := R) (K := K) α hα := by
  -- Compare the zero prefix field with the `α`-prefix field and rewrite the zero stage as `⊥`.
  simpa [wellOrder_prefixField_zero (R := R) (K := K)] using
    (wellOrder_prefixField_mono (R := R) (K := K)
      (show (0 : Ordinal) ≤ Ordinal.type (@WellOrderingRel K) from bot_le) hα
      (show (0 : Ordinal) ≤ α from bot_le))

/-- Helper for Lemma 10.159.1: the zero prefix field is already realized by a universe-lifted
base stage, after identifying `wellOrder_prefixField 0` with `⊥`. -/
theorem exists_zero_prefix_stage
    (K : Type v) [Field K] [Algebra (ResidueField R) K] :
    ∃ T : ResidueExtensionStage.{u, v, max u v} (R := R) K
        (⊥ : IntermediateField (ResidueField R) K),
      Nonempty
        (ResidueExtensionStage.Hom
          (show (⊥ : IntermediateField (ResidueField R) K) ≤ ⊥ by rfl)
          (ResidueExtensionStage.base (R := R) K) T) := by
  let A := ULift.{max u v, u} R
  letI : CommRing A := inferInstance
  letI : IsLocalRing A :=
    RingEquiv.isLocalRing (ULift.ringEquiv.symm : R ≃+* A)
  letI : Algebra R A := inferInstance
  let hlocal : IsLocalHom (algebraMap R A) := by
    change IsLocalHom (ULift.ringEquiv.symm.toRingHom : R →+* A)
    exact IsLocalHom.of_surjective
      (ULift.ringEquiv.symm.toRingHom : R →+* A)
      (show Function.Surjective (ULift.ringEquiv.symm.toRingHom : R →+* A) from
        ULift.ringEquiv.symm.surjective)
  let hflat : (algebraMap R A).Flat := by
    change RingHom.Flat (ULift.ringEquiv.symm.toRingHom : R →+* A)
    exact RingHom.Flat.of_bijective
      (f := (ULift.ringEquiv.symm.toRingHom : R →+* A))
      (show Function.Bijective (ULift.ringEquiv.symm.toRingHom : R →+* A) from
        ULift.ringEquiv.symm.bijective)
  let hmap : Ideal.map (algebraMap R A) (maximalIdeal R) = maximalIdeal A := by
    change Ideal.map (ULift.ringEquiv.symm.toRingHom : R →+* A)
        (maximalIdeal R) = maximalIdeal A
    exact IsLocalRing.map_ringEquiv_maximalIdeal
      (ULift.ringEquiv.symm : R ≃+* A)
  let eκ : ResidueField A ≃+* ResidueField R :=
    IsLocalRing.ResidueField.mapEquiv (ULift.ringEquiv : A ≃+* R)
  let T : ResidueExtensionStage.{u, v, max u v} (R := R) K
      (⊥ : IntermediateField (ResidueField R) K) :=
    { A := A
      commRing := inferInstance
      localRing := inferInstance
      algebra := inferInstance
      localHom := hlocal
      flat := hflat
      map_maximalIdeal := hmap
      residueEquiv := eκ.trans (ResidueExtensionStage.base (R := R) K).residueEquiv }
  refine ⟨T, ?_⟩
  refine ⟨?_⟩
  refine
    { toAlgHom :=
        { toRingHom := ULift.ringEquiv.symm.toRingHom
          commutes' := fun r ↦ rfl }
      isLocalHom := hlocal
      residue_comm := ?_ }
  ext x
  obtain ⟨r, rfl⟩ := IsLocalRing.residue_surjective x
  rfl

/-- Helper for Lemma 10.159.1: once a prefix field at stage `α` is realized by a source-faithful
stage, adjoining the next well-ordered element yields a realizing stage for the corresponding
one-element extension. Combined with `wellOrder_prefixField_succ`, this is exactly the solved
successor case of the source proof. -/
theorem exists_adjoin_singleton_stage_of_prefix_stage
    (K : Type v) [Field K] [Algebra (ResidueField R) K]
    {α : Ordinal} (hα : α < Ordinal.type (@WellOrderingRel K))
    (S : ResidueExtensionStage.{u, v, w} (R := R) K
      (wellOrder_prefixField (R := R) (K := K) α (le_of_lt hα))) :
    let Lsucc : IntermediateField (ResidueField R) K :=
      (IntermediateField.adjoin
        (wellOrder_prefixField (R := R) (K := K) α (le_of_lt hα))
        ({wellOrder_prefixElement (R := R) (K := K) hα} : Set K)).restrictScalars
          (ResidueField R)
    ∃ T : ResidueExtensionStage.{u, v, w} (R := R) K Lsucc,
      Nonempty
        (ResidueExtensionStage.Hom
          (ResidueExtensionStage.le_restrictScalars_adjoin_singleton (R := R)
            (wellOrder_prefixField (R := R) (K := K) α (le_of_lt hα))
            (wellOrder_prefixElement (R := R) (K := K) hα))
          S T) := by
  -- This is exactly the one-element extension theorem specialized to the next well-ordered
  -- generator of `K`.
  exact ResidueExtensionStage.extend_stage_by_element
    (S := S)
    (wellOrder_prefixElement (R := R) (K := K) hα)

end
