import Mathlib.RingTheory.DividedPowers.Padic
import StacksProject_2024.Chap23.Lemma_23_4_2

universe u

namespace DividedPowers

section

variable {p : ℕ}
variable [Fact p.Prime]
variable {A : Type u} [CommRing A] [Algebra ℤ_[p] A]

local notation "ZpLoc" => ℤ_[p]
local notation "pIdealZpLoc" => Ideal.span ({(p : ZpLoc)} : Set ZpLoc)
local notation "pIdealA" => Ideal.span ({(p : A)} : Set A)

/-
Source/core/bridge triage:
- `source-facing`: Example 23.2.3, namely the canonical divided power structure on `pA` for a
  `ℤ_(p)`-algebra `A`, characterized by the formula `γ_n(pa) = (p^n / n!) a^n`;
- `core/canonical`: the Chapter 23 owner `DividedPowers.extendsAlong`;
- `bridge/view`: the ideal-identification lemma `map_pIdealZpLoc_eq_pIdealA`, the source-owner
  formula lemma `padicInt_dividedPowers_dpow_eq`, and the extension companions relating the source
  formula to `DividedPowers.extendsAlong`.
-/

/-- The image in a `ℤ_(p)`-algebra of the principal ideal `(p)` of `ℤ_(p)` is the principal ideal
generated by `(p : A)`. -/
theorem map_pIdealZpLoc_eq_pIdealA :
    Ideal.map (algebraMap ZpLoc A) pIdealZpLoc = pIdealA := by
  simp [Ideal.map_span, Set.image_singleton]

/-- On the principal ideal `(p) ⊂ ℤ_(p)`, mathlib's canonical owner `PadicInt.dividedPowers p`
is given by the expected factorial formula. -/
theorem padicInt_dividedPowers_dpow_eq (n : ℕ) {x : ZpLoc} (hx : x ∈ pIdealZpLoc) :
    (PadicInt.dividedPowers p).dpow n x = Ring.inverse (n.factorial : ZpLoc) * x ^ n := by
  sorry

/-- Bridge companion: the canonical divided powers on `(p) ⊂ ℤ_(p)` extend along the structure
map `ℤ_(p) → A`. -/
theorem extendsAlong_algebraMap_awayPrime :
    (PadicInt.dividedPowers p).extendsAlong (algebraMap ZpLoc A) := by
  exact (PadicInt.dividedPowers p).extendsAlong_of_map_eq_bot_or_isPrincipal_or_flat
    (algebraMap ZpLoc A) <| Or.inr <| Or.inl <| inferInstance

/-- Bridge companion: the source factorial formula on `pA` is equivalent to compatibility with the
canonical divided powers on `(p) ⊂ ℤ_(p)`. -/
theorem isDPMorphism_iff_pDividedPowers_formula
    {γA : DividedPowers pIdealA}
    : IsDPMorphism (PadicInt.dividedPowers p) γA (algebraMap ZpLoc A) ↔
        ∀ n a,
          γA.dpow n ((p : A) * a) =
            algebraMap ZpLoc A (Ring.inverse (n.factorial : ZpLoc) * (p : ZpLoc) ^ n) * a ^ n := by
  sorry

/-- Example 23.2.3: if `A` is a `ℤ_(p)`-algebra, then the principal ideal `pA`, equivalently the
image of `(p)` from `ℤ_(p)`, carries a unique divided power structure characterized by the source
formula `γ_n(pa) = (p^n / n!) a^n`. -/
@[stacks 07GN]
theorem existsUniquePDividedPowers :
    ∃! γA : DividedPowers pIdealA,
      ∀ n a,
        γA.dpow n ((p : A) * a) =
          algebraMap ZpLoc A (Ring.inverse (n.factorial : ZpLoc) * (p : ZpLoc) ^ n) * a ^ n := by
  sorry

/-- Companion to Example 23.2.3: the source formula determines the divided powers on `pA`
uniquely. -/
theorem eq_pDividedPowers_of_formula
    {γA γA' : DividedPowers pIdealA}
    (hγA : ∀ n a,
      γA.dpow n ((p : A) * a) =
        algebraMap ZpLoc A (Ring.inverse (n.factorial : ZpLoc) * (p : ZpLoc) ^ n) * a ^ n)
    (hγA' : ∀ n a,
      γA'.dpow n ((p : A) * a) =
        algebraMap ZpLoc A (Ring.inverse (n.factorial : ZpLoc) * (p : ZpLoc) ^ n) * a ^ n) :
    γA = γA' := by
  exact ExistsUnique.unique existsUniquePDividedPowers hγA hγA'

/-- Any two divided power structures on `pA` compatible with the canonical divided powers on
`(p) ⊂ ℤ_(p)` coincide. -/
theorem eq_pDividedPowers_of_isDPMorphism
    {γA γA' : DividedPowers pIdealA}
    (hγA : IsDPMorphism (PadicInt.dividedPowers p) γA (algebraMap ZpLoc A))
    (hγA' : IsDPMorphism (PadicInt.dividedPowers p) γA' (algebraMap ZpLoc A)) :
    γA = γA' := by
  apply eq_pDividedPowers_of_formula
  · exact (isDPMorphism_iff_pDividedPowers_formula.mp hγA)
  · exact (isDPMorphism_iff_pDividedPowers_formula.mp hγA')

/-- Divided power structures on `pA` compatible with the canonical divided powers on
`(p) ⊂ ℤ_(p)` are unique. -/
instance instSubsingletonCompatiblePDividedPowers :
    Subsingleton
      {γA : DividedPowers pIdealA //
        IsDPMorphism (PadicInt.dividedPowers p) γA (algebraMap ZpLoc A)} where
  allEq γA γA' := by
    apply Subtype.ext
    exact eq_pDividedPowers_of_isDPMorphism γA.2 γA'.2

end

end DividedPowers
