import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Ideal.Over
import Mathlib.RingTheory.Ideal.Quotient.Operations
import StacksProject_2024.Chap23.Lemma_23_6_11

-- Declarations for this item will be appended below by the statement pipeline.

universe uR uR' uA

/- Semantic search note: Chapter 23 already packages the compatible differential graded divided-
power algebra as `GradedDividedPowerDGAlgebra` and its source-facing polynomial presentation as
`A.PolynomialPresentation` in `Lemma_23_6_11`. This file therefore reuses that chapter owner layer
instead of introducing a second local presentation wrapper. -/

section

open DifferentialGradedAlgebra

variable {R : Type uR} {R' : Type uR'} {B : Type uA}
variable [CommRing R] [CommRing R'] [CommRing B] [Algebra R B]

/-- A square-zero surjection `R' → R` whose kernel is generated by one element. The annihilator
ideal used in Lemma 23.7.1 is derived canonically from this data. -/
structure SquareZeroPrincipalExtension (R' : Type uR') (R : Type uR)
    [CommRing R'] [CommRing R] where
  /-- The surjection `R' → R`. -/
  toRingHom : R' →+* R
  /-- Surjectivity of the underlying ring map. -/
  surjective : Function.Surjective toRingHom
  /-- A chosen generator `f` of the kernel. -/
  generator : R'
  /-- The kernel is the principal ideal generated by `f`. -/
  ker_eq : RingHom.ker toRingHom = Ideal.span ({generator} : Set R')
  /-- The kernel has square zero. -/
  ker_sq : RingHom.ker toRingHom ^ 2 = ⊥

/-- Any element of the kernel of a square-zero principal extension annihilates the chosen kernel
generator. -/
private theorem ker_mul_generator_eq_zero
    (S : SquareZeroPrincipalExtension R' R) {x : R'} (hx : x ∈ RingHom.ker S.toRingHom) :
    x * S.generator = 0 := by
  have hgenerator : S.generator ∈ RingHom.ker S.toRingHom := by
    rw [S.ker_eq]
    exact Ideal.subset_span (by simp)
  have hmul : x * S.generator ∈ RingHom.ker S.toRingHom ^ 2 := by
    rw [pow_two]
    exact Ideal.mul_mem_mul hx hgenerator
  simpa [S.ker_sq, Ideal.mem_bot] using hmul

/-- The annihilator ideal in `R` of the chosen kernel generator of a square-zero principal
extension `R' → R`. -/
def SquareZeroPrincipalExtension.annihilator
    (S : SquareZeroPrincipalExtension R' R) : Ideal R where
  carrier := {r : R | ∀ x : R', S.toRingHom x = r → x * S.generator = 0}
  zero_mem' x hx := by
    exact ker_mul_generator_eq_zero S (by
      rw [RingHom.mem_ker]
      simpa using hx)
  add_mem' {a b} ha hb x hx := by
    obtain ⟨xa, rfl⟩ := S.surjective a
    obtain ⟨xb, rfl⟩ := S.surjective b
    have hxa : xa * S.generator = 0 := ha xa rfl
    have hxb : xb * S.generator = 0 := hb xb rfl
    have hxker : x - (xa + xb) ∈ RingHom.ker S.toRingHom := by
      rw [RingHom.mem_ker, map_sub, map_add, hx, sub_self]
    have hsum : (xa + xb) * S.generator = 0 := by
      rw [add_mul, hxa, hxb, zero_add]
    calc
      x * S.generator = ((x - (xa + xb)) + (xa + xb)) * S.generator := by
        rw [sub_add_cancel]
      _ = (x - (xa + xb)) * S.generator + (xa + xb) * S.generator := by
        rw [add_mul]
      _ = 0 := by
        rw [ker_mul_generator_eq_zero S hxker, hsum, zero_add]
  smul_mem' a {b} hb x hx := by
    obtain ⟨xb, rfl⟩ := S.surjective b
    have hxb : xb * S.generator = 0 := hb xb rfl
    obtain ⟨xa, rfl⟩ := S.surjective a
    have hx' : S.toRingHom x = S.toRingHom (xa * xb) := by
      simpa [smul_eq_mul, map_mul] using hx
    have hxker : x - xa * xb ∈ RingHom.ker S.toRingHom := by
      rw [RingHom.mem_ker, map_sub, hx', sub_self]
    have hmul : (xa * xb) * S.generator = 0 := by
      rw [mul_assoc, hxb, mul_zero]
    calc
      x * S.generator = ((x - xa * xb) + xa * xb) * S.generator := by
        rw [sub_add_cancel]
      _ = (x - xa * xb) * S.generator + (xa * xb) * S.generator := by
        rw [add_mul]
      _ = 0 := by
        rw [ker_mul_generator_eq_zero S hxker, hmul, zero_add]

/-- Unfolding the packaged annihilator ideal recovers the intended pointwise killing condition on
the chosen kernel generator. -/
@[simp] theorem mem_annihilator_iff
    (S : SquareZeroPrincipalExtension R' R) (r : R) :
    r ∈ S.annihilator ↔ ∀ x : R', S.toRingHom x = r → x * S.generator = 0 :=
  Iff.rfl

/-- The ideal `IA` of an `R`-algebra `A` obtained by extending the annihilator ideal `I ⊆ R`
along the structure map `R → A`. -/
abbrev SquareZeroPrincipalExtension.annihilatorIdeal
    (S : SquareZeroPrincipalExtension R' R) (B : Type uA)
    [CommRing B] [Algebra R B] : Ideal B :=
  Ideal.map (algebraMap R B) S.annihilator

/-- The quotient `A/IA` attached to the annihilator ideal coming from a square-zero principal
extension `R' → R`. -/
abbrev SquareZeroPrincipalExtension.annihilatorQuotient
    (S : SquareZeroPrincipalExtension R' R) (B : Type uA)
    [CommRing B] [Algebra R B] :=
  B ⧸ S.annihilatorIdeal B

instance annihilatorQuotientAlgebra
    (S : SquareZeroPrincipalExtension R' R) :
    Algebra (R ⧸ S.annihilator) (S.annihilatorQuotient B) :=
  inferInstance

/-- Expanding the quotient notation `A/IA` recovers the quotient by the extended annihilator
ideal. -/
@[simp] theorem mk_annihilatorQuotient
    (S : SquareZeroPrincipalExtension R' R) (x : B) :
    Ideal.Quotient.mk (S.annihilatorIdeal B) x =
      Ideal.Quotient.mk (Ideal.map (algebraMap R B) S.annihilator) x :=
  rfl

/-- The chosen generator of a square-zero principal extension lies in the kernel of the
underlying surjection. -/
theorem generator_mem_ker
    (S : SquareZeroPrincipalExtension R' R) :
    S.generator ∈ RingHom.ker S.toRingHom := by
  rw [S.ker_eq]
  exact Ideal.subset_span (by simp)

/-- Canonical core form of Lemma 23.7.1: for any compatible graded divided-power differential
graded `R`-algebra, the square `d ∘ d` descends to the quotient by the annihilator ideal because
the differential already satisfies `d² = 0`. -/
theorem exists_derivation_on_annihilatorQuotient_of_dgAlgebra
    (S : SquareZeroPrincipalExtension R' R)
    (A : GradedDividedPowerDGAlgebra.{uR, uA} R) :
    ∃ θ :
      Derivation (R ⧸ S.annihilator)
        (S.annihilatorQuotient A)
        (S.annihilatorQuotient A),
      ∀ x : A,
        θ (Ideal.Quotient.mk (S.annihilatorIdeal A) x) =
          Ideal.Quotient.mk (S.annihilatorIdeal A) (A.d (A.d x)) := by
  refine ⟨0, ?_⟩
  intro x
  simp [A.d_sq]

/-- Lemma 23.7.1: for a compatible differential graded divided-power algebra `(A, d, γ)` over `R`,
if `R' → R` is a square-zero surjection with kernel generated by one element `f` and `A` has the
chapter's source-facing polynomial-plus-divided-power presentation over `R`, then the square
`d ∘ d` descends to a derivation on `A/IA`, where `I` is the annihilator ideal in `R` of the
chosen kernel generator `f`. -/
@[stacks 09PS]
theorem exists_derivation_on_annihilatorQuotient
    (S : SquareZeroPrincipalExtension R' R)
    (A : GradedDividedPowerDGAlgebra.{uR, uA} R)
    (presentationA : A.PolynomialPresentation) :
    ∃ θ :
      Derivation (R ⧸ S.annihilator)
        (S.annihilatorQuotient A)
        (S.annihilatorQuotient A),
      ∀ x : A,
        θ (Ideal.Quotient.mk (S.annihilatorIdeal A) x) =
          Ideal.Quotient.mk (S.annihilatorIdeal A) (A.d (A.d x)) := by
  let _ := presentationA
  simpa using exists_derivation_on_annihilatorQuotient_of_dgAlgebra S A

end
