import Mathlib.Data.List.TFAE
import StacksProject_2024.stacks_project.Chap10.Definition_10_110_7
import StacksProject_2024.stacks_project.Chap10.Definition_10_135_5
import StacksProject_2024.stacks_project.Chap23.Definition_23_8_5
import Mathlib.RingTheory.Ideal.Cotangent

-- Declarations for this item will be appended below by the statement pipeline.

universe u

section

namespace Ideal

section

variable {R : Type u} [CommRing R]

/-- The conormal module `I / I² = I.Cotangent` can be generated by the codimension of the quotient
`R ⧸ I` in `R`. This is the ideal-level owner for the third clause of Lemma 23.8.3. -/
abbrev CotangentGeneratedByCodimension (I : Ideal R) : Prop :=
  ∃ c : ℕ, ringKrullDim (R ⧸ I) + c = ringKrullDim R ∧
    ∃ x : Fin c → I.Cotangent, Submodule.span (R ⧸ I) (Set.range x) = ⊤

/-- Unfolding `Ideal.CotangentGeneratedByCodimension` recovers the codimension-count conormal
generation clause. -/
@[simp] theorem cotangentGeneratedByCodimension_iff (I : Ideal R) :
    I.CotangentGeneratedByCodimension ↔
      ∃ c : ℕ, ringKrullDim (R ⧸ I) + c = ringKrullDim R ∧
        ∃ x : Fin c → I.Cotangent, Submodule.span (R ⧸ I) (Set.range x) = ⊤ :=
  Iff.rfl

end

end Ideal

variable {R : Type u} [CommRing R] [IsRegularRing R]

section

variable (p : PrimeSpectrum R) (I : Ideal R)

local notation "Rₚ" => Localization.AtPrime p.asIdeal
local notation "Iₚ" => Ideal.map (algebraMap R Rₚ) I
local notation "A" => Rₚ ⧸ Iₚ

/-
Source/core/bridge triage:
* source-facing: the three equivalent local conditions in Lemma 23.8.3 for the quotient `Rₚ / Iₚ`;
* core/canonical: `IsCompleteIntersectionLocalRing` and `Ideal.IsGeneratedByRegularSequence`;
* bridge/view: the codimension-count conormal criterion, exposed through the reusable ideal-level
  bridge `Ideal.CotangentGeneratedByCodimension`.

The main Stacks-tagged lemma therefore stays source-facing and spells out the generator-count
condition directly, while companion lemmas recover the reusable ideal-level bridge.
-/

-- Semantic recall note: `lean_leansearch` surfaced `Ideal.Cotangent` and
-- `ringKrullDim_add_length_eq_ringKrullDim_of_isRegular`; together with the verified local
-- precedents `Ideal.IsGeneratedByRegularSequence`, `IsCompleteIntersectionLocalRing`, and the
-- presentation-level conormal criterion around
-- `PolynomialPresentationAtPrime.conormalGeneratedByCondition`, this supports phrasing the third
-- clause through the reusable ideal-level bridge `Ideal.CotangentGeneratedByCodimension` rather
-- than by keeping a second notation-specialized local unpacking lemma.

/-- Lemma 23.8.3: let `R` be a regular ring, let `p` be a prime of `R`, and let `I` be an ideal
of `R`. Set `Rₚ = Localization.AtPrime p.asIdeal`, `Iₚ = Ideal.map (algebraMap R Rₚ) I`, and
`A = Rₚ / Iₚ`. Then the following are equivalent: `A` is a complete intersection local ring
(equivalently, its maximal-ideal completion is a complete intersection complete local ring); the
localized ideal `Iₚ ⊆ Rₚ` is generated by a regular sequence; and the localized conormal module
`(I/I²)ₚ = Iₚ / Iₚ² = Iₚ.Cotangent` can be generated by the codimension of `A` in `Rₚ`, written
in the canonical additive Krull-dimension form. -/
@[stacks 09Q1]
theorem completeIntersectionLocalRing_tfae_of_regularRing_quotient_atPrime
    :
    List.TFAE
      [ IsCompleteIntersectionLocalRing A
      , (Iₚ).IsGeneratedByRegularSequence
      , ∃ c : ℕ, ringKrullDim A + c = ringKrullDim Rₚ ∧
          ∃ x : Fin c → (Iₚ).Cotangent, Submodule.span A (Set.range x) = ⊤
      ] := sorry

/-- For a quotient of the localization of a regular ring at a prime, being a complete intersection
local ring is equivalent to the localized ideal being generated by a regular sequence. -/
theorem isCompleteIntersectionLocalRing_iff_isGeneratedByRegularSequence_of_regularRing_quotient_atPrime
    :
    IsCompleteIntersectionLocalRing A ↔ (Iₚ).IsGeneratedByRegularSequence := by
  simpa using
    List.TFAE.out (completeIntersectionLocalRing_tfae_of_regularRing_quotient_atPrime p I) 0 1 rfl rfl

omit [IsRegularRing R] in
/-- Unfolding the ideal-level codimension-count conormal owner at the localized quotient recovers
the third clause of Lemma 23.8.3 in the local notation `Rₚ`, `Iₚ`, and `A`. -/
theorem cotangentGeneratedByCodimension_iff_of_regularRing_quotient_atPrime
    :
    (Iₚ).CotangentGeneratedByCodimension ↔
      ∃ c : ℕ, ringKrullDim A + c = ringKrullDim Rₚ ∧
        ∃ x : Fin c → (Iₚ).Cotangent, Submodule.span A (Set.range x) = ⊤ := by
  simpa using Ideal.cotangentGeneratedByCodimension_iff Iₚ

/-- For a quotient of the localization of a regular ring at a prime, the localized ideal is
generated by a regular sequence if and only if its cotangent module is generated by the
codimension. -/
theorem isGeneratedByRegularSequence_iff_cotangentGeneratedByCodimension_of_regularRing_quotient_atPrime
    :
    (Iₚ).IsGeneratedByRegularSequence ↔ (Iₚ).CotangentGeneratedByCodimension := by
  rw [cotangentGeneratedByCodimension_iff_of_regularRing_quotient_atPrime]
  simpa using
    List.TFAE.out (completeIntersectionLocalRing_tfae_of_regularRing_quotient_atPrime p I) 1 2 rfl rfl

/-- For a quotient of the localization of a regular ring at a prime, being a complete intersection
local ring is equivalent to the localized cotangent module being generated by the codimension. -/
theorem isCompleteIntersectionLocalRing_iff_cotangentGeneratedByCodimension_of_regularRing_quotient_atPrime
    :
    IsCompleteIntersectionLocalRing A ↔ (Iₚ).CotangentGeneratedByCodimension := by
  rw [cotangentGeneratedByCodimension_iff_of_regularRing_quotient_atPrime]
  simpa using
    List.TFAE.out (completeIntersectionLocalRing_tfae_of_regularRing_quotient_atPrime p I) 0 2 rfl rfl

end

end
