import Mathlib
import StacksProject_2024.Chap23.Lemma_23_7_1

-- Declarations for this item will be appended below by the statement pipeline.

universe uR uR' uS uH1 uH2

open scoped BigOperators

/- Semantic search note: `lean_leansearch` pointed to the generic homology owners
`HomologicalComplex.homology` / `HomologicalComplex.cycles`, while local Chapter 23 search showed
that the current `Lemma_23_7_1` setup only packages the ring extension and the divided-power
polynomial presentation, not a concrete chain-complex owner for `A`. The statement below therefore
keeps `H₁(A)`, `H₂(A/IA)`, and the induced map `θ` on homology as explicit ambient parameters,
while making the polynomial presentation and the lifted relation data concrete. -/

section

open DifferentialGradedAlgebra

variable {R : Type uR} {R' : Type uR'} {S0 : Type uS}
variable [CommRing R] [CommRing R'] [CommRing S0] [Algebra R S0]

/-- The ideal `(f₁, ..., fₘ)` generated by the chosen polynomial presentation relations. -/
noncomputable abbrev polynomialPresentationIdeal {n m : ℕ}
    (rels : Fin m → MvPolynomial (Fin n) R) : Ideal (MvPolynomial (Fin n) R) :=
  Ideal.span (Set.range rels)

/-- Unfolding `polynomialPresentationIdeal` recovers the span of the listed defining relations. -/
theorem polynomialPresentationIdeal_eq_span {n m : ℕ}
    (rels : Fin m → MvPolynomial (Fin n) R) :
    polynomialPresentationIdeal rels = Ideal.span (Set.range rels) := sorry

/-- The class in `S/IS` represented by a polynomial lift `g' ∈ R'[x₁, ..., xₙ]` via the chosen
presentation `S0 ≃ R[x₁, ..., xₙ]/(f₁, ..., fₘ)`. This is the source element denoted `g` after
passing to `S/IS`. -/
noncomputable def liftedRelationTargetClass
    (extension : SquareZeroPrincipalExtension R' R)
    {n m : ℕ}
    (rels : Fin m → MvPolynomial (Fin n) R)
    (presentation :
      S0 ≃ₐ[R]
        MvPolynomial (Fin n) R ⧸ polynomialPresentationIdeal rels)
    (gLift : MvPolynomial (Fin n) R') :
    extension.annihilatorQuotient S0 :=
  Ideal.Quotient.mk (extension.annihilatorIdeal S0)
    (presentation.symm
      (Ideal.Quotient.mk (polynomialPresentationIdeal rels)
        (MvPolynomial.map extension.toRingHom gLift)))

/-- Expanding `liftedRelationTargetClass` gives the class of the coefficientwise image of `g'` in
`S/IS` through the chosen quotient presentation. -/
theorem liftedRelationTargetClass_def
    (extension : SquareZeroPrincipalExtension R' R)
    {n m : ℕ}
    (rels : Fin m → MvPolynomial (Fin n) R)
    (presentation :
      S0 ≃ₐ[R]
        MvPolynomial (Fin n) R ⧸ polynomialPresentationIdeal rels)
    (gLift : MvPolynomial (Fin n) R') :
    liftedRelationTargetClass extension rels presentation gLift =
      Ideal.Quotient.mk (extension.annihilatorIdeal S0)
        (presentation.symm
          (Ideal.Quotient.mk (polynomialPresentationIdeal rels)
            (MvPolynomial.map extension.toRingHom gLift))) := sorry

variable {H1A : Type uH1} {H2IA : Type uH2}
variable [AddCommGroup H1A] [AddCommGroup H2IA]

/-- Lemma 23.7.2: let `S0` be the chosen degree-zero homology ring `H₀(A)` together with a
polynomial presentation `R[x₁, ..., xₙ]/(f₁, ..., fₘ)`, let `H1A` be the chosen degree-one
homology group `H₁(A)`, let `H2IA` be the chosen second homology group `H₂(A/IA)`, and let
`θ : H₂(A/IA) → S/IS` be the map induced on homology by the derivation from Lemma 23.7.1. For a
syzygy `∑ rⱼ fⱼ = 0` whose coefficients lie in the annihilator ideal `I`, and for chosen lifts
`r'ⱼ`, `f'ⱼ`, and `g'` with `∑ r'ⱼ f'ⱼ = f g'`, there exists a class in `H₂(A/IA)` mapping to the
resulting obstruction class in `S/IS`. -/
theorem exists_secondHomologyClass_of_liftedRelation
    (extension : SquareZeroPrincipalExtension R' R)
    {n m : ℕ}
    (rels : Fin m → MvPolynomial (Fin n) R)
    (presentation :
      S0 ≃ₐ[R]
        MvPolynomial (Fin n) R ⧸ polynomialPresentationIdeal rels)
    (coeffs : Fin m → MvPolynomial (Fin n) R)
    (relation : ∑ j : Fin m, coeffs j * rels j = 0)
    (liftedCoeffs : Fin m → MvPolynomial (Fin n) R')
    (liftedRels : Fin m → MvPolynomial (Fin n) R')
    (lift_coeffs :
      ∀ j : Fin m, MvPolynomial.map extension.toRingHom (liftedCoeffs j) = coeffs j)
    (lift_rels :
      ∀ j : Fin m, MvPolynomial.map extension.toRingHom (liftedRels j) = rels j)
    (gLift : MvPolynomial (Fin n) R')
    (liftedRelation :
      ∑ j : Fin m, liftedCoeffs j * liftedRels j =
        MvPolynomial.C extension.generator * gLift)
    (coeff_mem_annihilator :
      ∀ j : Fin m, ∀ d, MvPolynomial.coeff d (coeffs j) ∈ extension.annihilator)
    (θ :
      H2IA →+ extension.annihilatorQuotient S0)
    (hH1 : Subsingleton H1A) :
    ∃ ξ : H2IA,
      θ ξ =
        liftedRelationTargetClass extension rels presentation gLift := sorry

end
