import IntroductoryLecturesOnConvexOptimization_Nesterov_2004.Compat
import IntroductoryLecturesOnConvexOptimization_Nesterov_2004.Nesterov.Chap07.Algorithm_7_12
import IntroductoryLecturesOnConvexOptimization_Nesterov_2004.Nesterov.Chap07.Definition_7_56
import IntroductoryLecturesOnConvexOptimization_Nesterov_2004.Nesterov.Chap07.Definition_7_57

-- Declarations for this item will be appended below by the statement pipeline.

open scoped BigOperators

noncomputable section

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-
Proposition 7.29 lies in the barrier-subgradient / weighted-average domain.

Mandatory domain-style sampling:
- `DualBarrierSubgradientMethod` in `Algorithm_7_12`, the source-facing owner of the iterates and
  stepsizes;
- `barrierSubgradientWeightSum` in `Theorem_7_15` and
  `barrierSubgradientAverageDualityGap_le_maximalGap` in `Lemma_7_12`, the chapter owners for
  `S_k` and the nearby averaged-gap estimate;
- `Finset.centerMass` and `ConcaveOn.le_map_centerMass`, the canonical finite weighted-average
  owner and Jensen inequality for concave functions;
- `maximalValueOn` and `barrierSubgradientMaximalGap`, the faithful `EReal` owners for the primal
  optimum `f_*` and the maximal gap `ℓ_k⋆`.

Best owner abstraction:
- source-facing: the weighted primal-value average generated by a `DualBarrierSubgradientMethod`;
- core/canonical: `Finset.centerMass` for that normalized average, together with
  `barrierSubgradientWeightSum`, `maximalValueOn`, and `barrierSubgradientMaximalGap`;
- bridge/view: the textbook quotient formula
  `(∑ λ_i f(x_i)) / (∑ λ_i)`, which is just the scalar expansion of `Finset.centerMass`.

Primitive data:
- the method owner `method : DualBarrierSubgradientMethod P f`;
- the index `k`.

Derived API:
- the scalar weighted average `centerMass` of the sampled values `f(method i)`;
- the normalization factor `barrierSubgradientWeightSum`;
- the explicit-rate specialization obtained by combining the main estimate with an assumed maximal
  gap bound.

The previous version duplicated both the denominator `S_k` and the normalized weighted average as
raw quotient expressions. This refinement keeps the proposition source-facing, but moves its public
surface to the existing weighted-average and gap owners already established earlier in the chapter.
-/

-- Proof sketch: for each feasible `y ∈ P`, concavity gives
-- `f y ≤ f(x_i) + ⟪g_i, y - x_i⟫` for every `i`. Multiply by the positive step sizes,
-- sum from `i = 0` to `k`, and then take the supremum over `y ∈ P` to identify the gap term
-- `barrierSubgradientMaximalGap ... k`.
/-- Helper for Proposition 7.29: the step-size normalization factor `S_k` is positive because
every step size in Algorithm 7.12 is positive. -/
lemma stepSize_weight_sum_pos
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) :
    0 < barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
  -- Lower-bound the whole weight sum by its strictly positive zeroth summand.
  rw [barrierSubgradientWeightSum_def]
  exact lt_of_lt_of_le (method.stepSize 0).2 <|
    Finset.single_le_sum
      (fun i _ ↦ (method.stepSize i).2.le)
      (by simp)

/-- Helper for Proposition 7.29: for each feasible point `y`, summing the affine upper supports
coming from the iterate subgradients and normalizing by `S_k` bounds `f y` by the weighted
average of the sampled values plus the normalized gap term. -/
lemma pointwise_value_le_centerMass_add_gap_ratio
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) (y : P) :
    f y ≤
      (Finset.range (k + 1)).centerMass
          (fun i ↦ (method.stepSize i : ℝ))
          (fun i ↦ f (method i)) +
        method.gapFunction k y /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
  set S : ℝ := barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k with hS
  have hS_pos : 0 < S := by
    simpa [hS] using stepSize_weight_sum_pos method k
  have hweighted :
      ∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f y ≤
        ∑ i ∈ Finset.range (k + 1),
          (method.stepSize i : ℝ) *
            (f (method i) +
              inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E))) := by
    -- Apply the concave-subgradient upper support inequality at each iterate and sum the weighted
    -- inequalities termwise.
    refine Finset.sum_le_sum ?_
    intro i hi
    have hsub_i : IsConcaveSubgradientAt f (method i : E) (method.iterateSubgradient i) := by
      simpa [DualBarrierSubgradientMethod.iterateSubgradient_eq] using
        method.subgradient_spec (method i)
    have hsupport :
        f y ≤
          f (method i) +
            inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E)) := by
      exact (isConcaveSubgradientAt_iff f (method i : E) (method.iterateSubgradient i)).mp hsub_i
        (y : E)
    exact mul_le_mul_of_nonneg_left hsupport (show 0 ≤ (method.stepSize i : ℝ) from
      (method.stepSize i).2.le)
  have hleft :
      ∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f y = S * f y := by
    rw [hS, barrierSubgradientWeightSum_def, Finset.sum_mul]
  have hright :
      ∑ i ∈ Finset.range (k + 1),
          (method.stepSize i : ℝ) *
            (f (method i) +
              inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E))) =
        (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
          method.gapFunction k y := by
    -- Split the weighted sum into the sampled-value part and the gap-function part.
    calc
      ∑ i ∈ Finset.range (k + 1),
          (method.stepSize i : ℝ) *
            (f (method i) +
              inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E))) =
          ∑ i ∈ Finset.range (k + 1),
            ((method.stepSize i : ℝ) * f (method i) +
              (method.stepSize i : ℝ) *
                inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E))) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            rw [mul_add]
      _ =
          (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
            ∑ i ∈ Finset.range (k + 1),
              (method.stepSize i : ℝ) *
                inner ℝ (method.iterateSubgradient i) ((y : E) - (method i : E)) := by
            rw [Finset.sum_add_distrib]
      _ =
          (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
            method.gapFunction k y := by
            rw [method.gapFunction_apply]
  have hsum :
      S * f y ≤
        (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
          method.gapFunction k y := by
    have hsum' := hweighted
    rw [hleft] at hsum'
    rw [hright] at hsum'
    exact hsum'
  have hS_ne : S ≠ 0 := ne_of_gt hS_pos
  have haverage :
      f y ≤
        ((∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
            method.gapFunction k y) / S := by
    -- Divide the weighted inequality by the positive normalization factor `S_k`.
    have hdiv :
        (S * f y) / S ≤
          ((∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
              method.gapFunction k y) / S := by
      exact div_le_div_of_nonneg_right hsum hS_pos.le
    simpa [hS_ne, div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm] using hdiv
  have hcenter :
      (Finset.range (k + 1)).centerMass
          (fun i ↦ (method.stepSize i : ℝ))
          (fun i ↦ f (method i)) =
        (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) / S := by
    -- Unfold `Finset.centerMass` to the normalized weighted sum formula.
    rw [Finset.centerMass, hS, barrierSubgradientWeightSum_def, div_eq_mul_inv]
    simp [smul_eq_mul, mul_comm]
  calc
    f y ≤
        ((∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) +
            method.gapFunction k y) / S := haverage
    _ =
        (∑ i ∈ Finset.range (k + 1), (method.stepSize i : ℝ) * f (method i)) / S +
          method.gapFunction k y / S := by
          rw [add_div]
    _ =
        (Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) +
          method.gapFunction k y / S := by
          rw [hcenter]
    _ =
        (Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) +
          method.gapFunction k y /
            barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
          rw [hS]

/-- Helper for Proposition 7.29: every pointwise gap evaluation is bounded above by the maximal
gap owner `ℓ_k⋆`. -/
lemma gapFunction_eval_le_maximalGap
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) (y : P) :
    ((method.gapFunction k y : ℝ) : EReal) ≤ method.maximalGap k := by
  -- Expand `ℓ_k⋆` as a supremum and use the evaluation at `y` as a witness.
  rw [DualBarrierSubgradientMethod.maximalGap_eq, barrierSubgradientMaximalGap_def]
  exact le_sSup (Set.mem_range_self y)

/-- Helper for Proposition 7.29: the real pointwise estimate lifts to `EReal`, with the gap term
replaced by the maximal-gap owner. -/
lemma pointwise_ereal_value_le_average_add_maximal_gap_ratio
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) (y : P) :
    ((f y : ℝ) : EReal) ≤
      (((Finset.range (k + 1)).centerMass
          (fun i ↦ (method.stepSize i : ℝ))
          (fun i ↦ f (method i)) : ℝ) : EReal) +
        method.maximalGap k /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
  have hpoint :=
    pointwise_value_le_centerMass_add_gap_ratio method k y
  have hpointE :
      ((f y : ℝ) : EReal) ≤
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) +
            method.gapFunction k y /
              barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k : ℝ) : EReal) := by
    exact_mod_cast hpoint
  have hgap_div :
      ((method.gapFunction k y : ℝ) : EReal) /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k ≤
        method.maximalGap k /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
    -- Divide the pointwise maximal-gap bound by the nonnegative denominator `S_k`.
    exact EReal.div_le_div_right_of_nonneg
      (by exact_mod_cast (stepSize_weight_sum_pos method k).le)
      (gapFunction_eval_le_maximalGap method k y)
  calc
    ((f y : ℝ) : EReal) ≤
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) +
            method.gapFunction k y /
              barrierSubgradientWeightSum
                (fun i ↦ (method.stepSize i : ℝ)) k : ℝ) : EReal) := hpointE
    _ =
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) +
          ((method.gapFunction k y : ℝ) : EReal) /
            barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
          simp [EReal.coe_add, EReal.coe_div]
    _ ≤
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) +
          method.maximalGap k /
            barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k := by
          simpa [add_comm] using
            add_le_add_right hgap_div
              ((((Finset.range (k + 1)).centerMass
                  (fun i ↦ (method.stepSize i : ℝ))
                  (fun i ↦ f (method i)) : ℝ) : EReal))

/-- Proposition 7.29: for a concave objective on the feasible set of the barrier subgradient
method, the weighted average of the values `f(x_i)` over the first `k + 1` iterates, written
canonically as a `Finset.centerMass`, is within `ℓ_k⋆ / S_k` of the maximal value
`f_* = maximalValueOn P f`, where `ℓ_k⋆` is `barrierSubgradientMaximalGap ... k` and
`S_k = barrierSubgradientWeightSum ... k`. -/
theorem barrierSubgradientMethod_primal_efficiency_estimate
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) (k : ℕ) :
    maximalValueOn P f -
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) ≤
      method.maximalGap k /
        barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k :=
  by
    -- Rewrite the target subtraction inequality as an upper bound on the maximal value owner.
    rw [EReal.sub_le_iff_le_add (.inl (EReal.coe_ne_bot _)) (.inl (EReal.coe_ne_top _))]
    rw [maximalValueOn_eq_sSup_image]
    -- It now suffices to bound each feasible value by the same `EReal` right-hand side.
    refine sSup_le ?_
    rintro _ ⟨y, hy, rfl⟩
    simpa [add_comm] using
      pointwise_ereal_value_le_average_add_maximal_gap_ratio method k ⟨y, hy⟩

-- Proof sketch: combine `barrierSubgradientMethod_primal_efficiency_estimate` with the explicit
-- bound assumed for `barrierSubgradientMaximalGap ... k / S_k`, where that bound is the one
-- obtained in the text from the parameter choice `(7.3.19)`.
/-- When the maximal-gap estimate produced by the parameter choice `(7.3.19)` holds, the weighted
average of the sampled values `f(x_i)` satisfies the corresponding explicit rate. -/
theorem barrierSubgradientMethod_primal_efficiency_estimate_explicit_rate
    {P : Set E} {f : E → ℝ}
    (method : DualBarrierSubgradientMethod P f) {M ν : ℝ}
    (hgap :
      ∀ k : ℕ,
        method.maximalGap k /
          barrierSubgradientWeightSum (fun i ↦ (method.stepSize i : ℝ)) k ≤
          ((2 * M *
              (Real.sqrt (ν / ((k : ℝ) + 1)) + ν / ((k : ℝ) + 1)) *
                (1 + Real.log (2 + (3 / 2 : ℝ) * Real.sqrt (ν * ((k : ℝ) + 1)))) : ℝ)))
    (k : ℕ) :
    maximalValueOn P f -
        (((Finset.range (k + 1)).centerMass
            (fun i ↦ (method.stepSize i : ℝ))
            (fun i ↦ f (method i)) : ℝ) : EReal) ≤
      ((2 * M *
          (Real.sqrt (ν / ((k : ℝ) + 1)) + ν / ((k : ℝ) + 1)) *
            (1 + Real.log (2 + (3 / 2 : ℝ) * Real.sqrt (ν * ((k : ℝ) + 1)))) : ℝ)) :=
  by
    -- Combine the abstract primal-efficiency estimate with the assumed explicit maximal-gap rate.
    exact le_trans
      (barrierSubgradientMethod_primal_efficiency_estimate method k)
      (hgap k)
