import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Definition_17_8_1 (from Chap17) -/
universe u

open AlgebraicGeometry
open TopologicalSpace

/- Domain-style sampling for Definition 17.8.1:
- primary domain: local generation of sheaves of modules on a ringed space by sections on a
  covering;
- inspected owner declarations:
  `SheafOfModules.GeneratingSections`,
  `SheafOfModules.LocalGeneratorsData`,
  `SheafOfModules.LocalGeneratorsData.IsFiniteType`,
  `SheafOfModules.IsFiniteType`;
- owner abstraction: the primitive mathlib owner data `SheafOfModules.LocalGeneratorsData`,
  specialized to the ambient category `RingedSpace.Modules X`;
- primitive data: a covering of the space together with generating sections on each restricted
  module sheaf;
- derived API: the source-facing existence predicate and its pointwise neighbourhood
  characterization.

Source/core/bridge triage:
- `source-facing`: the Stacks Project property that a sheaf is locally generated by sections;
- `core/canonical`: `Nonempty ℱ.LocalGeneratorsData`;
- `bridge/view`: the pointwise neighbourhood reformulation in
  `nonempty_localGeneratorsData_iff_pointwise`.

This item is therefore a canonical-recall item: the main entry should recall the owner
`SheafOfModules.LocalGeneratorsData`, while the source-facing existence condition is stated
directly as `Nonempty ℱ.LocalGeneratorsData` in companion declarations. -/

namespace SheafOfModules

variable {X : RingedSpace.{u}}

/- Definition 17.8.1: the canonical owner for local generation by sections on a ringed space is
`ℱ.LocalGeneratorsData`; existence of such data is exactly the source condition that `ℱ` is
locally generated by sections. -/
recall LocalGeneratorsData

/-- Any sheaf of modules of finite type is locally generated by sections. -/
instance (ℱ : RingedSpace.Modules X) [ℱ.IsFiniteType] :
    Nonempty ℱ.LocalGeneratorsData := by
  let ⟨σ, _⟩ := IsFiniteType.exists_localGeneratorsData ℱ
  exact ⟨σ⟩

-- Proof sketch: one direction extracts from `LocalGeneratorsData` an open of the chosen covering
-- containing `x`, together with the specified generating sections on that restriction. For the
-- converse, choose for each `x` a neighbourhood where the restriction is globally generated, then
-- package these neighbourhoods and generating families into `LocalGeneratorsData`.
/-- A sheaf of modules is locally generated by sections exactly when every point has an open
neighbourhood on which the restricted sheaf is generated by global sections. -/
theorem nonempty_localGeneratorsData_iff_pointwise
    (ℱ : RingedSpace.Modules X) :
    Nonempty ℱ.LocalGeneratorsData ↔
      ∀ x : X, ∃ (U : Opens X) (_ : x ∈ U), Nonempty ((ℱ.over U).GeneratingSections) := sorry

end SheafOfModules

/-! ### Lemma_17_8_2 (from Chap17) -/
noncomputable section

universe u

/- 
Domain-style sampling for Lemma 17.8.2:
- primary domain: local generation of `\mathcal O_X`-module sheaves under pullback on ringed
  spaces;
- inspected owner declarations:
  `(RingedSpace.Modules AlgebraicGeometry.RingedSpace)`,
  `SheafOfModules.LocalGeneratorsData`,
  `AlgebraicGeometry.RingedSpace.Hom.pullback`;
- best owner abstraction:
  the ambient owner category `(RingedSpace.Modules X)`, together with the primitive owner data
  `SheafOfModules.LocalGeneratorsData` and the canonical pullback functor `(f^*)`;
- primitive data:
  a morphism of ringed spaces `f : X ⟶ Y`, a module sheaf `𝒢 : (RingedSpace.Modules Y)`, and chosen local
  generator data on `𝒢`;
- derived API:
  the source-facing pullback-stability statement together with the corresponding instance-style
  propagation of `LocalGeneratorsData`.

Source/core/bridge triage:
- `source-facing`: pullback preserves the property of being locally generated by sections;
- `core/canonical`: `(RingedSpace.Modules X)`, `SheafOfModules.LocalGeneratorsData`, and `(f^*)`;
- `bridge/view`: the instance and companion theorem
  `Nonempty (((f^*).obj 𝒢).LocalGeneratorsData)`, obtained from chosen local generator data on
  `𝒢`.
-/

open AlgebraicGeometry
open scoped AlgebraicGeometry

namespace AlgebraicGeometry

variable {X Y : RingedSpace.{u}}

-- Proof sketch: choose local generating sections for `𝒢` on an open cover of `Y`, pull that
-- cover back along `f`, identify the restriction of `f^*𝒢` on each preimage with the pullback of
-- the corresponding restricted module, and use that pullback preserves the epimorphism from a free
-- module sheaf because it commutes with colimits and is right exact.
private theorem ringedSpaceModulePullback_exists_localGeneratorsData
    (f : X ⟶ Y) (𝒢 : RingedSpace.Modules Y) (h𝒢 : 𝒢.LocalGeneratorsData) :
    Nonempty (((f^*).obj 𝒢).LocalGeneratorsData) := sorry

/-- Chosen local generators data on `𝒢` pulls back to local generators data on `f^*𝒢`. -/
private noncomputable def ringedSpaceModulePullback_localGeneratorsData
    (f : X ⟶ Y) (𝒢 : RingedSpace.Modules Y) (h𝒢 : 𝒢.LocalGeneratorsData) :
    ((f^*).obj 𝒢).LocalGeneratorsData :=
  Classical.choice (ringedSpaceModulePullback_exists_localGeneratorsData f 𝒢 h𝒢)

/-- Lemma 17.8.2: for a morphism of ringed spaces
`f : (X, \mathcal O_X) \to (Y, \mathcal O_Y)`, if an `\mathcal O_Y`-module sheaf `\mathcal G`
is locally generated by sections, then its pullback `f^*\mathcal G` is locally generated by
sections. -/
theorem ringedSpaceModulePullback_nonempty_localGeneratorsData
    (f : X ⟶ Y) (𝒢 : RingedSpace.Modules Y)
    (h𝒢 : Nonempty 𝒢.LocalGeneratorsData) :
    Nonempty (((f^*).obj 𝒢).LocalGeneratorsData) := by
  rcases h𝒢 with ⟨σ⟩
  exact ⟨ringedSpaceModulePullback_localGeneratorsData f 𝒢 σ⟩

instance (f : X ⟶ Y) (𝒢 : RingedSpace.Modules Y) [h𝒢 : Nonempty 𝒢.LocalGeneratorsData] :
    Nonempty (((f^*).obj 𝒢).LocalGeneratorsData) :=
  ringedSpaceModulePullback_nonempty_localGeneratorsData f 𝒢 h𝒢

end AlgebraicGeometry
