import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open MeasureTheory MeasurableSpace ProbabilityTheory
open scoped MeasureTheory ProbabilityTheory

noncomputable section

universe u v

variable {Ω : Type u} [MeasurableSpace Ω] {I : Type v}

/- Auxiliary partition formula used to state the countable-partition conditional-expectation
identity. Following Definition 8.9, the coefficient on each atom is the canonical set average
of `X` over that atom. -/
private def countable_partition_condexp_formula
    (P : Measure Ω) (B : I → Set Ω) (X : Ω → ℝ) : Ω → ℝ :=
  fun ω ↦ ∑' i, (B i).indicator (fun _ ↦ ⨍ x in B i, X x ∂P) ω

/- On a partition atom `B i`, the textbook series formula collapses to the corresponding
event-conditioned average. -/
-- Proof sketch: in the defining `tsum`, the `i`-th indicator contributes the value
-- `⨍ x in B i, X x ∂P`, while pairwise disjointness forces every other indicator term to vanish at
-- `ω ∈ B i`.
private theorem countable_partition_condexp_formula_apply_of_mem
    (P : Measure Ω) (B : I → Set Ω) (X : Ω → ℝ)
    (h_disjoint : Pairwise fun i j ↦ Disjoint (B i) (B j)) {i : I} {ω : Ω} (hω : ω ∈ B i) :
    countable_partition_condexp_formula P B X ω = ⨍ x in B i, X x ∂P := by
  classical
  -- Collapse the partition series to the unique atom containing `ω`.
  rw [countable_partition_condexp_formula]
  rw [tsum_eq_single i]
  · simp [Set.indicator_of_mem hω]
  · intro j hj
    by_cases hωj : ω ∈ B j
    · have hω_empty : ω ∈ (∅ : Set Ω) := by
        exact (h_disjoint (i := j) (j := i) hj).le_bot ⟨hωj, hω⟩
      simp at hω_empty
    · simp [Set.indicator_of_notMem, hωj]

/-- Equation (8.6): the conditional expectation with respect to the σ-algebra generated by a
countable measurable partition is almost everywhere equal to the textbook partition formula. -/
theorem condExp_generateFrom_ae_eq_countable_partition_formula [Countable I]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (B : I → Set Ω) (hB : ∀ i, MeasurableSet (B i))
    (h_disjoint : Pairwise fun i j ↦ Disjoint (B i) (B j)) (h_cover : ⋃ i, B i = Set.univ)
    {X : Ω → ℝ} (hX : Integrable X P) :
    P[X | generateFrom (Set.range B)] =ᵐ[P]
      fun ω ↦ ∑' i, (B i).indicator (fun _ ↦ ⨍ x in B i, X x ∂P) ω := by
  classical
  simpa [countable_partition_condexp_formula] using
    (show P[X | generateFrom (Set.range B)] =ᵐ[P] countable_partition_condexp_formula P B X from
      let g : Ω → ℝ := countable_partition_condexp_formula P B X
      let coeff : I → ℝ := fun i ↦ ⨍ x in B i, X x ∂P
      have hm : generateFrom (Set.range B) ≤ ‹MeasurableSpace Ω› := by
        refine MeasurableSpace.generateFrom_le ?_
        rintro s ⟨i, rfl⟩
        exact hB i
      have hpi_range : IsPiSystem (Set.range B) := by
        intro s hs t ht hst
        rcases hs with ⟨i, rfl⟩
        rcases ht with ⟨j, rfl⟩
        by_cases hij : i = j
        · subst hij
          exact ⟨i, by ext x; simp⟩
        · exfalso
          rcases hst with ⟨x, hx⟩
          have hx_empty : x ∈ (∅ : Set Ω) := by
            exact (h_disjoint (i := i) (j := j) hij).le_bot hx
          simp at hx_empty
      let idx : Ω → I := fun ω ↦ Classical.choose <| by
        have hω_univ : ω ∈ Set.univ := by simp
        rw [← h_cover] at hω_univ
        simpa [Set.mem_iUnion] using hω_univ
      have hidx_mem : ∀ ω, ω ∈ B (idx ω) := by
        intro ω
        exact Classical.choose_spec <| by
          have hω_univ : ω ∈ Set.univ := by simp
          rw [← h_cover] at hω_univ
          simpa [Set.mem_iUnion] using hω_univ
      have hidx_preimage_singleton : ∀ i, idx ⁻¹' ({i} : Set I) = B i := by
        intro i
        ext ω
        constructor
        · intro hω
          simpa [Set.mem_singleton_iff.mp hω] using hidx_mem ω
        · intro hω
          have h_eq : idx ω = i := by
            by_contra hne
            have hω_empty : ω ∈ (∅ : Set Ω) := by
              exact (h_disjoint (i := idx ω) (j := i) hne).le_bot ⟨hidx_mem ω, hω⟩
            simp at hω_empty
          simp [h_eq]
      letI : MeasurableSpace I := ⊤
      have hidx_meas : @Measurable Ω I (generateFrom (Set.range B)) ⊤ idx := by
        refine @measurable_to_countable' I Ω ⊤ ‹Countable I› (generateFrom (Set.range B)) idx ?_
        intro i
        rw [hidx_preimage_singleton i]
        exact MeasurableSpace.measurableSet_generateFrom ⟨i, rfl⟩
      have hcoeff_meas : Measurable coeff := measurable_of_countable coeff
      have hg_on_atom : ∀ ⦃i : I⦄ ⦃ω : Ω⦄, ω ∈ B i → g ω = coeff i := by
        intro i ω hω
        change countable_partition_condexp_formula P B X ω = ⨍ x in B i, X x ∂P
        simpa [coeff] using
          (countable_partition_condexp_formula_apply_of_mem (Ω := Ω) P B X h_disjoint hω)
      have h_formula : g = fun ω ↦ coeff (idx ω) := by
        funext ω
        exact hg_on_atom (hidx_mem ω)
      have hg_meas : Measurable[generateFrom (Set.range B)] g := by
        -- Re-express the formula through the atom index map to get measurability for free.
        simpa [h_formula] using hcoeff_meas.comp hidx_meas
      have hg_strong : StronglyMeasurable[generateFrom (Set.range B)] g := by
        -- A measurable real-valued function is strongly measurable.
        exact hg_meas.stronglyMeasurable
      have h_atom_integrable : ∀ i, IntegrableOn g (B i) P := by
        intro i
        -- On each atom, the candidate formula is constant.
        refine
          (integrableOn_const (μ := P) (s := B i) (C := coeff i) (measure_ne_top P _)).congr_fun
            ?_ (hB i)
        intro ω hω
        simpa using (hg_on_atom hω).symm
      have h_atom_norm_le :
          ∀ i, ∫ x in B i, ‖g x‖ ∂P ≤ ∫ x in B i, ‖X x‖ ∂P := by
        intro i
        have hconst :
            Set.EqOn (fun x ↦ ‖g x‖) (fun _ ↦ ‖coeff i‖) (B i) := by
          intro ω hω
          change ‖g ω‖ = ‖coeff i‖
          rw [hg_on_atom hω]
        have havg :
            P.real (B i) * coeff i = ∫ x in B i, X x ∂P := by
          simpa [coeff, smul_eq_mul] using
            (measure_smul_setAverage (μ := P) (f := X) (s := B i) (measure_ne_top P (B i)))
        calc
          ∫ x in B i, ‖g x‖ ∂P = P.real (B i) * ‖coeff i‖ := by
            rw [setIntegral_congr_fun (hB i) hconst, setIntegral_const]
            rw [smul_eq_mul]
          _ = ‖P.real (B i) * coeff i‖ := by
            symm
            rw [norm_mul]
            change |P.real (B i)| * ‖coeff i‖ = P.real (B i) * ‖coeff i‖
            have hnonneg : 0 ≤ P.real (B i) := ENNReal.toReal_nonneg
            simp [abs_of_nonneg hnonneg]
          _ = ‖∫ x in B i, X x ∂P‖ := by rw [havg]
          _ ≤ ∫ x in B i, ‖X x‖ ∂P := by
            simpa using norm_integral_le_integral_norm (μ := P.restrict (B i)) X
      have hX_norm_on : IntegrableOn (fun x ↦ ‖X x‖) (⋃ i, B i) P := by
        simpa [IntegrableOn, h_cover] using hX.norm
      have hsum_X :
          Summable fun i ↦ ∫ x in B i, ‖X x‖ ∂P := by
        exact (hasSum_integral_iUnion hB h_disjoint hX_norm_on).summable
      have hsum_g :
          Summable fun i ↦ ∫ x in B i, ‖g x‖ ∂P := by
        refine Summable.of_nonneg_of_le
          (fun i ↦ integral_nonneg fun _ ↦ norm_nonneg _)
          h_atom_norm_le
          hsum_X
      have hg : Integrable g P := by
        -- Sum the atomwise `L¹` bounds over the whole partition.
        rw [← integrableOn_univ, ← h_cover]
        exact integrableOn_iUnion_of_summable_integral_norm h_atom_integrable hsum_g
      have h_atom_integral :
          ∀ i, ∫ x in B i, g x ∂P = ∫ x in B i, X x ∂P := by
        intro i
        have hconst : Set.EqOn g (fun _ ↦ coeff i) (B i) := by
          intro ω hω
          exact hg_on_atom hω
        calc
          ∫ x in B i, g x ∂P = ∫ x in B i, coeff i ∂P := by
            exact setIntegral_congr_fun (hB i) hconst
          _ = P.real (B i) * coeff i := by
            rw [setIntegral_const, smul_eq_mul]
          _ = ∫ x in B i, X x ∂P := by
            simpa [coeff, smul_eq_mul] using
              (measure_smul_setAverage (μ := P) (f := X) (s := B i) (measure_ne_top P (B i)))
      have hg_on_union : IntegrableOn g (⋃ i, B i) P := by
        simpa [IntegrableOn, h_cover] using hg
      have hX_on_union : IntegrableOn X (⋃ i, B i) P := by
        simpa [IntegrableOn, h_cover] using hX
      have h_integral : ∫ x, g x ∂P = ∫ x, X x ∂P := by
        calc
          ∫ x, g x ∂P = ∫ x in ⋃ i, B i, g x ∂P := by rw [h_cover, setIntegral_univ]
          _ = ∑' i, ∫ x in B i, g x ∂P := integral_iUnion hB h_disjoint hg_on_union
          _ = ∑' i, ∫ x in B i, X x ∂P := by exact tsum_congr h_atom_integral
          _ = ∫ x in ⋃ i, B i, X x ∂P := by
            symm
            exact integral_iUnion hB h_disjoint hX_on_union
          _ = ∫ x, X x ∂P := by rw [h_cover, setIntegral_univ]
      have h_set_integral :
          ∀ s : Set Ω, MeasurableSet[generateFrom (Set.range B)] s →
            ∫ x in s, g x ∂P = ∫ x in s, X x ∂P := by
        -- Route correction: reduce the generated σ-algebra to atom integrals and close by
        -- `induction_on_inter` instead of trying to manipulate the raw `tsum` on arbitrary sets.
        have h_generate :
            generateFrom (Set.range B) = generateFrom (insert ∅ (Set.range B)) := by
          exact (MeasurableSpace.generateFrom_insert_empty (S := Set.range B)).symm
        refine MeasurableSpace.induction_on_inter h_generate hpi_range.insert_empty ?_ ?_ ?_ ?_
        · simp
        · intro t ht
          rcases ht with rfl | ⟨i, rfl⟩
          · simp
          · exact h_atom_integral i
        · intro t ht h_ind
          have ht' : MeasurableSet t := hm (s := t) ht
          calc
            ∫ x in tᶜ, g x ∂P = ∫ x, g x ∂P - ∫ x in t, g x ∂P :=
              setIntegral_compl ht' hg
            _ = ∫ x, X x ∂P - ∫ x in t, X x ∂P := by rw [h_integral, h_ind]
            _ = ∫ x in tᶜ, X x ∂P := (setIntegral_compl ht' hX).symm
        · intro f hfd hfm hf
          have hfm' : ∀ i, MeasurableSet (f i) := fun i ↦ hm (s := f i) (hfm i)
          calc
            ∫ x in ⋃ i, f i, g x ∂P = ∑' i, ∫ x in f i, g x ∂P := by
              exact integral_iUnion hfm' hfd
                (hg.integrableOn.mono_set <| Set.iUnion_subset fun _ ↦ Set.subset_univ _)
            _ = ∑' i, ∫ x in f i, X x ∂P := by exact tsum_congr hf
            _ = ∫ x in ⋃ i, f i, X x ∂P := by
              symm
              exact integral_iUnion hfm' hfd
                (hX.integrableOn.mono_set <| Set.iUnion_subset fun _ ↦ Set.subset_univ _)
      -- Finish with the uniqueness theorem for conditional expectation.
      (ae_eq_condExp_of_forall_setIntegral_eq hm hX
        (fun s _ _ ↦ hg.integrableOn)
        (fun s hs hPs ↦ h_set_integral s hs)
        hg_strong.aestronglyMeasurable).symm)
