import IntroductoryLecturesOnConvexOptimization_Nesterov_2004.Chap02.Theorem_2_14
#check summable_geometric_of_abs_lt_1
#check tsum_geometric_of_abs_lt_1
#check Memℓp
#check memℓp_gen
#check lp.norm_rpow_eq_tsum
#check HasGradientAt
#check ContinuousLinearMap.id
#check IsStrongConvexSmoothObjective.translate
#check IsMinOn
#check isMinOn_univ_iff
#check Submodule.span_induction
#check ContDiff.differentiable_one
