import StacksProject_2024.Chap10.«10_69_0_1».AssociatedGradedBasic

open Polynomial
open scoped BigOperators TensorProduct Pointwise

universe u v

noncomputable section

namespace RingTheory.Sequence

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M]

/-- The product `∏ f_i^{e_i}` attached to a monomial exponent `e`. -/
def quasiRegularAssociatedGradedMonomialWeight
    (rs : List R) (e : Fin rs.length →₀ ℕ) : R :=
  ∏ i : Fin rs.length, rs.get i ^ e i

omit [CommRing R] in
/-- Helper for 10.69.0.1: total degree is additive on monomial exponents. -/
theorem quasiRegularTotalDegree_add {rs : List R}
    (e f : Fin rs.length →₀ ℕ) :
    quasiRegularTotalDegree (e + f) =
      quasiRegularTotalDegree e + quasiRegularTotalDegree f := by
  -- Use that `Finsupp.degree` is an additive monoid homomorphism.
  simpa [quasiRegularTotalDegree] using
    (Finsupp.degree : (Fin rs.length →₀ ℕ) →+ ℕ).map_add e f

/-- Helper for 10.69.0.1: monomial weights multiply by adding the exponent vectors. -/
theorem quasiRegularAssociatedGradedMonomialWeight_add (rs : List R)
    (e f : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedMonomialWeight rs e *
      quasiRegularAssociatedGradedMonomialWeight rs f =
    quasiRegularAssociatedGradedMonomialWeight rs (e + f) := by
  -- Rewrite the product of monomial weights as a pointwise product and simplify each exponent.
  unfold quasiRegularAssociatedGradedMonomialWeight
  rw [← Finset.prod_mul_distrib]
  congr with i
  rw [Finsupp.add_apply, pow_add]

-- Proof sketch: each factor `rs.get i ^ e i` lies in the corresponding power of the ideal
-- generated by `rs`; multiplying these contributions places the whole product in the power whose
-- exponent is the total degree of `e`.
/-- The monomial weight attached to `e` lies in the corresponding power of the ideal generated by
the sequence `rs`. -/
theorem quasiRegularAssociatedGradedMonomialWeight_mem_pow (rs : List R)
    (e : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedMonomialWeight rs e ∈
      (quasiRegularIdeal rs) ^ quasiRegularTotalDegree e := by
  -- Each factor `rs.get i ^ e i` lies in `J ^ e i`, so their product lies in the product of
  -- those powers, which simplifies to `J ^ (∑ i, e i)`.
  have hprod :
      quasiRegularAssociatedGradedMonomialWeight rs e ∈
        ∏ i : Fin rs.length, (quasiRegularIdeal rs) ^ e i := by
    refine Ideal.prod_mem_prod ?_
    intro i hi
    have hmem : rs.get i ∈ quasiRegularIdeal rs := by
      exact Ideal.subset_span (by simpa using List.getElem_mem rs i)
    exact Ideal.pow_mem_pow hmem (e i)
  simpa [quasiRegularAssociatedGradedMonomialWeight, quasiRegularTotalDegree,
    Finsupp.degree_eq_sum, Finset.prod_pow_eq_pow_sum] using hprod

-- Proof sketch: combine membership of the monomial weight in `J^|e|` with the description of
-- `J^|e| M` as `(J^|e|) • ⊤`.
/-- Multiplying an element of `M` by the monomial weight lands in the appropriate graded piece
submodule `J^|e| M`. -/
theorem quasiRegularAssociatedGradedMonomialWeight_smul_mem
    (rs : List R) (e : Fin rs.length →₀ ℕ)
    (m : M) :
    quasiRegularAssociatedGradedMonomialWeight rs e • m ∈
      quasiRegularStage rs M (quasiRegularTotalDegree e) := by
  -- View the graded stage as `(J ^ |e|) • ⊤` and use the ideal-power membership just proved.
  simpa [quasiRegularStage, idealAssociatedGradedStage] using
    (Submodule.smul_mem_smul
      (quasiRegularAssociatedGradedMonomialWeight_mem_pow rs e)
      (by simp : m ∈ (⊤ : Submodule R M)))

/-- Multiplication by the monomial weight on the `n`-th stage `J^n M`. -/
theorem quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ)
    (m : quasiRegularStage rs M n) :
    ((quasiRegularAssociatedGradedMonomialWeight rs e) •
        (quasiRegularStage rs M n).subtype) m ∈
      quasiRegularStage rs M (n + quasiRegularTotalDegree e) := by
  -- Move the target stage back to the explicit submodule `(J^|e|) • (J^n M)`.
  rw [quasiRegularStage,
    ← idealAssociatedGradedStage_pow_smul_eq
      (I := quasiRegularIdeal rs) (M := M) (d := quasiRegularTotalDegree e) (n := n)]
  exact Submodule.smul_mem_smul
    (quasiRegularAssociatedGradedMonomialWeight_mem_pow rs e) m.2

/-- Multiplication by the monomial weight, followed by passage to the quotient
`J^|e| M / J^(|e| + 1) M`. -/
def quasiRegularAssociatedGradedMonomialMapToPiece (rs : List R) (e : Fin rs.length →₀ ℕ) :
    M →ₗ[R]
      quasiRegularAssociatedGradedInternalPiece rs M (quasiRegularTotalDegree e) :=
  (Submodule.mkQ (quasiRegularDenominator rs M (quasiRegularTotalDegree e))).comp
    (LinearMap.codRestrict
      (quasiRegularStage rs M (quasiRegularTotalDegree e))
      ((quasiRegularAssociatedGradedMonomialWeight rs e) • (LinearMap.id : M →ₗ[R] M))
      (quasiRegularAssociatedGradedMonomialWeight_smul_mem rs e))

-- Proof sketch: if `m ∈ J M`, then multiplying by a degree-`|e|` monomial weight moves it into
-- `J^(|e| + 1) M`, which is zero in the quotient defining the graded piece.
/-- The monomial map to the graded piece vanishes on `J M`, so it factors through `M / J M`. -/
theorem quasiRegularAssociatedGradedMonomialMapToPiece_ker_le (rs : List R)
    (e : Fin rs.length →₀ ℕ) :
    ((quasiRegularIdeal rs) • ⊤ : Submodule R M) ≤
      LinearMap.ker
        (quasiRegularAssociatedGradedMonomialMapToPiece rs e) := by
  intro x hx
  -- Rewrite the quotient-zero test as denominator membership in the target graded piece.
  rw [LinearMap.mem_ker]
  change
    Submodule.Quotient.mk
      (⟨quasiRegularAssociatedGradedMonomialWeight rs e • x,
        quasiRegularAssociatedGradedMonomialWeight_smul_mem rs e x⟩ :
        quasiRegularStage rs M (quasiRegularTotalDegree e)) = 0
  rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_smul_top_iff]
  change quasiRegularAssociatedGradedMonomialWeight rs e • x ∈
    (quasiRegularIdeal rs) • quasiRegularStage rs M (quasiRegularTotalDegree e)
  -- Transport the target denominator back to `(J^|e|) • (J M)`.
  have hdenom :
      (((quasiRegularIdeal rs) ^ quasiRegularTotalDegree e) •
          ((quasiRegularIdeal rs) • idealAssociatedGradedStage (quasiRegularIdeal rs) M 0) :
            Submodule R M) =
        (quasiRegularIdeal rs) • quasiRegularStage rs M (quasiRegularTotalDegree e) := by
    simpa [quasiRegularStage] using
      (idealAssociatedGradedDenominator_pow_smul_eq
        (I := quasiRegularIdeal rs) (M := M) (d := quasiRegularTotalDegree e) (n := 0))
  rw [← hdenom]
  have hx_zero :
      x ∈ (quasiRegularIdeal rs) • idealAssociatedGradedStage (quasiRegularIdeal rs) M 0 := by
    simpa [idealAssociatedGradedStage] using hx
  simpa [idealAssociatedGradedStage] using
    (Submodule.smul_mem_smul
      (quasiRegularAssociatedGradedMonomialWeight_mem_pow rs e)
      hx_zero :
      quasiRegularAssociatedGradedMonomialWeight rs e • x ∈
        (((quasiRegularIdeal rs) ^ quasiRegularTotalDegree e) •
          ((quasiRegularIdeal rs) • idealAssociatedGradedStage (quasiRegularIdeal rs) M 0) :
            Submodule R M))

/-- The map `M / J M → J^|e| M / J^(|e| + 1) M` determined by the monomial exponent `e`. -/
def quasiRegularAssociatedGradedMonomialMap (rs : List R) (e : Fin rs.length →₀ ℕ) :
    M ⧸ ((quasiRegularIdeal rs) • ⊤ : Submodule R M) →ₗ[R]
      quasiRegularAssociatedGradedInternalPiece rs M (quasiRegularTotalDegree e) :=
  Submodule.liftQ
    ((quasiRegularIdeal rs) • ⊤ : Submodule R M)
    (quasiRegularAssociatedGradedMonomialMapToPiece rs e)
    (quasiRegularAssociatedGradedMonomialMapToPiece_ker_le rs e)

/-- The class of `(\prod_i f_i^{e_i}) • m` in the degree-`|e|` graded piece. -/
def quasiRegularAssociatedGradedInternalMonomialClass (rs : List R) (m : M)
    (e : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedInternalPiece rs M (quasiRegularTotalDegree e) :=
  Submodule.Quotient.mk
    ⟨quasiRegularAssociatedGradedMonomialWeight rs e • m,
      quasiRegularAssociatedGradedMonomialWeight_smul_mem rs e m⟩

-- Proof sketch: unfold the quotient lift defining
-- `quasiRegularAssociatedGradedMonomialMap`; on a representative `m : M` it is defined by the
-- class of `(\prod_i f_i^{e_i}) • m` in `J^|e| M / J^(|e| + 1) M`.
/-- On a representative `m : M`, the monomial map sends the class of `m` to the class of
`(\prod_i f_i^{e_i}) • m` in the degree-`|e|` graded piece. -/
theorem quasiRegularAssociatedGradedMonomialMap_mk (rs : List R) (m : M)
    (e : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedMonomialMap rs e
        (Submodule.Quotient.mk m) =
      quasiRegularAssociatedGradedInternalMonomialClass rs m e := by
  -- Unfold the quotient lift: on representatives the map is defined by the corresponding class.
  rw [quasiRegularAssociatedGradedMonomialMap, Submodule.liftQ_apply]
  rfl

/-- Multiplication by the monomial weight on the stage `J^n M`. -/
def quasiRegularAssociatedGradedMonomialMapOnStage
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ) :
    quasiRegularStage rs M n →ₗ[R]
      quasiRegularStage rs M (n + quasiRegularTotalDegree e) :=
  LinearMap.codRestrict
    (quasiRegularStage rs M (n + quasiRegularTotalDegree e))
    ((quasiRegularAssociatedGradedMonomialWeight rs e) • (quasiRegularStage rs M n).subtype)
    (quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage rs n e)

/-- Multiplication by the monomial weight sends the denominator `J (J^n M)` into the denominator
of `J^(n + |e|) M / J^(n + |e| + 1) M`. -/
theorem quasiRegularAssociatedGradedMonomialMapOnStage_denominator_le
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ) :
    quasiRegularDenominator rs M n ≤
      (quasiRegularDenominator rs M (n + quasiRegularTotalDegree e)).comap
        (quasiRegularAssociatedGradedMonomialMapOnStage rs n e) := by
  intro x hx
  rw [Submodule.mem_smul_top_iff] at hx
  -- Unpack denominator membership in the codomain quotient as membership in `J (J^(n + |e|) M)`.
  rw [Submodule.mem_comap, Submodule.mem_smul_top_iff]
  change
    quasiRegularAssociatedGradedMonomialWeight rs e •
        ((quasiRegularStage rs M n).subtype x) ∈
      (quasiRegularIdeal rs) • quasiRegularStage rs M (n + quasiRegularTotalDegree e)
  -- Rewrite the target denominator as `(J^|e|) • (J (J^n M))` and use `x ∈ J (J^n M)`.
  rw [quasiRegularStage,
    ← idealAssociatedGradedDenominator_pow_smul_eq
      (I := quasiRegularIdeal rs) (M := M) (d := quasiRegularTotalDegree e) (n := n)]
  exact Submodule.smul_mem_smul
    (quasiRegularAssociatedGradedMonomialWeight_mem_pow rs e) hx

/-- The monomial map on the `n`-th graded piece of the associated graded module. -/
def quasiRegularAssociatedGradedMonomialMapOnPiece
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedInternalPiece rs M n →ₗ[R]
      quasiRegularAssociatedGradedInternalPiece rs M (n + quasiRegularTotalDegree e) :=
  Submodule.mapQ
    (quasiRegularDenominator rs M n)
    (quasiRegularDenominator rs M (n + quasiRegularTotalDegree e))
    (quasiRegularAssociatedGradedMonomialMapOnStage rs n e)
    (quasiRegularAssociatedGradedMonomialMapOnStage_denominator_le rs n e)

-- Route correction: compute the quotient-piece monomial operators on representatives first, then
-- lift those formulas to homogeneous generators of the direct sum.

/-- Helper for 10.69.0.1: on a quotient representative, `mapQ` is the expected monomial-weight
action on the underlying stage element. -/
theorem quasiRegularAssociatedGradedMonomialMapOnPiece_mk
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ)
    (m : quasiRegularStage rs M n) :
    quasiRegularAssociatedGradedMonomialMapOnPiece rs n e (Submodule.Quotient.mk m) =
      Submodule.Quotient.mk
        ⟨quasiRegularAssociatedGradedMonomialWeight rs e • (m : M),
          quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage rs n e m⟩ := by
  -- Unfold only the quotient map and evaluate it on the chosen representative.
  rw [quasiRegularAssociatedGradedMonomialMapOnPiece, Submodule.mapQ_apply]
  rfl

/-- Helper for 10.69.0.1: the zero exponent acts trivially on each quotient piece. -/
-- TODO(10.69.0.1): reduce this quotient-level identity to representative computations using the
-- `Submodule.mapQ` API without relying on the currently failing eliminator elaboration.
theorem quasiRegularAssociatedGradedMonomialMapOnPiece_zero
    (rs : List R) (n : ℕ)
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    quasiRegularAssociatedGradedMonomialMapOnPiece rs n (0 : Fin rs.length →₀ ℕ) z = z := by
  -- Compute the quotient-piece map on one representative and simplify the zero monomial weight.
  refine Quotient.inductionOn z ?_
  intro m
  simpa [quasiRegularAssociatedGradedMonomialWeight, quasiRegularTotalDegree] using
    (quasiRegularAssociatedGradedMonomialMapOnPiece_mk
      (M := M) rs n (0 : Fin rs.length →₀ ℕ) m)

/-- The action of a monomial on the associated graded module. -/
def quasiRegularAssociatedGradedMonomialAction
    (rs : List R) (e : Fin rs.length →₀ ℕ) :
    quasiRegularAssociatedGradedInternal rs M →ₗ[R]
      quasiRegularAssociatedGradedInternal rs M :=
  DirectSum.toModule R ℕ (quasiRegularAssociatedGradedInternal rs M) fun n ↦
    ((DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M)
        (n + quasiRegularTotalDegree e)).restrictScalars R).comp
      (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e)

/-- Helper for 10.69.0.1: the monomial action sends a homogeneous generator in degree `n` to the
corresponding homogeneous generator in degree `n + |e|`. -/
theorem quasiRegularAssociatedGradedMonomialAction_lof
    (rs : List R) (n : ℕ) (e : Fin rs.length →₀ ℕ)
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    quasiRegularAssociatedGradedMonomialAction rs e
        (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M) n z) =
      DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M)
        (n + quasiRegularTotalDegree e)
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z) := by
  -- `DirectSum.toModule` evaluates on a single homogeneous generator by the defining branch.
  change
    (DirectSum.toModule R ℕ (quasiRegularAssociatedGradedInternal rs M) fun n ↦
        ((DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
            (quasiRegularAssociatedGradedInternalPiece rs M)
            (n + quasiRegularTotalDegree e)).restrictScalars R).comp
          (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e))
      ((DirectSum.lof R ℕ (quasiRegularAssociatedGradedInternalPiece rs M) n) z) =
    (((DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M)
          (n + quasiRegularTotalDegree e)).restrictScalars R).comp
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e)) z
  exact DirectSum.toModule_lof
    (R := R)
    (ι := ℕ)
    (M := quasiRegularAssociatedGradedInternalPiece rs M)
    (N := quasiRegularAssociatedGradedInternal rs M)
    (φ := fun n ↦
      ((DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M)
          (n + quasiRegularTotalDegree e)).restrictScalars R).comp
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e))
    n z

/-- Helper for 10.69.0.1: transporting a stage element along an equality of degrees does not
change its underlying module element. -/
theorem quasiRegularStage_cast_coe_eq
    (rs : List R) {n n' : ℕ} (h : n = n')
    (x : quasiRegularStage rs M n) :
    (((cast (congrArg (fun k ↦ ↥(quasiRegularStage rs M k)) h) x :
      quasiRegularStage rs M n') : M)) = x := by
  cases h
  rfl

/-- Helper for 10.69.0.1: quotienting commutes with transport between equal-degree internal
pieces. -/
theorem quasiRegularAssociatedGradedInternalPiece_cast_mk_eq
    (rs : List R) {n n' : ℕ} (h : n = n')
    (x : quasiRegularStage rs M n) :
    (Submodule.Quotient.mk
      (cast (congrArg (fun k ↦ ↥(quasiRegularStage rs M k)) h) x) :
      quasiRegularAssociatedGradedInternalPiece rs M n') =
      cast (congrArg (quasiRegularAssociatedGradedInternalPiece rs M) h)
        (Submodule.Quotient.mk x : quasiRegularAssociatedGradedInternalPiece rs M n) := by
  cases h
  rfl

/-- Helper for 10.69.0.1: `DirectSum.lof` is unchanged by transporting the homogeneous piece along
an equality of degrees. -/
theorem quasiRegularAssociatedGraded_lof_cast_eq
    (rs : List R) {n n' : ℕ} (h : n = n')
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
      (quasiRegularAssociatedGradedInternalPiece rs M) n'
      (cast (congrArg (quasiRegularAssociatedGradedInternalPiece rs M) h) z) =
    DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
      (quasiRegularAssociatedGradedInternalPiece rs M) n z := by
  cases h
  rfl

/-- Helper for 10.69.0.1: composing the quotient-piece monomial maps corresponds to adding
exponents, after the canonical graded-index cast. -/
theorem quasiRegularAssociatedGradedMonomialMapOnPiece_add
    (rs : List R) (n : ℕ) (e f : Fin rs.length →₀ ℕ)
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    cast (by rw [quasiRegularTotalDegree_add, Nat.add_assoc])
      (quasiRegularAssociatedGradedMonomialMapOnPiece rs (n + quasiRegularTotalDegree e) f
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z)) =
      quasiRegularAssociatedGradedMonomialMapOnPiece rs n (e + f) z := by
  refine Quotient.inductionOn z ?_
  intro m
  let x :
      quasiRegularStage rs M
        ((n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f) :=
    ⟨quasiRegularAssociatedGradedMonomialWeight rs f •
        (quasiRegularAssociatedGradedMonomialWeight rs e • (m : M)),
      quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage rs
        (n + quasiRegularTotalDegree e) f
        ⟨quasiRegularAssociatedGradedMonomialWeight rs e • (m : M),
          quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage rs n e m⟩⟩
  let y :
      quasiRegularStage rs M (n + quasiRegularTotalDegree (e + f)) :=
    ⟨quasiRegularAssociatedGradedMonomialWeight rs (e + f) • (m : M),
      quasiRegularAssociatedGradedMonomialWeight_smul_mem_stage rs n (e + f) m⟩
  have h :
      (n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f =
        n + quasiRegularTotalDegree (e + f) := by
    rw [quasiRegularTotalDegree_add, Nat.add_assoc]
  have hxy :
      cast (congrArg (fun k ↦ ↥(quasiRegularStage rs M k)) h) x = y := by
    apply Subtype.ext
    calc
      (((cast (congrArg (fun k ↦ ↥(quasiRegularStage rs M k)) h) x :
          quasiRegularStage rs M (n + quasiRegularTotalDegree (e + f))) : M)) = x := by
            exact quasiRegularStage_cast_coe_eq (M := M) rs h x
      _ = y := by
            simp [x, y, quasiRegularAssociatedGradedMonomialWeight_add, smul_smul, mul_comm]
  have hmk :
      cast (congrArg (quasiRegularAssociatedGradedInternalPiece rs M) h)
        (Submodule.Quotient.mk x :
          quasiRegularAssociatedGradedInternalPiece rs M
            ((n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f)) =
      (Submodule.Quotient.mk y :
        quasiRegularAssociatedGradedInternalPiece rs M
          (n + quasiRegularTotalDegree (e + f))) := by
    calc
      cast (congrArg (quasiRegularAssociatedGradedInternalPiece rs M) h)
          (Submodule.Quotient.mk x :
            quasiRegularAssociatedGradedInternalPiece rs M
              ((n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f)) =
        (Submodule.Quotient.mk
          (cast (congrArg (fun k ↦ ↥(quasiRegularStage rs M k)) h) x) :
            quasiRegularAssociatedGradedInternalPiece rs M
              (n + quasiRegularTotalDegree (e + f))) := by
              symm
              exact quasiRegularAssociatedGradedInternalPiece_cast_mk_eq
                (M := M) rs h x
      _ = Submodule.Quotient.mk y := by rw [hxy]
  simpa [x, y, h, quasiRegularAssociatedGradedMonomialMapOnPiece_mk] using hmk

/-- Helper for 10.69.0.1: successive monomial actions on a homogeneous generator correspond to
adding the exponent vectors. -/
theorem quasiRegularAssociatedGradedMonomialAction_comp_lof
    (rs : List R) (n : ℕ) (e f : Fin rs.length →₀ ℕ)
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    quasiRegularAssociatedGradedMonomialAction rs f
        (quasiRegularAssociatedGradedMonomialAction rs e
          (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M) n z)) =
      quasiRegularAssociatedGradedMonomialAction rs (e + f)
        (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M) n z) := by
  let h :
      (n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f =
        n + quasiRegularTotalDegree (e + f) := by
    rw [quasiRegularTotalDegree_add, Nat.add_assoc]
  calc
    quasiRegularAssociatedGradedMonomialAction rs f
        (quasiRegularAssociatedGradedMonomialAction rs e
          (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
            (quasiRegularAssociatedGradedInternalPiece rs M) n z)) =
      quasiRegularAssociatedGradedMonomialAction rs f
        (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M)
          (n + quasiRegularTotalDegree e)
          (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z)) := by
            rw [quasiRegularAssociatedGradedMonomialAction_lof]
    _ =
      DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M)
        ((n + quasiRegularTotalDegree e) + quasiRegularTotalDegree f)
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs (n + quasiRegularTotalDegree e) f
          (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z)) := by
            simpa using quasiRegularAssociatedGradedMonomialAction_lof
              (M := M) rs (n + quasiRegularTotalDegree e) f
              (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z)
    _ =
      DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M)
        (n + quasiRegularTotalDegree (e + f))
        (cast (congrArg (quasiRegularAssociatedGradedInternalPiece rs M) h)
          (quasiRegularAssociatedGradedMonomialMapOnPiece rs (n + quasiRegularTotalDegree e) f
            (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z))) := by
              simpa using
                (quasiRegularAssociatedGraded_lof_cast_eq (M := M) rs h
                  (quasiRegularAssociatedGradedMonomialMapOnPiece rs
                    (n + quasiRegularTotalDegree e) f
                    (quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z))).symm
    _ =
      DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M)
        (n + quasiRegularTotalDegree (e + f))
        (quasiRegularAssociatedGradedMonomialMapOnPiece rs n (e + f) z) := by
              rw [quasiRegularAssociatedGradedMonomialMapOnPiece_add (M := M) rs n e f z]
    _ =
      quasiRegularAssociatedGradedMonomialAction rs (e + f)
        (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M) n z) := by
            simpa using (quasiRegularAssociatedGradedMonomialAction_lof
              (M := M) rs n (e + f) z
              ).symm

/-- Helper for 10.69.0.1: the zero exponent acts trivially on the whole internal direct sum. -/
-- TODO(10.69.0.1): prove this by `DirectSum.induction_on` after the zero-action formula on each
-- quotient piece has been repaired.
theorem quasiRegularAssociatedGradedMonomialAction_zero
    (rs : List R) (x : quasiRegularAssociatedGradedInternal rs M) :
    quasiRegularAssociatedGradedMonomialAction rs (0 : Fin rs.length →₀ ℕ) x = x := by
  induction x using DirectSum.induction_on with
  | zero =>
      -- The zero direct-sum element is fixed by any linear endomorphism.
      simp
  | of n z =>
      -- On a homogeneous generator, reduce to the degreewise zero-exponent computation.
      simpa [quasiRegularTotalDegree, quasiRegularAssociatedGradedMonomialMapOnPiece_zero
        (M := M) rs n z] using
        (quasiRegularAssociatedGradedMonomialAction_lof
          (M := M) rs n (0 : Fin rs.length →₀ ℕ) z)
  | add x y hx hy =>
      -- Extend from generators to arbitrary direct-sum elements by additivity.
      simp [map_add, hx, hy]

/-- Helper for 10.69.0.1: composing monomial actions on the whole internal direct sum corresponds
to adding exponent vectors. -/
theorem quasiRegularAssociatedGradedMonomialAction_add
    (rs : List R) (e f : Fin rs.length →₀ ℕ)
    (x : quasiRegularAssociatedGradedInternal rs M) :
    quasiRegularAssociatedGradedMonomialAction rs f
        (quasiRegularAssociatedGradedMonomialAction rs e x) =
      quasiRegularAssociatedGradedMonomialAction rs (e + f) x := by
  induction x using DirectSum.induction_on with
  | zero =>
      -- The linear monomial actions both send `0` to `0`.
      simp
  | of n z =>
      -- Reduce to the generator computation proved just above.
      exact quasiRegularAssociatedGradedMonomialAction_comp_lof
        (rs := rs) (n := n) (e := e) (f := f) z
  | add x y hx hy =>
      -- Extend from generators to arbitrary direct-sum elements by additivity.
      simp [map_add, hx, hy]

/-- The polynomial action on the associated graded module defined by the monomial operators above.
-/
def quasiRegularAssociatedGradedPolynomialSmul (rs : List R)
    (p : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs)) :
    quasiRegularAssociatedGradedInternal rs M →
      quasiRegularAssociatedGradedInternal rs M :=
  fun x ↦ Finsupp.sum p fun e a ↦ a • quasiRegularAssociatedGradedMonomialAction rs e x

instance quasiRegularAssociatedGradedInternalSMul (rs : List R) :
    SMul (MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
      (quasiRegularAssociatedGradedInternal rs M) where
  smul p x := quasiRegularAssociatedGradedPolynomialSmul rs p x

/-- Helper for 10.69.0.1: a single monomial polynomial acts by its coefficient times the matching
monomial action. -/
theorem quasiRegularAssociatedGradedPolynomialSmul_monomial
    (rs : List R) (a : R ⧸ Ideal.ofList rs) (e : Fin rs.length →₀ ℕ)
    (x : quasiRegularAssociatedGradedInternal rs M) :
    (MvPolynomial.monomial e a) • x =
      a • quasiRegularAssociatedGradedMonomialAction rs e x := by
  -- Collapse the defining polynomial sum to its unique nonzero monomial term.
  change quasiRegularAssociatedGradedPolynomialSmul rs (MvPolynomial.monomial e a) x =
    a • quasiRegularAssociatedGradedMonomialAction rs e x
  simpa [quasiRegularAssociatedGradedPolynomialSmul] using
    (MvPolynomial.sum_monomial_eq
      (u := e) (r := a)
      (b := fun d b ↦ b • quasiRegularAssociatedGradedMonomialAction rs d x))

theorem quasiRegularAssociatedGradedInternal_one_smul
    (rs : List R) (x : quasiRegularAssociatedGradedInternal rs M) :
    (1 : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs)) • x = x := by
  -- Rewrite `1` as the zero monomial and use the zero-exponent action computation.
  rw [MvPolynomial.one_def, quasiRegularAssociatedGradedPolynomialSmul_monomial]
  simpa using quasiRegularAssociatedGradedMonomialAction_zero (rs := rs) (x := x)

-- TODO(10.69.0.1): split the finite-support polynomial sum in a way compatible with the current
-- `Finsupp.sum` elaboration, then recover additivity of the polynomial action.
/-- Helper for 10.69.0.1: the custom polynomial action is additive in the polynomial argument. -/
theorem quasiRegularAssociatedGradedPolynomialSmul_add_split
    (rs : List R) (p q : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
    (x : quasiRegularAssociatedGradedInternal rs M) :
    quasiRegularAssociatedGradedPolynomialSmul rs (p + q) x =
      quasiRegularAssociatedGradedPolynomialSmul rs p x +
        quasiRegularAssociatedGradedPolynomialSmul rs q x := by
  unfold quasiRegularAssociatedGradedPolynomialSmul
  exact Finsupp.sum_add_index'
    (fun _ => zero_smul _ _)
    (fun _ _ _ => add_smul _ _ _)

theorem quasiRegularAssociatedGradedInternal_add_smul
    (rs : List R) (p q : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
    (x : quasiRegularAssociatedGradedInternal rs M) :
    (p + q) • x = p • x + q • x := by
  -- Route correction: once the defining finite-support sum is split, scalar additivity is exact.
  exact quasiRegularAssociatedGradedPolynomialSmul_add_split (M := M) rs p q x

-- TODO(10.69.0.1): evaluate the defining finite-support sum of the zero polynomial directly.
theorem quasiRegularAssociatedGradedInternal_zero_smul
    (rs : List R) (x : quasiRegularAssociatedGradedInternal rs M) :
    (0 : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs)) • x = 0 := by
  -- Unfold the custom scalar action and evaluate the empty finite-support sum for `0`.
  change quasiRegularAssociatedGradedPolynomialSmul rs 0 x = 0
  rfl

-- TODO(10.69.0.1): recover right-additivity of the polynomial action once the scalar-additivity
-- lemma above is repaired.
theorem quasiRegularAssociatedGradedInternal_smul_zero
    (rs : List R) (p : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs)) :
    p • (0 : quasiRegularAssociatedGradedInternal rs M) = 0 := by
  -- Each monomial operator is linear, so every summand in the defining polynomial action vanishes.
  change quasiRegularAssociatedGradedPolynomialSmul rs p 0 = 0
  simp [quasiRegularAssociatedGradedPolynomialSmul]

-- TODO(10.69.0.1): prove distributivity over the direct-sum argument by induction on the
-- polynomial once `add_smul` is stabilized.
theorem quasiRegularAssociatedGradedInternal_smul_add
    (rs : List R) (p : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
    (x y : quasiRegularAssociatedGradedInternal rs M) :
    p • (x + y) = p • x + p • y := by
  induction p using MvPolynomial.induction_on' with
  | monomial e a =>
      rw [quasiRegularAssociatedGradedPolynomialSmul_monomial,
        quasiRegularAssociatedGradedPolynomialSmul_monomial,
        quasiRegularAssociatedGradedPolynomialSmul_monomial]
      rw [LinearMap.map_add, smul_add]
  | add p q hp hq =>
      simp [quasiRegularAssociatedGradedInternal_add_smul, hp, hq, add_assoc,
        add_left_comm]

/-- Helper for 10.69.0.1: each quotient-piece monomial operator commutes with the ambient
`R / J`-scalar action. -/
theorem quasiRegularAssociatedGradedMonomialMapOnPiece_map_smul
    (rs : List R) (n : ℕ) (a : R ⧸ Ideal.ofList rs) (e : Fin rs.length →₀ ℕ)
    (z : quasiRegularAssociatedGradedInternalPiece rs M n) :
    quasiRegularAssociatedGradedMonomialMapOnPiece rs n e (a • z) =
      a • quasiRegularAssociatedGradedMonomialMapOnPiece rs n e z := by
  refine Quotient.inductionOn₂ a z ?_
  intro r m
  change quasiRegularAssociatedGradedMonomialMapOnPiece rs n e
      (r • (Submodule.Quotient.mk m : quasiRegularAssociatedGradedInternalPiece rs M n)) =
    r • quasiRegularAssociatedGradedMonomialMapOnPiece rs n e (Submodule.Quotient.mk m)
  rw [← Submodule.Quotient.mk_smul, quasiRegularAssociatedGradedMonomialMapOnPiece_mk,
    quasiRegularAssociatedGradedMonomialMapOnPiece_mk, ← Submodule.Quotient.mk_smul]
  congr 1
  apply Subtype.ext
  simp [smul_smul, mul_comm]

/-- Helper for 10.69.0.1: each monomial action commutes with the ambient `R / J`-scalar action.
-/
theorem quasiRegularAssociatedGradedMonomialAction_map_smul
    (rs : List R) (a : R ⧸ Ideal.ofList rs) (e : Fin rs.length →₀ ℕ)
    (x : quasiRegularAssociatedGradedInternal rs M) :
    quasiRegularAssociatedGradedMonomialAction rs e (a • x) =
      a • quasiRegularAssociatedGradedMonomialAction rs e x := by
  induction x using DirectSum.induction_on with
  | zero =>
      simp
  | of n z =>
      change (quasiRegularAssociatedGradedMonomialAction rs e)
          (a • DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
            (quasiRegularAssociatedGradedInternalPiece rs M) n z) =
        a •
          (quasiRegularAssociatedGradedMonomialAction rs e)
            (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
              (quasiRegularAssociatedGradedInternalPiece rs M) n z)
      rw [← (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
        (quasiRegularAssociatedGradedInternalPiece rs M) n).map_smul,
        quasiRegularAssociatedGradedMonomialAction_lof,
        quasiRegularAssociatedGradedMonomialAction_lof,
        ← (DirectSum.lof (R ⧸ Ideal.ofList rs) ℕ
          (quasiRegularAssociatedGradedInternalPiece rs M)
          (n + quasiRegularTotalDegree e)).map_smul]
      congr 1
      exact quasiRegularAssociatedGradedMonomialMapOnPiece_map_smul
        (M := M) rs n a e z
  | add x y hx hy =>
      simp [map_add, hx, hy]

/-- Helper for 10.69.0.1: multiplying on the right by a monomial polynomial acts by the
corresponding scalar followed by the matching monomial operator. -/
theorem quasiRegularAssociatedGradedInternal_mul_smul_monomial
    (rs : List R) (p : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
    (e : Fin rs.length →₀ ℕ) (a : R ⧸ Ideal.ofList rs)
    (x : quasiRegularAssociatedGradedInternal rs M) :
    (p * MvPolynomial.monomial e a) • x =
      p • (a • quasiRegularAssociatedGradedMonomialAction rs e x) := by
  induction p using MvPolynomial.induction_on' with
  | monomial f b =>
      rw [MvPolynomial.monomial_mul, quasiRegularAssociatedGradedPolynomialSmul_monomial,
        quasiRegularAssociatedGradedPolynomialSmul_monomial,
        quasiRegularAssociatedGradedMonomialAction_map_smul,
        quasiRegularAssociatedGradedMonomialAction_add (M := M) (rs := rs) (e := e) (f := f)]
      simp [smul_smul, add_comm, mul_comm]
  | add p q hp hq =>
      rw [add_mul, quasiRegularAssociatedGradedInternal_add_smul, hp, hq,
        quasiRegularAssociatedGradedInternal_add_smul]

-- TODO(10.69.0.1): after restoring the polynomial-module distributivity lemmas, prove the
-- monomial-monomial case and extend bilinearly to all polynomials.
theorem quasiRegularAssociatedGradedInternal_mul_smul
    (rs : List R) (p q : MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
    (x : quasiRegularAssociatedGradedInternal rs M) :
    (p * q) • x = p • q • x := by
  induction q using MvPolynomial.induction_on' with
  | monomial e a =>
      simpa [quasiRegularAssociatedGradedPolynomialSmul_monomial] using
        quasiRegularAssociatedGradedInternal_mul_smul_monomial (M := M) rs p e a x
  | add q₁ q₂ hq₁ hq₂ =>
      simp [mul_add, quasiRegularAssociatedGradedInternal_add_smul,
        quasiRegularAssociatedGradedInternal_smul_add, hq₁, hq₂]

instance quasiRegularAssociatedGradedInternalModule (rs : List R) :
    Module (MvPolynomial (Fin rs.length) (R ⧸ Ideal.ofList rs))
      (quasiRegularAssociatedGradedInternal rs M) where
  smul := (· • ·)
  one_smul := quasiRegularAssociatedGradedInternal_one_smul rs
  mul_smul := quasiRegularAssociatedGradedInternal_mul_smul rs
  smul_add := quasiRegularAssociatedGradedInternal_smul_add rs
  smul_zero := quasiRegularAssociatedGradedInternal_smul_zero rs
  add_smul := quasiRegularAssociatedGradedInternal_add_smul rs
  zero_smul := quasiRegularAssociatedGradedInternal_zero_smul rs

end RingTheory.Sequence

end
