import StacksProject_2024.Chap04.Definition_4_35_1
import StacksProject_2024.Chap04.Definition_4_33_9
import StacksProject_2024.Chap04.Lemma_4_33_7
import StacksProject_2024.Chap07.Definition_7_13_1
import StacksProject_2024.Chap08.Definition_8_3_5
import StacksProject_2024.Chap08.Lemma_8_10_1
import Mathlib.Tactic.StacksAttribute

noncomputable section

universe u v uS vS w

namespace CategoryTheory

namespace FibredCategoryOver

variable {C : Type u} [Category.{v} C]

/-- Helper for Lemma 8.10.4 ProjectionFamilyCovering: a generating inherited precover pushes
forward to a covering sieve on the base. -/
private theorem functorPushforward_mem_base_of_stronglyCartesianLiftPrecoverage_mem
    (J : GrothendieckTopology C) (X : FibredCategoryOver C)
    {y : X.S} {R : Presieve y}
    (hR : R ∈ stronglyCartesianLiftPrecoverage J.toPrecoverage X.p y) :
    (Sieve.generate R).functorPushforward X.p ∈ J (X.p.obj y) := by
  -- Unpack the generator and read off exactly the base covering family in `J`.
  rcases hR with ⟨κ, Y, g, rfl, _hgstrong, hbasePrecover⟩
  rw [GrothendieckTopology.mem_toPrecoverage_iff] at hbasePrecover
  rw [← Sieve.generate_map_eq_functorPushforward]
  simpa [Presieve.map_ofArrows, Sieve.ofArrows] using hbasePrecover

/-- Helper for Lemma 8.10.4 ProjectionFamilyCovering: for a category fibred in groupoids,
pulling back a projected sieve along a projected arrow is contained in the projection of the
upstairs pullback. -/
private theorem pullback_functorPushforward_le_functorPushforward_pullback_of_fibredInGroupoids
    (X : FibredCategoryOver C) [IsFibredInGroupoids X.p]
    {y z : X.S} (R : Sieve y) (f : z ⟶ y) :
    ((R.functorPushforward X.p).pullback (X.p.map f)) ≤
      ((R.pullback f).functorPushforward X.p) := by
  intro W q hq
  -- A projected factorization of `q ≫ X.p.map f` is lifted to the total category, then factored
  -- through the strongly cartesian arrow `f`.
  rcases hq with ⟨a, r, l, hr, hfac⟩
  let aFiber : X.p.Fiber (X.p.obj a) := ⟨a, rfl⟩
  let t : X.S := (l ^*[canonicalPullbackChoice X.p] aFiber).1
  let χ : t ⟶ a := (canonicalPullbackChoice X.p).map l aFiber
  have hχStrong : X.p.IsStronglyCartesian l χ := by
    simpa [χ] using (canonicalPullbackChoice X.p).isStronglyCartesian l aFiber
  letI : X.p.IsStronglyCartesian l χ := hχStrong
  have hχLift : X.p.IsHomLift l χ := inferInstance
  letI : X.p.IsHomLift l χ := hχLift
  let e : X.p.obj t = W := IsHomLift.domain_eq X.p l χ
  let baseToZ : X.p.obj t ⟶ X.p.obj z := eqToHom e ≫ q
  have hχmap : X.p.map χ = eqToHom e ≫ l := by
    simpa [e, χ] using (IsHomLift.fac' X.p l χ)
  have hbase :
      X.p.map (χ ≫ r) = baseToZ ≫ X.p.map f := by
    calc
      X.p.map (χ ≫ r) = X.p.map χ ≫ X.p.map r := by
        simp [Functor.map_comp]
      _ = (eqToHom e ≫ l) ≫ X.p.map r := by
        rw [hχmap]
      _ = eqToHom e ≫ (q ≫ X.p.map f) := by
        simp [Category.assoc, hfac.symm]
      _ = baseToZ ≫ X.p.map f := by
        simp [baseToZ, Category.assoc]
  let m : t ⟶ z :=
    Functor.IsStronglyCartesian.map X.p (X.p.map f) f hbase (χ ≫ r)
  have hm_fac : m ≫ f = χ ≫ r := by
    -- The strongly cartesian universal property gives the required upstairs factorization.
    dsimp [m]
    exact Functor.IsStronglyCartesian.fac X.p (X.p.map f) f hbase (χ ≫ r)
  have hmLift : X.p.IsHomLift baseToZ m := by
    dsimp [m]
    infer_instance
  letI : X.p.IsHomLift baseToZ m := hmLift
  have hmR : (R.pullback f) m := by
    -- The pullback sieve contains the factored arrow because `R` is downward closed.
    rw [Sieve.pullback_apply, hm_fac]
    exact R.downward_closed hr χ
  refine ⟨t, m, eqToHom e.symm, hmR, ?_⟩
  have hmapm : baseToZ = X.p.map m :=
    IsHomLift.eq_of_isHomLift X.p baseToZ m
  -- Transport the chosen lift domain equality back to the original base arrow `q`.
  simpa [baseToZ, Category.assoc] using congrArg (fun k ↦ eqToHom e.symm ≫ k) hmapm

/-- Helper for Lemma 8.10.4 ProjectionFamilyCovering: every sieve generated by the inherited
precoverage remains covering after projection to the base topology. -/
private theorem functorPushforward_mem_base_of_inherited_sieve_mem
    (J : GrothendieckTopology C) (X : FibredCategoryOver C)
    [IsFibredInGroupoids X.p]
    {y : X.S} {R : Sieve y}
    (hR : R ∈ (stronglyCartesianLiftPrecoverage J.toPrecoverage X.p).toGrothendieck y) :
    R.functorPushforward X.p ∈ J (X.p.obj y) := by
  -- Induct over the saturation defining the generated Grothendieck topology.
  rw [Precoverage.mem_toGrothendieck_iff] at hR
  induction hR with
  | of y R hR =>
      exact functorPushforward_mem_base_of_stronglyCartesianLiftPrecoverage_mem J X hR
  | top y =>
      simpa using (J.top_mem (X.p.obj y))
  | pullback y R hR z f ih =>
      refine J.superset_covering
        (pullback_functorPushforward_le_functorPushforward_pullback_of_fibredInGroupoids
          X R f) ?_
      exact J.pullback_stable (X.p.map f) ih
  | transitive y S R hS hR ihS ihR =>
      refine J.transitive ihS (R.functorPushforward X.p) ?_
      intro Z q hq
      rcases hq with ⟨a, f, l, hf, hfac⟩
      have hlocal :
          ((R.pullback f).functorPushforward X.p).pullback l ∈ J Z :=
        J.pullback_stable l (ihR hf)
      refine J.superset_covering ?_ hlocal
      intro W k hk
      have hle :
          ((R.pullback f).functorPushforward X.p).pullback l ≤
            ((R.functorPushforward X.p).pullback (X.p.map f)).pullback l :=
        Sieve.pullback_monotone l (Sieve.functorPushforward_pullback_le (F := X.p) f R)
      have hk' := hle k hk
      simpa [Sieve.pullback_apply, hfac, Category.assoc] using hk'

/-- Helper for Lemma 8.10.5: the componentwise image of a fixed-target family under the
projection functor. -/
def projectionImageFamily
    (X : FibredCategoryOver C) {y : X.S} (S : SemiRepresentableFamily.Over.{w} y) :
    SemiRepresentableFamily.Over (X.p.obj y) where
  index := S.index
  obj := fun i ↦ (Over.post X.p).obj (S.obj i)

/-- Lemma 8.10.4 ProjectionFamilyCovering: an inherited covering family maps to a covering family downstairs.
The source proof first refines the inherited cover by a generating strongly cartesian family, then
enlarges that downstairs generator to the actual image family. -/
@[stacks 0CN0]
theorem image_family_isCovering_of_inherited_family_covering
    (J : GrothendieckTopology C) (X : FibredCategoryOver C) [IsFibredInGroupoids X.p]
    {y : X.S} (S : SemiRepresentableFamily.Over.{w} y)
    (hS :
      Presieve.ofArrows (fun i ↦ (S.obj i).left) (fun i ↦ (S.obj i).hom) ∈
        ((stronglyCartesianLiftPrecoverage J.toPrecoverage X.p).toGrothendieck.toPrecoverage) y) :
    Presieve.ofArrows (fun i ↦ X.p.obj ((S.obj i).left)) (fun i ↦ X.p.map ((S.obj i).hom)) ∈
      J.toPrecoverage (X.p.obj y) := by
  -- Route correction: avoid the generated-precoverage characterization requiring unavailable
  -- `HasPullbacks`; instead use the saturation invariant proved above.
  rw [GrothendieckTopology.mem_toPrecoverage_iff] at hS ⊢
  have hbase :
      (Sieve.generate
          (Presieve.ofArrows (fun i ↦ (S.obj i).left) (fun i ↦ (S.obj i).hom))).functorPushforward
          X.p ∈ J (X.p.obj y) :=
    functorPushforward_mem_base_of_inherited_sieve_mem J X hS
  -- Normalize the functor-pushforward of the generated upstairs family to the generated
  -- downstairs family appearing in the statement.
  rw [← Sieve.generate_map_eq_functorPushforward] at hbase
  simpa [Presieve.map_ofArrows, Sieve.ofArrows] using hbase

end FibredCategoryOver

end CategoryTheory
