import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open ProbabilityTheory

universe u v

/-- The family obtained from `A` by replacing `A i` with its complement whenever `α i = true`. -/
def complementedEventFamily {Ω : Type u} {ι : Type v} [MeasurableSpace Ω]
    (A : ι → Set Ω) (α : ι → Bool) : ι → Set Ω :=
  fun i ↦ if α i then (A i)ᶜ else A i

-- Proof sketch: unfold `complementedEventFamily` and simplify the Boolean case split at the chosen
-- index.
/-- Helper for Theorem 2.5: a pointwise description of the family obtained by complementing the
events selected by `α`. -/
theorem complementedEventFamily_apply {Ω : Type u} {ι : Type v} [MeasurableSpace Ω]
    (A : ι → Set Ω) (α : ι → Bool) (i : ι) :
    complementedEventFamily A α i = if α i then (A i)ᶜ else A i := by
  -- Unfolding the definition identifies the `i`-th event immediately.
  rfl

/-- Helper for Theorem 2.5: a singleton-generated measurable space is unchanged when its generator
is replaced by the complement. -/
lemma generateFrom_singleton_compl {Ω : Type u} (s : Set Ω) :
    MeasurableSpace.generateFrom {sᶜ} = MeasurableSpace.generateFrom {s} := by
  -- Each generator is measurable in the sigma-algebra generated by the other singleton.
  refine le_antisymm ?_ ?_
  · refine MeasurableSpace.generateFrom_le ?_
    intro t ht
    rw [Set.mem_singleton_iff] at ht
    subst ht
    exact (MeasurableSpace.measurableSet_generateFrom (Set.mem_singleton s)).compl
  · refine MeasurableSpace.generateFrom_le ?_
    intro t ht
    rw [Set.mem_singleton_iff] at ht
    rw [ht]
    simpa using (MeasurableSpace.measurableSet_generateFrom (Set.mem_singleton (sᶜ))).compl

/-- Helper for Theorem 2.5: complementing any chosen subfamily does not change indexed
independence. -/
lemma iIndepSet_complementedEventFamily_iff {Ω : Type u} {ι : Type v} [MeasurableSpace Ω]
    (A : ι → Set Ω) (α : ι → Bool) (μ : MeasureTheory.Measure Ω := by volume_tac) :
    iIndepSet (complementedEventFamily A α) μ ↔ iIndepSet A μ := by
  -- Independence of a family of events depends only on the generated one-set sigma-algebras.
  rw [ProbabilityTheory.iIndepSet_iff_iIndep, ProbabilityTheory.iIndepSet_iff_iIndep]
  have hgen :
      (fun i ↦ MeasurableSpace.generateFrom {complementedEventFamily A α i}) =
        fun i ↦ MeasurableSpace.generateFrom {A i} := by
    -- Compare the singleton-generated sigma-algebras after splitting on whether `α i` toggles it.
    funext i
    by_cases hα : α i
    · -- In the complemented branch, replace the generator by its complement and use the helper.
      trans MeasurableSpace.generateFrom {(A i)ᶜ}
      · rw [complementedEventFamily_apply]
        simp [hα]
      · exact generateFrom_singleton_compl (A i)
    · -- In the unchanged branch, the family agrees with the original event at index `i`.
      rw [complementedEventFamily_apply]
      simp [hα]
  rw [hgen]

-- Proof sketch: show that `iIndepSet` is preserved when one replaces any subfamily by complements,
-- then combine the implications `(iii) → (ii)`, `(ii) → (i)`, and `(i) → (iii)` in a `TFAE`
-- argument.
/-- Theorem 2.5: for a family of events `A`, independence is equivalent to independence of one, and
hence every, family obtained by replacing each `A i` either by itself or by its complement. -/
theorem iIndepSet_tfae_complementedEventFamily {Ω : Type u} {ι : Type v} [MeasurableSpace Ω]
    (A : ι → Set Ω) (μ : MeasureTheory.Measure Ω := by volume_tac) :
    List.TFAE
      [ iIndepSet A μ
      , ∃ α : ι → Bool, iIndepSet (complementedEventFamily A α) μ
      , ∀ α : ι → Bool, iIndepSet (complementedEventFamily A α) μ
      ] := by
  -- Route correction: prove the complement-invariance of the generated singleton sigma-algebras
  -- first, and package the three formulations only afterwards.
  tfae_have 1 → 3 := by
    intro hA α
    -- Once the core equivalence is available, every Boolean choice of complements is independent.
    exact (iIndepSet_complementedEventFamily_iff A α μ).2 hA
  tfae_have 3 → 2 := by
    intro hA
    -- The universal statement gives an existential witness by choosing no complements.
    exact ⟨fun _ ↦ false, hA (fun _ ↦ false)⟩
  tfae_have 2 → 1 := by
    rintro ⟨α, hα⟩
    -- The same core equivalence transports independence back to the original family.
    exact (iIndepSet_complementedEventFamily_iff A α μ).1 hα
  tfae_finish
