import Mathlib
import stacks_project.Chap18.Definition_18_17_1

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory Limits

universe v₁ v₂ u

namespace SheafOfModules

variable {C : Type u} [Category.{v₁} C] {D : Type u} [Category.{v₂} D]
variable {J : GrothendieckTopology C} {K : GrothendieckTopology D}
variable {F : C ⥤ D} [Functor.IsContinuous F J K]
variable {S : Sheaf J RingCat.{u}} {R : Sheaf K RingCat.{u}}
variable [HasWeakSheafify J AddCommGrpCat.{u}]
variable [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
variable [J.HasSheafCompose (forget₂ RingCat.{u} AddCommGrpCat.{u})]
variable [HasWeakSheafify K AddCommGrpCat.{u}]
variable [K.WEqualsLocallyBijective AddCommGrpCat.{u}]
variable [K.HasSheafCompose (forget₂ RingCat.{u} AddCommGrpCat.{u})]
variable (φ : S ⟶ (F.sheafPushforwardContinuous RingCat.{u} J K).obj R)
variable [(pushforward φ).IsRightAdjoint]
variable [IsIso (pullbackObjUnitToUnit φ)]

local notation "fStar" => pullback φ

-- Proof sketch: choose an isomorphism from `ℱ` to a free sheaf `free I`; apply the pullback
-- functor, use that it preserves coproducts because it is a left adjoint, and identify the
-- pullback of `unit S` with `unit R` via `pullbackObjUnitToUnit φ`.
/-- Lemma 18.17.2 (1): if an `\mathcal O_\mathcal D`-module is free, then its pullback along a
morphism of ringed topoi is free. -/
instance pullback_isFree (ℱ : SheafOfModules S) [IsFree ℱ] :
    IsFree ((fStar).obj ℱ) := sorry

-- Proof sketch: write `ℱ` as a free sheaf on a finite index type, pull back that free
-- presentation, and use the same argument as in the free case together with finiteness of the
-- indexing type.
/-- Lemma 18.17.2 (2): if an `\mathcal O_\mathcal D`-module is finite free, then its pullback
along a morphism of ringed topoi is finite free. -/
instance pullback_isFiniteFree (ℱ : SheafOfModules S) [IsFiniteFree ℱ] :
    IsFiniteFree ((fStar).obj ℱ) := sorry

-- Proof sketch: a generating family of global sections gives an epimorphism from a free sheaf;
-- pull back that epimorphism, use preservation of colimits/right exactness, and transport the
-- free source along the canonical identification of pullback of a free sheaf with a free sheaf.
/-- Lemma 18.17.2 (3): if an `\mathcal O_\mathcal D`-module is generated by global sections, then
its pullback along a morphism of ringed topoi is generated by global sections. -/
instance pullback_isGloballyGenerated (ℱ : SheafOfModules S)
    [Nonempty ℱ.GeneratingSections] :
    Nonempty (((fStar).obj ℱ).GeneratingSections) := sorry

/-
Proof sketch: start from an epimorphism `\mathcal O_\mathcal D^{\oplus r} \to \mathcal F`, pull
it back, and identify the pullback of `\mathcal O_\mathcal D^{\oplus r}` with
`\mathcal O_\mathcal C^{\oplus r}`.
-/
/-- Lemma 18.17.2 (4): if an `\mathcal O_\mathcal D`-module is generated by `r` global sections,
then its pullback along a morphism of ringed topoi is generated by `r` global sections. -/
instance pullback_isGeneratedBy (ℱ : SheafOfModules S) (r : ℕ)
    [IsGeneratedBy ℱ r] :
    IsGeneratedBy ((fStar).obj ℱ) r := sorry

-- Proof sketch: choose `r` with `ℱ` generated by `r` global sections, then apply the previous
-- rank-`r` pullback result.
/-- Lemma 18.17.2 (5): if an `\mathcal O_\mathcal D`-module is generated by finitely many global
sections, then its pullback along a morphism of ringed topoi is again finitely globally
generated. -/
instance pullback_isFiniteGloballyGenerated (ℱ : SheafOfModules S)
    [IsFiniteGloballyGenerated ℱ] :
    IsFiniteGloballyGenerated ((fStar).obj ℱ) := sorry

-- Proof sketch: choose a global presentation of `ℱ`, pull back the presentation diagram, use that
-- pullback preserves colimits, and identify the pulled-back free terms with free sheaves via the
-- canonical unit comparison isomorphism.
/-- Lemma 18.17.2 (6): if an `\mathcal O_\mathcal D`-module has a global presentation, then its
pullback along a morphism of ringed topoi has a global presentation. -/
instance pullback_hasGlobalPresentation (ℱ : SheafOfModules S)
    [Nonempty ℱ.Presentation] :
    Nonempty (((fStar).obj ℱ).Presentation) := sorry

-- Proof sketch: pull back a finite global presentation of `ℱ`; the pullback preserves the
-- presentation and leaves the finite indexing sets finite.
/-- Lemma 18.17.2 (7): if an `\mathcal O_\mathcal D`-module has a finite global presentation, then
its pullback along a morphism of ringed topoi again has a finite global presentation. -/
instance pullback_finitePresentation (ℱ : SheafOfModules S)
    [Nonempty {P : ℱ.Presentation // P.IsFinite}] :
    Nonempty {P : ((fStar).obj ℱ).Presentation // P.IsFinite} := sorry

end SheafOfModules
