import Mathlib

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open CategoryTheory.Idempotents
open CategoryTheory.Limits
open CategoryTheory.Subobject
open AlgebraicTopology
open AlgebraicTopology.DoldKan
open scoped Simplicial DoldKan

noncomputable section

universe v u

namespace AlgebraicTopology

namespace DoldKan

/- Domain-style sampling for Lemma 14.23.6:
- primary domain: the Dold-Kan decomposition of the alternating face map complex of a simplicial
  object into the normalized Moore complex and the degenerate subcomplex generated by the
  degeneracy maps;
- sampled owner declarations:
  `imageSubobject`,
  `QInfty`,
  `PInftyToNormalizedMooreComplex`,
  `Karoubi.decomposition`;
- best owner abstraction: the primitive source-facing owner is the degreewise subobject
  `degenerateSubobject U n`, which is only the finite supremum of the image subobjects of the
  degeneracy maps; the chain-complex and Karoubi decomposition data are built on top of that owner;
- primitive data: the degreewise degenerate subobjects `D(U)_n ⊆ U_n`;
- derived API: the degenerate subcomplex `D(U)`, its inclusion `D(U) ⟶ K(U)`, the factorization
  `K(U) ⟶ D(U)` of `Q_\infty`, and the source-facing comparison `K(U) ⟶ N(U) ⊞ D(U)`.

Source/core/bridge triage:
- `source-facing`: the degreewise owner `degenerateSubobject U n`, and the resulting degenerate
  subcomplex `D(U)`;
- `core/canonical`: `N₁.obj U`, its complement `((N₁.obj U).complement)`, and
  `Karoubi.decomposition (N₁.obj U)`;
- `bridge/view`: `D(U)`, `QInftyToDegenerateComplex`, `degenerateComplexι`, and the abelian
  identification of the Karoubi `P_\infty`-summand with `N(U)`.

The review feedback rules out taking a cokernel as the public owner of `D(U)`, so this file keeps
the generated-by-degeneracies subcomplex as the public source-facing object and leaves any quotient
description to future bridge lemmas. -/

section DegenerateSubobject

variable {C : Type u} [Category.{v} C] [HasZeroObject C] [HasBinaryCoproducts C] [HasImages C]

/-- The degree-`n` degenerate subobject of `U_n`, generated by the images of the degeneracy maps
`σ_i : U_{n-1} ⟶ U_n`. -/
def degenerateSubobject (U : SimplicialObject C) (n : ℕ) : Subobject (U _⦋n⦌) :=
  match n with
  | 0 => ⊥
  | n + 1 => Finset.univ.sup fun i : Fin (n + 1) ↦ imageSubobject (U.σ i)

end DegenerateSubobject

section Degenerate

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C]
  [HasBinaryCoproducts C] [HasImages C]

/-- Helper for Lemma 14.23.6: each individual degeneracy image is contained in the canonical
degreewise degenerate subobject. -/
private theorem degeneracy_image_le_degenerateSubobject
    (U : SimplicialObject C) (n : ℕ) (i : Fin (n + 1)) :
    imageSubobject (U.σ i) ≤ degenerateSubobject U (n + 1) := by
  -- The owner `degenerateSubobject U (n + 1)` is defined as the finite supremum of these images.
  change imageSubobject (U.σ i) ≤
      Finset.univ.sup (fun j : Fin (n + 1) ↦ imageSubobject (U.σ j))
  exact Finset.le_sup (s := Finset.univ)
    (f := fun j : Fin (n + 1) ↦ imageSubobject (U.σ j))
    (by simpa using (Finset.mem_univ i))

/-- Helper for Lemma 14.23.6: each summand in the source decomposition of `Q∞` lands in the
corresponding degeneracy image, hence in the degreewise degenerate owner. -/
private theorem decomposition_Q_summand_factors
    (U : SimplicialObject C) (n : ℕ) (i : Fin (n + 1)) :
    (degenerateSubobject U (n + 1)).Factors
      ((P i).f (n + 1) ≫ U.δ i.rev.succ ≫ U.σ (Fin.rev i)) := by
  -- First factor through the image of the last degeneracy, then compare that image with the sup.
  refine Subobject.factors_of_le _ (degeneracy_image_le_degenerateSubobject U n (Fin.rev i)) ?_
  simpa [Category.assoc] using imageSubobject_factors_comp_self (f := U.σ (Fin.rev i))
    ((P i).f (n + 1) ≫ U.δ i.rev.succ)

/-- Helper for Lemma 14.23.6: the projector `Q∞` lands in the degreewise degenerate owner. -/
private theorem degenerateSubobject_factors_QInfty_f (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U n).Factors ((QInfty : K[U] ⟶ K[U]).f n) := by
  -- TODO: expand `Q∞` using the source decomposition and sum the degreewise factorisations.
  sorry

/-- Helper for Lemma 14.23.6: any factorization through a subobject forces the image subobject to
be contained in that subobject. -/
private theorem imageSubobject_le_of_factors
    {X Y : C} (f : X ⟶ Y) (P : Subobject Y) (h : P.Factors f) :
    imageSubobject f ≤ P := by
  -- TODO: invoke the universal property of the image to compare `imageSubobject f` with `P`.
  sorry

/-- Helper for Lemma 14.23.6: each degeneracy image is contained in the image of `Q∞` in the same
degree. -/
private theorem degeneracy_image_le_image_QInfty
    (U : SimplicialObject C) (n : ℕ) (i : Fin (n + 1)) :
    imageSubobject (U.σ i) ≤ imageSubobject ((QInfty : K[U] ⟶ K[U]).f (n + 1)) := by
  -- TODO: rewrite `σ_i` through `Q∞` using `P∞ + Q∞ = 𝟙` and `σ_i ≫ P∞ = 0`, then compare images.
  sorry

/-- Helper for Lemma 14.23.6: the degreewise degenerate owner is contained in the image of `Q∞`.
-/
private theorem degenerateSubobject_le_image_QInfty
    (U : SimplicialObject C) (n : ℕ) :
    degenerateSubobject U n ≤ imageSubobject ((QInfty : K[U] ⟶ K[U]).f n) := by
  cases n with
  | zero =>
      -- In degree `0`, the degenerate owner is bottom.
      simp [degenerateSubobject]
  | succ n =>
      -- In positive degree, the degenerate owner is the finite sup of the degeneracy images.
      change Finset.univ.sup (fun i : Fin (n + 1) ↦ imageSubobject (U.σ i)) ≤
        imageSubobject ((QInfty : K[U] ⟶ K[U]).f (n + 1))
      refine Finset.sup_le ?_
      intro i hi
      exact degeneracy_image_le_image_QInfty U n i

/-- Helper for Lemma 14.23.6: the complementary projector `Q∞` acts as the identity on the
degreewise degenerate owner. -/
private theorem degenerateSubobject_arrow_comp_QInfty_f
    (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U n).arrow ≫ (QInfty : K[U] ⟶ K[U]).f n =
      (degenerateSubobject U n).arrow := by
  -- TODO: identify the degenerate owner with the image of `Q∞` and apply idempotence of `Q∞`.
  sorry

/-- Helper for Lemma 14.23.6: postcomposition by the degenerate inclusion distributes over the
projector decomposition `P∞ + Q∞`. -/
private theorem degenerateSubobject_arrow_comp_add
    (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U n).arrow ≫
        ((PInfty : K[U] ⟶ K[U]).f n + (QInfty : K[U] ⟶ K[U]).f n) =
      (degenerateSubobject U n).arrow ≫ (PInfty : K[U] ⟶ K[U]).f n +
        (degenerateSubobject U n).arrow ≫ (QInfty : K[U] ⟶ K[U]).f n := by
  -- This is the additive expansion needed when comparing the two projectors on the degenerate owner.
  exact
    (Preadditive.comp_add
      (degenerateSubobject U n : C) (U _⦋n⦌) (U _⦋n⦌)
      (degenerateSubobject U n).arrow
      ((PInfty : K[U] ⟶ K[U]).f n)
      ((QInfty : K[U] ⟶ K[U]).f n))

/-- Helper for Lemma 14.23.6: the normalized projector `P∞` kills the degreewise degenerate
owner. -/
private theorem degenerateSubobject_arrow_comp_PInfty_f_eq_zero
    (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U n).arrow ≫ (PInfty : K[U] ⟶ K[U]).f n = 0 := by
  -- TODO: combine `degenerateSubobject_arrow_comp_add` with `degenerateSubobject_arrow_comp_QInfty_f`
  -- and cancel the common summand.
  sorry

/-- Helper for Lemma 14.23.6: any morphism fixed by `Q∞` factors through the degreewise
degenerate owner. -/
private theorem factors_of_comp_QInfty_eq_self
    (U : SimplicialObject C) (n : ℕ) {X : C} (f : X ⟶ U _⦋n⦌)
    (hf : f ≫ (QInfty : K[U] ⟶ K[U]).f n = f) :
    (degenerateSubobject U n).Factors f := by
  -- Rewrite `f` through `f ≫ Q∞`, then use the factorization of `Q∞` itself.
  rw [← hf]
  exact Subobject.factors_of_factors_right f (degenerateSubobject_factors_QInfty_f U n)

private theorem degenerateSubobject_d_factors (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U n).Factors
      ((degenerateSubobject U (n + 1)).arrow ≫ (K[U]).d (n + 1) n) := by
  -- TODO: prove this composite is `Q∞`-fixed and invoke `factors_of_comp_QInfty_eq_self`.
  sorry

/-- Helper for Lemma 14.23.6: the component form of the chain-map identity for `Q∞` in
successive degrees. -/
private theorem qInfty_comm_succ (U : SimplicialObject C) (n : ℕ) :
    ((QInfty : K[U] ⟶ K[U]).f (n + 1)) ≫ (K[U]).d (n + 1) n =
      (K[U]).d (n + 1) n ≫ ((QInfty : K[U] ⟶ K[U]).f n) := by
  -- This is exactly the `(n + 1, n)` component of the chain-map commutativity of `Q∞`.
  simpa using (QInfty : K[U] ⟶ K[U]).comm (n + 1) n

private def degenerateComplex_d (U : SimplicialObject C) (n : ℕ) :
    (degenerateSubobject U (n + 1) : C) ⟶ (degenerateSubobject U n : C) :=
  (degenerateSubobject U n).factorThru
    ((degenerateSubobject U (n + 1)).arrow ≫ (K[U]).d (n + 1) n)
    (degenerateSubobject_d_factors U n)

private theorem degenerateComplex_d_arrow (U : SimplicialObject C) (n : ℕ) :
    degenerateComplex_d U n ≫ (degenerateSubobject U n).arrow =
      (degenerateSubobject U (n + 1)).arrow ≫ (K[U]).d (n + 1) n := by
  exact factorThru_arrow _ _ (degenerateSubobject_d_factors U n)

private theorem degenerateComplex_d_squared (U : SimplicialObject C) (n : ℕ) :
    degenerateComplex_d U (n + 1) ≫ degenerateComplex_d U n = 0 := by
  -- TODO: compare after the subobject arrow and reduce to `d ≫ d = 0` in `K(U)`.
  sorry

/-- The degenerate subcomplex `D(U)` of the alternating face map complex, generated degreewise by
the images of the degeneracy maps. -/
def degenerateComplex (U : SimplicialObject C) : ChainComplex C ℕ :=
  ChainComplex.of (fun n ↦ (degenerateSubobject U n : C))
    (degenerateComplex_d U) (degenerateComplex_d_squared U)

@[inherit_doc]
scoped[DoldKan] notation "D[" X "]" => AlgebraicTopology.DoldKan.degenerateComplex X

/-- Helper for Lemma 14.23.6: the degreewise inclusions of the degenerate owner assemble into a
chain map `D(U) ⟶ K(U)`. -/
private theorem degenerateComplexι_comm (U : SimplicialObject C) (j : ℕ) :
    (degenerateSubobject U (j + 1)).arrow ≫ (K[U]).d (j + 1) j =
      (D[U]).d (j + 1) j ≫ (degenerateSubobject U j).arrow := by
  -- TODO: this is the degree-`j` comparison underlying the chain-map condition for `D(U) ⟶ K(U)`.
  sorry

/-- The inclusion of the degenerate subcomplex `D(U)` into the alternating face map complex
`K(U)`. -/
def degenerateComplexι (U : SimplicialObject C) : D[U] ⟶ K[U] where
  f n := (degenerateSubobject U n).arrow
  comm' i j hij := by
    have hij' : j + 1 = i := by simpa using hij
    subst i
    exact degenerateComplexι_comm U j

private def QInftyToDegenerateComplex_f (U : SimplicialObject C) (n : ℕ) :
    U _⦋n⦌ ⟶ (degenerateSubobject U n : C) :=
  (degenerateSubobject U n).factorThru ((QInfty : K[U] ⟶ K[U]).f n)
    (degenerateSubobject_factors_QInfty_f U n)

private theorem QInftyToDegenerateComplex_f_arrow (U : SimplicialObject C) (n : ℕ) :
    QInftyToDegenerateComplex_f U n ≫ (degenerateSubobject U n).arrow =
      (QInfty : K[U] ⟶ K[U]).f n := by
  exact factorThru_arrow _ _ (degenerateSubobject_factors_QInfty_f U n)

private def degenerateComplexMap_f {U V : SimplicialObject C} (f : U ⟶ V) (n : ℕ) :
    (degenerateSubobject U n : C) ⟶ (degenerateSubobject V n : C) :=
  -- Route correction: define the map on `D(U)` by inclusion into `K(U)`, simplicial naturality,
  -- and projection back with the `Q∞`-retract.
  (degenerateSubobject U n).arrow ≫ f.app (Opposite.op ⦋n⦌) ≫ QInftyToDegenerateComplex_f V n

private theorem degenerateComplexMap_f_arrow {U V : SimplicialObject C} (f : U ⟶ V) (n : ℕ) :
    degenerateComplexMap_f f n ≫ (degenerateSubobject V n).arrow =
      (degenerateSubobject U n).arrow ≫ f.app (Opposite.op ⦋n⦌) := by
  -- TODO: use the retract description and naturality of `Q∞`.
  sorry

/-- Helper for Lemma 14.23.6: the degreewise retract maps induced by a simplicial morphism form a
chain map on the degenerate subcomplexes. -/
private theorem degenerateComplexMap_comm
    {U V : SimplicialObject C} (f : U ⟶ V) (j : ℕ) :
    degenerateComplexMap_f f (j + 1) ≫ (D[V]).d (j + 1) j =
      (D[U]).d (j + 1) j ≫ degenerateComplexMap_f f j := by
  -- TODO: this is the degree-`j` chain-map condition for the induced map on degenerate complexes.
  sorry

/-- The morphism of degenerate complexes induced by a simplicial morphism. -/
def degenerateComplexMap {U V : SimplicialObject C} (f : U ⟶ V) : D[U] ⟶ D[V] where
  f n := degenerateComplexMap_f f n
  comm' i j hij := by
    have hij' : j + 1 = i := by simpa using hij
    subst i
    exact degenerateComplexMap_comm f j

@[reassoc]
theorem degenerateComplexι_naturality {U V : SimplicialObject C} (f : U ⟶ V) :
    degenerateComplexMap f ≫ degenerateComplexι V =
      degenerateComplexι U ≫ (alternatingFaceMapComplex C).map f := by
  ext n
  simpa [degenerateComplexMap, degenerateComplexι] using degenerateComplexMap_f_arrow f n

private theorem degenerateComplexMap_id (U : SimplicialObject C) :
    degenerateComplexMap (𝟙 U) = 𝟙 D[U] := by
  -- TODO: compare after the subobject arrow and reduce to the identity in each degree.
  sorry

private theorem degenerateComplexMap_comp
    {U V W : SimplicialObject C} (f : U ⟶ V) (g : V ⟶ W) :
    degenerateComplexMap (f ≫ g) = degenerateComplexMap f ≫ degenerateComplexMap g := by
  -- TODO: compare after the target subobject arrow and reduce to simplicial functoriality degreewise.
  sorry

/-- The degenerate subcomplex construction is functorial in the simplicial object. -/
def degenerateComplexFunctor : SimplicialObject C ⥤ ChainComplex C ℕ where
  obj U := D[U]
  map := fun f ↦ degenerateComplexMap f
  map_id := degenerateComplexMap_id
  map_comp := degenerateComplexMap_comp

/-- The inclusion `D(U) ⟶ K(U)` is natural in `U`. -/
def degenerateComplexιNatTrans : degenerateComplexFunctor (C := C) ⟶ alternatingFaceMapComplex C
    where
  app U := degenerateComplexι U
  naturality _ _ f := degenerateComplexι_naturality f

/-- The canonical factorization of `Q_\infty : K(U) ⟶ K(U)` through the degenerate subcomplex
`D(U)`. -/
private theorem QInftyToDegenerateComplex_comm
    (U : SimplicialObject C) (j : ℕ) :
    QInftyToDegenerateComplex_f U (j + 1) ≫ (D[U]).d (j + 1) j =
      (K[U]).d (j + 1) j ≫ QInftyToDegenerateComplex_f U j := by
  -- TODO: this is the degree-`j` chain-map condition for the factorization of `Q∞` through `D(U)`.
  sorry

def QInftyToDegenerateComplex (U : SimplicialObject C) : K[U] ⟶ D[U] where
  f := QInftyToDegenerateComplex_f U
  comm' i j hij := by
    have hij' : j + 1 = i := by simpa using hij
    subst i
    exact QInftyToDegenerateComplex_comm U j

@[reassoc]
theorem QInftyToDegenerateComplex_naturality
    {U V : SimplicialObject C} (f : U ⟶ V) :
    (alternatingFaceMapComplex C).map f ≫ QInftyToDegenerateComplex V =
      QInftyToDegenerateComplex U ≫ degenerateComplexMap f := by
  -- TODO: compare after the target subobject arrow and reduce to degreewise naturality of `Q∞`.
  sorry

/-- Helper for Lemma 14.23.6: composing the factorization of `Q∞` through `D(U)` with the
inclusion `D(U) ⟶ K(U)` recovers `Q∞` itself. -/
private theorem QInftyToDegenerateComplex_comp_degenerateComplexι
    (U : SimplicialObject C) :
    QInftyToDegenerateComplex U ≫ degenerateComplexι U = QInfty := by
  ext n
  simpa [QInftyToDegenerateComplex, degenerateComplexι] using
    QInftyToDegenerateComplex_f_arrow U n

/-- Helper for Lemma 14.23.6: the inclusion of the degenerate summand followed by the `Q∞`
factorization is the identity on `D(U)`. -/
private theorem degenerateComplexι_comp_QInftyToDegenerateComplex
    (U : SimplicialObject C) :
    degenerateComplexι U ≫ QInftyToDegenerateComplex U = 𝟙 D[U] := by
  -- TODO: compare after the subobject arrow and use `degenerateSubobject_arrow_comp_QInfty_f`.
  sorry

/-- The projection `K(U) ⟶ D(U)` is natural in `U`. -/
def QInftyToDegenerateComplexNatTrans :
    alternatingFaceMapComplex C ⟶ degenerateComplexFunctor (C := C) where
  app U := QInftyToDegenerateComplex U
  naturality _ _ f := QInftyToDegenerateComplex_naturality f

end Degenerate

section AbelianBridge

variable {A : Type u} [Category.{v} A] [Abelian A]

/-- Helper for Lemma 14.23.6: the `Q∞`-factorization defines a morphism from the Karoubi
complement to the public degenerate subcomplex. -/
private theorem complementToDegenerateComplex_comm (U : SimplicialObject A) :
    (N₁.obj U).complement.p ≫ QInftyToDegenerateComplex U ≫
        ((toKaroubi _).obj D[U]).p = QInftyToDegenerateComplex U := by
  -- TODO: compare the projector-wrapped morphism with `Q∞ToDegenerateComplex U` degreewise.
  sorry

private def complementToDegenerateComplex (U : SimplicialObject A) :
    (N₁.obj U).complement ⟶ (toKaroubi _).obj D[U] where
  f := QInftyToDegenerateComplex U
  comm := complementToDegenerateComplex_comm U

/-- Helper for Lemma 14.23.6: the inclusion of the public degenerate complex is fixed by the
Karoubi complement projector. -/
private theorem degenerateComplexToComplement_comm (U : SimplicialObject A) :
    ((toKaroubi _).obj D[U]).p ≫ degenerateComplexι U ≫
        (N₁.obj U).complement.p = degenerateComplexι U := by
  -- TODO: compare the projector-wrapped inclusion with `degenerateComplexι U` degreewise.
  sorry

private def degenerateComplexToComplement (U : SimplicialObject A) :
    (toKaroubi _).obj D[U] ⟶ (N₁.obj U).complement where
  f := degenerateComplexι U
  comm := degenerateComplexToComplement_comm U

/-- Helper for Lemma 14.23.6: the comparison between the Karoubi complement and the public
degenerate complex is a left inverse on the complement side. -/
private theorem complementIsoDegenerateComplex_hom_inv_id (U : SimplicialObject A) :
    complementToDegenerateComplex U ≫ degenerateComplexToComplement U = 𝟙 (N₁.obj U).complement := by
  -- TODO: unfold the Karoubi-side identity and reduce to
  -- `QInftyToDegenerateComplex_comp_degenerateComplexι`.
  sorry

/-- Helper for Lemma 14.23.6: the comparison between the Karoubi complement and the public
degenerate complex is a right inverse on the degenerate side. -/
private theorem complementIsoDegenerateComplex_inv_hom_id (U : SimplicialObject A) :
    degenerateComplexToComplement U ≫ complementToDegenerateComplex U =
      𝟙 ((toKaroubi _).obj D[U]) := by
  -- Forgetting the Karoubi data, this is exactly the retract identity on `D(U)`.
  ext n
  simpa [complementToDegenerateComplex, degenerateComplexToComplement] using
    congrArg (fun k : D[U] ⟶ D[U] => k.f n)
      (degenerateComplexι_comp_QInftyToDegenerateComplex U)

private def complementIsoDegenerateComplex (U : SimplicialObject A) :
    (N₁.obj U).complement ≅ (toKaroubi _).obj D[U] where
  hom := complementToDegenerateComplex U
  inv := degenerateComplexToComplement U
  hom_inv_id := complementIsoDegenerateComplex_hom_inv_id U
  inv_hom_id := complementIsoDegenerateComplex_inv_hom_id U

/-- Helper for Lemma 14.23.6: the normalized inclusion is orthogonal to the degenerate projector
coming from `Q∞`. -/
private theorem inclusionOfMooreComplexMap_comp_QInftyToDegenerateComplex_eq_zero
    (U : SimplicialObject A) :
    inclusionOfMooreComplexMap U ≫ QInftyToDegenerateComplex U = 0 := by
  -- TODO: show the normalized inclusion is annihilated by `Q∞`, then factor through `D(U)`.
  sorry

/-- Helper for Lemma 14.23.6: the degenerate inclusion is orthogonal to the normalized
retraction. -/
private theorem degenerateComplexι_comp_PInftyToNormalizedMooreComplex_eq_zero
    (U : SimplicialObject A) :
    degenerateComplexι U ≫ PInftyToNormalizedMooreComplex U = 0 := by
  -- TODO: postcompose with `inclusionOfMooreComplexMap U` and use degreewise `P∞`-annihilation.
  sorry

-- Proof sketch: the core owner is the canonical Karoubi decomposition of `N₁.obj U`.
-- The source-facing comparison `K(U) ≅ N(U) ⊞ D(U)` is obtained by identifying the Karoubi
-- complement with `D(U)` via `QInftyToDegenerateComplex`/`degenerateComplexι`; this keeps the
-- public decomposition as a bridge/view statement rather than a second root owner.
/-- Helper for Lemma 14.23.6: the forward and backward maps in the biproduct decomposition of
`K(U)` compose to the identity on `K(U)`. -/
private theorem decomposition_hom_inv_id (U : SimplicialObject A) :
    biprod.lift (PInftyToNormalizedMooreComplex U) (QInftyToDegenerateComplex U) ≫
      biprod.desc (inclusionOfMooreComplexMap U) (degenerateComplexι U) = 𝟙 K[U] := by
  -- TODO: expand the biproduct composites and use `P∞ + Q∞ = 𝟙`.
  sorry

/-- Helper for Lemma 14.23.6: the backward and forward maps in the biproduct decomposition of
`K(U)` compose to the identity on `N(U) ⊞ D(U)`. -/
private theorem decomposition_inv_hom_id (U : SimplicialObject A) :
    biprod.desc (inclusionOfMooreComplexMap U) (degenerateComplexι U) ≫
      biprod.lift (PInftyToNormalizedMooreComplex U) (QInftyToDegenerateComplex U) =
        𝟙 (N[U] ⊞ D[U]) := by
  -- TODO: use biproduct extensionality with the four source-facing identities for the two summands.
  sorry

/-- Lemma 14.23.6: the alternating face map complex of a simplicial object decomposes as the direct
sum of the normalized Moore complex and the degenerate subcomplex generated by the degeneracies. -/
def decomposition (U : SimplicialObject A) : K[U] ≅ N[U] ⊞ D[U] where
  hom := biprod.lift (PInftyToNormalizedMooreComplex U) (QInftyToDegenerateComplex U)
  inv := biprod.desc (inclusionOfMooreComplexMap U) (degenerateComplexι U)
  hom_inv_id := decomposition_hom_inv_id U
  inv_hom_id := decomposition_inv_hom_id U

end AbelianBridge

end DoldKan

end AlgebraicTopology
