import Mathlib.Tactic.Recall
import ConvexAnalysis_Rockafellar_1970.Chap07.Text_34_2_4

/-!
Source/core/bridge triage:

- `source-facing`: Corollary 34.2.4 says that a saddle-function `K ∈ Ω(F)` is proper when the
  generating bifunction `F` is proper.
- `core/canonical`: the owner layer is already fixed upstream by `Bifunction.omega`,
  `SaddleFunction.IsProper`, and the theorem
  `Bifunction.isProper_of_mem_omega_of_uncurry_isConvex_of_uncurry_isProper`.
- `bridge/view`: this file adds no new owner data or weaker-to-stronger bridge. Its previous local
  wrapper only reintroduced the redundant source hypothesis `IsClosedConvex F`, although the
  properness proof uses only the derived convexity field `hF.convex`.

Primary mathematical domain:
- Chapter 34 saddle classes `Ω(F)` generated by a bifunction, together with graph properness and
  saddle properness.

Domain-style sampling used here:
- `Bifunction.omega` and `Bifunction.mem_omega_iff` from `Defn_34_2`;
- `Bifunction.IsClosedConvex` from `Defn_34_2`, whose `closed` field is not used by this
  properness result;
- `SaddleFunction.IsProper` from `Defn_34_3`;
- `Bifunction.isProper_of_mem_omega_of_uncurry_isConvex_of_uncurry_isProper` from
  `Text_34_2_4`.

Primitive data vs derived API:
- primitive data actually needed for this properness conclusion: graph convexity of `F`, graph
  properness of `F`, and membership `K ∈ Ω(F)`;
- derived stronger owner data: `IsClosedConvex F`, whose closedness component is unused here.

Layer target: `bridge/view`.
-/

/- Corollary 34.2.4 contributes no separate public theorem beyond the canonical upstream owner
`Bifunction.isProper_of_mem_omega_of_uncurry_isConvex_of_uncurry_isProper`; the source's
closedness hypothesis is redundant for this properness clause. -/
recall Bifunction.isProper_of_mem_omega_of_uncurry_isConvex_of_uncurry_isProper
