import Mathlib
import DifferentialForms_Cartan_1970.cartan.III.section11.PeriodLattice

-- Declarations for this item will be appended below by the statement pipeline.

-- Semantic recall note: the chapter owner `HasPeriodLattice` now lives in the importable library
-- module `cartan.III.section11.PeriodLattice`; this source file recalls that owner and keeps the
-- remaining source-facing constructions local.

universe u

/- Definition III.5-extra-7 (1): for a period pair `L`, a function on `ℂ` has the lattice
`Ω = L.lattice` as a group of periods when every `ω ∈ Ω` is a period of `f`. -/
#check HasPeriodLattice

/- Definition III.5-extra-7 (2): a function has the lattice generated by a period pair `L` as a
group of periods if and only if `L.ω₁` and `L.ω₂` are both periods of the function. -/
#check hasPeriodLattice_iff_periodic_generators

namespace PeriodPair

/-- Definition III.5-extra-7 (3): the period parallelogram with first vertex `z₀` attached to the
period pair `L` is the set of points `z₀ + t₁ ω₁ + t₂ ω₂` with `0 ≤ t₁, t₂ ≤ 1`. -/
def periodParallelogram (L : PeriodPair) (z₀ : ℂ) : Set ℂ :=
  {z | ∃ t₁ t₂ : ℝ, 0 ≤ t₁ ∧ t₁ ≤ 1 ∧ 0 ≤ t₂ ∧ t₂ ≤ 1 ∧
      z = z₀ + t₁ • L.ω₁ + t₂ • L.ω₂}

/-- A point lies in the period parallelogram exactly when it has the defining affine-coordinate
description with coefficients in the closed unit interval. -/
@[simp]
theorem mem_periodParallelogram_iff (L : PeriodPair) (z₀ z : ℂ) :
    z ∈ L.periodParallelogram z₀ ↔
      ∃ t₁ t₂ : ℝ, 0 ≤ t₁ ∧ t₁ ≤ 1 ∧ 0 ≤ t₂ ∧ t₂ ≤ 1 ∧
        z = z₀ + t₁ • L.ω₁ + t₂ • L.ω₂ :=
  Iff.rfl

end PeriodPair
