module

public import Book.Ch5.Definition_5_9.PeriodicExtension
public import Book.Ch5.Definition_5_24.HTTB
public import Book.Ch5.Definition_5_27.BCCB

public section

open scoped Matrix

universe u

namespace Matrix

variable {α : Type u}

/-- Helper for Proposition 5.28: periodic reduction of an integer difference agrees with the
corresponding `Fin` subtraction. -/
theorem periodicIndex_sub_eq_finSub {n : ℕ}
    (h : 0 < n) (i k : Fin n) :
    DiscreteSignal.periodicIndex n h (((i : ℕ) : ℤ) - ((k : ℕ) : ℤ)) = i - k := by
  -- Compare both reduced indices through their residue representatives in `ℤ`.
  apply Fin.ext
  have hsub : ((i - k : Fin n) : ℤ) = ((i : ℤ) - (k : ℤ)) % n :=
    Fin.coe_int_sub_eq_mod i k
  simpa [DiscreteSignal.periodicIndex_val] using congrArg Int.toNat hsub.symm

/-- Proposition 5.28 (1). If `C = Matrix.httb n_x n_y (Matrix.periodicExtension h_x h_y c)`,
then `C` is exactly the BCCB matrix `Matrix.bccb c`. -/
theorem periodicExtension_httb_eq_bccb {n_x n_y : ℕ}
    (h_x : 0 < n_x) (h_y : 0 < n_y) (c : Matrix (Fin n_x) (Fin n_y) α) :
    Matrix.httb n_x n_y (Matrix.periodicExtension h_x h_y c) = Matrix.bccb c := by
  -- Route correction: prove the HTTB-to-BCCB identification directly so this item no longer
  -- depends on the imported placeholder theorem in `Book/Ch5/Prop_5_28/HTTB.lean`.
  ext ji lk
  rcases ji with ⟨j, i⟩
  rcases lk with ⟨l, k⟩
  -- Expand both matrix owners to their entrywise formulas and reduce the periodic indices.
  rw [Matrix.httb_apply, Matrix.periodicExtension_apply, Matrix.bccb_apply]
  have hx :
      DiscreteSignal.periodicIndex n_x h_x (((i : ℕ) : ℤ) - ((k : ℕ) : ℤ)) = i - k := by
    -- Reduce the first coordinate by the general periodic-index normalization helper.
    simpa using periodicIndex_sub_eq_finSub h_x i k
  have hy :
      DiscreteSignal.periodicIndex n_y h_y (((j : ℕ) : ℤ) - ((l : ℕ) : ℤ)) = j - l := by
    -- Apply the same normalization in the block direction.
    simpa using periodicIndex_sub_eq_finSub h_y j l
  -- Rewriting the normalized periodic indices recovers the canonical BCCB entry formula.
  rw [hx, hy]

/-- Proposition 5.28 (2). The generating array `c` is recovered from the first
column of `Matrix.bccb c` by the canonical `Matrix.of` reconstruction. -/
theorem of_firstColumn_bccb {n_x n_y : ℕ} [NeZero n_x] [NeZero n_y]
    (c : Matrix (Fin n_x) (Fin n_y) α) :
    Matrix.of (fun i j ↦ ((Matrix.bccb c).col 0) (j, i)) = c := by
  -- Reuse the canonical first-column reconstruction for BCCB matrices.
  simpa using Matrix.of_bccb_col_zero c

/-- Proposition 5.28 (3). The `j`th block in the first block column of `Matrix.bccb c` is the
circulant matrix generated by the `j`th column of `c`. -/
theorem firstBlockColumn_bccb_eq_circulant {n_x n_y : ℕ} [NeZero n_y]
    (c : Matrix (Fin n_x) (Fin n_y) α) (j : Fin n_y) :
    (Matrix.bccb c).submatrix (fun i ↦ (j, i)) (fun k ↦ (0, k)) =
      Matrix.circulant (c.col j) := by
  -- Reuse the canonical description of the first block column of a BCCB matrix.
  simpa using Matrix.bccb_block_zero_eq_circulant c j

end Matrix
