module

public import ComputationalMethodsInverseProblems_Vogel_2002.Book.Ch2.Example_2_2.Instances
public import ComputationalMethodsInverseProblems_Vogel_2002.Book.Ch5.Definition_5_13

public section

noncomputable section

open scoped Matrix.Norms.Frobenius

namespace Matrix

/-- The generating coefficients of the circulant approximation of a real square matrix,
indexed by `j : Fin n`. -/
@[expose]
def bestCirculantApproximationCoeffs {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) : Fin n → ℝ :=
  fun j ↦ (1 / (n : ℝ)) * inner ℝ A (Matrix.circulantRightShift n ^ (j : ℕ))

/-- The circulant approximation of a real square matrix. -/
@[expose]
def bestCirculantApproximation {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) :
    Matrix (Fin n) (Fin n) ℝ :=
  Matrix.circulant (bestCirculantApproximationCoeffs A)

/-- Proposition 5.20. For a real square matrix `A`, `bestCirculantApproximation A` is the
circulant matrix generated by the coefficients
`fun j : Fin n ↦ (1 / (n : ℝ)) * inner ℝ A (Matrix.circulantRightShift n ^ (j : ℕ))`. -/
theorem bestCirculantApproximation_eq_circulant_frobeniusCoeffs
    {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) :
    bestCirculantApproximation A =
      Matrix.circulant
        (fun j : Fin n ↦
          (1 / (n : ℝ)) * inner ℝ A (Matrix.circulantRightShift n ^ (j : ℕ))) := by
  rfl

end Matrix
