import BauschkeLean.Chap29.Example_29_45
import BauschkeLean.Chap01.Fact_1_15
import BauschkeLean.Chap02.Lemma_2_45
import BauschkeLean.Chap03.Corollary_3_35
import BauschkeLean.Chap03.Theorem_3_16_2
import BauschkeLean.Chap30.Lemma_30_6

-- Declarations for this item will be appended below by the statement pipeline.

open Filter
open scoped Topology

universe u

section

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
variable {m : ℕ} (C : Fin m → Set H) (hC_cheb : ∀ i, IsChebyshev (C i)) (hm : 0 < m)

/-- The next finite-family Dykstra state `(x, q)` obtained by projecting onto the currently active
set and updating only the active correction term. -/
noncomputable def dykstraNextState (s : H × (Fin m → H)) (n : ℕ) : H × (Fin m → H) :=
  let i : Fin m := ⟨n % m, Nat.mod_lt n hm⟩
  let x := s.1
  let q := s.2
  let x' := P[C i, hC_cheb i] (x + q i)
  (x', Function.update q i (x + q i - x'))

/-- The Dykstra state for a finite family of Chebyshev sets, initialized at `x₀` with vanishing
corrections. This finite-family state owner is the canonical Lean replacement for the textbook's
single correction sequence `(q_n)` with `q_{-(m-1)} = ⋯ = q₀ = 0`. -/
noncomputable def dykstraState (x0 : H) : ℕ → H × (Fin m → H)
  | 0 => (x0, 0)
  | n + 1 => dykstraNextState C hC_cheb hm (dykstraState x0 n) n

/-- The primal iterate sequence generated by the finite-family Dykstra state recursion. -/
noncomputable def dykstraProjectionSequence (x0 : H) : ℕ → H :=
  fun n ↦ (dykstraState C hC_cheb hm x0 n).1

/-- The correction family carried by the finite-family Dykstra state recursion. -/
noncomputable def dykstraCorrectionSequence (x0 : H) : ℕ → Fin m → H :=
  fun n ↦ (dykstraState C hC_cheb hm x0 n).2

omit [InnerProductSpace ℝ H] [CompleteSpace H] in
/-- The Dykstra state starts from the prescribed initial point and the zero correction family. -/
@[simp] theorem dykstraState_zero (x0 : H) :
    dykstraState C hC_cheb hm x0 0 = (x0, 0) :=
  rfl

omit [InnerProductSpace ℝ H] [CompleteSpace H] in
/-- The Dykstra state satisfies its defining recursion. -/
@[simp] theorem dykstraState_succ (x0 : H) (n : ℕ) :
    dykstraState C hC_cheb hm x0 (n + 1) =
      dykstraNextState C hC_cheb hm (dykstraState C hC_cheb hm x0 n) n :=
  rfl

omit [InnerProductSpace ℝ H] [CompleteSpace H] in
/-- The primal Dykstra sequence starts at the prescribed initial point. -/
@[simp] theorem dykstraProjectionSequence_zero (x0 : H) :
    dykstraProjectionSequence C hC_cheb hm x0 0 = x0 :=
  rfl

omit [InnerProductSpace ℝ H] [CompleteSpace H] in
/-- The correction family of the Dykstra recursion is initially zero. -/
@[simp] theorem dykstraCorrectionSequence_zero (x0 : H) :
    dykstraCorrectionSequence C hC_cheb hm x0 0 = 0 :=
  rfl

section

variable {m : ℕ} {C : Fin m → Set H}
variable (hC_nonempty : (⋂ i, C i).Nonempty)
variable (hC_closed : ∀ i, IsClosed (C i)) (hC_convex : ∀ i, Convex ℝ (C i))

local notation "InterC" => ⋂ i, C i

local notation "hFamily_cheb" =>
  family_isChebyshev_of_iInter_nonempty_closed_convex C hC_nonempty hC_closed hC_convex

local notation "hInter_cheb" =>
  isChebyshev_of_nonempty_isClosed_convex hC_nonempty
    (isClosed_iInter hC_closed) (convex_iInter hC_convex)

/- mathlib semantic recall: `lean_leansearch` surfaced submodule and affine-subspace
`orthogonalProjection` owners, while nearby Chapter 30 precedent uses the project's metric
projection owner `P[C, hC]`; this item therefore uses the canonical projection onto `⋂ i, C i`
for the limit point and packages the cyclic Dykstra corrections as a finite family `Fin m → H`. -/

/-- Helper for Theorem 30.7: the active family index at step `n` is the residue class `n % m`. -/
private def dykstraActiveIndex (hm : 0 < m) (n : ℕ) : Fin m :=
  ⟨n % m, Nat.mod_lt n hm⟩

/-- Helper for Theorem 30.7: the primal Dykstra iterate at step `n + 1` is the projection of the
active corrected point onto the active set. -/
private theorem dykstraProjectionSequence_succ_apply (hm : 0 < m) (x0 : H) (n : ℕ) :
    dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) =
      P[C (dykstraActiveIndex (m := m) hm n), hFamily_cheb (dykstraActiveIndex (m := m) hm n)]
        (dykstraProjectionSequence C hFamily_cheb hm x0 n +
          dykstraCorrectionSequence C hFamily_cheb hm x0 n
            (dykstraActiveIndex (m := m) hm n)) := by
  -- Unfold one recursion step and expose the active projector update.
  simp [dykstraProjectionSequence, dykstraCorrectionSequence, dykstraState_succ,
    dykstraNextState, dykstraActiveIndex]

/-- Helper for Theorem 30.7: the active correction coordinate records the projection residual at
the next step. -/
private theorem dykstraCorrectionSequence_succ_active (hm : 0 < m) (x0 : H) (n : ℕ) :
    dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
        (dykstraActiveIndex (m := m) hm n) =
      dykstraProjectionSequence C hFamily_cheb hm x0 n +
        dykstraCorrectionSequence C hFamily_cheb hm x0 n
          (dykstraActiveIndex (m := m) hm n) -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) := by
  -- Unfold one recursion step and read the updated active coordinate of `Function.update`.
  simp [dykstraCorrectionSequence, dykstraProjectionSequence, dykstraState_succ,
    dykstraNextState, dykstraActiveIndex]

/-- Helper for Theorem 30.7: non-active correction coordinates are unchanged by a Dykstra step. -/
private theorem dykstraCorrectionSequence_succ_inactive
    (hm : 0 < m) (x0 : H) (n : ℕ) {j : Fin m}
    (hj :
      j ≠ dykstraActiveIndex (m := m) hm n) :
    dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) j =
      dykstraCorrectionSequence C hFamily_cheb hm x0 n j := by
  -- Unfold one recursion step and then use `Function.update_of_ne` on the inactive coordinate.
  rw [dykstraCorrectionSequence, dykstraState_succ, dykstraNextState]
  exact Function.update_of_ne hj _ _

/-- Helper for Theorem 30.7: the primal increment is the difference of the active correction
coordinates before and after the update. -/
private theorem dykstraProjectionSequence_sub_succ_eq_activeCorrectionDiff
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    dykstraProjectionSequence C hFamily_cheb hm x0 n -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) =
      dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
          (dykstraActiveIndex (m := m) hm n) -
        dykstraCorrectionSequence C hFamily_cheb hm x0 n
          (dykstraActiveIndex (m := m) hm n) := by
  -- Rewrite the active residual and regroup the common terms into the primal increment.
  rw [dykstraCorrectionSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)]
  abel_nf

/-- Helper for Theorem 30.7: the sum of the correction family changes by the primal increment in
one Dykstra step. -/
private theorem dykstraCorrectionSequence_sum_succ
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    (∑ i, dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) i) =
      (∑ i, dykstraCorrectionSequence C hFamily_cheb hm x0 n i) +
        (dykstraProjectionSequence C hFamily_cheb hm x0 n -
          dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
  let i : Fin m := dykstraActiveIndex (m := m) hm n
  let qn := dykstraCorrectionSequence C hFamily_cheb hm x0 n
  let qn1 := dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
  -- Isolate the active coordinate in the updated family sum.
  have hupdate : qn1 = Function.update qn i (qn1 i) := by
    funext j
    by_cases hj : j = i
    · subst hj
      simp
    · have hinactive :=
        dykstraCorrectionSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
          (j := j) hj
      simpa [qn, qn1, Function.update_of_ne hj] using hinactive
  -- Replace the active update by the primal increment identity.
  calc
    ∑ j, qn1 j
        = qn1 i + (∑ j ∈ Finset.univ.erase i, qn j) := by
            rw [hupdate]
            simpa [qn] using
              (Finset.sum_update_of_mem (s := Finset.univ) (i := i) (f := qn) (b := qn1 i)
                (by simp))
    _ = qn i + (∑ j ∈ Finset.univ.erase i, qn j) +
          (dykstraProjectionSequence C hFamily_cheb hm x0 n -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
              rw [dykstraProjectionSequence_sub_succ_eq_activeCorrectionDiff
                (C := C) (hC_nonempty := hC_nonempty) (hC_closed := hC_closed)
                (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)]
              dsimp [qn, qn1, i]
              abel_nf
    _ = (∑ j, qn j) +
          (dykstraProjectionSequence C hFamily_cheb hm x0 n -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
              rw [Finset.add_sum_erase (s := Finset.univ) (f := qn) (a := i) (by simp)]

/-- Helper for Theorem 30.7: the initial displacement `x₀ - xₙ` is exactly the sum of the
current correction family. -/
private theorem dykstraInitialGap_eq_sumCorrections
    (hm : 0 < m) (x0 : H) :
    ∀ n,
      x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n =
        ∑ i, dykstraCorrectionSequence C hFamily_cheb hm x0 n i
  | 0 => by
      -- The zero state has no correction family, so the gap identity is immediate.
      simp [dykstraProjectionSequence, dykstraCorrectionSequence]
  | n + 1 => by
      -- Telescope the previous gap identity with the one-step correction-sum update.
      calc
        x0 - dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)
            = (x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n) +
                (dykstraProjectionSequence C hFamily_cheb hm x0 n -
                  dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
                    abel_nf
        _ = (∑ i, dykstraCorrectionSequence C hFamily_cheb hm x0 n i) +
              (dykstraProjectionSequence C hFamily_cheb hm x0 n -
                dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
                  rw [dykstraInitialGap_eq_sumCorrections (hm := hm) (x0 := x0) n]
        _ = ∑ i, dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) i := by
              simpa using
                (dykstraCorrectionSequence_sum_succ (C := C) (hC_nonempty := hC_nonempty)
                  (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0)
                  (n := n)).symm

/-- Helper for Theorem 30.7: the active iterate belongs to the active set after each projection
step. -/
private theorem dykstraProjectionSequence_succ_mem_activeSet
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) ∈
      C (dykstraActiveIndex (m := m) hm n) := by
  -- The projector output lies in its target set.
  rw [dykstraProjectionSequence_succ_apply (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)]
  exact projectionPoint_mem _ _ _

/-- Helper for Theorem 30.7: the active correction satisfies the variational inequality coming from
the projection characterization on the active set. -/
private theorem dykstraActiveCorrection_inner_sub_right_nonpos
    (hm : 0 < m) (x0 : H) (n : ℕ) {y : H}
    (hy : y ∈ C (dykstraActiveIndex (m := m) hm n)) :
    inner ℝ
        (y - dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
        (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
          (dykstraActiveIndex (m := m) hm n)) ≤ 0 := by
  let i : Fin m := dykstraActiveIndex (m := m) hm n
  have hproj :
      dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) =
        P[C i, hFamily_cheb i]
          (dykstraProjectionSequence C hFamily_cheb hm x0 n +
            dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
    simpa [i] using
      dykstraProjectionSequence_succ_apply (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
  have hchar :=
    (eq_projectionPoint_iff_mem_and_inner_sub_right_nonpos_of_nonempty_isClosed_convex
      (C := C i)
      (hC_nonempty := ⟨
        Classical.choose hC_nonempty,
        Set.mem_iInter.mp (Classical.choose_spec hC_nonempty) i
      ⟩)
      (hC_closed := hC_closed i) (hC_convex := hC_convex i)
      (x := dykstraProjectionSequence C hFamily_cheb hm x0 n +
        dykstraCorrectionSequence C hFamily_cheb hm x0 n i)
      (p := dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))).mp hproj
  -- Replace the active residual by the explicit correction update.
  simpa [i, dykstraCorrectionSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)] using
    hchar.2 y hy

/-- Helper for Theorem 30.7: the private anchor family remembers, for each coordinate, the iterate
that last created the currently stored correction. -/
private noncomputable def dykstraCorrectionAnchorSequence (hm : 0 < m) (x0 : H) : ℕ → Fin m → H
  | 0 => fun _ ↦ x0
  | n + 1 =>
      Function.update
        (dykstraCorrectionAnchorSequence hm x0 n)
        (dykstraActiveIndex (m := m) hm n)
        (dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))

local notation "anchorSeq" =>
  dykstraCorrectionAnchorSequence (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex)

/-- Helper for Theorem 30.7: at the active coordinate, the anchor family is updated to the new
primal iterate. -/
private theorem dykstraCorrectionAnchorSequence_succ_active
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    anchorSeq hm x0 (n + 1) (dykstraActiveIndex (m := m) hm n) =
      dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) := by
  -- Unfold the recursive anchor update and read the active coordinate of `Function.update`.
  simp [dykstraCorrectionAnchorSequence, dykstraActiveIndex]

/-- Helper for Theorem 30.7: inactive anchor coordinates are preserved by one Dykstra step. -/
private theorem dykstraCorrectionAnchorSequence_succ_inactive
    (hm : 0 < m) (x0 : H) (n : ℕ) {j : Fin m}
    (hj : j ≠ dykstraActiveIndex (m := m) hm n) :
    anchorSeq hm x0 (n + 1) j = anchorSeq hm x0 n j := by
  -- Unfold the recursive anchor update and keep the inactive coordinate unchanged.
  rw [dykstraCorrectionAnchorSequence]
  exact Function.update_of_ne hj _ _

/-- Helper for Theorem 30.7: every stored correction keeps the projection inequality against the
iterate that created it. -/
private theorem dykstraStoredCorrectionAnchor_nonneg
    (hm : 0 < m) (x0 : H) :
    ∀ n (i : Fin m) {y : H}, y ∈ C i →
      0 ≤
        inner ℝ
          (anchorSeq hm x0 n i - y)
          (dykstraCorrectionSequence C hFamily_cheb hm x0 n i)
  | 0, i, y, hy => by
      -- The initial correction family vanishes, so the anchor pairing is zero.
      simp [dykstraCorrectionAnchorSequence, dykstraCorrectionSequence]
  | n + 1, i, y, hy => by
      by_cases hi : i = dykstraActiveIndex (m := m) hm n
      · subst hi
        have hnonpos :=
          dykstraActiveCorrection_inner_sub_right_nonpos (C := C) (hC_nonempty := hC_nonempty)
            (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
            (y := y) hy
        have hxy :
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) - y =
              -(y - dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
          abel_nf
        have hflip :
            inner ℝ
                (dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) - y)
                (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
                  (dykstraActiveIndex (m := m) hm n)) =
              -inner ℝ
                (y - dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
                (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
                  (dykstraActiveIndex (m := m) hm n)) := by
          rw [hxy, inner_neg_left]
        -- Flip the sign of the variational inequality to obtain the nonnegative anchor pairing.
        rw [dykstraCorrectionAnchorSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n), hflip]
        exact neg_nonneg.mpr hnonpos
      · have hanchor :=
          dykstraCorrectionAnchorSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
            (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
            (j := i) hi
        have hcorr :=
          dykstraCorrectionSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
            (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
            (j := i) hi
        -- Away from the active coordinate, both the anchor and the correction are unchanged.
        simpa [hanchor, hcorr] using
          dykstraStoredCorrectionAnchor_nonneg hm x0 n i hy

/-- Helper for Theorem 30.7: the scalar anchor pairing is the finite-family owner that telescopes
the source correction terms. -/
private noncomputable def dykstraAnchorPairing
    (hm : 0 < m) (x0 : H) (n : ℕ) (z : H) : ℝ :=
  ∑ i,
    inner ℝ
      (anchorSeq hm x0 n i - z)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 n i)

local notation "anchorPairing" =>
  dykstraAnchorPairing (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex)

/-- Helper for Theorem 30.7: one Dykstra step updates the scalar anchor pairing only through the
active coordinate. -/
private theorem dykstraAnchorPairing_step
    (hm : 0 < m) (x0 : H) (n : ℕ) (z : H) :
    anchorPairing hm x0 n z =
      anchorPairing hm x0 (n + 1) z +
        inner ℝ
          (anchorSeq hm x0 n (dykstraActiveIndex (m := m) hm n) - z)
          (dykstraCorrectionSequence C hFamily_cheb hm x0 n (dykstraActiveIndex (m := m) hm n)) -
        inner ℝ
          (dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) - z)
          (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
            (dykstraActiveIndex (m := m) hm n)) := by
  let i : Fin m := dykstraActiveIndex (m := m) hm n
  let oldTerm : ℝ :=
    inner ℝ
      (anchorSeq hm x0 n i - z)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 n i)
  let newTerm : ℝ :=
    inner ℝ
      (dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) - z)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) i)
  let f : Fin m → ℝ := fun j ↦
    inner ℝ
      (anchorSeq hm x0 n j - z)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 n j)
  let f1 : Fin m → ℝ := fun j ↦
    inner ℝ
      (anchorSeq hm x0 (n + 1) j - z)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) j)
  have hf1 :
      f1 = Function.update f i newTerm := by
    funext j
    by_cases hj : j = i
    · subst hj
      simp [f1, f, newTerm, i, dykstraCorrectionAnchorSequence_succ_active]
    · have hanchor :=
        dykstraCorrectionAnchorSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
          (j := j) hj
      have hcorr :=
        dykstraCorrectionSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
          (j := j) hj
      -- Outside the active coordinate, the scalar term is unchanged.
      rw [Function.update_of_ne hj]
      simp [f1, f, hanchor, hcorr]
  -- Isolate the active scalar contribution and rewrite the remaining sum through `Function.update`.
  calc
    anchorPairing hm x0 n z
        = oldTerm + ∑ j ∈ Finset.univ.erase i, f j := by
            rw [dykstraAnchorPairing]
            simp [f, oldTerm]
    _ = (newTerm + ∑ j ∈ Finset.univ.erase i, f j) + oldTerm - newTerm := by ring
    _ = anchorPairing hm x0 (n + 1) z + oldTerm - newTerm := by
          have hsum1 :
              anchorPairing hm x0 (n + 1) z = newTerm + ∑ j ∈ Finset.univ.erase i, f j := by
            rw [dykstraAnchorPairing]
            change ∑ j, f1 j = newTerm + ∑ j ∈ Finset.univ.erase i, f j
            rw [hf1]
            simpa [f, f1, newTerm] using
              (Finset.sum_update_of_mem (s := Finset.univ) (i := i) (f := f) (b := newTerm)
                (by simp))
          rw [hsum1]

/-- Helper for Theorem 30.7: the scalar anchor pairing is nonnegative at every point of the
intersection because each coordinate contribution is nonnegative. -/
private theorem dykstraAnchorPairing_nonneg
    (hm : 0 < m) (x0 : H) {z : H} (hz : z ∈ InterC) (n : ℕ) :
    0 ≤ anchorPairing hm x0 n z := by
  -- Sum the coordinatewise nonnegativity furnished by the stored-anchor invariant.
  rw [dykstraAnchorPairing]
  refine Finset.sum_nonneg ?_
  intro i hi
  exact
    dykstraStoredCorrectionAnchor_nonneg (hC_nonempty := hC_nonempty)
      (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) n i
      (Set.mem_iInter.mp hz i)

omit [CompleteSpace H] in
/-- Helper for Theorem 30.7: the one-coordinate source polarization identity that the future
augmented-energy telescope must use. -/
private theorem dykstraAugmentedEnergyPointStep
    (p p' a z q : H) :
    ‖p - z‖ ^ 2 + 2 * inner ℝ (a - z) q =
      ‖p' - z‖ ^ 2 + 2 * inner ℝ (p' - z) (p + q - p') +
        ‖p - p'‖ ^ 2 + 2 * inner ℝ (a - p') q := by
  have hp : p - z = (p' - z) + (p - p') := by
    abel_nf
  have ha : a - z = (a - p') + (p' - z) := by
    abel_nf
  have hq : p + q - p' = (p - p') + q := by
    abel_nf
  -- Expand the norm square around the new iterate and separate the old correction term.
  calc
    ‖p - z‖ ^ 2 + 2 * inner ℝ (a - z) q
        = ‖(p' - z) + (p - p')‖ ^ 2 + 2 * inner ℝ (a - z) q := by
            rw [hp]
    _ = ‖p' - z‖ ^ 2 + 2 * inner ℝ (p' - z) (p - p') +
          ‖p - p'‖ ^ 2 + 2 * inner ℝ (a - z) q := by
            rw [norm_add_sq_real]
    _ = ‖p' - z‖ ^ 2 + 2 * inner ℝ (p' - z) (p - p') +
          ‖p - p'‖ ^ 2 +
            2 * inner ℝ (a - p') q + 2 * inner ℝ (p' - z) q := by
              rw [ha, inner_add_left]
              ring
    _ = ‖p' - z‖ ^ 2 + 2 * inner ℝ (p' - z) (p + q - p') +
          ‖p - p'‖ ^ 2 + 2 * inner ℝ (a - p') q := by
            rw [hq, inner_add_right]
            ring

/-- Helper for Theorem 30.7: the augmented energy `‖x_n - z‖^2 + 2 B_n(z)` packages the pointwise
polarization identity together with the scalar anchor pairing. -/
private noncomputable def dykstraAugmentedEnergy
    (hm : 0 < m) (x0 : H) (n : ℕ) (z : H) : ℝ :=
  ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - z‖ ^ 2 +
    2 * anchorPairing hm x0 n z

local notation "augEnergy" =>
  dykstraAugmentedEnergy (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex)

/-- Helper for Theorem 30.7: the augmented energy changes by the squared step size plus the
active anchor pairing against the new iterate. -/
private theorem dykstraAugmentedEnergyStep
    (hm : 0 < m) (x0 : H) (n : ℕ) (z : H) :
    let i : Fin m := dykstraActiveIndex (m := m) hm n
    augEnergy hm x0 n z =
      augEnergy hm x0 (n + 1) z +
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖ ^ 2 +
        2 *
          inner ℝ
            (anchorSeq hm x0 n i -
              dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
            (dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
  let i : Fin m := dykstraActiveIndex (m := m) hm n
  let xN := dykstraProjectionSequence C hFamily_cheb hm x0 n
  let xN1 := dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)
  let aN := anchorSeq hm x0 n i
  let qN := dykstraCorrectionSequence C hFamily_cheb hm x0 n i
  let qN1 := dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1) i
  have hactive :
      qN1 = xN + qN - xN1 := by
    simpa [xN, xN1, qN, qN1, i] using
      (dykstraCorrectionSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n))
  have hpoint :
      ‖xN - z‖ ^ 2 + 2 * inner ℝ (aN - z) qN =
        ‖xN1 - z‖ ^ 2 + 2 * inner ℝ (xN1 - z) qN1 +
          ‖xN - xN1‖ ^ 2 + 2 * inner ℝ (aN - xN1) qN := by
    -- Rewrite the one-coordinate polarization identity through the active correction update.
    have hpoint0 :=
      dykstraAugmentedEnergyPointStep (p := xN) (p' := xN1) (a := aN) (z := z) (q := qN)
    rw [← hactive] at hpoint0
    simpa using hpoint0
  have hpair :=
    dykstraAnchorPairing_step (C := C) (hC_nonempty := hC_nonempty) (hC_closed := hC_closed)
      (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n) (z := z)
  -- Combine the pointwise identity with the scalar pairing telescope.
  calc
    augEnergy hm x0 n z
        = ‖xN - z‖ ^ 2 + 2 * anchorPairing hm x0 n z := by
            simp [dykstraAugmentedEnergy, xN]
    _ = ‖xN - z‖ ^ 2 +
          2 *
            (anchorPairing hm x0 (n + 1) z +
              inner ℝ (aN - z) qN -
              inner ℝ (xN1 - z) qN1) := by
                simpa [i, xN1, aN, qN, qN1] using hpair
    _ = (‖xN - z‖ ^ 2 + 2 * inner ℝ (aN - z) qN) +
          (2 * anchorPairing hm x0 (n + 1) z -
            2 * inner ℝ (xN1 - z) qN1) := by
              ring
    _ = (‖xN1 - z‖ ^ 2 + 2 * inner ℝ (xN1 - z) qN1 +
          ‖xN - xN1‖ ^ 2 + 2 * inner ℝ (aN - xN1) qN) +
          (2 * anchorPairing hm x0 (n + 1) z -
            2 * inner ℝ (xN1 - z) qN1) := by
              rw [hpoint]
    _ = augEnergy hm x0 (n + 1) z +
          ‖xN - xN1‖ ^ 2 + 2 * inner ℝ (aN - xN1) qN := by
            simp [dykstraAugmentedEnergy, xN1]
            ring

/-- Helper for Theorem 30.7: points of the intersection make the augmented energy nonincreasing
along the Dykstra orbit. -/
private theorem dykstraAugmentedEnergyStep_nonincreasing
    (hm : 0 < m) (x0 : H) {z : H} (n : ℕ) :
    augEnergy hm x0 (n + 1) z ≤ augEnergy hm x0 n z := by
  let i : Fin m := dykstraActiveIndex (m := m) hm n
  have hstep :=
    dykstraAugmentedEnergyStep (C := C) (hC_nonempty := hC_nonempty) (hC_closed := hC_closed)
      (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n) (z := z)
  have hmem :
      dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) ∈ C i := by
    simpa [i] using
      dykstraProjectionSequence_succ_mem_activeSet (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := n)
  have hanchor :
      0 ≤
        inner ℝ
          (anchorSeq hm x0 n i -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
          (dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
    -- Apply the anchor invariant with the active-set point `x_{n+1}`.
    exact
      dykstraStoredCorrectionAnchor_nonneg (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) n i hmem
  have hsq :
      0 ≤
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖ ^ 2 := by
    positivity
  -- Drop the nonnegative remainder terms from the exact augmented-energy identity.
  linarith [hstep, hanchor, hsq]

/-- Helper for Theorem 30.7: the scalar boundary tail packages the difference between the current
iterate and the stored anchor family against the current correction family. -/
private noncomputable def dykstraBoundaryTail
    (hm : 0 < m) (x0 : H) (n : ℕ) : ℝ :=
  ∑ i,
    |inner ℝ
      (anchorSeq hm x0 n i -
        dykstraProjectionSequence C hFamily_cheb hm x0 n)
      (dykstraCorrectionSequence C hFamily_cheb hm x0 n i)|

local notation "boundaryTail" =>
  dykstraBoundaryTail (C := C) (hC_nonempty := hC_nonempty)
    (hC_closed := hC_closed) (hC_convex := hC_convex)

/-- Helper for Theorem 30.7: the scalar boundary tail is nonnegative termwise. -/
private theorem dykstraBoundaryTail_nonneg
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    0 ≤ boundaryTail hm x0 n := by
  -- The owner is a finite sum of absolute values.
  refine Finset.sum_nonneg ?_
  intro i hi
  exact abs_nonneg _

/-- Helper for Theorem 30.7: the source inner-gap term is bounded above by the scalar boundary
tail once the correction-family sum identity is rewritten through the stored anchors. -/
private theorem dykstraBoundaryTail_innerGap_le
    (hm : 0 < m) (x0 : H) {z : H} (hz : z ∈ InterC) (n : ℕ) :
    inner ℝ
        (z - dykstraProjectionSequence C hFamily_cheb hm x0 n)
        (x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n) ≤
      boundaryTail hm x0 n := by
  let xN := dykstraProjectionSequence C hFamily_cheb hm x0 n
  let qN := dykstraCorrectionSequence C hFamily_cheb hm x0 n
  let aN := anchorSeq hm x0 n
  have hgap :
      x0 - xN = ∑ i, qN i := by
    simpa [xN, qN] using
      dykstraInitialGap_eq_sumCorrections (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) n
  -- Expand the source gap through the family-valued correction sum.
  calc
    inner ℝ (z - xN) (x0 - xN)
        = ∑ i, inner ℝ (z - xN) (qN i) := by
            rw [hgap, inner_sum]
    _ = ∑ i,
          (inner ℝ (z - aN i) (qN i) + inner ℝ (aN i - xN) (qN i)) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            have hsplit : z - xN = (z - aN i) + (aN i - xN) := by
              abel_nf
            rw [hsplit, inner_add_left]
    _ ≤ ∑ i, |inner ℝ (aN i - xN) (qN i)| := by
          refine Finset.sum_le_sum ?_
          intro i hi
          have hstored :
              0 ≤ inner ℝ (aN i - z) (qN i) := by
            simpa [aN, qN] using
              dykstraStoredCorrectionAnchor_nonneg (C := C) (hC_nonempty := hC_nonempty)
                (hC_closed := hC_closed) (hC_convex := hC_convex)
                (hm := hm) (x0 := x0) n i (Set.mem_iInter.mp hz i)
          have hnonpos :
              inner ℝ (z - aN i) (qN i) ≤ 0 := by
            have hflip :
                inner ℝ (z - aN i) (qN i) =
                  -inner ℝ (aN i - z) (qN i) := by
              have hza : z - aN i = -(aN i - z) := by
                abel_nf
              rw [hza, inner_neg_left]
            calc
              inner ℝ (z - aN i) (qN i)
                  = -inner ℝ (aN i - z) (qN i) := hflip
              _ ≤ 0 := neg_nonpos.mpr hstored
          calc
            inner ℝ (z - aN i) (qN i) + inner ℝ (aN i - xN) (qN i)
                ≤ 0 + inner ℝ (aN i - xN) (qN i) := by
                    gcongr
            _ ≤ 0 + |inner ℝ (aN i - xN) (qN i)| := by
                  gcongr
                  exact le_abs_self _
            _ = |inner ℝ (aN i - xN) (qN i)| := by ring
    _ = boundaryTail hm x0 n := by
          simp [dykstraBoundaryTail, xN, qN, aN]

/-- Helper for Theorem 30.7: the total norm of the correction family is controlled by the prefix
sum of primal step norms. -/
private theorem dykstraCorrectionNormSum_le_prefixSteps
    (hm : 0 < m) (x0 : H) :
    ∀ n,
      (∑ i, ‖dykstraCorrectionSequence C hFamily_cheb hm x0 n i‖) ≤
        ∑ k ∈ Finset.range n,
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
            dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖
  | 0 => by
      -- The correction family starts from zero, so the norm sum vanishes at the base time.
      simp [dykstraCorrectionSequence]
  | n + 1 => by
      let i : Fin m := dykstraActiveIndex (m := m) hm n
      let qN := dykstraCorrectionSequence C hFamily_cheb hm x0 n
      let qN1 := dykstraCorrectionSequence C hFamily_cheb hm x0 (n + 1)
      let step :=
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
          dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖
      have hupdate :
          (fun j ↦ ‖qN1 j‖) = Function.update (fun j ↦ ‖qN j‖) i ‖qN1 i‖ := by
        funext j
        by_cases hj : j = i
        · subst hj
          simp
        · have hcorr :=
            dykstraCorrectionSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
              (hC_closed := hC_closed) (hC_convex := hC_convex)
              (hm := hm) (x0 := x0) (n := n) (j := j) hj
          rw [Function.update_of_ne hj]
          simpa [qN, qN1] using congrArg norm hcorr
      have hactive :
          ‖qN1 i‖ ≤ ‖qN i‖ + step := by
        have hactiveRaw :
            qN1 i =
              dykstraProjectionSequence C hFamily_cheb hm x0 n +
                qN i -
                dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) := by
          simpa [i, qN, qN1] using
            dykstraCorrectionSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
              (hC_closed := hC_closed) (hC_convex := hC_convex)
              (hm := hm) (x0 := x0) (n := n)
        have hactive0 :
            qN1 i =
              qN i +
                (dykstraProjectionSequence C hFamily_cheb hm x0 n -
                  dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)) := by
          rw [hactiveRaw]
          abel_nf
        calc
          ‖qN1 i‖
              = ‖qN i +
                  (dykstraProjectionSequence C hFamily_cheb hm x0 n -
                    dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))‖ := by
                  rw [hactive0]
          _ ≤ ‖qN i‖ +
                ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
                  dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖ :=
                norm_add_le _ _
          _ = ‖qN i‖ + step := by rfl
      -- Isolate the active coordinate and use the triangle inequality on its update.
      have hsumq :
          ∑ j, ‖qN j‖ = ‖qN i‖ + ∑ j ∈ Finset.univ.erase i, ‖qN j‖ := by
        rw [Finset.add_sum_erase (s := Finset.univ) (f := fun j ↦ ‖qN j‖) (a := i) (by simp)]
      calc
        ∑ j, ‖qN1 j‖
            = ‖qN1 i‖ + ∑ j ∈ Finset.univ.erase i, ‖qN j‖ := by
                rw [hupdate]
                simpa using
                  (Finset.sum_update_of_mem (s := Finset.univ) (i := i)
                    (f := fun j ↦ ‖qN j‖) (b := ‖qN1 i‖) (by simp))
        _ ≤ (‖qN i‖ + step) + ∑ j ∈ Finset.univ.erase i, ‖qN j‖ := by
              gcongr
        _ = (∑ j, ‖qN j‖) + step := by
              calc
                (‖qN i‖ + step) + ∑ j ∈ Finset.univ.erase i, ‖qN j‖
                    = (‖qN i‖ + ∑ j ∈ Finset.univ.erase i, ‖qN j‖) + step := by ring
                _ = (∑ j, ‖qN j‖) + step := by rw [← hsumq]
        _ ≤ (∑ k ∈ Finset.range n,
              ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
                dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖) + step := by
              gcongr
              exact dykstraCorrectionNormSum_le_prefixSteps hm x0 n
        _ = ∑ k ∈ Finset.range (n + 1),
              ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
                dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖ := by
              simp [step, Finset.sum_range_succ, add_comm]

omit [InnerProductSpace ℝ H] [CompleteSpace H] in
/-- Helper for Theorem 30.7: the distance between two iterates is controlled by the sum of the
intermediate step norms. -/
private theorem norm_sub_le_sum_stepNorms (x : ℕ → H) (n k : ℕ) :
    ‖x n - x (n + k)‖ ≤
      ∑ j ∈ Finset.range k, ‖x (n + j) - x (n + j + 1)‖ := by
  induction k with
  | zero =>
      -- The empty chain has no displacement.
      simp
  | succ k hk =>
      -- Split the long displacement at the penultimate iterate and apply the triangle inequality.
      calc
        ‖x n - x (n + (k + 1))‖
            = ‖(x n - x (n + k)) + (x (n + k) - x (n + k + 1))‖ := by
                congr 1
                abel_nf
        _ ≤ ‖x n - x (n + k)‖ + ‖x (n + k) - x (n + k + 1)‖ := norm_add_le _ _
        _ ≤ (∑ j ∈ Finset.range k, ‖x (n + j) - x (n + j + 1)‖) +
              ‖x (n + k) - x (n + k + 1)‖ := by
                gcongr
        _ = ∑ j ∈ Finset.range (k + 1), ‖x (n + j) - x (n + j + 1)‖ := by
              simp [Finset.sum_range_succ]

/-- Helper for Theorem 30.7: shifting the active index over a full block of length `m` permutes
the coordinates of `Fin m`. -/
private theorem dykstraActiveIndex_add_injective_on_block
    (hm : 0 < m) (n : ℕ) :
    Function.Injective (fun r : Fin m ↦ dykstraActiveIndex (m := m) hm (n + r)) := by
  intro r s hrs
  apply Fin.ext
  have hmod : n + (r : ℕ) ≡ n + (s : ℕ) [MOD m] := by
    simpa [Nat.ModEq, dykstraActiveIndex] using congrArg Fin.val hrs
  -- Equal residues inside the same length-`m` block force equal offsets.
  exact Nat.ModEq.eq_of_lt_of_lt (Nat.ModEq.add_left_cancel' n hmod) r.2 s.2

/-- Helper for Theorem 30.7: every coordinate is hit exactly once in each block of length `m`. -/
private theorem dykstraActiveIndex_exists_unique_on_block
    (hm : 0 < m) (n : ℕ) (i : Fin m) :
    ∃! r : ℕ, r < m ∧ dykstraActiveIndex (m := m) hm (n + r) = i := by
  let f : Fin m → Fin m := fun r ↦ dykstraActiveIndex (m := m) hm (n + r)
  have hinj : Function.Injective f :=
    dykstraActiveIndex_add_injective_on_block (m := m) (hm := hm) n
  have hsurj : Function.Surjective f := Finite.surjective_of_injective hinj
  obtain ⟨r, hr⟩ := hsurj i
  refine ⟨(r : ℕ), ⟨r.2, ?_⟩, ?_⟩
  · simpa [f] using hr
  · intro s hs
    rcases hs with ⟨hslt, hsidx⟩
    have hsfin : (⟨s, hslt⟩ : Fin m) = r := by
      apply hinj
      simpa [f] using hsidx.trans hr.symm
    exact congrArg Fin.val hsfin

/-- Helper for Theorem 30.7: once a coordinate has been updated for the last time before `N`, its
stored anchor stays frozen until time `N`. -/
private theorem dykstraAnchor_eq_of_lastActive
    (hm : 0 < m) (x0 : H) {s N : ℕ} {i : Fin m}
    (hsi : dykstraActiveIndex (m := m) hm s = i)
    (hSN : s < N)
    (hinactive : ∀ t, s < t → t < N → dykstraActiveIndex (m := m) hm t ≠ i) :
    anchorSeq hm x0 N i =
      dykstraProjectionSequence C hFamily_cheb hm x0 (s + 1) := by
  rcases Nat.exists_eq_add_of_lt hSN with ⟨len, rfl⟩
  -- First identify the anchor right after the last active update.
  have hstart :
      anchorSeq hm x0 (s + 1) i =
        dykstraProjectionSequence C hFamily_cheb hm x0 (s + 1) := by
    simpa [hsi] using
      dykstraCorrectionAnchorSequence_succ_active (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) (n := s)
  -- Then freeze the same coordinate through the finite inactive tail from `s + 1` to `N`.
  have hfreeze_tail :
      ∀ len,
        (∀ t, s < t → t < s + len + 1 → dykstraActiveIndex (m := m) hm t ≠ i) →
          anchorSeq hm x0 (s + len + 1) i =
            dykstraProjectionSequence C hFamily_cheb hm x0 (s + 1) := by
    intro len
    induction len with
    | zero =>
        intro _
        simpa [Nat.add_assoc] using hstart
    | succ len ih =>
        intro hinactive_tail
        have hneq :
            dykstraActiveIndex (m := m) hm (s + 1 + len) ≠ i := by
          exact hinactive_tail (s + 1 + len) (by omega) (by omega)
        have hneq' : i ≠ dykstraActiveIndex (m := m) hm (s + 1 + len) := by
          simpa [eq_comm] using hneq
        have hfreeze :
            anchorSeq hm x0 (s + (len + 1) + 1) i =
              anchorSeq hm x0 (s + 1 + len) i := by
          simpa [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
            dykstraCorrectionAnchorSequence_succ_inactive (C := C) (hC_nonempty := hC_nonempty)
              (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0)
              (n := s + 1 + len) (j := i) hneq'
        have hinactive_prev :
            ∀ t, s < t → t < s + len + 1 → dykstraActiveIndex (m := m) hm t ≠ i := by
          intro t hst ht
          exact hinactive_tail t hst (by omega)
        have hprev :
            anchorSeq hm x0 (s + 1 + len) i =
              dykstraProjectionSequence C hFamily_cheb hm x0 (s + 1) := by
          simpa [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using ih hinactive_prev
        exact hfreeze.trans hprev
  exact hfreeze_tail len hinactive

/-- Helper for Theorem 30.7: every block-end anchor belongs to the set indexed by its stored
coordinate. -/
private theorem dykstraAnchor_mem_set_atBlockEnd
    (hm : 0 < m) (x0 : H) (n : ℕ) (i : Fin m) :
    anchorSeq hm x0 (n + m) i ∈ C i := by
  obtain ⟨r, ⟨hr_lt, hr_idx⟩, huniq⟩ :=
    dykstraActiveIndex_exists_unique_on_block (m := m) (hm := hm) n i
  have hs_lt : n + r < n + m := by
    omega
  have hinactive :
      ∀ t, n + r < t → t < n + m → dykstraActiveIndex (m := m) hm t ≠ i := by
    intro t hrt htN hti
    have ht_ge_n : n ≤ t := by
      omega
    have ht_sub_lt : t - n < m := by
      omega
    have ht_eq : n + (t - n) = t := by
      omega
    have hr_eq :
        t - n = r := by
      apply huniq
      refine ⟨ht_sub_lt, ?_⟩
      simpa [ht_eq] using hti
    omega
  have hanchor :
      anchorSeq hm x0 (n + m) i =
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + r + 1) := by
    exact
      dykstraAnchor_eq_of_lastActive (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0)
        (s := n + r) (N := n + m) (i := i) hr_idx hs_lt hinactive
  have hmem :
      dykstraProjectionSequence C hFamily_cheb hm x0 (n + r + 1) ∈ C i := by
    simpa [hr_idx] using
      dykstraProjectionSequence_succ_mem_activeSet (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0)
        (n := n + r)
  -- Replace the stored anchor by the iterate that last updated it.
  simpa [hanchor] using hmem

/-- Helper for Theorem 30.7: every stored anchor at time `n + m` lies within the last `m` primal
steps of the current iterate. -/
private theorem dykstraAnchor_windowNorm_le_recentSteps
    (hm : 0 < m) (x0 : H) (n : ℕ) (i : Fin m) :
    ‖anchorSeq hm x0 (n + m) i -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + m)‖ ≤
      ∑ j ∈ Finset.range m,
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
          dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖ := by
  obtain ⟨r, ⟨hr_lt, hr_idx⟩, huniq⟩ :=
    dykstraActiveIndex_exists_unique_on_block (m := m) (hm := hm) n i
  have hs_lt : n + r < n + m := by
    omega
  have hinactive :
      ∀ t, n + r < t → t < n + m → dykstraActiveIndex (m := m) hm t ≠ i := by
    intro t hrt htN hti
    have ht_ge_n : n ≤ t := by
      omega
    have ht_sub_lt : t - n < m := by
      omega
    have ht_eq : n + (t - n) = t := by
      omega
    have hr_eq :
        t - n = r := by
      apply huniq
      refine ⟨ht_sub_lt, ?_⟩
      simpa [ht_eq] using hti
    omega
  have hanchor :
      anchorSeq hm x0 (n + m) i =
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + r + 1) := by
    exact
      dykstraAnchor_eq_of_lastActive (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0)
        (s := n + r) (N := n + m) (i := i) hr_idx hs_lt hinactive
  let x : ℕ → H := dykstraProjectionSequence C hFamily_cheb hm x0
  let recent : ℕ → ℝ :=
    fun j ↦ ‖x (n + j) - x (n + j + 1)‖
  have hr_succ_le : r + 1 ≤ m := Nat.succ_le_of_lt hr_lt
  have hdist_tail :
      ‖x (n + r + 1) - x (n + m)‖ ≤
        ∑ j ∈ Finset.range (m - (r + 1)), recent (r + 1 + j) := by
    have hdist :=
      norm_sub_le_sum_stepNorms (x := x) (n := n + r + 1) (k := m - (r + 1))
    simpa [x, recent, Nat.add_assoc, Nat.add_sub_of_le hr_succ_le] using hdist
  have hsplit :
      (∑ j ∈ Finset.range m, recent j) =
        (∑ j ∈ Finset.range (r + 1), recent j) +
          ∑ j ∈ Finset.range (m - (r + 1)), recent (r + 1 + j) := by
    simpa [Nat.add_sub_of_le hr_succ_le, recent] using
      Finset.sum_range_add (f := recent) (r + 1) (m - (r + 1))
  have hprefix_nonneg : 0 ≤ ∑ j ∈ Finset.range (r + 1), recent j := by
    refine Finset.sum_nonneg ?_
    intro j hj
    exact norm_nonneg _
  have htail_le :
      (∑ j ∈ Finset.range (m - (r + 1)), recent (r + 1 + j)) ≤
        ∑ j ∈ Finset.range m, recent j := by
    linarith
  -- Transport the anchor to its last active iterate and compare the resulting tail with the
  -- full recent step window.
  calc
    ‖anchorSeq hm x0 (n + m) i -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + m)‖
        = ‖x (n + r + 1) - x (n + m)‖ := by
            simp [x, hanchor]
    _ ≤ ∑ j ∈ Finset.range (m - (r + 1)), recent (r + 1 + j) := hdist_tail
    _ ≤ ∑ j ∈ Finset.range m, recent j := htail_le
    _ = ∑ j ∈ Finset.range m,
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖ := by
          rfl

/-- Helper for Theorem 30.7: the scalar boundary tail at time `n + m` is bounded by the product of
the recent window of primal steps and the full prefix sum of step norms. -/
private theorem dykstraBoundaryTail_le_recentSteps_mul_prefixSteps
    (hm : 0 < m) (x0 : H) (n : ℕ) :
    boundaryTail hm x0 (n + m) ≤
      (∑ j ∈ Finset.range m,
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖) *
        (∑ k ∈ Finset.range (n + m),
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
            dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖) := by
  set recent :=
    ∑ j ∈ Finset.range m,
      ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖
    with hrecent_def
  set prefixSteps :=
    ∑ k ∈ Finset.range (n + m),
      ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
        dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖
    with hprefixSteps_def
  have hrecent_nonneg : 0 ≤ recent := by
    refine Finset.sum_nonneg ?_
    intro j hj
    exact norm_nonneg _
  have hterm :
      ∀ i ∈ Finset.univ,
        |inner ℝ
          (anchorSeq hm x0 (n + m) i -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + m))
          (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i)| ≤
          recent * ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖ := by
    intro i hi
    calc
      |inner ℝ
          (anchorSeq hm x0 (n + m) i -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + m))
          (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i)|
          ≤ ‖anchorSeq hm x0 (n + m) i -
              dykstraProjectionSequence C hFamily_cheb hm x0 (n + m)‖ *
              ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖ := by
                exact abs_real_inner_le_norm _ _
      _ ≤ recent * ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖ := by
            gcongr
            exact
              dykstraAnchor_windowNorm_le_recentSteps (C := C) (hC_nonempty := hC_nonempty)
                (hC_closed := hC_closed) (hC_convex := hC_convex)
                (hm := hm) (x0 := x0) (n := n) (i := i)
  have hcorr :
      (∑ i, ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖) ≤ prefixSteps := by
    rw [hprefixSteps_def]
    simpa using
      dykstraCorrectionNormSum_le_prefixSteps (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) (n := n + m)
  -- Estimate each boundary-tail term by Cauchy-Schwarz, then factor out the uniform window bound.
  calc
    boundaryTail hm x0 (n + m)
        = ∑ i,
            |inner ℝ
              (anchorSeq hm x0 (n + m) i -
                dykstraProjectionSequence C hFamily_cheb hm x0 (n + m))
              (dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i)| := by
              simp [dykstraBoundaryTail]
    _ ≤ ∑ i, recent * ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖ := by
          refine Finset.sum_le_sum ?_
          intro i hi
          exact hterm i hi
    _ = recent * ∑ i, ‖dykstraCorrectionSequence C hFamily_cheb hm x0 (n + m) i‖ := by
          rw [Finset.mul_sum]
    _ ≤ recent * prefixSteps := by
          exact mul_le_mul_of_nonneg_left hcorr hrecent_nonneg
    _ = (∑ j ∈ Finset.range m,
            ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
              dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖) *
          (∑ k ∈ Finset.range (n + m),
            ‖dykstraProjectionSequence C hFamily_cheb hm x0 k -
              dykstraProjectionSequence C hFamily_cheb hm x0 (k + 1)‖) := by
          rw [hrecent_def, hprefixSteps_def]

/-- Helper for Theorem 30.7: the squared primal step norms form a summable series because the
augmented energy at `P[InterC, hInter_cheb] x0` drops by at least one squared step at each
iteration. -/
private theorem dykstraStepSqSummable
    (hm : 0 < m) (x0 : H) :
    Summable
      (fun n ↦
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
            dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖ ^ 2) := by
  let p : H := P[InterC, hInter_cheb] x0
  have hp : p ∈ InterC := by
    change P[InterC, hInter_cheb] x0 ∈ InterC
    exact projectionPoint_mem InterC hInter_cheb x0
  let stepSq : ℕ → ℝ := fun n ↦
    ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖ ^ 2
  have hstepSq_nonneg : ∀ n, 0 ≤ stepSq n := by
    intro n
    positivity
  have haug_nonneg : ∀ n, 0 ≤ augEnergy hm x0 n p := by
    intro n
    have hpair_nonneg :=
      dykstraAnchorPairing_nonneg (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) hp n
    have hsq_nonneg :
        0 ≤
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 := by
      positivity
    -- The augmented energy is the sum of the squared distance and twice the nonnegative anchor
    -- pairing at the projection point.
    change 0 ≤
      ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 +
        2 * anchorPairing hm x0 n p
    nlinarith
  have hstep_le :
      ∀ n, stepSq n ≤ augEnergy hm x0 n p - augEnergy hm x0 (n + 1) p := by
    intro n
    let i : Fin m := dykstraActiveIndex (m := m) hm n
    have hstep :
        augEnergy hm x0 n p =
          augEnergy hm x0 (n + 1) p +
            stepSq n +
            2 *
              inner ℝ
                (anchorSeq hm x0 n i -
                  dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
                (dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
      simpa [stepSq, i] using
        dykstraAugmentedEnergyStep (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) (n := n) (z := p)
    have hmem :
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1) ∈ C i := by
      simpa [i] using
        dykstraProjectionSequence_succ_mem_activeSet (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) (n := n)
    have hanchor_nonneg :
        0 ≤
          inner ℝ
            (anchorSeq hm x0 n i -
              dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
            (dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
      -- Reuse the stored-anchor variational inequality at the active next iterate.
      exact
        dykstraStoredCorrectionAnchor_nonneg (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) n i hmem
    have hanchor_twice_nonneg :
        0 ≤
          2 *
            inner ℝ
              (anchorSeq hm x0 n i -
                dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1))
              (dykstraCorrectionSequence C hFamily_cheb hm x0 n i) := by
      nlinarith
    -- Drop the nonnegative remainder term from the exact one-step energy identity.
    linarith
  have hpartial_aux :
      ∀ N,
        (∑ k ∈ Finset.range N, stepSq k) + augEnergy hm x0 N p ≤ augEnergy hm x0 0 p
      := by
        intro N
        induction N with
        | zero =>
            simp
        | succ N ih =>
            rw [Finset.sum_range_succ]
            have hdrop := hstep_le N
            linarith
  have hpartial :
      ∀ N, ∑ k ∈ Finset.range N, stepSq k ≤ augEnergy hm x0 0 p := by
    intro N
    have haux := hpartial_aux N
    have hnonneg := haug_nonneg N
    linarith
  -- The partial sums are uniformly bounded above, so the nonnegative series is summable.
  exact summable_of_sum_range_le hstepSq_nonneg hpartial

/-- Helper for Theorem 30.7: an `EReal`-valued liminf identity at `0` yields a strict monotone
real subsequence converging to `0`. -/
private theorem tendstoZero_subseq_ofERealLiminfEqZero
    {u : ℕ → ℝ}
    (hliminf : Filter.liminf (fun n ↦ ((u n : ℝ) : EReal)) atTop = 0) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ Tendsto (u ∘ φ) atTop (𝓝 (0 : ℝ)) := by
  -- Route correction: use the Chapter 1 `EReal` subsequence extractor directly and only descend
  -- back to `ℝ` at the finite limit point `0`.
  obtain ⟨φ, hφ, hφ_tendsto⟩ :=
    Net.exists_subsequence_tendsto_liminf (fun n ↦ ((u n : ℝ) : EReal))
  have hφ_ereal :
      Tendsto (fun n ↦ (((u (φ n) : ℝ) : EReal))) atTop (𝓝 (0 : EReal)) := by
    simpa [Function.comp, hliminf] using hφ_tendsto
  have hφ_real :
      Tendsto (fun n ↦ EReal.toReal (((u (φ n) : ℝ) : EReal))) atTop (𝓝 (0 : ℝ)) := by
    simpa using
      (EReal.tendsto_toReal (a := (0 : EReal)) (by simp) (by simp)).comp hφ_ereal
  refine ⟨φ, hφ, ?_⟩
  simpa [Function.comp] using hφ_real

/-- Helper for Theorem 30.7: frequent attainment of the thresholds `1 / (k + 1)` yields a strict
monotone subsequence meeting every threshold. -/
private theorem strictMono_subseq_small_of_frequently_small
    {u : ℕ → ℝ}
    (hsmall : ∀ k, ∃ᶠ n in atTop, k ≤ n ∧ u n < 1 / (k + 1 : ℝ)) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∀ k, u (φ k) < 1 / (k + 1 : ℝ) := by
  -- Extract one index for each threshold while keeping the resulting sequence strictly monotone.
  rcases Filter.extraction_forall_of_frequently hsmall with ⟨φ, hφ, hφsmall⟩
  refine ⟨φ, hφ, ?_⟩
  intro k
  exact (hφsmall k).2

/-- Helper for Theorem 30.7: there is a strict monotone subsequence along which the scalar
boundary tail at block ends tends to `0`. -/
private theorem dykstraBoundaryTail_zeroSubsequence_exists
    (hm : 0 < m) (x0 : H) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧
      Tendsto (fun n ↦ boundaryTail hm x0 (φ n + m)) atTop (𝓝 (0 : ℝ)) := by
  let step : ℕ → ℝ := fun n ↦
    ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖
  let prod : ℕ → ℝ := fun n ↦
    (∑ j ∈ Finset.range m, step (n + j)) * ∑ k ∈ Finset.range (n + m), step k
  let τ : ℕ → ℝ
    | 0 => 0
    | n + 1 => step n
  have hstep_nonneg : ∀ n, 0 ≤ step n := by
    intro n
    exact norm_nonneg _
  have hstep_sq_summable : Summable (fun n ↦ (step n) ^ 2) := by
    simpa [step] using
      dykstraStepSqSummable (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0)
  have hτ_nonneg : ∀ n, 0 ≤ τ n := by
    intro n
    cases n with
    | zero =>
        simp [τ]
    | succ n =>
        simpa [τ] using hstep_nonneg n
  have hτ_sq_summable : Summable (fun n ↦ (τ n) ^ 2) := by
    have hshift :
        Summable (fun n ↦ (τ (n + 1)) ^ 2) := by
      simpa [τ] using hstep_sq_summable
    exact (summable_nat_add_iff (f := fun n ↦ (τ n) ^ 2) 1).1 hshift
  have hτ_partial :
      ∀ N, (∑ k ∈ Finset.range (N + 1), τ k) = ∑ k ∈ Finset.range N, step k := by
    intro N
    induction N with
    | zero =>
        simp [τ]
    | succ N ih =>
        calc
          ∑ k ∈ Finset.range (N + 1 + 1), τ k
              = (∑ k ∈ Finset.range (N + 1), τ k) + τ (N + 1) := by
                  rw [Finset.sum_range_succ]
          _ = (∑ k ∈ Finset.range N, step k) + step N := by
                simpa [τ] using congrArg (fun t ↦ t + τ (N + 1)) ih
          _ = ∑ k ∈ Finset.range (N + 1), step k := by
                rw [Finset.sum_range_succ]
  have hprod_formula :
      (fun n ↦
        (∑ k < n + (m - 1) + 2, τ k) *
          ((∑ k < n + (m - 1) + 2, τ k) - ∑ k < n + 1, τ k)) = prod := by
    funext n
    have hm_eq : n + (m - 1) + 2 = n + m + 1 := by
      omega
    have hsumLeft :
        (∑ k < n + (m - 1) + 2, τ k) =
          ∑ k ∈ Finset.range (n + m), step k := by
      simpa [Nat.Iio_eq_range, hm_eq] using hτ_partial (n + m)
    have hsumRight :
        (∑ k < n + 1, τ k) =
          ∑ k ∈ Finset.range n, step k := by
      simpa [Nat.Iio_eq_range] using hτ_partial n
    have hsplit :
        (∑ k ∈ Finset.range (n + m), step k) =
          (∑ k ∈ Finset.range n, step k) +
            ∑ j ∈ Finset.range m, step (n + j) := by
      simpa [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
        (Finset.sum_range_add (f := step) n m)
    have hdiff :
        (∑ k ∈ Finset.range (n + m), step k) -
            ∑ k ∈ Finset.range n, step k =
          ∑ j ∈ Finset.range m, step (n + j) := by
      rw [hsplit]
      ring
    -- Rewrite the textbook liminf owner into the block-end boundary-tail majorant.
    rw [hsumLeft, hsumRight, hdiff]
    simp [prod, mul_comm]
  have hprod_nonneg : ∀ n, 0 ≤ prod n := by
    intro n
    dsimp [prod]
    refine mul_nonneg ?_ ?_
    · refine Finset.sum_nonneg ?_
      intro k hk
      exact hstep_nonneg (n + k)
    · refine Finset.sum_nonneg ?_
      intro j hj
      exact hstep_nonneg j
  have hprod_frequently_small :
      ∀ k, ∃ᶠ n in atTop, k ≤ n ∧ prod n < 1 / (k + 1 : ℝ) := by
    intro k
    have hk_pos : 0 < 1 / (k + 1 : ℝ) := by
      positivity
    have hprod_frequently_lt :
        ∃ᶠ n in atTop, prod n < 1 / (k + 1 : ℝ) := by
      -- Rewrite the local block-end product once into the public Lemma 30.6 owner.
      refine
        (partialSumsMulSubPartialSums_frequently_lt_of_pos
          τ hτ_nonneg hτ_sq_summable (m - 1) hk_pos).mono ?_
      intro n hn
      have hprod_formula_n :
          (∑ k < n + (m - 1) + 2, τ k) *
              ((∑ k < n + (m - 1) + 2, τ k) - ∑ k < n + 1, τ k) =
            prod n := by
        simpa using congrFun hprod_formula n
      rwa [hprod_formula_n] at hn
    have hk_eventually : ∀ᶠ n in atTop, k ≤ n := by
      exact Filter.eventually_atTop.2 ⟨k, fun n hn ↦ hn⟩
    -- Intersect the threshold-small event with the eventual lower bound on the indices.
    refine (hprod_frequently_lt.and_eventually hk_eventually).mono ?_
    intro n hn
    exact ⟨hn.2, hn.1⟩
  obtain ⟨φ, hφ, hφsmall⟩ :=
    strictMono_subseq_small_of_frequently_small hprod_frequently_small
  have hprod_tendsto :
      Tendsto (fun n ↦ prod (φ n)) atTop (𝓝 (0 : ℝ)) := by
    have hrecip_tendsto :
        Tendsto (fun n : ℕ ↦ 1 / (n + 1 : ℝ)) atTop (𝓝 (0 : ℝ)) := by
      simpa using
        (tendsto_one_div_add_atTop_nhds_zero_nat :
          Tendsto (fun n : ℕ ↦ 1 / (n + 1 : ℝ)) atTop (𝓝 (0 : ℝ)))
    -- Squeeze the subsequence between `0` and the reciprocal threshold schedule.
    exact squeeze_zero
      (fun n ↦ hprod_nonneg (φ n))
      (fun n ↦ le_of_lt (hφsmall n))
      hrecip_tendsto
  have hboundary_tendsto :
      Tendsto (fun n ↦ boundaryTail hm x0 (φ n + m)) atTop (𝓝 (0 : ℝ)) := by
    -- Squeeze the boundary tail between `0` and the product majorant along the extracted
    -- subsequence.
    exact squeeze_zero
      (fun n ↦
        dykstraBoundaryTail_nonneg (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) (φ n + m))
      (fun n ↦ by
        simpa [prod, step] using
          dykstraBoundaryTail_le_recentSteps_mul_prefixSteps (C := C)
            (hC_nonempty := hC_nonempty) (hC_closed := hC_closed) (hC_convex := hC_convex)
            (hm := hm) (x0 := x0) (n := φ n))
      hprod_tendsto
  exact ⟨φ, hφ, hboundary_tendsto⟩

/-- Helper for Theorem 30.7: the fixed `m`-window sum of successive Dykstra step norms tends to
`0`. -/
private theorem dykstraRecentStepSum_tendsto_zero
    (hm : 0 < m) (x0 : H) :
    Tendsto
      (fun n ↦
        ∑ j ∈ Finset.range m,
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
              dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖)
      atTop (𝓝 (0 : ℝ)) := by
  let step : ℕ → ℝ := fun n ↦
    ‖dykstraProjectionSequence C hFamily_cheb hm x0 n -
        dykstraProjectionSequence C hFamily_cheb hm x0 (n + 1)‖
  have hstep_sq_summable : Summable (fun n ↦ (step n) ^ 2) := by
    -- Reuse the energy owner that makes the squared step norms summable.
    simpa [step] using
      dykstraStepSqSummable (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0)
  have hstep_tendsto_zero : Tendsto step atTop (𝓝 (0 : ℝ)) := by
    have hsqrt_tendsto :
        Tendsto (fun n ↦ Real.sqrt ((step n) ^ 2)) atTop (𝓝 (Real.sqrt 0)) := by
      exact Real.continuous_sqrt.continuousAt.tendsto.comp hstep_sq_summable.tendsto_atTop_zero
    -- Taking square roots converts the summable squared-step decay back to norm decay.
    simpa [step, Real.sqrt_zero, Real.sqrt_sq_eq_abs] using hsqrt_tendsto
  have hwindow_tendsto_zero :
      ∀ r : ℕ,
        Tendsto (fun n ↦ ∑ j ∈ Finset.range r, step (n + j)) atTop (𝓝 (0 : ℝ)) := by
    intro r
    induction r with
    | zero =>
        -- The empty window contributes nothing.
        simp
    | succ r ihr =>
        -- Extend the window by one shifted step term and combine the two limits.
        simpa [Finset.sum_range_succ, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
          ihr.add (hstep_tendsto_zero.comp (Filter.tendsto_add_atTop_nat r))
  simpa [step] using hwindow_tendsto_zero m

/-- Helper for Theorem 30.7: the Dykstra primal orbit stays in a fixed norm ball around the
projection point `P[InterC, hInter_cheb] x0`. -/
private theorem dykstraProjectionSequence_bounded
    (hm : 0 < m) (x0 : H) :
    Bornology.IsBounded (Set.range (dykstraProjectionSequence C hFamily_cheb hm x0)) := by
  let p : H := P[InterC, hInter_cheb] x0
  have hp : p ∈ InterC := by
    change P[InterC, hInter_cheb] x0 ∈ InterC
    exact projectionPoint_mem InterC hInter_cheb x0
  have hdist_le :
      ∀ n,
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ≤ ‖x0 - p‖ := by
    intro n
    have henergy_le :
        augEnergy hm x0 n p ≤ augEnergy hm x0 0 p := by
      induction n with
      | zero =>
          simp
      | succ n ihn =>
          exact le_trans
            (dykstraAugmentedEnergyStep_nonincreasing (C := C) (hC_nonempty := hC_nonempty)
              (hC_closed := hC_closed) (hC_convex := hC_convex)
              (hm := hm) (x0 := x0) (z := p) (n := n))
            ihn
    have hdist_sq :
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 ≤ ‖x0 - p‖ ^ 2 := by
      have hpair_nonneg :=
        dykstraAnchorPairing_nonneg (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) hp n
      calc
        ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2
            ≤ augEnergy hm x0 n p := by
                -- Drop the nonnegative anchor pairing part of the augmented energy.
                simp only [dykstraAugmentedEnergy]
                nlinarith
        _ ≤ augEnergy hm x0 0 p := henergy_le
        _ = ‖x0 - p‖ ^ 2 := by
              -- At time `0` the correction family vanishes, so the augmented energy is just the
              -- squared initial distance to the projection point.
              simp [dykstraAugmentedEnergy, dykstraAnchorPairing,
                dykstraCorrectionSequence, dykstraProjectionSequence,
                dykstraCorrectionAnchorSequence]
    exact (sq_le_sq₀ (norm_nonneg _) (norm_nonneg _)).1 hdist_sq
  rw [isBounded_iff_forall_norm_le]
  refine ⟨‖x0 - p‖ + ‖p‖, ?_⟩
  intro z hz
  rcases hz with ⟨n, rfl⟩
  have hdist := hdist_le n
  -- Convert the uniform bound around `p` into a uniform bound around the origin.
  calc
    ‖dykstraProjectionSequence C hFamily_cheb hm x0 n‖
        = ‖(dykstraProjectionSequence C hFamily_cheb hm x0 n - p) + p‖ := by
            congr 1
            abel_nf
    _ ≤ ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ + ‖p‖ := norm_add_le _ _
    _ ≤ ‖x0 - p‖ + ‖p‖ := by
          linarith

/-- Helper for Theorem 30.7: every weak limit of a block-end subsequence belongs to
`⋂ i, C i`. -/
private theorem dykstraBlockEndWeakLimit_mem_iInter
    (hm : 0 < m) (x0 : H) {χ : ℕ → ℕ} (hχ : StrictMono χ) {y : H}
    (hy :
      Tendsto
        (fun n ↦ toWeakSpace ℝ H
          (dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m)))
        atTop
        (𝓝 (toWeakSpace ℝ H y))) :
    y ∈ InterC := by
  refine Set.mem_iInter.2 ?_
  intro i
  let xχ : ℕ → H := fun n ↦ dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m)
  let aχ : ℕ → H := fun n ↦ anchorSeq hm x0 (χ n + m) i
  have ha_mem : ∀ n, aχ n ∈ C i := by
    intro n
    simpa [aχ] using
      dykstraAnchor_mem_set_atBlockEnd (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) (n := χ n) (i := i)
  have hrecent_tendsto_zero :
      Tendsto
        (fun n ↦
          ∑ j ∈ Finset.range m,
            ‖dykstraProjectionSequence C hFamily_cheb hm x0 (n + j) -
                dykstraProjectionSequence C hFamily_cheb hm x0 (n + j + 1)‖)
        atTop
        (𝓝 (0 : ℝ)) := by
    exact
      dykstraRecentStepSum_tendsto_zero (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0)
  have hdiff_norm :
      Tendsto (fun n ↦ ‖aχ n - xχ n‖) atTop (𝓝 (0 : ℝ)) := by
    refine squeeze_zero
      (f := fun n ↦ ‖aχ n - xχ n‖)
      (g := fun n ↦
        ∑ j ∈ Finset.range m,
          ‖dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + j) -
              dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + j + 1)‖)
      (fun _ ↦ norm_nonneg _)
      ?_
      ?_
    · intro n
      simpa [aχ, xχ] using
        dykstraAnchor_windowNorm_le_recentSteps (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) (n := χ n) (i := i)
    · simpa [xχ] using hrecent_tendsto_zero.comp hχ.tendsto_atTop
  have hdiff :
      Tendsto (fun n ↦ aχ n - xχ n) atTop (𝓝 (0 : H)) := by
    rw [tendsto_iff_norm_sub_tendsto_zero]
    simpa [aχ, xχ]
      using hdiff_norm
  have hdiff_weak :
      Tendsto (fun n ↦ toWeakSpace ℝ H (aχ n - xχ n)) atTop (𝓝 (0 : WeakSpace ℝ H)) := by
    simpa [toWeakSpaceCLM_eq_toWeakSpace] using
      ((toWeakSpaceCLM ℝ H).continuous.tendsto (0 : H)).comp hdiff
  have ha_weak :
      Tendsto (fun n ↦ toWeakSpace ℝ H (aχ n)) atTop (𝓝 (toWeakSpace ℝ H y)) := by
    -- The anchor subsequence shares the same weak limit because its strong difference from the
    -- block-end primal subsequence vanishes.
    have hsum :
        Tendsto
          (fun n ↦
            toWeakSpace ℝ H (aχ n - xχ n) +
              toWeakSpace ℝ H (xχ n))
          atTop
          (𝓝 (0 + toWeakSpace ℝ H y : WeakSpace ℝ H)) :=
      hdiff_weak.add hy
    simpa [aχ, xχ, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using hsum
  exact mem_of_tendsto_weakly_of_isClosed_convex (hC_closed i) (hC_convex i) ha_mem ha_weak

/-- Helper for Theorem 30.7: some block-end subsequence converges strongly to the projection
point, and along the same subsequence the boundary tail tends to `0`. -/
private theorem dykstraBlockEndStrongSubsequence_exists
    (hm : 0 < m) (x0 : H) :
    ∃ χ : ℕ → ℕ, StrictMono χ ∧
      Tendsto
        (fun n ↦ dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m))
        atTop
        (𝓝 (P[InterC, hInter_cheb] x0)) ∧
      Tendsto (fun n ↦ boundaryTail hm x0 (χ n + m)) atTop (𝓝 (0 : ℝ)) := by
  obtain ⟨φ, hφ, hφtail⟩ :=
    dykstraBoundaryTail_zeroSubsequence_exists (C := C) (hC_nonempty := hC_nonempty)
      (hC_closed := hC_closed) (hC_convex := hC_convex)
      (hm := hm) (x0 := x0)
  let xφ : ℕ → H := fun n ↦ dykstraProjectionSequence C hFamily_cheb hm x0 (φ n + m)
  have hxφ_bounded : Bornology.IsBounded (Set.range xφ) := by
    exact
      (dykstraProjectionSequence_bounded (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0)).subset <| by
          rintro _ ⟨n, rfl⟩
          exact ⟨φ n + m, rfl⟩
  obtain ⟨y, ψ, hψ, hψweak⟩ :=
    bounded_sequence_has_weakly_convergent_subsequence xφ hxφ_bounded
  let χ : ℕ → ℕ := φ ∘ ψ
  have hχ : StrictMono χ := hφ.comp hψ
  have hχweak :
      Tendsto
        (fun n ↦ toWeakSpace ℝ H
          (dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m)))
        atTop
        (𝓝 (toWeakSpace ℝ H y)) := by
    simpa [χ, xφ, Function.comp, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using hψweak
  have hχtail :
      Tendsto (fun n ↦ boundaryTail hm x0 (χ n + m)) atTop (𝓝 (0 : ℝ)) := by
    simpa [χ, Function.comp, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
      hφtail.comp hψ.tendsto_atTop
  have hy_mem :
      y ∈ InterC := by
    exact
      dykstraBlockEndWeakLimit_mem_iInter (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) hχ hχweak
  let xχ : ℕ → H := fun n ↦ dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m)
  have hsub_weak_zero :
      Tendsto (fun n ↦ toWeakSpace ℝ H (y - xχ n)) atTop (𝓝 (0 : WeakSpace ℝ H)) := by
    have hconst :
        Tendsto (fun _ : ℕ ↦ toWeakSpace ℝ H y) atTop (𝓝 (toWeakSpace ℝ H y)) :=
      tendsto_const_nhds
    simpa [xχ, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using hconst.sub hχweak
  have hinner_zero :
      Tendsto (fun n ↦ inner ℝ (y - xχ n) (x0 - y)) atTop (𝓝 (0 : ℝ)) := by
    simpa [xχ] using
      ((weakSpace_continuous_inner_right (H := H) (x0 - y)).tendsto (toWeakSpace ℝ H (0 : H))).comp
        hsub_weak_zero
  have hsq_le :
      ∀ n,
        ‖y - xχ n‖ ^ 2 ≤
          boundaryTail hm x0 (χ n + m) -
            inner ℝ (y - xχ n) (x0 - y) := by
    intro n
    have hgap :=
      dykstraBoundaryTail_innerGap_le (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) hy_mem (χ n + m)
    have hsplit :
        inner ℝ (y - xχ n) (x0 - xχ n) =
          inner ℝ (y - xχ n) (x0 - y) + ‖y - xχ n‖ ^ 2 := by
      calc
        inner ℝ (y - xχ n) (x0 - xχ n)
            = inner ℝ (y - xχ n) ((x0 - y) + (y - xχ n)) := by
                congr 2
                abel_nf
        _ = inner ℝ (y - xχ n) (x0 - y) +
              inner ℝ (y - xχ n) (y - xχ n) := by
                rw [inner_add_right]
        _ = inner ℝ (y - xχ n) (x0 - y) + ‖y - xχ n‖ ^ 2 := by
              rw [real_inner_self_eq_norm_sq]
    have hgap' :
        inner ℝ (y - xχ n) (x0 - y) + ‖y - xχ n‖ ^ 2 ≤ boundaryTail hm x0 (χ n + m) := by
      simpa [xχ, hsplit] using hgap
    linarith
  have hsq_zero :
      Tendsto (fun n ↦ ‖y - xχ n‖ ^ 2) atTop (𝓝 (0 : ℝ)) := by
    refine squeeze_zero (fun _ ↦ sq_nonneg _) hsq_le ?_
    simpa using hχtail.sub hinner_zero
  have hnorm_zero :
      Tendsto (fun n ↦ ‖y - xχ n‖) atTop (𝓝 (0 : ℝ)) := by
    have hsqrt_zero :
        Tendsto (fun n ↦ Real.sqrt (‖y - xχ n‖ ^ 2)) atTop (𝓝 (Real.sqrt 0)) := by
      exact Real.continuous_sqrt.continuousAt.tendsto.comp hsq_zero
    simpa [Real.sqrt_zero, Real.sqrt_sq_eq_abs, abs_of_nonneg, xχ]
      using hsqrt_zero
  have hstrong_y :
      Tendsto xχ atTop (𝓝 y) := by
    rw [tendsto_iff_norm_sub_tendsto_zero]
    simpa [xχ, norm_sub_rev] using hnorm_zero
  have hy_inner_nonpos :
      ∀ z ∈ InterC, inner ℝ (z - y) (x0 - y) ≤ 0 := by
    intro z hz
    have ha_tendsto :
        Tendsto (fun n ↦ inner ℝ (z - xχ n) (x0 - xχ n)) atTop
          (𝓝 (inner ℝ (z - y) (x0 - y))) := by
      simpa [xχ] using
        ((((continuous_const.sub continuous_id).inner (continuous_const.sub continuous_id)).tendsto
          y).comp hstrong_y)
    have hineq :
        ∀ n, inner ℝ (z - xχ n) (x0 - xχ n) ≤ boundaryTail hm x0 (χ n + m) := by
      intro n
      simpa [xχ] using
        dykstraBoundaryTail_innerGap_le (C := C) (hC_nonempty := hC_nonempty)
          (hC_closed := hC_closed) (hC_convex := hC_convex)
          (hm := hm) (x0 := x0) hz (χ n + m)
    exact le_of_tendsto_of_tendsto' ha_tendsto hχtail hineq
  have hy_proj :
      y = P[InterC, hInter_cheb] x0 := by
    exact
      (eq_projectionPoint_iff_mem_and_inner_sub_right_nonpos_of_nonempty_isClosed_convex
        (C := InterC) (hC_nonempty := hC_nonempty)
        (hC_closed := isClosed_iInter hC_closed)
        (hC_convex := convex_iInter hC_convex)
        (x := x0) (p := y)).2 ⟨hy_mem, hy_inner_nonpos⟩
  refine ⟨χ, hχ, ?_, hχtail⟩
  simpa [xχ, hy_proj] using hstrong_y

/-- Helper for Theorem 30.7: the anchor pairing is controlled by the current block-end error and
the scalar boundary tail. -/
private theorem dykstraAnchorPairing_le_blockEndError_add_boundaryTail
    (hm : 0 < m) (x0 : H) {p : H} (n : ℕ) :
    anchorPairing hm x0 n p ≤
      ‖p - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ *
          ‖x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ +
        boundaryTail hm x0 n := by
  let xN := dykstraProjectionSequence C hFamily_cheb hm x0 n
  let qN := dykstraCorrectionSequence C hFamily_cheb hm x0 n
  let aN := anchorSeq hm x0 n
  have hgap :
      x0 - xN = ∑ i, qN i := by
    simpa [xN, qN] using
      dykstraInitialGap_eq_sumCorrections (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex) (hm := hm) (x0 := x0) n
  have hsplit :
      anchorPairing hm x0 n p =
        (∑ i, inner ℝ (aN i - xN) (qN i)) +
          inner ℝ (xN - p) (x0 - xN) := by
    calc
      anchorPairing hm x0 n p
          = ∑ i, inner ℝ (aN i - p) (qN i) := by
              simp [dykstraAnchorPairing, aN, qN]
      _ = ∑ i, (inner ℝ (aN i - xN) (qN i) + inner ℝ (xN - p) (qN i)) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            have hab : aN i - p = (aN i - xN) + (xN - p) := by
              abel_nf
            rw [hab, inner_add_left]
      _ = (∑ i, inner ℝ (aN i - xN) (qN i)) +
            ∑ i, inner ℝ (xN - p) (qN i) := by
              rw [Finset.sum_add_distrib]
      _ = (∑ i, inner ℝ (aN i - xN) (qN i)) +
            inner ℝ (xN - p) (∑ i, qN i) := by
              rw [← inner_sum]
      _ = (∑ i, inner ℝ (aN i - xN) (qN i)) +
            inner ℝ (xN - p) (x0 - xN) := by
              rw [hgap]
  have hsum_le :
      ∑ i, inner ℝ (aN i - xN) (qN i) ≤ boundaryTail hm x0 n := by
    calc
      ∑ i, inner ℝ (aN i - xN) (qN i)
          ≤ ∑ i, |inner ℝ (aN i - xN) (qN i)| := by
              refine Finset.sum_le_sum ?_
              intro i hi
              exact le_abs_self _
      _ = boundaryTail hm x0 n := by
            simp [dykstraBoundaryTail, aN, qN, xN]
  have hinner_le :
      inner ℝ (xN - p) (x0 - xN) ≤
        ‖p - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ *
          ‖x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ := by
    calc
      inner ℝ (xN - p) (x0 - xN)
          ≤ ‖xN - p‖ * ‖x0 - xN‖ := real_inner_le_norm _ _
      _ = ‖p - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ *
            ‖x0 - dykstraProjectionSequence C hFamily_cheb hm x0 n‖ := by
              simp [xN, norm_sub_rev]
  -- Split the anchor pairing into the tail contribution and the global error term.
  rw [hsplit]
  linarith

/-- Theorem 30.7: for a strictly positive integer `m`, a family `(C_i)_{i = 1}^m` of closed
convex subsets of a real Hilbert space with nonempty intersection, and `x₀ ∈ H`, the Dykstra
projection sequence associated with the cyclic family `C` converges strongly to the metric
projection of `x₀` onto `⋂ i, C i`. -/
theorem dykstraProjectionSequence_tendsto_projection_iInter (hm : 0 < m) (x0 : H) :
    Tendsto
      (dykstraProjectionSequence C hFamily_cheb hm x0)
      atTop
      (𝓝 (P[InterC, hInter_cheb] x0)) := by
  let p : H := P[InterC, hInter_cheb] x0
  have hp : p ∈ InterC := by
    change P[InterC, hInter_cheb] x0 ∈ InterC
    exact projectionPoint_mem InterC hInter_cheb x0
  obtain ⟨χ, hχ, hχstrong, hχtail⟩ :=
    dykstraBlockEndStrongSubsequence_exists (C := C) (hC_nonempty := hC_nonempty)
      (hC_closed := hC_closed) (hC_convex := hC_convex)
      (hm := hm) (x0 := x0)
  let energy : ℕ → ℝ := fun n ↦ augEnergy hm x0 n p
  let xχ : ℕ → H := fun n ↦ dykstraProjectionSequence C hFamily_cheb hm x0 (χ n + m)
  have hpair_nonneg : ∀ n, 0 ≤ anchorPairing hm x0 n p := by
    intro n
    exact
      dykstraAnchorPairing_nonneg (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) hp n
  have henergy_nonneg : ∀ n, 0 ≤ energy n := by
    intro n
    have hsq_nonneg :
        0 ≤ ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 := by
      positivity
    change 0 ≤
      ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 +
        2 * anchorPairing hm x0 n p
    nlinarith [hpair_nonneg n, hsq_nonneg]
  have henergy_step :
      ∀ n, energy (n + 1) ≤ energy n := by
    intro n
    simpa [energy] using
      dykstraAugmentedEnergyStep_nonincreasing (C := C) (hC_nonempty := hC_nonempty)
        (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) (z := p) (n := n)
  have hdistχ_zero :
      Tendsto (fun n ↦ ‖p - xχ n‖) atTop (𝓝 (0 : ℝ)) := by
    have hsub :
        Tendsto (fun n ↦ p - xχ n) atTop (𝓝 (0 : H)) := by
      have hconst : Tendsto (fun _ : ℕ ↦ p) atTop (𝓝 p) := tendsto_const_nhds
      simpa [p, xχ, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
        hconst.sub hχstrong
    simpa [xχ] using hsub.norm
  have hx0distχ :
      Tendsto (fun n ↦ ‖x0 - xχ n‖) atTop (𝓝 ‖x0 - p‖) := by
    have hsub :
        Tendsto (fun n ↦ x0 - xχ n) atTop (𝓝 (x0 - p)) := by
      have hconst : Tendsto (fun _ : ℕ ↦ x0) atTop (𝓝 x0) := tendsto_const_nhds
      simpa [xχ, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using hconst.sub hχstrong
    simpa [xχ] using hsub.norm
  have hpair_upper_zero :
      Tendsto
        (fun n ↦
          ‖p - xχ n‖ * ‖x0 - xχ n‖ +
            boundaryTail hm x0 (χ n + m))
        atTop
        (𝓝 (0 : ℝ)) := by
    have hprod_zero :
        Tendsto (fun n ↦ ‖p - xχ n‖ * ‖x0 - xχ n‖) atTop (𝓝 (0 : ℝ)) := by
      simpa [zero_mul] using hdistχ_zero.mul hx0distχ
    simpa using hprod_zero.add hχtail
  have hpair_subseq_zero :
      Tendsto (fun n ↦ anchorPairing hm x0 (χ n + m) p) atTop (𝓝 (0 : ℝ)) := by
    refine squeeze_zero (fun n ↦ hpair_nonneg (χ n + m)) ?_ hpair_upper_zero
    intro n
    simpa [xχ] using
      dykstraAnchorPairing_le_blockEndError_add_boundaryTail (C := C)
        (hC_nonempty := hC_nonempty) (hC_closed := hC_closed) (hC_convex := hC_convex)
        (hm := hm) (x0 := x0) (χ n + m)
  have hdistSq_subseq_zero :
      Tendsto (fun n ↦ ‖xχ n - p‖ ^ 2) atTop (𝓝 (0 : ℝ)) := by
    have hsub :
        Tendsto (fun n ↦ xχ n - p) atTop (𝓝 (0 : H)) := by
      simpa [p, xχ, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
        hχstrong.sub (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ p) atTop (𝓝 p))
    have hnorm_zero : Tendsto (fun n ↦ ‖xχ n - p‖) atTop (𝓝 (0 : ℝ)) := by
      simpa [xχ] using hsub.norm
    simpa [xχ] using hnorm_zero.pow 2
  have henergy_subseq_zero :
      Tendsto (fun n ↦ energy (χ n + m)) atTop (𝓝 (0 : ℝ)) := by
    -- Along the strong block-end subsequence, both the distance term and the anchor pairing term
    -- vanish, hence so does the augmented energy.
    simpa [energy, dykstraAugmentedEnergy, xχ] using
      hdistSq_subseq_zero.add (hpair_subseq_zero.const_mul 2)
  have henergy_zero :
      Tendsto energy atTop (𝓝 (0 : ℝ)) := by
    rw [Metric.tendsto_nhds]
    intro ε hε
    have hsub_event :
        ∀ᶠ n in atTop, dist (energy (χ n + m)) 0 < ε := by
      exact (Metric.tendsto_nhds.1 henergy_subseq_zero) ε hε
    rcases Filter.eventually_atTop.1 hsub_event with ⟨N, hN⟩
    refine Filter.eventually_atTop.2 ⟨χ N + m, ?_⟩
    intro n hn
    have hanti : Antitone energy := antitone_nat_of_succ_le henergy_step
    have hmono : energy n ≤ energy (χ N + m) := hanti hn
    have hsmall :
        energy (χ N + m) < ε := by
      have hdist_small := hN N le_rfl
      simpa [Real.dist_eq, abs_of_nonneg (henergy_nonneg (χ N + m))] using hdist_small
    have hsmall_n : energy n < ε := lt_of_le_of_lt hmono hsmall
    simpa [Real.dist_eq, abs_of_nonneg (henergy_nonneg n)] using hsmall_n
  have hdistSq_le :
      ∀ n, ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2 ≤ energy n := by
    intro n
    have hpair_nonneg_n := hpair_nonneg n
    simp [energy, dykstraAugmentedEnergy]
    nlinarith
  have hdistSq_zero :
      Tendsto
        (fun n ↦ ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2)
        atTop
        (𝓝 (0 : ℝ)) := by
    refine squeeze_zero (fun _ ↦ sq_nonneg _) hdistSq_le henergy_zero
  have hdist_zero :
      Tendsto
        (fun n ↦ ‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖)
        atTop
        (𝓝 (0 : ℝ)) := by
    have hsqrt_zero :
        Tendsto
          (fun n ↦
            Real.sqrt
              (‖dykstraProjectionSequence C hFamily_cheb hm x0 n - p‖ ^ 2))
          atTop
          (𝓝 (Real.sqrt 0)) := by
      exact Real.continuous_sqrt.continuousAt.tendsto.comp hdistSq_zero
    simpa [Real.sqrt_zero, Real.sqrt_sq_eq_abs, abs_of_nonneg]
      using hsqrt_zero
  -- The norm distance to the projection point tends to zero, which is exactly strong convergence.
  rw [tendsto_iff_norm_sub_tendsto_zero]
  simpa [p, norm_sub_rev] using hdist_zero

end

end
