import Mathlib
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Assumption_4_3_1 (from Chap04) -/
open scoped Gradient

noncomputable section

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/- Assumption 4.3.1 lies in the second-order oracle / affine-span lower-complexity domain.

Sampled owner-style declarations:
* `hessian f x` in `Chap01/Definition_1_4_16`, the chapter's canonical second-order owner;
* the second-order oracle reply in `Chap01/Definition_1_2_9`, whose genuine higher-order data are
  guarded by `HasGradientAt` and `HasFDerivAt (∇ f)`;
* `SatisfiesSpanCondition` in `Chap02/Definition_2_9`, which keeps the span restriction itself
  binder-first rather than as an implication out of a regularity hypothesis;
* `AffineSubspace.mk'` and `AffineSubspace.mem_mk'` in mathlib, the canonical affine-span owner
  and its vector-form bridge.

Layer triage:
* source-facing: the second-order oracle-direction set `secondOrderOracleDirections f x`, the
  affine search space `secondOrderOracleSpanSearchSpace f testPoints k`, and the sequence
  predicate `IsSecondOrderSpanSequence f testPoints`;
* core/canonical: the pointwise oracle-data owner `HasSecondOrderOracleAt f x`, the Hessian owner
  `hessian f x`, and the affine-span owner `AffineSubspace.mk' (testPoints 0) V`;
* bridge/view: the companion vector-form restatement from `AffineSubspace.mem_mk'`.

Primitive data:
* the objective `f`;
* the query point `x`;
* the iterate sequence `testPoints`.

Derived API:
* the pointwise predicate saying the displayed gradient and Hessian at `x` are genuine second-order
  oracle data for `f`;
* the oracle-direction set at `x`, defined as the textbook closure of the convex hull of the
  solution vectors `d` to `[α I + (1 - α) ∇²f(x)] d = ∇f(x)`;
* the oracle-along-sequence predicate `HasSecondOrderOracleSequence f testPoints`;
* the affine search space generated by the earlier oracle-direction sets;
* the affine-subspace and vector-form span conditions on an oracle sequence.

The refinement keeps the source-facing oracle-direction owner at the textbook level and moves the
genuine second-order-oracle requirement to the sequence layer, in the same spirit that Chapter 2
keeps smoothness as an explicit hypothesis of the span-condition owner. This removes the earlier
off-domain reading `𝒢[f; x] = ∅` while preserving the intended `C²` semantics of Assumption 4.3.1.
-/

/-- The displayed gradient and Hessian at `x` are genuine first- and second-order oracle data for
`f`. -/
abbrev HasSecondOrderOracleAt (f : E → ℝ) (x : E) : Prop :=
  HasGradientAt f (∇ f x) x ∧ HasFDerivAt (∇ f) (hessian f x) x

/-- The textbook second-order oracle directions at `x`: the closure of the convex hull of the
solutions to `[α I + (1 - α) ∇² f(x)] d = ∇ f(x)` for `α ∈ [0,1]`. -/
def secondOrderOracleDirections
    (f : E → ℝ) (x : E) : Set E :=
  closure (convexHull ℝ (⋃ α : Set.Icc (0 : ℝ) 1, {
    u | (((α : ℝ) • ContinuousLinearMap.id ℝ E + (1 - (α : ℝ)) • hessian f x) u = ∇ f x)
  }))

/- Source-facing Lean notation for the textbook second-order oracle-direction set `𝒢_f(x)`. -/
namespace SecondOrderOracleDirections

scoped notation:max "𝒢[" f ";" x "]" => secondOrderOracleDirections f x

end SecondOrderOracleDirections

open scoped SecondOrderOracleDirections

/-- Membership in `𝒢[f; x]` is the textbook closure-convex-hull resolvent condition. -/
@[simp] theorem mem_secondOrderOracleDirections
    (f : E → ℝ) (x d : E) :
    d ∈ 𝒢[f; x] ↔
      d ∈ closure (convexHull ℝ (⋃ α : Set.Icc (0 : ℝ) 1, {
        u | (((α : ℝ) • ContinuousLinearMap.id ℝ E + (1 - (α : ℝ)) • hessian f x) u = ∇ f x)
      })) :=
  Iff.rfl

/-- A sequence of test points has genuine second-order oracle data when each query point carries
the displayed gradient and Hessian of `f`. -/
abbrev HasSecondOrderOracleSequence
    (f : E → ℝ) (testPoints : ℕ → E) : Prop :=
  ∀ k : ℕ, HasSecondOrderOracleAt f (testPoints k)

/-- The affine search space generated from the initial point `testPoints 0` and the earlier
second-order oracle directions `𝒢[f; testPoints 0], …, 𝒢[f; testPoints (k - 1)]`. -/
def secondOrderOracleSpanSearchSpace
    (f : E → ℝ) (testPoints : ℕ → E) (k : ℕ) :
    AffineSubspace ℝ E :=
  AffineSubspace.mk' (testPoints 0)
    (Submodule.span ℝ (⋃ i : Fin k, 𝒢[f; testPoints i]))

/-- Assumption 4.3.1: a sequence of test points generated by an iterative second-order scheme
satisfies `x_k ∈ x₀ + Lin{𝒢_f(x₀), …, 𝒢_f(x_{k-1})}` for every `k ≥ 0`, where the case `k = 0`
is tautological and the usual textbook form is recovered by replacing `k` with `k + 1`. The set
`𝒢_f(x)` is the textbook second-order oracle-direction set at `x`, and the sequence is required
to query points where the displayed gradient and Hessian are genuine second-order oracle data; on
a `C²` objective this is exactly the textbook affine-span restriction. -/
def IsSecondOrderSpanSequence
    (f : E → ℝ) (testPoints : ℕ → E) : Prop :=
  HasSecondOrderOracleSequence f testPoints ∧
    ∀ k : ℕ, testPoints k ∈ secondOrderOracleSpanSearchSpace f testPoints k

namespace IsSecondOrderSpanSequence

variable {f : E → ℝ} {testPoints : ℕ → E}

/-- A second-order span sequence queries only points with genuine second-order oracle data. -/
theorem oracle_at
    (hSequence : IsSecondOrderSpanSequence f testPoints) (k : ℕ) :
    HasSecondOrderOracleAt f (testPoints k) :=
  hSequence.1 k

/-- A second-order span sequence keeps every iterate in the corresponding affine search space. -/
theorem span_condition
    (hSequence : IsSecondOrderSpanSequence f testPoints) (k : ℕ) :
    testPoints k ∈ secondOrderOracleSpanSearchSpace f testPoints k :=
  hSequence.2 k

/-- A second-order span sequence keeps every iterate in the affine search space generated by the
earlier second-order oracle directions. -/
theorem sub_mem_span
    (hSequence : IsSecondOrderSpanSequence f testPoints) (k : ℕ) :
    testPoints k - testPoints 0 ∈
      Submodule.span ℝ (⋃ i : Fin k, 𝒢[f; testPoints i]) := by
  simpa [secondOrderOracleSpanSearchSpace, AffineSubspace.mem_mk'] using
    hSequence.span_condition k

end IsSecondOrderSpanSequence

/-- The affine-subspace formulation of Assumption 4.3.1 is equivalent to the corresponding
vector-form span condition. -/
theorem isSecondOrderSpanSequence_iff
    (f : E → ℝ) (testPoints : ℕ → E) :
    IsSecondOrderSpanSequence f testPoints ↔
      HasSecondOrderOracleSequence f testPoints ∧
        ∀ k : ℕ,
          testPoints k - testPoints 0 ∈
            Submodule.span ℝ (⋃ i : Fin k, 𝒢[f; testPoints i]) := by
  simp [IsSecondOrderSpanSequence, secondOrderOracleSpanSearchSpace, AffineSubspace.mem_mk']

/-! ### Corollary_4_3_1 (from Chap04) -/
noncomputable section

open scoped CoordinateSubspace

variable {n k t : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)

/-
Corollary 4.3.1 lies in the Chapter 4 hard-instance / second-order-span / coordinate-subspace
domain.

Sampled owner-style declarations in this domain:
* `IsSecondOrderSpanSequence` together with
  `IsSecondOrderSpanSequence.span_condition` / `IsSecondOrderSpanSequence.sub_mem_span` from
  `Assumption_4_3_1`, the chapter owner for the affine search-space restriction;
* `coordinateSubspace` with notation `ℝ^{k,n}` and `mem_coordinateSubspace_iff` from
  `Chap02/Text_2_13`, the chapter owner/view for prefix-supported vectors;
* `fk_first_second_order_mem_next_coordinate_subspaces` from `Lemma_4_3_1`, the hard-instance
  support-growth theorem for the gradient/Hessian data.

Best owner abstraction:
* source-facing: the corollary that the next iterate of a second-order span sequence for the hard
  instance remains in the next coordinate subspace;
* core/canonical: `IsSecondOrderSpanSequence (fk htn) testPoints` and the owner submodules
  `ℝ^{i,n}`;
* bridge/view: the coordinatewise zero-tail criterion `mem_coordinateSubspace_iff` and the
  hard-instance support-growth theorem from Lemma 4.3.1.

Primitive data:
* the hard-instance objective `fk htn`;
* the test-point sequence `testPoints`;
* the prefix support hypothesis `testPoints i ∈ ℝ^{i,n}` for `i < k + 1`.

Derived API:
* the support conclusion `testPoints (k + 1) ∈ ℝ^{k + 1,n}`.

This file stays source-facing. The corollary should reuse the existing span-sequence owner and the
hard-instance support-growth theorem directly, rather than introducing a parallel wrapper for the
coordinate-support argument.
-/

-- Proof sketch: apply `IsSecondOrderSpanSequence.sub_mem_span` at step `k + 1` for the hard
-- instance `fk htn`, use `testPoints 0 ∈ ℝ^{0,n}` to identify the basepoint with `0`, and feed
-- the earlier support hypotheses through `fk_first_second_order_mem_next_coordinate_subspaces`
-- and the owner search-space condition from `Assumption_4_3_1` to place the next iterate in
-- `ℝ^{k+1,n}`.
/-- Corollary 4.3.1: if the iterates `x_i`, `i = 0, ..., k`, lie in the coordinate subspaces
`ℝ^{i,n}` and the full sequence satisfies Assumption 4.3.1 for the hard-instance objective `f_t`,
with `k + 1 ≤ t ≤ n`, then the next iterate `x_{k+1}` belongs to `ℝ^{k+1,n}`. -/
theorem fk_spanSequence_next_iterate_mem_coordinateSubspace
    (hkt : k + 1 ≤ t) (htn : t ≤ n)
    {testPoints : ℕ → E}
    (hspan : IsSecondOrderSpanSequence (fk htn) testPoints)
    (htestPoints : ∀ i : Fin (k + 1), testPoints i ∈ ℝ^{i,n}) :
    testPoints (k + 1) ∈ ℝ^{k + 1,n} := sorry

/-! ### Definition_4_3_1 (from Chap04) -/
noncomputable section

universe u

open scoped ConstrainedArgmin

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

namespace SetConstrainedMinimizationProblem

/- Definition 4.3.1 lies in the unconstrained second-order minimization domain on complete real
inner-product spaces.

Sampled owner declarations:
* `SetConstrainedMinimizationProblem.unconstrained` in `Chap01/Definition_1_3_3`, the Chapter 1
  owner for whole-space minimization problems;
* `HasLipschitzContinuousHessian`, written on theorem surfaces as `f ∈ C22[L3]`, in
  `Definition_4_2_7`, the Chapter 4 owner for globally Lipschitz Hessian data;
* `argmin[Q]` and `mem_constrainedArgmin_iff` in `Chap01/Definition_1_3_3`, the canonical
  minimizer-set owner for a feasible set;
* `IsMinOn` in mathlib, the canonical minimizer predicate on a set.

Best owner abstraction:
* source-facing: the textbook description of a whole-space problem with Lipschitz Hessian and an
  attained minimum;
* core/canonical: `problem.feasibleSet = Set.univ ∧ ∃ L3 : NNReal, problem.objective ∈ C22[L3]`
  together with `(argmin[problem.feasibleSet] problem).Nonempty`;
* bridge/view: the specialization to `unconstrained f` and the explicit `IsMinOn` reformulations
  below.

Primitive data:
* the constrained problem `problem`;
* the ambient objective `f` when specializing to the whole-space owner `unconstrained f`.

Derived API:
* the Chapter 1 owner `unconstrained f`;
* the Chapter 4 regularity owner surface `problem.objective ∈ C22[L3]`;
* solvability as nonemptiness of the canonical minimizer set.
* the source-style positive-witness reformulation, derived by enlarging any `C22[L3]` witness.

Source/core/bridge triage:
* source-facing: Definition 4.3.1's whole-space Hessian-Lipschitz condition and solvability
  language;
* core/canonical: the conjunction above and `(argmin[problem.feasibleSet] problem).Nonempty`;
* bridge/view: `mem_constrainedArgmin_iff` and the `unconstrained` specialization.

Definition 4.3.1 adds no new owner beyond the Chapter 1 whole-space problem owner, the Chapter 4
`C22[L3]` owner, and the canonical minimizer-set owner. The earlier local class
`IsSecondOrderUnconstrainedWithLipschitzHessian` and alias `IsSolvable` only repackaged those
owners, so this file stays at direct recall/check surface. -/

section

variable (problem : SetConstrainedMinimizationProblem E)

/- The textbook positive-witness form is equivalent to the canonical existential `C22` surface,
since any Hessian-Lipschitz witness can be enlarged to a positive one. -/
theorem exists_pos_mem_C22_iff :
    (∃ L3 : NNReal, 0 < L3 ∧ problem.objective ∈ C22[L3]) ↔
      ∃ L3 : NNReal, problem.objective ∈ C22[L3] := by
  constructor
  · rintro ⟨L3, -, hL3⟩
    exact ⟨L3, hL3⟩
  · rintro ⟨L3, hL3⟩
    refine ⟨max L3 1, zero_lt_one.trans_le (le_max_right _ _), ?_⟩
    exact ⟨hL3.contDiff, hL3.lipschitz.weaken (le_max_left _ _)⟩

/- Definition 4.3.1: a second-order unconstrained minimization problem with Lipschitz Hessian is
exactly a constrained problem whose feasible set is all of `E` and whose objective belongs to
`C22[L3]` for some witness `L3`. The source's strict positivity requirement is the companion
reformulation `problem.exists_pos_mem_C22_iff`, not the main recall surface. -/
set_option linter.hashCommand false in
#check
  (problem.feasibleSet = Set.univ ∧
    ∃ L3 : NNReal, problem.objective ∈ C22[L3])

/- A constrained problem is solvable exactly when its canonical minimizer set is nonempty. -/
set_option linter.hashCommand false in
#check ((argmin[problem.feasibleSet] problem).Nonempty : Prop)

set_option linter.hashCommand false in
#check
  (show
      (argmin[problem.feasibleSet] problem).Nonempty ↔
        ∃ xStar : E, xStar ∈ problem.feasibleSet ∧
          IsMinOn problem problem.feasibleSet xStar from
    by
      constructor
      · rintro ⟨xStar, hxStar⟩
        exact
          ⟨xStar, (mem_constrainedArgmin_iff.mp hxStar).1,
            (mem_constrainedArgmin_iff.mp hxStar).2⟩
      · rintro ⟨xStar, hxFeasible, hxMin⟩
        exact ⟨xStar, (mem_constrainedArgmin_iff).2 ⟨hxFeasible, hxMin⟩⟩)

end

section

variable (f : E → ℝ)

/- The Chapter 1 owner for the whole-space minimization problem with objective `f` is
`unconstrained f`. -/
recall SetConstrainedMinimizationProblem.unconstrained

recall SetConstrainedMinimizationProblem.unconstrained_feasibleSet

recall SetConstrainedMinimizationProblem.unconstrained_apply

set_option linter.hashCommand false in
#check
  (show
      (∃ L3 : NNReal, (unconstrained f).objective ∈ C22[L3]) ↔ ∃ L3 : NNReal, f ∈ C22[L3] from
    Iff.rfl)

set_option linter.hashCommand false in
#check
  (show
      (argmin[(unconstrained f).feasibleSet] (unconstrained f)).Nonempty ↔
        ∃ xStar : E, IsMinOn f Set.univ xStar from
    by
      constructor
      · rintro ⟨xStar, hxStar⟩
        refine ⟨xStar, ?_⟩
        simpa using (mem_constrainedArgmin_iff.mp hxStar).2
      · rintro ⟨xStar, hxStar⟩
        refine ⟨xStar, ?_⟩
        rw [mem_constrainedArgmin_iff]
        exact ⟨by simp, by simpa using hxStar⟩)

end

end SetConstrainedMinimizationProblem

/-! ### Lemma_4_3_1 (from Chap04) -/
open scoped Gradient CoordinateSubspace CoordinateSymmetricMatrixSubspace

variable {n t i : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)

/- Lemma 4.3.1 lies in the Chapter 4 hard-instance / coordinate-support second-order domain.

Sampled owner-style declarations in this domain:
* `coordinateSubspace` and `mem_coordinateSubspace_iff` in `Chap02/Text_2_13`, the chapter owner
  and coordinatewise view for prefix-supported vectors `ℝ^{i,n}`;
* `coordinateSymmetricMatrixSubspace` and `mem_coordinateSymmetricMatrixSubspace_iff` in
  `Definition_4_3_3`, the chapter owner and entrywise view for the symmetric matrix block support
  condition `𝕊^{i,n}`;
* `hessianMatrix` / `∇²` in `Chap01/Definition_1_4_16`, the canonical matrix owner for second
  derivatives on Euclidean space.

Best owner abstraction:
* source-facing: the textbook claim that the gradient/Hessian data of `f_t` at a point in
  `ℝ^{i,n}` only reveal the first `i + 1` coordinates;
* core/canonical: the two atomic memberships `∇ (fk htn) x ∈ ℝ^{i + 1,n}` and
  `∇² (fk htn) x ∈ 𝕊^{i + 1,n}`;
* bridge/view: the packaged product membership
  `(∇ (fk htn) x, ∇² (fk htn) x) ∈ (ℝ^{i + 1,n}).prod 𝕊^{i + 1,n}`.

Primitive data:
* gradient support in the next coordinate subspace;
* Hessian matrix support in the next symmetric coordinate subspace.

Derived API:
* the product-membership theorem bundling those two owner facts.
-/

-- Proof sketch: expand the gradient plus the Hessian matrix `∇² (fk htn) x`
-- coordinatewise. If `x ∈ ℝ^{i,n}`, then `mem_coordinateSubspace_iff` says that
-- the coordinates of `x` vanish from index `i` onward. For `i < t`, the adjacent-difference terms
-- plus tail terms in Definition 4.3.2 involve only coordinates up to `i + 1`. This places the
-- gradient in `ℝ^{i+1,n}`; the same coordinate inspection places the Hessian matrix in
-- `𝕊^{i+1,n}`.
/-- If `x ∈ ℝ^{i,n}` with `i < t`, then the gradient of the hard-instance objective `f_t`
belongs to the next coordinate subspace `ℝ^{i+1,n}`. -/
theorem fk_gradient_mem_next_coordinateSubspace
    (htn : t ≤ n) {x : E} (hx : x ∈ ℝ^{i,n}) (hit : i < t) :
    ∇ (fk htn) x ∈ ℝ^{i + 1,n} := sorry

/-- If `x ∈ ℝ^{i,n}` with `i < t`, then the Hessian matrix of the hard-instance objective `f_t`
belongs to the next symmetric coordinate subspace `𝕊^{i+1,n}`. -/
theorem fk_hessian_mem_next_coordinateSymmetricMatrixSubspace
    (htn : t ≤ n) {x : E} (hx : x ∈ ℝ^{i,n}) (hit : i < t) :
    ∇² (fk htn) x ∈ 𝕊^{i + 1,n} := sorry

/-- Lemma 4.3.1: if `x ∈ ℝ^{i,n}` with `i < t`, then for the hard-instance function `f_t`
formalized by `fk`, the pair formed by the gradient and Hessian matrix at `x` belongs to
`ℝ^{i+1,n} × 𝕊^{i+1,n}`. -/
theorem fk_first_second_order_mem_next_coordinate_subspaces
    (htn : t ≤ n) {x : E} (hx : x ∈ ℝ^{i,n}) (hit : i < t) :
    (∇ (fk htn) x, ∇² (fk htn) x) ∈
      (ℝ^{i + 1,n}).prod 𝕊^{i + 1,n} := by
  exact ⟨fk_gradient_mem_next_coordinateSubspace htn hx hit,
    fk_hessian_mem_next_coordinateSymmetricMatrixSubspace htn hx hit⟩

/-! ### Proposition_4_3_1 (from Chap04) -/
noncomputable section

open scoped BigOperators ConstrainedArgmin

variable {n k : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)

/- Proposition 4.3.1 lies in the Chapter 4 cubic hard-instance / degree-3 uniform-convexity
domain on Euclidean spaces.

Sampled owner-style declarations:
* `argmin[Q]` and `mem_constrainedArgmin_iff` in `Chap01/Definition_1_3_3`, the chapter owner
  for feasible minimizer sets;
* `uniformConvexPowerModulus` in `Definition_4_2_8`, the chapter owner for the degree-`p` power
  modulus used on theorem surfaces;
* `HasUniformConvexityParameterOfDegree` in `Definition_4_2_11`, whose primitive witness data is
  a positive constant `σ` with `UniformConvexOn Set.univ (uniformConvexPowerModulus σ p) f`;
* `lower_bound_at_minimizer_of_uniformConvexOn` in `Theorem_4_2_1`, the chapter owner theorem
  built from `argmin[Q]` and `UniformConvexOn`;
* mathlib `UniformConvexOn.strictConvexOn`, the canonical bridge from a positive modulus witness
  to strict convexity.

Best owner abstraction:
* source-facing: the cubic hard-instance objective `fk hkn`, its explicit minimizer `x_*`, its
  optimal value, and the radius estimate;
* core/canonical: a positive degree-`3` witness
  `∃ σ > 0, UniformConvexOn Set.univ (uniformConvexPowerModulus σ (3 : ℝ)) (fk hkn)` together
  with the minimizer owner `argmin[Set.univ] (fk hkn)`;
* bridge/view: the singleton-argmin consequence for the explicit minimizer, plus the coordinate
  and norm-expansion lemmas below.

Primitive data:
* the hard-instance objective `fk hkn`;
* the explicit vector `cubicLowerBoundMinimizer n k`.

Derived API:
* the coordinate formula for the explicit minimizer;
* degree-`3` whole-space uniform convexity of `fk hkn`;
* uniqueness of the explicit global minimizer through the canonical owner
  `argmin[Set.univ] (fk hkn)`;
* the value and distance formulas at that minimizer.

The file therefore keeps the explicit minimizer as the source-facing owner for the hard instance,
but uses the chapter's canonical degree-`3` `UniformConvexOn` and `argmin[Set.univ]` surfaces
instead of a raw existential modulus function `∃ φ : ℝ → ℝ, ...` or a bespoke uniqueness package.
-/

/-- The explicit vector `x_*` with coordinates `x_*^(i) = (k - i + 1)_+`. -/
def cubicLowerBoundMinimizer (n k : ℕ) : EuclideanSpace ℝ (Fin n) :=
  (EuclideanSpace.equiv (Fin n) ℝ).symm fun i : Fin n ↦ ((k - (i : ℕ) : ℕ) : ℝ)

-- Proof sketch: unfold `cubicLowerBoundMinimizer`; on the `i`-th zero-based coordinate the value
-- is the truncated natural difference `k - i`, which is exactly `(k - i + 1)_+` in textbook
-- one-based indexing.
/-- The coordinates of the explicit minimizer are `x_*^(i) = (k - i + 1)_+`. -/
theorem cubicLowerBoundMinimizer_apply (i : Fin n) :
    cubicLowerBoundMinimizer n k i = ((k - (i : ℕ) : ℕ) : ℝ) := by
  simp [cubicLowerBoundMinimizer]

-- Proof sketch: the cubic sum of adjacent differences and tail coordinates in `fk hkn`
-- yields a modulus witnessing uniform convexity.
/-- Proposition 4.3.1 (1): the hard-instance objective `fk hkn` from
Definition 4.3.2 is uniformly convex. -/
theorem cubicLowerBoundObjective_uniformlyConvex
    (hkn : k ≤ n) :
    ∃ σ > 0,
      UniformConvexOn Set.univ
        (uniformConvexPowerModulus σ (3 : ℝ))
        (fk hkn) := sorry

-- Proof sketch: strict convexity follows from the positive modulus in
-- `cubicLowerBoundObjective_uniformlyConvex`, and a strictly convex function has at most one
-- global minimizer. The explicit vector `cubicLowerBoundMinimizer n k` is then identified as the
-- unique point of the canonical owner `argmin[Set.univ] (fk hkn)` by checking the optimality
-- conditions.
/-- Proposition 4.3.1 (2): the canonical minimizer set of the cubic hard-instance objective is the
singleton containing the explicit vector `x_*^(i) = (k - i + 1)_+`. -/
theorem cubicLowerBoundObjective_argmin_eq_singleton
    (hkn : k ≤ n) :
    argmin[Set.univ] (fk hkn) = {cubicLowerBoundMinimizer n k} := sorry

-- Proof sketch: substitute the explicit coordinates of `cubicLowerBoundMinimizer` into the
-- defining formula of `fk hkn`; each adjacent difference contributes `1`,
-- the tail contributes the final `1`, and the linear term contributes `-k`.
/-- Evaluating the cubic hard instance at the explicit minimizer gives the optimal value
`f_k(x_*) = -(2 / 3) k`. -/
theorem cubicLowerBoundObjective_value_at_minimizer (hkn : k ≤ n) :
    fk hkn (cubicLowerBoundMinimizer n k) =
      -((2 : ℝ) / 3) * k := sorry

-- Proof sketch: the zero initialization leaves only the coordinates of `x_*`; summing their
-- squares gives `∑_{i=1}^k i^2` after reindexing from textbook one-based coordinates to `Fin n`,
-- using `k ≤ n` so the nonzero coordinates of `x_*` all lie in the ambient space.
/-- The squared Euclidean distance from the zero vector to the explicit minimizer is
`∑_{i=1}^k i^2` under the hard-instance range hypothesis `k ≤ n`. -/
theorem cubicLowerBoundMinimizer_sqDist_eq_sumSquares
    (hkn : k ≤ n) :
    ‖(0 : E) - cubicLowerBoundMinimizer n k‖ ^ (2 : ℕ) =
      ∑ i ∈ Finset.Icc 1 k, (i : ℝ) ^ (2 : ℕ) := sorry

-- Proof sketch: compare the sum of squares with the integral of `x^2` on `[0, k + 1]`, or use
-- the closed formula `k (k + 1) (2 k + 1) / 6`.
/-- The squared Euclidean distance from the zero vector to the explicit minimizer is strictly less
than `(k + 1)^3 / 3` under the hard-instance range hypothesis `k ≤ n`. -/
theorem cubicLowerBoundMinimizer_sqDist_lt
    (hkn : k ≤ n) :
    ‖(0 : E) - cubicLowerBoundMinimizer n k‖ ^ (2 : ℕ) <
      (((k + 1 : ℕ) : ℝ) ^ (3 : ℕ)) / 3 := sorry

/-! ### Theorem_4_3_1 (from Chap04) -/
noncomputable section

open scoped Gradient

variable {n : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)

/- Theorem 4.3.1 lies in the second-order oracle / lower-complexity domain on `ℝ^n`.

Sampled owner-style declarations:
* `IsSecondOrderSpanSequence` in `Assumption_4_3_1`, the chapter owner for the second-order
  affine-span restriction;
* `bestFunctionValueUpTo` in `Chap03/Definition_3_55`, the chapter owner for the best sampled
  objective value on a finite prefix;
* `HasLipschitzContinuousHessian` and the notation `C22[L]` in `Definition_4_2_7`, the chapter
  owner for globally Hessian-Lipschitz objectives;
* the project-standard positive-parameter owner `NNRealˣ`, used throughout the project whenever a
  displayed denominator is mathematically required to stay strictly positive;
* `SatisfiesSpanCondition` in `Chap02/Definition_2_9`, the earlier chapter pattern showing that a
  lower-complexity method should be modeled by its primitive iterate family, with the span
  restriction kept as a separate theorem-level hypothesis rather than as bundled data.

Source/core/bridge triage:
* source-facing: the cubic hard-instance lower bound for a second-order method complexity profile;
* core/canonical: `IsSecondOrderSpanSequence`, `bestFunctionValueUpTo`, and `f ∈ C22[L]`;
* bridge/view: the trajectory-value specialization `fun i ↦ f (testPoints f x0 i)` of the owner
  sampled-minimum API.

Primitive data:
* the iterate family `testPoints`;
* the strictly positive complexity profile `complexityConstant`.

Derived API:
* the initialization law `testPoints f x0 0 = x0`;
* the second-order span restriction on every `C²` objective;
* the uniform guarantee on `bestFunctionValueUpTo` for every Hessian-Lipschitz objective.

The previous file bundled the theorem hypotheses into a local `SecondOrderMethod` structure and
redefined the sampled-prefix minimum locally. The refinement keeps the source-facing theorem, but
uses the chapter owners `IsSecondOrderSpanSequence`, `bestFunctionValueUpTo`, and `C22[L]`
directly, leaving only the genuine primitive data as explicit inputs. The complexity denominator is
owned by `NNRealˣ`, so the displayed quantity `L_f ρ₀^3 / C_𝓜(k)` keeps its textbook
positive-denominator semantics instead of degenerating at `C_𝓜(k) = 0`.
-/

-- Proof sketch: apply the hard-instance family `f_t` with `t = 4m + 3` and start from `x₀ = 0`.
-- The span-sequence restriction keeps the first `k + 1` iterates in the coordinate subspaces
-- given by Corollary 4.3.1, so Lemma 4.3.2 identifies the best value among those iterates with
-- the hard-instance gap `f_k^* - f_t^* = (2 / 3) (m + 1)`. Proposition 4.3.2 supplies the
-- Hessian-Lipschitz constant on the canonical `C22[...]` surface, Proposition 4.3.1 controls the
-- distance from `0` to the minimizer, and rearranging the assumed estimate (4.3.7) yields the
-- displayed upper bound.
/-- Theorem 4.3.1: let the Hessian of the objective be Lipschitz continuous with constant `L_f`,
and let a second-order method satisfy the textbook second-order information restriction and the
guarantee
`min_{0 ≤ i ≤ k} f(x_i) - f(x^*) ≤ L_f ρ₀^3 / C_𝓜(k)` for every starting point
`x₀` with `‖x₀ - x^*‖ ≤ ρ₀`. Then, whenever `k = 3m + 2` with `m + 1 ≤ n / 4`
(equivalently `4 * (m + 1) ≤ n`), the strictly positive complexity quantity satisfies
`C_𝓜(k) ≤ 36 (k + 1)^{3.5}`. -/
theorem secondOrderMethod_complexityConstant_le_cubicHardInstance_bound
    (testPoints : (E → ℝ) → E → ℕ → E)
    (complexityConstant : ℕ → NNRealˣ)
    (htestPoints_zero :
      ∀ (f : E → ℝ) (x0 : E), testPoints f x0 0 = x0)
    (hspan :
      ∀ (f : E → ℝ) (_ : ContDiff ℝ 2 f) (x0 : E),
        IsSecondOrderSpanSequence f (testPoints f x0))
    (hguarantee :
      ∀ (f : E → ℝ) (Lf : NNReal) (_ : f ∈ C22[Lf])
        (xStar x0 : E) (rho0 : ℝ) (k : ℕ),
        IsMinOn f Set.univ xStar →
          ‖x0 - xStar‖ ≤ rho0 →
            bestFunctionValueUpTo (fun i ↦ f (testPoints f x0 i)) k - f xStar ≤
              (Lf : ℝ) * rho0 ^ 3 / (complexityConstant k : ℝ))
    {k m : ℕ} (hk : k = 3 * m + 2) (hm : m + 1 ≤ n / 4) :
    (complexityConstant k : ℝ) ≤
      36 * ((k + 1 : ℝ) ^ 3 * Real.sqrt (k + 1)) := sorry

end

/-! ### Definition_4_3_2 (from Chap04) -/
noncomputable section

open scoped BigOperators

variable {n k : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)

private theorem fk_prefix_len_le (hk : 0 < k) (hkn : k ≤ n) : (k - 1) + 1 ≤ n := by
  omega

private def fkPrefixEmb (hk : 0 < k) (hkn : k ≤ n) : Fin ((k - 1) + 1) ↪ Fin n :=
  Fin.castLEEmb (fk_prefix_len_le hk hkn)

private def fkTailEmb : Fin (n - k) ↪ Fin n :=
  Fin.natAdd_castLEEmb (Nat.sub_le n k)

private def fkPrefixCoords (hk : 0 < k) (hkn : k ≤ n) (x : E) : Fin ((k - 1) + 1) → ℝ :=
  x ∘ fkPrefixEmb hk hkn

private def fkTailCoords (x : E) : Fin (n - k) → ℝ :=
  x ∘ fkTailEmb

/-- Definition 4.3.2: for `k ≤ n`, `fk hkn` extends the textbook hard-instance objective
`f_k : ℝ^n → ℝ`; when `0 < k`, it is given by the cubic sum of adjacent-coordinate differences
over the first `k - 1` coordinates, the cubic tail sum from coordinate `k` onward, and the linear
term `-x^{(1)}`, while the degenerate case `k = 0` keeps only the cubic tail term so the owner is
defined for all `k ≤ n`. -/
def fk (hkn : k ≤ n) : E → ℝ :=
  fun x ↦
    if hk : 0 < k then
      (1 / 3 : ℝ) *
          ((∑ i : Fin (k - 1),
              |fkPrefixCoords hk hkn x (Fin.castSucc i) - fkPrefixCoords hk hkn x i.succ| ^
                  (3 : ℕ)) +
            |fkPrefixCoords hk hkn x (Fin.last (k - 1))| ^ (3 : ℕ)) -
        fkPrefixCoords hk hkn x 0 +
        (1 / 3 : ℝ) * ∑ i : Fin (n - k), |fkTailCoords x i| ^ (3 : ℕ)
    else
      (1 / 3 : ℝ) * ∑ i : Fin n, |x i| ^ (3 : ℕ)

/-- Expanding `fk` recovers the textbook coordinate formula for the hard-instance objective
`f_k`. -/
@[simp]
theorem fk_apply (hkn : k ≤ n) (x : E) :
    fk hkn x =
      if hk : 0 < k then
        (1 / 3 : ℝ) *
            ((∑ i : Fin (k - 1),
                |x (Fin.castLE (fk_prefix_len_le hk hkn) (Fin.castSucc i)) -
                    x (Fin.castLE (fk_prefix_len_le hk hkn) i.succ)| ^ (3 : ℕ)) +
              |x (Fin.castLE (fk_prefix_len_le hk hkn) (Fin.last (k - 1)))| ^ (3 : ℕ)) -
          x (Fin.castLE (fk_prefix_len_le hk hkn) 0) +
          (1 / 3 : ℝ) *
            ∑ i : Fin (n - k),
              |x (Fin.natAdd_castLEEmb (Nat.sub_le n k) i)| ^ (3 : ℕ)
      else
        (1 / 3 : ℝ) * ∑ i : Fin n, |x i| ^ (3 : ℕ) := by
  by_cases hk : 0 < k
  · simp [fk, hk, fkPrefixCoords, fkPrefixEmb, fkTailCoords, fkTailEmb]
  · simp [fk, hk]

end

/-! ### Lemma_4_3_2 (from Chap04) -/
variable {n k p : ℕ}

local notation "E" => EuclideanSpace ℝ (Fin n)
open scoped CoordinateSubspace

-- Proof sketch: unfold `fk` on both sides. If `x ∈ coordinateSubspace k n`,
-- then `mem_coordinateSubspace_iff` says that every coordinate with index at least `k` vanishes,
-- so the extra adjacent-difference terms and tail terms introduced when passing from `f_k` to
-- `f_{k+p}` are all zero, while the shared terms and the linear term `-x^{(1)}` are unchanged.
/-- Lemma 4.3.2: if `x` lies in the coordinate subspace `ℝ^{k,n}`, then enlarging the hard-instance
index from `k` to `k + p` does not change the value of the textbook function `f_k`. -/
theorem fk_add_eq_of_mem_coordinateSubspace
    (hkpn : k + p ≤ n) {x : E}
    (hx : x ∈ ℝ^{k,n}) :
    fk hkpn x =
      fk (le_trans (Nat.le_add_right k p) hkpn) x := by
  have hkn : k ≤ n := le_trans (Nat.le_add_right k p) hkpn
  by_cases hp0 : p = 0
  · subst p
    exact congrArg (fun h : k ≤ n ↦ fk h x) (Subsingleton.elim _ _)
  have hp : 0 < p := Nat.pos_of_ne_zero hp0
  have hx0 := mem_coordinateSubspace_iff.mp hx
  have hx_tail {j : ℕ} (hkj : k ≤ j) (hjn : j < n) : x ⟨j, hjn⟩ = 0 :=
    hx0 ⟨j, hjn⟩ hkj
  by_cases hk : 0 < k
  · have hkppos : 0 < k + p := Nat.add_pos_left hk p
    rw [fk_apply, fk_apply]
    simp [hk, hkppos]
    let tailk : ℕ → ℝ := fun j ↦ if hj : k + j < n then |x ⟨k + j, hj⟩| ^ (3 : ℕ) else 0
    let tailkp : ℕ → ℝ := fun j ↦
      if hj : k + p + j < n then |x ⟨k + p + j, hj⟩| ^ (3 : ℕ) else 0
    let diff : ℕ → ℝ := fun j ↦
      if hj : j + 1 < n then |x ⟨j, Nat.lt_of_succ_lt hj⟩ - x ⟨j + 1, hj⟩| ^ (3 : ℕ) else 0
    have htailk_left :
        (∑ i : Fin (n - k), |x (Fin.natAdd_castLEEmb (Nat.sub_le n k) i)| ^ (3 : ℕ)) =
          ∑ i : Fin (n - k), tailk i := by
      refine Finset.sum_congr rfl ?_
      intro i hi
      have hi' : k + (i : ℕ) < n := by
        omega
      have hcast : (Fin.natAdd_castLEEmb (Nat.sub_le n k) i : Fin n) = ⟨k + i, hi'⟩ := by
        ext
        simp [Fin.natAdd_castLEEmb]
        omega
      simp [tailk, hi', hcast]
    have htailk :
        (∑ i : Fin (n - k), |x (Fin.natAdd_castLEEmb (Nat.sub_le n k) i)| ^ (3 : ℕ)) = 0 := by
      rw [htailk_left]
      rw [show (∑ i : Fin (n - k), tailk i) = ∑ j ∈ Finset.range (n - k), tailk j by
        simpa using (Fin.sum_univ_eq_sum_range tailk (n - k))]
      apply Finset.sum_eq_zero
      intro j hj
      have hjlt : k + j < n := by
        have : j < n - k := Finset.mem_range.mp hj
        omega
      have hxj : x ⟨k + j, hjlt⟩ = 0 := hx_tail (Nat.le_add_right k j) hjlt
      simp [tailk, hjlt, hxj]
    have htailkp_left :
        (∑ i : Fin (n - (k + p)), |x (Fin.natAdd_castLEEmb (Nat.sub_le n (k + p)) i)| ^
          (3 : ℕ)) =
          ∑ i : Fin (n - (k + p)), tailkp i := by
      refine Finset.sum_congr rfl ?_
      intro i hi
      have hi' : k + p + (i : ℕ) < n := by
        omega
      have hcast : (Fin.natAdd_castLEEmb (Nat.sub_le n (k + p)) i : Fin n) = ⟨k + p + i, hi'⟩ := by
        ext
        simp [Fin.natAdd_castLEEmb]
        omega
      simp [tailkp, hi', hcast]
    have htailkp :
        (∑ i : Fin (n - (k + p)), |x (Fin.natAdd_castLEEmb (Nat.sub_le n (k + p)) i)| ^
          (3 : ℕ)) = 0 := by
      rw [htailkp_left]
      rw [show (∑ i : Fin (n - (k + p)), tailkp i) = ∑ j ∈ Finset.range (n - (k + p)), tailkp j by
        simpa using (Fin.sum_univ_eq_sum_range tailkp (n - (k + p)))]
      apply Finset.sum_eq_zero
      intro j hj
      have hjlt : k + p + j < n := by
        have : j < n - (k + p) := Finset.mem_range.mp hj
        omega
      have hxj : x ⟨k + p + j, hjlt⟩ = 0 := by
        refine hx_tail ?_ hjlt
        omega
      simp [tailkp, hjlt, hxj]
    have hdiff_small_left :
        (∑ i : Fin (k - 1),
          |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ)) =
          ∑ i : Fin (k - 1), diff i := by
      refine Finset.sum_congr rfl ?_
      intro i hi
      change |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ) = diff i
      have hi' : (i : ℕ) + 1 < n := by
        omega
      have hleft : (Fin.castLE (by omega) i : Fin n) = ⟨i, Nat.lt_of_succ_lt hi'⟩ := by
        ext
        simp
      have hright : (Fin.castLE (by omega) i.succ : Fin n) = ⟨i + 1, hi'⟩ := by
        ext
        simp
      simp [diff, hleft, hright, hi']
    have hdiff_small :
        (∑ i : Fin (k - 1),
          |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ)) =
          ∑ j ∈ Finset.range (k - 1), diff j := by
      rw [hdiff_small_left]
      simpa [diff] using (Fin.sum_univ_eq_sum_range diff (k - 1))
    have hdiff_large_left :
        (∑ i : Fin (k + p - 1),
          |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ)) =
          ∑ i : Fin (k + p - 1), diff i := by
      refine Finset.sum_congr rfl ?_
      intro i hi
      change |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ) = diff i
      have hi' : (i : ℕ) + 1 < n := by
        omega
      have hleft : (Fin.castLE (by omega) i : Fin n) = ⟨i, Nat.lt_of_succ_lt hi'⟩ := by
        ext
        simp
      have hright : (Fin.castLE (by omega) i.succ : Fin n) = ⟨i + 1, hi'⟩ := by
        ext
        simp
      simp [diff, hleft, hright, hi']
    have hdiff_large :
        (∑ i : Fin (k + p - 1),
          |x (Fin.castLE (by omega) i) - x (Fin.castLE (by omega) i.succ)| ^ (3 : ℕ)) =
          ∑ j ∈ Finset.range (k + p - 1), diff j := by
      rw [hdiff_large_left]
      simpa [diff] using (Fin.sum_univ_eq_sum_range diff (k + p - 1))
    have hsplit :
        ∑ j ∈ Finset.range (k + p - 1), diff j =
          ∑ j ∈ Finset.range (k - 1), diff j + ∑ j ∈ Finset.Ico (k - 1) (k + p - 1), diff j := by
      exact (Finset.sum_range_add_sum_Ico diff (show k - 1 ≤ k + p - 1 by
        omega)).symm
    have hdiff_km1 : diff (k - 1) = |x ⟨k - 1, by omega⟩| ^ (3 : ℕ) := by
      have hklt : k < n := by
        omega
      have hxk : x ⟨k, hklt⟩ = 0 := hx_tail le_rfl hklt
      have hsame : k - 1 + 1 = k := by
        omega
      simp [diff, hsame, hklt, hxk]
    have hrest_zero : ∑ j ∈ Finset.Ico k (k + p - 1), diff j = 0 := by
      apply Finset.sum_eq_zero
      intro j hj
      have hjk : k ≤ j := (Finset.mem_Ico.mp hj).1
      have hjlt : j + 1 < n := by
        have hjup : j < k + p - 1 := (Finset.mem_Ico.mp hj).2
        omega
      have hxj : x ⟨j, by omega⟩ = 0 := hx_tail hjk (by omega)
      have hxj1 : x ⟨j + 1, hjlt⟩ = 0 := by
        refine hx_tail ?_ hjlt
        omega
      simp [diff, hjlt, hxj, hxj1]
    have hextra :
        ∑ j ∈ Finset.Ico (k - 1) (k + p - 1), diff j = |x ⟨k - 1, by omega⟩| ^ (3 : ℕ) := by
      rw [Finset.sum_eq_sum_Ico_succ_bot (show k - 1 < k + p - 1 by
        omega) diff]
      have hrest_zero' : ∑ j ∈ Finset.Ico (k - 1 + 1) (k + p - 1), diff j = 0 := by
        simpa [show k - 1 + 1 = k by
          omega] using hrest_zero
      simpa [hdiff_km1] using hrest_zero'
    have hterm_small : |x (Fin.castLE (by omega) (Fin.last (k - 1)))| ^ (3 : ℕ) =
        |x ⟨k - 1, by omega⟩| ^ (3 : ℕ) := by
      have hlast : (Fin.castLE (by omega) (Fin.last (k - 1)) : Fin n) = ⟨k - 1, by omega⟩ := by
        ext
        simp
      simp [hlast]
    have hterm_large : |x (Fin.castLE (by omega) (Fin.last (k + p - 1)))| ^ (3 : ℕ) = 0 := by
      have hlast :
          (Fin.castLE (by omega) (Fin.last (k + p - 1)) : Fin n) = ⟨k + p - 1, by omega⟩ := by
        ext
        simp
      have hxlast : x ⟨k + p - 1, by omega⟩ = 0 := by
        refine hx_tail ?_ (by omega)
        omega
      simp [hlast, hxlast]
    rw [hdiff_large, hdiff_small, htailkp, htailk, hsplit, hextra, hterm_small, hterm_large]
    ring_nf
    congr 1
  · have hk0 : k = 0 := Nat.eq_zero_of_not_pos hk
    subst k
    have hxzero : x = 0 := by
      ext i
      exact hx0 i (Nat.zero_le i.1)
    simp [fk_apply, hxzero]

/-! ### Proposition_4_3_2 (from Chap04) -/
variable {n k : ℕ}

/-- Proposition 4.3.2: for `k ≤ n`, the hard-instance objective `fk hkn` has globally
`(8 * √2)`-Lipschitz Hessian, recorded on the chapter's canonical `C22[...]` surface. The
degenerate cases `k = 0, 1` are included because the same owner bound still applies there. -/
theorem fk_mem_C22
    (hkn : k ≤ n) :
    fk hkn ∈ C22[⟨8 * Real.sqrt 2, by positivity⟩] := sorry

/-! ### Theorem_4_3_2 (from Chap04) -/
noncomputable section

open LinearMap (BilinForm)
open LinearMap.BilinForm
open scoped BInducedNorm CubicNewtonStepNotation

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]

/- Theorem 4.3.2 lies in the optimal cubic-Newton estimating-sequence rate domain on a
finite-dimensional real inner-product space.

Sampled owner-style declarations:
* `OptimalCubicNewtonMethod` in `Algorithm_4_3_1`, the chapter owner for the iterate sequence,
  the cubic Newton step `T_M`, the estimating functions `ψ_k`, and the accumulated weights `A_k`;
* `OptimalCubicNewtonMethod.psi_isMin` in `Algorithm_4_3_1`, the derived owner theorem recording
  that each `v_k` minimizes `ψ_k`;
* `OptimalCubicNewtonMethod.accumulated_weight_lower_bound` in `Lemma_4_3_5`, the predecessor
  owner theorem producing the lower bound on `A_k` from the residual sandwich and the estimating
  majorization at `xStar`.

Best owner abstraction:
* core/canonical: `OptimalCubicNewtonMethod B Mf f x0 sigma`

Primitive data:
* the method data already stored by `OptimalCubicNewtonMethod`
* the comparison point `xStar`
* the scalar sandwich factor `γ`

Derived API:
* the estimating-function majorization at the comparison point `xStar`
* the residual sandwich `r_M(y_k) ≤ ρ_k ≤ γ r_M(y_k)`
* the lower bound on the accumulated weights `A_k`

Source/core/bridge triage:
* source-facing: Theorem 4.3.2's inverse-`7/2` objective-gap estimate
* core/canonical: the owner `OptimalCubicNewtonMethod`
* bridge/view: the passage from the accumulated-weight lower bound to the explicit rate
-/

section

variable {B : BilinForm ℝ E} {Mf : NNRealˣ} {f : PrimalSpace B → ℝ}
  [Fact B.toQuadraticMap.PosDef]
  {x0 xStar : PrimalSpace B} {sigma γ : ℝ}
  (method : OptimalCubicNewtonMethod B Mf f x0 sigma)

namespace OptimalCubicNewtonMethod

-- Proof sketch: combine Lemma 4.3.4 with the upper majorization of `ψ_k` at the comparison point
-- `xStar` to get
-- `f (method k) - f xStar ≤ (1 / (2 * method.A k)) * ‖x₀ - xStar‖^2` for `k ≥ 1`. Then apply
-- `method.accumulated_weight_lower_bound` to bound `method.A k` from below and simplify the
-- resulting reciprocal estimate using `M = M_f / σ`.
/-- Theorem 4.3.2: if `f` is convex, the auxiliary parameters of Algorithm 4.3.1 satisfy
the residual sandwich `r_M(y_k) ≤ ρ_k ≤ γ r_M(y_k)` from Lemma 4.3.5, and the estimating
functions are majorized at a comparison point `xStar` by
`A_k f(xStar) + (1 / 2) ‖x₀ - xStar‖^2`, then Algorithm 4.3.1 with `M = M_f / σ` satisfies, for
every `k ≥ 1`,
`f(x_k) - f(xStar) ≤ (2 γ^(3/2) M_f ‖x₀ - xStar‖^3 / (σ * √(1 - σ^2))) * (3 / (2k + 1))^(7/2)`,
where the norm is the primal norm induced by `B`. -/
theorem gap_le_inverse_seven_halves_rate
    (hf_conv : ConvexOn ℝ Set.univ f)
    (hpsi_upper : ∀ k : ℕ,
      let Δ := x0 - xStar
      method.psi k xStar ≤
        method.A k * f xStar + (1 / 2 : ℝ) * ‖Δ‖[B] ^ (2 : ℕ))
    (hresidual_lower : ∀ k : ℕ, r[(method.step)] (method.y k) ≤ method.rho k)
    (hresidual_upper : ∀ k : ℕ, method.rho k ≤ γ * r[(method.step)] (method.y k))
    {k : ℕ} (hk : 1 ≤ k) :
    let Δ := x0 - xStar
    f (method k) - f xStar ≤
      (((2 : ℝ) * Real.rpow γ (3 / 2 : ℝ) * (Mf : ℝ)) *
          ‖Δ‖[B] ^ (3 : ℕ) /
        (sigma * Real.sqrt (1 - sigma ^ (2 : ℕ)))) *
        Real.rpow ((3 : ℝ) / (2 * k + 1 : ℝ)) (7 / 2 : ℝ) := sorry

end OptimalCubicNewtonMethod

end

/-! ### Definition_4_3_3 (from Chap04) -/
noncomputable section

variable {n : ℕ}

local notation "Mat" => Matrix (Fin n) (Fin n) ℝ

/- Definition 4.3.3 lies in the finite-dimensional linear-algebra / symmetric-matrix subspace
domain.

Sampled owner-style declarations in this domain:
* `coordinateSubspace` and `mem_coordinateSubspace_iff` in `Text_2_13`, the Chapter 2 owner/view
  for coordinatewise vanishing subspaces in `ℝⁿ`;
* mathlib `selfAdjointMatricesSubmodule`, the canonical submodule owner for symmetric real
  matrices via the identity bilinear form;
* mathlib `Submodule.pi` and `Submodule.comap`, the canonical owners for coordinatewise support
  conditions on function spaces;
* mathlib `Matrix.ofLinearEquiv`, the canonical bridge between matrices and curried entrywise
  functions.

Best owner abstractions:
* source-facing: `coordinateSymmetricMatrixSubspace k n`, the textbook subspace `𝕊^{k,n}`;
* core/canonical: the intersection of the symmetric-matrix owner
  `selfAdjointMatricesSubmodule (1 : Matrix (Fin n) (Fin n) ℝ)` with the coordinate-support
  submodule defined via `Submodule.comap`/`Submodule.pi`;
* bridge/view: `mem_coordinateSymmetricMatrixSubspace_iff`.

Primitive data:
* symmetry of the matrix;
* the allowed support pattern: diagonal entries are free, and off-diagonal entries are free only
  inside the leading `k × k` block.

Derived API:
* the source-facing owner `coordinateSymmetricMatrixSubspace`;
* its notation `𝕊^{k,n}`;
* the textbook membership criterion `mem_coordinateSymmetricMatrixSubspace_iff`.

This file therefore keeps the textbook owner `𝕊^{k,n}` but deletes the hand-written additive
closure proofs in favor of the canonical symmetric-matrix owner and a private support submodule.
-/

#check coordinateSubspace
#check mem_coordinateSubspace_iff

private theorem mem_symmetricMatrixSubmodule_iff {H : Mat} :
    H ∈ selfAdjointMatricesSubmodule (1 : Mat) ↔ H.IsSymm := by
  rw [mem_selfAdjointMatricesSubmodule]
  simp [Matrix.IsSelfAdjoint, Matrix.IsAdjointPair, Matrix.IsSymm]

private def coordinateMatrixSupportSubmodule (k n : ℕ) :
    Submodule ℝ (Matrix (Fin n) (Fin n) ℝ) :=
  Submodule.comap
    ((Matrix.ofLinearEquiv ℝ : (Fin n → Fin n → ℝ) ≃ₗ[ℝ] Matrix (Fin n) (Fin n) ℝ).symm.toLinearMap)
    (Submodule.pi Set.univ (fun i : Fin n ↦
      Submodule.pi Set.univ (fun j : Fin n ↦
        if i = j ∨ (i.1 < k ∧ j.1 < k) then (⊤ : Submodule ℝ ℝ) else ⊥)))

private theorem mem_coordinateMatrixSupportSubmodule_iff {H : Mat} {k : ℕ} :
    H ∈ coordinateMatrixSupportSubmodule k n ↔
      ∀ i j : Fin n, i ≠ j → (k ≤ i.1 ∨ k ≤ j.1) → H i j = 0 := by
  have hsupp :
      H ∈ coordinateMatrixSupportSubmodule k n ↔
        ∀ i j : Fin n,
          H i j ∈
            (if i = j ∨ (i.1 < k ∧ j.1 < k) then (⊤ : Submodule ℝ ℝ) else ⊥) := by
    simp [coordinateMatrixSupportSubmodule, Submodule.mem_comap, Submodule.mem_pi]
  rw [hsupp]
  constructor
  · intro h i j hij hk
    have hmem := h i j
    have hk' : ¬ (i.1 < k ∧ j.1 < k) := by
      omega
    simpa [hij, hk'] using hmem
  · intro h i j
    by_cases hij : i = j
    · simp [hij]
    · by_cases hk : i.1 < k ∧ j.1 < k
      · simp [hij, hk]
      · have hk' : k ≤ i.1 ∨ k ≤ j.1 := by
          omega
        simp [hij, hk, h i j hij hk']

/-- Definition 4.3.3: `coordinateSymmetricMatrixSubspace k n` is the coordinate subspace
`𝕊^{k,n}` of symmetric matrices whose off-diagonal entries vanish whenever one index lies beyond
the first `k` coordinates. -/
def coordinateSymmetricMatrixSubspace (k n : ℕ) : Submodule ℝ (Matrix (Fin n) (Fin n) ℝ) :=
  selfAdjointMatricesSubmodule (1 : Matrix (Fin n) (Fin n) ℝ) ⊓ coordinateMatrixSupportSubmodule k n

scoped[CoordinateSymmetricMatrixSubspace] notation "𝕊^{" k "," n "}" =>
  coordinateSymmetricMatrixSubspace k n
open scoped CoordinateSymmetricMatrixSubspace

-- Proof sketch: `coordinateSymmetricMatrixSubspace` is the intersection of the canonical
-- symmetric-matrix submodule and the private coordinate-support submodule, so membership is the
-- conjunction of symmetry and the displayed off-diagonal vanishing criterion.
/-- Membership in `𝕊^{k,n}` means that the matrix is symmetric and
all off-diagonal entries vanish whenever one of the indices lies past the first `k` positions. -/
theorem mem_coordinateSymmetricMatrixSubspace_iff {H : Mat} {k : ℕ} :
    H ∈ 𝕊^{k,n} ↔
      H.IsSymm ∧
        ∀ i j : Fin n, i ≠ j → (k ≤ i.1 ∨ k ≤ j.1) → H i j = 0 := by
  rw [coordinateSymmetricMatrixSubspace, Submodule.mem_inf, mem_symmetricMatrixSubmodule_iff,
    mem_coordinateMatrixSupportSubmodule_iff]

/-! ### Lemma_4_3_3 (from Chap04) -/
noncomputable section

open LinearMap (BilinForm)
open LinearMap.BilinForm
open scoped BInducedNorm CubicNewtonStepNotation

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]

/- Lemma 4.3.3 lies in the bilinear-form-induced cubic-Newton / Hessian-Lipschitz remainder
domain.

Sampled owner-style declarations:
* `HasLipschitzContinuousHessian` in `Definition_4_3_5`, written on theorem surfaces as
  `f ∈ C22[Mf]` on `PrimalSpace B`;
* `HasLipschitzContinuousHessian.gradient_deviation_le` in `Chap01/Lemma_1_5_11`, read on the
  intrinsic carrier `PrimalSpace B`;
* `CubicNewtonStep` in `Definition_4_3_6`, the source-facing owner of the chosen cubic Newton map;
* `CubicNewtonStep.firstOrderOptimalityCondition` in `Definition_4_3_6`, the owner-level
  first-order optimality theorem for the chosen cubic Newton point.

Best owner abstraction:
* source-facing: the cubic Newton step `step : CubicNewtonStep B f M`;
* core/canonical: the owners `((f : PrimalSpace B → ℝ) ∈ C22[Mf])` and
  `CubicNewtonStep B f M`;
* bridge/view: the gradient remainder estimate along `step x - x` and the scalar optimality
  identity obtained from the minimizing property of `step`.

Primitive data:
* the bilinear form `B`;
* the positive-definite quadratic data of `B`;
* the canonical Hessian-Lipschitz owner instance on `PrimalSpace B`;
* the chosen cubic Newton step `step`.

Derived API:
* the owner gradient Taylor remainder bound `HasLipschitzContinuousHessian.gradient_deviation_le`
  between arbitrary points `x` and `y`;
* the scalar pairing of the owner-level first-order optimality condition with the displacement
  `step x - x`;
* the lower bounds of Lemma 4.3.3 built from those owner theorems.

The previous file stored the remainder estimate and scalar optimality relation as separate local
`Prop` wrappers, and then specialized the remainder theorem directly to `y = step x`. Those were
not new mathematical owners; they were derived API that should sit on the existing owners
`HasLipschitzContinuousHessian` and `CubicNewtonStep`. This refinement deletes the duplicate
wrapper layer and uses the Chapter 1 remainder theorem together with the owner-level first-order
optimality theorem on `CubicNewtonStep` directly.
-/

section

variable {B : BilinForm ℝ E} {Mf : NNReal} {f : E → ℝ}
variable [Fact B.toQuadraticMap.PosDef]
variable (hf : (f : PrimalSpace B → ℝ) ∈ C22[Mf])

-- Proof sketch: apply the owner gradient remainder estimate at `(x, step x)`, combine it with
-- the scalar identity obtained by pairing
-- `step.firstOrderOptimalityCondition x`,
-- with `step x - x`,
-- expand `r[step](x) = ‖step x - x‖[B]`, and rearrange the resulting quadratic inequality in
-- the remainder term.
/-- Lemma 4.3.3 (1): for positive regularization `M`, the pairing of the gradient at the cubic
Newton point with the displacement `x - T_M(x)` is bounded below by the reciprocal-residual
dual-gradient term plus the cubic correction `((M² - M_f²) / (4M)) r_M(x)^3`. -/
lemma cubicNewtonStep_dualPairing_lower_bound
    {M : ℝ} (step : CubicNewtonStep B f M)
    (hM : 0 < M)
    (x : E) :
    let g := fderiv ℝ f (step x)
    g (x - step x) ≥
      (1 / (M * r[step](x))) *
          ‖g‖[B,*] ^ (2 : ℕ) +
        ((M ^ (2 : ℕ) - (Mf : ℝ) ^ (2 : ℕ)) / (4 * M)) *
          (r[step](x)) ^ (3 : ℕ) := sorry

-- Proof sketch: start from `cubicNewtonStep_dualPairing_lower_bound`, use the hypothesis
-- `M ≥ M_f / σ` in the equivalent form `M_f ≤ σ M`, and simplify the cubic coefficient
-- `((M² - M_f²) / (4M))` to `((1 - σ²) / 4) M`.
/-- Lemma 4.3.3 (2): if `σ ∈ (0, 1]` and `M ≥ M_f / σ`, then the cubic correction in the lower
bound can be replaced by `((1 - σ²) / 4) M r_M(x)^3`; the positive-regime hypothesis `0 < M`
keeps the reciprocal-residual term in its textbook form. -/
lemma cubicNewtonStep_dualPairing_lower_bound_of_sigma
    {M : ℝ} (step : CubicNewtonStep B f M)
    {σ : ℝ}
    (hσ : σ ∈ Set.Ioc (0 : ℝ) 1)
    (hMσ : M ≥ (1 / σ) * (Mf : ℝ))
    (hM : 0 < M)
    (x : E) :
    let g := fderiv ℝ f (step x)
    g (x - step x) ≥
      (1 / (M * r[step](x))) *
          ‖g‖[B,*] ^ (2 : ℕ) +
        ((1 - σ ^ (2 : ℕ)) / 4 : ℝ) * M * (r[step](x)) ^ (3 : ℕ) := sorry

end

/-! ### Proposition_4_3_3 (from Chap04) -/
noncomputable section

open LinearMap (BilinForm)
open scoped Gradient CubicNewtonStepNotation

universe u

variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/- Proposition 4.3.3 lies in the symmetric bilinear-form-induced cubic-Newton first-order
optimality domain.

Sampled owner declarations:
* `LinearMap.BilinForm.primalSeminorm` in `Definition_4_3_4`, the chapter owner for the
  `B`-induced norm `‖·‖[B]`;
* `LinearMap.BilinForm.IsSymm` in `Definition_4_2_5`, the canonical symmetry owner needed to
  expose the cubic derivative as the explicit covector `B (T_M(x) - x)`;
* `LinearMap.BilinForm.PrimalSpace` in `Definition_4_2_9`, the intrinsic owner for the
  `B`-geometry carried by Chapter 4.3;
* `cubicNewtonModel` in `Definition_4_3_6`, the source cubic model minimized by `T_M(x)`;
* `CubicNewtonStep.firstOrderOptimalityCondition` in `Definition_4_3_6`, the core owner-level
  stationarity theorem `fderiv ℝ (cubicNewtonModel B f M x) (T_M x) = 0`;
* `hessian_isSelfAdjoint_of_contDiffAt` in `Text_4_2_3`, the chapter bridge turning a `C²`
  hypothesis into the self-adjointness needed to rewrite the Hessian derivative term.

Best owner abstraction:
* source-facing: the explicit first-order optimality equation `(4.3.12)` for `T_M(x)`;
* core/canonical: `CubicNewtonStep B f M` together with
  `CubicNewtonStep.firstOrderOptimalityCondition`;
* bridge/view: the dual-valued expansion of that derivative-zero statement, where the quadratic
  term is written with `hessian f x` only after a self-adjointness bridge, and the cubic term is
  written as `((M / 2) * r_M(x)) • B (T_M(x) - x)` only after a symmetry bridge for `B`.

Primitive data:
* the bilinear form `B`;
* the objective `f`;
* the regularization parameter `M`;
* the chosen cubic Newton step `step : CubicNewtonStep B f M`;
* the symmetry hypothesis `B.IsSymm`;
* the self-adjointness hypothesis `IsSelfAdjoint (hessian f x)`.

Derived API:
* the residual `r[step](x) = ‖step x - x‖[B]`;
* the owner derivative-zero statement for the cubic Newton model;
* the source-facing optimality equation below, obtained by expanding that owner theorem;
* the `C²` companion theorem obtained by the canonical bridge
  `hessian_isSelfAdjoint_of_contDiffAt`.

This proposition is therefore a source-facing bridge theorem on the existing Chapter 4.3 owner
`CubicNewtonStep`; it must not be collapsed to the ambient-norm Chapter 4.2 owner
`CubicRegularizationMapping`. -/

namespace CubicNewtonStep

variable {B : BilinForm ℝ E} [Fact B.toQuadraticMap.PosDef] {f : E → ℝ} {M : ℝ}

/-- Proposition 4.3.3 in primitive bridge form: if `B` is symmetric and `hessian f x` is
self-adjoint, then the cubic Newton point `T_M(x)` satisfies the source first-order optimality
condition `(4.3.12)`, written as an equality of linear functionals so the explicit Chapter 4.3
covector `B (T_M(x) - x)` remains visible. -/
theorem firstOrderOptimalityCondition_toDual_of_isSelfAdjoint
    (step : CubicNewtonStep B f M) (x : E)
    (hSymm : B.IsSymm) (hH : IsSelfAdjoint (hessian f x)) :
    InnerProductSpace.toDual ℝ E (∇ f x + hessian f x (step x - x)) +
        ((M / 2 : ℝ) * r[step](x)) • B (step x - x) = 0 := by
  sorry

/-- Proposition 4.3.3: if `f` is `C²` at `x` and `B` is symmetric, then the cubic Newton point
`T_M(x)` satisfies the source first-order optimality condition `(4.3.12)`. This is the Chapter
4.3 `C²` bridge obtained from
`firstOrderOptimalityCondition_toDual_of_isSelfAdjoint` via
`hessian_isSelfAdjoint_of_contDiffAt`. -/
theorem firstOrderOptimalityCondition_toDual
    (step : CubicNewtonStep B f M) (x : E)
    (hSymm : B.IsSymm) (hf : ContDiffAt ℝ 2 f x) :
    InnerProductSpace.toDual ℝ E (∇ f x + hessian f x (step x - x)) +
        ((M / 2 : ℝ) * r[step](x)) • B (step x - x) = 0 := by
  exact step.firstOrderOptimalityCondition_toDual_of_isSelfAdjoint x hSymm
    (hessian_isSelfAdjoint_of_contDiffAt f x hf)

end CubicNewtonStep

/-! ### Definition_4_3_4 (from Chap04) -/
noncomputable section

open Module LinearMap

universe u

/- Definition 4.3.4 lies in the bilinear-form / induced-seminorm / finite-dimensional duality
domain.

Sampled owner-style declarations:
- project `Seminorm.IsNorm`
- project `Seminorm.dualNorm`
- project `Seminorm.primalDualOperatorNorm`
- `QuadraticMap.PosDef`
- `QuadraticMap.associated`
- `QuadraticMap.associated_eq_self_apply`
- `LinearMap.BilinForm.toDual`
- `LinearMap.BilinForm.apply_toDual_symm_apply`

Best owner abstraction:
- source-facing: the dual norm induced by the positive-definite quadratic data of a bilinear form
- core/canonical: the induced seminorm owner `primalSeminorm B : Seminorm ℝ E`, defined from
  `B.toQuadraticMap` and its canonical associated symmetric bilinear form
- bridge/view: the finite-dimensional dual equivalence `B.toDual`

Primitive data:
- `B : BilinForm ℝ E`
- `hPos : B.toQuadraticMap.PosDef`

Derived API:
- the pointwise formula for the induced seminorm
- in finite dimension, the derived source-facing dual norm on `E⋆`
- positive-definite nondegeneracy of `B`
- the canonical preimage map `dualPreimage hPos : E⋆ → E`, i.e. the source-facing `B⁻¹`
  applied to a covector
- under symmetry, the `B.toDual` bridge from the dual norm to the textbook inverse-pairing
  formula

The primal and support-function owners depend only on the positive-definite quadratic data
`B.toQuadraticMap`; symmetry is retained only for the later `B.toDual` bridge theorem, where the
inverse-pairing formula genuinely needs a symmetric representative. The primal owner is exposed as
a reusable `Seminorm` rather than a parallel function-valued wrapper.
-/

namespace LinearMap.BilinForm

variable {E : Type u} [AddCommGroup E] [Module ℝ E]

/-- Definition 4.3.4 in owner form: the positive-definite quadratic data of `B` induce the
canonical seminorm `x ↦ ⟪Bx, x⟫^(1/2)`. -/
def primalSeminorm (B : LinearMap.BilinForm ℝ E) (hPos : B.toQuadraticMap.PosDef) :
    Seminorm ℝ E :=
  Seminorm.of (fun x ↦ Real.sqrt (B.toQuadraticMap x))
    (fun x y ↦ by
      let A : LinearMap.BilinForm ℝ E := B.toQuadraticMap.associated
      have hA_symm : A.IsSymm := by
        exact ⟨QuadraticMap.associated_isSymm ℝ B.toQuadraticMap⟩
      have hA_linear : LinearMap.IsSymm A := LinearMap.BilinForm.isSymm_iff.1 hA_symm
      have hdiag : ∀ z : E, A z z = B.toQuadraticMap z := fun z ↦ by
        simpa [A] using QuadraticMap.associated_eq_self_apply ℝ B.toQuadraticMap z
      have hs : ∀ z : E, 0 ≤ A z z := fun z ↦ by
        rw [hdiag z]
        exact hPos.nonneg z
      have hxy_sq : (A x y) ^ 2 ≤ (Real.sqrt (A x x) * Real.sqrt (A y y)) ^ 2 := by
        have hbase : (A x y) ^ 2 ≤ (A x x) * (A y y) := A.apply_sq_le_of_symm hs hA_linear x y
        nlinarith [hbase, Real.sq_sqrt (hs x), Real.sq_sqrt (hs y)]
      have hxy : A x y ≤ Real.sqrt (A x x) * Real.sqrt (A y y) := by
        exact le_of_sq_le_sq hxy_sq (by positivity)
      have hyx : A y x ≤ Real.sqrt (A x x) * Real.sqrt (A y y) := by
        calc
          A y x = A x y := hA_symm.eq _ _
          _ ≤ Real.sqrt (A x x) * Real.sqrt (A y y) := hxy
      have hsum : A x y + A y x ≤ 2 * (Real.sqrt (A x x) * Real.sqrt (A y y)) := by
        nlinarith [hxy, hyx]
      have hsq :
          A (x + y) (x + y) ≤
            (Real.sqrt (A x x) + Real.sqrt (A y y)) *
              (Real.sqrt (A x x) + Real.sqrt (A y y)) := by
        calc
          A (x + y) (x + y) = A x x + (A x y + A y x) + A y y := by
            simp [map_add, add_left_comm, add_comm]
          _ ≤ A x x + 2 * (Real.sqrt (A x x) * Real.sqrt (A y y)) + A y y := by
            gcongr
          _ = (Real.sqrt (A x x) + Real.sqrt (A y y)) *
                (Real.sqrt (A x x) + Real.sqrt (A y y)) := by
            nlinarith [Real.sq_sqrt (hs x), Real.sq_sqrt (hs y)]
      have htri :
          Real.sqrt (A (x + y) (x + y)) ≤ Real.sqrt (A x x) + Real.sqrt (A y y) := by
        apply nonneg_le_nonneg_of_sq_le_sq
        · exact add_nonneg (Real.sqrt_nonneg _) (Real.sqrt_nonneg _)
        · nlinarith [hsq, Real.sq_sqrt (hs (x + y))]
      simpa only [hdiag (x + y), hdiag x, hdiag y] using htri)
    (fun a x ↦ by
      by_cases ha : a = 0
      · simp [ha]
      have hsx : 0 ≤ B.toQuadraticMap x := hPos.nonneg x
      have hsax : 0 ≤ B.toQuadraticMap (a • x) := hPos.nonneg (a • x)
      refine (Real.sqrt_eq_iff_eq_sq hsax (by positivity)).2 ?_
      have habs : a * a = ‖a‖ * ‖a‖ := by
        calc
          a * a = a ^ 2 := by ring
          _ = ‖a‖ ^ 2 := (sq_abs a).symm
          _ = ‖a‖ * ‖a‖ := by ring
      have hsqrt :
          Real.sqrt (B.toQuadraticMap x) * Real.sqrt (B.toQuadraticMap x) = B.toQuadraticMap x := by
        simpa [sq] using Real.sq_sqrt hsx
      have hsmul :
          B.toQuadraticMap (a • x) = (a * a) * B.toQuadraticMap x := by
        simp [BilinMap.toQuadraticMap_apply, smul_eq_mul, mul_assoc]
      calc
        B.toQuadraticMap (a • x) = (a * a) * B.toQuadraticMap x := hsmul
        _ = (‖a‖ * ‖a‖) * B.toQuadraticMap x := by rw [habs]
        _ = ‖a‖ * ‖a‖ * (Real.sqrt (B.toQuadraticMap x) * Real.sqrt (B.toQuadraticMap x)) := by
          rw [hsqrt]
        _ = ‖a‖ * Real.sqrt (B.toQuadraticMap x) * (‖a‖ * Real.sqrt (B.toQuadraticMap x)) := by
          ring
        _ = ‖a‖ * (fun y ↦ Real.sqrt (B.toQuadraticMap y)) x *
              (‖a‖ * (fun y ↦ Real.sqrt (B.toQuadraticMap y)) x) := by
          rfl
        _ = (‖a‖ * (fun y ↦ Real.sqrt (B.toQuadraticMap y)) x) ^ 2 := by
          ring)

namespace BInducedNorm

/- Source-facing Lean notation for the primal norm induced by the positive-definite quadratic data
of `B`. -/
scoped notation:max "‖" x "‖[" B " | " hPos "]" =>
  LinearMap.BilinForm.primalSeminorm B hPos x

/- Instance-driven shorthand for the primal norm when positive-definiteness is already available
as a local `Fact` instance. -/
scoped notation:max "‖" x "‖[" B "]" =>
  LinearMap.BilinForm.primalSeminorm B Fact.out x

end BInducedNorm

open scoped BInducedNorm

/-- Evaluating `primalSeminorm B` recovers the formula `√(⟪Bx, x⟫)`. -/
@[simp] theorem primalSeminorm_apply (B : LinearMap.BilinForm ℝ E)
    (hPos : B.toQuadraticMap.PosDef) (x : E) :
    ‖x‖[B | hPos] = Real.sqrt (B x x) := by
  rfl

/-- The positive-definite bilinear-form-induced seminorm is separated. -/
instance primalSeminorm_isNorm (B : LinearMap.BilinForm ℝ E) (hPos : B.toQuadraticMap.PosDef) :
    Seminorm.IsNorm (primalSeminorm B hPos) where
  eq_zero_of_map_eq_zero {x} hx := by
    have hsx : 0 ≤ B x x := by
      simpa [BilinMap.toQuadraticMap_apply] using hPos.nonneg x
    have hxx : B x x = 0 := by
      exact (Real.sqrt_eq_zero hsx).mp (by simpa [primalSeminorm_apply] using hx)
    exact hPos.anisotropic x hxx

/-- A bilinear form whose associated quadratic map is positive definite is nondegenerate. -/
theorem nondegenerate_of_posDef (B : LinearMap.BilinForm ℝ E) (hB : B.toQuadraticMap.PosDef) :
    B.Nondegenerate := by
  let B' : LinearMap.BilinForm ℝ E := B.flip
  refine ⟨separatingLeft_of_anisotropic hB.anisotropic, ?_⟩
  intro x hx
  have hflip : B'.toQuadraticMap.Anisotropic := by
    intro y hy
    apply hB.anisotropic y
    simpa [BilinMap.toQuadraticMap_apply] using hy
  exact separatingLeft_of_anisotropic hflip x hx

section

/-- Definition 4.3.4: in finite dimension, the dual norm induced by the positive-definite
quadratic data of `B` is the support function of the primal `B`-unit ball. The finite-dimensional
hypothesis is the source-facing owner layer guaranteeing this support value is an honest real
supremum. -/
def dualNorm [FiniteDimensional ℝ E] (B : LinearMap.BilinForm ℝ E)
    (hPos : B.toQuadraticMap.PosDef) :
    Dual ℝ E → ℝ :=
  fun g ↦ sSup ((fun x : E ↦ g x) '' {x | ‖x‖[B | hPos] ≤ 1})

namespace BInducedNorm

/- Source-facing Lean notation for the bilinear-form dual norm, written so it applies both to
linear dual vectors and to continuous dual vectors via the canonical coercion to `Module.Dual`. -/
scoped notation:max "‖" g "‖*[" B " | " hPos "]" =>
  LinearMap.BilinForm.dualNorm B hPos ((g : _ →ₗ[ℝ] ℝ))

/- Instance-driven shorthand for the bilinear-form dual norm when positive-definiteness is already
available as a local `Fact` instance. -/
scoped notation:max "‖" g "‖[" B ",*]" =>
  LinearMap.BilinForm.dualNorm B Fact.out ((g : _ →ₗ[ℝ] ℝ))

end BInducedNorm

/-- Expanding `dualNorm B` gives the support-function formula over the primal `B`-unit ball. -/
theorem dualNorm_eq_sSup_primalUnitBall [FiniteDimensional ℝ E]
    (B : LinearMap.BilinForm ℝ E) (hPos : B.toQuadraticMap.PosDef) (g : Dual ℝ E) :
    ‖g‖*[B | hPos] = sSup ((fun x : E ↦ g x) '' {x | ‖x‖[B | hPos] ≤ 1}) := rfl

section

variable {F : Type u} [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F]

/-- On a finite-dimensional real inner-product space, the Chapter 2 dual norm of the primal
seminorm induced by `B` agrees with the Chapter 4 bilinear-form dual norm after passing to the
canonical dual vector `InnerProductSpace.toDual ℝ F x`. -/
theorem seminormDualNorm_eq_dualNorm_toDual [FiniteDimensional ℝ F]
    (B : LinearMap.BilinForm ℝ F) (hPos : B.toQuadraticMap.PosDef) (x : F) :
    Seminorm.dualNorm (B.primalSeminorm hPos) x =
      B.dualNorm hPos (InnerProductSpace.toDual ℝ F x).toLinearMap := by
  rw [Seminorm.dualNorm_apply, dualNorm_eq_sSup_primalUnitBall]
  simp [InnerProductSpace.toDual_apply_apply]

end

/-- The vector `B⁻¹ g`, characterized by the pairing identity `B (B.dualPreimage hPos g) x = g x`.
This is the preimage of `g` under the finite-dimensional equivalence `B.toDual` supplied by
positive-definiteness. -/
abbrev dualPreimage [FiniteDimensional ℝ E] (B : LinearMap.BilinForm ℝ E)
    (hPos : B.toQuadraticMap.PosDef)
    (g : Dual ℝ E) : E :=
  (B.toDual (B.nondegenerate_of_posDef hPos)).symm g

/-- The canonical preimage `B.dualPreimage hPos g` evaluates against `B` to recover `g`. -/
@[simp] theorem dualPreimage_apply [FiniteDimensional ℝ E] (B : LinearMap.BilinForm ℝ E)
    (hPos : B.toQuadraticMap.PosDef) (g : Dual ℝ E) (x : E) :
    B (B.dualPreimage hPos g) x = g x := by
  rw [dualPreimage]
  exact apply_toDual_symm_apply g x

/-- Under symmetry and positive-definiteness, the finite-dimensional `B`-dual norm agrees with the
textbook formula `g ↦ ⟪g, B⁻¹ g⟫^(1/2)`, written through the canonical bridge
`B.dualPreimage hPos g`. -/
theorem dualNorm_apply [FiniteDimensional ℝ E] (B : LinearMap.BilinForm ℝ E) (hSymm : B.IsSymm)
    (hPos : B.toQuadraticMap.PosDef) (g : Dual ℝ E) :
    ‖g‖*[B | hPos] = Real.sqrt (g (B.dualPreimage hPos g)) := sorry

end

end LinearMap.BilinForm
