import AchimKlenkeLean.Items.Chap19.Definition_19_13

open scoped BigOperators

universe u

attribute [local instance] Classical.propDecidable

noncomputable section

namespace ProbabilityTheory

variable {E : Type u}

/- The source-facing Ohm-law current for a resistance function `R` and potential `u`. Its
diagonal is set to zero definitionally, matching the antisymmetry already required of flows. -/
def ohmicCurrent (R : E → E → ℝ) (u : E → ℝ) : E → E → ℝ :=
  by
    classical
    exact fun x y ↦ if x = y then 0 else (u x - u y) / R x y

/-- On distinct vertices, `ohmicCurrent R u` is given by Ohm's law. -/
theorem ohmicCurrent_apply_of_ne (R : E → E → ℝ) (u : E → ℝ) {x y : E} (hxy : x ≠ y) :
    ohmicCurrent R u x y = (u x - u y) / R x y := by
  simp [ohmicCurrent, hxy]

/-- On the diagonal, `ohmicCurrent R u` vanishes. -/
theorem ohmicCurrent_apply_self (R : E → E → ℝ) (u : E → ℝ) (x : E) :
    ohmicCurrent R u x x = 0 := by
  simp [ohmicCurrent]

section

variable [Fintype E]

/-- Definition 19.14: a flow `I` on `E \ A` is a current flow with resistance function `R` if it
is antisymmetric, satisfies Kirchhoff's node law on `E \ A`, has zero total net flow across `A`,
and there exists a potential `u : E → ℝ` such that Ohm's rule
`I x y = (u x - u y) / R x y` holds for every distinct pair of vertices `x ≠ y`. -/
class IsCurrentFlow (R : E → E → ℝ) (A : Set E) (I : E → E → ℝ) : Prop
    extends IsFlowOutside A I where
  /-- There exists an electrical potential whose potential differences generate the flow by
  Ohm's rule. -/
  eq_ohmicCurrent : ∃ u : E → ℝ, I = ohmicCurrent R u

/-- A current flow is generated by a potential satisfying Ohm's law on distinct vertices. -/
theorem IsCurrentFlow.exists_potential {R : E → E → ℝ} {A : Set E} {I : E → E → ℝ}
    (hI : IsCurrentFlow R A I) :
    ∃ u : E → ℝ, ∀ ⦃x y : E⦄, x ≠ y → I x y = (u x - u y) / R x y := by
  rcases hI.eq_ohmicCurrent with ⟨u, rfl⟩
  exact ⟨u, by
    intro x y hxy
    exact ohmicCurrent_apply_of_ne R u hxy⟩

/-- A flow outside `A` becomes a current flow as soon as it is given by an Ohm-law current. -/
theorem IsFlowOutside.isCurrentFlow {R : E → E → ℝ} {A : Set E} {I : E → E → ℝ}
    (hI : IsFlowOutside A I) {u : E → ℝ} (hOhm : I = ohmicCurrent R u) :
    IsCurrentFlow R A I where
  toIsFlowOutside := hI
  eq_ohmicCurrent := ⟨u, hOhm⟩

/-- A flow outside `A` is already a current flow once Ohm's law holds on all distinct pairs. The
diagonal case then follows from antisymmetry. -/
theorem IsFlowOutside.isCurrentFlow_of_ohmicCurrent_apply
    {R : E → E → ℝ} {A : Set E} {I : E → E → ℝ} (hI : IsFlowOutside A I) {u : E → ℝ}
    (hOhm : ∀ ⦃x y : E⦄, x ≠ y → I x y = (u x - u y) / R x y) :
    IsCurrentFlow R A I := by
  refine hI.isCurrentFlow <| by
    funext x y
    by_cases hxy : x = y
    · subst y
      have hdiag : I x x = 0 := by
        have hantisymm := hI.antisymm x x
        linarith
      simpa [ohmicCurrent] using hdiag
    · simpa [ohmicCurrent, hxy] using hOhm hxy

/-- The zero flow is a current flow for every resistance function and every boundary set. -/
instance instIsCurrentFlowZero (R : E → E → ℝ) (A : Set E) :
    IsCurrentFlow R A (fun _ _ : E ↦ 0) where
  toIsFlowOutside := instIsFlowOutsideZero A
  eq_ohmicCurrent := ⟨fun _ ↦ 0, by
    funext x y
    by_cases hxy : x = y <;> simp [ohmicCurrent, hxy]⟩

end

end ProbabilityTheory
