import Mathlib
import BauschkeLean.Chap06.Definition_6_38

-- Declarations for this item will be appended below by the statement pipeline.

open scoped InnerProductSpace Pointwise

universe u

section

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- Helper for Example 6.43: translating an affine subspace by a point in it identifies the
translate with the direction subspace. -/
private lemma affineSubspace_sub_singleton_eq_direction
    (C : AffineSubspace ℝ H) {x : H} (hx : x ∈ (C : Set H)) :
    ((C : Set H) - ({x} : Set H)) = (C.direction : Set H) := by
  -- Rewrite the translate as the right-vsub image provided by the affine-subspace API.
  simpa [vsub_eq_sub] using
    (AffineSubspace.coe_direction_eq_vsub_set_right (s := C) hx).symm

/-- Helper for Example 6.43: the cone generated by a linear subspace is the subspace itself. -/
private lemma cone_eq_self_of_submodule (V : Submodule ℝ H) :
    Set.cone (V : Set H) = (V : Set H) := by
  ext y
  constructor
  · intro hy
    -- The convex-cone hull is contained in any convex cone containing the subspace.
    exact ConvexCone.hull_min (C := V.toConvexCone) (fun z hz ↦ hz) hy
  · intro hy
    -- Every vector of the subspace lies in the cone it generates.
    exact ConvexCone.subset_hull hy

/-- Helper for Example 6.43: on a submodule, the normal-cone support inequality is equivalent to
membership in the orthogonal complement. -/
private lemma innerSupremumOn_le_zero_iff_mem_orthogonal_of_submodule
    (V : Submodule ℝ H) {u : H} :
    innerSupremumOn (V : Set H) u ≤ 0 ↔ u ∈ Vᗮ := by
  constructor
  · intro hu
    -- Compare the support value on `V` with the singleton `{0}` to get pointwise bounds.
    have hsep : innerSupremumOn (V : Set H) u ≤ innerInfimumOn ({0} : Set H) u := by
      simpa using hu
    have hpoint :=
      (innerSupremumOn_le_innerInfimumOn_iff_forall_inner_le
        (V : Set H) ({0} : Set H) u).mp hsep
    rw [V.mem_orthogonal u]
    intro v hv
    -- Testing the pointwise inequality on `v` and `-v` forces the inner product to vanish.
    have h_nonpos : ⟪v, u⟫_ℝ ≤ 0 := by
      simpa using hpoint v hv 0 (by simp)
    have h_neg_nonpos : ⟪-v, u⟫_ℝ ≤ 0 := by
      simpa using hpoint (-v) (V.neg_mem hv) 0 (by simp)
    have h_nonneg : 0 ≤ ⟪v, u⟫_ℝ := by
      simpa [inner_neg_left] using h_neg_nonpos
    linarith
  · intro hu
    -- Orthogonality makes every inner product on the subspace equal to the value at `0`.
    have hpoint : ∀ v ∈ (V : Set H), ∀ z ∈ ({0} : Set H), ⟪v, u⟫_ℝ ≤ ⟪z, u⟫_ℝ := by
      intro v hv z hz
      have hz0 : z = 0 := by
        simpa using hz
      subst z
      have h_zero : ⟪v, u⟫_ℝ = 0 := (V.mem_orthogonal u).mp hu v hv
      simp [h_zero]
    have hsep : innerSupremumOn (V : Set H) u ≤ innerInfimumOn ({0} : Set H) u :=
      (innerSupremumOn_le_innerInfimumOn_iff_forall_inner_le
        (V : Set H) ({0} : Set H) u).mpr hpoint
    simpa using hsep

-- Proof sketch: unfold `Set.tangentCone` at a point of the affine subspace, rewrite the translate
-- `C - x` as the parallel subspace `C.direction`, and identify the cone generated by a linear
-- subspace with the subspace itself before taking closure.
/-- Example 6.43 (1): if `x ∈ C`, then the tangent cone to the affine subspace `C` is the closure
of the parallel linear subspace `V = C - C`, expressed in Lean as `closure (C.direction : Set H)`.
-/
theorem tangentCone_affineSubspace_eq_closure_direction_of_mem
    (C : AffineSubspace ℝ H) {x : H} (hx : x ∈ (C : Set H)) :
    Set.tangentCone (C : Set H) x = closure (C.direction : Set H) := by
  -- Rewrite the tangent cone at `x` in terms of the translate `C - {x}`.
  rw [Set.tangentCone_of_mem hx, affineSubspace_sub_singleton_eq_direction (C := C) hx]
  -- The translate is a linear subspace, so its generated cone is already itself.
  rw [cone_eq_self_of_submodule C.direction]

-- Proof sketch: apply the general theorem that the tangent cone is empty away from the base set.
/-- Example 6.43 (2): if `x ∉ C`, then the tangent cone to the affine subspace `C` at `x` is
empty. -/
theorem tangentCone_affineSubspace_eq_empty_of_not_mem
    (C : AffineSubspace ℝ H) {x : H} (hx : x ∉ (C : Set H)) :
    Set.tangentCone (C : Set H) x = ∅ := by
  -- Away from the affine subspace, the general tangent-cone formula is empty.
  simpa using Set.tangentCone_of_not_mem hx

-- Proof sketch: unfold `Set.normalCone` at a point of the affine subspace, rewrite the translate
-- `C - x` as the parallel subspace `C.direction`, and identify the negative polar of a linear
-- subspace with its orthogonal complement.
/-- Example 6.43 (3): if `x ∈ C`, then the normal cone to the affine subspace `C` is the
orthogonal complement of the parallel linear subspace `V = C - C`, expressed in Lean as
`C.directionᗮ`. -/
theorem normalCone_affineSubspace_eq_direction_orthogonal_of_mem
    (C : AffineSubspace ℝ H) {x : H} (hx : x ∈ (C : Set H)) :
    Set.normalCone (C : Set H) x = (C.directionᗮ : Set H) := by
  -- Rewrite the normal cone at `x` as the support inequality on the translate `C - {x}`.
  rw [Set.normalCone_of_mem hx, affineSubspace_sub_singleton_eq_direction (C := C) hx]
  -- For a submodule, that support inequality is exactly orthogonality.
  ext u
  exact innerSupremumOn_le_zero_iff_mem_orthogonal_of_submodule C.direction

-- Proof sketch: apply the general theorem that the normal cone is empty away from the base set.
/-- Example 6.43 (4): if `x ∉ C`, then the normal cone to the affine subspace `C` at `x` is
empty. -/
theorem normalCone_affineSubspace_eq_empty_of_not_mem
    (C : AffineSubspace ℝ H) {x : H} (hx : x ∉ (C : Set H)) :
    Set.normalCone (C : Set H) x = ∅ := by
  -- Away from the affine subspace, the general normal-cone formula is empty.
  simpa using Set.normalCone_of_not_mem hx

end
