name = "stacks_project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["stacks_project"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.longLine = false
weak.linter.style.emptyLine = false
weak.linter.style.cdot = false
weak.linter.style.maxHeartbeats = false
weak.linter.unnecessarySimpa = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "52cc3b456983d90c47ffb6c14bfa0979d43d160e"

[[lean_lib]]
name = "stacks_project"
srcDir = "."

[[lean_lib]]
name = "P2512_19197"

[[lean_lib]]
name = "stacks_proof"
