import Books.FirstOrderMethodsInOptimization_Beck_2017.Chap14.Algorithm_14_1
import Books.FirstOrderMethodsInOptimization_Beck_2017.Chap14.Theorem_14_6

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

universe u

section

variable {p : ℕ} {Ei : Fin p → Type u}
variable [∀ i, NormedAddCommGroup (Ei i)] [∀ i, NormedSpace ℝ (Ei i)]

/- `prompt_add/` is absent in this workspace, so the statement design is sampled directly from the
nearby Chapter 11 and Chapter 14 files.

This item is `source-facing`: it is the existential-radius corollary of the Chapter 14
`O(1 / k)` convergence-rate theorem for the objective gap along an alternating-minimization
trajectory under Assumption 14.10. The relevant live owners are:
- `composite_model_objective f.toEReal (separableSum g)` from Chapter 10/Chapter 6 for the
  objective `F(x) = f(x) + ∑ i, g_i(x_i)`;
- `IsAlternatingMinimizationConvexRateProblem` for Assumption 14.10;
- the Algorithm 14.1 trajectory owner `is_alternating_minimization_trajectory` for the generated
  sequence; and
- an explicit-radius rate certificate supplied to the theorem below.

The latest canonical Theorem 14.6 retains Assumption 14.10 but no longer exports the old
explicit-radius rate theorem.  Keeping that missing result as an explicit premise makes the
migration boundary visible while this file supplies the canonical existential bridge from
Assumption 14.10 to the required initial-sublevel radius witness. -/

section

variable {f : ((i : Fin p) → Ei i) → ℝ} {g : ∀ i : Fin p, Ei i → EReal}
variable {XStar : Set ((i : Fin p) → Ei i)} {FOpt : ℝ} {Lf : NNReal}
variable [IsAlternatingMinimizationConvexRateProblem f g XStar FOpt Lf]

local notation "F" => composite_model_objective f.toEReal (separableSum g)

-- Proof sketch: choose one positive level `α` above the initial value `F(x^0)`, extract the
-- corresponding radius witness from Assumption 14.10 once and for all, and then apply the
-- supplied explicit-radius certificate uniformly in `k`.
/-- Theorem 14.7: if Assumption 14.10 holds and `x` is generated by the alternating-minimization
method for `F(x) = f(x) + ∑ i, g_i(x_i)`, then there exists a radius `R = R_{F(x^0)}` controlling
the initial sublevel set `{y | F(y) ≤ F(x^0)}` such that, for every `k ≥ 2`, the
objective gap satisfies
`F(x^k) - F_opt ≤ max {((1 / 2)^((k - 1) / 2)) (F(x^0) - F_opt), 8 L_f p^2 R^2 / (k - 1)}`. -/
theorem alternating_minimization_objective_gap_le_max_geometric_or_sublinear
    (x : ℕ → (i : Fin p) → Ei i) (htraj : is_alternating_minimization_trajectory F x)
    (hExplicitRadiusRate :
      ∀ (R : PosReal),
        (∀ ⦃y xStar : (i : Fin p) → Ei i⦄,
          F y ≤ F (x 0) →
          xStar ∈ XStar →
          ‖y - xStar‖ ≤ (R : ℝ)) →
        ∀ k : ℕ,
          2 ≤ k →
            (F (x k)).toReal - FOpt ≤
              max
                (((1 / 2 : ℝ) ^ (((k - 1 : ℕ) : ℝ) / 2)) *
                  ((F (x 0)).toReal - FOpt))
                ((8 * (Lf : ℝ) * (p : ℝ) ^ (2 : ℕ) * (R : ℝ) ^ (2 : ℕ)) /
                  ((k - 1 : ℕ) : ℝ))) :
    ∃ R : PosReal,
      (∀ ⦃y xStar : (i : Fin p) → Ei i⦄,
        F y ≤ F (x 0) →
        xStar ∈ XStar →
        ‖y - xStar‖ ≤ (R : ℝ)) ∧
      ∀ k : ℕ,
        2 ≤ k →
          (F (x k)).toReal - FOpt ≤
            max
              (((1 / 2 : ℝ) ^ (((k - 1 : ℕ) : ℝ) / 2)) *
                ((F (x 0)).toReal - FOpt))
              ((8 * (Lf : ℝ) * (p : ℝ) ^ (2 : ℕ) * (R : ℝ) ^ (2 : ℕ)) /
                ((k - 1 : ℕ) : ℝ)) := by
  let α : PosReal := ⟨max (F (x 0)).toReal 1, by
    change 0 < max (F (x 0)).toReal 1
    exact lt_of_lt_of_le zero_lt_one (le_max_right _ _)⟩
  have hx0_dom : x 0 ∈ effective_domain F := is_alternating_minimization_trajectory_zero htraj
  have hx0_top : F (x 0) ≠ ⊤ := (mem_effective_domain.mp hx0_dom).ne
  have hproblem : IsAlternatingMinimizationConvexRateProblem f g XStar FOpt Lf := inferInstance
  have hx0_le_α : F (x 0) ≤ ((α : ℝ) : EReal) := by
    calc
      F (x 0) ≤ (((F (x 0)).toReal : ℝ) : EReal) := EReal.le_coe_toReal hx0_top
      _ ≤ ((α : ℝ) : EReal) := by
        exact_mod_cast (le_max_left (F (x 0)).toReal (1 : ℝ))
  rcases hproblem.bounded_initial_sublevel_distance_to_each_optimal_point hx0_le_α with ⟨R, hR⟩
  have hR' :
      ∀ ⦃y xStar : (i : Fin p) → Ei i⦄,
        F y ≤ F (x 0) → xStar ∈ XStar → ‖y - xStar‖ ≤ (R : ℝ) :=
    fun {_ _} hy hxStar ↦ hR hy hxStar
  refine ⟨R, hR', ?_⟩
  intro k hk
  exact hExplicitRadiusRate R hR' k hk

end

end
