-- Theorem-local support for Chap08 Lemma 8 6 11.
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.FaithfulSliceSetoids
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.LocalizedTerminalCover
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.SliceYonedaEvaluation
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.SliceLocalClasses
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.EssentialSurjCompatibility
import stacks_proof.stacks_project.Chap08.Lemma_8_6_11.FixedCoverFullness
