import Mathlib
import StacksProject_2024.Chap10.Definition_10_69_1
import StacksProject_2024.Chap10.Lemma_10_69_2
import StacksProject_2024.Chap15.Definition_15_30_1
import StacksProject_2024.Chap15.Lemma_15_28_4
import StacksProject_2024.Chap15.Lemma_15_30_4
import StacksProject_2024.Chap15.Lemma_15_30_5

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

universe u

open CategoryTheory
open CategoryTheory.Limits
open HomologicalComplex
open MonoidalCategory
open ModuleCat
open scoped KoszulComplex
open scoped TensorProduct

namespace RingTheory.Sequence

variable {R : Type u} [CommRing R]
variable {M : Type u} [AddCommGroup M] [Module R M]

/- Domain triage:
* primary domain: module-valued `H₁`-regularity and quasi-regularity for finite families in
  commutative algebra;
* sampled owner declarations: `IsH1RegularOn`, `IsQuasiRegular`,
  `IsRegular.isQuasiRegular`, and `IsH1RegularOn.of_flat_of_isBaseChange`;
* best owner abstraction: `IsH1RegularOn` is the source-facing owner on the hypothesis side, while
  `IsQuasiRegular` is the Chapter 10 owner for the associated-graded criterion;
* primitive data vs derived API: the primitive data is just the finite family `f`; the
  quasi-regularity conclusion is derived bridge data and should therefore be exposed as an
  owner-style theorem under `IsH1RegularOn`, not as a parallel freestanding wrapper.
-/

-- Proof sketch: identify quasi-regularity with the graded coefficient criterion for
-- `quasiRegularSequenceAssociatedGradedMap M (List.ofFn f)`. The `H₁`-regularity hypothesis
-- forces the degree-one Koszul relations to be generated by the trivial ones, and the argument in
-- the Stacks proof uses Lemmas `15.30.4`, `15.30.5`, and `15.28.4` to induct on the total degree
-- of a homogeneous relation and conclude that every coefficient lies in the ideal generated by
-- `f`, yielding bijectivity of the associated-graded map.
namespace IsH1RegularOn

/-- Helper for Lemma 15.30.6: the tensorized Koszul complex attached to a finite family. -/
private abbrev tensor_koszul_complex (R : Type u) [CommRing R] (M : Type u)
    [AddCommGroup M] [Module R M] {r : ℕ} (f : Fin r → R) :
    ChainComplex (ModuleCat R) ℕ :=
  ((tensorLeft (of R M)).mapHomologicalComplex (ComplexShape.down ℕ)).obj (K^•(f))

/-- Helper for Lemma 15.30.6: vanishing of homology transports across an isomorphism of chain
complexes. -/
private theorem isZero_homology_iff_of_iso
    {C D : ChainComplex (ModuleCat R) ℕ} (e : C ≅ D) (i : ℕ) :
    IsZero (C.homology i) ↔ IsZero (D.homology i) := by
  -- Proof comment: the homology comparison induced by an isomorphism is itself an isomorphism.
  exact Iso.isZero_iff (HomologicalComplex.homologyMapIso e i)

/-- Helper for Lemma 15.30.6: flat base change followed by an invertible linear change of
generators preserves `H_1`-regularity. -/
theorem of_matrix_linear_combination_of_flat
    {S : Type u} [CommRing S] [Algebra R S] [Module.Flat R S] {r : ℕ}
    (x : Matrix (Fin r) (Fin r) S) [Invertible x] {f : Fin r → R}
    (hH1 : IsH1RegularOn M f) :
    IsH1RegularOn (S ⊗[R] M) (x.toLin' fun i ↦ algebraMap R S (f i)) := by
  -- Proof comment: first transport `H₁`-regularity to the flat base change.
  have hbase : IsH1RegularOn (S ⊗[R] M) (fun i ↦ algebraMap R S (f i)) :=
    hH1.of_flat
  have hzero :
      IsZero
        ((tensor_koszul_complex S (S ⊗[R] M) (fun i ↦ algebraMap R S (f i))).homology 1) := by
    -- Proof comment: unfold the owner predicate once to expose the tensorized Koszul complex.
    simpa [IsH1RegularOn, tensor_koszul_complex] using hbase
  let e :
      tensor_koszul_complex S (S ⊗[R] M) (fun i ↦ algebraMap R S (f i)) ≅
        tensor_koszul_complex S (S ⊗[R] M) (x.toLin' fun i ↦ algebraMap R S (f i)) :=
    (((tensorLeft (ModuleCat.of S (S ⊗[R] M))).mapHomologicalComplex
      (ComplexShape.down ℕ)).mapIso
        (koszul_complex_on_matrix_linear_combination_iso x
          (fun i ↦ algebraMap R S (f i))))
  have hzero' :
      IsZero
        ((tensor_koszul_complex S (S ⊗[R] M)
          (x.toLin' fun i ↦ algebraMap R S (f i))).homology 1) := by
    -- Proof comment: the Koszul-complex isomorphism from Lemma `15.28.4` preserves first homology.
    exact (isZero_homology_iff_of_iso (e := e) 1).mp hzero
  -- Proof comment: fold the tensorized complex back into the owner predicate.
  simpa [IsH1RegularOn, tensor_koszul_complex] using hzero'

/-- Helper for Lemma 15.30.6: replacing the last generator of an `H_1`-regular family by a
positive power preserves `H_1`-regularity. -/
theorem snoc_pow {r : ℕ} {fs : Fin r → R} {a : R}
    (hH1 : IsH1RegularOn M (Fin.snoc fs a)) (n : ℕ) :
    IsH1RegularOn M (Fin.snoc fs (a ^ (n + 1))) := by
  induction n with
  | zero =>
      -- Proof comment: the exponent `1` case is exactly the original hypothesis.
      simpa using hH1
  | succ n ih =>
      -- Proof comment: first keep the already verified power `a ^ (n + 1)`, then multiply by
      -- one more copy of `a` using Lemma `15.30.4`.
      have hpow : IsH1RegularOn M (Fin.snoc fs (a ^ (n + 1))) :=
        ih
      have hmul :
          IsH1RegularOn M (Fin.snoc fs (a ^ (n + 1) * a)) :=
        snoc_mul hpow hH1
      simpa [pow_succ, mul_comm, mul_left_comm, mul_assoc] using hmul

/-- Helper for Lemma 15.30.6: the concrete degree-`1 → 0` differential model for a finite family
is the linear combination `u ↦ ∑ i, s i • u i`. -/
private def familyLinearCombination {n : ℕ} (s : Fin n → R) :
    (Fin n → M) →ₗ[R] M where
  toFun := fun u ↦ ∑ i, s i • u i
  map_add' := by
    intro u v
    simp [smul_add, Finset.sum_add_distrib]
  map_smul' := by
    intro a u
    simp [Finset.smul_sum, smul_smul, mul_comm]

/-- Helper for Lemma 15.30.6: degree `0` of the tensorized Koszul complex is canonically `M`. -/
private noncomputable abbrev tensor_koszul_zero_term_iso {n : ℕ} (s : Fin n → R) :
    (tensor_koszul_complex R M s).X 0 ≅ ModuleCat.of R M :=
  ((tensorLeft (ModuleCat.of R M)).mapIso
      (ModuleCat.exteriorPower.iso₀ (ModuleCat.of R (Fin n → R)))) ≪≫
    (TensorProduct.rid R M).toModuleIso

/-- Helper for Lemma 15.30.6: degree `1` of the tensorized Koszul complex is canonically
`Fin n → M`. -/
private noncomputable abbrev tensor_koszul_one_term_iso {n : ℕ} (s : Fin n → R) :
    (tensor_koszul_complex R M s).X 1 ≅ ModuleCat.of R (Fin n → M) :=
  ((tensorLeft (ModuleCat.of R M)).mapIso
      (ModuleCat.exteriorPower.iso₁ (ModuleCat.of R (Fin n → R)))) ≪≫
    (TensorProduct.piScalarRight R R M (Fin n)).toModuleIso

/-- Helper for Lemma 15.30.6: tensoring a linear map on the right acts on pure tensors by
applying the map to the second factor. -/
private theorem tensorLeft_map_apply_tmul {N P : Type u}
    [AddCommGroup N] [Module R N] [AddCommGroup P] [Module R P]
    (φ : N →ₗ[R] P) (x : M) (y : N) :
    (((tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom φ)).hom) (x ⊗ₜ[R] y) =
      x ⊗ₜ[R] φ y :=
  rfl

/-- Helper for Lemma 15.30.6: coercing the degree-one Koszul differential back to the ambient
exterior algebra recovers contraction by the defining linear form. -/
@[simp] private theorem koszul_differential_linearMap_apply_coe
    {n : ℕ} (φ : (Fin n → R) →ₗ[R] R) (x : ⋀[R]^1 (Fin n → R)) :
    (koszulDifferentialLinearMap φ 0 x : ExteriorAlgebra R (Fin n → R)) =
      CliffordAlgebra.contractLeft φ x :=
  rfl

/-- Helper for Lemma 15.30.6: transporting a scalar through `⋀⁰(R^n) ≃ R` is just the scalar
inclusion into the exterior algebra. -/
private theorem exteriorPower_zeroEquiv_symm_scalar_as_algebraMap {n : ℕ} (a : R) :
    (((exteriorPower.zeroEquiv R (Fin n → R)).symm a : ⋀[R]^0 (Fin n → R)) :
      ExteriorAlgebra R (Fin n → R)) =
      algebraMap R (ExteriorAlgebra R (Fin n → R)) a := by
  -- Proof comment: the degree-zero exterior power is the copy of `R` generated by `1`.
  simpa [exteriorPower.zeroEquiv_symm_apply, ExteriorAlgebra.ιMulti,
    Algebra.algebraMap_eq_smul_one]

/-- Helper for Lemma 15.30.6: before tensoring with `M`, the first Koszul differential on `s`
becomes the tuple linear form after transporting `⋀¹` and `⋀⁰` to concrete coordinates. -/
private theorem first_koszul_differential_eq_linearForm {n : ℕ} (s : Fin n → R) :
    (exteriorPower.zeroEquiv R (Fin n → R)).toLinearMap.comp
        (koszulDifferentialLinearMap (koszulLinearForm s) 0) =
      (koszulLinearForm s).comp
        (exteriorPower.oneEquiv R (Fin n → R)).toLinearMap := by
  -- Proof comment: evaluate on degree-one generators and compare both sides in the ambient
  -- exterior algebra after transporting the degree-zero class back through `⋀⁰(R^n) ≃ R`.
  apply exteriorPower.linearMap_ext
  ext m
  simp only [LinearMap.compAlternatingMap_apply, LinearMap.coe_comp, Function.comp_apply]
  have hone :
      (exteriorPower.oneEquiv R (Fin n → R)) (exteriorPower.ιMulti R 1 m) = m 0 := by
    simpa using (exteriorPower.oneEquiv_ιMulti (R := R) (M := Fin n → R) (f := m))
  have hone' :
      (koszulLinearForm s)
          ((exteriorPower.oneEquiv R (Fin n → R)).toLinearMap
            (exteriorPower.ιMulti R 1 m)) =
        (koszulLinearForm s) (m 0) := by
    simpa [hone]
  rw [hone']
  apply_fun (exteriorPower.zeroEquiv R (Fin n → R)).symm using
    (exteriorPower.zeroEquiv R (Fin n → R)).symm.injective
  simp only [Nat.reduceAdd, LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply, Fin.isValue]
  apply Subtype.ext
  rw [exteriorPower_zeroEquiv_symm_scalar_as_algebraMap (R := R) (n := n)
    ((koszulLinearForm s) (m 0))]
  simpa [koszul_differential_linearMap_apply_coe, ExteriorAlgebra.ιMulti,
    Algebra.algebraMap_eq_smul_one] using
    (CliffordAlgebra.contractLeft_ι
      (Q := (0 : QuadraticForm R (Fin n → R)))
      (d := koszulLinearForm s) (x := m 0))

/-- Helper for Lemma 15.30.6: after transporting `Fin n → M` back to a tensor product, the
tensorized tuple linear form sends a supported basis vector to `s i • x`. -/
private theorem tensor_koszul_linearForm_on_single {n : ℕ}
    (s : Fin n → R) (i : Fin n) (x : M) :
    (((TensorProduct.piScalarRight R R M (Fin n)).toModuleIso.inv ≫
        (tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom (koszulLinearForm s)) ≫
        (TensorProduct.rid R M).toModuleIso.hom).hom) (Pi.single i x) =
      s i • x := by
  -- Proof comment: transport the supported basis vector to a pure tensor, then evaluate the tuple
  -- linear form on the matching standard basis vector.
  change
    (TensorProduct.rid R M)
      (((tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom (koszulLinearForm s))).hom
        (((TensorProduct.piScalarRight R R M (Fin n)).symm) (Pi.single i x))) =
      s i • x
  have hsingle :
      ((TensorProduct.piScalarRight R R M (Fin n)).symm) (Pi.single i x) =
        x ⊗ₜ[R] (Pi.single i (1 : R)) := by
    apply (TensorProduct.piScalarRight R R M (Fin n)).injective
    ext j
    simp [Pi.single_apply]
  rw [hsingle, tensorLeft_map_apply_tmul]
  have hcoeff : koszulLinearForm s (Pi.single i (1 : R)) = s i := by
    simp [koszulLinearForm, Module.piEquiv_apply_apply, Pi.single_apply]
  simp [hcoeff]

/-- Helper for Lemma 15.30.6: after transporting the tensorized tuple linear form through the
degree-one and degree-zero coordinate changes, it becomes `familyLinearCombination s`. -/
private theorem tensor_koszul_linearForm_eq_familyLinearCombination {n : ℕ}
    (s : Fin n → R) :
    (TensorProduct.piScalarRight R R M (Fin n)).toModuleIso.inv ≫
        (tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom (koszulLinearForm s)) ≫
        (TensorProduct.rid R M).toModuleIso.hom =
      ModuleCat.ofHom (familyLinearCombination (R := R) (M := M) s) := by
  -- Proof comment: compare the two maps on supported basis vectors of `Fin n → M`.
  apply ModuleCat.hom_ext
  change
    (((TensorProduct.piScalarRight R R M (Fin n)).toModuleIso.inv ≫
        (tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom (koszulLinearForm s)) ≫
        (TensorProduct.rid R M).toModuleIso.hom).hom) =
      familyLinearCombination (R := R) (M := M) s
  apply LinearMap.pi_ext
  intro i x
  rw [tensor_koszul_linearForm_on_single (R := R) (M := M) s i x]
  classical
  have hsingle :
      ∑ j, s j • Pi.single i x j = s i • x := by
    rw [Finset.sum_eq_single i]
    · simp
    · intro j _ hij
      simp [hij]
    · intro hi
      exact (hi (Finset.mem_univ i)).elim
  simpa [familyLinearCombination] using hsingle.symm

/-- Helper for Lemma 15.30.6: in the untensored family Koszul complex, the degree `1 → 0`
differential is the defining degree-zero Koszul differential map. -/
private theorem koszul_complex_first_differential_eq_ofHom {n : ℕ} (s : Fin n → R) :
    (K^•(s)).d 1 0 =
      ModuleCat.ofHom (koszulDifferentialLinearMap (koszulLinearForm s) 0) := by
  -- Proof comment: unfold the family Koszul complex once so the categorical differential becomes
  -- the defining degree-zero Koszul differential.
  simpa [koszulComplex, koszulDifferential] using
    (ChainComplex.of_d ((ModuleCat.of R (Fin n → R)).exteriorPower)
      (koszulDifferential (koszulLinearForm s)) _ 0)

/-- Helper for Lemma 15.30.6: after transporting the untensored degree `1 → 0` differential to
concrete coordinates, it is exactly the tuple linear form `koszulLinearForm s`. -/
private theorem first_koszul_differential_transport_eq_linearForm {n : ℕ} (s : Fin n → R) :
    (ModuleCat.exteriorPower.iso₁ (ModuleCat.of R (Fin n → R))).inv ≫
        (K^•(s)).d 1 0 ≫
        (ModuleCat.exteriorPower.iso₀ (ModuleCat.of R (Fin n → R))).hom =
      ModuleCat.ofHom (koszulLinearForm s) := by
  -- Proof comment: compare the transported categorical differential with the linear-map statement
  -- `first_koszul_differential_eq_linearForm`.
  apply ModuleCat.hom_ext
  have htransport :=
    congrArg
      (fun ψ : ⋀[R]^1 (Fin n → R) →ₗ[R] R ↦
        ψ.comp (exteriorPower.oneEquiv R (Fin n → R)).symm.toLinearMap)
      (first_koszul_differential_eq_linearForm (R := R) (s := s))
  simpa [koszul_complex_first_differential_eq_ofHom (R := R) (s := s), LinearMap.comp_assoc]
    using htransport

/-- Helper for Lemma 15.30.6: after transporting degree `1` and degree `0` to concrete module
coordinates, the first tensorized Koszul differential is `familyLinearCombination s`. -/
private theorem tensor_koszul_first_differential_eq_familyLinearCombination {n : ℕ}
    (s : Fin n → R) :
    (tensor_koszul_one_term_iso (R := R) (M := M) s).inv ≫
        (tensor_koszul_complex R M s).d 1 0 ≫
        (tensor_koszul_zero_term_iso (R := R) (M := M) s).hom =
      ModuleCat.ofHom (familyLinearCombination (R := R) (M := M) s) := by
  -- Proof comment: peel off the degree-one and degree-zero coordinate changes so the middle map
  -- becomes the untensored first Koszul differential, then apply the tuple-linear-form model.
  calc
    (tensor_koszul_one_term_iso (R := R) (M := M) s).inv ≫
        (tensor_koszul_complex R M s).d 1 0 ≫
        (tensor_koszul_zero_term_iso (R := R) (M := M) s).hom =
      (TensorProduct.piScalarRight R R M (Fin n)).toModuleIso.inv ≫
          (tensorLeft (ModuleCat.of R M)).map
            ((ModuleCat.exteriorPower.iso₁ (ModuleCat.of R (Fin n → R))).inv ≫
              (K^•(s)).d 1 0 ≫
              (ModuleCat.exteriorPower.iso₀ (ModuleCat.of R (Fin n → R))).hom) ≫
          (TensorProduct.rid R M).toModuleIso.hom := by
            simp [tensor_koszul_one_term_iso, tensor_koszul_zero_term_iso, tensor_koszul_complex,
              Category.assoc, CategoryTheory.Functor.mapHomologicalComplex_obj_d]
    _ =
      (TensorProduct.piScalarRight R R M (Fin n)).toModuleIso.inv ≫
          (tensorLeft (ModuleCat.of R M)).map (ModuleCat.ofHom (koszulLinearForm s)) ≫
          (TensorProduct.rid R M).toModuleIso.hom := by
            -- Proof comment: replace the untensored first differential by the tuple linear form.
            rw [first_koszul_differential_transport_eq_linearForm (R := R) (s := s)]
    _ = ModuleCat.ofHom (familyLinearCombination (R := R) (M := M) s) := by
          exact tensor_koszul_linearForm_eq_familyLinearCombination (R := R) (M := M) s

/-- Helper for Lemma 15.30.6: quotienting the last coordinate gives the source proof's target
module for the degree-one boundary extraction. -/
private noncomputable def last_coordinate_quotient_map {r : ℕ} (s : Fin (r + 1) → R) :
    ModuleCat.of R (Fin (r + 1) → M) ⟶
      ModuleCat.of R (M ⧸ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))) :=
  ModuleCat.ofHom
    ((Submodule.mkQ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))).comp
      (LinearMap.proj (R := R) (Fin.last r)))

/-- Helper for Lemma 15.30.6: every value of the Koszul linear form already lies in the owner
ideal generated by the family. -/
private theorem koszulLinearForm_mem_ownerIdeal {r : ℕ} (s : Fin (r + 1) → R)
    (v : Fin (r + 1) → R) :
    koszulLinearForm s v ∈ Ideal.ofList (List.ofFn s) := by
  -- Proof comment: expand the linear form as a sum of owner generators multiplied by scalars.
  rw [koszulLinearForm, Module.piEquiv_apply_apply]
  refine Ideal.sum_mem _ ?_
  intro i _
  rw [Ideal.ofList]
  exact Ideal.mul_mem_left _ _ <| Ideal.subset_span <| by
    cases i using Fin.cases with
    | zero =>
        simp [List.mem_ofFn']
    | succ j =>
        simp [List.mem_ofFn']

/-- Helper for Lemma 15.30.6: in the untensored family Koszul complex, the degree `2 → 1`
differential is the defining degree-one Koszul differential. -/
private theorem koszul_complex_second_differential_eq_ofHom {n : ℕ} (s : Fin n → R) :
    (K^•(s)).d 2 1 =
      ModuleCat.ofHom (koszulDifferentialLinearMap (koszulLinearForm s) 1) := by
  -- Proof comment: unfold the family Koszul complex once so the categorical differential becomes
  -- the degree-one Koszul differential.
  simpa [koszulComplex, koszulDifferential] using
    (ChainComplex.of_d ((ModuleCat.of R (Fin n → R)).exteriorPower)
      (koszulDifferential (koszulLinearForm s)) _ 1)

/-- Helper for Lemma 15.30.6: on a pure tensor with an `ιMulti` generator, the tensorized degree
`2 → 1` Koszul differential is the usual alternating deletion sum. -/
private theorem tensor_koszul_second_differential_apply_tmul_ιMulti {r : ℕ}
    (s : Fin (r + 1) → R) (x : M) (v : Fin 2 → Fin (r + 1) → R) :
    ((tensor_koszul_complex R M s).d 2 1).hom (x ⊗ₜ[R] exteriorPower.ιMulti R 2 v) =
      ∑ k : Fin 2, ((-1 : R) ^ (k : ℕ) * (koszulLinearForm s) (v k)) •
        (x ⊗ₜ[R] exteriorPower.ιMulti R 1 (fun i ↦ v (Fin.succAbove k i))) := by
  -- Proof comment: rewrite the categorical differential as the degree-one Koszul differential,
  -- then apply the owner-level alternating-deletion formula termwise on the tensor factor.
  change
    (((tensorLeft (ModuleCat.of R M)).map ((K^•(s)).d 2 1)).hom)
        (x ⊗ₜ[R] exteriorPower.ιMulti R 2 v) =
      ∑ k : Fin 2, ((-1 : R) ^ (k : ℕ) * (koszulLinearForm s) (v k)) •
        (x ⊗ₜ[R] exteriorPower.ιMulti R 1 (fun i ↦ v (Fin.succAbove k i)))
  rw [koszul_complex_second_differential_eq_ofHom (R := R) (s := s)]
  change
    x ⊗ₜ[R] koszulDifferentialLinearMap (koszulLinearForm s) 1
        (exteriorPower.ιMulti R 2 v) =
      ∑ k : Fin 2, ((-1 : R) ^ (k : ℕ) * (koszulLinearForm s) (v k)) •
        (x ⊗ₜ[R] exteriorPower.ιMulti R 1 (fun i ↦ v (Fin.succAbove k i)))
  rw [koszulDifferentialLinearMap_apply_ιMulti_eq_sum]
  rw [TensorProduct.tmul_sum]
  refine Finset.sum_congr rfl ?_
  intro k hk
  rw [TensorProduct.tmul_smul]

/-- Helper for Lemma 15.30.6: transporting a degree-one `ιMulti` generator through the degree-one
tensor-term coordinate change gives the expected tuple of scalar multiples. -/
private theorem tensor_koszul_one_term_iso_hom_apply_tmul_ιMulti_one {r : ℕ}
    (s : Fin (r + 1) → R) (x : M) (v : Fin 1 → Fin (r + 1) → R) :
    ((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom)
        (x ⊗ₜ[R] exteriorPower.ιMulti R 1 v) =
      fun i ↦ (v 0 i) • x := by
  -- Proof comment: the degree-one exterior-power identification sends `ιMulti` to its unique
  -- coordinate, and `TensorProduct.piScalarRight` turns the resulting pure tensor into the
  -- corresponding supported tuple of scalar multiples of `x`.
  ext i
  change
    (((TensorProduct.piScalarRight R R M (Fin (r + 1))).toModuleIso.hom.hom)
      (x ⊗ₜ[R]
        ((ModuleCat.exteriorPower.iso₁ (ModuleCat.of R (Fin (r + 1) → R))).hom.hom
          (exteriorPower.ιMulti R 1 v)))) i =
      ((v 0 i) • x)
  have hcoord :
      ((ModuleCat.exteriorPower.iso₁ (ModuleCat.of R (Fin (r + 1) → R))).hom.hom)
          (exteriorPower.ιMulti R 1 v) =
        v 0 := by
    -- Proof comment: `⋀¹(R^(r+1)) ≃ R^(r+1)` identifies the unique `ιMulti` generator with its
    -- single coordinate.
    change
      (exteriorPower.oneEquiv R (Fin (r + 1) → R))
          (exteriorPower.ιMulti R 1 v) =
        v 0
    simpa using
      (exteriorPower.oneEquiv_ιMulti (R := R) (M := Fin (r + 1) → R) (f := v))
  simp [hcoord]

/-- Helper for Lemma 15.30.6: after transporting the degree-one term to concrete coordinates, the
last coordinate of `x ⊗ ιMulti` is the expected scalar multiple of `x`. -/
private theorem last_coordinate_quotient_on_tmul_ιMulti_one {r : ℕ}
    (s : Fin (r + 1) → R) (x : M) (v : Fin 1 → Fin (r + 1) → R) :
    ((last_coordinate_quotient_map (R := R) (M := M) s).hom)
        (((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom)
          (x ⊗ₜ[R] exteriorPower.ιMulti R 1 v)) =
      Submodule.mkQ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))
        ((v 0 (Fin.last r)) • x) := by
  -- Proof comment: first identify the transported degree-one generator with the concrete tuple
  -- `i ↦ v 0 i • x`, then project to the last coordinate and pass to the quotient.
  rw [tensor_koszul_one_term_iso_hom_apply_tmul_ιMulti_one (R := R) (M := M) s x v]
  rfl

/-- Helper for Lemma 15.30.6: every degree-two boundary maps to zero after taking the last
coordinate modulo the owner ideal. -/
private theorem last_coordinate_quotient_comp_second_differential {r : ℕ}
    (s : Fin (r + 1) → R) :
    (tensor_koszul_complex R M s).d 2 1 ≫
        (tensor_koszul_one_term_iso (R := R) (M := M) s).hom ≫
        last_coordinate_quotient_map (R := R) (M := M) s = 0 := by
  -- Proof comment: the degree-two tensor product is generated by pure tensors, and the degree-two
  -- exterior power is generated by the `ιMulti` basis. On each such generator, the preceding two
  -- lemmas identify the composite with a quotient class killed by the owner ideal.
  apply ModuleCat.hom_ext
  apply TensorProduct.ext'
  intro x
  let φ :
      ↑((K^•(s)).X 2) →ₗ[R]
        M ⧸ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M)) :=
    ((last_coordinate_quotient_map (R := R) (M := M) s).hom).comp
      (((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom).comp
        (((tensor_koszul_complex R M s).d 2 1).hom.comp
          (TensorProduct.mk R M ↑((K^•(s)).X 2) x)))
  have hφ : φ = 0 := by
    apply exteriorPower.linearMap_ext
    ext v
    change
      ((last_coordinate_quotient_map (R := R) (M := M) s).hom)
          (((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom)
            (((tensor_koszul_complex R M s).d 2 1).hom
              (x ⊗ₜ[R] exteriorPower.ιMulti R 2 v))) =
        0
    rw [tensor_koszul_second_differential_apply_tmul_ιMulti (R := R) (M := M) s x v]
    let ψ :
        ↑((tensor_koszul_complex R M s).X 1) →ₗ[R]
          M ⧸ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M)) :=
      ((last_coordinate_quotient_map (R := R) (M := M) s).hom).comp
        ((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom)
    change ψ
        (∑ k : Fin 2, ((-1 : R) ^ (k : ℕ) * (koszulLinearForm s) (v k)) •
          (x ⊗ₜ[R] exteriorPower.ιMulti R 1 (fun i ↦ v (Fin.succAbove k i)))) =
      0
    rw [map_sum]
    refine Finset.sum_eq_zero ?_
    intro k hk
    let a : R := (-1 : R) ^ (k : ℕ) * (koszulLinearForm s) (v k)
    have hterm :
        ψ (a • x ⊗ₜ[R] exteriorPower.ιMulti R 1 (fun i ↦ v (Fin.succAbove k i))) =
          Submodule.mkQ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))
            ((v (Fin.succAbove k 0) (Fin.last r)) • (a • x)) := by
      -- Proof comment: the degree-one transport identifies the remaining truncated generator with
      -- its last coordinate, exactly as in the source proof's boundary computation.
      simpa [ψ, a] using
        (last_coordinate_quotient_on_tmul_ιMulti_one (R := R) (M := M) s (a • x)
          (fun i ↦ v (Fin.succAbove k i)))
    rw [hterm]
    refine (Submodule.Quotient.mk_eq_zero _).2 ?_
    have ha :
        a ∈ Ideal.ofList (List.ofFn s) := by
      exact Ideal.mul_mem_left _ _ (koszulLinearForm_mem_ownerIdeal (R := R) s (v k))
    have hmem :
        a • ((v (Fin.succAbove k 0) (Fin.last r)) • x) ∈
          Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M) := by
      exact Submodule.smul_mem_smul ha (by simp)
    convert hmem using 1
    simp [a, smul_smul, mul_comm, mul_left_comm]
  intro y
  change φ y = 0
  simpa using
    (LinearMap.congr_fun hφ y :
      φ y =
        (0 :
          ↑((K^•(s)).X 2) →ₗ[R]
            M ⧸ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))) y)

/-- Helper for Lemma 15.30.6: vanishing of the first homology object identifies the degree-one
cycles in the tensorized Koszul complex with the degree-two boundaries. -/
private theorem tensor_koszul_range_eq_ker_at_one {r : ℕ} {s : Fin (r + 1) → R}
    (hH1 : IsH1RegularOn M s) :
    LinearMap.range ((tensor_koszul_complex R M s).d 2 1).hom =
      LinearMap.ker ((tensor_koszul_complex R M s).d 1 0).hom := by
  -- Proof comment: rewrite `H₁ = 0` as exactness at degree `1`, then specialize the short-complex
  -- exactness statement to `range = ker`.
  rw [IsH1RegularOn] at hH1
  rw [← HomologicalComplex.exactAt_iff_isZero_homology] at hH1
  rw [HomologicalComplex.exactAt_iff' _ 2 1 0 (by simp [ChainComplex.prev])
    (by exact ChainComplex.next_nat_succ 0)] at hH1
  rw [ShortComplex.moduleCat_exact_iff_range_eq_ker] at hH1
  exact hH1

/-- Helper for Lemma 15.30.6: evaluating the transported degree-`1 → 0` differential on a
concrete tuple recovers the family linear combination `∑ i, s i • u i`. -/
private theorem tensor_koszul_first_differential_apply_inv_eq_family_sum {r : ℕ}
    (s : Fin (r + 1) → R) (u : Fin (r + 1) → M) :
    ((tensor_koszul_zero_term_iso (R := R) (M := M) s).hom.hom)
        (((tensor_koszul_complex R M s).d 1 0).hom
          ((tensor_koszul_one_term_iso (R := R) (M := M) s).inv.hom u)) =
      ∑ i, s i • u i := by
  -- Proof comment: apply the transported differential formula to the tuple `u` itself.
  have hmap :=
    congrArg
      (fun φ : ModuleCat.of R (Fin (r + 1) → M) ⟶ ModuleCat.of R M ↦ φ.hom u)
      (tensor_koszul_first_differential_eq_familyLinearCombination
        (R := R) (M := M) s)
  simpa [Category.assoc, familyLinearCombination] using hmap

/-- Helper for Lemma 15.30.6: a trivial linear relation among the generators forces the last
coordinate into the owner ideal. -/
theorem last_coordinate_mem_of_trivial_relation {r : ℕ} {s : Fin (r + 1) → R}
    {u : Fin (r + 1) → M} (hH1 : IsH1RegularOn M s)
    (hu : ∑ i, s i • u i = 0) :
    u (Fin.last r) ∈ Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M) := by
  -- Proof comment: transport the tuple `u` into degree `1` of the tensorized Koszul complex.
  let z := (tensor_koszul_one_term_iso (R := R) (M := M) s).inv.hom u
  have hz_cycle :
      ((tensor_koszul_complex R M s).d 1 0).hom z = 0 := by
    -- Proof comment: the new transport lemma turns the given trivial relation into the cycle
    -- condition for `z`.
    have hz_eval :
        ((tensor_koszul_zero_term_iso (R := R) (M := M) s).hom.hom)
            (((tensor_koszul_complex R M s).d 1 0).hom z) = 0 := by
      simpa [z, hu] using
        tensor_koszul_first_differential_apply_inv_eq_family_sum
          (R := R) (M := M) s u
    have hz_eval' :=
      congrArg ((tensor_koszul_zero_term_iso (R := R) (M := M) s).inv.hom) hz_eval
    calc
      ((tensor_koszul_complex R M s).d 1 0).hom z =
          ((tensor_koszul_zero_term_iso (R := R) (M := M) s).inv.hom)
            (((tensor_koszul_zero_term_iso (R := R) (M := M) s).hom.hom)
              (((tensor_koszul_complex R M s).d 1 0).hom z)) := by
                symm
                simpa using
                  (tensor_koszul_zero_term_iso (R := R) (M := M) s).hom_inv_id_apply
                    (((tensor_koszul_complex R M s).d 1 0).hom z)
      _ = ((tensor_koszul_zero_term_iso (R := R) (M := M) s).inv.hom) 0 := hz_eval'
      _ = 0 := by
            simpa using
              ((tensor_koszul_zero_term_iso (R := R) (M := M) s).inv.hom.map_zero)
  have hz_ker :
      z ∈ LinearMap.ker ((tensor_koszul_complex R M s).d 1 0).hom := by
    -- Proof comment: record the cycle condition as membership in the kernel.
    simpa [LinearMap.mem_ker] using hz_cycle
  have hz_range :
      z ∈ LinearMap.range ((tensor_koszul_complex R M s).d 2 1).hom := by
    -- Proof comment: `H₁ = 0` identifies degree-one cycles with degree-two boundaries.
    rw [tensor_koszul_range_eq_ker_at_one (R := R) (M := M) (hH1 := hH1)]
    exact hz_ker
  rcases hz_range with ⟨y, hy⟩
  have hboundary :
      ((last_coordinate_quotient_map (R := R) (M := M) s).hom)
          (((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom)
            (((tensor_koszul_complex R M s).d 2 1).hom y)) =
        0 := by
    -- Proof comment: every degree-two boundary has trivial last coordinate modulo the owner
    -- ideal.
    simpa using
      congrArg
        (fun φ :
          (tensor_koszul_complex R M s).X 2 ⟶
            ModuleCat.of R (M ⧸ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))) ↦
          φ.hom y)
        (last_coordinate_quotient_comp_second_differential (R := R) (M := M) s)
  have hlast_zero :
      Submodule.mkQ (Ideal.ofList (List.ofFn s) • (⊤ : Submodule R M))
          (u (Fin.last r)) =
        0 := by
    -- Proof comment: rewrite the boundary value as the transported tuple `u`.
    have hboundary' :
        ((last_coordinate_quotient_map (R := R) (M := M) s).hom)
            (((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom) z) =
          0 := by
      rw [← hy]
      exact hboundary
    have hz_transport :
        ((tensor_koszul_one_term_iso (R := R) (M := M) s).hom.hom) z = u := by
      let e1 := (tensor_koszul_one_term_iso (R := R) (M := M) s).toLinearEquiv
      simpa [z, e1] using e1.apply_symm_apply u
    have hu_last_zero :
        ((last_coordinate_quotient_map (R := R) (M := M) s).hom) u = 0 := by
      rw [← hz_transport]
      exact hboundary'
    simpa [last_coordinate_quotient_map] using hu_last_zero
  exact (Submodule.Quotient.mk_eq_zero _).1 hlast_zero

/-- Helper for Lemma 15.30.6: the owner ideal generated by `List.ofFn f` is the span of the
range of the finite family `f`. -/
private theorem ofList_ofFn_eq_span_range {n : ℕ} (f : Fin n → R) :
    Ideal.ofList (List.ofFn f) = Ideal.span (Set.range f) := by
  -- Proof comment: `List.ofFn` enumerates exactly the values of `f`, so the list-generated ideal
  -- and the span of the range coincide definitionally after simplification.
  simp [Ideal.ofList, List.mem_ofFn', Set.range]

/-- Helper for Lemma 15.30.6: replacing the last generator of a finite family by a positive power
does not enlarge the owner ideal generated by the family. -/
private theorem ownerIdeal_snoc_pow_le {r : ℕ} (fs : Fin r → R) (a : R) (n : ℕ) :
    Ideal.ofList (List.ofFn (Fin.snoc fs (a ^ (n + 1)))) ≤
      Ideal.ofList (List.ofFn (Fin.snoc fs a)) := by
  -- Proof comment: every unchanged generator is still one of the original list entries, while the
  -- powered last generator lies in the original owner ideal because it is a power of `a`.
  rw [ofList_ofFn_eq_span_range, ofList_ofFn_eq_span_range]
  refine Ideal.span_le.2 ?_
  rintro _ ⟨i, rfl⟩
  refine Fin.lastCases ?_ ?_ i
  · have ha :
      a ∈ Ideal.span (Set.range (Fin.snoc fs a)) := by
      simpa [Fin.lastCases_last] using
        (Ideal.subset_span (Set.mem_range_self (Fin.last r)) :
          ((Fin.snoc fs a : Fin (r + 1) → R) (Fin.last r)) ∈
            Ideal.span (Set.range (Fin.snoc fs a)))
    simpa [Fin.lastCases_last] using
      (Ideal.pow_mem_of_mem _ ha (n + 1) (Nat.succ_pos n))
  · intro j
    simpa [Fin.lastCases_castSucc] using
      (Ideal.subset_span (Set.mem_range_self j.castSucc) :
        ((Fin.snoc fs a : Fin (r + 1) → R) j.castSucc) ∈
          Ideal.span (Set.range (Fin.snoc fs a)))

/-- Helper for Lemma 15.30.6: after replacing the last generator by a positive power, a trivial
degree-one relation still forces the last coefficient into the original owner ideal. -/
private theorem last_coordinate_mem_of_trivial_relation_snoc_pow {r : ℕ}
    {fs : Fin r → R} {a : R} {u : Fin (r + 1) → M}
    (hH1 : IsH1RegularOn M (Fin.snoc fs a)) (n : ℕ)
    (hu : ∑ i : Fin (r + 1),
        ((Fin.snoc fs (a ^ (n + 1)) : Fin (r + 1) → R) i) • u i = 0) :
    u (Fin.last r) ∈ Ideal.ofList (List.ofFn (Fin.snoc fs a)) • (⊤ : Submodule R M) := by
  -- Proof comment: first run the already established degree-one boundary argument on the powered
  -- family, then descend along the inclusion of the powered owner ideal into the original one.
  have hpow : IsH1RegularOn M (Fin.snoc fs (a ^ (n + 1))) :=
    snoc_pow hH1 n
  have hmem_pow :
      u (Fin.last r) ∈
        Ideal.ofList (List.ofFn (Fin.snoc fs (a ^ (n + 1)))) • (⊤ : Submodule R M) :=
    last_coordinate_mem_of_trivial_relation
      (R := R) (M := M) (s := Fin.snoc fs (a ^ (n + 1))) hpow hu
  exact (Submodule.smul_mono
    (ownerIdeal_snoc_pow_le (R := R) fs a n) le_rfl) hmem_pow

/-- Helper for Lemma 15.30.6: multiplying a multivariable polynomial by a power of the last
variable shifts coefficients in the expected way. -/
private theorem coeff_X_last_pow_mul {r : ℕ} {A : Type u} [CommSemiring A]
    (k : ℕ) (p : MvPolynomial (Fin (r + 1)) A) (d : Fin (r + 1) →₀ ℕ) :
    (((MvPolynomial.X (Fin.last r)) ^ k) * p).coeff
        (d + Finsupp.single (Fin.last r) k) =
      p.coeff d := by
  induction k generalizing d with
  | zero =>
      -- Proof comment: multiplying by the zeroth power leaves every coefficient unchanged.
      simpa using rfl
  | succ k ih =>
      -- Proof comment: rewrite the extra power as one more multiplication by `X_last`, then
      -- apply the standard coefficient-shift formula and the induction hypothesis.
      rw [pow_succ]
      have hshift :
          (((MvPolynomial.X (Fin.last r)) ^ k) * p * MvPolynomial.X (Fin.last r)).coeff
              (d + Finsupp.single (Fin.last r) (k + 1)) =
            ((((MvPolynomial.X (Fin.last r)) ^ k) * p).coeff)
              (d + Finsupp.single (Fin.last r) k) := by
        simpa [Nat.succ_eq_add_one, add_assoc, Finsupp.single_add] using
          (MvPolynomial.coeff_mul_X
            (m := d + Finsupp.single (Fin.last r) k)
            (s := Fin.last r)
            (p := ((MvPolynomial.X (Fin.last r)) ^ k) * p))
      simpa [pow_succ, mul_assoc, mul_left_comm, mul_comm] using hshift.trans (ih d)

/-- Helper for Lemma 15.30.6: multiplication by a power of the last variable is injective on
multivariable polynomials. -/
private theorem X_last_pow_mul_injective {r : ℕ} {A : Type u} [CommSemiring A]
    (k : ℕ) :
    Function.Injective
      (fun p : MvPolynomial (Fin (r + 1)) A ↦ ((MvPolynomial.X (Fin.last r)) ^ k) * p) := by
  intro p q hpq
  ext d
  -- Proof comment: compare the shifted coefficient indexed by `d + k·e_last` on both sides.
  have hcoeff :=
    congrArg
      (fun z : MvPolynomial (Fin (r + 1)) A ↦
        z.coeff (d + Finsupp.single (Fin.last r) k))
      hpq
  simpa [coeff_X_last_pow_mul] using hcoeff

/-- Lemma 15.30.6, owner form: if a finite family `f` is `M`-`H_1`-regular, then the associated
finite sequence `List.ofFn f` is `M`-quasi-regular. -/
theorem isQuasiRegular {r : ℕ} {f : Fin r → R} (hH1 : IsH1RegularOn M f) :
    IsQuasiRegular M (List.ofFn f) := by
  cases r with
  | zero =>
      -- Proof comment: the empty sequence is regular, hence quasi-regular, independently of the
      -- `H₁`-regularity hypothesis.
      by_cases hM : Subsingleton M
      · let _ : Subsingleton M := hM
        rw [isQuasiRegular_iff_injective]
        intro x y _
        exact Subsingleton.elim _ _
      · let _ : Nontrivial M := not_subsingleton_iff_nontrivial.mp hM
        simpa using (IsRegular.isQuasiRegular (M := M) (rs := ([] : List R))
          (IsRegular.nil R M))
  | succ r =>
      -- Proof comment: for a nonempty family, rewrite quasi-regularity as injectivity of the
      -- associated-graded comparison map, matching the source proof's coefficient criterion.
      rw [isQuasiRegular_iff_injective]
      -- Route correction: the degree-1 Koszul/exactness seam is now closed in this file, and the
      -- coefficient-shift injectivity needed for denominator clearing is also isolated above. The
      -- pure-last degree-one step is now packaged by
      -- `last_coordinate_mem_of_trivial_relation_snoc_pow`; the remaining blocker is the
      -- source-faithful homogeneous coefficient descent over the localization
      -- `R[x₁, …, xᵣ, 1 / xᵣ]`.
      -- TODO(Lemma 15.30.6): prove the nonempty coefficient criterion by combining the special
      -- pure-last-exponent case from `last_coordinate_mem_of_trivial_relation_snoc_pow`, the
      -- localization change-of-variables argument via `of_matrix_linear_combination_of_flat`, and
      -- the final polynomial-level denominator-clearing step using `X_last_pow_mul_injective`.
      sorry

end IsH1RegularOn

end RingTheory.Sequence
