import StacksProject_2024.Chap10.Lemma_10_19_1
import StacksProject_2024.Chap15.Lemma_15_126_3

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open IsLocalRing

section

variable {R : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]

-- Domain-style sampling:
-- * primary domain: systems of parameters and parameter ideals in two-dimensional Noetherian
--   local rings;
-- * sampled owner declarations: `IsSystemOfParameters`, `parameterIdeal`,
--   `exists_systemOfParameters_cons_mem_maximalIdeal_pow_of_not_mem_minimalPrimes`;
-- * best owner abstraction: the chosen parameter family should be expressed in the chapter's
--   canonical `Fin.cons` form, here specialized to a singleton tail;
-- * primitive-vs-derived: the primitive data are the chosen second parameter `g` and the resulting
--   family `Fin.cons f ![g]`, while perturbation stability and quotient-length equality are
--   derived properties of that owner family.

-- Proof sketch: use Lemma `15.126.3` with tail length `d = 1` and `k = 1` to choose
-- `g ∈ maximalIdeal R` such that `Fin.cons f ![g]` is a system of parameters. Since the
-- corresponding parameter ideal is an ideal of definition, a power of the maximal ideal is
-- contained in it. For any `h` in the next power, write `h = af + b` with `a ∈ maximalIdeal R`
-- and `b` already in the ideal generated by `g`; then `1 + a` is a unit, so replacing `f` by
-- `f + h` does not change the parameter ideal. Equality of parameter ideals gives both the
-- perturbed system-of-parameters statement and the equality of quotient lengths.

omit [IsNoetherianRing R] in
/-- Helper for Lemma 15.126.4: the parameter ideal of a two-term ordered family is the supremum
of the two principal ideals generated by its entries. -/
private theorem parameterIdeal_cons_singleton (f g : maximalIdeal R) :
    parameterIdeal (Fin.cons f ![g]) =
      Ideal.span ({(f : R)} : Set R) ⊔ Ideal.span ({(g : R)} : Set R) := by
  have hrange :
      Set.range (fun i : Fin 2 ↦ (((Fin.cons f ![g] : Fin 2 → maximalIdeal R) i) : R)) =
        insert (f : R) ({(g : R)} : Set R) := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩
      fin_cases i <;> simp
    · intro hx
      rcases hx with rfl | hx
      · exact ⟨0, rfl⟩
      · have hgx : x = (g : R) := by
          simpa using hx
        exact ⟨1, hgx.symm⟩
  -- Rewrite the two-point range as an inserted singleton and expand the span.
  rw [parameterIdeal_eq_span, hrange, Ideal.span_insert]

omit [IsNoetherianRing R] in
/-- Helper for Lemma 15.126.4: perturbing the first parameter by an element of
`(maximalIdeal R)^(n + 1)` lands in `maximalIdeal R * I` as soon as `(maximalIdeal R)^n ≤ I`. -/
private theorem maximalIdeal_pow_succ_le_mul_parameterIdeal_of_pow_le
    {I : Ideal R} {n : ℕ} (hn : maximalIdeal R ^ n ≤ I) :
    maximalIdeal R ^ (n + 1) ≤ maximalIdeal R * I := by
  -- Peel off one maximal-ideal factor and use monotonicity on the right factor.
  rw [pow_succ']
  exact Ideal.mul_mono_right hn

omit [IsNoetherianRing R] in
/-- Helper for Lemma 15.126.4: an element of `maximalIdeal R * parameterIdeal (Fin.cons f ![g])`
splits into a maximal-ideal multiple of `f` plus a remainder already in the singleton tail ideal. -/
private theorem exists_head_singleton_decomposition_of_mem_mul_parameterIdeal_cons
    (f g : maximalIdeal R) {x : R}
    (hx : x ∈ maximalIdeal R * parameterIdeal (Fin.cons f ![g])) :
    ∃ a : maximalIdeal R, ∃ b : R, b ∈ Ideal.span ({(g : R)} : Set R) ∧
      x = (a : R) * (f : R) + b := by
  have hxSplit :
      x ∈ maximalIdeal R * Ideal.span ({(f : R)} : Set R) ⊔
        maximalIdeal R * Ideal.span ({(g : R)} : Set R) := by
    -- Expand the two-parameter ideal into its head and tail pieces before distributing.
    rw [parameterIdeal_cons_singleton, Ideal.mul_sup] at hx
    simpa using hx
  rcases Submodule.mem_sup.mp hxSplit with ⟨u, hu, v, hv, huv⟩
  -- Normalize the principal-factor product into pointwise smul to read off the head coefficient.
  rw [Ideal.mul_comm] at hu
  change u ∈ Ideal.span ({(f : R)} : Set R) • maximalIdeal R at hu
  rw [Submodule.ideal_span_singleton_smul] at hu
  rcases (Submodule.mem_smul_pointwise_iff_exists u (f : R) (maximalIdeal R)).1 hu with
    ⟨a, ha, hua⟩
  have hb : v ∈ Ideal.span ({(g : R)} : Set R) := by
    exact (Ideal.mul_le_left : maximalIdeal R * Ideal.span ({(g : R)} : Set R) ≤
      Ideal.span ({(g : R)} : Set R)) hv
  have hua' : u = (f : R) * a := by
    simpa [smul_eq_mul] using hua.symm
  refine ⟨⟨a, ha⟩, v, hb, ?_⟩
  calc
    x = u + v := huv.symm
    _ = (f : R) * a + v := by rw [hua']
    _ = (a : R) * (f : R) + v := by rw [mul_comm]

omit [IsNoetherianRing R] in
/-- Helper for Lemma 15.126.4: perturbing the first parameter by an element of
`maximalIdeal R * parameterIdeal (Fin.cons f ![g])` does not change the generated parameter ideal. -/
private theorem parameterIdeal_cons_singleton_eq_of_mem_maximalIdeal_mul
    (f g h : maximalIdeal R)
    (hh : (h : R) ∈ maximalIdeal R * parameterIdeal (Fin.cons f ![g])) :
    parameterIdeal (Fin.cons (f + h) ![g]) = parameterIdeal (Fin.cons f ![g]) := by
  let I : Ideal R := parameterIdeal (Fin.cons f ![g])
  let J : Ideal R := parameterIdeal (Fin.cons (f + h) ![g])
  have hI :
      I = Ideal.span ({(f : R)} : Set R) ⊔ Ideal.span ({(g : R)} : Set R) := by
    simpa [I] using parameterIdeal_cons_singleton (R := R) f g
  have hJ :
      J =
        Ideal.span ({(((f + h : maximalIdeal R) : R))} : Set R) ⊔
          Ideal.span ({(g : R)} : Set R) := by
    simpa [J] using parameterIdeal_cons_singleton (R := R) (f + h) g
  rcases exists_head_singleton_decomposition_of_mem_mul_parameterIdeal_cons (R := R) f g hh with
    ⟨a, b, hb, hdecomp⟩
  have hJac : maximalIdeal R ≤ Ring.jacobson R := by
    simpa [Ideal.jacobson_bot] using
      (IsLocalRing.maximalIdeal_le_jacobson (⊥ : Ideal R))
  have hunit : IsUnit (1 + (a : R)) := by
    exact
      (ideal_le_ring_jacobson_iff_isUnit_one_add (R := R) (I := maximalIdeal R)).1 hJac
        a a.property
  have htail_le_I : Ideal.span ({(g : R)} : Set R) ≤ I := by
    rw [hI]
    exact le_sup_right
  have htail_le_J : Ideal.span ({(g : R)} : Set R) ≤ J := by
    rw [hJ]
    exact le_sup_right
  have hfI : (f : R) ∈ I := by
    rw [hI]
    exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self (f : R))
  have hbI : b ∈ I := htail_le_I hb
  have hheadI : (((f + h : maximalIdeal R) : R)) ∈ I := by
    have hfaI : (f : R) + (a : R) * (f : R) ∈ I := by
      exact I.add_mem hfI (I.mul_mem_left _ hfI)
    have hsumI : (f : R) + (a : R) * (f : R) + b ∈ I := by
      exact I.add_mem hfaI hbI
    change (f : R) + (h : R) ∈ I
    simpa [hdecomp, add_assoc, add_left_comm, add_comm, add_mul] using hsumI
  have hheadJ : (((f + h : maximalIdeal R) : R)) ∈ J := by
    rw [hJ]
    exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self (((f + h : maximalIdeal R) : R)))
  have hbJ : b ∈ J := htail_le_J hb
  have hscaled_fJ : (1 + (a : R)) * (f : R) ∈ J := by
    have htmp : ((((f + h : maximalIdeal R) : R)) - b) ∈ J := by
      exact J.sub_mem hheadJ hbJ
    have hrewrite : ((((f + h : maximalIdeal R) : R)) - b) = (f : R) + (a : R) * (f : R) := by
      change (f : R) + (h : R) - b = (f : R) + (a : R) * (f : R)
      rw [hdecomp]
      ring
    rw [hrewrite] at htmp
    have hsumJ : (f : R) + (a : R) * (f : R) ∈ J := htmp
    simpa [add_mul] using hsumJ
  rcases hunit with ⟨u, hu⟩
  have hscaled_u : ((↑u : R) * (f : R)) ∈ J := by
    simpa [hu] using hscaled_fJ
  have hfJ : (f : R) ∈ J := by
    have hmul : ((↑u⁻¹ : R) * ((↑u : R) * (f : R))) ∈ J := by
      exact J.mul_mem_left _ hscaled_u
    simpa [mul_assoc] using hmul
  have hJI : J ≤ I := by
    rw [hJ]
    refine sup_le ?_ ?_
    · exact (Ideal.span_singleton_le_iff_mem I).2 hheadI
    · exact htail_le_I
  have hIJ : I ≤ J := by
    rw [hI]
    refine sup_le ?_ ?_
    · exact (Ideal.span_singleton_le_iff_mem J).2 hfJ
    · exact htail_le_J
  exact le_antisymm hJI hIJ

omit [IsNoetherianRing R] in
/-- Helper for Lemma 15.126.4: once the parameter ideals agree, both the system-of-parameters
property and the quotient length transport across that equality. -/
private theorem isSystemOfParameters_and_length_eq_of_parameterIdeal_eq {d : ℕ}
    (x y : Fin d → maximalIdeal R) (hx : IsSystemOfParameters x)
    (hxy : parameterIdeal x = parameterIdeal y) :
    IsSystemOfParameters y ∧
      Module.length R (R ⧸ parameterIdeal x) =
        Module.length R (R ⧸ parameterIdeal y) := by
  constructor
  · -- Keep the dimension clause and rewrite the ideal-of-definition clause.
    rw [isSystemOfParameters_iff] at hx ⊢
    exact ⟨hx.1, hxy ▸ hx.2⟩
  · -- Equal ideals define equivalent quotient modules, so their lengths coincide.
    exact LinearEquiv.length_eq (Submodule.quotEquivOfEq _ _ hxy)

/-- Lemma 15.126.4: in a two-dimensional Noetherian local ring, if `f ∈ maximalIdeal R` avoids
all minimal primes, then there exist `g ∈ maximalIdeal R` and an exponent `n` (equivalently
`N = n + 1`) such that `Fin.cons f ![g]` is a system of parameters, and every perturbation of the
head entry by an element of `(maximalIdeal R)^(n + 1)` preserves the system of parameters and the
quotient length. -/
theorem exists_systemOfParameters_cons_singleton_stable_under_highOrder_perturbation_of_not_mem_minimalPrimes
    (hdim : ringKrullDim R = 2) (f : maximalIdeal R)
    (hmin : ∀ p ∈ minimalPrimes R, (f : R) ∉ p) :
    ∃ g : maximalIdeal R, ∃ n : ℕ,
      IsSystemOfParameters (Fin.cons f ![g]) ∧
        ∀ h : maximalIdeal R, ((h : R) ∈ maximalIdeal R ^ (n + 1)) →
          IsSystemOfParameters (Fin.cons (f + h) ![g]) ∧
              Module.length R (R ⧸ parameterIdeal (Fin.cons f ![g])) =
              Module.length R (R ⧸ parameterIdeal (Fin.cons (f + h) ![g])) := by
  rcases
    exists_systemOfParameters_cons_mem_maximalIdeal_pow_of_not_mem_minimalPrimes
      (R := R) (d := 1) (k := 1) hdim f hmin with
    ⟨y, hy, _hyPow⟩
  have hy_eq : y = ![y 0] := by
    ext i
    fin_cases i
    rfl
  have hsop : IsSystemOfParameters (Fin.cons f ![y 0]) := by
    rw [← hy_eq]
    exact hy
  have hrad :
      (parameterIdeal (Fin.cons f ![y 0])).radical = maximalIdeal R := by
    simpa [Ideal.IsIdealOfDefinition] using hsop.2
  have hrad_le :
      maximalIdeal R ≤ (parameterIdeal (Fin.cons f ![y 0])).radical := by
    exact hrad.symm.le
  obtain ⟨n, hn⟩ :
      ∃ n : ℕ, maximalIdeal R ^ n ≤ parameterIdeal (Fin.cons f ![y 0]) := by
    exact
      Ideal.exists_pow_le_of_le_radical_of_fg hrad_le
        (show (maximalIdeal R).FG from Ideal.fg_of_isNoetherianRing (maximalIdeal R))
  refine ⟨y 0, n, hsop, ?_⟩
  intro h hh
  have hhMul :
      (h : R) ∈ maximalIdeal R * parameterIdeal (Fin.cons f ![y 0]) := by
    exact
      maximalIdeal_pow_succ_le_mul_parameterIdeal_of_pow_le (R := R)
        (I := parameterIdeal (Fin.cons f ![y 0])) hn hh
  have hparam :
      parameterIdeal (Fin.cons (f + h) ![y 0]) = parameterIdeal (Fin.cons f ![y 0]) := by
    exact parameterIdeal_cons_singleton_eq_of_mem_maximalIdeal_mul (R := R) f (y 0) h hhMul
  -- The perturbation preserves the parameter ideal, so both owner-level conclusions transport.
  rcases
    isSystemOfParameters_and_length_eq_of_parameterIdeal_eq
      (R := R) (Fin.cons f ![y 0]) (Fin.cons (f + h) ![y 0]) hsop hparam.symm with
    ⟨hpert, hlen⟩
  exact ⟨hpert, hlen⟩

end
