import Mathlib
import StacksProject_2024.stacks_project.Chap12.Lemma_12_25_4
import StacksProject_2024.stacks_project.Chap12.Lemma_12_26_2
import StacksProject_2024.stacks_project.Chap15.Lemma_15_28_12
import StacksProject_2024.stacks_project.Chap15.Definition_15_30_1
import StacksProject_2024.stacks_project.Chap15.Lemma_15_30_3
import StacksProject_2024.stacks_project.Chap15.Lemma_15_30_5
import StacksProject_2024.stacks_project.Chap15.Lemma_15_30_6
import StacksProject_2024.stacks_project.Chap15.Lemma_15_30_10
import StacksProject_2024.stacks_project.Chap15.Lemma_15_30_11

-- Declarations for this item will be appended below by the statement pipeline.

universe u

namespace RingTheory.Sequence

variable {A : Type u} [CommRing A]

open scoped KoszulComplex

/- Domain triage:
* primary domain: Koszul-regular finite sequences in commutative algebra and their behavior under
  passage to the quotient by the ideal generated by an initial block;
* sampled owner declarations: `RingTheory.Sequence.IsKoszulRegularSequence`,
  `RingTheory.Sequence.isKoszulRegularSequence_quotient_of_append`,
  `RingTheory.Sequence.isH1RegularSequence_append_of_quotient`,
  `RingTheory.Sequence.isKoszulRegularSequence_of_span_eq`;
* best owner abstraction: the finite-family predicate `IsKoszulRegularSequence`, with the quotient
  ring canonically taken by the prefix ideal `Ideal.span (Set.range f)`;
* primitive data vs derived API: the primitive source data are only the families `f` and `g`
  together with the regularity hypotheses; an extra ideal parameter `I` and equality witness
  `Ideal.span (Set.range f) = I` are derived presentation data and should not remain in the public
  statement;
* layer: `bridge/view`, since the source-facing append theorem is expressed directly through the
  owner predicate rather than through an auxiliary named-ideal wrapper.
-/

-- Proof sketch: identify the Koszul complex on `Fin.append f g` with the total complex of the
-- tensor product of the Koszul complexes on `f` and `g`. The hypothesis on `f` makes the first
-- factor a finite free resolution of `A ⧸ Ideal.span (Set.range f)`, so tensoring with the second
-- factor identifies this total complex with the Koszul complex of the image family of `g` in that
-- quotient ring. The quotient-side Koszul-regularity assumption then gives the required vanishing
-- of all positive homology.
/-- Helper for Lemma 15.30.13: the Koszul hypotheses already force the appended family to be
`H_1`-regular. -/
private theorem append_isH1Regular_of_quotient_koszul {n m : ℕ} (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f)
    (hg : IsKoszulRegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j))) :
    IsH1RegularSequence (Fin.append f g) := by
  -- First downgrade both Koszul-regular hypotheses to the `H₁`-regular statements consumed by
  -- Lemma `15.30.11`.
  have hf_h1 : IsH1RegularSequence f :=
    isH1RegularSequence_of_isKoszulRegularSequence hf
  have hg_h1 :
      IsH1RegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j)) :=
    isH1RegularSequence_of_isKoszulRegularSequence hg
  -- Then apply the owner-level append theorem for `H₁`-regularity over the quotient.
  exact isH1RegularSequence_append_of_quotient f g hf_h1 hg_h1

/-- Helper for Lemma 15.30.13: the same hypotheses also give quasi-regularity of the appended
list presentation. -/
private theorem append_isQuasiRegular_of_quotient_koszul {n m : ℕ} (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f)
    (hg : IsKoszulRegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j))) :
    IsQuasiRegularSequence (List.ofFn f ++ List.ofFn g) := by
  -- Convert the prefix hypothesis to quasi-regularity through the chapter bridge
  -- `Koszul-regular => H₁-regular => quasi-regular`.
  have hf_h1 : IsH1RegularSequence f :=
    isH1RegularSequence_of_isKoszulRegularSequence hf
  have hf_quasi : IsQuasiRegularSequence (List.ofFn f) := by
    simpa [IsH1RegularSequence] using hf_h1.isQuasiRegular
  -- The quotient-side Koszul hypothesis likewise provides the `H₁`-regular tail input.
  have hg_h1 :
      IsH1RegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j)) :=
    isH1RegularSequence_of_isKoszulRegularSequence hg
  -- Now apply the source-facing append theorem for quasi-regularity.
  exact isQuasiRegularSequence_append_of_quotient_h1Regular f g hf_quasi hg_h1

-- Route correction: the two easy prefix consequences are now verified above. The remaining gap is
-- only the source-faithful homology comparison from the quotient-side Koszul complex on `g mod (f)`
-- to the appended Koszul complex on `Fin.append f g`.
/-- Helper for Lemma 15.30.13: the canonical prefix ideal generated by the family `f`. -/
private abbrev append_prefix_ideal {n : ℕ} (f : Fin n → A) : Ideal A :=
  Ideal.span (Set.range f)

/-- Helper for Lemma 15.30.13: the quotient-side tail family obtained by reducing `g` modulo the
prefix ideal generated by `f`. -/
private abbrev append_quotient_family {n m : ℕ} (f : Fin n → A) (g : Fin m → A) :
    Fin m → A ⧸ append_prefix_ideal f :=
  fun j ↦ Ideal.Quotient.mk (append_prefix_ideal f) (g j)

/-- Helper for Lemma 15.30.13: restriction of scalars from the quotient ring `A / (f)` back to
`A`. -/
private noncomputable abbrev append_quotient_restrictScalars {n : ℕ} (f : Fin n → A) :
    CategoryTheory.Functor (ModuleCat (A ⧸ (append_prefix_ideal f))) (ModuleCat A) :=
  ModuleCat.restrictScalars (Ideal.Quotient.mk (append_prefix_ideal f))

/-- Helper for Lemma 15.30.13: the quotient-side Koszul complex on `g mod (f)`, viewed back in
`ModuleCat A` via restriction of scalars. -/
private noncomputable abbrev append_quotient_koszul_restrict {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) : ChainComplex (ModuleCat A) ℕ :=
  ((append_quotient_restrictScalars f).mapHomologicalComplex (ComplexShape.down ℕ)).obj
    (koszulComplex (koszulLinearForm (append_quotient_family f g)))

/-- Helper for Lemma 15.30.13: the appended-side tensor bicomplex with stable owner
`K^•(f)_p ⊗ K^•(g)_q`. -/
private noncomputable abbrev append_tensor_bicomplex {n m : ℕ} (f : Fin n → A) (g : Fin m → A) :
    HomologicalComplex₂ (ModuleCat A) (ComplexShape.down ℕ) (ComplexShape.down ℕ) :=
  ((((CategoryTheory.MonoidalCategory.curriedTensor (ModuleCat A)).mapBifunctorHomologicalComplex
      (ComplexShape.down ℕ) (ComplexShape.down ℕ)).obj
        (koszulComplex (koszulLinearForm f))).obj
          (koszulComplex (koszulLinearForm g)))

/-- Helper for Lemma 15.30.13: totalizing the fixed tensor bicomplex gives the ordinary tensor
product complex without further transport. -/
private noncomputable def append_tensor_bicomplex_total_iso_tensorObj {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    HomologicalComplex₂.total (append_tensor_bicomplex f g) (ComplexShape.down ℕ) ≅
      HomologicalComplex.tensorObj
        (koszulComplex (koszulLinearForm f))
        (koszulComplex (koszulLinearForm g)) :=
  CategoryTheory.Iso.refl _

/-- Helper for Lemma 15.30.13: reindexing both tensor-bicomplex directions along
`embeddingDownNat` packages the chain-level tensor bicomplex as a cochain bicomplex on `up ℤ`. -/
private noncomputable abbrev append_reindexed_tensor_bicomplex {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    HomologicalComplex₂ (ModuleCat A) (ComplexShape.up ℤ) (ComplexShape.up ℤ) :=
  ((((ComplexShape.embeddingDownNat.extendFunctor (ModuleCat A)).mapHomologicalComplex
      (ComplexShape.down ℕ)).obj (append_tensor_bicomplex f g)).extend
        ComplexShape.embeddingDownNat)

/-- Helper for Lemma 15.30.13: totalizing the doubly reindexed tensor bicomplex is just the
outer `embeddingDownNat` reindexing of the original nat-indexed total complex. -/
private noncomputable def append_reindexed_tensor_total_iso {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    HomologicalComplex₂.total (append_reindexed_tensor_bicomplex f g) (ComplexShape.up ℤ) ≅
      (HomologicalComplex₂.total (append_tensor_bicomplex f g)
        (ComplexShape.down ℕ)).extend ComplexShape.embeddingDownNat :=
  CategoryTheory.Iso.refl _

/-- Helper for Lemma 15.30.13: the natural `embeddingDownNat` reindexing leaves the tensor
bicomplex supported only in nonpositive horizontal degrees. -/
private theorem append_reindexed_tensor_isZero_X_of_pos {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) {p : ℤ} (hp : 0 < p) :
    CategoryTheory.Limits.IsZero ((append_reindexed_tensor_bicomplex f g).X p) := by
  -- The outer `embeddingDownNat` extension only hits degrees `-n`, so every positive row is zero.
  exact
    ((((ComplexShape.embeddingDownNat.extendFunctor (ModuleCat A)).mapHomologicalComplex
        (ComplexShape.down ℕ)).obj (append_tensor_bicomplex f g)).isZero_extend_X
          ComplexShape.embeddingDownNat p (fun j hj ↦ by
            have hnonpos : (ComplexShape.embeddingDownNat.f j : ℤ) ≤ 0 := by
              simp [ComplexShape.embeddingDownNat]
            rw [hj] at hnonpos
            omega))

/-- Helper for Lemma 15.30.13: consequently every term of the reindexed tensor bicomplex with
positive horizontal degree vanishes. -/
private theorem append_reindexed_tensor_isZero_of_pos {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) {p q : ℤ} (hp : 0 < p) :
    CategoryTheory.Limits.IsZero (((append_reindexed_tensor_bicomplex f g).X p).X q) := by
  -- Evaluating a zero horizontal row at any vertical degree still gives a zero object.
  exact
    (HomologicalComplex.eval (ModuleCat A) (ComplexShape.up ℤ) q).map_isZero
      (append_reindexed_tensor_isZero_X_of_pos f g hp)

/-- Helper for Lemma 15.30.13: every term of the reindexed tensor bicomplex with positive
vertical degree vanishes as well. -/
private theorem append_reindexed_tensor_isZero_of_vertical_pos {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) {p q : ℤ} (hq : 0 < q) :
    CategoryTheory.Limits.IsZero (((append_reindexed_tensor_bicomplex f g).X p).X q) := by
  by_cases hp : 0 < p
  · -- Positive horizontal degree is already impossible after the outer `embeddingDownNat`
    -- reindexing.
    exact append_reindexed_tensor_isZero_of_pos f g hp
  · have hp_le : p ≤ 0 := le_of_not_gt hp
    let k : ℕ := Int.toNat (-p)
    have hk : (ComplexShape.embeddingDownNat.f k : ℤ) = p := by
      dsimp [k, ComplexShape.embeddingDownNat]
      have hnonneg : 0 ≤ -p := by omega
      rw [Int.toNat_of_nonneg hnonneg]
      omega
    let B :=
      (((ComplexShape.embeddingDownNat.extendFunctor (ModuleCat A)).mapHomologicalComplex
        (ComplexShape.down ℕ)).obj (append_tensor_bicomplex f g))
    have hzero_row_component : CategoryTheory.Limits.IsZero ((B.X k).X q) := by
      -- The vertical direction of `B.X k` is itself an `embeddingDownNat` extension of a chain
      -- complex, so its positive degrees vanish.
      change CategoryTheory.Limits.IsZero
        ((((append_tensor_bicomplex f g).X k).extend ComplexShape.embeddingDownNat).X q)
      exact
        ((append_tensor_bicomplex f g).X k).isZero_extend_X
          ComplexShape.embeddingDownNat q (fun j hj ↦ by
            have hnonpos : (ComplexShape.embeddingDownNat.f j : ℤ) ≤ 0 := by
              simp [ComplexShape.embeddingDownNat]
            rw [hj] at hnonpos
            omega)
    let ep : (append_reindexed_tensor_bicomplex f g).X p ≅ B.X k :=
      B.extendXIso ComplexShape.embeddingDownNat hk
    -- Transport the positive-degree vanishing across the horizontal `extendXIso`.
    exact IsZero.of_iso hzero_row_component
      ((HomologicalComplex.eval (ModuleCat A) (ComplexShape.up ℤ) q).mapIso ep)

/-- Helper for Lemma 15.30.13: after reindexing both tensor directions by
`embeddingDownNat`, the tensor bicomplex has finite antidiagonal support. -/
private theorem append_reindexed_tensor_has_finite_antidiagonal_support {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    CategoryTheory.doubleComplexHasFiniteAntidiagonalSupport
      (append_reindexed_tensor_bicomplex f g) := by
  intro t
  -- A nonzero term on the antidiagonal `p + q = t` must satisfy `p ≤ 0` and `q ≤ 0`, hence
  -- `t ≤ p ≤ 0`.
  refine (Set.finite_Icc t 0).subset ?_
  intro p hp
  constructor
  · by_contra hpt
    have hq_pos : 0 < t - p := by omega
    have hzero :
        CategoryTheory.Limits.IsZero
          (((append_reindexed_tensor_bicomplex f g).X p).X (t - p)) :=
      append_reindexed_tensor_isZero_of_vertical_pos f g hq_pos
    exact hp hzero
  · by_contra hp0
    have hp_pos : 0 < p := by omega
    have hzero :
        CategoryTheory.Limits.IsZero
          (((append_reindexed_tensor_bicomplex f g).X p).X (t - p)) :=
      append_reindexed_tensor_isZero_of_pos f g hp_pos
    exact hp hzero

/-- Helper for Lemma 15.30.13: the appended Koszul complex has the same homology as the total of
the fixed tensor bicomplex. -/
private noncomputable def append_koszul_homology_iso_tensor_bicomplex_total {n m i : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    ((koszulComplex (koszulLinearForm (Fin.append f g))).homology i) ≅
      (HomologicalComplex₂.total (append_tensor_bicomplex f g) (ComplexShape.down ℕ)).homology i := by
  -- First identify the appended Koszul complex with the ordinary tensor product complex, then
  -- rewrite that tensor complex to the chosen total owner once and for all.
  exact
    HomologicalComplex.homologyMapIso
      ((koszulComplexOn_append_iso_tensorObj f g) ≪≫
        (append_tensor_bicomplex_total_iso_tensorObj f g).symm) i

/-- Helper for Lemma 15.30.13: restricting scalars on the quotient-side Koszul complex commutes
with taking homology. -/
private noncomputable def append_koszul_restrictScalars_homology_iso {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) (i : ℕ) :
    (append_quotient_koszul_restrict f g).homology i ≅
      (append_quotient_restrictScalars f).obj
        ((koszulComplex (koszulLinearForm (append_quotient_family f g))).homology i) := by
  -- This is the standard homology transport for `mapHomologicalComplex`.
  simpa [append_quotient_koszul_restrict] using
    ((koszulComplex (koszulLinearForm (append_quotient_family f g))).sc i).mapHomologyIso
      (append_quotient_restrictScalars f)

/-- Helper for Lemma 15.30.13: zero homology on the restricted quotient-side complex is equivalent
to zero homology on the unreduced quotient-side complex after applying restriction of scalars. -/
private theorem append_koszul_restrictScalars_homology_isZero_iff {n m i : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    CategoryTheory.Limits.IsZero ((append_quotient_koszul_restrict f g).homology i) ↔
      CategoryTheory.Limits.IsZero
        ((append_quotient_restrictScalars f).obj
          ((koszulComplex (koszulLinearForm (append_quotient_family f g))).homology i)) := by
  -- The two homology objects differ only by the canonical restriction-of-scalars comparison.
  exact (append_koszul_restrictScalars_homology_iso f g i).isZero_iff

/-- Helper for Lemma 15.30.13: the quotient-side Koszul-regularity hypothesis still kills positive
homology after restricting scalars back to `A`. -/
private theorem append_koszul_quotient_homology_isZero_restrict {n m i : ℕ}
    (f : Fin n → A) (g : Fin m → A)
    (hg : IsKoszulRegularSequence (append_quotient_family f g))
    (hi : 1 ≤ i) :
    CategoryTheory.Limits.IsZero ((append_quotient_koszul_restrict f g).homology i) := by
  -- First read the quotient-side hypothesis as vanishing of the quotient-side Koszul homology.
  rw [isKoszulRegularSequence_iff] at hg
  have hzero_quotient :
      CategoryTheory.Limits.IsZero
        ((koszulComplex (koszulLinearForm (append_quotient_family f g))).homology i) :=
    hg i hi
  have hzero_restricted :
      CategoryTheory.Limits.IsZero
        ((append_quotient_restrictScalars f).obj
          ((koszulComplex (koszulLinearForm (append_quotient_family f g))).homology i)) :=
    CategoryTheory.Functor.map_isZero (append_quotient_restrictScalars f) hzero_quotient
  -- Then transport that vanishing back across the canonical homology comparison isomorphism.
  exact (append_koszul_restrictScalars_homology_isZero_iff f g).2 hzero_restricted

/-- Helper for Lemma 15.30.13: after reindexing both complexes from `down ℕ` to `up ℤ`, the
canonical tensor-total comparison onto the quotient-side Koszul complex is a quasi-isomorphism. -/
/-- Helper for Lemma 15.30.13: the tensor bicomplex viewed as an augmented row of cochain
complexes after reindexing each fixed row by `embeddingDownNat`. -/
private noncomputable abbrev append_tensor_row_resolution {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :=
  (((ComplexShape.embeddingDownNat.extendFunctor (ModuleCat A)).mapHomologicalComplex
      (ComplexShape.down ℕ)).obj (append_tensor_bicomplex f g))

/-- Helper for Lemma 15.30.13: the explicit augmentation from the horizontal degree-`0` row of
the tensor bicomplex to the quotient-side Koszul complex. -/
private noncomputable def append_tensor_zero_row_to_quotient {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    (append_tensor_row_resolution f g).X 0 ⟶
      (append_quotient_koszul_restrict f g).extend ComplexShape.embeddingDownNat := by
  -- Route correction: isolate the source-proof augmentation first. The remaining work is to write
  -- the degreewise quotient map `A ⊗ K_q(g) → (A / (f)) ⊗ K_q(g)` and then transport it through
  -- the canonical identification with `K_q(A / (f), g mod (f))`.
  -- TODO(Lemma 15.30.13): define the degreewise quotient projection on the `K(f)_0 ≅ A` factor,
  -- prove it commutes with the vertical Koszul differentials in `q`, and package the result as a
  -- chain map from the row `p = 0` to the quotient-side Koszul complex.
  sorry

/-- Helper for Lemma 15.30.13: the concrete comparison map from the tensor total complex to the
quotient-side Koszul complex. -/
private noncomputable def append_tensor_total_to_quotient_extend_map {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) :
    (HomologicalComplex₂.total (append_tensor_bicomplex f g)
      (ComplexShape.down ℕ)).extend ComplexShape.embeddingDownNat ⟶
      (append_quotient_koszul_restrict f g).extend ComplexShape.embeddingDownNat :=
  (append_reindexed_tensor_total_iso f g).inv.hom ≫
    augmentedTotalTo (append_tensor_row_resolution f g)
      (append_tensor_zero_row_to_quotient f g)

/-- Helper for Lemma 15.30.13: after reindexing both complexes from `down ℕ` to `up ℤ`, the
canonical tensor-total comparison onto the quotient-side Koszul complex is a quasi-isomorphism. -/
private theorem append_tensor_total_to_quotient_extend_quasiIso {n m : ℕ}
    (f : Fin n → A) (g : Fin m → A) (hf : IsKoszulRegularSequence f) :
    ∃ ψ :
        (HomologicalComplex₂.total (append_tensor_bicomplex f g)
          (ComplexShape.down ℕ)).extend ComplexShape.embeddingDownNat ⟶
          (append_quotient_koszul_restrict f g).extend ComplexShape.embeddingDownNat,
      QuasiIso ψ := by
  refine ⟨append_tensor_total_to_quotient_extend_map f g, ?_⟩
  -- Route correction: the source proof compares the tensor total to the quotient complex through
  -- the horizontal-degree-zero cokernel, so the canonical map goes from `Tot` to the quotient
  -- complex, not the other way around.
  -- The main remaining bicomplex input is now the specialized nonpositive-row comparison in this
  -- correct direction; once that is built, the positive-degree homology comparison below becomes a
  -- formal transport through `extendHomologyIso` and the fixed tensor-total model.
  have hsupport :
      ∀ p q : ℤ, 0 < p → CategoryTheory.Limits.IsZero
        (((append_reindexed_tensor_bicomplex f g).X p).X q) := by
    intro p q hp
    exact append_reindexed_tensor_isZero_of_pos f g hp
  have hfin :
      CategoryTheory.doubleComplexHasFiniteAntidiagonalSupport
        (append_reindexed_tensor_bicomplex f g) :=
    append_reindexed_tensor_has_finite_antidiagonal_support f g
  -- The explicit map is now fixed as `append_tensor_total_to_quotient_extend_map`. The remaining
  -- source-faithful blocker is to verify the augmented-row hypotheses needed for
  -- `total_quasiIso_of_exact_augmented_row_and_kernel_rows`: exactness of the negative rows from
  -- `hf`, identification of the degree-`0` augmentation with the quotient-side Koszul complex,
  -- and exactness of the induced kernel rows.
  -- TODO(Lemma 15.30.13): prove the row exactness and kernel-row exactness hypotheses for
  -- `append_tensor_row_resolution f g` and `append_tensor_zero_row_to_quotient f g`, then apply
  -- `total_quasiIso_of_exact_augmented_row_and_kernel_rows` to the fixed map above.
  sorry

/-- Helper for Lemma 15.30.13: in every positive degree, the appended Koszul complex has the same
homology as the quotient-side Koszul complex on `g`, viewed back in `ModuleCat A`. -/
private noncomputable def append_koszul_positive_homology_iso_restrict_quotient {n m i : ℕ}
    (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f) (_hi : 1 ≤ i) :
    ((koszulComplex (koszulLinearForm (Fin.append f g))).homology i) ≅
      ((append_quotient_koszul_restrict f g).homology i) := by
  classical
  -- Move the tensor-total-to-quotient comparison to the common `up ℤ` indexing, where the
  -- remaining row-comparison theorem lives.
  let ψ := Classical.choose (append_tensor_total_to_quotient_extend_quasiIso f g hf)
  let hψ := Classical.choose_spec (append_tensor_total_to_quotient_extend_quasiIso f g hf)
  letI : QuasiIso ψ := hψ
  let eQuotientUp :=
    (append_quotient_koszul_restrict f g).extendHomologyIso
      ComplexShape.embeddingDownNat
      (show ComplexShape.embeddingDownNat.f i = -((i : ℕ) : ℤ) by rfl)
  let eTotalUp :=
    (HomologicalComplex₂.total (append_tensor_bicomplex f g)
      (ComplexShape.down ℕ)).extendHomologyIso
        ComplexShape.embeddingDownNat
        (show ComplexShape.embeddingDownNat.f i = -((i : ℕ) : ℤ) by rfl)
  let eComparison :=
    CategoryTheory.asIso (HomologicalComplex.homologyMap ψ (-((i : ℕ) : ℤ)))
  -- The appended side already identifies with the nat-indexed total tensor complex, so only the
  -- formal reindexing transport and the forward reindexed quasi-isomorphism remain.
  exact
    append_koszul_homology_iso_tensor_bicomplex_total f g ≪≫
      eTotalUp.symm ≪≫
      eComparison ≪≫
      eQuotientUp

/-- Helper for Lemma 15.30.13: once the quotient-to-append bicomplex comparison is built, every
positive homology object of the appended Koszul complex vanishes. -/
private theorem append_koszul_homology_isZero_of_quotient {n m i : ℕ}
    (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f)
    (hg : IsKoszulRegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j)))
    (hi : 1 ≤ i) :
    CategoryTheory.Limits.IsZero
      ((koszulComplex (koszulLinearForm (Fin.append f g))).homology i) := by
  have hzero_restrict := append_koszul_quotient_homology_isZero_restrict f g hg hi
  -- Transport the quotient-side vanishing across the isolated positive-degree homology
  -- comparison. This leaves only the bicomplex comparison theorem itself as the remaining blocker.
  simpa using hzero_restrict.of_iso
    (append_koszul_positive_homology_iso_restrict_quotient f g hf hi)

/-- Lemma 15.30.13: if `f` is a Koszul-regular sequence in `A`, and the images of `g` form a
Koszul-regular sequence in the quotient ring `A ⧸ Ideal.span (Set.range f)`, then the concatenated
sequence `Fin.append f g` is Koszul-regular in `A`. -/
theorem isKoszulRegularSequence_append_of_quotient {n m : ℕ} (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f)
    (hg : IsKoszulRegularSequence (fun j ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g j))) :
    IsKoszulRegularSequence (Fin.append f g) := by
  -- First rewrite the target owner predicate into positive Koszul-homology vanishing.
  rw [isKoszulRegularSequence_iff]
  intro i hi
  -- The remaining work is exactly the isolated bicomplex-comparison helper above.
  exact append_koszul_homology_isZero_of_quotient f g hf hg hi

end RingTheory.Sequence
