import Mathlib
import Mathlib.Data.List.TFAE
import StacksProject_2024.stacks_project.Chap10.Lemma_10_20_1_Nakayama_s_lemma
import StacksProject_2024.stacks_project.Chap15.Definition_15_8_3

-- Declarations for this item will be appended below by the statement pipeline.

open scoped FittingIdeal TensorProduct

universe u v

/-
Domain-style sampling for Lemma 15.8.7:
- primary domain: commutative algebra of finite modules, Fitting ideals, residue-field fibers, and
  local generation after localization;
- sampled owner-level declarations:
  `fittingIdeal`,
  `fittingIdeal_baseChange`,
  `Module.finrank`,
  `exists_sub_one_mem_and_span_localized_eq_top_of_quotient_span_eq_top`;
- best owner abstraction: clause (1) should use the chapter owner `fittingIdeal` directly, via the
  canonical notation `Fit[R]_(k)(M)`, while clauses (3) and (4) use the intrinsic generation
  owner `Submodule.span ... = ⊤` rather than introducing a parallel wrapper for "generated by
  `k` elements";
- primitive data: the finite module `M`, the integer `k`, and the prime ideal `p`;
- derived API: the residue-field finrank criterion, the at-prime generation criterion, and the
  away-local generation criterion linked by base change and Nakayama.

Source/core/bridge triage:
- `source-facing`: the four equivalent conditions of Lemma 15.8.7;
- `core/canonical`: `fittingIdeal` and the canonical localization/base-change objects;
- `bridge/view`: the residue-field finrank test and the localized generation clauses. -/

section

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M] [Module.Finite R M]

/-- Helper for Lemma 15.8.7: over a field, the `k`th Fitting ideal of the standard free module of
rank `n` is `0` for `k < n` and the unit ideal for `n ≤ k`. -/
private theorem fittingIdeal_free_eq_zero_or_top_of_field
    {K : Type*} [Field K] (n k : ℕ) :
    Fit[K]_(k)(Fin n → K) = if k < n then ⊥ else ⊤ := by
  let π : (Fin n → K) →ₗ[K] (Fin n → K) := LinearMap.id
  have hπ : Function.Surjective π := by
    intro x
    exact ⟨x, rfl⟩
  -- Compute the intrinsic Fitting ideal from the identity presentation of the free module.
  rw [fittingIdeal_eq_presentationFittingIdeal (R := K) (M := Fin n → K) k π hπ]
  by_cases hk : k < n
  · have hnk : 0 < n - k := Nat.sub_pos_of_lt hk
    -- When the requested minors have positive size, every column of the identity-presentation
    -- kernel matrix is zero, so every determinant vanishes.
    rw [presentationFittingIdeal, if_pos hk, Matrix.minorIdeal, Ideal.span_eq_bot]
    intro x hx
    rcases hx with ⟨⟨e₁, e₂⟩, rfl⟩
    exact Matrix.det_eq_zero_of_row_eq_zero ⟨0, hnk⟩ fun j ↦ by
      have he₂j : (((e₂ j : LinearMap.ker π) : Fin n → K)) = 0 := by
        exact LinearMap.mem_ker.mp (e₂ j).property
      simpa [he₂j]
  · have hk' : n ≤ k := Nat.le_of_not_gt hk
    -- Once `k` reaches the rank, the presentation-level Fitting ideal is already the unit ideal.
    rw [if_neg hk]
    simpa [π] using
      presentationFittingIdeal_eq_top_of_le (R := K) (M := Fin n → K) hk' π

/-- Helper for Lemma 15.8.7: over a field, noncontainment of the `k`th Fitting ideal in `0` is
equivalent to the vector-space dimension being at most `k`. -/
private theorem fittingIdeal_not_le_bot_iff_finrank_le_of_field
    {K : Type*} [Field K]
    {V : Type*} [AddCommGroup V] [Module K V] [Module.Finite K V]
    (k : ℕ) :
    (¬ Fit[K]_(k)(V) ≤ (⊥ : Ideal K)) ↔ Module.finrank K V ≤ k := by
  let e : V ≃ₗ[K] (Fin (Module.finrank K V) → K) := (Module.finBasis K V).equivFun
  have hfit :
      Fit[K]_(k)(V) = Fit[K]_(k)(Fin (Module.finrank K V) → K) := by
    simpa using fittingIdeal_eq_of_linearEquiv (R := K) (M := V) (k := k) e
  -- Transport the problem to the standard free module of rank `finrank K V`.
  rw [hfit, fittingIdeal_free_eq_zero_or_top_of_field]
  by_cases hk : k < Module.finrank K V
  · have hnot : ¬ Module.finrank K V ≤ k := Nat.not_le_of_gt hk
    simp [hk, hnot]
  · have hk' : Module.finrank K V ≤ k := Nat.le_of_not_gt hk
    simp [hk, hk']

/-- Helper for Lemma 15.8.7: a finite-dimensional vector space of dimension at most `k` is
generated by `k` vectors. -/
private theorem exists_generators_of_finrank_le_of_field
    {K : Type*} [Field K]
    {V : Type*} [AddCommGroup V] [Module K V] [Module.Finite K V]
    {k : ℕ} (hk : Module.finrank K V ≤ k) :
    ∃ v : Fin k → V, Submodule.span K (Set.range v) = ⊤ := by
  let r := Module.finrank K V
  let e : V ≃ₗ[K] (Fin r → K) := (Module.finBasis K V).equivFun
  let ρ : (Fin k → K) →ₗ[K] (Fin r → K) :=
    LinearMap.pi fun i : Fin r ↦ LinearMap.proj (Fin.castLE hk i)
  have hρ : Function.Surjective ρ := by
    -- Extend a coordinate vector on `Fin r` by zero on the remaining coordinates.
    intro y
    refine ⟨fun i ↦ if h : i.1 < r then y ⟨i.1, h⟩ else 0, ?_⟩
    ext i
    simp [ρ, i.2]
  let σ : (Fin k → K) →ₗ[K] V := e.symm.toLinearMap.comp ρ
  have hσ : Function.Surjective σ := e.symm.surjective.comp hρ
  let v : Fin k → V := fun i ↦ σ (Pi.single i (1 : K))
  have hlin : Fintype.linearCombination K v = σ := by
    -- The standard coordinate vectors of `Fin k → K` recover the original linear map `σ`.
    apply LinearMap.ext
    intro x
    calc
      (Fintype.linearCombination K v) x
          = ∑ i, x i • σ (Pi.single i (1 : K)) := by
              simp [v, Fintype.linearCombination_apply]
      _ = ∑ i, σ (x i • (Pi.single i (1 : K) : Fin k → K)) := by
            congr with i
            exact (σ.map_smul (x i) (Pi.single i (1 : K))).symm
      _ = σ (∑ i, x i • (Pi.single i (1 : K) : Fin k → K)) := by
            symm
            simp [map_sum]
      _ = σ x := by
            congr 1
            ext i
            simpa [Pi.single_apply, mul_comm] using
              (Fintype.sum_pi_single (i := i) (f := x))
  refine ⟨v, ?_⟩
  -- Rephrase the surjective coordinate map as a spanning statement.
  rw [span_range_eq_top_iff_surjective_fintypeLinearCombination]
  intro x
  rcases hσ x with ⟨c, rfl⟩
  refine ⟨c, ?_⟩
  simpa [hlin]

/-- Helper for Lemma 15.8.7: the maximal-ideal residue field of a local ring agrees with its
ambient residue field. -/
private noncomputable abbrev maximalIdeal_residueField_equiv
    (A : Type*) [CommRing A] [IsLocalRing A] :
    (IsLocalRing.maximalIdeal A).ResidueField ≃+* IsLocalRing.ResidueField A :=
  (RingEquiv.ofBijective
    (algebraMap (IsLocalRing.ResidueField A) (IsLocalRing.maximalIdeal A).ResidueField)
    (Ideal.bijective_algebraMap_quotient_residueField (IsLocalRing.maximalIdeal A))).symm

/-- Helper for Lemma 15.8.7: the maximal-ideal residue-field identification sends a residue class
to the canonical local residue class. -/
private theorem maximalIdeal_residueField_equiv_apply_algebraMap
    (A : Type*) [CommRing A] [IsLocalRing A] (a : A) :
    maximalIdeal_residueField_equiv A
        (algebraMap A (IsLocalRing.maximalIdeal A).ResidueField a) =
      IsLocalRing.residue A a := by
  -- Both residue-field models of `A` represent the same class of `a`.
  rw [show algebraMap A (IsLocalRing.maximalIdeal A).ResidueField a =
      algebraMap (IsLocalRing.ResidueField A)
        (IsLocalRing.maximalIdeal A).ResidueField (IsLocalRing.residue A a) by rfl]
  change
    maximalIdeal_residueField_equiv A
        ((maximalIdeal_residueField_equiv A).symm (IsLocalRing.residue A a)) =
      IsLocalRing.residue A a
  exact (maximalIdeal_residueField_equiv A).apply_symm_apply (IsLocalRing.residue A a)

/-- Helper for Lemma 15.8.7: localizing at a prime does not change the corresponding residue
field. -/
private noncomputable abbrev prime_localization_residueField_equiv
    (p : Ideal R) [p.IsPrime] :
    IsLocalRing.ResidueField (Localization.AtPrime p) ≃+* p.ResidueField :=
  (maximalIdeal_residueField_equiv (Localization.AtPrime p)).symm.trans <|
    by
      -- Reinterpret the prime residue field as the ambient residue field of the local ring `R_p`.
      change (IsLocalRing.maximalIdeal (Localization.AtPrime p)).ResidueField ≃+* p.ResidueField
      exact maximalIdeal_residueField_equiv (Localization.AtPrime p)

/-- Helper for Lemma 15.8.7: the prime-local residue-field equivalence sends the local residue
class of a base element to its prime-residue-field class. -/
private theorem prime_localization_residueField_equiv_apply_algebraMap
    (p : Ideal R) [p.IsPrime] (a : R) :
    prime_localization_residueField_equiv (R := R) (p := p)
        (algebraMap (Localization.AtPrime p)
          (IsLocalRing.ResidueField (Localization.AtPrime p))
          (algebraMap R (Localization.AtPrime p) a)) =
      algebraMap R p.ResidueField a := by
  -- First identify the chosen equivalence with the local residue class, then rewrite that class in
  -- the prime-residue-field model.
  calc
    prime_localization_residueField_equiv (R := R) (p := p)
        (algebraMap (Localization.AtPrime p)
          (IsLocalRing.ResidueField (Localization.AtPrime p))
          (algebraMap R (Localization.AtPrime p) a)) =
      IsLocalRing.residue (Localization.AtPrime p) (algebraMap R (Localization.AtPrime p) a) := by
        simpa [prime_localization_residueField_equiv, RingEquiv.trans_apply] using
          maximalIdeal_residueField_equiv_apply_algebraMap (Localization.AtPrime p)
            (algebraMap R (Localization.AtPrime p) a)
    _ = algebraMap R p.ResidueField a := by
      rfl

/-- Helper for Lemma 15.8.7: the inverse prime-local residue-field equivalence sends the
prime-residue-field class of a base element to the canonical local residue class. -/
private theorem prime_localization_residueField_equiv_symm_apply_algebraMap
    (p : Ideal R) [p.IsPrime] (a : R) :
    (prime_localization_residueField_equiv (R := R) (p := p)).symm
        (algebraMap R p.ResidueField a) =
      algebraMap (Localization.AtPrime p)
        (IsLocalRing.ResidueField (Localization.AtPrime p))
        (algebraMap R (Localization.AtPrime p) a) := by
  -- Apply the forward formula and invert the residue-field equivalence.
  exact (prime_localization_residueField_equiv (R := R) (p := p)).injective <| by
    rw [RingEquiv.apply_symm_apply,
      prime_localization_residueField_equiv_apply_algebraMap (R := R) (p := p) (a := a)]

/-- Helper for Lemma 15.8.7: if `f ∉ p`, then every power of `f` also avoids `p`. -/
private abbrev prime_compl_of_not_mem
    (p : Ideal R) [p.IsPrime] {f : R} (hf : f ∉ p) :
    p.primeCompl :=
  ⟨f, hf⟩

/-- Helper for Lemma 15.8.7: if `f ∉ p`, then every power of `f` also avoids `p`. -/
private theorem pow_not_mem_prime
    (p : Ideal R) [p.IsPrime] {f : R} (hf : f ∉ p) (n : ℕ) :
    f ^ n ∉ p := by
  -- Prime ideals are radical, so membership of a power forces membership of the base element.
  intro hpow
  exact hf ((inferInstance : p.IsPrime).mem_of_pow_mem n hpow)

/-- Helper for Lemma 15.8.7: if `f ∉ p`, every power of `f` maps into the prime-complement
submonoid used to define `R_p`. -/
private theorem powers_le_primeCompl_comap_of_not_mem
    (p : Ideal R) [p.IsPrime] {f : R} (hf : f ∉ p) :
    Submonoid.powers f ≤ Submonoid.comap (RingHom.id R) p.primeCompl := by
  -- The identity map preserves the fact that every power of `f` stays outside the prime ideal.
  intro x hx
  rcases hx with ⟨n, rfl⟩
  simpa using pow_not_mem_prime (p := p) (f := f) hf n

/-- Helper for Lemma 15.8.7: if `f ∉ p`, then every power of `f` lies in the prime-complement
submonoid of `R`. -/
private theorem powers_le_primeCompl_of_not_mem
    (p : Ideal R) [p.IsPrime] {f : R} (hf : f ∉ p) :
    Submonoid.powers f ≤ p.primeCompl := by
  -- Forget the trivial `RingHom.id` from the localization-ready inclusion above.
  simpa using powers_le_primeCompl_comap_of_not_mem (R := R) (p := p) hf

/-- Helper for Lemma 15.8.7: if `f ∉ p`, there is a canonical comparison map `R_f → R_p`. -/
private noncomputable abbrev awayToAtPrime
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) :
    Localization.Away f →+* Localization.AtPrime p :=
  IsLocalization.map
    (Localization.AtPrime p)
    (RingHom.id R)
    (powers_le_primeCompl_comap_of_not_mem (R := R) (p := p) hf)

/-- Helper for Lemma 15.8.7: the canonical map `R_f → R_p` sends the standard fraction `r / f^n`
to the same fraction in the prime localization. -/
private theorem awayToAtPrime_map_mk'
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) (r : R) (n : ℕ) :
    awayToAtPrime (R := R) p f hf
        (IsLocalization.mk' (Localization.Away f) r (Submonoid.pow f n)) =
      IsLocalization.mk' (Localization.AtPrime p) r
        (prime_compl_of_not_mem (p := p) (hf := pow_not_mem_prime (p := p) (f := f) hf n)) := by
  -- This is the strict transport formula for `IsLocalization.map` on a standard fraction.
  simpa [awayToAtPrime] using
    (IsLocalization.map_mk'
      (Q := Localization.AtPrime p)
      (g := RingHom.id R)
      (powers_le_primeCompl_comap_of_not_mem (R := R) (p := p) hf)
      r
      (Submonoid.pow f n))

/-- Helper for Lemma 15.8.7: the canonical away-to-at-prime comparison on localized modules is
the localization map induced by `powers f ≤ pᶜ`. -/
private noncomputable abbrev awayToAtPrime_linearMap
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) :
    LocalizedModule.Away f M →ₗ[R] LocalizedModule.AtPrime p M :=
  LocalizedModule.liftOfLE (Submonoid.powers f) p.primeCompl
    (powers_le_primeCompl_of_not_mem (R := R) (p := p) hf)

/-- Helper for Lemma 15.8.7: on a standard away-local fraction `m / f^n`, the localized
comparison `M_f → M_p` sends it to the same fraction in `M_p`. -/
private theorem awayToAtPrime_linearMap_apply_mk
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) (m : M) (s : Submonoid.powers f) :
    awayToAtPrime_linearMap (R := R) (M := M) p f hf (LocalizedModule.mk m s) =
      IsLocalizedModule.mk'
        (LocalizedModule.mkLinearMap p.primeCompl M)
        m
        ⟨s.1, (powers_le_primeCompl_of_not_mem (R := R) (p := p) hf) s.2⟩ := by
  -- Proof comment: `liftOfLE` is defined by the universal localization map, so it preserves the
  -- represented numerator and only changes the denominator witness from `f^n` to the same element
  -- viewed in `pᶜ`.
  simp only [awayToAtPrime_linearMap, IsLocalizedModule.mk_eq_mk',
    IsLocalizedModule.liftOfLE_mk']

/-- Helper for Lemma 15.8.7: the away-to-at-prime comparison agrees with the prime-localization
map on denominator-`1` generators. -/
private theorem awayToAtPrime_linearMap_apply_mk_one
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) (m : M) :
    awayToAtPrime_linearMap (R := R) (M := M) p f hf (LocalizedModule.mk m 1) =
      LocalizedModule.mkLinearMap p.primeCompl M m := by
  -- Proof comment: specialize the fraction formula to denominator `1` and simplify the target
  -- localization class.
  rw [awayToAtPrime_linearMap_apply_mk (R := R) (M := M) (p := p) (f := f) (hf := hf) m 1]
  convert
    (IsLocalizedModule.mk'_one p.primeCompl
      (LocalizedModule.mkLinearMap p.primeCompl M) m) using 1

/-- Helper for Lemma 15.8.7: composing the away-to-at-prime comparison with the away-localization
map from `M` recovers the prime-localization map from `M`. -/
private theorem awayToAtPrime_linearMap_comp_mkLinearMap
    (p : Ideal R) [p.IsPrime] (f : R) (hf : f ∉ p) :
    (awayToAtPrime_linearMap (R := R) (M := M) p f hf).comp
        (LocalizedModule.mkLinearMap (Submonoid.powers f) M) =
      LocalizedModule.mkLinearMap p.primeCompl M := by
  -- Proof comment: both sides send a global element `m` to the denominator-`1` class of `m` in
  -- `M_p`.
  ext m
  simpa using awayToAtPrime_linearMap_apply_mk_one (R := R) (M := M) (p := p) (f := f) hf m

/-- Helper for Lemma 15.8.7: a set of `k` generators over `R_f` still generates after further
localizing at a prime `p` with `f ∉ p`. -/
private theorem atPrime_generators_of_away_generators
    {k : ℕ} (p : Ideal R) [p.IsPrime] {f : R} (hf : f ∉ p)
    (w : Fin k → LocalizedModule.Away f M)
    (hw : Submodule.span (Localization.Away f) (Set.range w) = ⊤) :
    ∃ v : Fin k → LocalizedModule.AtPrime p M,
      Submodule.span (Localization.AtPrime p) (Set.range v) = ⊤ := by
  -- Proof comment: the remaining step is to upgrade the explicit `R`-linear comparison
  -- `awayToAtPrime_linearMap` to an `R_f`-linear map and then transport the `R_f`-spanning family
  -- through that map. The comparison lemmas above isolate the denominator-`1` and localization
  -- compatibility calculations needed for that upgrade.
  let _ := awayToAtPrime_linearMap_comp_mkLinearMap (R := R) (M := M) p f hf
  let _ := w
  let _ := hw
  sorry

section LocalResidueGeneration

variable {A : Type*} [CommRing A] [IsLocalRing A]
variable {N : Type*} [AddCommGroup N] [Module A N] [Module.Finite A N]

local notation "𝔪" => IsLocalRing.maximalIdeal A
local notation "κ" => IsLocalRing.ResidueField A
local notation "Nbar" => N ⧸ (𝔪 • (⊤ : Submodule A N))

/-- Helper for Lemma 15.8.7: the maximal-ideal quotient carries the residue-field scalar action. -/
local instance residueQuotient_module : Module κ Nbar :=
  inferInstanceAs (Module (A ⧸ 𝔪) Nbar)

/-- Helper for Lemma 15.8.7: the ambient ring and residue field act compatibly on the quotient. -/
local instance residueQuotient_smulCommClass : SMulCommClass A κ Nbar :=
  inferInstanceAs (SMulCommClass A (A ⧸ 𝔪) Nbar)

/-- Helper for Lemma 15.8.7: scalar restriction from the residue field to the local ring is a
tower on the maximal-ideal quotient. -/
local instance residueQuotient_isScalarTower : IsScalarTower A κ Nbar :=
  inferInstanceAs (IsScalarTower A (A ⧸ 𝔪) Nbar)

/-- Helper for Lemma 15.8.7: the maximal-ideal quotient stays finite over the residue field. -/
local instance residueQuotient_moduleFinite : Module.Finite κ Nbar :=
  inferInstanceAs (Module.Finite (A ⧸ 𝔪) Nbar)

/-- Helper for Lemma 15.8.7: over a local ring, tensoring a module with the residue field
identifies it with the quotient by the maximal-ideal multiple. -/
private noncomputable def residue_tensor_quotient_linearEquiv :
    (κ ⊗[A] N) ≃ₗ[κ] Nbar := by
  let f : κ →ₗ[κ] N →ₗ[A] Nbar :=
    (LinearMap.ringLmapEquivSelf κ κ (N →ₗ[A] Nbar)).symm
      (Submodule.mkQ (𝔪 • (⊤ : Submodule A N)))
  let e₀ : (κ ⊗[A] N) →ₗ[κ] Nbar :=
    TensorProduct.AlgebraTensorModule.lift f
  have e₀_apply (y : N) : e₀ ((1 : κ) ⊗ₜ[A] y) = Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) y := by
    -- Evaluate the tensor lift on a denominator-`1` tensor to recover the quotient class of `y`.
    simp [e₀, f]
  have e₀_restrictScalars :
      e₀.restrictScalars A = (TensorProduct.quotTensorEquivQuotSMul N 𝔪).toLinearMap := by
    -- Both tensor-to-quotient maps agree on pure tensors, hence they are equal by extensionality.
    apply TensorProduct.ext'
    intro r y
    refine Quotient.inductionOn r ?_
    intro a
    change e₀ (Ideal.Quotient.mk 𝔪 a ⊗ₜ[A] y) =
      TensorProduct.quotTensorEquivQuotSMul N 𝔪 (Ideal.Quotient.mk 𝔪 a ⊗ₜ[A] y)
    rw [TensorProduct.quotTensorEquivQuotSMul_mk_tmul]
    simp [e₀, f]
    simpa using (algebraMap_smul κ a (Submodule.Quotient.mk y))
  exact
    LinearEquiv.ofBijective e₀
      ⟨by
          intro u v huv
          have huv' : e₀.restrictScalars A u = e₀.restrictScalars A v := huv
          rw [e₀_restrictScalars] at huv'
          exact (TensorProduct.quotTensorEquivQuotSMul N 𝔪).injective huv'
        , by
          intro z
          obtain ⟨y, rfl⟩ := Submodule.mkQ_surjective (𝔪 • (⊤ : Submodule A N)) z
          exact ⟨(1 : κ) ⊗ₜ[A] y, e₀_apply y⟩⟩

/-- Helper for Lemma 15.8.7: in a local ring, if the residue classes of `k` chosen lifts span the
closed fiber, then the lifts already generate the whole module. -/
private theorem span_eq_top_of_residue_quotient_span_eq_top
    {k : ℕ} (x : Fin k → N)
    (hquot :
      Submodule.span A
        (Set.range (fun i : Fin k ↦ Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i))) = ⊤) :
    Submodule.span A (Set.range x) = ⊤ := by
  classical
  let s : Finset N := Finset.univ.image x
  have hs : (s : Set N) = Set.range x := by
    -- Replace the finite image of `Fin k` with the corresponding range set.
    ext y
    simp [s]
  have himage :
      ((Submodule.mkQ (𝔪 • (⊤ : Submodule A N))) '' (s : Set N) : Set Nbar) =
        Set.range (fun i : Fin k ↦ Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i)) := by
    -- Passing the finite set `s` through the quotient map recovers exactly the chosen residue
    -- classes of the lifts.
    rw [hs]
    ext y
    constructor
    · rintro ⟨z, ⟨i, rfl⟩, rfl⟩
      exact ⟨i, rfl⟩
    · rintro ⟨i, rfl⟩
      exact ⟨x i, ⟨i, rfl⟩, rfl⟩
  have hquot' :
      Submodule.span A ((Submodule.mkQ (𝔪 • (⊤ : Submodule A N))) '' (s : Set N)) = ⊤ := by
    -- Rewrite the quotient-span hypothesis into the finite-set form required by Nakayama.
    rw [himage]
    exact hquot
  have hmaxJac₀ : 𝔪 ≤ Ideal.jacobson (⊥ : Ideal A) :=
    IsLocalRing.maximalIdeal_le_jacobson (⊥ : Ideal A)
  have hmaxJac : 𝔪 ≤ Ring.jacobson A := by
    -- In a local ring the maximal ideal lies in the Jacobson radical.
    rw [← Ideal.jacobson_bot]
    exact hmaxJac₀
  -- Nakayama upgrades generation of the closed fiber to generation of the original module.
  simpa [hs] using
    (span_eq_top_of_quotient_span_eq_top_of_le_ring_jacobson
      (R := A) (M := N) (I := 𝔪) (s := s) hquot' hmaxJac)

/-- Helper for Lemma 15.8.7: once the closed fiber over a local ring has `κ`-dimension at most
`k`, one can choose `k` residue generators and lift them to generators of the module itself. -/
private theorem exists_generators_of_finrank_le_residue_quotient
    {k : ℕ} (hk : Module.finrank κ Nbar ≤ k) :
    ∃ x : Fin k → N, Submodule.span A (Set.range x) = ⊤ := by
  classical
  obtain ⟨w, hw⟩ :=
    exists_generators_of_finrank_le_of_field (K := κ) (V := Nbar) hk
  let x : Fin k → N := fun i ↦
    Classical.choose ((Submodule.mkQ_surjective (𝔪 • (⊤ : Submodule A N))) (w i))
  have hx :
      ∀ i : Fin k, Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i) = w i := by
    -- Pick arbitrary lifts of the residue generators.
    intro i
    exact Classical.choose_spec
      ((Submodule.mkQ_surjective (𝔪 • (⊤ : Submodule A N))) (w i))
  have hquot :
      Submodule.span A
        (Set.range (fun i : Fin k ↦ Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i))) = ⊤ := by
    have hcomp :
        (fun i : Fin k ↦ Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i)) = w := by
      funext i
      exact hx i
    -- Forgetting scalars from `κ` back to `A` preserves the spanning statement on the quotient.
    rw [hcomp, ← Submodule.restrictScalars_span A κ Ideal.Quotient.mk_surjective,
      Submodule.restrictScalars_eq_top_iff]
    exact hw
  -- Apply the local lifting lemma to the chosen residue generators.
  exact ⟨x, span_eq_top_of_residue_quotient_span_eq_top (A := A) (N := N) x hquot⟩

/-- Helper for Lemma 15.8.7: if `k` elements generate a module over a local ring, then their
residue classes span a `k`-dimensional quotient over the residue field. -/
private theorem finrank_le_residue_quotient_of_exists_generators
    {k : ℕ} (x : Fin k → N)
    (hx : Submodule.span A (Set.range x) = ⊤) :
    Module.finrank κ Nbar ≤ k := by
  let xbar : Fin k → Nbar := fun i ↦ Submodule.mkQ (𝔪 • (⊤ : Submodule A N)) (x i)
  have hspanA :
      Submodule.span A (Set.range xbar) = ⊤ := by
    have hmap :
        Submodule.map (Submodule.mkQ (𝔪 • (⊤ : Submodule A N)))
            (Submodule.span A (Set.range x)) =
          Submodule.span A (Set.range xbar) := by
      rw [Submodule.map_span]
      congr 1
      ext y
      constructor
      · rintro ⟨z, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, rfl⟩
      · rintro ⟨i, rfl⟩
        exact ⟨x i, ⟨i, rfl⟩, rfl⟩
    -- Mapping a generating family through the quotient map still spans the whole quotient.
    rw [← hmap, hx, Submodule.map_top]
    rw [LinearMap.range_eq_top]
    exact Submodule.mkQ_surjective (𝔪 • (⊤ : Submodule A N))
  have hspanκ :
      Submodule.span κ (Set.range xbar) = ⊤ := by
    -- Forgetting scalars from `κ` to `A` does not change the spanning statement on the quotient.
    rw [← Submodule.restrictScalars_eq_top_iff]
    simpa [Submodule.restrictScalars_span A κ Ideal.Quotient.mk_surjective] using hspanA
  have hsurj :
      Function.Surjective (Fintype.linearCombination κ xbar) := by
    rw [span_range_eq_top_iff_surjective_fintypeLinearCombination] at hspanκ
    exact hspanκ
  -- A surjective map `κ^k → Nbar` bounds the residue-field dimension by `k`.
  have hle :
      Module.finrank κ (LinearMap.range (Fintype.linearCombination κ xbar)) ≤ k := by
    have hrank :
        Module.finrank κ (LinearMap.range (Fintype.linearCombination κ xbar)) +
          Module.finrank κ (LinearMap.ker (Fintype.linearCombination κ xbar)) = k := by
      simpa using LinearMap.finrank_range_add_finrank_ker (Fintype.linearCombination κ xbar)
    rw [← hrank]
    exact Nat.le_add_right _ _
  have hrange : LinearMap.range (Fintype.linearCombination κ xbar) = ⊤ :=
    LinearMap.range_eq_top.2 hsurj
  rw [hrange, finrank_top] at hle
  exact hle

end LocalResidueGeneration

/-- Helper for Lemma 15.8.7: the residue-field fiber has dimension at most `k` exactly when the
prime localization can be generated by `k` elements. -/
private theorem residueField_finrank_le_iff_exists_atPrime_generators
    (k : ℕ) (p : Ideal R) [p.IsPrime] :
    Module.finrank p.ResidueField (p.ResidueField ⊗[R] M) ≤ k ↔
      ∃ v : Fin k → LocalizedModule.AtPrime p M,
        Submodule.span (Localization.AtPrime p) (Set.range v) = ⊤ := by
  -- Proof comment: this is the closed-fiber Nakayama bridge. The intended route is to identify
  -- `κ(p) ⊗[R] M` with the closed fiber of `M_p`, lift residue generators through the quotient map,
  -- and then apply `span_eq_top_of_residue_quotient_span_eq_top`; the reverse direction sends
  -- chosen local generators to the quotient and bounds the fiber dimension by the surjective
  -- linear-combination map from `κ(p)^k`.
  sorry

/-- Helper for Lemma 15.8.7: forming determinantal ideals commutes with coefficientwise reduction
to the prime residue field. -/
private theorem matrix_minorIdeal_map_eq_residueField
    (p : Ideal R) [p.IsPrime] {ι κ : Type*} (t : ℕ) (A : Matrix ι κ R) :
    Ideal.map (algebraMap R p.ResidueField) (Matrix.minorIdeal t A) =
      Matrix.minorIdeal t (A.map (algebraMap R p.ResidueField)) := by
  classical
  -- Proof comment: unfold the determinantal ideal and move the residue-field map across each
  -- determinant generator separately.
  unfold Matrix.minorIdeal
  rw [Ideal.map_span]
  congr 1
  ext y
  constructor
  · rintro ⟨x, ⟨q, rfl⟩, rfl⟩
    refine ⟨q, ?_⟩
    have hsub :
        (algebraMap R p.ResidueField).mapMatrix (A.submatrix q.1 q.2) =
          (A.map (algebraMap R p.ResidueField)).submatrix q.1 q.2 := by
      ext i j
      rfl
    simpa [hsub] using
      (RingHom.map_det (algebraMap R p.ResidueField) (A.submatrix q.1 q.2)).symm
  · rintro ⟨q, hq⟩
    refine ⟨(A.submatrix q.1 q.2).det, ?_, ?_⟩
    · exact ⟨q, rfl⟩
    · have hsub :
          (algebraMap R p.ResidueField).mapMatrix (A.submatrix q.1 q.2) =
            (A.map (algebraMap R p.ResidueField)).submatrix q.1 q.2 := by
        ext i j
        rfl
      calc
        algebraMap R p.ResidueField (A.submatrix q.1 q.2).det =
            ((A.map (algebraMap R p.ResidueField)).submatrix q.1 q.2).det := by
              simpa [hsub] using
                RingHom.map_det (algebraMap R p.ResidueField) (A.submatrix q.1 q.2)
        _ = y := hq

/-- Helper for Lemma 15.8.7: tensoring the standard free module `R^n` with the prime residue
field identifies it with `κ(p)^n`. -/
private noncomputable abbrev residueField_tensor_free_equiv
    (p : Ideal R) [p.IsPrime] (n : ℕ) :
    p.ResidueField ⊗[R] (Fin n → R) ≃ₗ[p.ResidueField] (Fin n → p.ResidueField) :=
  TensorProduct.piScalarRight R p.ResidueField p.ResidueField (Fin n)

/-- Helper for Lemma 15.8.7: a surjection `R^n → M` induces the standard residue-field
presentation `κ(p)^n → κ(p) ⊗ M`. -/
private noncomputable abbrev residueField_presentation
    {n : ℕ} (p : Ideal R) [p.IsPrime]
    (π : (Fin n → R) →ₗ[R] M) :
    (Fin n → p.ResidueField) →ₗ[p.ResidueField] p.ResidueField ⊗[R] M :=
  (π.baseChange p.ResidueField).comp
    ((residueField_tensor_free_equiv (R := R) (p := p) n).symm.toLinearMap)

/-- Helper for Lemma 15.8.7: the residue-field presentation obtained from a surjection remains
surjective after tensoring. -/
private theorem residueField_presentation_surjective
    {n : ℕ} (p : Ideal R) [p.IsPrime]
    (π : (Fin n → R) →ₗ[R] M) (hπ : Function.Surjective π) :
    Function.Surjective (residueField_presentation (R := R) (M := M) p π) := by
  -- Proof comment: tensoring preserves surjections, and the free-module tensor model is the
  -- canonical `κ(p)^n` linear equivalence.
  exact
    (by
      simpa [residueField_presentation, LinearMap.baseChange_eq_ltensor] using
        (LinearMap.lTensor_surjective p.ResidueField hπ).comp
          (residueField_tensor_free_equiv (R := R) (p := p) n).symm.surjective)

/-- Helper for Lemma 15.8.7: after base change to the prime residue field, the `k`th Fitting
ideal is the image of the original `k`th Fitting ideal. -/
private theorem fittingIdeal_residueField_baseChange
    (k : ℕ) (p : Ideal R) [p.IsPrime] :
    Fit[p.ResidueField]_(k)(p.ResidueField ⊗[R] M) =
      Ideal.map (algebraMap R p.ResidueField) (Fit[R]_(k)(M)) := by
  -- Proof comment: the deterministic transport pieces are now isolated. The remaining blocker is
  -- the finite exactness step that extracts a finite spanning family in
  -- `LinearMap.ker (residueField_presentation p π)` from the exact sequence
  -- `κ(p) ⊗ ker π → κ(p)^n → κ(p) ⊗ M → 0`, so that
  -- `presentationFittingIdeal` on the residue-field side can be compared with the image of the
  -- original presentation ideal via `matrix_minorIdeal_map_eq_residueField`.
  sorry

/-- Helper for Lemma 15.8.7: noncontainment of the `k`th Fitting ideal in a prime ideal is
equivalent to the residue-field fiber having dimension at most `k`. -/
private theorem fittingIdeal_not_le_prime_iff_finrank_le_residueField
    (k : ℕ) (p : Ideal R) [p.IsPrime] :
    (¬ Fit[R]_(k)(M) ≤ p) ↔ Module.finrank p.ResidueField (p.ResidueField ⊗[R] M) ≤ k := by
  have hmap_bot :
      Ideal.map (algebraMap R p.ResidueField) (Fit[R]_(k)(M)) = (⊥ : Ideal p.ResidueField) ↔
        Fit[R]_(k)(M) ≤ p := by
    -- The residue-field quotient kills exactly the prime ideal `p`.
    rw [Ideal.map_eq_bot_iff_le_ker]
    have hker : RingHom.ker (algebraMap R p.ResidueField) = p := by
      ext x
      simp
    simpa [hker]
  -- Base-change the Fitting ideal to the residue field and then invoke the field computation.
  calc
    (¬ Fit[R]_(k)(M) ≤ p)
        ↔ ¬ Ideal.map (algebraMap R p.ResidueField) (Fit[R]_(k)(M)) ≤
            (⊥ : Ideal p.ResidueField) := by
          rw [show Ideal.map (algebraMap R p.ResidueField) (Fit[R]_(k)(M)) ≤
              (⊥ : Ideal p.ResidueField) ↔
              Ideal.map (algebraMap R p.ResidueField) (Fit[R]_(k)(M)) =
                (⊥ : Ideal p.ResidueField) by simp]
          simpa [hmap_bot]
    _ ↔ ¬ Fit[p.ResidueField]_(k)(p.ResidueField ⊗[R] M) ≤ (⊥ : Ideal p.ResidueField) := by
          rw [fittingIdeal_residueField_baseChange (R := R) (M := M) k p]
    _ ↔ Module.finrank p.ResidueField (p.ResidueField ⊗[R] M) ≤ k := by
          exact
            fittingIdeal_not_le_bot_iff_finrank_le_of_field
              (K := p.ResidueField) (V := p.ResidueField ⊗[R] M) k

/-- Helper for Lemma 15.8.7: if a localized submodule is all of a localization, then the
localization of the corresponding quotient module is trivial. -/
private theorem localized_quotient_subsingleton_of_localized_eq_top
    {A : Type*} [CommRing A]
    {N : Type*} [AddCommGroup N] [Module A N]
    (S : Submonoid A) (P : Submodule A N)
    (hlocalized : Submodule.localized (p := S) P = ⊤) :
    Subsingleton (LocalizedModule S (N ⧸ P)) := by
  let e :
      (LocalizedModule S N ⧸ Submodule.localized (p := S) P) ≃ₗ[Localization S]
        LocalizedModule S (N ⧸ P) :=
    localizedQuotientEquiv S P
  have hquot :
      Subsingleton (LocalizedModule S N ⧸ Submodule.localized (p := S) P) := by
    -- Quotienting by the localized whole submodule leaves only the zero quotient.
    rw [hlocalized]
    infer_instance
  letI : Subsingleton (LocalizedModule S N ⧸ Submodule.localized (p := S) P) := hquot
  -- Transport the quotient-by-`⊤` subsingleton structure across `localizedQuotientEquiv`.
  exact e.symm.toEquiv.subsingleton

/-- Helper for Lemma 15.8.7: if a finite module vanishes after localizing at a prime, then some
basic open neighborhood of that prime already kills the away-localized module. -/
private theorem exists_localizationAway_subsingleton_of_finite_localizedAtPrime_subsingleton
    {A : Type*} [CommRing A] (q : PrimeSpectrum A)
    {N : Type*} [AddCommGroup N] [Module A N] [Module.Finite A N]
    (hsub : Subsingleton (LocalizedModule.AtPrime q.asIdeal N)) :
    ∃ s : A, s ∉ q.asIdeal ∧ Subsingleton (LocalizedModule.Away s N) := by
  classical
  rcases Module.Finite.exists_fin' A N with ⟨n, π, hπ⟩
  let kill : Fin n → A := fun j ↦
    Classical.choose <|
      (LocalizedModule.subsingleton_iff (S := q.asIdeal.primeCompl) (M := N)).mp
        hsub (π (Pi.single j (1 : A)))
  have hkill_mem : ∀ j : Fin n, kill j ∉ q.asIdeal := by
    -- Each chosen annihilator lies in the prime complement by construction.
    intro j
    exact (Classical.choose_spec <|
      (LocalizedModule.subsingleton_iff (S := q.asIdeal.primeCompl) (M := N)).mp
        hsub (π (Pi.single j (1 : A)))).1
  have hkill_zero : ∀ j : Fin n, kill j • π (Pi.single j (1 : A)) = 0 := by
    -- The same witnesses kill the chosen finite generating family.
    intro j
    exact (Classical.choose_spec <|
      (LocalizedModule.subsingleton_iff (S := q.asIdeal.primeCompl) (M := N)).mp
        hsub (π (Pi.single j (1 : A)))).2
  let s' : q.asIdeal.primeCompl := ∏ j, ⟨kill j, hkill_mem j⟩
  have hs_gen : ∀ j : Fin n, s'.1 • π (Pi.single j (1 : A)) = 0 := by
    intro j
    have hs_split :
        ((Finset.univ.erase j).prod fun i ↦ kill i) * kill j = s'.1 := by
      simpa [s'] using
        (Finset.prod_erase_mul (s := Finset.univ) (f := fun i : Fin n ↦ kill i)
          (a := j) (by simp : j ∈ (Finset.univ : Finset (Fin n))))
    -- Multiplying by the full product still kills the `j`th generator because one factor does.
    calc
      s'.1 • π (Pi.single j (1 : A)) =
          ((Finset.univ.erase j).prod fun i ↦ kill i) •
            (kill j • π (Pi.single j (1 : A))) := by
              rw [← hs_split, mul_smul]
      _ = 0 := by
            simp [hkill_zero j]
  have hs_ann : s'.1 ∈ Module.annihilator A N := by
    rw [Module.mem_annihilator]
    intro x
    rcases hπ x with ⟨y, rfl⟩
    have hy :
        (∑ j, y j • (Pi.single j (1 : A) : Fin n → A)) = y := by
      ext j
      simpa [Pi.single_apply, mul_comm] using
        (Fintype.sum_pi_single (i := j) (f := y))
    -- Surjectivity reduces the annihilator computation to the chosen finite generators after
    -- expanding an arbitrary vector in the standard basis of `A^n`.
    rw [← hy]
    calc
      s'.1 • π (∑ j, y j • (Pi.single j (1 : A) : Fin n → A)) =
          s'.1 • ∑ j, y j • π (Pi.single j (1 : A) : Fin n → A) := by
            simp [map_sum, map_smul]
      _ = ∑ j, s'.1 • (y j • π (Pi.single j (1 : A) : Fin n → A)) := by
            simpa using
              (Finset.smul_sum
                (s := Finset.univ)
                (r := s'.1)
                (f := fun j : Fin n ↦ y j • π (Pi.single j (1 : A) : Fin n → A)))
      _ = ∑ j, y j • (s'.1 • π (Pi.single j (1 : A) : Fin n → A)) := by
            refine Finset.sum_congr rfl ?_
            intro j hj
            rw [smul_smul, mul_comm, smul_smul]
      _ = 0 := by
            refine Finset.sum_eq_zero ?_
            intro j hj
            rw [hs_gen j, smul_zero]
  refine ⟨s'.1, s'.2, ?_⟩
  rw [LocalizedModule.subsingleton_iff (S := Submonoid.powers s'.1) (M := N)]
  intro x
  refine ⟨s'.1, ⟨1, by simp⟩, ?_⟩
  exact (Module.mem_annihilator.mp hs_ann) x

/-- Helper for Lemma 15.8.7: generators of the prime localization descend to generators on some
basic open neighborhood of the prime. -/
private theorem exists_away_generators_of_atPrime_generators
    {k : ℕ} (p : Ideal R) [p.IsPrime]
    (v : Fin k → LocalizedModule.AtPrime p M)
    (hv : Submodule.span (Localization.AtPrime p) (Set.range v) = ⊤) :
    ∃ f : R, f ∉ p ∧ ∃ w : Fin k → LocalizedModule.Away f M,
      Submodule.span (Localization.Away f) (Set.range w) = ⊤ := by
  classical
  let locp : M →ₗ[R] LocalizedModule.AtPrime p M :=
    LocalizedModule.mkLinearMap p.primeCompl M
  let rep : Fin k → M × p.primeCompl := fun i ↦
    Classical.choose (IsLocalizedModule.mk'_surjective p.primeCompl locp (v i))
  let num : Fin k → M := fun i ↦ (rep i).1
  let den : Fin k → p.primeCompl := fun i ↦ (rep i).2
  have hrepr : ∀ i : Fin k, IsLocalizedModule.mk' locp (num i) (den i) = v i := by
    -- Choose one numerator/denominator representation for each localized generator.
    intro i
    exact Classical.choose_spec (IsLocalizedModule.mk'_surjective p.primeCompl locp (v i))
  let P : Submodule R M := Submodule.span R (Set.range num)
  have hv_mem : ∀ i : Fin k, v i ∈ Submodule.localized (p := p.primeCompl) P := by
    -- Each chosen localized generator comes from a numerator already lying in the source span.
    intro i
    rw [Submodule.mem_localized']
    exact ⟨num i, Submodule.subset_span ⟨i, rfl⟩, den i, hrepr i⟩
  have hPlocal_top : Submodule.localized (p := p.primeCompl) P = ⊤ := by
    have hspan_le :
        Submodule.span (Localization.AtPrime p) (Set.range v) ≤
          Submodule.localized (p := p.primeCompl) P := by
      refine Submodule.span_le.2 ?_
      rintro _ ⟨i, rfl⟩
      exact hv_mem i
    -- Once the chosen localized generators lie in the localized source span, that span is all of
    -- `M_p` because the generators already span `M_p`.
    exact top_unique <| by
      simpa [hv] using hspan_le
  have hquot_sub :
      Subsingleton (LocalizedModule.AtPrime p (M ⧸ P)) :=
    localized_quotient_subsingleton_of_localized_eq_top
      (S := p.primeCompl) P hPlocal_top
  let q : PrimeSpectrum R := ⟨p, inferInstance⟩
  obtain ⟨f, hfp, haway_sub⟩ :=
    exists_localizationAway_subsingleton_of_finite_localizedAtPrime_subsingleton
      (q := q) (N := M ⧸ P) hquot_sub
  let w : Fin k → LocalizedModule.Away f M := fun i ↦
    LocalizedModule.mkLinearMap (Submonoid.powers f) M (num i)
  have hPaway_top : Submodule.localized (p := Submonoid.powers f) P = ⊤ := by
    let e :
        (LocalizedModule.Away f M ⧸ Submodule.localized (p := Submonoid.powers f) P) ≃ₗ[
          Localization.Away f] LocalizedModule.Away f (M ⧸ P) :=
      localizedQuotientEquiv (Submonoid.powers f) P
    have hquot :
        Subsingleton
          (LocalizedModule.Away f M ⧸ Submodule.localized (p := Submonoid.powers f) P) := by
      letI : Subsingleton (LocalizedModule.Away f (M ⧸ P)) := haway_sub
      exact e.toEquiv.subsingleton
    letI :
        Subsingleton
          (LocalizedModule.Away f M ⧸ Submodule.localized (p := Submonoid.powers f) P) := hquot
    -- A quotient module is subsingleton exactly when the localized submodule is all of the
    -- localization.
    exact top_unique fun y _ ↦ by
      have hyzero :
          Submodule.mkQ (Submodule.localized (p := Submonoid.powers f) P) y = 0 :=
        Subsingleton.elim _ _
      simpa using hyzero
  have hspan_away :
      Submodule.span (Localization.Away f) (Set.range w) = ⊤ := by
    have himage :
        ((fun a ↦ LocalizedModule.mk a 1) '' Set.range num : Set (LocalizedModule.Away f M)) =
          Set.range w := by
      ext y
      constructor
      · rintro ⟨a, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, rfl⟩
      · rintro ⟨i, rfl⟩
        exact ⟨num i, ⟨i, rfl⟩, rfl⟩
    -- Rewrite the localized span of the chosen numerators as the span of their denominator-`1`
    -- away-local images.
    have hspan_image :
        Submodule.span (Localization.Away f)
          (((fun a ↦ LocalizedModule.mk a 1) '' Set.range num : Set (LocalizedModule.Away f M))) =
            ⊤ := by
      simpa [P, Submodule.localized'_span] using hPaway_top
    simpa [w, himage] using hspan_image
  exact ⟨f, hfp, w, hspan_away⟩

-- Proof sketch: use `fittingIdeal_baseChange` from Lemma `15.8.4` to reduce clause (1) to
-- the case over the residue field `κ(p)`, where Example `15.8.5` computes the relevant Fitting
-- ideal of a finite-dimensional vector space. The equivalence of clauses (2), (3), and (4) is the
-- usual local-generation criterion via Nakayama's lemma, passing between `M ⊗[R] κ(p)`,
-- `M_p`, and an open neighborhood `D(f)` of `p`.
/-- Lemma 15.8.7: for a finite `R`-module `M`, a nonnegative integer `k`, and a prime ideal `p`,
the following are equivalent: the `k`th Fitting ideal of `M` is not contained in `p`; the
residue-field fiber `M ⊗[R] κ(p)` has dimension at most `k`; the localization `M_p` is generated
by `k` elements over `R_p`; and some localization `M_f` with `f ∉ p` is generated by `k`
elements over `R_f`. -/
theorem fittingIdeal_not_le_prime_tfae_residueField_finrank_and_local_generators
    (k : ℕ) (p : Ideal R) [p.IsPrime] :
    List.TFAE
      [ ¬ Fit[R]_(k)(M) ≤ p
      , Module.finrank p.ResidueField (p.ResidueField ⊗[R] M) ≤ k
      , ∃ v : Fin k → LocalizedModule.AtPrime p M,
          Submodule.span (Localization.AtPrime p) (Set.range v) = ⊤
      , ∃ f : R, f ∉ p ∧ ∃ v : Fin k → LocalizedModule.Away f M,
          Submodule.span (Localization.Away f) (Set.range v) = ⊤
      ] := by
  -- Route correction: the source-faithful proof should reduce `(1) ↔ (2)` by base change and only
  -- then run the Nakayama/localization argument for `(2)`, `(3)`, and `(4)`.
  tfae_have 1 ↔ 2 := by
    -- Proof comment: clause `(1)` is already reduced to the residue-field finrank condition once
    -- the local base-change identity for Fitting ideals is available.
    exact fittingIdeal_not_le_prime_iff_finrank_le_residueField (R := R) (M := M) k p
  tfae_have 2 ↔ 3 := by
    -- TODO for Lemma 15.8.7: identify `κ(p) ⊗[R] M` with the closed fiber of `M_p`, lift residue
    -- generators through the quotient map, and apply the local Nakayama lemma embodied in
    -- `span_eq_top_of_residue_quotient_span_eq_top`.
    exact residueField_finrank_le_iff_exists_atPrime_generators (R := R) (M := M) k p
  tfae_have 3 → 4 := by
    intro h₃
    rcases h₃ with ⟨v, hv⟩
    exact exists_away_generators_of_atPrime_generators (R := R) (M := M) p v hv
  tfae_have 4 → 3 := by
    intro h₄
    rcases h₄ with ⟨f, hf, v, hv⟩
    -- Proof comment: refine the away-local spanning family further to the prime localization via
    -- the canonical comparison `M_f → M_p`.
    exact atPrime_generators_of_away_generators (R := R) (M := M) p hf v hv
  tfae_finish

end
