import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Data.Finset.NatAntidiagonal
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.RingTheory.Support
import StacksProject_2024.stacks_project.Chap10.Definition_10_5_1
import StacksProject_2024.stacks_project.Chap15.Lemma_15_4_3
import StacksProject_2024.stacks_project.Chap15.Definition_15_8_3

-- Declarations for this item will be appended below by the statement pipeline.

universe u v w

open PrimeSpectrum
open scoped TensorProduct
open scoped FittingIdeal

/-
Domain-style sampling for Lemma 15.8.4:
- primary domain: Fitting ideals of modules over a commutative ring;
- sampled owner-level declarations:
  `fittingIdeal`,
  `fittingIdeal_eq_presentationFittingIdeal`,
  `presentationFittingIdeal`,
  `Module.support_eq_zeroLocus`;
- best owner abstraction: `fittingIdeal` is already the intrinsic module-level owner from
  `Definition_15_8_3`, so this file should extend that owner directly rather than introduce a
  parallel alias;
- primitive data: the intrinsic ideal `fittingIdeal R M k` and, when needed, a surjective finite
  free presentation computing it;
- derived API: direct-sum, base-change, annihilator, support, and quotient formulas.

Source/core/bridge triage:
- `source-facing`: the numbered formulas of Lemma 15.8.4;
- `core/canonical`: `fittingIdeal`;
- `bridge/view`: `fittingIdeal_eq_presentationFittingIdeal` for presentation comparison, and the
  canonical support owner theorem `Module.support_eq_zeroLocus` together with the local bridge
  `zeroLocus_fittingIdeal_zero_eq_support`. -/

section

variable {R : Type u} [CommRing R]
variable {M : Type v} [AddCommGroup M] [Module R M]
variable [Module.Finite R M]

variable {M' : Type w} [AddCommGroup M'] [Module R M']

/-- Helper for Lemma 15.8.4: the `0`th minor ideal of any matrix is the unit ideal. -/
private theorem matrix_minorIdeal_zero_eq_top {ι : Type*} {κ : Type*} (A : Matrix ι κ R) :
    Matrix.minorIdeal 0 A = ⊤ := by
  classical
  -- The empty minor contributes determinant `1`, so the span already contains a unit.
  rw [Matrix.minorIdeal]
  refine Ideal.eq_top_of_isUnit_mem _ ?_ isUnit_one
  let e₁ : Fin 0 ↪ ι := ⟨Fin.elim0, fun i ↦ Fin.elim0 i⟩
  let e₂ : Fin 0 ↪ κ := ⟨Fin.elim0, fun i ↦ Fin.elim0 i⟩
  have hmem :
      (1 : R) ∈
        Set.range (fun p : (Fin 0 ↪ ι) × (Fin 0 ↪ κ) ↦
          Matrix.det (Matrix.submatrix A p.1 p.2)) := by
    refine ⟨⟨e₁, e₂⟩, ?_⟩
    simp [e₁, e₂, Matrix.det_fin_zero]
  exact Ideal.subset_span hmem

/-- Helper for Lemma 15.8.4: reindexing the rows and columns of a matrix by equivalences does not
change the corresponding minor ideal. -/
private theorem matrix_minorIdeal_reindex_eq
    {ι : Type*} {ι' : Type*} {κ : Type*} {κ' : Type*}
    (r : ℕ) (A : Matrix ι κ R) (e₁ : ι' ≃ ι) (e₂ : κ' ≃ κ) :
    Matrix.minorIdeal r (A.submatrix e₁ e₂) = Matrix.minorIdeal r A := by
  refine le_antisymm ?_ ?_
  · -- A selected minor of the reindexed matrix is the same selected minor of the original matrix
    -- after composing the chosen row and column embeddings with `e₁` and `e₂`.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨f₁, f₂⟩, rfl⟩
    simpa [Matrix.submatrix_submatrix, Function.comp_def] using
      Matrix.det_submatrix_mem_minorIdeal r A
        (f₁.trans e₁.toEmbedding) (f₂.trans e₂.toEmbedding)
  · -- The reverse inclusion is the same argument applied to the inverse reindexing functions.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨f₁, f₂⟩, rfl⟩
    let f₁' : Fin r ↪ ι' := f₁.trans e₁.symm.toEmbedding
    let f₂' : Fin r ↪ κ' := f₂.trans e₂.symm.toEmbedding
    have hsub :
        Matrix.submatrix (A.submatrix e₁ e₂) f₁' f₂' = Matrix.submatrix A f₁ f₂ := by
      ext i j
      simp [f₁', f₂', Matrix.submatrix]
    simpa [hsub] using
      Matrix.det_submatrix_mem_minorIdeal r (A.submatrix e₁ e₂) f₁' f₂'

/-- Helper for Lemma 15.8.4: at the source rank, a presentation Fitting ideal is the unit ideal. -/
private theorem presentationFittingIdeal_eq_top_at_sourceRank {n : ℕ}
    (π : (Fin n → R) →ₗ[R] M) :
    presentationFittingIdeal R M n π = ⊤ := by
  -- At `k = n`, the presentation owner asks for `0 × 0` minors of the kernel-vector matrix.
  rw [presentationFittingIdeal, Nat.sub_self]
  simpa using
    matrix_minorIdeal_zero_eq_top
      (R := R)
      (A := (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π) R))

-- Proof sketch: choose a surjection `R^n → M`; the intrinsic presentation formula shows that all
-- `(n - n) × (n - n)` minors generate the unit ideal, and then compare with the canonical infimum
-- definition.
/-- Lemma 15.8.4 (1): if `M` is generated by `n` elements, then its `n`th Fitting ideal is the
unit ideal. -/
theorem fittingIdeal_eq_top_of_exists_surjective_fin (n : ℕ)
    (h : ∃ π : (Fin n → R) →ₗ[R] M, Function.Surjective π) :
    Fit[R]_(n)(M) = ⊤ := by
  rcases h with ⟨π, hπ⟩
  -- Route correction: clause (1) closes directly from one surjective presentation, so no further
  -- block-diagonal or base-change transport is needed here.
  rw [fittingIdeal_eq_presentationFittingIdeal R M n π hπ]
  exact presentationFittingIdeal_eq_top_at_sourceRank (R := R) (M := M) π

section

variable [Module.Finite R M']

/-- Helper for Lemma 15.8.4: the free module on `Fin (n + n')` splits into the two coordinate
blocks used for the product presentation. -/
private def fin_add_arrow_linearEquiv (n n' : ℕ) :
    (Fin (n + n') → R) ≃ₗ[R] (Fin n → R) × (Fin n' → R) :=
  let e₁ : (Fin (n + n') → R) ≃ₗ[R] ((Fin n ⊕ Fin n') → R) :=
    LinearEquiv.funCongrLeft (R := R) (M := R) (finSumFinEquiv (m := n) (n := n'))
  let e₂ : ((Fin n ⊕ Fin n') → R) ≃ₗ[R] ((Fin n → R) × (Fin n' → R)) :=
    LinearEquiv.sumArrowLequivProdArrow (Fin n) (Fin n') R R
  e₁.trans e₂

/-- Helper for Lemma 15.8.4: the surjective presentations of `M` and `M'` combine into the
standard product presentation of `M × M'`. -/
private def prod_presentation {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    (Fin (n + n') → R) →ₗ[R] M × M' :=
  (LinearMap.prodMap π π').comp (fin_add_arrow_linearEquiv (R := R) n n').toLinearMap

/-- Helper for Lemma 15.8.4: the product presentation is surjective once each factor presentation
is surjective. -/
private theorem prod_presentation_surjective {n n' : ℕ}
    {π : (Fin n → R) →ₗ[R] M} {π' : (Fin n' → R) →ₗ[R] M'}
    (hπ : Function.Surjective π) (hπ' : Function.Surjective π') :
    Function.Surjective (prod_presentation (R := R) (M := M) (M' := M') π π') := by
  intro x
  rcases hπ x.1 with ⟨a, ha⟩
  rcases hπ' x.2 with ⟨b, hb⟩
  -- Use the free-source splitting equivalence to glue preimages of the two coordinates.
  refine ⟨(fin_add_arrow_linearEquiv (R := R) n n').symm (a, b), ?_⟩
  ext <;> simp [prod_presentation, ha, hb]

/-- Helper for Lemma 15.8.4: after splitting the free source, the kernel of the product
presentation is linearly equivalent to the product of the two original kernels. -/
private theorem ker_prod_presentation_equiv_exists {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    Nonempty <|
      LinearMap.ker (prod_presentation (R := R) (M := M) (M' := M') π π') ≃ₗ[R]
        LinearMap.ker π × LinearMap.ker π' := by
  let e := fin_add_arrow_linearEquiv (R := R) n n'
  -- Split a kernel vector into its two coordinate blocks, and reassemble it with `e.symm`.
  refine ⟨
    { toFun := fun x ↦
        (⟨(e x.1).1, by
            have hx := x.2
            change (π ((e x.1).1), π' ((e x.1).2)) = 0 at hx
            exact congrArg Prod.fst hx
          ⟩,
         ⟨(e x.1).2, by
            have hx := x.2
            change (π ((e x.1).1), π' ((e x.1).2)) = 0 at hx
            exact congrArg Prod.snd hx
          ⟩)
      invFun := fun x ↦
        ⟨e.symm (x.1.1, x.2.1), by
          -- The inverse simply concatenates the two kernel vectors back into one source vector.
          have hx : (π x.1.1, π' x.2.1) = 0 := by
            ext <;> simp
          simpa [prod_presentation, e, LinearMap.comp_apply] using hx
        ⟩
      left_inv := by
        intro x
        ext i
        simpa [e] using congrFun (e.left_inv x.1) i
      right_inv := by
        intro x
        rcases x with ⟨x, y⟩
        apply Prod.ext
        · ext i
          have hx : (e (e.symm (x.1, y.1))).1 = x.1 := by
            exact congrArg Prod.fst (e.apply_symm_apply (x.1, y.1))
          simpa [e] using congrFun hx i
        · ext i
          have hy : (e (e.symm (x.1, y.1))).2 = y.1 := by
            exact congrArg Prod.snd (e.apply_symm_apply (x.1, y.1))
          simpa [e] using congrFun hy i
      map_add' := by
        intro x y
        apply Prod.ext
        · ext i
          simp [e]
        · ext i
          simp [e]
      map_smul' := by
        intro a x
        apply Prod.ext
        · ext i
          simp [e]
        · ext i
          simp [e] }⟩

/-- Helper for Lemma 15.8.4: choose the kernel equivalence supplied by
`ker_prod_presentation_equiv_exists`. -/
private noncomputable def ker_prod_presentation_equiv {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    LinearMap.ker (prod_presentation (R := R) (M := M) (M' := M') π π') ≃ₗ[R]
      LinearMap.ker π × LinearMap.ker π' :=
  Classical.choice <|
    ker_prod_presentation_equiv_exists (R := R) (M := M) (M' := M') π π'

/-- Helper for Lemma 15.8.4: the direct-sum presentation relations are generated by the left and
right kernel vectors inserted into the two source blocks. -/
private noncomputable def prod_kernel_relationMap {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    ((LinearMap.ker π ⊕ LinearMap.ker π') →₀ R) →ₗ[R] (Fin (n + n') → R) :=
  Finsupp.lsum R fun s ↦
    (LinearMap.id : R →ₗ[R] R).smulRight <|
      match s with
      | Sum.inl x => (fin_add_arrow_linearEquiv (R := R) n n').symm (x.1, 0)
      | Sum.inr y => (fin_add_arrow_linearEquiv (R := R) n n').symm (0, y.1)

/-- Helper for Lemma 15.8.4: a left-kernel generator of the relation map lands in the left source
block. -/
private theorem prod_kernel_relationMap_single_inl {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M')
    (x : LinearMap.ker π) (a : R) :
    prod_kernel_relationMap (R := R) (M := M) (M' := M') π π'
        (Finsupp.single (Sum.inl x) a) =
      a • (fin_add_arrow_linearEquiv (R := R) n n').symm (x.1, 0) := by
  -- Unfold the `Finsupp.lsum` definition on one generator and simplify the scalar action.
  simp [prod_kernel_relationMap, LinearMap.smulRight_apply]

/-- Helper for Lemma 15.8.4: a right-kernel generator of the relation map lands in the right
source block. -/
private theorem prod_kernel_relationMap_single_inr {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M')
    (y : LinearMap.ker π') (a : R) :
    prod_kernel_relationMap (R := R) (M := M) (M' := M') π π'
        (Finsupp.single (Sum.inr y) a) =
      a • (fin_add_arrow_linearEquiv (R := R) n n').symm (0, y.1) := by
  -- Unfold the `Finsupp.lsum` definition on one generator and simplify the scalar action.
  simp [prod_kernel_relationMap, LinearMap.smulRight_apply]

/-- Helper for Lemma 15.8.4: the chosen sum-indexed relation map generates exactly the kernel of
the product presentation. -/
private theorem prod_kernel_relationMap_range_eq_ker {n n' : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    LinearMap.range (prod_kernel_relationMap (R := R) (M := M) (M' := M') π π') =
      LinearMap.ker (prod_presentation (R := R) (M := M) (M' := M') π π') := by
  classical
  let e := fin_add_arrow_linearEquiv (R := R) n n'
  refine le_antisymm ?_ ?_
  · -- Each relation generator maps to a kernel vector, so the whole range lies in the kernel.
    rw [LinearMap.range_le_ker_iff]
    apply LinearMap.ext
    intro l
    induction l using Finsupp.induction_linear with
    | zero =>
        simp [prod_kernel_relationMap]
    | add l₁ l₂ hl₁ hl₂ =>
        simp [map_add, hl₁, hl₂]
    | single s a =>
        cases s with
        | inl x =>
            -- The left block generator dies because `x` already lies in `ker π`.
            simp [prod_kernel_relationMap_single_inl, prod_presentation, e, x.2]
        | inr y =>
            -- The right block generator dies because `y` already lies in `ker π'`.
            simp [prod_kernel_relationMap_single_inr, prod_presentation, e, y.2]
  · -- A kernel vector splits into its two coordinate blocks, each of which is generated by one
    -- relation basis element.
    intro z hz
    rw [LinearMap.mem_ker] at hz
    let x : LinearMap.ker π := by
      refine ⟨(e z).1, ?_⟩
      change (π (e z).1, π' (e z).2) = 0 at hz
      exact congrArg Prod.fst hz
    let y : LinearMap.ker π' := by
      refine ⟨(e z).2, ?_⟩
      change (π (e z).1, π' (e z).2) = 0 at hz
      exact congrArg Prod.snd hz
    refine ⟨Finsupp.single (Sum.inl x) (1 : R) + Finsupp.single (Sum.inr y) (1 : R), ?_⟩
    -- Apply the source splitting equivalence so both sides become the same explicit pair.
    apply e.injective
    simp [prod_kernel_relationMap_single_inl, prod_kernel_relationMap_single_inr, e, x, y]

/-- Helper for Lemma 15.8.4: a finitely supported function is the sum of its single-coordinate
generators over any finite set containing its support. -/
private theorem finsupp_eq_sum_attach_single_smul_of_support_subset
    {α : Type*} (f : α →₀ R) (s : Finset α) (hs : f.support ⊆ s) :
    (∑ a : {x // x ∈ s}, f a.1 • Finsupp.single a.1 (1 : R)) = f := by
  classical
  -- Compare the two finitely supported functions coefficientwise on each ambient index.
  ext b
  by_cases hb : b ∈ s
  · -- Inside the chosen support set, only the `b`-summand survives.
    simp [hb, Finsupp.single_apply]
  · -- Outside the chosen support set, `f b = 0` because the support is contained in `s`.
    have hfb : f b = 0 := by
      by_contra hfb
      exact hb (hs (by simpa [Finsupp.mem_support_iff] using hfb))
    simp [hb, Finsupp.single_apply, hfb]

/-- Helper for Lemma 15.8.4: transposing a matrix does not change the corresponding minor ideal. -/
private theorem matrix_minorIdeal_transpose_eq
    {ι : Type*} {κ : Type*} (r : ℕ) (A : Matrix ι κ R) :
    Matrix.minorIdeal r (Matrix.transpose A) = Matrix.minorIdeal r A := by
  refine le_antisymm ?_ ?_
  · -- Each selected minor of the transpose is the transpose of a selected minor of the original
    -- matrix, so the determinant generator is unchanged.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
    change ((Matrix.transpose A).submatrix e₁ e₂).det ∈ Matrix.minorIdeal r A
    have hdet : ((Matrix.transpose A).submatrix e₁ e₂).det = (A.submatrix e₂ e₁).det := by
      calc
        ((Matrix.transpose A).submatrix e₁ e₂).det =
            (Matrix.transpose (A.submatrix e₂ e₁)).det := by
          rw [Matrix.transpose_submatrix]
        _ = (A.submatrix e₂ e₁).det := by
          rw [Matrix.det_transpose]
    rw [hdet]
    exact Matrix.det_submatrix_mem_minorIdeal r A e₂ e₁
  · -- Apply the same transpose comparison again to move back from `Aᵀ` to `A`.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
    change (A.submatrix e₁ e₂).det ∈ Matrix.minorIdeal r (Matrix.transpose A)
    have hdet : (A.submatrix e₁ e₂).det =
        ((Matrix.transpose A).submatrix e₂ e₁).det := by
      calc
        (A.submatrix e₁ e₂).det = (Matrix.transpose (A.submatrix e₁ e₂)).det := by
          rw [Matrix.det_transpose]
        _ = ((Matrix.transpose A).submatrix e₂ e₁).det := by
          rw [Matrix.transpose_submatrix]
    rw [hdet]
    exact Matrix.det_submatrix_mem_minorIdeal r (Matrix.transpose A) e₂ e₁

/-- Helper for Lemma 15.8.4: a determinant built from any column-selector already belongs to the
corresponding minor ideal; repeated columns force the non-injective cases to vanish. -/
private theorem det_submatrix_mem_minorIdeal_of_colMap
    {ι : Type*} {κ : Type*} (r : ℕ) (A : Matrix ι κ R)
    (e₁ : Fin r ↪ ι) (f : Fin r → κ) :
    (A.submatrix e₁ f).det ∈ Matrix.minorIdeal r A := by
  -- Apply the repeated-row version to the transpose and then identify the transposed determinant.
  have hmem :
      ((Matrix.transpose A).submatrix f e₁).det ∈ Matrix.minorIdeal r (Matrix.transpose A) :=
    Matrix.det_submatrix_mem_minorIdeal_of_rowMap r (Matrix.transpose A) f e₁
  have hdet : ((Matrix.transpose A).submatrix f e₁).det = (A.submatrix e₁ f).det := by
    calc
      ((Matrix.transpose A).submatrix f e₁).det =
          (Matrix.transpose (A.submatrix e₁ f)).det := by
        rw [Matrix.transpose_submatrix]
      _ = (A.submatrix e₁ f).det := by
        rw [Matrix.det_transpose]
  rw [matrix_minorIdeal_transpose_eq (R := R) r A] at hmem
  rwa [hdet] at hmem

/-- Helper for Lemma 15.8.4: right multiplication does not enlarge a minor ideal. -/
private theorem matrix_minorIdeal_mul_right_le
    {ι : Type*} {κ : Type*} {κ' : Type*} [Fintype κ]
    (r : ℕ) (A : Matrix ι κ R) (T : Matrix κ κ' R) :
    Matrix.minorIdeal r (A * T) ≤ Matrix.minorIdeal r A := by
  classical
  -- Expand each selected minor of `A * T` by Cauchy-Binet along the chosen output columns.
  refine Ideal.span_le.2 ?_
  rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
  change (((A * T).submatrix e₁ e₂).det) ∈ Matrix.minorIdeal r A
  let M : Matrix (Fin r) κ R := A.submatrix e₁ (fun x : κ ↦ x)
  let N : Matrix κ (Fin r) R := T.submatrix (fun x : κ ↦ x) e₂
  have hmul : (A * T).submatrix e₁ e₂ = M * N := by
    ext i j
    simp [M, N, Matrix.mul_apply]
  have hdet : (((A * T).submatrix e₁ e₂).det) = (M * N).det := by
    rw [hmul]
  rw [hdet]
  rw [show (M * N).det =
      ∑ p : Fin r → κ, ∑ σ : Equiv.Perm (Fin r),
        ↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i) * N (p i) i by
      simp only [Matrix.det_apply', Matrix.mul_apply, Finset.prod_univ_sum, Finset.mul_sum,
        Fintype.piFinset_univ]
      rw [Finset.sum_comm]]
  refine (Matrix.minorIdeal r A).sum_mem fun p _ ↦ ?_
  have hp_det :
      ∑ σ : Equiv.Perm (Fin r), ↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i) =
        (M.submatrix id p).det := by
    symm
    exact Matrix.det_apply' (M.submatrix id p)
  have hp_factor :
      (∑ σ : Equiv.Perm (Fin r), ↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i) * N (p i) i) =
        (∏ i, N (p i) i) * (M.submatrix id p).det := by
    -- Pull the `T`-coefficients out of the determinant expansion and keep the chosen minor of `A`.
    calc
      (∑ σ : Equiv.Perm (Fin r), ↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i) * N (p i) i) =
          ∑ σ : Equiv.Perm (Fin r),
            (∏ i, N (p i) i) * (↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i)) := by
              refine Finset.sum_congr rfl fun σ _ ↦ ?_
              simp [Finset.prod_mul_distrib, mul_assoc, mul_left_comm, mul_comm]
      _ = (∏ i, N (p i) i) * ∑ σ : Equiv.Perm (Fin r),
            ↑(Equiv.Perm.sign σ) * ∏ i, M (σ i) (p i) := by
              rw [Finset.mul_sum]
      _ = (∏ i, N (p i) i) * (M.submatrix id p).det := by
              rw [hp_det]
  rw [hp_factor]
  have hminor : (M.submatrix id p).det ∈ Matrix.minorIdeal r A := by
    -- The chosen rows of `M` are exactly the chosen rows of `A`, with the column selector `p`.
    simpa [M, Matrix.submatrix_submatrix, Function.comp_def] using
      det_submatrix_mem_minorIdeal_of_colMap (R := R) r A e₁ p
  exact Ideal.mul_mem_left _ _ hminor

/-- Helper for Lemma 15.8.4: passing to a selected submatrix can only decrease the corresponding
minor ideal. -/
private theorem matrix_minorIdeal_submatrix_le
    {ι : Type*} {ι' : Type*} {κ : Type*} {κ' : Type*}
    (r : ℕ) (A : Matrix ι κ R) (e₁ : ι' ↪ ι) (e₂ : κ' ↪ κ) :
    Matrix.minorIdeal r (A.submatrix e₁ e₂) ≤ Matrix.minorIdeal r A := by
  refine Ideal.span_le.2 ?_
  rintro _ ⟨⟨f₁, f₂⟩, rfl⟩
  simpa [Matrix.submatrix_submatrix, Function.comp_def] using
    Matrix.det_submatrix_mem_minorIdeal r A (f₁.trans e₁) (f₂.trans e₂)

/-- Helper for Lemma 15.8.4: after restricting to the union of supports of chosen preimages, the
selected kernel-column matrix factors through the finitely many `Finsupp.single` columns. -/
private theorem finsupp_minor_factorization_through_support_union
    {n r : ℕ} {α : Type*} [DecidableEq α] (π : (Fin n → R) →ₗ[R] M)
    (φ : (α →₀ R) →ₗ[R] LinearMap.ker π)
    (e₂ : Fin r ↪ LinearMap.ker π)
    (g : Fin r → α →₀ R)
    (hg : ∀ j : Fin r, φ (g j) = e₂ j) :
    let s : Finset α := Finset.univ.biUnion fun j : Fin r => (g j).support
    let A : Matrix (Fin n) {a // a ∈ s} R :=
      fun i a ↦ ((φ (Finsupp.single a.1 (1 : R)) : LinearMap.ker π) : Fin n → R) i
    let T : Matrix {a // a ∈ s} (Fin r) R := fun a j ↦ g j a.1
    (fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i : Matrix (Fin n) (Fin r) R) = A * T := by
  classical
  intro s A T
  ext i j
  -- Expand the chosen preimage `g j` over the finite support union `s`.
  have hs : (g j).support ⊆ s := by
    intro a ha
    exact Finset.mem_biUnion.2 ⟨j, by simp, ha⟩
  have hsum :
      (∑ a : {x // x ∈ s}, g j a.1 • Finsupp.single a.1 (1 : R)) = g j :=
    finsupp_eq_sum_attach_single_smul_of_support_subset (R := R) (f := g j) s hs
  have hpreimage :
      g j = ∑ a : {x // x ∈ s}, g j a.1 • Finsupp.single a.1 (1 : R) := by
    simpa using hsum.symm
  have hmap :
      φ (g j) =
        φ (∑ a : {x // x ∈ s}, g j a.1 • Finsupp.single a.1 (1 : R)) :=
    congrArg φ hpreimage
  have hφsum :
      φ (g j) =
        ∑ a : {x // x ∈ s}, g j a.1 • φ (Finsupp.single a.1 (1 : R)) := by
    calc
      φ (g j) = φ (∑ a : {x // x ∈ s}, g j a.1 • Finsupp.single a.1 (1 : R)) := hmap
      _ = ∑ a : {x // x ∈ s}, φ (g j a.1 • Finsupp.single a.1 (1 : R)) := by
        rw [map_sum]
      _ = ∑ a : {x // x ∈ s}, g j a.1 • φ (Finsupp.single a.1 (1 : R)) := by
        refine Finset.sum_congr rfl ?_
        intro a ha
        rw [map_smul]
  -- Evaluating the expanded preimage at coordinate `i` produces the matrix product formula.
  calc
    ((e₂ j : LinearMap.ker π) : Fin n → R) i = ((φ (g j) : LinearMap.ker π) : Fin n → R) i := by
      simpa [hg j]
    _ =
        ((∑ a : {x // x ∈ s}, g j a.1 • φ (Finsupp.single a.1 (1 : R)) :
            LinearMap.ker π) : Fin n → R) i := by
          rw [hφsum]
    _ = ∑ a : {x // x ∈ s},
          ((φ (Finsupp.single a.1 (1 : R)) : LinearMap.ker π) : Fin n → R) i * g j a.1 := by
          simp [mul_comm, mul_left_comm, mul_assoc]
    _ = (A * T) i j := by
          simp [A, T, Matrix.mul_apply, mul_comm, mul_left_comm, mul_assoc]

/-- Helper for Lemma 15.8.4: every selected kernel minor coming from a surjective `Finsupp`
relation family already lies in the minor ideal generated by the `Finsupp.single` columns. -/
private theorem selected_minorIdeal_le_finsupp_family_minorIdeal
    {n r : ℕ} {α : Type*} (π : (Fin n → R) →ₗ[R] M)
    (φ : (α →₀ R) →ₗ[R] LinearMap.ker π) (hφ : Function.Surjective φ)
    (e₂ : Fin r ↪ LinearMap.ker π) :
    Matrix.minorIdeal r
        (fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i : Matrix (Fin n) (Fin r) R) ≤
      Matrix.minorIdeal r
        (fun i a ↦ ((φ (Finsupp.single a (1 : R)) : LinearMap.ker π) : Fin n → R) i :
          Matrix (Fin n) α R) := by
  classical
  choose g hg using fun j : Fin r => hφ (e₂ j)
  let s : Finset α := Finset.univ.biUnion fun j : Fin r => (g j).support
  let A : Matrix (Fin n) {a // a ∈ s} R :=
    fun i a ↦ ((φ (Finsupp.single a.1 (1 : R)) : LinearMap.ker π) : Fin n → R) i
  let T : Matrix {a // a ∈ s} (Fin r) R := fun a j ↦ g j a.1
  let B : Matrix (Fin n) α R :=
    fun i a ↦ ((φ (Finsupp.single a (1 : R)) : LinearMap.ker π) : Fin n → R) i
  let e : {a // a ∈ s} ↪ α := ⟨Subtype.val, fun a b h => Subtype.ext h⟩
  have hfactor :
      (fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i : Matrix (Fin n) (Fin r) R) = A * T :=
    finsupp_minor_factorization_through_support_union
      (R := R) (M := M) π φ e₂ g hg
  have hsub : A = B.submatrix (Function.Embedding.refl (Fin n)) e := by
    ext i a
    rfl
  -- First factor the selected matrix through the finite support union, then enlarge back to the
  -- full `α`-indexed family matrix.
  calc
    Matrix.minorIdeal r
        (fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i : Matrix (Fin n) (Fin r) R) =
      Matrix.minorIdeal r (A * T) := by
        rw [hfactor]
    _ ≤ Matrix.minorIdeal r A := by
        exact matrix_minorIdeal_mul_right_le (R := R) r A T
    _ ≤ Matrix.minorIdeal r B := by
        simpa [hsub] using
          (matrix_minorIdeal_submatrix_le
            (R := R) r B (Function.Embedding.refl (Fin n)) e :
              Matrix.minorIdeal r (B.submatrix (Function.Embedding.refl (Fin n)) e) ≤
                Matrix.minorIdeal r B)

/-- Helper for Lemma 15.8.4: a surjective finitely supported relation family computes the same
presentation Fitting ideal as the full kernel-column matrix. -/
private theorem presentationFittingIdeal_eq_minorIdeal_of_surjective_finsupp_family
    {n k : ℕ} {α : Type*} (π : (Fin n → R) →ₗ[R] M)
    (φ : (α →₀ R) →ₗ[R] LinearMap.ker π) (hφ : Function.Surjective φ) :
    presentationFittingIdeal R M k π =
      Matrix.minorIdeal (n - k)
        (fun i a ↦ ((φ (Finsupp.single a (1 : R)) : LinearMap.ker π) : Fin n → R) i :
          Matrix (Fin n) α R) := by
  classical
  let K : Matrix (Fin n) (LinearMap.ker π) R := fun i x ↦ x.1 i
  let B : Matrix (Fin n) α R :=
    fun i a ↦ ((φ (Finsupp.single a (1 : R)) : LinearMap.ker π) : Fin n → R) i
  -- Route correction: split the equality into the surjective-family inclusion and the tautological
  -- inclusion coming from the fact that every `Finsupp.single` column is itself a kernel vector.
  rw [presentationFittingIdeal]
  refine le_antisymm ?_ ?_
  · -- Each selected kernel-column minor factors through finitely many preimages under `φ`.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
    let S : Matrix (Fin n) (Fin (n - k)) R :=
      fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i
    have hSel :
        Matrix.minorIdeal (n - k) S ≤ Matrix.minorIdeal (n - k) B :=
      selected_minorIdeal_le_finsupp_family_minorIdeal
        (R := R) (M := M) π φ hφ e₂
    have hmem :
        Matrix.det (Matrix.submatrix S e₁ (Function.Embedding.refl (Fin (n - k)))) ∈
          Matrix.minorIdeal (n - k) B := by
      exact hSel <|
        Matrix.det_submatrix_mem_minorIdeal (n - k) S e₁
          (Function.Embedding.refl (Fin (n - k)))
    simpa [S] using hmem
  · -- Every chosen minor of the `Finsupp.single` family is already a kernel-column minor.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
    let g : Fin (n - k) → LinearMap.ker π := fun j ↦ φ (Finsupp.single (e₂ j) (1 : R))
    have hsub : B.submatrix e₁ e₂ = K.submatrix e₁ g := by
      ext i j
      simp [B, K, g]
    change (B.submatrix e₁ e₂).det ∈ Matrix.minorIdeal (n - k) K
    rw [hsub]
    exact det_submatrix_mem_minorIdeal_of_colMap (R := R) (n - k) K e₁ g

/-- Helper for Lemma 15.8.4: once the product kernel is replaced by the explicit relation map, the
remaining direct-sum computation is the block-diagonal minors identity. -/
private theorem presentationFittingIdeal_directSum_of_presentations {n n' l : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (π' : (Fin n' → R) →ₗ[R] M') :
    presentationFittingIdeal R (M × M') l
        (prod_presentation (R := R) (M := M) (M' := M') π π') =
      Finset.sum (Finset.antidiagonal l) fun p ↦
        presentationFittingIdeal R M p.1 π * presentationFittingIdeal R M' p.2 π' := by
  -- Route correction: the previous endgame stayed on the raw kernel subtype. The source-faithful
  -- next step is to rewrite through `prod_kernel_relationMap_range_eq_ker`, apply the new
  -- `presentationFittingIdeal_eq_minorIdeal_of_surjective_finsupp_family`, and then identify the
  -- resulting relation matrix with a literal block-diagonal matrix.
  have hrange :=
    prod_kernel_relationMap_range_eq_ker (R := R) (M := M) (M' := M') π π'
  -- TODO: transport `presentationFittingIdeal` across `hrange`, rewrite the relation matrix of
  -- `prod_kernel_relationMap` as `Matrix.fromBlocks`, and finish with
  -- `Matrix.minorIdeal_fromBlocks`.
  sorry

-- Proof sketch: use finite free presentations of `M` and `M'`, form the block-diagonal
-- presentation of `M ⊕ M'`, and invoke the corresponding minors formula from the matrix-level
-- statement.
/-- Lemma 15.8.4 (3): the `l`th Fitting ideal of a direct sum is the sum of the products of the
`k`th and `k'`th Fitting ideals over all decompositions `k + k' = l`. -/
theorem fittingIdeal_directSum (l : ℕ) :
    Fit[R]_(l)(M × M') =
      Finset.sum (Finset.antidiagonal l) fun p ↦ Fit[R]_(p.1)(M) * Fit[R]_(p.2)(M') := by
  obtain ⟨n, π, hπ⟩ := Module.Finite.exists_fin' R M
  obtain ⟨n', π', hπ'⟩ := Module.Finite.exists_fin' R M'
  have hprod :
      Function.Surjective
        (prod_presentation (R := R) (M := M) (M' := M') π π') :=
    prod_presentation_surjective (R := R) (M := M) (M' := M') hπ hπ'
  have hM :
      ∀ k : ℕ, Fit[R]_(k)(M) = presentationFittingIdeal R M k π := fun k ↦
        fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M) k π hπ
  have hM' :
      ∀ k : ℕ, Fit[R]_(k)(M') = presentationFittingIdeal R M' k π' := fun k ↦
        fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M') k π' hπ'
  -- Route correction: first rewrite the intrinsic Fitting ideals on both sides using one chosen
  -- surjective presentation for each module, so the remaining gap is the source-level
  -- block-diagonal presentation identity for `prod_presentation`.
  rw [fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M × M') l
    (prod_presentation (R := R) (M := M) (M' := M') π π') hprod]
  simp_rw [hM, hM']
  -- The presentation-level direct-sum identity is now isolated in a dedicated helper built from
  -- the sum-indexed relation map `prod_kernel_relationMap`.
  exact presentationFittingIdeal_directSum_of_presentations
    (R := R) (M := M) (M' := M') π π'

-- Proof sketch: specialize the general direct-sum formula at `l = 0`; the antidiagonal of `0`
-- has the single term `(0, 0)`.
/-- Lemma 15.8.4 (2): the zeroth Fitting ideal of a direct sum is the product of the zeroth
Fitting ideals. -/
theorem fittingIdeal_zero_directSum :
    Fit[R]_(0)(M × M') = Fit[R]_(0)(M) * Fit[R]_(0)(M') := by
  have h :
      Fit[R]_(0)(M × M') =
        Finset.sum (Finset.antidiagonal 0) fun p ↦ Fit[R]_(p.1)(M) * Fit[R]_(p.2)(M') :=
    fittingIdeal_directSum 0
  simpa [Finset.antidiagonal] using h

end

section

/-- Helper for Lemma 15.8.4: forming the `r × r` minor ideal commutes with a ring map. -/
private theorem matrix_minorIdeal_map_eq
    {S : Type*} [CommRing S] (σ : R →+* S) {ι κ : Type*} (r : ℕ) (A : Matrix ι κ R) :
    Ideal.map σ (Matrix.minorIdeal r A) = Matrix.minorIdeal r (A.map σ) := by
  classical
  -- Unfold the determinantal-ideal owner and move the ring map across each determinant generator.
  unfold Matrix.minorIdeal
  rw [Ideal.map_span]
  congr 1
  ext y
  constructor
  · rintro ⟨x, ⟨p, rfl⟩, rfl⟩
    refine ⟨p, ?_⟩
    have hsub :
        σ.mapMatrix (A.submatrix p.1 p.2) = (A.map σ).submatrix p.1 p.2 := by
      ext i j
      rfl
    simpa [hsub] using (RingHom.map_det σ (A.submatrix p.1 p.2)).symm
  · rintro ⟨p, hp⟩
    refine ⟨(A.submatrix p.1 p.2).det, ?_, ?_⟩
    · exact ⟨p, rfl⟩
    · have hsub :
          σ.mapMatrix (A.submatrix p.1 p.2) = (A.map σ).submatrix p.1 p.2 := by
        ext i j
        rfl
      calc
        σ (A.submatrix p.1 p.2).det = ((A.map σ).submatrix p.1 p.2).det := by
          simpa [hsub] using RingHom.map_det σ (A.submatrix p.1 p.2)
        _ = y := hp

/-- Helper for Lemma 15.8.4: a surjective finite relation family computes the same presentation
Fitting ideal as the full kernel-column matrix. -/
private theorem presentationFittingIdeal_eq_minorIdeal_of_surjective_fin_family
    {n m k : ℕ} (π : (Fin n → R) →ₗ[R] M)
    (φ : (Fin m → R) →ₗ[R] LinearMap.ker π) (hφ : Function.Surjective φ) :
    presentationFittingIdeal R M k π =
      Matrix.minorIdeal (n - k)
        (fun i j ↦ ((φ (Pi.single j (1 : R)) : LinearMap.ker π) : Fin n → R) i :
          Matrix (Fin n) (Fin m) R) := by
  let e : (Fin m →₀ R) ≃ₗ[R] (Fin m → R) := Finsupp.linearEquivFunOnFinite R R (Fin m)
  let ψ : (Fin m →₀ R) →ₗ[R] LinearMap.ker π := φ.comp e.toLinearMap
  have hψ : Function.Surjective ψ := by
    intro x
    rcases hφ x with ⟨y, rfl⟩
    refine ⟨e.symm y, ?_⟩
    simp [ψ, e]
  -- Transport the finite-family presentation through the canonical equivalence between functions
  -- on `Fin m` and finitely supported functions on `Fin m`.
  calc
    presentationFittingIdeal R M k π =
        Matrix.minorIdeal (n - k)
          (fun i a ↦ ((ψ (Finsupp.single a (1 : R)) : LinearMap.ker π) : Fin n → R) i :
            Matrix (Fin n) (Fin m) R) := by
              exact presentationFittingIdeal_eq_minorIdeal_of_surjective_finsupp_family
                (R := R) (M := M) (n := n) (k := k) (α := Fin m) π ψ hψ
    _ =
        Matrix.minorIdeal (n - k)
          (fun i j ↦ ((φ (Pi.single j (1 : R)) : LinearMap.ker π) : Fin n → R) i :
            Matrix (Fin n) (Fin m) R) := by
              congr 1
              ext i j
              simp [ψ, e]

/-- Helper for Lemma 15.8.4: tensoring the range inclusion of a linear map identifies the same
submodule as the range of the tensorized map. -/
private theorem range_subtype_baseChange_eq_range_baseChange
    {R' : Type w} [CommRing R'] [Algebra R R']
    {N : Type*} [AddCommGroup N] [Module R N]
    {P : Type*} [AddCommGroup P] [Module R P]
    (g : N →ₗ[R] P) :
    LinearMap.range (((LinearMap.range g).subtype).baseChange R') =
      LinearMap.range (g.baseChange R') := by
  -- Factor `g` through its range before tensoring, so the tensorized range restriction witnesses
  -- that tensoring the subtype inclusion does not change the image.
  have hfactor : g = (LinearMap.range g).subtype.comp g.rangeRestrict := by
    ext x
    rfl
  have hcomp :
      g.baseChange R' =
        (((LinearMap.range g).subtype).baseChange R').comp (g.rangeRestrict.baseChange R') := by
    have hbase :=
      LinearMap.baseChange_comp (A := R') (f := g.rangeRestrict) ((LinearMap.range g).subtype)
    rw [hfactor] at hbase
    exact hbase
  rw [hcomp, LinearMap.range_comp_of_range_eq_top]
  rw [LinearMap.range_eq_top]
  simpa [LinearMap.baseChange_eq_ltensor] using
    LinearMap.lTensor_surjective R' g.surjective_rangeRestrict

/-- Helper for Lemma 15.8.4: tensoring the quotient map by a submodule makes its kernel equal to
the canonical tensorized submodule. -/
private theorem ker_mkQ_baseChange_eq
    {R' : Type w} [CommRing R'] [Algebra R R']
    {N : Type*} [AddCommGroup N] [Module R N]
    (P : Submodule R N) :
    LinearMap.ker (P.mkQ.baseChange R') = P.baseChange R' := by
  -- Rewrite the tensorized quotient map in the canonical `lTensor` form and use its kernel owner
  -- theorem directly.
  ext x
  have hx :=
    congrArg (fun S : Submodule R (TensorProduct R R' N) ↦ x ∈ S) (lTensor_mkQ R' P)
  simpa [LinearMap.baseChange_eq_ltensor, Submodule.baseChange] using hx

-- Proof sketch: tensor a finite free presentation of `M` with `R'` on the left; tensor product
-- preserves right exactness, and the minors in the base-changed presentation generate the image
-- ideal.
/-- Lemma 15.8.4 (4): after base change along `R → R'`, the `k`th Fitting ideal of the canonical
scalar extension `R' ⊗[R] M` is the ideal of `R'` generated by the image of the `k`th Fitting
ideal over `R`. -/
theorem fittingIdeal_baseChange {R' : Type w} [CommRing R'] [Algebra R R'] (k : ℕ) :
    Fit[R']_(k)(R' ⊗[R] M) = Ideal.map (algebraMap R R') (Fit[R]_(k)(M)) := by
  -- The coefficientwise minor-ideal transport is now isolated in `matrix_minorIdeal_map_eq`.
  -- Route correction: the remaining source-faithful work is now concentrated in one quotient
  -- presentation bridge. The new helpers `range_subtype_baseChange_eq_range_baseChange` and
  -- `ker_mkQ_baseChange_eq` reduce the tensor comparison to identifying the finite free source
  -- `R' ⊗[R] (Fin n → R)` with `Fin n → R'` and then transporting the resulting presentation
  -- matrix through `matrix_minorIdeal_map_eq`.
  sorry

section

variable [Module.Finite R M']

/-- Helper for Lemma 15.8.4: enlarging the kernel of a presentation only enlarges the associated
presentation Fitting ideal. -/
private theorem presentationFittingIdeal_mono_of_ker_le {n k : ℕ}
    {π : (Fin n → R) →ₗ[R] M} {π' : (Fin n → R) →ₗ[R] M'}
    (hker : LinearMap.ker π ≤ LinearMap.ker π') :
    presentationFittingIdeal R M k π ≤ presentationFittingIdeal R M' k π' := by
  classical
  -- Every chosen kernel minor for `π` is also a kernel minor for `π'` via the kernel inclusion.
  rw [presentationFittingIdeal, presentationFittingIdeal]
  refine Ideal.span_le.2 ?_
  rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
  let e₂' : Fin (n - k) ↪ LinearMap.ker π' :=
    ⟨fun i ↦ ⟨(e₂ i).1, hker (e₂ i).2⟩,
      fun i j hij ↦ by
        have hval : (e₂ i).1 = (e₂ j).1 := by
          exact congrArg (fun z : LinearMap.ker π' => z.1) hij
        apply e₂.injective
        exact Subtype.ext hval⟩
  have hsub :
      Matrix.submatrix (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π) R) e₁ e₂ =
        Matrix.submatrix (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π') R) e₁ e₂' := by
    ext i j
    rfl
  -- After reindexing the columns through the inclusion `ker π ↪ ker π'`, the selected minor is
  -- literally one of the generators for the larger determinantal ideal.
  simpa [hsub] using
    (Matrix.det_submatrix_mem_minorIdeal (n - k)
      (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π') R) e₁ e₂')

-- Proof sketch: compose a finite free presentation of `M` with the surjection `M → M'`. Every
-- presentation of `M` induces one of `M'`, so the defining presentation ideals for `M` lie below
-- those for `M'`.
/-- Lemma 15.8.4 (6): a surjection `M → M'` makes the `k`th Fitting ideal of `M` contained in the
`k`th Fitting ideal of `M'`. -/
theorem fittingIdeal_mono_of_surjective (f : M →ₗ[R] M') (hf : Function.Surjective f) (k : ℕ) :
    Fit[R]_(k)(M) ≤ Fit[R]_(k)(M') := by
  obtain ⟨n, π, hπ⟩ := Module.Finite.exists_fin' R M
  have hcomp : Function.Surjective (f.comp π) := by
    -- The composed presentation is still surjective because both maps are surjective.
    intro x
    rcases hf x with ⟨y, rfl⟩
    rcases hπ y with ⟨z, rfl⟩
    exact ⟨z, rfl⟩
  have hker : LinearMap.ker π ≤ LinearMap.ker (f.comp π) := by
    -- A relation for `π` is automatically a relation after postcomposing with `f`.
    intro x hx
    rw [LinearMap.mem_ker] at hx ⊢
    simpa [LinearMap.comp_apply, hx]
  -- Compute both intrinsic ideals from the chosen presentation and compare the kernels.
  calc
    Fit[R]_(k)(M) = presentationFittingIdeal R M k π := by
      exact fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M) k π hπ
    _ ≤ presentationFittingIdeal R M' k (f.comp π) := by
      exact presentationFittingIdeal_mono_of_ker_le (R := R) (M := M) (M' := M') hker
    _ = Fit[R]_(k)(M') := by
      symm
      exact fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M') k (f.comp π) hcomp

end

section

/-- Helper for Lemma 15.8.4: for a surjective presentation, the determinant of any square matrix
whose columns are kernel vectors annihilates the quotient module. -/
private theorem det_kernel_matrix_mem_annihilator_of_surjective {n : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (hπ : Function.Surjective π)
    (e₂ : Fin n ↪ LinearMap.ker π) :
    Matrix.det (fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i : Matrix (Fin n) (Fin n) R) ∈
      Module.annihilator R M := by
  let A : Matrix (Fin n) (Fin n) R :=
    fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i
  have hcolumn_zero : ∀ j : Fin n, π (fun i ↦ A i j) = 0 := by
    intro j
    exact (e₂ j).2
  have hadjugate_column_zero : ∀ j : Fin n, π (fun i ↦ (A * A.adjugate) i j) = 0 := by
    intro j
    -- Each adjugate column is an `R`-linear combination of the original kernel columns.
    have hcolumn :
        (fun i ↦ (A * A.adjugate) i j) =
          ∑ t : Fin n, A.adjugate t j • fun i ↦ A i t := by
      ext i
      simp [A, Matrix.mul_apply, dotProduct, mul_comm]
    rw [hcolumn, map_sum]
    refine Finset.sum_eq_zero ?_
    intro t ht
    rw [π.map_smul, hcolumn_zero t, smul_zero]
  have hbasis_zero : ∀ j : Fin n, π (A.det • (Pi.single j (1 : R) : Fin n → R)) = 0 := by
    intro j
    -- Rewrite the adjugate identity columnwise to get the determinant relation on a basis vector.
    calc
      π (A.det • (Pi.single j (1 : R) : Fin n → R)) =
          π (fun i ↦ ((A.det • (1 : Matrix (Fin n) (Fin n) R)) i j)) := by
            congr 1
            ext i
            by_cases hij : i = j
            · subst hij
              simp
            · simp [Matrix.one_apply, Pi.single_apply, hij]
      _ = π (fun i ↦ (A * A.adjugate) i j) := by
            rw [Matrix.mul_adjugate]
      _ = 0 := hadjugate_column_zero j
  -- Evaluate the determinant relation on a chosen preimage of an arbitrary module element.
  rw [Module.mem_annihilator]
  intro x
  rcases hπ x with ⟨v, rfl⟩
  have hv :
      ∑ j : Fin n, v j • (Pi.single j (1 : R) : Fin n → R) = v := by
    ext i
    simpa [Pi.single_apply, mul_comm] using (Fintype.sum_pi_single (i := i) (f := v))
  have hπv :
      π v = ∑ j : Fin n, v j • π (Pi.single j (1 : R) : Fin n → R) := by
    calc
      π v = π (∑ j : Fin n, v j • (Pi.single j (1 : R) : Fin n → R)) := by
        rw [hv]
      _ = ∑ j : Fin n, π (v j • (Pi.single j (1 : R) : Fin n → R)) := by
        simp [map_sum]
      _ = ∑ j : Fin n, v j • π (Pi.single j (1 : R) : Fin n → R) := by
        simp [map_sum, map_smul]
  calc
    A.det • π v = A.det • ∑ j : Fin n, v j • π (Pi.single j (1 : R) : Fin n → R) := by
      rw [hπv]
    _ = ∑ j : Fin n, A.det • (v j • π (Pi.single j (1 : R) : Fin n → R)) := by
      simpa using Finset.smul_sum (s := Finset.univ) (r := A.det)
        (f := fun j : Fin n ↦ v j • π (Pi.single j (1 : R) : Fin n → R))
    _ = ∑ j : Fin n, v j • (A.det • π (Pi.single j (1 : R) : Fin n → R)) := by
      refine Finset.sum_congr rfl ?_
      intro j hj
      simp [smul_smul, mul_comm]
    _ = ∑ j : Fin n, v j • π (A.det • (Pi.single j (1 : R) : Fin n → R)) := by
      refine Finset.sum_congr rfl ?_
      intro j hj
      rw [← π.map_smul]
    _ = 0 := by
      refine Finset.sum_eq_zero ?_
      intro j hj
      rw [hbasis_zero j, smul_zero]

/-- Helper for Lemma 15.8.4: every full-row presentation minor of a surjective presentation is an
annihilator element. -/
private theorem full_row_minor_mem_annihilator_of_surjective {n : ℕ}
    (π : (Fin n → R) →ₗ[R] M) (hπ : Function.Surjective π)
    (e₁ : Fin n ↪ Fin n) (e₂ : Fin n ↪ LinearMap.ker π) :
    Matrix.det
        (Matrix.submatrix
          (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π) R) e₁ e₂) ∈
      Module.annihilator R M := by
  classical
  let e : Fin n ≃ Fin n :=
    Equiv.ofBijective e₁ ⟨e₁.injective,
      (Finite.injective_iff_surjective (f := e₁)).1 e₁.injective⟩
  let A : Matrix (Fin n) (Fin n) R :=
    fun i j ↦ ((e₂ j : LinearMap.ker π) : Fin n → R) i
  have hsub :
      Matrix.submatrix
          (fun i x ↦ x.1 i : Matrix (Fin n) (LinearMap.ker π) R) e₁ e₂ =
        Matrix.reindex e.symm (Equiv.refl (Fin n)) A := by
    ext i j
    simp [Matrix.reindex_apply, A, e]
  -- The selected rows are a permutation of all rows, so the determinant changes only by a sign.
  rw [hsub]
  have hdet :
      Matrix.det (Matrix.reindex e.symm (Equiv.refl (Fin n)) A) =
        (↑(Equiv.Perm.sign ((Equiv.refl (Fin n)).symm.trans e.symm)) : R) * Matrix.det A := by
    simpa using Matrix.det_reindex e.symm (Equiv.refl (Fin n)) A
  rw [hdet]
  exact Ideal.mul_mem_left _ _
    (det_kernel_matrix_mem_annihilator_of_surjective (R := R) (M := M) π hπ e₂)

-- Proof sketch: use a finite presentation of `M` and the determinant trick on the maximal minors
-- of a presentation matrix to show that every generator of `Fit₀(M)` annihilates `M`.
/-- Lemma 15.8.4 (7): the zeroth Fitting ideal of `M` is contained in the annihilator ideal of
`M`. -/
theorem fittingIdeal_zero_le_annihilator :
    Fit[R]_(0)(M) ≤ Module.annihilator R M := by
  obtain ⟨n, π, hπ⟩ := Module.Finite.exists_fin' R M
  -- Route correction: for `k = 0`, every generator is a full-size determinant, so the source proof
  -- reduces to the adjugate identity on one surjective presentation.
  rw [fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M) 0 π hπ, presentationFittingIdeal]
  refine Ideal.span_le.2 ?_
  rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
  -- Each selected maximal minor is a row permutation of a square kernel-column matrix, hence it
  -- annihilates `M` by the determinant trick proved above.
  exact full_row_minor_mem_annihilator_of_surjective (R := R) (M := M) π hπ e₁ e₂

-- Proof sketch: combine the previous annihilator containment with the characterization of support
-- of a finite module as the zero locus of its annihilator via `Module.support_eq_zeroLocus`, and
-- compare with the determinant criterion after reducing modulo a prime.
/-- Lemma 15.8.4 (8): the zero locus of the zeroth Fitting ideal of `M` is the support of `M`. -/
theorem zeroLocus_fittingIdeal_zero_eq_support :
    zeroLocus (Fit[R]_(0)(M)) = Module.support R M := by
  apply le_antisymm
  · -- TODO: prove the reverse inclusion by localizing at a prime and invoking clause `(1)` after
    -- base change to the residue field; the remaining blocker is the missing base-change theorem.
    sorry
  · -- The annihilator containment already gives the easy support inclusion.
    rw [Module.support_eq_zeroLocus]
    exact (zeroLocus_subset_zeroLocus_iff (I := Module.annihilator R M)
      (J := Fit[R]_(0)(M))).2 <|
      le_trans (fittingIdeal_zero_le_annihilator (R := R) (M := M)) Ideal.le_radical

end

end

-- Proof sketch: start from a finite presentation of `M`; the relevant ideal is generated by a
-- finite set of minors of a finite presentation matrix, hence is finitely generated.
/-- Lemma 15.8.4 (5): if `M` is finitely presented, then each Fitting ideal of `M` is finitely
generated. -/
theorem fittingIdeal_fg_of_finitePresentation [Module.FinitePresentation R M] (k : ℕ) :
    (Fit[R]_(k)(M)).FG := by
  rcases (Module.FinitePresentation.iff_exists_exact_free_sequence R M).mp inferInstance with
    ⟨n, m, f, g, hfg, hg⟩
  rw [fittingIdeal_eq_presentationFittingIdeal (R := R) (M := M) k g hg]
  rw [LinearMap.exact_iff] at hfg
  have hfker : ∀ x, f x ∈ LinearMap.ker g := by
    intro x
    rw [hfg]
    exact LinearMap.mem_range_self f x
  let φ : (Fin m → R) →ₗ[R] LinearMap.ker g := LinearMap.codRestrict (LinearMap.ker g) f hfker
  have hφ : Function.Surjective φ := by
    intro x
    have hx : x.1 ∈ LinearMap.range f := by
      simpa [hfg] using x.2
    rcases hx with ⟨y, hy⟩
    refine ⟨y, ?_⟩
    apply Subtype.ext
    exact hy
  let A : Matrix (Fin n) (Fin m) R :=
    fun i j ↦ ((φ (Pi.single j (1 : R)) : LinearMap.ker g) : Fin n → R) i
  have hpresent :
      presentationFittingIdeal R M k g = Matrix.minorIdeal (n - k) A := by
    exact presentationFittingIdeal_eq_minorIdeal_of_surjective_fin_family
      (R := R) (M := M) g φ hφ
  -- Compute the presentation ideal from the finite family `φ`, then observe that the resulting
  -- determinantal ideal is the span of a finite set of minors.
  rw [hpresent, Matrix.minorIdeal]
  simpa [A] using
    (Submodule.fg_span
      (Set.finite_range
        (fun p : (Fin (n - k) ↪ Fin n) × (Fin (n - k) ↪ Fin m) ↦
          Matrix.det (Matrix.submatrix A p.1 p.2))) :
      (Ideal.span
        (Set.range fun p : (Fin (n - k) ↪ Fin n) × (Fin (n - k) ↪ Fin m) ↦
          Matrix.det (Matrix.submatrix A p.1 p.2))).FG)

/-- Helper for Lemma 15.8.4: the first minor ideal of a `1 × κ` matrix is the ideal spanned by
its entries. -/
private theorem matrix_minorIdeal_one_eq_span_single_row {κ : Type*} (A : Matrix (Fin 1) κ R) :
    Matrix.minorIdeal 1 A = Ideal.span (Set.range fun j : κ ↦ A (0 : Fin 1) j) := by
  classical
  rw [Matrix.minorIdeal]
  refine le_antisymm ?_ ?_
  · -- Every `1 × 1` minor is just one matrix entry from some chosen column.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨⟨e₁, e₂⟩, rfl⟩
    have he₁ : e₁ = Function.Embedding.refl (Fin 1) := by
      ext i
      exact congrArg Fin.val (Subsingleton.elim (e₁ i) i)
    rw [he₁]
    exact Ideal.subset_span ⟨e₂ (0 : Fin 1), by simp⟩
  · -- Conversely, each entry appears as the determinant of the minor picking that column.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨j, rfl⟩
    let e₂ : Fin 1 ↪ κ := ⟨fun _ ↦ j, fun _ _ _ ↦ Subsingleton.elim _ _⟩
    exact Ideal.subset_span ⟨⟨Function.Embedding.refl (Fin 1), e₂⟩, by
      simp [e₂]⟩

/-- Helper for Lemma 15.8.4: the entries of the kernel vectors in the rank-`1` quotient
presentation generate exactly the quotient ideal. -/
private theorem quotient_presentation_entry_span_eq_ideal (I : Ideal R) :
    let π : (Fin 1 → R) →ₗ[R] R ⧸ I :=
      (Ideal.Quotient.mkₐ R I).toLinearMap.comp (LinearEquiv.funUnique (Fin 1) R R).toLinearMap
    Ideal.span (Set.range fun x : LinearMap.ker π => x.1 (0 : Fin 1)) = I := by
  let e : (Fin 1 → R) ≃ₗ[R] R := LinearEquiv.funUnique (Fin 1) R R
  let π : (Fin 1 → R) →ₗ[R] R ⧸ I := (Ideal.Quotient.mkₐ R I).toLinearMap.comp e.toLinearMap
  change Ideal.span (Set.range fun x : LinearMap.ker π => x.1 (0 : Fin 1)) = I
  refine le_antisymm ?_ ?_
  · -- A kernel vector maps to zero in `R ⧸ I`, so its unique coordinate lies in `I`.
    refine Ideal.span_le.2 ?_
    rintro _ ⟨x, rfl⟩
    have hx := x.2
    change (Ideal.Quotient.mkₐ R I) (x.1 (0 : Fin 1)) = 0 at hx
    exact (Ideal.Quotient.eq_zero_iff_mem).1 hx
  · -- Every element of `I` gives a kernel vector by placing it in the unique source coordinate.
    intro r hr
    refine Ideal.subset_span ?_
    have hx : π (e.symm r) = 0 := by
      change (Ideal.Quotient.mkₐ R I) r = 0
      exact (Ideal.Quotient.eq_zero_iff_mem).2 hr
    refine ⟨⟨e.symm r, hx⟩, ?_⟩
    simp [e]

-- Proof sketch: use the standard one-generator presentation of `R ⧸ I`; its `1 × 1` minors are
-- exactly the elements of `I`, so the zeroth Fitting ideal recovers `I`.
/-- Lemma 15.8.4 (9): the zeroth Fitting ideal of the quotient module `R ⧸ I` is `I`. -/
theorem fittingIdeal_zero_quotient (I : Ideal R) :
    Fit[R]_(0)(R ⧸ I) = I := by
  let e : (Fin 1 → R) ≃ₗ[R] R := LinearEquiv.funUnique (Fin 1) R R
  let π : (Fin 1 → R) →ₗ[R] R ⧸ I := (Ideal.Quotient.mkₐ R I).toLinearMap.comp e.toLinearMap
  have hπ : Function.Surjective π := by
    -- The quotient map is surjective, and `Fin 1 → R` is canonically `R`.
    intro x
    obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective x
    refine ⟨e.symm r, ?_⟩
    simp [π, e]
  rw [fittingIdeal_eq_presentationFittingIdeal R (R ⧸ I) 0 π hπ]
  -- Route correction: for the quotient clause we stay on the source route and compute from the
  -- canonical one-generator quotient presentation rather than detouring through direct sums.
  calc
    presentationFittingIdeal R (R ⧸ I) 0 π
        = Matrix.minorIdeal 1 (fun i x ↦ x.1 i : Matrix (Fin 1) (LinearMap.ker π) R) := by
            simp [presentationFittingIdeal]
    _ = Ideal.span (Set.range fun x : LinearMap.ker π => x.1 0) := by
      exact matrix_minorIdeal_one_eq_span_single_row
        (R := R) (A := (fun i x ↦ x.1 i : Matrix (Fin 1) (LinearMap.ker π) R))
    _ = I := by
      simpa [π] using quotient_presentation_entry_span_eq_ideal (R := R) I

end
