import LinearRepresentations_Serre_1977.Chap17.Theorem_17_17_6_1.FixedConstituentTransportCover

universe u v w x

open scoped TensorProduct

namespace Representation

section

variable {p : ℕ}
variable {A : Type u} [CommRing A] [HenselianLocalRing A]
variable [CharP (IsLocalRing.ResidueField A) p]
variable {h : ℕ}
variable {G : Type v} [Group G] [Finite G]
variable {V : Type x} [AddCommGroup V] [Module (IsLocalRing.ResidueField A) V]
variable [FiniteDimensional (IsLocalRing.ResidueField A) V]

local notation "k" => IsLocalRing.ResidueField A
private noncomputable instance theorem171761TargetModule : Module A V :=
  Module.compHom V (algebraMap A k)
private instance theorem171761TargetScalarTower : IsScalarTower A k V :=
  IsScalarTower.of_algebraMap_smul fun _ _ ↦ rfl

/-- Helper for Theorem 17-17.6-1: a Hall-kernel element `x ∈ I` acts on the fixed lift carrier by
`ρA_I x`, and this literal action already lies in the transport fiber over `(x : G)`. This is the
source-faithful embedding of Serre's subgroup `I` into the total-space cover `G₁`. -/
noncomputable def fixed_constituent_transport_fiber_of_hall_kernel_element
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    (x : I) :
    fixed_constituent_transport_fiber
      (A := A) (G := G) I ρA_I (x : G) := by
  let ex : P_S ≃ₗ[A] P_S :=
    LinearEquiv.ofBijective (ρA_I x) (ρA_I.apply_bijective x)
  refine Representation.Equiv.mk ex ?_
  intro a
  ext v
  let b : I := (MulAut.conjNormal ((x : G))⁻¹) a
  have hmul : x * b = a * x := by
    apply Subtype.ext
    simp [b, mul_assoc]
  calc
    ex (((ρA_I.comp (MulAut.conjNormal ((x : G))⁻¹).toMonoidHom) a) v) =
        (ρA_I x) ((ρA_I b) v) := by
          simp [ex, b]
    _ = ρA_I (x * b) v := by
          simpa using (LinearMap.congr_fun (ρA_I.map_mul x b) v).symm
    _ = ρA_I (a * x) v := by
          rw [hmul]
    _ = ρA_I a (ρA_I x v) := by
          simpa using LinearMap.congr_fun (ρA_I.map_mul a x) v

/-- Helper for Theorem 17-17.6-1: transport-fiber elements over equal group elements are
heterogeneously equal when their underlying maps agree. -/
private theorem fixed_constituent_transport_fiber_heq_of_apply_eq_local
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G} (hst : s = t)
    {u : fixed_constituent_transport_fiber (A := A) (G := G) I ρA_I s}
    {v : fixed_constituent_transport_fiber (A := A) (G := G) I ρA_I t}
    (h : ∀ z : P_S, u z = v z) :
    HEq u v := by
  subst t
  apply heq_of_eq
  ext z
  exact h z

/-- Helper for Theorem 17-17.6-1: the literal Hall-kernel copy `x ↦ (x, ρA_I x)` is a monoid
homomorphism from `I` into Serre's total-space cover `G₁`. This is the generator family used
later to define the source-faithful subgroup `G₂`. -/
noncomputable def fixed_constituent_transport_total_space_embed_hall_kernel
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) :
    I →*
      fixed_constituent_transport_total_space (A := A) (G := G) I ρA_I where
  toFun x :=
    ⟨x,
      fixed_constituent_transport_fiber_of_hall_kernel_element
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) x⟩
  map_one' := by
    rw [fixed_constituent_transport_total_space_one
      (A := A) (G := G) (I := I) (ρA_I := ρA_I)]
    apply Sigma.ext
    · rfl
    · refine fixed_constituent_transport_fiber_heq_of_apply_eq_local I ρA_I rfl ?_
      intro v
      change (LinearEquiv.ofBijective (ρA_I 1) (ρA_I.apply_bijective 1)) v = v
      simp [LinearEquiv.ofBijective_apply]
  map_mul' x y := by
    rw [fixed_constituent_transport_total_space_mul_eq
      (A := A) (G := G) (I := I) (ρA_I := ρA_I)]
    apply Sigma.ext
    · rfl
    · refine fixed_constituent_transport_fiber_heq_of_apply_eq_local I ρA_I rfl ?_
      intro v
      change
        (LinearEquiv.ofBijective (ρA_I (x * y)) (ρA_I.apply_bijective (x * y))) v =
          (LinearEquiv.ofBijective (ρA_I x) (ρA_I.apply_bijective x))
            ((LinearEquiv.ofBijective (ρA_I y) (ρA_I.apply_bijective y)) v)
      simp [LinearEquiv.ofBijective_apply]

/-- Helper for Theorem 17-17.6-1: Serre's determinant subgroup `C` is generated by the
determinants of the lifted `I`-action on the fixed constituent lift. This isolates the later
determinant-normalization step defining the finite subgroup `G₂ ≤ G₁`. -/
noncomputable def fixed_constituent_action_det
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
  (ρA_I : Representation A I P_S)
  (x : I) : Aˣ :=
  (LinearMap.isUnit_det (ρA_I x) <| by
      refine ⟨⟨ρA_I x, ρA_I x⁻¹, ?_, ?_⟩, rfl⟩
      · ext y
        simp
      · ext y
        simp).unit

/-- Helper for Theorem 17-17.6-1: Serre's determinant subgroup `C` is generated by the
determinants of the lifted `I`-action on the fixed constituent lift. This isolates the later
determinant-normalization step defining the finite subgroup `G₂ ≤ G₁`. -/
noncomputable def fixed_constituent_determinant_subgroup
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) : Subgroup Aˣ :=
  Subgroup.closure
    (Set.range fun x : I ↦ fixed_constituent_action_det (A := A) (G := G) I ρA_I x)

/-- Helper for Theorem 17-17.6-1: the determinant of a transport-fiber element is the scalar data
that Serre uses to cut the finite subgroup `G₂` out of `G₁`. -/
noncomputable def fixed_constituent_transport_fiber_det
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s : G}
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) : Aˣ :=
  LinearEquiv.det u.toLinearEquiv

/-- Helper for Theorem 17-17.6-1: inverting a transport operator in `U_s` inverts its
determinant. This records the determinant behavior of Serre's literal inverse operation before
the scalar-kernel analysis of `U₁`. -/
theorem fixed_constituent_transport_fiber_det_inv
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s : G}
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I)
        (fixed_constituent_transport_fiber_inv
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u) =
      (fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u)⁻¹ := by
  -- The inverse fiber operator is the literal inverse linear equivalence on the fixed lift
  -- carrier, so its determinant is the inverse determinant.
  change LinearEquiv.det (u.toLinearEquiv.symm) = (LinearEquiv.det u.toLinearEquiv)⁻¹
  simpa using (LinearEquiv.det_symm u.toLinearEquiv)

/-- Helper for Theorem 17-17.6-1: composing transport operators multiplies their determinants.
This is the determinant bookkeeping for Serre's literal multiplication on the total space
`G₁ = Σ s, U_s`. -/
theorem fixed_constituent_transport_fiber_det_comp
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G}
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s)
    (v :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I t) :
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I)
        (fixed_constituent_transport_fiber_comp
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u v) =
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v *
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u := by
  -- The transported copy of `v` over `s` has the same underlying linear equivalence as `v`
  -- itself, so the determinant follows the usual multiplicative rule for composition.
  change LinearEquiv.det (v.toLinearEquiv.trans u.toLinearEquiv) =
      LinearEquiv.det v.toLinearEquiv * LinearEquiv.det u.toLinearEquiv
  rw [LinearEquiv.det_trans]
  ac_rfl

/-- Helper for Theorem 17-17.6-1: comparing two points in the same transport fiber `U_s`
produces a point in the kernel fiber `U₁`. This is Serre's literal reduction of same-fiber
comparison to the kernel before classifying `U₁ = Aˣ`. -/
noncomputable def fixed_constituent_transport_fiber_reindex
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G} (h : s = t) :
    fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s →
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I t :=
  by
    cases h
    intro u
    exact u

/-- Helper for Theorem 17-17.6-1: reindexing a transport fiber along an equality of indices
does not change the underlying determinant. This gives a transport-stable bridge from the raw
fiber `U_{s s⁻¹}` to the kernel fiber `U₁`. -/
@[simp] private theorem fixed_constituent_transport_fiber_det_reindex
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G} (h : s = t)
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I)
        (fixed_constituent_transport_fiber_reindex
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) h u) =
      fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u := by
  cases h
  rfl

/-- Helper for Theorem 17-17.6-1: reindexing a transport fiber along an equality of indices
does not change the underlying transport operator. -/
@[simp] theorem fixed_constituent_transport_fiber_reindex_apply
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G} (h : s = t)
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s)
    (x : P_S) :
    (fixed_constituent_transport_fiber_reindex
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) h u) x =
      u x := by
  cases h
  rfl

/-- Helper for Theorem 17-17.6-1: reindexing a transport fiber along an equality of indices
does not change the underlying linear map. -/
@[simp] theorem fixed_constituent_transport_fiber_reindex_toLinearMap_apply
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s t : G} (h : s = t)
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s)
    (x : P_S) :
    ((fixed_constituent_transport_fiber_reindex
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) h u).toLinearMap) x =
      u.toLinearMap x := by
  cases h
  rfl

/-- Helper for Theorem 17-17.6-1: comparing two points in the same transport fiber `U_s`
produces a point in the kernel fiber `U₁`. This is Serre's literal reduction of same-fiber
comparison to the kernel before classifying `U₁ = Aˣ`. -/
noncomputable def fixed_constituent_transport_fiber_ratio
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s : G}
    (u v :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    fixed_constituent_transport_fiber
      (A := A) (G := G) I ρA_I (1 : G) := by
  -- Compare two elements of the same fiber by multiplying one with the inverse of the other.
  exact
    fixed_constituent_transport_fiber_reindex
      (A := A) (G := G) (I := I) (ρA_I := ρA_I) (by simp)
      (fixed_constituent_transport_fiber_comp
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
        (fixed_constituent_transport_fiber_inv
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v))

/-- Helper for Theorem 17-17.6-1: the kernel ratio `u / v` composed with `v` recovers `u` on the
lift carrier. This is the transport-stable comparison identity needed when an arbitrary fiber
element is reduced through the chosen section point in the same fiber. -/
theorem fixed_constituent_transport_fiber_ratio_comp_right
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s : G}
    (u v :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    (fixed_constituent_transport_fiber_ratio
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u v).toLinearMap.comp
        v.toLinearMap =
      u.toLinearMap := by
  -- Unfold the ratio once: it is literally the product `u * v⁻¹` in the transport total space,
  -- so composing it with `v` cancels the inverse and returns `u`.
  ext x
  unfold fixed_constituent_transport_fiber_ratio
  rw [LinearMap.comp_apply]
  rw [fixed_constituent_transport_fiber_reindex_toLinearMap_apply]
  simp [fixed_constituent_transport_fiber_comp, fixed_constituent_transport_fiber_inv]

/-- Helper for Theorem 17-17.6-1: determinants of two elements in the same fiber differ by the
determinant of their kernel ratio in `U₁`. This isolates the exact source-faithful bridge from
fiberwise determinant cosets to the still-missing kernel classification. -/
theorem fixed_constituent_transport_fiber_det_eq_ratio_mul
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {s : G}
    (u v :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u =
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v *
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_ratio
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u v) := by
  have hraw :
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_comp
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
            (fixed_constituent_transport_fiber_inv
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) v)) =
        fixed_constituent_transport_fiber_det
            (A := A) (G := G) (I := I) (ρA_I := ρA_I)
            (fixed_constituent_transport_fiber_inv
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) v) *
          fixed_constituent_transport_fiber_det
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u := by
    -- The raw ratio is the literal product `u * v⁻¹` in the transport total space.
    exact
      fixed_constituent_transport_fiber_det_comp
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
        (fixed_constituent_transport_fiber_inv
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v)
  have hratio :
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_ratio
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u v) =
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_comp
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
            (fixed_constituent_transport_fiber_inv
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) v)) := by
    -- Reindexing from `U_{s s⁻¹}` to `U₁` leaves the determinant unchanged.
    unfold fixed_constituent_transport_fiber_ratio
    exact
      fixed_constituent_transport_fiber_det_reindex
        (A := A) (G := G) (I := I) (ρA_I := ρA_I)
        (s := s * s⁻¹) (t := 1) (by simp)
        (fixed_constituent_transport_fiber_comp
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
          (fixed_constituent_transport_fiber_inv
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) v))
  have hmul :
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v *
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_comp
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
            (fixed_constituent_transport_fiber_inv
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) v)) =
      fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u := by
    rw [hraw, fixed_constituent_transport_fiber_det_inv]
    simp
  calc
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u =
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v *
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_comp
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u
            (fixed_constituent_transport_fiber_inv
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) v)) := by
            exact hmul.symm
    _ =
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) v *
        fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_ratio
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u v) := by
              rw [hratio]

/-- Helper for Theorem 17-17.6-1: once an element of the kernel fiber `U₁` is identified with a
unit scalar homothety on the fixed lift carrier, its determinant is the corresponding `d`-th
power. This is Serre's literal determinant computation inside the scalar kernel `Aˣ`. -/
theorem linearEquiv_det_unit_smul_refl
    {M : Type*} [AddCommGroup M] [Module A M] [Module.Free A M]
    (a : Aˣ) :
    LinearEquiv.det (a • LinearEquiv.refl A M) = a ^ Module.finrank A M := by
  -- Reduce the determinant of the scalar linear equivalence to the determinant of the scalar
  -- identity linear map.
  apply Units.ext
  unfold LinearEquiv.det LinearMap.GeneralLinearGroup.generalLinearEquiv
  change
    LinearMap.det (((a • LinearEquiv.refl A M : M ≃ₗ[A] M) : M →ₗ[A] M)) =
      ((a ^ Module.finrank A M : Aˣ) : A)
  rw [show (((a • LinearEquiv.refl A M : M ≃ₗ[A] M) : M →ₗ[A] M)) =
      (a : A) • (LinearMap.id : M →ₗ[A] M) by rfl]
  rw [LinearMap.det_smul, LinearMap.det_id]
  simpa

/-- Helper for Theorem 17-17.6-1: once an element of the kernel fiber `U₁` is identified with a
unit scalar homothety on the fixed lift carrier, its determinant is the corresponding `d`-th
power. This is Serre's literal determinant computation inside the scalar kernel `Aˣ`. -/
theorem fixed_constituent_transport_kernel_det_eq_unit_pow
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    {u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I (1 : G)}
    {a : Aˣ}
    (hu : u.toLinearEquiv = a • LinearEquiv.refl A P_S) :
    fixed_constituent_transport_fiber_det
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u =
      a ^ Module.finrank A P_S := by
  -- Replace the kernel transport by the scalar homothety given by the kernel classification.
  unfold fixed_constituent_transport_fiber_det
  rw [hu]
  -- Delegate the scalar determinant calculation to the generic homothety lemma above.
  exact linearEquiv_det_unit_smul_refl (A := A) (M := P_S) a

/-- Helper for Theorem 17-17.6-1: assuming Serre's kernel statement `U₁ = Aˣ`, every determinant
in a fiber `U_s` differs from the determinant of the chosen section element by a `d`-th power of
a unit. This isolates the determinant-coset step before the later normalization to `G₂`. -/
theorem fixed_constituent_transport_fiber_det_eq_section_det_mul_unit_pow_of_kernel_scalar
    (hp : Nat.Prime p)
    (I : Subgroup G) [I.Normal]
    (hIcop : Nat.Coprime p (Nat.card I))
    (ρ : Representation k G V)
    (Sbar : Subrepresentation (ρ.comp I.subtype))
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    (red_S : P_S →ₗ[A] Sbar.toSubmodule)
    (hLiftSbar : IsResidueFieldLift Sbar.toRepresentation ρA_I red_S)
    (hTransport :
      ∀ s : G,
        Nonempty
          (Sbar.toRepresentation.Equiv
            (transportedSubrepresentation ρ Sbar s).toRepresentation))
    (hTransportLift :
      ∀ s : G,
        IsResidueFieldLift
          (transportedSubrepresentation ρ Sbar s).toRepresentation
          ρA_I
          (((hTransport s).some.toLinearMap.restrictScalars A).comp red_S))
    (hkernel :
      ∀ u :
        fixed_constituent_transport_fiber
          (A := A) (G := G) I ρA_I (1 : G),
        ∃ a : Aˣ, u.toLinearEquiv = a • LinearEquiv.refl A P_S)
    (s : G)
    (u :
      fixed_constituent_transport_fiber
        (A := A) (G := G) I ρA_I s) :
    ∃ a : Aˣ,
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u =
        fixed_constituent_transport_fiber_det
            (A := A) (G := G) (I := I) (ρA_I := ρA_I)
            ((fixed_constituent_transport_total_space_section
              (p := p) (A := A) (G := G) (V := V)
              hp I hIcop ρ Sbar ρA_I red_S hLiftSbar hTransport hTransportLift s).2) *
          a ^ Module.finrank A P_S := by
  let u0 :=
    (fixed_constituent_transport_total_space_section
      (p := p) (A := A) (G := G) (V := V)
      hp I hIcop ρ Sbar ρA_I red_S hLiftSbar hTransport hTransportLift s).2
  -- Compare the arbitrary point in `U_s` with the chosen section point by the kernel ratio.
  obtain ⟨a, ha⟩ :=
    hkernel
      (fixed_constituent_transport_fiber_ratio
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u u0)
  refine ⟨a, ?_⟩
  have hratio :
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I) u =
        fixed_constituent_transport_fiber_det
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u0 *
          fixed_constituent_transport_fiber_det
            (A := A) (G := G) (I := I) (ρA_I := ρA_I)
            (fixed_constituent_transport_fiber_ratio
              (A := A) (G := G) (I := I) (ρA_I := ρA_I) u u0) := by
    -- The ratio lemma is the literal source reduction from the fiber `U_s` to the kernel `U₁`.
    exact
      fixed_constituent_transport_fiber_det_eq_ratio_mul
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) u u0
  have hratio_det :
      fixed_constituent_transport_fiber_det
          (A := A) (G := G) (I := I) (ρA_I := ρA_I)
          (fixed_constituent_transport_fiber_ratio
            (A := A) (G := G) (I := I) (ρA_I := ρA_I) u u0) =
        a ^ Module.finrank A P_S := by
    -- The kernel classification converts the ratio determinant into a plain `d`-th power.
    exact
      fixed_constituent_transport_kernel_det_eq_unit_pow
        (A := A) (G := G) (I := I) (ρA_I := ρA_I) ha
  simpa [u0, hratio_det] using hratio

/-- Helper for Theorem 17-17.6-1: this structure isolates the finite central-extension stage in
Serre's source proof before the final lower-height recursion on the quotient module `τ`. -/
private structure ConstituentProjectiveExtensionQuotientData
    (I : Subgroup G) [I.Normal]
    (ρ : Representation k G V)
    (Sbar : Subrepresentation (ρ.comp I.subtype))
    (P_S : Type (max u v x)) [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    (red_S : P_S →ₗ[A] Sbar.toSubmodule) where
  G2 : Type v
  instGroupG2 : Group G2
  instFiniteG2 : Finite G2
  pi : G2 →* G
  I2 : Subgroup G2
  instNormalI2 : I2.Normal
  Nbar : Subgroup (G2 ⧸ I2)
  instNormalNbar : Nbar.Normal
  hNbar_central : Nbar ≤ Subgroup.center (G2 ⧸ I2)
  hNbar_cyclic : IsCyclic Nbar
  hNbar_coprime : Nat.Coprime p (Nat.card Nbar)
  tau : Representation k (G2 ⧸ I2) (fixed_isotypic_multiplicity_space (I := I) (ρ := ρ) Sbar)
  tau_irred : tau.IsIrreducible
  quotientEquiv : ((G2 ⧸ I2) ⧸ Nbar) ≃* (G ⧸ I)
  descendLift :
    ∀ {P_tau : Type (max u v x)} (_ : AddCommGroup P_tau) (_ : Module A P_tau)
      (_ : Module.Free A P_tau) (_ : Module.Finite A P_tau)
      (ρA_tau : Representation A (G2 ⧸ I2) P_tau)
      (red_tau :
        P_tau →ₗ[A] fixed_isotypic_multiplicity_space (I := I) (ρ := ρ) Sbar),
        IsResidueFieldLift tau ρA_tau red_tau →
          ∃ (P : Type (max u v x)) (_ : AddCommGroup P) (_ : Module A P)
            (_ : Module.Free A P) (_ : Module.Finite A P)
            (ρA : Representation A G P)
            (red : P →ₗ[A] V),
              IsResidueFieldLift ρ ρA red

attribute [instance]
  ConstituentProjectiveExtensionQuotientData.instGroupG2
  ConstituentProjectiveExtensionQuotientData.instFiniteG2
  ConstituentProjectiveExtensionQuotientData.instNormalI2
  ConstituentProjectiveExtensionQuotientData.instNormalNbar

/-- Helper for Theorem 17-17.6-1: if a free `A[N]`-representation reduces to the trivial
`k[N]`-representation and `|N|` is prime to `p`, then the lifted `A[N]`-representation is already
trivial. This isolates the Chapter `15` descent step used after building Serre's finite projective
cover. -/
theorem isTrivial_of_residueFieldLift_trivial_of_coprime_card
    (hp : Nat.Prime p)
    {N : Type u} [Group N] [Finite N]
    {W : Type*} [AddCommGroup W] [Module k W] [FiniteDimensional k W]
    {P : Type*} [AddCommGroup P] [Module A P]
    [Module.Free A P] [Module.Finite A P]
    {ρA : Representation A N P}
    {red : P →ₗ[A] W}
    (hLift : IsResidueFieldLift (Representation.trivial k N W) ρA red)
    (hNcop : Nat.Coprime p (Nat.card N)) :
    Representation.IsTrivial ρA := by
  have hNndvd : ¬ p ∣ Nat.card N := hp.coprime_iff_not_dvd.mp hNcop
  have hBaseChange : IsBaseChange k red := hLift.1
  have hTrivialLift :
      IsResidueFieldLift
        (Representation.trivial k N W)
        (Representation.trivial A N P)
        red := by
    let ρAtriv : Representation A N P := Representation.trivial A N P
    letI : Module (MonoidAlgebra A N) P := Module.compHom P ρAtriv.asAlgebraHom.toRingHom
    letI : IsScalarTower A (MonoidAlgebra A N) P :=
      IsScalarTower.of_algebraMap_smul fun a x ↦ by
        change ρAtriv.asAlgebraHom (algebraMap A (MonoidAlgebra A N) a) x = a • x
        simpa [Algebra.smul_def] using LinearMap.congr_fun (ρAtriv.asAlgebraHom.commutes a) x
    let ρltriv : Representation k N W := Representation.trivial k N W
    letI : Module (MonoidAlgebra k N) W := Module.compHom W ρltriv.asAlgebraHom.toRingHom
    letI : IsScalarTower k (MonoidAlgebra k N) W :=
      IsScalarTower.of_algebraMap_smul fun a x ↦ by
        change ρltriv.asAlgebraHom (algebraMap k (MonoidAlgebra k N) a) x = a • x
        simpa [Algebra.smul_def] using LinearMap.congr_fun (ρltriv.asAlgebraHom.commutes a) x
    letI : Module (MonoidAlgebra A N) W :=
      Module.compHom W (MonoidAlgebra.mapRingHom N (algebraMap A k))
    letI : IsScalarTower A (MonoidAlgebra A N) W :=
      IsScalarTower.of_algebraMap_smul fun a x ↦ by
        change
          (MonoidAlgebra.mapRingHom N (algebraMap A k))
              (MonoidAlgebra.single (1 : N) a) • x =
            a • x
        rw [MonoidAlgebra.mapRingHom_single]
        have hsingle :
            MonoidAlgebra.single (1 : N) (IsLocalRing.residue A a) =
              algebraMap k (MonoidAlgebra k N) (IsLocalRing.residue A a) := by
          rw [MonoidAlgebra.single_eq_algebraMap_mul_of]
          simp
        calc
          MonoidAlgebra.single (1 : N) (IsLocalRing.residue A a) • x
              = (IsLocalRing.residue A a) • x := by
                  simpa only [hsingle] using
                    (IsScalarTower.algebraMap_smul (MonoidAlgebra k N)
                      (IsLocalRing.residue A a) x)
          _ = a • x := by
                simpa [IsLocalRing.ResidueField.algebraMap_eq] using
                  (IsScalarTower.algebraMap_smul k a x)
    change red.IsResidueFieldReduction N
    constructor
    · -- The base-change witness is unchanged when both source and target actions are trivial.
      exact hBaseChange
    · -- Equivariance becomes the tautological fixed-point relation for the trivial action.
      refine Representation.IsIntertwiningMap.mk ?_
      intro g x
      have hsrc : MonoidAlgebra.single g (1 : A) • x = x := by
        change (ρAtriv.asAlgebraHom (MonoidAlgebra.single g (1 : A))) x = x
        rw [Representation.asAlgebraHom_single]
        simpa using Representation.isTrivial_apply ρAtriv g x
      have htgt : MonoidAlgebra.single g (1 : A) • red x = red x := by
        change
          (MonoidAlgebra.mapRingHom N (algebraMap A k) (MonoidAlgebra.single g (1 : A))) •
            red x =
            red x
        rw [MonoidAlgebra.mapRingHom_single]
        change (ρltriv.asAlgebraHom (MonoidAlgebra.single g (1 : k))) (red x) = red x
        rw [Representation.asAlgebraHom_single]
        simpa using Representation.isTrivial_apply ρltriv g (red x)
      simpa [Representation.ofModule'] using
        calc
          red (MonoidAlgebra.single g (1 : A) • x) = red x := by rw [hsrc]
          _ = MonoidAlgebra.single g (1 : A) • red x := by rw [htgt]
  obtain ⟨e, _⟩ :=
    residueFieldLift_unique_up_to_equivariant_iso
      (A := A) (p := p) (G := N) (V := W)
      hNndvd
      (Representation.trivial k N W)
      (Representation.trivial A N P) red hTrivialLift
      ρA red hLift
  refine Representation.IsTrivial.mk ?_
  intro g
  ext x
  -- Compare `ρA g` with the trivial action by conjugating through the unique lift equivalence.
  have hEq := LinearMap.congr_fun (e.isIntertwining' g) (e.symm x)
  have hEq' : (ρA g) (e (e.symm x)) = e (e.symm x) := by
    simpa [Representation.trivial] using hEq.symm
  simpa using hEq'

/-- Helper for Theorem 17-17.6-1: the determinant of the fixed lifted `I`-action is a genuine
group homomorphism `I → Aˣ`. This is the owner used to identify Serre's determinant subgroup `C`
with a finite image subgroup. -/
noncomputable def fixed_constituent_action_det_hom
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) : I →* Aˣ where
  toFun := fixed_constituent_action_det (A := A) (G := G) I ρA_I
  map_one' := by
    -- The identity element acts as the identity linear map, whose determinant is `1`.
    apply Units.ext
    change LinearMap.det (ρA_I 1) = 1
    simp
  map_mul' x y := by
    -- Determinant turns Serre's multiplicative `I`-action into multiplication in `Aˣ`.
    apply Units.ext
    change LinearMap.det (ρA_I (x * y)) = LinearMap.det (ρA_I x) * LinearMap.det (ρA_I y)
    rw [map_mul]
    exact LinearMap.det_comp (ρA_I x) (ρA_I y)

/-- Helper for Theorem 17-17.6-1: Serre's determinant subgroup `C` is exactly the range of the
determinant homomorphism on the fixed lifted `I`-action. This packages the earlier closure
definition into a finite subgroup owner. -/
theorem fixed_constituent_determinant_subgroup_eq_range
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) :
    fixed_constituent_determinant_subgroup (A := A) (G := G) (I := I) ρA_I =
      (fixed_constituent_action_det_hom (A := A) (G := G) (I := I) ρA_I).range := by
  -- The defining generators of `C` already lie in the image subgroup, and conversely every image
  -- point is one of those generators.
  unfold fixed_constituent_determinant_subgroup
  refine Subgroup.closure_eq_of_le
    ((fixed_constituent_action_det_hom (A := A) (G := G) (I := I) ρA_I).range) ?_ ?_
  · intro a ha
    rcases ha with ⟨x, rfl⟩
    exact ⟨x, rfl⟩
  · rintro a ⟨x, rfl⟩
    exact Subgroup.subset_closure ⟨x, rfl⟩

/-- Helper for Theorem 17-17.6-1: the determinant subgroup `C` of the fixed lifted Hall-kernel
action has order dividing `|I|`. This is the finite-group part of Serre's determinant
normalization stage. -/
theorem fixed_constituent_determinant_subgroup_card_dvd
    (I : Subgroup G) [I.Normal]
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) :
    Nat.card (fixed_constituent_determinant_subgroup (A := A) (G := G) (I := I) ρA_I) ∣
      Nat.card I := by
  -- Replace `C` by the determinant-image subgroup and apply the standard cardinal divisibility for
  -- the range of a homomorphism from a finite group.
  rw [fixed_constituent_determinant_subgroup_eq_range
    (A := A) (G := G) (I := I) (ρA_I := ρA_I)]
  exact Subgroup.card_range_dvd (fixed_constituent_action_det_hom
    (A := A) (G := G) (I := I) ρA_I)

/-- Helper for Theorem 17-17.6-1: the determinant subgroup `C` has order prime to `p` because it
is a quotient of the Hall kernel `I`, whose order is already prime to `p`. -/
theorem fixed_constituent_determinant_subgroup_coprime
    (I : Subgroup G) [I.Normal]
    (hIcop : Nat.Coprime p (Nat.card I))
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S) :
    Nat.Coprime p
      (Nat.card (fixed_constituent_determinant_subgroup (A := A) (G := G) (I := I) ρA_I)) := by
  -- Coprimality descends along the determinant-image divisibility just proved above.
  exact hIcop.of_dvd_right
    (fixed_constituent_determinant_subgroup_card_dvd
      (A := A) (G := G) (I := I) ρA_I)

/-- Helper for Theorem 17-17.6-1: the fixed lifted constituent has the same finite rank over `A`
as its reduced constituent has over the residue field `k`. This is the rank comparison extracted
from the residue-field lift witness. -/
theorem fixed_constituent_lift_finrank_eq
    (I : Subgroup G) [I.Normal]
    (ρ : Representation k G V)
    (Sbar : Subrepresentation (ρ.comp I.subtype))
    (hSbar_irred : Sbar.toRepresentation.IsIrreducible)
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    (red_S : P_S →ₗ[A] Sbar.toSubmodule)
    (hLiftSbar : IsResidueFieldLift Sbar.toRepresentation ρA_I red_S) :
    Module.finrank A P_S = Module.finrank k Sbar.toSubmodule := by
  letI : Module k k := Semiring.toModule
  letI : FiniteDimensional k Sbar.toSubmodule :=
    IsIrreducible.finiteDimensional_of_finite Sbar.toRepresentation
  letI : Module A k := Module.compHom k (algebraMap A k)
  letI : IsScalarTower A k k :=
    moduleCompHomIsScalarTower (R := A) (S := k) (M := k)
  letI : SMulCommClass k A k :=
    moduleCompHomSMulCommClass (R := A) (S := k) (M := k)
  letI : Module (MonoidAlgebra A I) P_S := representationCarrierGroupAlgebraModule ρA_I
  letI : IsScalarTower A (MonoidAlgebra A I) P_S :=
    representationCarrierGroupAlgebraIsScalarTower ρA_I
  letI : Module (MonoidAlgebra k I) Sbar.toSubmodule :=
    representationCarrierGroupAlgebraModule Sbar.toRepresentation
  letI : IsScalarTower k (MonoidAlgebra k I) Sbar.toSubmodule :=
    representationCarrierGroupAlgebraIsScalarTower Sbar.toRepresentation
  let hred : red_S.IsResidueFieldReduction I := hLiftSbar
  -- The base-change equivalence in the reduction owner preserves finite rank exactly.
  have hbase :
      Module.finrank k (k ⊗[A] P_S) = Module.finrank A P_S := by
    exact Module.finrank_baseChange (R := k) (S := A) (M' := P_S)
  exact hbase.symm.trans hred.1.equiv.finrank_eq

/-- Helper for Theorem 17-17.6-1: the fixed lifted constituent has nonzero finite rank because
its residue-field reduction is an irreducible `I`-representation. -/
theorem fixed_constituent_lift_finrank_ne_zero
    (I : Subgroup G) [I.Normal]
    (hIcop : Nat.Coprime p (Nat.card I))
    (ρ : Representation k G V)
    (Sbar : Subrepresentation (ρ.comp I.subtype))
    (hSbar_irred : Sbar.toRepresentation.IsIrreducible)
    {P_S : Type (max u v x)} [AddCommGroup P_S] [Module A P_S]
    [Module.Free A P_S] [Module.Finite A P_S]
    (ρA_I : Representation A I P_S)
    (red_S : P_S →ₗ[A] Sbar.toSubmodule)
    (hLiftSbar : IsResidueFieldLift Sbar.toRepresentation ρA_I red_S) :
    Module.finrank A P_S ≠ 0 := by
  letI : FiniteDimensional k Sbar.toSubmodule :=
    IsIrreducible.finiteDimensional_of_finite Sbar.toRepresentation
  letI : Module (MonoidAlgebra k I) Sbar.toSubmodule :=
    Sbar.toRepresentation.instModuleMonoidAlgebraAsModule
  letI : IsSimpleModule (MonoidAlgebra k I) Sbar.toSubmodule :=
    (irreducible_iff_isSimpleModule_asModule Sbar.toRepresentation).mp hSbar_irred
  letI : Nontrivial Sbar.toSubmodule :=
    IsSimpleModule.nontrivial (MonoidAlgebra k I) Sbar.toSubmodule
  have hred_pos : 0 < Module.finrank k Sbar.toSubmodule := Module.finrank_pos
  rw [fixed_constituent_lift_finrank_eq
    (A := A) (G := G) (I := I) (ρ := ρ) (Sbar := Sbar) hSbar_irred ρA_I red_S hLiftSbar]
  exact Nat.ne_of_gt hred_pos

end

end Representation
