import Mathlib
import ConvexAnalysis_Rockafellar_1970.Chap01.Text_5_4_7
import ConvexAnalysis_Rockafellar_1970.Chap03.Theorem_12_2
import ConvexAnalysis_Rockafellar_1970.Chap03.Text_12_3_6
import ConvexAnalysis_Rockafellar_1970.Chap03.Corollary_13_2_1

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

universe u v

open scoped Rockafellar
open Function

section

variable {𝕜 : Type*} {X : Type u} {Y : Type v}
variable [Field 𝕜] [ConditionallyCompleteLinearOrder 𝕜] [IsOrderedRing 𝕜]
variable [TopologicalSpace 𝕜]
variable [TopologicalSpace X] [AddCommGroup X] [Module 𝕜 X] [FiniteDimensional 𝕜 X]
variable [AddCommMonoid Y] [Module 𝕜 Y]
variable [HasLinearPairing X Y 𝕜] [HasContinuousPairing X Y 𝕜]

/-!
Source/core/bridge triage for this item.

- `source-facing`: Theorem 13.5 identifies two support functions coming from the zero sublevel
  sets of a closed proper convex function and of its conjugate with the closures of the positively
  homogeneous convex functions generated by `f*` and `f`, respectively.
- `core/canonical`: the owner abstractions already present in the project are `supportFunction`,
  `convexConjugate`, `lowerSemicontinuousHull`, `Function.sublinearHull`,
  `Function.IsClosedProperConvex`, and the dual owner lemmas
  `Function.IsConvex.biconjugate_eq_lowerSemicontinuousHull`,
  `convexConjugate_lowerSemicontinuousHull_eq`,
  `nonpositiveSublevel_convexConjugate_eq_setOf_forall_pairing_le`.
- `bridge/view`: the theorem surface uses the chapter notation `δᵛ(· | ·)` and `cl(·)` for the
  support-function and lower-semicontinuous-hull owners, while the sets
  `{x | f(x) ≤ 0}` and `{x⋆ | f*(x⋆) ≤ 0}` are kept directly as zero sublevel sets of `f` and
  `convexConjugate f`.

Domain-style sampling used here:
- `supportFunction` from Defintion 4.8.2;
- `Function.sublinearHull` from Text 5.4.7;
- `lowerSemicontinuousHull_eq_supportFunction_setOf_forall_pairing_le` and
  `nonpositiveSublevel_convexConjugate_eq_setOf_forall_pairing_le` from Corollary 13.2.1;
- `Function.IsConvex.biconjugate_eq_lowerSemicontinuousHull` from Theorem 12.2.

Primitive data vs derived API:
- primitive input for clause `(2)`: a proper convex function
  `f : X → WithBotTop 𝕜` on a finite-dimensional module `X` over `𝕜` with a continuous linear
  pairing to `Y`, given through the owner predicates `f.IsConvex 𝕜` and `f.IsProper`;
- derived API: clause `(2)`, the source-facing identity for the generated function of `f`, and
  clause `(1)`, its dual companion for `f⋆`, obtained by combining clause `(2)` with the closed
  proper convex owner theorems for Fenchel conjugation and biconjugacy on the self-pairing layer.

Layer target: `source-facing`, stated directly with the canonical project owners rather than by
introducing a wrapper for the generated functions or a local alias for the zero sublevel sets.
-/

variable (f : X → WithBotTop 𝕜)

-- Proof sketch: apply Corollary 13.2.1 directly to the positively homogeneous convex function
-- generated by `f`, and rewrite the resulting support set with
-- `nonpositiveSublevel_convexConjugate_eq_setOf_forall_pairing_le`.
/-- Theorem 13.5 (2): for a proper convex function `f` on a finite-dimensional module with a
continuous linear pairing, the closure of the generated function, written on the theorem surface as
`cl(sublinearHull f)`, is the support function of the zero sublevel set
`{x⋆ | f*(x⋆) ≤ 0}`. Closedness is not part of this clause because the left-hand side is already a
closure. -/
theorem lowerSemicontinuousHull_generatedBy_eq_supportFunction_nonpositiveSublevel_convexConjugate
    (hf_convex : f.IsConvex 𝕜) (hf_proper : f.IsProper)
    :
    cl(sublinearHull f) =
      (δᵛ(· | {yStar : Y | f⋆ yStar ≤ 0}) : X → WithBotTop 𝕜) := sorry

end

section

variable {𝕜 : Type*} {E : Type u}
variable [Field 𝕜] [ConditionallyCompleteLinearOrder 𝕜] [IsOrderedRing 𝕜]
variable [TopologicalSpace 𝕜] [TopologicalSpace (WithBotTop 𝕜)]
variable [TopologicalSpace E] [AddCommGroup E] [Module 𝕜 E] [FiniteDimensional 𝕜 E]
variable [HasLinearPairing E E 𝕜] [HasContinuousPairing E E 𝕜]
local notation "IsClosedProperConvex[" 𝕜 "]" => Function.IsClosedProperConvex (𝕜 := 𝕜)

variable (f : E → WithBotTop 𝕜)

-- Proof sketch: apply clause (2) to `f⋆`. The closed-proper-convex owner API supplies the same
-- hypothesis for `f⋆`, and closed-convex biconjugacy rewrites the resulting nonpositive sublevel
-- set `{x | f⋆⋆ x ≤ 0}` to `{x | f x ≤ 0}`.
/-- Theorem 13.5 (1): for a closed proper convex function `f` on a finite-dimensional module with
a continuous linear self-pairing, the support function of the zero sublevel set
`{x | f x ≤ 0}` is the closure of the generated function of `f⋆`, written on
the theorem surface as `cl(sublinearHull f⋆)`. -/
theorem supportFunction_nonpositiveSublevel_eq_lowerSemicontinuousHull_generatedBy_convexConjugate
    (hf : IsClosedProperConvex[𝕜] f)
    :
    (δᵛ(· | {x : E | f x ≤ 0}) : E → WithBotTop 𝕜) = cl(sublinearHull f⋆) := sorry

end
