import Mathlib.Analysis.InnerProductSpace.l2Space

-- Declarations for this item will be appended below by the statement pipeline.

open scoped BigOperators Topology InnerProductSpace

universe u v

section

variable {ι : Type v}
variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]

/- Source/core/bridge triage:
- `source-facing`: Proposition 29.15 states the projection formulas for the closed span of an
  orthonormal family and for a one-dimensional subspace generated by a unit vector.
- `core/canonical`: the owner abstraction is `Submodule.starProjection`.
- `bridge/view`: `HilbertBasis.hasSum_orthogonalProjection` gives the closed-span series formula
  once the orthonormal family is viewed as a Hilbert basis of its closed span, and
  `Submodule.starProjection_unit_singleton` is the canonical one-dimensional specialization. -/

/-- Proposition 29.15 (1): if `e` is a countable orthonormal family in a real Hilbert space, then
the orthogonal projection onto the closed span of `Set.range e` is the orthogonal series
`∑' i, ⟪x, e i⟫_ℝ • e i`. -/
theorem starProjection_closedSpan_eq_tsum_of_orthonormal
    (e : ι → H) (he : Orthonormal ℝ e) (x : H) :
    ((Submodule.span ℝ (Set.range e)).topologicalClosure).starProjection x =
      ∑' i : ι, ⟪x, e i⟫_ℝ • e i := by
  let S : Submodule ℝ H := Submodule.span ℝ (Set.range e)
  let U : Submodule ℝ H := S.topologicalClosure
  have hU_closed : IsClosed (U : Set H) := by
    simpa [U] using Submodule.isClosed_topologicalClosure S
  letI : IsClosed (U : Set H) := hU_closed
  let v : ι → U := fun i ↦
    ⟨e i, (Submodule.le_topologicalClosure S) (Submodule.subset_span (Set.mem_range_self i))⟩
  have hv : Orthonormal ℝ v := by
    simpa [v] using he
  have hU :
      ⊤ ≤ (Submodule.span ℝ (Set.range v)).topologicalClosure := by
    intro y hy
    change y ∈ closure ((Submodule.span ℝ (Set.range v) : Submodule ℝ U) : Set U)
    rw [closure_subtype]
    have hrange : U.subtype '' Set.range v = Set.range e := by
      ext z
      constructor
      · rintro ⟨w, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, rfl⟩
      · rintro ⟨i, rfl⟩
        exact ⟨v i, ⟨i, rfl⟩, rfl⟩
    have hmap :
        (Submodule.span ℝ (Set.range v)).map U.subtype = S := by
      rw [Submodule.map_span, hrange]
    have hcarrier :
        Subtype.val '' ((Submodule.span ℝ (Set.range v) : Submodule ℝ U) : Set U) =
          (S : Set H) := by
      simpa [Submodule.map_coe, Submodule.coe_subtype] using
        congrArg (fun p : Submodule ℝ H ↦ (p : Set H)) hmap
    have hy' : (y : H) ∈ closure (S : Set H) := by
      simpa [U, S] using y.property
    simpa [hcarrier] using hy'
  let b : HilbertBasis ι ℝ U :=
    @HilbertBasis.mk ι ℝ _ U _ _ (hU_closed.completeSpace_coe) v hv hU
  have hb : (b : ι → U) = v := by
    simpa [b] using
      (@HilbertBasis.coe_mk ι ℝ _ U _ _ (hU_closed.completeSpace_coe) v hv hU :
        ((@HilbertBasis.mk ι ℝ _ U _ _ (hU_closed.completeSpace_coe) v hv hU :
            HilbertBasis ι ℝ U) : ι → U) = v)
  have hsum' : HasSum (fun i : ι ↦ ⟪(b i : H), x⟫_ℝ • (b i : H)) (U.starProjection x) := by
    simpa only [Submodule.starProjection_apply] using
      (@HilbertBasis.hasSum_orthogonalProjection ι ℝ _ H _ _ U
        (hU_closed.completeSpace_coe) b x).mapL U.subtypeL
  have hsum : HasSum (fun i : ι ↦ ⟪x, e i⟫_ℝ • e i) (U.starProjection x) := by
    simpa [hb, v, real_inner_comm] using hsum'
  exact hsum.tsum_eq.symm

end

section

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- Proposition 29.15 (2): if `u` is a unit vector, then the orthogonal projection onto the line
`ℝ ∙ u` is `x ↦ ⟪x, u⟫_ℝ • u`. -/
theorem starProjection_spanSingleton_eq_inner_smul_of_norm_eq_one
    (u x : H) (hu : ‖u‖ = 1) :
    (ℝ ∙ u).starProjection x = ⟪x, u⟫_ℝ • u := by
  have hproj : (ℝ ∙ u).starProjection x = ⟪u, x⟫_ℝ • u :=
    @Submodule.starProjection_unit_singleton ℝ H _ _ _ u hu x
  simpa [real_inner_comm] using hproj

end
