-- Proof rescue support index.
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.InheritedProjectionDescent
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.ForgetToSource
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.ForgetToSourceDescent
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.PullbackNaturality
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.LiteralBaseReindex
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.LiteralBaseDescentLaws
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetTransfer
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetPathTransport
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetPathLift
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetPathOverlap
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetPathTail
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetOverlap
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.TargetReconstruction
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.Gluing
import stacks_proof.stacks_project.Chap08.Lemma_8_10_5.Reconstruction
