name = "Serre"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Serre"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "Serre"

[[lean_lib]]
name = "serre"

[[lean_lib]]
name = "serre_docs"
srcDir = "."
roots = [
  "Serre.Chap01",
  "Serre.Chap02",
  "Serre.Chap03",
]
