import Mathlib
import StacksProject_2024.stacks_project.Chap10.Definition_10_135_5
import StacksProject_2024.stacks_project.Chap10.Lemma_10_104_2
import StacksProject_2024.stacks_project.Chap10.Lemma_10_106_3
import StacksProject_2024.stacks_project.Chap10.Lemma_10_106_4

-- Declarations for this item will be appended below by the statement pipeline.

universe u v w

section

variable {A : Type u} {B : Type v} {C : Type w}
variable [CommRing A] [CommRing B] [CommRing C]
variable [IsRegularLocalRing A] [IsRegularLocalRing B] [IsLocalRing C]

/- Domain-style sampling pass.

Primary domain: surjective local homomorphisms of regular local rings, with kernels generated by
regular sequences and compared through quotient dimension formulas.

Sampled owner declarations:
* `RingHom.KernelIsGeneratedByRegularSequence`;
* `Module.regularLocalRing_selfModule_cohenMacaulay`;
* `Module.isRegular_iff_ringKrullDim_quotient_add_length_eq`;
* `IsLocalRing.exists_regularSystemOfParameters_with_prefix_span_eq_of_quotient_isRegularLocalRing`.

Best owner abstraction: the kernel predicate
`RingHom.KernelIsGeneratedByRegularSequence` is the primitive source-facing owner. The numerical
clauses about `dim(A) - dim(C)` and `dim(B) - dim(C)` generators are derived API, obtained by
combining the Cohen-Macaulay self-module owner for regular local rings with the quotient
dimension criterion for regular sequences, plus the parameter-system presentation of kernels of
surjections whose source and quotient are regular local.

Primitive vs. derived:
* primitive data: the surjective local maps `A → B → C` and the owner predicates on
  `RingHom.ker (ψ.comp φ)` and `RingHom.ker ψ`;
* derived API: finite generating families of those kernels whose cardinalities match the relevant
  dimension drops.

Source/core/bridge triage:
* source-facing: the `List.TFAE` comparison between the two kernels in Lemma `10.135.6`;
* core/canonical: `RingHom.KernelIsGeneratedByRegularSequence` and the regular-local/Cohen-Macaulay
  owner theorems above;
* bridge/view: the explicit `Fin d → A` and `Fin d → B` families spanning the two kernels.
-/

-- Proof sketch: `A` and `B` are Cohen-Macaulay as modules over themselves by the regular-local
-- owner instance from Lemma `10.106.3`. For each surjective map onto the regular local quotient
-- `C`, Lemma `10.104.2` converts the kernel regular-sequence owner into the additive dimension
-- criterion `ringKrullDim C + d = ringKrullDim _` together with a `d`-element generating family.
-- Lemma `10.106.4` supplies the same expected-number-of-generators presentation for the kernel of
-- `φ`, so the two kernel conditions are equivalent by comparing the composite quotient
-- `A ⧸ ker (ψ.comp φ)` with the successive quotients through `B`.
/-- Lemma 10.135.6: for surjective local ring homomorphisms `A → B → C` with `A` and `B` regular
local, the following are equivalent: the kernel of `A → C` is generated by a regular sequence, the
kernel of `A → C` is generated by `dim(A) - dim(C)` elements, the kernel of `B → C` is generated by
a regular sequence, and the kernel of `B → C` is generated by `dim(B) - dim(C)` elements. -/
theorem ker_generatedBy_regularSequence_tfae_of_surjective_local_of_isRegularLocalRing
    (φ : A →+* B) (ψ : B →+* C) [IsLocalHom φ] [IsLocalHom ψ]
    (hφ : Function.Surjective φ) (hψ : Function.Surjective ψ) :
    List.TFAE
      [ (ψ.comp φ).KernelIsGeneratedByRegularSequence
      , ∃ (d : ℕ) (_ : ringKrullDim C + d = ringKrullDim A) (x : Fin d → A),
          Ideal.span (Set.range x) = RingHom.ker (ψ.comp φ)
      , ψ.KernelIsGeneratedByRegularSequence
      , ∃ (d : ℕ) (_ : ringKrullDim C + d = ringKrullDim B) (y : Fin d → B),
          Ideal.span (Set.range y) = RingHom.ker ψ
      ] := sorry

end
