import Mathlib
import StacksProject_2024.stacks_project.Chap10.Definition_10_60_10
import StacksProject_2024.stacks_project.Chap10.Definition_10_103_1
import StacksProject_2024.stacks_project.Chap10.Definition_10_68_1
import StacksProject_2024.stacks_project.Chap10.Lemma_10_60_14

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open RingTheory Sequence IsLocalRing

section

variable {R : Type u} [CommRing R] [IsRegularLocalRing R]

/- Domain-style sampling pass.

Primary domain: local commutative algebra of regular local rings, regular systems of parameters,
regular sequences, and the self-module Cohen-Macaulay condition.

Sampled owner declarations:
* `IsLocalRing.IsRegularSystemOfParameters`;
* `IsLocalRing.parameterIdeal`;
* `ringKrullDim_quotient_parameterIdeal_eq_sub` from `Chap10/Lemma_10_60_14.lean`;
* `Module.CohenMacaulay`.

Best owner abstraction: the source-facing chosen-family owner is
`IsLocalRing.IsRegularSystemOfParameters x` for a family `x : Fin d → maximalIdeal R`, and the
prefix quotients are canonically `R ⧸ parameterIdeal (x ∘ Fin.castLE hi)`. The public statements
below should therefore live at that owner level; the underlying `List.ofFn` regular sequence is a
derived bridge/view, while the Cohen-Macaulay conclusion lands directly in the owner
`Module.CohenMacaulay R R`.

Primitive vs. derived:
* primitive data: the regular-local owner hypothesis `[IsRegularLocalRing R]`, a length `d`, a
  chosen family `x : Fin d → maximalIdeal R`, and the owner hypothesis
  `hx : IsRegularSystemOfParameters x`;
* derived API: regularity of the underlying sequence `List.ofFn fun i ↦ (x i : R)`,
  regular-locality and dimension formulas for the prefix quotients
  `R ⧸ parameterIdeal (x ∘ Fin.castLE hi)`, and the self-module owner instance
  `Module.CohenMacaulay R R`.

Source/core/bridge triage:
* source-facing: parts (1)–(3), stated for a regular system of parameters and its canonical prefix
  quotients;
* core/canonical: `IsRegularLocalRing R`, `IsRegularSystemOfParameters`, `parameterIdeal`, and
  `Module.CohenMacaulay R R`;
* bridge/view: the regularity statement for the underlying list
  `List.ofFn fun i ↦ (x i : R)`.
-/

namespace IsLocalRing

-- Proof sketch: a regular system of parameters is already the canonical chosen-family owner for a
-- minimal generating family of `maximalIdeal R`. Part (1) is therefore only the derived bridge
-- from that owner to the regularity of the underlying ordered sequence.
/-- Lemma 10.106.3 (1): if `x : Fin d → maximalIdeal R` is a regular system of parameters, then
the underlying list `List.ofFn fun i ↦ (x i : R)` is a regular sequence. -/
theorem IsRegularSystemOfParameters.isRegular {d : ℕ} {x : Fin d → maximalIdeal R}
    (hx : IsRegularSystemOfParameters x) :
    IsRegular R (List.ofFn fun i ↦ (x i : R)) := sorry

-- Proof sketch: quotient successively by the initial entries of a regular system of parameters.
-- The quotient owner is stated canonically with the prefix parameter ideal
-- `parameterIdeal (x ∘ Fin.castLE hi)` rather than via an ad hoc list prefix.
/-- Lemma 10.106.3 (2): if `x : Fin d → maximalIdeal R` is a regular system of parameters, then
every quotient by a prefix parameter ideal is again a regular local ring. -/
theorem IsRegularSystemOfParameters.isRegularLocalRing_quotient_parameterIdeal {d i : ℕ}
    {x : Fin d → maximalIdeal R} (hx : IsRegularSystemOfParameters x) (hi : i ≤ d) :
    IsRegularLocalRing (R ⧸ parameterIdeal (x ∘ Fin.castLE hi)) := sorry

-- Proof sketch: the owner-level quotient-dimension formula is already available from
-- `ringKrullDim_quotient_parameterIdeal_eq_sub`; the present statement is its additive reformulation
-- specialized to a regular system of parameters.
/-- Lemma 10.106.3 (3): if `x : Fin d → maximalIdeal R` is a regular system of parameters, then
the quotient by its first `i` parameters has Krull dimension `d - i`, written canonically as
`ringKrullDim (R ⧸ parameterIdeal (x ∘ Fin.castLE hi)) + i = ringKrullDim R`. -/
theorem IsRegularSystemOfParameters.ringKrullDim_quotient_parameterIdeal_add_eq {d i : ℕ}
    {x : Fin d → maximalIdeal R} (hx : IsRegularSystemOfParameters x) (hi : i ≤ d) :
    ringKrullDim (R ⧸ parameterIdeal (x ∘ Fin.castLE hi)) + i = ringKrullDim R := sorry

-- Proof sketch: unpack the extension witness in
-- `IsPartOfRegularSystemOfParameters`, apply the full regular-system theorem to the appended
-- family, and identify the prefix parameter ideal with `parameterIdeal x`.
/-- If `x` is part of a regular system of parameters, then quotienting by the ideal generated by
`x` yields a regular local ring. This is the owner-level derived view on
`IsPartOfRegularSystemOfParameters`; no extra wrapper around the prefix family is needed. -/
theorem IsPartOfRegularSystemOfParameters.isRegularLocalRing_quotient_parameterIdeal
    {d c : ℕ} {x : Fin c → maximalIdeal R} (hx : IsPartOfRegularSystemOfParameters d x) :
    IsRegularLocalRing (R ⧸ parameterIdeal x) := by
  sorry

-- Proof sketch: unpack the extension witness in
-- `IsPartOfRegularSystemOfParameters`, use regularity of the full appended regular system of
-- parameters, and pass to the initial segment corresponding to `x`.
/-- If `x` is part of a regular system of parameters, then its underlying list is a regular
sequence. This is the canonical list-level bridge derived from the owner
`IsPartOfRegularSystemOfParameters`. -/
theorem IsPartOfRegularSystemOfParameters.isRegular
    {d c : ℕ} {x : Fin c → maximalIdeal R} (hx : IsPartOfRegularSystemOfParameters d x) :
    IsRegular R (List.ofFn fun i ↦ (x i : R)) := by
  sorry

end IsLocalRing

-- Proof sketch: choose a regular system of parameters for `R`, apply the regularity and prefix
-- quotient statements above, and conclude by the depth-equals-dimension owner criterion for the
-- self-module `R`.
/-- Lemma 10.106.3 (4): a regular local ring is Cohen-Macaulay when viewed as a module over
itself. -/
instance regularLocalRing_selfModule_cohenMacaulay : Module.CohenMacaulay R R := sorry

end
