import Mathlib.RingTheory.Ideal.Pure
import Mathlib.Tactic.TFAE
import StacksProject_2024.stacks_project.Chap05.Lemma_5_12_12
import StacksProject_2024.stacks_project.Chap10.Lemma_10_21_3

-- Declarations for this item will be appended below by the statement pipeline.

universe u

open PrimeSpectrum

section

variable {R : Type u} [CommRing R]

namespace Ideal

/-- An ideal is generated by idempotents if it is spanned by its idempotent elements. -/
def IsGeneratedByIdempotents (I : Ideal R) : Prop :=
  Ideal.span {e : R | IsIdempotentElem e ∧ e ∈ I} = I

/-- The span of idempotents is generated by idempotents. -/
private theorem isGeneratedByIdempotents_span {S : Set R} (hS : ∀ e ∈ S, IsIdempotentElem e) :
    (Ideal.span S : Ideal R).IsGeneratedByIdempotents := by
  rw [IsGeneratedByIdempotents]
  refine le_antisymm ?_ ?_
  · exact Ideal.span_le.2 fun e he ↦ he.2
  · exact Ideal.span_mono fun e he ↦ ⟨hS e he, Ideal.subset_span he⟩

-- Proof sketch: use the Stacks criterion behind this lemma to show that such an ideal satisfies the
-- finite-generation test for purity, reducing generators one idempotent at a time.
/-- An ideal generated by idempotents is pure. -/
theorem IsGeneratedByIdempotents.pure {I : Ideal R} (hI : I.IsGeneratedByIdempotents) :
    I.Pure :=
  sorry

end Ideal

variable (T : Set (PrimeSpectrum R))

/- Domain-style sampling:
- primary domain: commutative algebra and prime-spectrum topology for closed unions of connected
  components, clopen subsets, and pure ideals;
- same-domain owner declarations inspected:
  `isClosed_of_isIntersectionOfClopens`,
  `isIntersectionOfClopens_of_isClosed_of_union_connectedComponents`,
  `Ideal.Pure`,
  `Ideal.zeroLocus_inj_of_pure`;
- best owner abstraction:
  `source-facing`: `Ideal.IsGeneratedByIdempotents` for the new ideal-side clause in this file;
  `core/canonical`: the chapter-5 clopen/connected-component theorems and the mathlib owner
    `Ideal.Pure`;
  `bridge/view`: the existential `⋂₀` presentation of `T` and the uniqueness statement obtained
    from `Ideal.zeroLocus_inj_of_pure`.

Primitive data are only the ring `R`, the subset `T : Set (PrimeSpectrum R)`, and the ideal
`I : Ideal R`. The clopen-intersection clause and the pure-ideal uniqueness step are derived from
the existing owners above, so the only owner this file needs to keep locally is the source-facing
predicate `Ideal.IsGeneratedByIdempotents`. -/

-- Proof sketch: `(1) ↔ (2)` is the spectral-space topology statement that closed unions of
-- connected components are exactly intersections of clopens by
-- `isClosed_of_isIntersectionOfClopens`,
-- `connectedComponent_subset_of_isIntersectionOfClopens`, and
-- `isIntersectionOfClopens_of_isClosed_of_union_connectedComponents`. For `(2) → (3)`, write
-- each clopen as `D(e)` using Lemma 10.21.3 and rewrite the intersection as the zero locus of the
-- ideal generated by the complementary idempotents. For `(3) → (2)`, express `V(I)` as the
-- intersection of the clopens `V(e) = D(1 - e)` coming from idempotent generators of `I`.
/-- Lemma 10.22.1 (1): for a subset `T ⊆ Spec(R)`, the following are equivalent: `T` is closed and a
union of connected components of `Spec(R)`; `T` is an intersection of open and closed subsets of
`Spec(R)`; and `T = V(I)` for an ideal `I` of `R` generated by idempotents. -/
theorem primeSpectrum_tfae_closed_union_components_sInter_clopens_zeroLocus_generatedByIdempotents :
    List.TFAE
      [ IsClosed T ∧ ∀ x ∈ T, connectedComponent x ⊆ T
      , ∃ S : Set (Set (PrimeSpectrum R)), (∀ Z ∈ S, IsClopen Z) ∧ T = ⋂₀ S
      , ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I ] := sorry

/-- If `T ⊆ Spec(R)` is closed and a union of connected components, then `T = V(I)` for an ideal
generated by idempotents. -/
theorem exists_ideal_isGeneratedByIdempotents_zeroLocus_eq
    (hT : IsClosed T ∧ ∀ x ∈ T, connectedComponent x ⊆ T) :
    ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I :=
  ((primeSpectrum_tfae_closed_union_components_sInter_clopens_zeroLocus_generatedByIdempotents
    T).out 0 2).mp hT

-- Proof sketch: any ideal generated by idempotents is pure, so uniqueness follows from
-- `Ideal.zeroLocus_inj_of_pure` once two such ideals define the same closed subset of `Spec(R)`.
/-- Lemma 10.22.1 (2): if `T = V(I)` for an ideal `I` generated by idempotents, then `I` is unique. -/
theorem existsUnique_ideal_isGeneratedByIdempotents_zeroLocus_eq
    (hT : ∃ I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I) :
    ∃! I : Ideal R, I.IsGeneratedByIdempotents ∧ T = zeroLocus I := by
  rcases hT with ⟨I, hI, hzero⟩
  refine ⟨I, ⟨hI, hzero⟩, fun J hJ ↦ ?_⟩
  letI : I.Pure := hI.pure
  letI : J.Pure := hJ.1.pure
  exact ((Ideal.zeroLocus_inj_of_pure).mp <| by
    simpa [hzero] using hJ.2).symm

end
