import Mathlib
import StacksProject_2024.stacks_project.Chap10.Definition_10_48_3

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory Limits
open AlgebraicGeometry CommRingCat

universe u

namespace Algebra

section

variable {k A : Type u} [Field k] [CommRing A] [Algebra k A]

/-- Geometric connectedness descends along injective algebra morphisms. -/
-- Proof sketch: an injective map `B →ₐ[k] A` induces an injective map after tensoring with
-- `AlgebraicClosure k`; then use the prime-spectrum/idempotent characterization of connectedness.
private theorem geometricallyConnected_of_injective {B : Type u} [CommRing B] [Algebra k B]
    (f : B →ₐ[k] A) (hf : Function.Injective f) :
    geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k A))) →
      geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k B))) := sorry

/-- Lemma 10.48.5 (1): every `k`-subalgebra of a geometrically connected `k`-algebra is
geometrically connected over `k`. -/
-- Proof sketch: apply `geometricallyConnected_of_injective` to the inclusion of the subalgebra.
theorem geometricallyConnected_subalgebra (S : Subalgebra k A) :
    geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k A))) →
      geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k S))) :=
  geometricallyConnected_of_injective S.val Subtype.val_injective

/-- Lemma 10.48.5 (2): if all finitely generated `k`-subalgebras of `A` are geometrically
connected over `k`, then `A` is geometrically connected over `k`. -/
-- Proof sketch: argue using the characterization by nontrivial idempotents after base change and
-- the fact that any idempotent in the tensor product comes from a finitely generated subalgebra.
theorem geometricallyConnected_of_forall_fg
    (h : ∀ S : Subalgebra k A, S.FG →
      geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k S)))) :
    geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k A))) := sorry

end

section

variable {k I : Type u} [Field k] [Preorder I] [IsDirectedOrder I]

/-- Lemma 10.48.5 (3): a directed colimit of geometrically connected `k`-algebras is
geometrically connected over `k`. -/
-- Proof sketch: if the index type is empty, the colimit in `CommAlgCat k` is the initial
-- `k`-algebra `k`, which is geometrically connected by `Definition_10_48_3`. Otherwise every
-- finitely generated `k`-subalgebra of the colimit is generated by finitely many elements coming
-- from stages of the directed system; move those generators to a common stage and apply
-- `geometricallyConnected_of_forall_fg`.
theorem geometricallyConnected_colimit_of_directedSystem
    (F : I ⥤ CommAlgCat k)
    (hF : ∀ i,
      geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k (F.obj i))))) :
    geometrically (ConnectedSpace ·) (Spec.map (ofHom (algebraMap k (colimit F : CommAlgCat k)))) :=
  sorry

end

end Algebra
