import Mathlib
import StacksProject_2024.Chap10.Definition_10_42_1

-- Declarations for this item will be appended below by the statement pipeline.

open scoped IntermediateField

universe u v

section

variable {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]

/-- A point `y` is a one-element separable generator over the transcendence basis `x` if adjoining
`y` to the field generated by `x` yields all of `K`, and `y` is separable over that generated
field. -/
def IsOneSeparableGeneratorOver
    (x : Fin (Cardinal.toNat (Algebra.trdeg k K)) → K) (y : K) : Prop :=
  IntermediateField.adjoin k (Set.range x ∪ {y}) = ⊤ ∧
    IsSeparable (IntermediateField.adjoin k (Set.range x)) y

-- Proof sketch: choose a transcendence basis witnessing separable generation, replace it by a
-- basis indexed by `Fin (Cardinal.toNat (Algebra.trdeg k K))`, and then apply the primitive
-- element theorem to the finite separable extension over the generated intermediate field.
/-- Lemma 10.42.3: if `K / k` is a separably generated, finitely generated field extension and
`r = Cardinal.toNat (Algebra.trdeg k K)`, then there are `r` elements of `K` forming a
transcendence basis over `k` together with one additional element whose union with that basis
generates `K`, and which is separable over the field generated by the basis. -/
theorem exists_transcendence_basis_and_one_separable_generator
    [Algebra.EssFiniteType k K]
    [Algebra.IsSeparablyGenerated k K] :
    ∃ x : Fin (Cardinal.toNat (Algebra.trdeg k K)) → K,
      IsTranscendenceBasis k x ∧ ∃ y : K, IsOneSeparableGeneratorOver x y := sorry

end
