import Mathlib
import StacksProject_2024.Chap15.Lemma_15_11_2
import StacksProject_2024.Chap15.Lemma_15_11_9
import StacksProject_2024.Chap15.Lemma_15_11_15
import StacksProject_2024.Chap15.Lemma_15_92_3
import StacksProject_2024.Chap15.Lemma_15_94_9

-- Declarations for this item will be appended below by the statement pipeline.

universe u

section

variable {A : Type u} [CommRing A] {I : Ideal A}

/-
Domain-style sampling:
- primary domain: derived completeness of the ring `A`, viewed as an `A`-module, and the induced
  henselian pair structure on `(A, I)`;
- sampled owner-side declarations:
  `ModuleCat.IsDerivedCompleteWithRespectTo`,
  `HenselianRing`,
  `ModuleCat.surjective_adicCompletion_of_isDerivedCompleteWithRespectTo`,
  `principalPowerIntersection_sq_eq_bot_of_ring_isDerivedComplete`;
- best owner abstraction: the source-facing statement should conclude directly in the canonical
  owner `HenselianRing A I`; the source hypothesis is already the chapter owner
  `(ModuleCat.of A A).IsDerivedCompleteWithRespectTo I`, so no additional wrapper around henselian
  pairs or derived-complete rings is appropriate here;
- primitive data: the ring `A`, the ideal `I`, and the derived-completeness hypothesis on the
  canonical `A`-module `ModuleCat.of A A`;
- derived API: principal-ideal reduction through `largestHenselianIdeal`, the principal completion
  surjectivity bridge
  `ModuleCat.surjective_adicCompletion_of_isDerivedCompleteWithRespectTo`, the locally nilpotent
  henselian owner bridge `henselianRing_of_isLocallyNilpotent`, the quotient comparison
  `henselianRing_iff_henselianRing_and_quotient_henselianRing`, and the canonical mathlib
  completion-to-henselian bridge `IsAdicComplete.henselianRing`.

Source/core/bridge triage:
- `source-facing`: the theorem below, matching the Stacks statement that derived completeness of
  `A` with respect to `I` makes `(A, I)` a henselian pair;
- `core/canonical`: `HenselianRing A I` together with the owner predicate
  `ModuleCat.IsDerivedCompleteWithRespectTo`;
- `bridge/view`: the principal-adic completion and nilpotent-intersection lemmas used to pass from
  derived completeness to the henselian owner.
-/

-- Proof sketch: use the canonical maximal owner `largestHenselianIdeal` from Lemma `15.11.15` to
-- reduce to the principal ideals generated by elements of `I`. For a fixed `f ∈ I`, derived
-- completeness with respect to `I` restricts to derived completeness with respect to the principal
-- ideal `(f)`, so Lemma `15.92.3` makes the map to the `f`-adic completion surjective. The target
-- quotient is henselian by the canonical completion owner bridge `IsAdicComplete.henselianRing`,
-- and Lemma `15.11.9` reduces the original henselianity statement to showing that the
-- intersection `⋂ n, (f)^n` is locally nilpotent; this follows from Lemma `15.94.9` together with
-- the locally nilpotent owner bridge `henselianRing_of_isLocallyNilpotent`.
/-- Lemma 15.94.10: if the ring `A`, viewed as an `A`-module, is derived complete with respect to
an ideal `I`, then the canonical owner predicate `HenselianRing A I` holds. -/
theorem henselianRing_of_isDerivedCompleteWithRespectTo
    (hA : (ModuleCat.of A A).IsDerivedCompleteWithRespectTo I) :
    HenselianRing A I := sorry

end
