import Mathlib
import StacksProject_2024.Chap15.Definition_15_30_1
import StacksProject_2024.Chap15.Lemma_15_30_11

-- Declarations for this item will be appended below by the statement pipeline.

universe u

namespace RingTheory.Sequence

variable {A : Type u} [CommRing A]

/-
Domain triage:
* primary domain: Koszul-regular finite sequences in commutative algebra and their behavior under
  quotienting by the ideal generated by an initial block;
* sampled owner declarations:
  `RingTheory.Sequence.IsKoszulRegularSequence`,
  `RingTheory.Sequence.isKoszulRegularSequence_append_of_quotient`,
  `Ideal.ofList_ofFn_eq_span_range`,
  `RingTheory.Sequence.IsQuasiRegular.tail_quotient`;
* best owner abstraction: the finite-family owner predicate `IsKoszulRegularSequence`, with the
  canonical quotient-by-prefix ideal expressed chapter-wide as `Ideal.ofList (List.ofFn f)`;
* primitive data vs derived API: the primitive source data are the families `f`, `g`, and the two
  Koszul-regularity hypotheses; the source-facing quotient by `Ideal.span (Set.range f)` is a
  derived view obtained from the owner-level quotient by `Ideal.ofList (List.ofFn f)`.
-/

-- Proof sketch: use Lemma 15.28.12 to identify the Koszul complex on `Fin.append f g` with the
-- total complex of the tensor product of the Koszul complexes on `f` and `g`. Since `f` is
-- Koszul-regular, the complex on `f` resolves `A ⧸ Ideal.span (Set.range f)`, so tensoring with the
-- complex on `g` identifies the homology with that of the Koszul complex on the image family of
-- `g` in the quotient ring. The assumed Koszul-regularity of `Fin.append f g` then forces all
-- positive homology of that quotient Koszul complex to vanish.
private theorem isKoszulRegularSequence_quotient_of_append_ofList {n m : ℕ} (f : Fin n → A)
    (g : Fin m → A) (hf : IsKoszulRegularSequence f)
    (hfg : IsKoszulRegularSequence (Fin.append f g)) :
    IsKoszulRegularSequence (fun i ↦ Ideal.Quotient.mk (Ideal.ofList (List.ofFn f)) (g i)) := by
  sorry

/-- Lemma 15.30.14: if both `f_1, \ldots, f_n` and the concatenated family
`f_1, \ldots, f_n, g_1, \ldots, g_m` are Koszul-regular sequences in `A`, then the images of
`g_1, \ldots, g_m` in `A / (f_1, \ldots, f_n)` form a Koszul-regular sequence. -/
theorem isKoszulRegularSequence_quotient_of_append {n m : ℕ} (f : Fin n → A) (g : Fin m → A)
    (hf : IsKoszulRegularSequence f) (hfg : IsKoszulRegularSequence (Fin.append f g)) :
    IsKoszulRegularSequence (fun i ↦ Ideal.Quotient.mk (Ideal.span (Set.range f)) (g i)) := by
  rw [← Ideal.ofList_ofFn_eq_span_range f]
  exact isKoszulRegularSequence_quotient_of_append_ofList f g hf hfg

end RingTheory.Sequence
