import Mathlib.Algebra.Module.LocalizedModule.AtPrime
import Mathlib.RingTheory.Localization.AtPrime.Basic
import StacksProject_2024.Chap15.Lemma_15_8_1
import StacksProject_2024.Chap15.Lemma_15_97_1

-- Declarations for this item will be appended below by the statement pipeline.

noncomputable section

open Matrix
open scoped nonZeroDivisors

universe u

section

variable {A : Type u} [CommRing A]

local notation "CpxA" => CochainComplex (ModuleCat A) ℤ

open scoped EtaDeterminantalIdeal

/- Domain-style sampling:
- primary domain: determinantal ideals of cochain-complex presentation maps, localized at a prime
  and compared with powers of a nonzerodivisor;
- sampled owner declarations:
  `etaDeterminantalIdeal`,
  `etaPresentationLinearMap`,
  `fittingIdeal_eq_presentationFittingIdeal`,
  `fittingIdeal_baseChange`;
- best owner abstraction:
  `source-facing`: `etaDeterminantalIdeal`, the degree-`i` ideal attached to `(f, d^i)`;
  `core/canonical`: the intrinsic Fitting-ideal owner from `15.97.1`;
  `bridge/view`: the chosen-basis matrix of `etaPresentationLinearMap f M i`, used only to
    compare the owner with the classical maximal-minors presentation;
- primitive data vs. derived API: the primitive public data already live in `15.97.1` as the map
  `etaPresentationLinearMap f M i` and its quotient. The matrix formula here is derived bridge
  data and should not be a second owner. -/

-- Proof sketch: compute the intrinsic owner `etaDeterminantalIdeal` from the canonical quotient
-- presentation `etaPresentationQuotient f M i`, then identify that quotient with the cokernel of
-- the chosen matrix of `etaPresentationLinearMap f M i`.
/-- The intrinsic determinantal ideal `I_i(M^\bullet, f)` is computed from the maximal minors of
the chosen matrix of `(f, d^i)`. -/
theorem etaDeterminantalIdeal_def (f : A) (M : CpxA) (i : ℤ)
    [Module.Free A (M.X i)] [Module.Finite A (M.X i)]
    [Module.Free A (M.X (i + 1))] [Module.Finite A (M.X (i + 1))] :
    let bi := Module.Free.chooseBasis A (M.X i)
    let bi1 := Module.Free.chooseBasis A (M.X (i + 1))
    I[f]_(i)(M) =
      I_((Module.finrank A (M.X i)))(
        (LinearMap.toMatrix bi (bi.prod bi1) (etaPresentationLinearMap f M i))) := sorry

local instance etaDeterminantalIdealTermModuleFree
    {M : CpxA} [hMff : CategoryTheory.CochainComplex.IsTermwiseFiniteFree M] (j : ℤ) :
    Module.Free A (M.X j) :=
  (hMff j).1

local instance etaDeterminantalIdealTermModuleFinite
    {M : CpxA} [hMff : CategoryTheory.CochainComplex.IsTermwiseFiniteFree M] (j : ℤ) :
    Module.Finite A (M.X j) :=
  (hMff j).2

-- Proof sketch: localize at `p`, use the base-change formula for `I_i(M^\bullet, f)` and the
-- invariance under replacing `M^\bullet` by a quasi-isomorphic bounded finite free complex, then
-- apply the splitting result for complexes with free localized cohomology to replace `M^\bullet_p`
-- by the zero-differential complex on its cohomology. For a zero-differential complex, `(f, d^i)`
-- becomes `(f, 0)`, whose maximal minors generate a power of `f`.
/-- Lemma 15.97.4: let `A` be a ring, let `𝔭 ⊂ A` be a prime ideal, and let `f ∈ A` be a
nonzerodivisor. Let `M^\bullet` be a bounded complex of finite free `A`-modules. If
`H^i(M^\bullet)_𝔭` is free for all `i`, then `I_i(M^\bullet, f)_𝔭` is generated by a power of the
image of `f` for every `i`. -/
theorem etaDeterminantalIdeal_atPrime_eq_principalIdeal_pow_of_homology_free
    (p : PrimeSpectrum A) (f : A) (hf : f ∈ nonZeroDivisors A) (M : CpxA)
    (hboundedBelow : ∃ a : ℤ, M.IsStrictlyGE a)
    (hboundedAbove : ∃ b : ℤ, M.IsStrictlyLE b)
    [CategoryTheory.CochainComplex.IsTermwiseFiniteFree M]
    (hcohom :
      ∀ j : ℤ,
        Module.Free (Localization.AtPrime p.asIdeal)
          (LocalizedModule.AtPrime p.asIdeal (M.homology j)))
    (i : ℤ) :
    let Aₚ := Localization.AtPrime p.asIdeal
    ∃ n : ℕ,
      Ideal.map (algebraMap A Aₚ) (I[f]_(i)(M)) =
        principalIdeal ((algebraMap A Aₚ f) ^ n) := sorry

end
