import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations

-- Declarations for this item will be appended below by the statement pipeline.

universe u v

section

variable {R : Type u} [CommRing R]

/-- The principal ideal `(f)` of a commutative ring `R`. -/
abbrev principalIdeal (f : R) : Ideal R :=
  Ideal.span ({f} : Set R)

/- Textbook notation for the principal ideal `(f)`, attached to the owner `principalIdeal`. -/
scoped[PrincipalIdeal] notation:max "(" f:max ")" => principalIdeal f

open scoped PrincipalIdeal

/-- The principal ideal `(f)` is finitely generated. -/
theorem principalIdeal_fg (f : R) : ((f) : Ideal R).FG := by
  simpa [principalIdeal] using
    (Submodule.fg_span_singleton f : (Ideal.span ({f} : Set R)).FG)

/-- The principal ideal `(f^n)` of a commutative ring `R`. -/
abbrev principalPowerIdeal (f : R) (n : ℕ) : Ideal R :=
  ((f) : Ideal R) ^ n

/-- The `(f)`-adic completion of a commutative ring `R`. -/
abbrev principalAdicCompletion (f : R) :=
  AdicCompletion ((f) : Ideal R) R

theorem principalIdeal_le_comap_of_map_eq
    {S : Type v} [CommRing S] (σ : R →+* S) {x : R} {y : S} (hxy : σ x = y) :
    ((x) : Ideal R) ≤ Ideal.comap σ ((y) : Ideal S) := by
  rw [principalIdeal, Ideal.span_le]
  intro z hz
  change σ z ∈ ((y) : Ideal S)
  rcases Set.mem_singleton_iff.mp hz with rfl
  rw [hxy, principalIdeal]
  exact Ideal.subset_span (by simp)

/-- The quotient map induced by `σ` between principal quotients when `σ x = y`. -/
abbrev principalIdealQuotientMap
    {S : Type v} [CommRing S] (σ : R →+* S) (x : R) {y : S} (hxy : σ x = y) :
    R ⧸ ((x) : Ideal R) →+* S ⧸ ((y) : Ideal S) :=
  Ideal.quotientMap _ σ (principalIdeal_le_comap_of_map_eq σ hxy)

theorem principalPowerIdeal_le_comap_of_map_eq
    {S : Type v} [CommRing S] (σ : R →+* S) {x : R} {y : S} (hxy : σ x = y) (n : ℕ) :
    principalPowerIdeal x n ≤ Ideal.comap σ (principalPowerIdeal y n) := by
  have hpow : σ (x ^ n) = y ^ n := by
    simpa [hxy] using map_pow σ x n
  simpa [principalPowerIdeal, principalIdeal, Ideal.span_singleton_pow, hpow] using
    principalIdeal_le_comap_of_map_eq σ hpow

/-- For `n ≥ 1`, the principal ideal `(x^n)` maps into the principal ideal generated by the image
of `x`. -/
theorem principalPowerIdeal_le_comap_principalIdeal
    {S : Type v} [CommRing S] (σ : R →+* S) (x : R) {n : ℕ} (hn : 1 ≤ n) :
    principalPowerIdeal x n ≤ Ideal.comap σ (principalIdeal (σ x)) := by
  refine (principalPowerIdeal_le_comap_of_map_eq σ rfl n).trans ?_
  refine Ideal.comap_mono ?_
  have hn' : n ≠ 0 := Nat.pos_iff_ne_zero.mp (Nat.succ_le_iff.mp hn)
  simpa [principalPowerIdeal, principalIdeal, Ideal.span_singleton_pow] using
    (Ideal.pow_le_self (I := principalIdeal (σ x)) hn')

/-- The quotient map induced by `σ` between principal-power quotients when `σ x = y`. -/
abbrev principalPowerIdealQuotientMap
    {S : Type v} [CommRing S] (σ : R →+* S) (x : R) {y : S} (hxy : σ x = y) (n : ℕ) :
    R ⧸ principalPowerIdeal x n →+* S ⧸ principalPowerIdeal y n :=
  Ideal.quotientMap _ σ (principalPowerIdeal_le_comap_of_map_eq σ hxy n)

/-- The quotient map induced by `σ` from modulo `(x^n)` to modulo `((σ x)^n)`. -/
abbrev principalPowerIdealImageQuotientMap
    {S : Type v} [CommRing S] (σ : R →+* S) (x : R) (n : ℕ) :
    R ⧸ principalPowerIdeal x n →+* S ⧸ principalPowerIdeal (σ x) n :=
  principalPowerIdealQuotientMap σ x rfl n

/-- For `n ≥ 1`, the quotient map induced by `σ` from modulo `(x^n)` to modulo `(σ x)`. -/
abbrev principalPowerIdealReductionMap
    {S : Type v} [CommRing S] (σ : R →+* S) (x : R) {n : ℕ} (hn : 1 ≤ n) :
    R ⧸ principalPowerIdeal x n →+* S ⧸ principalIdeal (σ x) :=
  Ideal.quotientMap _ σ (principalPowerIdeal_le_comap_principalIdeal σ x hn)

end
