import Mathlib.AlgebraicGeometry.Sites.Fpqc
import Mathlib.CategoryTheory.Sites.Sheaf

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory
open AlgebraicGeometry

universe w v

/- Semantic recall for this item:
`lean_leansearch` surfaced `CategoryTheory.Presheaf.IsSheaf`,
`CategoryTheory.Presieve.IsSheafFor`, and `AlgebraicGeometry.Scheme.grothendieckTopology`; the
fixed-family clause is the presieve sheaf condition for `Presieve.ofArrows`, and the fpqc clause
is the sheaf condition for the scheme Grothendieck topology generated by flat and quasi-compact
morphisms together with joint surjectivity. -/

/-- Definition 34.9.13 (1): a contravariant set-valued functor on schemes satisfies the sheaf
property for a fixed family `U i ⟶ T` when it satisfies the canonical presieve sheaf condition for
that family. -/
abbrev satisfiesSheafPropertyForFamily
    (F : Schemeᵒᵖ ⥤ Type v) {ι : Type w} {T : Scheme}
    (U : ι → Scheme) (f : ∀ i, U i ⟶ T) : Prop :=
  Presieve.IsSheafFor F (Presieve.ofArrows U f)

/-- Unfolding lemma for `satisfiesSheafPropertyForFamily`. -/
theorem satisfiesSheafPropertyForFamily_iff
    (F : Schemeᵒᵖ ⥤ Type v) {ι : Type w} {T : Scheme}
    (U : ι → Scheme) (f : ∀ i, U i ⟶ T) :
    satisfiesSheafPropertyForFamily F U f ↔
      Presieve.IsSheafFor F (Presieve.ofArrows U f) :=
  Iff.rfl

/-- Definition 34.9.13 (2): a contravariant set-valued functor on schemes satisfies the sheaf
property for the fpqc topology when it is a sheaf for the Grothendieck topology on `Scheme`
generated by jointly surjective families of flat quasi-compact morphisms. -/
abbrev satisfiesFpqcSheafProperty (F : Schemeᵒᵖ ⥤ Type v) : Prop :=
  Presheaf.IsSheaf Scheme.fpqcTopology F

/-- Unfolding lemma for `satisfiesFpqcSheafProperty`. -/
theorem satisfiesFpqcSheafProperty_iff (F : Schemeᵒᵖ ⥤ Type v) :
    satisfiesFpqcSheafProperty F ↔
      Presheaf.IsSheaf Scheme.fpqcTopology F :=
  Iff.rfl
