import Mathlib
import StacksProject_2024.stacks_project.Chap34.Definition_34_8_4

-- Declarations for this item will be appended below by the statement pipeline.

open CategoryTheory

universe u v

namespace AlgebraicGeometry

-- Semantic recall: `lean_leansearch` returned `Precoverage`, `Pretopology`,
-- and `Precoverage.toGrothendieck`; local Chapter 34 precedent keeps the source-facing chosen big
-- site presentation explicit while using `Pretopology` as the canonical site owner.

/-- Definition 34.8.9: a big ph site is a chosen small site presentation of schemes together with
a chosen seed set `S₀` of schemes and a chosen seed set `Cov₀` of ph coverings among those
schemes. The canonical site owner is a `Pretopology` on the small category, while the ph-specific
content is recorded by requiring both the seed coverings and all chosen covering families to be
represented by ph covering families after forgetting to `Scheme`. -/
structure BigPhSite where
  /-- The chosen small category `\mathit{Sch}_\alpha` of schemes. -/
  carrier : Type u
  /-- The category structure on the chosen small category of schemes. -/
  [str : Category.{v} carrier]
  /-- Pullbacks exist in the chosen small category of schemes, as required to speak about the site
  structure from Definition 7.6.2 via the canonical `Pretopology` owner. -/
  [hasPullbacks : Limits.HasPullbacks carrier]
  /-- The functor exhibiting `\mathit{Sch}_\alpha` as a category of schemes. -/
  toScheme : carrier ⥤ Scheme.{u}
  /-- The chosen seed set `S₀` of schemes inside the small presentation. -/
  seedSchemes : Set carrier
  /-- The chosen seed set `Cov₀` of ph coverings among the schemes in `S₀`, encoded as presieves
  on the small category. -/
  seedCoverings : ∀ X : carrier, Set (Presieve X)
  /-- The chosen site structure on `\mathit{Sch}_\alpha`. -/
  pretopology : Pretopology carrier
  /-- Every chosen seed covering has target in the chosen seed set `S₀`. -/
  seed_target_mem :
    ∀ {X : carrier} {R : Presieve X}, R ∈ seedCoverings X → X ∈ seedSchemes
  /-- Every arrow appearing in a chosen seed covering has source in the chosen seed set `S₀`. -/
  seed_source_mem :
    ∀ {X : carrier} {R : Presieve X}, R ∈ seedCoverings X → {Y : carrier} → (f : Y ⟶ X) →
      R f → Y ∈ seedSchemes
  /-- Each chosen seed covering is represented by a ph covering family after forgetting from the
  small category of schemes to `Scheme`. -/
  seedCovering_isPh :
    ∀ {X : carrier} {R : Presieve X}, R ∈ seedCoverings X →
      ∃ (ι : Type (max u v)) (Y : ι → carrier) (π : ∀ i, Y i ⟶ X),
        R = Presieve.ofArrows Y π ∧
          PhCovering (fun i ↦ toScheme.obj (Y i)) (fun i ↦ toScheme.map (π i))
  /-- The chosen site contains the chosen seed ph coverings. -/
  seedCoverings_le :
    ∀ {X : carrier} {R : Presieve X}, R ∈ seedCoverings X → R ∈ pretopology X
  /-- Every covering in the chosen site is represented by a ph covering family after forgetting
  from the small category of schemes to `Scheme`. -/
  covering_isPh :
    ∀ {X : carrier} {R : Presieve X}, R ∈ pretopology X →
      ∃ (ι : Type (max u v)) (Y : ι → carrier) (π : ∀ i, Y i ⟶ X),
        R = Presieve.ofArrows Y π ∧
          PhCovering (fun i ↦ toScheme.obj (Y i)) (fun i ↦ toScheme.map (π i))

/-- A big ph site coerces to its underlying small category of schemes. -/
instance : CoeSort BigPhSite (Type u) where
  coe Schph := Schph.carrier

namespace BigPhSite

variable (Schph : AlgebraicGeometry.BigPhSite.{u, v})

/-- The underlying category structure of a big ph site. -/
instance instCategoryCarrier : Category.{v} Schph :=
  Schph.str

/-- Pullbacks exist in the underlying category of a big ph site. -/
instance instHasPullbacksCarrier :
    Limits.HasPullbacks Schph :=
  Schph.hasPullbacks

/-- The chosen Grothendieck topology generated by the site presentation of a big ph site. -/
abbrev toGrothendieck : GrothendieckTopology Schph :=
  Schph.pretopology.toGrothendieck

/-- Every chosen seed covering in a big ph site has target in the chosen seed set. -/
theorem seedCovering_target_mem {X : Schph} {R : Presieve X}
    (hR : R ∈ Schph.seedCoverings X) :
    X ∈ Schph.seedSchemes :=
  Schph.seed_target_mem hR

/-- Every arrow in a chosen seed covering of a big ph site has source in the chosen seed set. -/
theorem seedCovering_source_mem {X : Schph} {R : Presieve X}
    (hR : R ∈ Schph.seedCoverings X) {Y : Schph} (f : Y ⟶ X) (hf : R f) :
    Y ∈ Schph.seedSchemes :=
  Schph.seed_source_mem hR f hf

/-- Every chosen seed covering in a big ph site is represented by a ph covering family after
forgetting to `Scheme`. -/
theorem seedCovering_exists_phFamily {X : Schph} {R : Presieve X}
    (hR : R ∈ Schph.seedCoverings X) :
    ∃ (ι : Type (max u v)) (Y : ι → Schph) (π : ∀ i, Y i ⟶ X),
      R = Presieve.ofArrows Y π ∧
        PhCovering (fun i ↦ Schph.toScheme.obj (Y i)) (fun i ↦ Schph.toScheme.map (π i)) :=
  Schph.seedCovering_isPh hR

/-- Every chosen seed covering belongs to the chosen precoverage of a big ph site. -/
theorem mem_pretopology {X : Schph} {R : Presieve X}
    (hR : R ∈ Schph.seedCoverings X) :
    R ∈ Schph.pretopology X :=
  Schph.seedCoverings_le hR

/-- Every covering in the chosen pretopology of a big ph site is represented by a ph covering
family after forgetting to `Scheme`. -/
theorem covering_exists_phFamily {X : Schph} {R : Presieve X}
    (hR : R ∈ Schph.pretopology X) :
    ∃ (ι : Type (max u v)) (Y : ι → Schph) (π : ∀ i, Y i ⟶ X),
      R = Presieve.ofArrows Y π ∧
        PhCovering (fun i ↦ Schph.toScheme.obj (Y i)) (fun i ↦ Schph.toScheme.map (π i)) :=
  Schph.covering_isPh hR

end BigPhSite

end AlgebraicGeometry
