import Mathlib
import Integer.Chapters.Chap03.section_3_2.ch3_sec3_2_theorem_3_6
import Integer.Chapters.Chap03.section_3_6.ch3_sec3_6_proposition_3_15
import Integer.Chapters.Chap03.section_3_15.ch3_sec3_15_definition_3_15_extra_1
import Integer.Chapters.Chap03.section_3_15.ch3_sec3_15_definition_3_15_extra_2

open scoped BigOperators Matrix

-- Declarations for this item will be appended below by the statement pipeline.

/-- Helper for Theorem 3.46: if the projection cone equals the cone generated by `rays`, then
each listed ray is itself a nonnegative multiplier annihilating `B`. -/
lemma ray_mem_projection_multiplier_cone
    {m p q : ℕ}
    (B : Matrix (Fin m) (Fin p) ℝ)
    (rays : Fin q → Fin m → ℝ)
    (h_cone : polyhedron_projection_cone B = finitely_generated_cone rays)
    (t : Fin q) :
    0 ≤ rays t ∧ rays t ᵥ* B = 0 := by
  -- The singleton coefficient vector realizes `rays t` as a cone generator.
  have hray_mem : rays t ∈ finitely_generated_cone rays := by
    refine mem_finitely_generated_cone_iff.mpr ⟨Pi.single t 1, ?_, ?_⟩
    · intro s
      by_cases hs : s = t
      · subst hs
        norm_num
      · simp [hs]
    · ext i
      classical
      rw [Finset.sum_eq_single t]
      · simp
      · intro s hs hst
        simp [hst]
      · simp
  have hmem : rays t ∈ polyhedron_projection_cone B := by
    simpa [h_cone] using hray_mem
  -- Transport the singleton-combination witness across the cone equality hypothesis.
  exact (mem_polyhedron_projection_cone_iff.mp hmem)

/-- Helper for Theorem 3.46: a feasible point `(x,z)` satisfies every multiplier inequality coming
from a nonnegative row multiplier that annihilates `B`. -/
lemma multiplier_evaluation_le_of_feasible
    {m n p : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ)
    (B : Matrix (Fin m) (Fin p) ℝ)
    (b : Fin m → ℝ)
    {x : Fin n → ℝ}
    {u : Fin m → ℝ}
    (hx : ∃ z : Fin p → ℝ, A *ᵥ x + B *ᵥ z ≤ b)
    (hu : 0 ≤ u)
    (huB : u ᵥ* B = 0) :
    u ⬝ᵥ (A *ᵥ x) ≤ u ⬝ᵥ b := by
  rcases hx with ⟨z, hz⟩
  -- Multiply each row inequality by the nonnegative coefficient `u i` and sum over all rows.
  have hsum : u ⬝ᵥ (A *ᵥ x + B *ᵥ z) ≤ u ⬝ᵥ b := by
    simpa [dotProduct] using
      (Finset.sum_le_sum fun i _ ↦ mul_le_mul_of_nonneg_left (hz i) (hu i))
  have hzero : u ⬝ᵥ (B *ᵥ z) = 0 := by
    -- The `B`-part disappears because the multiplier lies in the projection cone.
    rw [Matrix.dotProduct_mulVec, huB]
    simp
  calc
    u ⬝ᵥ (A *ᵥ x) = u ⬝ᵥ (A *ᵥ x) + u ⬝ᵥ (B *ᵥ z) := by
      rw [hzero, add_zero]
    _ = u ⬝ᵥ (A *ᵥ x + B *ᵥ z) := by
      rw [dotProduct_add]
    _ ≤ u ⬝ᵥ b := hsum

/-- Helper for Theorem 3.46: feasibility of the projection system is equivalent to feasibility of
the shifted `z`-system `B *ᵥ z ≤ b - A *ᵥ x`. -/
lemma projection_feasible_iff_shifted_system_feasible
    {m n p : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ)
    (B : Matrix (Fin m) (Fin p) ℝ)
    (b : Fin m → ℝ)
    (x : Fin n → ℝ) :
    (∃ z : Fin p → ℝ, A *ᵥ x + B *ᵥ z ≤ b) ↔
      (∃ z : Fin p → ℝ, B *ᵥ z ≤ b - A *ᵥ x) := by
  constructor
  · intro hx
    rcases hx with ⟨z, hz⟩
    -- Move the fixed term `A *ᵥ x` to the right-hand side row by row.
    refine ⟨z, ?_⟩
    intro i
    have hzi : (B *ᵥ z) i + (A *ᵥ x) i ≤ b i := by
      simpa [add_comm, add_left_comm, add_assoc] using hz i
    exact (le_sub_iff_add_le).2 hzi
  · intro hx
    rcases hx with ⟨z, hz⟩
    -- Reverse the same rowwise rearrangement to rebuild the original projection system.
    refine ⟨z, ?_⟩
    intro i
    have hzi : (B *ᵥ z) i + (A *ᵥ x) i ≤ b i := (le_sub_iff_add_le).1 (hz i)
    simpa [add_comm, add_left_comm, add_assoc] using hzi

/-- Helper for Theorem 3.46: any element of the cone generated by `rays` preserves the raywise
valid inequalities `rays t ⬝ᵥ (A *ᵥ x) ≤ rays t ⬝ᵥ b`. -/
lemma finitely_generated_cone_evaluation_le_of_raywise_le
    {m n q : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ)
    (b : Fin m → ℝ)
    (rays : Fin q → Fin m → ℝ)
    {x : Fin n → ℝ}
    {u : Fin m → ℝ}
    (h_raywise : ∀ t : Fin q, rays t ⬝ᵥ (A *ᵥ x) ≤ rays t ⬝ᵥ b)
    (hu : u ∈ finitely_generated_cone rays) :
    u ⬝ᵥ (A *ᵥ x) ≤ u ⬝ᵥ b := by
  rcases (mem_finitely_generated_cone_iff.mp hu) with ⟨μ, hμ_nonneg, rfl⟩
  -- Expand the multiplier as a conic combination of rays and sum the raywise inequalities.
  calc
    (∑ t : Fin q, μ t • rays t) ⬝ᵥ (A *ᵥ x)
        = ∑ t : Fin q, (μ t • rays t) ⬝ᵥ (A *ᵥ x) := by
          simpa using
            (sum_dotProduct Finset.univ (fun t : Fin q ↦ μ t • rays t) (A *ᵥ x))
    _ = ∑ t : Fin q, μ t * (rays t ⬝ᵥ (A *ᵥ x)) := by
          simp [smul_eq_mul]
    _ ≤ ∑ t : Fin q, μ t * (rays t ⬝ᵥ b) := by
          refine Finset.sum_le_sum ?_
          intro t ht
          exact mul_le_mul_of_nonneg_left (h_raywise t) (hμ_nonneg t)
    _ = ∑ t : Fin q, (μ t • rays t) ⬝ᵥ b := by
          simp [smul_eq_mul]
    _ = (∑ t : Fin q, μ t • rays t) ⬝ᵥ b := by
          symm
          simpa using (sum_dotProduct Finset.univ (fun t : Fin q ↦ μ t • rays t) b)

/-- Helper for Theorem 3.46: the shifted system `B *ᵥ z ≤ d` is feasible exactly when every
nonnegative left-kernel multiplier of `B` evaluates nonnegatively on `d`. -/
lemma shifted_system_feasible_iff_nonnegative_multiplier_nonnegative
    {m p : ℕ}
    (B : Matrix (Fin m) (Fin p) ℝ)
    (d : Fin m → ℝ) :
    (∃ z : Fin p → ℝ, B *ᵥ z ≤ d) ↔
      ∀ u : Fin m → ℝ, 0 ≤ u → u ᵥ* B = 0 → 0 ≤ u ⬝ᵥ d := by
  let h_farkas :=
    mixed_linear_system_feasible_iff_nonnegative_multiplier_evaluation
      (0 : Matrix (Fin m) (Fin 0) ℝ)
      B
      (0 : Matrix (Fin 0) (Fin 0) ℝ)
      (0 : Matrix (Fin 0) (Fin p) ℝ)
      d
      (0 : Fin 0 → ℝ)
  have h_left :
      (∃ x : Fin 0 → ℝ, ∃ z : Fin p → ℝ,
        0 ≤ x ∧
          (0 : Matrix (Fin m) (Fin 0) ℝ) *ᵥ x + B *ᵥ z ≤ d ∧
          (0 : Matrix (Fin 0) (Fin 0) ℝ) *ᵥ x + (0 : Matrix (Fin 0) (Fin p) ℝ) *ᵥ z = 0) ↔
        (∃ z : Fin p → ℝ, B *ᵥ z ≤ d) := by
    constructor
    · rintro ⟨x, z, _, hxz, _⟩
      exact ⟨z, by simpa using hxz⟩
    · rintro ⟨z, hz⟩
      exact ⟨0, z, by simp, by simpa using hz, by simp⟩
  have h_right :
      (∀ u : Fin m → ℝ, ∀ v : Fin 0 → ℝ,
        0 ≤ u →
          0 ≤ u ᵥ* (0 : Matrix (Fin m) (Fin 0) ℝ) + v ᵥ* (0 : Matrix (Fin 0) (Fin 0) ℝ) →
            u ᵥ* B + v ᵥ* (0 : Matrix (Fin 0) (Fin p) ℝ) = 0 →
              0 ≤ u ⬝ᵥ d + v ⬝ᵥ (0 : Fin 0 → ℝ)) ↔
        ∀ u : Fin m → ℝ, 0 ≤ u → u ᵥ* B = 0 → 0 ≤ u ⬝ᵥ d := by
    constructor
    · intro h u hu huB
      have huB' : u ᵥ* B + (0 : Fin 0 → ℝ) ᵥ* (0 : Matrix (Fin 0) (Fin p) ℝ) = 0 := by
        simpa using huB
      simpa using h u 0 hu (by simp) huB'
    · intro h u v hu _ huB
      have hv : v = 0 := by
        ext i
        exact Fin.elim0 i
      subst hv
      have huB' : u ᵥ* B = 0 := by
        simpa using huB
      simpa using h u hu huB'
  exact h_left.symm.trans (h_farkas.trans h_right)

/-- Helper for Theorem 3.46: infeasibility of the shifted system `B *ᵥ z ≤ d` yields a
nonnegative multiplier annihilating `B` and evaluating negatively on `d`. -/
theorem shifted_system_infeasible_has_multiplier
    {m p : ℕ}
    (B : Matrix (Fin m) (Fin p) ℝ)
    (d : Fin m → ℝ) :
    (¬ ∃ z : Fin p → ℝ, B *ᵥ z ≤ d) →
      ∃ u : Fin m → ℝ, 0 ≤ u ∧ u ᵥ* B = 0 ∧ u ⬝ᵥ d < 0 := by
  intro h_infeasible
  classical
  -- Negate the desired certificate and specialize the earlier mixed-system alternative.
  by_contra h_no_multiplier
  have h_nonnegative_eval :
      ∀ u : Fin m → ℝ, 0 ≤ u → u ᵥ* B = 0 → 0 ≤ u ⬝ᵥ d := by
    intro u hu_nonneg hu_annihilates
    -- Any negative evaluation would itself be the missing Farkas witness.
    by_contra hu_negative
    exact h_no_multiplier ⟨u, hu_nonneg, hu_annihilates, lt_of_not_ge hu_negative⟩
  have h_feasible : ∃ z : Fin p → ℝ, B *ᵥ z ≤ d :=
    (shifted_system_feasible_iff_nonnegative_multiplier_nonnegative B d).2 h_nonnegative_eval
  exact h_infeasible h_feasible

/-- Bridge/view for Theorem 3.46: if the projection cone is generated by the listed multipliers,
then the `x`-projection is exactly the set cut out by their inequalities. -/
theorem polyhedron_x_projection_eq_generator_inequalities
    {m n p q : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ)
    (B : Matrix (Fin m) (Fin p) ℝ)
    (b : Fin m → ℝ)
    (rays : Fin q → Fin m → ℝ)
    (h_cone : polyhedron_projection_cone B = finitely_generated_cone rays) :
    Prod.fst '' {xz : (Fin n → ℝ) × (Fin p → ℝ) | A *ᵥ xz.1 + B *ᵥ xz.2 ≤ b} =
      {x : Fin n → ℝ | ∀ t : Fin q, rays t ⬝ᵥ (A *ᵥ x) ≤ rays t ⬝ᵥ b} := by
  ext x
  rw [mem_image_fst_iff]
  constructor
  · intro hx t
    obtain ⟨hray_nonneg, hray_annihilates⟩ :=
      ray_mem_projection_multiplier_cone B rays h_cone t
    exact multiplier_evaluation_le_of_feasible A B b hx hray_nonneg hray_annihilates
  · intro hx
    by_contra hx_not
    have hshift_infeasible : ¬ ∃ z : Fin p → ℝ, B *ᵥ z ≤ b - A *ᵥ x := by
      simpa [projection_feasible_iff_shifted_system_feasible A B b x] using hx_not
    obtain ⟨u, hu_nonneg, hu_annihilates, hu_negative⟩ :=
      shifted_system_infeasible_has_multiplier B (b - A *ᵥ x) hshift_infeasible
    have hu_comb : u ∈ finitely_generated_cone rays := by
      have hmem : u ∈ polyhedron_projection_cone B := by
        exact (mem_polyhedron_projection_cone_iff.mpr ⟨hu_nonneg, hu_annihilates⟩)
      rwa [h_cone] at hmem
    have hu_le : u ⬝ᵥ (A *ᵥ x) ≤ u ⬝ᵥ b :=
      finitely_generated_cone_evaluation_le_of_raywise_le A b rays hx hu_comb
    have hu_negative' : u ⬝ᵥ b - u ⬝ᵥ (A *ᵥ x) < 0 := by
      simpa [dotProduct_sub] using hu_negative
    linarith

/-- Theorem 3.46. Let
`P = {(x, z) | A *ᵥ x + B *ᵥ z ≤ b}` and
`C_P = {u | 0 ≤ u ∧ u ᵥ* B = 0}`.
If `C_P` is pointed and `rays` is a representative family of its extreme rays up to `SameRay ℝ`,
then the projection of `P` to the `x`-coordinates is exactly the set of `x` satisfying the
inequalities `rays t ⬝ᵥ (A *ᵥ x) ≤ rays t ⬝ᵥ b` for all `t`. -/
theorem polyhedron_x_projection_eq_extreme_ray_inequalities
    {m n p q : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ)
    (B : Matrix (Fin m) (Fin p) ℝ)
    (b : Fin m → ℝ)
    (rays : Fin q → Fin m → ℝ)
    (h_pointed : is_pointed (polyhedron_projection_cone B))
    (h_rays_extreme :
      ∀ t : Fin q, IsExtremeRayOfCone (polyhedron_projection_cone B) (rays t))
    (h_extreme_rep :
      ∀ r : Fin m → ℝ, IsExtremeRayOfCone (polyhedron_projection_cone B) r →
        ∃ t : Fin q, SameRay ℝ r (rays t)) :
    Prod.fst '' {xz : (Fin n → ℝ) × (Fin p → ℝ) | A *ᵥ xz.1 + B *ᵥ xz.2 ≤ b} =
      {x : Fin n → ℝ | ∀ t : Fin q, rays t ⬝ᵥ (A *ᵥ x) ≤ rays t ⬝ᵥ b} := by
  have h_cone :=
    polyhedron_projection_cone_eq_cone_of_extreme_rays
      B rays h_pointed h_rays_extreme h_extreme_rep
  exact polyhedron_x_projection_eq_generator_inequalities A B b rays h_cone
