import LinearRepresentations_Serre_1977.Chap11.Proposition_11_11_4_1.RegularOwnerIncidence
#check hasAssociatedPElementarySubgroupInClass_of_le
#check associated_p_elementary_subgroup_nonempty_inter_carrier
#check nonempty_inter_carrier_of_hasAssociatedPElementarySubgroupInClass
