module

import Topology_Munkres_2000.Book.Definition_19_1.BoxTopology

/- Definition 19.7: For an indexed family of topological spaces `X`, the topology
generated by the basis `Pi.boxBasis X` of all full coordinate boxes `∏ i, U i`,
with every `U i` open in `X i`, is the box topology `Pi.boxTopologicalSpace X`. -/
#check Pi.boxTopologicalSpace
