module

public import Topology_Munkres_2000.Book.Theorem_53_1.CircleMap
public import Topology_Munkres_2000.Book.Definition_54_4
public import Topology_Munkres_2000.Book.Exercise_54_6.Power
public import Topology_Munkres_2000.Book.Theorem_79_4
public import Mathlib.Analysis.Convex.Contractible
public import Mathlib.Topology.Algebra.Module.LocallyConvex
public import Mathlib.Topology.Bases
public import Mathlib.Topology.Connected.LocallyPathConnected
public import Mathlib.Topology.Homeomorph.Lemmas

public section

universe u v

open TopologicalSpace Topology

/-- Helper for Example 79.1: the domain of a local homeomorphism into a locally
path-connected space is locally path-connected. -/
private lemma IsLocalHomeomorph.domainLocallyPathConnectedSpace
    {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]
    [LocallyPathConnectedSpace Y] {f : X → Y} (hf : IsLocalHomeomorph f) :
    LocallyPathConnectedSpace X := by
  -- Refine the local-section basis by path-connected open neighborhoods downstairs.
  let ℘ : Set (Set X) := {U | IsOpen U ∧ IsPathConnected U}
  have h℘ : IsTopologicalBasis ℘ := by
    refine isTopologicalBasis_of_isOpen_of_nhds (fun U hU ↦ hU.1) ?_
    intro x U hxU hU
    obtain ⟨S, ⟨V, hV, s, hs, hsS⟩, hxS, hSU⟩ :=
      hf.isTopologicalBasis.exists_subset_of_mem_open hxU hU
    rw [← hsS] at hxS
    obtain ⟨x', rfl⟩ := hxS
    have hsOpen : IsOpenEmbedding s :=
      hf.isOpenEmbedding_of_comp (hs ▸ hV.isOpenEmbedding_subtypeVal) s.continuous
    letI : LocallyPathConnectedSpace V := hV.locallyPathConnectedSpace
    obtain ⟨W, hW⟩ := (isOpen_isPathConnected_basis x').ex_mem
    refine ⟨s '' W, ⟨hsOpen.isOpenMap W hW.1, hW.2.2.image s.continuous⟩,
      ⟨x', hW.2.1, rfl⟩, ?_⟩
    exact (Set.image_subset_range s W).trans (hsS.symm ▸ hSU)
  -- This basis supplies path-connected neighborhoods at every point of the domain.
  refine LocallyPathConnectedSpace.of_bases (fun x ↦ h℘.nhds_hasBasis) ?_
  intro x U hU
  exact hU.1.2

/-- Helper for Example 79.1: every subgroup of `Multiplicative ℤ` is generated by
the image of a nonnegative integer. -/
private lemma Subgroup.exists_eq_zpowers_ofAdd_nat (H : Subgroup (Multiplicative ℤ)) :
    ∃ n : ℕ, H = Subgroup.zpowers (Multiplicative.ofAdd (n : ℤ)) := by
  -- The element `ofAdd 1` generates all of `Multiplicative ℤ`.
  have hGenerator : Subgroup.zpowers (Multiplicative.ofAdd (1 : ℤ)) = ⊤ := by
    rw [eq_top_iff]
    intro x _hx
    refine ⟨x.toAdd, ?_⟩
    apply Multiplicative.ext
    simp only [toAdd_zpow, toAdd_ofAdd, zsmul_eq_mul, Int.cast_id, mul_one]
  -- Cyclic-subgroup classification then chooses a nonnegative power of that generator.
  have hContained : H ≤ Subgroup.zpowers (Multiplicative.ofAdd (1 : ℤ)) := by
    rw [hGenerator]
    exact le_top
  obtain ⟨n, hn⟩ :=
    (Subgroup.le_zpowers_iff (Multiplicative.ofAdd (1 : ℤ)) H).mp hContained
  refine ⟨n, hn.trans ?_⟩
  congr 1
  apply Multiplicative.ext
  simp only [toAdd_pow, toAdd_ofAdd, nsmul_eq_mul, mul_one]

/-- Helper for Example 79.1: the universal real covering of the circle has trivial
induced fundamental-group range. -/
private lemma Circle.turnExp_fundamentalGroupMapRange_eq_bot :
    Circle.isCoveringMap_turnExp.fundamentalGroupMapRange Circle.turnExp_zero = ⊥ := by
  -- The domain fundamental group is a subsingleton because `ℝ` is contractible.
  rw [IsCoveringMap.fundamentalGroupMapRange, MonoidHom.range_eq_bot_iff]
  apply MonoidHom.ext
  intro γ
  have hγ : γ = 1 := Subsingleton.elim _ _
  rw [hγ]
  exact map_one _

namespace CircleMap

/-- Helper for Example 79.1: a nonzero natural-degree integer power map of the circle
is a covering map. -/
private lemma isCoveringMap_zpower_nat (m : ℕ) (hm : m ≠ 0) :
    IsCoveringMap (zpower (m : ℤ)) := by
  -- Compare the bundled integer power with mathlib's natural power covering.
  letI : NeZero m := ⟨hm⟩
  have hfun : (zpower (m : ℤ) : Circle → Circle) = fun z ↦ z ^ m := by
    funext z
    rw [zpower_apply, zpow_natCast]
  rw [hfun]
  exact (Circle.isQuotientCoveringMap_npow m).isCoveringMap

/-- Helper for Example 79.1: in integer coordinates, the subgroup induced by a circle
power covering is generated by its degree. -/
private lemma zpower_fundamentalGroupMapRange_map (k : ℤ)
    (hk : IsCoveringMap (zpower k)) :
    (hk.fundamentalGroupMapRange (zpower_one k)).map
        Circle.fundamentalGroupEquivInt.toMonoidHom =
      Subgroup.zpowers (Multiplicative.ofAdd k) := by
  -- First expose the induced homomorphism and transport its range through integer coordinates.
  rw [IsCoveringMap.fundamentalGroupMapRange, MonoidHom.map_range]
  calc
    (Circle.fundamentalGroupEquivInt.toMonoidHom.comp
        (FundamentalGroup.mapOfEq (zpower k) (zpower_one k))).range =
        ((zpowGroupHom k).comp
          Circle.fundamentalGroupEquivInt.toMonoidHom).range :=
      congrArg MonoidHom.range
        (induced_zpower k Circle.fundamentalGroupEquivInt)
    _ = Circle.fundamentalGroupEquivInt.toMonoidHom.range.map (zpowGroupHom k) :=
      MonoidHom.range_comp _ _
    _ = (⊤ : Subgroup (Multiplicative ℤ)).map (zpowGroupHom k) := by
      exact congrArg (fun S : Subgroup (Multiplicative ℤ) ↦ S.map (zpowGroupHom k))
        (MulEquiv.range_eq_top Circle.fundamentalGroupEquivInt)
    _ = (zpowGroupHom k : Multiplicative ℤ →* Multiplicative ℤ).range :=
      (MonoidHom.range_eq_map _).symm
    _ = Subgroup.zpowers (Multiplicative.ofAdd k) := by
      ext x
      constructor
      · rintro ⟨y, rfl⟩
        refine ⟨y.toAdd, ?_⟩
        apply Multiplicative.ext
        simp only [toAdd_zpow, toAdd_ofAdd]
        exact mul_comm _ _
      · rintro ⟨j, rfl⟩
        refine ⟨Multiplicative.ofAdd j, ?_⟩
        apply Multiplicative.ext
        simp only [toAdd_zpow, toAdd_ofAdd]
        exact mul_comm _ _

end CircleMap

/-- Example 79.1. Every path-connected covering of the circle is equivalent over the circle
either to the standard real covering or to a positive-degree power covering. -/
theorem circleCovering_equivalent_turnExp_or_zpower {E : Type u}
    [TopologicalSpace E] [PathConnectedSpace E]
    (p : E → Circle) (hp : IsCoveringMap p) (h_surjective : Function.Surjective p) :
    CoveringMap.Equivalent p Circle.turnExp ∨
      ∃ n : ℕ, 0 < n ∧ CoveringMap.Equivalent p (CircleMap.zpower (n : ℤ)) := by
  -- Choose a point above the standard basepoint and install the local hypotheses needed
  -- by the connected-covering classification theorem.
  obtain ⟨e₀, he₀⟩ := h_surjective (1 : Circle)
  letI : LocallyPathConnectedSpace Circle :=
    Circle.isAddQuotientCoveringMap_exp.toIsQuotientMap.locallyPathConnectedSpace
  letI : LocallyPathConnectedSpace E :=
    hp.isLocalHomeomorph.domainLocallyPathConnectedSpace
  -- Transport the induced subgroup to integers and classify it by one natural degree.
  obtain ⟨n, hn⟩ := Subgroup.exists_eq_zpowers_ofAdd_nat
    ((hp.fundamentalGroupMapRange he₀).map
      Circle.fundamentalGroupEquivInt.toMonoidHom)
  by_cases hnZero : n = 0
  · left
    apply (hp.equivalent_iff_fundamentalGroupMapRange_isConj
      Circle.isCoveringMap_turnExp e₀ 0 1 he₀ Circle.turnExp_zero).mpr
    -- Degree zero means that both induced subgroups are trivial.
    have hRange : hp.fundamentalGroupMapRange he₀ =
        Circle.isCoveringMap_turnExp.fundamentalGroupMapRange Circle.turnExp_zero := by
      apply (Subgroup.map_injective
        (f := Circle.fundamentalGroupEquivInt.toMonoidHom)
        Circle.fundamentalGroupEquivInt.injective)
      rw [hn, hnZero, Circle.turnExp_fundamentalGroupMapRange_eq_bot]
      simp only [Nat.cast_zero, ofAdd_zero,
        Subgroup.zpowers_one_eq_bot, Subgroup.map_bot]
    rw [hRange]
  · right
    have hnPos : 0 < n := Nat.pos_of_ne_zero hnZero
    have hPower : IsCoveringMap (CircleMap.zpower (n : ℤ)) :=
      CircleMap.isCoveringMap_zpower_nat n hnZero
    refine ⟨n, hnPos, ?_⟩
    apply (hp.equivalent_iff_fundamentalGroupMapRange_isConj
      hPower e₀ 1 1 he₀ (CircleMap.zpower_one (n : ℤ))).mpr
    -- Equality after applying the integer coordinate equivalence cancels back upstairs.
    have hRange : hp.fundamentalGroupMapRange he₀ =
        hPower.fundamentalGroupMapRange (CircleMap.zpower_one (n : ℤ)) := by
      apply (Subgroup.map_injective
        (f := Circle.fundamentalGroupEquivInt.toMonoidHom)
        Circle.fundamentalGroupEquivInt.injective)
      rw [hn, CircleMap.zpower_fundamentalGroupMapRange_map]
    rw [hRange]
