module

public import Topology_Munkres_2000.Book.Remark_74_2.Vertices
public import Topology_Munkres_2000.Book.Theorem_74_4.Presentation
public import Topology_Munkres_2000.Book.Theorem_75_5.Classification
public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
public import Mathlib.AlgebraicTopology.SingularHomology.Basic
public import Mathlib.Algebra.Category.Grp.Abelian
public import Mathlib.Data.ZMod.Basic

public section

open CategoryTheory Set

namespace OctagonSurface

/-- The edge pasting with signed boundary word `a b c d a d⁻¹ c b⁻¹`. -/
noncomputable def pasting (poly : CyclicPolygon 8) : poly.EdgePasting (Fin 4) :=
  .ofSigns poly ![0, 1, 2, 3, 0, 3, 2, 1] ![true, true, true, true, true, false, true, false]

/-- The quotient space obtained from the octagonal edge pasting. -/
abbrev Space (poly : CyclicPolygon 8) := (pasting poly).Realization

/-- The quotient map from the octagonal region to its pasted realization. -/
noncomputable def quotientMap (poly : CyclicPolygon 8) : poly.region → Space poly :=
  (pasting poly).quotientMap

/-- The boundary of the polygon regarded as a subset of its filled region. -/
def boundarySource (poly : CyclicPolygon 8) : Set poly.region :=
  {x | (x : EuclideanSpace ℝ (Fin 2)) ∈ poly.boundary}

/-- The image `π(Bd P)` of the polygon boundary in the pasted quotient. -/
def boundaryImage (poly : CyclicPolygon 8) : Set (Space poly) :=
  quotientMap poly '' boundarySource poly


end OctagonSurface

namespace FourEdgeGraph

/-- The pair of endpoint vertices of each of the four directed graph edges. -/
def incidence (i : Fin 4) : Fin 2 × Fin 2 :=
  ![(0, 0), (0, 1), (1, 1), (1, 0)] i

/-- The selected endpoint of one of the four interval edges. -/
def endpoint (i : Fin 4) (terminal : Bool) : Fin 4 × unitInterval :=
  (i, if terminal then 1 else 0)

/-- Two interval points are directly related when they are endpoints incident to the same
graph vertex. -/
def EndpointRelated (x y : Fin 4 × unitInterval) : Prop :=
  ∃ i j : Fin 4, ∃ terminal source : Bool,
    x = endpoint i terminal ∧ y = endpoint j source ∧
      (if terminal then (incidence i).2 else (incidence i).1) =
        if source then (incidence j).2 else (incidence j).1

/-- The equivalence relation generated by the four-edge graph endpoint identifications. -/
def Identified : Setoid (Fin 4 × unitInterval) :=
  Relation.EqvGen.setoid EndpointRelated

/-- The topological graph with two vertices, one loop at each vertex, and two connecting edges. -/
abbrev Space := Quotient Identified


end FourEdgeGraph

/-- Exercise 75.4 (1). The octagonal quotient map does not identify all polygon vertices. -/
theorem octagonVertices_not_all_identified (poly : CyclicPolygon 8) :
    ¬ (OctagonSurface.pasting poly).VerticesIdentified := sorry

/-- Exercise 75.4 (2). The image of the octagon boundary is the graph with two vertices,
one loop at each vertex, and two edges joining the vertices. -/
theorem octagonBoundary_homeomorph_fourEdgeGraph (poly : CyclicPolygon 8) :
    Nonempty (OctagonSurface.boundaryImage poly ≃ₜ FourEdgeGraph.Space) := sorry

/-- Exercise 75.4 (3). The fundamental group of the boundary image is free of rank three. -/
theorem octagonBoundary_fundamentalGroup (poly : CyclicPolygon 8)
    (a₀ : OctagonSurface.boundaryImage poly) :
    Nonempty
      (FundamentalGroup (OctagonSurface.boundaryImage poly) a₀ ≃*
        FreeGroup (Fin 3)) := sorry

/-- Exercise 75.4 (4). The octagonal quotient has the standard genus-three
nonorientable-surface fundamental-group presentation. -/
theorem octagonSurface_fundamentalGroup (poly : CyclicPolygon 8)
    (x₀ : OctagonSurface.Space poly) :
    Nonempty
      (FundamentalGroup (OctagonSurface.Space poly) x₀ ≃*
        NonorientableSurfaceGroup.Presentation 3) := sorry

/-- Exercise 75.4 (5). The first integral homology group of the octagonal quotient is
`ℤ × ℤ × ZMod 2`. -/
theorem octagonSurface_firstHomology (poly : CyclicPolygon 8) :
    Nonempty
      (((AlgebraicTopology.singularHomologyFunctor AddCommGrpCat 1).obj
          (AddCommGrpCat.of ℤ)).obj (TopCat.of (OctagonSurface.Space poly)) ≅
        AddCommGrpCat.of ((ℤ × ℤ) × ZMod 2)) := sorry

/-- Exercise 75.4 (6). If the octagonal quotient belongs to the classified list of closed
surfaces, then it is the three-fold projective plane. -/
theorem octagonSurface_homeomorph_threeFoldProjectivePlane (poly : CyclicPolygon 8)
    (h_classified : ClassifiedClosedSurface (OctagonSurface.Space poly)) :
    Nonempty
      (OctagonSurface.Space poly ≃ₜ
        NonorientableSurfacePresentation.mFoldProjectivePlane 3
          (Nat.one_lt_succ_succ 1)) := sorry

end
