import Mathlib
import ConvexAnalysis_Rockafellar_1970.Chap04.Definition_17_2_5

-- Declarations for this item will be appended below by the statement pipeline.

section

universe u v

open scoped BigOperators Rockafellar

variable {E : Type u} {R : Type v}
    [Semiring R] [PartialOrder R] [IsOrderedRing R]
    [AddCommMonoid E] [Module R E]

local notation "EStar" => E × R

/-!
Source/core/bridge triage:

- `source-facing`: this item exposes membership in the cone generated by
  `SStar ∪ {((0 : E), 1)}` via finite nonnegative combinations over `SStar`.
- `core/canonical`: the chapter owner abstraction is `cone[R] (adjoin_vertical_unit SStar)`,
  introduced upstream through the canonical generated-cone owner `cone[R] = PointedCone.hull`.
- `bridge/view`: `PointedCone.mem_hull_set` supplies the canonical finite conic-combination witness
  in `adjoin_vertical_unit SStar`; splitting the distinguished generator `((0 : E), 1)` produces a
  primitive nonnegative vertical slack coefficient.

Domain-style sampling used here:
- `cone[R]` from `Chap01.Definition_2_6_10`;
- `adjoin_vertical_unit` and `vertical_unit` from Definition 17.2.5;
- `PointedCone.hull`;
- `PointedCone.mem_hull_set`;
- finite subset sums via `Finset.attach`;
- coordinate projections on the product module `E × R`.

Primitive data vs derived API:
- primitive owner object: `cone[R] (adjoin_vertical_unit SStar)`;
- primitive source-facing API: the finite-support certificate on a finite subset of `SStar`
  together with an explicit nonnegative vertical slack coefficient;
- derived API: the inequality formulation obtained by eliminating this slack through subtraction.

Ambient minimization:
- the statement uses only the additive/module structure needed by
  `cone[R] (adjoin_vertical_unit SStar)`, so the owner file stays at the generic module level
  instead of specializing prematurely to `ℝ^n`.

Layer target: `bridge/view`; the public statement keeps the source-facing finite certificate but
derives it from the existing owner `cone[R] (adjoin_vertical_unit SStar)`.
-/

/-- Primitive internal slack certificate for generated-cone membership in Definition 17.2.5:
finite support in `SStar`, nonnegative coefficients, exact first-coordinate reconstruction, and an
explicit nonnegative vertical slack coefficient on the second coordinate. -/
private structure GeneratedConeSlackCert
    (SStar : Set EStar) (pStar : EStar) where
  support : Finset EStar
  support_subset : (support : Set EStar) ⊆ SStar
  weights : {y // y ∈ support} → R
  weights_nonneg (y : {z // z ∈ support}) : 0 ≤ weights y
  fst_eq : pStar.1 = support.attach.sum (fun y ↦ weights y • (y : EStar).1)
  slack : R
  slack_nonneg : 0 ≤ slack
  snd_eq : support.attach.sum (fun y ↦ weights y * (y : EStar).2) + slack = pStar.2

/-- Semiring-level internal bridge for Lemma 17.2.9: a point belongs to the cone generated by
`SStar ∪ {((0 : E), 1)}` iff it is a finite nonnegative conic combination of points of `SStar`
plus an explicit nonnegative vertical slack coefficient. -/
-- Proof sketch: apply `PointedCone.mem_hull_set` to the generating set
-- `SStar ∪ {((0 : E), 1)}`. Separate the coefficient of the distinguished singleton generator
-- `((0 : E), 1)` from the remaining finitely many generators in `SStar`.
private theorem mem_generated_cone_iff_exists_conicCombination_with_slack
    {SStar : Set EStar} {pStar : EStar} :
    pStar ∈ (K⋆[R] SStar) ↔
      Nonempty (GeneratedConeSlackCert SStar pStar) := by
  constructor
  · intro hmem
    classical
    rcases (PointedCone.mem_hull_set.mp (show
      pStar ∈ PointedCone.hull R (adjoin_vertical_unit SStar) by
        simpa using hmem)) with ⟨c, hcS, hc0, hsum⟩
    let s : Finset EStar := c.support.filter fun y ↦ y ∈ SStar
    let weights : {y // y ∈ s} → R := fun y ↦ c y
    have h_eq_vertical {y : EStar} (hy : y ∈ c.support) (hyS : y ∉ SStar) :
        y = vertical_unit := by
      rcases hcS hy with hy_eq | hyS_mem
      · exact hy_eq
      · exact (hyS hyS_mem).elim
    have hs : (s : Set EStar) ⊆ SStar := by
      intro y hy
      exact (Finset.mem_filter.mp hy).2
    have hweights : ∀ y, 0 ≤ weights y := by
      intro y
      exact hc0 y
    have hxfull : pStar.1 = ∑ y ∈ c.support, c y • y.1 := by
      calc
        pStar.1 = (∑ y ∈ c.support, c y • y).1 := by
          simpa [Finsupp.sum] using (congrArg Prod.fst hsum).symm
        _ = ∑ y ∈ c.support, c y • y.1 := by
          simpa using
            (Prod.fst_sum :
              (∑ y ∈ c.support, c y • y).1 = ∑ y ∈ c.support, (c y • y).1)
    have hfirst_omitted : ∑ y ∈ c.support.filter (fun y ↦ y ∉ SStar), c y • y.1 = 0 := by
      refine Finset.sum_eq_zero fun y hy ↦ ?_
      have hy_support : y ∈ c.support := (Finset.mem_filter.mp hy).1
      have hyS : y ∉ SStar := (Finset.mem_filter.mp hy).2
      rw [h_eq_vertical hy_support hyS]
      simp [vertical_unit]
    have hx : pStar.1 = s.attach.sum (fun y ↦ weights y • (y : EStar).1) := by
      calc
        pStar.1 = ∑ y ∈ c.support, c y • y.1 := hxfull
        _ = (∑ y ∈ s, c y • y.1) + ∑ y ∈ c.support.filter (fun y ↦ y ∉ SStar), c y • y.1 := by
          symm
          simpa [s] using
            (Finset.sum_filter_add_sum_filter_not c.support
              (fun y ↦ y ∈ SStar) (fun y ↦ c y • y.1))
        _ = ∑ y ∈ s, c y • y.1 := by rw [hfirst_omitted, add_zero]
        _ = s.attach.sum (fun y ↦ weights y • (y : EStar).1) := by
          simpa [weights] using (Finset.sum_attach s (fun y ↦ c y • y.1)).symm
    have hmu_full : ∑ y ∈ c.support, c y * y.2 = pStar.2 := by
      calc
        ∑ y ∈ c.support, c y * y.2 = (∑ y ∈ c.support, c y • y).2 := by
          simpa [smul_eq_mul] using
            (Prod.snd_sum :
              (∑ y ∈ c.support, c y • y).2 = ∑ y ∈ c.support, (c y • y).2).symm
        _ = pStar.2 := by
          simpa [Finsupp.sum] using congrArg Prod.snd hsum
    let slack : R := ∑ y ∈ c.support.filter (fun y ↦ y ∉ SStar), c y * y.2
    have hslack_nonneg : 0 ≤ slack := by
      dsimp [slack]
      refine Finset.sum_nonneg fun y hy ↦ ?_
      have hy_support : y ∈ c.support := (Finset.mem_filter.mp hy).1
      have hyS : y ∉ SStar := (Finset.mem_filter.mp hy).2
      rw [h_eq_vertical hy_support hyS]
      simpa [vertical_unit] using hc0 vertical_unit
    have hmu_eq :
        s.attach.sum (fun y ↦ weights y * (y : EStar).2) + slack = pStar.2 := by
      have hsecond_sum :
          s.attach.sum (fun y ↦ weights y * (y : EStar).2) = ∑ y ∈ s, c y * y.2 := by
        simpa [weights] using (Finset.sum_attach s (fun y ↦ c y * y.2))
      calc
        s.attach.sum (fun y ↦ weights y * (y : EStar).2) + slack =
            (∑ y ∈ s, c y * y.2) + ∑ y ∈ c.support.filter (fun y ↦ y ∉ SStar), c y * y.2 := by
          simpa [slack] using congrArg (fun t : R ↦ t + slack) hsecond_sum
        _ = ∑ y ∈ c.support, c y * y.2 := by
          simpa [s] using
            (Finset.sum_filter_add_sum_filter_not c.support
              (fun y ↦ y ∈ SStar) (fun y ↦ c y * y.2))
        _ = pStar.2 := hmu_full
    exact ⟨{
      support := s
      support_subset := hs
      weights := weights
      weights_nonneg := hweights
      fst_eq := hx
      slack := slack
      slack_nonneg := hslack_nonneg
      snd_eq := hmu_eq
    }⟩
  · rintro ⟨s, hs, weights, hweights, hx, slack, hslack_nonneg, hmu_eq⟩
    have hmem_points :
        ∀ y : {z // z ∈ s}, (y : EStar) ∈ K⋆[R] SStar := by
      intro y
      simpa using
        (PointedCone.subset_hull ((subset_adjoin_vertical_unit (SStar := SStar)) (hs y.2)))
    have hsum_mem :
        s.attach.sum (fun y ↦ weights y • (y : EStar)) ∈ K⋆[R] SStar := by
      classical
      induction s.attach using Finset.induction_on with
      | empty =>
          change (0 : EStar) ∈ K⋆[R] SStar
          exact (K⋆[R] SStar).zero_mem
      | @insert y t hy ht =>
          simpa [Finset.sum_insert, hy] using
            (K⋆[R] SStar).add_mem
              ((K⋆[R] SStar).smul_mem (hweights y) (hmem_points y)) ht
    have hv_mem :
        slack • vertical_unit ∈ K⋆[R] SStar := by
      refine (K⋆[R] SStar).smul_mem hslack_nonneg ?_
      simpa using
        (PointedCone.subset_hull (vertical_unit_mem_adjoin_vertical_unit (SStar := SStar)))
    have hfst :
        (s.attach.sum (fun y ↦ weights y • (y : EStar))).1 =
          s.attach.sum (fun y ↦ weights y • (y : EStar).1) := by
      simpa using
        (Prod.fst_sum :
          (s.attach.sum (fun y ↦ weights y • (y : EStar))).1 =
            s.attach.sum (fun y ↦ (weights y • (y : EStar)).1))
    have hsnd :
        (s.attach.sum (fun y ↦ weights y • (y : EStar))).2 =
          s.attach.sum (fun y ↦ weights y * (y : EStar).2) := by
      simpa [smul_eq_mul] using
        (Prod.snd_sum :
          (s.attach.sum (fun y ↦ weights y • (y : EStar))).2 =
            s.attach.sum (fun y ↦ (weights y • (y : EStar)).2))
    have heq :
        pStar =
          s.attach.sum (fun y ↦ weights y • (y : EStar)) +
            slack • vertical_unit := by
      ext
      · simp [vertical_unit, hfst, hx]
      · simpa [vertical_unit, hsnd] using hmu_eq.symm
    rw [heq]
    exact (K⋆[R] SStar).add_mem hsum_mem hv_mem

end

section

universe u v

open scoped BigOperators Rockafellar

variable {E : Type u} {R : Type v}
    [Semiring R] [PartialOrder R] [IsOrderedRing R] [ExistsAddOfLE R] [AddLeftReflectLE R]
    [AddCommMonoid E] [Module R E]

local notation "EStar" => E × R

/-- Semiring-level source-facing bridge for Lemma 17.2.9: the primitive nonnegative slack witness is
equivalent to the textbook inequality on the scalar coordinate. -/
theorem mem_generated_cone_iff_exists_conicCombination
    {SStar : Set EStar} {pStar : EStar} :
    pStar ∈ (K⋆[R] SStar) ↔
      ∃ s : Finset EStar,
        (∀ y ∈ s, y ∈ SStar) ∧
          ∃ weights : {y // y ∈ s} → R,
            (∀ y, 0 ≤ weights y) ∧
              pStar.1 = s.attach.sum (fun y ↦ weights y • (y : EStar).1) ∧
              s.attach.sum (fun y ↦ weights y * (y : EStar).2) ≤ pStar.2 := by
  constructor
  · intro hmem
    rcases (mem_generated_cone_iff_exists_conicCombination_with_slack.mp hmem) with
      ⟨s, hs, weights, hweights, hx, slack, hslack_nonneg, hmu_eq⟩
    refine ⟨s, ?_, weights, hweights, hx, ?_⟩
    · intro y hy
      exact hs hy
    · calc
        s.attach.sum (fun y ↦ weights y * (y : EStar).2) ≤
            s.attach.sum (fun y ↦ weights y * (y : EStar).2) + slack :=
          le_add_of_nonneg_right hslack_nonneg
        _ = pStar.2 := hmu_eq
  · rintro ⟨s, hs, weights, hweights, hx, hmu⟩
    have hs' : (s : Set EStar) ⊆ SStar := by
      intro y hy
      exact hs y hy
    rcases exists_add_of_le hmu with ⟨slack, hmu_eq⟩
    have hsum_le :
        s.attach.sum (fun y ↦ weights y * (y : EStar).2) ≤
          s.attach.sum (fun y ↦ weights y * (y : EStar).2) + slack := by
      simpa [hmu_eq, add_assoc, add_left_comm, add_comm] using hmu
    have hslack_nonneg : 0 ≤ slack := by
      exact (le_add_iff_nonneg_right
        (s.attach.sum (fun y ↦ weights y * (y : EStar).2))).1 hsum_le
    refine (mem_generated_cone_iff_exists_conicCombination_with_slack).mpr ?_
    refine ⟨{
      support := s
      support_subset := hs'
      weights := weights
      weights_nonneg := hweights
      fst_eq := hx
      slack := slack
      slack_nonneg := hslack_nonneg
      snd_eq := hmu_eq.symm
    }⟩

end
