import CombinatorialGroupTheory.Items.Chap02.Proposition_2_5_7

-- Declarations for this item will be appended below by the statement pipeline.

-- Layer triage:
-- `source-facing`: the proof item establishing Magnus's conclusion that equal singleton normal
-- closures in a free group force conjugacy up to inversion.
-- `core/canonical`: the chapter owner theorem
-- `conjugate_or_conjugate_inv_of_normalClosure_eq`, built from `Subgroup.normalClosure` for
-- singleton normal closures and `IsConj` for conjugacy.
-- `bridge/view`: this item is proof text, so the file should recall the canonical chapter theorem
-- directly instead of restating its proposition shape.
-- Domain sampling:
-- 1. `Subgroup.normalClosure` is mathlib's owner construction for the normal subgroup generated by
--    a subset.
-- 2. `IsConj` is mathlib's canonical relation for conjugacy in a group.
-- 3. The surrounding Chapter II files use the abstract free-group owner level `[IsFreeGroup F]`
--    rather than the concrete model `FreeGroup X` when no chosen basis belongs in the statement.
-- 4. `conjugate_or_conjugate_inv_of_normalClosure_eq` in Proposition `2-5-7` is already the
--    upstream owner theorem for this exact Magnus conclusion.
-- Primitive vs. derived:
-- the item contributes no new source-facing object beyond this theorem statement, so the present
-- file should record only a direct recall of the existing owner theorem.

/- Theorem 2-6-2: this item is Magnus's proof of formula `(5.8)`, namely that if two elements of
a free group have the same singleton normal closure, then one is conjugate to the other or to its
inverse.

Since this textbook entry is proof text rather than a new independent construction, the file keeps
only a direct recall of the chapter's canonical owner theorem instead of restating its full type.
-/
#check conjugate_or_conjugate_inv_of_normalClosure_eq
