import Mathlib
import Mathlib.CategoryTheory.Sites.Coverage
import Mathlib.Tactic.Recall

-- Declarations for this item will be appended below by the statement pipeline.


/-! ### Lemma_7_48_1 (from Chap07) -/
universe u v

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Lemma 7.48.1:
- primary domain: sites presented by a coverage and the induced Grothendieck topology;
- sampled owner API:
  `Coverage.toGrothendieck`,
  `GrothendieckTopology.toCoverage`,
  `Coverage.toGrothendieck_eq_sInf`,
  `Presieve.isSheaf_coverage`;
- source/core/bridge triage:
  `source-facing`: the passage from covering families to the generated topology, together with the
  sheaf condition stated directly for those covering families;
  `core/canonical`: `Coverage.toGrothendieck` and `Presieve.isSheaf_coverage`;
  `bridge/view`: `GrothendieckTopology.toCoverage` and `Coverage.toGrothendieck_eq_sInf`, which
  compare the coverage presentation with the ambient Grothendieck-topology lattice.

Primitive data are only the coverage `K` and the set-valued presheaf `F`. The generated topology
and the coverage-level sheaf criterion are derived canonical API from the owner abstraction
`Coverage`, so this file should stay at direct recall/use rather than introducing a parallel local
definition or wrapper theorem.
-/

/- Lemma 7.48.1 (part 1): the covering sieves generated by the covering families of a site form
the canonical Grothendieck topology `K.toGrothendieck`. -/
recall Coverage.toGrothendieck

/- Lemma 7.48.1 (part 2): a set-valued presheaf is a sheaf for the topology generated by the
covering families of the site if and only if it satisfies the sheaf condition for every covering
family of the site. This is the canonical mathlib theorem `Presieve.isSheaf_coverage`. -/
recall Presieve.isSheaf_coverage

end CategoryTheory

/-! ### Definition_7_48_2 (from Chap07) -/
universe u v

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

/- Domain-style sampling for Definition 7.48.2:
- primary domain: sites presented by a `Coverage` and the associated Grothendieck topology;
- sampled owner API:
  `Coverage.toGrothendieck`,
  `Coverage.toGrothendieck_eq_sInf`,
  `Coverage.toGrothendieck_toPrecoverage`,
  `Precoverage.toGrothendieck`;
- source/core/bridge triage:
  `source-facing`: the textbook passage from a site given by covering presieves to its associated
  topology;
  `core/canonical`: `Coverage.toGrothendieck`;
  `bridge/view`: `Coverage.toGrothendieck_toPrecoverage` and `Coverage.toGrothendieck_eq_sInf`,
  relating the coverage presentation to precoverages and the Grothendieck-topology lattice.

Primitive data are only the coverage `K`. The associated Grothendieck topology is derived canonical
API from that owner abstraction, so this file should stay at direct recall/use rather than
introducing a parallel local alias or wrapper.
-/

/- Definition 7.48.2: for a site presented by its covering presieves, the associated topology is
the canonical Grothendieck topology `Coverage.toGrothendieck`, i.e. the topology
constructed in Lemma 7.48.1 from those coverings. -/
recall Coverage.toGrothendieck

end CategoryTheory

/-! ### Remark_7_48_3 (from Chap07) -/
universe v u

namespace CategoryTheory

variable {C : Type u} [Category.{v} C]

namespace Coverage

open SemiRepresentableFamily.Over

/-- Helper for Remark 7.48.3: a fixed-target cover family packaged with the universe parameters
used by this file's site API. -/
private abbrev CoverFamily (X : C) := SemiRepresentableFamily.Over.{max u v} X

/- Domain-style sampling for Remark 7.48.3:
- primary domain: sites via `Coverage`, `Precoverage`, and `toGrothendieck`;
- sampled owner API:
  `Precoverage.toGrothendieck_le_iff_le_toPrecoverage`,
  `Precoverage.toGrothendieck_mono`,
  `Coverage.toGrothendieck_toPrecoverage`,
  `SemiRepresentableFamily.Over.IsCovering`,
  `Presieve.exists_eq_ofArrows`;
- source/core/bridge triage:
  `source-facing`: this remark-level invariance statement for tautological enlargements;
  `core/canonical`: `Precoverage.toGrothendieck`;
  `bridge/view`: `SemiRepresentableFamily.Over.toPresieve`,
  `toSieve_eq_of_tautologicallyEquivalent`,
  `Presieve.exists_eq_ofArrows`.

Primitive data are the inclusion `K.toPrecoverage ≤ L` and the fact that every `L`-covering
family is tautologically equivalent to a `K`-covering family with the same target. The equality
of Grothendieck topologies is derived API.
-/

-- Proof sketch: `hK` gives one inequality by monotonicity. For the reverse inequality, every
-- `L`-cover is tautologically equivalent to some `K`-cover, hence generates the same sieve as that
-- `K`-cover; therefore it already belongs to `K.toGrothendieck.toPrecoverage`.
/-- Remark 7.48.3: if `L` contains the original covering families of the site `K` and every
`L`-covering family is tautologically equivalent to a `K`-covering family with the same target,
then `L` defines the same Grothendieck topology as `K`. -/
theorem toGrothendieck_eq_of_tautological_enlargement
    {K : Coverage C} {L : Precoverage C}
    (hK : K.toPrecoverage ≤ L)
    (hL : ∀ ⦃X : C⦄ (𝒱 : CoverFamily X)
      (_ : IsCovering L 𝒱),
      ∃ 𝒰 : CoverFamily X,
        IsCovering K.toPrecoverage 𝒰 ∧ TautologicallyEquivalent 𝒰 𝒱) :
    L.toGrothendieck = K.toGrothendieck := by
  apply le_antisymm
  · rw [Precoverage.toGrothendieck_le_iff_le_toPrecoverage]
    intro X R hR
    rw [GrothendieckTopology.mem_toPrecoverage_iff]
    rcases R.exists_eq_ofArrows with ⟨ι, Y, f, rfl⟩
    let 𝒱 : CoverFamily X := ofArrows Y f
    have h𝒱 : IsCovering L 𝒱 := by
      simpa [𝒱, IsCovering] using hR
    rcases hL 𝒱 h𝒱 with ⟨𝒰, h𝒰, h𝒰𝒱⟩
    change 𝒱.toSieve ∈ K.toGrothendieck X
    rw [← toSieve_eq_of_tautologicallyEquivalent h𝒰𝒱,
      ← Coverage.toGrothendieck_toPrecoverage K]
    simpa using Precoverage.generate_mem_toGrothendieck h𝒰
  · simpa [Coverage.toGrothendieck_toPrecoverage] using Precoverage.toGrothendieck_mono hK

end Coverage

end CategoryTheory
