import Integer.Chapters.Chap05.section_5_1_1.ch5_sec5_1_1_lemma_5_4

open scoped Matrix

-- Semantic recall note: no canonical mathlib owner surfaced for this Chapter 5 undominated
-- split-cut notion, so the file keeps the slack dominance comparison auxiliary and bundles the
-- distinguished multiplier hypotheses into the primary source-facing owner.

section Lemma59

variable {m nI nC : ℕ}

/-- `is_largest_abs_subdeterminant_bound A_C Δ` means that `Δ` is the maximum of `1` and the
absolute values of the determinants of all square submatrices of `A_C`. -/
def is_largest_abs_subdeterminant_bound
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (Δ : ℝ) : Prop :=
  1 ≤ Δ ∧
    (∀ ⦃k : ℕ⦄ (rows : Fin k ↪ Fin m) (cols : Fin k ↪ Fin nC),
      |(A_C.submatrix rows cols).det| ≤ Δ) ∧
    (Δ = 1 ∨
      ∃ (k : ℕ) (rows : Fin k ↪ Fin m) (cols : Fin k ↪ Fin nC),
        Δ = |(A_C.submatrix rows cols).det|)

/-- Every square subdeterminant of `A_C` has absolute value at most `Δ` when
`is_largest_abs_subdeterminant_bound A_C Δ` holds. -/
theorem abs_subdet_le_of_is_largest_abs_subdeterminant_bound
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (Δ : ℝ)
    (hΔ : is_largest_abs_subdeterminant_bound A_C Δ)
    {k : ℕ}
    (rows : Fin k ↪ Fin m)
    (cols : Fin k ↪ Fin nC) :
    |(A_C.submatrix rows cols).det| ≤ Δ :=
  hΔ.2.1 rows cols

/-- The slack-form left-hand side of the split inequality `(5.6)` generated by `u`, evaluated on a
nonnegative slack vector `r`. -/
noncomputable def split_cut_slack_value
    (b : Fin m → ℝ)
    (u : Fin m → ℝ)
    (r : Fin m → ℝ) : ℝ :=
  row_multiplier_pos u ⬝ᵥ r / Int.fract (u ⬝ᵥ b) +
    row_multiplier_neg u ⬝ᵥ r / (1 - Int.fract (u ⬝ᵥ b))

/-- If `r` is the residual slack vector of a mixed point, `split_cut_slack_value` agrees with the
mixed Gomory fractional-cut expression `(5.6)`. -/
theorem split_cut_slack_value_eq_mixed_gomory_fractional_cut_value
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (u : Fin m → ℝ)
    (xy : MixedRealPoint nI nC) :
    split_cut_slack_value b u (b - (A_I *ᵥ xy.1 + A_C *ᵥ xy.2)) =
      mixed_gomory_fractional_cut_value A_I A_C b u xy := sorry

/-- `split_cut_strictly_dominates_on_nonnegative_slacks A_I A_C b v u` means that the split
inequality `(5.6)` generated by `v` is at least as strong as the one generated by `u` on every
nonnegative slack vector, and is strictly stronger for some nonnegative slack vector. -/
def split_cut_strictly_dominates_on_nonnegative_slacks
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (v u : Fin m → ℝ) : Prop :=
  IsMixedGomoryFractionalCutMultiplier A_I A_C b v ∧
    (∀ r : Fin m → ℝ, (∀ i : Fin m, 0 ≤ r i) →
      split_cut_slack_value b v r ≤ split_cut_slack_value b u r) ∧
    ∃ r : Fin m → ℝ, (∀ i : Fin m, 0 ≤ r i) ∧
      split_cut_slack_value b v r < split_cut_slack_value b u r

/-- `split_cut_is_undominated A_I A_C b u` means that `u` itself is a mixed Gomory fractional-cut
multiplier and that no other split inequality of the same form strictly dominates the split
inequality `(5.6)` generated by `u` on the cone of nonnegative slack vectors. -/
def split_cut_is_undominated
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (u : Fin m → ℝ) : Prop :=
  IsMixedGomoryFractionalCutMultiplier A_I A_C b u ∧
    ¬ ∃ v : Fin m → ℝ,
        split_cut_strictly_dominates_on_nonnegative_slacks A_I A_C b v u

/-- `split_cut_is_undominated` is the bundled source-facing owner combining the distinguished
multiplier hypothesis on `u` with the auxiliary slack-form no-domination condition. -/
theorem split_cut_is_undominated_iff_multiplier_and_no_strict_domination
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (u : Fin m → ℝ) :
    split_cut_is_undominated A_I A_C b u ↔
      IsMixedGomoryFractionalCutMultiplier A_I A_C b u ∧
        ¬ ∃ v : Fin m → ℝ,
            split_cut_strictly_dominates_on_nonnegative_slacks A_I A_C b v u :=
  Iff.rfl

/-- Expanded companion form of `split_cut_is_undominated` exposing the textbook multiplier
conditions on `u` directly and expressing domination for the slack-form split inequality `(5.6)`
on all nonnegative slack vectors. -/
theorem split_cut_is_undominated_iff
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (u : Fin m → ℝ) :
    split_cut_is_undominated A_I A_C b u ↔
      (∀ j : Fin nI, ∃ z : ℤ, (u ᵥ* A_I) j = (z : ℝ)) ∧
        u ᵥ* A_C = 0 ∧
        (¬ ∃ z : ℤ, u ⬝ᵥ b = (z : ℝ)) ∧
        ¬ ∃ v : Fin m → ℝ,
          (∀ j : Fin nI, ∃ z : ℤ, (v ᵥ* A_I) j = (z : ℝ)) ∧
            v ᵥ* A_C = 0 ∧
            (¬ ∃ z : ℤ, v ⬝ᵥ b = (z : ℝ)) ∧
            (∀ r : Fin m → ℝ, (∀ i : Fin m, 0 ≤ r i) →
              split_cut_slack_value b v r ≤ split_cut_slack_value b u r) ∧
            ∃ r : Fin m → ℝ, (∀ i : Fin m, 0 ≤ r i) ∧
              split_cut_slack_value b v r < split_cut_slack_value b u r := sorry

/-- If the split cut generated by `u` is undominated, then no mixed Gomory multiplier `v`
produces a strictly stronger split inequality `(5.6)` of the same form on the cone of
nonnegative slack vectors. -/
theorem not_strictly_dominates_of_split_cut_is_undominated
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (u v : Fin m → ℝ)
    (hundom : split_cut_is_undominated A_I A_C b u)
    (hv : split_cut_strictly_dominates_on_nonnegative_slacks A_I A_C b v u) :
    False := sorry

/-- Lemma 5.9. For an ambient system whose integer block `A_I` and right-hand side `b` are
entrywise integral, let `Δ` be the largest among `1` and the absolute values of all square
subdeterminants of `A_C`. Let `u` satisfy that `u A_I` is integral, `u A_C = 0`, `u b ∉ ℤ`, and
the split inequality `(5.6)` generated by `u` is undominated on the cone of nonnegative slack
vectors. Then each coordinate of `u` satisfies `|u_i| ≤ m Δ`. -/
theorem abs_row_multiplier_le_of_undominated_split_cut
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (Δ : ℝ)
    (u : Fin m → ℝ)
    (hAI_entries : ∀ i : Fin m, ∀ j : Fin nI, ∃ z : ℤ, A_I i j = (z : ℝ))
    (hb_entries : ∀ i : Fin m, ∃ z : ℤ, b i = (z : ℝ))
    (hΔ : is_largest_abs_subdeterminant_bound A_C Δ)
    (hAI : ∀ j : Fin nI, ∃ z : ℤ, (u ᵥ* A_I) j = (z : ℝ))
    (hAC : u ᵥ* A_C = 0)
    (hub : ¬ ∃ z : ℤ, u ⬝ᵥ b = (z : ℝ))
    (hundom : ¬ ∃ v : Fin m → ℝ,
      split_cut_strictly_dominates_on_nonnegative_slacks A_I A_C b v u) :
    ∀ i : Fin m, |u i| ≤ (m : ℝ) * Δ := sorry

/-- Bundled companion form of Lemma 5.9 using `split_cut_is_undominated A_I A_C b u`, still under
the ambient entrywise-integrality assumptions on `A_I` and `b`. -/
theorem abs_row_multiplier_le_of_undominated_split_cut_of_multiplier
    (A_I : Matrix (Fin m) (Fin nI) ℝ)
    (A_C : Matrix (Fin m) (Fin nC) ℝ)
    (b : Fin m → ℝ)
    (Δ : ℝ)
    (u : Fin m → ℝ)
    (hAI_entries : ∀ i : Fin m, ∀ j : Fin nI, ∃ z : ℤ, A_I i j = (z : ℝ))
    (hb_entries : ∀ i : Fin m, ∃ z : ℤ, b i = (z : ℝ))
    (hΔ : is_largest_abs_subdeterminant_bound A_C Δ)
    (hundom : split_cut_is_undominated A_I A_C b u) :
    ∀ i : Fin m, |u i| ≤ (m : ℝ) * Δ := sorry

end Lemma59
